bigbluebutton/bigbluebutton

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx

Issue: participants redirected to about://blank when attempting to join a breakout (`isFreeJoin=true`)
Steps to reproduce:
Join a new meeting as moderator. Create Breakouts, with the option to choose which room to enter. Bring your user to a room 1and hit Create.
In the new modal
in _some_ cases clicking on "Join room" - we are redirected in a new tab to a blank tab. In Chrome this is about://blank
I have seen this a few times in large meetings on a busy server but was able to replicate once on a local server with 1 meeting, 1 user.
I have seen it only in the cases when I do not touch the dropdown in the modal, but it might be a timing (race condition) issue.
When debugging I would occasionally see only user with different userId in …

Ensure getURL value for breakout before redirecting

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ThumbnailCreatorImp.java

There are some cases where the thumbnails are mistakenly going to the blank fallback.
The problem normally happens to me when the second page enters the rename method https://github.com/bigbluebutton/bigbluebutton/blob/de14c705f469aa864573367c76f70c7d25c0a839/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ThumbnailCreatorImp.java#L115-L151 before the first page to finishes. This happens every time for the default presentation because the first slide is an image much more complex than the followers. So what's going on is that the second thumbnail is receiving a hardcoded `thumbs-1.png` name and then the first page enters it and overrides it. So when the blank slide generator starts it can't find `thumbs-2.png` because it actually doesn't exists.
I believe there are better …

Avoid wrongly naming a thumbnail as thumb-1

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Since we are now including post_events_analytics_callback enabled, it is also necessary to set keepEvents enabled by default.

enable post_events by default by setting keepEvents=true

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Adds `height: 100%` to `screenshareVideo ` element
#9735

Prevent screen share cropping on chrome 84

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx

Fixes `Cannot read property 'map' of undefined` error that was causing the client to hang when joining from greenlight.
#10058

Fix TypeError: Cannot read property 'map' of undefined

---

bigbluebutton-html5/package-lock.json

Pull request #9851 added package 'hark' but did not include package-lock.json details needed for production deployments. I am adding this missing info

Add missing package-lock info for "hark"

---

bigbluebutton-html5/private/config/settings.yml

Sets  `raiseHandAudioAlerts: true` and `raiseHandPushAlerts: true` by default in setting.yml

Set raise hand notification / sound on by default

---

bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Sanitize uri's within welcome message and modOnlyMessage if they contain links different than https.
Also adjusted the default values for `defaultWelcomeMessage` and `defaultWelcomeMessageFooter` so the uri they contain is https, not http.

Only allow for https uri in welcome and modOnly messages

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Fix exception caused by negative values being used in presentation <svg>
attempt to fix
7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9 Error: <svg> attribute width: A negative value is not valid. ("-53.333333333333336")
Et @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9 Error: <svg> attribute height: A negative value is not valid. ("-30")
Et @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9

Prevent negative values being used in presentation height / width

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
bigbluebutton-html5/private/locales/en.json

Add's `aria-label` to the poll results in the whiteboard.
Provides clearer poll results for the screen reader in the whiteboard. 
_Before:_
graphic    Unlabeled graphic    To get missing image descriptions, open the context menu.
graphic    00
graphic    0%0%
graphic    TrueFalse
_After:_
graphic Poll Results: True | 0 | 0% | False | 0 | 0%

Add aria-label to whiteboard poll result

---

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/arc-player.jsx

LGTM report:
The escape sequence '\.' is equivalent to just '.', so the sequence may
still represent a meta-character when it is used in a regular expression.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix regular expression in Arc Player (LGTM)

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/activity-check/component.jsx
bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

If activity check was enabled in server, the activity check modal wasn't showed to users and after a given time the user was disconnect, also fix the meeting-end and error-screen messages, informing the user the reason why he was ejected.

Restore activity check modal.

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss
bigbluebutton-html5/imports/ui/components/media/styles.scss
bigbluebutton-html5/imports/ui/components/screenshare/styles.scss
bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

This is a set of UI improvements targeted at cameras in 2.2.
Mainly:
- No more border radius in video containers, fullscreen buttons or user info span;
- Reduced the spacing between cameras to 1px;
- Replaced the loading spinners with a black background + the user name at the center (R.I.P. spinning arrows, won't be missed);
- Changed the color of the talking indicator to be the primary color with 0.7 opacity;
- Make the user name in the video container have opacity 1;
- Fix: make the webcam containers 4:3 even while loading. They were stretched thin before.
This has been widely tested. Also contains two commits from a coworker of mine (@CristianSilvaGrosseli).
_P.S.: PR #10208 follow-up 1._
None
I reckon there will be still some improvements to make to the UI and overall camera UX …

video-provider: UI improvements

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/private/config/settings.yml

Adds the ability to automatically throttle camera streams according to the number of shared cameras **in a meeting**. Mainly:
- Possibility of configuring ["invisible" camera profiles](https://github.com/bigbluebutton/bigbluebutton/blob/629e2dbfd46632ee2bb2d6e89fdedfb39e5483a8/bigbluebutton-html5/private/config/settings.yml#L123) in the `cameraProfiles` property of HTML5's `settings.yml`. Those can be configured with a `hidden: true` property and **won't** appear in the **video preview**.
- New `kurento.cameraQualityThresholds` configuration dictionary in HTML5's `settings.yml`.
```
cameraQualityThresholds:
enabled: true
thresholds: # array
- threshold: N # number of cameras used as a threshold for `profile` to be activated
profile: <profileId> # An `id` from one of the …
```

video-provider: dynamic video profiles (aka automatic bitrate/frame rate throttling)

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx

Remove the options for MuteAll and MuteAllExceptPresenter from the Gear-menu in active breakout rooms.
Before
)
After
Closes #10210

Remove muteAll and muteAllExceptPresenter from breakouts

---

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js

Large number of the parameters' values are not JSON, so this should not be an error. We were not outputting the key-value pair properly.

Improve log for parsed passed parameter error

---

bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
bigbluebutton-html5/imports/ui/components/join-handler/component.jsx

Allowed for a wider range of html tags to be preserved during sanitization step of welcome message and moderator only message
Motivation:
https://groups.google.com/g/bigbluebutton-dev/c/46bfAAMblM0/m/OspyiSU0AwAJ

Allow more tags in welcome message/ mod only message

---

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/container.jsx
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js

This PR improves the poll results displayed in the public chat by fixing the following:
* poll messages being grouped together.
* unread counter not resetting when last message is a poll.
* poll messages rendering above older messages.
* poll results loose styles when scrolling long lists quickly.
closes #10138

Improve poll results in public chat

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/private/config/settings.yml

A small follow-up to #10213.
- Normalize hidden cameraProfiles constraints to not use the `video` key and be consistent to what we used before.
- Add some docs to settings.yml cameraProfiles and cameraQualityThresholds configs.
None

video-provider: normalize hidden cameraProfiles constraints

---

bigbluebutton-html5/private/config/settings.yml

This patch switches to using a much more readable YAML syntax for the
logging configuration in the HTML5 client.

Switch to YAML Syntax for Logging

---

bigbluebutton-html5/imports/ui/components/media/component.jsx

Adjust presentation area height to 100% when webcam's data savings is enabled.
from:
to:

Check video data savings to set presentation max-height

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Makes the parsed text from the presentation slides available to screen readers.

Add presentation slide text for screen readers

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Fixes `mirrorOwnWebcam` behaviour (regression introduced in #10208, mea culpa).
Closes #10263

video-provider: fix mirrorOwnWebcam behaviour (regression from #10208)

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/private/locales/en.json

Adds a configurable video pagination mode which gives the possibility to control the number
of simultaneous cameras being showed to an end user, but give them the agency to see all of
them separately (in pages).
Caveat: page changes renegotiate WebRTC peers. See the last item in `Pending` for more info.
More testing is welcome (please).
```
pagination:
enabled: false 
pageChangeLockTimeout: 5000
desktopPageSizes:
moderator: 0
viewer: 5
mobilePageSizes:
moderator: 3
viewer: 3
```
There's demand for some way to control the number of concurrent streams being shown to end users for both server-side and client-side reasons. We need to rein in Kurento's CPU/bandwidth usage in some way and also prevent end users from getting their computers melted with a full mesh scenario. This is an initial …

video-provider: first tackle at video pagination

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

Under some specific circumstances pages would be calculated as `NaN` due to the modulo operation dividing stuff by zero.
This fixes it.
Follow up to #10293.
None

video-provider: fix pagination edge case

---

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/panopto.jsx

Updates the external video player `MATCH_URL` regex.
Handles self hosted Panopto installations, where the whole `hostname` can be arbitrary
mentioned in #10200

Make external video MATCH_URL even more generic

---

bigbluebutton-html5/imports/ui/components/media/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

Fixes video-provider's dynamic camera quality thresholds accounting when using pagination mode.
With pagination, the streams array gave a partial vision of shared streams so I had to extend the
service method to return the absolute number of streams as well so dynamic profiles would work
as intended when pagination is enabled
Follow up to #10293 
None

video-provider: fix dynamic profile accounting when using pagination

---

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

This adds `bbb_record_video` userdata that, when is set to false, signals
bbb-webrtc-sfu to avoid generating the stream recording assets for a
particular user.
By default, `bbb_record_video` is true.
Associated with https://github.com/bigbluebutton/bigbluebutton/issues/10249 and https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/56.

Add individual video record control

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

- Change the stream ordering in pagination mode to prioritise presenters
* `Local -> Presenter -> Alphabetic`
- Restore the full mesh stream ordering to behave like it did before 2.2.22 (#10208)
* `Local -> Alphabetic`
I'm still not too fond of the way I did the presenter prioritization and neither did I measure if it has any performance impact.
I'd love to hear from others on that.
Follow up to #10293.
None
1. Presenters should be put in a fixed position and prioritized in pagination mode to reduce the burden on the end user.
2. The old full mesh ordering seems to make more sense.

video-provider: prioritise presenter in pagination ordering, restore pre-.22 full mesh ordering

---

bigbluebutton-html5/private/config/settings.yml

- Add inline docs for pagination configuration
- Change the default page sizes for mobile to 2
Follow up to #10293.
None
Regarding the default page size change for mobiles: 2 (+ max 1 local) fits mobile screens better. 
I think 2 is what we need; 1 is too little and 3 is just absurd.

video-provider: add inline docs for pagination configuration

---

bigbluebutton-html5/private/config/settings.yml

This patch switchessing a somewhat more modern default for the camera
profiles by requesting 720p for the `high` and `hd` profiles like this.
This was discussed on the developer's list at:
- https://groups.google.com/g/bigbluebutton-dev/c/PL3kXV9pZmo

Modern Camera Profiles

---

record-and-playback/core/lib/recordandplayback/events_archiver.rb

Update the list of invalid characters based on what the XML
specification permits and discourages.

Events archiver: Strip more invalid characters

---

bigbluebutton-html5/imports/ui/components/screenshare/service.js

The HTML5 code for screensharing is pretty old in some aspects.
I've improved some of the findOne calls to be more in tune with 2.2.
Specially in `isVideoBroadcasting`. I don't even know how screensharing was working properly the way it was.
None.

screenshare: improve screenshare service findOne calls

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx

- Add a new `PropType` entry for `totalNumberOfStreams`
- Remove `socketOpen` state check as a trigger for rendering `VideoList`
None
Removal of `socketOpen` check:
- The check is old as hell and makes no sense. Removing it makes the video list load faster and webcam sharing feel more responsive due to pre-rendering named containers even before the websocket connection is established.
- Still left the state for it because it's "useful" in forcing a re-render when the websocket connection is established.

video-provider: add missing PropType, remove render socketOpen check

---

bigbluebutton-config/bin/bbb-record

Only wav files in freeswitch cache directory were deleted. With this PR also opus files are deleted.
Extends `bbb-record --delete`  and `--deleteall` to remove `opus` files
closes #10345
privacy

Also delete opus files in freeswitch cache dir

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Default the presentations current width / height to 0 if the `slidePosition` doesn't exist.
#10372

Fix presentation width of undefined or null

---

bigbluebutton-html5/imports/api/external-videos/server/methods/startWatchingExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js

Add an extra verification on extracted data to avoid some edge case where those values are `undefined` and the video started to play in into another meeting.

Add check when start/stop an external video

---

bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

- Add a client-side microphone mute-unmute via the `MediaStreamTrack.enabled` property.
* The track enabled property makes the encoder generate silent frames instead of capturing from the input source.
* It's supported by all major browser for a long time now
* There will still be OPUS stream being transmitted to the server, but those will be silent frames. That can range up to 48kbps (our current audio limit), but will usually be way lower than 10kbps (depending on the browser).
Partially addresses https://github.com/bigbluebutton/bigbluebutton/issues/8951
https://github.com/bigbluebutton/bigbluebutton/issues/8951
Caveats:
- A server-side unmute (via FreeSWITCH) or a remote unmute (when allowModsToUnmuteUsers=true) will still work. But the local end mute state will be correctly …

Add a client-side microphone mute/unmute

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

Fix a small edge case on full mesh video stream sorting when multiple cameras from the same source are being used.
None.

video-provider: fix mesh stream sorting with multiple cameras

---

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js
bigbluebutton-html5/imports/startup/client/intl.jsx

This PR adds a new user settings called `bbb_override_default_locale` to user settings
Closes #10085

Add override default locale to user settings

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Clean up the client-side mute/unmute methods (thanks @paulmenzel).

audio-manager: refactor client-side mute/unmute

---

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
bigbluebutton-html5/imports/ui/components/screenshare/service.js
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/video-provider/service.js

Currently, _for legacy reasons_, the presenter's screenshare preview is from the remote end (server).
This PR changes it to be local (played directly from the source stream).
None
There's no reason for the preview to be remote anymore. It was that way for legacy reasons (to preserve the behaviour displayed in the Flash client, I think).
With this PR, we're shaving off 1mbps (default) + the decoding CPU usage + 1 peer negotiation overhead from the presenter's side, while also making it visually  more responsive.
Only drawback I can see is that the presenter might have a slightly skewed vision of screenshare in comparison to viewers (because we're taking off network and some decoding-introduced artifacts).

screenshare: make presenter's screenshare preview local instead of remote

---

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx
bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx

Fix bug when alternate panel. Fix external video size

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Abort the `setSenderTrackEnabled` call if the bridge is in listen only mode as it's pointless.
Also fixes some occasional exceptions when on listen only that I introduced with the mute stuff.

audio-manager: shortcut on setSenderTrackEnabled when in listen only

---

bigbluebutton-config/bin/apply-lib.sh

This PR modifies `/etc/bigbluebutton/bbb-conf/apply-lib.sh` to make it easy for the BigBlueButton administrator to run three parallel versions of Kurento media server (KMS): each one dedicated to handling one of the following media types
* listen only, 
* webcam, and 
* screen share.
To enable running three KMS servers, add the following line to `/etc/bigbluebutton/bbb-conf/apply-config.sh`
~~~
enableMultipleKurentos
~~~
and run `bbb-conf --restart`.
To revert BigBlueButton's configuration to a single running a single KMS server (which handles all three streams), change the above to
~~~
disableMultipleKurentos
~~~
and run `bbb-conf --restart` again.
Running three dedicated Kurento media servers should increase the stability of media handling BigBlueButton as the load for starting/stopping …

Enable three parallel KMS servers

---

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx

Close the window (tab) when the user selects Menu -> Leave-> OK while in Breakout. In the main meeting we keep the old default, which is to redirect to logoutURL if any.

In Breakouts close the tab if the user intentionally selects Leave -> OK

---

bigbluebutton-config/bin/bbb-conf

Fix the logic for updating the FreeSWITCH password.  It uses `/usr/share/bbb-fsesl-akka/conf/application.conf` as the source of the password (and generates a new one if it's the default 'ClueCon').

properly update ESL password

---

bigbluebutton-config/bin/apply-lib.sh

This adds a missing step to setting up with three Kurento servers.  
It adds the path `pemCertificateRSA` in `WebRtcEndpoint.conf.ini`.  
closes #10467 
This will be in BigBlueButton 2.2.25.

Fix dtls path

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

Initially removed in #8417 on BBB 2.3. However when propagating #10401 from BBB 2.2 into BBB 2.3 ( #10482 ) these 2 lines incorrectly made their way back to BBB 2.3

Remove maxInactivity added in merge from 2.2.24

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GuestsWaiting.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeTestData.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GuestsMsgs.scala
bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss
bigbluebutton-html5/imports/ui/components/connection-status/service.js
bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx
bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss
bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/chat-avatar/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml

Looks like this:
Use the former Flash client avatarURL join param to replace the name
initials avatar from the user list, chat, waiting guests and connection
status list.
It is possible to define a defaultAvatarURL at bbb-web and enable/disable it
Closes #8566.
EDIT: Right now the css **animation displayed at the user avatar when she/he is talking was disabled when the user has an image on**. Did that because the image was being covered by the color glow and it didn't had the same cool effect it does to the name initials' avatar. It can be fixed but I would like first to understand if that is still needed since we have the talking users feature now.

Support for avatar images

---

bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js
bigbluebutton-html5/imports/ui/services/auth/index.js

If an ejected user tries to enter in the meeting using the current url, the client keep trying to validate that user, but without success causing a validateAuthToken message spam until the connection times out. This PR invalidated this behavior on the first time the user tries to rejoin.

Prevent validateAuthToken spamming for ejected users

---

bigbluebutton-web/grails-app/conf/application.yml

Revert this to make whatever you want when running bbb-web without https

Add secure tag to bbb-web JSESSIONID cookie

---

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/container.jsx

Adding nginx log from client to be able to say with certainty that a meeting X was ended by user Y hitting the EndMeeting button

add log for moderator forcing end meeting

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx

Fixes a bug which prevents showing meeting URL in the chat window since 2.3a.
related to #10441 
The meeting URL shown on version 2.2 was useful, although not very elegant.

Show invitation URL in chat window on 2.3a

---

record-and-playback/core/scripts/utils/gen_webvtt

The indexes returned in recording events from BBB refer to positions
within a UTF-16 encoded string. Rather than attempt to untangle this in
the server (which might have a performance cost), it's easier to switch
the caption processing code to operate in UTF-16 encoding as well to
make it work consistently.
The PyICU library provides a UnicodeString type which is a UTF-16 string
similar to Java and JavaScript, but which supports all the python
indexing methods. It's fairly straightforwards to swap it in in place of
the types used previously, and works natively as an input to the ICU
line break iterator too.
Fixes #10531

Perform captions generation in UTF-16 encoding

---

record-and-playback/presentation/scripts/publish/presentation.rb

We were seeing some recording failures where a shape was missing the "thickness" attribute in the events file.
Not sure what causes this issue, but there's nothing reasonable that can be done to draw a shape with no thickness. Just skip it.

Recording: Skip shapes with missing "thickness" attribute

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
bbb-common-web/src/main/java/org/bigbluebutton/api/domain/User.java
bbb-common-web/src/main/java/org/bigbluebutton/web/services/EnteredUserCleanupTimerTask.java
bbb-common-web/src/main/java/org/bigbluebutton/web/services/UserCleanupTimerTask.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

This patch includes two improvements made for bbb-web. It tries to better isolate
the sessionToken's handling and session's validation, including logs for each one of
these steps; and removes maxParticipats control from registered users (that are no
longer removed from bbb-web collections) binding it to joined users or users that
reached the enter API call. The following adds more details about this last one:
User's regular flow to join a meeting goes around an API join call -> redis register event ->
redirect to client page -> API enter call -> redis join event. When the guest policy is ASK_MODERATOR,
non-moderators are registered and redirected to a guest lobby that polls for her/his guest status and
only enters the meeting after a moderator approval.
Using registered users as control …

Patch of improvements for bbb-web

---

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
bigbluebutton-html5/imports/api/users/server/publishers.js
bigbluebutton-html5/imports/ui/services/auth/index.js

Another attempt to prevent multiple calls on onClose event. Prevent to set userId if previous set, because when we set userId in `validateAuthToken` the `current-user` publisher trigger again. [https://docs.meteor.com/api/pubsub.html#Subscription-userId](url)

Prevent repeated setUserId

---

bigbluebutton-html5/private/config/settings.yml

adds identifier for samsungs mobile browser (based on chromium) as supported browser for check
closes #9952

add samsung internet as compatible browser

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/jhotdraw/Bezier.java

Fixes compile error occurs at two special characters. 
closes #...
Probably depending on the locale of terminal where I compile the source code, I sometimes experienced compile errors.
I am not 100% sure if I am right in the second fix of the formula.

Fix compile error in Bezier.java

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

A few of the libs have recurring vulnerability issues (npm audit) and aside from that we don't really use these libs on 2.2 anymore. On 2.3 we have improved the QA significantly. When merging this to upstream we want to keep the upstream version of these files.
Clarifying that these vulnerabilities were not on production, only on dev environment since the libraries are listed under `devDependencies` and not `dependencies`.

Removing webdriverio* QA libs on 2.2

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

Thanks to @prlanzarin , who pointed out we need to also map stun/turn servers when using fallback servers.
Related to #10580  and #10569

Map stun/turn servers into WebRTC's iceServers, when using fallback stun

---

bigbluebutton-html5/imports/ui/components/media/component.jsx

If someone is sharing her/his webcam and the presenter enables webcam's data savings the
draggable overlay covers a portion of the presentation slide.

Hide draggable overlay when data saving is enabled

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/components/chat/alert/audio-alert/component.jsx
bigbluebutton-html5/imports/ui/components/polling/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/service.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

When refusing ("thumbs down" button) echo test, user is able to select a different input device. This should work fine for chrome, firefox and safari (once user grants permission when asked by html5client).
For output devices, we depend on setSinkId function, which is enabled by default on current chrome release (2020) but not in Firefox (user needs to enable "setSinkId in about:config page). This implementation is listed as (?) in MDN.
In other words, output device selection should work out of the box for chrome, only.
When selecting an output device, all alert sounds (hangup, screen-share , polling, etc) also goes to the same output device.
This solves #10592
Fix wrong input/output device selection in latest audio-manager code (which is ported to latest SIP.js version) 
closes #10592 …

Correctly set audio input/output devices - latest SIP.js version

---

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx

Users must return their audio to the main room before joining a different one.
Since the audio transfer and the UI state manager doesn't provide a shortcut for
jumping from a breakout room to another, avoid making this option available.
@fcecagno recently found out about this problem. If a moderator joins a breakout room by audio and then tries to do the same for another breakout room while his audio is in the other room the client gets in an inconsistent state. Since I'm not sure about the use case scenarios on this feature I just did this small fix just to assure the UI state won't break for the regular users so this issue can be taken care a better way in the future.

Fix the UI state on breakout room audio join

---

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
bigbluebutton-html5/private/locales/en.json

removes `aria-label` from webcam button. The screen readers announces the `label` prop and since both strings should be the same, we can omit the aria tag.
This fixes the screen reader announcing the wrong message based on the state of the button. Previously no matter what state the button was in, it would always announce "Share webcam".

Fix share webcam button label for screen readers

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx

Cursor coordinates are calculated using the presentation SVG object
DOMMatrix. When getting this matrix, some browsers (Firefox at least)
responds it as null if the svg object does not have a visible area.
This adds a check before trying to transform the cursor coordinates
using the matrix inverse so we avoid calling a method from a null object.
If there isn't a DOMMatrix to be used as reference, returns a simple out of
bounds SVGPoint (-1, -1).
```
[15:05:49:0695] ERROR: clientLogger: TypeError: CTM is null https://lxc.bbb/html5client/app/app.js?hash=c0787811183bca015570b0925f99e84f6ab20362:63105:12 modules.js:56509:1396
Uncaught TypeError: CTM is null
coordinateTransform component.jsx:13
getTransformedSvgPoint component.jsx:59
checkLastCursor component.jsx:86
render component.jsx:178 …
```

Check if DOMMatrix exists before cursor coordinate transform

---

bigbluebutton-html5/imports/ui/components/dropdown/list/item/component.jsx
bigbluebutton-html5/private/locales/en.json

Updates the message announced by screen readers for currently active emoji's.
The selected emoji menu item shows a visual blue highlight to indicate that it is active. This info should be relayed to the screen readers as well.
announced before: `Away`
announced after: `Away active`

Make emoji list item announce active state for screen readers

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx

Add a keyboard shortcut (enter key) to toggle fullscreen mode in the presentation toolbar.
related to #10589 
I would like to do a parallel presentation, that is, to broadcast by BBB a face-to-face seminar (with a projector and white screen). I need to stay in the fullscreen mode as much as possible. Doing so, however, I encountered a problem indicated in the issue above.
In the perfect world, one should be able to do everything (or many things) staying in the fullscreen mode as well.

Shortcut key to toggle fullscreen

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/component.jsx
bigbluebutton-html5/private/locales/en.json

Fixes the label of "undoing full screen button" for presentation. 
closes #...
On the full screen presentation mode, the pop up of  "undo full screen button" (with four-arrows going to center) still reads "Make XXX fullscreen". 
This PR should fix the same problem in full-screened screensharing, but lucky or unlucky, we cannot see it.
PS I realized that this happens only when one uses developer tools (as far as I tested, but who knows).

Fix undo-presentation-fullscreen button label

---

bigbluebutton-html5/imports/api/annotations/addAnnotation.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

Ensures that the HTML5 client sends the correct bounding rectangle size for the recordings.
There were cases where the text in the text-area's wasn't being wrapped correctly in the recordings.

Fix text-area bounding rectangle in the recording 

---

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
bigbluebutton-html5/imports/ui/components/meeting-ended/service.js
bigbluebutton-html5/imports/ui/services/auth/index.js
bigbluebutton-html5/imports/utils/logoutRouteHandler.js
bigbluebutton-html5/private/config/settings.yml

Added allowDefaultLogoutUrl config to optionally ignore non-custom logoutUrl
Split the MeetingEnded component's render into two parts for simplification - based on whether user feedback is enabled
On large deployments if no custom logout parameter is set on meeting create you get unnecessary requests for your business' homepage every time a user is logged out / provides feedback / meeting is ended. That load to the homepage can prove to be significant, so with this new configuration you can set it up so users are hitting a 'dead end' page - i.e. there is no appropriate page to be redirected to and `window.close()` is not an option due to the window not being opened programatically in first place.(Note: in #10455 we could close the tab due to the fact that we had opened it in first place) …

Added allowDefaultLogoutUrl config to optionally ignore non-custom logoutUrl

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

We now let sip.js handle getUserMedia calls, same should happen when skipCheck is active.
Solves #10652.

Fix wrong skipCheck handling

---

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/arc-player.jsx

In some cases the extra '.' would be included and the url would not load properly.

Dont include extra dot in instructure media url

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx

This PR corrects the errors that are thrown in either OSX or iOS Safari. The issue was that both components expected a boolean but navigator.userAgent.match(/iPhone/i) return an array -> ["Iphone"] instead of a boolean. This line of code was used in two different components in the same way.
closes #7953
I was experimenting with BBB and this error caught my eye.

Fix for OSX and iOS Safari errors in console

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/private/config/settings.yml

For some reason (still investigating), using turn/coturn on 443/tcp makes firefox's iceGathering process (during echo test) takes 12+ seconds (tested on webrtc's trickle page with multiple instances).
This was found when testing the current default (15s) on production with a private turn/coturn server on port 443/tcp. For default bbb setup (stun only), echo test still runs fast.
To avoid adding extra delay to iceGathering on this scenario (Firefox + turn on 443/tcp), i am just setting the default value back to the 5s (old default).
So , for those who wants to reduce the 1004 occurrences, increasing the iceGatheringTimeout could help (just be aware this adds delay on the mentioned scenario).

Change default value of iceGatheringTimeout to current's SIP.js default

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

When closing/reloading tab with active microphone, audio exits successfully but a wrong log-error (1005) is shown.
We now process closing/reloading tab the same way we do when user hangup the call.

Prevent 1005 error log when user close/reload bbb's window/tab

---

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx

On mobile if you clicked on a user or your own user to set their status, the tethered modal would keep it's z-index (15), which would prevent the user from interacting with anything because the tethered modal would overlap the whole site.
I think strictly comparing **keepOpen** variable to **null** was done mistakenly as the **keepOpen** variable is either true or false and that was the reason the modal didn't close after setting or clearing user status.
closes #...
Haven't found any issues about this problem
After work debugging

[Mobile] - Setting or clearing user status locks the whole screen

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
bigbluebutton-html5/private/config/settings.yml

We now check if `muteAlert` #9851 when we include the component, not when we render it.
This allows now to properly disable the feature (temporarily until we figure out a breaking issue)

Move the check to disable mutedAlert feature; temp disable it

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/WhiteboardApp2x.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WhiteboardMsgs.scala
bigbluebutton-html5/imports/api/annotations/server/methods/sendAnnotationHelper.js

Adds `drawEndOnly` to `SendWhiteboardAnnotationPubMsg`. As part of the whiteboard improvements for the HTML5 client it no longer sends `DRAW_START` and `DRAW_UPDATE` events (#9019). 
Thanks @hiroshisuga  for pointing out where the problem was in #10485
Closes #10408

Fix broken undo of consecutive pencil annotations

---

bbb-libreoffice/install.sh

This is a simple change that will avoid problems on upgrades of development server ( where `./uninstall.sh` and `./install.sh` are called multiple times ).

Avoid cache usage when building docker image

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

Makes the toggle presentation download button tooltip display the correct message.
#10748

Fix presentation downloadable tooltip label

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss

Increases the `z-index` on the buttons in the actions bar
#10779

Fix actions bar buttons not being clickable on iPad 

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

It removes a line of code, which dumps the whole base64 encoded binary of every api-uploaded pdf to the logs. This may lead to strange errors (oom / crashes) with big files.
#9092 
I do not think that it is really necessary to leave the line of code, wrapped in a "isDebugEnabled" condition as suggested in the issue. It does not make sense to flood the debug log with binary strings by default. Even it makes no sense when debugging arbitrary other things in bbb-web. So I decided myself to remove it.

Remove unwanted debug logging of PDF binaries

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

We now use both peer's connectionstatechange and iceconnectionstatechange to monitor ICE state for audio sessions.
The same way we did with old sip.js version, we leave iceconnectionstate trigger audio actions , such as connect, disconnect, reconnect.
We still listen for 'failed' state for connectionstatechange event, because chrome triggers this (tested on 86+).
This should reduce the audio error 1010 ocurrences, once some browsers (specially Chrome/Android) don't trigger connectionstatechangeevent.
This might reduce problems reported in #10708, which still needs more investigation though.

Use iceConnectionState to monitor ICE connection status

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

Although Chrome's default is now unified plan, Chrome <-> FreeSWITCH ICE connection fails for some Chrome installations (specially those running on Windows).
FS ICE fails when Chromes's SDP has "a=mid:<index>" (instead of "a=mid:audio").
This fixes Error 1010 and situations where echo test takes too long.
This fixes #6414 regression, once we do the same older version of SIP.js used to do.

Force using plan-b as default sdpSemantics for chrome

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/public/compatibility/sip.js

Long story short: this adds the possibility to configure the SIP Via header to plain WS to allow reverse proxying from WSS to WS internally. This potentially works around FreeSWITCH's sofia-sip transport stack lockup, issue #9667, as some community members have tested it with positive indications.
Partially addresses #9667. Don't think it closes the issue as I'd prefer fixing the bug in FreeSWITCH.
Working around the sofia-sip transport stack deadlock while we can't find a definitive fix.
Less intrusive than other suggested workarounds with no need to setup additional watchdogs.
Trade-off is making the internal nginx <-> freeswitch connection unencrypted.
Detailed discussion: https://github.com/bigbluebutton/bigbluebutton/issues/9667
Special thanks to @jarmediagmbh for testing this and …

[html5/audio] Add a configurable hackViaWs to SIP.js. Part of a workaround for #9667 

---

bigbluebutton-config/bin/apply-lib.sh

Using this larger value helps reducing occurrences 1005/1010 errors for Chrome, avoiding an openssl's error which interrupts the dtls handshake (Chrome triggers "DTLS timeout expired" error)
This key size is also the default value used by freeswitch on switch_core_cert.c

Increase private key size for dtls-srtp.pem to 4096

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Split error message from session token ( making it easier to translate - and more secure - avoiding concatenation )

Split error message from session token in bbb-web enter API

---

bigbluebutton-html5/imports/utils/safari-webrtc.js
bigbluebutton-html5/private/config/settings.yml

- Fixed two occurrences where the `tryGenerateIceCandidates` workaround rejected without an error, which borked the callers' (as in all recvonly peer instatiators) error handling
- Put it behind a config flag. Enabled by default.
* `public.media.recvonlyIceGatheringCheck`
None
Besides the clear bug that the empty rejections caused (essentially freezing the peer creation process), there's the flag thing.
This workaround used to be important when Kurento didn't infer prflx candidates properly, but that's no longer the case. With the flag, we can disable the workaround to see if there's any visible regression and hopefully remove it down the road if it's safe. I sure want to get rid of it because it's ugly and error prone.
More details on the workaround motivation are in the inline comments: …

[html5/webrtc] Fix tryGenerateIceCandidates rejections and put it behind a flag

---

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/styles.scss
bigbluebutton-html5/imports/ui/components/chat/styles.scss
bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx

Fixes safari console log errors on iPad / add z-index's 
These errors were being shown in the safari console on iPad.

Fix console errors in safari on iPad

---

bigbluebutton-config/bin/bbb-record

This patch modifies `bbb-record` allowing the user `bigbluebutton` to
delete recordings. The user has all necessary access rights, meaning
that the deletion works without a problem and the check for root does
not protect anything. The user owns the data after all. The current
check just makes things less convenient.
_Making this a patch against 2.2.x since it pretty safe and it would be really convenient to have this._

Allow user bigbluebutton to delete recordings

---

bigbluebutton-html5/imports/startup/server/index.js

Sockjs-node has a hardcoded timeout for ping/pong of 10 seconds ( https://github.com/sockjs/sockjs-node/blob/1ef08901f045aae7b4df0f91ef598d7a11e82897/lib/transport/websocket.js#L78 ).
When meteor is busy ( CPU 100% ) it causes all clients to be disconnected and reconnecting, causing new timeouts, this PR inject's a modified version of heartbeat function that:
1. Keeps track of last websocket traffic event.
2. Skips sending the heartbeat if the connection is not inactive ( if there is traffic, doesn't generate server->client heartbeats ).
3. Logs user ID when a disconnection happens due to ping ( server-> client ) timeout.
https://www.dropbox.com/s/jgc8cmv6inizndx/Jo%C3%A3o%20Siebel%20-%20sem_pr.mp4?dl=0
https://www.dropbox.com/s/02mlob93gxa0e8u/Jo%C3%A3o%20Siebel%20-%20com_pr.mp4?dl=0

Tweak sockjs timeout value

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java

The message/event UserLeftVoiceConfToClientEvtMsg is used when user leaves mic and listenonly, but it only sets to false the 'voiceJoined' (which represents the <hasVoiceVoiceJoined> property in BBB's XML API.
We now also set to false the 'listeningOnly' (which represents the <isListeningOnly> property in BBB's XML API). Setting both to false is not a problem, once 'MIC' and 'ListenOnly' states are mutually exclusives
Fixes #10852

Set listenOnly to false when user left voice

---

bigbluebutton-html5/imports/startup/client/intl.jsx
bigbluebutton-html5/imports/startup/server/redis.js
bigbluebutton-html5/imports/ui/components/legacy/component.jsx
bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
bigbluebutton-html5/imports/ui/components/settings/service.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Code changes to allow for meetings' redis events to be processed on different html5 nodejs pid's
Packaging changes are to be made before this can be used but for this code bypasses the need of loadbalancing of potentially multiple parallel processes. `bbb-meetinginstance=X` (where X is 1...N (the number of running processes)) property will need to be passed as part of the **create** meeting command in the `meta` section.
When this is merged it will be backward compatible (that is you do not need to pass the meta parameter, no need to run multiple nodejs processes either)

Support for parallel bbb-html5 nodejs processes. Part 1

---

bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/groupChatMsgBroadcast.js
bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js

The function used for changing data in mongo DB is asynchronous when it receives a callback.
The effect of this is that the queue was not waiting the end of the processing of a message to call the next one.
It could cause a high CPU usage ( hundreds of async calls at same time ).
One practical example of this problem is that under high load the chat messages was being handled out of order, this PR removes the callback from all upsert calls, forcing the handle of queue messages to be synchronous ( making the queue work as expected ).
The gifs below compare the receive order from 100 messages:

Handle chat messages in sync way

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx

This could leave users to have your audio reconnected in the main room, while joining a breakout room, causing confusion between participants.
Some information can be found in #10528
I am also reverting 0a601359bbc8c45eafc784da08f49d1e6162cfa1, because this breaks the username in breakout's participant list every time moderator activate the audio in the breakout room. This happens because, when activating audio from the main's room, the moderator joins the breakout room as a FreeSWITCH's voice user; since callerIdName contains base64-encoded name (instead of the username of the moderator), users in breakout see the encoded name, instead of the real one.
Fixing this will take more changes on akka-apps that i will separate in a new patch, containing the reverted commit + akka-apps changes.

Do not trigger reconnect when ICE connection terminates before hanging up process is finished

---

bigbluebutton-config/bin/bbb-conf

Warns the administrator during `bbb-conf --check` if the server has the default `stun.freeswitch.org` configuration and points to documentation link on changing it.

Added check for default stun.freeswitch.org

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

This is the same behavior we used to have on older sip.js version code
By doing this we reduce errors when user try to perform join/hangup during an websocket reconnection

Reduce delay for the first reconnection attempt of audio's websocket

---

bigbluebutton-config/bin/bbb-conf

Don't print a warning about using `:5066` in `sip.js` if `sipjsHackViaWs=true` in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`.

Don't warn about sip.js if sipjsHackViaWs=true

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

Instead of sending using rfc4733 standard, we use INFO message for all transfers
INFO message was used in older SIP.js version. Although this is not a standard for sending DTMF tones, this has more reliability (once it sent over TCP)
This might reduce occurrences of 1008

Use INFO message as default for sending dtmf on call transfer

---

bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js
bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js
bigbluebutton-html5/private/config/settings.yml

* Disabled by default logging from client -> bbb-html5 (Winston). Most servers I know of utilize the path Bunyan (client side) -> nginx -> writing to file. So the logs in systemd were a duplicate.
* Adjusted two logs that appeared broken
* Removed the too-frequent logging for cursor (when debug enabled)

Reduce server side logging

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/peertube.jsx

This implements a ReactPlayer wrapper for the PeerTube video API. Not all functionality is ready, but it's just enough so that we can synchronize it using ou External Video Component. Currently the regex used to detect peertube videos is very broad, since the service could be hosted in any domain, but since it will try the regex after all other services failed it should be ok. This PR was tested with the following videos:
https://peertube.fr/videos/watch/161eaaa2-92ad-47f9-b6e0-17c7585bbef1
https://tube.4aem.com/videos/watch/85107722-44c0-446e-8fcd-8ba2d5ccbdbd
https://worldofvids.com/videos/watch/6e4722a4-028d-4f51-910c-345cc95c5ff9
Currently the presenter can play, pause, seek and change the playback rate of the video and this will be synchronized along to the viewers. Viewer controls …

First version of a PeerTube player

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/private/locales/en.json

BigBlueButton already allows mirroring the users own webcam as a global
setting set by administrators. Users have no way of choosing this on
their own.
This patch turns this functionality into a user setting for all webcams.
Every camera menu now gets a “mirror” entry.
The global setting is still used as a default value, keeping the current
behavior as it is to not confuse users.

Allow mirroring individual webcams

---

bigbluebutton-config/bin/apply-lib.sh

Removes empty `After=` in creation statement for `/etc/systemd/system/bbb-webrtc-sfu.service.d/override.conf` in 
`apply-lib.sh`.
systemd send a warning for this line.
Thanks to @davka :-)
Kind regards
Timm

Empty After= may confuses systemd

---

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx

This PR adds data-tests to all different types of chat messages **system**/**user**:
- adds **data-test="chatWelcomeMessageText"** to Welcome chat message
- adds **data-test="chatUserMessageText"** to Users chat messages
- adds **data-test="chatPollMessageText"** to Poll results chat messages
- adds **data-test="chatClearMessageText"** to Clear Messages chat message
It's gonna be used to fix and update old automated tests and add Welcome Message test spec to Chat test suite.

adds data-tests to chat all different types of messages

---

.github/workflows/check-merge-conflict.yml

This patch adds a simple GitHub Actions workflow which will
automatically check open pull requests on code changes, adding a comment
and a label if the pull request has conflicts. The label will
automatically be removed again once the conflict has been resolved.
We use this for a while now with opencast and it really helps since
people do not have to manually check if their pull requests need an
update any longer.
An example, of hoe this looks in action can be found at
https://github.com/opencast/opencast/pull/2053#issuecomment-734987582

Automate Conflict Check for Pull Requests

---

bigbluebutton-config/bin/apply-lib.sh

Activated by calling `setNumberOfHTML5Processes 2` (or change 2 with different number, representing the desired number of parallel instances of nodejs)
The checks for min / max acceptable values are done in `workers-start.sh` (included in bbb-html5)
Related to #10933  #10868 #10860

Added setNumberOfHTML5Processes to apply-lib.sh

---

bigbluebutton-html5/imports/ui/components/media/container.jsx

fixes screenshare toast - issue: #10982

---

record-and-playback/presentation/scripts/process/presentation.rb
record-and-playback/presentation/scripts/publish/presentation.rb

Collects the shared notes' HTML raw data and publishes it along with the other
recording files. The playback will fetch for this file and include an option to
display it's content over the chat.
Along with the new playback (https://github.com/bigbluebutton/bbb-playback)
this can be used to check the last state of the shared notes from a meeting that
was recorded.

Publish recorded shared notes' content

---

record-and-playback/presentation/scripts/publish/presentation.rb

This is the same as #10252 but with a new target branch.
During presentation publishing, files are opened but not closed. On NFS storage, this prevents cleanup of the parent directory after the actual work is done. The scripts fail with an `Directory not empty @ dir_s_rmdir` error. PR #9857 tried to fix this, but missed some spots. This PR fixes the "publish" phase, which was missed by the previous PR.
closes #9062
closes #9110
Both are already closed, though.
We run a large BBB Instance on NFS storage and hat custom fixes for this issue in place. We removed the custom fixes thinking this issue is resolved. It broke again. Thus, this PR.
That's all.

Fix: Presentation publishing fails when run on NFS storage

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiErrors.java
bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Cherry-picked the commits from https://github.com/bigbluebutton/bigbluebutton/pull/9251 and https://github.com/bigbluebutton/bigbluebutton/pull/9855 which were already merged into 2.3.x, but not yet into 2.2.x.
Also see Issue #9024
Description from the cherry-picked PR 9251 from @elor:
```
Fixes #9024 (voiceBridge collision for two independent meetings) by performing two changes:
1. Abort meeting creation if either telVoice or webVoice collide with an existing meeting
2. If telVoice is generated by BBB (i.e. not passed to the API), try up to 10 times for a unique telVoice
Since the issue is extremely rare, step 2 should find a valid telVoice within 1 try.
The fix was tested by forcing telVoice collisions through the API as well as by setting colliding values in ApiController.groovy and …
```

2.2.x: Fix voiceBridge collision

---

bigbluebutton-config/bin/bbb-conf

Same pull request as in bbb-install, as it uses the same method to determine the primary ip address.
https://github.com/bigbluebutton/bbb-install/pull/286
from the hostname man: "Do not make any assumptions about the order of the output."
Other interfaces, like Docker bridges tend to be first in line in "hostname -I", which will result in a malconfigured BBB.
This change determines the primary interface by looking up the primary device of the default route.

The first element of "hostname -I" is not intended to receive the primary IP address in bbb-conf

---

bigbluebutton-html5/imports/api/group-chat-msg/server/methods/stopUserTyping.js

Prevent calling `stopUserTyping` when parameteres are `undefined`.
closes #10977

Prevent calling stopUserTyping when parameters are undefined

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/private/config/settings.yml

This was added as an option (websocketKeepAliveInterval), which is the interval to send keep alive messages.
Setting websocketKeepAliveInterval to 0 disables the keep alive, producing the same old behavior.
This helps avoid websocket disconnection due to socket inactivity, preventing it to unnecessarily reconnect.
Also, sometimes reconnect fails and error 1005 is triggered.
Fixes problems reported in bigbluebutton#10985.
Reduces occurrences of error 1005.
Also added option "traceSip in settings.yml (SIP tracing is now disabled by default)

Add keep alive message to audio's websocket 

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

In #11008 I removed the obsolete url for Flash client and had consolidated the join url for the HTML5 client under the same name (i.e. `defaultClientUrl`) since we only support one client type now. However, this change caused issues when upgrading servers due to the fact that we do not overwrite bigbluebutton.properties ..
In this PR I rename the `defaultClientUrl` parameter to be the new, unused `defaultHTML5ClientUrl` to avoid any collisions and to ensure the correct values are used on any type of BBB 2.3 installation

Change bigbluebutton.properties client url param to defaultHTML5ClientUrl

---

akka-bbb-apps/src/universal/conf/application.conf

change http -> https at services-bbbWebAPI.
Most of the users, especially those who tweak the source code of akka-bbb-apps, should be using https.
http at this place prevents to start breakout room under a modified akka-bbb-apps in BBB 2.2 (2.3 seems to be OK). Setting https as a default value would be less confusing.
I am not sure if this problem is universal or specific to my server.

secure http in application.conf

---

bigbluebutton-html5/imports/ui/components/actions-bar/service.js
bigbluebutton-html5/private/locales/en.json

The videoDock locales - this is my mistake - when I pull from 2.2 I reset all locales/ files since I don't want to cause conflicts. I should pay more attention if en.json was modified.
The isPresenter needed a default value because now that we don't keep offline users on client side, the presenter's UI was breaking when being removed from the meeting

Handle ejected presenter case, add missing videoDock locales

---

record-and-playback/presentation/scripts/presentation.nginx
record-and-playback/presentation/scripts/publish/presentation.rb

This PR modifies the presentation playback link to https://github.com/bigbluebutton/bbb-playback. Also, it makes bbb-playback the default playback for presentation even for old recordings.

Support for bbb-playback

---

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss

Enables the copy-pasting (pointer events) in the chat window on 2.3a3
Most likely after 2.3a3, copy and pasting in the chat window has been impossible. Thus copying the invitation URL has been quite tedious. 
The problem was confirmed in test23 server. The attribute "pointer-events: none;" is falling down from somewhere.

enabling copy-pasting in the chat window on 2.3a3

---

bbb-libreoffice/docker/Dockerfile

Add fonts-noto-cjk to build of libreoffice docker container

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Fixes a problem in 2.3a2, that is, the slide size gets crazy when turning on and off fullscreen mode.
closes #10459 , related to #10589 
Ultimately to perform whole presentation in fullscreen mode.
The problem is that "PresentationIsFullscreen" variable in layout/layout-manager is one step delayed to be updated. This is caused because the effect of "layoutContextDispatch" method in presentation/component does not reach immediately to that variable.
I mean,
(1) Toggle fullscreen -> (2) slide size decided before the "PresentationIsFullscreen" variable being updated in layout/layout-manager -> (3) "layoutContextDispatch" method in presentation/component fired and "PresentationIsFullscreen" variable is finally updated, but it's too late.
Obviously this PR does not indicate the best solution. …

Fix slide size problem at fullscreen <-> window-mode transition

---

.gitmodules

This PR adds bbb-webrtc-sfu, etherpad-lite and freeswitch as git submodules, in order to facilitate the planned 2.3 build process.
(none)
We agreed on this in today's meeting (@ffdixon, @basisbit, @schrd).
If I'm not mistaken, the repo should now be cloned/updated with parameters for submodules. What would be the right place to document this?
```
git clone --recurse-submodules -j4 https://github.com/bigbluebutton/bigbluebutton
git pull --recurse-submodules
```

add submodules: bbb-webrtc-sfu, etherpad-lite, freeswitch

---

bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

This PR adds bbb-web code for adjusting the guestWaitURL so it contains the meeting instanceId needed for bbb-html5.
It also removes the requirement for `authed: true` in the HTML5 client which was causing [approve] guests to not be shown in the userlist (although they were in the meeting). This requirement was fairly new (2.3), and in the past used to be `connectionStatus: 'online'`. Given that on 2.3 we added a ConnectionManager to filter the offline users, I think it is a more correct transition to just drop the connectionStatus condition, rather than replacing it with a stricter one.
Before this PR waiting guests would be redirected to 404 page, where the URL did not contain meeting instanceId
Related to #11008 where the joinURL underwent the same replacement of %%INSTANCEID%%

Handle guestWait url for multiple nodejs instanceIds

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Fixes #11057
before: `https://bbb.example.com/html5client/2resources/sounds/silence.mp3`
after:    `https://bbb.example.com/html5client/2/resources/sounds/silence.mp3`
Thanks @Rahimimojtaba for reporting!

Correct path to silence.mp3

---

bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx

Fixes #10965
The id was duplicated a few lines below (the first one seemed unnecessary) 
```
<label htmlFor="video-modal-input" id="video-modal-input">
{intl.formatMessage(intlMessages.input)}
<input
id="video-modal-input"
```

Remove duplicated html id video-modal-input

---

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx

This PR addresses the following issue:
Users A and B join a meeting
User A sends public chat message and then leaves
User B refreshes the client. We no longer store info about userA, so when we try to re-render the old chat message, we cannot reconstruct the avatar string in the chat list. In this PR I simply provide a fallback value of "  ".
@Tainan404 has been working on significant changes to chat (including storing the username of the sender in the chat object), so once his work is merged, this temporary fix will be overwritten. It is in place just to ensure there is no errors in 2.3-alpha5 meanwhile.
The chat messages sent from now-offline users will have empty avatar string
Related to #11111

Temporarily allow undefined user name for offline chat sender

---

bigbluebutton-html5/private/config/settings.yml

Increased camera `baseTimeout` from 15 to 30 seconds in the HTML5 client. After this timeout, the frontend cancels the webcam sharing dialog and displays a `1020 error`.
When most students of one or more school classes start webcam sharing at the same time, Kurento occasionally takes longer than 15 seconds to return the webrtc connection success state to the client. This problem also happens quite often when students return from breakout rooms. 
This change reduces the amounts of the frontend showing `error 1020` and thus avoid the additional connection establishing requests from clients who try multiple times and who thus made the problem exponentially worse.
See https://github.com/bigbluebutton/bigbluebutton/issues/11099#issuecomment-753985300

Increase camera baseTimeout to 30 seconds (webcam share timeout workaround)

---

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/User.java

There are some case scenarios where the stream is duplicated at the API collection. It likely happens because of some stream start event duplication or webcam reconnection. This is not so easy to replicate at development but it has been seen in production more than once.
These changes validate the stream before including it at the user's stream collection.
cc @prlanzarin .

Check if stream already exists before adding in list

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/private/config/settings.yml

In some scenarios, there's no need for the browser to apply such audio filters. For example, when user's microphone already does audio filtering (echo cancellation, noise supression ...).
This commit doens't change the current behavior (filters still follow browser's default config): admins need to uncomment/set these values if disabling/enabling specific filters if desired.
This is related to #4873

Allow audio constraints to be changed in bbb-html5's settings.yml

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

Video provider's service for local stream control was wrongly setting the disconnected
state when a multiple webcam user tried to stop a single cam. The `stopVideo` method
was inconsistent when called multiple times for the same `cameraId`.
Included a better testing scope for event dispatching and disconnected state handling.
Closes #11140

Fix stream stop for multiple webcams

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

Remove the requirement of mountModal function (in presentation uploader), which seems not necessary anymore.
Sometime I got a warning of mountModal being undefined.
This warning has been persistent since I started using 2.3a, although it doesn't make any harm. Oddly I don't see it in the test23 server.

Remove mountModal requirement in presentation uploader

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx

This is a very simple patch improving the support for 16x9 cameras.
In mixed mode – if 4x3 and 16x9 cameras are present – everything looks
like it did before but if only 16x9 (or wider) cameras are present,
BigBlueButton will drop the letter boxes and show a 16x9 video
container.
---
This relates to #6974
This relates to #9463

Improve 16x9 Support

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/audio/container.jsx
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/private/locales/en.json
bigbluebutton-html5/private/locales/pt_BR.json

As explained in #11143, disabling audio filters is desired in some scenarios.
This basically adds an option for user to disable default constraints.
When user doesn't change this value in Settings > Application, the default
value for each audio constraints is retrieved from settings.yml.
When user changes this value in Settings > Application, audio
filters (AGC, Noise Supression and Echo Cancellation) are all set to
true/false, according to the value selected in the Settings GUI.
To start it simple, we decided to not to add a different setting in the GUI for
each audio contraint. This may be added in the future, though (perhaps in a
dedicated Audio Settings tab)
This is related to #4873

Add setting for enabling/disabling microphone audio filters

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

adds a click handler to close open text area's. This will prevent the situation where the `select` elements are unable to expand.
Closes #11197

Prevent open text-area blocking select menus

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

This removes the console warning about invalid constraint
For more info see: #11206

Avoid setting empty/undefined constraint

---

bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/private/config/settings.yml

The `action-bar` mute toggle currently has no debounce nor throttle, making it spammable.
Pretty easy to overload meteor if remote logging is on and enough people do it at the same time.
So I did the following:
- Add a throttle to audio-controls' toggleMuteMicrophone
- Make the throttle's interval configurable
* New configuration parameter: `Meteor.settings.public.media.toggleMuteThrottleTime`. Throttle interval in ms.
* Default value is 300 ms. I did not use much science coming up with that default. I just tested it a bit to see what would mitigate damage while not making it too clunky.
* Original behaviour is restored by setting it to 0 ms (worst case scenario it'll be clamped to 1 ms depending on the JS engine).
This is really just a workaround. Throttling should be server-mandated. …

audio: add a configurable throttle to action-bar`s mute toggle

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

When multiple actions were bolted in the dropdown (mirror, focus), the video-list-item actions dropdown entry keys were getting duplicated as $cameraId. 
This is a regression from https://github.com/bigbluebutton/bigbluebutton/pull/10925. I'm not sure why React isn't churning out warnings in the console, but nonetheless the keys should be revised.
So:
- Add a new entry to video-list's `actions` called `actionName`, which is the hardcoded action name (constants)
- Use the actionName to create a unique ID concatenated with the cameraId `${cameraId}-${action.actionName}`
None
https://github.com/bigbluebutton/bigbluebutton/pull/10925

video-provider: make video-list-item actions dropdown keys unique

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx

This reverts commit b8fc94c722035ef32bb0d6395d6c7a72f5c6b1d9, which was introduced by PR #10912.
None.
Mea culpa. I did not test #10912 as thoroughly as I should.
There's a regression with aspect ratio containment in the video dock, with Safari, when there are vertical (ie smartphone) cameras shared in the meeting. Likely induced by the maxHeight change which I know behaves a bit clunkier than in Blink or Gecko. Regressions I've seen:
- Webcam's aren't contained to the presentation
- All webcam entries are scaled to the entry with the largest height, and that one isn't cropped
Example screenshot: 
I personally don't intend to invest any time in 16x9 UI support in 2.2, so I'm reverting it for the time being.
#10912.

video-provider: Revert "Improve 16x9 Support"

---

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx

The debounce introduced in https://github.com/bigbluebutton/bigbluebutton/pull/9756 was broken because the first argument passed to it was wrong. 
That opened a tiny little breach where a spammer could effectively unmute an user right after muting them (which the talking indicator was designed not to allow even if bbb-web allows mods to unmute users (?)).
Moreover, if akka-apps' rights management ejections are activated and mods aren't allowed to unmute users, the mod would get kicked out. So:
- Fix `muteUser`'s debouncing
- Make it's interval a constant (not configurable for the time being, kept the original 500ms)
Fixes #11226
Might fix https://github.com/bigbluebutton/bigbluebutton/issues/9731 ? I don't really know what's up with that issue. If #9756 was supposed to fix it it should've …

audio: fix talking-indicator mute debounce

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

Backporting #11207 to 2.2.x
> adds a click handler to close open text area's. This will prevent the situation where the select elements are unable to expand.

Prevent open textarea blocking dropdown menus

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

This was missed in recent audio/sip.js changes.
MediaStream is now returned from SIP.js
Related to #10733

Correctly return MediaStream object when calling audio-manager's inputStream

---

bigbluebutton-web/grails-app/conf/spring/resources.xml

Restores allowRequestsWithoutSession to actually be populated from the properties file.
I wanted to use bigbluebutton in an iframe in chrome, safari, etc, and allowRequestsWithoutSession
wasn't working.
It was removed in an overzealous deletion in
https://github.com/bigbluebutton/bigbluebutton/pull/11008/commits/418fdb1a318a9d6524d0250485750109883acd82

Restore allowRequestsWithoutSession to resources.xml

---

.travis.yml

Changes to the Travis CI configuration:
- Update to Node.js 12 (LTS)
- Update to Ubuntu 18.04 Bionic
- Small refactor
It seems like the docker commands in the `after_script` are useless right now. Also, CI needs to be expanded to test far more extensive.

Travis CI: Update build environment, refactor

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

This patch fixes the issue that regexp special characters like `$` in a
room name cause an error when trying to enter the room.
This fixes #8900
This fixes #4671

Fix Special Characters in Room Names

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/service.js

Changes the username listing on breakout room creation by adding an identification to the current user name.
closes #8551

Show current user identification on breakout room creation

---

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx

This PR fix two issues related to messages ovelapping on chat
The cache:
In virtualized chat a cache is used for each item to avoid unnecessary recalculations, this logic works great for static items, but in our chat the messages increase in size when grouping messages, to fix I invalidated the old cache by forcing the virtualized list to recalculate when a new message arrives
The CSS calculation:
The messages of welcome have some styles that changes the final height of the element and the time to apply this stylies depends of the CPU/GPU performance, causing sometime it happens after the vritualized list size calculation, the solutions is trigger the recalculation sometimes to get the right dimensions

Fix overlapping messages

---

bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx

This PR introduces a small fix for random user picking. The modal that says there's no viewers to pick from didn't work properly. This PR makes sure presenter sees such modal when the meeting consists of moderators only.

Fix for random user picking: presenter is notified when there's no viewers to randomly pick from

---

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js
bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
bigbluebutton-html5/private/config/settings.yml

Adds a join param `bbb_skip_check_audio_on_first_join` to skip echo test on the first join only.
when `bbb_skip_check_audio_on_first_join`=true on client load you are automatically joined in audio, bypassing echo test. If you hang up and try to join audio again (via UI button) you will be presented with echo test
Closes #11283

Add new join param skip echo test on first join only

---

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js
bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/container.jsx
bigbluebutton-html5/imports/ui/components/video-preview/service.js
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx
bigbluebutton-html5/private/config/settings.yml

Reverts the changes in PR #8353, so if the `userdata-bbb_skip_video_preview` parameter is set to `true` the video preview always skips
Introduces `userdata-bbb_skip_video_preview_on_first_join` parameter to skip only on first joining of webcam
closes #10454

Changes on webcam skip preview behavior

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx

Changes video preview modal behavior by not rendering it if `userdata-bbb_skip_video_preview_on_first_join=true` or `userdata-bbb_skip_video_preview=true`
Restores `data-test` on join video button

Fix video preview modal behavior

---

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx

Ensures the chat list element `key` is unique so the component knows to update.
Closes #10002

Fix message list not updating when switching between private chats

---

bigbluebutton-html5/private/config/settings.yml

Changes the default value for cursorInterval rom 40ms to 150ms
Recommended in https://github.com/bigbluebutton/bigbluebutton/issues/11183 and further justified in https://github.com/bigbluebutton/bigbluebutton/pull/11187#issuecomment-764946902 with significant community support
We need to backport this to 2.2.x-release

Set default cursorInterval to 150ms (was 40ms)

---

bbb-webhooks/.gitignore
bbb-webhooks/README.md

The current bbb-webhooks `readme.md` documentation doesn't accurately tell how to get the bbb-webhooks configured for custom development, and release procedures. Updates are my venture into configuring webhooks for my own personal use, while providing documentation to help others in the future from having to start a new topic in regards, on the bigbluebutton-dev group forum.

Updated the bbb-webhooks documentation. Ensuring the configuration file gets ignored.

---

bigbluebutton-html5/imports/api/guest-users/server/modifiers/clearGuestUsers.js
bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js
bigbluebutton-html5/imports/api/voice-call-states/server/modifiers/clearVoiceCallStates.js
bigbluebutton-html5/imports/api/whiteboard-multi-user/server/modifiers/clearWhiteboardMultiUser.js

The collections for `guestUsers`, `voiceCallStates` and `whiteboard-multi-user` aren't been cleared after a meeting end, this PR implements the missing functions and clear those collection after the meeting has ended.

Clear missing collections on meeting end

---

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx

Disable typing notification events when the feature is disabled (rendering was already disabled)
closes #11161

Disable user typing notifications when feature is disabled

---

bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js
bigbluebutton-html5/imports/api/screenshare/server/modifiers/clearScreenshare.js

Properly clear screen share collection when a meeting ends. This PR cover the case where the moderator end the meeting before the presenter stop the screen share.

Cover clear screen share collection case

---

bigbluebutton-html5/imports/ui/components/external-video-player/service.js

This prevents problems if the presenter tries to use insecure http urls on the external video modal. If we share them the browser might block the iframe or some users.

Don't validate insecure http urls for external video to prevent browser errors

---

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx

Changes screenshare behavior on join breakout room to match audio and video (screenshare will now stop when user joins a breakout room).
closes #10035

Stop screenshare on joining breakout room

---

bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/invitation/container.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/service.js
bigbluebutton-html5/private/config/settings.yml

Added new settings `breakouts.sendInvitationToIncludedModerators` to enable/disable breakout invitations to moderators.
Changes `settings.public.app.breakoutRoomLimit` to `settings.public.app.breakouts.breakoutRoomLimit`
closes #11276

Add property to settings.yml to enable/disable breakout invitations to moderators

---

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx

Fixes a bug where the video actions dropdown won't close after you open it.
closes #11338

Fix webcam video dropdown collapse after expanding

---

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx

Adds a delay to join video button click event, to prevent double clicks on leave/join video
closes #8367

Add delay to join video button

---

akka-bbb-apps/src/templates/systemloader/systemd/start-template
akka-bbb-fsesl/src/templates/systemloader/systemd/start-template

Currently there is a mechanism in bbb-config which adds overlay units.
This is not neccesary because sbt allows you to specify your own unit
files.
It removes the necessity to install systemd override files by bbb-config

Customize systemd unit files

---

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx

This bug fixes clearing the public chat history to not break the client.
This bug was introduced in #11305, as the system-generated message notifying
the user that the chat history has been cleared does not have an id.
closes #11349
I want to implement a window.postMessage driven chat clearing event, but first need
to be able to not have chat clearing break everything.

Fix rendering after public chat cleared

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx

This makes the screen reader announce the status changes in the user list so user's don't have to navigate to get the info. 
The caveat with this solution is the status notifications are not done through the toasts. For the screen reader this means to announce the status changes, the user-list must be open.
Closes #11372

Make screen reader announce status changes in userlist

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js

Fixes slide position bug described on issue #11270 by checking if slide position values exist.
closes #11270

Set safe default values for slide position (WIP)

---

akka-bbb-apps/src/debian/DEBIAN/postinst
akka-bbb-apps/src/debian/DEBIAN/preinst

**Goal:** get to the point where upgrades can occur without having to re-run bbb-conf (or anything else)
The Scala build tool (sbt) allows packaging scripts to be put in the `src/debian/DEBIAN` directory to augment (not replace) the standard scripts provided by sbt.
I've verified that this patch successfully preserves the two settings in question over an upgrade, and doesn't affect the script's standard operation, which is to add bbb-apps-akka as a system service and start it running.

preserve bbbWebAPI and sharedSecret over upgrades

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala

Check the resulting role passed through the message body instead of the user's current role.
https://github.com/bigbluebutton/bigbluebutton/issues/11182

User role is incorrect after client reconnect.

---

bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

After audio reconnection, a muted user would have it's microphone unmuted by default, unless muteOnStart is set to true. This fix this problem.
Fixes #9016

Preserve mutestatus when disconnecting/reconnecting microphone

---

bigbluebutton-html5/imports/startup/client/intl.jsx
bigbluebutton-html5/imports/ui/components/loading-screen/styles.scss

Changes the way `loadingScreen` component is displayed when changing language settings.
**Before:** when `loadingScreen` appears all content is unmounted, then remounted
**Now:** `loadingScreen` appears on top of content
This change prevents webcam, screenshare and external video interruption when user changes language settings.
closes #11351 + #7736

Fixes interruption of webcam, external video and screenshare when user changes language settings

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EndBreakoutRoomInternalMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LogoutAndEndMeetingCmdMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingExpiryTrackerHelper.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/meeting/EndMeetingSysCmdMsgHdlr.scala

Inserts userId attribute to End meeting function calls for Analytics purpose.

fix inserts userId to the EndMeeting function calls.

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx

Fixes a bug where a user had to open the slide upload dialog twice to see all uploaded slides after he has become presenter.
closes #10377

Show uploaded slides from other users

---

bigbluebutton-html5/imports/ui/components/dropdown/styles.scss

Removes the `transform` on the `.tether-out-of-bounds` for small breakpoints
Closes #10915

Fix user-list-item dropdowns breaking on mobile screen sizes

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
akka-bbb-apps/src/universal/conf/application.conf
akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/GetUsersStatusCommand.java

This is a refurbish of PR #10959. Dial-in's are now theoretically handled (need someone to test it).
Reconnects may introduce ghost voice users in a meeting when the client fails to
rejoin but the audio connection remains active.
While fetching for the voice conference user's status, apps can now check if a
voice user has a matching user record. If it doesn't, eject the voice user.
**TODO**:
- ~~Avoid dial-in users to be ejected~~ Tackled in 8f233b7, 3c0493a
- ~~Once dial-in is covered, the breakout room check can be removed~~G

Option to eject voice users with no matching user (re-submit #10959)

---

bigbluebutton-html5/private/config/settings.yml

- enable `cameraQualityThresholds` by default
- enable `videoPagination` for mobile devices @ 4(student)/6(mod) streams ~and for desktop devices @ 25(student)/50(mod) streams~
This change contains rather high values so that admins see that these features exist, but typical use cases which might not want video-pagination enabled (typical 28people school class) are still not "annoyed".
One of the main issues in 2.2.x problem reports currently in the wild in social media and in the bbb admin groups seems to be that people turn a couple of webcams on and the clients or the server or the internet connection already can't handle it any more. In most cases, enabling video-pagination for mobile devices and also cameraQualityThresholds already "solves" the problem and makes it possible for much …

Enable video-pagination and cameraQualityThresholds by default

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/styles.scss

Adds a default poll button for `yes / no / abstention`.
The `yes / no / abstention` default poll option wasn't included as part of the UI updates.

Add yes / no / abstention option to updated Poll UI

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

This PR skips calculating / rendering the poll results to the whiteboard for the specific user who may have a swapped presentation. I suspect this will be a temporary solution until the poll annotation calculations are moved from the client side.
Closes #11097

Skip publishing poll annotation to whiteboard if presentation swapped

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx

Fix user offline/online status indicator on chat.
Closes #11395
Closes #11394

Fix user status in chat

---

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addSystemMsg.js
bigbluebutton-html5/imports/api/polls/server/eventHandlers.js
bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/container.jsx
bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js
bigbluebutton-html5/private/config/settings.yml

Prevents user messages containing `bbb-published-poll-` from being displayed as poll results, by changing the way poll result messages are parsed before being displayed on chat.
(includes all changes made on PR #11415 + resolves conflicts caused by PR #11366)
closes #11393

Fix user-sent poll result messages

---

bigbluebutton-config/bin/apply-lib.sh

This function was introduced in 2.3-alpha5 to provide a way to set how many nodejs processes you want to run as part of `bbb-html5`'s routine.
#11317 reverted that approach for parallel processes and introduced an alternative which requires instead two values - number of 'frontend' processes and number of 'backend' processes.
This additonal variable, coupled with comments from community members who treated the `apply-config.sh` as a configuration file rather than a script, has led me to believe that it's best for administrators to go straight to the config file `/usr/share/meteor/bundle/bbb-html5-with-roles.conf` and change the defaults if needed. A restart of `bbb-html5` would be required. (`sudo systemctl restart bbb-html5`)
```
NUMBER_OF_BACKEND_NODEJS_PROCESSES=2 …
```

Remove setNumberOfHTML5Processes

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx

Fixes a bug that made `bbb_skip_check_audio_on_first_join` parameter stop working as expected.
This bug was caused by changes made on PR #11381 and reported by @maths22 
> This PR accidentally broke `bbb_skip_check_audio_on_first_join`. In particular the changes to `bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx` combined with the version of `joinMicrophone` in `bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js` dropped the check for `skipCheckOnJoin`

Fix bbb_skip_check_audio_on_first_join parameter

---

bigbluebutton-html5/imports/startup/server/index.js
bigbluebutton-html5/imports/ui/components/captions/writer-menu/component.jsx
bigbluebutton-html5/imports/ui/components/captions/writer-menu/container.jsx
bigbluebutton-html5/imports/ui/components/locales-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
bigbluebutton-html5/private/config/settings.yml

- Adds `showAllAvailableLocales` (default: false) flag to the settings file for quick enable/disable.
- Changes locale settings and captions dropdown to only display a locale if:
- it is a general version of a locale with no specific locales
- it is a specific version of a selected locale with many specific versions
- it is a specific version of a locale with no general locale

Reduces the number of options displayed on locale settings dropdown

---

akka-bbb-apps/build.sbt
akka-bbb-apps/src/debian/DEBIAN/postinst
akka-bbb-apps/src/debian/DEBIAN/postrm
akka-bbb-apps/src/debian/DEBIAN/preinst
akka-bbb-fsesl/build.sbt
akka-bbb-fsesl/src/debian/DEBIAN/postrm
akka-bbb-fsesl/src/debian/DEBIAN/preinst
bigbluebutton-config/bin/bbb-conf

This PR lets `bbb-apps-akka` and `bbb-fsesl-akka` read their configuration from `/etc/bigbluebutton/`. The files in `/etc/bigbluebutton` include the config files shipped with the packages and let the operator customize settings without changing files from the packages.
Operators who use configuration management tools like ansible, chef or puppet have to adjust their templates each time the BigBlueButton developers introduce new configuration settings. With this patch both can be kept seperate. On the other hand it reduces complexity from the postinst/preinst scripts of the packages as well.

Akka config

---

bigbluebutton-html5/imports/ui/components/modal/base/component.jsx

Basically same as #11406, but more generic modification - with this PR all modals will be shown over the full-screened slide or shared-screen. Inspired by the comment by @KDSBrowne in the PR 11406.
closes #11402. 
The PR #11406 is not necessary anymore if this PR is merged, so can be closed as well.
To do a "hybrid" lecture, which is to broadcast a face-to-face lecture by BBB, I need to do lectures by full-screen presentation (which would be shown by a projector in the real lecture room) as much as possible.
The modal overlaying by this PR is possible for a full-screen slide and for a full-screen shared-screen, but not for a full-screen shared external video, which uses iframe.
#11406 is only for the random user selection modal. This PR influences all modals.

Show modals overlaid on full-screen slide or shared screen

---

bigbluebutton-html5/imports/startup/client/intl.jsx

Locales were being fetched even if you simply open and save settings window (without changing any setting)
We now test it similarly we do on 2.2
Closes #11318
When first testing #11318 (bbb2.3-alpha5) , saving/chaing settings also dropped microphone's connection, but this doesn't happen anymore in bbb2.3-alpha7. So i am closing #11318, once  there's no more evidences that microphone would drop after saving/changing settings.
This is the problem this PR fixes (notice the loading page after saving settings):

Do not uncessarily fetch locales at first time you open/save settings menu

---

bigbluebutton-html5/private/locales/en.json

This PR removes `app.poll.yn` from [locales/en.json](https://github.com/bigbluebutton/bigbluebutton/blob/3f83691c52f778b9c190cd5990ce4c2f0a1019d4/bigbluebutton-html5/private/locales/en.json#L248) while it's not anymore used.

Remove unused 'app.poll.yn' from locales/en.json

---

bigbluebutton-html5/imports/ui/components/app/container.jsx

When observing changes in User colletion, we must guarantee these changes are from main room, and not from breakout one.
Fixes #11029

Prevent ejecting user from them main room when leaving breakout room

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/service.js

Enabling moving slides by arrow keys immediately after toggling the fullscreen mode, by changing the focus.
closes #11397 
Increasing demand on "hybrid lecture", which is to broadcast the lecture that is performed face to face, requires me to do the BBB presentation by fullscreen mode all the time (showing it in the classroom by a projector). For doing so, the current implementation of toggling fullscreen is annoying.
I tested on Chrome and Edge. Other browsers have not been tested yet, but I believe it will work.

Enable arrow keys immediately after fullscreen

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Shows the polling button over the shared screen shown full-screen.
related to #10783, which has been partially fixed by #11319. This PR complements #11319.
Currently the polling button is not shown when the shared screen is displayed in full-screen mode (even the polling sound does not ring). The lecturer wants to do polling during a screen is shared, but he cannot control if the students watch it by full-screen or not. 
The problem is that the poll result is not visible anyway when the students stay full-screen. The presenter has to stop the screen share to show the result, or ask the students to stop full screen to see it. But I believe it's better than the current implementation. Currently, the poll button would not be shown in the display of full-screen students, which the presenter …

Show polling button over the full-screened shared-screen

---

bigbluebutton-html5/imports/ui/components/activity-check/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-test/container.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

After ending the notification playback, we set the ".src" property to null, which immediately stop the internal player of mobile browser (tested on Chrome for Android -  device list is on #11458).
For the specific list of devices, this prevents the internal buffer error "-61" described in #11458.
Closes #11458 
Here is the ADB logcat output immediately after setting the ".src" property to null. This log was retrieved from a Moto G8 device (chrome version 88) .
```
02-22 21:16:44.291 14160 14258 D AAudio  : AAudioStream_requestStop(s#24) called                                                                                                                                   
02-22 21:16:44.292 14160 14258 D AudioTrack: stop(155): called with 665036 frames delivered …
```

Clean up HTMLAudioElement used for notification sounds

---

bigbluebutton-html5/imports/ui/components/user-list/service.js

Instead, return empty array when **both** users and groupChats arrays are empty.
The public chat and user chats may be active when groupChats array is empty.
Fixes #11476

Do not return empty array when groupChats is empty

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.scss

Adds CSS property to force line breaks on long links (or any other long text) present in system messages.
closes #11445

Add break-word to system messages

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

Fix whiteboard text-area not allowing input on Firefox

---

bigbluebutton-html5/private/config/settings.yml

Changes the default value for customHeartbeat
We encountered a scenario where the customHeartbeat #10826 keeps the sockJS websocket open despite the fact that the ping-pong procedure #7753 identified users as unresponsive and requested their removal from the meeting
Given that customHeartbeat was introduced to alleviate high nodejs CPU leading to reconnections, and that we see significantly reduced CPU loads since 2.2.30 and 2.2.31, I am disabling customHeartbeat by default to avoid conflicts with ping-pong routine.

Disable customHeartbeat 10826

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala

Sets falllback value of `voiceConf.ejectRogueVoiceUsers` to true
In #11414 we set default value for `ejectRogueVoiceUsers = true` but at the same time we have a fallback for the lazy value to be false.
Here I set the fallback value (in case the configuration line `ejectRogueVoiceUsers = true` was missing from the configuration file) to `true`, which I believe is the safer fallback value

Set falllback value of voiceConf.ejectRogueVoiceUsers to true

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss

Changes connection status modal to only display help link if `stats.help` url is set to a valid link on settings file.
Changes alignment of "no connectivity issues" message to center.

Visual changes on connection status modal

---

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx

Prevents "invisible box" of dropdown component from appearing on iPad and other mobile devices when on landscape orientation, by also checking if mobile device is in portrait orientation.
`tether-element` is used on the userlist menu, and should have 100% width/height on mobile devices (only on portrait orientation, but the orientation was not being verified).
closes #11212

Fix whiteboard use for iPad and other landscape mobile devices

---

akka-bbb-apps/project/Dependencies.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/ApiService.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/service/HealthzService.scala
akka-bbb-apps/src/universal/conf/application.conf

This PR is WIP for healthz service introduced for health check capability on bbb-core
To provide health check capability for bbb-core via Http endpoints. 
To test: issue  an Http Get request at localhost:8901/healthz 
you should expect a hardcoded json response

WIP: Http endpoint added for health check

---

bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Fixes #11490
The confusion mentioned in #11490 is caused because when you leave audio (while in audio transfer) the state of breakout component isn't properly cleared. This means when user join audio again, the breakout menu will show the label "Return audio" (but the user didn't even join breakout audio). 
This is the behavior fixed by this PR:
The default behavior for audio is: when leaving or reconnecting audio, we recover the mute state but not the 'breakout-room-state' (the breakout-room audio that was active before the audio disconnect/reconnect). So we leave the user to return to breakout room by himself.
We could change this behavior by automatically connecting user into breakout audio transfer (after leaving or reconnecting) , but this could be reported in a new …

Cleanup joinedAudioOnly state when user disconnects or reconnect microphone

---

bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Prevent toggleMute api call to be called for listenonly
This has no effect to the end user, but avoids unnecessary server calls

Do not try to recover mute state when joining listenonly

---

bigbluebutton-html5/imports/startup/client/base.jsx

Removes a dependency on `BaseContainer` which was leading to a crash when a user tagged as *mobile* is removed from the meeting (the removed line was causing unnecessary re-renders when `user.mobile` property is changed).
closes #11488

Fix mobile user removal bug

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/audio/container.jsx

Do not join microphone when user is already in breakout
Fixes #11511
Related to the feature implemented in c451666
Avoid setting an unknown input deviceId 
Without 'exact' match, the browser fallbacks to the default inputDeviceId
This prevents the error (input device error)  when breakout is ended and we try to skipCheck the microphone when user returns o main room (assuming the user had the microphone active before joining breakout room). 
Related to the feature c451666

Breakout room audio fixes

---

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx

Fix textarea resizing to the wrong height, by setting `async = true` as mentioned in the [lib docs](https://github.com/buildo/react-autosize-textarea#props)
closes #11354

Fix chat textarea resizing bug

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/ValidateAuthTokenRespMsgSender.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala
bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js

This PR helps @Tainan404 to work on #11438 
When user reconnects the client will load chat messages incrementally to make it faster. It will be made based on the token validation time.
This PR:
1.  Create in Akka `lastAuthTokenValidatedOn`
_Time will be refreshed every time user validates token_
2. Include this info in pubSub `ValidateAuthTokenRespMsg`
_Send the `authTokenValidatedOn` via Redis pubsub in return of token validation_
3. Store in Meteor/Mongo (User)
_Store `authTokenValidatedOn` in mongo user model as `authTokenValidatedTime`_

Adds lastAuthTokenValidatedOn to users

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/ExternalVideoApp2x.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StartExternalVideoPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StopExternalVideoPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/UpdateExternalVideoPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/ExternalVideoMsgs.scala
bigbluebutton-html5/imports/api/external-videos/server/eventHandlers.js
bigbluebutton-html5/imports/api/external-videos/server/handlers/startExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/handlers/stopExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/handlers/updateExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/index.js
bigbluebutton-html5/imports/api/external-videos/server/methods.js
bigbluebutton-html5/imports/api/external-videos/server/methods/emitExternalVideoEvent.js
bigbluebutton-html5/imports/api/external-videos/server/methods/startWatchingExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js
bigbluebutton-html5/imports/api/external-videos/server/streamer.js
bigbluebutton-html5/imports/api/meetings/server/handlers/meetingDestruction.js
bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js
bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
bigbluebutton-html5/imports/api/users/server/store/bannedUsers.js
bigbluebutton-html5/imports/startup/server/index.js
bigbluebutton-html5/imports/startup/server/redis.js
bigbluebutton-html5/imports/ui/components/external-video-player/service.js
bigbluebutton-html5/private/config/settings.yml

This PR allows to split html5-server in multiple processes. It is inspired by PR # 8788 but with a different approach. The main idea is to create multiple html5-server processes that allow bypassing the current limitation imposed by the fact that node executes practically in a single thread. In this way, you can get more users per meeting.
Currently, there is a limitation whereby a meeting can have between 100-200 users depending on the restrictions applied to users. I would like get more users per meeting.
Using an environment variable METEOR_ROLE = [backend | frontend] multiple processes can be started. There should only be one backend process that will handle all events related to the mongoDB. The frontend processes, which only listen to the frontend-redis-channel redis channel, will …

 Split html5-server in multiple processes to larger meetings

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/GetScreenBroadcastPermissionReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/GetScreenSubscribePermissionReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamBroadcastPermissionReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamSubscribePermissionReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/GetGlobalAudioPermissionReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala

- Add RPCs to be traded **internally** between `akka-apps` and `bbb-webrtc-sfu` to add better permission checks for **video, listen only and screen sharing**
- All responses give or deny auth through the `allowed` property (bool). When false, SFU rejects requests with error `{ code: 2301, message: SFU_UNAUTHORIZED }`
- List of implement probes:
* GetGlobalAudioPermissionReqMsg/RespMsg, 
* GetCamBroadcastPermissionReqMsg/RespMsg, 
* GetCamSubscribePermissionReqMsg/RespMsg, 
* GetScreenBroadcastPermissionReqMsg/RespMsg, 
* GetScreenSubscribePermissionReqMsg/RespMsg
Needs https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/79 to have any effect.

Improve permission checks for video, screen sharing and listen only

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Fixes a new variation of #11270 bug, also related to a not-yet loaded presentation
closes #11270

Fix svg width error

---

bigbluebutton-html5/imports/startup/client/base.jsx

Fixes a layout failure when nobody is using webcam.
On a 2.3 server, sometimes a slide is shown to fit to the width of presentation area (Figure 1), sometimes not (Figure 2; there is space on the sides, seeming to reserve a webcam space) when nobody is joining with a webcam. I believe that the intended design is to show the slide as largely as possible (i.e., Figure 1 style) when nobody is using the webcam. 
After an investigation, I've found that "numUsersVideo" can be "undefined" even though the initial value is "null" in bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx.
if it's null, numUsersVideo < 1 is true, but if it's undefined, numUsersVideo < 1 is false. Thus depending on this variable being null or undefined, the layout can be changed. I suppose this is not …

numUsersVideo being undefined breaks layout

---

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java

Pad exporter uses this same location to serve pad's downloaded content
but the the match was failing because padId is not the last element
of the URL on that scenario.
Pattern follows `/pad/p/<padID>[/export/(format)]?<query>`.
Closes #11545

Fix padId getter

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx

This PR fix the clear for single message, the "issue" is on react-virtualized, the List component doesn't have reference to the list only to the list's size so when a chat with single message is cleared the size keeps the same, in that case I force the list to re-render.  
closes #11530

Fix clear chat for single message

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js

Fixes a bug where a slide with `(True/False)` would auto-generate a quick polling with the wrong label
Changes quick poll `onClick` event when there's more than one option available to match single option behavior
Slides used for testing: 
[quick-poll-slides.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6085723/quick-poll-slides.pdf)

Quick poll improvements

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Latest audio improvements already merged in 2.3. Here's the list:
- Mute state when returning from breakout audio: https://github.com/bigbluebutton/bigbluebutton/pull/11505
- "Confusion" on mute/mic state when leaving audio with breakout transfer active: https://github.com/bigbluebutton/bigbluebutton/pull/11515
- Avoid trying to recover mic state when using listen only mode: https://github.com/bigbluebutton/bigbluebutton/pull/11516
- Avoid setting unknown input device id: https://github.com/bigbluebutton/bigbluebutton/pull/11520/commits/de05622d19a574817f0989b42759fa159d33a033

Backport audio improvements from 2.3

---

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx
bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx

Adds poll and shared notes data to `layout-manager` and `panel-manager` components.
When merged, it will fix:
- `Unexpected openPanel value` browser console errors
- Camera disappearing when dragged to change position if shared notes or poll panel is open
- Incorrect presentation resizing if shared notes or poll panel is open
closes #11071
closes #11118

Fix openPanel errors related to polling and shared notes

---

bigbluebutton-config/bin/bbb-conf
bigbluebutton-web/grails-app/conf/application.groovy

It lets `bbb-web` read its config from `/etc/bigbluebutton/bbb-web.properties` in addition to `bigbluebutton.properties`. This is a follow up to #11454
bbb-conf is changed accordingly to write configuration values to
`/etc/bigbluebutton/bbb-web.properties`
Operators can define their own config for bbb-web which will not be overwritten by packages.
please have a look at `bbb-conf`. I hope I did not miss anything. It might be a good idea to let packages create `/etc/bigbluebutton/bbb-web.properties` in the postinst script and remove it if packages are purged.

add overlay config for bbb-web

---

bigbluebutton-config/bin/bbb-conf

Add description to `bbb-conf --check` of the new `bbb-web.properties` override file.
Use existing `HOST` variable for setting `public.kurento.wsUrl` in `settings.yml`.  This variable already takes into account the above override file.

Added text for override of bbb-web.properties

---

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx
bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/service.js
bigbluebutton-html5/private/locales/en.json

- Do not display `This action will end the session for X active user(s).` part of the `endMeetingDescription` message if no other participants are active.
- Changes active users counting so it ignores current user
closes #11585

Changes on end meeting message

---

bigbluebutton-html5/imports/startup/client/base.jsx

It is safer to look at subscription's state to users instead of depending
on the initial state of the collection at mounting time. Although
i couldn't force any race conditions on this, there's a chance it could
happen. The fix avoid this problem.
This complements #11533
Also added small complements based on #11568 suggestions

Improve the way we observe changes on Users's collection

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Using this information can be helpful when mounting or recovering breakout 
panel with correct audio transfer status.
We now track this state based also on current microphone state.
Fixes #11333  (see the following screen capture)

Improve the way store information about breakout audio transfer

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx

User may have incomplete session layout data if PR #11529 is applied, causing the error `Cannot read property 'width' of undefined`. 
This PR fixes it by checking if all required information is present.

Fixes incomplete session data error caused by PR #11529

---

akka-bbb-fsesl/build.sbt
akka-bbb-fsesl/src/debian/DEBIAN/postinst

This PR adds a post-install script to akka-bbb-fsesl that pulls the esl password from event_socket.conf.xml and installs it in the proper place in /etc/bigbluebutton/bbb-fsesl-akka.conf.
It also adds a dependency, to make akka-bbb-fsesl depend on bbb-freeswitch-core.  Not only does this make sense, but it ensures that bbb-freeswitch-core will get configured first, and its post-install script currently copies the esl password from an older event_socket.conf.xml into the new one (on an update).  So, configuring in this order makes everything upgrade properly.

Update fsesl password on package installation

---

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx

Fixes an issue where an invisible box would appear in front of the cameras if presentation is hidden, preventing the user from clicking on the video dropdown.

Fixes presentation invisible box appearing if presentation is hidden

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/ValidateAuthTokenRespMsgSender.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
akka-bbb-apps/src/test/scala/org/bigbluebutton/core2/testdata/TestDataGen.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala
bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js
bigbluebutton-html5/imports/api/users/server/methods/userLeftMeeting.js

This PR provides the backend logic required to support User logged out flow to prevent from rejoining by copy/paste url.  
closes # 11220  https://github.com/bigbluebutton/bigbluebutton/issues/11220
validateauthtoken now contains the reason, the ui should determine how to present it to user.

User logged out ValidateAuthToken retracted  

---

bigbluebutton-html5/imports/ui/components/media/component.jsx
bigbluebutton-html5/imports/ui/components/media/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Lift #11233 to 2.3.
- Add (fix) inbound/recvonly video stream reconnections
* Track all peer's connectionState and trigger a timed reconnect on `failed`
* Add a new unhealthy stream UI for when the stream is deemed to be unhealthy. The UI is applies a grayscale filter over the video-list-item which is deemed to be unhealthy and also shows the old connecting spinner.
* The baseTimeout - maxTimeout reconnection time cycle continues to exist. When an inbound feed gets into an unhealthy state, it'll try to reconnect indefinitely and each retry increases the reconnection interval up to maxTimeout.
- Fix Chromium-based browsers (>= M78) re-connection triggers
- Refactor the video streams <-> video elements attachment code
- Fix an issue where camera error toasts would be fired unnecessarily on …

video-provider: add inbound/recvonly video reconnection (was #11233)

---

bigbluebutton-html5/imports/ui/components/polling/component.jsx

Allows the user to press enter to submit response to a typed poll instead of clicking submit button.
closes #11578

Submit typed polling response by pressing enter

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx

The recent work on the echo test, especially b01246, created a visible change in my user experience.
I typically set autoJoin=true, listenOnlyMode=false, and skipCheck=true.  This causes my users to connect in to the conference with no modal dialog, just a "Connecting..." box that appears and then vanishes once the audio connection is established.
After b01246, they now get a modal dialog with a single option: "Microphone".
The current PR ensures that in this case, the dialog box is not presented at all and the user connects as before.
I was thinking about making a table of all the different audio join options and how the system is expected to respond in each case, but I decided to keep the PR short and simple.

don't prompt for "Microphone" if that's the only option presented to the user

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/private/config/settings.yml

Makes audio's peer connection `sdpSemantics` configurable via settings.yml.
Plan B phase out plan in Chrome:
```
M89 (Stable in February, 2021): Deprecation warning is added in the developer console.
M93 (Stable in August, 2021): Plan B is removed, with the option to extend this deadline by opting-in to a Reverse Origin Trial. More information about this option will be announced at a later date.
M96 (Stable in January, 2022): The extended deadline ends and Plan B is removed for everybody.
```
Our SDP usage in audio is dead simple. We don't need to care about P2P scenarios. Switching to Unified Plan should be a no brainer (we already use it with Firefox/Safari because that's the only thing they do and we aren't translating them to Plan B anymore).
That being said, we should field trial it …

audio: make sdpSemantics configurable

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx

Let the color of the color-picker icon be changed even when the text tool is selected
closes #11641 
I think the color of the color-picker and that of the annotation icon should always be the same to avoid confusion.
In the current implementation, both this.thicknessListIconRadius and this.thicknessListIconColor are null when the text tool is selected. So "if (this.thicknessListIconRadius && this.thicknessListIconColor)" never happens as long as the text tool is selected. I don't think it's the intended behaviour.
Anyway, this is what happens when this modification is applied:

Change the color of color-picker icon even when the text tool is selected

---

bigbluebutton-config/bin/apply-lib.sh

Catch the correct value for the parameter bigbluebutton.web.serverURL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties.
closes #...
In 2.3alpha8, the parameter bigbluebutton.web.serverURL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties can be overwritten by the same parameter in  /etc/bigbluebutton/bbb-web.properties, as far as I understand. However, the current implementation almost always change this parameter as "http://server", even though it's set "https://server", because grep bigbluebutton.web.serverURL /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties returns a lot of lines such as "defaultHTML5ClientUrl=${bigbluebutton.web.serverURL}/html5client/join". As a result, the sever makes a 401 error in my server. I guess this is happening in other …

correctly catch bigbluebutton.web.serverURL

---

bigbluebutton-html5/imports/ui/components/polling/component.jsx

Prevents the sending of a typed poll response by pressing enter if the response is empty.

Prevent sending typed poll empty response

---

bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/private/config/settings.yml

- New config called `public.kurento.paginationThresholds` defines classes of page sizes to be applied based on the number of participants in a meeting;
- The rationale is pretty much the same as the `cameraQualityThresholds`, but here thresholds are users and the ceilings are page sizes;
- Disabled by default. `public.kurento.paginationThresholds.enabled` is that flag that controls it;
- Don't need to define mobile/desktop entries for every threshold class. If one of those is not set, it'll fall back to the default page sizes from `public.kurento.pagination.desktop/mobilePageSizes`.
- The default page sizes (`public.kurento.pagination.desktop/mobilePageSizes`) will be applied when there's no threshold hit yet.
None
Pagination serves two purposes: 1) constraining client-side resource usage …

video-provider: add dynamic video page sizes based on number of users 

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Adds green microphone icon in video when user has joined audio and is not muted.
closes #11637

Show unmuted microphone in video

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml

1) Allows for meetings to override the `defaultKeepEvents` property (formerly `keepEvents` https://github.com/bigbluebutton/bigbluebutton/pull/6385 ) by passing `meetingKeepEvents=` `true` or `false`
2) I set `defaultKeepEvents` to false, which is reverting https://github.com/bigbluebutton/bigbluebutton/pull/10097 , cc @jfederico 
Note that `defaultKeepEvents` is only used in case `meetingKeepEvents` is not passed.
none
We would like to have finer control over which meetings' events are recorded. Until now you would either keep events from all or none of the meetings

Replaced keepEvents with defaultKeepEvents and meetingKeepEvents

---

record-and-playback/core/lib/recordandplayback/edl/audio.rb

This PR incorporates two changes related to audio sync issues:
1. An improvement to the way the ffmpeg filter chain is generated such that the cut points of the audio segments in the recording are calculated absolutely from the start of the meeting, instead of relative to the previous segment. This prevents accumulation of rounding errors from affecting audio synchronization. (That said, the way *video* is cut can still accumulate errors!)
2. Incorporate the audio sync fixes from #11626 - add the `aresample` filter with the async option to fill in timestamp gaps in the source audio, and prefer using the libopus decoder on opus input files. These changes were completely independent of the screenshare audio feature, and should be applied to all audio streams.

Recording: Audio processing changes to reduce audio desync

---

bigbluebutton-html5/public/compatibility/kurento-utils.js

-  html5, kurento-utils: update UAParser to v0.7.24 (was v0.7.17) 
-  html5, kurento-utils: update js.merge to v2.1.1 (was v1.2.0) 
Tested with:
- iOS Safari (13, 14)
- Latest Chrome, Firefox and Samsung Browser versions in Android (also latest)
- Latest Chrome, Firefox and Edge in Windows
- macOS Safari: latest version of Safari 12, 13 and 14.

kurento-utils: update UAParser and js.merge

---

record-and-playback/core/lib/recordandplayback/generators/presentation.rb

There isn't any known security issue here, since BigBlueButton is already generating internal filenames for slides, but adding an extra layer of protection to make sure there's no string escaping issues can't hurt.

Recording: Don't use string interpolation when generating commands for slide conversion

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/container.jsx

Relates with https://github.com/bigbluebutton/bigbluebutton/pull/11684
Adjusts the user interface to keep coherence when activating the multi-user
whiteboard while there is only the presenter in the meeting.
cc @hiroshisuga , what are your impressions?

Handle multi-user whiteboard for solo presenter

---

bigbluebutton-html5/imports/ui/components/app/styles.scss

Fixes an issue with the userlist height, by setting the component height to 100% of available height instead of 100% of viewport height.
closes #10850

Fix userlist height if banner is enabled

---

bigbluebutton-html5/imports/ui/components/video-provider/many-users-notify/container.jsx

Fixes crash that happens on an ejection if the ejected user has a webcam active.
closes #11680

Fix client crash when user is sharing video

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

Follow up to #11681
I am adding a getter for `defaultKeepEvents`
In some environments I see
```
2021-03-21T19:54:50.686-04:00 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meetingService' defined in class path resource [spring/resources.xml]: Cannot resolve reference to bean 'paramsProcessorUtil' while setting bean property 'paramsProcessorUtil'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'defaultKeepEvents' of bean class …
```

Add getter for defaultKeepEvents

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

Reverts bigbluebutton/bigbluebutton#11705
The issue was caused by old jars with incorrect permission. No need of this change, the setter suffices. The error message was referring to the old jar

Revert "Add getter for defaultKeepEvents"

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss

Increases userlist context menu width
closes #11702

Increasing userlist menu width

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx

The bug happened because the message queue to be processed wasn't cleared when the clear chat is triggered, thus being processed later and added to the context, causing the bug of having message before the clear message.
closes #11618

Fix messages being not cleared

---

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
bigbluebutton-html5/imports/ui/components/dropdown/styles.scss

- Increases presenter context menu width - desktop
- fixes presentation list width and alignment - mobile
- fixes "close" button z-index - mobile
closes #11701

Increasing presenter menu width

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/service.js
bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/public/locales/en.json

Moves the raise hand functionality to a button on the actions bar.
Provides a faster way for a user to raise their hand. Adding a button on the actions bar reduces the number of clicks needed to perform the action from 3 to 1. This will also allow for the addition of an `accesskey` shortcut.

Move Raise Hand Functionality To Actions Bar Button

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx

Wait for userId to be available before trying to get pre-join messages of current meeting.
closes #11674

Retrieve guest user pre-join messages only when userId is available

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/private/config/settings.yml

This sets back the default value after fixes done in #11272 and #11268
This PR also fixes #11433

Default enable banner alert when user speaks with mic muted

---

bigbluebutton-html5/imports/api/auth-token-validation/server/modifiers/upsertValidationState.js
bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
bigbluebutton-html5/imports/ui/services/auth/index.js

Prevent user that logged out to spam validateAuthToken when trying to join using the previous session token.
In 2.2 we had a verification that didn't allowed logged out users to join again using their last session token, since 2.3 we started to remove offline users from collection, because of that we couldn't check if the user has logged out. Changes made in #11607 made it possible to identify those users.

Prevent logged out user to spam validateAuthToken

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/AbstractPadRecordEvent.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/AddPadRecordEvent.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js
bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
bigbluebutton-html5/imports/api/note/server/helpers.js
bigbluebutton-html5/imports/api/note/server/methods/createNote.js
bigbluebutton-html5/imports/startup/server/etherpad.js
bigbluebutton-html5/imports/startup/server/redis.js
record-and-playback/core/lib/recordandplayback.rb
record-and-playback/core/lib/recordandplayback/generators/events.rb
record-and-playback/core/scripts/archive/archive.rb
record-and-playback/core/scripts/bigbluebutton.yml

Since Meteor was split in multiple process and events started to be
filtered by instances, all Etherpad's Redis events were being discarded.
Etherpad has a Redis' publisher plugin that is unaware of BigBlueButton's
existence. All the communication between them is kept simple with minimal
of internal data exchange. The concept of distincts subscribers at Meteor's
side broke part of this simplicity and, now, Etherpad has to know which
instance must receive it's messages. To provide such information I decided
to include Meteor's instance as part of the pad's id. Should look like:
- [instanceId]padId for the shared notes
- [instanceId]padId_cc_(locale) for the closed captions
With those changes the pad id generation made at the recording scripts had to
be re-done because there is no instance …

Handle pad's events and Meteor's instances

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx

Reconnection was not being detected in Firefox, this PR adds the connectionID on useState hook 
Single user:
https://user-images.githubusercontent.com/15806883/112214470-ffd3f600-8bfd-11eb-98d4-acb02d1a8bba.mp4
multi user:
https://user-images.githubusercontent.com/15806883/112214768-593c2500-8bfe-11eb-9622-8243cb60e781.mp4

Fix reactive issue with reconnection

---

bigbluebutton-html5/private/config/settings.yml

Change full audio's default SDP format to Unified Plan. Making the default transition a bit earlier so that we can field trial it and be sure it's safe enough.
Rationale in https://github.com/bigbluebutton/bigbluebutton/pull/11631.
None.
https://github.com/bigbluebutton/bigbluebutton/pull/11631

audio: change default SDP format to Unified Plan

---

bigbluebutton-html5/imports/ui/components/screenshare/service.js

Add a check after gDM resolves (getDisplayMedia, screen sharing)  to see whether the user is still the presenter; if they aren`t, just clean up the gDM stream and do nothing.
None.
getDisplayMedia's promise cannot be aborted.
If the presenter gets changed while the user kept the getDisplayMedia browser picker open, accepting the getDisplayMedia prompt might get the previous presenter´s client-side state inconsistent as if they were sharing. Although screen sharing is a no-op in that scenario, the client side state should be preserved.

screenshare: check if the user is still presenter after gDM resolves

---

bigbluebutton-html5/private/config/settings.yml

Initially enabled was `false`, waiting for the recording portion of the work to be completed. That was finished in #11626
As of time of writing screenshare with audio is only supported when sharing a *tab* via Chromium based browsers

Enabled by default screenshare with audio (#11622)

---

record-and-playback/core/lib/recordandplayback/edl/audio.rb

Fixes a crash: ``undefined method `[]' for nil:NilClass``
that happens in the log output statements when a corrupt audio file is hit.

Don't print audio info for corrupt audio files

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx

This small PR makes sure that the drag and drop input field is not displayed when typed response poll is chosen.
closes #11740
When typed response poll is chosen during the poll creation, it doesn't make sense to display the drag and drop functionality, since presenter doesn't specify the responses.

Remove the drag and drop input field for typed responses polls

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx

Reduces the audio modal heading from `h3` to `h2` in order to be more semantically correct.
fixes:

Reduce Audio Modal Heading To H2

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx

remove `role="complementary"` from `UserContent`
Fixes:

Remove complementary role from user content

---

bigbluebutton-html5/imports/ui/components/app/styles.scss

Removes the gradients being applied to the contents background.
Fixes accessibility contrast issues.
before:
after:
The remaining item is related to the user avatar and all the pseudo elements surrounding it. I've verified the avatars all fall within the accepted AA requirement for their randomly selected background colors. https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js#L14.

Remove gradient from content styling

---

record-and-playback/core/lib/recordandplayback/edl/audio.rb

Screenshare input files have video+audio so the scripts were trying to process video and the default codec theora is not in the bbb ffmpeg package, which lead to error 
`Automatic encoder selection failed for output stream #0:1. Default encoder for format ogg (codec theora) is probably disabled. Please choose an encoder manually.`
Fix #11746

Recording: Ignore video in audio processing scripts

---

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addBulkGroupChatMsgs.js
bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js
bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/syncMeetingChatMsgs.js
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

This PR is a follow up for PR #11722, this PR removes the properties `sender.name` and `color` from the message payload because with the new collection we don't need this information in the message anymore.
Clearing the chat and sending private message:
https://user-images.githubusercontent.com/15806883/112378152-5821fb00-8cc5-11eb-83fb-6822fa69569a.mp4
Moderator message:

Remove `sender.name` and `color` from message payload

---

bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js
bigbluebutton-html5/imports/api/users-persistent-data/index.js
bigbluebutton-html5/imports/api/users-persistent-data/server/index.js
bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/addUserPersistentData.js
bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/clearUsersPersistentData.js
bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/setOnlineStatus.js
bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/setloggedOutStatus.js
bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js
bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
bigbluebutton-html5/server/main.js

This PR implements a new collection named `users-persistent-data` with information that we want to keep available to client even for disconnected users: `userId, extId, meetingId, name, role, token, avatar, guest, color, loggedOut`.
This collection is loaded after the initial data synchronization ( after client is usable ), and before the chat history synchronization.
Closes #11081

Add collection user persistent data

---

bigbluebutton-config/cron.hourly/bbb-restart-kms

The `connectionStatus` property was removed from the Users collection in 2.3, so the check was always returning 0 which means the cron job could potentially restart KMS and SFU while there were still active users.
This PR removes the deprecated filter. Since the collection in 2.3 doesn't store offline users anymore, this should be good enough.
Closes  #11418

bbb-config, packaging: prevent cron job from restarting KMS unnecessarily

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

In the poll published results in the presentation canvas, there is an issue for RTL languages that caused to show reverse results label for True/False or Yes/No or even custom polls.
There is a reported issue for `tspan` tag in[chromium]( https://bugs.chromium.org/p/chromium/issues/detail?id=360176) and it can fix with 
closes #9273

Fix for poll result in RTL languages

---

bigbluebutton-html5/public/compatibility/kurento-utils.js

Removes a barrier in kurento-utils (which I added a few years ago) that only released SDP offers from Safari endpoints when the ICE gathering state transitioned to `complete`.
Affected components: video, screen sharing, listen only.
None
This basically stemmed from a discussion I had with @rasos in https://github.com/bigbluebutton/bigbluebutton/issues/10746.
After analyzing some info, I tripped upon this beautiful chunk of code when I was investigating that issue.
Back when Safari 11 was still a thing, there was this _annoying_ bug where peer connections COULD get stuck during it's startup phase if, due to some unknown trigger, the SDP was generated BEFORE the ICE candidate gathering had run its course.
To work around that, the SDP generation was put behind a barrier that was opened when …

video,screeshare,listenonly: remove Safari gathering barrier for SDP offer generation

---

bigbluebutton-html5/private/config/settings.yml

Bump base and max screen sharing _negotiation_ timeouts to 30s/60s to follow the values we currently use for cameras.
None.
I actually forgot to bump those in #11622. They were supposed to be the same as the camera's timeouts (30/60), but I accidentally left the old values (15/35) in place.

screenshare: bump base/max timeouts to 30s/60s

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java

This is a backport of #11750
This PR reduces the impact of #8618 by increasing hardcoded timeout from 7s to 60s

Quick fix to avoid empty slides ( 2.2 backport )

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss

prevents the left and center actions bar buttons from being overlapped by the right side (raise hand / restore presentation)
Closes #11733

Fix actions bar buttons overlapped by right side

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Included a message and a redirect for the cases where the guest is
not allowed to join or the meeting has expired/ended.
This refactors the `guestWait` API call to include more details on errors
responses and gives an extra responsiveness to the guest lobby page.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/11782

Improve guest lobby feedback

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss

Makes the video dropdown use all available space in mobile (ignoring video size).
Closes #7597

Mobile video dropdown size

---

bigbluebutton-html5/private/config/settings.yml

Packaging already replaces `url: ETHERPAD_HOST` so it should be safe to have `note:enabled: true`
Enabled by default Shared notes in BBB 2.3

Enabled by default Shared notes in 2.3

---

bigbluebutton-web/grails-app/conf/spring/resources.groovy
bigbluebutton-web/grails-app/conf/spring/resources.xml

This adds a config overlay for the turn/stun server config of bbb-web:
If `/etc/bigbluebutton/turn-stun-servers.xml` exists/is readable bbb-web now uses this config file.
If `/etc/bigbluebutton/turn-stun-servers.xml` is missing/not readable the default configuration file `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` is used. Which configuration file is used is being logged to `bbb-web.log`.
With the new config overlay options in `/etc/bigbluebutton` it is possible to deploy a BBB server without touching any of the packaged config files with one exception: turn/stun server configuration. This PR closes this last gap.
This is in a way a follow up PR of #11470 by @schrd
Tested on my dev environment: BBB 2.3-beta1, worked without problems so far
Add documentation
Idea for …

Config overlay for bbb-web turn server config

---

bigbluebutton-html5/imports/ui/components/user-list/service.js

The option `allowModsToUnmuteUsers=true` doesn't work anymore due to a change in PR #11215 by @pedrobmarin (as far as I could see): commit bd15f14ca01bb362843bb2f75146276acd4ba65b
https://github.com/bigbluebutton/bigbluebutton/blob/bd15f14ca01bb362843bb2f75146276acd4ba65b/bigbluebutton-html5/imports/ui/components/user-list/service.js#L362
Closes #11820
I've been using this option in 2.2 and now tried it in 2.3-beta1. Figured out it's not working, wanted to make it work again.
I couldn't figure out if this bug was introduced by the attempt of a bigger refactoring (userProps) and parts of it have been forgotten to implement. This PR is just a quick fix for it. If a bigger refactoring was intended feel free to drop this PR, of course, and fix the issue in the PR which does the refactoring. …

Fix: making allowModsToUnmuteUsers=true work again

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx

We now stop the MediaStream (cloned/dummy input stream) when this is not
needed anymore.
We don't create/clone a new MediaStream when it already exists.
Fixed eslint warning in muted-alert/component.jsx
When listen only fallbacks from Kurento to FreeSWITCH, we must guarantee
the muted alert won't be created, speciallly because listen-only's fallback
uses a flow similar to microphone's. Client currently crashes when this
happens: this commit fixes this peoblem.

Improvements in muted banner

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/audio/container.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Firefox doesn't create a  device called 'default' and we were trying
to set this when user is joining the room. We don't do this anymore, letting
devices to be changed when there's some user request.
Moved outputDeviceId inputDeviceId information to be managed in bridge
(just like we do with inputDeviceId), we don't store this duplicated
information in audio container anymore.
Fixed the eslint warning in "playAlertSound(url) { ..."
We are safe to let users try to change input/output devices because the
device list is retrieved from enumerateDevices.

fix: MEDIA_ERROR when joining room using Firefox

---

bigbluebutton-html5/private/config/settings.yml

With defaults of 2 backend and 2 frontend bbb-html5 nodejs processes we can handle more breakouts. @ritzalam confirmed no audio changes are needed

Set breakoutRoomLimit to 16

---

bigbluebutton-html5/imports/api/common/server/etherpad.js

Etherpad has a limitation of 50 characters for it's pad ids. Although
our SHA1 hash function generates 40 characters length values, after
prefixing (Meteor's instance id) and suffixing (closed captions support)
the pad id we can reach an invalid size.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/11862

Reduce pad's hash size

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

When browser's name string has whitespaces, we must treat it before adding to the
body class. For example Edge uses 'microsoft edge' string
This class string must match names used in css.
Tested in firefox, chrome and safari and it's corresponding mobile versions,
this is working for all.
Fixes #11865

fix: User can't join using microsoft edge

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
bigbluebutton-html5/imports/ui/components/video-preview/component.jsx

This was being shown in both audio in video modal.
Related to #11865.

fix: Do not show unsupported browser warning for microsoft edge

---

.github/ISSUE_TEMPLATE/core-issue.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/html5-issue.md
.github/ISSUE_TEMPLATE/installation-issue.md
.github/ISSUE_TEMPLATE/recording-issue.md
.github/workflows/check-merge-conflict.yml

Replaces the previous label format with the new one.
Finding labels and trying to understand their usage was getting complicated. I decided to set prefixed topics to gather labels by groups and build a better indicative on how to compose them.
e.g.:
- an `enhancement` can target `robustness` of the `whiteboard` component in the `client`;
- a `bug` related to a `performance` issue can be identified at `core`'s `polling` handler; or
- a `recording` `refactor` can improve the `stability` of the `chat` events processing.

Set new labels to templates and workflows

---

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss

Fixes an issue where actionbar buttons and chat/userlist panel would appear over settings modal on mobile devices, by adding z-index CSS for settings modal component.
Closes #11833
Closes #11834

Fix settings modal z-index

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/handlers/AbstractCommandHandler.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/Office2PdfPageConverter.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml

This PR include some improvements for previous PR #11750
- Includes config `svgConversionTimeout` to let user set the timeout for PDF to SVG conversion
- Handle timeout errors and log in console (in Pdf2Svg and Office2Pdf)
It was necessary to set `process.waitFor` with timeout + 1 second. It will guarantee that the command timeout will exceed first and return the code 124 while Java is still waiting.

Make timeout configurable and log timeout errors for conversions (Pdf2Svg and Office2Pdf)

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss

Unset the width of confirm button of presentation uploader.
Closes #
With non-English languages. sometime the button labelling is broken.
With this change the button seems to be OK on mobile devices.
Screenshot of a PC (before the change)

Minimum width of confirm button

---

akka-bbb-apps/run-dev.sh
akka-bbb-apps/run.sh
akka-bbb-fsesl/run-dev.sh
akka-bbb-fsesl/run.sh
bbb-lti/docker-entrypoint.sh
bbb-lti/run.sh
bigbluebutton-html5/docker-entrypoint.sh
bigbluebutton-web/docker-entrypoint.sh
bigbluebutton-web/pres-checker/run.sh
bigbluebutton-web/run-prod.sh
bigbluebutton-web/run.sh

The starting scripts now `exec` the main service instead of starting
it as a subprocess. Also in line with docker-entrypoint recommendations.
Replaces #9216 (there does not seem to be a way to update a PR when the origin fork has been deleted)

Services run as starting PID

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx

This PR fixes the issue of the chat indicator doesn't disapearing, it is caused because the condition only works for messages smaller than the screen.
Closes #11617

Fix unread message indicator remaining visible

---

bigbluebutton-config/bin/bbb-conf

This is the same fix that was made in bbb-install: https://github.com/bigbluebutton/bbb-install/pull/327/
Fix https://github.com/bigbluebutton/bigbluebutton/issues/11452
If there are multiple default routes on a system, we only care for the first one.
Closes #11452
Just fixing my own issue here and hope it's useful for others.

Handle multiple default routes in bbb-conf

---

bigbluebutton-html5/imports/ui/components/app/styles.scss

Fix an issue where the action button would appear over the userlist panel and dropdown, by changing userlist z-index value.
Closes #11903

Fix action button appearing over userlist and dropdown

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx

This PR improves the UX of the in #11703 newly introduced hand raised button so it reflects the current hand raised state.
Closes #11772
Improving the UX of the newly introduced great feature of the hand raise button
I transferred the styling code of the webcam share button to the hand raise button code. Works flawlessly in my dev environment.
Maybe we should still have a look at the focusing state of the button (because it keeps the focus when clicking on it). I didn't touch that because I'm not sure if this would influence the accessibility in a bad way. The other buttons don't have this "problem" because they all open up a new window which requests focus, so the buttons lose the focus as far as I understand it.

Hand raise button now reflects hand raised state

---

bigbluebutton-html5/private/config/settings.yml

Removes settings.yml block for `memoryMonitoring`
`heapdump` and `memwatch` were removed in https://github.com/bigbluebutton/bigbluebutton/pull/8390 as they we not supported in Node12
I did not find any code in the repo using these properties.

Removed memoryMonitoring from settings.yml

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx

Remove a duplicate event listener that was causing the keyboard navigation to skip users in the userlist
Closes #11839

Fix Keyboard Navigation Skipping Users In Userlist

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx

Alternative to #11908 based on feedback from @antobinary:
> Would it be an option to not show the 'real' font size in the button if larger than 32?
> 28 - show 28
> 32 - show 32
> 36 - **show 32**
Closes #7426

Do not show real font-size in whiteboard text tool button

---

bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/setloggedOutStatus.js
bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/updateRole.js
bigbluebutton-html5/imports/api/users/server/modifiers/changeRole.js
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

Made these modifications to handle a problem that role change was dropping users-persistent-data subscriber and not putting it back up again.
There is some points here that I would like to register though. While trying to understand why there was this issue on role change I got at this problem https://github.com/bigbluebutton/bigbluebutton/issues/9733 . As I could understand, since then some collections depend on the user role to control access but this seem to be forcing all the collections to resubscribe when the role changes. 
**IMPORTANT**: although this solves a problem, I'm not sure if it isn't adding something @Tainan404 was trying to avoid. So I recommend him to take a good look and propose anything different if needed.

Update users persistent data

---

bigbluebutton-html5/imports/ui/stylesheets/mixins/_indicators.scss
bigbluebutton-html5/imports/ui/stylesheets/variables/general.scss

Removes user icon styles that are specific for Microsoft Edge browser.
Closes #11898

Fix user icons alignment for Microsoft Edge browser

---

bigbluebutton-config/bin/bbb-conf

Since #11804 (already live in beta2) an overlay config for `turn-stun-servers.xml` in `/etc/bigbluebutton` is possible. This PR makes `bbb-conf` consider this case:
Take `/etc/bigbluebutton/turn-stun-servers.xml` for reading stun server if it exists. Default config file `/usr/share/bbb-conf/WEB-INF/classes/spring/turn-stun-servers.xml` is only considered if `/etc/bigbluebutton/turn-stun-servers.xml` doesn't exist.
Closes #11929
As I were the one sending in the PR for the overlay config I see it as my duty to fix this follow up issue ;-)
In PR #11804 there is no merging between config files: If the overlay config file exists, it replaces the default config file as a whole, so for this PR it's sufficient to just check if the overlay config file exists and replace the corresponding config …

Consider /etc/bigbluebutton/turn-stun-servers.xml overlay config file in bbb-conf

---

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/container.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss

Removes RecordingIndicator component text from mobile (phones only) view.
Closes #7934
Closes #11816

Remove recording button text on phones

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

IOS keyboards are triggered by the text area's 
Closes #11647

Fix Text Area's Not Opening IOS Virtual Keyboard

---

bigbluebutton-html5/imports/ui/components/muted-alert/styles.scss

fix: when muted alert is active, can't click on 'Leave audio'

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx
bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

Removes unused variables from chat-related files reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

Remove unused chat-related variables

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx

Moves `key` attribute in the poll component from `div` to `span`
This will remove the warning that appears while creating a new poll, after setting a response type.

Fix new poll key warning

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

This PR changes the order of the presentation lists both in the action bar dropdown menu and the presentation uploader.
Closes #11917
Inspired by the use case of having many presentations with similar names (numbered), for example when wanting to show many pictures which are numbered as a presentation. See also use case mentioned in #11916.
In action bar dropdown presentations are now sorted alphabetically by name.
In presentation uploader it's a bit more "complicated":
First of all, **CARE: This PR changes the current behavior of showing presentations ordered by their upload timestamp**
New order:
- Presentations are generally sorted alphabetically
- Presentations with identical name are sorted like it was before (latest one bottom)
- Newly added (not yet uploaded) presentations are …

Update order of presentation lists

---

bigbluebutton-html5/imports/ui/components/audio/audio-dial/component.jsx

Formats a 9 digit PIN number to make it easier to read.
Closes #11935

Formatting of PIN number within client

---

bigbluebutton-html5/imports/ui/components/whiteboard/service.js

Whiteboard service wasn't considering the current presentation id when
fetching for the current whiteboard id. Calls were always returning
the id of the first slide available. This was effecting the state of the
whiteboard access feedback at the users' list.
Closes #11988

fix: whiteboard access for multiple presentations

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx

Fixes the problem that locking public chat also locks private chat and locking private chat also locks public chat.
Closes #11986
I really want to go productive with 2.3-beta as soon as possible :-)
I'm not super deep into the whole chat implementation, so I'm not 100% sure about the PUBLIC_CHAT_KEY comparison to differ public from private chats, but it worked in my dev environment, so... :-)

Fix private public chat lock interference

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Prevents a crash that would happen if there's an active poll and the user refreshes the page without voting
Closes #11968

Fix active poll refresh crash

---

bigbluebutton-html5/imports/ui/components/polling/styles.scss

Removes `max-width` styles from polling container
Closes #11999

Remove max-width from polling options container

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx

This PR makes sure that the number of poll options is in sync with what's drag-and-dropped.
Closes #11741

Syncing the length of poll options list with the drag and drop input

---

bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx

Prevents a layout bug affecting poll, closed captions and waiting list panels by setting correct width value on resizing.
Closes #11975
Closes #11946

Fix panel resizing for poll, cc and waiting list

---

bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
bigbluebutton-html5/imports/ui/services/auth/index.js

Removes unused imports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

Removing unused imports

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy

It is a complement for PR #11956
After the previous PR, the Nginx expects to receive error code 403 as response for auth_request error (/presentations).
This change is necessary and was missing.

Makes bbb-web return error code 403 when uploaded file exceeds limit

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js

- Fixes *Avoid alerting messages received before enabling alerts* on chat alerts (PR #11992)
- Removes unused `chatService` code

Fix previous messages chat alerts and remove unused code

---

record-and-playback/core/lib/recordandplayback/generators/events.rb

This function is useful any place you want the matched recording marks
with timestamps rebased so 0 is the start of the meeting, I've used it
for chat analysis, for example.
There is no functional change here, it only exposes the extra function
for recording scripts or dropin/post scripts to use.

Split the EDL recording marks generation out to a helper function

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx

PR #11989 wasn't completely doing what it was supposed to do:
If private chat lock was enabled attendees couldn't open private chats with mods anymore (which is the current behavior in 2.2 and IMO also the intended behavior).
This PR fixes that problem.
Follow up PR on #11989, an issue wasn't opened.
Problem was mentioned by @GyR4uk: https://github.com/bigbluebutton/bigbluebutton/pull/11989#issuecomment-818247917
Thank you for that!
Correcting my incomplete PR.
As information about the conversation partner is needed to differ private chat with attendees from private chat with mods my idea of solving this was to move the implementation of the isChatLocked property into the ChatContainer. Therefore I had to split up the property in the lockContextContainer. If there is a better option, …

Fix: Allow open private chats with mods if private chats are disabled

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
bigbluebutton-html5/public/locales/en.json

Adds property "app.notes.locked" to locales file and use it for shared notes locked status.
Closes #9538

Dedicated locales property for shared notes locked text

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx

Increases chat panel min/max width to match poll panel size.
When I was working on #12039, I tried to find out why is the minimum chat panel width so small and could not find a reason (these values are desktop/tablets only - phone users will always have 100% width panels). 
With this PR the chat values are increased to the same values we already have in polling creation panel.
The current minimum value is so small that you can't even read the user name at this size:

Increase chat min/max width values

---

bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js

Adds bars to chat poll results.
Closes #12039

Add bars to chat poll results

---

bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Fixes an issue where the user could not join video in breakout room after audio auto-joining 
Before joining video, `audioModalIsOpen` value [is checked](https://github.com/bigbluebutton/bigbluebutton/blob/32dec42264b501e92bb70bc6dae677fceeec225e/bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx#L497-L498)... but if you auto-join audio, `audioModalIsOpen` was never set to false
Closes #11985

Fix join webcam breakout room

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

Stops random user modal from triggering in every update of the component (and only appearing when the Select Random User feature is used)
Closes #11985

Fix random user modal

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx

This is a regression fix of PR  #12034 causing private chats to moderators being locked when private chat lock is enabled.
While investigating I found out that the PR also broke the locking of private chats when users were ejected or left the meeting. Fixed this as well.
Closes #12073
End of april is coming... :-)

Fix regression: Unintentional locking of private chat with moderator, chat lock on left/ejected user not triggered

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx

This PR adds the ability to manage assigning users to breakout rooms via the keyboard only. 
Previously there was no way to assign users to breakout rooms without a mouse or using the random assign option.

Make Breakout Rooms User Assignment Keyboard Accessible

---

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx

This PR solves 2 problems with the interactions between screen readers and the tethered dropdown menus. 
- Allows screen readers access to tethered dropdown menu content.
- Reduces the amount of navigation needed to reach the menu content. 
Previously, screen readers did not have access to tethered dropdown menu content. This was due to the screen-reader-trap restricting the screen reader to the dropdown menu which was an element containing the menu trigger and content. With the addition of the tethered dropdown the content was moved out of the menu and attached to the body of the document. The new placement of the content in the DOM also included extra navigation for screen readers to get to the menu content, this was an attempt to reduce / improve that..

Fix Screen Reader Access To Tethered Dropdown Menu's

---

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx

- Adds a timeout to the userRemove handler, preventing the user from being redirected to the wrong component in ejection
- Changes `meetingEnded` component logs to display a different message if the user was removed
After a long discussion with @Tainan404 and @jfsiebel about PR #12052 we decided to try another solution, as the real problem is that we have 2 event happening when the user is removed from a meeting: one for `userEjected` and one for `removeUser`... And they happen almost at the same time.
This behavior often makes `User.remove` (from removeUser) cancel `User.update` (from userEjected), displaying the wrong component to the removed user (`ErrorScreen` instead of `MeetingEnded`).
This new solution is a workaround to stop this wrong behavior from happening. 
We think a *better* …

Add delay to userRemove

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml

This PR will solve #11651. The Png was being generated with poor quality because it was using resolution 150 ppi. Now it will be possible to set a higher quality (and by default will be better).
- Creates `svgPresentationResolutionPpi` config in `bigbluebutton.properties`
- Set default `svgPresentationResolutionPpi = 300` (before it was using 150 when needed to convert to png)

Makes presentation svg resolution configurable, and improve default quality

---

bigbluebutton-html5/imports/api/captions/server/methods/addCaptionsPads.js
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/captions/pad/service.js
bigbluebutton-html5/imports/ui/components/presentation/cursor/cursor-wrapper-container/service.js

Removes unused imports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

Remove unused imports

---

bigbluebutton-html5/imports/ui/components/settings/component.jsx

Updates the `lang` attribute on `html` when the client's locale changes.
Closes #12092

Update Language On Html After Locale Change

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/AudioFloorChangedVoiceConfEvtMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp2x.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/FreeswitchConferenceEventListener.java
akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/IVoiceConferenceService.java
akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/events/AudioFloorChangedEvent.java
akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java
akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/VoiceConferenceService.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
bbb-fsesl-client/src/main/java/org/freeswitch/esl/client/inbound/Client.java
bigbluebutton-html5/imports/api/video-streams/server/eventHandlers.js
bigbluebutton-html5/imports/api/video-streams/server/handlers/floorChanged.js
bigbluebutton-html5/imports/api/video-streams/server/modifiers/floorChanged.js
bigbluebutton-html5/imports/api/video-streams/server/modifiers/sharedWebcam.js
bigbluebutton-html5/imports/api/voice-users/server/eventHandlers.js
bigbluebutton-html5/imports/api/voice-users/server/handlers/floorChanged.js
bigbluebutton-html5/imports/api/voice-users/server/modifiers/updateVoiceUser.js
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js
bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx
bigbluebutton-html5/private/config/settings.yml

- Added stream sorting based on voice activity (voice switching, last N, paginated last N, call it what you want)
* Works with or without pagination enabled, transparently
* Based on video **floor** heuristics from FS with configurable transition timers (based on number of audio frames) rather than the trigger happy _talking_ events from FS
- Made video stream sorting extensible and configurable
* The sorting modes for when pagination is enabled or disabled can be configured in settings.yml
* New sorting modes can be added to the stream sorting util under video-provider. Inline docs explain how to do that.
* Different sorting modes can be set when pagination is toggled on or off
- Changed how the stream ID attribute from the video-streams collection was passed to downstream components
* …

video: voice activity video sorting

---

bigbluebutton-html5/.eslintrc.js
bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

This commit contains three fixes: one already reported and two detected
during the investigation of the solution.
This started as a fix for firefox (#12023), but i also fixed the muted
alert/banner when device changes: the banner wasn't detecting device changes,
unless audio was deactived/actived.
There's another fix for the microphone stream: we now keep sender's track
disabled if it was already disabled for the sender's track of the previous
selected device.
Also did small refactor for eslint checking.
Some technical information: in sip bridge (bridge/sip.js), setInputStream and
liveChangeInputDevice function were both fully turned into promises, which
guarantees we have everything ready when it resolves to the respective values.
This helps AudioManager (audio-manager/index.js) to …

fix: mic selection (firefox/all browsers) and muted alert when mic is changed

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/container.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js
bigbluebutton-html5/imports/ui/components/audio/container.jsx

When joining/returning breakouts, audio would always connect
with full audio. This can lead to a performance problem, once
all listenonly users would join full audio, increasing the
number of streams in FreeSWITCH.
We now have a consistent behavior, which is:
1 - The choice made by the user in the main room is predominant:
if mic is active in main room, user will automatically
join mic in breakout room. When returning from breakout
room, user will also join with mic again.
2 - Changes made in breakout room won't have effect when
returning to the main room. This means if user, for example,
change from listenonly to mic in breakout room, the returning
will consider the option choosen previously (listenonly) and
listenonly will be active again in the main room.
3 - If user didn't join audio …

fix: breakout autojoin audio with wrong behavior

---

bigbluebutton-html5/imports/ui/components/button/styles.scss

adds `outline-offset` to buttons being clipped in Firefox by focus outline. 
Closes #11970

Fix Focus Outline Clipping Buttons In Firefox

---

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx

Removes duplicated property `data-test` from nav-bar button.

Remove duplicated property from nav-bar button

---

bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx
bigbluebutton-html5/public/locales/en.json

Makes hand raised notification message differentiate between one and multiple users.
no separate issue opened: Label showed "USERNAME has raised **_their_** hand", even if just one user was raising **_his/her_** hand.
annoyed me, fixed it

Makes hand raised message differentiate between one and multiple users

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/container.jsx
bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

Removes unused imports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

Remove unused imports/variables

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

This PR fixes the client crash when theres several chats with unread messages, the issue is in subscription being redone and clearing the steam messages, but not the id in the unread message Set, therefore, keeping a non-existent timeWindowId in unread messages Set.
Closes #12093

Fix client crashing with multiple private chats

---

bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss

Longer usernames or longer button names of accept and reject (in other languages) make the buttons disappear to the back.
Issue on: https://test23.bigbluebutton.org/ 
tested with Chrome

Make waiting users more responsiv

---

bigbluebutton-html5/private/config/settings.yml

Set `paginationSorting` to VOICE_ACTIVITY_LOCAL by default (audio floors -> alphabetical -> local stream[always shown]).
None
Rationale: a more sensible default mode for pagination that actually works a bit better for the end user than
the previous mode (presenter -> alphabetical). 
Should reduce the need for page switching by focusing on the ones that are actually active in the conference.
_Presenters are no longer pinned to first in line_.
Follow up to #12004

feat(video): set audio floor sorting as default for pagination

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx

Prevents viewers from play/stop external videos.
Closes #11708

Stop viewer play/stop actions on external videos

---

bigbluebutton-html5/imports/startup/client/base.jsx

Removed the reference for invalidateCookie, since it doesn't exist anymore.

fix: client may crash when loading develop version

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/styles.scss

Changes new poll buttons CSS:
- true/false and A/B/C/D buttons will now adapt to text size
- Add item button will now have 100% width
Closes #12117

Fix new poll button sizes

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

Fix size of poll results annotation when there are duplicated answers.
Closes #12085

Resize duplicated poll results annotation

---

bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/button/styles.scss
bigbluebutton-html5/imports/ui/components/connection-status/icon/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/icon/styles.scss
bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss
bigbluebutton-html5/imports/ui/components/connection-status/service.js

Replace previous icon with a flexible version to fit inside other
nodes (e.g: buttons).

style(connection status): replace icons

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml

This PR will solve #8835 (Presentation have low quality when converting LaTeX-PDF to SVG).
And will reduce impact of #12087 (default resolution ppi as 300 can generate too large files for slides)
It implements to new configs:
- **forceRasterizeSlides**: Force conversion of slides to PNG before converting to SVG
- **pngWidthRasterizedSlides**: Presentation will be resized to this width (in pixels) when rasterizing (converting to PNG). By default will be set 2048px (this width keep presentation with good quality and it is not heavy for the browser to render).
**forceRasterizeSlides** motivation:
If the PDF->SVG conversion is generating bad quality SVGs, the user will have an option to force the conversion to PNG first! And as image the presentation will have better quality. …

Implements forceRasterizeSlides and pngWidthRasterizedSlides

---

bigbluebutton-config/bin/apply-lib.sh

set `TasksMax=infinity` if enableMultipleKurentos is used.
Closes #12154
`TasksMax=infinity` is used for a single Kurento environment too.

fix(bbb-conf): add TasksMax=infinity to Kurento's unit files

---

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addSystemMsg.js

Prevents client crash when sending poll results popup alert by removing sender object from message.
Closes #12149

fix: Remove sender object from message payload in poll result

---

bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx

Removes user-list unused code reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

refactor: Remove user-list unused code

---

bigbluebutton-html5/imports/api/connection-status/server/methods/addConnectionStatus.js
bigbluebutton-html5/imports/api/connection-status/server/modifiers/updateConnectionStatus.js
bigbluebutton-html5/private/config/settings.yml

Makes connection status logs a bit easier to parse
Enables connection status logging by default
Continuation from #12139
```
I20210426-21:15:02.670(0)? info: Connection status updated: meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1619467657473 userId=w_xn9xolkepaoo status=danger type=socket rtt=1000
I20210426-21:15:05.373(0)? info: Connection status updated: meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1619467657473 userId=w_xn9xolkepaoo status=critical type=socket rtt=2000
I20210426-21:06:42.955(0)? verbose: Updated connection status meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1619467657473 userId=w_xn9xolkepaoo level=warning
I20210426-21:06:50.141(0)? info: Connection status updated: meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1619467657473 …
```

chore(connection status): Connection status logs enhancement

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

Fixes a bug where poll results could appear as unread messages and not be displayed in chat, by preventing the grouping of system messages.
Closes #12160

fix(chat): no grouping for system messages

---

bbb-libreoffice/assets/convert-local.sh
bbb-libreoffice/assets/convert-remote.sh

Minor enhancements in Libreoffice conversion scripts as suggested by @uka-support in https://github.com/bigbluebutton/bigbluebutton/issues/12066#issuecomment-823306145.
Changes:
- Uses quotes to get parameters variable instead of brackets 
> Rationale: curly brackets are not required there (quote from manual: _"The braces are required when parameter is a positional parameter with more than one digit, or when parameter is followed by a character that is not to be interpreted as part of its name."_), but quotes should be used to protect against spaces in the file names.

Minor enhancement in Libreoffice conversion scripts

---

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/service.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js
bigbluebutton-html5/private/config/settings.yml

Add screen sharing bitrate configuration to bbb-html5's settings.yml.
New config: `public.kurento.screenshare.bitrate`.
None.
Make it easier to configure screen sharing bitrate/bandwidth usage.
Camera bitrates are already configurable in bbb-html5, which is good because it's easier than dealing directly with bbb-webrtc-sfu. Just doing the same to screen sharing (with the same mechanisms).
* would be good to add this to the docs after it is tagged

feat(screenshare): add screen bitrate config in bbb-html5

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx

Prevents system message clipping, by recomputing heights multiple times when switching between public and private chats.
Closes #12130

fix(chat): Public chat overlay default message after switching back from private chat

---

bbb-webhooks/application.js
bbb-webhooks/config/custom-environment-variables.yml
bbb-webhooks/config/default.example.yml
bbb-webhooks/web_server.js

This PR enables bbb-webhooks to bind on localhost, which, moreover, should be default as we use nginx reverse proxying to pass request to nodejs server.
That lets us with a more secure application as nodejs was by default listening on 0.0.0.0, so server:3005 was exposed by default.
No issues are related to this PR to my knowledge
Motivation behind this PR was to have a more secure application by default, being open to the world should be a specificity and a conscious choice, not the default.
Hope the PR will make it, and thanks you all for the work and effort

[add] enable bbb-webhooks to bind nodejs localhost, and make it default

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

Needed for firefox for consistently changing microphone using device selector
Refs #12054

fix: match exact deviceId when retrieving mic streams

---

bigbluebutton-html5/tests/puppeteer/core/page.js
bigbluebutton-html5/tests/puppeteer/virtualizedlist/virtualize.js

After the implementation of the new collection `users-persistent-data` and after removing `connectionStatus` from `users` collection, the virtualized userslist automated test got outdated. So this PR is a fix and update for it.

Fix and update virtualized list test suite

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx

Adds `aria-live` to the time-window-list. This allows the screen reader to auto announce new chat messages.
Currently doesn't announce messages automatically.

Make Screen Readers Auto Announce Chat Messages

---

bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss

Removes the `box-shadow` from the active class.  It also fixes the `active` style for chat items only being applied to the public chat.
After talking with @tylercopeland it was decided to only remove the outline from the active style. 
before:
after:
Closes #7746

fix: Fix Active Style For Current Chat

---

bigbluebutton-html5/imports/ui/components/debug-window/component.jsx

This PR implements a shortcut (command + K) to access the debug window in Mac OS.
Today we only able to access by the (Alt + K) in Windows.

Allow for Mac OS to trigger debug shortcut

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

`forceRasterizeSlides` was included as a workaround and possibly can be removed next release!
**This PR includes a warning about that!**
`forceRasterizeSlides` will be removed as soon as:
- pdftocairo fix the problem (PR Open): https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/152
- BBB identify PDF with "Type 3" fonts and force rasterize automatically

Includes warning that forceRasterizeSlides can be removed next release

---

bigbluebutton-html5/imports/ui/components/media/container.jsx
bigbluebutton-html5/public/locales/en.json

Remove leftover code from https://github.com/bigbluebutton/bigbluebutton/pull/11622, including:
- getUserMedia/extension based screen sharing support checks
- Chrome screen sharing extension checks
None
Ref.: https://github.com/bigbluebutton/bigbluebutton/issues/11666#issuecomment-808726642

refactor(screenshare): remove unused extension/support checks

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx

Removes unused CSS class in `AudioControls` component

refactor: remove unused class from component

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/styles.scss
bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
bigbluebutton-html5/public/locales/en.json

Adds a way for the user to close and stop mute alerts until the next time it mutes itself.
Closes #12024

feat: Add button to close mute alert

---

bigbluebutton-config/bin/bbb-record
record-and-playback/core/lib/recordandplayback/workers/archive_worker.rb
record-and-playback/core/lib/recordandplayback/workers/base_worker.rb
record-and-playback/core/lib/recordandplayback/workers/sanity_worker.rb
record-and-playback/core/scripts/rap-enqueue.rb

This PR includes 3 closely related fixes for handling of recorded meetings without recording marks:
- Stop processing after the 'archive' step instead of after the 'sanity' step. This fixes the issue where post_archive scripts (which are actually run after the sanity step) were getting run for non-recorded meetings, a behaviour change from 2.2
- Halt recording processing on meetings without recording marks cleanly (without causing a failed resque job). This is done by creating a new exception type which can be raised by a worker to indicate that the job completed successfully, but that processing should not continue.
- Fix the `bbb-record --rebuild` command to restart processing at the 'sanity' step. Previously it restarted at the 'archive' step, which caused the `.norecord` file to be …

Recording: Fix handling of recordings without recording marks

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx

Reduces the number of re-renders on page load and when switching chats/panels by only recomputing chat messages height after fonts are loaded
Closes #11378

fix(chat): reduce re-renders in chat recompute heights

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

Allow guest-page.html to be translated without requiring external resources
Related #10649
The lobby was not localized because bbb-html5 has not granted access to any
assets yet.
This introduces initial translations for the guest-wait pages.
The only supported languages are en and de for now. Needs a concept
to hook it up with transifex.

feature(bbb-html5): localize guest-wait.html

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

Removed duplicated `waitForModerator` localization and included translations for portuguese (the cool one) and something that could be considered spanish.

chore(guest): pt/es guest lobby localization

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

The substr string method is receiving the wrong type of parameter
as length (boolean instead of number) forcing it to always use the
english fallback.

fix(guest): navigator language

---

bigbluebutton-config/bin/bbb-conf

Fixed a missing `$` that prevented `/etc/bigbluebutton/bbb-web.properties` from getting updated with `bigbluebutton.web.logoutURL=default` if `bigbluebutton.web.logoutURL` was not undefined.

Fix adding bigbluebutton.web.logoutURL value of default

---

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
bigbluebutton-html5/imports/api/guest-users/index.js
bigbluebutton-html5/imports/api/note/server/methods/addPad.js
bigbluebutton-html5/imports/api/users/server/methods/setMobileUser.js
bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/group-chat-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/modal/remove-user/component.jsx

Removes unused imports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

refactor: remove unused imports

---

bigbluebutton-html5/dev_local_deployment/workers-start.sh

When self-deploying bbb-html5 using the `deploy_to_usr_share.sh` script, the newly generated/copied `workers-start.sh` file is missing the statement to consider overlay config file `/etc/bigbluebutton/bbb-html5-with-roles.conf` like the packaged version does. This PR adds this real quick.
No issue to close, this isn't affecting a default installation.
stumbled across it as I self-deployed a patched html5 client, want others not to trip over it...

Consider overlay file /etc/bigbluebutton/bbb-html5-with-roles.conf when self-deploying bbb-html5

---

bigbluebutton-html5/deploy_to_usr_share.sh

Updates the inline instructions for how many NodeJS processes to start for each role in bbb-html5
Closes #12232
The values were updated to `2` but the inline instructions state `default = 1` causing confusion
I already made the same changes to packaging bbb-html5, the updates will be part of BBB 2.3.1

docs: Update numbers for default bbb-html5 backends and frontends

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

Moves the position side panel in the DOM to improve the tab order flow.
Before: 
After:

fix(accessibility): Improve Tab Order Flow

---

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss

Adds margin between record button and time passed.

fix: Add margin between record button and time

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/handlers/AbstractCommandHandler.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/handlers/PdfFontType3DetectorHandler.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java

The option `forceRasterizeSlides ` was implemented in #12124 to solve #8835.
When this option is enabled all presentations are rasterized, even those that don't need (already have good quality without rasterize).
As identified by @GhaziTriki, only PDF pages that contains text with font Type 3 have poor quality after conversion.
With this PR, bbb-web will automatically detects when the slide contain this font Type 3 and force rasterize for this cases.

Automatically rasterize if slide contains font Type 3

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

Prevents a bug that would cause the displaying of incorrect number of votes in whiteboard annotation if there are many grouped (by #11718) responses

fix: number of votes displayed in poll results annotation

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
bigbluebutton-html5/imports/ui/components/audio/container.jsx
bigbluebutton-html5/private/config/settings.yml

When listenOnlyMode=false, skipCheck=true and skipCheckOnJoin=true, the
audio tries to start a session more than one time, causing it to fail
at the first one (and reconnect after that).
Now we check if user is already connecting before trying to start a new
audio session.
Added some info in settings.yml for the options related to this commit
Closes #12190

fix: first audio join in breakout fails with specific config

---

bigbluebutton-html5/imports/ui/components/activity-check/component.jsx

Removed the wrong reference to alert.
Probably it wasn't caught by eslint because 'alert' name is also present
in browser's scope.
Closes #12228

 fix: bug in playAudioAlert method 

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js

When setting skipCheckOnJoin to true, an extra audio channel is created in
FreeSWITCH, after user accepts the echo test. The extra channel is removed
when user leaves the room, but this still may affect performance.

fix: prevent an extra audio channel to be created when skipCheckOnJoin is true

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

Add an extra check when choosing the video sort algorithm to see if pagination is _in effect_ instead of only checking if it's _enabled_ via config.
That fixes the scenario where pagination hasn't actually kicked in yet (due to the number of cameras being smaller than page size), but the sorting algorithm chosen still ends up being pagination's.
Closes #12270

fix(video): check if pagination is in effect before choosing sort

---

bigbluebutton-html5/imports/api/video-streams/server/modifiers/floorChanged.js

Add the `multi: true` option to `VideoStream`'s update on floor changes to account for users who are sharing _multiple_ cameras at once.
That fixes the scenario where audio floor sorting is _active_ and the floor has multiple cameras, but only their _first_ camera would be re-ordered first. The rest of their cameras wouldn't be annotated with neither `lastFloorTime` nor `floor: true`.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12278

fix(video): annotate ALL streams from an user on floor updates

---

bigbluebutton-html5/imports/ui/components/text-input/component.jsx

Enter key will send the message to the waiting room instead of adding a newline to the textarea.
no open issue, just very little UX improvement
Waiting room messages aren't usually longer texts. So if the user hits the enter key he most likely wants to send the message instead of adding another line. Line breaks in the message are being ignored anyway when message is being sent to the waiting room, so this makes it more clear.
Shift+Enter still makes it possible to enter a linebreak

Waiting room panel: Hitting enter sends message

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

Updates the `App`  component default prop value for `locale` from a hardcoded string to either the over ride locale defined in the config or the browsers preferred language.
Closes #12246

Update App Default Locale Prop Value

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx

Fixes a crash that would happen in a particular case:
1. join a meeting with moderators A (first, gets presenter status) and B
2. user A changes tool to any tool except text
3. user A changes tool thickness
4. user A changes tool to text
5. user B clicks "take presenter" button, gets presenter status
6. user A clicks "take presenter" button, gets error message

fix: toolbar crash with presenter changes

---

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
bigbluebutton-html5/private/config/settings.yml

This allows showing (or hiding) the option from users in the conference.
Default value is true (show this option to users).
Fixed some eslint warnings.
This commit is compatible with older versions of `settings.yml`. This means  if `showAudioFilters` is not set, it will assume the default value.

feat(audio): add showAudioFilters option in settings.yml

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

This should prevent long poll answers from making poll results unreadable in whiteboard
Adjustments made:
- Add constant to set a maximum length for answers displayed in whiteboard
- Increase of answers column width (and decrease of votes bar column width)
Closes #6782
Closes #12111
Closes #10226

Adjust poll results annotations

---

bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js
bigbluebutton-html5/imports/ui/components/checkbox/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/peertube.jsx
bigbluebutton-html5/imports/ui/components/media/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/default-content/component.jsx

Removes unused variables reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

refactor: remove unused variables

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx

This PR changes the condition for the audio alert to be played when the window is not in focus. Now it will check if there are new messages in chat.
Closes #12253

fix: only play audio alert if there are new messages

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss

Fit conversion error message in toast notification
closes #12293

Fit conversion error message in toast notification

---

bigbluebutton-html5/imports/ui/components/polling/styles.scss

Adds scroll to poll question container when the window height is too small.
I chose to add scroll to the whole container (and not only for the question) because it's possible to create a poll with many answers (buttons). 
A poll with A/B/C/D/E answers could take more than 50% of the screen in that case, making the question unreadable even with a scroll bar.
Closes #12069

Add scroll to poll question container

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx

Fixes chat popup alerts appearing when private chat is open.
Closes #12287

fix: chat popup alerts in open private chat

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss

Reduces padding and margin in network popup for a better mobile experience.
font size: 100% - mobile
font size: 125% - mobile
font size: 100% - desktop
font size: 100% - mobile
font size: 125% - mobile
font size: 100% - desktop
Closes #11972

fix: reduce padding/margin in network popup

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx

Displays "please select presentation" message to poll panel when no presentation is selected (same behavior as 2.2).
Closes #12141

fix: show message when starting poll without active presentation

---

record-and-playback/core/lib/recordandplayback/workers/events_worker.rb
record-and-playback/core/scripts/rap-starter.rb
record-and-playback/core/systemd/bbb-rap-resque-worker.service

Something was already done at rap-starter using `INotify` to trigger the events
worker. It looked like a reasonable approach so I included the missing pieces to
cover all `keepEvents` scenarios:
- ended
- ended, recorded with recording marks
- ended, recorded without recording marks
Also updated with Etherpad events fetching (.etherpad file) as implemented and
running at BigBlueButton v2.2.
Closes #12196

fix(events): keep events using resque workflow

---

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/public/locales/en.json

Add complementary text about content generated during the meeting on meeting end.
closes #10721

feat: Add warning on meeting end modal about content in meeting. 

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
bigbluebutton-html5/imports/ui/components/activity-check/component.jsx

**What it solves?**
This PR fix #11062.
Also, this PR will improve `meetingExpireWhenLastUserLeftInMinutes`. Because there were a problem while ejecting inactives users from meeting. Thus if some user forgot to close the window, the meeting would remains running. Now all users will be ejected (_if set  in conf_) and after that the meeting will be destroyed.
**What does it do?**
- This PR fix a problem that users were never being ejected from meeting even after the countdown of warning message was 0.
**Working now:**

Fix: Eject user from meeting after inactivity warning timeout

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss

Increases audio selector menu width
Closes #12089

fix: increase audio menu width

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss

Hides the action buttons when audio selector is open in mobile devices

fix: action buttons in audio selector - mobile

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/container.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/service.js
bigbluebutton-html5/private/config/settings.yml

Allows for hiding of 'Remember choice' checkbox in User management AND hiding of gear icon menu 'Guest policy'.
In certain deployments the Guest management feature is not desired. However, on BBB 2.3 moderators have the 'Guest policy' menu for dynamically changing the policy which makes hiding of Guest management feature difficult.
However, simply hiding the row is not sufficient because 'Remember choice' in User Management would be out of reach if previously checked. That's why I had to hide both at the same time. 
The default is 'true' - keeping the behaviour of 2.3.0 intact

feat(guests): Introduce dynamicGuestPolicy in setting.yml

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

fix for `presentations.map is not a function` error in presentation uploader
Closes #12363

fix: presentation uploader error

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

- Check if the encodings array of an RTCRTPSender is empty before trying to re-apply the parameter set to alter bitrate
* Bitrate changes come from the dynamic camera profiles
* The encodings array is spoofed like it would if it was undefined
* Although I could not reproduce I suppose it's feasible to assume that the crash might occur due to a race condition
- Remove an unused floorStream variable in video-provider's component
_Tentatively closes_ #12366

 fix(video): check if encodings array is empty before trying to apply bitrate

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx

This Pr fix the presentaitons moving down when someone is talking, this happens because the talking indicator appears in the screen changing the navbar height causing as side effect the decrease of the presentations area height, my first solutions was put the talking indicator floating in the screen, but it lead in the issue of it overlaps the presntations in some cases, talking to @vitormateusalmeida  he gaves the idea of increase the nav bar height so avoid it changing in real time.
Closes #12251

Fix presentation moving down when someone is talking

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss
bigbluebutton-html5/imports/ui/components/debug-window/component.jsx
bigbluebutton-html5/imports/ui/components/debug-window/styles.scss

Move remaining switch texts out of button (connection status modal and debug window).

fix: move toggle text outside of buttons in debug window and network modal

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/private/config/settings.yml

Adds `public.app.raiseHandActionButton.enabled` (default: true) in settings file to enable/disable raise hand button in actions bar.
Closes #12396

feat: add setting to enable/disable raise hand action button

---

bigbluebutton-html5/imports/api/captions/server/methods/appendText.js
bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js
bigbluebutton-html5/imports/ui/components/captions/service.js

Handles pad update on dictation reported at one of the [mailing lists](https://groups.google.com/g/bigbluebutton-dev/c/xEJFWpfG4go/m/OhgB647BAgAJ).
BigBlueButton v2.3 uses an instance prefix while generating padIds. Closed
captions was missing this information when updating pad's content for dictation
mode.
Also fixes a regression that might have broken the closed caption recording.

fix(closed captions): dictation mode and redis communication

---

bigbluebutton-html5/imports/ui/components/chat/component.jsx

The bug was caused because the reference of some variables were changed, some of them are injected, so to avoid unnecessary re-renders I used the react memo.
Closes #7926

Fix re-renders when another chat receives new messages

---

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx

Removes useless conditionals reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
*If a condition always evaluates to true or always evaluates to false, this often indicates incomplete code or a latent bug and should be examined carefully.* (https://lgtm.com/rules/7860090/)

refactor: remove useless conditionals

---

bigbluebutton-html5/imports/ui/components/chat/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/container.jsx

- Adds auto scroll to bottom when a new user enters an ongoing meeting
- Fixes a bug that could prevent auto scroll if the user sends a message and scrolls back twice
Closes #12399

fix(chat): auto scroll to bottom for new users

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Upgrade redis from version 2.8 to version 3.1. Recomended by npm audit security report (https://npmjs.com/advisories/1662).
Closes #12379

fix(security): update redis 2.8 -> 3.1

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Upgrade postcss and postcss plugins. Recomended by npm audit security report (https://npmjs.com/advisories/1693).

fix(security): update postcss and postcss plugins

---

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx

Improve Start A Poll button after publishing poll results

Improve Start A Poll button after publishing poll results

---

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss

Hides the options button when save chat dropdown is open in mobile devices.
Adding CSS to hide the button when the dropdown is active instead of changing z-index values (similar to #12360), as we had many z-index issues lately and changing these values seems to cause more problems than it solves.
Closes #12373

fix: options button appearing in save chat

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala

fix: don't show empty line when poll have 7 answers

---

bigbluebutton-html5/package.json

Removes `git add` from linter configuration.
This is a breaking change from [lint-staged 10.0.0](https://github.com/okonet/lint-staged/releases/tag/v10.0.0):
_Prior to version 10, tasks had to manually include git add as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects git add in task configurations, it will show a warning in the console. Please remove git add from your configuration after upgrading._

fix: remove git add from linter config

---

bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/errors.js

Removes unused imports and exports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

refactor: removing unused imports/exports

---

bigbluebutton-html5/imports/startup/server/index.js

Adds 2 additional cases in browser locale check:
1. browser locale is a region locale but we only have a specific locale of that language available
2. browser locale is a specific locale but we only have another specific locale of that language available
Both cases will return a specific locale that is not the same as the one asked by the browser, but is the same language
browser locale is `cs` and bbb has no `cs` in locales, but has `cs-CZ`
**current behavior:** bbb will return `en.json` (fallback)
**new behavior:** bbb will return `cs-CZ`
browser locale is `zh-SG` and bbb has no `zh` in locales, but has `zh-CN`
**current behavior:** bbb will return `en.json` (fallback)
**new behavior:** bbb will return `zh-CN`
Closes #12413

fix: handle additional cases for locales

---

bigbluebutton-config/bin/bbb-conf

```bbb-conf --status```  command outputs the status of each of the frontend and backend nodejs workers and parallel kurento media servers (if they exist).
Closes #11299
Moving from BBB v2.2 where bbb-html5.service's status gave an idea of the actual status, people might be interested in knowing if all the backend and frontend workers are active (as in BBB v2.3, bbb-html5.service's status doesn't express this and may give a false impression sometimes.)

Show the status of multiple nodejs workers and kurento media servers in bbb-conf status

---

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss

Adds padding to actions bar dropdowns
Closes #12348

fix: add padding to action bar dropdowns

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx

Fixes a crash with the displaying of poll results after a change in a function return.

fix: extract poll question crash

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/container.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js
bigbluebutton-html5/imports/ui/components/polling/component.jsx
bigbluebutton-html5/imports/ui/components/polling/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js

Define pollTypes constants and use them everywhere.
Use same regexes from quickpoll detection to detect the poll type when creating normal poll. Extract as a method in the Service file. 
This fixes certain poll type detection for other languages than english, so that the correct poll type is sent in the events (they were being detected as custom)
Better code readability/reuse

refactor(poll): improve poll types code

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/poll-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js
bigbluebutton-html5/imports/ui/components/polling/component.jsx

Show the translated answers for default polls in the poll result chat message.

fix: translate poll answer key for default polls in chat message

---

bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx

Adds missing `div` element with `pollPanel` styles to new Layout Manager.

fix: poll panel styles - new LM

---

bigbluebutton-html5/imports/ui/components/user-list/captions-list-item/component.jsx

Prevents a crash when clicking in a language in captions list.

fix: captions button crash

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Changes sidebar panels z-index for all new layouts so they all match `customLayout` values. 
This change will fix an issue where the "Manage users" dropdown does not appear in layouts other than `customLayout`

fix: use same z-index for all layouts - new LM

---

record-and-playback/core/scripts/post_publish/post_publish_recording_ready_callback.rb

Fetch for server's security salt at etc's bbb-web properties file and move metadata's
callback url getter to a separated method.
Started these changes while investigating issue https://github.com/bigbluebutton/bigbluebutton/issues/8392.
Although I could not reproduce the problem, changing to use `etc` `bbb-web.properties`
file instead of `usr` `bigbluebutton.properties` makes sense at this new configuration
files distribution.
Thanks for the heads up, @jibon57 . Closes #12147

refactor(recording): recording ready url callback

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala

Reuse `ParticipantStatusChangeEvent` record event, already used by emojis and
webcam streams, to record `UserRoleChangedEvtMsg`.
Role change is stored at `events.xml` as:
- promotion
```
<event timestamp="2068340" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent">
<timestampUTC>1622384175759</timestampUTC>
<date>2021-05-30T14:16:15.759Z</date>
<status>role</status>
<userId>w_fowyht7g0tfi</userId>
<value>MODERATOR</value>
</event>
```
- demotion
```
<event timestamp="2071437" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent">
<timestampUTC>1622384178855</timestampUTC>
<date>2021-05-30T14:16:18.855Z</date>
<status>role</status>
<userId>w_fowyht7g0tfi</userId>
<value>VIEWER</value>
</event>
```
Important to achieve #9789

feat(recording): record role change event

---

bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/container.jsx
bigbluebutton-html5/imports/ui/components/settings/service.js
bigbluebutton-html5/imports/ui/components/settings/submenus/notification/component.jsx

Avoid showing the guest's notification toggles at client's settings if the guest
policy isn't `ASK_MODERATOR`.
Closes #12444

feat(guests): notification settings

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/WebcamsOnlyForModeratorRecordEvent.scala

BREAKING CHANGE: fix typo at moderator only webcams recorded event.
I noticed this while investigating on how to include this event at the recordings.
Left a `BREAKING CHANGE` mark since folks might be already processing this
event at some third party application. Could not find anything within BigBlueButton's
main repository or [bbb-events](https://github.com/bigbluebutton/bbb-events).

fix!(recording): moderator only webcams

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Config xml support was removed as that was for Flash. 
And if some user pass it as custom config it could cause some issues.
As suggested by @ritzalam, this PR:
- Removes support for `configToken` param
Thus pass a custom xml config will not be possible anymore.

Removes support for configToken param

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomUsersUpdateMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala

This PR will fix #10822
If `userInactivityInspectTimerInMinutes` is enabled, users are ejected due to inactivity from the main meeting while they are in a breakout room.
**This PR changes will:**
- Update lastActivityTime periodically for each user that is in a breakout room (avoiding being considered inactive)
_The original issue was about `maxInactivityTimeoutMinutes`, this option is not available anymore but the problem still exists in `UsersInactivityInspection`._

fix: Avoid users to be ejected due to inactivity while they are in a breakout room

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx

Remove z-index property from navbar in new Layout Manager, to prevent settings dropdown bugs.

fix: navbar z-index - new LM

---

bigbluebutton-config/bin/bbb-conf

Checks whether multiple kurento's per server are set up prior to checking and printing their status
https://github.com/bigbluebutton/bigbluebutton/pull/12372 works great if multiple kurento media servers are set up, but if they are not (default), three lines of warnings are displayed every time we check status / restart BBB / etc
Closes #12442
before:
```
$ bbb-conf --status
Failed to get unit file state for kurento-media-server-8888.service: No such file or directory
Failed to get unit file state for kurento-media-server-8889.service: No such file or directory
Failed to get unit file state for kurento-media-server-8890.service: No such file or directory
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka …
```

fix(bbb-conf):Only show status for multi kurento if that is configured

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

upgrades node-sass to latest version 6.0.0. The caveat being meteors `nathantreid:css-modules` package throws a warning until it is updated.
`WARNING: version mismatch for node-sass; installed version is 6.0.0, but version >=3.x <=4.x is required by nathantreid:css-modules)`.
There seems to already be an issue created for this see:
https://github.com/akanix42/meteor-css-modules/pull/133

Update Node-Sass To Latest Version (6.0.0)

---

bigbluebutton-html5/imports/startup/client/intl.jsx
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx

Changes the value of navbar height based on the current locale. Locales with large fonts (`te` and `km`) will have a different value.
Navbar size impacts on the size of the presentation, so this PR tries to reduce the presentation size impact by only using the `LARGE_NAVBAR_HEIGHT` when needed.

fix: different navbar size for locales with large fonts

---

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
bigbluebutton-html5/public/locales/en.json

Improves the message displayed when a meeting is ended by a moderator.
Closes #12515

fix: improve "meeting ended by user" message

---

bigbluebutton-html5/imports/startup/client/intl.jsx
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx

Changes the value of navbar height based on the current locale. Locales with large fonts (`te` and `km`) will have a different value.
Navbar size impacts on the size of the presentation, so this PR tries to reduce the presentation size impact by only using the `LARGE_NAVBAR_HEIGHT` when needed.
Re-implementation of #12497 + fix to issue reported in #12512

fix: different navbar height for large fonts

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.scss
bigbluebutton-html5/private/config/settings.yml

Adds `chat.moderatorChatEmphasized` in settings.yml (default: `true`). 
Setting it to `true` makes moderators messages **bold** in public chat.

feat: emphasize moderator messages in public chat

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js

Fix client crash with A-F options due to missing translation.
Correctly set poll type for YN/YNA/TF quick polls.
Closes #12531

fix(poll): fix client crash with A-F as options and quick-poll type

---

bigbluebutton-html5/client/main.html

The PR changes the font import, placing it in the html to preload them, previously this was made in css which caused the late loading of some elements on screen (such as icons and messages) which caused the need for some workarounds ([sample](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx#L200)) in the code that can now be removed
Currently no one
without preload (icons aren't shown and message changes its size):
https://user-images.githubusercontent.com/15806883/121376207-b602ce00-c917-11eb-8011-d3fd9205cfea.mp4
With preload:
https://user-images.githubusercontent.com/15806883/121376694-1abe2880-c918-11eb-8e0f-3a1a886d492a.mp4

fix: Preload fonts

---

bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx

Makes raise hand notification list names in the correct order. 
Closes #12549

fix: raise hand notification order

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx

Prevents a condition that would happen to viewers when trying to join audio with `skipCheck` enabled and Lock Viewers -> Share microphone set to `locked`.
Closes #12511

fix: Attendee join with mic-ish permission even though mic is Locked

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Use `npm-force-resolutions` to force update dependency `trim-newlines` and remove vulnerability (https://www.npmjs.com/advisories/1753)

fix: update trim-newlines dependency

---

bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/public/locales/en.json

Add the `camera` icon in the user list for whoever is sharing,
in order to improve the understanding of who is sharing the webcam.
It is possible to enable/disable this indication in the settings.yml
Closes #12479
cc @frankemax

feat(video): indicate who is sharing webcam

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx

Fix wrong extra argument in quick-polls (introduced in https://github.com/bigbluebutton/bigbluebutton/pull/12534/)

fix(poll): remove wrong argument in quick-polls

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss
bigbluebutton-html5/imports/ui/components/presentation/download-presentation-button/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/download-presentation-button/styles.scss
bigbluebutton-html5/imports/ui/components/screenshare/switch-button/styles.scss

Add fullscreen presentation button style to download presentation
button.
Adds margin to presentation and screenshare buttons
in order to prevent outline cut.
cc @Arthurk12

style(layout): download presentation button

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js

Fix for the `isPresenter` check at presentation upload modal.
The modal will now only be mounted if the current user is the presenter, preventing [a bug mentioned in issue #12532](https://github.com/bigbluebutton/bigbluebutton/issues/12532#issuecomment-859737404):
If a presenter opens the presentation upload modal and another moderator presses "Take presenter" button, the upload modal won't close for the first user.

fix: check for presenter status at presentation upload modal

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss
bigbluebutton-html5/public/locales/en.json

Prevents the user from creating a breakout room with a duration shorter than the minimum (5 minutes).
Closes #12557

fix: add minimum duration for breakout room

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

Quick fix to prevent the moderator who joins the
breakout room from being unable to unmute himself
Closes #12579
cc @frankemax

fix(breakout-room): avoid muteOnStart at breakout room

---

bbb-common-web/project/Dependencies.scala
bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java
bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Allow html tags or text between `<>` in meeting and user name
closes #10221
closes #12370
After discussing about escaping meeting and user name and how to store this information in backend, it was decided to store those values in raw form. e.g: `<strong>Sinforoso</strong>`, and only when the information is needed it will be escaped.

Allow tags in meeting and user name

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx

Makes improvements based on [feedback from PR #12560:](https://github.com/bigbluebutton/bigbluebutton/pull/12560#issuecomment-861477847)
- When the input value is null or set to a value below the mininum, the increase and decrease duration buttons will now set the duration to the mininum value.

fix: create breakout room form improvements

---

bigbluebutton-html5/imports/ui/components/polling/styles.scss

Fix layout bug caused in Yes/No/Abstention poll questions.
Thanks @germanocaumo for spotting this!

fix: layout for Yes/No/Abstention polls

---

bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx

Fix poll panel position in new layout manager - mobile

fix: poll panel position - new LM

---

bigbluebutton-html5/imports/api/polls/server/eventHandlers.js
bigbluebutton-html5/imports/api/polls/server/handlers/pollPublished.js
bigbluebutton-html5/private/config/settings.yml

Added chatMessage in settings.yml to allow disabling publish poll results in the cat.
Closes #12592
from: #12592
> Since version 2.3 poll results are reported in chat. This is an awesome feature and generally the conference benefits from it.
> 
> At my university BigBlueButton is also getting used for political gettogethers and the poll feature is being used to vote on proposals. In this setting pariticpants sometimes hold more than one vote because the voting rights have been transfered. The poll feature is not able to represent this and it doesnt have to.
> In version 2.2 the results were only being reported on the presentation and were easily removable. A chat message is non removable.
> 
> This leads to the following Problem:
> 
> The actual result of the poll for the reason stated …

feat(poll): add option to disable poll chat message

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

Adds the following components to the new layout manager:
- presentation uploader
- toast (notifications)
- chat alerts
- polling container

Add missing components to new layout manager

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/layout/context/context.jsx
bigbluebutton-html5/imports/ui/components/layout/defaultValues.js
bigbluebutton-html5/imports/ui/components/layout/enums.js
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/container.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx

Fixes an issue where the actions bar buttons would be partially out of screen if settings -> font size is set to 125%.
Actions bar height will now change based on font size settings.

fix: actions bar buttons out of screen - new LM

---

record-and-playback/presentation/scripts/publish/presentation.rb

Generate a poll JSON file at the recordings with an array of published
polling data:
- type;
- question;
- answers;
- number of responders; and
- number of respondents
This file will be published along with the other presentation format files
and can be used to display the poll results at the playback.

feat(recording): process published polls

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-pointer-listener/component.jsx

Fixes a bug that prevents sendLastMessage from sending the final coordinates when shapes are drawn.
Closes #12635

fix a bug when a shape coordinate is zero

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-pointer-listener/component.jsx

Backports the bug fix for when a shape coordinate is zero to 2.3.  #12639

Backport Bug Fix When A Shape Coordinate Is Zero

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx

Adds additional checks to prevent custom layout settings from being ignored on page refresh.

fix: keep changed layout after refresh

---

bigbluebutton-html5/imports/ui/components/chat/component.jsx

Fix  hide (`Alt + H`) and close (`Alt + G`) private chat shortcuts.
Closes #12644

fix: private chat shortcuts

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/private/config/settings.yml

More than 5 answers are now of Custom type poll and answers passed directly.
Increase A-I slide options detection
Rename max_custom to maxCustom in settings.yml to follow pattern.
Closes #12608

fix(poll): Respect maxCustom property in quick-polls

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/component.jsx
bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx

Adds fullscreen presentation feature to new Layout Manager.
In the new Layout Manager, the fullscreen presentation won't be a "real" fullscreen, it will use all available space in the browser window instead.

feat: fullscreen presentation in new Layout Manager

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala

Add role check to allow webcamsOnlyForModerator changes.
Closes #12636

Add role check to allow webcamsOnlyForModerator changes

---

bigbluebutton-config/bin/bbb-conf

This PR puts "bbb-conf --check" in place to correctly handle checking for one or more than one STUN server declared in "$SERVLET_DIR/WEB-INF/classes/spring/turn-stun-servers.xml" or "/etc/bigbluebutton/turn-stun-servers.xml" respectively. 
The PR also adds an additional check to the output of "stunclient" in order to result in an error condition when the hostname is just misspelled (and therefore not resolvable by DNS). 
It closes bigbluebutton/bbb-install#363 and also most probably #12638, and #12407.
It is recommended to operate more than one STUN (and TURN) server. Without this patch, "bbb-conf --check" returns an error if more than one STUN server is configured. At the same time, misspellings in the STUN's hostname, are going to be ignored.

Fix the behavior of "bbb-conf --check" when multiple STUN servers are defined

---

bigbluebutton-html5/imports/api/auth-token-validation/server/modifiers/clearAuthTokenValidation.js
bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
bigbluebutton-html5/imports/startup/server/ClientConnections.js

Reorganized the handling of `UserLeftMeetingEvtMsg` by bbb-html5 so that the backends handle processing to update MongoDB and the frontends handle processing to update the ClientConnections. This way there's no overlap/unpredictability
- split the handling of logic for UserLeft message - backend handles the updates for Mongo, frontend handles the updates to ClientConnections
- removed the 1 second delay since now only backend handles the userleft+user ejected messages and they are syncronous
- no longer initialize ClientConnections on backend instances
Closes #12080 since we are now guaranteed to be processing sequentially the two relevant events in a single NodeJS instance:
```
Jun 30 20:04:35 anton.vm systemd_start.sh[36803]: warn: Received event to handle …
```

fix: removeUser - handle connections in frontends, db changes in backend

---

bigbluebutton-html5/imports/ui/components/app/styles.scss

Adds missing styles required for correct display of `pollingContainer` in new layout manager.

fix: polling component position - new LM

---

bigbluebutton-html5/imports/api/connection-status/server/methods/addConnectionStatus.js

Prevent spamming the logs when user is not authenticated in  `addConnectionStatus` method.

Prevent addConnectionStatus log spam when not authenticated

---

bigbluebutton-html5/imports/ui/components/poll/service.js

Remove linefeed letters from the yes / no (/abstention) options for quick poll. 
For some Asian languages such as Japanese, words are not separated by spaces. Thus even the word "abstention" can be folded in two lines (i.e., abs \n tention) . This leads to a failure of parsing the slide text for the quick polling.
In the following figure, はい / いいえ / どちらでもない corresponds to Yes / No / Abstention. Note that "Abstention" is not parsed correctly.

Remove linefeed for polling option

---

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js
bigbluebutton-html5/imports/utils/sdpUtils.js
bigbluebutton-html5/private/config/settings.yml

Here's what we do when user activates mic:
1 - We do something similar to listenonly's joining process
until we find a valid candidate-pair. The information about this
local candidate is stored.
2 - We then start a new userAgent, and as soon as browser finds
a candidate with the same local ip address. We leave only this
candidate in the SDP and send this to FreeSWITCH. SDP should
contain only a single candidate.
3 - The rest of signaling process is basically the same.

feat(audio): use kurento's trickle-ice to improve mic negotiation

---

bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/container.jsx

Prevents a crash when a viewer is ejected from the meeting while userlist is hidden.
Closes #12714

fix: client crash when userlist is hidden and viewer is ejected

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx

Makes webcam position on mobile not dependent to the orientation of presentation file.
Closes #12708

fix: layout issues on mobile with portrait presentation

---

bigbluebutton-html5/deploy_to_usr_share.sh

In https://github.com/bigbluebutton/bigbluebutton/pull/12589 @oktab1 raises a good point that depending on the dev env setup, the directory (absolute location) might be incorrect. In this PR I add a check, and early exit in case the setup is incorrect.
@oktab1 had a different username
In one of my setups https://github.com/bigbluebutton/docker-dev the directory is /home/bigbluebutton/src/bigbluebutton-html5...

fix: Check for correct directory before deploying bbb-html5

---

bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js

Prevent `loggedOut` property to be undefined in `UserLeaveReqMsg` message.
Closes #12656

Prevent loggedOut property to be undefined

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx

When mic is locked, user is not able to talk so it doesn't make sense
to alert the user about unmute (mute button is also disabled when mic
is locked).
Closes #12048

fix(audio): prevent mute notification to be triggered when mic is locked

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Update `reconnecting-websocket` in bbb-html5 to 4.4.0
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12727
[v4.2.0](https://github.com/pladaria/reconnecting-websocket/releases/tag/v4.2.0) fixed the problem outlined in #12727. Bumped to 4.4.0 as I've detected no regressions of any sorts.

build(deps): update reconnecting-websocket to 4.4.0 (bbb-html5)

---

bigbluebutton-html5/.meteor/packages
bigbluebutton-html5/.meteor/versions
bigbluebutton-html5/imports/api/polls/index.test.js
bigbluebutton-html5/imports/api/polls/server/modifiers/updateVotes.js
bigbluebutton-html5/imports/startup/server/logger.js

Implements server unit testing using Meteors recommendation of Mocha / Chai. 
Meteor-Mocha: https://github.com/meteortesting/meteor-mocha
Chai: https://www.chaijs.com/api/

test: Add Unit Tests For Meteor Polls API

---

bigbluebutton-html5/imports/ui/components/polling/styles.scss

Fixes a problem of alignment of polling options in mobile device.
Closes #12709
In the issue, aligning options in two columns suggested, but I guess aligning in one column is the intended design for mobile devices.

Fixes poll option misalignment in mobile device

---

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js

- Fix a client crash on the presenter's side when a screen was being shared and the presenter changed (https://github.com/bigbluebutton/bigbluebutton/issues/12742)
- Append error messages to screenshare's broker failure log message to make it easier to read
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12742
Scenario: presenter's client could crash when the presenter changed while they were sharing their screen.
That is due to a race condition on the stop procedure in the bridge: two stops can be triggered (one from the server-side websocket tear off and another from the client itself detecting the presenter change).
That could create a scenario where the broker was cleaned in one stop procedure after the second had checked its availability, causing an attribute access of a …

fix(screenshare): fix client crash on presenter change

---

record-and-playback/core/lib/recordandplayback/generators/events.rb
record-and-playback/presentation/scripts/publish/presentation.rb

Generate a external_videos.json file at the recordings with an array of
played external videos url and timestamp.
This file will be published along with the other presentation format files
and can be used to display at the playback.

feat(recording): process published external videos

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/public/locales/en.json

Add error feedback (via toasts) when webcams are ejected by the server due to lack of valid incoming media.
Closes #12732

fix(webcams): add error feedback when media is ejected by the server

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx

Properly clean up temporary webcam streams in video-preview when changing webcam quality profiles.
Fix regression introduced by commit 0ddf02e (#12700).
None
Context: temporary media streams (which were not stored, hence are not in use by video-provider) were supposed to be stopped and cleaned up in video-preview before every new gUM request.
Webcam profile switching wasn't doing that cleanup, so it leaked media streams. I centralized that in the `getCameraStream` method to be a bit more robust.

fix(webcams): avoid leaking media streams on webcam profile changes

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx

Fixes a bug that would cause the poll panel to remain open if a user loses presenter status.

fix: close poll panel if user is no longer the presenter

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/styles.scss
bigbluebutton-html5/public/locales/en.json

Change the previous loading spinner to the new loading dots, ensuring
a bit more UI consistency.
Add the "unhealthy stream" filter to make the dots a little more visible and
remove the loading spinner.
Presenter:
Viewer:
cc @frankemax

feat(screenshare): change loading icon

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

isFullscreen is a state property and is being fetched from the component
props. I think this is something I messed up while resolving a cherry-pick
conflict.

fix(screenshare): fullscreen status from state

---

bigbluebutton-html5/imports/ui/components/fullscreen-button/component.jsx
bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx
bigbluebutton-html5/imports/ui/components/layout/context/context.jsx
bigbluebutton-html5/imports/ui/components/layout/context/initState.js
bigbluebutton-html5/imports/ui/components/layout/enums.js
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx

Adds fullscreen feature to cameras and screenshare in new layout manager.

feat: fullscreen cameras and screenshare in new Layout Manager

---

bigbluebutton-html5/imports/ui/components/webcam/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/drop-areas/container.jsx

Add webcam resize values to Storage in order to restore them after dragging/refreshing (custom layout)

feat: keep webcam resize in storage

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx

Adds the correct values for sidebar z-index in new layouts to prevent dropdown overlap

fix: sidebar z-index - new layouts

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Fixes a bug that happens if the layout type is changed while the sidebar panel is closed.

fix: empty sidebar panel when switching layouts

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx

- Makes save user names feature use the locale value from Settings instead of the property in HTML tag to format date and time. 
- Adds fallback if value is not available.
Closes #12689

Get locale value from settings in export usernames

---

bigbluebutton-html5/imports/ui/components/media/component.jsx
bigbluebutton-html5/imports/ui/components/media/container.jsx
bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx

Fixes an issue where dragging the camera container to right in RTL languages will place it in the left side.
Closes #12567

fix: left/right webcam drag & drop for RTL languages

---

bigbluebutton-html5/imports/ui/components/note/service.js
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/video-provider/service.js

- Fixes a bug that will keep `See other viewers webcams` and `Edit shared Notes` locked for a viewer that has been unlocked
- Adds `Locked` label and unlock option for viewers in userlist dropdown if only these two options are locked
Closes #12658

fix: Unlocking specific user doesn't unlock all options to him

---

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx

Fixes an issue where breakout room panel would stay open after all breakout rooms end.
Closes #12581
Closes #12623

fix: Breakout room panel isn't closing after breakouts end

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx

Fixes an issue where the "create breakout rooms" modal will stay open even if the user loses moderator status.
Closes #12622

fix: close breakout creation modal if user loses moderator status

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-close-button/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/component.jsx

- Makes webcam area use all available space when presentation is hidden (Smart and Custom layouts).
- Removes "Hide presentation" button in Focus on presentation layout

feat: Webcam area size change when presentation is hidden - new layouts

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx

Fixes an issue where the cameras would not use all available space when fullscreen in focus on presentation layout.

fix: fullscreen cameras - focus on presentation

---

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx
bigbluebutton-html5/public/locales/en.json

Change the 'stop dictation' button to 'start dictation' button when the speech recognition stops after some silence. A notification also appears.
Closes #12782 
After the stop of speech recognition due to the API's restriction, we need to click the button twice to make it work again. Moreover we cannot know that it stops because there is no notification.
Some discussion is https://groups.google.com/g/bigbluebutton-dev/c/zqhHDz56ag8/m/P-MW2XlpAQAJ
A screenshot with this PR:

Initialize the start/stop dictation button when speech recognition stops after some silence

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx
bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx

Use the same values for poll, notes, breakout and chat panel min and max width - legacy layout.
Closes #12659

fix: make panels use same min and max width - legacy layout

---

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

This PR adds an event to notify when subscriptions are ready and a condition to start synchronizing chat messages after this event, it is made so the websocket is not flooded with old chat messages while essential data of the meeting are synchronized
One might ask why I'm using an event and not Meteor.session, in my testing I realized that the session stores data between client refresh and it would allow synchronization to start before the subscriptions are ready.
I made a few tests using the [BBB websocket traffic measurer](https://github.com/iMDT/bigbluebutton-pupeteer-measure-websocket-traffic) using different amount of messages and I can notice a improvement and meeting sync load.
(fresh meeting)
```
Wait for audio modal
Audio modal detected. Total websocket traffic: 0.06 mb
Click on …
```

Postpone chat message sync

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetPresenterInPodReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala

Prevent spam of `PresenterAssignedEvtMsg` and `PresenterUnassignedEvtMsg` events, also add more logs to the process of assign and unassig presenter role.
For some reason `akka-apps` could get stuck in assigning and unassigned presenter role, causing disk and cpu usage problems.
To test the PR it will be needed to build and run akka-apps from [code source ](https://docs.bigbluebutton.org/2.3/dev.html#developing-akka-apps).
related to #12284

WIP Prevent spam of assign presenter role

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/layout/defaultValues.js

Fixes an issue where the chat would appear even if `startClosed` is set to `true` and/or `userdata-bbb_show_public_chat_on_login` is set to `false`.
Closes #12647
Closes #12491
Closes #12660

fix: start closed chat option does not work

---

bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/menu/styles.scss
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/styles.scss
bigbluebutton-html5/package.json

Add's a more accessible / simplified  dropdown menu than the current implementation.
#12573, #12574

Add a more accessible dropdown menu

---

bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/media/container.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

- Fixes an issue where sharing an external video in new layouts would not end screenshare
- Moves screenshare notifications from media container to screenshare component

fix: sharing external video does not stop screenshare

---

bigbluebutton-html5/imports/ui/components/chat/service.js

The error occurs because the syncing and synced messages are not mapped in the export function
Closes #12597

Fix export messages throwing a error

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/private/config/settings.yml

This PR complements #12789, and fixes the issues mentioned in @antobinary's [comment](https://github.com/bigbluebutton/bigbluebutton/pull/12789#pullrequestreview-711052637): 
_"Did not work as expected for me:_
_1. I added defaultMeetingLayout=PRESENTATION_FOCUS in /etc/bigbluebutton/bbb-web.properties and restarted bbb-web. Creating a new meeting had Smart layout preselected rather than the presentation focus
2. I tried to pass meetingLayout=PRESENTATION_FOCUS on meeting create but it did not seem to take effect_
_Looking deeper at this, for both 1) and 2) the value is correctly propagated to Mongo, so the issue lies in the client using the layout. I will proceed to merge this PR and we will resolve the update of the value in the client separately."_

Remove default layout override from settings file

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Fixes an issue where the chat panel would get stuck behind the userlist after the following steps:
1. join a meeting in desktop
2. reduce window size until it enters mobile mode and hides userlist and chat panel
3. increase window size until it enters tablet mode
4. increase window size to desktop

fix: hidden chat on resize

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

This PR fixes a problem introduced in PR #12805: meeting layout is always set as default on join (even if the user sets another layout and refreshes the page). It also removes unnecessary `newLayoutContextDispatch` call

fix: persist settings layout after refresh

---

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx

Properly cleans up HTMLMediaElement's source medias when necessary for cameras, screen sharing and listen only.
Closes #12806
As described in #12806, Chrome 92 kicked in an intervention that hard limits the number of concurrent players per session to 75/40, and `paused` (for sure) and `suspended` (I _think_) elements count towards those limits.
The problem: webcam video players were left dangling in paused state despite the _video elements_ themselves being cleaned up from the page. That generated a skewed accounting of WebMediaPlayers in a session, even with pagination. And since webcam media elements are dynamic and fluctuate in number, it could hit the hard limit.
I also took the opportunity to review screen sharing and listen only tear off procedures. They would also leave paused …

fix: avoid leaving dangling HTMLMediaElements in paused state (#12806)

---

bigbluebutton-html5/imports/api/connection-status/server/methods/addConnectionStatus.js

Until now we only logged for `normal`, `danger` and `critical` leading to some ambiguity in log analysis
Closes #
Allows for clearer picture when debugging on a production server

fix: ConnectionStatus - log info on 'warning'

---

bigbluebutton-html5/imports/ui/components/menu/component.jsx

Fix for an issue that prevents the second level of the accessible menu (PR #12745) from opening in languages different from english.
Closes #12826

fix: second level of accessible menu only opens if language is set to english

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Prevents crash when setting a camera to fullscreen in legacy layout.
Closes #12828

fix: fullscreen webcam video crash - legacy layout

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Sets slide size when the presenter changes presentation, fixing an issue that would prevent recalculation of camera position.

fix: set slide size when changing presentation - smart layout

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Fixes camera position issues when presentation is hidden (custom and focus on video layouts).
https://user-images.githubusercontent.com/56703993/126561973-3e18184a-3e2e-410e-a469-cc6674ef37a2.mp4

fix: camera position when presentation is hidden

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/layout/context/context.jsx
bigbluebutton-html5/imports/ui/components/layout/defaultValues.js
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Adds new values for actions bar wrapper and inner height based on font-size and padding, preventing actions bar from being too close to the bottom of the screen

refactor: actions bar size calculation - new layouts

---

bigbluebutton-html5/imports/ui/services/virtual-background/service.js

Forcefully disables camera effects on Safari (macOS; iOS was already blocked).
None
Safari (even macOS) is not properly supported with this feature (yet) and I don't intend on spending time tinkering with that right now.

fix(virtual-backgrounds): disable on Safari

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Prevents the following external video position issues in new layouts:
- external video appearing in the wrong position when switching between 'focus on presentation' and 'focus on video' while webcam is being shared
- external video crash when switching from 'focus on presentation' to 'focus on video' while sharing video and then start sharing webcam
https://user-images.githubusercontent.com/56703993/126557591-dec7d2dd-18d8-4d64-9fe8-783201a51d18.mp4

fix: external video position on layout change

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/constraint/MeetingIDConstraint.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/constraint/MeetingNameConstraint.java

Modified the regex pattern in the meeting name and ID constraints that was incorrectly rejecting meeting names that contain international characters.

Modified regex pattern to allow international characters

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/IsBooleanValidator.java

Modified isBooleanValidator to consider '0' and '1' as valid boolean values.

Allow numerical boolean values

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss

Adds missing styles for items with no available action in userlist.
Closes #12817

fix: presenter position in breakout room userlist

---

bigbluebutton-html5/imports/api/breakouts/server/publishers.js

This PR limits the link from being sent to others, just to the user it relates to.
Closes #
After specific set of steps one user in the meeting could obtain the link to join as another user in the breakouts.

fix(breakouts): Do not allow users to obtain 'redirectToHtml5JoinURL' for others

---

bigbluebutton-html5/imports/api/polls/server/publishers.js

Checks the subscribing user's role and only publishes data if the user is moderator.
Closes #
We needed to do more to avoid viewers programatically trying to obtain info about polls

fix(polls): Avoid viewer manually subscribing to current-poll

---

bigbluebutton-html5/imports/api/guest-users/server/publishers.js
bigbluebutton-html5/imports/api/polls/server/publishers.js

Limits the visibility of pending guests, so that viewers cannot programatically obtain info about them
Closes #
The guestUser collection is subscribed to by default but only moderators should see the list of pending guests

fix(guests): Propagate list of pending guests only to mods

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx

Prevents an issue with the pagination button appearing in "focus on presentation" layout when chat panel is closed, by including an additional check to video-list pagination buttons.

fix: pagination buttons appearing when camera dock is hidden

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/GuestWait.java
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Fixed an issue with the 'guestWait' API that prevented guests from joining meetings after being approved by a moderator.

Fixed issue with guests not joining meeting after being approved

---

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx

Stops the dictation function when the user changes the language with the voice recognition on, so that it can reset the language that it expects by restarting the service (the user needs to click the 'start dictation' button again). 
Closes #12793 
I am trying to implement an automatic translation. Before working on it, I found that the captioning function still shows some unexpected behaviours.

Stop dictation when swapping languages with the voice recognition on

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Fixes a small bug which allows the user to use the
shrink/expand button before the display it is
fully loaded
closes: https://github.com/bigbluebutton/bigbluebutton/issues/12895

fix(screenshare): broken maximized ui before fully loaded

---

bigbluebutton-config/web/index.html

As a food for thought: if the path should be changed in the documentation for the new version, it must also be adjusted in the API demo, among other things. 
I think for 2.2 to change the date is no longer worth it? I hope that the 2.3 will soon be ready.
```
https://docs.bigbluebutton.org/2.2/install.html#5-install-api-demos-optional
^^
```

Fix version on API Demo index.html

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/constraint/MeetingNameConstraint.java

Modified the meeting name constraint to allow commas.

Commas are again allowed in meeting names

---

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/container.jsx

Fixes a crash incroduced by https://github.com/bigbluebutton/bigbluebutton/pull/12871 - where if no users were assigned to breakouts (for example if allowing viewers to pick their own room) the viewer's client would crash due to not handling the case of no `users` in the structure where we look for `redirectToHtml5JoinURL`
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12901

fix: Check for users before grabbing breakout url

---

bigbluebutton-html5/imports/api/polls/server/publishers.js

Modifies the constraints introduced by https://github.com/bigbluebutton/bigbluebutton/pull/12872 so that non-moderator presenters also can receive data for `current-poll` collection
Closes #12888

fix: Grant current-poll access to attendee presenter too

---

bigbluebutton-html5/imports/api/guest-users/server/publishers.js
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

Auto-triggers subscription to Meteor collection `guestUser` for users when the user's role changes [i.e. promoted to moderator or demoted to viewer]. This allows for newlypromoted viewers to receive notifications on guests waiting.
Closes #12890

fix: Re-subscribe user to guestUser collection on promotion/demotion

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Prevents an issue with sidebarContent height calculation that could lead to the presentation not being correctly displayed.

fix: sidebar height - focus on video layout

---

bigbluebutton-html5/imports/ui/components/breakout-room/service.js

Handles a case for breakouts join when `freeJoin: true` and the initial dialog for selecting a room has been closed by the user, resorting to the participants list Breakouts section to select and join a room.
Closes #
Related to #12905

fix: handle case of freeJoin breakout with no users

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

upgrades node-sass to latest version 6.0.1. The caveat being meteors nathantreid:css-modules package throws a warning until it is updated.

upgrade node-sass version

---

bigbluebutton-html5/imports/startup/client/intl.jsx

Fixes `userdata-bbb_override_default_locale` checking on join so the parameter is correctly set.
Closes #12687

fix: override default locale api parameter

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

Adds `userdata-bbb_override_default_locale` (API) and `application.overrideLocale` (settings.yml) support to guest wait page.
Closes #12887

Add override locale support - guest wait page

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/shared/GetChecksum.java

Changed how the checksum is removed from the query string back to the old method. Checksums constructed from percent encoded URLs should no longer fail validation.
Closes #12919

Modified how the checksum is removed from the query string

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
bigbluebutton-html5/imports/ui/services/virtual-background/service.js
bigbluebutton-html5/public/locales/en.json

Display the camera effect selector in a disabled state when the device is not supported (iOS/Safari).
There's also an informative description explaining why.
Courtesy of @frankemax 
Closes #12893
Users can't infer whether and why something is disabled if there's no UI for it.

style(virtual-backgrounds): disabled when env. is not supported

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx

Prevents the make presentation and give whiteboard access menu items being rendered for `dail-in-users`.
Closes #12952

Remove Menu Items Not Applicable For Dial-In-Users

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx

Fixes video position in RTL languages by adding missing props to external video component.
Closes #12934

fix: RTL language - external video, wrong position on client interface

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx

Update cameras grid position when the number of streams changes.
Closes #12969

fix: camera position does not update when sharing is stopped

---

bigbluebutton-html5/imports/ui/components/webcam/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/container.jsx

Reduces cameraDock size when dragging (custom layout).
Closes #12611
Closes #12940

reduce cameraDock size when dragging

---

bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Prevents an issue where screenshare and external video would not appear if presentation is hidden (custom and smart layouts).
Closes #12942

fix: screen sharing does not show up when presentation is hidden

---

bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js

We have a race condition between the `assignPresenter` and `addUser` methods, causing the user to be marked as non presenter in html5 client.
Closes #12843

Fix first moderator to join not be marked as presenter is some cases

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

- removes fullscreen-related code from screenshare component state;
- adds context call to end fullscreen if the fullscreen component is unmounted (presentation, webcam, screenshare);
Closes #12953

fix: viewing shared screen in full screen mode will break the interface when screen share closes

---

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx

Setting the waiting state false as default was leaving an open gap where
the users still did not have a valid breakout room's join url and it's
join button enabled.
Change the first waiting state to true and handle the join type as the
component finishes mounting. If it's a free to choose room scenario,
dispatch the whole Promise based solution and let it manage the waiting
state as the interval checks for the URL response.
Closes #12989

fix(breakout rooms): waiting url state

---

bigbluebutton-html5/imports/ui/components/app/styles.scss

Some parts of text wasn't show if webcams are on. This is happening only with Firefox. 
Tested on: 90.0.2 (64-bit)
Closes #
**Before:**
**After:**

fix: z-index issue in firefox for captions

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx

Adds a pop out icon to the activity Report menu item
For accessibility this item required the pop out icon since it opens a new window. Similar to the Help option in the Settings menu.

Add Popout Icon To Learning Dashboard Menu Item

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/public/locales/en.json

Adds aria description tag to the `randomly assign` button
This button required more descriptive context for the screen readers

Add Aria Description To Randomly Assign Button

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-captions/component.jsx

Fixes an issue with the captions toggle button not working after captions panel is manually closed.
Closes #13017

fix: couldn't reopen closed caption panel

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx

Restores keyboard access in breakout room modal.
Closes #13003

fix: Keyboard Access To Assign Users To Breakout Room Broken

---

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx

Fixes a condition that would render an empty settings menu for viewers.
Closes #13001

fix: empty settings menu - viewers

---

bigbluebutton-html5/imports/ui/components/webcam/component.jsx

Adds an event to stop video/presentation area resize/drag (custom layout) if user switches browser tabs.
Closes #11971
Closes #7991

fix: resize / drag & drop won't stop if user switches tabs

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/live-result/styles.scss
bigbluebutton-html5/imports/ui/components/poll/styles.scss

Applies the following changes to the poll panel, making it usable even with the panel size set to minimum:
- makes all response type buttons use 100% width
- moves ON or OFF label outside the 'anonymous poll' switch
- adds line-breaks to buttons content if there's not enough width to display in one line
Closes #12928

fix: Poll layout errors

---

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx
bigbluebutton-html5/imports/ui/components/captions/pad/container.jsx
bigbluebutton-html5/imports/ui/components/captions/pad/styles.scss
bigbluebutton-html5/imports/ui/components/note/component.jsx
bigbluebutton-html5/imports/ui/components/note/container.jsx
bigbluebutton-html5/imports/ui/components/note/styles.scss

Prevents panel resizing issues with etherpad's iframe (used in captions and shared notes).
Closes #13021

Closed captions / shared notes resizing improvements

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx

Removes focus state if a webcam is unshared.
Closes #12475

fix: incorrect layout when a focused webcam is unshared

---

bigbluebutton-html5/imports/ui/components/user-list/custom-logo/styles.scss

Change the custom logo style to centralize the logo image.

style(logo): centralize image

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.scss
bigbluebutton-html5/public/locales/en.json

Adds focus outline and tooltip to virtual background thumbnails.
Closes #12847

add focus and tooltips to virtual backgrounds

---

bigbluebutton-html5/client/stylesheets/toggleSwitch.css
bigbluebutton-html5/imports/ui/components/switch/styles.scss

Makes toggles use global success/danger colors.
Closes #12767

Color variables on toggle

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/notification/component.jsx
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-html5/public/locales/en.json

Adds user leave notifications. 
Closes #12698

feat: user leave alerts

---

record-and-playback/core/systemd/bbb-rap-resque-worker.service

Redis must be started before bbb-rap-resque-worker.service which will connect to Redis

Avoid race condition between redis and bbb-rap-resque-worker

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx

userName is a list, and its contents must have an unique key.
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `UserName`. See https://fb.me/react-warning-keys for more information.
in span (created by UserName)
in UserName (created by UserDropdown)
in div (created by UserDropdown)
in div (created by UserDropdown)
in div (created by UserDropdown)
in div (created by BBBMenu)
in div (created by BBBMenu)
in BBBMenu (created by Context.Consumer)
in injectIntl(BBBMenu) (created by UserDropdown)
in UserDropdown (created by Context.Consumer)
```
**To Reproduce**
Steps to reproduce the behavior:
1. Join as desktop user
2. Join as mobile user
3. The mobile user then shares his webcam
4. The desktop user now see two labels underneath 
his name: Webcam | …

fix(webcam): key list not provided

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

Makes presentation `isDownloadable` state change only apply after confirmation button is pressed.
Closes #12676

fix: only change presentation isDownloadable state after confirmation 

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx

Fixes wrong margin between `Camera` dropdown and `Quality` label.
Closes #13032

fix: uneven spacing - video-preview modal

---

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/listenonly-broker.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js
bigbluebutton-html5/private/config/settings.yml

Let the server (bbb-webrtc-sfu) generate subscriber offers so that it becomes easier for us to
do RTP payload type normalization between publishers and subscribers. This involves:
- webcams
- listen only: configurable via `public.media.listenOnlyOffering`. Default is `true` (client as offerer).
- screen sharing: configurable via `public.kurento.screenshare.subscriberOffering`. Default is `true` (client as offerer).
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12982
I originally did the PT normalization manually at the server-side, but that sucked. Dealing with it
by letting the server dictate the subscribers' offers is just better overall than trying to rewrite it.
Addresses the mono-PT behavior with the current mediasoup adapter,
which made it difficult to interop Firefox …

refactor(webcams, screenshare, listen-only): let the server generate subscriber offers

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx

Prevents an issue with the camera position in mobile devices when a portrait presentation is used.
Closes #12383

fix: incorrect camera position in mobile - smart layout

---

bigbluebutton-html5/imports/ui/services/notification/index.js

Adds a div wrapper with `role="alert"` to  notification service.
Closes #12572

Fix Screen Reader Announcement Of Toasts In Firefox

---

bigbluebutton-html5/imports/ui/components/poll/live-result/styles.scss

Adds new styles to poll live-results, with columns having the same size in each row (60% of available width to answers, 30% to number of votes and 10% to vote percentage).
Closes #12445

poll live result - layout improvements

---

bigbluebutton-html5/imports/startup/client/intl.jsx
bigbluebutton-html5/private/static/guest-wait/guest-wait.html

- Prevents endless loop while fetching locales when one of the requested files has invalid json
- Adds a client side log to make it easier to understand which file has the error

fix: prevent endless loop if locale file is invalid json

---

bigbluebutton-html5/private/config/settings.yml

Enabled by default https://github.com/bigbluebutton/bigbluebutton/pull/13085 on BBB 2.4+
Closes #
The network stats feature was added on 2.3 last week to address some support challenges. Since it was late into the 2.3 cycle, the feature landed disabled by default. 2.4 is still in beta/rc stage, so we enable by default.

chore: Enable by default enableNetworkStats

---

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx

Adds debounce to captions start/stop dictation button in order to prevent a crash that happens if a user clicks the button too quickly.
Closes #13035

fix: client crashes when quickly clicking start/stop captions dictation button 3 times

---

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx

Avoids a crash by clicking the start (stop) dictation button too much quickly.
Closes #13035
It's just a workaround. I tried to fix it in a more elegant way such as by using recognition.onstart and recognition.onstop to detect the state of recognition, which improved the error but did not work against a very quick clicking anyhow. In the end this was a dirty but the smallest modification.

Avoid crash by clicking the start dictation button quickly

---

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
bigbluebutton-html5/imports/api/screenshare/client/bridge/service.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/listenonly-broker.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js
bigbluebutton-html5/imports/ui/services/meeting-settings/index.js
bigbluebutton-html5/private/config/settings.yml

This is the same as https://github.com/bigbluebutton/bigbluebutton/pull/12207 with a few tweaks on top of it.
New config set at settings.yml:
- public.kurento.screenshare.mediaServer  (e.g.: `Kurento`)
- public.kurento.videoMediaServer 
- public.kurento.listenOnlyMediaServer 
Add a set of metadata parameters:
- meta_media-server-screenshare (e.g.: `Kurento`)
- meta_media-server-video
- meta_media-server-listenonly
I've also centralized metadata fetching in the client using a similar pattern from the userdata fetch.
inb4: I'm not using userdata-* because these aren't supposed to be per-user configuration parameters. These things are either meeting wide or server wide configurations.
None

feat: add media server configuration via metadata and settings.yml

---

bigbluebutton-html5/imports/ui/components/tooltip/component.jsx

Prevents a bug where the "Options" tooltip would stay open after a user ends the meeting.
Closes #13066

fix: Settings menu tooltip open after ending the session

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Hides screenshare component when sidebar content is closed, preventing an issue with the screenshare component appearing behing the sidebar in focus on video layout.
Closes #13115

fix: Share screen placeholder is showing behind side menu

---

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx

Restores waiting list formatting (the way it was in 2.3, as mentioned in [PR #12876](https://github.com/bigbluebutton/bigbluebutton/pull/12876#issuecomment-903389161)).

fix: restore waiting list whitespace

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Restore `Unfocus` label in focused video.
Closes #13127

fix: restore camera unfocus label

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Removes unused component state properties reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
*Unused or undefined React component state properties can cause errors or make code hard to read and understand. Any computation used to initialize an unused state property is wasted, which may lead to performance problems. Any access to an undefined component state property trivially evaluates to the value undefined, which may come as a surprise.* (https://lgtm.com/rules/1506221406550/)

refactor: remove unused state properties

---

bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx

Prevents an issue where the tooltip of a button would appear after closing a menu/modal. 
The issue happened because the default behavior when closing a menu or modal is to restore focus to the element that triggered the opening of that menu/modal. 
My solution only removes focus of the element on `click` events, so it does not break keyboard navigation.
Closes #11814
Closes #13102

remove tooltip focus when closing menu/modal

---

bigbluebutton-html5/imports/ui/components/captions/writer-menu/component.jsx
bigbluebutton-html5/imports/ui/components/captions/writer-menu/container.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/container.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/guest-policy/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/guest-policy/container.jsx

Prevents an issue where _Lock viewers_, _Guest policy_ and _Write closed caption_ modals would stay open if the user loses moderator status.
Closes #13116

fix: Moderator options still open after user being demoted

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx

Check for video-provider's mounted state after peer creation calls. If the provider got unmounted while the procedure was still being processed, clean up the resulting peer.
Closes #13130 
There could be a race condition where a peer creation (async) would resolve after the provider was unmounted.
That would lead to a state inconsistency which could generate all sorts of cryptic problems (see https://github.com/bigbluebutton/bigbluebutton/issues/13130).

fix(webcams): check for component state after peer creation

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/Enter.java
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Moves the max participants check back to the ApiController for now.

Max participants constraint fix

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
bbb-common-web/src/main/java/org/bigbluebutton/api/LearningDashboardService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
bbb-learning-dashboard/src/App.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml

This PR will:
- Remove config `learningDashboardCleanupEnabled` (now to disable set `learningDashboardCleanupDelayInMinutes=0`)
- Include config `learningDashboardCleanupDelayInMinutes` that makes configurable the delay to remove Learning Dashboard (after the end of the meeting) (default value is 2 minutes) (0=disabled).
Also,
- Rename json filename from `activity_report.json` to `learning_dashboard_data.json`

Makes configurable the delay to clean up Learning Dashboard

---

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/public/locales/en.json

Adds a new label (Generate URL) in breakout room list, for when the user does not have join URL for that room.
In the example, the user does not have breakout room URL for Room 2
Closes #13140

add label for when the user does not have breakout URL

---

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx

Changes background-color of the button in "end meeting" modal.
Closes #13148

Change end meeting call-to-action button color

---

record-and-playback/core/.gitignore
record-and-playback/core/Gemfile
record-and-playback/core/Gemfile.lock
record-and-playback/core/Rakefile
record-and-playback/core/lib/recordandplayback/generators/events.rb
record-and-playback/core/resources/raw/183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1630430006889/events.xml
record-and-playback/core/resources/raw/2a1de53edf0543d950056bf3c0d4d357eba3383f-1630607370684/events.xml
record-and-playback/core/resources/raw/chat_0_9.xml
record-and-playback/core/scripts/bigbluebutton.yml
record-and-playback/core/test/recordandplayback/generators/test_events.rb
record-and-playback/presentation/scripts/publish/presentation.rb

Move the handling of chat events into the shared library so it can be
used by multiple recording formats.
The anonymization of names is based on the external user id, if
available, so users have a consistent name through the meeting. Note
that no effort is made to edit chat messages - if someone is mentioned
by name in a chat message, that will still be visible.
Default settings for anonymization can be controlled in
bigbluebutton.yml, and per-meeting overrides can be done using meta
parameters on the create call.
Fixes #13073
This PR should target BBB 2.4; please switch the branch if appropriate.

recording: Anonymize names in chat

---

bigbluebutton-html5/imports/ui/components/menu/component.jsx

Changes BBBMenu z-index value, making the dropdown menus appear in front of the toast notifications.
Closes #13146

fix: z-ordering puts menu behind notifications

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/webcam/component.jsx

Prevents an issue with the camera dock size not being correct when `autoSwapLayout` is set to `true`.
Closes #12947

fix: swap layout camera dock size

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/RequestBreakoutJoinURLReqMsgHdlr.scala

Constraint viewer capability to ask for breakout's url that he is not assigned.

Constraint  viewer capability of request breakout url

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx

Prevents bugs related to the breakout not being completely closed on breakout room creation and when sending invitations.
Closes #13143

fix: breakout room managing window opening bug

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx

Makes the connection strength image visible to the screen readers.
Currently the screen reader is not aware of the connection strengths displayed in the connection status modal.

WCAG2.1 - Connection Status Modal

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/public/locales/en.json

Updates the delete poll option button to reflect current input option, Also alerts the SR when an option is deleted.
1) Multiple delete buttons exist when adding multiple custom answer options that fail to differentiate.
2) When an option is deleted, there is no feedback given to the user that the item was removed.

WCAG2.1 - Moderator > Start a poll

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx

Prevents an issue with the presentation area position in breakout rooms (customLayout only).
Closes #13167

fix: presentation position in breakout room - custom layout

---

bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

When a viewer was promoted to moderator, and after that the user starting a new private chat thae clear steam was called deleting the messages, now the clear stream messages is only called when the user changes the role keeping the messages when the new chat is created.
Closes #13192

fix: Fix public chat being cleared when starting a new private chat

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/ScreenshareModel.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StartExternalVideoPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StopExternalVideoPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala
bigbluebutton-html5/imports/ui/components/app/container.jsx

This PR solves #12803 
- Makes Akaa stop ScreenShare streaming when a External Video is started
- Change the client `shouldShowScreenshare` removing externalVideo check once now it is handled by Akka
- Reuse stop msgs from `MsgBuilder` instead of duplicate

Stop ScreenShare when External Video is started (handling it in Akka)

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-html5/public/locales/en.json

Moves focus to the breakout room panel when opened.
updates the breakout room name input fields aria labels.
Notify screen reader of errors presented in breakout room management.
Update `Join Room` and `Generate` button `aria-label` to use room name.
Fixes the following accessibility issues
1) Selecting the breakout rooms button fails to move the user’s focus into the newly-presented breakout rooms flyout.
2) The name fields for each room identify as “Duration (minutes)”, thus failing to adequately identify the field purpose.
3) The Error dialog regarding the room name is not made aware to screen reader users.
4) The “Join room” action announces as “Join room 1”, “Join room 2” to screen reader users, regardless of the room name provided.

WCAG2.1 - Breakout Room Management

---

bigbluebutton-html5/imports/ui/components/learning-dashboard/service.js

This PR fix #13175 
- Increases the expires time of the Learning Dashboard `accessToken` to 30days instead of 1hour

Learning Dashboard: Increase the token expiry time

---

bigbluebutton-html5/public/locales/en.json

The learning-dashboard is missing out on a language key (column heading "activity score")
Closes #13159
#13163 was kinda messed up, so this one :-)

Add language key for activity report column in learning dashboard

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx
bigbluebutton-html5/public/locales/en.json

adds `aria-expanded` / `aria-haspopup` to whiteboard toolbar submenu items as well as region and label to the toolbar.
Fixes the following accessibility issues
1) The presentation tools that contain submenu items (e.g., “Tools”, “Colors”) fail to indicate their current state to screen reader users.
2) The presentation tools toolbar would benefit from additional context for screen reader users.

WCAG2.1 - Moderator > Whiteboard Toolbar

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PageToConvert.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationConversionCompletionService.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/PageConvertProgressMessage.java

In some cases the default presentation isn't showed for a breakout room., this happened because the `presentation_end_conversion` service isn't called for that breakout room.
Closes #13109
Thanks to @gustavotrott for helping on debugging the problem

Fix a case where default presentation doesn't show in breakouts

---

bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutJoinURL.js

Prevents a bug in breakout invitation, where both `handleBreakoutJoinURL` and `handleBreakoutRoomStarted` were able to insert a record in `Breakouts` collection. 
After the changes, `handleBreakoutJoinURL` will only be able to update the collection (and only after the insertion has been made by `handleBreakoutRoomStarted`).
Closes #13022

fix: Breakout room invitation bug

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx

Closes #13201
Puts the Learning Dashboard button at the bottom of the dropdown menu and adds a divider on top of it.
Motivation
Learning Dashboard is a new feature so it should be in a place where it is easy to notice.

Refactor: Move Learning Dashboard entry to bottom of menu #13201 

---

bigbluebutton-html5/imports/startup/client/base.jsx

Fixes an issue with cameras [sometimes] not being displayed if a user joins the meeting when cameras are already shared.
Closes #13218

fix: webcam dock isn't visible in certain scenarios

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala

This PR fix the following problem related by @ritzalam:
When `endWhenNoModerator` is `true`, since all moderators have left the meeting the server start a countdown to end the meeting.
But this countdown is being restarted every time another user (non-moderator) leave the meeting.
This change will fix this problem.

Fix: endWhenNoModerator not ending the meeting after all moderators left

---

bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutJoinURL.js

Allows sending of more breakout room invitations if viewers do not accept the first one.
After investigating the issue, I found the "cause": [$elemMatch](https://github.com/bigbluebutton/bigbluebutton/pull/12871/files#diff-11194f8c3661fb45f66950ede48b85e35dcb81f34a9ad69a74bfafc2c540781eR51) (used in breakout publisher so each viewer only has access to its own joinURL) [returns only the first matching element](https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/#proj._S_elemMatch). So, even if a moderator keeps sending more invites, the viewer will only get the first one.
With the changes made in this PR, only the last invitation of each user will be kept in the collection.
Closes #13223

fix: Breakout room assignment only working first time

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss

Closes #13235
It reimplements the feature of making the presence of the download presentation button dependant on a presentation.allowDownloadable variable in settings.yml file.
<h3>Motivation</h3>
This feature has been accidentally lost in process of removing bugs.
<h3>More</h3>
The presentation.allowDownloadable variable has already been there so settings.yml is not modified.

fix: Reimplement presentation.allowDownloadable

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/waiting-users/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/container.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/service.js
bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss
bigbluebutton-html5/public/locales/en.json

This PR activates the waiting room panel permanently dependent on the current guest policy (if `ASK_MODERATOR` is enabled) and dependent on the config parameter `isGuestLobbyMessageEnabled`.
I tried to handle all of the combinations properly (config parameter, guest policy, are there pending users right now despite guest policy is not `ASK_MODERATOR` any longer etc.). I hope I covered all cases.
Closes #13158
Waiting room is currently only active if there are waiting users which means that moderators cannot change the lobby message as long as there isn't at least one waiting user.
Use case: Moderator wants to open the session a few minutes in advance, instantly set the lobby message to inform all users about something (session starts 5min later or sth similar) so that every user …

feat: Activate waiting room permanently

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx

Prevents camera position bug when resizing, by removing cameras width/height manipulation in customLayout.

fix: camera resizing bug
