bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx

Fix teh issue of new tabs for breakout room being blocked because took too much time to generate the breakout url

Fix pop-up blocking when joining a breakout room

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/styles.scss

fix: presentation position in focus on video layout

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx

- Replaces `newLayoutContextDispatch` with `layoutContextDispatch` in actions bar poll button.
- Removes unused code in actions dropdown component

Fix: poll menu button in actions bar

---

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
bigbluebutton-html5/public/locales/en.json

chore: Merge 2.3.11 into 'develop'

---

bbb-activity-report/package-lock.json

- Update `/bbb-activity-report/package-lock.json`
Update from `npm audit`

Learning Dashboard: Fix package-lock.json

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-tests/puppeteer/chat/elements.js

After the refactoring that updated dropdown to menus, some of the data-test props were lost. This PR fixes it

test: fix data-test in menus

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js

Capitalizes A-I poll answers (Start Poll menu and quick polls).
Closes #12696

fix: poll options are not capitalized

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/app/styles.scss
bigbluebutton-html5/imports/ui/components/layout/context.jsx
bigbluebutton-html5/imports/ui/components/layout/defaultValues.js
bigbluebutton-html5/imports/ui/components/layout/initState.js
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Adds captions component to new layouts and makes changes needed to display it in the correct position.
Closes #13002

restore captions feature in new layouts

---

bigbluebutton-html5/client/main.jsx
bigbluebutton-html5/client/wdyr.jsx
bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Add the Why did you render library. ([https://github.com/welldone-software/why-did-you-render](https://github.com/welldone-software/why-did-you-render))

Add why did you render lib

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx
bigbluebutton-html5/imports/ui/components/webcam/component.jsx

Prevents an issue with content resizing when external video is being shared (caused by pointer events in external video iframe) .
Closes #12948

fix: Bug when resizing content in custom layout

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/ActivityTrackerActor.scala
bbb-activity-report/src/components/UsersTable.jsx

This PR will fix #12936 
- Add Dial-in users to Dashboard
- Set Phone icon to Dial-in users

Learning Dashboard: List Dial-In users in the dashboard

---

bigbluebutton-html5/public/locales/en.json

Add a message for 408 error code.
closes #12832

Add missing error code 408 message

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/drop-areas/component.jsx

Removes unused imports and variables reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)

refactor: remove unused imports/variables

---

build/packages-template/bbb-html5/bigbluebutton.nginx
labs/vertx-akka/nginx/vertx-akka

fix: Remove spurious nginx error_page directive

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss
bigbluebutton-html5/imports/ui/components/button/button-emoji/ButtonEmoji.jsx
bigbluebutton-html5/imports/ui/components/button/styles.scss
bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
bigbluebutton-html5/imports/ui/components/muted-alert/styles.scss

* Updates the media selection dropdown to a menu
* Make the media selection button accessible via keyboard 
* Fix leave audio button tooltip not displaying when focused via keyboard 
* Update muted alert notification position

Update Media Selection Dropdown to Menu

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

update a magic number to a constant;
Suggested in #13014

Update Value To Key Code Constant

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
bigbluebutton-html5/imports/ui/components/menu/component.jsx

chore(audio): fix eslint / sonar smells on button-emoji

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.scss

This recovers the grey scale styling applied to disabled virtual background buttons. Also updates the spacing between the buttons to be consistent across screen sizes.
Suggestions pointed out in #13107.

Recover Greyscale Background Thumbnail Styles

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Fix link to BBB tutorials

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Closes #13136
Same as #13137 but on 2.3 branch

Fix link to BBB tutorials on 2.3

---

bigbluebutton-html5/package-lock.json

Updated sub-dependency `tar` from `6.1.6` to `6.1.11` due to reported security vulnerabilities

chore: Npm audit - update "tar"

---

bbb-learning-dashboard/src/App.js

This PR localizes the (HTML) title of the learning dashboard
Stumbled over it when dealing with #13159 and creating #13163.

refactor: Localize learning dashboard title

---

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.scss
bigbluebutton-html5/imports/ui/stylesheets/variables/palette.scss
bigbluebutton-html5/imports/utils/dom-utils.js
bigbluebutton-html5/public/locales/en.json

Updates the color for chat timestamp.  Provide screen reader alert for copied chat transcript.
Fixes the following accessibility issues 
1) In chat message, the contrast between the grey foreground and white background time of post text colors is insufficient (2.8:1); falling short of the 4.5:1 required for small text.
2) The “Public chat” chat option “Copy” fails to indicate to screen reader users that it has copied the transcript to the paste buffer when actioned.

WCAG2.1 - Common updates

---

bigbluebutton-html5/imports/ui/components/webcam/drop-areas/component.jsx
bigbluebutton-html5/public/locales/en.json

Adds localization support to "Drop here" message in cameras drop zone.

localize camera dropzone label

---

bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/menu/styles.scss

Fixes icon padding in menu in RTL Languages

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss

Place both buttons at the bottom of the video dock when cameras are vertically positioned

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/constraint/PasswordConstraint.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/EndMeeting.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/JoinMeeting.java

ModeratorPW and attendeePW parameters are now optional, but recommended, again.
Closes #13220

Make create passwords optional

---

build/packages-template/bbb-html5/after-install.sh
build/packages-template/bbb-html5/bionic/systemd_start.sh
build/packages-template/bbb-html5/bionic/systemd_start_frontend.sh
build/packages-template/bbb-html5/build.sh

Updates NodeJS in the `bbb-html5` package. Meteor 2.3 needs NodeJS 14.
I want to build working bbb-html5 packages.
This change is also required in the develop branch.

Update build scripts to reflect meteor update

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala

Merged 2.3.x into 2.4.x (mostly to pick up the fix https://github.com/bigbluebutton/bigbluebutton/pull/13234 )
Preparation for next BBB 2.4.x release

chore: Merge 2.3.x into 2.4.x

---

bigbluebutton-html5/imports/ui/components/app/container.jsx

Fixes presentation restoreOnUpdate feature.
Closes #13258

fix: restoreOnUpdate: true, parameter not working

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Updates a few npm dependencies to their latest versions
Preparation for 2.3.14

chore: Update axios and other npm deps

---

bigbluebutton-html5/dev_local_deployment/systemd_start.sh
bigbluebutton-html5/dev_local_deployment/systemd_start_frontend.sh

Recovers the ability to deploy locally from source bbb-html5
none
Follow up to #13219

fix: Adjusted local_deployment NodeJS version

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Fixes user list appears even if custom parameters is false

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/baseLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

- Adds `LayoutEngine` component
- Moves all shared code from each layout to LayoutEngine

refactor: reduce complexity and remove duplicated code from layouts

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/peertube.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/volume-slider/component.jsx
bigbluebutton-html5/imports/ui/components/reload-button/component.jsx
bigbluebutton-html5/imports/ui/components/reload-button/styles.scss

This PR fixes some small issues with the external video interface, volume slider and reload button as well as adds a volume slider for PeerTube and removes an error condition happening with Vimeo videos.
Each commit is very small and easy to follow I hope!

fix(external-video): Adjustments to external video design and custom players

---

bigbluebutton-html5/public/locales/en.json

Corresponding PR for #13317 for branch v2.4.x-release
Closes #13312 for v2.4.x-release

[2.4] Fix missing message in waiting room when meeting was ended before being able to join

---

bbb-learning-dashboard/src/components/PollsTable.jsx
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UsersTable.jsx

Backport 2.4: Learning Dashboard line wrap fix

---

.gitlab-ci.yml
build/packages-template/bbb-html5/build.sh

Instead of updating the local Meteor version to the needed one, on every build, request the right version when specifying the Dockerfile instructions. This is the tag in use: https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/commits/v2021-09-30
Closes # none
Cuts a minute or so of an unneeded update of Meteor + network traffic

build: Rely on meteor version from docker image

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

This PR will force to disable LearningDashboard when creating Breakout Rooms.

refactor: Disable LearningDashboard for Breakout Rooms

---

bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js

Prevent a edge case where the `setPresenterInPod/AssignPresenter` was in a loop.
Closes #12284

fix: Prevent a case where the setInPod get stuck on a loop

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx

Use new external-video on/off icons on the actions dropdown button.

feature(external-video): New external video icon

---

bigbluebutton-html5/client/wdyr.jsx

Closes#13340
Fixed the error with implementation of devDependancy why-did-you-render?
<h3>Motivation</h3>
A bug in the import

fix: Fixed the error with implementation of devDependancy (wdyr)

---

bigbluebutton-html5/client/wdyr.jsx

Reverts bigbluebutton/bigbluebutton#13411
Errors on dev env

revert: Revert "fix: Fixed the error with implementation of devDependancy (wdyr)"

---

bigbluebutton-html5/imports/api/captions/server/methods/appendText.js

Avoid appendText call if the requester is not the closed captions' pad
owner.

fix(closed captions): check owner on text append

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

Adjusts guest waiting page loading dots to be the same as the one displayed
at the client.
How it is on the client:
How it is on the guest waiting page:
With this changes:

style(guest page): loading dots

---

bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js
bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js
bigbluebutton-html5/imports/api/captions/server/modifiers/addCaption.js

Missing updates on Meteor's data validation for the closed captions
backend recording events.

fix(closed captions): captions recording

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/shared/PostChecksum.java
bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java

All parameters can again be passed in the request body with no query string.

Parameters allowed in request body again

---

bbb-libreoffice/docker/Dockerfile
bigbluebutton-config/bin/bbb-conf
bigbluebutton-html5/imports/api/captions/server/methods/appendText.js
bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js
bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js
bigbluebutton-html5/imports/api/captions/server/modifiers/addCaption.js
bigbluebutton-html5/imports/api/note/server/methods/getNoteId.js
bigbluebutton-html5/imports/ui/components/breakout-room/service.js
bigbluebutton-html5/imports/ui/components/note/service.js
bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json
bigbluebutton-html5/private/static/guest-wait/guest-wait.html
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Merged branch v2.3.x-release into branch v2.4.x-release in preparation for a release of 2.4-rc-2
Closes # none
List of files which had conflicts resolved manually:
```
```
I did not carry over locale files

chore: Merge 2.3 into 2.4

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/api-version.ftlx

Add the bbb version in `/api` response, also add a configuration (`allowRevealOfBBBVersion`) to reveal the information
`allowRevealOfBBBVersion=false`
`allowRevealOfBBBVersion=true`

Add bbb version in api response

---

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java
bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/api-version.ftlx

Add `version` tag back to api response.

Add version tag back to response

---

build/packages-template/bbb-html5/after-install.sh

Missed during #13610
bbb-html5 won't start without this change
Closes # none

build: Set bbb-html5 Nodejs version to 14.18.1

---

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

fix(screenshare): bad isPresenter transition check (#13245)

---

bigbluebutton-html5/imports/api/meetings/server/modifiers/updateRandomViewer.js
bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx
bigbluebutton-html5/imports/ui/components/modal/random-user/container.jsx

Closes#13448
This change makes the behaviour of Random User Select feature more consistent and efficient.
<h3>Motivation</h3>
The behaviour of this feature was hard to predict:
<ul>
<li>It didn't always listen to the choice of akka-apps.</li>
<li>It has been sending data in different structures</li>
<li>It has been reappearing on some operations after being closed</li>
<li>There wasn't a defined number of iterations in a function,</li>
</ul>

Random user ordering

---

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss

This PR fixes the user list button's incorrect arrow direction for RTL languages.
Closes #13618

fix: user list button's arrow

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/styles.scss
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
bigbluebutton-html5/public/locales/en.json

Rewrite fullscreen button following BBB v2.4 new layout manager fullscreen changes

feat(external-videos): rewrite fullscreen button

---

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss

This PR fixes the problem described in #13665.
**Desktop:**
**Mobile:**
Closes #13665

fix: hidden content in waiting users component

---

bigbluebutton-html5/imports/ui/components/actions-bar/captions/reader-menu/styles.js
bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/styles.js
bigbluebutton-html5/imports/ui/components/app/styles.js
bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.js
bigbluebutton-html5/imports/ui/components/captions/writer-menu/styles.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/styles.js
bigbluebutton-html5/imports/ui/stylesheets/styled-components/palette.js

Adds the possibility to change color variables of the styled-components via API.

refactor: Styled-components CSS variables

---

bigbluebutton-html5/imports/ui/components/video-preview/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

Re-use lock check from video-provider in video-preview
None
Two methods doing the same thing in two different places.

refactor(webcams): re-use lock check from video-provider in video-preview

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/services/virtual-background/service.js

This PR restores the background settings when leaving the breakout room and rejoining the main room.
Closes #13241

fix: virtual background not kept when switching from breakout to main room

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/fullscreen-button/component.jsx
bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx

Restores 2.3 fullscreen behavior (with fullscreen API instead of only use all available window space).

Restore 2.3 fullscreen style

---

bbb-learning-dashboard/src/App.js

Fix problem reported in #13704.
**Before**: When data request fails, Dashboard try to request data again immediately.
**After**: Each time data request fails, the interval to try again is increased exponentially.

fix: Avoids Learning Dashboard from requesting data exceedingly

---

README.md
SECURITY.md

Two dead links will be removed and replaced, respectively. 
I do not like dead links.  🙃

Replace dead links

---

bigbluebutton-html5/imports/startup/server/index.js
bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/captions/service.js
bigbluebutton-html5/imports/ui/components/debug-window/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx

handle cases where `toUpperCase` may throw error if undefined.
#13707

fix:  Fix cannot read properties of undefined (reading 'toUpperCase')

---

bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/service.js
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/container.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/poll/container.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
bigbluebutton-html5/imports/ui/components/screenshare/service.js
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/container.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/container.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/service.js

Removes duplicated `isPresenter`, `isUserPresenter` and `amIPresenter` methods, and retrieve presenter information from `usersContext` when possible.
Closes #12582

refactor: isPresenter rework

---

bbb-learning-dashboard/src/components/PollsTable.jsx
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UsersTable.jsx

- Smaller cell horizontal padding.
- `whitespace-nowrap` will only span `<td>` elements.
Closes #13456

fix: table sizing (learning dashboard)

---

bigbluebutton-html5/imports/ui/services/settings/index.js

Fixes a bug when restoring the settings after refreshing the page.
Closes #13750

fix: settings state

---

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js

fix: Fix server side connection close on user disconnection

---

bigbluebutton-html5/imports/api/polls/server/publishers.js
bigbluebutton-html5/imports/ui/components/polling/component.jsx
bigbluebutton-html5/imports/ui/components/polling/container.jsx
bigbluebutton-html5/imports/ui/components/polling/service.js

Prevents a leak of the typed response poll answers.

fix: prevent poll response leak

---

bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss

Fixes waiting room panel content misalignment.
Closes #13761

fix: waiting room ui regression

---

bigbluebutton-html5/public/locales/en.json

Updates string to match the fallback text used in the guest lobby title.

Update Guest Lobby Title String

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

Adds try/catch and fallback values to presentation uploader in order to prevent client crash.
Closes #13659

fix: 2.4 RC3 - bug - presentation causes the client to crash

---

bigbluebutton-html5/imports/ui/components/layout/defaultValues.js

Reduces userlist and chat min-width, so it becomes more usable in small windows.

reduce sidebar min-width - 2.4

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx

Reduces userlist and chat min-width, so it becomes more usable in small windows.
Closes #12183

reduce userlist and chat min-width

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx

Makes random-user modal only open if there are no other modals open at the same time. (https://github.com/bigbluebutton/bigbluebutton/pull/13800 port to 2.3)
Closes #13794

fix: random-user modal blocks other modals

---

bbb-learning-dashboard/src/components/PollsTable.jsx

- Hides the anonymous poll row unless it's needed.

learning dashboard: hides anonymous poll row

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy

Check if there's a valid session cookie/JSESSIONID in the checkAuthorization endpoint if `allowRequestsWithoutSession: false`.
None

fix(core): look for session/jsession cookie in checkAuthorization endpoint

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserEmojiCmdMsgHdlr.scala

Improved a few cases for emoji status permissions

fix: Fix Emoji Permissions in akka-apps

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy

[2.3] fix(core): look for session/jsession cookie in checkAuthorization endpoint

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js
bigbluebutton-html5/imports/ui/components/audio/service.js
bigbluebutton-html5/imports/ui/services/audio-manager/index.js

Forces audio connecting process to end if audio modal is closed.
Closes #7903

fix: Cannot interrupt audio Connecting process

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala

<h3>What does this PR do?<h3>
Improved a few cases for whiteboard drawing permissions

Fixed annotation permission

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala

To remove a duplicated condition in akka-apps
Closes #

Remove a duplicated condition

---

bigbluebutton-html5/client/main.html
bigbluebutton-html5/imports/ui/components/fullscreen-button/service.js
bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx
bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Prevents the following bugs (all related to fullscreen on Safari browser):
- part of the screen becomes white when in fullscreen
- minimize presentation button appearing when the presentation is fullscreen
- presentation not using all available space when in fullscreen
Closes #11092

fix: Safari fullscreen issues

---

bigbluebutton-html5/imports/ui/services/webrtc-base/bbb-video-stream.js

This fixes the camera's unexpected blurred background after choosing no virtual background.
Closes #13796

fix: unexpected blurred effect

---

bbb-common-web/src/main/java/org/bigbluebutton/api/model/constraint/JoinPasswordConstraint.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/EndMeeting.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/JoinMeeting.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/shared/JoinPassword.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/shared/ModeratorPassword.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/shared/Password.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/JoinPasswordValidator.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/ModeratorPasswordValidator.java

Added a new constraint to join requests that validates the provided password against the moderator and attendee passwords set for the meeting.

New Constraint Added to Join Requests

---

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy

Backport relevant parts of https://github.com/bigbluebutton/bigbluebutton/pull/13827 into 2.3.
None

[2.3] chore: add user infos in custom headers to checkAuthorization OK response

---

bbb-webrtc-sfu.placeholder.sh

build: bump bbb-webrtc-sfu to v2.6.3

build: bump bbb-webrtc-sfu to v2.6.3

---

bigbluebutton-html5/package-lock.json

Updates a bunch of npm dependencies to more recent versions
Closes # none

chore: Updated npm dependencies

---

bbb-learning-dashboard/package-lock.json

Those are changes after running `npm audit fix` in the learning-dashboard directory.
I have tested those changes and all worked fine.

chore: update Dashboard's package-lock.json

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala
bbb-learning-dashboard/src/components/PollsTable.jsx

Once BBB supports multiple choices polls. 
This PR will make Dashboard supports that users can have more than one answer per poll.
Closes #13576.
_Plus: It also forces the Polls to be shown in the correct creation order._

feat: Dashboard support for multiple choices polls

---

bigbluebutton-tests/playwright/webcam/util.js

Let a loop do more than one iteration.
Closes #
I don't have an environment to test this code, but it seems to be a bug, about which Sonarcloud is always complaining.
Let me know if I misunderstand something.

fix (test): non-iterating loop in Playwright

---

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js

Reverts bigbluebutton/bigbluebutton#13748
Issues with looping authenticate on audio user being ejected. More details to follow

Revert "fix: Fix server side connection close on user disconnection"

---

bigbluebutton-config/bin/bbb-conf

Cherry-pick the fix https://github.com/bigbluebutton/bigbluebutton/pull/12682 to backport it to 2.3.x

Fix rewrite recording info in metadata.xml after change of hostname

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/component.jsx

Add region roles to improve screen reader navigation.
Closes #13807

fix(accesibility): Add Region Roles for Screen Reader Navigation

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala

Refactor akka actor of LearningDashboard to store infos using users `extId` instead of `intId`.
**Motivation:**
If some user leaves the meeting and come back later. There were two rows for this user in the Dashboard.
With this change, the two rows will be merged into one.
**Data sample**
- Before
```json
{
"intId":"5799a2519cd89b5459480194197985b2cd486b62-1638555309291",
"name":"random-8119495",
"users":{
"w_bbovdmffgkd4":{
"intId":"w_bbovdmffgkd4",
"extId":"123",
"name":"user 3",
"registeredOn":1638555346215,
"leftOn":1638555474499
},
"w_ij0vr4rigert":{
"intId":"w_ij0vr4rigert",
"extId":"123",
"name":"user 3",
"registeredOn":1638555807560,
"leftOn":0
}
}
}
```
- After
```json
{
"intId":"5799a2519cd89b5459480194197985b2cd486b62-1638555309291",
"name":"random-8119495",
"users":{
"123":{ …
```

Refactor: Dashboard grouped by extId

---

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js

Offer direction should only be controlled that way in listen only

fix(fullaudio): remove cross wired configs

---

bigbluebutton-html5/imports/api/auth-token-validation/server/publishers.js

The loop occurs because the publisher takes a long time to return and the client was retrying too much times.
OBS: this only occurs on 2.4, 2.5 doesn't user a publisher to validate

Revert auth token validation publisher changes

---

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js

This is a re-implementation of #13748, because was reverted at #13885.
The issue happens because the connection was closed before removing the user from the video and audio and set the user as offline.

re-implement the server-side connection close when user is removed

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/ModifyWhiteboardAccessPubMsgHdlr.scala

Improved a few cases for modifying whiteboard access permissions.

fixWhiteboardModifyPermissionsCheck

---

bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UsersTable.jsx
bbb-learning-dashboard/src/services/UserService.js

This PR refactors the Learning Dashboard for supporting the grouping by `extId` rather than `intId`.
With #13926, the info will be stored using extId rather than intId. So, this PR adds the necessary Dashboard changes for matching that implementation.

refactor(Dashboard): add support for users grouped by extdId

---

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/service.js

fix(webcams): keep base peer object in component, fix viewers randomly failing

---

bigbluebutton-web/bbb-web.nginx
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy

For the sake of backwards compatibility

chore: add legacy checkAuthorization endpoint

---

bigbluebutton-html5/imports/ui/components/app/component.jsx

Fix some cases that a user is flagged as mobile on desktop environments with small viewport.

fix(layout): false positive mobile user

---

bigbluebutton-html5/imports/ui/components/layout/context.jsx

Forces navigation sidebar to open with content sidebar.
Closes #13953

fix(layout): navigation sidebar not opening with content sidebar 

---

bigbluebutton-html5/imports/ui/services/virtual-background/index.js

This PR is a backporting of #13855, which is authored by @drlight17.
Note: it includes some linting.

refactor: virtual background drawing

---

bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js

fixes a crash in bbb-html5 when someone uses phone dialin. The
crash resulted in users joining the audio convference but not being
visible in the users list.
Fixed stack trace:
~~~
error: UserJoinedVoiceConfToClientEvtMsg: Error: Match error: Missing key 'pin'
at check (packages/check/match.js:36:17)
at addUser (imports/api/users/server/modifiers/addUser.js:23:3)
at addDialInUser (imports/api/users/server/modifiers/addDialInUser.js:30:10)
at EventEmitter.handleJoinVoiceUser (imports/api/voice-users/server/handlers/joinVoiceUser.js:36:5)
at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:114:10)
at imports/startup/server/redis.js:126:28
at …

Fix telephone dialin

---

record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb

Updated usage as this was still copypasted from the other file (post_events.rb), while this is technically not correct.
Haven't created an issue for something this small.
Usage section seemed wrong.

Updated usage section of analytics script to match actual syntax

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Fixes initial state of navigation sidebar on all layouts.
Navigation sidebar opens along with the content sidebar.
Closes #13979

fix(layout): sidebar inconsistent state

---

bbb-learning-dashboard/learning-dashboard.nginx

Committed inclorrectly in https://github.com/bigbluebutton/bigbluebutton/pull/14027

fix: adjust path to file in learning analytics dashboard

---

bigbluebutton-html5/client/main.html
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/settings/component.jsx

This PR adds the support for setting the main font based on the currently chosen language of the client. Tahoma is set for Persian language.
Closes #13596

Tahoma font for Persian language

---

bbb-webrtc-sfu.placeholder.sh

Fixes https://github.com/bigbluebutton/bigbluebutton/issues/14066

build: bump bbb-webrtc-sfu to v2.6.5

---

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx

Changes the window title for breakout room tabs.
Implements exactly the behavior described in #14086.
Closes #14086

refactor: window title in breakout rooms

---

bbb-learning-dashboard/src/components/Card.jsx
bbb-learning-dashboard/src/components/PollsTable.jsx
bbb-learning-dashboard/src/services/UserService.js

Fixes a few errors encountered in Dashboard, maybe after [8bffc](https://github.com/bigbluebutton/bigbluebutton/pull/14081) (?).

fix(Dashboard 2.5): patch

---

bbb-learning-dashboard/src/App.js

Fix the average activity score calculation to avoid a possible 'infinity'.
None

fix(Dashboard): average activity score

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx

- Fix a potential infinite loop that crashes the client when the `defaultWelcomeMessage` and `defaultWelcomeMessageFooter` are empty.
Closes #14118

fix: infinite loop in chat component

---

bigbluebutton-html5/imports/ui/components/error-boundary/component.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx

This PR uses the  error boundary component  to wrap the chat and show I more meaningful message to errors and log it to server to make easy the debug of any issue on chat

Wrap the chat with the error Boundary component and add the Logger to it

---

record-and-playback/screenshare/scripts/screenshare.yml

Closes #13356
The use of bbb-playback-screenshare is required in my case, and some peoples seems to need it.

fix(recording): not processed screenshare

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx

Plays the chat notification sound and displays toast for messages when the panel is open.
~Partially Closes #11042~
Closes #11042

Play Audio Alerts For Chats While Panel Is Open

---

record-and-playback/presentation/scripts/publish/presentation.rb

fix(recording): fix publish crash when poll has no options/answers

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

_Add check to avoid undefined values_
Closes #14188

fix: Add check to avoid undefined previous slide

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Updates npm dependencies to resolve npm audit alerts.

chore: update npm dependencies

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bigbluebutton-html5/imports/api/users-settings/server/publishers.js
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Found a more consistent space in bbb-web to merge the userdata, without relying 
on queries and iterations over MongoDB on user join.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14139

fix(userdata): consistent breakout room userdata

---

bigbluebutton-config/bin/bbb-conf

Add bbb-pads service to bbb-conf `status`, `start` and `stop` scripts.

feat(pads): add pads to bbb-conf

---

build/packages-template/bigbluebutton/build.sh

Add bbb-pads at bigbluebutton's build packages list

fix(build): missing bbb-pads

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss
bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/styles.scss
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/styles.scss

Add a margin on buttons that are "in focus" to avoid being cut off by other
components
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14237

fix(button): add button margin

---

build/packages-template/bbb-html5/after-install.sh

Fix permissions for `settings.yml`

Fix permissions for settings.yml

---

build/packages-template/bbb-config/opts-trusty.sh

Remove trusty build script from bbb-config

Remove trusty build script

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
bigbluebutton-html5/imports/ui/components/menu/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-tests/playwright/audio/audio.js
bigbluebutton-tests/playwright/breakout/join.js
bigbluebutton-tests/playwright/chat/chat.js
bigbluebutton-tests/playwright/connectionStatus/connectionStatus.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/core/util.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/settings/language.js
bigbluebutton-tests/playwright/sharednotes/util.js
bigbluebutton-tests/playwright/user/lockViewers.js
bigbluebutton-tests/playwright/user/multiusers.js
bigbluebutton-tests/playwright/user/user.spec.js
bigbluebutton-tests/playwright/user/util.js
bigbluebutton-tests/playwright/webcam/util.js
bigbluebutton-tests/playwright/webcam/webcam.js

- Adds tests to all **Lock Viewers** options;
- Adds test to Unlock a user (viewer);
- Improves selectors and function calls;

test: Adds lock viewers tests

---

build/packages-template/bbb-etherpad/settings.json

Enable PDF, ODT and DOCX Etherpad's content exportation.

build(etherpad): add soffice path

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/service.js

Fixes audio data access in the connection status modal. Audio data object is different than expected.
Closes #14275

fix: audio data

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/RequestBreakoutJoinURLReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala
bigbluebutton-html5/imports/api/external-videos/server/streamer.js

This PR implements some constraint improvements from 2.4/2.5 which are backwards compatible with 2.3
PRs:
#13117
#13788
#13803
#13850

Backport constraint improvements to 2.3

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

- i just put a Session variable to validation if the component will be unmounted and dont setState and throw error in console
Closes #14229
When you leave of a meeting was throwing a error of component unable setState when will be unmounted

Error in console when leave meeting

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/settings/language.js
bigbluebutton-tests/playwright/settings/util.js

Improves locale test
- now the test checks if some pre-selected elements have the translation applied;
- the test should fail if there is no translation applied or if it has the wrong one;

test: Locale test improvements

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx

Prevents an issue where external video would be muted when echo test begins but would not be unmuted after echo test ends.
Closes #14190

fix: Inconsistent behaviors when muting microphone when sharing external video

---

bbb-libreoffice/docker/Dockerfile

Backport of #14318 to BigBlueButton 2.3

chore(bbb-libreoffice): Update to Libreoffice 7.2

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GuestsWaitingApprovedMsgHdlr.scala
bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js

Reverts bigbluebutton/bigbluebutton#14147
I did some preliminary bisecting for #14323 and if I'm not mistaken the PR being reverted is the culprit.

Revert "fix: Phone users to abide by guest policy"

---

bigbluebutton-html5/imports/ui/components/modal/simple/styles.scss
bigbluebutton-html5/imports/ui/stylesheets/variables/palette.scss

Add palette's overlay color as a variable
None
Improve client's customization

style: add palette's overlay color

---

bigbluebutton-html5/client/stylesheets/toggleSwitch.css

Set color as the primary variable color so it can be customized.

style(layout): toggle switch box shadow

---

bigbluebutton-html5/imports/ui/components/fallback-errors/fallback-view/styles.scss
bigbluebutton-html5/imports/ui/components/meeting-ended/styles.scss

Set elements to use the background color variable
None

style: improve background customization

---

bbb-webrtc-sfu.placeholder.sh

build: bump bbb-webrtc-sfu to v2.7.0-alpha.6
n/a
n/a
n/a

build: bump bbb-webrtc-sfu to v2.7.0-alpha.6

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SyncGetWebcamInfoRespMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
bigbluebutton-html5/imports/api/video-streams/server/eventHandlers.js
bigbluebutton-html5/imports/api/video-streams/server/handlers/webcamSync.js
bigbluebutton-html5/imports/api/video-streams/server/modifiers/sharedWebcam.js
bigbluebutton-html5/imports/api/video-streams/server/modifiers/updatedVideoStream.js

Closes https://github.com/bigbluebutton/bigbluebutton/issues/14116

fix(webcam): add state sync between bbb-html5 and akka-apps

---

bbb-webrtc-sfu.placeholder.sh

https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.7.0-alpha.8

build: bump bbb-webrtc-sfu to 2.7.0-alpha.8

---

.gitlab-ci.yml

Updates the tag of the image used by default for building packages
Closes # none
In that tag the change is https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/commit/0e016c9524efa2926246060313c8dcbf26f04845
Update of NodeJS from 14 to 16 (needed for bbb-webrtc-sfu)
I hit some issues when trying to install npm dependencies for Node 16 bbb-webrtc-sfu by using the old npm 6, so I upgraded npm to 8.4.1 and was able to install the dependencies.
This change alone is not sufficient if you are using bbb-install.sh to install a 2.5 server, you would need to re-run using changes like proposed in https://github.com/bigbluebutton/bbb-install/pull/477

build: Node 16 for SFU, NPM 8.4.1, image tag update for BBB 2.5

---

build/packages-template/bbb-freeswitch-core/before-install.sh
build/packages-template/bbb-html5/before-install.sh
build/packages-template/bbb-web/before-install.sh

Disable login for freeswitch and meteor users when creating their accounts in packaging scripts.

Disable login for freeswitch and meteor users

---

bigbluebutton-html5/private/config/settings.yml

Updates bbbServerVersion to 2.5 in settings.yml
Closes # none

chore: updated bbbServerVersion to 2.5

---

build/packages-template/bbb-html5/build.sh

Edits settings.yml in the bbb-html5 package at build time to swap the placeholder `HTML5_CLIENT_VERSION` with the build number.
"html5ClientBuild: HTML5_CLIENT_VERSION"
Closes # none
When I test this locally it always results in `html5ClientBuild: 1`, so mileage may vary.

build: Set bbb-html5 client built in settings.yml

---

bigbluebutton-config/bin/apply-lib.sh

Backport of #14398 Thanks @sebastianberm

fix: Typo in appy-lib #14398

---

build/packages-template/bbb-pads/after-install.sh

Set public.pads.url for bbb-pads

Set public.pads.url for bbb-pads

---

bigbluebutton-config/bin/bbb-conf

fix: set public.pads.url instead of public.note.url in bbb-conf

---

build/packages-template/bbb-pads/after-install.sh

Let `bbb-conf` set `public.pads.url`.

removed in favour of #14412

---

build/packages-template/bbb-config/after-install.sh
build/packages-template/bbb-pads/opts-bionic.sh

Make bbb-pads dependent on bbb-web; fix permissions for bbb-fsesl-akka logs

Make bbb-pads dependent on bbb-web; fix permissions for bbb-fsesl-akka logs

---

bigbluebutton-tests/playwright/connectionStatus/connectionStatus.js
bigbluebutton-tests/playwright/connectionStatus/connectionStatus.spec.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/playwright.config.js
bigbluebutton-tests/playwright/settings/util.js

This PR does the following:
- apply some fixes to make test specs work with 2.5 (selectors + feature-related fixes)
- make the tests run on all 3 browsers by default.
Some fixes include the use of `aria-label`, which is most likely a temporary workaround.

test: Playwright adjustments for 2.5

---

bbb-learning-dashboard/src/components/UserDetails/component.jsx

Changes the way that the 'Average' column is calculated. Calculates it as average of total activity rather than average of activity points.
This is a missing part of https://github.com/bigbluebutton/bigbluebutton/pull/14365

fix(Dashboard): average column calculation

---

build/packages-template/bbb-html5/after-install.sh

Replacing the value for `bbbServerVersion` with the correct version for the BBB release
Closes # none
Reported by @sergey-balychev in https://github.com/bigbluebutton/bigbluebutton/pull/14281#issuecomment-1046106942

build: set BBB full version in settings.yml

---

bbb-playback.placeholder.sh

Accumulated changes since the previous defined version:
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v2.3.4
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v2.3.5
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.0.0
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.1.0
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.1.1
- https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.2.0

build(playback): bump version

---

bigbluebutton-html5/imports/ui/components/waiting-users/styles.js

Removes extra unused styles from guest waiting list.
Closes #14472

fix: Not able to see the guest waiting list, blocked view

---

bigbluebutton-config/bin/bbb-conf
bigbluebutton-html5/deploy_to_usr_share.sh
bigbluebutton-html5/docker-entrypoint.sh

Drops usage of obsolete settings-production.json
Closes # none
settings-production.json was last used in BBB 2.2

refactor(bbb-config): drop usage of obsolete settings-production.json

---

bigbluebutton-html5/imports/ui/components/components-data/users-context/service.js
bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx

Reduces the number of renders in userlist when many users are joining/leaving at the same time, improving performance.
https://user-images.githubusercontent.com/3728706/156049263-3b72ef99-9a1e-4ab4-8014-fec296c48790.mov
https://user-images.githubusercontent.com/3728706/156049293-2b8ccc04-16e9-4e45-b243-ef0fc8f6ac1e.mov

refactor: improve userlist performance

---

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx

_Backport of_ https://github.com/bigbluebutton/bigbluebutton/pull/14454

[2.4] fix: breakout room 'shortName'

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/AudioFloorChangedRecordEvent.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala

Include at the meeting's recorded events the audio floor changed event.
Partially https://github.com/bigbluebutton/bigbluebutton/issues/14213

feat(events): add audio floor change

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Reduce the number of guest status' polls per minute.
None

refactor(guest): increase polling interval

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx

Fixes an issue with the userlist not being updated when lock users is changed.
Closes #14501

fix: See other viewers in the Users list" lock viewer option is not working 

---

bbb-webrtc-sfu.placeholder.sh

buiild: bump bbb-webrtc-sfu to v2.7.0-beta.1

buiild: bump bbb-webrtc-sfu to v2.7.0-beta.1

---

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx

Fix problem related in #14545.

fix: meeting crashing when trying to end

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-placeholder/component.jsx
bigbluebutton-html5/public/locales/en.json

- changes presentation placeholder message to "There is no currently active presentation"
- hides presentation placeholder in smart layout.
Closes #14376

Change presentation placeholder message and behavior

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/StartPollReqMsgHdlr.scala
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/polling/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
bigbluebutton-html5/imports/ui/services/features/index.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Add new feature to disableable list: `polls`

feat: Support to disable polls via disabledFeatures

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StartExternalVideoPubMsgHdlr.scala
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/services/features/index.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Add new feature to disableable list: `externalVideos`

feat: Support to disable external videos via disabledFeatures

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/message-form/component.jsx
bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/notification/component.jsx
bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
bigbluebutton-html5/imports/ui/services/features/index.js
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Add new feature to disableable list: `chat`

feat: Support to disable chat via disabledFeatures

---

bbb-learning-dashboard/package-lock.json

Changes after running `npm audit fix`.

chore(Dashboard): fix npm dependencies

---

bigbluebutton-html5/public/locales/en.json

I added texts to translate in en.jon which will be used a translalations in the mobile application.
Translate texts in the mobile aplicattion

translations to mobile app

---

build/packages-template/bbb-freeswitch-sounds/build.sh

Replace "you are now muted" and "you are now unmuted" with sounds from [senfcall.de](https://gitlab.senfcall.de/senfcall-public/mute-and-unmute-sounds) (thanks!).
Fix #9352

replace muted/unmuted with sounds from senfcall.de (thanks)

---

build/packages-template/bbb-freeswitch-sounds/build.sh

Add back lines to fetch sounds.tar.gz

Add back lines to fetch sounds.tar.gz

---

build/packages-template/bbb-freeswitch-sounds/build.sh

Reduce volume for mute/unmute sound

Reduce volume for mute/unmute sound

---

bbb-api-demo/README
bigbluebutton-config/bin/bbb-conf
build/deb-helper.sh
build/packages-template/bbb-demo/opts-bionic.sh

Changes the tomcat user to tomcat10
Goes together with an upcoming change for bbb-install-2.5.sh
Closes # partially #14519
#14519

build and conf: Upgrade tomcat8 to 10 for bbb-demo

---

build/packages-template/bbb-web/build.sh

Tweak the URL for artima.com/releases to use https, not http
Closes # none
Trips up the installation process on JVM 11
- similar to https://docs.bigbluebutton.org/2.4/dev.html#developing-bbb-web

fix: set repo.artima.com/releases to https

---

bigbluebutton-web/pres-checker/build.gradle

Fixes the building of `pres-checker` component of bbb-web. Follow up from #14611
Closes # none
Had missed this portion when trying to build bbb-web locally in #14611 so the builds (remotely) were failing

build: handle bbb-web pres-checker

---

bigbluebutton-web/build.gradle

Excludes a duplicated library because of which bbb-web could not start
```
/usr/share/bbb-web/WEB-INF/lib# grep -irn InterceptorRegistry
Binary file spring-webmvc-5.3.12.jar matches
Binary file micronaut-aop-3.0.3.jar matches
```
credits: @GhaziTriki !!! :heart:  Thank you, Ghazi!
Closes #none

fix: bbb-web exclude micronaut-aop-3.0.3.jar

---

build/packages-template/bbb-demo/after-remove.sh
build/packages-template/bbb-etherpad/after-remove.sh
build/packages-template/bbb-html5/after-remove.sh
build/packages-template/bbb-learning-dashboard/after-remove.sh
build/packages-template/bbb-lti/after-remove.sh
build/packages-template/bbb-lti/build.sh
build/packages-template/bbb-playback-notes/after-remove.sh
build/packages-template/bbb-playback-notes/build.sh
build/packages-template/bbb-playback-podcast/after-remove.sh
build/packages-template/bbb-playback-podcast/build.sh
build/packages-template/bbb-playback-presentation/after-remove.sh
build/packages-template/bbb-playback-presentation/build.sh
build/packages-template/bbb-playback-screenshare/after-remove.sh
build/packages-template/bbb-playback-screenshare/build.sh
build/packages-template/bbb-playback/after-remove.sh
build/packages-template/bbb-playback/build.sh
build/packages-template/bbb-record-core/after-remove.sh
build/packages-template/bbb-record-core/build.sh
build/packages-template/bbb-web/after-remove.sh
build/packages-template/bbb-web/build.sh
build/packages-template/bbb-webhooks/after-remove.sh
build/packages-template/bbb-webhooks/build.sh
build/packages-template/bbb-webrtc-sfu/after-remove.sh
build/packages-template/bbb-webrtc-sfu/build.sh

Reverts an attempt to clean up on package removal. The cleanup of .nginx files was also triggered on package upgrade.
Closes #
We don't want .nginx files to go missing on package upgrade
Thanks to @prlanzarin for reporting the issue

build: do not delete .nginx file, it is removed on upgrade too

---

bbb-api-demo/build.gradle

Changes `compile` to `implementation` in build.gradle for `bbb-demo` to recover the build process. This was required by the upgrade of gradle/grails/etc in #14611 
Closes #none
bbb-demo package could not build

build: recover building bbb-demo

---

bbb-webrtc-sfu.placeholder.sh

build: bump bbb-webrtc-sfu to v2.8.0-alpha.1

build: bump bbb-webrtc-sfu to v2.8.0-alpha.1

---

bigbluebutton-tests/playwright/package-lock.json
bigbluebutton-tests/playwright/package.json
bigbluebutton-tests/puppeteer/package-lock.json
bigbluebutton-tests/puppeteer/package.json

- fix audit alerts with `npm audit fix`;
- updates packages to latest version;
- removes unused packages;

test: Update dependencies

---

build/packages-template/bbb-freeswitch-core/after-install.sh
build/packages-template/bbb-freeswitch-core/opts-focal.sh

Ensure that `local_ip_v4` in `/opt/freeswitch/etc/freeswitch/vars.xml` has a value for iP address. 
Closes #14670

Update vars xml

---

bigbluebutton-html5/imports/ui/components/whiteboard/annotation-factory/reactive-annotation/container.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/annotation-factory/reactive-annotation/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/container.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx

Makes the whiteboard text tool send annotation updates.
Partially reverts 40b18b0662b0d11ce109a1ffb703a4057de99840.
Thanks to @Arthurk12

refactor(whiteboard): text tool updates

---

build/packages-template/bbb-record-core/after-install.sh
build/packages-template/bbb-record-core/build.sh
build/packages-template/bbb-record-core/opts-focal.sh
record-and-playback/core/scripts/rap-starter.rb
record-and-playback/core/systemd/bbb-rap-caption-inbox.service
record-and-playback/core/systemd/bbb-rap-resque-worker.service
record-and-playback/core/systemd/bbb-rap-starter.service

- uses Ubuntu's bundler version
- vendors all required gems
- all of that now happens at build time

make bbb-record-core package install again on focal

---

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js

Prevent removal of user connections and sessions before the user be removed from DB in the Frontend.
*Details:*
On receiving `UserLeftMeetingEvtMsg`, frontend server will create an observer to check when user was removed from db, and then it kill his connections and sessions.
Closes #12080

fix: Ejected user keep trying to reconnect

---

.gitlab-ci.yml
build/packages-template/bbb-record-core/build.sh

Install `ruby-bundler` and `libsystemd-dev` as part of the container used in package building, rather than installing them on each build of `bbb-record-core`
Closes #none
Optimization; Handling a TODO from the scripts
Follow up from #14662
Goes together with https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/commit/bd48d9e0c21fc79bdc643bfce382f9149a974459

build: move ruby-bundler libsystemd-dev to docker image

---

bbb-playback.placeholder.sh
bigbluebutton-html5/public/locales/en.json

[add theme toggle's locale](https://github.com/bigbluebutton/bigbluebutton/commit/1949da3513ea5579bf71ae7ca900d67b85ff2144)
> Reference: https://github.com/bigbluebutton/bbb-playback/pull/183
[bump to v3.4.0](https://github.com/bigbluebutton/bigbluebutton/commit/222517e77374ae0c84c14c7f1b8b6d73e2576d7a)
> Accumulated changes:
>  - https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.3.0
>  - https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.3.1
>  - https://github.com/bigbluebutton/bbb-playback/releases/tag/v3.4.0
None

build(playback): update to v3.4.0

---

bigbluebutton-html5/imports/startup/client/base.jsx

Removes spurious console.log in bbb-html5's base.jsx.
None
n/a
n/a

fix: remove spurious console.log in base.jsx

---

.gitlab-ci.yml
build/packages-template/bbb-freeswitch-sounds/build.sh

Moving the installation of package `sox` (which is used in bbb-freeswitch-sounds` build) to the docker image used during building. https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/commit/bef5e043a9a14272869d6e08417f1fc041354a15
Closes #
For some reason I was not able to build bbb-freeswitch-sounds on a new setup due to
```
+ apt-get install -y sox
(...)
E: Unable to locate package sox
```

chore: move sox dependency to Dockerfile

---

bigbluebutton-html5/imports/ui/components/common/toast/styles.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js

Fixes styles of the 'Current presentation' toast.
Closes #14443

fix: toast notification style

---

bbb-learning-dashboard/package-lock.json

* Updates some npm dependencies
* updated package-lock.json with npm version 8.5.x (to match the npm version used in package creation, so that npm dependencies are correctly handled)
Closes # none

chore: npm update deps learning dashboard

---

.gitlab-ci.yml
bbb-learning-dashboard/package-lock.json
bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js
bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/common/toast/styles.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/container.jsx
bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
build/packages-template/bbb-freeswitch-sounds/build.sh

Closes # none
Regular propagation of improvements from BBB 2.5 to upsteam (develop branch)

chore: Merge 2.5.x into 'develop'

---

SECURITY.md

Clarifies on the maintained versions of BBB
Closes # none
We were listing multiple unsupported versions. Now it says version 2.2 or earlier

docs: Dropped redundant 2.0 or earlier unsupported

---

bbb-learning-dashboard/deploy.sh
bbb-learning-dashboard/run-dev.sh
bigbluebutton-html5/run-dev.sh

Moving on with #14713.
This PR will:
- Add `bbb-learning-dashboard/deploy.sh`
- Add `bbb-learning-dashboard/run-dev.sh`
- Small improvement to `bigbluebutton-html5/run-dev.sh`

feat: Add scripts to run and deploy Learning Dashboard

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx

fix(presentation snapshot): function to get ref instead of ref directly

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx

`forEach` instead of `map`. We don't need the return value.
Avoids SonarCloud warnings.
Closes # none

fix: forEach instead of map

---

bigbluebutton-html5/imports/ui/components/pads/content/component.jsx
bigbluebutton-html5/imports/ui/components/pads/content/styles.js

This PR removes the `dangerouslySetInnerHTML` from the list shared notes viewing mode and use a iframe instead

refactor: Refactor shared notes viewing mode

---

bbb-pads.placeholder.sh

Update `bbb-pads` version.
The new `bbb-pads` version includes an extra layer of fault tolerance
upon repeated command events that trigger Etherpad's API calls.
Issue reference https://github.com/bigbluebutton/bigbluebutton/issues/14757
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.1.0

chore(pads): v1.1.0

---

bigbluebutton-config/bin/bbb-conf

Reverts bigbluebutton/bigbluebutton#14791
We'll apply on the `v2.5.x-release` branch first

Revert "Update securitySalt (shared secret) in bbb-web.properties"

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js
bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx

Makes it possible to cancel webcam sharing while connecting.
Simplifies button state logic.
Closes #14739

refactor(webcam): cancellable button

---

bbb-playback.placeholder.sh

Update `bbb-plaback` version.
Style changes and dependencies updated.
https://github.com/bigbluebutton/bbb-playback/pull/189

chore(playback): v3.4.1

---

bigbluebutton-config/bin/bbb-conf

Closes #13891
Re-sending #14791 but against branch `v2.5.x-release` and with a typo fixed

fix(bbb-conf): Update securitySalt (shared secret) in bbb-web.properties

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js

Merges v2.4.x-release branch into v2.5.x-release and resolves conflicts.

chore: Merge 2.4 into 2.5

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.js

_Aligns the time of the message with the user name._
Before:
After:

fix: chat message time alignment

---

bigbluebutton-html5/package-lock.json

Updates package-lock.json to be more compatible with npm 8.5.x
Closes #14785
#14785
Also package-lock.json with `lockfileVersion: 2` is supposed to save us some time when building (we now use npm 8.5.x for bbb-html5 package creation) Possibly some newer capabilities are enabled too

chore: update package-lock.json for lockfileVersion: 2

---

bigbluebutton-html5/public/locales/en.json

- It add texts to translate in en.jon which will be used a translalations in the mobile application.
- Translate texts in the mobile aplicattion

refactor: Edit mobile translations (WIP)

---

bigbluebutton-html5/imports/ui/components/user-list/custom-logo/styles.js

style: increase logo area size to 3rem

---

bigbluebutton-html5/package-lock.json

Updates npm dependency `async`
Closes #none

chore: bump up version of npm async

---

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx

Refactor of assignment inside expression in `chat-dropdown` component, reported by [SonarCloud](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=bigbluebutton_bigbluebutton&open=AXs7rKeRxOOdclLhaxeK).
_Expected an assignment or function call and instead saw an expression._
_Any statement (other than a null statement, which means a statement containing only a semicolon ;) which has no side effect and does not result in a change of control flow will normally indicate a programming error, and therefore should be refactored._

refactor: assignment in expression

---

bbb-learning-dashboard/src/App.js

[2.5] fix(Dashboard): apply charset=UTF-8 to csv data

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/styles.js

Merges v2.5.x-release branch into develop branch.

chore: merge 2.5 into develop

---

bbb-learning-dashboard/package-lock.json

Run `npm audit fix` in Dashboard directory.

chore(Dashboard): npm audit fix

---

bbb-learning-dashboard/package-lock.json

Run `npm audit fix` in Dashboard directory.

[2.4] chore(Dashboard): npm audit fix

---

bbb-webrtc-sfu.placeholder.sh

Bump bbb-webrtc-sfu to v2.6.14.
n/a
n/a

build: bump bbb-webrtc-sfu to v2.6.14

---

.github/workflows/automated-tests.yml
bigbluebutton-tests/playwright/breakout/breakout.spec.js
bigbluebutton-tests/playwright/playwright.config.js

This implementation adds the execution of automated tests in github workflows.
To do it, the workflow is configured to:
1. Build packages
2. Install BBB from these packages
3. Execute automated tests marked with `@ci`

test,chore: Add github workflow to run automated tests

---

bigbluebutton-html5/imports/startup/server/index.js
bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Backporting "refactor: Remove the endpoint html5/useragent" #14886 to 2.3

fix: Backport refactor: Remove the endpoint html5/useragent #14886

---

bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/Card.jsx
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UserDetails/component.jsx

Changes required by linter.
Closes # none

fix(Dashboard): changes required by linter

---

bigbluebutton-html5/imports/ui/components/user-list/service.js

Prevents an issue where users that left the meeting would appear in userlist.
Closes #14742

fix: User who left the meeting sometimes remains in some user lists

---

bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/Card.jsx
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UserDetails/component.jsx

Reverts bigbluebutton/bigbluebutton#14892
Caused empty spaces in the URLs for some links. We'll re-do this

Revert "fix(Dashboard): changes required by linter"

---

bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js

- [fix(audio): abide to signalCandidates configuration flag](https://github.com/bigbluebutton/bigbluebutton/commit/6a0e0a87c2f86843255b70ba043c2f987ba73d48)
* Yet another configuration flag handler missing
n/a
n/a
n/a

fix(audio): abide to signalCandidates configuration flag

---

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/styles.js
bigbluebutton-html5/imports/ui/components/external-video-player/subtitles/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/subtitles/styles.js
bigbluebutton-html5/imports/ui/components/reload-button/styles.js
bigbluebutton-html5/public/locales/en.json

Before this PR the viewers couldn't enable subtitles!
Now they can enable/disable subtitles by clicking the CC button.
https://user-images.githubusercontent.com/19312495/166060158-d0ad32b6-2827-4303-b10f-bbfa285722c3.mp4
If the video is not from youtube, then the subtitles button won't be displayed.
https://user-images.githubusercontent.com/19312495/166060450-8cfe48ec-6857-495e-9d2f-2c8be4cf71fe.mp4

Implements a subtitles button for viewers.

---

bbb-learning-dashboard/.eslintrc.js
bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/Card.jsx
bbb-learning-dashboard/src/components/StatusTable.jsx
bbb-learning-dashboard/src/components/UserDetails/component.jsx

As described in https://github.com/bigbluebutton/bigbluebutton/pull/14918, the previous attempt to fix linting issues (https://github.com/bigbluebutton/bigbluebutton/pull/14917) resulted in bugs. This PR handles that bugs.

fix(Dashboard): some changes required by linter

---

bigbluebutton-html5/imports/ui/components/video-provider/service.js

- [refactor(webcam): remove unused code in video-provider/service](https://github.com/bigbluebutton/bigbluebutton/commit/bdd781e6477ec1e03a07f5c0cb485af2b4402010)
none
>    // to be used soon (Paulo)
:+1: 
n/a

refactor(webcam): remove unused code in video-provider/service

---

bbb-webhooks/callback_emitter.js
bbb-webhooks/config/default.example.yml
bbb-webhooks/hook.js
bbb-webhooks/id_mapping.js
bbb-webhooks/logger.js
bbb-webhooks/messageMapping.js
bbb-webhooks/package.json
bbb-webhooks/test/test.js
bbb-webhooks/userMapping.js
bbb-webhooks/web_hooks.js
bbb-webhooks/web_server.js

Backports updates of [bigbluebutton/bbb-webhooks](https://github.com/bigbluebutton/bbb-webhooks) repository.
Which includes dependencies updates and 2 new features:
- https://github.com/bigbluebutton/bbb-webhooks/pull/3
- https://github.com/bigbluebutton/bbb-webhooks/pull/5

chore: Backport (bbb-webhooks 2.3.0) updates to BBB 2.3

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Remove old reference to phone icon in `bigbluebutton-web/grails-app/conf/bigbluebutton.properties`

Remove old reference to phone icon

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx

Recomputes row heights not only for system messages but also for user messages.
Closes #14369

[2.5] fix(chat): recompute row height for message items

---

bigbluebutton-html5/public/compatibility/kurento-utils.js

The code was marked for review since 2018 - isn't necessary anymore and was triggering a static code analysis alert as well. Simplified it to a good extent.
Also removed some trailing whitespaces from the file so that my editor stops bothering me.
None
heh
n/a

refactor: remove play and retry code from kurento-utils

---

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js

- Fixes an issue where subsequent failures might lead to wrong error codes being
reported;
- Splits the screen sharing bridge stop method into a reconnect-safe version and
a public one - should also address some quirks with inbound stream re-connection.
None
n/a
n/a

fix(screenshare): properly reset connection attempts on stop

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/component.jsx

fix(webcam): fix reconnecting spinner
Fix loading spinner not spinning
Probably break after the styled-components implementation
fix(webcam): joined value
Add correct prop types to user-status
Fix an issue with prop-types related to https://github.com/bigbluebutton/bigbluebutton/pull/14590

fix(webcam): spinner and prop types

---

bigbluebutton-tests/playwright/README.md

This PR adds a couple of extra sentences to `README.md` (`npx playwright install-deps` command + Node version).

test: minor README update

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx

Cherry-pick #14991 into 2.6.
Don't know when the next merge is scheduled. If very soon, close this when the merge PR supersedes it.
n/a
n/a
n/a

[2.6] fix: client crash on meeting end/user left with cameras

---

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/styles.js
bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu-item/styles.js

_Fixes border-radius of whiteboard toolbar buttons._
Before
After
---
Before
After (remains the same as before)
Closes #15009

[2.5] fix(whiteboard): border-radius of toolbar buttons #15009

---

bbb-pads.placeholder.sh

Update `bbb-pads` version.
https://github.com/bigbluebutton/bigbluebutton/issues/15025
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.2.1

build(pads): v1.2.1

---

bigbluebutton-html5/private/static/guest-wait/guest-wait.html

Before this PR, when the viewer gets denied and refreshes the page, it returns a confusing message.
Now, when the viewer refreshes the page, it returns a clear message saying to wait, and then it shows the user was denied of joining the meeting.
CLOSES #14992

Changed the loading message to be more understandable.

---

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js

Prevents a crash that happens in breakout rooms when the "message all rooms" feature is used.

fix: export chat crash on breakout room

---

.github/workflows/automated-tests.yml
bigbluebutton-tests/playwright/breakout/breakout.spec.js
bigbluebutton-tests/playwright/playwright.config.js

Backport #14880 to BBB 2.5
It contained `on.push.branches` v2.5.x-release, but we did not have the actual workflow present on the branch :smile: 
Credits once again go to @TiagoJacobs

ci: Add github workflow to run automated tests (was #14880)

---

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/breakout-room/styles.js
bigbluebutton-html5/imports/ui/components/captions/component.jsx
bigbluebutton-html5/imports/ui/components/captions/styles.js
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/component.jsx
bigbluebutton-html5/imports/ui/components/chat/styles.js
bigbluebutton-html5/imports/ui/components/common/button/styles.js
bigbluebutton-html5/imports/ui/components/common/control-header/component.jsx
bigbluebutton-html5/imports/ui/components/common/control-header/left/component.jsx
bigbluebutton-html5/imports/ui/components/common/control-header/left/styles.js
bigbluebutton-html5/imports/ui/components/common/control-header/right/component.jsx
bigbluebutton-html5/imports/ui/components/common/control-header/right/styles.js
bigbluebutton-html5/imports/ui/components/common/control-header/styles.js
bigbluebutton-html5/imports/ui/components/notes/component.jsx
bigbluebutton-html5/imports/ui/components/notes/styles.js
bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/styles.js
bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
bigbluebutton-html5/imports/ui/components/waiting-users/styles.js

UI polishing of sidebar content panel header buttons.
Default styles
Hover styles
Focus styles
Closes #15030

refactor: sidebar content panel UI polishing

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
bigbluebutton-html5/imports/ui/components/common/button/button-emoji/styles.js
bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx

**Before**
**After**
Closes #15068

fix: point media button chevrons upwards

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala

Ensure that user is a participant of the chat that he's sending a message
Make more clear who can send a message in the chat

Make sure that user is in a chat participant when send a message

---

bigbluebutton-html5/imports/ui/components/chat/container.jsx

Make sure that the right text will be shown in user left message
Make chat message prettier

Make sure do not show wrong data in user left message

---

akka-bbb-fsesl/build.sbt

Changes the target from Java8 to 11, similar to #14611
Missed in https://github.com/bigbluebutton/bigbluebutton/pull/14611

fix: set target to jvm-1.11 in akka-bbb-fsesl

---

bigbluebutton-html5/imports/api/voice-users/server/handlers/leftVoiceUser.js

fixes issue #14969. `removeUser` was called with wrong parameters
Closes #14969 
Dial in is super important :-)

Fix: voice users not removed from participants list

---

bbb-learning-dashboard/package-lock.json

Runs `npm audit fix` on Dashboard directory.
None
n/a
n/a

chore(Dashboard): run npm audit fix

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/chat/container.jsx
bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/screenreader-alert/collection.js
bigbluebutton-html5/imports/ui/components/screenreader-alert/component.jsx
bigbluebutton-html5/imports/ui/components/screenreader-alert/container.jsx
bigbluebutton-html5/imports/ui/components/screenreader-alert/service.js
bigbluebutton-html5/imports/utils/dom-utils.js
bigbluebutton-html5/imports/utils/string-utils.js

this PR backport of 2.4 of:
#14755
#15067
#15087

fix: Remove use of innerHTML, dangerouslySetInnerHTML etc

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

* Move multiuser whiteboard button to presentation toolbar.
* Set zoom increments to 10%.
* Hide cursors when moved outside the whiteboard.
* Disable panning for users without whiteboard access.

feat(whiteboard): Move Multiuser Whiteboard Button to Presentation Toolbar

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/styles.js

Fix the problems described here https://github.com/bigbluebutton/bigbluebutton/pull/14938#pullrequestreview-966966502
- Hide icons when squeezed
- Remove little gap between video and border
- ~Change webcam loading background color~
- ~Change webcam letterbox color~
- Align user status icons to match other icons paddings/margins
- Prevent state update on an unmounted component
https://github.com/bigbluebutton/bigbluebutton/pull/14938#pullrequestreview-966966502
https://user-images.githubusercontent.com/42683590/171046083-97607096-0dfc-4a45-8828-1ada52efcf86.mp4
https://user-images.githubusercontent.com/42683590/171046094-8c968e07-125c-427c-8e6d-148376872851.mp4

feat(webcam) camera avatar polishment

---

bbb-webhooks.placeholder.sh

Updates `bbb-webhooks` version.
https://github.com/bigbluebutton/bbb-webhooks/releases/tag/v2.6.0

build(webhooks): v2.6.0

---

bigbluebutton-html5/imports/ui/components/actions-bar/styles.js
bigbluebutton-html5/imports/ui/components/common/button/styles.js
bigbluebutton-html5/imports/ui/stylesheets/styled-components/palette.js

Updates primary circle button styles.
https://user-images.githubusercontent.com/3728706/170778992-eb83a118-d770-41c8-afa8-8a39dac6f188.mp4
https://user-images.githubusercontent.com/3728706/170778983-5906a4b9-6b8f-48b5-8319-433893850769.mp4
Closes #7653
Closes #7698

style: Revised styles for our primary circle buttons

---

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx
bigbluebutton-html5/imports/ui/components/common/button/styles.js
bigbluebutton-html5/imports/ui/components/common/modal/fullscreen/styles.js
bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/modal/styles.js

Updates primary button styles and adjusts buttons with incorrect color (audio modal, settings modal, external video modal).
Closes #7744

style: Revised styles for our primary button

---

bigbluebutton-tests/playwright/settings/util.js

Minor node version compatibility fix (backport of [this fix](https://github.com/bigbluebutton/bigbluebutton/commit/6146971c40ee03774db2fd57fb948466eff6717a#diff-1e883995fe11dbaf3f750ec29016da05755afc135f59f7aa436238599fed6c5e))

test: node version compatibility fix

---

.github/ISSUE_TEMPLATE/config.yml

Fix typo in the issue template chooser
Closes #

Fix typo in the issue template chooser

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

Adds 'new message' indicators for poll result messages. Poll results will count as unread messages. The indicators won't be displayed for presenters.
_User 1 (presenter)_
_User 2_
_User 2_
_User 1 (presenter)_
Closes #15113
n/a
n/a

fix(chat): show new message indicators for poll mesages

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/utils/hooks/index.js

Fixes duplication of the popup notification of the first chat message.
Closes #15088
n/a
n/a

fix(chat notification): duplication of first message notification

---

bbb-learning-dashboard/src/components/UsersTable.jsx

_Makes username look more clickable._
Normal
Focus
Hover
Focus+Hover
Focus+Active
Closes #15122 
n/a
n/a

fix(Dashboard): make username look more clickable

---

bigbluebutton-html5/imports/ui/components/breakout-room/service.js

fix(audio): moderator not able to transfer audio to breakout room

---

SECURITY.md

Changes the Security policy to specify that we no longer maintain BBB 2.3
BigBlueButton 2.5 is the recommended version to install on a new server. 2.4 is still supported (until 2.6.0 is released)
Closes # none

docs: set 2.5 as the recommended version, discontinue 2.3

---

bigbluebutton-html5/imports/ui/components/poll/container.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/container.jsx

Restores current-poll subscription update frequency (regression caused by #15143)

fix: secret poll value not recalculated

---

bbb-learning-dashboard/src/services/UserService.js

Adjusts user join/left times formatting in learning dashboard "save session data" feature.
Closes #15199

fix: Learning Dashboard downloaded data wrong join and left time values

---

bigbluebutton-html5/transifex.sh

Adjusts the URLs used in `transifex.sh` to point to the newly created 2.6 Transifex project
Closes # none
Going through the steps to prepare for BBB 2.6.0-alpha.1

fix: tweak transifex.sh to the new 2.6 Transifex project

---

bbb-pads.placeholder.sh

Bump bbb-pads to v1.2.2.
n/a
n/a
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.2.2

build(pads): v1.2.2

---

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx

This is a backport of PR https://github.com/bigbluebutton/bigbluebutton/pull/14841 from 2.6 to 2.5.
_Refactor of assignment inside expression in chat-dropdown component, reported by SonarCloud._
_Expected an assignment or function call and instead saw an expression._
_Any statement (other than a null statement, which means a statement containing only a semicolon ;) which has no side effect and does not result in a change of control flow will normally indicate a programming error, and therefore should be refactored._

refactor: assignment in expression (2.5)

---

bbb-webrtc-sfu.placeholder.sh

- See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.3
- See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.4
n/a
n/a
n/a

build(bbb-webrtc-sfu): v2.8.4

---

bbb-webrtc-sfu.placeholder.sh

See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-alpha.2
n/a
n/a
n/a

build(bbb-webrtc-sfu): v2.9.0-alpha.2

---

bigbluebutton-config/bin/bbb-conf

Porting #15265 to `v2.6.x-release` so that we can support an upgrade of BBB 2.5.2 -> 2.6.0-alpha.1
Credits: @GuiLeme

fix(bbb-conf): Change in bbb-conf to not rely on tomcat (port of #15265)

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/drag-and-drop/component.jsx

Adds a check for potential undefined `userId`.

fix: add check for potential undefined userId

---

bigbluebutton-tests/playwright/core/helpers.js

Drops unnecessary join api parameter `joinViaHtml5`
Closes # none
joinViaHtml5=true is pretty much retired, has not been needed for long time

test: drop unnecessary joinViaHtml5=true

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/cursors/container.jsx
bigbluebutton-html5/package.json

Fix cursors not updating for mobile users and removes the `react-cursor-position` package.
Also [[2.6] MultiUser wb username label displayed when multiuser is off](https://github.com/bigbluebutton/bigbluebutton/issues/15271#)
#15271 , #15275

Fix Cursor Not Updating For Mobile

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx

Restores audio mute/unmute/leave shortcuts.

fix: audio shortcuts regression

---

bigbluebutton-html5/imports/ui/components/cursor/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/service.js

This is a port of whiteboard annotations and cursors fixes from 2.4 to 2.5.
Includes changes made in https://github.com/bigbluebutton/bigbluebutton/pull/15262, https://github.com/bigbluebutton/bigbluebutton/pull/14964 and https://github.com/bigbluebutton/bigbluebutton/pull/15167

fix: port whiteboard annotations/cursors fixes to 2.5

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.0-alpha.4](https://github.com/bigbluebutton/bigbluebutton/commit/a467e97dccefe83d395fd0b370b4097e414b6126)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-alpha.4

build(bbb-webrtc-sfu): v2.9.0-alpha.4

---

bbb-webrtc-sfu.placeholder.sh

[build(bbb-webrtc-sfu): v2.8.5](https://github.com/bigbluebutton/bigbluebutton/commit/9231fde389ad9e2d7d684878d1342dadf3cbf46b)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.5

build(bbb-webrtc-sfu): v2.8.5

---

bbb-webrtc-sfu.placeholder.sh

[build(bbb-webrtc-sfu): v2.6.15](https://github.com/bigbluebutton/bigbluebutton/commit/8ab45053fce1fd22d9c784bf1b4013e9e118a58f)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.15

build(bbb-webrtc-sfu): v2.6.15

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
bigbluebutton-tests/playwright/audio/audio.spec.js
bigbluebutton-tests/playwright/breakout/breakout.spec.js
bigbluebutton-tests/playwright/chat/chat.spec.js
bigbluebutton-tests/playwright/connectionStatus/connectionStatus.js
bigbluebutton-tests/playwright/connectionStatus/connectionStatus.spec.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/notifications/presenterNotifications.js
bigbluebutton-tests/playwright/polling/poll.js
bigbluebutton-tests/playwright/polling/polling.spec.js
bigbluebutton-tests/playwright/presentation/presentation.js
bigbluebutton-tests/playwright/presentation/presentation.spec.js
bigbluebutton-tests/playwright/presentation/util.js
bigbluebutton-tests/playwright/user/user.spec.js
bigbluebutton-tests/playwright/webcam/webcam.spec.js

This PR includes new test specs for presentation and connection status test suites:
- multi-presentation upload
- fit to width
- copy connection stats
- use link to settings when there's a connection issue.
It also adds test plan links to the test specs.

test: New 2.5 tests + links from test specs to 2.5 test plan

---

akka-bbb-apps/src/templates/systemloader/systemd/start-template
akka-bbb-fsesl/src/templates/systemloader/systemd/start-template

Follow up to #14616 
Closes #none
akka-apps and akka-fsesl's service files are located separately from the other build files, easy to miss.
When calling `systemctl stop bigbluebutton.target` the two of them would remain active

build: akka apps + fsesl as part of bigbluebutton.target

---

build/packages-template/bbb-export-annotations/.build-files
build/packages-template/bbb-export-annotations/build.sh
build/packages-template/bbb-html5/opts-focal.sh

Set bbb-export-annotations as a required package (for bbb-html5) just like bbb-pads is
Fixed an issue where we were not copying the package files correctly, resulting in an empty package bbb-export-annotations 
Closes #14630 -- I now know what the purpose of .build-files is! Learned it the hard way!
Follow up from #15333

build: set bbb-export-annotations as a required package (for bbb-html5)

---

build/packages-template/bbb-export-annotations/after-install.sh

Auto enables `bbb-export-annotations` service
Closes #none
I missed this part in #15333 and #15351
Without it I kept seeing
`bbb-export-annotations ► [✘ - inactive]`
until I manually ran `systemctl enable bbb-export-annotations`

build: auto-enable service bbb-export-annotations

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

Tldraw uses the constructor name for session complete names:
https://github.com/tldraw/tldraw/blob/80ed0bf27bbaa8566b230df318364dec85304d31/packages/tldraw/src/state/TldrawApp.ts#L2916
So in production they are changed because of js minifier.
I changed the onCommand reactor to be one generic for all session:complete actions.
Also fixed some crashes with grouping and ungrouping shapes, in those cases the order of adding/removing is important because children have a reference to the father (grouping shape).

fix(tldraw): fix shapes not persisting in production +

---

bigbluebutton-html5/imports/ui/components/audio/local-echo/component.jsx
bigbluebutton-html5/public/locales/en.json

[fix: change local echo Stop hearing locale to Stop audio feedback](https://github.com/bigbluebutton/bigbluebutton/commit/7b76d2e88f888385a6fc328670f0b7594c92774e)
None
Current locale is confusing.
n/a

fix: change local echo `Stop hearing` locale to `Stop audio feedback`

---

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx
bigbluebutton-html5/imports/ui/components/common/button/component.jsx
bigbluebutton-html5/imports/ui/components/common/button/styles.js
bigbluebutton-html5/imports/ui/components/common/modal/fullscreen/component.jsx
bigbluebutton-html5/imports/ui/components/common/modal/fullscreen/styles.js
bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx
bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

This PR styles some specific buttons according to Tyler's design, see it below:
Closes #7745

style: Revised styles for our secondary buttons

---

.gitignore
.gitlab-ci.yml
bigbluebutton-config/bin/bbb-conf
bigbluebutton-web/.gitignore

Removes remaining traces from bbb-demo ( follow up from #15216 )
Closes #none
follow up from #15216

refactor: further cleanup of bbb-demo

---

build/packages-template/bbb-html5/bigbluebutton.nginx

It fixes broken assets
Related to https://github.com/bigbluebutton/bigbluebutton/pull/15216

fix(config): Correction to nginx assets folder

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js

Sometimes the handler that listens for the state change in the callState is
not updated correctly.
In these rare cases, the state of the callstate changes directly to in_conference,
not taking the expected path: call_started -> in_echo_test -> in_conference
Closes https://github.com/bigbluebutton/bigbluebutton/issues/15357

fix(audio): prevent race condition when joining audio

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.0-alpha.5](https://github.com/bigbluebutton/bigbluebutton/commit/d5c63d10e568fa0f68cd999ccaba610de0fd6d24)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-alpha.5

build(bbb-webrtc-sfu): v2.9.0-alpha.5

---

.github/ISSUE_TEMPLATE/test-scenario.md

Added a template for test case tracking
Closes # none
Improve the tracking of what test cases need to be added. Allow for a developer to be marked as an assignee for it.

chore: Added a template for test case tracking

---

.github/workflows/automated-tests.yml

Suggested by @naveensrinivasan
Backports #15309 to BBB 2.5
Closes # none
Thanks to @naveensrinivasan for suggesting this in #15309 !
Unfortunatelly we still don't find CLA from them and this is an important change, and at the same time rather succint, so we're propagating it to the various branches of BigBlueButton that have ci enabled.

test: set permissions: content: read [2.5]

---

.github/workflows/automated-tests.yml
bbb-learning-dashboard/src/App.css
bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/UserDetails/component.jsx
bbb-learning-dashboard/src/utils/string.js
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx

Pulling fixes from BBB 2.5 to be included in the next release of BBB 2.6

chore: pull BBB 2.5.4+ into 2.6

---

bigbluebutton-tests/playwright/connectionStatus/connectionStatus.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/sharednotes/sharednotes.js
bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
bigbluebutton-tests/playwright/sharednotes/util.js

This PR includes new shared notes tests that type, edit and export the content.

test: new 2.5 Playwright tests for shared notes

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx

Fixes the "snapshot of current slide" feature so that it works together with the new whiteboard.
Closes #15286
Closes #15425

fix: snapshot of current slide

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

Fixes the whiteboard crashing when a viewer resizes a panel.

Prevent Viewer Panel Resize Crashing Whiteboard

---

bigbluebutton-html5/imports/ui/components/chat/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
bigbluebutton-html5/imports/utils/dom-utils.js

Adjusts chat component to correctly set the width when a resizing event happens in RTL languages.
Closes #15431

fix: chat panel resizing in RTL

---

bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/user/lockViewers.js
bigbluebutton-tests/playwright/user/status.js
bigbluebutton-tests/playwright/webcam/util.js

Fewer small updates to the test suite than initially proposed:
- "Change user status" needs to wait for the default presentation toast to clear
- versions of PR #15055 and PR #15071 for the `v2.5.x-release` branch (the other two PRs are for the `v2.4.x-release` branch)

test: Various test suite updates

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx

- Checks the virtual background index before applying the action on click.
- Prevents a crash when removing virtual background by clicking on `None`.
None

fix: check virtual background index

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.0-beta.0](https://github.com/bigbluebutton/bigbluebutton/commit/e4f0dee91e93f0026d4b4c0f89b60fef22a5affd)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-beta.0

build(bbb-webrtc-sfu): v2.9.0-beta.0

---

bbb-export-annotations/.eslintrc.js
bbb-export-annotations/config/settings.json
bbb-export-annotations/master.js
bbb-export-annotations/package-lock.json
bbb-export-annotations/package.json
bbb-export-annotations/workers/collector.js
bbb-export-annotations/workers/notifier.js
bbb-export-annotations/workers/process.js

Adds ESLint to `bbb-export-annotations` in order to enforce a consistent style.
Improve readability, maintainability, and security of the component. Refactors detected code smells and removes vulnerabilities.
Implements SonarCloud's generic fix to avoid a shell from being spawned when starting PDF-conversion related processes.
(`spawnSync` with shell set to false instead of `execSync`).

refactor: add eslint to bbb-export-annotations

---

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx

Adjusts dial-in button styles in audio modal.
https://user-images.githubusercontent.com/3728706/182912541-3089ff4a-2521-46bc-84c5-d3c31bcca9d7.mp4
https://user-images.githubusercontent.com/3728706/182912524-70478ad8-db0a-456b-b04b-00762a903140.mp4

fix(styles): adjust dial-in button styles

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

This is a port of external video and screenshare display fixes from 2.6 to 2.5.
Includes changes made in #15424 and #15455

fix: port screenshare/external video fixes to 2.5

---

bbb-pads.placeholder.sh

See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.3.0
- [build(bbb-pads): v1.3.0](https://github.com/bigbluebutton/bigbluebutton/commit/3486755df87d4fc2cede6688b90274280e2dcc78)
None
See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.3.0
See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.3.0

build(bbb-pads): v1.3.0

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.0-beta.1](https://github.com/bigbluebutton/bigbluebutton/commit/2535f346928d3c6c52bc032534510fbee41acec6)
None
n/a
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-beta.1

build(bbb-webrtc-sfu): v2.9.0-beta.1

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

Fix `isDownloadable` state regression in presentation uploader.
https://groups.google.com/g/bigbluebutton-dev/c/-vfr3vitoKg/m/wdVEElVyAgAJ

fix: presentation isDownloadable state

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx

Saves virtual background info when changing backgrounds in _Webcam settings_. The idea is to save virtual background info every time the user changes the virtual background, if the webcam is already shared. That helps to restore the correct background when the webcam is reshared.
Closes #15111

fix: restore virtual background after leaving breakout room

---

.github/workflows/automated-tests.yml

Utilizes the new `-j` bbb-install parameter to skip server requirement checks in ci (since it's not produciton)
https://github.com/bigbluebutton/bbb-install/pull/548
Closes #none
We were seeing build+test failing since https://github.com/bigbluebutton/bbb-install/commit/09c16f9bdff3408e342af1e5c6bf378d10076ba8

build: github action install to use -j skip checks

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.0](https://github.com/bigbluebutton/bigbluebutton/commit/3c4da1a9379ea9b9fb6003b3033ead63a1f0fee2)
* Full changelog: https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0
None

build(bbb-webrtc-sfu): v2.9.0

---

bigbluebutton-html5/imports/ui/components/whiteboard/service.js

Fixes calculation of number of users in multi user whiteboard. It counts all users with access to the whiteboard (presenter included).
Closes #15291

fix: incorrect calculation of number of users in multi user whiteboard

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx

This PR ensures the whiteboard toolbar is always visible / accessible on smaller sizes without overlapping other elements.

fix: Make Whiteboard Toolbar Responsive to Smaller Sizes

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPageCountErrorPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationUploadTokenReqMsgHdlr.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationPodsMsgs.scala
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/DocPageCountExceeded.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/DocPageCountFailed.java
bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
bigbluebutton-html5/imports/api/presentation-upload-token/server/handlers/presentationUploadTokenPass.js
bigbluebutton-html5/imports/api/presentation-upload-token/server/methods/requestPresentationUploadToken.js
bigbluebutton-html5/imports/api/presentation-upload-token/server/publishers.js
bigbluebutton-html5/imports/api/presentations/server/handlers/presentationConversionUpdate.js
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js

It fixes the page-count-exceed error by forwarding the `temporaryPresentationId` to the front-end.
Closes #15543
This PR is deeply connected to #15551

(fix) -  Fixed page count exeed error

---

bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx

Adds data-test props on each lock settings item

test: Data-test props in lock settings

---

bbb-libreoffice/docker/Dockerfile
bigbluebutton-html5/client/stylesheets/fonts.css
build/packages-template/bbb-html5/build.sh

Porting #15562 by @ramonlsouza to BBB 2.6

fix: preloaded fonts being requested again [2.6]

---

bigbluebutton-tests/playwright/notifications/chatNotifications.js
bigbluebutton-tests/playwright/notifications/notifications.js

Fixes the path used to link to `openSettings`
Closes #none
Noticed that ci tests on #15603 were failing

test: fix path to util openSettings

---

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx

Adjusts emoji picker button styles.
https://user-images.githubusercontent.com/3728706/185683410-5c8ca0e2-856c-4b21-b376-b60d20644042.mp4
https://user-images.githubusercontent.com/3728706/185683426-59e089d5-aa32-4130-8e10-4f20ee7a0adf.mp4

fix: emoji picker button styles

---

bbb-learning-dashboard/src/components/UserDetails/component.jsx

- https://github.com/bigbluebutton/bigbluebutton/commit/9730623c29ba2b18355a9f5d0fa172045d31ec0f: Fix hook calling order, which was pointed out by SonarCloud:
- https://github.com/bigbluebutton/bigbluebutton/commit/7859ff142a1e1477f084e2993f34719459f6635f: Rename some identifiers to be more clear.
Closes none
SonarCloud warnings.
n/a

fix(Dashboard): SonarCloud warnings

---

bigbluebutton-html5/imports/api/breakouts/server/publishers.js

Adds missing condition in breakout publisher.

fix: adjust breakout publisher

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx

Restore imports that were removed on a merge.

fix: restore imports lost on merge

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GuestPolicyValidator.java
bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/MaxParticipantsValidator.java
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

Modifies the maxParticipants calculation to only count joined users. A new maxParticipants check is done when a user moves from being entered to joined and the user is ejected if this check fails.

refactor: Modify maxParticipant calculation

---

bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/container.jsx

Fixes the following SonarCloud warnings:
Closes none

fix: SonarCloud warnings

---

bigbluebutton-config/bin/bbb-conf
build/packages-template/bbb-config/build.sh
build/packages-template/bbb-html5/after-install.sh
build/packages-template/bbb-libreoffice-docker/build.sh
build/packages-template/bbb-lti/build.sh

Selects `/usr/lib/systemd/system` over `/lib/systemd/system` for consistency
Closes #15553
https://github.com/bigbluebutton/bigbluebutton/issues/15553#issuecomment-1234395598
Thanks to @danimo for assisting!

build: /lib vs /usr/lib closes #15553

---

bigbluebutton-tests/puppeteer/package-lock.json

Fix npm audit alerts in puppeteer.

chore(tests): npm audit fix

---

bigbluebutton-html5/imports/api/breakouts/server/publishers.js

This is a port of PR #15618 from develop branch to 2.4.
_Adds missing condition in breakout publisher._

fix: port adjustments in breakout publisher to 2.4

---

bigbluebutton-config/bin/bbb-conf

Fix latest crashed warnings related to tomcat due to this PR #15265.
Related: #15306

fix(conf): Fix tomcat warnings

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx

Adds unique className to "current presentation" toasts.

refactor: Add "current presentation" toast unique class

---

bigbluebutton-html5/imports/api/breakouts/server/publishers.js

This is a port of PR #15618 from develop branch to 2.5.
_Adds missing condition in breakout publisher._

fix: port adjustments in breakout publisher to 2.5

---

bbb-playback.placeholder.sh

* chore(deps): bump terser from 5.14.1 to 5.14.2 by @dependabot in https://github.com/bigbluebutton/bbb-playback/pull/209
* fix(tldraw): respect view area width/height + by @germanocaumo in https://github.com/bigbluebutton/bbb-playback/pull/214
**Full Changelog**: https://github.com/bigbluebutton/bbb-playback/compare/v5.0.0-alpha.1...v5.0.0-alpha.2

chore(playback): v5.0.0-alpha.2

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.1](https://github.com/bigbluebutton/bigbluebutton/commit/6396c3e7bdb78ef27a1565fbdb6e50a412e73743)
* See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.1

build(bbb-webrtc-sfu): v2.9.1

---

bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/presentation/presentation.js
bigbluebutton-tests/playwright/presentation/presentation.spec.js

Implements two tests for the presentations. 
The first one is to test the upload and remove of an presentation by the same user.
The second one tests the upload and remove of an presentation but with a different user.
Closes #15540

Upload and remove presentations test

---

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/options/options.js
bigbluebutton-tests/playwright/options/options.spec.js

Implements the help button test.
Closes #

test: Help button test

---

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
bigbluebutton-tests/playwright/chat/chat.js
bigbluebutton-tests/playwright/chat/chat.spec.js
bigbluebutton-tests/playwright/chat/privateChat.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/core/settings.js

Tests for the emoji picker button and the auto-converted emoji on the public and private chat.
Closes #15478
Closes #15477

Emojis tests for the public/private chat

---

bbb-libreoffice/docker/Dockerfile

refactor (backport 2.5): Upgrade Libreoffice docker from java 11 to java 17

---

bigbluebutton-html5/client/main.jsx
bigbluebutton-html5/imports/ui/services/LiveDataEventBroker/LiveDataEventBroker.js
bigbluebutton-html5/private/config/settings.yml

This is a port of PR #15717 from 2.6 to 2.5. 
It also makes disabling xhr fallback configurable (default value: **false**, same behavior as before the changes).

fix: disable xhr fallback on websocket connection (2.5)

---

bbb-libreoffice/docker/Dockerfile
bigbluebutton-config/bin/apply-lib.sh
bigbluebutton-config/bin/bbb-conf
bigbluebutton-html5/client/main.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
bigbluebutton-html5/imports/ui/components/chat/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/services/LiveDataEventBroker/LiveDataEventBroker.js
bigbluebutton-html5/private/config/settings.yml
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
build/packages-template/bbb-html5/build.sh
record-and-playback/core/lib/recordandplayback/edl/video.rb

Merges v2.5.6 into v2.6.x-release and resolves conflicts.

chore: Merge v2.5.6 into v2.6

---

build/packages-template/bbb-html5/bbb-html5-with-roles.conf

Updates the inline instructions for default NodeJS processes for each role in bbb-html5-with-roles.conf
https://github.com/bigbluebutton/bigbluebutton/pull/12257#issuecomment-1259921277

build: update number of default servers for bbb-html5

---

bigbluebutton-html5/imports/ui/components/video-preview/styles.js

improvement: disable text selection of brightness labels

---

bigbluebutton-html5/imports/startup/server/index.js
bigbluebutton-html5/imports/startup/server/logger.js

Removes empty object from logs that do not have additional data.

fix: remove empty object in logs

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

It fixes the export pdf to chat toast, so that now it properly closes instead of loading indefinitely.
This error was created due to #15474 here is a demonstration of how it went:
https://user-images.githubusercontent.com/69865537/194619049-ee739cdb-5d9b-44d5-b6a4-20f38b209393.mov
Now it is working properly again.

(fix) - Fix toast of export to chat

---

bigbluebutton-html5/imports/startup/client/base.jsx

fix: add missing condition for showing MeetingEnded

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
bigbluebutton-html5/imports/ui/components/polling/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/public/locales/en.json

Support typed response polls in the smart slides.
[Test pdf](https://github.com/bigbluebutton/bigbluebutton/files/9767429/Untitled.presentation.pdf)
Closes #15820, #15819

Update Smart Slides to Support Typed Response Poll

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WhiteboardMsgs.scala
bigbluebutton-html5/imports/api/annotations/server/handlers/whiteboardSend.js
bigbluebutton-html5/imports/api/annotations/server/methods/sendAnnotationHelper.js
bigbluebutton-html5/imports/startup/server/redis.js
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

Backport of https://github.com/bigbluebutton/bigbluebutton/pull/15745
Code should also be compatible with 2.4

chore(whiteboard): backport of annotations dupplication fix

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
bigbluebutton-html5/imports/ui/components/polling/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/public/locales/en.json

Backports #15826 changes to 2.5.
_Support typed response polls in the smart slides._

Update Smart Slides to Support Typed Response Poll (2.5)

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx

It fixes a very specific situation where the current wouldn't be persisted. It is better described in the following issue: #15843.
Closes #15843

(fix) - Fix current not being persisted

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodHdlrs.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationUploadedFileTimeoutErrorPubMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationPodsMsgs.scala
bbb-common-web/src/main/java/org/bigbluebutton/presentation/ConversionMessageConstants.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/SvgImageCreator.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ImageToSwfSlidesGenerationService.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PageToConvert.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SwfSlidesGenerationProgressNotifier.java
bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/UploadFileTimedoutMessage.java
bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
bigbluebutton-html5/imports/api/presentations/server/eventHandlers.js
bigbluebutton-html5/imports/api/presentations/server/handlers/presentationConversionUpdate.js
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
bigbluebutton-html5/public/locales/en.json
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml

It backports changes in #15688 to `v2.5.x-release`

backport 2.5 - fix timeout error when PDF is too complex

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/imports/utils/string-utils.js

Adds custom poll functionality to the smart slides in order to pull out full option text.
Test Slides:
[Untitled presentation.pdf](https://github.com/bigbluebutton/bigbluebutton/files/9810567/Untitled.presentation.pdf)
[Smart Slides Test.pptx](https://github.com/bigbluebutton/bigbluebutton/files/9810570/Smart.Slides.Test.pptx)
Closes #15851

Add Custom Poll Functionality Via Smart Slides

---

bigbluebutton-web/build.gradle

It updates modified dependencies to newer versions

refactor (bbb-web): upgrade dependencies

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/service.js

Backports #15856 changes to 2.5.
_Adds custom poll functionality to the smart slides in order to pull out full option text._

Add Custom Poll Functionality Via Smart Slides (2.5)

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToPollReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala

This PR reinforces server-side validation of who has already responded to the poll.

refactor: Improvements in Poll validation

---

bigbluebutton-html5/imports/ui/components/presentation/service.js
bigbluebutton-html5/imports/utils/string-utils.js

Adds a check to regex used in presentation service.

refactor: check content size in smart slide feature

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Once #15860 was merged.
It add the instructions to take advantage of that option.

bbb-web: Instruction to disable default presentation

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToPollReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala

backport 2.5 - refactor (akka-apps): Improvements in Poll validation

---

bbb-common-web/project/Dependencies.scala

Upgrade Apache Commons Text to version 1.10.0.

refactor (bbb-web): Upgrade lib Apache Commons Text

---

bbb-voice-conference/config/freeswitch/conf/autoload_configs/conference.conf.xml
bbb-voice-conference/config/freeswitch/conf/autoload_configs/opus.conf.xml
bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml
bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml

This is a port of PR #15766 from 2.6 to 2.5. 
Closes #15776

Update FreeSWITCH settings for improved audio (2.5)

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala

Include validation missing in #15840.

refactor (akka-apps): Improvements in Poll validation

---

bigbluebutton-html5/imports/ui/components/breakout-room/styles.js

style: breakout item padding

---

bigbluebutton-html5/imports/ui/components/common/checkbox/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
bigbluebutton-html5/public/locales/en.json

- Update upload virtual background button and other aria description. (labels & descriptions should not be the same text)
- Remove double tab on checkbox component.
- Fix checkbox aria label.
- Fix aria descriptions on delete background buttons.
These are A11y improvements for 2.6

Video Preview Modal A11y Updates

---

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx

Adjusts the position of audio and video dropdown buttons.

style: adjust audio/video dropdown position

---

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx

Mutes external video audio when in echo test modal.
Closes #15760

fix: mute external video when in echo test

---

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
bigbluebutton-html5/imports/ui/components/shortcut-help/styles.js

- Absolute modal height.
- Table style.
Closes #15824

style: keyboard shortcuts modal

---

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/chat/alert/styles.js
bigbluebutton-html5/public/locales/en.json

Fixes chat notification for poll messages.
**After**
Closes #15865

fix: poll chat message popup notification

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.2](https://github.com/bigbluebutton/bigbluebutton/commit/30985565c11fe0051fbe177b33fca75b54f6fee2)
* See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.2
n/æ

build(bbb-webrtc-sfu): v2.9.2

---

bbb-pads.placeholder.sh

- [build(bbb-pads): v1.3.1](https://github.com/bigbluebutton/bigbluebutton/commit/ad04550cb5446804994f10a3ccae3f3bc8627dcc) 
* See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.3.1
n/æ
See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.3.1

build(bbb-pads): v1.3.1

---

build/packages-template/bbb-freeswitch-core/audio.patch

Update audio patch for 1.10.8 source code.
We want to use FreeSWITCH 1.10.8 in 2.6

Update audio patch for 1.10.8

---

bigbluebutton-html5/imports/ui/components/external-video-player/service.js

Validates if the url is from youtube shorts and change the url 'shorts' to 'watch'.
https://user-images.githubusercontent.com/39932802/194107200-a1df029e-babe-4c61-909f-6b47a31a7aea.mp4

fix(external videos) youtube shorts link working

---

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx

Restores the main option menu item descriptions for screen readers.

Restore Option Menu Item Descriptions

---

bigbluebutton-web/build.gradle

Partially back-ports dependency upgrades to 2.5
It has already been implemented in #15859

refactor(bbb-web) (backport 2.5): Upgrade dependencies 

---

bbb-export-annotations/workers/process.js

Fixes a bug where the first annotation of each slide was not showing up in the exported PDF.
Previously, the background itself counted as a shape in the client, so `bbb-export-annotations` skipped shapes whose `childIndex` was smaller than or equal to 1. As this is not the case anymore, these shapes have to be rendered.
- Refactors how points are rendered into strokes to avoid code duplication
- Stroke coordinates set to only use 2 decimal place, reducing the slide size significantly.

fix(bbb-export-annotations): stop first shape from disappearing

---

bbb-learning-dashboard/src/components/PollsTable.jsx

In the Learning Analytics Dashboard, displays poll answers that are the most common in bold.
Closes #15890

Bold Most Common Poll Answers In Analytics Dashboard

---

bigbluebutton-html5/imports/ui/services/settings/index.js

Fixes a spelling mistake in the BBB HTML5 client.
Closes #15803

fix: spelling errors in session keys

---

bigbluebutton-html5/imports/ui/components/webcam/drop-areas/styles.js

Improves the contrast level of webcam drop areas.

style: improving contrast on webcam drop area

---

bbb-api-demo/src/main/webapp/demo3.jsp

A minor PR to silence sonarcloud warnings, and also to test our CI system.

Silence sonarcloud warnings on some old HTML

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

Prevents an issue where the slide would fail to update after a new presentation is uploaded.

fix: issue with slides not changing after upload

---

build/packages-template/bbb-config/after-install.sh
build/packages-template/bbb-html5/bbb-html5.nginx

limit parrallel connections for a same ws url to improve performance

New nginx rules

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Fixes text editing losing focus when in multi user mode: https://github.com/tldraw/tldraw/pull/1037

chore(whiteboard): bump tldraw version

---

bbb-learning-dashboard/package-lock.json
bbb-learning-dashboard/package.json
bbb-learning-dashboard/src/components/PollsTable.jsx

Replaces the poll table with the mui datagrid. This improves the overall a11y (screen reader announcements / keyboard access and hover / focus styling) also includes the ability to sort by users column.
Before:
After:

Replace Poll Table With DataGrid In Learning Dashboard

---

bbb-learning-dashboard/package-lock.json

Outcome of running `npm audit fix` in `bbb-learning-dashboard`.

chore (bbb-learning-dashboard): npm audit fix

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.4](https://github.com/bigbluebutton/bigbluebutton/commit/e47245c62f555fa38268a8980c321f29a2788b9b)
* See:
- https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.3
- https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.4
None

build(bbb-webrtc-sfu): v2.9.4

---

bbb-pads.placeholder.sh

See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.4.0
None

build(bbb-pads): v1.4.0

---

bigbluebutton-html5/package-lock.json

Outcome of running `npm audit fix` in `bigbluebutton-html5`.

chore (bigbluebutton-html5): npm audit fix

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/presentation/presentation.js
bigbluebutton-tests/playwright/presentation/presentation.spec.js

Implements the download presentation test according to Anton's automated tests list coverage  #15456.

test: Download presentation

---

build/packages-template/bbb-config/after-install.sh
build/packages-template/bbb-html5/bbb-html5.nginx

Add new nginx rules

---

bigbluebutton-html5/imports/ui/components/common/modal/header/component.jsx
bigbluebutton-html5/imports/ui/components/common/modal/header/styles.js

Fixes the following console warnings:
**Also**:
Includes a minor style fix.

fix: console warnings due to invalid attributes

---

bbb-learning-dashboard/src/components/PollsTable.jsx

This fixes the most common answer comparison check which is used to correctly apply the bold style.

Fix Most Common Poll Answer Bold Style

---

bbb-common-web/project/Dependencies.scala

backport 2.4 (bbb-web): Upgrade lib Apache Commons Text

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/styles.js

Adjusts the styles of the poll custom input toggle.
Before
After

style: poll custom input toggle and anonymous poll toggle

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

Fixes presentation toolbar and presentation menu not appearing after taking over presenter.

fix: Toolbar not appearing if presenter is changed

---

bbb-webrtc-sfu.placeholder.sh

- [build(bbb-webrtc-sfu): v2.9.5](https://github.com/bigbluebutton/bigbluebutton/commit/242927c0cfec27afd631be7e087e2448852f016b) 
* See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.5

build(bbb-webrtc-sfu): v2.9.5

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx

Prevents an issue with the chat (sometimes) not appearing when the user first joins a meeting.

fix: chat not appearing on join

---

bbb-playback.placeholder.sh

Updates bbb-playback to v5.0.0-beta.1
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0-beta.1

build(bbb-playback): v5.0.0-beta.1

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/context.jsx

fix: Webcam backgrounds crash the entire client on Firefox

---

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx

Fix issue with conditional hook reported by sonarcloud alerts.

refactor: conditional hook in talking indicator

---

bbb-learning-dashboard/package-lock.json

Adjusting the package-lock.json file to be able to install correctly.
Closes #
The automated building and testing has been tripping while building `bbb-learning-dashboard` package.
Likely related to https://github.com/bigbluebutton/bigbluebutton/pull/15701

chore: adjust package-lock.json for learning dashb to not interrupt ci

---

bigbluebutton-html5/public/locales/de.json

Pulled the latest 2.6 HTML5 client locales on December 14, 2022.

chore: Pulled the latest 2.6 HTML5 locales from Transifex

---

bbb-learning-dashboard/src/App.js

Include cross-origin credentials for the Dashboard to work when using [Cluster Proxy Setup](https://docs.bigbluebutton.org/admin/clusterproxy.html).

refactor(Dashboard): include cross-origin credentials

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx

fix: Breakout rooms don't save room assigning

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala

Re-applies lock settings fix 
Closes #8992
PR has not been merged correctly in past and code ended up in a wrong section

re-fix: Phone user lock settings

---

bigbluebutton-tests/playwright/user/multiusers.js
bigbluebutton-tests/playwright/user/user.spec.js

Implements the test where the moderator gives and removes the whiteboard access from a user.

test: Give and remove whiteboard access

---

transifex.yml

Work in progress to integrate a workflow for pulling Transifex localization into BBB + Transifex live monitoring for changes to en.json from BBB
Closes # none
Looks like branch `v2.6.x-release` has lost monitoring in Transifex. Exploring the app integration.

chore: add transifex.yml for better Transifex integration

---

transifex.yml

fix: Modify transifex.yml structure to include git

---

akka-bbb-apps/build.sbt
akka-bbb-apps/project/Dependencies.scala
akka-bbb-fsesl/build.sbt
akka-bbb-fsesl/project/Dependencies.scala
bbb-common-message/build.sbt
bbb-common-message/project/Dependencies.scala
bbb-common-web/build.sbt
bbb-common-web/project/Dependencies.scala
bbb-fsesl-client/build.sbt
bbb-fsesl-client/project/Dependencies.scala

Upgrading Scala from 2.13.4 to 2.13.9
Closes # none
Silencing https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-36944 being reported
- I had to change the target to `"-target:11",` as I was hitting compile issues. I followed the official docs for this format. Somewhat confusing though, as while compiling I see a warning to use `-release` but on the official docs `-release` is for Java up to and including 9 but `-target` lists higher Java versions https://docs.scala-lang.org/overviews/compiler-options/index.html

chore: upgrade scala 2.13.4 -> 2.13.9

---

bigbluebutton-html5/public/locales/en.json

Change the meaning of the locale Hi-ID from "Indian" to "Hindi"
Closes #
As far as I know, the language "Indian" does not really exist. It may even make some people unhappy. "Hindi" would be better.

Hi-ID language

---

bigbluebutton-html5/public/locales/en.json

fix: Hindi naming backport #16251

---

bigbluebutton-web/pres-checker/build.gradle

Upgrades bbb-web presentation checker's dependency `org.apache.commons:commons-compress` to version `1.21`
Closes #none
https://www.cve.org/CVERecord?id=CVE-2021-36090

chore: Upgrade commons-compress to 1.21

---

build/packages-template/bbb-freeswitch-core/audio.patch

Backport of https://github.com/bigbluebutton/bigbluebutton/pull/15926 for BBB 2.5 (follow up from #15925 )

fix: Update audio patch for 1.10.8

---

bigbluebutton-html5/imports/ui/components/common/locales-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/settings/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/data-saving/component.jsx
bigbluebutton-html5/imports/ui/components/settings/submenus/notification/component.jsx

Adds `On` /  `Off` string to aria labels in settings for screen reader context

fix: Update Control Labels In Settings

---

bigbluebutton-html5/imports/api/breakouts/server/handlers/joinedUsersChanged.js
bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
bigbluebutton-html5/imports/api/video-streams/server/modifiers/sharedWebcam.js
bigbluebutton-html5/imports/ui/components/user-list/service.js
bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js
bigbluebutton-html5/imports/utils/string-utils.js

- fix userlist names being sorted by name and not sortName
- add sortName to webcam streams
- add sortName to the list of users joined in breakout rooms

fix: incorrect userlist order if name starts with a space

---

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
bigbluebutton-html5/imports/ui/components/video-provider/component.jsx

2.6 port of https://github.com/bigbluebutton/bigbluebutton/pull/15918
Full PR description there. Largely the same.
n/æ

fix(webcam): intermittent client crashes when sharing camera (2.6)

---

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
bigbluebutton-html5/public/locales/en.json

Backporting to BBB 2.6 @hiroshisuga 's pull requests https://github.com/bigbluebutton/bigbluebutton/pull/16277 and https://github.com/bigbluebutton/bigbluebutton/pull/16278

refactor: Shortcuts instructions modifications (backport)

---

bigbluebutton-web/build.gradle

Backport of #16357 for BBB 2.5

fix: Bump bbb-common-message version

---

bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml
bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml

fix(audio conf): Revert jitterbuffer values & increase them (backport)

---

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

Fixes the eraser animation being out of position.

fix: Restore Tldraw Eraser Animation

---

akka-bbb-apps/deploy.sh

Tweaks some echo commands, no real code change
Closes #none
Likely was copy-pasted from bbb-web's service and remained with the old echo's

fix: use correct service name in akka-apps deploy

---

bbb-learning-dashboard/Readme.md

Improves a bit the instructions for how to rebuild the learning analytics dashboard component
Closes # none
It's now a bit easier to just execute every line, no hiccups due to different dir or existing/non existing directories

fix: Improve the dev build instructions for l dashboard

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala
bigbluebutton-web/grails-app/conf/bigbluebutton.properties

Committing auto-applied indentation
Closes # none
- The akka-apps indentation changes were automatically applied locally when building the code. Committing them in this form should stop the re-indentation from happening in every developer's environment
- the missing last row in bbb properties was tripping some scripts in the past, see https://github.com/bigbluebutton/bbb-install/commit/0338b9006026503185e401cd20ca6b978a4e906a

refactor: fix indentation in core

---

bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx

(chore) Muilti -> Multi

---

bigbluebutton-html5/private/config/settings.yml

Updated the copyright year to 2023
Closes # none
It's 2023 and we're still doing heavy changes

chore: Updated the copyright year to 2023

---

bbb-playback.placeholder.sh

https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0-beta.2
Thanks @germanocaumo !

chore: Bump bbb-playback to v5.0.0-beta.2

---

bbb-learning-dashboard/package-lock.json
bigbluebutton-html5/package-lock.json

Updating npm dependencies for html5 and learning dashboard
Closes # none
`npm audit` was reporting vulnerabilities

chore: updating npm dependencies for html5 and learning dashboard

---

.gitlab-ci.yml
bbb-common-web/build.sbt
bigbluebutton-html5/package-lock.json
bigbluebutton-tests/playwright/api/api.spec.js
bigbluebutton-tests/playwright/api/breakout.js
bigbluebutton-web/build.gradle
bigbluebutton-web/gradle.properties

Carrying forward any fixes from BBB 2.5 to BBB 2.6+
In this case the net changes are
- grails 5.2.4
- #16024

chore: Merge ~2.5.10 into ~BBB 2.6.0-beta.5

---

bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

Upgrading `flat` npm dependency for bbb-html5 (major version upgrade)
Closes # none
npm audit was warning about a critical level vulnerability
```
=== npm audit security report ===                        
SEMVER WARNING: Recommended action is a potentially breaking change
Critical        flat vulnerable to Prototype Pollution                        
Package         flat                                                          
Dependency of   flat                                                          
Path            flat                                                          
More info       https://github.com/advisories/GHSA-2j2x-2gpw-g8fm             
found 1 critical severity vulnerability in 849 scanned packages
1 vulnerability requires semver-major dependency updates.
```

chore: npm audit upgrade "flat"

---

build/packages-template/bbb-html5/build.sh

Copy the fonts to be served in `/files`
Closes # none
Follow up to https://github.com/bigbluebutton/bigbluebutton/pull/16429 as there were still issues with the fonts path on production env
However,...
This means that the package is 4MB larger, and I am still checking if the client is any heavier...
I am marking this PR as Draft because I'd like to see what I can do for compression https://github.com/bigbluebutton/bigbluebutton/issues/16404
Also I am not sure if we really need all of **642** fonts file
```
$ du -sh  /usr/share/meteor/bundle/programs/web.browser/app/files/ 
13M	/usr/share/meteor/bundle/programs/web.browser/app/files/
```
```
$ ls  /usr/share/meteor/bundle/programs/web.browser/app/files/     
caveat-brush-all-400-normal.woff			     source-code-pro-greek-ext-300-normal.woff2 …
```

build: copy tldraw fonts to be served in files/

---

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml

Continuing from  #16422
merging BBB 2.5.11's fix into BBB 2.6
Also adjusting the 2.6 property `allowDuplicateExtUserid` in the same way as #16422
Closes # none
Porting BBB fixes from 2.5 to 2.6+

fix: move allowDuplicateExtUserid to bigbluebutton.properties; contd from #16422

---

bigbluebutton-config/bin/bbb-conf

fix(bbb-conf): ensure BBB target restarts

---

bigbluebutton-html5/imports/ui/components/captions/button/component.jsx
bigbluebutton-html5/imports/ui/components/captions/live/component.jsx
bigbluebutton-html5/imports/ui/components/captions/reader-menu/component.jsx
bigbluebutton-html5/imports/ui/components/captions/writer-menu/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/user/multiusers.js
bigbluebutton-tests/playwright/user/user.spec.js

Implements the closed captions typing test.

test: closed captions typing

---

bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx

It fixes this random behavior of the create breakout rooms button.
https://user-images.githubusercontent.com/69865537/212393846-31826a19-80a5-461f-adaf-9464679ba27c.mp4
Closes #15756 #16118

fix(breakout) - Fix inconsistent behavior of create breakout rooms button

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

After inserting a new text shape, the chars were not being synced, only after it already existed and it was being edited.

fix(whiteboard): restore per character text shape updates

---

bigbluebutton-html5/imports/ui/components/audio/captions/select/component.jsx

It makes a patch for a SonarCloud warning

refactor: Extract hook as a variable (syntax complaint)

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx

Closes #
Calling getAvailableOptions() twice seems to be redundant.

refactor: Reduce redundant redundency in getAvailableOptions()

---

bigbluebutton-web/build.gradle

fix(sec): upgrade databinding to 5.2.4 (port of #16522)

---

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx
bigbluebutton-html5/private/config/settings.yml

It renames configs to make more sense from the user's perspective to configure it.
Closely linked to #16468

refactor (html5): Rename breakoutroom configs

---

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx

fix: avoid aria-describedby warning

---

bbb-common-web/project/Dependencies.scala
bigbluebutton-web/build.gradle

Upgrades `nuProcess` to 2.0.5 (continuation from https://github.com/bigbluebutton/bigbluebutton/pull/15859 )
Closes # no open issue
https://security.snyk.io/vuln/SNYK-JAVA-COMZAXXER-3033308

fix(sec): bump nuProcess to 2.0.6

---

bbb-common-web/build.sbt
bigbluebutton-web/build.gradle

Upgrades postgresql to 42.4.3
Closes # none
https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-2390459 follow up from https://github.com/bigbluebutton/bigbluebutton/pull/15859/
https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-3146847

fix(sec): bump postgresql to 42.4.3

---

akka-bbb-apps/project/Dependencies.scala
bbb-common-message/project/Dependencies.scala
bbb-common-web/project/Dependencies.scala

Upgrades several Jackson related dependencies to address reported security issues with those
Closes # none open
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038424
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244

fix(sec): bump jackson to 2.13.5

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java

Adds logging to user authentication in Akka apps as well as when the guestWaitCleanUpService runs.

Added some additional logs for user authentiction and purging

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

the zoom were being set wrong when the presentation changes
Closes #16285
https://user-images.githubusercontent.com/15806883/215095014-65202ae9-dc4a-4f5f-b9be-3484c496bd31.mp4

fix: Fix whiteboard positioning when switching slides with zoom

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

Improve invalid shape filter, to also include an additional check for orphaned shapes

fix(whiteboard): improve invalid shape filter

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

Fix issues with the pan tool not working correctly.
Closes #16595

fix: Zoom + drag on whiteboard does not move full range

---

.github/workflows/automated-tests.yml
build/packages-template/bigbluebutton/build.sh

Temporarily remove the building of the optional `bbb-playback-video` package from CI
Closes #none
Need to do more work on it (see https://github.com/bigbluebutton/bigbluebutton/pull/16616 ) but it's blocking the CI right now

ci: drop bbb-playback-video from CI

---

bbb-playback.placeholder.sh

Including the latest changes from release https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0-rc.1
Closes # none

chore: bump bbb-playback to v5.0.0-rc.1

---

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

This should improve the performance of the users cursor.
Closes #16602

Add Dependency Array to UseEffect in Cursor Component

---

bigbluebutton-html5/imports/ui/components/poll/component.jsx
bigbluebutton-html5/imports/ui/components/poll/service.js

Fix blue screen when trying to create a poll with more than 5 answers.
Closes #16610

fix: Poll is breaking when trying to add more than 5 answer items

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/notes/component.jsx
bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx

Prevents an issue with the pinned shared notes not appearing correctly.
Closes #16592

fix: pinned shared notes

---

build/packages-template/bbb-libreoffice-docker/opts-focal.sh

Add dependency for `apparmor-utils` to `bbb-libreoffice`.
https://github.com/bigbluebutton/bbb-install/issues/600

build(bbb-libreoffice-docker): Add dependency for apparmor-utils

---

docs/src/css/custom.css

fix(docs): Make index page behave in dark mode and fix spacing

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx

Restores missing whiteboard shortcuts (previous slide, next slide, fullscreen).
Closes #16380

fix: Fullscreen not toggled by Enter key

---

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

Adjusts whiteboard cursor component in order to update mouse/touch event listeners when presenter changes.
Closes #15965

fix(whiteboard): cursor in the wrong place if presenter is changed with multi-user whiteboard

---

bbb-common-web/project/Dependencies.scala
bigbluebutton-web/build.gradle

Backport to BBB 2.5 of #16560
https://security.snyk.io/vuln/SNYK-JAVA-COMZAXXER-3033308

fix(sec): bump nuProcess to 2.0.6 (backport)

---

bbb-presentation-video.placeholder.sh

Adds a file to pull bbb-presentation-video and more importantly,
to pin the version of bbb-presentation-video that corresponds to the specific BBB
version.
Closes # none
Also this allows us to list the change of version in the release notes.

chore: bump bbb-presentation-video to 4.0.0-beta.4

---

bigbluebutton-html5/imports/api/meetings/server/handlers/recordingStatusChange.js
bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/container.jsx

Fix issue with recording notification appearing for the user who started a recording.
Closes #16663

fix: NotifyRecordingIsOn should not offer me to leave

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx

Adjusts camera position in breakout rooms - smart layout.
Closes #15775

fix: Layout bug with "Smart layout" in Breakout Rooms

---

bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/user/multiusers.js
bigbluebutton-tests/playwright/user/user.spec.js

Implements the test where the moderator rejects the raised hand of a user.

test: raise hand rejected

---

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
bigbluebutton-tests/playwright/breakout/breakout.spec.js
bigbluebutton-tests/playwright/breakout/create.js
bigbluebutton-tests/playwright/breakout/join.js
bigbluebutton-tests/playwright/core/elements.js

Implements the test where the user is allowed to choose a breakout room on joining.

test: allow user to choose a breakout room on joining

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx

Allow upload of presentations if hidePresentation=true.
Closes #16716

fix: hidePresentation=true prevents uploading/managing presentations within the client

---

bigbluebutton-tests/playwright/chat/chat.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/core/page.js
bigbluebutton-tests/playwright/presentation/presentation.js
bigbluebutton-tests/playwright/sharednotes/sharednotes.js
bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
bigbluebutton-tests/playwright/sharednotes/util.js
bigbluebutton-tests/playwright/user/multiusers.js

Implements the undo and redo test inside the formatting shared notes test and also implements the file extension check and the exported content check from the shared notes.

test: export-format notes

---

bigbluebutton-tests/playwright/customparameters/constants.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js
bigbluebutton-tests/playwright/customparameters/util.js

Fixes the failing custom parameters tests, and removed the disableScreensharing test, because there is no more the parameter userdata-bbb_enable_screen_sharing .

test: fixing custom parameters

---

bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/customparameters/constants.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js

Implements the remaining custom parameters tests.
- userdata-bbb_hide_actions_bar
- userdata-bbb_hide_nav_bar
- userdata-bbb_preferred_camera_profile
- userdata-bbb_override_default_locale

test: remaining custom parameters

---

bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/component.jsx
bigbluebutton-html5/imports/ui/components/common/icon/component.jsx

Fix warnings in presentation uploader toast and raise hand dropdown.

fix: warning in raise hand and presentation upload toast

---

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
bigbluebutton-html5/public/locales/en.json

List of alternative hotkeys for the white board added in the 'Keyboard shortcuts' area.
#16455

fix: Alternatives to some keyboard shortcuts added to the keyboard shortcut list

---

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx
bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.js
bigbluebutton-html5/imports/ui/components/connection-status/service.js

Removes unused code related to dataSaving in connection-status modal.

refactor: remove unused code in connection-status modal

---

bigbluebutton-html5/imports/api/users/server/modifiers/userInactivityInspect.js
bigbluebutton-html5/imports/api/users/server/modifiers/userLeftFlagUpdated.js

Adds the meetingId to some logs in bbb-html5 for easier debugging.
Closes #none
Requested by @ritzalam

refactor: Add meetingId in log for user left

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx

Fix: Not all camera background alternatives showing up.
#16746

fix: Not all Virtual Backgrounds are shown in the UI to select

---

.github/workflows/deploy-docs.yml

Follow up to #16686 - fix the deployment of the build.

(docs/ci): Use actions publishing for pages

---

.github/workflows/deploy-docs.yml
docs/.gitignore
docs/README.md
docs/build.sh
docs/docusaurus.config.js

Trigger the docs pipeline also on workflow changes.

(docs/ci): Build docs on workflow changes

---

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js

Wrong file type notification when trying to upload files now fixed. 
No issue was open.
1. Create a call on API mate
2. As presenter try to upload a file that isn't a image or text. As the following image:

fix: Notification of wrong file type fixed.

---

bigbluebutton-tests/playwright/core/elements.js

Implements an update on the pollContainer selector.

test: update pollContainer selector

---

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java

It basically removes a message that has been frequently logging up in bbb-web. It was just a debug log according to @paultrudel.

refactor: Remove frequently logged message

---

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
bigbluebutton-html5/imports/ui/components/nav-bar/styles.js

This PR removes the arrow indicating user list toggle on mobile.
#16524

Arrow indicating user list toggle removed on mobile.

---

bbb-pads.placeholder.sh

- [build(bbb-pads): v1.4.1](https://github.com/bigbluebutton/bigbluebutton/commit/77ce8ce440db1774db82ab78839eb7d14b97c6f1) 
* See https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.4.1
n/a

build(bbb-pads): v1.4.1

---

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/public/locales/en.json

Upload presentation label and icon changed for better new user experience.
#16843

Upload presentation label and icon changed.

---

bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/component.jsx

Emoji now appear in the "Raise Hand" button. Users are now able to clear status clicking the the button as well.
#16816

feat: Raise hand button now shows current emoji and can also clear emoji.

---

bbb-playback.placeholder.sh

https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0-rc.2

 chore: bump bbb-playback to v5.0.0-rc.2

---

bbb-learning-dashboard/src/App.js
bbb-learning-dashboard/src/components/UsersTable.jsx

Implements a few necessary data-tests on the learning dashboard for testing.

test: Adding data-test to learning dashboard for testing

---

bbb-presentation-video.placeholder.sh

https://github.com/bigbluebutton/bbb-presentation-video/releases/tag/4.0.0-rc.1

build(bbb-presentation-video): Bump to 4.0.0-rc.1

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

fix: Fix an inline typo

---

.github/workflows/automated-tests.yml
docs/docs/new-features.md

- Syncs up changes from https://github.com/bigbluebutton/bigbluebutton.github.io/blob/master/_posts/2.6/2021-06-09-new.md to the new docs
- Also exclude changes within `docs/` or any markdown files from triggering the test suite
Closes # none
preparation to transition to the new docs

docs: sync up 2.6 docs

---

docs/docs/new-features.md

Fix broken links from #16970 
Closes #none

docs: fix broken links

---

bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx

Adds auto focus on the input of external video modal
[Screencast from 2023-03-09 16-56-31.webm](https://user-images.githubusercontent.com/3728706/224139576-54aeb6db-ba74-4b87-a05c-00882edf2812.webm)
Suggested by @TiagoJacobs :)

fix: Auto focus on external video input

---

bigbluebutton-html5/imports/ui/components/cursor/service.js
bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

- [fix(cursor): improve cursor position for others](https://github.com/bigbluebutton/bigbluebutton/commit/c1810360ef8589cbfe969aa7489e5de18dc5f15c)
- Cursor position was desynced after the presenter zoomed with ctrl+scroll, also fixes the last position of the cursor not being sent sometimes.
Move the throttle to the service call so it is considered in all cases (and there was already a throttle there).
- [fix(cursor): send cursor position disabled on unmount](https://github.com/bigbluebutton/bigbluebutton/commit/8aa15ef8617b5e4023976bae31978add212b1a62)
- This fixes the cursors staying visible in the recording after the multiuser was disabled.
Also stop sending some unnecessary end events.
Closes #16736

fix(tldraw): cursor fixes

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
bigbluebutton-html5/private/config/settings.yml

Remove unused presentation code

fix(presentation): Remove old presentation minize code

---

docs/docs/greenlight/v3/customize.md

Fix the paths within the docker image of GLv3.
Closes #
https://groups.google.com/g/bigbluebutton-dev/c/NKCzbkxld3M

[doc] Fix path for customization of GLv3

---

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

Adds the crosshair cursor to the arrow and eraser tool.

Add Crosshair Cursor for Arrow and Eraser Tool

---

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/imports/ui/components/webcam/container.jsx

Reverts bigbluebutton/bigbluebutton#16823
after merging #16823 @antonbsa found that presentation does not appear if the default presentation takes some time to process, so we might need more time to make it work without this issue

Revert "fix(html5): Empty space when removing all presentations"

---

bbb-presentation-video.placeholder.sh

* Fix error rendering curved arrows on Ubuntu 20.04
* Fix https://github.com/bigbluebutton/bbb-presentation-video/issues/25
* Fix https://github.com/bigbluebutton/bbb-presentation-video/issues/27
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.0-rc.1...4.0.0-rc.2
* https://github.com/bigbluebutton/bbb-presentation-video/issues/24
* https://github.com/bigbluebutton/bbb-presentation-video/issues/26

chore(bbb-presentation-video): Update to 4.0.0-rc.2

---

build/packages-template/bbb-playback-video/after-install.sh

Adds an nginx reload on `bbb-playback-video` install
Closes # none
If you had just installed `bbb-playback-video` you would not be able to view the video due to the url not being recognized

build: reload nginx after bbb-playback-video is installed

---

.github/ISSUE_TEMPLATE/docs-issue.md

We needed a template to facilitate docs issues reporting. See #17055

chore: added a template for docs issues

---

docs/build.sh
docs/docusaurus.config.js

Include building of BBB's docs on branch `v2.5.x-release` now that we have these docs -- #17078 
Closes # none
Related #17055 
Steps towards transitioning to the new docs

docs: enable building of 2.5 docs

---

bigbluebutton-html5/client/stylesheets/bbb-icons.css
bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
bigbluebutton-html5/public/locales/en.json

Add a button for viewers to change the layout.
Add a icon's variable as a temporary icon for the layouts button.
https://user-images.githubusercontent.com/39932802/223527396-6c29e637-7858-4e02-915f-e9b280446224.mp4

feature(layout) viewers layout button

---

SECURITY.md

Updates our Security policy
Closes #none
BBB 2.6.0 is released!

chore: Update SECURITY.md for BBB 2.6

---

bigbluebutton-html5/imports/ui/components/text-input/component.jsx

Fix copy/paste/cut on guest user message input.
Closes #16969

fix: Copy/Paste into Guest Policy textbox will cause a text box to appear in whiteboard

---

bigbluebutton-tests/playwright/polling/poll.js

Updates the test checks due to #17039

test: Update polling tests

---

bigbluebutton-html5/imports/ui/components/app/component.jsx
bigbluebutton-html5/imports/ui/components/app/styles.js
bigbluebutton-html5/imports/ui/components/whiteboard/utils.js

Fix visual issue with the polling results in Firefox.

fix: poll results size calculation on firefox

---

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx

Adds a `setTimeout` to prevent a race condition which causes the role to be removed permanently when resized or new messages come in.
related to #16949

fix(access): Prevent Race Condition Removing Role Value

---

docs/docusaurus.config.js

Sets the URL of the new docs to be the same as the old docs (i.e. can't distinguish them by home URL)
`https://docs.bigbluebutton.org/bigbluebutton/` -> `https://docs.bigbluebutton.org/`
Closes # none
Working with @tibroc  towards setting the new docs as default

docs: remove basename for docs website

---

docs/docs/new-features.md

docs: Fix broken image in 2.5 docs

---

docs/docs/administration/configure-firewall.md
docs/docs/administration/customize.md
docs/docs/administration/install.md
docs/docs/administration/lti.md
docs/docs/development/dev-guide.md
docs/docs/development/localization.md
docs/docs/development/webhooks.md

Fix broken links mentioned in #17121

docs: Docs fix links

---

docs/docs/greenlight/v3/migration.md

Update the documentation to reference the correct Greenlight V2 branch for fetching the migration file, as the master branch now contains Greenlight V3.
Related to issue posted on [BBB google group](https://groups.google.com/g/bigbluebutton-dev/c/y5mkmP_mRlQ)

fix(docs): update path to Greenlight migration file

---

docs/docs/greenlight/v3/migration.md

Add section to Greenlight migration guide on how to use rake task for bulk password reset

fix(docs): add After Migration section to Greenlight migration docs 

---

docs/docs/new-features.md

docs: Fix link for recording

---

.gitmodules

Removes a submodule added on https://github.com/bigbluebutton/bigbluebutton/pull/15673/files because it was breaking sync-ing in Jenkins...
Closes #none

build: Remove submodule

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Google search result showed an old docs page for 2.6. This commit adds a redirect for that link to the  new docs.

docs: Redirect from old docs to new

---

bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js

This PR fixes bug where a drop down menu doesn't show all options.
#17125

Fixed: Missing buttons on menus in low resolutions.

---

bigbluebutton-html5/imports/ui/components/whiteboard/styles.js

fix issue with dragging the presentation instead of selected shape after rotating a shape.
Closes #17023

fix: Dragging presentation area instead of rotated shape

---

docs/docusaurus.config.js

Make the old docs' link to API work on the new docs
Closes # none
The old API link is linked in a few places (forums, etc) and is commonly bookmarked.

docs: Forward from old docs API link

---

bbb-playback.placeholder.sh

Updates bbb-playback to v5.0.0 https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0
Related to https://github.com/bigbluebutton/bigbluebutton/issues/17086

chore: Bump bbb-playback to v5.0.0

---

bbb-presentation-video.placeholder.sh

Bug-fix release for BigBlueButton 2.6
* https://github.com/bigbluebutton/bbb-presentation-video/pull/37
* https://github.com/bigbluebutton/bbb-presentation-video/pull/38
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.0...4.0.1

bbb-presentation-video: Update to 4.0.1

---

docs/docusaurus.config.js

docs: fix link to GL v3

---

bigbluebutton-config/assets/index.html

Swaps innerHTML for innerText in one spot when presenting an error screen.
Closes #none
SonarCloud detected and complained

fix(bbb-conf): switch to the safer .innerText

---

docs/docs/development/dev-guide.md

[doc] run-war -> run-app

---

bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx

This PR removes the unnecessary text formatting causing the application to send an error message.
#17351

Fixed: Error message on layout change.

---

bigbluebutton-tests/playwright/README.md

credits: @antonbsa
Points to the right parameter name to use when we only want to target a specific browser
Closes #none

test: update instructions to only test specific browser

---

bigbluebutton-html5/imports/ui/components/common/button/button-emoji/styles.js

This PR better centralizes the drop down menu's arrows.

style: drop down arrow better centralized.

---

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx

Fix cameras position in the sidebar when notificationBar is displayed.
[Screencast from 2023-04-04 09-43-11.webm](https://user-images.githubusercontent.com/3728706/229795421-bd8411c9-8192-44b4-972f-8afb5c3a0e08.webm)

fix: camera position when notificationBar appears

---

bigbluebutton-html5/imports/startup/client/base.jsx
bigbluebutton-html5/imports/ui/components/app/container.jsx
bigbluebutton-html5/public/locales/en.json

Removed the code that caused the user to enter the old "waiting for approval" status.

fix(reconnect) waiting for approval

---

bigbluebutton-html5/imports/ui/components/common/tooltip/bbbtip.css

This PR fixes a bug where the bbb tip over lapses some elements it shouldn't.

Fix: BBB tips overlapping other elements out of his own box

---

bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx

This PR solves error occurring when trying to use custom style via URL.
#17330

Fixed: Error when trying to apply custom styles via URL.

---

bbb-webrtc-sfu.placeholder.sh

See:
- https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.9
- https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.10
There should be no effect from those in default setups as they contain off-by-default features.
None

build(bbb-webrtc-sfu): v2.9.10 (from v2.9.8)

---

bigbluebutton-html5/imports/ui/components/audio/local-echo/service.js

- [fix(audio): output device changes not effective in local echo test](https://github.com/bigbluebutton/bigbluebutton/commit/1ada7dc57e33a0d19dc9ddf75d401af495464eca)
* This commit fixes the issue by piping the AudioContext destination through the main audio element rather than using WebAudio directly for playback. An additional stub media element (muted) is added to circumvent one of Chrome's WebAudio issues.
* This should work with FF (setSinkId enabled) and a wide array of Chromium versions.
* The alternative would be to use AudioContext's setSinkId, but it isn't supported by Firefox (setSinkId enabled) and Chrome < 110.
Closes #16764 
Output device changes aren't working in 2.6's echo test when artifical delay is on due to the fact that the feedback audio is being played via the …

fix(audio): output device changes not effective in local echo test

---

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx

This PR handles the addition of the `onKeyDownCapture` event to the dropdown menu in order to prevent interference with the listeners from `tldraw`.
The dropdown menus did not have the expected behavior for keyboard interactions. When the menu is opened, pressing the up or down arrow keys would not travers the list.
before:
After:

fix(access): Keyboard Navigation With Arrows Only In Dropdown Menus

---

docs/docs/greenlight/v3/migration.md

migrations.rake file at the given path doesnt exist. Modified the path.
Closes #17350 
Documentation issue in v2.5

docs: Update url for GL migration path

---

bigbluebutton-html5/imports/ui/components/common/control-header/left/component.jsx

Suppresses "tabindex is not a valid DOM" for React component seen time to time when working on 2.5 source code.

[2.5 chore] tabindex -> tabIndex

---

docs/docs/development/dev-guide.md

Adds a missing step to the docs -- without it I could not switch to user `bigbluebutton` in terminal
Closes #none

docs: Add missing step to switch to bigbluebutton user in  dev-guide.md

---

bbb-presentation-video.placeholder.sh

* [Limit the max size of image surface to render PDF](https://github.com/bigbluebutton/bbb-presentation-video/pull/42) by @kepstin
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.1...4.0.2

bbb-presentation-video: update to 4.0.2

---

bigbluebutton-config/bin/apply-lib.sh

Have `/etc/bigbluebutton/bbb-conf/bin/apply-config.sh` or `/etc/bigbluebutton/bbb-conf/bin/apply-lib.sh` write to the overriding file `/etc/bigbluebutton/bbb-html5.yml` instead of the file from the package `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`
Closes partially #17193 (except for Kurento)
#17193

fix: change apply-lib.sh to use /etc/bigbluebutton/bbb-html5.yml

---

docs/docs/administration/install.md
docs/docs/new-features.md

Includes info on TURN being set up by default in 2.6+
Closes partially https://github.com/bigbluebutton/bigbluebutton/issues/17530

docs: include info on TURN being set up by default in 2.6+

---

docs/docusaurus.config.js

Handles a few docs broken links
<!-- List here all the issues closed by this pull request. Use keyword `closes` before each issue number

docs: Handle paths /2.6/new-features, /dev/ and /admin/

---

bigbluebutton-tests/playwright/customparameters/constants.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js

Adds two more tests to the disabledFeatures, the presentation disabled and the custom virtual background disabled.

test: added two tests for disabledFeatures 

---

docs/docs/greenlight/v3/install.md

This PR adds in a new section for the Greenlight 3 installation docs documenting the usage of the relative URL root path feature for sysadmins.

Docs: Added `Relative URL ... Setup` section to Greenlight 3 install chapter.

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/SyncGetVoiceUsersMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GuestsWaitingApprovedMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
akka-bbb-apps/src/test/scala/org/bigbluebutton/core2/testdata/TestDataGen.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js
bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
bigbluebutton-html5/imports/api/voice-users/server/handlers/getVoiceUsers.js
bigbluebutton-html5/imports/api/voice-users/server/handlers/joinVoiceUser.js
bigbluebutton-html5/imports/api/voice-users/server/handlers/voiceUsers.js
bigbluebutton-html5/imports/api/voice-users/server/modifiers/addVoiceUser.js

Now the user color is being picked in the backend.
But it was missing for voiceUsers create msgs!
Closes #17671

fix: dial-in-participants not appearing in the participant list

---

bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/notes/component.jsx
bigbluebutton-html5/imports/ui/components/screenshare/component.jsx

Includes #17512 + fix for setting initial state.
Closes #17668
Closes #17464

Fix: Presentation un-minimizing when exiting external video or screen sharing.

---

bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meetings.ftlx

- Align the output withgetMeetingInfo
- Make output suitable for computational needs
Closes #17688

fix: Do not format maxUsers in the getMeetings API response

---

docs/docs/administration/customize.md

backport of #17713 from @ThibautPlg

docs: Correcting the virtual background images upload path

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx

between merges some references were lost

Fix: Wrong import for confirmation modal

---

docs/docs/administration/turn-server.md

Fix an incorrect path for overriding `turn-stun-servers.xml`

Fix an incorrect path for overriding `turn-stun-servers.xml`.

---

bigbluebutton-html5/imports/ui/components/webcam/component.jsx

This PR fixes the issue where the cameras were obstructing buttons.
#17703

Fix: Cameras don't obstruct buttons anymore.

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatDAO.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageDAO.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatUserDAO.scala
bbb-graphql-client-test/src/ChatsInfo.js
bbb-graphql-server/bbb_schema.sql
bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_chat_user.yaml
bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat.yaml

Used as condition to show this chat in the list of chats above the Userlist.

refactor (graphql-server): Introduces flag "visible" to chat_user

---

bigbluebutton-config/bin/apply-lib.sh
bigbluebutton-config/bin/bbb-conf
bigbluebutton-config/bin/bbb-record
build/packages-template/bbb-config/after-install.sh
build/packages-template/bbb-config/build.sh
build/packages-template/bbb-config/opts-jammy.sh
build/packages-template/bbb-html5/after-install.sh
build/packages-template/bbb-html5/build.sh
build/packages-template/bbb-html5/opts-jammy.sh
build/packages-template/bbb-playback-podcast/after-install.sh
build/packages-template/bbb-playback-podcast/build.sh
build/packages-template/bbb-playback-podcast/opts-jammy.sh
build/packages-template/bbb-playback-presentation/build.sh
build/packages-template/bbb-playback-presentation/opts-jammy.sh
build/packages-template/bbb-playback-video/build.sh
build/packages-template/bbb-playback-video/opts-jammy.sh
build/packages-template/bbb-record-core/after-install.sh
build/packages-template/bbb-record-core/build.sh
build/packages-template/bbb-record-core/opts-jammy.sh
build/packages-template/bbb-webhooks/after-install.sh
build/packages-template/bbb-webhooks/build.sh
build/packages-template/bbb-webhooks/opts-jammy.sh
build/packages-template/bbb-webrtc-sfu/after-install.sh
build/packages-template/bbb-webrtc-sfu/build.sh
build/packages-template/bbb-webrtc-sfu/opts-jammy.sh
docs/docs/administration/customize.md
docs/docs/support/troubleshooting.md

Makes changes in packaging, bbb-conf, bbb-record, apply-lib, some docs in order to support the upgrade of `yq` from v3 to v4 https://mikefarah.gitbook.io/yq/upgrading-from-v3
I have already made compatible chages to bbb-install-2.8.sh
There are still a bunch of spots to change
- (more) on bbb-conf
- more on docs
I am pausing here for now as I think these changes should suffice so I can install+run BBB on Ubuntu 22.04 and can more reliably verify that all is well.
Closes #
Related https://github.com/bigbluebutton/bigbluebutton/issues/14511
Related #17727 
Related #16100

build-conf: Change yq syntax from v3 to v4 (part1)

---

docs/docs/administration/lti.md

First pass at updating the LTI docs for 2.6.

Update LTI docs

---

.github/workflows/automated-tests.yml

Modifies the version of bbb-install to correctly pick the env + scripts for installing BBB on this branch
Closes #
Part of the setup for BBB 2.8 on Ubuntu 22.04

ci: use bbb-install-2.8.sh

---

build/packages-template/bbb-webrtc-sfu/opts-jammy.sh

Drops openh264-gst-plugins-bad-1.5 sfu dependency
Closes #
The rest of Kurento related build files were already dropped in #17727

build: drop openh264-gst-plugins-bad-1.5 sfu dependency

---

build/packages-template/bbb-freeswitch-core/opts-jammy.sh

Closes #
On Ubuntu 22.04 we have `libldns3` instead of 2. https://packages.ubuntu.com/jammy/libldns-dev
Thanks @kepstin for the assist!

build: require libldns3 for bbb-freeswitch-core

---

bigbluebutton-html5/imports/ui/components/whiteboard/service.js

This PR adds some corrections and tweeks do async annotations.

fix: Meteor migration async annotation tweaks

---

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addBulkGroupChatMsgs.js
bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js
bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js
bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx

What was happening is that every time we start a new private chat the group-chat-message subscription was being redone and all data it's send to client again.

Fix: duplicate messages when start a new chat

---

docs/docs/administration/customize.md

Fixes a typo and adds an image.
Closes #17785

[2.6 doc] typo and missing image in the customize section

---

docs/docs/administration/customize.md

Explains explicitly what the three dots mean as a comment, so that user can copy and paste it.
Closes #17785
See #17785. 
Sorry that I didn't fix it in the previous PR #17802.

[2.6 doc] explain three dots in bbb-html5 setting

---

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx

This PR fixes the lack of cursor when entering a meeting.
#17741

Fix: Default cursor not appearing when entering meeting.

---

bigbluebutton-html5/imports/ui/components/breakout-room/message-form/component.jsx
bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx

Removes error message from chat input on submit.
Closes #17723

fix(chat): character limit warning is not removed on submit

---

bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js

Ensures we don't run timeout code within Fiber
Closes # none
Proactively trying to avoid issues like what the lack of https://github.com/bigbluebutton/bigbluebutton/pull/17817 caused

refactor: ensure setTimeout and clearTimeout run within Fiber

---

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx

Enables the quick poll button generated from a simple "Yes/No" sentence.
Closes #17826 
I am not sure if it's a bug. But it does the job at least in my server.

fix(poll): fix Yes/No quick poll button

---

docs/docs/administration/customize.md

Based on @daniel-at-git 's suggestions in https://github.com/bigbluebutton/bigbluebutton/pull/17682 -- making the same changes in BBB' 2.6 branch
Closes # none

docs: Update location of default.pdf and favicon.ico -- assets/

---

.github/config.yml

Closes # none
This has been a manual process and sometimes pull requests slip in so that we have to ask for CLA long after the PR has been created
https://github.com/apps/welcome

chore: Include an automatic welcome for first time contributors

---

bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java

Adds statements to release some resources, such as file streams, that were opened but never closed.
This is most likely not an issue that can be exploited, but it is always good practice to release resources that have been opened.

fix(sec): Unreleased streams fix

---

bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java

Adds statements to release some resources, such as file streams, that were opened but never closed.
This is most likely not an issue that can be exploited, but it is always good practice to release resources that have been opened.

fix(sec): Unreleased streams fix 2.5

---

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java

Disable learning dashboard on breakout rooms.
Closes #17840

fix: Learning dashboard is available in breakout rooms

---

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/container.jsx

fix (html5): User prevent the second user from opening private chat

---

build/packages-template/bbb-graphql-server/after-install.sh
build/packages-template/bbb-graphql-server/build.sh

Drops the postgres database before trying to create it (on upgrade/install) to avoid calling create on an existing db
Closes # none
Matching #17783 in packaging

build: drop db before creating it

---

bigbluebutton-html5/imports/ui/components/user-list/service.js

This PR fixes the behavior of Save users ordering.
#17734

Fix: Order of first and last names in save users

---

build/packages-template/bbb-graphql-server/after-install.sh
build/packages-template/bbb-graphql-server/build.sh

Copy over config.yaml and use it on the `hasura metadata apply` step
Closes # none
Further changes to packaging of bbb-graphql-server

build: copy over config.yaml for graphql

---

bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx

This PR makes only the presenter able to edit polls.

fix: Making poll results editing possible to presenter

---

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/service.js
bigbluebutton-html5/imports/utils/mimeTypes.js
bigbluebutton-html5/private/config/settings.yml

This PR allows webp format images on virtual backgrounds.

feat (html5): Virtual backgrounds now accepts webp format

---

bigbluebutton-tests/playwright/reconnection/reconnection.js
bigbluebutton-tests/playwright/reconnection/reconnection.spec.js
bigbluebutton-tests/playwright/reconnection/util.js

This PR adds re-connection tests: chat (disabled, enabled) and audio.

test: chat and audio reconnection tests

---

bigbluebutton-tests/playwright/customparameters/constants.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js

Changes the current test due to https://github.com/bigbluebutton/bigbluebutton/pull/16769

test: fix hide presentation on join test

---

bigbluebutton-html5/imports/ui/Types/chat.ts
bigbluebutton-html5/imports/ui/Types/message.ts
bigbluebutton-html5/imports/ui/Types/user.ts
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/componet.tsx
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/queries.ts
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts
bigbluebutton-html5/imports/ui/components/chat/time-window-list/container.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
bigbluebutton-html5/public/locales/en.json

This PR introduces the graphql to the chat messages in BBB, with the new pagination we stabilzed pages and load it incrementaly as the user request to look into the message history, not storing more the whole chat history in client memory.
Make the chat support graphql and make use of pagination to improve client performance

Refactor: Chat using graphql and pagination

---

bigbluebutton-html5/imports/api/presentations/server/handlers/sendExportedPresentationChatMsg.js
bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx

This PR adds unread notification when presentation is sent to chat.
#17888 
Example:

Fix: Send to chat presentation not having unread notification

---

record-and-playback/core/scripts/README

Fix a minor mistyping

---

record-and-playback/core/scripts/utils/gen_webvtt

Just fixes a typo in a comment.

[chore - recording] typo in a comment

---

.github/workflows/automated-tests.yml

- updates bbb-install.sh script to use BBB 2.7's version (needs PR https://github.com/bigbluebutton/bbb-install/pull/651 to be merged)
- sets the repository to `focal-27-dev` so we use 2.7 packages
Closes #none

ci: Update automated-tests.yml for BBB 2.7

---

build/packages-template/bbb-freeswitch-core/build.sh

Upgrades FreeSWITCH's dependency `sofia-sip` to 1.13.15
Closes #
https://github.com/freeswitch/sofia-sip/security/advisories/GHSA-rm4c-ccvf-ff9c

fix(sec): upgrade FS dep sofia-sip to 1.13.15

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/ShowPollResultReqMsgHdlr.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageDAO.scala
akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PostgresProfile.scala
bbb-graphql-server/bbb_schema.sql
bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_private.yaml
bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_public.yaml
bbb-graphql-server/update_graphql_data.sh
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/componet.tsx
bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx

This PR introduces two new columns in chat_msgs:
`messageType`: It indicates the handler that should render this message, e.g: `default` or `poll`.
`messageMetadata`: Here will be the data that can be used to render the message.
When it's a SYSTEM msg, the `senderId` will be `null`.
Query:
```
{
chat_message_public {
messageType
messageMetadata
messageId
message
}
}
```
Result:
```
{
"data": {
"chat_message_public": [
{
"messageType": "poll",
"messageMetadata": "{\"numResponders\":2,\"answers\":[{\"id\":0,\"key\":\"A\",\"numVotes\":0},{\"id\":1,\"key\":\"B\",\"numVotes\":1},{\"id\":2,\"key\":\"C\",\"numVotes\":0},{\"id\":3,\"key\":\"D\",\"numVotes\":1}],\"id\":\"4ca4733f955a8c64c169553bf76be2c51507e2ec-1684936681694/1/1684936722787\",\"numRespondents\":2,\"questionType\":\"A-\",\"questionT …
```

refactor (graphql-server): Insert Poll Result as Chat msg

---

build/packages-template/bbb-freeswitch-core/build.sh
freeswitch.placeholder.sh

Backport of #17973 and #16672 to BBB 2.5

fix(sec)/build: upgrade FS to 1.10.9 and sofia-sip to 1.13.15 (BBB 2.5 backports)

---

bigbluebutton-tests/playwright/audio/audio.js
bigbluebutton-tests/playwright/audio/audio.spec.js
bigbluebutton-tests/playwright/core/media/.~lock.smartSlidesPresentation.pdf#
bigbluebutton-tests/playwright/user/multiusers.js

Changes the audio test, so it can also support the serial mode.

test: Audio serial mode

---

bigbluebutton-tests/playwright/.env.template
bigbluebutton-tests/playwright/breakout/breakout.spec.js
bigbluebutton-tests/playwright/chat/chat.spec.js
bigbluebutton-tests/playwright/connectionStatus/connectionStatus.spec.js
bigbluebutton-tests/playwright/core/constants.js
bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js
bigbluebutton-tests/playwright/learningdashboard/learningdashboard.spec.js
bigbluebutton-tests/playwright/notifications/notifications.spec.js
bigbluebutton-tests/playwright/options/options.spec.js
bigbluebutton-tests/playwright/polling/poll.js
bigbluebutton-tests/playwright/polling/polling.spec.js
bigbluebutton-tests/playwright/presentation/presentation.js
bigbluebutton-tests/playwright/presentation/presentation.spec.js
bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
bigbluebutton-tests/playwright/user/guestPolicy.js
bigbluebutton-tests/playwright/user/user.spec.js
bigbluebutton-tests/playwright/webcam/webcam.spec.js

- Increases the tests running on each PR (**60 -> 133**);
- Adds description for env variable TIMEOUT_MULTIPLIER;
- Increments in 5 seconds the pdf upload default timeout aiming to avoid unexpected failures;

test: Increase tests running on CI

---

record-and-playback/presentation/scripts/publish/presentation.rb

Fixes cursor not showing in playback
Closes #17997

fix(recording): missing cursor

---

bigbluebutton-config/bin/bbb-conf
docs/docs/administration/configure-firewall.md

Update links in bbb-conf to the new docs structure
Closes #none
The links were broken

fix: Update links in bbb-conf to the new docs structure

---

bigbluebutton-html5/private/config/settings.yml

Enables by default Camera as content.
Closes #none
See #18021

chore: Enable by default Camera as content

---

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ScreenshareDAO.scala
bbb-graphql-server/bbb_schema.sql

Populate new column `screenshare.contentType` in graphql.

refactor (graphql-server): Provide data introduced for "camera as content"

---

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx

fix blank presentation after minimizing.
Closes #18039

fix: Viewer gets blank presentation after minimize/restore

---

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js
bigbluebutton-html5/imports/ui/stylesheets/styled-components/palette.js

Changes webcam placeholder border color for grid view.
Closes #17943

style: change webcam placeholder border color

---

bbb-common-web/build.sbt
bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/CallbackUrlService.java
bigbluebutton-web/grails-app/conf/bigbluebutton.properties
bigbluebutton-web/grails-app/conf/spring/resources.xml

fix(sec): SSRF fix 2.5

---

bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
bigbluebutton-web/grails-app/conf/spring/resources.xml

fix: Default presentation bypass validation 25

---

docs/docusaurus.config.js

Fixes missing main page for GL
Closes #none
#18080 dropped the page we used to redirect on navbar hits for GL

docs: Fix missing main page for GL

---

docs/docs/administration/customize.md

Document HTML5 config maxNumberOfAnnotations
Closes #17126
The reason for its existence and the way to override it have been a common question.

docs: Document maxNumberOfAnnotations

---

docs/docs/new-features.md

docs: Add a note in the 2.6-whats-new about max annotations cap

---

bigbluebutton-html5/imports/ui/components/actions-bar/interactions-button/component.jsx

This PR fixes the props of the sub-menu element of interactions, making the drop-down menu arrow take its right orientation.

Fix: Arrow upside down on interactions sub-menu

---

bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
bigbluebutton-html5/imports/ui/components/media/service.js
bigbluebutton-html5/imports/ui/components/pads/service.js

fix pin/unpin shared notes feature

fix: pin/unpin shared notes

---

bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js

Restores mobile menu styles
Closes #18100

fix: Dropdowns on mobile appear misplaced+overlay some of the controls

---

bigbluebutton-html5/private/config/settings.yml

Enables Timer introduced via #17941 #18133
Closes #none
If it's enabled by default, it will be easier to be noticed by others, it will be better tested, plus it can always be disabled locally

chore: Enable Timer by default

---

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
bigbluebutton-html5/package-lock.json
bigbluebutton-html5/package.json

This adds a debounce to the `handleResize` and `zoomChanger` functions which prevents zoom changes when resizing the browser quickly.
Closes #17843

fix: Add Debounce To handleResize And zoomChanger

---

.gitlab-ci.yml
bigbluebutton-html5/imports/startup/server/index.js
docs/docs/new-features.md

Related to https://github.com/bigbluebutton/bigbluebutton/issues/16101 
bigbluebutton/bigbluebutton portion of https://github.com/bigbluebutton/bbb-install/pull/654
NodeJS 16 will become unsupported EOL on Sept 11, 2023 https://nodejs.org/en/blog/announcements/nodejs16-eol
Note: I also created a BBB repository for the dockerfile we use for packaging https://github.com/bigbluebutton/bbb-docker-build-packages and pushed to a BigBlueButton dockerhub https://hub.docker.com/r/bigbluebutton/bbb-build

chore: upgrade NodeJS to 18

---

bbb-export-annotations/package-lock.json
bbb-export-annotations/package.json

Allows newer nodejs to be used on bbb-export-annotations
Cont'd from #18159 
Being tripped when rebuilding bbb-export-annotations after #18159 
```
/var/tmp/bbb-export-annotations_2.7_focal_m27f /var/tmp/bbb-export-annotations_2.7_focal_m27f
+ cd staging/usr/local/bigbluebutton/bbb-export-annotations/
+ npm install --production
[37;40mnpm[0m [0m[30;43mWARN[0m [0m[35mconfig[0m production Use `--omit=dev` instead.
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m EBADENGINE
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mengine[0m Unsupported engine
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mengine[0m Not compatible with your version of node/npm: bbb-export-annotations@0.0.1
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnotsup[0m Not compatible with your …
```

chore: allow newer nodejs to be used on bbb-export-annotations

---

bigbluebutton-tests/playwright/core/elements.js
bigbluebutton-tests/playwright/customparameters/constants.js
bigbluebutton-tests/playwright/customparameters/customparameters.js
bigbluebutton-tests/playwright/customparameters/customparameters.spec.js

Implements the disabledFeaturesExclude test alongside the disabledFeatures test.

test: Disabled features exclude
