bigbluebutton-html5/private/config/settings.yml
This is a follow up to https://github.com/bigbluebutton/bigbluebutton/pull/12983.
Webcams already did that by default. Screen sharing and listen only were generating offers in the client, though.
After further testing I'm toggling the defaults for screen sharing/listen only as well.
None
Refer to https://github.com/bigbluebutton/bigbluebutton/pull/12983
=> chore(webrtc): let the server generate subscriber offers by default

bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/imports/api/group-chat-msg/index.js, bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx, bigbluebutton-html5/imports/ui/services/collection-hooks-callbacks/collection-hooks-callbacks.js, bigbluebutton-html5/imports/ui/services/collection-hooks/collection-hooks.js
Implements the CollectionEventsBroker which directly listens for the collection event and skips the insertion in the minimongo, this reduces memory usage, as the item is now stored in one place only, it also reduces CPU usage because the event parse occurs only once, removes the eventListener which makes the application more robust because it doesn't need workarounds for the client reconnect
=> Implements CollectionEventsBroker for chat context - develop

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
Prevents an issue with the breakout room panel where UI gets stuck at **Generating URL...** if a user tries to generate more than one join URL without closing the breakout panel.
Closes #13249
=> fix: Breakout generation URL keeps loading even after it has finished

bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/imports/api/audio/client/bridge/bridge-whitelist.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/private/config/settings.yml
We are now able to switch between audio bridges, by selecting it in
config files. We don't recommend doing it now because this won't work
without some updates that will come later.
This is one of the first steps to allow adding audio bridges for existing
or new media servers (kurento, mediasoup, etc..). By switching default
bridges, we can switch the media server that is going to be used
by fullaudio (microphone)
=> feat(audio): add bridge configurable scheme

build/packages-template/bigbluebutton/build.sh
Folks, I realize you may not be terrible motivated to accept a change for a typo in this build script, but I'd actually found it first at https://docs.bigbluebutton.org/2.3/install.html, and I tried to find where that text may be here in the githib repo. But I could only find this. (While the text is identical, I don't expect that you somehow pull this text into that front page.)
So I'm offering this, whether you may agree with the value of touching this build.sh file to correct a typo, as much to just get your attention so that you may get that front page fixed some other way.
And indeed, if you require me to go through the submission/acceptance of the contributor agreement before you could accept this, I'll say you can just decline/delete/ignore this and hopefully just make the change …
=> correct typo: occurs here and front install page

bigbluebutton-html5/private/static/guest-wait/guest-wait.html
Add `h1` element.
Add `lang` attribute.
Add `aria-live` to guest wait messages.
Add `BigBlueButton` string to page title.
Fixes the following accessibility issues:
1) Page title fails to include the product name stating only “guest lobby”.
2) The page lacks a declared language of the page.
3) The page lacks any declared headings.
4) When a message is pushed to the guest lobby the user is not made aware of the content change.
=> refactor: WCAG2.1 - Guest Wait Page

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Prevents an issue with the presentation toolbar size in specific conditions:
- layout is set to focus on video layout
- 1 or more cameras are being shared
- presentation is fullscreen
=> fix: presentation toolbar size in focus on video layout

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/listenonly-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js, bigbluebutton-html5/private/config/settings.yml
- feat(webrtc): add EXPERIMENTAL option to disable ICE candidate signaling 2eadf94
* ICE Lite implementations (eg mediasoup) don't need candidates signaled out-of-band; neither does KMS in certain scenarios
* Disabling their signaling saves us some ticks in bbb-webrtc-sfu and some bandwidth all around
* Default behavior is `true` (i.e.: status quo)
None (this is a experiment)
`Disabling their signaling saves us some ticks in bbb-webrtc-sfu and some bandwidth all around`
KMS in certain scenarios => use at your own risk. One is more likely to blow their feet off by disabling candidate signaling with KMS.
=> feat(webrtc): add EXPERIMENTAL option to disable ICE candidate signaling

bigbluebutton-html5/public/locales/en.json
Improves the message when the hand has been lowered. In the case a moderator lowers the hand of a participant the viewer sees the message that he/she(!) has lowered his hand despite him/her doing nothing at all. New message includes both the case a viewer lowers his hand by him/herself and the case of the moderator does it for him/her
doesn't need a separate one? :-)
BBB should be as non-confusing as possible...
Feel free to include in 2.4 and possibly even 2.3
=> Improve message when hand has been lowered

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
Show button to extend breakout rooms time for moderators only.
**Before**:
https://user-images.githubusercontent.com/56703993/134987368-81da6d92-5590-4c8e-809f-fefeab3e7e5f.mp4
**After**:
https://user-images.githubusercontent.com/56703993/134987686-8a233376-f979-4a62-8f3c-46c718f67629.mp4
=> fix: Button to extend breakout rooms time is being shown for normal users

bigbluebutton-html5/imports/ui/components/button/component.jsx, bigbluebutton-html5/imports/ui/components/button/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-close-button/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/variables/palette.scss
Adds a new button variant (muted) to be used in presentation buttons.
It utilizes the same colors used in the presentation bar.
=> change presentation fullscreen/minimize buttons color

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
Changes the color of the Leave Meeting action in options dropdown.
=> change leave meeting color

build/packages-template/bbb-html5/build.sh
Removes node-sass rebuild (used to be needed for node 12 build but now we use node 14)
Also removed the `verbose` flag for the `tar` command, so that build logs are < 5000 lines again
Closes # none
The build of bbb-html5 on branch 'develop' is not completing and on some environments I can't scroll to the bottom to see why
=> build: Remove node-sass rebuild (not needed for node 14)

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
Adds eventListener to the toggleUserlist shortcut on Firefox for macOS.
Closes #9331
=> fix: userlist shortcut on firefox for macos

bigbluebutton-html5/private/static/guest-wait/guest-wait.html, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Waiting users shouldn't count as valid participants at the meeting's
`maxParticipants` constraint.
Avoid calling `enter` at the waiting page.
Reference https://github.com/bigbluebutton/bigbluebutton/pull/10542
=> fix(guests): max participants

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx, bigbluebutton-html5/imports/ui/components/media/service.js, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
- restores `hidePresentation` feature
- removes "Your presentation will begin shortly ..." message when `hidePresentation=true`
- removes `Manage Presentations` from actions bar when `hidePresentation=true`
Closes #13256
=> fix: Hide presentation custom parameter not working

bigbluebutton-html5/public/locales/en.json
Adds a missing lang string to fix up the "undefined" message in the waiting room when meeting has been ended.
Closes #13312
bugfixing <3
That's a quick fix by adding a missing message. However, I feel like `validationError` is something which not only is being sent when the meeting has ended (so the message I chose wouldn't fit at all in these cases).
So maybe the issue here is not the missing message but the fact that a wrong error type is being sent back to the guest waiting page by the API. Please consider this possibilty while reviewing and close this PR if this has to be fixed on the API side.
Maybe should als go to `v2.4.x-release`
=> Fix missing message in waiting room when meeting was ended before being able to join

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserEmojiCmdMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx
This PR enables viewers being presenter to see the raised hand dialog and lower hands of other viewers in this case.
Closes #12357
A presenter usually is the one interacting with the participants, so he should be notified about raised hands and also being able to lower the hands if the viewers don't do it themselves.
As there are 5 "thumbs up" for the feature that presenters should also be able to lower hands, I decided to implement that :-)
Additional thoughts for the reviewer of this PR:
- A viewer usually isn't allowed to influence the emoji state of other viewers. So this PR breaks this basic rule mentioned in #12357 by @ffdixon.
- To keep this break as small as possible I only allowed this very specific case of "lowering hand" by a viewer who is presenter which leads to some ugly …
=> feat: Allow non-mod presenters to see raised hands dialog and lower raised hands

build/packages-template/bbb-html5/build.sh
This resolves an issue where we were building the npm dependencies against Meteor matching Node 12 but were trying to install locally for Node 14.
An additional change to consider could be to include the correct Meteor version in the Dockerfile for BBB but that may mean different images per BBB version.
I also leave here some simple outputs for node, npm and meteor versions, to hopefully allow us to catch such discrepancies more easily in the future
Closes # none
Get bbb-html5 building on branch 'develop'. Follow up from #13332
=> build: Specify meteor version before building

bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java
Backport to 2.4
This PR is a complement for #13316
Includes to Presentation-Checker a new checksum of a PNG that makes LibreOffice crashes.
LibreOffice can't handle with a transparent pixel used in some PowerPoint templates.
This PR makes the Pres Checker identify this pixel and avoid BBB to try to convert that presentations to PDF.
=> Avoid BBB to convert presentation with a problematic image/transparent pixel

bbb-learning-dashboard/src/components/UsersTable.jsx
This PR adds the possibility to sort the Dashboard by column Activity Score.
By default, when user click in the card "Activity Score", it sorts the data in descending order.
If user click in the column name, the order is toggled between ascending/descending.
=> Learning Dashboard: Sort data by ActivityScore in Desc/Asc order

bbb-libreoffice/docker/Dockerfile
Forces an `apt update` before `apt install`.
It fixes the following error:
```
...
#
#
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM openjdk:11-jre
---> 57108072ce35
Step 2/6 : ENV DEBIAN_FRONTEND noninteractive
---> Using cache
---> 14ebdd7614cb
Step 3/6 : RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
---> Using cache
---> 82aea50fc615
Step 4/6 : RUN apt update
---> Using cache
---> 29c8a3bbdc48
Step 5/6 : RUN apt -y install locales-all fontconfig libxt6 libxrender1
---> Using cache
---> 420ef45b377d
Step 6/6 : RUN apt install -y -t buster-backports libreoffice
---> Running in 5dd64a7d4b03
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree... …
```
=> Fix broken apt cache when installing libreoffice

bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java
Backport to 2.3
This PR is a complement for #13316
Includes to Presentation-Checker a new checksum of a PNG that makes LibreOffice crashes.
LibreOffice can't handle with a transparent pixel used in some PowerPoint templates.
This PR makes the Pres Checker identify this pixel and avoid BBB to try to convert that presentations to PDF.
=> Backport 2.3: Avoid BBB to convert presentation with a problematic image/transparent pixel

bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx
Small fix to #13363 
Fix a problem while comparing insertedTime of last breakoutRoom Url.
_PS: Already fixed in 2.3_
=> Fix: Small fix to BreakoutRoom URL comparing

bigbluebutton-html5/public/locales/en.json
As I already suspected in #13317 the root cause for #13312 seems to be a wrong return message of the API, not a missing translation message as #13312 seems to be fixed by #13371 (I tested this, it now shows the corrent "Meeting ended" message, my added language string isn't needed anymore).
Closes none, reverts wrong quick fix
This should be merged after #13371 has been merged. It also should be reverted in `develop` as soon as #13371 is being merged into `develop` as well.
I'm not sure if this language key I added should be kept in case the API returns a validationError message. If so, it definitely should contain a different message.
=> fix: Revert #13341 in favor of #13371

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Fix for cameras fullscreen position when the presentation is hidden (2.4 only).
This is already fixed in develop branch (PR #13277)
Closes #13367
=> fix: fullscreen cameras position with hidden presentation

bigbluebutton-html5/private/config/settings.yml
This is a backport of #13254 to v2.4.x-release.
> 
> This is a follow up to https://github.com/bigbluebutton/bigbluebutton/pull/12983.
> 
> Webcams already did that by default. Screen sharing and listen only were generating offers in the client, though.
> 
> After further testing I'm toggling the defaults for screen sharing/listen only as well.
None
> Refer to #12983
=> chore(webrtc): let the server generate subscriber offers by default (backports #13254)

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
Set the "goal" value of the animated effect for thickness and color items of whiteboard toolbar, so that the SVG's animate tag functions properly.
Closes #13380 
To fix the problem #13380 
It seems the behaviour of SVG's animate tag has changed. I didn't find the document. I actually thought it's dependent only on browsers. Otherwise, did React has changed something?
Before this patch:
With this patch:
=> Fix toolbar item vanish on 2.4

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
PR #13381 port to 2.4
_Set the "goal" value of the animated effect for thickness and color items of whiteboard toolbar, so that the SVG's animate tag functions properly._
=> Fix: toolbar item vanish (2.4)

record-and-playback/core/scripts/archive/archive.rb, record-and-playback/core/scripts/bigbluebutton.yml
Track the raw media files directory used by webrtc-sfu/mediasoup in the record-and-playback scripts.
None (although related to #12894)
I was going to resort to some trickery to make mediasoup raw files end up in the
same directory as KMS to reduce changes, but it ended up being too dirty.
I am adding a third directory (/var/mediasoup) to be tracked by the rap scripts
which is where the new raw files end up in.
There are still changes in other places to be done (packaging, bbb-conf et al) to make
sure /var/mediasoup is up, owned by `bigbluebutton` and writable.
=> chore(recording): track mediasoup raw media files locations

bigbluebutton-html5/imports/api/polls/index.js, bigbluebutton-html5/imports/api/polls/server/publishers.js, bigbluebutton-html5/imports/api/users/index.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/poll/service.js
This PR Creates a custom cursor for the `current-poll` and `current-user` to avoid the merge of information and handle the data separately
Make easy the use of the [`local-collections`](https://github.com/bigbluebutton/bigbluebutton/pull/13174/files#diff-08851df058fe549758f0be2caed9d522811e129e59c6943724e3f21acbd6b3deR1) and then smooth reconnection of the client.
=> Create custom cursor for current poll and user

bigbluebutton-html5/imports/api/note/server/index.js, bigbluebutton-html5/imports/api/note/server/methods.js, bigbluebutton-html5/imports/api/note/server/methods/getNoteId.js, bigbluebutton-html5/imports/api/note/server/publishers.js, bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/note/service.js
PR #13392 port to 2.4
_Remove padIds from the shared notes MongoDB collection subscription._
_Users now have to fetch the padId from Meteor when needed. Meteor is
responsible for checking the user's access level and return the
proper id._
=> fix(shared notes): avoid padId subscription (2.4)

bigbluebutton-html5/imports/api/captions/server/methods.js, bigbluebutton-html5/imports/api/captions/server/methods/getPadId.js, bigbluebutton-html5/imports/api/captions/server/methods/takeOwnership.js, bigbluebutton-html5/imports/api/captions/server/methods/updateOwner.js, bigbluebutton-html5/imports/api/captions/server/modifiers/addCaption.js, bigbluebutton-html5/imports/api/captions/server/modifiers/updateOwnerId.js, bigbluebutton-html5/imports/api/captions/server/publishers.js, bigbluebutton-html5/imports/ui/components/captions/component.jsx, bigbluebutton-html5/imports/ui/components/captions/container.jsx, bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx, bigbluebutton-html5/imports/ui/components/captions/pad/container.jsx, bigbluebutton-html5/imports/ui/components/captions/pad/service.js, bigbluebutton-html5/imports/ui/components/captions/service.js
PR #13396 port to 2.4
_Remove padIds from the closed captions MongoDB collection subscription._
_Users now have to fetch the padId from Meteor when needed. Meteor is
responsible for checking the user's access level and return the
proper id._
=> fix(closed captions): avoid padId subscription (2.4)

bigbluebutton-html5/imports/api/note/server/index.js, bigbluebutton-html5/imports/api/note/server/methods.js, bigbluebutton-html5/imports/api/note/server/methods/getNoteId.js, bigbluebutton-html5/imports/api/note/server/publishers.js, bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/note/service.js
Remove padIds from the shared notes MongoDB collection subscription.
Users now have to fetch the padId from Meteor when needed. Meteor is
responsible for checking the user's access level and return the
proper id.
=> fix(shared notes): avoid padId subscription

bigbluebutton-config/bin/bbb-conf
`Bbb-conf --check` warns about sip.js only if `sipjsHackViaWs=false`. And not for `null` or `undefined` values.
Once bbb-html5 consider `null` and `undefined` as `false`, bbb-conf should warn in this cases too.
This PR makes a small change to consider `false`, `null` and `undefined` values in the condition to warn about sip.js.
=> refactor: Bbb-conf warn about sip.js if sipjsHackViaWs is null or undefined

bigbluebutton-html5/deploy_to_usr_share.sh, build/packages-template/bbb-html5/build.sh
(does pretty much the same for both packaging and development deploy of `bbb-html5`)
* Drops the `--production` flag when installing meteor dependencies
* Adds lots of inline comments explaining why we pass what we pass and why we run two different variations of `npm install` at different times
* Removes the unnecessary step of creating an archive and then extracting
Closes # none
When building bbb-html5 with the `build/package-templates` scripts we were seeing the following error (as of lately)
```
/root/.meteor/packages/meteor-tool/.2.3.6.f552aq.1g2ai++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
throw error;
^
Error: Broken symbolic link encountered at …
```
=> build: bbb-html5 npm deps improvements

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Creating a meeting with an existing voicebridge now returns the proper error.
Closes #13556
=> duplicate voice bridge now returns the proper error

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/store/pendingAuthentications.js, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js
this PR refactors the functioning of the authToken validation function on the client-side, using the return values from meteor.call and no longer depending on any subscription or collection to validate this information
On some reconnections, the client was not reauthenticating the user, because it created more than one reference to the `auth-token-validation` subscription and could not find the one that was ready
=> Client authentication refactoring

akka-bbb-apps/project/build.properties, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GetGroupChatMsgsReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SyncGetGroupChatsInfoMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GroupChats.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/PublicChatRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/models/GroupsChatTests.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addBulkGroupChatMsgs.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/syncMeetingChatMsgs.js, bigbluebutton-html5/imports/ui/components/chat/service.js, record-and-playback/core/lib/recordandplayback/generators/events.rb
Remove `color` and `sender.name` from `GroupChatMessageBroadcastEvtMsg` and `SendGroupChatMessageMsg` events, also update the events recording script.
close #11696
=> Remove unused properties from chat message event

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/JoinMeeting.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Add a new parameter `role` in join url. The `role` parameter will take over the password. e.g. if the url have `role=viewer` and used the password for moderator, the new user will join as viewer.
Currently the user role is defined by the password information passed on join url, this PR introduce a new way to define an user role.
=> Add role parameter in join url

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
Lifting #13639 into 2.4.
SFU will also have some safeguards added to reduce the number of scenarios where state can get inconsistent, but what screen sharing really needs is a re-do of it's server side state management RPCs and that is slated for 2.5.
Closes #13245
=> fix(screenshare): bad isPresenter transition check

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/styles.scss
This PR fixes the missing publish button for user response polls.
For the case in which there is no answers yet, a label will be displayed when the user hits the publish button and the publication will be skipped:
Closes #13582
=> fix: publish button for user response polls

bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
Removes an unused button style, which constantly gives annoying warnings.
Closes #
Styles.button seems to have been removed since long time ago, by the PR #8485. But there is still a survivor which gives persistent warnings.
Edit: although my local server complains about the absence of styles.button, test24.bigbluebutton.org server does not give any such warnings...
=> Remove unused button style

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx, bigbluebutton-html5/public/locales/en.json
This PR fixes the following error when publishing a user response poll with no responses:
Closes no issue(s).
=> fix: publication for user response polls

bigbluebutton-html5/imports/ui/components/modal/simple/styles.scss, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
This PR improves the video preview modal.
- Removes the undesirable inner scrollbar.
- Makes the video preview modal "full screen" in phones.
**Samsung Galaxy S20:**
Closes #12840
=> improvement: video preview modal

bigbluebutton-html5/package-lock.json
Includes two npm dependency descriptions in package-lock.json
Closes #
We were not able to install the dependencies (at packaging step) by relying on package-lock.json because these two were undefined. Addition to #13649
=> fix: Include bintrees and tdigest in package-json (needed for prod)

bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
When joining breakouts, we now wait for the bridge to be loaded before
automatically start user's audio.
This problems happens only in the fullaudio bridge.
=> fix(audio): prevent audio to hang when user is transferred to breakout room

build/packages-template/bbb-webrtc-sfu/bbb-restart-kms
The cronjob queries the number of users. The query was still from BBB 2.2
and returned always 0. Now we take every user into account.
=> build: fix bbb-webrtc-sfu cronjob

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
This PR fixes the video preview alignment when it's "finding webcams".
Closes no issue(s)
=> fix: video preview alignment

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
Prevents issues with camera, screenshare and external video position when the presentation is minimized (focus on presentation layout).
Closes #13555
=> fix: Focus on presentation - Minimizing presentation/screenshare working incorrectly

bigbluebutton-tests/puppeteer/core/page.js, bigbluebutton-tests/puppeteer/presentation/presentation.js, bigbluebutton-tests/puppeteer/presentation/presentation.obj.js, bigbluebutton-tests/puppeteer/trigger/trigger.js, bigbluebutton-tests/puppeteer/trigger/trigger.obj.js
Adds a test that simulates a forced disconnection from Meteor, checking the behavior after reconnection.
- For this test it must have previous `sudo` permission and preinstalled external `dsniff` package - this is what breaks the tcp connection.
- Must pass after the improvements applied in #13574;
- This PR also improves how extra browser flags/arguments are added;
=> test: Adds Meteor reconnection test

bbb-learning-dashboard/public/index.html
This PR changes the Learning Dashboard's favicon to the default one.
Closes #13683
=> fix: learning dashboard's favicon

bigbluebutton-tests/playwright/README.md, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/chat/clear.js, bigbluebutton-tests/playwright/chat/save.js, bigbluebutton-tests/playwright/chat/send.js, bigbluebutton-tests/playwright/chat/util.js, bigbluebutton-tests/playwright/elements.js, bigbluebutton-tests/playwright/page.js, bigbluebutton-tests/playwright/settings/language.js, bigbluebutton-tests/playwright/settings/settings.spec.js, bigbluebutton-tests/playwright/settings/util.js, bigbluebutton-tests/playwright/user/multiusers.js, bigbluebutton-tests/playwright/user/status.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/user/util.js
This PR does the following:
- adds the first multi-page test in Playwright
- tests the locales selection (`settings` tests)
- adds a minor fix for the documentation (missing command).
Some of this code is based on the existing Puppeteer tests.
=> Playwright tests: multi-user test + testing locales

bigbluebutton-html5/imports/api/captions/server/methods/takeOwnership.js, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/icon/component.jsx, bigbluebutton-html5/imports/ui/components/layout/defaultValues.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js
Removes unused imports and exports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
=> refactor: remove unused imports/exports

bigbluebutton-html5/imports/ui/components/button/styles.js
Add missing (from sass -> styled-components conversion) styles to buttons.
=> fix: add missing styles to buttons

bigbluebutton-html5/imports/ui/components/video-preview/container.jsx
Follow-up to https://github.com/bigbluebutton/bigbluebutton/pull/13722
Didn't pay attention enough and left some garbage behind when cleaning the original garbage. Shame on me.
=> chore(webcams): cleanup unused vars in video-preview container

bigbluebutton-config/bin/bbb-conf
"bbb-conf --setip <hostname>" updates a lot of configuration files. Among other things, it also updates the "metadata.xml" files of recordings in order to have URLs pointing to the new hostname. The primarily used "sed" commands did not touch URLs when linebreaks have been between the opening XML tags and the URLs themselves or when the XML attributes are in a different order. 
The PR should fix this by using "xmlstarlet" which has been already used by "bbb-conf" for other changes/updates.
Closes #12628
Altering XML files with a line-based stream editor (like "sed") is not a good idea in general. It is always prone to exceptions to the pattern a programmer has in mind. Especially, the XML files for rather old recordings might have been generated by scripts that have been exchanged for …
=> More robust updates of recordings' "metadata.xml" when issuing "bbb-conf --setip"

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
Sets z-index attribute to screen share component, only when it is in full screen mode.
This is the same way it is done for presentation component.
Closes #13710
=> fix(layout): unable resize side panel

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx
This PR fixes the bug that prevented new layout from being pushed if the user who triggered it already had the same layout chosen locally.
If you are using "Focus on presentation" and then you decide to push the same layout to others, it doesn't trigger the push, because your front-end thinks nothing changed. Same happens for other types of layout.
=> Fix for pushing layout: attempting to push while already using chosen layout locally

bigbluebutton-html5/imports/ui/components/modal/remove-user/component.jsx, bigbluebutton-html5/imports/ui/components/modal/remove-user/styles.js
Fix typo that causes a crash in remove-user modal: `Buttom` -> `Button`
Closes #13715
=> fix: Client crashes when trying to remove a user

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
Fix wrong camera position in RTL languages (smart layout only).
`camerasMargin` value should not be applied when cameras are on top. 
Closes #13730
=> fix: webcam alignment in RTL languages - smart layout

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx
Remove seemingly unnecessary code from the text annotation.
Closes #
I am working on selectable annotations, and found out that only text annotation has a clippath with its id, which prevents my work anyhow. In my understanding, this code was added by #5532 to avoid flickering in the text area (#5467). It seems to me however, unnecessary after numerous browser updates.
=> refactor: Remove unnecessary clippath from textarea annotation on Firefox

bigbluebutton-html5/imports/ui/components/sidebar-navigation/component.jsx
Adds custom styles to prevent resize handle/scrollbar overlap in userlist.
Closes #13711
=> fix: Userlist scrollbar overlaps with resizing area

bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx, bigbluebutton-html5/imports/ui/components/modal/simple/styles.js
Adds margin-left to modal title (only when the close button is displayed) to make it centered.
This is based on @Buda9's PR (#13694), which had to be done in a different way due to [recent changes to styles](https://github.com/bigbluebutton/bigbluebutton/pull/13680)
=> style: Center modal title

bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/polling/styles.scss
It is currently difficult for screen reader users to directly navigate
to poll options. I spoke to a screen reader user, he suggested to make
the poll question title a h2 element so users can directly jump to it.
Styling was adjusted to not add extra space for the title which would be introduced by switching to an h2 tag.
=> fix: [a11y] Make poll question navigatable

build/packages-template/bigbluebutton/build.sh
Updates the Maintainer field visible when inspecting packages build via the build scripts
=> build: Update the Maintainer field for bigblutbutton

bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
Keeps polling panel active when switching to other panels, adding the possibility to navigate to chat/shared notes without losing input values of a poll that has not been started.
Closes #13512
=> Polling panel to remember "Work In Progress" polls

bigbluebutton-html5/imports/startup/server/settings.js
Changes the way configuration override file (/etc/bigbluebutton/bbb-html5.yml) is merged with default settings.
Arrays are merged, making the removal of unneeded settings impossible.
Default configuration arrays are replaced with the ones from override file (when present).
Closes #13597
=> refactor: Replace arrays in configuration override file

bigbluebutton-html5/imports/api/polls/server/methods/publishTypedVote.js
Adds a check before publishing typed poll vote, the same way it is done in other polls.
=> fix: prevent users from being able to send more than one typed poll answer

bbb-learning-dashboard/src/App.js, bigbluebutton-html5/public/locales/en.json
This PR removes the possibility to copy Dashboard link once it is not desirable.
=> Remove button to Copy Dashboard Link

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
Prevents an issue where focus is kept after clicking on previous/next/skip to slide on presentation toolbar.
Closes #13675
=> fix: Space bar does not switch to move tool

bigbluebutton-html5/imports/api/external-videos/server/streamer.js
Adds meetingId verification in external video streamer to prevent subscriptions from users that are not in the meeting.
=> fix: external video info leak

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/RegisteredUser.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSession.java, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/RegisterUser.java, bbb-common-web/src/main/java/org/bigbluebutton/api/pub/IPublisherService.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/MeetingsManagerActor.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/ToAkkaAppsSendersTrait.scala, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This PR introduces a new param `excludeFromDashboard` to be set as parameter in API `/join` (bbb-web).
Valid values:
- **false:** Default value. User will be present in the Dashboard.
- **true:** All data related to this user will be ignored by the Dashboard. Absent even from the `.json` file.
Closes #13653.
----
1. **User 1** (none params)
2. **User 2** (excludeFromDashboard=true)
3. **User 3** (excludeFromDashboard=false)
4. **Result** (User 2 absent from Dashboard):
=> feat: Add new /join param excludeFromDashboard

record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/core/lib/recordandplayback/generators/video.rb, record-and-playback/presentation/scripts/process/presentation.rb
Uses archived raw files directly instead of copying them over.
Specifies paths in XPATH expressions for faster query speeds instead of using the `//` operator.
Linting changes:
Removes useless assignments to `ext`, `metadata_with_playback` variables
Use YAML safe load and JSON parse over load
Rescue `StandardError` instead of `Exception`
Use frozen string literals
Uniform formatting
Closes #5635
Improving the performance, readability and security of the presentation recording processing script.
Developed for TU Munich's Open Source Lab course.
Example benchmark of this PR's impact:
1. Record a short meeting in BBB
2. Add a large file to the meeting's raw data to simulate a long recording:
`curl https://speed.hetzner.de/10GB.bin --output 10GB_File` **Warning - 10 GB download** 
3. Run …
=> Prevent unnecessary file copying in presentation recording processing

bigbluebutton-html5/imports/api/auth-token-validation/server/publishers.js, bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js, bigbluebutton-html5/imports/api/polls/server/publishers.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
This PR moves the data necessary for publishers to be get internally and use the parameters only to maintain publisher reactivity to data changes
List of all publishers with parameters:
- breakouts - publisher already use data from internal source the parameter is used to reactivitty
- guestUsers - publisher already use data from internal source the parameter is used to reactivitty
- meetings - publisher already use data from internal source the parameter is used to reactivitty
- users - publisher already use data from internal source the parameter is used to reactivitty
- currentPoll - added check, the value is used as the second parameter in a comparison, there is no way to override the system option
- presentationUploadToken - It already checks the parameters and uses the fields userId …
=> Removes parameters usage in the group-chat-messages and authtoken-validation publishers

bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
Changes settings dropdown z-index value so it appears in front of raised hands toast.
Closes #13580
=> fix: Menu is behind show hands popup

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Adjusts sidebar media size/position in focus on video and focus on presentation layouts when a banner is being displayed.
Closes #13805
=> fix: Banner in meeting conflicts with layout calculation

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/listenonly-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/utils.js, bigbluebutton-html5/private/config/settings.yml
- Add forceRelayOnFirefox option (false by default)
* Low effort mitigation for the problem described in: https://github.com/bigbluebutton/bigbluebutton/issues/13746#issuecomment-979390209
* iOS endpoints are ignored from the trigger because _all_ iOS browsers are either native WebKit or WKWebView based (so they shouldn't be affected)
- refactor(audio): remove unused relayOnlyOnReconnect config
* Deprecated/left behind when SIP.js was bumped from 0.7.x to 0.15.x
The new flag applies _only_ to components that support mediasoup usage (webcams, listen only and screen sharing).
None
https://github.com/bigbluebutton/bigbluebutton/issues/13746#issuecomment-979390209
=> chore: add forceRelayOnFirefox option (false by default)

build/packages-template/bbb-html5/mongo-ramdisk.conf
Add in production settings to disable js execution in mongoDB
=> disable JS execution in mongodb

akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/LockSettingsUtil.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamBroadcastPermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamSubscribePermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStartMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStopMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Webcams.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamBroadcastStoppedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamStreamSubscribedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamStreamUnsubscribedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
- Account for camera viewers in akka-apps. They should now be present in the analytics endpoint.
- Improve permission checks by making them lock-settings aware
- Further integrate akka-apps and webrtc-sfu so their states remain consistent. We'd also like to be 
able to slowly dehydrate some of the logic that today resides in webrtc-sfu and move it to akka-apps and this is a first step.
- Add additional broadcasted stream ID checks (ownership and streamID format)
None
=> fix(webcams): viewer accounting, improved perm. checks in akka-apps, [...]

bigbluebutton-html5/imports/api/auth-token-validation/server/modifiers/upsertValidationState.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/users/server/modifiers/changeHasMessages.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
- Removes user data from `voiceUsers` on leave;
- Removes user data from `users-persistent-data` on leave (only if the user did not send any messages in the chat);
- Removes `auth-token-validation` data from previous connections.
=> Remove unused user data on leave

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
When a user join the meeting but not validate the token the user isn't added to Users2x, so, when user is ejected (due to have a shared extId) the user isn't ejected because the condition to the `for` runs is have a full joined user. The PR make the ejection runs every time and the full user only when we have the Users2x data
=> fix: Fixes the validation of banned users

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss, bigbluebutton-html5/imports/ui/components/button/button-emoji/ButtonEmoji.jsx, bigbluebutton-html5/imports/ui/components/button/styles.scss, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/styles.scss, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
- Add an "advanced options" selector button to the webcam button
* Opens video-preview modal on click;
* Goal is to allow swapping of virtual background effects on the fly (underlying mechanisms were there, UI was missing);
* UI is the same as audio's device selector, behavior slightly different;
* Mobile endpoints: there's no selector button. The new behavior is: clicking the webcam button _always_ opens the video-preview modal. The selector is too tiny to be usable in mobile endpoints, so trade-offs.
* Multiple cameras: clicking the webcam button with multiple cameras shared will now _unshare all of them_. The old behavior of opening the video-preview modal is achievable by clicking the selector button.
- Add a margin to audio device selector/webcam selector button
* Make the separation …
=> feat(webcam): add a way to re-open video preview without multiple cameras

bigbluebutton-html5/imports/api/polls/server/methods/publishTypedVote.js
This is a port of PR #13757 from 2.4 to 2.3.
_Adds a check before publishing typed poll vote, the same way it is done in other polls._
=> fix: prevent users from being able to send more than one typed poll answer (2.3)

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/fullscreen-button/service.js, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
This is a port of PR #13487 from 2.3 to 2.4.
_Prevents the following bugs (all related to fullscreen on Safari browser):_
_- part of the screen becomes white when in fullscreen_
_- minimize presentation button appearing when the presentation is fullscreen_
_- presentation not using all available space when in fullscreen_
=> fix: Safari fullscreen issues (2.4)

bbb-libreoffice/install-local.sh
Based on #13183.
On Libreoffice docker install script, it creates: `/etc/sudoers.d/zzz-bbb-docker-libreoffice`
This PR improve permissions forcing:
- Root as owner and group;
- Set file mod to (not world-writable) `0440`.
=> refactor: Libreoffice - Force correct permissions for sudoers file

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy, build/packages-template/bbb-webrtc-sfu/webrtc-sfu.nginx
- chore: add user infos in custom HTTP headers to checkAuthorization's OK response
* Allows server-side endpoints to fetch userId, meetingId and voice bridge via req headers (annotated by bbb-web)
- chore: pipe user info from bbb-web checkAuth to webrtc-sfu
* Forwards the aforementioned user infos to bbb-webrtc-sfu so we can use them there
None
=> chore: add user infos in custom HTTP headers to checkAuthorization's OK, forward them to SFU

akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/LockSettingsUtil.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamBroadcastPermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamSubscribePermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStartMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStopMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Webcams.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamBroadcastStoppedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamStreamSubscribedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/streams/CamStreamUnsubscribedInSfuEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
Backports #13790 into 2.3.
>   - Improve permission checks by making them lock-settings aware
>   - Account for camera viewers in akka-apps. They should now be
>     present in the analytics endpoint
>   - Further integrate akka-apps and webrtc-sfu so their states remain
>     consistent. We'd also like to be able to slowly dehydrate some
>     of the logic that today resides in webrtc-sfu and move it to
>     akka-apps and this is a first step.
>   - Add additional broadcasted stream ID checks (ownership and streamID
>     format)
None
This also implies a minor version bump in the bbb-webrtc-sfu version BBB 2.3 uses.
The target is now bbb-webrtc-sfu v2.6.x (up from v2.5.x), making it on par with BBB 2.4.
=> [2.3] fix(webcams): viewer accounting, improved perm. checks in akka-apps, [...]

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
=> fix: typing indicator names position (2.4)

bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/styles.js
=> fix: typing indicator names position (2.5)

bigbluebutton-html5/imports/ui/components/poll/component.jsx
Prevents an issue where (after closing poll panel and opening it again) a presenter starts a regular (not anonymous) poll and is not able to see viewers answers in live-result.
Closes #13841
=> fix: Users disappearing from the polling results when they vote

bigbluebutton-html5/imports/ui/components/presentation/service.js
This fixes the presentation download. The presentation download URL was constructed the wrong way. The default configuration doesn't need a protocol specified, and in a cluster setup the protocol is defined in the settings.
Unfortunately this slipped through in commit c46556e1f65bdfee874bec3c39ff765011ee01da
Sorry for that.
=> fix presentation download

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
Makes whiteboard annotation for poll results use the same order as chat/live-result.
Closes #13280
=> Keep original order of poll answers in whiteboard annotation

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
This is a port of PR #13873 from 2.3 to 2.4.
_Makes whiteboard annotation for poll results use the same order as chat/live-result._
=> Keep original order of poll answers in whiteboard annotation (2.4)

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
We are receiving feedback that due to this 30s period that the user remains in the room, if a user exits a breakout room, that  user won't be able to re-join it until 30s elapses.
More investigation is needed but given that this 30s value is somewhat large, I'm [temporarily] reducing it to 10s. Related #13531
Related to https://github.com/bigbluebutton/bigbluebutton/issues/13832 but the full solution is deeper than this. We should open an issue about the internal plan from @TiagoJacobs and @Tainan404 
Requested by @ffdixon 
Will be further investigated likely by @Tainan404
=> refactor: Decrease time allowed for reconnection

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
Properly reference the `enableWebcamSelectorButton` config.
I missed this in https://github.com/bigbluebutton/bigbluebutton/pull/13818
None
There's no big deal in this since the default is true and the borked config evaluation also evaluates to true, so default works as expect.
This restores the expected behavior where setting `false` would disable the webcam options selector.
=> fix(webcams): bad reference to enableWebcamSelectorButton config

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
Remove `disablePortal` option from menu. 
Closes #13820
=> Fix Screen Reader Not Entering Actions Menu in FF (via Shortcut)

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
Prevents a case where the breakout panel component updates after the join button is clicked, resulting in multiple breakout windows opening at the same time.
Closes #13889
=> fix: Joining breakout rooms creates popup windows

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Fixes refresh icon misplaced on mobile when external-video is minimized.
=> fix(layout): mobile external-video refresh icon

bbb-learning-dashboard/src/App.js, bbb-learning-dashboard/src/components/StatusTable.jsx, bbb-learning-dashboard/src/components/UsersTable.jsx
This PR refactors the Learning Dashboard for supporting the grouping by `extId` rather than `intId`. Only one row per user will be displayed in the tables.
With #13826, the info will be stored using `extId` rather than `intId`. So, this PR adds the necessary Dashboard changes for matching that implementation.
=> refactor: Dashboard support for users grouped by extId

bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx
Let the whiteboard cursor travel the last mile so that the pointer reactivity gets much better (actually same as 2.2.x). 
Closes #
I saw many complaints about the whiteboard reactivity here and there since 2.3.x. I also felt it pretty uncomfortable time to time, without knowing what. 
I recently found out that one of the problems is obviously that the cursor position update happens in componentDidUpdate, so the cursor does not reflect the latest update.
I moved it to shouldComponentUpdate, but probably it is not the right place to go. Please suggest if I am terribly wrong.
Here is the result. In these movie the cursor bears black (in fact it is an XOR background texture) colour, instead of the default red colour, but never mind.
Before the change:
After the change:
=> Fix (whiteboard): cursor has to travel the last mile

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/screenshare/styles.scss, bigbluebutton-html5/private/config/settings.yml
- Adds a volume slider to screen share container when it has audio.
* ~Adds a gain node to screen share audio stream with gain interval between 0(muted) and 2(boost).~ 
* Edits by @prlanzarin: 
- Volume control is done via HTMLMediaElement's `volume` property. Gain node usage was put on hold until we can assert there are no audio quality regressions;
- Range is [0-1]; default, starting values are `1`.
- Volume control availability can be controlled via settings.yml => `public.kurento.screenshare.enableVolumeControl`
* Default is `false` (I'd prefer testing this in the wild a bit before making it available by default)
Closes #13519
=> feat(screenshare): volume control

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Fixes an issue where volume controls would fall back to mobile mode in desktop envs if the viewport was small enough.
Lack of touch events would make them inaccessible.
None
https://github.com/bigbluebutton/bigbluebutton/pull/13688#issuecomment-993732751)
=> fix(external-videos): use deviceInfo to detect mobile envs

bbb-learning-dashboard/src/components/PollsTable.jsx, bbb-learning-dashboard/src/components/StatusTable.jsx, bbb-learning-dashboard/src/components/UsersTable.jsx
This PR will truncate big names in Dashboard.
---
=> fix: Dashboard breaks with user using big name

record-and-playback/presentation/scripts/publish/presentation.rb
Adds a fallback for the fill property for older BBB versions where the fill property is missing in `events.xml`.
This script is failing for older recordings with no fill attribute. In that case,`event.at_xpath('fill')` is `nil`, failing once `.text` on `nil` is called.
Discussion with @hiroshisuga in:
https://github.com/bigbluebutton/bigbluebutton/pull/10737#issuecomment-991685610
Originally planned to include it in #13836, but since it's a small change it can be added/reviewed now.
=> Bug fix: support recordings with no fill attribute

bbb-learning-dashboard/src/components/PollsTable.jsx
Backport of a fix sent in #13861.
This PR forces the Polls to be shown in the correct creation order.
=> Fix: Forces the Polls to be shown in the correct creation order in Dashboard

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js
Excludes voice floor holder from camera quality limiter.
I don't think it's a good idea to preserve camera profiles by user role (presenter, moderator et al). Voice activity (and user pins in the future) should be enough. So:
Closes #11764
cameraQualityThresholds does not discriminate cameras by their relevance, meaning everybody gets slammed down to 2 FPS if configured to do so. That should be the case for almost everyone except those who should have a spotlight in the meeting. In this case, active talkers.
=> feat(webcams): exclude voice floor holder from camera quality limiter

bigbluebutton-html5/imports/api/polls/server/publishers.js
- makes current-poll data only available for the presenter
- user only has access to current-poll data of polls requested by the same userId
=> fix: increase current-poll security

bbb-etherpad.placeholder.sh
Before - 1.8.13
Now 1.8.16
Link to etherpad-lite's releases
https://github.com/ether/etherpad-lite/releases
Local tests were fine. No visual differences from what I can tell.
Thanks @pedrobmarin and @alangecker
=> build: Update ehterpad-lite from 1.8.13 to 1.8.16

build/packages-template/bbb-etherpad/build.sh
Switches from mconf's `ep_cursortrace` back to the official `ep_cursortrace` Etherpad plugin
Effectively revering PR #13470
The difference was https://github.com/ether/ep_cursortrace/pull/25 which was closed
=> build: use official ep_cursortrace

SECURITY.md
Supporting BBB 2.3 and 2.4 while developing the next BBB (likely to be called 2.5).
=> docs: Update SECURITY.md for 2.4

bigbluebutton-web/bbb-web.nginx, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
For the sake of backwards compatibility
Backport of #13941 to 2.3.
=> [2.3] chore: add legacy checkAuthorization endpoint

bigbluebutton-web/grails-app/conf/spring/resources.xml
Setting wasn't being picked up by bbb-web/bigbluebutton.properties.
Only worked as a `create` parameter.
Forgot about that one in #13915.
None
=> fix(webcams): missing allowModsToEjectCameras in resources.xml

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/playwright.config.js, bigbluebutton-tests/playwright/settings/language.js, bigbluebutton-tests/playwright/settings/settings.spec.js, bigbluebutton-tests/playwright/settings/util.js
This PR improves the locales test: it does all the actions within one browser session, instead of creating a new session for each locale.
- looping through the locales within one browser session
- using `data-test` instead of `aria-label` for selecting the options button in the navbar (`aria-label` changes its value when language changes, so it can't be used for the locales test)
- increasing the timeout for Playwright tests to 3 minutes (the default value isn't enough for looping through all locales).
=> test: Playwright- fixes for the locales test

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx
- Fix a client crash on camera user ejections (the old user collection data is nullish drill)
- Added extra proptypes validation to video-list-item
- Made sure to add extra ?. checks to voiceUsers in video-list-item as well because... who knows? 
- Removed unused user role prop from video-list-item
None (although this can be considered a regression of #13835)
=> fix(webcams): fix client crash on camera user ejection

bigbluebutton-html5/imports/ui/components/fallback-errors/fallback-view/component.jsx
`FallbackView` component was referencing wrong locale keys.
I supposed it meant these: https://github.com/bigbluebutton/bigbluebutton/blob/9e371dc0414a1337979267bc84d05545906218b2/bigbluebutton-html5/public/locales/en.json#L586-L588
The ones currently being used are undefined.
None
=> fix: wrong locales keys on FallbackView

bigbluebutton-html5/imports/ui/services/virtual-background/index.js
to cover container with Virtual background instead of stretch
This PR adds drawImageProp function to cover container with Virtual background instead of stretch (see 1st answer in https://stackoverflow.com/questions/21961839/simulation-background-size-cover-in-canvas)
This is fix for stretched virtual background image in case of non-standard camera aspect ratios. Image covers container instead of stretch.
Compiled main meteor js for quick test is available in my repo https://github.com/drlight17/bbb-html5client-vb-cover. See README.
=> added drawImageProp function

bigbluebutton-html5/imports/ui/components/external-video-player/volume-slider/styles.scss
Add a padding to the volume slider.
=> fix(video): borderless/ugly volume slider

bigbluebutton-html5/imports/ui/components/screenshare/styles.scss
Custom color isn't applied in the screenshare container. This PR fixes it.
=> fix(style): custom style in screenshare container

bigbluebutton-config/cron.daily/bigbluebutton
=> Fix #13994 - bigbluebutton cron job inadvertently deletes /var/bigbluebutton/learning-dashboard

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
This PR removes the grace period for locked users and remove the behaviour of eject the locked users who sent chat messages (because there might be delayed messages sent between changing the lock setting)
=> Remove Grace Period for locked user in chat

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
Prevents a visual bug with the welcome message not being correctly displayed in specific conditions.
Tested in Firefox with a 1920x1080 23" monitor.
```
وینک قلبی اتعذب فی هواک وینک قلبی العاشق ما ینساک لا جوابات یا ناسینی فیهم شوق و ود وشایلین سلامات کل یوم راح تجینی ترد لقلبی البسمه و للیل النجمات عندما یحب الرجل المرأة بصمت .. یخسر کل شیء حتى هی… وعندما تحب المرأة الرجل بصوت.. تخسر کل شیء حتى هو! ففی الحب الصمت جریمة الرجل والصوت جریمة المرأة…
اربك تكست هو اول موقع يسمح لزواره الكرام بتحويل الكتابة العربي الى كتابة مفهومة من قبل اغلب برامج التصميم مثل الفوتوشوب و الافترايفكتس و البريمير و الافد ميدا كومبوزر و السموك و برامج اخرى كثيرة
```
```
Willkommen zu "<b>%%CONFNAME%%</b>"<br><br>Eine kurze BigBlueButton-Einf&uuml;hrung in Form von Video-Tutorials findet sich unter: <a …
```
=> fix: welcome message overlap

bigbluebutton-html5/imports/ui/components/user-list/service.js
Adds locked label and unlock option to userlist if **see other viewers in Users list** is the only active lock.
Closes #13958
=> fix: See other users in user list lock

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
Replace the webcam icon in the user list for the pin icon when an user's pinned.
Make it clear in the user list that a user's webcam is pinned.
=> fix(webcam): user list pin icon

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
Fix a problem that username in video container isn't wrapped if it's too long.
Fix a problem that can cause the audio indicator to disappear.
Fix some problems with the overflow property.
Refactor in css for the talking indicator be more centralized
Closes: https://github.com/bigbluebutton/bigbluebutton/issues/13839
=> fix(video): webcam video username dropdown

bigbluebutton-html5/imports/ui/components/chat/time-window-list/styles.scss
this fixes autoscroll not goint all the way to end of the scrollbar
Essentially reverts [#4802](https://github.com/bigbluebutton/bigbluebutton/pull/4802), the problem does not happen anymore on firefox.
=> fix(chat): remove empty area after message list

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/public/locales/en.json
Previously these notifications would not be available unless the user list was open. This PR updates the screen reader alert for new messages so that they are announced even when the list is closed.
Related to #10942
=> Update SR New Message Notification 

bigbluebutton-html5/imports/ui/components/video-preview/styles.js
Fixes incorrect alignment while it's waiting for the user to grant/deny camera permissions.
Before:
After:
Closes #14038
=> fix(video preview): bad alignment

bigbluebutton-html5/imports/ui/components/menu/styles.scss
Changes max-width value for dropdown menus, allowing the new Learning Dashboard name (Learning Analytics Dashboard) to fit in one line.
Does not have a related issue, suggested by @ffdixon [in a comment](https://github.com/bigbluebutton/bigbluebutton/pull/14027#issuecomment-1008305955)
=> change dropdown menu max-width value

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
The component name were out of the form, then i changed from 'UserMessage' to 'UserMessageContainer'
Keep the name in the norm
=> refactor: Container name out of the form fixed

bbb-common-web/src/main/java/org/bigbluebutton/api/LearningDashboardService.java
Closes #13692.
Bbb-web was crashing when receiving big numbers for `learningDashboardCleanupDelayInMinutes`.
Once it was being converted to milliseconds and it was becoming higher then Java limit (`Integer.MAX_VALUE`).
Now Bbb-web uses `Date` instead of `int` as parameter for `schedule` and so it supports numbers like `252000` perfectly.
=> fix: API crashes when a big number is set for learningDashboardCleanupDelayInMinutes

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
Changes audio modal behavior when `userdata-bbb_listen_only_mode` is set to `false`.
When audio modal is mounted with listen only disabled, the microphone button is displayed and the user needs to click on it in order to start echo test.
When audio modal is mounted with listen only disabled, it will start echo test without the need of clicking microphone button (like it was in bbb 2.2).
Closes #12681
=> fix: Different behaviour on userdata-bbb_listen_only_mode=false

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
Prevents an issue with the _forceCacheUpdate_  method (added in #14023) where the wrong index could be recomputed, causing an infinite loop.
=> fix: forceCacheUpdate method

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PollsMsgs.scala, bigbluebutton-html5/imports/api/polls/server/handlers/userTypedResponse.js
Sometimes a vote for a new answer text was being computed as a vote for the first option due to poll collection late update.
I changed the `UserRespondedToTypedPollRespMsg` message in akka to return the new answerId directly to avoid having to search it in html5.
=> fix(polls): fix wrong typed poll results due to race condition

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Prevents webcam/speaker list overlap in breakout rooms and specific conditions:
- Custom layout + presentation minimized
- Focus on presentation layout + presentation minimized
- Focus on video layout
Closes #13933
=> fix: Webcams overlap speakerlist in Breakout Rooms

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/ui/components/legacy/component.jsx
Appends build string to locales requests, preventing an issue where an old translation file would stay in browser cache after BBB version update.
Closes #13984
=> fix: html5 client loads outdated language file from browser cache after update

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx
Forces the video preview modal opening when triggered by the webcam selector button regardless of skip video preview userdata. This fixes webcam selector button with no action when skip video preview is set(`usedata-bbb_skip_video_preview=true`).
Closes #14073
=> fix(webcam): unresponsive webcam selector button

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/SyncGetScreenshareInfoRespMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala, bigbluebutton-html5/imports/api/screenshare/server/eventHandlers.js, bigbluebutton-html5/imports/api/screenshare/server/handlers/screenshareSync.js
Addresses a _TODO_ 5 years in the making.
Partially fixes https://github.com/bigbluebutton/bigbluebutton/issues/14072 which is two different issues in itself.
This targets:
```
Second way to reproduce:
4b. restart bbb-html5* services (sudo systemctl restart bbb-html5*) or technically just the backend the meeting is on
The meeting should recover (depending on the .service including #13527) but nobody will be able to take control of the presentation area because akka-apps(?) has on record that screenshare is 
```
A fix for the presenter disconnection (which is kind of _unclear_ on how to reproduce since not all disconnections cause that to happen) will land in a separate PR.
Partially addresses https://github.com/bigbluebutton/bigbluebutton/issues/14072
Noitavitom
=> fix(screenshare): add state sync between bbb-html5 and akka-apps

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
Fixes #14084 by option 1.
Makes the camera button on mobile always open the video preview modal If the user is already sharing camera.
This allows mobile users to switch virtual backgrounds.
Closes #14084
=> fix(webcam): unresponsive camera button on mobile

build/packages-template/bbb-html5/bionic/bbb-html5-backend@.service, build/packages-template/bbb-html5/bionic/bbb-html5-frontend@.service
Restarts a failing bbb-html5* sevice (check the constraints) to restore the capacity of a server.
In BBB 2.3 we encountered a number of bbb-html5* crashes (OOM, etc) which were inconvenient, especially the bbb-html5-backend ones.
Credits to @zhem0004 . Cherrypicking the original PR was a bit messy though, so I included the changes in 1 commit.
Closes # none
Backport of #13527
This change is also included in the packaging for BBB 2.4 as of BBB 2.4.1, so including this PR in the open source build scripts   keeps the sync.
=> build: Added auto restart of bbb-html5-backend and frontend on failure

bigbluebutton-html5/private/config/settings.yml
Enable camera pin and screenshare volume control features by default.
They were added in v2.4.x as hidden/false-by-default features since they were late to the party,
but they should be enabled by default in v2.5.
None
=> [2.5] chore(bbb-html5): enable camera pin/screenshare volume control by default

build/packages-template/bbb-etherpad/after-install.sh, build/packages-template/bbb-etherpad/opts-bionic.sh, build/packages-template/bbb-freeswitch-core/after-install.sh, build/packages-template/bbb-freeswitch-core/opts-bionic.sh, build/packages-template/bbb-freeswitch-sounds/opts-bionic.sh, build/packages-template/bbb-html5/after-install.sh, build/packages-template/bbb-html5/opts-bionic.sh, build/packages-template/bbb-web/opts-bionic.sh
`fpm` was called with the dangerous `--deb-user`, `--deb-group` and `--deb-use-file-permissions` command line options. All files in packages should be owned by root.
The dangerous `fpm` options are still used in the `bbb-lti` package. I did not modify this because I don't use LTI and have no idea if something breaks if this is changed.
Closes #11752
Closes #10831
=> Fix: ensure services can't modify their code

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Prevents an issue where custom styles will fail to overwrite body background because of hardcoded styles.
Closes #14079
=> fix: body background gets overwritten by .layout--Z2pPMwf

bigbluebutton-html5/imports/ui/components/poll/component.jsx
Fixes strange typing behavior in poll option text fields
Closes #14098
Find a bug, fix it
The intention of the existing part of code probably(!) was to
1) avoid multiple whitespaces
2) avoid leading whitespaces
The problem of the current implementation is that this is already done while the user is typing and not when submitting the poll which leads to the problematic behavior described in #14098.
Now improved:
- You still can't enter multiple whitespaces
- You can't insert whitespaces at the beginning
- Hitting a whitespace at the beginning when already having some text will now not remove the text, but just ignore the whitespace input
- Even if you copy and paste text into the input field, leading and doubled whitespaces will be properly removed (before that PR pasting wouldn't have …
=> Fix: Improve typing input behavior of poll option text fields

bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Fix an error that the hide/show button does not work when there is external
video/screenshare and the layout is "videoFocus".
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14100
=> fix(layout): hide/show media in videoFocus

record-and-playback/screenshare/scripts/screenshare.yml
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/14019 to BBB 2.4
Thanks @jgribonvald !
=> fix(recording): not processed screenshare fix issue #13356

bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
If a user tries to rejoin the meeting after being removed, some logs will be logged with the level of 'error'. This PR changes the level to 'warn'.
Closes #13944
Those logs don't seem to be 'errors'. So, They don't need to be treated as such.
=> fix: change log level from 'error' to 'warn'

bigbluebutton-html5/client/main.html, bigbluebutton-html5/client/stylesheets/bbb-icons.css
Appends build string to font requests, preventing an issue where an old font file would stay in browser cache after BBB version update.
Closes #14094
=> fix: append build string to font requests

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx, bigbluebutton-tests/playwright/chat/characterLimit.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/chat/emptyMessage.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/core/util.js, bigbluebutton-tests/playwright/notifications/util.js, bigbluebutton-tests/playwright/stress/stress.js, bigbluebutton-tests/playwright/stress/util.js
This PR updates Playwright tests to do the following:
- Add additional chat tests.
- Improve selectors (using `data-test` instead of `aria-label`; `aria-label` is unrealiable, because it changes with language).
- Fix the utility function that's used in the stress test (caused an error).
=> test: Playwight: new chat tests, improved selectors, fixed stress test

bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss
- Adds a subtle margin around the _text box_ in order to prevent focus outline from overflowing.
Before:
After:
Closes #13955
=> fix(waiting users): text box outline

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/ClearWhiteboardPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/ModifyWhiteboardAccessPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/UndoWhiteboardPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/WhiteboardApp2x.scala
<p>This PR changes the way grace period in permission check works. </p>
<p>Before: After permission is removed, permission checks would still pass for 5 seconds in case a message came late.</p>
<p>Now: Permission is removed immediately, but no one gets ejected for failed permission for 5 seconds</p>
=> FixGracePeriod

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
Changes what happens when screenshare ends (like it was in bbb 2.2).
Presentation is restored after screenshare ends (even if it was hidden when screenshare started).
If the presentation is closed when screenshare starts, it will not be restored after screenshare ends.
Closes #14069
=> fix: Keep the state of the presentation after sharing the screen

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Adds a text hint about the accepted presentation file size limit on the presentation upload modal.
Currently, the user is informed about the presentation size limit only when a uploading error occurs.
Therefore, this is intended to inform users about the presentation size limit before they attempt to upload a file.
=> refactor(presentation): extra hint upload limit

record-and-playback/core/lib/recordandplayback/generators/presentation.rb
Make BBB to generate thumbnails from the presentation file uploaded by users, not from default.pdf, which happens always in my server. 
I found it weird that nobody reports it. I am scared that this is only happening to me...
If not, the bug seems to be that "originalFilename" tag is not present in "SharePresentationEvent" in metadata.xml. 
Same PR in #9570 , but this PR is for the release 2.2. Apologizes if this violates the PR rule here.
I post this here in part because of the PR in Greenlight.
https://github.com/bigbluebutton/greenlight/pull/1796
In this PR I tried to implement a selectable thumbnail dropdown for the room owner. 
Discussions opened in https://github.com/bigbluebutton/greenlight/issues/1767 and #9811.
=> fix(recording): Generate thumbnails from uploaded file

record-and-playback/core/lib/recordandplayback/generators/presentation.rb
In the playback list the thumbnails are always being generated from default.pdf.
This seems to be a bug; "originalFilename" tag is not present in "SharePresentationEvent", and thus presentation_filename would never be "default.pdf".
=> fix(recording): Generate thumbnails from uploaded file (backport)

bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
Fix for a bug that would display the wrong icon when user is muted or listen-only (the "voice" icon is displayed instead).
=> fix: mute + listen only icons in userlist

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
- Enforces `mirrorOwnWebcam` value on video dock, not only on video preview.
- Currently the webcam always starts unmirrored on video dock.
Closes #14130
=> fix(webcam): initial webcam direction

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/webcam/component.jsx
Adds a different background-color (`--color-content-background`, the same color used in screenshare) for presentation/cameras when positioned in sidebar-content.
Closes #14153
=> Add a different background color for contents that are being displayed under the side panel

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- Add extra error handling to publisher's peer creation callback
- Add extra error handling to subscriber's peer creation callback
Essentially addresses some scenarios where errors were uncaught and not logged properly.
None
video-provider is a race-condition prone mess and those callbacks were missing try-catches so eventual failures would bubble up as uncaught errors and not be logged properly.
It's worth mentioning that due to a number of tangential design failures in that component, 90% of the errors generated there are, to the end user, invisible false positives. 
Thus: expect an increase in false-positive error logs with this.
=> fix(webcams): add extra error handling to pub/sub peer callbacks

bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
Restores missing variable in presentation focus layout, removed when merging 2.4 into 2.5.
=> fix: restore missing variable

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/ScreenshareModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StartExternalVideoPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
- Adds a server-side screen share broadcast ejection procedure between akka-apps and webrtc-sfu
* akka-apps now requests an internal stream shutdown _before_ notifying a broadcast stop to the client
* Current behavior is notify the client and then hope the stream closes
- akka-apps: change screen broadcast shutdown trigger on external video start to the new approach
- akka-apps: add a screen broadcast shutdown trigger when the presenter changes
- akka-apps: small refactor in `ScreenshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr`
Partially addresses #14072 (hopefully)
#14072
Needs https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/b9238526ae71631e56f9e78a774ea21a2e1652d0 (still untagged) to be effective; development branch.
=> fix(screenshare): add akka-apps|webrtc-sfu broadcast stop sys msg

build/packages-template/bbb-etherpad/after-install.sh
Fixes installation crash of etherpad during fresh BBB installations. Bug was introduced in this commit: https://github.com/bigbluebutton/bigbluebutton/commit/5cce940346b8e49fc67b9d5a7e522fc5955c3ac7
None
Our deployment failed.
Nothing
=> fix missing directory error for etherpad installation

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/utils/dom-utils.js, bigbluebutton-html5/public/locales/en.json
Adds a polite screen reader alert to inform the user of presentation slide changes.
(the polite alert will not interrupt any ongoing announcements).
The new presentation alert was working as expected.
Closes #14141
=> Add Polite Presentation Slide Change Announcement (Screen Reader)

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
Switches breakout room related user_action logs from debug to info.
Closes # none
These log keywords come in handy when debugging whether a student intentionally did an action X or the system (or moderator?) did it instead. I am switching them to .info as they are occasionally needed on production systems for debugging but debug level is not really a recommended production log level.
Requested by @ritzalam 
The rest of the `user_action` logs I find are all `info` level
=> refactor: Switch user_action logs from debug to info

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/AppsTestFixtures.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/services/virtual-background/service.js
This PR implements a new param called `virtualBackgroundsDisabled` to API.
_By default the value is false._
Options:
**true**: Virtual Backgrounds will be disabled for this meeting.
**false** or absent: Virtual Backgrounds will respect the configs set in `settings.yml`.
Closes #13964.
https://user-images.githubusercontent.com/5660191/149225027-a8ab67b9-7553-40bf-84ff-412d14c04f70.mp4
=> Add param to disable Virtual Backgrounds in API /create

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
Add a create meeting parameter to enable or disable the user's cookie
session requests.
`allowRequestsWithoutSession=true/false`
=> feat(api): allowRequestsWithoutSession as a meeting create param

bigbluebutton-html5/package-lock.json
Updates caniuse-lite browser data. It should remove the following warning (displayed when using `npm start`):
_Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest--update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating_
=> chore: update caniuse-lite

bigbluebutton-config/bin/bbb-record
Extends BigBlueButton's recording diagnostic utility with permission and ownership checks that may help in circumstances where recording processing is not starting.
Checks were written based on the configuration set in the `after-install.sh` script, community feedback as in [#12627](https://github.com/bigbluebutton/bigbluebutton/issues/12627) and [#9279 ](https://github.com/bigbluebutton/bigbluebutton/issues/9279), and personal experience.
- The`list-recent` option has been documented in `--help`.
- Introduces a `--list-workflows` option.
- Informs about playback protocol.
There were no configuration checks for the default presentation format.
Developed for the Open Source Lab at TUM.
[x] Lint with shellcheck:
- Replace cat with `'cmd < file | ..' or 'cmd file | ..'`
- Use `./*glob*` or …
=> bbb-record: refactoring, more config checks, list-workflows option

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SelectRandomViewerReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/EjectUserFromVoiceCmdMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala, bigbluebutton-html5/imports/api/voice-users/server/methods/ejectUserFromVoice.js, bigbluebutton-html5/imports/ui/components/user-list/service.js
Closes #14002
Fixes the issue where users have been getting banned from the meeting after being removed, while connected via phone call
<h3>Motivation</h3>
Previously: If moderator removed a user connected via phone-call - user would get banned regardless of the moderator's choice
Currently: Moderator can choose whether the user will be able to reconnect after getting banned.
=> Fix: Removing phone users always bans them

build/packages-template/bbb-pads/after-install.sh
JSON file format requires double quoted string data. Add quotes when configuring
ETHERPAD_API_KEY at bbb-pads build scripts.
=> fix(pads): add double quotes to APIKEY

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx
Removes unused imports and exports reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
=> refactor: remove unused imports/variables

bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/container.jsx
Prevents an issue where the sidebar content panel would close for non-presenters when userlist updates.
Closes #13963
=> fix: close sidebar panel for non-presenters

bigbluebutton-config/bin/bbb-conf
Corrected the path for bbb-pads so we can see it when running `bbb-conf --status`
After:
`bbb-pads ——————————————► [✔ - active]`
=> fix(config): correct path for bbb-pads.service

bigbluebutton-html5/imports/ui/components/screenshare/styles.js
Restores missing styles for screenshare (presenter view)
=> fix: screenshare position regression

bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_sfu.xml, bbb-webrtc-sfu.placeholder.sh
- chore: bump bbb-webrtc-sfu to v2.7.0-alpha.1 
* Bidirectional media flows with single transport in mediasoup (#14020)
- feat: add new dialplan rule for bbb-webrtc-sfu calls
Closes #14020
Dialplan rationale in commit message details (3d1b2c8)
=> chore: webrtc-sfu@v2.7.0-alpha.1 (full audio + mediasoup)

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This is an improved version of #14127, which can be closed.
Fixes a bug, in which a filename by Asian letters is not decoded when pre-uploaded from Greenlight. 
I tested this PR and confirmed working on 2.4.x. 
By mistake, I submitted this against "develop" branch. Let me know if I have to resubmit it against 2.4.x
It can be fixed also in Greenlight, but BBB should have this fail-safe fix to make the API robust.
Below are the screenshots explaining the bug:
This is when the presentation is pre-uploaded from GL.
Here, the file above is pre-uploaded from GL, and the one below is a newly uploaded one from HTML5 client. The latter is displayed correctly.
=> fix(bbb-web) broken Asian filename for pre-uploaded presentation (fix on bbb-web)

build/packages-template/bbb-html5/bionic/bbb-html5.nginx, build/packages-template/bbb-html5/build.sh
The BBB html5 client is huge and can be compressed easliy. As nginx
already services the static files, it can also handle service gzipped
files.
Ship compressed files with the package.
When benchmarking my cluster proxy setup, I let many clients join in a short time frame. I noticed that client loading needed a lot of bandwidth, much more than for example video traffic. So I started investigating...
If we had a more recent Ubuntu and nginx, we could also serve brotli compressed files which reduces the size of the Javascript from 3.6 MB to around 600k instead of 900k with gzip.
@antobinary you might want to adapt this to the scripts building the official packages.
=> fix: serve compressed Javascript and CSS

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
This small patch enables the translation of "blur" for the virtual background picture selection modal.
Closes a half of #14222
To have the same style (translation) with other thumbnails. 
before:
after:
=> fix(virtualBG): snippet "blur" translation

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
Removes extra parentheses from virtual background blur label (client was crashing during startup process because of this).
=> fix: remove extra parentheses from virtual background label

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.scss
This small patch prevents the null and blur thumbnails from being shrunken in the virtual BG selection modal, when more than one custom BG picture is added.
Closes a half of #14222
For a cosmetic reason.
Before:
After:
=> fix(virtualBG): recover shrunken thumbnails on the modal

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala, bbb-webrtc-sfu.placeholder.sh
- Bump bbb-webrtc-sfu to [v2.6.8](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.8)
- refactor(screenshare): add voiceConf to ScreenshareBroadcastStopSysMsg
* Just to make it easier to guarantee idempotence in webrtc-sfu while we don't get rid of voiceConf usage
n/a
n/a
=> build: bump bbb-webrtc-sfu to v2.6.8

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
Removes "first join" information (from video preview and echo test) when a user leaves the meeting, preventing an issue where `getEchoTest` and `isFirstJoin` data could be preserved from a previous session.
Closes #14132
=> fix: remove audio/video first join info on meeting end

bbb-webrtc-sfu.placeholder.sh
Bump bbb-webrtc-sfu to v2.7.0-alpha.4.
This makes mediasoup the default media server for everything except recordings
n/a
=> build: bump bbb-webrtc-sfu to v2.7.0-alpha.4 (mediasoup is default)

bigbluebutton-html5/imports/api/connection-status/server/modifiers/updateConnectionStatus.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/changeHasConnectionStatus.js, bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/changeHasMessages.js, bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
Makes the following changes, which makes disconnected users data available to moderators:
- move hasMessages from Users collection to shouldPersist.hasMessages in UsersPersistentData collection;
- add shouldPersist.hasConnectionStatus to UsersPersistentData collection;
- only remove data if both `shouldPersist.hasMessages` and `shouldPersist.hasConnectionStatus` are false;
- filter data on UsersPersistentData publisher based on user role (connection status of offline users is only available to moderators).
User data is removed on leave unless the user sends a message in chat.
Logged out users data remains available to moderators even if the user did not send any message in chat, and available do viewers if the user sends a message in chat.
Closes #14099
=> fix: Disconnected users omitted from connection history

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamBroadcastPermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
- Add streamId to broadcast permission checks
* Guarantees better enforcement of stream ownership
- Always run camera lock settings enforcement on user demotion
* Checking for the user locked state before running the procedure is not entirely
correct since some lock settings should always be applied. An example of this
the See other viewers lock which must be enforced on demotion regardless of
whether the demoted user is locked or not.
n/a
n/a
Works with webrtc-sfu@v2.6.9
=> fix(webcams): add stream ID to broadcast check, better lock setting enforcement

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetCamBroadcastPermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/14269 into v2.3
> ### What does this PR do?
> 
> - Add streamId to broadcast permission checks
>   * Guarantees better enforcement of stream ownership
> - Always run camera lock settings enforcement on user demotion
>   * Checking for the user locked state before running the procedure is not entirely
> correct since some lock settings should always be applied. An example of this
> the See other viewers lock which must be enforced on demotion regardless of
> whether the demoted user is locked or not.
> 
> ### Closes Issue(s)
> 
> n/a
> 
> 
> ### Motivation
> 
> n/a
> 
> ### More
> 
> Works with webrtc-sfu@v2.6.9
=> [2.3] fix(webcams): add stream ID to broadcast check, better lock setting enforcement

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.scss
Removes mobileHide styles from talking indicator, allowing the display of the talking indicator in mobile devices even when the sidebar content is open.
Closes #14272
=> fix: Talking indicator element not showing on mobile with content sidebar open

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/SyncGetScreenshareInfoRespMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala, bigbluebutton-html5/imports/api/screenshare/server/eventHandlers.js, bigbluebutton-html5/imports/api/screenshare/server/handlers/screenshareSync.js
Backport of #14076 and #14091 to 2.3 (from 2.4)
Newly added: 
- refactor(screenshare): add voiceConf to ScreenshareBroadcastStopSysMsg
* Just to make it easier to guarantee idempotence in webrtc-sfu while we dont get rid of voiceConf usage. Will lift to v2.4.
None
- Intentionally left some mismatched parts out of the backport (the server-side ejection on external video start).
=> [2.3] fix(screenshare): add state sync, akka-apps|webrtc-sfu broadcast stop sys msg

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/public/locales/en.json
Changes toast notification text from "Screenshare has stopped" to "Screenshare has stopped due to data saving" whenever screenshare stops due to data savings.
Closes #14277
=> (Optional) fix(screenshare): change toast notification text

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
Restores "real" fullscreen feature to presenter toolbar shortcut (when **enter** is pressed).
=> fix: fullscreen presentation shortcut in presenter toolbar

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
Makes smartLayout ignore presentation size in screenshare and external video size calculation.
Closes #13990
=> fix: Smart layout under some circumstances not behaving as expected when sharing video or screen

bigbluebutton-html5/imports/ui/components/media/autoplay-overlay/styles.scss
Prevents the _autoplay overlay_ from overlapping the _echo test modal_.
**Before:**
**After:**
Closes #14298
=> fix(screenshare): decrease autoplay-overlay z-index

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Replace the hardcoded guest's waiting timeout between polling requests - reference used
to remove a guest from the waiting list when the user leaves the waiting page - with a
bbb-web's configuration property.
=> feat(guest): configurable wait timeout

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Makes every room box the same size and increases "not assigned" box height (3 times the height of room boxes).
Closes #13123
=> Increase create breakout room users list height

bbb-pads.placeholder.sh
Bumps bbb-pads build version to the latest
None
bbb-pads' release v1.0.2 mitigates an issue on BigBlueButton server's start routine that was causing a false APIKEY mismatch error at bbb-pads.
=> build(bbb-pads): bump v1.0.2

bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx
Changed the format of number values in the gettingMeetingInfo template to remove commas.
Closes #14337
=> fix: Change format of number values in getMeetingInfo

bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx
Backport of #14348
*What does this PR do?*
Changed the format of number values in the gettingMeetingInfo template to remove commas.
=> fix: Change format of number values in getMeetingInfo - backport #14348

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
_Fixes an undesirable scrollbar on presentation upload toast notification in RTL mode._
**Then:**
**Now:**
Closes #12168
=> fix(presentation): toast notification in RTL mode

build/packages-template/bbb-freeswitch-core/build.sh
Allows the patch `audio.patch` to be applied despite the difference in whitespace (spaces vs tabs, etc) so the patch can be included prior to compiling
Closes # none
When I tried this locally it failed to apply the patch
=> fix(FS): Allow patch with different whitespace

build/packages-template/bbb-html5/mongod_start_pre.sh
Closes#13257
<h3> What does this PR do? </h3>
The main purpose of this change is to  get rid of misleading error messages of mongod by redirecting them to /dev/null.
Before - id: ‘mongod’: no such user
Currently no message is received.
<h3> References </h3>
It was suggested by https://github.com/playernine
=> Implemented the fix regarding mongod error messages

build/packages-template/bbb-apps-akka/build.sh, build/packages-template/bbb-web/build.sh
Copy to build scripts the same commands added on #14346.
It will force to remove all cached .jar before publish `common-message`  and `bbb-common-web` during the build.
=> (build) Clear cache before publish common-message and common-web

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
Uses `dangerouslySetInnerHTML` for injecting HTML so that links will be evaluated properly.
Closes #14374
The sanitizing part is done here: https://github.com/JoVictorNunes/bigbluebutton/blob/6fe2b69dc784b018dddb25f6e2667131542b6589/bigbluebutton-html5/imports/api/group-chat-msg/server/methods/sendGroupChatMsg.js#L15-L29
So, the message content is already sanitized on the browser, which prevents security issues like XSS attack.
=> fix: URL display in chat push notification

akka-bbb-apps/run-dev.sh, bbb-common-message/deploy.sh, bbb-common-web/deploy.sh, build/packages-template/bbb-apps-akka/build.sh, build/packages-template/bbb-web/build.sh
Instead of removing the old .jars, there is a better way to force the projects to retrieve the last version of external libraries.
It is using `sbt update` command.
https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html
This PR reverts the previous "clear cache" approach sent in #14346 and #14377.
And include the command `sbt update` before run/compile Akka, Common-web and Bbb-web.
=> fix: Force update of common-message and common-web libs

bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
Changes the chat notifications to only display notifications when another user sends a message in the chat.
Closes #14375
=> fix: Chat notifications are displayed for the user own messages

bigbluebutton-html5/private/config/settings.yml, build/packages-template/bbb-html5/after-install.sh
On package `bbb-html5` installation we try to set the value for `bbbServerVersion` to what the component `bbb-config` contains -- a reliable source of full BBB version.
Together with https://github.com/bigbluebutton/bigbluebutton/pull/14281 this PR closes  #10443
I also enable by default `displayBbbServerVersion`
Closes #10443
See #10443 and #10451
=> build: Automatically set bbbServerVersion in settings.yml

build/packages-template/bbb-html5/bionic/bbb-html5-backend@.service, build/packages-template/bbb-html5/bionic/bbb-html5-frontend@.service
This PR sets stat limit action to none. Since in 2.5 "exit " is not recognised, this is a functionally similar replacement. 
Closes #14338
Previously:
When action exit worked it used to exit the execution when the limit of restarts on failure was hit. 
However action exit is no longer being recognised, thus error below would be thrown
`Failed to parse failure action specifier, ignoring: exit`
Failure to exit could cause restarting infinitely
Currently:
In case of "none" it does not exit explicitly, but rather prevents start when StartLimit is reached.
For example id back-end reaches restart frequency limit error message bellow will be thrown and it will no longer restart automatically.
`Failed to start BigBlueButton HTML5 service, backend instance 1.`
=> fix: change StartLimitAction to none

bigbluebutton-html5/public/locales/en.json
Add a locale for when the guest user reach the status of  `meetingForciblyEnded`, that means the guest user was in guest while a meeting has been ended
Closes  #14366
How I reproduced:
- Change locale to DE
- Join a meeting as moderator
- Make sure guest police is `ask moderator`
- Join with a guest user 
- end the meeting trough settings dropdown
=> fix(guest-wait): Add missing locale meetingForciblyEnded

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx
Adds tooltips to user names in userlist, displaying the entire name on mouse hover.
Closes #14402
=> Add tooltips to user names in userlist

build/packages-template/bbb-apps-akka/build.sh, build/packages-template/bbb-fsesl-akka/build.sh
In this PR I use the passed value ($1) as a build number and append it to the version at build time.
Closes #14407 
We were not setting the version of `bbb-apps-akka` and `bbb-fsesl-akka` packages, so each new build was reusing only the release portion `2.5`. This also meant that newer builds of these packages were not replacing the old ones (same version).
See #14407
=> build: Use $1 if no EPOCH in akka-apps version

bigbluebutton-html5/jsconfig.json
As the BBB uses absolute imports in some cases it makes it more difficult to track the file and open it, making the developer spend a lot of time looking for the file in the file explorer and not being able to use auto complete tools, adding the jsconfig file makes it easier for some code editors understand the root path of imports and make development more agile 
Improve DX in bbb-html5 
With jsconfig:
https://user-images.githubusercontent.com/15806883/154966334-f0dccdaa-415c-4ab1-9ac5-a402d8611846.mp4
without jsconfig:
https://user-images.githubusercontent.com/15806883/154966457-41d0d739-42a9-437b-858f-e2f324a580dc.mp4
=> chore: Add jsconfig for bigbluebutton-html5/

bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx
Removes code that makes tooltips disappear when a component updates.
Closes #14401
=> fix: remove hide-on-update behavior from tooltip component

record-and-playback/deploy.sh
While working on issue 13547, the one related to the differentiation of user's roles in the recording chat, I faced a building problem as I am going to describe it as follows:
As playback of 2.3 stays in another repository now, any changes in ruby scripts of the process or publish phase caused the removal of all folders inside `/var/bigbluebutton/playback/presentation/` including the 2.3 folder which is responsible to display the recording in the browser. As a result, playback stopped working.
So, this PR simply change the removal of all the folders inside `/var/bigbluebutton/playback/presentation/` directory and instead, it only removes the 3 directories that this script will re-deploy: `0.81`, `0.9.0` and `2.0`. The other change in the deploy file simply take care of the nginx not to …
=> refactor(recording): Refactored record-and-playback's deploy script to work properly

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Seems to have been introduced by a partial merge commit (v2.4 -> v2.5)
There were a bunch of style changes introduced by that partial commit as well; I kept those changes to avoid introducing further conflicts between v2.4-2.5...
Also: the duplicated definition was a stale one and it was overriding the fresh definition.
n/a
n/a
n/a
=> refactor(audio): remove duplicated loadBridges method definition

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
Reduces space between dropdown and button (settings and actions dropdown).
=> Adjust dropdown menu position

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/public/locales/en.json
In some cases when uploading a large presentation file, for some unknown reason a `net::ERR_CONNECTION_CLOSED` exception will be raised.
That impedes the upload progress of reaching `100`. Then, a generic error message is showed:
This PR adds a more descriptive error message for that case:
Closes #14362
=> fix(presentation): new message for presentation item status

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala
The initial idea was to show in Dashboard if the user had been Moderator at any moment.
But as @pedrobmarin explained, it could cause some confusing.
With this PR the Dashboard will always show the last role of the user.
Closes #14101
=> fix: Dashboard doesn't update user demote

bbb-libreoffice/docker/Dockerfile
Remove older log4j-1* files in Libreoffice docker container as they are picked up by security scans.
=> chore(bbb-libreoffice): Remove older log4j-1* files

bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js, bigbluebutton-html5/public/locales/en.json
- Adds tooltip to user avatar in raise hand notification
- Restores vertical padding in raise hand notification
=> Add tooltip to raise hand notification

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Prevents an issue where presentation download permission would fail to be removed.
Closes #14440
=> fix: Cannot change presentation download permission twice

bigbluebutton-html5/imports/ui/components/status-notifier/styles.scss
Adjusts the position of the raise hand notification icon in mobile devices.
=> fix: raise hand notification icon position

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
_Fixes the 'sortName' prop access. Passes it as a parameter into the function._
Closes #14452
=> fix: breakout room 'shortName'

bigbluebutton-html5/imports/ui/components/common/toast/component.jsx, bigbluebutton-html5/imports/ui/components/common/toast/styles.js
Restores missing toast styles.
=> Fix: toast background styles

build/packages-template/bbb-freeswitch-core/build.sh
Drops opus related packages which are installed at build time for `bbb-freeswitch-core` which are already present, installed via Dockerfile
Closes # None
Packages `libopusfile-dev`,  `opus-tools`,  `libopusenc-dev` and `software-properties-common` are part of Dockerfile already -- https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/blob/v2022-02-08-bbb-2.5/Dockerfile
And so is the PPA `ppa:bigbluebutton/support`
=> build: FreeSWITCH dependencies installed in Dockerfile instead

build/packages-template/bbb-config/opts-bionic.sh
Drops `stuntman-client` as a dependency for `bbb-config`
Closes #
It is no longer used on BBB 2.5+ (and happens to not be supported on Ubuntu 20.04)
=> build: drop stuntman-client dependency, obsolete

bbb-api-demo/README, bbb-lti/README.rst, bigbluebutton-config/bin/apply-lib.sh, bigbluebutton-config/bin/bbb-conf, bigbluebutton-config/cron.daily/bigbluebutton, build/deb-helper.sh, build/packages-template/bbb-lti/after-remove.sh, build/packages-template/bbb-playback-podcast/opts-trusty.sh, build/packages-template/bbb-playback-presentation/opts-trusty.sh, build/packages-template/bbb-web/before-install.sh, build/packages-template/bbb-web/build.sh, build/packages-template/bbb-web/opts-trusty.sh
Drops any references to tomcat6 or tomcat7 leftover from previous BBB versions
Closes #
On BBB 2.4 and 2.5 we only install/use tomcat8. Preparing for easier/cleaner upgrade of tomcat.
=> build and config: drop references to tomcat6 or 7

build/packages-template/bbb-demo/opts-trusty.sh, build/packages-template/bbb-playback-podcast/opts-trusty.sh, build/packages-template/bbb-playback-presentation/opts-trusty.sh, build/packages-template/bbb-record-core/after-install.sh, build/packages-template/bbb-record-core/opts-trusty.sh, build/packages-template/bbb-web/opts-trusty.sh
Drops obsolete ubuntu trusty (or xenial) files (currently on Ubuntu bionic)
Closes #
These are obsolete, we're on `bionic` now.
=> build: drop ubuntu trusty (or xenial) files

bigbluebutton-html5/private/config/settings.yml
Remove unneeded redis channel subscription from the html5 module
None
Since bbb-pads the html client Etherpad redis' channel subscription isn't
needed anymore. All communication between Etherpad and BigBlueButton goes
through bbb-pads.
=> refactor(pads): unneeded redis subscription

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
It changes the logic of altering the current document when sending a request via `InsertDocument` endpoint. It simply ignores the `current` attribute  sent in the payload (if any).
Closes #14431
As a context, it is important to comment that because of the recent decision of [refactoring the toast messages](https://github.com/bigbluebutton/bigbluebutton/issues/14493), this part was not tackled by this PR, since it would be redone soon.
=> Change in current attribute for InsertDocument endpoint

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Since `disabledFeatures` was added to `bigbluebutton.properties` with null value:
`bbb-conf --check` is showing this warning
This PR let this line commented by default in order to avoid this warning.
=> fix: warning "disabledFeatures have no value"

bigbluebutton-html5/imports/api/meetings/server/methods/clearRandomlySelectedUser.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/updateRandomViewer.js, bigbluebutton-html5/imports/ui/components/common/modal/random-user/component.jsx
- prevents client crash in random user selection modal.
- prevents a bug where the modal would not open after being closed by the presenter
Closes #14488
=> fix: Client crashing when clicking to "Select random user"

bigbluebutton-html5/package-lock.json
Adds package-lock changes after install html-to-image as dependency.
Changes missing from https://github.com/bigbluebutton/bigbluebutton/pull/14406
=> chore: package-lock changes for html-to-image lib

bigbluebutton-html5/private/config/settings.yml
Set height to 720 in HD and High camera profiles.
Closes #14476
Having only width set in HD/High profiles was causing certain devices to output webcam streams with non-standard ARs. Specifying height ups the chances that the stream's AR will be cohesive.
Will backport to v2.4 once I'm sure this doesn't bring unexpected overconstraining issues (shouldn't).
=> fix: specify height in high and hd camera profiles

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
Fixes an edge case where screen ejections weren't being requested internally on
ungraceful presenter changes (presenter ejections, disconnections, ...; anything 
that wouldn't trigger presenter unassigned events).
Partially addresses #14072 
#14072
=> fix(screenshare): request ejection when presenter automatically changes

.gitlab-ci.yml
I had used a `.` in the old one (a dot) and it's causing headaches
=> chore: re-tag BBB docker image so it does not contain dot

build/packages-template/bbb-html5/sip.nginx, build/packages-template/bbb-webrtc-sfu/webrtc-sfu.nginx
This PR reduces the timeout intervals for bbb-webrtc-sfu and FS's WebSocket proxies in nginx to more sane values (60s and 120s, respectively).
The heartbeat routine in bbb-webrtc-sfu runs every 20s. The heartbeat routine in SIP.js/FS runs every 30(+10)s. The new timeouts are those values multiplied by 3.
None.
Reducing those timeouts allow resources (WebSockets) to be cleaned up faster when their terminations are ungraceful.
Moreover: the old 6h values seem far too large and I can't recall nor find any good justification for them to be that way. If anyone can, feel free to voice their concerns in this PR.
=> refactor: reduce timeout intervals for webrtc-sfu and FS WebSocket proxies

bbb-voice-conference/config/freeswitch/conf/autoload_configs/modules.conf.xml
modifies the list of loaded modules in FreeSWITCH to support G722 codec.
8 kHz audio sucks.
same change as in #14520 but for BBB 2.5+ build system
=> build: enable G722 by default

build/packages-template/bbb-lti/build.sh, build/packages-template/bbb-lti/opts-bionic.sh
- handles the extra level of `bbb-lti` directory introduced when I extracted bbb-lti into its own directory https://github.com/bigbluebutton/bigbluebutton/pull/14489 . The method I used focused on preserving the file git history. When I tried to `git mv` the files so we don't have `bbb-lti` inside `bbb-lti` it looked like we'd lose the history (everything was 1 commit old). In fact, I ended up re-creating the repository and repeating the extraction process and this time left bbb-lti/bbb/lti intact.
- Also drops the `fpm` flags about file ownership left out from #14110 Now that this can be built again, we'll know if anything's not working correctly
- Drops a few repeated commands for copying over .nginx and .service
Closes # none
`bbb-lti` package could not be built
=> build: recover bbb-lti packaging (now from own repo)

bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/load-play.js
An util script responsible for loading+playing media elements was missing the import of a secondary util called mediaElementPlayRetry.
The latter should only be used on very rare edge cases hence why I think it went unnoticed for so long;
might be worth reviewing/removing down the road.
None
n/a
n/a
=> fix: missing import in load-play util script (webrtc)

bbb-api-demo/src/main/webapp/bbb_api_conf.jsp, bigbluebutton-config/bin/bbb-conf, build/packages-template/bbb-demo/after-remove.sh
- includes an [almost] empty file `bbb_api_conf.jsp`, a placeholder so that bbb-demo can be installed
- includes code in `bbb-conf --setip` to populate the current SALT and URL in `bbb_api_conf.jsp`
- ensure `demo/` unpacked directory is fully gone on removal of `bbb-demo`
Closes #14533
Closes #12520
Currently we can't install `bbb-demo` because we're missing `bbb_api_conf.jsp` and it is required in
` <%@ include file="bbb_api_conf.jsp"%> ` in bbb-demo
* It is now mandatory to run `bbb-conf --setip yourserver.com` after an upgrade or clean install so that bbb-demo can get its `bbb_api_conf.jsp` file updated. Note that `bbb-demo` is an optional package
=> fix: bbb-demo, ship empty bbb_api_conf.jsp, populate in --setip

bigbluebutton-html5/imports/ui/components/video-provider/service.js
User's camera cap should be disabled when set to zero but the UI control
wasn't respecting this configuration.
None
=> fix(video): respect disabled cap

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/styles.js
Adds breakout duration to sidebar.
Partially resolves #9887
=> Add breakout-room duration to sidebar

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
Refactor of parameter `groups` introduced in #13678.
As suggested in https://github.com/bigbluebutton/bigbluebutton/issues/13628#issuecomment-1060913533.
There is no need to make each user of the `roster` to be an object with only `id` property.
So this PR convert this property to an array of Strings instead of array of Objects.
Before:
```js
{ roster: [{id:123},{id:234},{id:345}] }
```
After:
```js
{ roster: [123,234,345] }
```
=> refactor: simplify groups json format

build/packages-template/bbb-etherpad/settings.json
Inside narrow panels, Etherpad's toolbar icons overlap themselves.
This PR changes the etherpad config in order to avoid this scenario.
https://user-images.githubusercontent.com/42683590/157463940-6f4ba30e-f7b7-4bdb-9e3d-832a86f4fcfa.mp4
https://user-images.githubusercontent.com/42683590/157463962-98088ce9-02c9-4fc0-87b2-6cfb323038f6.mp4
=> fix(etherpad): avoid icons overlapping

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/InMessages.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EjectUserFromBreakoutInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
When a user is removed from the main room, he is not being removed from the breakout rooms as well.
This PR fix this problem.
Closes #14194
=> fix: Users not being ejected from breakout rooms (only from main room)

build/packages-template/bbb-etherpad/build.sh
It does two things:
- adds a cleanup step before each clone, so that `build.sh` can be re-run without errors
- executes a removal of etherpad-lite's package.json ... because it did not have a matchingn package-lock.json... and based on https://github.com/ether/etherpad-lite/issues/4962#issuecomment-916642078 it seems removal of package.json helps resolve the issue.
**I am not super sure on how this is correct**. I am adding the word 'hacky' in the PR name and a `?` in the title.
Locally this removal helped. But to be fully sure I need to monitor it a bit when built and used on staging.
Closes # none open
When building `bbb-etherpad` in the step `bin/installDeps.sh` we were not able to run `npm ci`. I am not sure what exactly caused this obstacle.
+ set +e
+ bin/installDeps.sh
Installing …
=> ?build: bbb-etherpad missing deps, hacky rm package.json

build/packages-template/bbb-etherpad/build.sh
- Adding logs to see why I am missing package-lock.json in some instances of building bbb-etherpad
- commenting out the odd removal of package.json from #14583
Closes # none
Continuing with #14583 -- still encountering the issue of not being able to do the `bin/installDeps.sh` step of build.sh
=> build: bbb-etherpad add logs; comment out #14583

build/packages-template/bbb-etherpad/build.sh
Sets npm to 6.14.11 for building of `bbb-etherpad`. Worked muuuch better locally than using npm 8.5.0. I was able to run bbb-etherpad built locally with this set of scripts.
Closes # none
Continuation from #14583
=> build: bbb-etherpad set npm to 6.14.11

build/packages-template/bbb-freeswitch-core/build.sh
Use the default compiler flags for building FreeSWITCH (and not the debug version we were building for testing)
=> Use default compiler optimizations for FreeSWITCH

bbb-webrtc-sfu.placeholder.sh
Bump bbb-webrtc-sfu to [v2.7.0](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.7.0)
=> build: bump bbb-webrtc-sfu to v2.7.0

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js, bigbluebutton-html5/imports/api/audio/client/bridge/base.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/audio/client/bridge/service.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/fullaudio-broker.js
- Implements echo test in the experimental full audio bridge
* Includes a refactor to make the transfer tracking code re-usable across bridges
* Transfer is done via server-side DTMF. Similar to the default bridge, but the DTMF signal point is in the server instead of in the client
- Implements input/output device changes in the experimental full audio bridges
* Includes a refactor to make some of the input/output device code re-usable across bridges. More can be moved around in the future.
- Handles audio constraints/filter changes in the new bridge
- Handles the `forceRelayOnFirefox` and `forceRelay` flags
- Remove client RPC parameters that are fetched in the server (userId, meetingId, voiceBridge) + some unused ones (userName)
Closes …
=> feat(fullaudio): implement echo test, device change and audio filters (new bridge)

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/pads/PadCreateGroupReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/pads/PadCreateSessionReqMsgHdlr.scala, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/components/captions/service.js, bigbluebutton-html5/imports/ui/components/notes/service.js, bigbluebutton-html5/imports/ui/services/features/index.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Add new features to disableable list: `sharedNotes` and `captions`.
=> feat: Support to disable shared notes and captions via disabledFeatures

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/conf/spring/resources.xml
As suggested by @svergata https://github.com/bigbluebutton/bigbluebutton/pull/14293#issuecomment-1062698666
This PR will revert the exclusion of API Create param `learningDashboardEnabled` in order to avoid a breaking api change in minor version.
- The `learningDashboardEnabled` was not fully implemented. When the parameter is `false` it will automatically add `learningDashboard` to `disabledFeatures` instead.
- A `[DEPRECATION]` warning was added when `learningDashboardEnabled` be used as API Create param or if it is set in `bigbluebutton.properties`.
=> fix: Keep support for deprecated API param learningDashboardEnabled

build/packages-template/bbb-web/after-remove.sh
No longer deletes `/usr/share/bigbluebutton/nginx/web` on bbb-web` upgrade (the file was not replaced)
Closes #none
After `bbb-web` rebuild, we were missing `/usr/share/bigbluebutton/nginx/web` which is needed for a link to web.nginx
This is a follow up from overzealous https://github.com/bigbluebutton/bigbluebutton/pull/14600
=> build: do not remove /usr/share/bigbluebutton/nginx/web on upgrade

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
Adds `current` as an optional parameter when using the internal endpoint to upload files.
```javascript
...
formData.append('is_downloadable', false);
formData.append('current', true); // This will set the file attached below as the one to be displayed
formData.append('fileUpload', file);
...
```
This avoids the need of waiting for the upload to finish, getting the generated ID of the latest presentation, and making a `setPresentation` call with the corresponding `presId` and `podId`.
For features such as PR #14585, users expect to see the shared notes being quickly uploaded and with as little manual intervention as possible.
The `insertDocument` API call already supports `current=true`, this PR adds the equivalent option internally.
The attribute is entirely optional. Existing …
=> fix: Adds 'current' as optional parameter of the internal upload endpoint

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/fullaudio-broker.js
- Properly clean up SFU audio broker in its bridge when it's stopped
- Guarantee that the peer connection exists before trying to access SFU's audio broker local stream
None
Re-connections could occasionally fail due to old brokers being erroneously carried over to new connections.
n/a
=> fix(audio): clean up sfu broker, guarantee peer exists in getLocalStream

bbb-webrtc-sfu.placeholder.sh
Bump bbb-webrtc-sfu to [v2.6.11](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.11)
=> build: bump bbb-webrtc-sfu to v2.6.11

bbb-webrtc-sfu.placeholder.sh
Bump bbb-webrtc-sfu to [v2.7.1](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.7.1)
=> build: bump bbb-webrtc-sfu to v2.7.1

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/components/user-avatar/styles.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/styles.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Implements a loading skeleton in userlist component that appears in the initial loading of users, using [React Loading Skeleton](https://www.npmjs.com/package/react-loading-skeleton).
Initial load might take a while if user connection is slow or if many users are in the meeting, and see "Users: 0" and an empty userlist might confuse users. The loading skeleton is an indicator that content is still loading.
https://user-images.githubusercontent.com/3728706/159066713-7179a802-ef25-4a84-9960-7023ff3c88ac.mp4
=> Add loading skeleton in userlist

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/styles.scss
The viewer can't see if the shared video is ending or in the middle.
This PR adds a progress bar for the viewers, so they can follow the progress of the video.
=> Implements a progress bar on external video for viewers.

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/private/config/settings.yml
- Backports https://github.com/bigbluebutton/bigbluebutton/pull/14513 from 2.5
- fix(video): add debounce and option to exclude constraints from dynamic camera profiles
* Tries to mitigate too-rapidly-switching camera profiles causing video freezes due to encoder resets. 
* Excluding constraints might not help a lot since the thing that actually restarts the encoder is the bitrate change, but they're not really important in the context of dynamic profiles. We can't get rid of bitrate changes, though, since it's what does the actual quality constraining.
* The camera profile change debounce timer is 2.5s by default (which is the same timer used for floor changes).
- Fixed an issue with camera profile changes backfiring due to badly defined peers
- feat(video): add flag to disable quality …
=> fix(video): improvements to dynamic camera profiles

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/pads/PadCreateGroupReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetLockSettingsReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/MeetingStatus2x.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/LockSettingsParams.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-html5/imports/api/meetings/server/methods/toggleLockSettings.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/changeLockSettings.js, bigbluebutton-html5/imports/ui/components/lock-viewers/context/context.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Backend portion of #14636
Implements `lockSettingsHideViewersCursor` param in API /create.
And in `bigbluebutton.properties`:
Let `hideViewersCursor` available for html5 in `lockSettingsProps`:
=> feat: Implements param lockSettingsHideViewersCursor (Backend only)

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
When troubleshooting audio issues it is often useful to know which devices and browsers users are actually connecting with. This PR adds the browser user agent as well as BBB server and HTML5 client versions to the SIP user agent string. Refs: #7007
=> Send browser UA string in SIP UA, also add BBB server and client version

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss
Add a padding in order to avoid cropped "onFocus"
Add an overflow property in order to avoid horizontal scrollbar
Before:
After:
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14619
=> fix(waiting-users): button cropped

bigbluebutton-config/bin/apply-lib.sh, bigbluebutton-config/bin/bbb-conf, build/deb-helper.sh
Replaces all uses of the depcrecated net-tools utilities with those from
iproute2 which are available on all linux distributions release in the last
couple of years.
Closes #14623
Closes #12262
=> Replace use of net-tools utilities with those from iproute2

akka-bbb-apps/src/test/scala/org/bigbluebutton/core/AppsTestFixtures.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/services/features/index.js, bigbluebutton-html5/imports/ui/services/virtual-background/service.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- Add new feature to disableable list: `virtualBackgrounds`;
- Keep support for previous API param `virtualBackgroundsDisabled`, but log a [DEPRECATION] warning when this param is used.
=> feat: Support to disable Virtual backgrounds via disabledFeatures

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Upgrades eslint-plugin-import to latest version (2.25.4) to resolve npm audit alerts.
=> chore: upgrade eslint-plugin-import version

bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
Prevents an issue with the unread messages notification reappearing when a user is promoted/demoted.
Closes #14103
=> fix: chat notification bug on promotion/demotion

bigbluebutton-config/bin/bbb-conf, bigbluebutton-html5/deploy_to_usr_share.sh, bigbluebutton-web/run-dev.sh, bigbluebutton-web/run.sh, build/packages-template/bbb-html5/run_mongo.sh, build/packages-template/bbb-html5/systemd_start.sh, build/packages-template/bbb-html5/systemd_start_frontend.sh
Swaps `netstat` usage with `ss`, following @danimo's https://github.com/bigbluebutton/bigbluebutton/pull/14647
Closes # none
On a clean install I encountered `/usr/share/meteor/bundle/systemd_start_[frontend.sh](http://frontend.sh/): line 12: netstat: command not found`
and
`/usr/bin/bbb-conf: line 915: netstat: command not found`
Made changes suggested by @danimo so if this works, all credit goes to @danimo :)
=> refactor: swap netstat with ss

bigbluebutton-config/bin/bbb-conf
Skip commented lines when checking for empty assignment in bbb-conf
=> Update bbb-conf to skip commented lines 

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/pin-area/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/pin-area/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/view-actions/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/view-actions/styles.js
- This PR is directly linked to the third item in this issue https://github.com/bigbluebutton/bigbluebutton/issues/12954
- Provides a solution by refactoring the `UI code (video list rendering, video container rendering, BBB UI state tracking, ...)`
With this new approach proposed by this PR, the main component (video-list-item) was divided into 4 other components, where each of them has its own responsibility.
- **Video List Item:** responsible only for the video. It acts as the parent of the smaller components:
- **View Actions:** top right corner area. It has fullscreen controls and other visualization-related buttons.
- **Pin Area:** top left corner area. It has the icon to unpin the user.
- **User Actions:** bottom left corner area. It has the user dropdown and the logic involved in …
=> refactor(video-list-item): hookify and reorganize component

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
Prevents a bug with the auto-focus feature (keyboard-only navigation) by adjusting menu click event so the correct value is obtained in Firefox.
Closes #14669
=> fix: In Firefox, "Start a private chat" is always with hover style (2.5)

bigbluebutton-html5/imports/ui/components/menu/component.jsx
This is a backport of PR #14681 from 2.5 to 2.4.
_Prevents a bug with the auto-focus feature (keyboard-only navigation) by adjusting menu click event so the correct value is obtained in Firefox._
=> fix: In Firefox, "Start a private chat" is always with hover style (2.4)

bbb-voice-conference/config/freeswitch/conf/autoload_configs/switch.conf.xml, bbb-voice-conference/config/freeswitch/conf/sip_profiles/external-ipv6.xml, bbb-voice-conference/config/freeswitch/conf/sip_profiles/external.xml
Change FreeSWITCH configuration such that the core database as well as profile databases are stored fully in memory.
Closes #11887
From a FreeSWITCH [release notes](https://signalwire.com/blogs/product/signalwire-stack-release-20-19-7):
> ## New Features
> * [FS-11827](https://freeswitch.org/jira/browse/FS-11827) - Add feature allowing FreeSWITCH to store CORE DB (SQLite) fully in memory
We should use that mechanism in order to make the FreeSWITCH setup more robust. Moving core and profile databases into the memory removes the risk of db file corruption and permission issues.
=> Store FreeSWITCH databases fully in memory

bigbluebutton-html5/imports/ui/components/chat/time-window-list/styles.js
Adjusts chat area padding/margin.
Closes #7579
=> fix: adjust chat area size

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/container.jsx
Adjusts isFullscreen value in presentation menu, so it displays the correct text when presentation is full-screen.
Closes #14673
=> fix: fullscreen instead of Exit Full Screen (presentation)

bigbluebutton-web/run-dev.sh
- fix: false positive when checking if bbb-web is running, run-dev.sh
* -a flag would list everything, including UNIX sockets, and then arbitrarily grep for 8090. That would lead to false positives.
* Swap -an for -lt (only TCP sockets on LISTEN) so we can drop the extra LISTEN grep. 
* Add an extra `:` to the port grep (avoid factoring things like tcp 18090)
None
That thing is frequently tripping me up on dev env.
n/a
=> fix: false positive when checking if bbb-web is running, run-dev.sh

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
The viewer can't mute the volume. 
https://user-images.githubusercontent.com/19312495/160689998-3fdaa0f9-b9d9-4619-b009-ecd60c7be966.mp4
Now, the viewer can mute and unmute the volume with no problems.
https://user-images.githubusercontent.com/19312495/160690014-36a233eb-64f5-4d68-b06a-b43adc0e14d4.mp4
=> fix(external-video): Viewers can now mute/unmute their view of external video

build/packages-template/bbb-freeswitch-core/opts-focal.sh
Drops the dependency `net-tools` introduced in #14677
Closes #
@ffdixon made adjustments in #14677 to close #14670 but also re-introduced `net-tools` as a dependency (which was removed a few days earlier, see https://github.com/bigbluebutton/bigbluebutton/issues/14670#issuecomment-1083147298)
Related to #14670
=> build: drop net-tools from bbb-freeswitch-core

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
As expected in #8701.
This PR makes `API/create` support the following params:
- `meetingExpireIfNoUserJoinedInMinutes`
- `meetingExpireWhenLastUserLeftInMinutes`
*If set via parameter, it will override the config file.*
=> feat: Add meetingExpire params to API /create

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
Backport of #14620 for 2.4 + fix to a condition where setSwapLayout happens only after other components are mounted.
_Prevents an issue where external video / screenshare does not appear to a user that joins after video is shared._
Closes #14689
=> fix: Screenshare is not displayed to new users, if autoSwapLayout=true

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx
Prevents an issue where setSwapLayout would fail to set the initial "swapLayout" value before other components change it if `autoSwapLayout=true`. (2.5 partial port of #14705)
=> fix: setSwapLayout happens after other components change its value

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js
Prevents an issue where the clear chat feature would not work.
Clear chat feature was not working because it was trying to call a method (`addGroupChatMsg`) that needs additional parameters.
Closes #14655
=> fix: Clear chat button is not working

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx, bigbluebutton-html5/public/locales/en.json
Adds a locale for the hardcoded `Test your speaker volume` string in the AudioSettings modal.
None (I think)
n/a
n/a
=> fix(locale): add locale for audio settings speaker test label

bbb-webrtc-sfu.placeholder.sh
build: bump bbb-webrtc-sfu to [v2.6.13](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.13)
=> build: bump bbb-webrtc-sfu to v2.6.13

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
Currently, users are redirected to the logout url after they finish interacting with the feedback component (if enabled in _Settings.yml_ - `askForFeedbackOnLogout`), which skips the modal to open the Learning Dashboard.
This PR fixes that behavior. So, after the users finish interacting with the feedback component they will be "redirected" to the Learning Dashboard modal. Only after that they will be redirected to the logout url.
https://user-images.githubusercontent.com/62393923/157530039-704b089d-642b-4219-9350-e494f18d5b07.mp4
Closes #14416
=> fix: prevent redirect after feedback of user

bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/imports/ui/components/settings/container.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/data-saving/component.jsx
Hides screensharing/webcam data saving toggle switches in settings menu when the features are disabled.
Hides Data Savings tab if both `enableScreensharing` and `enableVideo` are set to **false**.
Closes #10813
=> fix: Do not display data saving toggles when features are disabled

bigbluebutton-config/bin/bbb-conf
Checks are unnecessary in 2.5 (KMS is not default).
They aren't necessary even in 2.4 since folks should be relying on externalIPv4 rather than STUN servers, but I won't touch that for the time being.
None (I think)
https://github.com/bigbluebutton/bbb-install/pull/504
=>  fix(bbb-conf): remove KMS STUN server checks

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Prevents an issue with the presentation where it fails to set slides size on initial load if the user joins shortly after meeting creation.
It happened because `getInitialPresentationSizes` was triggered only on component mount (when slides information might not be available).
=> fix: presentation does not appear if user joins shortly after meeting start

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Prevents an issue with the presentation where it fails to set slides size on initial load if the user joins shortly after meeting creation (similar to #14743).
Closes #14750
=> fix: Presentation sometimes starts minimized (2.4.6)

bigbluebutton-html5/imports/ui/components/pads/service.js
Add a throttle control to avoid multiple create session calls in a short
period of time.
Partial solution for #14757
I'll include extra controls at bbb-pads to avoid multiple sessions for an user at the same pad
=> refactor(pads): improve session creation

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Removed a single `postMessage` line which is not used.
Closes #
Looks like it re-entered via https://github.com/bigbluebutton/bigbluebutton/pull/13821 after it was removed in https://github.com/bigbluebutton/bigbluebutton/pull/13778
=> fix: Drop old postMessage leftover

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx
Prevents an issue where cameras could appear at the wrong position on meeting start if `autoSwapLayout` is set to true.
Closes #14766
=> fix: "Autoswaplayout: true" doesn't work as expected

bigbluebutton-html5/imports/ui/components/user-list/captions-list-item/styles.js
Adjusts closed captions button icon styles.
Closes #14745
=> fix: Closed caption button with style bug

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx, bigbluebutton-html5/imports/ui/components/common/modal/confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/common/modal/confirmation/styles.js, bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx
This PR remove the usage of the `dangerouslySetInnerHTML` of two components:
Modal confimation: IT was used for structure the description message by adding a few `<p>` tags, it was replaced by the breakline code (`\n`) and adding a css style to break the text every breakline.
Chat alert: It had a piece of code that was no longer used so I removed it
=> refactor: Remove unnecessary dangerouslySetInnerHTML of the client

akka-bbb-apps/.gitignore, bbb-common-message/.gitignore, bbb-common-web/.gitignore
Since sbt 1.4.0 on every bootstrap sbt will create `.bsp/sbt.json` file that is environment specific.
Reference: https://contributors.scala-lang.org/t/build-server-protocol-in-sbt/4234
=> chore: Add .bsp directory to .gitignore

bigbluebutton-html5/imports/api/connection-status/server/methods/voidConnection.js, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/logger.js, bigbluebutton-html5/imports/startup/server/prom-metrics/metrics.js, bigbluebutton-html5/imports/startup/server/prom-metrics/promAgent.js, bigbluebutton-html5/imports/startup/server/prom-metrics/winstonPromTransport.js, bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/imports/ui/components/connection-status/service.js, bigbluebutton-html5/private/config/settings.yml
- Added bbb-html5 prometheus metrics:
```
```
- New config in settings.yml:
`settings.private.prometheus.collectRedisMetrics, disabled by default`
- Fix stream-cursor event to not include the meeting-id in the event name.
Adds some new relevant metrics to help monitoring meteor.
=> refactor(prom-html5) More prometheus metrics

bigbluebutton-config/bin/bbb-conf
Update securitySalt (shared secret) in `/etc/bigbluebutton/bbb-web.properties` instead of changing the original `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`.
=> Update securitySalt (shared secret) in bbb-web.properties

bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
Makes resizing possible in media part of sidebar in "focus on" layouts.
https://user-images.githubusercontent.com/3728706/162790845-b012b09e-77a2-4e2d-8d0b-fddcdad525db.mp4
Closes #14762
=> Enable sidebar resize in media area of 'focus on' layouts

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
Adjusts video list icons position in RTL.
Closes #14790
=> fix: Incorrect position of the microphone icon in the webcam box in RTL - BBB v2.4.5

bigbluebutton-config/bin/bbb-conf
It changes the "rewrite" `>` to "append" `>>` to bbb-web.properties on --setip
Closes #13892
We should support setting of IP (hostname) and not losing all other settings
=> fix(conf): setip should not wipe out existing properties

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
It fixes the bug of crashing the `presentation-uploader` component when a presentation is sent with `filename` having german umlauts.
The fix is a refactor of the `temporaryPresId` format to not rely on UTF-8 encoding when sending the multipart/form-data content-type in `futch` method. Therefore it won't be wrongly decoded in the back-end and end up not being validated in the front-end.
Closes #14749
=> fix(presentation) - Refactored `temporaryPresId` format to accept german umlauts

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/app/styles.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.js, bigbluebutton-html5/imports/ui/components/connection-status/icon/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/styles.js, bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Add a new package for [dark mode](https://github.com/darkreader/darkreader).
Add a new toggle button to enable/disable dark theme in settings modal.
Dark theme can be disable via settings.yml
https://user-images.githubusercontent.com/42683590/162489084-3cda38eb-7b21-45b2-9aa9-9a0d3b73f194.mp4
- Closes https://github.com/bigbluebutton/bigbluebutton/issues/11218
=> feat(theme): add dark mode

bigbluebutton-web/grails-app/conf/application.yml
Looks like the path for `session.cookie` has changed and we have to tweak how we set property `secure`
Credit: @pedrobmarin 
Closes #none
Local testing worked fine
=> fix: Adjust property path for grails session.cookie.secure

bigbluebutton-html5/private/config/settings.yml
Enables [drag & drop file poll feature](https://github.com/bigbluebutton/bigbluebutton/pull/11559) by default.
=> chore: Enable drag and drop polls by default

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx
_Updates previous open dropdown (if open) on user list reordering. This prevents users from clicking on user actions with wrong data._
Before reordering:
After reordering:
Closes #14659
=> fix(menu): update previous open dropdown on user list reordering

bigbluebutton-html5/package-lock.json
Recovers bbb-html5 building (was not completing due to missing deps in package-lock.json)
Closes #none
We missed to commit package-lock.json when adding darkreader npm dependency in https://github.com/bigbluebutton/bigbluebutton/pull/14783/files#diff-74e8d1f64f49dca98b0912dc60601454c8c96873af2f93e83055de948003bf9eR42
=> fix: add missing darkreader in package-lock.json

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
Prevents a "blue screen" crash in userlist, that could happen when users are still loading (and `user` prop is undefined).
=> fix: undefined user prop crash in userlist

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/styles.js
Removes undesirable border-radius from multi-user whiteboard button.
=> fix: whiteboard toolbar border-radius

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
Adds error handling to microphone join.
Before:
After:
Closes #6948
=> fix(microphone): modal not showing errors

bbb-webrtc-sfu.placeholder.sh
build: bump bbb-webrtc-sfu to [v2.8.0-alpha.4](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.0-alpha.4)
=> build: bump bbb-webrtc-sfu to v2.8.0-alpha.4

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js
The experimental audio bridge didn't make a distinction between the configured media server adapters for microphone and listen only, always defaulting to the one used in microphones. This PR fixes that behavior. 
It also includes a minor linter warning fix and removes an unnecessary (and undefined) `this.voiceBridge` reference in the callerId assembly.
None
n/a
n/a
=> fix(audio): use correct media server in listen only via fullaudio bridge

bigbluebutton-html5/private/config/settings.yml
mediasoup is the default media server in v2.5, so we don't need ICE candidates 
to be signaled to bbb-webrtc-sfu (ICE-lite, ...). 
n/a
Disabling it saves resources, both in the client and server.
The `signalCandidates` config should only be enabled if someone wishes to use
Kurento as the media server for some reason. I'll add that to the docs later.
=> chore: disable candidate signaling by default

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/fullaudio-broker.js
- [refactor(audio): address linter warnings in fullaudio-broker.js](https://github.com/bigbluebutton/bigbluebutton/pull/14865/commits/2eaf96ae9530bf0db919ed52c75cbd737fb303d5)
- [refactor(audio): generic use of sfu audio broker to cover mic and listen only](https://github.com/bigbluebutton/bigbluebutton/pull/14865/commits/1e80d050b7a1348c46fb188b9c82acda7e2635fc)
* Renames fullaudio-broker.js to audio-broker.js
* Transform all logCode prefixes to `sfu_audio`
* Add `role` to all log extraInfos
* Review leftover, out-of-place references to keywords `listen`, `\clistenonly`, `fullaudio`
- [fix(audio): prevent uncaught rejections in the experimental audio bridge](https://github.com/bigbluebutton/bigbluebutton/pull/14865/commits/6fd6a52d47e372edc154aba1013624066e9d98bd)
* #14639
Partially …
=> fix(audio): prevent uncaught rejections in the experimental audio bridge startup; [+]

bigbluebutton-html5/imports/ui/components/button/styles.scss
Adjusts audio button icon position in RTL languages.
Closes #14864
=> fix: Audio device selector icon wrong position in RTL layout

bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/customparameters/customparameters.js, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/virtualizedlist/virtualize.js
This PR introduces some minor fixes for 2.4 Playwright tests in the following areas:
- breakout rooms (updated presentation-related selector)
- user list (fix for the following scenario: when there's one user in the meeting, there's no user list element selectable by `div[data-test="userListItem"]`, so that means `userListItemCurrent` needs to be used)
- minor cleanup for the selector of users in the user list (`elements.js)
- custom parameters (change the order of switching between slides to make sure slides navigation buttons are enabled)
- notifications (presentation upload notification test seems to be unstable due to timing issue, so it is moved to `fixme` category).
=> test: fixes for 2.4 Playwright tests

bbb-webrtc-sfu.placeholder.sh
Bump bbb-webrtc-sfu to v2.8.0.
Changelog in https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.0.
n/a
n/a
n/a
=> build: bump bbb-webrtc-sfu to v2.8.0

build/packages-template/bbb-config/build.sh, build/packages-template/bbb-html5/build.sh, build/packages-template/bbb-html5/opts-focal.sh, build/packages-template/bbb-playback-podcast/build.sh, build/packages-template/bbb-playback-presentation/build.sh, build/packages-template/bbb-playback-presentation/opts-focal.sh, build/packages-template/bbb-record-core/build.sh, build/packages-template/bbb-record-core/opts-focal.sh, build/packages-template/bbb-webhooks/build.sh, build/packages-template/bbb-webhooks/opts-focal.sh, build/packages-template/bbb-webrtc-sfu/build.sh, build/packages-template/bbb-webrtc-sfu/opts-focal.sh
yq package is now provided in the [BigBlueButton support PPA](https://launchpad.net/~bigbluebutton/+archive/ubuntu/support/+packages) for BBB 2.5 on focal, so we can depend on the package now. Ensure the dependency is specific to avoid an incompatible yq version 4 from being installed.
The dependency can't be specified in the `opts-${dist}.sh` files because it contains some characters that would case escaping issues in the bash variables. This could potentially be fixed by changing the variables to be bash arrays instead of strings.
=> packaging: Add dependencies on yq 3

bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx
Avoids closing all active toasts.
Closes #14754
=> fix: check whether there's a toast before dismissing

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Removing `html5/useragent` since it will not be referenced in the documentation anymore.
https://github.com/bigbluebutton/bigbluebutton.github.io/commit/5c5b2ea21ee86a0c3a66ff9541d00160075d55a9
=> refactor: Remove the endpoint html5/useragent

bigbluebutton-html5/imports/ui/components/app/component.jsx
Prevents an issue where the minimize button would not appear if `oldMinimizeButton = true` and `autoSwapLayout: true`
=> fix: minimize button does not appear with autoSwapLayout and oldMinimizeButton

bbb-webrtc-sfu.placeholder.sh
build: bump bbb-webrtc-sfu to [v2.8.1](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.1)
n/a
n/a
n/a
=> build: bump bbb-webrtc-sfu to v2.8.1

bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml, bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
Adjust jitterbuffer settings based on feedback from SignalWire (the folks behind FreeSWITCH).
We are always looking for ways to improve the audio in BigBlueButton.  We reached out to SignalWire, the developers of FreeSWITCH, and asked them to look over the default audio settings.  They suggested this change to improve the audio.
See also 
https://groups.google.com/g/bigbluebutton-setup/c/5F2z24avZvk/m/vBeCrq_LAAAJ
=> Adjust jitterbuffer settings in FreeSWITCH to improve audio

bigbluebutton-config/bin/bbb-conf
Propagate default value for shared secret to `/etc/bigbluebutton/bbb-web.properites`.  This ensures subsequent scripts can find the value in this file.
=> Propagate default value for shared secret to bbb-web.properites

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/styles.scss, bigbluebutton-html5/imports/ui/components/external-video-player/volume-slider/styles.scss
1 - The viewer can't see the progress bar on their phones.
2 - Now, the viewer can see the progress bar when hovering the video area.
=> Implements a progress-bar on mobile inside the external video for the viewers.

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js
The initial selected output device in AudioSettings could be the wrong one if
the user's session had an output device ID already stored, but is joining on a
new session. That would cause the remote-media tag not to be updated with the
correct output device ID when it should (the service.js change)
The issue is tackled by guaranteeing the output device ID is set on all ends
when AudioSettings/AudioModal mounts.
n/a
Related to https://github.com/bigbluebutton/bigbluebutton/pull/14736
Related to https://github.com/bigbluebutton/bigbluebutton/pull/14906
n/a
=> fix(audio): guarantee consistency of selected output devices in AudioSettings

bbb-learning-dashboard/.eslintrc.js
Temporarily disabling the `max-len` eslint rule as the package could not be created...
The previous attempt at fixing the actual lint issues resulted in a bug #14917 , so this is a bit deeper than it looks 
```
+ npm run build
> learning-analytics-dashboard@0.1.0 build
> react-scripts build
Creating an optimized production build...
warn - The RTL features in Tailwind CSS are currently in preview.
warn - Preview features are not covered by semver, and may be improved in breaking ways at any time.
Failed to compile.
src/App.js
Line 90:1:  This line has a length of 121. Maximum allowed is 100  max-len
Line 97:1:  This line has a length of 149. Maximum allowed is 100  max-len
src/components/Card.jsx
Line 37:1:  This line has a length of 108. Maximum allowed is 100  max-len …
```
=> build: temp disable max-len eslint to avoid error

record-and-playback/core/lib/recordandplayback/edl/video.rb
In some cases with incomplete/partially corrupt files, the input video file can be shorter than the displayed time. If there is a badly timed cut, this can result in a seek being generated to a point where ffmpeg is unable to start at.
Add a detection for this situation, and replace with a blank video.
Fixes errors that look like this:
```
[Parsed_movie_13 @ 0x5569fb8fe4c0] /srv/bn-rs/work/recording/raw/XXX/deskshare/YYY.webm: could not seek to position 2477000
[AVFilterGraph @ 0x5569fb892a00] Error initializing filter 'movie' with args '/var/bigbluebutton/recording/raw/XXX/deskshare/YYY.webm:sp=2.477'
```
=> record-and-playback: Don't seek past end of video input

record-and-playback/core/lib/recordandplayback/edl/video.rb
In some cases with incomplete/partially corrupt files, the input video file can be shorter than the displayed time. If there is a badly timed cut, this can result in a seek being generated to a point where ffmpeg is unable to start at.
Add a detection for this situation, and replace with a blank video.
Fixes errors that look like this:
```
[Parsed_movie_13 @ 0x5569fb8fe4c0] /srv/bn-rs/work/recording/raw/XXX/deskshare/YYY.webm: could not seek to position 2477000
[AVFilterGraph @ 0x5569fb892a00] Error initializing filter 'movie' with args '/var/bigbluebutton/recording/raw/XXX/deskshare/YYY.webm:sp=2.477'
```
This is a backport of #14928 to BBB 2.4
=> record-and-playback: Don't seek past end of video input (BBB 2.4)

bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
Prevents blue screen if User is undefined.
=> fix: check user in lock-viewers container

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/container.jsx, bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx, bigbluebutton-html5/private/config/settings.yml
Modifies `remainingTimeAlertThreshold` structure, so it receives an array (it is also renamed to `remainingTimeAlertThresholdArray`). 
An alert is displayed in the breakout rooms when breakout remaining time reaches any of the informed values (default: 1 and 5 minutes).
Closes #14909
=> Breakout rooms: have multiple "remaining time" notifications

bigbluebutton-html5/imports/api/audio/client/bridge/base.js
- `this.user.callerIdName` doesn't exist (so the log didn't really work, threw uncaught exception)
- `error` was logged as in its raw form (wrong)
- Add more info to those logs (bridge name, deviceId, isLive)
None
n/a
n/a
=> fix(audio): incorrect change output device error log

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-settings/styles.js, bigbluebutton-html5/imports/ui/components/audio/device-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/device-selector/styles.js
- [refactor(audio): style adjustments to AudioSettings device selectors](https://github.com/bigbluebutton/bigbluebutton/pull/14937/commits/538a9447aa421f39631e5fde34963da12c96ec46)
* Similar to what video-preview does: dropdown icon indicator, focus/hover handling, ...
n/a
n/a
Current:
https://user-images.githubusercontent.com/4529051/166482711-5b8ccad8-78da-4bf8-9642-62bafbf215ef.mp4
This PR:
https://user-images.githubusercontent.com/4529051/166483475-ed1ae366-35ee-4c02-ad85-e1ae75b255db.mp4
=> refactor(audio): style adjustments to AudioSettings device selectors

bigbluebutton-html5/imports/ui/components/common/switch/component.jsx, bigbluebutton-html5/imports/ui/components/common/switch/styles.js
Before this PR, the toggle button animation wasn't working.
https://user-images.githubusercontent.com/19312495/166699537-2bd5c29f-505e-4b4c-8774-5cccd6f517c5.mp4
Now, the animation is working as it should be.
Closes #14922
=> Fix enabling button inside lock-viewers RTL.

bigbluebutton-html5/imports/ui/components/nav-bar/styles.js
Before this PR the room name font wasn't working as expected, because the Cyrillic alphabet hasn't some font-weights on Source Sans Pro font. In this case, the font-weight had a value of 200.
Now, I changed the font-weight to 400, to show the correct font with the Cyrillic alphabet.
Closes #9190
=> Updates font-weight for the Cyrillic alphabet work properly.

bigbluebutton-html5/imports/ui/components/cursor/service.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Clears temporary annotation data when a user loses access to multi-user whiteboard.
Closes #14948
=> [2.4] fix: clear fake annotations on multi-user whiteboard off

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/private/config/settings.yml
FreeSWITCH has mDNS resolution capabilities as of 1.10.7. Having the filtering
configurable in the client allows us to field trial whether we should keep that
on or off. The default is still to filter them out because FreeSWITCH does not
resolve mDNS candidates by default (ice_resolve_candidate in switch.conf.xml).
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14908
https://groups.google.com/g/bigbluebutton-dev/c/1iSkpihoQwEr
The added bonus is that allowing mDNS candidates + resolution might reduce 
1004's.
Documentation on how to enable mDNS resolution on FS is probably desirable 
once 2.6 docs are in place.
=> feat(audio): add sipjsAllowMdns option to control mDNS filtering in SIP.js

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- [fix(screenshare): remove broken presenter screen reconnect](https://github.com/bigbluebutton/bigbluebutton/commit/1838dc8d91c94f233dea0eabf612aff55a31951f)
* Outbound/presenter screen sharing reconnect was broken from [inception](https://github.com/bigbluebutton/bigbluebutton/pull/11622), so it's being removed until properly re-implemented (_to be tracked separately_).
* This also fixes an issue where presenter disconnections would be silent for the end user - now an error toast is shown and the error properly logged.
- [fix(screenshare): make viewers reconnect immediately mid-call](https://github.com/bigbluebutton/bigbluebutton/commit/ee97000db995afa3b9e35d325d3991fcb8e68a28)
* If a viewer session failed mid-call, it was being scheduled for a reconnect via the min-max connection …
=> fix(screenshare): remove broken presenter screen reconnect, faster viewer reconnections

bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
Fixes an issue that when the user joins with a custom avatar, the talking
indicator div ends up covering the avatar image.
Before
After
=> fix(user-avatar): avatar image covered

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js
Screen streams were only deemed unhealthy when the transport's ICE state
transitioned to failed. That was as good as nothing because the stream would
stay frozen with no visual UI feedback until it reconnected. Bad UX.
This commit mitigates that issue via two changes:
- A stream is now deemed *potentially* unhealthy if the transport's
state becomes disconnected
- If a stream is deemed potentially unhealthy, a probe is started to 
check whether there is media/packet flow (every 500ms).
If there's no packet flow, the stream is flagged as unhealthy and
UI feedback is rendered.
There also changes to make the "unhealthy" UI clearer: a grayscale is applied 
along with a clearer background. I believe that still can be improved further.
It's still not as good as it could be - relying on …
=> fix(screenshare): check packet flow to detect unhealthy streams earlier

build/packages-template/bbb-fsesl-akka/build.sh
Switches the building of akka-fsesl dependencies `bbb-common-message` and `bbb-fsesl-client` to build in sequence, not in parallel.
Closes #
In GitHub Actions we sometimes see the action hit an error
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.bigbluebutton:bbb-fsesl-client:0.0.1652198455-SNAPSHOT
```
I am not 100% sure if this is the cause, but given the small size of the two dependencies, I think it's not an issue do build them in sequence.
=> build(fsesl-akka): build deps in sequence to allow for ci use

bigbluebutton-config/bin/bbb-conf
- [refactor(bbb-conf): review --check helpers and var names related to bbb-webrtc-sfu](https://github.com/bigbluebutton/bigbluebutton/commit/8a156718e1482b5cadd617d4025b06538e15cb4c)
* Naming most of those Kurento|KURENTO|kurento-<something> is not really accurate
- [chore(bbb-conf): list mediasoup IPs in --check](https://github.com/bigbluebutton/bigbluebutton/commit/22272c02f854e7ee9a8d79c76e09f5a1d5b4707e)
Closes https://github.com/bigbluebutton/bigbluebutton/issues/13654
n/a
n/a
=> chore(bbb-conf): list mediasoup IPs in --check, review Kurento keyword usage

bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/grails-app/services/org/bigbluebutton/web/services/PresentationService.groovy
It changes the flow to preupload some documents: now with the parameter `preUploadedPresentationOverrideDefault=false`, it is possible to have the documents preuploaded along with the `default.pdf` too. 
Closes #14828
=> Upload presentations and still have default.pdf

build/packages-template/bbb-config/after-install.sh
Handle a missed case on setting BBB's full version to be displayed within HTML5 client's About modal.
Closes #14843
Follow up from https://github.com/bigbluebutton/bigbluebutton/pull/14393
The above PR does the job when bbb-html5 is updated on its own (within a release). But when there's an upgrade of BBB, for example from beta.2 to beta.3, bbb-html5 is upgraded first, it pulls the release string before bbb-config's upgrade sets it to beta.3.
This PR duplicates the set version code, so that this additional case is also handled.
bbb-html5's upgrade will set the (old) beta.2 in settings.yml
then
bbb-config's upgrade will set the (new) beta.3 in settings.yml
=> build: set html5 client version on bbb-config update

bbb-webrtc-sfu.placeholder.sh
- build: bump bbb-webrtc-sfu to [v2.9.0-alpha.0](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.9.0-alpha.0)
=> build: bump bbb-webrtc-sfu to v2.9.0-alpha.0

bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_sfu.xml
Use the presence_data field to annotate channels with a filterable
identifier that allows us to differentiate SIP.js channels from SFU
ones.
None
Motivation: allow metrics exporters/instrumentations/etc to
generate comparison metrics (eg.: mediaStats, usage) between the default
bridge and the experimental one without having to do multiple or overly
verbose json_api or mod_command/fs_cli calls to filter channels out.
n/a
=> feat: add filterable identifier to FS channels originated from SFU

bigbluebutton-html5/imports/ui/components/notes/converter-button/service.js
Requesting a token for upload now requires a temporary presentation id (#14537), a change which was not yet reflected in the shared notes export. As a result, the "Move shared notes to whiteboard" button stopped functioning.
Additionally, if throughout a meeting an instructor chooses to repeatedly use this feature, the resulting file will now be appended with the corresponding version number instead of being the same every time:
Make it easier for instructors to find the latest exported shared notes file.
Automatic upload of the shared notes stopped functioning.
=> fix(Shared notes): missing temporaryPresentationId parameter in upload

bigbluebutton-config/bin/bbb-conf
Cherry-pick from drafted #14616 (@danimo):
- [chore: remove obsolete gstream upgrade routine](https://github.com/bigbluebutton/bigbluebutton/commit/08ca953ba8eded14119b93646d1a678bba70ab37)
[..]
We don't need that code anymore. Cherry-picking from the aforementioned PR because 08ca953 is important on its own.
n/a
=> chore: remove obsolete gstream upgrade routine (cherry-picked from #14616)

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
Before this PR, if the user typed a smiley face it would stay the same way.
Now, if the user types a smiley face, it will convert to an emoji.
To disable this functionality, set autoConvertEmoji to false inside the settings file.
=> feat(chat): Auto convert text to emoji

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateDefaultPublicGroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GetGroupChatsReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SyncGetGroupChatsInfoMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GroupChats.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/models/GroupsChatTests.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala, bigbluebutton-html5/imports/api/group-chat/server/methods/createGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/addGroupChat.js
This is a port of PR #14723 from 2.4 to 2.5.
_Removes unused group chat property "name" from bigbluebutton-html5 and akka-bbb-apps/bbb-common-message._
=> Remove group chat unused info: name (2.5)

bigbluebutton-html5/imports/ui/components/pads/service.js, build/packages-template/bbb-etherpad/build.sh, build/packages-template/bbb-etherpad/notes.nginx
Fix shared notes and closed captions to work in a cluster proxy setup
None
I use a cluster proxy setup as described in https://docs.bigbluebutton.org/admin/clusterproxy.html 
Etherpad did not work with BBB 2.5 in this configuration.
Etherpad uses the sessionID cookie for authorization. In cluster setups the
host part of the URI which serves the html5 frontend is different from
the hostname part of the URI which serves etherpad. Therefore the
bbb-html5 client can't set a cookie for etherpad which contains the
etherpad sessionID.
This patch uses the `ep_auth_session` etherpad plugin which takes the
`sessionID` as query parameter, sets the cookie in the browser and
redirects the iframe to the pad URI.
I tested shared notes, shared notes in a breakout session and closed captions. 
Is there …
=> Fix etherpad session authentication to work in cluster setups

bigbluebutton-html5/imports/ui/components/components-data/users-context/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx
Removes debounce (added in #14445) and adds throttle to the userlist updates. 
It prevents an issue where the userlist update could be delayed forever if users keep joining/leaving.
**Before:** userlist is only updated if no user joined/left in the last second.
**After:** userlist is updated when a user joins/leaves unless there was an update within the last second.
=> fix: userlist throttle instead of debounce

bigbluebutton-html5/deploy_to_usr_share.sh
After running `bigbluebutton-html/deploy_to_usr_share.sh` in 2.4 branch my server was broken.
Investigating a while, I've noticed that the script was getting aborted because the wrong path of `mongo-ramdisk.conf`.
This PR fixes this problem.
=> fix: fixes deployment of modified bigbluebutton-html5 code 

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateDefaultPublicGroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GetGroupChatsReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SyncGetGroupChatsInfoMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GroupChats.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/models/GroupsChatTests.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala, bigbluebutton-html5/imports/api/group-chat/server/methods/createGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/addGroupChat.js
Removes unused group chat property "name" from bigbluebutton-html5 and akka-bbb-apps/bbb-common-message.
=> refactor: Remove group chat unused info: name (2.4)

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/modifiers/updateUserConnectionId.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js, bigbluebutton-html5/public/locales/en.json
Displays an error message (in the old tab) when a user opens a new tab with the same sessionToken.
=> fix: prevent user join from multiple tabs with same sessionToken

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
Adds more spacing around menu items in order to achieve a result that is more similar to what we had before #15048, but without white borders around the menu items.
Suggested by @ffdixon in https://github.com/bigbluebutton/bigbluebutton/pull/15048#issuecomment-1134729749
=> style: increase dropdown menu padding

bigbluebutton-html5/imports/ui/components/pads/content/styles.js
Before this PR there wasn't any border inside shared notes for the viewers when they were locked.
Now, there is a border on the bottom and another one on the top
.
Closes #15000
=> Adding border inside shared notes for viewers

bbb-webrtc-sfu.placeholder.sh
- build: bump bbb-webrtc-sfu to [v2.8.2](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.2)
**Full Changelog**: https://github.com/bigbluebutton/bbb-webrtc-sfu/compare/v2.8.1...v2.8.2
- [fix(video): memory leak due to orphaned event handlers](https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/dc34e6083cc8692a8c362c41cf8a12e2f4adc769)
* Addressed a significant memory leak in one of the subprocesses - `VideoProcess.js`
- [fix(mediasoup): fix worker replacement routine](https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/30b10f8d235bed0efe94967cbc78381da9bf6f76)
* Guarantee the bare minimum is done in case a mediasoup-worker crashes:
- Increment the Prometheus crash counter
- Remove the crashed worker reference
- Replace the crashed worker (in the correct worker …
=> build: bump bbb-webrtc-sfu to v2.8.2

bigbluebutton-html5/imports/ui/components/webcam/component.jsx
Prevents camera dock from changing position (custom layout) when no dragging operation is fired. That prevents it from changing when the user clicks on both the camera dock and a drop area at the same time. The idea of that PR is to allow position change only if the user performs at least one dragging operation.
Closes #15036
=> fix(camera): prevent dock position change on click

bigbluebutton-html5/imports/ui/components/chat/styles.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.js
Before this PR the external links hadn't any styles, like hover, focus, or pressed.
So, I changed the styles according to this png above.
And Now, the external links has those styles, hover, focus, pressed, focus/hover, and focus/pressed. 
Closes #7716
=> style: Adding revised styles for our external links

bigbluebutton-html5/imports/ui/components/common/button/styles.js
Fixes a small bug introduced in https://github.com/bigbluebutton/bigbluebutton/pull/15044/commits/2a09629698136f725cbbd95bddfff145b53dee8b that messes up focus shadow of a few buttons.
**Before**
_Normal / Focus_
**After**
_Normal / Focus_
None
n/a
n/a
=> fix: ghost button focus shadow

bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js
Use the built-in getLocalStream from the peer wrapper instead (which
relies on getSenders - the proper, spec-compliant way).
None
Two different issues are addressed:
- RTCPeerConnection.getLocalStreams is a pre-1.0 WebRTC spec which is
deprecated and not recommended.
- Fixed an issue where a switch from full audio to listen only could
cause the latter to be rejected with an error 1004 in rare scenarios. Hard to
reproduce, but identified via log processing that pointed down to 
getLocalStreams usage on Safari.
n/a
=> fix(audio): remove deprecated getLocalStreams usage

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/BroadcastPushLayoutMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/LayoutApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/LayoutMsgs.scala, bigbluebutton-html5/imports/api/meetings/server/eventHandlers.js, bigbluebutton-html5/imports/api/meetings/server/handlers/broadcastPushLayout.js, bigbluebutton-html5/imports/api/meetings/server/methods.js, bigbluebutton-html5/imports/api/meetings/server/methods/setPushLayout.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/setPushLayout.js, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/container.jsx, bigbluebutton-html5/imports/ui/components/layout/service.js
* Allows moderator to set the pushLayout flag for the meeting (it will still follow the presenter layout, but moderator can set it on/off)
* Correctly pushes the layout once pushLayout flag is set from flase -> true
* Allow the pushing of layoutType again
=> fix(layout): Fix propagation bugs and allow moderators to set the pushLayout flag

record-and-playback/core/scripts/rap-enqueue.rb
In BBB 2.5, we switched the recording system to use bundled gems
included privately in the recording package, rather than installed
system-wide. The rap-enqueue.rb script needs to be updated to load the
bundler gems.
According to bundler devs, setting the BUNDLE_GEMFILE environement
variable is the supported way to tell bundler where to find it
(otherwise bundler will search starting at the current working directory,
which in the case of rap-enqueue.rb is probably nowhere near the
Gemfile).
Use a relative path from the directory where the script is located so it
can be run both when installed and from a development environment.
Switch the script interpreter to use /usr/bin/env to load ruby from the
path. Doesn't make a difference in the installed package, but it makes
testing on …
=> Fix rap-enqueue.rb to load gems with bundler

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala
Fixes the error of not removing a user from a breakout room with a previously set userID when being removed from the main meeting. 
To reproduce the error (using a `v2.4.x-release` server):
- Create a meeting;
- Enter with a moderator;
- Then enter as a viewer, setting userID param,either via API Mate, or via the `join` request with a `userID=` URL parameter;
- Create a breakout Room and assign the viewer to it;
- Then, after the user has entered the room, remove they from the main meeting;
- Note that the user continues in the breakout.
When using this branch, the expected behavior should be followed (the user is kicked out from both the breakout room and the main meeting).
=> Fixed user not removed from the breakout when userID set

bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.js
Adjusts audio modal buttons position:
- reduces spacing between title and buttons
- increases spacing between content and modal bottom
- increases spacing between button icon and buttons label
=> Audio modal polishing

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala
Fixes user removal from breakout room when `userID` is previously set.
[@gustavotrott request in here](https://github.com/bigbluebutton/bigbluebutton/pull/15135#issuecomment-1149354113)
=> fix user removal in breakout

bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx
Prevents an issue where the userlist is not updated for viewers when a user leaves (only happens if a user leaves by closing the browser tab).
Closes #15069
=> fix: user not removed from users context on leave

bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx
Reverts bigbluebutton/bigbluebutton#15155 (it was causing https://github.com/bigbluebutton/bigbluebutton/issues/15162)
=> Revert "fix: user not removed from users context on leave"

bigbluebutton-html5/imports/ui/components/chat/service.js
Before this PR when the moderator cleared the public chat and then tried to save or copy instead of getting this specific message "The public chat history was cleared by a moderator" it was returning the message "PUBLIC_CHAT_CLEAR".
Now, when the moderator does the same thing as described above the save and copy functionality is returning the specific message "The public chat history was cleared by a moderator" as it should be.
=> fix: missing "chat has been cleared" message at chat export

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/public/locales/en.json
Changes the text of snapshot button in order to better describe the feature (the snapshot file is for the current slide only).
=> Rename snapshot button label

bigbluebutton-html5/imports/api/polls/server/publishers.js, bigbluebutton-html5/imports/ui/components/poll/container.jsx
Prevents a bug where the current poll would not be published if the meeting presenter changes.
=> fix: re-subscribe to current poll when presenter changes

bigbluebutton-html5/package-lock.json
Adds a missing block from package-lock.json
Closes # none
we could not build bbb-html5 package, 
```
METEOR@2.7.1
+ meteor npm ci --production
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Missing: emoji-mart@^3.0.1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /root/.npm/_logs/2022-06-14T20_29_00_818Z-debug.log …
```
=> fix: add missing emoji-mart in html5 package-lock.json

bigbluebutton-html5/imports/ui/components/pads/content/styles.js, bigbluebutton-html5/imports/ui/components/pads/styles.js
Before this  PR the etherpad iframe was cutting off the last line at the end of the document.
Now, the etherpad isn't cutting the text and it works correctly.
Closes #12286
=> fix: Etherpad cutting off text

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/styles.js
Unify audio buttons in actions bar according to this designs: https://github.com/bigbluebutton/bigbluebutton/issues/12914#issuecomment-903386603
Move device selection dropdown to microphone button
Remove the audio exit button when device !== mobile
Move option 'leave audio' to an option within the dropdown
https://user-images.githubusercontent.com/42683590/172710519-f376d332-512f-4cee-b6d9-782e696d7772.mp4
Closes https://github.com/bigbluebutton/bigbluebutton/issues/12914
=> feat(audio): unify audio buttons

record-and-playback/core/scripts/archive/archive.rb
It  ensures that the etherpad endpoint is available, if so, it proceeds with the request and the logic, if that's not the case, it doesn't request the endpoint, and there is no Error log.
Closes #15160
=> (fix) - Fixed error logs in recordings about etherpad

bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx, bigbluebutton-html5/imports/ui/components/common/button/styles.js, bigbluebutton-html5/imports/ui/components/common/modal/fullscreen/styles.js, bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/styles.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Fixes the zoom value displayed on the presentation toolbar being reset when the presentation component is unmounted / mounted.
=> Display Correct Zoom Value on Presentation Restore

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Disables the ability to drop files directly onto the whiteboard.
We currently don't transmit assets to `akka`
=> fix: Disable File Drop on Whiteboard

bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx, bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx
Fixes an issue where the userlist is not updated for viewers when a user leaves by closing the browser tab.
Closes #15069
=> fix: users counter inconsistent

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js
It adjusts the presentation menu to use the common menu component instead of hard-coding a new menu.
=> refactor: Adding bbbmenu component to presentation menu

bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/user/lockViewers.js
This fixes a test that was failing against a stock 2.4.7 BBB server.
There was a race condition in `lockShareWebcam` where the test locked attendees sharing webcams, there was an attendee webcam already shared, and the test expected it to have vanished without waiting for it to vanish.
I added two new helper functions, `hasNElements` and `wasNthElementRemoved`, and used them to test for the appearance and disappearance of the second webcam.  I also made the test check for the webcams on all user pages, including the user that shared the webcame, which it didn't do before.
Now github is telling me that it can't automatically merge this PR.  I'm guessing that's because I created it from v2.4.x-release, which seemed to me the most sensible thing to do, since I'm testing against the 2.4.7 …
=> test: lockShareWebcam

bigbluebutton-tests/playwright/webcam/util.js
Check that webcam videos are changing by computing a hash of their entire contents, rather than checking a single pixel, which was producing false failures.
I cut-and-pasted a public domain hash function, slightly modified to work on arrays instead of hashes.  It's only a dozen lines of code, and I don't know a better way to get some kind of library module loaded into the test browser, as opposed to the test harness.
Default settings pause 1.2 seconds between each check, to give the video time to change, so even if the hash function slows things down slightly, it's unnoticeable.
=> test: webcamContentCheck

build/packages-template/bbb-etherpad/etherpad.service, build/packages-template/bbb-html5/bbb-html5.service, build/packages-template/bbb-pads/bbb-pads.service, build/packages-template/bbb-web/bbb-web.service, build/packages-template/bbb-webhooks/bbb-webhooks.service, build/packages-template/bbb-webrtc-sfu/bbb-webrtc-sfu.service, record-and-playback/core/systemd/bbb-rap-resque-worker.service, record-and-playback/core/systemd/bbb-rap-starter.service
* fix unit name: the unit name on Ubuntu is `redis-server.service`
* services which need a working redis require both After= and Wants=
Closes #10989
See the description for `After=` and `Wants=` in the `systemd.unit` man page.
=> Fix(build): add service dependency to redis for several services

build/packages-template/bbb-config/after-install.sh, build/packages-template/bbb-config/build.sh
The redis dependency for `bbb-apps-akka` and `bbb-fsesl-akka` has
already beed added to the unit files in commit b6777ed9cbed26adf8b06e295c17866d3427c1ec so
the override is no longer neccesary.
Closes #15192
=> fix: remove obsolete systemd overrides

bigbluebutton-config/bin/bbb-conf
Tweaks bbb-conf so that it refers to the correct source of truth for the BBB secret - /etc/bigbluebutton/bbb-web.properties
Closes # none
=> fix: bbb-conf to point to the correct file for BBB secret

bigbluebutton-config/bin/bbb-conf
It doesn't let the `bbb-conf --restart` flow crash when tomcat is not available. It also doesn't log tomcat-related error, instead, it logs a warning.
Closes #14852
To test it, the reviewer could mock a situation where tomcat is blocked and can't be started. They could achieve it by doing: 
``` bash
sudo systemctl mask tomcat9
sudo systemctl start tomcat9 #just to make sure
```
Now replace the old bbb-conf script with the new one, by doing: 
``` bash 
#!/bin/bash
cd ../bigbluebutton-config/bin/
sudo rm /usr/bin/bbb-conf
sudo rm /usr/bin/bbb-record
sudo cp bbb-record /usr/bin/bbb-record
sudo cp bbb-conf /usr/bin/bbb-conf
```
Then try `sudo bbb-conf --restart` the expected output should contain: 
``` bash 
Starting BigBlueButton
Failed to start tomcat9.service: Unit tomcat9.service is …
```
=> fix: Change in bbb-conf to not rely on tomcat

bigbluebutton-html5/imports/api/presentations/server/modifiers/addPresentation.js
Prevents a bug where some presentation slides are not loaded after conversion.
Closes #15209
=> fix: some presentation slides are not loaded after conversion

bigbluebutton-html5/imports/api/presentations/server/modifiers/addPresentation.js
This is a port of PR #15215 from develop branch to 2.5.
_Prevents a bug where some presentation slides are not loaded after conversion._
=> fix: some presentation slides are not loaded after conversion (2.5)

bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.js
This PR fixes the Microphone/Listen Only design inside the audio modal that was stretching when changing the Microphone/Listen Only label to a bigger sentence.
#15211
=> fix: microphone design inside audio modal

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
Adds additional check to chat-context adapter to prevent a crash when user data is not present.
=> fix: prevent chat-context crash on missing data

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Disables the hover highlight on slide background image.
Also disables shape selection for non presenter (when multiuser is not enabled).
=> Disable Background Slide Image Hover Highlight

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.js
Adjusts recording indicator to be the same for viewers and moderators when the meeting is being recorded.
Closes #15252
=> fix: Recording indicator too subtle

bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- [fix(audio): check if broker exists before trying to stop](https://github.com/bigbluebutton/bigbluebutton/commit/f026c397d9f147da453a9c8290b38cf8588d9f82)
None - recently found via log analysis.
There are scenarios where the full audio broker (SFU) stop  procedure
may be called multiple times in a very short timestamp - eg a concurrent
stop + connection failure; a timeout in the transfer procedure + a
reconnect attempt, [...]. When that happens, calls to exitAudio may throw
errors if the broker was already released - and that's not the expected
behavior.
n/a
=> fix(audio): check if broker exists before trying to stop

bigbluebutton-html5/private/config/settings.yml
Enables the feature set introduced in https://github.com/bigbluebutton/bigbluebutton/pull/14736 by default.
n/a
Seen a couple of months of real testing by now, so it's stable even if it's not 100% UX/UI-ideal.
n/a
=> chore(audio): enable local echo test and volume meter by default

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.js
Improves styling of virtual background selector thumbnails. Fixes bad alignment of images within selector containers.
_Before_ (images are a bit off)
After
None
n/a
n/a
=> improvement: virtual background selector thumbnail

bigbluebutton-html5/imports/ui/services/virtual-background/index.js
- [fix(webcam): prevent camera freeze due to _renderMask exceptions](https://github.com/bigbluebutton/bigbluebutton/commit/0c7c628f7a245a589975b348a5fa618ad7fe860f)
* Address the issue with a try-catch and a log for debugability (it's high
frequency, hence why not error level). We should probably remove the log
entirely once we figure out why the post-processing method is failing.
None
Under some scenarios, cameras are freezing when the virtual background
code is running due to runPostProcessing(_renderMask) throwing
NS_ERROR_FAILURE - mainly on Firefox - consequently preventing
subsequent TimerWorker ticks from being scheduled.
Cases where I've seen that happen are:
- conferences running under an iframe where the iframe is briefly
stalled for some reason
n/a
=> fix(webcam): prevent camera freeze due to _renderMask exceptions

bigbluebutton-tests/playwright/README.md
Add documentation to playwright README file explaining how to record Meteor traffic during test sessions.
=> test: add documentation on how to record Meteor traffic

bigbluebutton-html5/imports/ui/components/common/button/button-emoji/ButtonEmoji.jsx, bigbluebutton-html5/imports/ui/components/common/button/button-emoji/styles.js, bigbluebutton-html5/imports/ui/components/common/icon/component.jsx, bigbluebutton-html5/imports/ui/components/common/icon/styles.js
Move icon rotate info from ButtonEmoji component to Icon component.
None
Improve reuse.
Suggested by @prlanzarin in https://github.com/bigbluebutton/bigbluebutton/pull/15290
=> refactor: Icon component rotate info

bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js, bigbluebutton-html5/imports/ui/components/poll/service.js
Fixes a bug in poll publishing that could cause wrong results to be displayed in the chat, by moving the grouping of similar answers in poll results to sendPollChatMsg.
=> fix: wrong poll results displayed in the chat when answers are grouped

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ThumbnailCreatorImp.java, record-and-playback/core/lib/recordandplayback/generators/presentation.rb
Fixes how thumbnails and slides are displayed in recordings when the presentation slide was cropped.
1. Crop a PDF slide using a tool like Apple's Preview
2. Upload cropped PDF to meeting
4. Record meeting, add anotations
5. Playback shows uncropped thumbnails and slides, with incorrect annotation positioning
**Expected result:**
**Actual result:** (recreated)
As Tldraw recordings use the SVG slides that were shown in the meeting, that should not be an issue there. But the thumbnails likely still have to be changed in 2.6.
Tested on 2.5 but issue also present in 2.4.
=> fix(recording): Add PDF cropbox parameter to thumbnails and slides for playback

.github/workflows/automated-tests.yml, bigbluebutton-config/bin/bbb-conf
Reloads nginx configuration before BBB start
Closes #none
I have had to reload the configuration on all new installations the last few attemps. I see the same error on automated tests too and it seems to get resolved with reloading the configuration.
```
curl: (7) Failed to connect to droplet-4180.bbb-server.com port 443: Connection refused
.curl: (7) Failed to connect to droplet-4180.bbb-server.com port 443: Connection refused
.curl: (7) Failed to connect to droplet-4180.bbb-server.com port 443: Connection refused
....
.curl: (7) Failed to connect to droplet-4180.bbb-server.com port 443: Connection refused
```
=> fix(config): Reload nginx configuration before BBB start

build/setup-inside-docker.sh, build/setup.sh
Modfies the package build scripts to calculate GIT_REV and COMMIT_DATE outside the docker container and pass them in as environment variables, since we can't compute them inside the docker container if the source directory is a git worktree
Closes #14888
I'm not sure how this interacts with the CI environment, since I can't easily test it.  In particular, it moves a reference to CI_COMMIT_SHA from `setup-inside-docker.sh` to `setup.sh`.  Somebody who knows the CI system should check to make sure this doesn't break things.
=> Let packaging scripts operate in a git worktree

build/setup-inside-docker.sh, build/setup.sh
This is the `2.4.x-release` variant of PR #14889
Modfies the package build scripts to calculate GIT_REV and COMMIT_DATE outside the docker container and pass them in as environment variables, since we can't compute them inside the docker container if the source directory is a git worktree
Closes #14888
I'm not sure how this interacts with the CI environment, since I can't easily test it.  In particular, it moves a reference to CI_COMMIT_SHA from `setup-inside-docker.sh` to `setup.sh`.  Somebody who knows the CI system should check to make sure this doesn't break things.
=> build: Let packaging scripts operate in a git worktree

build/packages-template/bbb-config/before-install.sh, build/packages-template/bbb-config/build.sh
Introduces a wait time in Redis' start procedure to ensure it is up, running and listening before other BBB components start. See #15342
Closes #15342
After #14616 was introduced we were seeing #15342 
@danimo came up with this solution. I am including it in the packaging.
Credits: @danimo
=> build: ensure redis is up redis-server.service.d/overrride.conf

bigbluebutton-html5/imports/ui/components/audio/local-echo/component.jsx, bigbluebutton-html5/imports/ui/components/audio/local-echo/styles.js
[fix(audio): make `hearing` a transient prop in local-echo](https://github.com/bigbluebutton/bigbluebutton/commit/c3cba9ccc6738709840978cedf85e4a926dd2f3a)
None
Prevents annoying console exceptions in dev mode.
n/a
=> fix(audio): make `hearing` a transient prop in local-echo

bigbluebutton-config/bin/bbb-conf
This PR adds a `--set-port-range` option to `bbb-conf`, and adds code to make `bbb-conf --check` display the existing port ranges.
There's a one-line awk snippet taken from stackexchange to extract the port range from Kurento's ini file.  Probably too trivial to be a copyright issue.
sed/awk to parse and edit ini files should probably be replaced with a tool like `crudini`, but that's a separate PR.
=> feat(config): Set port range

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
Avoids crashing when `users[Auth.meetingID][Auth.userID]` is `undefined`.
Closes #15359
=> fix(chat): `undefined` property access

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/styles.js
Prevents a crash in the client when audio is muted.
=> fix: add missing import in audio controls

record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb
Only applying the code currently available in 2.5+ to 2.4. For its inclusion if / when another release comes out.
=> fix(recording): Override configuration properties applied to 2.4 (closes #15388)

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
The user list in the main room showed user being in breakout rooms who
already left a breakout room. It adds a check if the user is still in a breakout room or not.
Closes #14982
=> Fix: only show breakout room in user list when user is in breakout room

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Syncs presentation data `isCurrent` between props and local state.
Closes #15272
=> fix: apply presentation 'isCurrent' changes to local state

bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js, bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUser.js
- [refactor(audio): log VoiceUser cleanup on User remove and centralize it](https://github.com/bigbluebutton/bigbluebutton/commit/6331e869b9db5df85b1ea7e644ef87011254d858)
* This commit centralizes that cleanup in a new clearVoiceUser modifier in
voice-user as well as logs when it works.
None
There's a VoiceUser cleanup procedure bound to the User's cleanup
routine in Meteor's server-side. That cleanup is _silent_ and does not
use a dedicated modifier from voice-user et al, which is not
straightforward and might waste a few minutes of understanding what's
happening when debugging audio collections.
n/a
=> refactor(audio): log VoiceUser cleanup on User remove and centralize it

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
- [fix(layout): set external-video/screen share initial states on all layouts](https://github.com/bigbluebutton/bigbluebutton/commit/8f77f4cd1f12ff5f1460253f028c659b81adba22)
* This commit guarantees those features are taken into account when
populating initial input states for Focus On*/Custom layouts.
None
Only smart layout takes screen sharing/external video states in account
when populating its initial state. The others don't, and that causes
some weird issues when switching back-and-forth between layout types due
to their input states becoming inconsistent - ie having an active screen
sharing and transitioning from Smart to a buggy layout would mark screen sharing
as false and pollute its state for subsequent layouts. 
A practical example of this issue: smart layout isn't …
=> fix(layout): set external-video/screen share initial states on all layouts

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/container.jsx
Fixes the breakout rooms remaining time label in languages whose translation for the word "Duration" is more than one word.
_For example, Persian (Farsi)_
Closes #15397
=> fix: breakout remaining time label

bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
Before
After
Closes none, but related to https://github.com/bigbluebutton/bigbluebutton/issues/15168#issuecomment-1186213746.
=> fix: whiteboard access avatar icon in RTL mode

bigbluebutton-tests/playwright/screenshare/util.js
Waiting for `e.screenshareConnecting` creates a race condition if the
screen share connects quickly, before the test waits for the
screenshareConnecting message.
=> test: Don't wait for screenshareConnecting

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js
- [fix(layout): use actual screen share size when calculating smart layout](https://github.com/bigbluebutton/bigbluebutton/pull/15429/commits/b8811bafd410feb4460a902048e7e169d12a5836)
Closes https://github.com/bigbluebutton/bigbluebutton/issues/14691
Smart layout (et al) presumes screen sharing will always use 100%
width of the media area. That causes cameras to always be positioned on
top, which is not always the optimal position depending on the viewport
and stream aspect ratio/resolution - so space is wasted.
This commit uses the actual screen sharing video size as provided by
HTMLVideo's videoWidth/videoHeight properties. The calculation uses the
same logic as the one used for presentation/slides, which should make it
a bit familiar.
There's also a handler for HTMLVideo's `resize` …
=> fix(layout): use actual screen share size when calculating smart layout

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/public/locales/en.json
Implements a notification to the action chosen by the moderator inside the waiting user's list.
Closes #15127
=> fix: Adding notification to waiting users list

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
This is a (partial) port of PR #15109 from 2.4 to 2.5.
_Prevents a bug where the restoreOnUpdate feature (sometimes) fail if a large file is uploaded._
=> fix: autoSwapLayout/restoreOnUpdate new presentation fails to show (2.5)

record-and-playback/presentation/scripts/publish/presentation.rb
It fixes a typo in presentation script that was generating nil errors.
Closes #15439
=> fix(recording): Fix typo in presentation scripts

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Sets initial values for external video/screnshare for mobile devices.
Closes #15453
=> fix: In Android Screen share and Share external video not showing to newly joined

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-stream-volume/component.jsx, bigbluebutton-tests/playwright/audio/audio.js, bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/audio/util.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/user/multiusers.js
- Add 5 new audio tests:
- Mute yourself by clicking the mute button (_also on **CI**_);
- Change audio input and keep it connected;
- Keep the last mute state after rejoining audio (_also on **CI**_);
- Mute yourself by clicking the talking indicator (_also on **CI**_);
- Mute another user by clicking the talking indicator (_also on **CI**_);
- Add links to the test plan;
=> test: Add new audio tests

record-and-playback/core/scripts/bigbluebutton.yml, record-and-playback/presentation/scripts/process/presentation.rb, record-and-playback/presentation/scripts/publish/presentation.rb
- Update the version to 2.6.0 to ease the detection of old/new whiteboard events
- Fix recording cursor when there is no pan/zoom and annotations in tldraw
- Don't generate slides pngs for 2.6.0, they are not used anymore in playback (svgs instead).
=> fix(recording): bump bbb_version to 2.6.0 in events.xml

bigbluebutton-html5/imports/ui/components/audio/captions/button/styles.js
Adjusts captions button icon position.
=> fix: adjust captions icon position

bigbluebutton-config/bin/bbb-conf
Add checks to `bbb-conf --status` to check the state of
- bbb-rap-caption-inbox
- bbb-rap-resque-worker
- bbb-rap-starter
This is to help warn the administrator if these services are not running.
See discussion https://groups.google.com/g/bigbluebutton-dev/c/KWWxS1rWjao/m/xVvcOkrmBgAJ.
Still need to determine why these scripts are not running on upgrade.
=> check status of services for recording workers with `bbb-conf --status`

bigbluebutton-tests/playwright/webcam/util.js
Use browser's SHA-1 hash from Web Crypto API instead of a custom hash function
This is the `v2.4.x-release` version of a change made to `v2.5.x-release` in PR #15236
=> test: webcamContentCheck (2.4)

build/packages-template/bbb-record-core/after-install.sh
Enable servies `bbb-rap-resque-worker.service` and `bbb-rap-starter.service` so recordings will process after server reboots.
Closes #15138
=> build: Enable bbb-rap-resque-worker and bbb-rap-starter on install

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Updates the way the tldraw toolbar is positioned in BBB to use the provided API.
Also fixes the locale strings not updating on the whiteboard when language is changed.
=> fix: Position Whiteboard Toolbar with API | Sync Current Locale

bbb-export-annotations/config/settings.json, bbb-export-annotations/workers/collector.js, bbb-export-annotations/workers/notifier.js, bbb-export-annotations/workers/process.js
Suppresses the `protocol://hostname` in the public link generated for annotated PDF downloads since HTML links use the same parameters as the current page.
Reduce coupling by removing the need for packaging/after-install scripts to define the protocol, hostname, and port in annotated PDF exports.
Removes unnecessary message being sent to parent worker before child exits.
=> refactor: remove host parameters in bbb-export-annotations config

bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/layout/initState.js, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
Shows both `navbar` and `actions-bar` only after the layout has been calculated.
Closes #15341
Just setting properties like `width`, `min-width`, `min-height` is not enough to hide the navbar and actions-bar. Still, the content will overflow and both navbar and actions-bar will be visible for a brief moment if the layout calculation takes too long.
=> fix(layout): don't show `navbar`/`actions-bar` before layout has been calculated

build/packages-template/bbb-export-annotations/opts-focal.sh
This is a first cut in ensuring the dependencies from https://github.com/bigbluebutton/bigbluebutton/pull/14562 are present
Closes #none
Without `cairosvg` the generated pdfs are blank...
`imagemagick` is already present on the system as dependency of bbb-web but I include it here to in case bbb-export-annotation outlives bbb-web.
`ghostscript` seems to already be present within Ubuntu but I see no harm in ensuring its presence.
There is still work to do in this area based on https://github.com/bigbluebutton/bigbluebutton/pull/14562 :
This work should be coming in a subsequent PR
=> build: export-annotations depend on cairosvg imagemagick ghostscript

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Fixes a bug where removed presentations would still appear in the presentation upload modal. 
Closes #15503
=> fix: Removing presentation is broken

bigbluebutton-tests/playwright/polling/poll.js
wait a bit longer for a slide conversion that might fail a test if too slow
=> test: 'Create quick poll - from the slide' improvement

bigbluebutton-tests/playwright/customparameters/customparameters.js
test 'Skip audio check' - clear default presentation toast or test can fail because there'll be two small toasts at the end of this test
=> test: 'Skip audio check' improvement

bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js, bigbluebutton-html5/imports/ui/services/webrtc-base/peer.js, bigbluebutton-html5/private/config/settings.yml
- [feat: configurable DSCP marking for WebRTC media](https://github.com/bigbluebutton/bigbluebutton/commit/0e162f1cda54a00cb67fde38cc7d8b348fe75fcd)
* See the public.app.media.networkPriorities configuration in
settings.yml. 
* Audio, camera and screenshare priorities can be controlled
separately. 
* For further info on the possible values, see:
- https://www.w3.org/TR/webrtc-priority/
- https://datatracker.ietf.org/doc/html/rfc8837#section-5
None
RTCRTPSender exposes DSCP marking via `networkPriority` in the encodings
configuration dictionaries. That should allow us to control QoS priorities for 
different media streams, eg audio with higher network priority than video. 
The only browser that implements that right now is Chromium.
Disabled by default until we can make sure there isn't …
=> feat: configurable DSCP marking for WebRTC media

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
BBB's pan tool was removed from the whiteboard toolbar with the recent updates. This PR temporarily adds back a pan tool to the presentation toolbar.
https://github.com/bigbluebutton/bigbluebutton/issues/15345
=> refactor: Add Pan Button to Presentation Toolbar

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Fixes styling of the multi user whiteboard button in RTL mode.
Fixes styling of both previous slide button and next slide button in RTL mode.
Before
After
Closes #15484
Closes #15542
=> style: presentation toolbar in RTL mode

bigbluebutton-html5/imports/ui/components/app/component.jsx
- https://github.com/bigbluebutton/bigbluebutton/commit/95077975882a8188d0041b785150c72ad516a9ed: Fixes the issue described in https://github.com/bigbluebutton/bigbluebutton/issues/15509.
- https://github.com/bigbluebutton/bigbluebutton/commit/f4fc11d53b1b456cfb7c920a20da6e372cf1cd24: Fixes the cases to switch between layouts (see an example below).
> Example:
> 
> 1. User A joins as moderator.
> 2. User B joins as viewer.
> 3. User A changes layout to, let's say, Focus on Video, turns Push Layout on and confirms it.
> 4. Layout is pushed to User B (correct!).
> 5. Now, User A changes layout to different one, turns Push Layout off and confirms it.
> 
> Expected behavior: Layout changes only for User A.
> 
> Actual behavior: Layout changes for User B as well.
> 
> Note: this must be tested …
=> fix: push layout not working unless changed

bigbluebutton-html5/imports/api/video-streams/server/modifiers/updatedVideoStream.js
- [fix(webcam): properly flatten videoStream on meteor sync call](https://github.com/bigbluebutton/bigbluebutton/commit/325eb036960f5b171c4c409e6e82a80a3baf46be)
Closes https://github.com/bigbluebutton/bigbluebutton/issues/15547
https://github.com/bigbluebutton/bigbluebutton/issues/15547
=> fix(webcam): properly flatten videoStream on meteor's webcam sync call

.github/workflows/automated-tests.yml, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js
Configure github to run Firefox tests on PRs with the "test Firefox" (or "Test Firefox") label
Also add conditions to the screen share tests so they're not attempted on Firefox without a DISPLAY variable set, because Firefox can't find a screen to share in that case
=> test suite: add Firefox tests to CI (2.6)

bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/core/util.js, bigbluebutton-tests/playwright/notifications/util.js
`checkElement` was being called from `waitAndClearDefaultPresentationNotification` in such a way that `svg[data-test="whiteboard"]` was being destructured in `checkElement` with `element` set to `s` and `index` set to `v`, instead of `element` being `svg[data-test="whiteboard"]` and `index` being `0`.  Therefore, this call to `checkElement` was always returning false.
Fixing that problem revealed a new one: `svg[data-test="whiteboard"]` is almost always present, even when a toast is being posted to indicate that the default presentation is being loaded.  Therefore, change `waitAndClearDefaultPresentationNotification` to check for the toast being present (and clearing it), rather than checking for the whiteboard being present.
I also added some code to `checkElement` to try and catch …
=> test suite: fix check for default presentation toast

.github/workflows/automated-tests.yml, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js
Configure github to run Firefox tests on PRs with the "test Firefox" (or "Test Firefox") label
Also add conditions to the screen share tests so they're not attempted on Firefox without a DISPLAY variable set, because Firefox can't find a screen to share in that case
=> test suite: add Firefox tests to CI (2.5)

bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Since _text annotations_ are synced in 'real time', we shouldn't clean them up.
Closes #15458
=> fix: don't clear text fake annotations

bbb-libreoffice/docker/Dockerfile
Upgrade the Java version of Libreoffice container to `openjdk:17-slim-bullseye`, once this is the next LTS version since current `openjdk:11-jre-bullseye`.
The Libreoffice conversions is working fine with this upgrade!
=> refactor: Upgrade Libreoffice docker from java 11 to java 17

akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala
- Sends back-end notifications (from akka) to the appropriate _Redis_ channel, as they are handled by _bbb-html5 frontend_ instances.
https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-html5/imports/api/meetings/server/modifiers/emitNotification.js#L4
Closes #15463
=> fix: send notification messages to appropriate redis channel

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Adds missing paramater that contains custom virtual background data. Otherwise, we can't initialize custom backgrounds and an exception is thrown.
It was left out in https://github.com/bigbluebutton/bigbluebutton/pull/15566.
Closes none
=> fix: add missing custom virtual background param

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
Adjusts presentation uploader in order to correctly display errors when a presentation that exceeds file size or page limits is uploaded.
This PR was inspired by #15438 (thanks @MBM1607!), but includes other fixes to 2.5 presentation uploader issues.
Closes #15543
Closes #15435
=> fix: display presentation uploader limit errors

bigbluebutton-tests/playwright/core/page.js
Don't check for a transient "connecting" message, check instead that it's been removed.
=> test suite: fix race condition on webcam connecting (2.5)

bigbluebutton-html5/client/stylesheets/fonts.css, build/packages-template/bbb-html5/build.sh
- adjusts build script, so `v=VERSION` is replaced by the correct build number.
- appends version number to font urls in fonts.css file, preventing the following warning from appearing in browser console: 
_The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally_
=> fix: preloaded fonts being requested again

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Adjust breakout room assignment buttons size and position.
=> style: adjust breakout room assignment buttons

bigbluebutton-html5/imports/ui/components/common/button/component.jsx
Adds `light` as a valid button color.
=> fix: light button warning

bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
When the user is ejected due to inactivity, a generic error is being showed.
And there is a random behavior where sometimes the user see the first print and sometimes the second.
This PR will show the properly reason why he was removed:
When the user has problem with disconnection. When the connection is re-established he can't join to the meeting again!
He is immediately removed once he connects to the server!
https://user-images.githubusercontent.com/5660191/185202180-51e6ef30-3677-4bb9-8299-b2e29c21d32b.mp4
With this PR this situation will be avoided once the user will have 3 seconds to try to re-establish the connection before being removed from the meeting:
https://user-images.githubusercontent.com/5660191/185202404-13081143-afe4-419c-b5ba-87f66b1c0b82.mp4
-----
- Problem 1 details: …
=> fix (2.6): enhancements over disconnection situation (delay to remove and show ejected reason)

bigbluebutton-config/assets/index.html
It adds the logic to show errors when necessary by reading the URL query params and display them in a certain way
BBB-demo had this feature, which was nice as it explains to the user why and what has happened. But since we don't have bbb-demo anymore, the new static content that goes in the root can be responsible for that.
This first picture shows what would happen if we had more the one error to display.
For just one error.
And for no errors, it would maintain the same as it was before.
=> (fix) - Show errors in root

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.js
Increases "send to chat" button font size, so it becomes easier to read (text looks "broken" in current size).
=> style: increase send to chat button font size

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
- Handles the Safari edge case: disable brightness on it.
- Prevents unnecessary execution of the segmentation algorithm: Start the segmentation when the Video Preview modal opens and stops it when it closes if brightness is unchanged (`brightness === 0`)
Closes none
n/a
https://github.com/bigbluebutton/bigbluebutton/pull/15603
=> fix(camera): disable brightness on Safari and stop segmentation if brightness is unchanged

bigbluebutton-config/bin/bbb-conf
* restores `bigbluebutton.target` as the one in control of what needs to be started/stopped with bbb-conf --start/stop
* one more tweak to the tomcat9 checks
Closes #none
In https://github.com/bigbluebutton/bigbluebutton/pull/14616 we changed the start/stop command to utilize `bigbluebutton.target` However, likely during a merge from v2.5.x-release, we added a bunch more services to the command reducing its value.
The check for Tomcat is an addition to https://github.com/bigbluebutton/bigbluebutton/pull/15489 -- we were still listing tomcat9 as a non-running app
=> fix: bbb-conf --start to use bigbluebutton.target only

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Reduces the distance from the toolbar to the bottom.
Closes #15658
=> fix(whiteboard toolbar): reduce distance from the bottom

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/service.js, bigbluebutton-html5/imports/ui/services/webrtc-base/bbb-video-stream.js
- [fix(webcam): retry gUM on NotReadableError for Chrome/Edge](https://github.com/bigbluebutton/bigbluebutton/commit/5d04bcaf93af68eab7a90b75a626860ed41e65ef)
* Chrome/Edge sometimes bork gUM calls when switching camera
profiles. This looks like a browser bug (issue TBD). Track release not
being done synchronously -> quick subsequent gUM calls for the same
device (profile switching) -> device becoming unavaible while previous
tracks aren't finished.
Since track stop is not "awaitable", this commit adds a retry procedure
that re-runs gUM up to 5 times (200 ms delay) only if error.name is
NotReadableError and browser is either Chrome or Edge.
- [fix(webcam): add MediaStream id to 'inactive' event handlers](https://github.com/bigbluebutton/bigbluebutton/commit/646db913676a4bca47d6e9b1b7168fab …
=> fix(webcam): switching profiles in preview fails intermittently

bigbluebutton-html5/imports/api/audio/client/bridge/base.js, bigbluebutton-html5/imports/api/audio/client/bridge/service.js, bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/public/locales/en.json
There's no rollback procedure in case a device switch fails right now,
nor does the code entrypoints that call the switching procedures wait
for resolution or failure before marking the new device as chosen. That
may cause inconsistent states in a couple of ways:
- No rollback: switch fails, audio is still on but no actual
microphone input is being transmitted
- Not waiting for resolutions: inconsistent chosen devices on failures
Device switching errors are also not surfaced to the end user
This commit:
- Adds device rollback and proper resolution/failure response
awaits to try and make the state a bit more consistent.
- Centralizes the input device switching code to be reused between
different bridges
- Centralizes device ID state management in audio-manager to try and
mantain them a bit …
=> fix(audio): review in/out device management and switching

bigbluebutton-html5/imports/ui/services/virtual-background/index.js
Checks the type of virtual background on change. If it is **image**, go ahead and create a new image tag. If it's not (it's **Blur** effect), skip such step. That way, we avoid an undesirable request to `public/resources/images/virtual-backgrounds/Blur` (which doesn't even exist and doesn't need to).
Closes #15555
=> fix: check virtual background type on change

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Adjust presentation toolbar so buttons don't overflow when in focused/active state
=> fix: button overflow in presentation toolbar

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
- Updates the `react-intl` dependency to `@6.1.0`.
- Adds config to disable the fallback mechanism when the locale string is empty.
Closes #15579
This will allow us to disable fallback text and show empty strings instead.
For example:
Consider
```json
"app.chat.titlePublic": ""
```
in `en.json`.
With `fallbackOnEmptyLocaleString: true`:
With `fallbackOnEmptyLocaleString: false`:
The update was made paying attention to the breaking changes:
- [**v3 -> v4**](https://formatjs.io/docs/react-intl/upgrade-guide-4x)
- [**v4 -> v5**](https://formatjs.io/docs/react-intl/upgrade-guide-5x)
- [**v5 -> v6**](https://github.com/formatjs/formatjs/releases/tag/react-intl%406.0.0)
(None of them affects BBB)
=> chore/fix: update `react-intl` to `6.1.0` and add config to disable fallback

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/common/button/base/component.jsx, bigbluebutton-html5/imports/ui/components/common/control-header/left/component.jsx
Fix the following warnings:
- Warning: Received false for a non-boolean attribute panning. (`ButtonBase` component)
- Warning: Invalid DOM property tabindex. Did you mean tabIndex? (control header `Left` component)
- Warning: Failed prop type: The prop layoutType is marked as required in LayoutEngine, but its value is undefined. (`LayoutEngine` being rendered too soon in `App` component)
=> Fix: bigbluebutton-html5 warnings

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Restores the per character text shape updates that was lost in the `tldraw` upgrade.
=> fix: Restore Text Shape Updates Per Character

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Sets room name inputs as read-only and removes "text" cursor when the moderator is managing breakout users (after breakout creation).
https://user-images.githubusercontent.com/3728706/189920692-266eed9f-b1a7-4355-abc2-a1a38085a3b0.mp4
https://user-images.githubusercontent.com/3728706/189920661-b640692c-ad22-4e6c-a372-3a56d2278084.mp4
Breakout room names can't be changed after creation, but displaying them as editable text fields might confuse users.
Closes #15669
=> fix: set breakout name input as readonly when updating users

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
Prevents malformed cursor position messages from being sent
Due to cursor loading faster than whiteboard in certain cases it caused position messages to be sent with missing whiteboard ID resulting in 
`ERROR o.b.c.p.s.ReceivedJsonMsgHandlerActor - Failed to deserialize message Missing creator property 'whiteboardId' (index 0); 'DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES' enabled`
Also it adds a log that lets user know that cursor position has not been sent
1. Create meeting
2. Join as Moderator
3. Join Audio as soon as possible
4. Pick pencil annotation and start drawing immediately
=> handle missing cursor property case

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
When matching user-supplied meeting IDs in API calls, use `ServiceUtils.findMeetingFromMeetingID` instead of `meetingService.getMeeting`, in order to handle either external or internal meeting IDs
Prior to this PR, passing an internal meeting ID to `getMeetingInfo` (and probably other API calls) would trigger a 500 Internal Server Error in response.
Since the authentication API returns the internal meeting ID in response to a `checkAuthorization` call, it is important for the client-facing API to handle this case.
=> use findMeetingFromMeetingID in API calls

record-and-playback/core/lib/recordandplayback/edl/video.rb
When converting from using the 'movie' source filter to using separate ffmpeg command line inputs, it wasn't taken into account that the 'movie' filter passes through timestamps from the source file, while the ffmpeg input adjusts timestamps so that '0' is the selected seek point.
The easiest fix is to add an option to the ffmpeg command to disable the timestamp adjustments.
Fixes #15644 (This needs to go into BigBlueButton 2.5 and 2.6)
=> recording: Fix incorrect seek offsets in video

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/logger.js, bigbluebutton-html5/private/config/settings.yml
This is a port of PR #15699 from 2.5 to 2.6.
_Makes the following changes so it becomes easier to monitor the health of the html5 servers:_
_- adds timestamp and information about server instance to server logs_
_- adds a new log message with cpu/memory usage for each server_
=> refactor: html5 server log improvements (2.6)

bbb-libreoffice/docker/Dockerfile, bigbluebutton-config/bin/apply-lib.sh
The build for `bbb-soffice` docker file started to fail.  After a bit of testing, found it installs with removing `-t bullseye-backports` from Dockerfile.
Closes #15703
While this appears to get the install working again, more testing is needed.
=> Fix bbb libreoffice dockerfile

bigbluebutton-config/bin/apply-lib.sh
When `/usr/share/bbb-web//WEB-INF/classes/bigbluebutton.properties` does not end in a newline, it can trip up getting `bigbluebutton.web.serverURL` from `/etc/bigbluebutton/bbb-web.properties`.
=> Add newline when scanning bigbluebutton.properites

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
Adjusts poll live results to correctly display translated strings in multiple response polls.
Closes #15686
=> fix: multiple answer translation in live results

bigbluebutton-html5/client/main.jsx
Disable xhr fallback on websocket connection.
=> fix: disable xhr fallback on websocket connection

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/logger.js, bigbluebutton-html5/private/config/settings.yml
Makes the following changes so it becomes easier to monitor the health of the html5 servers:
- adds timestamp and information about server instance to server logs
- adds a new log message with cpu/memory usage for each server
`info : Added presentation id=8ed482ae3f9e099142b9a939c663d0ee41e66cc9-1663336566249 meeting=197cc79b2223ce7871d7059d9b990a127aecd8df-1663336566196 {}`
`2022-09-16T13:56:13.306Z backend-1 [info] : Added presentation id=8ed482ae3f9e099142b9a939c663d0ee41e66cc9-1663336566249 meeting=197cc79b2223ce7871d7059d9b990a127aecd8df-1663336566196 {}`
`2022-09-16T13:22:04.818Z frontend 1 [info] : Server health {"memoryUsage":{"rss":"111.24 MB","heapTotal":"59.7 MB","heapUsed":"55.67 MB","external":"23.42 MB"},"cpuUsage":{"system":"0.17 MB","user":"2.88 MB"}}`
=> refactor: html5 server log improvements

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GuestPolicyValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/MaxParticipantsValidator.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Modifies the maxParticipants calculation to only count joined users. A new maxParticipants check is done when a user moves from being entered to joined and the user is ejected if this check fails.
=> refactor: Modify maxParticipant calculation 2.5

bigbluebutton-html5/imports/ui/components/chat/service.js
Fix for a crash that happens if a moderator sends a broadcast message to breakouts and the breakout user has push alerts enabled.
Closes #15709
=> fix: broadcast push alert crash in breakouts

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
This is a port of PR #15687 from 2.6 to 2.5.
_Adjusts poll live results to correctly display translated strings in multiple response polls._
=> fix: multiple answer translation in live results (2.5)

bigbluebutton-html5/deploy_to_usr_share.sh
When running the script `deploy_to_usr_share.sh`, it ends with the following error:
As @ramonlsouza noticed, it happens because in the docker-dev, `npm` version is different from `meteor npm` version
In order to avoid this problem I made the script use the command `meteor npm i` (instead of `npm i`) and then use the same version that meteor used in the previous commands.
=> fix: script to deploy html5 using wrong npm version

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
Allows _Webcam Settings_ modal to open when `userdata-bbb_skip_video_preview=true`, webcam is shared and device is desktop.
Closes #15692
=> fix: allow video settings to open

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GetChecksumValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Adds support for SHA384 and SHA512 checksums. A new property, checksumHash, has been added to the bigbluebutton properties file which allows a user to set what hash algorithm should be used to validate checksums. If no algorithm is defined it defaults to using SHA1.
=> Checksum Hash Algorithm Updates

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GuestPolicyValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/MaxParticipantsValidator.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
What does this PR do?
Modifies the maxParticipants calculation to only count joined users. A new maxParticipants check is done when a user moves from being entered to joined and the user is ejected if this check fails.
=> Modify maxParticipant calculation 2.4

bigbluebutton-html5/private/config/settings.yml
Sets `disableWebsocketFallback: true` by default in settings.yml (same as it was in 2.6 before the [2.5 PR with the settings](https://github.com/bigbluebutton/bigbluebutton/pull/15723) was merged into 2.6)
=> chore: set disableWebsocketFallback default value to true

bigbluebutton-html5/imports/ui/components/webcam/component.jsx
Prevents a bug that may cause the whiteboard cursor to appear in the wrong position if it is dragged & dropped in the same position.
https://user-images.githubusercontent.com/3728706/192372239-b9ab5600-59ab-4ee9-96a7-5d919065b59a.mp4
=> fix: cursor bug after camera is dropped in the same place

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GetChecksumValidator.java
Fix a bug introduced in #15684.
When the config `checksumHash=sha256` is set, bbb-web is using `sha384` instead.
=> Fix (bbb-web): checksumHash=sha256 not working

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.js, bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
Prevents avatar text and _offline_ label from being selected when selecting text in chat.
Closes #15746
=> improvement: text selection in chat

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-picker/component.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-tests/playwright/core/settings.js
Adds config in `Settings.yml` to disable frequent emoji sort on emoji click.
Closes #15712
=> fix: add config to disable emoji sort on click

bbb-libreoffice/docker/Dockerfile
As reported in https://hub.docker.com/_/openjdk, the current parent image `openjdk` is deprecated!
This PR will switch the parent docker image to `amazoncorretto`.
It will bring some pros:
- It will use less disk space
- It brings a more recent version of Libreoffice
  | Before | After
-- | -- | --
OS | Debian 11 (bullseye) | Alpine Linux v3.15
LibreOffice | 7.0.4.2 00 | 7.2.2.2
Jdk | 17.0.2 2022-01-18 | 17.0.4.1 2022-08-12 LTS
Bbb-soffice image size | 2.48GB | 877MB
Parent Image | openjdk | amazoncorretto
Parent Image size | 408MB | 333MB
=> refactor (bbb-soffice): Switch parent image to amazoncorretto:17-alpine

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx, bigbluebutton-tests/playwright/chat/privateChat.js
- Hide cursor for others when the mouse leave the whiteboard
- Set -1.0 as out of bound posistions so the cursor is also treated correctly in playback (otherwise it could be seen at the top left (0.0, 0.0)
[15690](https://github.com/bigbluebutton/bigbluebutton/pull/15690) introduced a bug where the out of bounds position were not being sent to akka.
=> fix(cursor): hide cursor for others on mouse leave

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Sometimes when whiteboard props change (mainly resizes), the tldraw component gets mounted again, resetting its camera, and was causing zoom to be applied incorrectly. I've added a useEffect to better react to when the camera resets and set to the corret zoom.
Closes #15656 
Expept the undo stopping working (number 4), since the tldraw app gets mounted again, it loses it's history. We will probably have a way to have a local copy of the history/stack to avoid this
=> fix(whiteboard): several zoom fixes

bbb-voice-conference/config/freeswitch/conf/autoload_configs/conference.conf.xml, bbb-voice-conference/config/freeswitch/conf/autoload_configs/opus.conf.xml, bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml, bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
These are the update FreeSWITCH settings based on research by Ghazi Triki and feedback from members of the community.  See
https://groups.google.com/g/bigbluebutton-setup/c/OJwurn8hfhM/m/pfS6kQg0BQAJ
We want to thank the many members of the community that have been experimenting and sharing feedback on the FreeSWITCH audio settings.   
This change reverts the setting of the jitterbuffer in FreeSWITCH back to "60:120".  See    https://github.com/bigbluebutton/bigbluebutton/issues/15172.
In testing with Chrome, with the old settings, the outbound RTP data from the client was about 30 KBits/sec, and with the new settings the client sends about 60 KBits/sec, which also provides a better audio quality.
In contrast, I tested the above changes for a few hours with FireFox and couldn't get the …
=> Update FreeSWITCH settings for improved audio

build/packages-template/bbb-html5/systemd_start_frontend.sh
Enables `SERVER_WEBSOCKET_COMPRESSION` in html5client front-end servers, reducing data size transferred via websocket.
From Pablo's report in [bigbluebutton-dev group](https://groups.google.com/g/bigbluebutton-dev/c/gy6KmK-41mY/m/RHJmTzvmBQAJ):
_Modern browsers are sending a header like this:_
_Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits_
_That tells the server that browser can handle compressed messages. But, as of now, BigBlueButton is ignoring that header._
_The first parameter "level" is recommended to be set between 4 and 6. All three options are good compression for little cpu being 6 the highest compression and 4 the most cpu. Other level of compressions are not suitable for this situation._
_I already have this in my 2.5.4 production server with level 4 …
=> build: enable websocket compression in front-end servers

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
[This line](https://github.com/bigbluebutton/bigbluebutton/blob/fe6a300ef3086d77d18c2c2282c257228f04eef9/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L420) was commented as default before #15467.
=> (refactor) bbb-web - Undo disabledFeatures=none in bigbluebutton.properties

bigbluebutton-html5/imports/ui/components/notes/converter-button/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx
It fixes the debounce feature that worked the wrong way (it restarted the timeout every time the user clicked the button `move notes to whiteboard`).
It also disables the button while this debouncing is activated, so now the user sees a block sign in place of the mouse indicator whenever they hover it, and the click event is forbidden during this period. 
https://user-images.githubusercontent.com/69865537/194387726-445685d2-39aa-4486-a7f1-ff44fd332e76.mp4
Here is a demo - so when clicked once, the debounce is activated and it prevents the user to click again for some amount of time, which now is 15 s.
=> [fix] - fix debounce not working properly

bigbluebutton-html5/imports/ui/components/external-video-player/volume-slider/styles.js, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/styles.js
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/15631.
=> fix: screenshare volume control

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/logger.js
Backports #15772 changes to 2.5.
_Removes empty object from logs that do not have additional data._
=> fix: remove empty object in logs (2.5)

build/packages-template/bbb-html5/systemd_start_frontend.sh
Backports #15779 changes to 2.5.
_Enables SERVER_WEBSOCKET_COMPRESSION in html5client front-end servers, reducing data size transferred via websocket._
=> build: enable websocket compression in front-end servers (2.5)

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/private/config/settings.yml
Introduces a new setting `alwaysShowWaitingRoomUI` which defaults to true and mantains current 'Waiting Users' UI behavior. If it's set to false the 'Waiting Users' UI element won't appear unless there is at least one guest user waiting to enter the meeting.
=> Option to hide waiting users icon when no pending users

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/private/config/settings.yml
Backports #15827 changes to 2.5.
_Introduces a new setting alwaysShowWaitingRoomUI which defaults to true and mantains current 'Waiting Users' UI behavior. If it's set to false the 'Waiting Users' UI element won't appear unless there is at least one guest user waiting to enter the meeting._
=> Option to hide waiting users icon when no pending users (2.5)

bigbluebutton-config/bin/bbb-conf
1. Change bbb-conf to use and prefer `stun` (available on focal) to check STUN servers, and only fallback on `stunclient` (only available on bionic) if `stun` is not installed on the system
2. Change how `stunclient` is called (drop the `--mode full`) to avoid nuisance complaints
When ported to v2.4.x-release, will close bbb-install issue [#565](https://github.com/bigbluebutton/bbb-install/issues/565)
`bbb-conf` currently checks accessibility of STUN servers only if `stunclient` is installed, and furthermore runs the check with `--mode full`, which runs additional tests that often return errors.
Also, `stunclient`'s package (`stuntman`) is not installed by `bbb-install`, and has been removed from focal.
This PR will make `bbb-conf` run `stun` if it is present, fall back on `stunclient` if …
=> Improve STUN checks in bbb-conf

bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Allows default presentation to be null
In past it would cause ambiguous errors if presentation is null
=> Fix: Default presentation allow null

bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Since #15860 was merged, the default presentation is always absent!
This PR undo this behavior.
=> fix (bbb-web): Default presentation is always null

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GetChecksumValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Fixes issues introduced in #15684 that made it so users who wished use to sha1 to validate checksums were required to make a configuration change in bigbluebutton.properties. This PR allows the following hash algorithms: SHA1, SHA256, SHA384, and SHA512, to be used without any additional configuration. Users who wish to reduce the number of available algorithms can edit the "supportedChecksumAlgorithms" property in the bugbluebutton.properties file to remove algorithms that are not needed.
=> Fixed issue with checksum algorithms

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Ensures shapes can't be sent behind the background slide image.
Closes #15836
=> Fix Moved to Back Shapes Lost Forever

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx
Fixes the mute items not updating and restores the menu item descriptions.
When all users have been muted, the control labels remain the same instead of changing to the unmute.
(Currently the labels only updates after closing / re-opening the user list)
=> Fix User Options Mute Items Not Updating

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/public/locales/en.json
Fix menu item descriptions not being announced by screen reader.
Update description for learning analytics dashboard item.
announcement before:
`Learning Analytics Dashboard  9 of 9`
announcement  after:
`Learning Analytics Dashboard Dashboard with users activities (opens new tab)  9 of 9`
Potential violation: The learning analytics dashboard menu item will open a new window or tab. The option fails to announce to screen reader users that the control opens a new window/tab.
=> Fix Menu Item Descriptions Not Being Announced

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
Adds video settings dropdown menu to the tab order.
Also adds hover and focus styles for reset zoom and skip slide elements.
Video settings dropdown was not accessible via keyboard.
Skip slide dropdown and reset zoom button have no styles for focus and hover states.
=> Add Dropdown to Tab Order and Hover / Focus Styles

bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/public/locales/en.json
- Remove paths from layout button aria labels.
- Add hover and focus states to layout buttons.
- Add aria descriptions to  layout buttons.
- Hide duplicate button label from screen reader.
also 
- Update whiteboard options button label with more context.
These are A11y improvements for 2.6
=> Layout Selection Modal A11y Updates

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/breakout-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx
Provides unique ids for menu component.
Multiple elements exist with the same id of `default-dropdown-menu` which creates problem with a11y.
=> Update Menu Ids to Remove Duplicates

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/public/locales/en.json
Adds a screen reader notification about the landing position of a selected user when assigning / moving to a breakout room.  
`Moved [userName] to room [roomNumber]`
When a moderator is assigning a user to a breakout room using a keyboard only: if they are also using a screen reader they are not provided with any feedback that the user has been successfully moved to a new breakout room.
=> Add Screen Reader Notification When Moving Users to Rooms

bigbluebutton-html5/imports/ui/components/learning-dashboard/service.js
Appends the `report` parameter when the session is no longer valid, instead of relying on the value being present as a cookie.
Closes: #15821
=> fix: show learning dashboard after session was ended in cluster proxy scenario

build/packages-template/bbb-config/opts-focal.sh
This is a followup to PR #15850, ensuring that a STUN client will be installed, so that `bbb-conf` will run STUN checks
Closes bbb-install issue [#565](https://github.com/bigbluebutton/bbb-install/issues/565)
=> Add stun-client package dependency to bbb-config

bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.8.7](https://github.com/bigbluebutton/bigbluebutton/commit/09bec2daf9ef90fb12e1d25972d9050f05df3c7b)
* See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.7
- Switch away from the forked repo back to npm/upstream
- This includes massive memory usage improvements in mediasoup
None
n/æ
n/æ
=> build(bbb-webrtc-sfu): v2.8.7

bigbluebutton-html5/imports/ui/components/learning-dashboard/service.js
Reverts bigbluebutton/bigbluebutton#15822
This change goes against a security requirement `Avoid anonymous access to Learning Dashboard (remove token from URL params)`.
The access link used to contain the param `report`, but it was removed in #13084 (https://github.com/bigbluebutton/bigbluebutton/pull/13084/commits/ddb383cf0591859ac5c29dd5c187aaab0a9e9077) for security reasons.
The Dashboard keeps reading `report` param because there is an idea of a button "Share public link" for the future. But this should not be the default way to access the Dashboard.
=> Revert "fix: show learning dashboard after session was ended in cluster proxy scenario"

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx
Stops the propagation of the click so we prevent a re-render.
Closes #15854
=> fix: necessity of clicking twice for downloading presentation

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-dropdown/component.jsx, bigbluebutton-html5/public/locales/en.json
Adds localization for the `Manage users` label, which is used in breakout dropdown.
None
=> fix(locale): add localization for `Manage users` label

bigbluebutton-config/bin/bbb-conf
This is PR #15850, backported to 2.4.
I left out a backport of PR #15904 (adding `stun-client` to the package dependencies), because 2.4 packaging already lists `stuntman-client` (the older STUN client) as a dependency, and PR #15850 will work with either `stuntman-client` or `stun-client` (the newer one).
Closes bbb-install issue [#565](https://github.com/bigbluebutton/bbb-install/issues/565)
=> Improve STUN checks in bbb-conf (2.4)

freeswitch.placeholder.sh
Bump the build of FreeSWITCH from 1.10.7 to 1.10.8.  See https://github.com/signalwire/freeswitch/releases/tag/v1.10.8
Bring in the most recent build of FreeSWITCH for testing in 2.6
=> Bump FreeSWITCH build to 1.10.8

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/imports/ui/components/settings/service.js, bigbluebutton-html5/imports/ui/services/locale/index.js
Adds internationalization singleton object in order to translate messages outside of React lifecycle.
Closes #15713
We needed a transparent way of translating text outside of React lifecycle/components.
=> improvement: add internationalization singleton

bigbluebutton-web/build.gradle, bigbluebutton-web/pres-checker/build.gradle
Today the build of `bigbluebutton-web` started to fail!
It seems that the repository JCenter has been shutdown!
https://blog.gradle.org/jcenter-shutdown
In order to fix this problem this PR removes this repository from the list.
=> fix: bbb-web is not building (JCenter repository failing)

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Correctly starts webcam brightness whenever the user changes camera device or camera quality profile.
Closes #15834
=> fix(webcam): brightness not working when changing quality profile

bigbluebutton-web/build.gradle, bigbluebutton-web/pres-checker/build.gradle
Following #15937
This will add `mavenCentral` as replacement for `jcenter` in repositories.
=> bbb-web: Adds mavenCentral as replacement for jcenter in repositories

bigbluebutton-web/build.gradle, bigbluebutton-web/pres-checker/build.gradle
=> backport 2.5: bbb-web: Adds mavenCentral as replacement for jcenter in repositories

bbb-export-annotations/workers/process.js
Prevents `bbb-export-annotations` from crashing should rendering of the text inside a shape fail.
Increase resilience of the annotation export component.
=> fix(bbb-export-annotations): Handle edge case in a shape's text label

bigbluebutton-html5/imports/ui/components/presentation/service.js
Display single yes/no poll option for the given example. No longer also presents the typed response.
Closes #15933
=> Remove Typed Response Option For Smart Slides Yes/No Poll

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/styles.js, bigbluebutton-html5/public/locales/en.json
Adds a quick play dropdown menu on the presentation toolbar for available external video links in the slide content.
Closes #15928
=> Add External Videos To Smart Slides

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/container.jsx
Removes the disabled flag for poll items in the smart slides.
=> Allow Poll Start From Smart Slides With Active Poll

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
Fixes cursor position when notification bar and banner bar are present.
https://user-images.githubusercontent.com/62393923/199795087-c09b803d-dff9-47ba-bd83-47cff0401ae5.mp4
https://user-images.githubusercontent.com/62393923/199795068-c1a4f870-24f1-45a9-8f04-7be6cf613bf6.mp4
=> fix(whiteboard): take notification bar and banner bar into account when calculating cursor offset

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Adjusts previous slide styles in RTL.
Closes #15951
=> fix: Previous slide button icon inverted in RTL

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
Fixes the `getSibling` function returning the wrong panels and lint issues.
This was causing the cursor positions to be incorrect when in a breakout room with any of the side panels closed.
Before:
After:
=> Fix Panel Used In Breakout Room Cursor Calculation

bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_sip.xml
Removes spurious `bbb_sip.xml` dialplan from FreeSWITCH config.
The `bbb_sip.xml` dialplan is a remnant from the BBB red5 era. Nowadays calls are established exclusively via WebRTC socket (`ws` or `wss`).
Under specific circumstances the `bbb_sip.xml` dialplan will match WebRTC calls (supposed to be handled by `bbb_webrtc.xml`). If that happens, then `jb_use_timestamps` and `include_external_ip` channel vars will not be set in the affected channel (since they aren't set in `bbb_sip.xml`). I've observed this misbehavior on a node running behind a NAT where `nginx` was configured to connect to FreeSWITCH using an RFC1918 address (i.e. private IPv4).
Note: Channel vars of an ongoing call can be examined using `uuid_dump` command in the fs console.
=> fix: Remove spurious FreeSWITCH dialplan bbb_sip.xml

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
On breakout room create meeting API call, lookup the parent meeting,
throw exception if it doesn't exist, and use its internal meeting ID for parentMeetingId if it does
Fixes issue #15696
=> Check parent meeting IDs on create meeting API calls

bigbluebutton-html5/imports/api/audio/client/bridge/service.js, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/service.js, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/services/settings/index.js, bigbluebutton-html5/imports/ui/services/storage/index.js, bigbluebutton-html5/private/config/settings.yml
Persists, on `localStorage`, audio and video setup that the user last selected in order to share it among different sessions.
It uses a new config option as described in https://github.com/bigbluebutton/bigbluebutton/pull/15413 to define which storage BBB will use to store the settings: `localStorage` or `sessionStorage`.
if `userSettingsStorage: session`: the last used devices won't be persisted across meetings. In short, it will work as-is currently.
if `userSettingsStorage: local`: the last used devices will be persisted across meetings. When entering a new meeting, the stored devices will be automatically selected when opening either audio or video modals.
Closes none
Every time users join a session they need to set up their preferred audio and video devices (which don't change …
=> improvement: share audio and video setup among different sessions

bigbluebutton-tests/playwright/api/api.js, bigbluebutton-tests/playwright/api/api.spec.js, bigbluebutton-tests/playwright/core/helpers.js, bigbluebutton-tests/playwright/package-lock.json, bigbluebutton-tests/playwright/package.json
This tests the bug fixed in PR #15652
Creates a new `api` directory `bigbluebutton-tests/playwright` intended for API tests.  Currently only `getMeetings` and `getMeetingInfo` are tested explicitly, though `create` and `join` are also tested because they're used throughout the test suite.
This also creates a new package requirement (xml2js) for the playwright test suite and adds a new helper function to make an API call and obtain its parsed XML response as a JavaScript object.
=> test suite: add API tests for getMeetings/getMeetingInfo

bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/services/mobile-app/index.js, bigbluebutton-html5/imports/utils/browserInfo.js
The screenshare was not working for version 2.6, mainly because of a change in the order of methods called, it broke the mechanism used to detect the type of call in the webRTC library shim.
This pull request also propagates the configuration of STUN/TURN servers, for situations in which the direct connection is not possible.
With this PR, the screenshare works just fine:
PS: to try it, please use the version in TestFlight: https://testflight.apple.com/join/7k0KWvF6
=> (fix:screenshare) fixes screenshare using BigBlueButton-Tablet app

bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
First, this PR reverts https://github.com/bigbluebutton/bigbluebutton/commit/74c4c1c4ccc8f183704121a5747c769a3802bd15 because it causes fake annotations from the text tool not to be removed. Since the text tool is the only one that generates fake annotations(because it is the only one that is live synced), the function to clear fake annotations is directly intended to clear them.
Also this PR fixes 2 issues that are extremelly related:
- **text annotations being stuck as fake**
Cleans up and modifies the added annotation handler to suit only for text annotation. As soon as the `DRAW_END` message is sent, the local fake annotations are removed and replaced by the complete/not fake annotation.
- **right click to cancel annotation not working**
Re-adds cancelling text annotation on right …
=> fix(whiteboard): text annotations stuck as fake and re-adds right click to cancel

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy
Set `bbb-web` `grails-plugin-url-mappings` with the same rules used in nginx `/presentation` location
https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-web/nginx-confs/presentation-slides.nginx
=> refactor (bbb-web): set presentation mapping as it is in nginx

bbb-learning-dashboard/src/components/PollsTable.jsx
Enables sorting for all poll columns in the data grid.
=> Enable Sorting On All Poll Grid Columns

bbb-learning-dashboard/src/components/PollsTable.jsx
Fixes the `valueGetter` failing when results are empty. 
This was causing the poll grid to not render sometimes.
=> Patch valueGetter To Return Correct Value

bbb-learning-dashboard/src/components/PollsTable.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/public/locales/en.json
* Add counter column to poll grid (displays the number of answers given by the corresponding user).
also:
* Set `Tldraw` theme to light on mount.
* Default to correct text justification on mount (no longer start at center - based on RTL direction).
=> feat (learning-dashboard): Adds number of answers of each user to Poll Grid

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Restores per character updates in the sticky notes.
This fixes the text clearing in sticky notes while writing and new shapes are being added or updated.
=> Restore Per Character Updates In Sticky Note

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/test/resources/get-meeting-info.ftlx, bbb-common-web/src/test/resources/get-meetings.ftlx, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meetings.ftlx
When a user leave the meeting:
1.  It waits between 10 and 20 seconds to remove users from the UI Userlist (to prevent from removing users facing connection instability)
2. Once the user was removed from the Userlist, the API wait 1 more minute to remove the user from the memory (waiting for re-connection attempts)
And the API endpoints `getMeetingInfo` and ` getMeetings` considers all users that are in the memory to calc `participantCount`.
It cause a strong delay between the user leave the meeting the the API shows the correct `participantCount`.
https://user-images.githubusercontent.com/5660191/201402154-f3b5ea81-a3a6-41f7-b57d-8527d0a77a62.mp4
This PR removes the delay of the step 2. And count only users that are currently online. It will make the API `participantCount` be synced with …
=> fix: getMeetings returns wrong number of participantCount

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Preserves the state of the local shape being edited during.  
fixes characters being reset while typing
=> Preserve Local Edited Shape State During Memo Updates

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Fixes issue with the copy shortcut not working in the chat area
=> fix: copy shortcut does not work on chat

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Add check to see if patched shape exists before sending data to update.
This fixes a whiteboard crash when a user is typing quickly.
=> Handle Whiteboard Crash When Typing Quickly

bigbluebutton-html5/imports/ui/components/webcam/drop-areas/styles.js
Fixes sidebar content webcam drop area text overflowing when sidebar content is closed.
**Before**
**After**
None
=> fix: text overflow in sidebar drop area

bigbluebutton-config/bin/bbb-conf
The command `bbb-conf --setip` modify the recordings metadata updating the URL to the new host.
It is not being successful when the directory `/var/bigbluebutton/published` is a symlink to another disk.
This PR adds the param `-L` to the command `find` in order to make it follow symbolic links.
Source: https://man7.org/linux/man-pages/man1/find.1.html
Closes #15887
=> fix: bbb-conf --setip command does not follow symlinks

bigbluebutton-html5/imports/ui/components/common/tooltip/bbbtip.css, bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx
This increases the horizontal padding of all tooltips. 
Additionally, it also fixes an issue where the top padding of some tooltips decreases when using fullscreen mode (see examplary screenshots).
Fixed padding (non fullscreen):
Weird padding (fullscreen):
Fixed padding (fullscreeen):
Closes #15979
=> adjust horizontal tooltip padding

bigbluebutton-tests/playwright/README.md, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/package-lock.json, bigbluebutton-tests/playwright/package.json
Allows testsuite users to print browser console logs to playwright's standard output.
You can print the browser console log to standard output by setting the environment variable `CONSOLE`:
```
$ CONSOLE= npm test chat -- --project=firefox
```
`CONSOLE` can be blank (as in the example), or can be a comma-separated list of the following options:
| Option | Meaning |
| ------ | ------- |
| color  | (or "colour") colorize the output |
| label  | label each line with the BigBlueButton user |
| norefs | remove JavaScript reference URLs |
| nots   | remove timestamps |
| nocl   | remove "clientLogger:" strings |
=> Testsuite console log

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Improves the responsiveness of the whiteboard toolbar. Corrects a situation where the toolbars are overlapping on smaller sizes.
=> Improve Whiteboard Toolbar Responsiveness To Element Width

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
This PR fixes the state where the client keeps looking normal after the meeting is already ended, It happens in the cases where the client is disconnected and the meeting is ended before client reconnection
1. Join with two user in different devices at same meeting.
2. In one of the devices disconnects from internet.
3. Ih the another one finish the meeting.
4. Reconnects the internet.
Improve client reconnection.
=> Fix client reconnection after meeting end

bigbluebutton-html5/imports/ui/components/waiting-users/guest-policy/container.jsx
Adjust guest policy container name (reported by sonarcloud alerts).
_React component names must start with an uppercase letter._
=> refactor: adjust guest policy component name

bigbluebutton-html5/imports/ui/components/audio/captions/button/component.jsx, bigbluebutton-html5/imports/ui/components/audio/captions/select/component.jsx
Fix issues with conditional hooks reported by sonarcloud alerts.
_React Hooks must be called in the exact same order in every component render._
_From React documentation:_
_"Always use Hooks at the top level of your React function, before any early returns. By following this rule, you ensure that Hooks are called in the same order each time a component renders. That’s what allows React to correctly preserve the state of Hooks between multiple useState and useEffect calls."_
_React is relying on the order of the Hook calls to know which local state matches which Hook call. That is why it’s important that the Hooks are not called inside loops, conditions, or nested functions._
_Also this rule ensures that the Hooks are called only from React function components or custom Hooks so that the …
=> refactor: conditional hooks

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Just show presentation 3-dot menu and toolbar after Tldraw has been mounted.
**Before**
**After**
https://user-images.githubusercontent.com/62393923/203594461-ad7bc555-c868-4c85-8f8d-0cdc1649f509.mp4
Closes none
=> fix(presentation): 3-dot menu and toolbar

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Removes postcss and related dependencies.
postcss is no longer used in BBB 2.6
=> chore: remove postcss

record-and-playback/core/lib/recordandplayback/edl/video.rb
Because the input videos for BigBlueButton recording processing switch resolution and aspect ratio, the filter chain gets re-initialized, and any state in the filters is lost. This causes problems with the following filters.
The end result of all of these issues is that a lot of duplicate frames were created with invalid timestamps, which eventually get discarded by ffmpeg. But a lot of time is wasted, causing recordings to sometimes take hours to process when they should be ready in minutes.
This is a backport of #16047 to BigBlueButton 2.5, see that PR for details on the problem and fix.
Fixes #16044
=> Recording: Don't use stateful filters in ffmpeg video processing (2.5 backport)

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx
Prioritizes the user name from the `Users` collection for the talking indicator tooltip, otherwise it uses the one from the `VoiceUsers` collection.
Closes #16058
=> fix: Speaking person tooltip has wrong encoding

bigbluebutton-web/gradle.properties
Bumps up tomcat-embedded version as a first step in progress to major version upgrade
#16102
=> chore: upgrade tomcat to 9.0.70

bigbluebutton-html5/imports/ui/components/video-preview/styles.js
Adjusts video preview modal max-height in (small) desktop devices.
Closes #16080
=> style: increase video modal max-height 

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
Fix selectedTab check in connection-status modal (selectTab is an integer, and would always be false if checked against a string).
=> fix: string in selectedTab comparison - connection status modal

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Adjusts breakout room creation boxes so they all have the same height (enough to display ~10 items without scrolling)
Closes #15944
=> style: increase breakout room box size

bigbluebutton-web/gradle.properties
Bumps up tomcat-embedded version as a first step in progress to major version upgrade
#16102
=> chore: upgrade tomcat to 9.0.70 on branch 2.5

bigbluebutton-html5/client/collection-mirror-initializer.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/imports/ui/services/LocalCollectionSynchronizer/LocalCollectionSynchronizer.js
- [fix: guarantee cleanup of stale data on re-subscriptions](https://github.com/bigbluebutton/bigbluebutton/commit/401ddc401424a1e6775752800940baf8a0af3a92)
* Currently, collection cleanup code is only run when an added event is received from the server. Where that fails is in scenarios where a server-side collection turns empty while an affected users is disconnected - and then reconnects. There's no removed (or updated) event so no cleanup code is run and you have stale data.
* This commit guarantees a stale data check is run whenever a subscription is established again. The `added` check was also maintained, although I'm not too sure it's still needed. That may need to be revisited.
Part of https://github.com/bigbluebutton/bigbluebutton/issues/15829
Part of …
=> fix: guarantee cleanup of stale data on re-subscriptions

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx
Prevents client crash due to unavailable data by adding early return in VideoListItemContainer if user data is unavailable.
=> fix: do not render video list item if user data is unavailable

bbb-export-annotations/config/index.js, bbb-export-annotations/config/settings.json, bbb-export-annotations/package.json, bbb-export-annotations/workers/notifier.js
In cluster proxy setup as described in https://docs.bigbluebutton.org/admin/clusterproxy.html you cannot assume that the BBB Web API URL is at the same domain as the html5 client. Therefore operators need to adjust the URL where presentation download is available.
This patch adds the ability to override the config provided by the package and adds a setting for the BBB Web API public URI. As the `bbb-export-annotations.service` constructs the URI for downloading the annotations, it has to know the public API URI
Belongs to #14484
=> fix(export-presentation): Fix slides export for cluster setup

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Disabling copy-paste of files, as we currently don't support the propagation of copy-pasted images on the whiteboard.
Closes #16059
=> Disable paste file in whiteboard

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java
It adds trim to name parameter to improve the string sanitising in bbb-web
Having white-spaces in front of name used to mess up the list sorting 
Related: https://github.com/bigbluebutton/bigbluebutton/pull/16127
=> fix: Add trim to name parameter

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Hides the hint explaining about presentation with annotations exporting when the feature is disabled.
before:
after:
Closes #none
The label is out of place if the feature is not enabled for the meeting
- To test this simply pass `disabledFeatures=downloadPresentationWithAnnotations` in API MATE vs not passing it in a different meeting
=> fix: hide export presentation hint if feature is disabled

transifex.yml
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/16186 to BBB 2.5
=> chore: add transifex.yml for GitHub<->Transifex integration

freeswitch.placeholder.sh
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/15925 to BBB 2.5
=> chore: Upgrade FreeSWITCH to v1.10.8

bigbluebutton-html5/imports/ui/components/captions/live/component.jsx
Removes the `aria-live` and `aria-atomic` props
Functional accessibility issue: If a screen reader user enables the closed captions (which is highly unlikely for a screen reader user to choose to do, as a screen reader user could hear a cacophony of both the person speaking the words in the meeting, as well as the screen reader announcing the captions of those same words shortly thereafter. Perhaps an admin would want to check if these captions are working) Additionally, the closed captioning contains an aria-atomic="true" attribute, causing the presented captions to be announced in full upon every presented change, and thus announcing a given caption snippet often more than once (e.g., You could hear the screen reader announce “Welcome to the… Welcome to the meeting everyone… Welcome to …
=> fix: Remove Aria Live From Captions

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- [feat(bbb-web): make HTTP session timeout configurable](https://github.com/bigbluebutton/bigbluebutton/commit/0a796ef39d1e1c01913e82fd27f5ca59636c35c6)
* This commit makes bbb-web's HTTP session timeout configurable, system-wide, via
bigbluebutton.properties. Default timeout (4h) is preserved.
None
Java/Grails' HTTP session inactivity timeout is hardcoded to 4 hours.
This gives less flexibility for long-lived sessions - ie in rare
scenarios where users stay connected for >= that amount of time without
any re-connections or intermediate calls to checkAuthorization.
Ideally, we should look into a more permanent solution to avoid
invalidating perfectly healthy user sessions. This commit fixes
nothing in that regard.
=> feat(bbb-web): make HTTP session timeout configurable

bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/converters/messages/CreateMeetingMessage.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
Renames `uploadExternalUrl` and `uploadExternalDescription` parameters to `presentationUploadExternalUrl` and `presentationUploadExternalDescription`
It might not be clear that the parameters are related to presentation.
https://github.com/bigbluebutton/bigbluebutton/pull/15251
=> refactor: rename external upload parameters

build/packages-template/bbb-etherpad/settings.json
Removes "Import" from the text presented to users when hovering over or pressing the shared notes export button.
Closes #15802
Closes #7054
"Import" was being presented as an option to users even though the notes are restricted to export only.
- Backporting this to 2.5 should be possible, but I did not try this.
- An alternative way to fix this is via Etherpad's `ep_bigbluebutton_patches` plugin, in which locales set there can override those in the main meeting. However, the API has a bug preventing this approach as I reported [here](https://github.com/ether/etherpad-lite/issues/5628). Once BBB starts using an Etherpad version with the fix, we can consider moving to individual language files instead of listing the locales in the JSON.
=> fix(locale): Remove 'Import' as option from shared notes UI

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationWithAnnotationsMsgHdlr.scala, bbb-export-annotations/lib/utils/logger.js, bbb-export-annotations/lib/utils/message-builder.js, bbb-export-annotations/package-lock.json, bbb-export-annotations/workers/collector.js, bbb-export-annotations/workers/notifier.js, bbb-export-annotations/workers/process.js
A change in how poll shape ids are stored in the client made them unusable in the annotation export due to the presence of path characters. This PR sanitizes incoming ids to display polling results in the generated PDF again.
Closes #16151
Having all annotations in the exported PDF.
Refactors how progress messages are sent back to the client to lay the groundwork necessary to inform instructors of e.g. breakout rooms without content.
=> fix(export-annotations): Display poll results

.github/workflows/check-merge-conflict.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/bigbluebutton/bigbluebutton/actions/runs/3169919638/jobs/5162154087#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflow:
- check-merge-conflict.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-t …
=> ci: add minimum GitHub token permissions for workflow

bigbluebutton-config/bin/apply-lib.sh, bigbluebutton-config/bin/bbb-conf
`bbb-conf` now uses `systemctl restart bigbluebutton.target` for a more deterministic restart.
Also adds a firewall entry for 3478 if local turn server is detected (experimental)
Closes #16304
=> Fix bbb-conf restart

bigbluebutton-html5/imports/api/audio/client/bridge/FullAudioBridge.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- [fix(webcam): client intermittently crashes when sharing camera](https://github.com/bigbluebutton/bigbluebutton/commit/f74c7d4d0ad0e937e647748de6250230c0bd55b0) 
* Under some specific scenarios, the virtual background restore code might
kick in _before_ the preloaded MediaStream is actually assigned to the
peer instance. That causes a crash because the peer attachment code
(where the vbg restore is triggered) tries to access the device ID of
said MediaStream - and it is undefined in the first place because it was
only being set in after the initial offer is generated which is an async
procedure.
- [fix(webcam): client crash due to undefined intl var](https://github.com/bigbluebutton/bigbluebutton/commit/32734586fbae5ad2e088399d67f2907383eb04f5)
- [fix(audio): check for session …
=> fix(webcam): intermittent client crashes when sharing camera (2.5)

.gitlab-ci.yml
renames gitlab ci job bbb-learning-dashboard to bbb-learning-dashboard-build, so it's consistent with the others.
this fixes my tooling
=> build: consistent naming of gitlab ci jobs

bigbluebutton-web/build.gradle
Bumping the version of `bbb-common-message` required for `bigbluebutton-web`.
Closes #
I missed this in https://github.com/bigbluebutton/bigbluebutton/pull/16185 and is only showing up now that https://github.com/bigbluebutton/bigbluebutton/pull/15679 was also included. Without the change from this current PR, development environments (or any env which had .21-SNAPSHOT cached) would not allow bbb-web <-> akka-apps interoperability.
=> fix: Bump bbb-common-message version #16185

bigbluebutton-html5/public/locales/en.json
Change the shortcut name "Zoom to Fit" to "Reset Zoom"
Closes #
In my personal opinion, "reset zoom" is easier to understand.
=> (Short cut) Zoom to Fit -> Reset Zoom

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
Proposing a different way of short cut key expression.
Closes #
We developers know up-arrow means the shift key, but ordinary people may not. It may be mixed up with the actual arrow key. 
Also, key combo expression is a bit confusing; in one place "Ctrl A" but in another "Shift + V". It would be more comfortable without "+" (there is "Ctrl Shift U", which could be too long with "+", and there is also "Ctrl +" for zooming in). In the worst case, people may try to push the "+" button as well.
Whether we include "+" or not may be related to the UI design. In the general shortcut everything includes "+", which I don't touch for now.
=> Shortcut expression (replace up-arrow with Shift and omit +)

bbb-libreoffice/docker/Dockerfile
Backporting https://github.com/bigbluebutton/bigbluebutton/pull/15743 to BBB 2.5
(due to the deprecation notice, see #15743 for more info)
=> refactor (bbb-soffice): Switch parent image to amazoncorretto:17-alpine (backport)

bigbluebutton-tests/playwright/README.md, bigbluebutton-tests/playwright/package.json
This npm script will ssh to a BigBlueButton server, obtain its URL and SECRET, then run the test suite using these settings.
This reduces the complexity of running tests (no need to set environment variables) if you have ssh access to the server.
The shell script is a bit obscure, and comments are not allowed in JSON.
The "set -e" switch is used to exit the script if the ssh fails, but this only works if the ssh is not part of a pipeline, which is why it is assigned to a separate variable. (see https://unix.stackexchange.com/a/23099/37949)
=> test: Add `npm run test:ssh` command to test suite

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
Adds the `active` context to the currently selected presentation in the actions dropdown menu for screen readers.
Before:
`default.pdf uploaded presentation file  1 of 8`
`DifferentSizes.pdf uploaded presentation file 2 of 8`
After:
`default.pdf uploaded presentation file  1 of 8`
`DifferentSizes.pdf uploaded presentation file - Active  2 of 8`
The currently selected presentation fails to indicate that it is active to screen reader users
=> fix: Add Active Status to Presentation Menu Item for SR

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/utils.js, bigbluebutton-html5/imports/utils/fetchStunTurnServers.js, bigbluebutton-html5/private/config/settings.yml
TURN credentials were cached forever. However they expire. So refresh them when required.
Force Firefox to use a turn server if there is one configured. Get rid of `public.kurento.forceRelayOnFirefox` configuration option
closes #16171
closes #16164 
* BBB should not stop working when users have long running sessions.
* BBB should work in all supported browsers, no matter how weird network conditions are
=> fix: Only cache TURN Servers as long as credentials are valid and force firefox to use the turn server

bbb-common-web/build.sbt, bigbluebutton-web/build.gradle, bigbluebutton-web/gradle.properties, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/services/org/bigbluebutton/web/services/PresentationService.groovy, bigbluebutton-web/run-prod.sh
Backport to BBB 2.5 of https://github.com/bigbluebutton/bigbluebutton/pull/15467
Backport to BBB 2.5 of https://github.com/bigbluebutton/bigbluebutton/pull/15771
Backport to BBB 2.5 of https://github.com/bigbluebutton/bigbluebutton/pull/15782
```
Upgrade org.grails:grails-core@5.0.1 to fix
✗ Improper Handling of Case Sensitivity [Low Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2689634] in org.springframework:spring-context@5.3.12
introduced by org.grails:grails-core@5.0.1 > org.springframework:spring-context@5.3.12 and 8 other path(s)
✗ Denial of Service (DoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-2434828] in org.springframework:spring-expression@5.3.12
introduced by org.grails:grails-core@5.0.1 > …
```
=> fix: Upgrade spring to 2.7.x (backport)

bigbluebutton-tests/playwright/api/api.js, bigbluebutton-tests/playwright/api/api.spec.js, bigbluebutton-tests/playwright/api/breakout.js
Adds some breakout room tests to the API tests:
- test failure if creating breakout rooms without parent or invalid parent (tests [Issue 15696](https://github.com/bigbluebutton/bigbluebutton/issues/15696))
- test failure if creating breakout rooms without sequence number
- test proper getMeetingInfo for simple breakout room created from HTML5 client
=> testsuite: Initial breakout room tests

bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Fixes the poll annotation in the whiteboard to be consistent to the chat message and also live result, grouping the answers case insensitive
=> fix(whiteboard): group answers case insensitive in the poll text

bigbluebutton-web/grails-app/conf/spring/resources.xml
Corrects the lines that were not back-ported properly in https://github.com/bigbluebutton/bigbluebutton/pull/16388
The names of variables in that place need to match names in `bigbluebutton.properties` file
=> fix: Correct the back-port of Spring

bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
It moves setting the default value from xml file to bigbluebutton.properties
The change we are doing is including these properties + the default value in bigbluebutton.properties so that they can be overriden in `/etc/bigbluebutton/bbb-web.properties
Closes #16416
During the upgraded version of Spring two properties were affected:
`learningDashboardEnabled` and `breakoutRoomsEnabled` https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/bigbluebutton-web/grails-app/conf/spring/resources.xml#L156
=> fix: (bbb-web) Set default value for learningDashboardEnabled and breakoutRoomsEnabled in bigbluebutton.properties instead

bigbluebutton-html5/.gitignore, bigbluebutton-html5/package.json, build/packages-template/bbb-html5/bbb-html5.nginx
Fixes issue with tldraw fonts not working [with Meteor.js] after https://github.com/tldraw/tldraw/pull/1091, by making a copy of the files to `public/files` directory.
Closes #16424
Closes #15886
https://forums.meteor.com/t/anybody-successful-with-fontsource/57524
=> fix: Tl;draw fonts not found

bigbluebutton-html5/imports/ui/services/settings/index.js, bigbluebutton-html5/private/config/settings.yml
It adds a config option to configure the HTML5 client settings storage. 
The default value is same behaviour as without this patch.
When BBB is run as a single node or in a scaleout setup with a cluster
proxy in front (see https://docs.bigbluebutton.org/admin/clusterproxy.html) it
is useful to store client settings in browser `localStorage` instead of
`sessionStorage`. If `localStorage` is configured then the client will keep seetings
like notifications for user joining, chat etc across meetings.
It is not advisable to set the setting to `local` in a setup of multiple BBB
nodes without a cluster proxy in front of it because this would lead to
unexpected behaviour at users. The browser would store settings for each server
and for users it would look like BBB is sometimes store the settings …
=> feat: Add config option for HTML5 settings storage

record-and-playback/core/lib/recordandplayback/edl/video.rb
In cases of extremely short (single frame) input videos, the fps filter can sometimes generate 0-frame output videos, resulting in the tpad filter having no input (this breaks it, causing a busy loop).
Move the tpad filter to before the fps filter to solve this problem. This isn't perfect, since the tpad filter doesn't work well on variable- framerate video (it generates extremely high framerate video with a lot of frames that will be discarded), but this only happens between the tpad and fps filters, and only at the end of an input video (usually right before a cut) so this seems acceptable.
Since the tpad and fps filter are in the same process, these duplicate frames don't actually require copying any data (the frame is reference-counted), and still process reasonably quickly.
Fixes …
=> Recording: move tpad ffmpeg filter before fps

record-and-playback/core/lib/recordandplayback/edl/video.rb
In cases of extremely short (single frame) input videos, the fps filter can sometimes generate 0-frame output videos, resulting in the tpad filter having no input (this breaks it, causing a busy loop).
Move the tpad filter to before the fps filter to solve this problem. This isn't perfect, since the tpad filter doesn't work well on variable- framerate video (it generates extremely high framerate video with a lot of frames that will be discarded), but this only happens between the tpad and fps filters, and only at the end of an input video (usually right before a cut) so this seems acceptable.
Since the tpad and fps filter are in the same process, these duplicate frames don't actually require copying any data (the frame is reference-counted), and still process reasonably quickly.
Backport …
=> Recording: move tpad ffmpeg filter before fps (2.5 backport)

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
Fix incorrect content being displayed in connection status modal tabs.
Closes #16440
=> fix: Connection status tabs confusion

build/packages-template/bbb-html5/build.sh
Cont'd from https://github.com/bigbluebutton/bigbluebutton/pull/16443
Removes the "public" directory created for the fonts.
Closes # none
Looks like `public` was only needed for development environments to fit into Meteor's structure. On production nodejs app all other files are outside of `public`
=> build: copy tldraw fonts to be served in files/

bigbluebutton-html5/client/main.html
Adjust `main` element style so "meeting ended" message appears in the middle of the page.
=> fix: main element styles

bigbluebutton-config/bin/bbb-conf
reverts a78248331ce914c5cf358126f20593b7c56eb7f2
This is a different take on https://github.com/bigbluebutton/bigbluebutton/pull/16347 and partially reverting it.
After #16347 we were no longer running `start_bigbluebutton()` https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf#L355-L398 aside from `--clean`.
As a result `nginx` configs were not reloaded and possibly Mongo was not starting correctly in rare cases (although this is hypothetical).
This pull request also likely cancels out https://github.com/bigbluebutton/bbb-install/pull/586
Closes # none
Reports that nginx needed to be explicitly reloaded on freshly installed systems of BBB 2.6.0-beta.5 that do not utilize `bbb-install-2.6.sh`
=> fix(bbb-conf): ensure BBB target restarts (retake)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
Displays Tldraw tool cursors:
https://user-images.githubusercontent.com/62393923/211910857-3f38104c-ef15-46da-9c0e-e5a608320363.mp4
Closes #16130
n/a
Note:
1. Currently BBB has neither custom `png`'s nor `svg`'s for the _select_, _erase_ and _arrow_ tools, so those will keep being `none`.
2. Both Rectangle and Sticky will have the same cursor (not good, but it's a way to go until we have a custom svg for the sticky cursor).
=> fix(tldraw): show tool cursors

build/packages-template/bbb-web/opts-focal.sh
It configures the `file` command as a dependency of `bbb-web`, otherwise it will fail to process and convert whatever presentation the user tries to upload.
Closes #16363
=> build(bbb-web): Added 'file' as a dependency necessary to process presentation

bigbluebutton-html5/imports/ui/components/audio/captions/select/component.jsx, bigbluebutton-html5/public/locales/en.json
It simply changes the message that appear in the microphone activation toast when the live transcription is not enabled. Instead of saying that the browser doesn't support the feature, it now says that this feature is not enabled for the meeting or for the server.
Closes #16375 
This PR is slightly related to #16170, so in order to test, feel free to play around with the possibilities explained in it.
=> fix: Omit liveTranscription message if it is not enabled
