bigbluebutton/bigbluebutton

akka-bbb-apps/project/Dependencies.scala, bbb-recording-imex/pom.xml
This PR upgrades `logback-classic` to the last 1.2.x version available which is `1.2.11`. 
Versions available: https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
Projects impacted: `akka-bbb-apps` and `bbb-recording-imex`.
Motivation:
`bbb-recording-imex` project is using a version that contains known vulnerabilities.
https://security.snyk.io/package/maven/ch.qos.logback:logback-core/1.2.3
Closes #16446 once it will become behind.
=> fix(sec): Upgrade ch.qos.logback to 1.2.11

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fix issue with breakout slides not appearing correctly in main room.
Closes #16489
=> fix(whiteboard): Presentation showing wrong slide (when capturing whiteboard from breakout room)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/private/config/settings.yml
Add config option for setting the default font family for the text tool.
Partially addresses #15964.
=> feat(whiteboard): configurable text tool font family

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/notes/component.jsx, bigbluebutton-html5/imports/ui/components/notes/container.jsx, bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx, bigbluebutton-html5/imports/ui/components/sidebar-content/container.jsx, bigbluebutton-html5/private/config/settings.yml
Add a delay to truely unmount the shared notes, when the shared notes is unmounted the connection with the etherpad is closed ans takes a few second to reconnect, delaying it we hold the connection when the user is navigating through other panels (chat, poll and etc)
Remove the speed bump though the navigation to another panels.
2.6
https://user-images.githubusercontent.com/15806883/204860716-4289a01c-4cc8-48d0-9530-9958892a16db.mp4
PR:
https://user-images.githubusercontent.com/15806883/204860813-ac7e12ff-8780-4eec-926b-221ec0ed3db0.mp4
=> fix: add delay for shared note true unmount

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Adds  a check for slidePosition before using it
Closes #16508
Looks like we were using `slidePosition.viewBoxWidth` and `slidePosition.viewBoxHeight` without checking if `slidePosition` exists. I added checks where they were missing (most uses were pre-checked).
=> fix: check for slidePosition before using it

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Properly completes a draw session when clicking outside of the viewport.
Closes #16479
=> fix(whiteboard): complete draw session when clicking outside of viewport

bbb-common-web/build.sbt
It removes the dependencies that were backported from 2.6 to 2.5, but aren't necessary in 2.5.
(Introduced in https://github.com/bigbluebutton/bigbluebutton/pull/16397/files )
An error that was occurring because of it:
`ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Exception during pool initialization.`
=> Refactor: removing dependencies that aren't necessary to back-port

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fallback different `es` locales to the one compatible with tldraw.
Refactored the code a bit.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/16507
We have different es locales ('es', 'es-es', 'es-419', 'es-mx'), while tldraw only has 'es'. Fallback the other ones so tldraw shows 'es' in all cases.
=> fix(tldraw): fallback es-xx locales to es

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx, bigbluebutton-html5/private/config/settings.yml
It creates 3 new configurations to start the checkbox, as specified, when mounting the modal for creation of breakout rooms.
Those are (settings.yml):  
```
breakouts:
startWithAllowUserToChooseABreakout: false
startWithCaptureWhiteboardForBreakout: false
startWithCaptureSharedNotesForBreakout: false
```
PS.: If you guys want the names to change, just say so.
Closes #16141
=> feat(config): Default values for checkbox in breakout rooms modal

bbb-learning-dashboard/src/components/UserDetails/component.jsx
This PR improves the semantics of the visual tables in the learning dashboard user details.
Converts the div structure to a table. Also adds visual headings to the heading order.
Content presented visually as a data table is not coded semantically as a table
Recommendation: Use a `<table>` and `<th>` and `<td>` elements to display the content, thus allowing proper interpretation and navigation for screen reader users.
---------------
The user details modal contains visible headings that are not part of the page’s heading order.
Recommendation: Add the headings to the page’s heading order.
=> Update Learning Dashboard User Details Semantics

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/XmlService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/RecordingServiceDbImpl.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/RecordingServiceFileImpl.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/XmlServiceImpl.java, bbb-recording-imex/get-recordings.sh, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/RecordingController.groovy
Modifies the pagination in getRecordings requests to use limit/offset based pagination instead of page/size style pagination.
This results in the following changes:
1.  Support for page/size parameters in getRecordings requests has been removed.
2.  Support for offset/limit parameters has been added.
- offset: The index of the first recording to return. Must be greater than or equal to 0
- limit: The maximum number of recordings to return. Must be between 1 and 100.
- If only the limit parameter is provided a default offset value of 0 will be used.
- If the offset and limit parameters are not provided then the response will not be paginated.
3. If no IDs and no limit parameters are provided in the request (i.e. the request seeks to return every recording in a single response)  then no …
=> refactor(api): Recording pagination changes

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Adding another way of disabling copy-paste of images in the whiteboard, as the current one only works if the whiteboard is focused.
=> fix: Disable paste file in whiteboard

bigbluebutton-web/build.gradle
Upgrade grails databinding to version 5.2.4
A vulnerability was introduced in grails plugin rest, but it is resolved in grails databinding 5.2.1, yet we upgrade to 5.2.4 to match the current version of grails
=> Refactor: upgrade databinding to 5.2.4

bigbluebutton-web/bbb-web.nginx, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
It removes quirks from bbb-web nginx config and uses grails config options to properly support CORS requests. CORS requests are only required if you run a cluster proxy setup as described in https://docs.bigbluebutton.org/admin/clusterproxy.html
Closes #15436 
Grails can handle CORS on its own. It just has to be configured in
`/etc/bigbluebutton/bbb-web.properties`:
~~~
grails.cors.enabled=true
grails.cors.allowedOrigins=https://bbb-proxy.example.com
grails.cors.allowCredentials=true
~~~
This is a breaking change of the nginx config if (and only if) you run a
cluster setup as described in
https://docs.bigbluebutton.org/admin/clusterproxy.html
**If** you run such a setup, you **need** to change
`/etc/bigbluebutton/bbb-web.properties`. Otherwise users won't be able
to join meetings, upload …
=> Fix: use grails configuration for CORS settings

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx
Restores setPresentationIsOpen in presentation component.
Closes #16464
=> fix: setPresentationIsOpen is undefined

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR orders the id's of the shapes to be deleted, making sure the shapes of type group are removed last.
Prevents the following parent id crash when deleting grouped shapes with the eraser.
=> fix(whiteboard): Prevent Parent Id Crash when Erasing Grouped Shapes

bigbluebutton-html5/imports/ui/components/audio/local-echo/service.js, bigbluebutton-html5/private/config/settings.yml
Adds delay to the loopback audio test.
If BBB 2.6 is used without headphones, the audio test works differently than in 2.5. In 2.5 audio traffic is routed to freeswitch and then returned to the browser. This adds usually some latency which makes it easy to hear you audio quality. In 2.6 there is a local loopback. As there is almost no latency, it is either difficult or even impossible to check your own audio quality as echo cancellation of the browser will filter out your own signal.
This patch adds a delay node to the audio loopback test, which makes is easier to check your quality.
As this is my first change on media related stuf and I do not completely understand what is going on, someone with deeper insight should double check that. Ping @prlanzarin 
I tested this on Firefox and …
=> fix(audio): add delay for loopback test

bigbluebutton-web/build.gradle
Upgrades version of org.yaml:snakeyaml from 1.28 to 1.31
https://www.cve.org/CVERecord?id=CVE-2022-38751
=> fix(sec): upgrade org.yaml:snakeyaml 1.31

bigbluebutton-web/build.gradle
Carry forward fixes from BBB 2.5 to 2.6
In this case only https://github.com/bigbluebutton/bigbluebutton/pull/16526 is relevant
=> chore: Merge BBB 2.5 into 2.6

bigbluebutton-html5/imports/ui/components/notes/component.jsx
Fixes the bug where the shared notes were appearing when open the breakouts room panel, it was introduced in the PR #16072, were was cached the connection for etherpad, looks the state was not applying the display none for when the element is hide
#16541
=> Fix: note appearing instead of breakout room panel

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Adjusts whiteboard draw position after resize.
Closes #16389
=> fix(whiteboard): Incorrect pen position after column resize

build/packages-template/bbb-html5/bbb-html5-backend@.service, build/packages-template/bbb-html5/bbb-html5-frontend@.service, build/packages-template/bbb-webrtc-sfu/bbb-webrtc-sfu.service
- [build: use FIFO scheduler in bbb-webrtc-sfu](https://github.com/bigbluebutton/bigbluebutton/commit/ef7b1fb3e5d59a32266aea67d471ea0e5f499b3a)
* This commit puts bbb-webrtc-sfu in the FIFO scheduling policy (same as
bbb-html5). Also bumps bbb-html5 nice level up to 18 and sets SFU to
nice 19 (so bbb-html5 has some advantage when push comes to shove).
Closes #
bbb-webrtc-sfu (and mediasoup) are running in the CFS scheduler which
means it has to compete with (much) lower priority tasks like
presentation conversion, recording processing, [...]
Since it encompasses an RTC application which also handles audio, it
should be _at least_ on the same scheduling policy as FS/bbb-html5 - and
that should be safer now with mediasoup which has a lower footprint
(and generates lower CPU noise overall). …
=> build: use FIFO scheduler in bbb-webrtc-sfu

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
It fixes error that happened when creating a meeting with meetingID not trimmed.
When this happens, it is not possible to enter a meeting, nor ending it.
Comment https://github.com/bigbluebutton/bigbluebutton/pull/16144#pullrequestreview-1219919588
I would like to raise a discussion here about the way parameters are being treated in back-end.
So, apparently, this error was just happening, because after the validation of the parameters https://github.com/bigbluebutton/bigbluebutton/blob/775dfd05af2fe5ba930988e46578af8c51b11d6b/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L117 the code still saves the meetingID not sanitized, and because of that, for some reason, when the comparison is made in the join endpoint, the controller doesn't find …
=> fix: Fix error when meetingID is not trimed. 

bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/public/locales/en.json
Moves the visible accessibility warning label on the presentation download links in the chat to an `aria` tag / tooltip.
Closes #16554
=> Move Visible Accessibility Warning Note To Aria Tag / Tooltip

bbb-learning-dashboard/src/components/StatusTable.jsx
This allows screen readers access to the actions on the timeline. 
Some actions within the timeline view are not announced to screen reader users (e.g.,  “Raise hand”)
=> fix(access): Make Timeline Actions Visible to Screen Reader

bigbluebutton-html5/imports/api/slides/server/methods/zoomSlide.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Uses 100% as default fallback for the whiteboard zoom level calculation should it reach 0 or infinity.
Closes #16544
Closes #16515
Increase whiteboard resilience by preventing issues arising from divisions by zero and NaN values.
=> fix(whiteboard): Prevent infinite zoom levels

bigbluebutton-html5/imports/ui/components/common/modal/service.js
Adds execution of Meteor tracker change function on creation of the modal component
Closes #16474
Previously this functionality was done via 
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/audio/container.jsx#L176
However, it would stop working in case that line was not to be executed because of audio modal being turned off, which resulted in app crash;
=> fix: modal initialisation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fix viewport width/height calc after tldraw update
Closes #16587 
Tldraw fixed the width/height mismatch bug in the latest version: https://github.com/tldraw/tldraw/pull/1104
=> fix(whiteboard): update viewport variables after update

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/styles.js, bigbluebutton-html5/imports/utils/browserInfo.js
Fixes poll annotation color when Chrome's dark mode flag is enabled.
**Before**
**After**
Closes #13444
=> fix: Poll question on slide not visible when Chrome's dark mode flag is enabled

bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
This ensures that yes / no polls initiated via smart slides displays the question and options for the cases described in the issue below.
Closes #16013
=> Prevent Yes/No Quick Poll Without Options or Question

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
Changes the point at which  a `RegistedUser` has their guest status set to `ALLOW` to be the same as the corresponding `User` and `UserSession` instances.
Closes #14582
Currently when a user is approved to enter a meeting by a moderator their guest status is set to ALLOW in the `User` and `UserSession` related to them, but the corresponding `RegisteredUser` instance does not have its guest status updated until after the `enter` API endpoint has been called and the user has fully entered the meeting. This discrepancy can lead to situation where users that join slowly may be purged by the `WaitingGuestCleanup` service. If this occurs the user will be stuck in an infinite loop trying to authenticate which will always fail since they are no longer registered in the meeting. By updating the …
=> fix (bbb-web): users stuck in waiting room (purging waiting guests)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Adds `maxNumberOfAnnotations` in `settings.yml`  to limit the number of annotations per slide (default: 100).
Closes #16552
=> Implement cap for max number of annotations per slide

bigbluebutton-html5/imports/ui/components/presentation/service.js
Makes quick poll regex only match when a space comes after `)` or `.`
After the changes, it should work for `a) text` and `b. text`, but not for `c.text` or `d)text`
Reducing the number of wrong matches.
=> fix(poll): improve quick poll regex

bbb-common-web/docker-compose.yml, bbb-common-web/hibernate-cfg.sh, bbb-common-web/src/main/java/db/migration/V1__Initial_create.sql
Removes the explicit database creation in the Postgres startup script and adds permanent volume to the Postgres container to ensure that data is not lost of the container is deleted.
The Postgres docker container would fail to startup after being initially created because it would fail to run the initialization script due to the database already existing. In addition, when the container was deleted any information in that container would be disconnected from future instances of the container due to there not being an explicit Postgres data volume to store the information in.
=> refactor(imex): Docker Compose Postgres Improvements

bigbluebutton-html5/imports/ui/components/presentation/service.js
Improves the poll regex so it does not detect parts of words as poll options. 
Prevents slide content like `à mettre en garde contre sa dangerosité sociale.`  being detected as a poll option `e.`
There are cases where smart slides may not detect a response poll due to invalid detection of poll options.  
A slide with the following text should display a response poll in smart slides.
```
This is a test sentence.  more text.
Can you find these words in the paragraphs? 
```
Another improvement on https://github.com/bigbluebutton/bigbluebutton/pull/16622
=> fix(poll): Improve Poll Regular Expression

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/styles.js
Adds css parameters to invert presentation background color when in dark mode.
Ensures the background is white.
Bypasses svg images.
Closes #16605 
Closes #16625
=> fix(presentation): dark mode

bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
This is a port of #16609 and #15935 from 2.6 to 2.5.
_- Display single yes/no poll option for the given example. No longer also presents the typed response._
_- This ensures that yes / no polls initiated via smart slides displays the question and options for the cases described in the issue below._
=> fix: Prevent Yes/No Quick Poll Without Options or Question (2.5)

akka-bbb-apps/project/Dependencies.scala, bbb-common-message/project/Dependencies.scala, bbb-common-web/project/Dependencies.scala
Backport to BBB 2.5 of #16567 and #16491
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038424
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244
=> fix(sec): bump jackson to 2.13.5; logback to 1.2.11 (backport)

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx
Adds aria label to the squeezed webcam options button. This provides more context to screen readers so they know which user options they have focused.
Closes #16048
=> Add Aria Label to Webcam Options Button

bigbluebutton-html5/imports/ui/components/app/component.jsx
Adds extra check to prevent executing dark mode's enable method when already enabled and the same to disable.
This should have some impact over performance(lighter), because the call to the `enable` method of the dark mode API is inside the `componentDidUpdate` function in the `App` component. It means that every time the App was updated, a call to enable the dark mode was executed regardless of its state.
Also logs when dark mode is enabled and disabled.
=> fix(dark mode): consecutive enables

bigbluebutton-html5/private/config/settings.yml
Increase default value for `maxNumberOfAnnotations` from 100 to 300.
Current default is too low.
#16624
=> chore: increase default value for max number of annotations per slide

bigbluebutton-config/cron.daily/bigbluebutton
It just cleans unused docker images on a daily basis. By doing that, it removes folders with plenty of data inside `/var/lib/docker/overlay2` directory
Closes #16381
=> fix(bbb-conf): Crontab New routine to remove unused docker images

bigbluebutton-html5/imports/ui/components/app/styles.js
Adds a new style that tells darkReader lib to invert the logo image colors.
=> fix(dark mode): logo colors inversion

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Add icons to the presentation menu items for a better accessibility.
The current menu items show just texts, which take a while to understand for some locales (such as Japanese) and for some people due to the their lengths.
For the snapshot, the video icon may not be the best one. It should be changed if somebody designs a camera icon. But for now it's good enough.
=> [2.6.0] Add icons to presentation menu

bigbluebutton-html5/imports/ui/components/app/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/styled-components/general.js
- adjusts presentation menu buttons so they all have the same size and position
- removes border from presentation menu and whiteboard toolbar buttons in dark mode
[Screencast from 2023-02-10 10-34-12.webm](https://user-images.githubusercontent.com/3728706/218105756-b9698762-9275-4f7f-8fdd-b19937f4b7ba.webm)
[Screencast from 2023-02-10 10-35-14.webm](https://user-images.githubusercontent.com/3728706/218105721-f8cff7b7-6f7e-4d63-b338-7a15597d62cf.webm)
[Screencast from 2023-02-10 10-34-37.webm](https://user-images.githubusercontent.com/3728706/218105738-c24f5584-6ff6-40e0-934d-2cc2d1b2c403.webm)
[Screencast from 2023-02-10 10-34-57.webm](https://user-images.githubusercontent.com/3728706/218105727-b8741849-2bcc-4eb0-8e5d-f0031a9da099.webm)
=> style: adjust presentation menu buttons

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GetChecksumValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/PostChecksumValidator.java
Modifies the checksum validation done by bbb-common-web to be case insensitive.
Closes #11561
Two checksums containing the same characters, but with different character cases, are considered to have the same value and therefore the checksum validation should ignore case when evaluating the equality of two checksum strings.
=> fix(bbb-web): Case Insensitive Checksum Validation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
Sets cursor to `move` when moving an annotation in the whiteboard.
[Screencast from 2023-02-10 15-33-56.webm](https://user-images.githubusercontent.com/3728706/218170446-43efebb2-feaa-47eb-95ff-9ea674ea7da2.webm)
Closes #16664
=> fix(whiteboard): change cursor when moving shapes

record-and-playback/core/lib/recordandplayback/edl/video.rb
When a deskshare stream with combined audio + video starts up, it can happen that the audio starts before the video - so the first video frame will be some amount of time after the file start.
If there's a recording processing cut in this gap, the procesing can crash because it can generate an output video with no video frames.
There are two parts to the fix:
* Trim input videos with the trim filter, configured to ensure at least 1 output frame is generated, even if it would be after the end timestamp.
* Use the tpad filter to pad the *start* of a video stream to make sure there's something in the gap.
An example where this happened has a deskshare file that looks like this:
```
$ ffprobe -v fatal -show_entries format=start_time:stream=start_time,codec_type,index …
```
=> recording: Fix handling deskshare with delayed video

record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/video/scripts/process/video.rb, record-and-playback/video/scripts/video.yml
A few minor updates and fixes to the video recording format:
* The `show_moderator_viewpoint` recording setting is now honoured.
* The desktop sharing video replaces the presentation area - it no longer hides webcams (it now matches the live meeting).
* The `playback_protocol` recording setting is now honoured (recording links will correctly use https when that's configured).
=> recording: video format updates & fixes

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/container.jsx
Makes the following changes in order to reduce the number of renders in whiteboard cursors: 
- restores BBB 2.5 `cursorInterval` behavior
- do not pass tldrawAPI object to cursor component (only pass the parts needed by Cursors component)
=> fix: reduce whiteboard cursor updates

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This will add a focus ring around the interactive elements in the top tldraw toolbar. 
Also removes the gap between the toolbar and top of the presentation (more visible in dark mode).
Before:
After:
As part of the a11y issues, the “Styles / undo and redo” controls lacked a visible focus indicator different from the hover style.
=> Add Focus Ring To Items In Top Tldraw Toolbar

bigbluebutton-html5/imports/ui/components/notes/component.jsx, bigbluebutton-html5/imports/ui/components/notes/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/container.jsx
Prevents the shared notes notification from always being lit.
Closes #16598 
https://user-images.githubusercontent.com/33319791/218263134-75788f4b-afb6-4780-bd7f-860d96119ef0.mov
=> fix: Notes notification perpetually unread

bigbluebutton-html5/imports/api/slides/server/helpers.js
Force slide scaling to a fixed size, fixing annotation size issues.
[Screencast from 2023-02-14 13-35-35.webm](https://user-images.githubusercontent.com/3728706/218799927-899504aa-6f05-4ac3-b009-95c96dc050a0.webm)
[Screencast from 2023-02-14 13-34-06.webm](https://user-images.githubusercontent.com/3728706/218799942-7eb3b812-325a-4151-8c4d-72e0d5e93a65.webm)
Closes #16145
=> fix: Sticky notes are giant on portrait view slides

bigbluebutton-html5/imports/api/connection-status/server/modifiers/updateConnectionStatus.js, bigbluebutton-html5/imports/api/connection-status/server/publishers.js, bigbluebutton-html5/imports/ui/components/connection-status/service.js
Currently all clients (users) update the collection `connection-status` with `connectionAliveAt: now` every 10 seconds (by default).
And moderators receive this information for each update.
It is necessary to check if the client didn't update `connectionAliveAt` for more than 10 seconds , which means the client is facing some connection problem.
It turned out that in meeting with a lot of users, Moderators are receiving too much information about `connectionAliveAt` updated.
And what moderators really need to know is if someone is not responding.. the exact timestamp is not important.
So this PR introduces a new field called `clientNotResponding`.
Now `connection-status-Publisher` will stop sending the `connectionAliveAt` and will send just a flag `clientNotResponding` instead.
And the …
=> refactor: Avoid flood moderators with useless connection status

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Removes the space that appears if there is no item under the "more" button of style tool. It is usually the case for iPhone.
On iPhone the panel doesn't look very pretty.
Confirmed that it works for RTL languages. I didn't check it on a real iPhone. Please somebody do it.
Before:
After:
=> style: Remove space on the right of style tool on iPhone

.github/workflows/automated-tests.yml
The automated tests are failing during the audio tests.
It seems that it happens because the loopback address entry in `/etc/hosts`
This PR fixes it setting the private IP address instead! e.g: `10.1.0.156 bbb-ci.test`
The problem was happening probably because of the sip_profile it got when connecting to 127.0.0.1.
=> ci: Set private IP address instead of loopback address

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/styles.js
This PR adds a dropdown menu, which allows a user to change their emoji status, to the raise hand button. 
In some lectures professors like to use the status for getting a general overview over the students opinions. This is more comfortable than starting a poll. The menu to change the status was pretty hidden. This PR makes it easier to access it.
=> feat: Emoji Status Control in Raise Hand Button

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/service.js
It fixes the incorrectly displayed message "Invalid Date" to not displaying anything when this property (`conn.timestamp`) is not sent.
=> fix (html5): Fix "Invalid Date" on Connection Status modal

akka-bbb-fsesl/src/debian/DEBIAN/postinst
Fix error of `bbb-fsesl-akka` logging:
```log
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(logs/bbb-fsesl-akka.log,true) call failed. java.io.FileNotFoundException: logs/bbb-fsesl-akka.log (Permission denied)
```
Closes #16590
After lots of digging, I looked up into some logs I inserted in the `bbb-install.sh` script, and it seemed, at first sight, that the folder `/var/log/bbb-fsesl-akka` was not yet created when the install script tried to first run the component. But some new debugs and information came, and from the looks of it, while `bbb-apps-akka` had the changing of ownership in its `postinst` script in the debian package, `bbb-fsesl-akka` didn't.
So, a simple solution was to insert the ownership directly in the `postinst` script in `fsesl` debian …
=> build(akka-fsesl): Fix permission denied to bbb-fsesl-akka logging

record-and-playback/core/lib/recordandplayback/edl/video.rb, record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/core/test/recordandplayback/edl/test_video.rb, record-and-playback/core/test/recordandplayback/generators/test_events.rb
This PR includes a few fixes to recording processing.
The most major one is [Enforce minimum length of video segments](https://github.com/bigbluebutton/bigbluebutton/commit/7d17ffc5f960be776d0ef3414144771118d38245) - this fixes an issue where recording processing could break if there's a too-short gap between two changes to what video streams are visible, or between the start and stop events. It merges events and extends the generated recording slightly if needed to ensure that processing succeeds. There's negligible impact on audio/video sync. This change includes tests.
I have updated the tests for the `get_chat_events` function, which no longer passed due to changes in the code. The tests found a bug that had been introduced in handling of very old recordings - I have included the …
=> recording: Enforce minimum length of video segments, etc.

.github/workflows/automated-tests.yml
While investigating the problem fixed in #16730, it was very useful to analyze the Logs and Configs of the server running in CI.
So this PR propose to include this information as artifacts always when the test fail!
It includes:
Probably this PR will not fail in the testing check... so the artifacts will not be generated here.
But it's possible to check in this draft: #16687
=> CI: Include bbb logs and configs as artifacts (when fail)

bigbluebutton-html5/imports/ui/components/components-data/group-chat-context/adapter.jsx
Replaces `diffAndDispatch` function with `groupChatCursor.observe` method, reducing the number of `.find()` calls in group chat context adapter.
=> refactor: reduce groupChat.find calls in group-chat-context

.github/workflows/deploy-docs.yml, docs/.gitignore, docs/README.md, docs/build.sh, docs/docusaurus.config.js
This pull request introduces github actions to build the new docs and deploy them to github pages (#16665). It builds all versions that are on a release branch or on 'develop' and have a docusaurus-config (#16671). There is also an updated readme to explain local development (#16666).
The behavior for the versioning is that 2.6 is currently both the 'latest' version as well as the 'next' version. As soon as 2.7 is built, it will then be displayed as the 'next' version.
Details can be found in the commit descriptions.
An example deployment can be seen at https://tibroc.github.io/bigbluebutton/
=> (docs/ci): Docs deployment

record-and-playback/core/lib/recordandplayback/edl/video.rb, record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/core/test/recordandplayback/edl/test_video.rb, record-and-playback/core/test/recordandplayback/generators/test_events.rb
This is a backport of #16740 and #16774 from BigBlueButton 2.6 to BigBlueButton 2.5; see those PRs for details.
=> recording: Enforce minimum length of video segments, etc. (2.5 backport)

record-and-playback/core/lib/recordandplayback/edl/video.rb
Includes two fixes:
* Fix a bug introduced in 1dd40b838036aa33b28436b5f6172a6433d0c008 that caused the start of some deskshare videos to be delayed, possibly by as much as several seconds. This could also cause a recording to fail to process, because sometimes the compositing ffmpeg process would exit without reading all of its input.
* Fix a bug exposed by 49cf81f4a0712ae461f0486047aa95df6d693578 where if an EDL entry (cut) was missing an area that was present in the layout, recording processing would crash. This case is now treated the same way as if the area was present but had no videos.
=> fix(recording): Recording stability & A/V sync fixes

bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/polling/styles.js
- Automatically move user focus to the polling options when they are mounted.
- Updates the polling container to an `<aside>` with `role="complementary"`  in order to provide an additional means for a screen reader user to navigate to the poll region easily.
The resulting poll modal fails to meet the a11y standard for gaining keyboard focus automatically when presented
=> fix(access): Move Focus To Polling Option When Presented

bbb-learning-dashboard/src/App.js, bbb-learning-dashboard/src/components/UsersTable.jsx, bbb-learning-dashboard/src/index.css
This PR improves the color of some elements in the learning dashboard that did not meet the minimum required contrast ratio.
before:
after:
fixes the contrast errors
=> fix(access): Darken Color Contrast For Non Compliant Elements

bbb-learning-dashboard/src/components/UserDetails/component.jsx
This PR fixes an a11y issue by adding context to the time values to provide more clarity to screen reader users in the learning dashboard user details. Also improves the screen reader navigation.
Before:
```heading    level 3  Kert
heading    level 3  Overview
busy indicator  
Start Time
10:51 AM
End Time
Active
00:10:38
Duration
10:51 AM
Joined
```
After:
```
heading    level 3  Overview
Student 5 online time 01:34:49  busy indicator  
Start Time 14:28:50
Active
Duration 01:34:49
Joined 14:28:54
Online
```
The duration indicator fails to provide sufficient context to screen reader users announcing only the time with no instruction or additional information describing the number.
=> fix(access): Add Context To Time Values in Learning Dashboard User Details 

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
This PR deactivates 'propagate layout and layout settings' when disabledFeatures is passed as a custom parameter.
#16777
=> fix: Propagate layout and layout setting don't show up when disabled features is enabled as a custom parameter. 

build/packages-template/bbb-config/after-install.sh, build/packages-template/bbb-html5/after-install.sh, build/packages-template/bbb-html5/bbb-html5-conn-limit.conf, build/packages-template/bbb-html5/bbb-html5.nginx, build/packages-template/bbb-html5/build.sh
Currently the config `limit_conn ws_zone 3;` is being set to all request of location `/html5client`.
Which can cause problems once the var `$uri` ignores the query string `?sessionToken=umztpwmivztkapmi` and thus all join requests are aiming the exact same `$uri` (`/html5client/join`).
This PR will set this limit of 3 simultaneous connections (by uri) only for location `/html5client/sockjs`, in which the `$uri` is always different (`/html5client/sockjs/998/06d05kqd/websocket`).
Improves #15977
Might help to fix #14582
---
_Plus: Also removes limit_conn_zone config from `bbb-config/after-install.sh` and follow the pattern of `bbb-html5-loadbalancer.conf` instead._
=> refactor (nginx): Set limit_conn only for location /html5client/sockjs

bigbluebutton-config/bin/apply-lib.sh
Open 3478 on ufw only if haproxy running
If the administrator installs BigBlueButton with the [bbb-install-2.6.sh](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh) using the option
```
-c <hostname>:<secret> Configure with coturn server at <hostname> using <secret> (instead of built-in TURN server)
```
then don't open port 3478.
=> fix(config): Open 3478 on ufw only if haproxy running

bigbluebutton-config/bin/bbb-conf
When running `bbb-conf --secret` as a non-root user, a needless check is done against `/etc/bigbluebutton/turn-stun-servers.xml` and throwing an error.
Closes #16814
=> Skip reading of turn-stun-servers.xml in bbb-conf --secret

bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/RecordingServiceDbImpl.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/RecordingServiceFileImpl.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml
Adds a new property `allowFetchAllRecordings` to bigbluebutton properties that controls whether every recording on a server can be returned in a single response. By default this property is set to true and allows all recordings to be returned in a single response. When switched to false a `no meetings` response will be returned if a user attempts to get all recordings without using pagination.
Closes #16753
=> refactor (bbb-web): getRecordings - introduce new config allowFetchAllRecordings

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/pan-tool-injector/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Moves the Pan tool from the presentation toolbar to the tldraw toolbar (below the pointer tool).
Closes #16662
=> refactor: Move Pan Tool Next To The Pointer Tool

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Fix an issue with the first slide of the presentation appearing when switching slides.
[Screencast from 2023-02-27 13-13-12.webm](https://user-images.githubusercontent.com/3728706/221618017-5b50a728-990b-4b6c-823c-d18273c34c62.webm)
[Screencast from 2023-02-27 13-12-32.webm](https://user-images.githubusercontent.com/3728706/221618064-f8a130fa-4321-4b76-ab42-de6be66b07c2.webm)
Closes #16725
=> fix: First slide appears on slide transition later on

bigbluebutton-html5/imports/ui/components/app/container.jsx
Restores presentation area when layout change is pushed
Closes #16436
Behaviour:
Layout push did not restore presentation area (unless it's custom layout & you use `Push layout` button)
Expected:
If you have `Push to all` toggle on - you expect everyone's layout to become what's on image
=> fix: Restore presentation on layout push

bigbluebutton-web/gradle.properties
Upgrades the embedded Tomcat server version from 9.0.70 to 9.0.71.
Version 9.0.70 is vulnerable to [CVE-2023-24998](https://www.cve.org/CVERecord?id=CVE-2023-24998).
=> fix(sec): Upgrade embedded Tomcat version

bigbluebutton-web/build.gradle
Upgrades the commons fileupload dependency from version 1.4 to 1.5.
Version 1.4 of the dependency was vulnerable to [CVE-2023-24998](https://www.cve.org/CVERecord?id=CVE-2023-24998).
=> fix(sec): Upgrade file upload dependency

bbb-common-web/build.sbt
Removes the Glassfish expression language dependency from bbb-common-web.
Dependency has an unpatched security vulnerability [CVE-2021-28170](https://www.cve.org/CVERecord?id=CVE-2021-28170).
=> fix(sec): Removed glassfish el dependency

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/pan-tool-injector/component.jsx, bigbluebutton-html5/public/locales/en.json
This PR does the following:
- Stops lines being drawn while panning. 
- Moves the styles menu closer to the whiteboard toolbar.
- Update the pan cursor and include grabbing.
- Update the pan tool label when disabled.
- Fixes a bug where the pan tool selected style would not stay applied when zooming in.
Zooming in was causing the pan tool to remove it's selected style
Lines were being drawn while panning on occasion
Styles menu to far from the whiteboard toolbar
The cursor icons for panning were different when using the shortcut vs toolbar to pan.
=> fix: Prevent Lines Being Drawn While Panning | Style Updates

bigbluebutton-web/build.gradle
Upgrades the Grails/Gradle asset pipeline dependency from 3.3.4 to 4.0.0.
The 3.3.4 version of the dependency contained the following vulnerabilities:
- [CVE-2022-23221](https://www.cve.org/CVERecord?id=CVE-2022-23221)
- [CVE-2021-23463](https://www.cve.org/CVERecord?id=CVE-2021-23463)
- [CVE-2021-42392](https://www.cve.org/CVERecord?id=CVE-2021-42392)
=> fix(sec): Upgrade asset-pipeline-gradle dependency to 4.0.0

bigbluebutton-web/build.gradle
Upgrades the commons fileupload dependency from version 1.4 to 1.5.
Version 1.4 of the dependency was vulnerable to [CVE-2023-24998](https://www.cve.org/CVERecord?id=CVE-2023-24998).
=> fix(sec): Upgrade commons-fileupload

bigbluebutton-web/gradle.properties
Upgrades the embedded Tomcat server version from 9.0.70 to 9.0.71.
Version 9.0.70 is vulnerable to [CVE-2023-24998](https://www.cve.org/CVERecord?id=CVE-2023-24998).
=> fix(sec): Upgrade embedded Tomcat version to 9.0.71

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
This PR contains a fix for not being unable to move a group of objects, along with the addition of the select cursor.
Closes: #16910 , #16892
=> fix: Inability to Move a Group of Objects | Add Select Cursor

bigbluebutton-html5/imports/api/presentations/server/modifiers/setCurrentPresentation.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx
This PR fixes the restoreOnUpdate feature, The bug was caused because the meeting was without a current presentation for some time, this generated some inconsistencies when deciding whether to update the layout or not.
Closes #16824
=> Fix: restoreOnUpdate feature does not work when switching presentation

bigbluebutton-html5/imports/ui/components/webcam/container.jsx
This PR erases the part of the code that keeps webcam activated when returning from breakout rooms.
#16437
=> fix: Switching from breakout room to parent meeting no longer keeps the webcam activated.

bigbluebutton-tests/playwright/presentation/presentation.spec.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js, bigbluebutton-tests/playwright/user/user.spec.js
This PR disables three tests that are failing in CI. They require further investigations/fixes.
Two shared notes tests required further investigation. Manual testing doesn't show any issues. Looks like a CI-specific issue.
Issue: https://github.com/bigbluebutton/bigbluebutton/issues/16928.
Presentation upload test failure is caused by the different order of attributes within the HTML of moderator and viewer presentations. It is a good idea to start using visual regression for this test, it looks like an easy fix that way.
Issue: https://github.com/bigbluebutton/bigbluebutton/issues/16927.
=> test: Disable three tests that are failing in CI: shared notes + upload presentation

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Now moderators with see the 'Push layout' toggle in the layout modal. This will set layout synchronization on/off, but everyone will still follow the presenters layout.
=> feature(layout): Moderators can now setPushLayout

bigbluebutton-html5/imports/api/breakouts/index.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutClosed.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutJoinURL.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutList.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/joinedUsersChanged.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/updateTimeRemaining.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/userBreakoutChanged.js, bigbluebutton-html5/imports/api/breakouts/server/modifiers/clearBreakouts.js, bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/ui/services/api/index.js
This PR Migrates the backend of the breakout rooms for the new Metor async api introduced in the Meteor version 2.8 (Migration guide [here](https://guide.meteor.com/2.8-migration.html)).
Closes #16101 in part.
In Meteor 3.0 the fibers will be descontinued due incompatibility with node 16, so we need migrate our code base for the new async api, discussions:
https://github.com/meteor/meteor/discussions/11505
https://github.com/meteor/meteor/pull/12028
https://github.com/meteor/meteor/pull/11605
My idea is migrate it by rounds to make it easy to review and mitigate the impact of every change.
OBS: we don't need to migrate the collections calls in frontend, but the async api is avaible for the client-side too.
> Fibers don't exist in the client so you don't need to use the new API in the …
=> refactor: Migrate the breakout room backend to new async api

docs/docusaurus.config.js
The workflow to edit the page would either way not be a simple click to an edit page. But you'd have to fork the repo, sign a CLA, and then do a PR against the correct version. So I decided to remove it.
Closes #16863
=> docs: Remove the edit button on the bottom of each page

docs/build.sh
The script that adds the different versions to docusaurus was broken when not running it from the develop branch. This commit should fix that.
=> docs: Fix the version build script

bigbluebutton-html5/imports/ui/services/auth/index.js
Fix "OK" button not working for removed user after refresh (related to #16754, the button was not appearing before these changes).
=> fix: return logoutUrl on logout even if the user is not logged in

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Performs an extra check to ensure that we have a page before checking its id (to use it as a new whiteboard Id)
Closes # none
This issue was spotted during the community call on Monday March 6.
It can be reproduced if you switch back and forth between uploaded presentations quickly.
=> fix: avoid wb crash when switching presentation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Updates tldraw document when a new presentation is added in order to avoid a crash that happens when a page is not available.
This issue was spotted during the community call on Monday March 6.
It can be reproduced if you upload a new presentation with more pages than the default one and switch to a page that does not exist in default presentation.
=> fix: whiteboard crash with new presentation

docs/build.sh
In order to be able to control better which branches are actually used for building the docs, this commit changes the logic of the script to only add manually specified versions to the docs.
=> docs: Build only manually specified versions

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR ensures that the tool remains locked after drawing shapes when it is activated.
Closes #16959
=> fix: Stop Tool Lock Being Reset on Updates

bigbluebutton-web/deploy_to_usr_share.sh
Adjusts the deployment script of bbb-web to not interrupt if dir `exploded` is present
Closes # none
deployment was consistently interrupted for me while testing https://github.com/bigbluebutton/bigbluebutton/pull/16919
=> fix: Allow for existing dir 'exploded' in bbb-web deploy_to_usr_share.sh

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
this PR fixes the sent to chat success notification not being displayed.
Before:
After:
When sharing a presentation to the chat for users to download, no indication is provided to the user that the presentation was shared in the chat.
=> fix: Notifications on export presentation with annotations

bbb-export-annotations/config/settings.json, bbb-export-annotations/workers/process.js
Implements the new slide scaling logic implemented in #16721.
Closes #16827
Annotation positioning was incorrect in the exported slides.
Stops hyphens from being escaped with a `/` in the generated PDF.
=> fix(export-annotations): change slide scaling calculation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/pan-tool-injector/component.jsx, bigbluebutton-html5/public/locales/en.json
This PR removes the disabling of the pan tool at 100%.
Closes #16992
=> Remove Disabled Functionality From Pan Tool

docs/README.md
The build-script is only used for the deployment and can lead to confusing problems with local development if run locally.
=> docs: Improve docs readme

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
fix "Could not download current presentation" error when trying to download a snapshot of the current slide in presentation.
=> fix: snapshot of current slide

.github/workflows/automated-tests.yml, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js, bigbluebutton-tests/playwright/user/user.spec.js
This PR also re-enable SharedNotes-Tests (disabled in #16929). In order to make further investigation on it.
(I ran automated-tests twice to this current PR and I was not able to make it fails. Chances are that it is fixed already by some previous PR).
=> test: Adds bbb-pad logs for CI artifacts (when fail)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR removes the need to hold `CRTL` key down while using the mouse wheel to zoom in and out.
Closes #16379
=> Zoom By Mouse Wheel Only Operation

bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/notifications/presenterNotifications.js
- Change the uploaded file for `Presentation upload notification` test in order to decrease unnecessary wait time;
- Reintroduce `Poll results notification` test since it's not failing locally for a while;
=> test: Improve notification test execution time and reintroduce skipped test

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/utils/keyCodes.js
Handle ctrl+A shortcut when the whiteboard is focused so it selects all shapes instead of selecting objects outside of the whiteboard.
Closes #17029
=> fix: Ctrl+A shortcut selects objects at outside of whiteboard

bigbluebutton-html5/imports/ui/components/presentation/service.js
Fixes the response poll option displaying for True / False
Closes #17046
=> fix: Prevent Response Poll Displaying For True / False

bigbluebutton-html5/imports/ui/components/audio/container.jsx
There was an observer being linked to all breakout rooms that the user has access to. This logic works for attendees, but not for moderators. Moderators have access to the list of all breakout rooms, so they were set with an observer to breakout rooms that they didn't participate, which caused the audio and video modals to appear everytime the breakout rooms were closed. So, this commit:
- hangs an breakout rooms' observer only on those mods that have joined any breakout room. This way, mods that didn't participate in any breakout room won't be disturbed by the audio and video modal.
- adds an extra check to ensure that the observer will only be run in non-breakout meetings.
Closes #15716
=> fix(breakout rooms): video and audio modal appearing for all mods when rejoining

docs/docusaurus.config.js
This commits adds configuration to docusaurus that prevents the 'unmaintained' banner to be shown for version 2.5.
=> Docs: Don't display 'unmaintained' banner for 2.5

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/utils.js
Makes the following changes to the poll results displayed in whiteboard:
- adds border and solid background
- changes the font to monospaced
- align percent values to the right
Closes #16682
Closes #16917
=> fix: Poll results are difficult to read and not scaled to fit slide

bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/video-provider/service.js
In the end of breakouts, in FireFox I had my client crash. There were some temporary webcam issues involved which might make this even more rare.
Closes #
=> fix: Fix undefined user in rare end-breakout scenario

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiErrors.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Displays an error message to a user when they are denied access to a meeting to explain why they cannot join.
Closes #12335
=> fix: Display error message when guest is denied access to a meeting

docs/docs/administration/install.md, docs/docs/new-features.md, docs/docs/support/road-map.md, docs/src/components/HomepageFeatures/index.tsx
Mark BBB 2.6.0 as stable (in contrast to "under development")
Closes # none
2.6.0 release
=> docs: marking 2.6.0 as stable

docs/src/css/custom.css
Bold fonts were not rendered due to wrong naming of font-styles.
This commit fixes that.
Closes #17119
@dmtrhfr contributed to this
=> Docs: Fix bold font rendering

.github/workflows/automated-tests.yml
Moves `paths-ignore` to **pull_request** setting
=> ci: Fix paths-ignore to docs folder

.github/workflows/deploy-docs.yml, docs/build.sh, docs/docusaurus.config.js
From now on the docs will only be build on develop and not on the release branches.
This commit adjusts the build script and the `docusaurus.config` on develop and the gh-action workflow accordingly.
=> docs: Build docs only on develop

bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
Fix the bug where the custom background keeps being shared after be removed in the selector.
Closes #17072
Also I made it set the new background when it's uploaded.
https://user-images.githubusercontent.com/15806883/226457456-ee86f420-746c-48cf-b974-1a3965b7cf33.mp4
=> Fix custom virtual background not being disabled when removed

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
Closes poll modal when moderator changes slide
Closes #16870
Previously - if the user hasn't answered - the modal would remain open permanently
=> fix: Close poll on slide change

bigbluebutton-html5/imports/ui/components/presentation/service.js
This prevents URLs triggering typed response poll option in smart slides.
Closes #17093
=> Prevent URLs Triggering Typed Response Poll Option

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/styles.js
Improves usability of waiting user element by:
replacing buttons `Message | Accept | Deny` with icons to free up space for the name, also by making name capable of occupying multiple lines for more visibility
Closes #16390
Previously the buttons used to cover the name on smaller screens which, especially on certain locales
PR removes background and cursor change on hovering over waiting user as it may mislead into thinking that user is clickable
=> fix: Allow viewing of longer names in guest waiting queue

record-and-playback/video/scripts/video.yml
The deskshare video was accidentally set to 920px wide instead of 960px wide, so it was not completely covering the presentation area.
=> recording/video: Fix typo in area layout

docs/docs/support/troubleshooting.md
- fix(docs): additional instructions for systems without CAP_SYS_NICE
* bbb-webrtc-sfu is missing from the troubleshooting section. 
* FreeSWITCH needs an update.
* The LXD section could reuse each subsection to avoid redundancy.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/17059
40 minute compile times :+1: 
FreeSWITCH instructions could be further updated to use overrides as well.
I'm not going to test that right now, though, so I kept changes to a minimum.
=> fix(docs): additional instructions for systems without CAP_SYS_NICE

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx
This PR restores the keyboard access to breakout management by preventing the presentation moving focus outside the modal.
before:
after:
A11y issue where keyboard controls didn't allow for assigning users to breakout rooms.
=> fix(access): Presentation Interference With Keyboard Access in Breakout Management

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
It fixes the presentation-uploader modal when trying to cleaning errors and it is not uploading anything else. See error ahead:
https://user-images.githubusercontent.com/69865537/227521804-5338d79f-6d2a-498c-8cd4-3a22e07232a5.mp4
=> (fix) - fix presentation modal freeze when cleaning errors

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/service.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
This is a workaround to the conflict that is happening when an user tries to download the slide when dark mode is enabled. There is a conflict between dark mode's styles and the html-to-image lib. To temporarily prevent this from happening, the dark mode is disabled before downloading the slide, and then re-enabled when the download is complete.
In order to be able to enable and disable dark mode from another component than the App, all the dark mode switch logic was extracted into the service of the app component.
Closes #17192
=> fix(presentation): workaround for slide download

record-and-playback/core/lib/recordandplayback/edl/video.rb
The encoding settings for intermediate files was using `-preset veryfast -crf 30`, which resulted in very poor quality video.
After a bit of experimenting, I decided to change this to `-preset veryfast -crf 23`. This results in files which are roughly twice the size of before, but they look significantly better.
There's improvements possible at the same filesize by switching to a slower encoding mode. But in the case of -preset medium for example, when normalized to the same output file size, you end up using about 1.5 times as much cpu time to gain only a very small amount of video quality.
=> recording: Increase quality of libx264 intermediate files

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
This PR removes the red dot indicating change on shared notes when they're pinned.
#16943
=> Fixed: Note notification removed when shared notes pinned.

bigbluebutton-web/build.gradle, bigbluebutton-web/gradle.properties
Upgrades Spring WebMVC dependency to version 5.3.26 as well upgrades Grails version to 5.3.2.
The Spring WebMVC dependency is vulnerable to [CWE-284](https://cwe.mitre.org/data/definitions/284.html) and upgrading to latest version without the vulnerability requires an upgrade to the Grails version.
=> fix(sec): Upgrade Spring WebMVC Version

bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala, record-and-playback/video/scripts/process/video.rb
Changes the state of video recordings to `published` instead of `available`, following the same approach as [Scalelite](https://github.com/blindsidenetworks/scalelite/blob/master/app/models/recording.rb#L47), and retrieves meetingId info from `meta` tag if there is no `meeting` tag present.
#16791
=> fix(bbb-com-web): Change video state to published and get meetingIds from meta tag

bigbluebutton-web/build.gradle
Excludes the H2 database and GraalVM SDK dependencies brought in by asset-pipeline-grails. After these changes running the `deplpy_to_usr_share.sh` should remove the `h2.jar` and `graal-sdk-22.0.0.2.jar` from `/usr/share/bbb-web/WEB-INF/lib/'.
There is no H2 database being used by bbb-web so there is no need to include the transitive dependency for it.
The version of GraalVM SDK that is brought in to bbb-web by asset-pipeline-grails has many vulnerabilities
- [CVE-2022-21443](https://www.cve.org/CVERecord?id=CVE-2022-21443)
- [CVE-2022-21434](https://www.cve.org/CVERecord?id=CVE-2022-21434)
- [CVE-2022-21426](https://www.cve.org/CVERecord?id=CVE-2022-21426)
- [CVE-2022-21496](https://www.cve.org/CVERecord?id=CVE-2022-21496)
- [CVE-2022-21449](https://www.cve.org/CVERecord?id=CVE-2022-21449 …
=> fix(sec): Exclude GraalVM and H2 Dependencies

bigbluebutton-html5/imports/api/slides/server/helpers.js, record-and-playback/core/scripts/bigbluebutton.yml, record-and-playback/presentation/scripts/publish/presentation.rb
Reduce the maximum size of the whiteboard canvas page to `maxImageWidth = 1440`, `maxImageHeight = 1080`.
Closes #17086
=> fix(whiteboard): Reduce max canvas size

bbb-presentation-video.placeholder.sh
This is the release of bbb-presentation-video for BigBlueButton 2.6.1.
* https://github.com/bigbluebutton/bbb-presentation-video/pull/31 by @kepstin
* https://github.com/bigbluebutton/bbb-presentation-video/pull/30 by @germanocaumo
* https://github.com/bigbluebutton/bbb-presentation-video/pull/33 by @kepstin
* https://github.com/bigbluebutton/bbb-presentation-video/pull/34 by @kepstin
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.0-rc.2...4.0.0
=> fix(bbb-presentation-video): Update to 4.0.0

bbb-export-annotations/config/settings.json
Reduce the maximum size of the canvas page to `maxImageWidth = 1440`, `maxImageHeight = 1080`.
Closes #17086
This change should only be merged once the same changes in `bbb-html5` have been applied.
=> fix(bbb-export-annotations): Reduce max canvas size

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Restores background slide when presentation is changed.
=> fix: empty slide on presentation change

.github/workflows/automated-tests.yml
Keeps `paths-ignore` on push in order to avoid triggering it
=> ci: Prevents CI triggering on push events

bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
Adds variable type keywords to fix some code smell
Closes #none
=> fix: fix some code smell by adding const for variables

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
We were trying to save a poll result shape before it was converted to tldraw style, which was not compatible.
Ignore those annotations, they will come later in the right format.
Closes #17348
=> fix(recording): crash on redisrecorderactor when poll is published

record-and-playback/core/lib/recordandplayback/edl/video.rb
The Fcntl::F_SETPIPE_SZ constant was added in Ruby 3.0, but Ubuntu 20.04 still uses Ruby 2.7. Add some error handling so processing doesn't fail if the constant is not found.
=> recording: Fix video processing incompatibility with Ruby 2.7

record-and-playback/core/lib/recordandplayback/edl/video.rb
Backport of #17379 by @kepstin
=> recording: Fix video processing incompatibility with Ruby 2.7 (backport to 2.5)

docs/docs/release-notes.md, docs/docs/support/faq.md, docs/docusaurus.config.js, docs/sidebars.js, docs/src/components/HomepageFeatures/index.tsx
The Greenlight references points to GLv2 docs `greenlight/v2/overview`.
Fix it so that it now redirects you to the GLv3 docs instead `greenlight/v3/install`.
=> fix(docs): set Greenlight v3 as default reference for Greenlight

docs/docusaurus.config.js
It fixes the restoring to default version when changing from one tab to another in bbb documentation `navbar`. 
Closes  #17157
Just a demo of the final result:
https://user-images.githubusercontent.com/69865537/229228566-8d5601f5-1025-45ad-88c6-8099338a6925.mp4
=> docs: fixed reseting to default version in bbb documentation

docs/docs/administration/customize.md, docs/docs/development/api.md, docs/docs/new-features.md
It inserts documentation for `hidePresentationOnJoin` as suggested in comment https://github.com/bigbluebutton/bigbluebutton/pull/16769#issuecomment-1454662628
Related to https://github.com/bigbluebutton/bigbluebutton/pull/16769.
See snapshots of the update:
=> docs: Insert documentation for hidePresentationOnJoin

docs/docusaurus.config.js
After setting `lastVersion: '2.6'`, routes for 2.6 version are no longer prefixed with `2.6/` so some redirects were failing
Closes #
reated: https://github.com/bigbluebutton/bigbluebutton/pull/17398
=> docs: fix - 2.6 route does not exist now that 2.6 is current

record-and-playback/presentation/scripts/publish/presentation.rb
The code was skipping the check for cursor x or y position < 0 when the tldraw whiteboard was in use. That condition is still needed on the tldraw whiteboard to indicate that the cursor should be hidden.
Only the check for cursor x or y position >100 needs to be skipped when the tldraw whiteboard is in use (since tldraw cursors are in the slide coordinate space, they can go up to x=1440 or y=1080)
=> recording-and-playback/presentation: Fix hiding tldraw cursors

docs/docs/development/api.md, docs/src/components/APITableComponent/index.tsx, docs/src/components/APITableComponent/styles.module.css, docs/src/data/create.tsx, docs/src/data/deleteRecordings.tsx, docs/src/data/end.tsx, docs/src/data/getMeetingInfo.tsx, docs/src/data/getRecordingTextTracks.tsx, docs/src/data/getRecordings.tsx, docs/src/data/insertDocument.tsx, docs/src/data/isMeetingRunning.tsx, docs/src/data/join.tsx, docs/src/data/publishRecordings.tsx, docs/src/data/putRecordingTextTrack.tsx, docs/src/data/updateRecordings.tsx
It mainly refactors the current table structure to follow a similar pattern as we had with the previous documentation.
Closes #16930
There were 2 other attempts of making this table referencing work: 
- With `yaml` files as the data source for the tables;
- And with `json` files as the data source;
Both of them were unsuccessful on the grounds that it would be too much refactor for too little return, and also, I am not sure if we would be able to use the index search that `docusaurus` has.
On the other hand, with `tsx` files as the data source, not only do we have the indexing search, but also, `docusaurus` themselves already use this approach, see [`src/data/quotes.tsx`](https://github.com/facebook/docusaurus/blob/bf9b69cfbf4b71d3124e9d876c57efba90688754/website/src/data/quotes.tsx) …
=> docs: Fix for tables broken references

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/pan-tool-injector/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Fix darkening wb toolbar icons when pointer hovered. 
In the previous toolbar I found three problems (commented in #16801):
1. The pan tool does not darken when the pointer hovered
2. The tooltip of pan tool appears a bit faster than the other tools, and it hide the next button (pen tool) almost completely
3. When the pan tool is selected, the other buttons do not darken when the pointer hovered on them.
Closes the problems 1 and 3 listed above.
Since the injection of pan tool into the tldraw toolbar (which is really nice indeed), the icon darkening has not been working correctly.
The problem 2 in which the tooltip appears too much faster remains to be solved.
Before:
After:
<video src="https://user-images.githubusercontent.com/45039819/229360584-9dce90f2-35d2-414e-ab28-2ecb53a257cd.mov" …
=> [2.6 fix] recover hover effect on icons of whiteboard toolbar

bigbluebutton-tests/gns3/.gitignore, bigbluebutton-tests/gns3/NPDC.placeholder.sh, bigbluebutton-tests/gns3/README.md
Add a script to checkout the NPDC repository, which is used by the gns3 script.
It was originally a submodule, but there's a backwards compatibility issue (the need to convert to SVN to support the Jenkins build system) that prevents using submodules.
I currently have it set to checkout the `master` branch of NPDC.  Git submodules are typically tied to a single commit (not a branch).  Not sure if there will be a problem pointing the script to `master`.
There's also a `.gitignore` file to ignore the (untracked) NPDC directory, as well as ignoring SSL certs and keys.  The certs and keys should probably be moved to a different location, but that's a different PR.
=> GNS3 placeholder

bigbluebutton-html5/imports/ui/components/user-list/service.js
This PR sets the priority of privet chats in the following order:
1. Unread messages (and if more than one alphabetical).
2. Alphabetical (if none is unread). 
#17403
=> Enhancement: Unread and read privet chats now order by unread and alphabetical order.

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Move the setting of tldraw's `isForcePanning` property to the `onPatch` event.
Closes #17331
=> fix: Move Setting isForcePanning To Patch Event

bigbluebutton-html5/imports/api/slides/server/methods/zoomSlide.js
This will validate the slide number to handle the exception when calling the `zoomSlide` method.
Closes #16951
=> fix: Handle Exception While Invoking ZoomSlide

bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js, bigbluebutton-html5/imports/ui/services/webrtc-base/peer.js
* [feat: add option to force/extend gathering window in SFU components](https://github.com/bigbluebutton/bigbluebutton/commit/be6a23a00350dd25eb7c94da103ecbc7e88d1239) 
- There's an edge case in finnicky networks where firewalls with ALG-like sorcery
tamper with USE-CANDIDATE STUN packets and, consequently, bork ICE-lite
connectivity establishment. The odd part is that client-side gathering
seems to complete if intermediate STUN bindings work (before the final
USE-CANDIDATE), which may cause the peer not to generate relay
candidates == connectivity fails.
- This adds the `public.kurento.gatheringTimeout` option to forcefully extend
the candidate gathering window in peers that act as offerers. The
behavior is as follows: if the flag is set (ms), the peer will wait
either the gathering …
=> feat: add option to force/extend gathering window in SFU components, +

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/service.js, bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js, bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js, bigbluebutton-html5/imports/ui/services/webrtc-base/peer.js, bigbluebutton-html5/private/config/settings.yml
Introduces a bunch of improvements to cam/screen re-connection procedures 
I've found to have regressed (in behavior) when migrating to 2.5+-based 
environments. In detail, per commit:
- [fix(video): properly render reconnecting view](https://github.com/bigbluebutton/bigbluebutton/commit/728877b68a7c89556824c6bab31984a70fe8dc91) 
* The stream state change handler in video-list-item is using a component
state reference inside a DOM event callback - which means it is always
presuming `isStreamHealthy` is false (initial value). That prevents the
health state from actually transitioning when necessary (and
consequently rendering the reconnecting view in video-list item).
- [fix(video): add proper signaling WS heartbeat, +](https://github.com/bigbluebutton/bigbluebutton/commit/ab1807adc23fd66ba …
=> fix: re-connection improvements for cameras and screen sharing

build/setup.sh
This bug was introduced in PR #14889
When is LOCAL_BUILD ever not set?  Does the release packaging, perhaps, call docker with LOCAL_BUILD set to something other than `1`?
=> build script: fix LOCAL_BUILD being tested before it was set 

bigbluebutton-html5/imports/ui/components/layout/enums.js, bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
Fills the empty space shown after removing all presentations in the Custom and Smart Layout with available webcams.
Restores layout once new media (pinned notes, presentation, deskshare, external video) is available.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/16511
https://user-images.githubusercontent.com/33319791/230175281-61f5698c-77af-4d1b-8443-de95647853b2.mov
https://user-images.githubusercontent.com/33319791/230171081-5c47d271-8ed3-4e0d-a381-e94c0a83552c.mov
https://user-images.githubusercontent.com/33319791/230171110-2c4029b0-ae2d-451c-8e23-336d47402647.mov
https://user-images.githubusercontent.com/33319791/230171133-801b11dd-ceb5-4dab-9111-847bb5052621.mov
=> fix(bbb-html5): Maximize webcams when removing all presentations

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/container.jsx, bigbluebutton-html5/public/locales/en.json
Adds a button to toggle the visibility of toolbars.
Closes #15739
Testing 2.6, I am a bit frustrated that the new tldraw toolbar is not (re)movable. It's larger than the old whiteboard toolbar and hide more space within the slide. It's more problematic when I use a laptop with a small screen.
To solve this problem, I have implemented a button that enables hiding/showing the toolbars. 
As @KDSBrowne suggested in #15739, using the "focus mode" of tldraw native API would be more elegant. However I found this approach makes other problems on the layout of toolbars. 
The menu icon should be better refined (for now they are assigned on "better-than-nothing" basis).
=> [2.6] Hide tldraw toolbar

docs/docusaurus.config.js
It basically adds a redirect to all `/2.6` paths so that old links pointing at this version won't fall into a 404 page.
=> (fix) - Adds redirect of all /2.6 links

docs/docs/administration/install.md
Add a description to open port 443 and 80 when -e option is chosen.
I failed in a clean install of BBB 2,5 without this operation.
I am not sure if it's the same for 2.6. 
I saw a post in the past that somebody suffered this issue.
=> [doc] open 80 and 443 for Let's Encrypt

bigbluebutton-html5/imports/ui/components/common/button/component.jsx
Suppress warning of the color 'light' not found in the preset list.
Closes #
I've also found that it's been fixed in 2.6 source code. We'd better fix it also for 2.5. Although 2.5 is not the developmental mainstream anymore, I suppose there are still many users who haven't migrated to 2.6.
=> [2.5 chore] add color light to button

bigbluebutton-html5/imports/ui/components/common/button/component.jsx, bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/pan-tool-injector/component.jsx
Making the injected pan tool show the tooltip in a similar way as the other wb tools.
Closes the issue 2 in the comment on #16801
The tooltip of pan tool appeared a bit faster than the other tools, and it hide the next button (pen tool) almost completely because it shows up at the bottom of the icon, while the other tools show tooltips above the icons.
Together with the PR #17395, the new whiteboard toolbar looks almost consistent.
Before:
(look at the pan tool behaving differently from others, showing no hover effect, tooltips appearing very fast and its position is different from others)
After:
=> [2.6 fix] Show the pan tool tip at the same timing and position as other tools

bigbluebutton-html5/imports/ui/components/whiteboard/annotation-factory/component.jsx
Suppresses the warning that annotationSelector.text does not have the type func, but is the type object.
=> [2.5 chore] type of annotationSelector.text is object

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Currently, if no `disabledFeatures` is provided in `bbb-web.properties`, the default value is set as:
```json
"disabledFeatures" : [ "${disabledFeatures}" ]
```
It seems that over the upgrades of spring, grails, etc.. we had to tweak how this config is read.
Tweaked first in #15467, then in #15782.
Turned out that now it accepts the current value as `disabledFeatures=` (which used to throw error in the past).
And it fixes the problem of the invalid default value:
Besides that:
This PR also includes options `customVirtualBackgrounds` and `presentation` to the list of `# Available options:`
=> fix (bbb-web): invalid default value for disabledFeatures when config is missing

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GuestsWaiting.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/ColorPicker.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/RandomStringGenerator.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/UserJoinedMeetingEvtMsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeTestData.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core2/testdata/TestDataGen.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GuestsMsgs.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala, bigbluebutton-html5/imports/api/guest-users/server/handlers/guestsWaitingForApproval.js, bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
Mainly this PR aims to keep compatibility between codes of 2.6 and 2.7. It will be introduced in 2.7 through #17124.
---
When the user is registered, he receives a color.
Currently it is picked in Meteor in a random way..
This PR moves this decision to `akka-apps` and the color will be chosen when the user is registered.
It seems that this was the idea all the time:
It is one step in the way to remove decisions from Meteor.
PS: In addition, now the color will not be chosen randomly anymore. Instead it will always pick the next color of the list, decreasing the probability of repeating.
=> refactor: Moves user color picker to akka-apps (instead of meteor-backend)

bigbluebutton-html5/imports/ui/components/media/autoplay-overlay/styles.js
Autoplay overlay is shown over the audio modal
Changed z-index of autoplay overlay to be behind the modals.
https://user-images.githubusercontent.com/39932802/230986236-5d7eca74-f40c-4d5e-b1db-af9af6f54aed.mp4
=> fix(screenshare) autoplay overlay

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This removes the `throttledResetCurrentPoint` function which was being used to force a re-render on the whiteboard element.
Makes the whiteboard annotations return to their correct placements after being resized.
before:
after:
=> fix: Improve Whiteboard Zoom After Resize

docs/docs/data/create.tsx, docs/docs/development/dev-guide.md
Updates the docs for `bbb-export-annotations`, adding API references for `breakoutRoomCaptureSlides` and `breakoutRoomCaptureNotes` as well as more detailed development/maintenance instructions.
Requested in https://github.com/bigbluebutton/bigbluebutton/pull/15755#issuecomment-1501735814
=> docs: Update breakout capture API reference

docs/docusaurus.config.js
It changes the way we do the redirects, according to docusaurus documentation:
> The parameter `path` is a route that Docusaurus has already created. It can be seen as the "to", and your return value is the "from". Returning a falsy value will not create any redirect pages for this particular path.
(https://docusaurus.io/docs/2.3.1/api/plugins/@docusaurus/plugin-client-redirects#CreateRedirectsFn)
so what it does is create new paths that the documentation will accept.
=> [fix] - fixed redirects to fit docusaurus pattern 

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Upgrades react-virtualized version from 9.22.3 to 9.22.4.
Added support to react 17 and 18.
=> chore: upgrade react-virtualized

docs/docs/data/join.tsx, docs/docs/development/api.md
Add documentation for the new `join` API parameter, `errorRedirectUrl`, that was added in #17202.
=> docs: Document join parameter `errorRedirectUrl`

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
The `join` API did not respect the `redirect` parameter and would continue to redirect users on errors even if `redirect` was set to false. Also added support for a new parameter on `join` API calls called `redirectUrl` that allows a user to either provide a custom URL to redirect users to, or it can be set to `logout` to redirect the user to the meeting's logout URL.
Closes #11241
Closes #12824
=> fix/feature (bbb-web): Add new join param `errorRedirectUrl` and fix to respect redirect

bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/notes/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
This PR makes the minimized presentation stay minimized even though the screen sharing or external video sharing get deactivated.
#17464
=> Fix: Presentation un-minimizing when exiting external video or screen sharing.

bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/notes/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
Reverts bigbluebutton/bigbluebutton#17512
as it seems to cause https://github.com/bigbluebutton/bigbluebutton/issues/17668
=> Revert "Fix: Presentation un-minimizing when exiting external video or screen sharing."

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR ensures the whiteboard toolbars stay hidden when switching pages and the auto hide feature is enabled.
There was a bug that was causing the toolbars to stay visible after switching the page when auto hide was enabled.
before:
After:
=> fix: Patch Auto Hidden Tools To Stay Invisible On Page Change

bigbluebutton-html5/client/main.html
This PR addresses an issue with the stylus and iPad, enhancing the drawing experience. Previously, during drawing sessions, elements were getting unintentionally selected and highlighted, causing interruptions. This update ensures that the stylus and iPad work without any selection interference. Now the magnifying glass is displayed instead of the highlight / selection.
=> fix: Prevent Canvas Selection While Using Stylus On iPad

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
This PR serves as a follow-up to #17678, which previously disabled the text copying functionality in the chat via selection. The initial fix successfully prevented the selection of unintended elements but inadvertently introduced a side effect where the magnifier would appear frequently during drawing. This update restores the chat's text copying capability and resolves the issue with the selection and magnifier's interruptions.
Closes: #17679
=> fix: Disable Canvas Magnifier On iPad While Using Canvas

.github/workflows/automated-tests.yml, .gitlab-ci.yml, bbb-webrtc-recorder.placeholder.sh, bigbluebutton-config/bin/bbb-conf, build/package-names.inc.sh, build/packages-template/bbb-webrtc-recorder/.build-files, build/packages-template/bbb-webrtc-recorder/after-install.sh, build/packages-template/bbb-webrtc-recorder/bbb-webrtc-recorder.service, build/packages-template/bbb-webrtc-recorder/before-remove.sh, build/packages-template/bbb-webrtc-recorder/build.sh, build/packages-template/bbb-webrtc-recorder/opts-focal.sh, build/packages-template/bbb-webrtc-sfu/bbb-webrtc-sfu.service, build/packages-template/bbb-webrtc-sfu/opts-focal.sh, build/packages-template/bigbluebutton/build.sh, record-and-playback/core/scripts/archive/archive.rb, record-and-playback/core/scripts/bigbluebutton.yml
Partial port of bbb-webrtc-recorder's own build scripts.
The app's build uses nfpm. That's fine - I just ported most of the stuff to BBB's pattern (fpm + scripts) so we don't need to add nfpm to the mix or deal with package importing from the external repo's CI pipeline.
None
Ref #13999 
* Testing:
- build + install
- set `recordingAdapter: bbb-webrtc-recorder` in `/etc/bigbluebutton/bbb-webrtc-sfu/production.yml`
- restart bbb-webrtc-sfu
- record something
* captured files can be verified in /var/lib/bbb-webrtc-recorder
* logs will end up in bbb-webrtc-recorder.service's journal
- Pending:
=> build: add bbb-webrtc-recorder

bigbluebutton-html5/imports/ui/components/common/button/button-emoji/styles.js
fix incorrect size for raise hand dropdown on ios
Closes #16944
=> fix: Wrong style for set status dropdown button on iPhone

docs/docs/administration/customize.md
Update the "[Server Customization](https://docs.bigbluebutton.org/2.5/administration/customize)" doc to match the correct virtual background images path.
Before :
`/usr/share/meteor/bundle/programs/web.browser/app/resources/img/virtual-backgrounds`
After :
`/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds`
Might need to be backported to 2.5/2.6 docs.
Regards,
=> docs: Correcting the virtual background images upload path

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-graphql-client-test/src/UserList.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_ref.yaml, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/queries.ts
- `Disconnected` (old `userLeftFlag`)
Currently when the user closes the window or he lost connection with the server, BBB set `leftFlag: true` to this user.
But this flag's name is not self explanatory, once it's name suggest the user left the meeting, what sometimes is not the case.
So we renamed it to `disconnected` that explains much better what really happend.
- `Expired`
And after 10 seconds with `disconnected == true` the user is removed from the userList. And we need some flag in graphql `user` collection to indicate that the user is with this status. So the name for it is `expired` that means BBB waited for 10 seconds for some re-connection but this time expired.
=> refactor (graphql-server): Introduces flags disconnected and expired to Graphql

bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_public.yaml
When this option is `true`, viewers should not see when other viewers are typing.
This PR set this permission in Hasura.
=> fix (graphql-server): Locked viewers can see other viewers typing

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/queries.ts
It should use the endpoint `user_current` instead of the generic `user`.
=> fix (html5): Set proper query to get current user in graphql

bigbluebutton-html5/imports/ui/components/mobile-app-modal/component.jsx, bigbluebutton-html5/imports/utils/deviceInfo.js, bigbluebutton-html5/private/config/settings.yml
For tablet users the user agent returns macOS instead of iOs.
This PR improves the iOS detection to consider tablet as iOs instead of macOS, so that the transfer button is displayed correctly.
Also, it fixes the url concatenation to encode its parameters and avoid breaking.
https://user-images.githubusercontent.com/7821065/234858078-fcd9c2c4-5884-44ba-a6e5-14d21a39a1ce.mov
Closes #17360
=> fix: Transfer button not displayed in tablets

build/packages-template/bbb-config/opts-jammy.sh, build/packages-template/bbb-html5/opts-jammy.sh, build/packages-template/bbb-playback-podcast/opts-jammy.sh, build/packages-template/bbb-playback-presentation/opts-jammy.sh, build/packages-template/bbb-record-core/opts-jammy.sh, build/packages-template/bbb-webhooks/opts-jammy.sh, build/packages-template/bbb-webrtc-sfu/opts-jammy.sh
Temporarily removing the dependency `yq` until an Ubuntu 22.04 version v4 of it is packaged in our ppa. `bbb-install-2.8.sh` already downloads+links it correctly.
Closes #
7 BBB packages use `yq` within their scripts (mostly post-install).
On Ubuntu 20.04 we had packaged `yq` v3 as a ppa package. We are transitioning to v4 on Ubuntu 22.04 but have not yet packaged it in the support ppa. Therefore even if we install `yq` in the recommended way (https://github.com/mikefarah/yq/#install) and is usable locally, it is not recognized as an installed dependency of these BBB packages.
=> build: (TEMP) drop yq as a dependency -- it is a script not package on 22.04

bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
This PR makes the cameras not available for dragging when presentation is minimized and layout is custom.
=> Fix: Draggable cameras when presentation minimized.

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/DatabaseConnection.scala, akka-bbb-apps/src/universal/conf/application.conf, bbb-graphql-server/hasura-config.env, bbb-graphql-server/install-hasura.sh, bbb-graphql-server/metadata/databases/databases.yaml
Maybe in the future bbb will have more Postgresql databases.
So it is better to specify the service name in the database name.
This PR renames it from `bigbluebutton` to `bbb_graphql`.
=> refactor (graphql-server): Alter graphql database name to bbb_graphql

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_usersPolicies.yaml
Motivation: To avoid this kind of rule on the client side.
How to use:
```
query {
meeting {
usersPolicies {
moderatorsCanMuteAudio
moderatorsCanUnmuteAudio
}
}
}
```
- `moderatorsCanMuteAudio`: False when it's a breakout room
- `moderatorsCanUnmuteAudio`: False when it's a breakout room or it has the config `allowModsToUnmuteUsers=false`
=> feat (graphql-server): Add flags moderatorsCanMute/Unmute to usersPolicies

bbb-graphql-server/bbb_schema.sql
Creates a trigger `update_chatUser_clear_typingAt_trigger` that clear the chat_user prop `typingAt` every time a new `chat_message` is inserted.
=> fix (graphql-server): User continue typing after msg is sent

build/packages-template/bbb-etherpad/notes.nginx, build/packages-template/bbb-html5/bigbluebutton.nginx
The etherpad component's nginx configuration needs to know the request scheme in order to set some variables that influence whether the 'Secure' flag is set on cookies. Right now it directly uses the $scheme variable, but this variable does not get set to the expected value if nginx is behind a reverse-proxy where the proxy handles TLS termination.
Adjust the etherpad nginx config to use a variable with a different name $real_scheme, which can be set in the nginx server block to match the configuration of the nginx listeners.
This variable is set to the value of $scheme in the default /etc/sites-available/bigbluebutton file.
This needs to be merged along with the corresponding update to the bbb-install.sh script: https://github.com/bigbluebutton/bbb-install/pull/642 People using other …
=> nginx config: Allow overriding the $scheme variable

bigbluebutton-tests/playwright/chat/chat.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/chat/privateChat.js, bigbluebutton-tests/playwright/chat/util.js, bigbluebutton-tests/playwright/layouts/layouts.spec.js
Changes the chat test from parallel mode to serial mode, where we use the same meeting for testing.
=> test: Chat to serial mode

bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Similar to #17792, this PR fixes the lack of cursor for non-presenter users when multi-user whiteboard is enabled.
=> fix: cursor not appearing for non-presenter when multi-user whiteboard is enabled

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
Meteor code must always run in a fiber, but the `setTimeout` handler was breaking out from the Meteor fiber which would cause meteor to crash since it could not re-enter the fiber once left. Meteor provides a built-in version of `setTimeout` to handle this situation.
=> fix: Use meteor.setTimeout to keep call inside fiber

bbb-export-annotations/workers/collector.js
Adds supports for sending annotated `.jpg` presentations to chat. Previously, only `.jpeg` images were being converted.
Closes #17807
=> fix(export-annotations): Support .jpg images

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
When users would leave a meeting the `joined` attribute in their corresponding `RegisteredUser` in akka-apps was not being updated to false which was resulting in future users not being able to join when the `maxParticpants` property was set on a meeting since any users who had joined were still being counted against the current number of participants even if they had left. Now whenever a user is removed from a meeting their `joined` status is set to false so that they are not counted in the `maxParticipants` check. 
Closes #15070
Closes #17699
=> fix: maxParticipants check counting users that have left

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/RandomStringGenerator.scala
Switches the PRNG used to generate user IDs to a cryptographically secure PRNG.
Given any two outputs from a non-cryptographically secure PRNG a person is able to recover the seed of the PRNG which will allow them to know all future outputs. This could potentially lead to a security issue if someone would be able to predict all future user IDs.
=> fix(sec): Switched PRNG to secure PRNG

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
This updates the question regex so it excludes urls as matches and fixes a console error for undefined of includes when using the dropdown menu to play detected links.
url triggering typed response option:
error:
=> fix: Update Question Regex to Exclude URLs

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/RandomStringGenerator.scala
Switches the PRNG used to generate user IDs to a cryptographically secure PRNG.
Given any two outputs from a non-cryptographically secure PRNG a person is able to recover the seed of the PRNG which will allow them to know all future outputs. This could potentially lead to a security issue if someone would be able to predict all future user IDs.
=> fix(sec): Switched PRNG to secure PRNG 2.5

bigbluebutton-html5/imports/ui/components/notifications/container.jsx
Removes notification from local collection after displaying so they don't appear again if language is changed.
Closes #17720
=> fix: Toast notifications shows again when the language is switched

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx
Currently, when switching presentations using the `(+)` dropdown menu, the change is not being properly propagated to the presentation uploader modal. The same issue occurs when moving shared notes to the presentation area, where an incorrect presentation is displayed as the selected current presentation.
This inconsistency causes confusion and makes it difficult for users to keep track of their active presentation. If the modal is quickly opened and dismissed with `Confirm`, an undesired presentation change occurs.
**Dropdown**
https://user-images.githubusercontent.com/33319791/235474833-caf78bfa-d24e-4765-81d9-8909a801690e.mov
**Shared notes**
State of the presentation uploader modal after moving notes to the presentation area. The blue `CURRENT` badge does not match the checked circle. …
=> fix(bbb-html5): Inconsistent current presentation indicator

bigbluebutton-config/cron.daily/bigbluebutton
It checks for the status (`.done`) of the other recording formats, as well as for presentation.
Closes #16646
=> fix(config): check status of other recording formats

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/container.jsx
Invisible grid no longer appears because streams are filtered with userId before going to video-list-item to render.
Screenshare's end alert only play on started -> ended or starting -> ended transitions, not * -> reconnecting -> ended.
There might be an invisible camera container in the grid when a webcam sharer reconnects.
Screenshare's end alert plays on intermediate reconnection attempts while it should only play on started -> ended or starting -> ended transitions, not * -> reconnecting -> ended.
=> fix: overlapping screen end alerts and invisible cameras on reconnections

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
The system will now display a confirmation toast each time a file is downloaded, regardless of whether it is annotated. This PR also rectifies a previously encountered issue that resulted in the display of multiple toasts.
Not reported.
@GuiLeme's PR https://github.com/bigbluebutton/bigbluebutton/pull/17648 highlighted an existing edge-case issue where multiple export confirmation toasts could be triggered. These steps replicate the issue:
1. Join a meeting
2. Add some annotations to the whiteboard
3. Export the same file repeatedly
4. Erase the annotations
5. Export annotations again
6. See multiple toasts confirming export.
This PR should be merged in before https://github.com/bigbluebutton/bigbluebutton/pull/17648 to prevent any conflicts from occurring. Thanks to @GuiLeme as well for …
=> fix(bbb-html5): Successful annotated export toast

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Removing seemingly unnecessary style for the fit-to-width button.
The "panning" variable seems not passed anymore since 2.6.
=> style: remove unnecessary fit-to-width style

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Preserve font settings on page change
Closes #17891
=> fix(whiteboard): Font selection is reset on slide change

bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/imports/ui/services/settings/index.js, bigbluebutton-html5/public/locales/en.json
This PR adds a feature that allows user to disable his on web cam, and in doing so, saving his own computer resources.
#16114
Example:
=> feat: Disable self-view of webcam

bigbluebutton-html5/imports/ui/components/presentation/service.js
This PR fixes an issue with quick poll options, where the regular expressions were hardcoded to English, leading to inconsistent behaviour for non-English locales.
the regular expression has been updated to dynamically adjust based on the currently selected locale. This results in consistent quick poll options across different languages, improving the overall user experience.
Closes #17466
=> fix: Localize Regular Expressions for Quick Poll Options

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Adds a new condition to the check for duplicate meetings to ensure that meetings with the same ID and name, but no moderator or attendee passwords return a success response instead of an error.
Closes #17886
=> fix: Add check for no passwords in meeting create

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Hide self view disabled message if camera is not being shared
Closes #17945
=> fix: The indicator for disabled self view should hide on webcam unshare

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
Adjusts webcam settings toggle so the correct value is displayed. 
[Screencast from 2023-05-22 10-21-24.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/b114e384-c95e-4f6c-810e-edc3095c76f4)
[Screencast from 2023-05-22 10-22-28.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/b81f8c42-0a37-41c4-9e99-82425eea9160)
=> fix: webcam self view toggle label

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fix slide image render issue in Firefox, when a slide renders before image loading is finished. 
Closes #17969
=> fix: Some images are not shown in presentation if using Firefox as client and using a PDF created by MS Office

build/packages-template/bbb-freeswitch-core/build.sh
I missed this in #17990 when backporting. It was applied on BBB 2.6 via https://github.com/bigbluebutton/bigbluebutton/pull/16672
=> build: bump libks to v1.8.2 (FreeSWITCH)

bigbluebutton-html5/imports/ui/components/webcam/component.jsx
This PR fixes a bug related to the dragging cameras in custom layouts, mentioned in the issue linked bellow. 
#17906
=> Fix: Cameras behind drop areas and presentation when dragging

bigbluebutton-web/build.gradle
Upgrades `org.json` dependency to 20230227.
Previous version of the dependency was vulnerable to [CVE-2022-45688](https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5488379)
=> fix(sec): Upgrade org.json

bbb-common-web/build.sbt, bigbluebutton-web/gradle.properties
Upgrade Spring dependency to 2.7.12.
Previous version of Spring was vulnerable to:
- [CVE-2023-20883](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5564390)
- [CVE-2023-20883](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5564390)
- [CVE-2023-20873](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5441321)
=> fix(sec): Upgrade Spring

bigbluebutton-web/build.gradle
Upgrades `spring-webmvc` dependency to 5.3.27.
Previous version of the dependency was vulnerable to [CVE-2023-20863](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-5422217).
=> fix(sec): Upgrade spring-webmvc

bigbluebutton-web/build.gradle
Upgrades `grails-core` dependency to 5.3.2.
Previous version of the dependency was vulnerable to [CVE-2020-36518](https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244).
=> fix(sec): Upgrade grails-core

bbb-graphql-client-test/src/usePatchedSubscription.js, bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/msgpatch/jsonpatch.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/sessiontokenreader.go
A few graphql subscriptions will take advantage of the **cache** provided by apollo-client.
For example when two components needs exactly the same information, it will be smart to use the same query for both and the second one will receive the data immediately once the first component already received it and apollo-client stored it in its cache.
When using json-patch, the cache benefit will not be possible once the last data might be only the patch and not the entire object.
In this case the second component would receive the patch and it would be useless once it doesn't have the previous data to apply the patch.
In order make possible the use of cache, now the component will be able to opt if its subscription support patch or not.
It is a trade-off case:
- `usePatchedSubscription`: If it …
=> refactor (graphql-middleware): Support enable json-patch per subscription

bigbluebutton-web/build.gradle
Upgrades `org.json` dependency to 20230227.
Previous version of the dependency was vulnerable to [CVE-2022-45688](https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5488379)
=> fix(sec): Upgrade org.json (backport from BBB 2.6)

bbb-common-web/build.sbt, bigbluebutton-web/gradle.properties
Upgrade Spring dependency to 2.7.12.
Previous version of Spring was vulnerable to:
- [CVE-2023-20883](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5564390)
- [CVE-2023-20883](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5564390)
- [CVE-2023-20873](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5441321)
=> fix(sec): Upgrade Spring (backport from BBB 2.6)

bigbluebutton-web/gradle.properties
Upgrades Tomcat dependency to 9.0.74.
Previous version of the dependency was vulnerable to:
-[CVE-2023-28708](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-3369687)
-[CVE-2023-28708](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-3369687)
=> fix(sec): Upgrade tomcat (backport from BBB 2.6)

bigbluebutton-web/build.gradle
Upgrades `spring-webmvc` dependency to 5.3.27.
Previous version of the dependency was vulnerable to [CVE-2023-20863](https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-5422217).
=> fix(sec): Upgrade spring-webmvc (backport from BBB 2.6)

bigbluebutton-html5/imports/ui/components/poll/component.jsx
This PR removes the empty 'E' on Letter type polls.
#17893
=> Fix: Empty 'E' on polls answer options

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fixes the whiteboard toolbar options button being overlapped on certain screen sizes.
Closes #18031
=> fix: UI Overlap Toolbar Options Button

bigbluebutton-html5/imports/ui/components/common/modal/base/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/status-helper/component.jsx
- fix "adjusting your settings" button appearing only when connection level is danger or critical
- fix settings modal priority when inside connection status modal
=> fix: connection status modal "adjusting your settings" button not working as expected

bigbluebutton-html5/private/config/settings.yml
* enables by default the newly introduced reactions bar (emoji - raise hand button)
* adds inline comments on which option takes precedence
Closes #
BBB 2.7 has alternatives for reactions/raise hand action, see https://github.com/bigbluebutton/bigbluebutton/pull/17764
=> chore: Enable ReactionsBar by default

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx
The list of attendees in `getMeetingInfo` responses did not accurately reflect the number of participants in a meeting since the list was including users that were offline. The list of attendees would only be correct once the offline users had been purged from the meeting after 60 seconds of being offline. The attendee list now only includes users that are online.
Closes #17936
=> fix(Meeting API): Only include online users in attendee list

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx
Fix presentation uploader export options dropdown not working on 2.7.
[Screencast from 2023-06-01 09-31-04.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/21348b08-21f6-4757-9179-15d467f9c8be)
=> fix: presentation uploader dropdown styles

docs/docs/development/recording.md
Adds a note in the beginning of the docs section on changing the Start/Stop recording marks under Recording.
Closes # none
Community member @defnull pointed out that since the introduction of https://github.com/bigbluebutton/bigbluebutton/pull/18044 our docs for changing the Start/Stop recording marks are no longer applicable in their old form. Thank you!
=> docs: Added a note for recording processing with recordFullDurationMedia

bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
Removes a clippath that is making a problem on the recently updated Chromium-based browsers.
Closes #18066 
Related discussion: https://groups.google.com/g/bigbluebutton-dev/c/r35CE7Z1zfU
I need a quick fix because my class is starting from next week!
To me this clippath seems not necessary at all. I will post another PR (#18085) that removes all.
This PR itself might not be necessary if the bug (which I suppose so) is fixed on the Chromium side. But even so, removing this clippath does not harm anything as far as I checked.
=> fix: recover drawing area (minimum version)

bigbluebutton-web/build.gradle
Upgrades `grails-core` dependency to 5.3.2.
Previous version of the dependency was vulnerable to [CVE-2020-36518](https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244).
=> fix(sec): Upgrade grails-core (backport from BBB 2.6)

bigbluebutton-html5/imports/ui/components/notes/component.jsx
This PR fixes the bug where the pin to the shared notes wasn't restoring presentation.
#18040
=> Fix: pinning shared notes should restore presentation

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
An uncaught exception was being thrown if a `create` request was sent with `isBreakout` set to true and no `parentMeetingID` provided, since the parent meeting could not be found. Added a check in the `create` request handler to ensure that a `parentMeetingID` is always passed when `isBreakout` is true.
Closes #17949
=> fix: Added check for parentMeetingId if isBreakout is true

bigbluebutton-html5/imports/ui/components/notes/component.jsx
Fix crash when leaving meeting with shared notes open
=> fix: crash on leave if shared notes is open

docs/docs/administration/cluster-proxy.md
Adds missing documentation for cluster proxy setup.
Closes #16542
`bbb-web` needs configuration for correct CORS headers in cluster setup. Otherwise API calls from `bbb-html5` to `bbb-web` will be rejected by grails and the html5 client wont work properly.
It was not properly documented yet, just hidden in https://github.com/bigbluebutton/bigbluebutton/issues/16542#issuecomment-1418668932
=> Docs: add missing configuration option for cluster setup

bigbluebutton-html5/imports/ui/components/chat/service.js
It asks the browser to open the presentation with annotations download in a new tab.
In cluster proxy setup the browser wants to open downloaded presentation with annotations in the same tab as the BBB session. I don't understand why this is happening only in cluster proxy setup where the URL host part differs from the URL host of the html5 client.
URLs sent to chat by users also add the `target="blank"` attribute so I assume this is safe.
=> Fix: open documents download presentation in new tab

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/cursor/component.jsx, bigbluebutton-html5/private/config/settings.yml
Enables users to change the size of presentation pointer and sets the default value 10 in diameter, which is what BBB 2.5 adopted.
Starting lectures using BBB 2.6, I realised that the presentation (cursor) pointer is way smaller than it has been until 2.5. Not sure if it's intended change or confusion of radius with diameter, but I prefer a larger pointer. For those who prefer different size, I set this value configurable. 
Until 2.5:
On 2.6:
After the change (configurable at setting.yml):
=> feat(config): Configurable presentation pointer size

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR preserves the canvas position for each slide so it doesn't reset when switching.
Closes #18026
=> fix: Preserve Canvas Position On Slide Change

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.js
This PR makes smooth adjustments to talking indicator's padding, making so it does't hide behind other UI elements.
#18077
=> Fix: Presentation area in front of talking indicator elements.

build/packages-template/bbb-webhooks/after-install.sh, build/packages-template/bbb-webhooks/build.sh
Mimics setting unsafe-perm from package `bbb-webrtc-sfu` to replace the way it was done in `bbb-webhooks`. `npm config set unsafe-perm` seems discontinued after npm v6
Closes #18142 
- More testing of the resulting bbb-webhooks would be great
- This (or a better solution) should be backported to BBB 2.5
=> build: recover installation of bbb-webhooks

bbb-common-web/src/main/java/org/bigbluebutton/api/LearningDashboardService.java
Fix the encoding of the file that stores Learning Dashboard data to support Emoji chars.
----
This fix will be specially useful when Learning Dashboard shows Reactions!
=> fix (Learning Dashboard): Emoji not working on Learning Dashboard

bigbluebutton-html5/imports/ui/components/user-list/service.js
Fix locked label not appearing in userlist if only "See other viewers annotations" lock is enabled.
=> fix: locked label in userlist

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
Allow copy of the contents in breakout panel (list of users in each breakout room)
**Expected behavior**
If the user tries to copy the list of users in each breakout room (ctrl+c or select copy from the context menu), the contents should be added to the clipboard.
**Actual behavior**
`{"type":"tldr/clipboard"}` is added instead of the breakout panel content.
[Screencast from 2023-06-19 15-42-31.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/91366775-7f86-41f5-84c7-81cdaf42a662)
[Screencast from 2023-06-19 15-45-36.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/c145b8a1-380e-448a-8683-574277e47db6)
=> fix: copy event in breakout panel

bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
Removes a clippath that is making a problem on Microsoft Edge.
Suggested by @hiroshisuga in https://github.com/bigbluebutton/bigbluebutton/pull/18084#issuecomment-1597203201
Closes #18066
=> fix: recover drawing area - Microsoft Edge

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fix wrong slide position if zoom is changed back to 100% after being increased.
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/c36ecffe-dfbf-4098-b174-0ab9e89e6528
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/c59458f2-cb4e-4784-9f1d-675eda589f28
=> fix(presentation): reset slide position if zoom is 100%

bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Fix presenter permission for editing/moving poll results annotation if presenter is changed.
=> fix: presenter permission for poll results annotation

bigbluebutton-config/bin/bbb-conf
When (re)starting BBB, the freeswitch status check may be run too early. The `fs_cli` call can connect, but the piped in `/quit` command is ignored and the session never terminates. This patch will fail the check after 5 seconds and print a warning, instead of stalling the (re)start of BBB indefinitely.
closes #18140
This rare but annoying race condition causes some of your ansible based BBB deployments to fail on first try.
=> fix: Freeswitch status check hangs during `bbb-conf --(re)start`

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
Do not display "clear all status icons" action in presenter menu if user status is disabled.
=> fix: only display clear status if status is enabled

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fix force panning (by pressing space bar) in the whiteboard.
=> fix: panning with space bar shortcut does not work

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationWithAnnotationsMsgHdlr.scala, bbb-export-annotations/config/index.js, bbb-export-annotations/config/settings.json, bbb-export-annotations/package-lock.json, bbb-export-annotations/package.json, bbb-export-annotations/workers/notifier.js, bigbluebutton-html5/imports/ui/components/chat/service.js
This pull request fixes the link in the "Download" button for original presentation files (i.e, no annotations) when they are sent to chat in cluster setups.
It also removes any cluster-specific settings from `akka-bbb-apps` and `bbb-export-annotations` for downloads, exports, and captures. From now on, links will be created without the need for the `bbbWebBase` information, letting Meteor alone handle this on the client side. The goal of this change is to decrease the coupling between components, making it easier for system admins to maintain and configure them.
Only the link in the toast notification was working properly when downloading files without annotations in cluster setups. This issue was reported by @schrd. His feedback on this pull request would be appreciated.
=> refactor: Fix original presentation download link in cluster setups

bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/rating/component.jsx
replaces [createRoot](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis) with react-dom render
Closes #18215
Closes #18224
Closes #18234
A warning is displayed if render is used in react 18:
=> fix: undo createRoot changes in main

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/component.jsx
Removes duplicated muted indicator from grid mode avatar.
=> Remove duplicated muted indicator from grid mode

docs/docs/administration/install.md
Updates install.md documentation related to suggested server examples, Hetzner AX51 are not available any more. Use AX52 instead (AMD Ryzen 7700).
Docs should not point to server size which is not available any more.
See https://www.hetzner.com/dedicated-rootserver/matrix-ax
=> Update install.md, Hetzner AX51 are not available any more. Use AX52 instead.

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/timer/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/timer/component.jsx
Changes the behavior of activating the timer. The behavior set by this commit is: when the timer is activated, only the moderator who triggered it will see the sidebar content switch to the timer. This change required hanging an observer to catch the timer activation and dispatch the sidebar content change since timer messages are passing through akka.
Closes #18251
=> fix(timer): sidebar content when activated

bbb-graphql-client-test/src/App.js, bbb-graphql-client-test/src/TotalOfUsersTalking.js, bbb-graphql-client-test/src/UserConnectionStatus.js, bbb-graphql-client-test/src/UserConnectionStatusReport.js, bbb-graphql-client-test/src/UserList.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_user_connectionStatus.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_connectionStatusReport.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Each client will need to update its `connectionAliveAt` prop each 10 seconds:
```
mutation UpdateConnectionAliveAt($userId: String, $connectionAliveAt: timestamp) {
update_user_connectionStatus(
where: {},
_set: { connectionAliveAt: "now()" }
) {
affected_rows
}
}
```
When the prop `connectionAliveAt` is updated, the server automatically set `userClientResponseAt=null`.
Once the client check that the prop `userClientResponseAt` is `null`. The client will update this prop:
```
mutation UpdateConnectionAliveAt($userId: String, $userClientResponseAt: timestamp) {
update_user_connectionStatus(
where: {userClientResponseAt: {_is_null: true}}
_set: { userClientResponseAt: "now()" }
) {
affected_rows
}
}
```
Using both fields the server will be able to calculate the client rtt `rtt = …
=> refactor (graphql-server): Implements connection status control through graphql

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR resolves a bug causing the whiteboard to crash when switching between between presentation with zoomed-in slides. The fix involves a null check for the 'camera' object before attempting to access its 'zoom' property.
Closes #18231
=> fix: Whiteboard Crash When Switching Between Zoomed-In Slides

bigbluebutton-html5/imports/api/meetings/server/modifiers/changeLockSettings.js, bigbluebutton-html5/imports/ui/components/pads/service.js
Fix throttledCreateSession only running once
Closes #18256
=> fix: Unlocking specific user to edit shared notes is not working properly

bigbluebutton-tests/playwright/sharednotes/sharednotes.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
Adds a check for the restore presentation on pin notes to the whiteboard for the viewers.
=> test: restore presentation on pin notes to whiteboard

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Filters out of slide shapes on snapshot.
Closes #18261
=> fix: Long snapshots with no extra content when shape is applied out of presentation area

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js
This PR changes the way self-view disabling behaves, showing now the avatar when self-view is disabled, instead of last frame.
#18217
Example:
=> Client: self-view disabled changed, overlay over avatar.

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateDefaultPublicGroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserStateDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/MeetingStatus2x.scala
This PR will:
- Make sure that Public Chat is created after the Meeting
- Avoid to update Locksettings before it's created
- Set `null` value on Db when the moderator that approved guest was `SYSTEM`
=> refactor (graphql-server): Fix some conflicts on updating graphql-database

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
Restores pinned shared notes when screenshare ends.
Closes #18220
=> Preserve pinned notes after screenshare

bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/hascli/replayer/replayer.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/invalidator/invalidator.go, bbb-graphql-middleware/internal/websrv/sessiontokenreader.go
This PR will migrate from the Go locker `Mutex` to `RWMutex`.
Using `RWMutex` the graphql-middleware will be able to process several messages simultaneously once the read of a message will not lock `ActiveSubscriptions` anymore.
Using `RWMutex`, the map `ActiveSubscriptions` will be locked only when it needs to write into it (when new subscriptions are created or one is deleted). But most of the time the middleware will only read from it, so it is not necessary to completely lock.
In some slightly tests I could see the process of 50 messages running in half of the time than previously! 
More info at: https://pkg.go.dev/sync#RWMutex
=> refactor (graphql-middleware): Use RWMutex to improve performance

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
Adds 'F' and 'G' to the quick poll options to prevent a mix of letter and numbers being displayed when parsing a poll with 7 options.
Closes  #18223
=> fix: Add Quick Poll Options For 'F' And 'G'

bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js
Add timestamp to closed chat list, so it can be used to not reopen a chat unless a new message is received.
Closes #18258
=> fix: Promote and demote users is reopening closed private chats

bigbluebutton-html5/imports/startup/client/base.jsx
Fix issue #18297 
Closes #18297
I want to use localStorage to keep client settings across meetings. Permanently banning users from using free software is not an option.
=> Fix: use connection id to determine if a user is ejected or not

bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/container.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Instructors would like to see if anyone in the chat still wants to participate. This is very important for the moderation.
Showing the names could lead to people not wanting to participate (self-awareness that others are watching when you type).
The provided changes should solve this issue by adding a new configuration option. This option allows to enable or disable the names in the typing indicator.
No issue associated.
More participation by students (especially introverted and timid people) in chat when typing indication is enabled.
=> Html5: Add config to hide names in typing indicator

bigbluebutton-html5/imports/ui/components/common/modal/simple/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
This PR fixes an issue where focus was lost when using tab controls with keyboard within a modal. With this fix, user focus will stay within the modal when navigating through controls.
Using the tab controls for both the keyboard shortcuts and the connection status controls result in the user focus moving from the control to the main landmark of the page (outside of the modal) when a tab is actioned.
=> fix: Improve Focus When Changing Modal Tabs With Keyboard

bbb-learning-dashboard/src/components/StatusTable.jsx, bbb-learning-dashboard/src/components/UsersTable.jsx, bigbluebutton-html5/imports/ui/components/common/locales-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
* Add lang attribute to locale select options
* Improve style menu color contrast in dark mode
* Darken activity score green boxes for compliant contrast ratio
* Convert first column from `td` to `th` / add scope & label
* The user language dropdown fails to identify the change of language.
* When in the dark mode theme, The “Color” label lacks sufficient contrast within the “Styles” menu. The contrast between the foreground and background text colors is insufficient (1.3:1), falling short of the 4.5:1 required for normal text.
* Multiple activity score colors lack sufficient contrast. A user interface component (Activity score) has a contrast between foreground and background that is insufficient (1.2:1); falling short of the 3:1 contrast ratio required.
* The timeline tab contains a …
=> fix(accessibility): Enhance Color Contrast, Language Dropdown, and Screen Reader Feedback

bigbluebutton-tests/playwright/core/helpers.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js
Separates the create and join parameters, so the create parameter will be used on creating the meeting, and the join parameter will be used on joining the meeting. Before, it wasn't clear which type of parameter was being used, because it had only the custom parameter type.
=> test: separate create and join parameters

bigbluebutton-web/gradle.properties
Upgrades the embedded Tomcat version in `bbb-web` from `9.0.74` to `9.0.78`.
The current Tomcat version is vulnerable to [CVE-2023-34981](https://www.cve.org/CVERecord?id=CVE-2023-34981).
=> fix(sec): Upgrade embedded Tomcat to 9.0.78

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingWelcomeDAO.scala, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx
Related to this button:
This PR fix the following bugs:
- Not showing "Show Welcome Message" to Viewers
- Not showing "Show Welcome Message" to Moderators if there is only `welcomeMsgForModerators` and not `welcomeMsg`
- It's showing "Show Welcome Message" if the value of `welcomeMsg` is `null` (instead of `""`)
- Wrong icon for `Clear` button
- Akka-apps: Set `welcomeMsgs` as `null` instead of `""` in Database
- Fix a console error about BBBMenu
=> fix: Button "Show Welcome Message" with errors

bigbluebutton-html5/imports/ui/components/notes/component.jsx
Fix crash that happens if shared notes is unpinned by a different presenter.
=> fix: unpin shared notes after switching presenter

bbb-graphql-client-test/src/MyInfo.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
Currently, it's easy to identify if a user is configuring their microphone and is not yet able to listen by noting a particular icon:
An exciting update, identified as #14021, is set to be added to BBB, introducing the feature of "transparent listen only". This new feature paves the way for us to change the system behavior and enables a user to join the audio automatically upon opening the BBB interface. This contrasts with the current system, where the user needs to manually click to join audio.
However, if we implement this new default behavior, we face a challenge. While a user is configuring their microphone and performing the Echo Test, the meeting audio is automatically muted. During this time, other users might presume the first user is already listening, which is not the case. To …
=> graphql: Introduces a new flag isRunningEchoTest

bigbluebutton-tests/playwright/sharednotes/sharednotes.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
- Changes test name to `Pin and unpin notes onto whiteboard` - now also checking the unpin action;
- Adds steps to cover crash-bug fixed in https://github.com/bigbluebutton/bigbluebutton/pull/18343;
Note: we're facing some inconsistencies running shared notes tests, since opening 2 or more tabs in the same window/browser type might show an alert with a button to force the user to use only one of them. We don't want to hit this in the tests, but no workaround has been found yet. if necessary, we'll skip them temporally but, for now, all shared notes tests are available
=> test(notes): Pinning notes improvement

bbb-etherpad.placeholder.sh, build/packages-template/bbb-etherpad/settings.json
This PR upgrades `bbb-etherpad` to use Etherpad 1.9.1.
The current release (1.8.17) is over a year old.
There's a known bug in Etherpad 1.9.1 that prevents empty pads from being created through the HTTP API. This results in a "You do not have permission to access this pad" message being shown to the shared notes user. To work around this issue, the pad's default text is set to a zero-width space character. For more information, see the [relevant Etherpad issue](https://github.com/ether/etherpad-lite/issues/5787).
In Etherpad 1.9.1, serializing the Pad object with `JSON.stringify()` removes the `id` attribute of the pad since it implements its own `toJSON` method (see https://github.com/ether/etherpad-lite/issues/5814). As a workaround, a `padId` attribute is manually added in such cases. …
=> chore: Bump Etherpad to 1.9.1

docs/docs/development/dev-guide.md
Modifies BBB's documentation to include instructions for resolving potential conflicts when multiple versions of Java are installed. The modifications suggest using the `update-java-alternatives` command to set Java 17 as the active version. This is necessary as `bbb-common-message` now requires Java 17, but might mistakenly use Java 11 if it's also installed.
The motivation for this change comes from running into repeated build errors myself. The command suggested is in line with the one used in a previous [commit](https://github.com/bigbluebutton/bbb-install/pull/660/files#diff-b02a2e8accf3dc268b4cc8c4a6ce2b6b51cbaee1a254fb674c6429fbfdf5ef81R320).
=> docs: Add instructions for resolving Java version conflicts

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Adds new styles to quick poll button.
=> style: primary color in quick poll button

bigbluebutton-tests/playwright/core/elements.js
Backport of connection status selector fix (https://github.com/bigbluebutton/bigbluebutton/pull/18378) on BBB 2.6.x
=> test: Connection status element selector fix

bigbluebutton-html5/imports/ui/components/app/container.jsx
Makes `userdata-bbb_hide_presentation_on_join` parameter work again on BBB 2.7
Closes #18386
=> fix: bbb_hide_presentation_on_join parameter not working

.github/workflows/automated-tests.yml
This PR aims to improve the handling of failures during the automated-test workflow.
Currently, most of the commands run inside a block like this:
```
sudo sh -c '
command 1
command 2
command 3
'
````
As it turns out, if command 2 fails and command 3 succeeds, the Step will still be marked as Successful. However, the correct behavior would be for it to fail!
So, I've tweaked most of the steps to run in a block like this:
```
sudo -i <<EOF
set -e
command 1
command 2
command 3
EOF
```
In this way, if one of the commands fails, the Step will be marked as a Failure. This will help us identify where the problem lies.
Additionally, I've tweaked the `wget` command to use the `-nv` (non-verbose) parameter instead of `-q`. This is because `-q` was suppressing the error message, making it more …
=> tests: Improve the handling of failures during the workflow

bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/webcam/webcam.spec.js
- Adds `@flaky` test flag - the idea is to use it on the tests that are failing due to a known bug, aiming to keep the CI outputs as clear and reliable as possible. We'll avoid the to run on CI and will re-add it once we have the bug fixed
- Skipping the `Disabled features > Download Presentation With Annotations` test on CI due to a reported bug -
=> test: Add @flaky test flag and avoid them when running the tests on CI

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/presentation-ops-injector/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/presentation-ops-injector/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/presentation-ops-injector/menu/component.jsx
This PR addresses the issue of the incorrect tab order in the presentation options dropdown.
At first, thought of cloning the entire menu element and programmatically moving it to the intended location. However, this method was problematic as we lost the click handlers, thereby affecting the component's interactivity.
Next, considered importing the menu directly into its new location within the TLdraw UI. Unfortunately, this approach also hit a roadblock due to the loss of the Intl and Layout context.
To navigate these challenges. I duplicated the menu component and removed the Intl and Layout related items. Then, passed these elements as props to the component.
Closes #18257
=> fix: Correct Tab Order For Presentation Options Dropdown

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_current_time.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
This endpoint is useful to synchronize the time of the Client with the time of the Server.
```gql
query {
current_time {
currentTimeMillis
currentTimestampUTC
currentTimestampWithTimeZone
currentTimestampWithoutTimeZone
}
}
```
Result:
```json
{
"data": {
"current_time": [
{
"currentTimeMillis": 1690939172815.8418,
"currentTimestampUTC": "2023-08-02T01:19:32.815842",
"currentTimestampWithTimeZone": "2023-08-01T22:19:32.815842-03:00",
"currentTimestampWithoutTimeZone": "2023-08-01T22:19:32.815842"
}
]
}
}
```
=> graphql-server: New endpoint to get server current_time

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx, bigbluebutton-html5/imports/ui/services/features/index.js, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- "actions" label in presentation uploader will always be displayed
- splits disabled download of presentation params (allowDownloadable -> allowDownloadOriginal and allowDownloadWithAnnotations)
- only hide download presentation dropdown if both download presentation options are disabled
Closes #18408
=> fix: Disabling the presentation download with annotation is also disabling the original presentation download

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addBulkGroupChatMsgs.js
The refactoring in 838accf0158f1ecf0fdf60c6319d200a98ab9106 incorrectly replaced the wrong `parseMessage()` function in `addBulkGroupChatMsgs.js`
This bug is only triggered when the option `public.chat.bufferChatInsertsMs` does not equal `0`.
This also needs to be fixed in `v2.7.x-release`
Fixes #18429
=> fix: do not escape text twice

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.js
This PR better adjusts the margin of talking indicator element.
=> style: Margin of talking indicator adjusted to better fitting size

bigbluebutton-tests/playwright/core/settings.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/presentation/presentation.js, bigbluebutton-tests/playwright/presentation/presentation.spec.js
Changes two tests, the enable download original presentation and the download presentation with annotations.
And removed the @flaky because the tests are not failing anymore since the bug was fixed.
=> test: changes on download presentation

bigbluebutton-html5/imports/ui/components/waiting-users/guest-policy/component.jsx, bigbluebutton-html5/public/locales/en.json
Implements a notification to the guest users modal, displayed when a moderator changes the guest policy.
=> fix: Notify guest policy change

.github/workflows/automated-tests.yml, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, build/setup.sh
It stores the built packages in Github cache.
Then in the next run it can re-use the cached package if the code of that project was untouched. 
It reduces a lot the time of the building step.
<table>
<tr>
<td>
<b>Before</b> (11min on average)
<br>
Without cache
</td>
<td>
<b>After</b> (4min on average)
<br>
Using actions/cache@v3
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> ci(tests): Speed up building time by using cache

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, bigbluebutton-html5/imports/api/user-reaction/server/helpers.js
If the user selects an Reaction emoji and it automatically expires after 1 minute.
The user is not able to select exactly the same Emoji again.
This PR fix it.
=> fix (html5): Unable to choose same Reaction emoji twice in a row

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-tests/playwright/presentation/presentation.spec.js
This PR fixes two issues: the slide position being off when zooming and the synchronization error that was previously experienced when changing presentations while 'fit to width' was enabled and the slide was zoomed in.
Closes #18232 and #17982
=> fix: Correct Slide Positioning After Zoom and Sync During Presentation Change

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Fix issue with breakout settings being cut out of the modal if text is long.
Closes #18434
=> fix: Labels flowing out of a <div> in breakout rooms creation view

bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
The function `followRedirect` was supposed to obtain the final URL when the first URL is a redirect link.
Turned out that it is always returning the first URL instead of follow the redirect and return the final URL.
This PR fix it.
=> fix (bbb-web): Getting wrong final URL (from redirect) on presentation upload

bigbluebutton-config/bin/bbb-conf, build/packages-template/bbb-html5/bbb-html5-with-roles.conf
After upgrading yq to 4.x the combined yml configuration for bbb-html, bbb-webrtc-sfu and bbb-webrtc-recorder variables contain the actual yml, not the uri to the yml.
Recovered a block of code which was accidentally removed and its omission was causing a syntax error.
-----
<details>
A subsequent PR will continue the work of ...
Resending #18409
Basically, using CI to try to bypass some Mongo4.4 ->6.0 upgrade configuration changes (replica set initialization) which are blocking us from starting `bbb-html5-*` processes. This PR contains a config change which forces only one copy of the `bbb-html5-backend` process to handle both backend and frontend roles.
</details>
=> fix(bbb-conf): Handle yq upgrade related issues

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/MakePresentationDownloadReqMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/presentation/service.js
This fixes the issue where it is not possible to download the original presentation. 
Closes #18446 
As mentioned by @danielpetri1 in https://github.com/bigbluebutton/bigbluebutton/pull/18150, we changed the way we build the absolute URL for downloading the presentations due to clustering issues:
> From now on, links will be created without the need for the bbbWebBase information, letting Meteor alone handle this on the client side
This PR was already tested on a cluster environment, but any further testing is welcome!!
@schrd, if you have any suggestions, please, comment them down!! Thank you in advance!
=> fix: download of original presentation not working not working

bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx, bigbluebutton-html5/imports/ui/components/polling/service.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx, bigbluebutton-html5/imports/utils/debounce.js
Replaces radash debounce with a native function.
The existing debounce implementation (from radash) lacks support for the `leading` and `trailing` modifiers. As a result, certain inconsistencies were found in its behavior (thanks @prlanzarin!) compared to the previously used library (lodash).
=> refactor: replace debounce function

.github/workflows/automated-tests.yml
Cancel previous jobs of github-actions when push a new commit.
> Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
More info: https://docs.github.com/en/actions/using-jobs/using-concurrency
=> ci(tests): cancel previous PR runs on github-actions when push a new commit

build/packages-template/bbb-html5/systemd_start.sh, build/packages-template/bbb-html5/systemd_start_frontend.sh, build/packages-template/bbb-html5/workers-start.sh
Moves the code for initializing MongoDB replicaset outside (and before) of the `bbb-html5-backend` and `bbb-html5-frontend` process starting scripts.
Closes #none
This was triggered by the fact that MongoDB 6.x+ allows for only one replicaset initialization and back on 4.x we were initializing on the start of every bbb-html5-* service (likely unnecessarily and wrongly).
I can't yet tell if there is any drawback to this change but will know quite soon. This is a stepping stone to continue the work on installing/running BBB on Ubuntu 22.04
=> build: start replicaset once, before bbb-html5- backends frontends

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
it's been recently introduced, which displays the same `leaveAudio` data-test (used for listen-only tests) for all reaction buttons. This PR just removes this line, which should bring listen-only tests passing again
=> fix: Remove leaveAudio data-test from the reaction buttons

freeswitch.placeholder.sh
- [build(freeswitch): bump to](https://github.com/bigbluebutton/bigbluebutton/commit/a3264bb1526b6e98a31f4050bd4ac1e20718c15a) https://github.com/signalwire/freeswitch/commit/41507363 
- See https://github.com/signalwire/freeswitch/commit/41507363f3fffcdad547b168e55fbe3383a24c3d
n/a
Follow up to https://github.com/bigbluebutton/bigbluebutton/pull/18517
=> build(freeswitch): bump to signalwire/freeswitch/master@41507363

.github/workflows/automated-tests-build-package-job.yml, .github/workflows/automated-tests.yml
It will reduce duplication of code!
A new file `automated-tests-build-package-job.yml` was added, which is called by each building job of `automated-tests.yml`.
This new workflow will:
- Checkout master branch
- Merge pr branch into master branch
- Set the cache key
- Try to use cache
- Generate artifacts (if cache was not found)
- Upload artifacts (to be used by the install phase)
Inspiration: https://dev.to/n3wt0n/avoid-duplication-github-actions-reusable-workflows-3ae8
Suggested by @antobinary
=> ci(tests): Make a reusable workflow for the building phase

.github/workflows/automated-tests-build-package-job.yml, .github/workflows/automated-tests.yml
This PR:
- Makes it checkout master branch when the event is a `push` (instead of `pull_request`)
- Rename the job to improve visualization of the Actions/Summary screen
- Add `.gitlab-ci.yml` to be part of the cache-key of all packages
=> ci(tests) fix: Checkout failing when it's not a Pull Request (push event)

bigbluebutton-html5/imports/ui/components/whiteboard/service.js
This PR adds the whiteboard dropdown menu to the list of elements that are set to autohide. This ensures that the dropdown does not obstruct any slide content, especially after its position was recently changed.
the position of the whiteboard dropdown menu was moved and this change created instances where the dropdown could overlap with some of the slide content, obstructing the view for users.
=> fix: Add Whiteboard Dropdown As Element To Autohide

.github/workflows/automated-tests-build-package-job.yml
It is necessary to rebuild the caches when `build/deb-helper.sh` is changed!
=> (ci) tests: Add build/deb-helper.sh to cache key

bigbluebutton-html5/imports/ui/services/virtual-background/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Backport of #18557 to BigBlueButton 2.6
=> fix(html5): backport 'Replace wasm detection library #18557' to 2.6

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/styles.js
Adds the username to camera elements in grid mode
=> fix: display username in grid mode

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
This PR handles the inconsistent slide position between presenter and viewer when switching slides while fit to width is enabled.
related to [comment on ](https://github.com/bigbluebutton/bigbluebutton/issues/17982#issuecomment-1684213824) #17982
=> fix: Handle Slide Change With Fit To Width

bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/webcam/webcam.spec.js
- Adds the `@flaky` flag to the webcam background test preventing it from running in CI temporarily due to recent failures
=> test: Skip webcam test to run on CI

freeswitch.placeholder.sh
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/18543 to BBB 2.6
=> build(freeswitch): v1.10.10 (backport to 2.6)

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx
This PRs adds dedupe in message insertion to avoid duplicated messages on chat.
=> fix: Add dedupe to messages based on referenceId (backport of #18230 from 2.7)

build/packages-template/bbb-webrtc-sfu/after-install.sh
- [build(bbb-webrtc-sfu): use bbb-webrtc-recorder, drop kurento from config](https://github.com/bigbluebutton/bigbluebutton/commit/a3759f681f1648347b656e65a03ba1310677123b) 
- Set bbb-webrtc-recorder as the default `recordingAdapter` in bbb-webrtc-sfu by default
- Set `kurento` in SFU's config to an empty array; Kurento isn't provided by 2.8+ by default
None
=> build(bbb-webrtc-sfu): use bbb-webrtc-recorder, drop kurento from config

.github/workflows/publish-test-report.yml
Introduces a comment when the testing workflow ends informing which is the output status. If a commit is pushed when there's already a comment, the previous one will be deleted. Failed runs will contain a link to the automated tests summary check
| Passing  | Failing |
| --- | --- |
| ![Screenshot from 2023-08-11 16-28-07](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/b108a250-057c-4c77-bcc6-0c90580a62da) | ![Screenshot from 2023-08-11 16-28-18](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/6c608fd5-fb60-4efe-a16d-7be5de0f1c21) |
=> CI: Introduces automated tests output comment on PR

.github/workflows/automated-tests.yml
This PR exposes the necessary data used on the comment workflow introduced by https://github.com/bigbluebutton/bigbluebutton/pull/18633
- Skips PRs containing changes only in `bigbluebutton-html5/public/locales/*.json` files - avoiding running CI in transifex merges
- Changes `npm install` to `npm ci`
=> CI: Expose PR data for comment workflow

bigbluebutton-config/bin/bbb-conf
To be reverted when the recording services function again on 22.04
=> build: TEMP ensure CI runs on 2.8 by masking recording services

bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_camera.yaml
Allow to query aggregate functions on `user_camera`.
=> graphql-server: Allow user_camera_aggregate

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx
Adjusts self-view label so the label changes to "enable self-view" if a camera is disabled.
=> fix: disable self-view label

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts
Reimplements the "more messages below" button so the feature works with the new graphQL components.
=> fix: restore unread messages button

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- [fix: expose camera as content in mobile endpoints](https://github.com/bigbluebutton/bigbluebutton/commit/38965d100c283f72c5840fe7c8ac6b80d5060883) 
* It's actively blocked in code, but I think that's an oversight -
probably leftover from an initial iteration of the feature.
It should be useful in mobile endpoints and it's also supposed to work
seamlessly due to how the feature is implemented.
* Lift the mobile block and expose "camera as content" in the presenter's
actions dropdown.
Closes #18640
=> fix: expose camera as content in mobile endpoints

bigbluebutton-tests/playwright/presentation/presentation.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/webcam/webcam.spec.js
Fixed the test "send out presentation to chat for the download" that was failing on ci, and also added a flaky tag for the test "select one of the default backgrounds" that was also failing on ci.
=> test: failing tests on ci

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR addresses two issues related to slide zoom functionality:
- It prevents the slide position from breaking when using mouse wheel zoom.
- It ensures the zoom value displayed on the presentation toolbar updates correctly when switching between slides.
Closes #18645
=> fix: Mouse Wheel Zoom Disrupting Slide Position

bbb-graphql-server/install-hasura.sh, build/packages-template/bbb-graphql-server/after-install.sh, build/packages-template/bbb-graphql-server/after-remove.sh, build/packages-template/bbb-graphql-server/build.sh
- Upgrade Hasura version to 2.32.1 (we were stuck on 2.29+ because newer versions requires Ubuntu 22)
- Test copying only hasura-cli binary instead of the whole `node_modules/hasura-cli/`  dir
=> graphql-server: Upgrade Hasura to version 2.32.1 and change hasura-cli path

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/popup-content/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/chat-list-item/styles.ts, bigbluebutton-html5/public/locales/en.json
Fixes the following issues and warnings:
- adjusts chat list item border
- add close button label in welcome message popup
- fix getcontentanchorel typo
- fix `size` prop type in emoji component
=> fix: 2.8 warnings

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/DatabaseConnection.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPageCursorDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/update_graphql_data.sh
- Count as unread message only messages sent after `user.registeredOn` time
- Remove log when inserting `pres_page_cursor`, it was flooding akka-apps logs
- Initialize Postgres connection right away when Akka-apps starts (the first meeting was taking longer to initialize because there were no connections ready)
- Add a delay 2 seconds to run `hasura metadata apply` (to prevent errors where the service didn't initialize)
=> refactor (graphql-server): General improvements related to Graphql

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/styles.ts
A follow up to #18675, this PR:
- adds missing `key` to message list wrapper
- restores active styles in userlist actions button
before:
after:
=> fix: 2.8 warnings and missing styles

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
Fix userlist styles in RTL languages
=> fix: userlist styles in rtl lang

build/packages-template/bbb-etherpad/build.sh, build/packages-template/bbb-export-annotations/build.sh, build/packages-template/bbb-pads/build.sh, build/packages-template/bbb-webhooks/build.sh, build/packages-template/bbb-webrtc-sfu/build.sh
Closes # none
Related #18680 
Without this step existing BigBlueButton 2.6 servers will upgrade to 2.6.14 fine but the system NodeJS installed and used for our packages will remain v16.
With this change, the following message will be displayed and will block the install 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
bbb-export-annotations : Depends: nodejs (>= 18)
E: Unable to correct problems, you have held broken packages.
```
=> !build: require node 18 to install bbb packages

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/services.ts
Adjusts export chat function so it works if the chat has been cleared.
=> fix: save/copy chat if chat has been cleared

build/packages-template/bbb-etherpad/build.sh, build/packages-template/bbb-export-annotations/build.sh, build/packages-template/bbb-pads/build.sh, build/packages-template/bbb-webhooks/build.sh, build/packages-template/bbb-webrtc-sfu/build.sh
Fixes a copy-paste error -- correcting the upper boundary for accepted `nodejs` version in packages. Thanks @schrd for spotting and reporting this!
Closes #none
Related to #18686
=> build: fix nodejs version paste error in #18686

scripts/code-review/checkout-to-pr.sh
Fixes the `./scripts/code-review/checkout-to-pr.sh` parameter count check, that was using `! > 0`.
Now it uses the syntax `-le` that correctly applies the check and also have better readability.
=> Fix parameter check on checkout-to-pr script

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/LiveSelection.tsx, bigbluebutton-html5/imports/ui/components/audio/captions/button/component.jsx, bigbluebutton-html5/imports/ui/components/common/menu/component.jsx, bigbluebutton-html5/imports/ui/components/common/menu/menuTypes.ts, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx
It adds the option `isSeparator` to the `BBBMenu` items so that it enhances readability in the code.
Not only it will enhance readability but it will also give us another type of item to work with in the menus. It will specially be useful for PR https://github.com/bigbluebutton/bigbluebutton/pull/18607 where one of the possible menu items the plugin developer can choose is the separator itself.
Below we have some screenshots of the new menus on the following order:
`develop` branch -> `refactor-bbb-menu` branch
Actions dropdown menu
Audio control menu
Captions menu
Settings dropdown menu
User list dropdown item - nested item
User list options dropdown menu
=> refactor: add isSeparator option as a menu item

package-lock.json
In PR #18454 a `package-lock.json` file was added by mistake.
This doesn't cause any issue, but the file should not be there.
This pull request removes this file.
=> Remove package-lock.json from main directory

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/externalvideo/StopExternalVideoPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ExternalVideoDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_externalVideo.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_external_video.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Some enhancements on the database schema of `externalVideo` in graphql-server:
- new query
```gql
subscription {
externalVideo {
externalVideoId
externalVideoUrl
playerCurrentTime
playerPlaybackRate
playerPlaying
startedSharingAt
stoppedSharingAt
updatedAt
} 
}
```
- new result
```json
{
"data": {
"externalVideo": [
{
"externalVideoId": "1694030652352-hyagul55",
"externalVideoUrl": "https://youtu.be/WLqpjAM?si=ZfX0-urN3W0",
"playerCurrentTime": 24,
"playerPlaybackRate": 1,
"playerPlaying": false,
"startedSharingAt": "2023-09-06T20:04:12.372+00:00",
"stoppedSharingAt": null,
"updatedAt": "2023-09-06T20:16:08.144+00:00"
}
]
}
}
```
It is ready for the refactor of the client, a few instructions for the client refactor:
- Calc the player current time based on `updatedAt` + …
=> refactor (graphql-server): ExternalVideo data schema enhanced

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
Adjust reactions button icon and styles when raise hand is active.
Closes #18696
=> fix: Raised hand button incorrect state

record-and-playback/core/lib/recordandplayback/edl.rb, record-and-playback/core/scripts/archive/archive.rb
- [fix(recording): handle archive remux failures](https://github.com/bigbluebutton/bigbluebutton/commit/286434e833f62a059c3d3a6a3ec74587b48a590c) 
* Recording archive may fail when remuxing invalid files from KMS or the
new recorder - eg when the raw files are 0-byte sized.
* This commit handles the exception raised by EDL::encode so archive keeps
going, logs the issue as a warning and archives the problematic file anyways.
* EDL::encode now removes the temporary file when the ffmpeg command execution
fails - this should avoid leaving any stale files around in case of failure
* No specific check for the nature of the error is done - the idea is that
subsequent phases will discard or fix the files if necessary according
to the processing scripts' necessities, making the behavior (in this …
=> fix(recording): handle archive remux failures

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
=> fix: remove lodash

.github/workflows/ts-code-compilation.yml, .github/workflows/ts-code-validation.yml
It will ignore the Typescript related workflows when no TS/TSX files was changed.
And it will monitor only the directory `bigbluebutton-html5`.
=> refactor (Github Actions): Run typescript workflows only when ts/tsx within bbb-html5 was modified

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
backport (from https://github.com/bigbluebutton/bigbluebutton/pull/18675) for the emoji prop warning fix:
=> fix: size prop type warning

bigbluebutton-html5/imports/ui/components/audio/container.jsx
It basically fixes the `videoPreview` crashing when `userdata-bbb_auto_share_webcam=true` and the user clicks on `Start Sharing`.
Closes #18736
=> fix: videoPreview not working

bbb-webrtc-recorder.placeholder.sh, bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.12.0-beta.1](https://github.com/bigbluebutton/bigbluebutton/pull/18669/commits/8dbe6ae8fc1115f2ae43fa92693aa570b19c666b) 
* feat: add recordingFallbackOnFailure option
* feat: improve recording retry and recovery, add carbon copies
* feat(recorder): add keep-alive and handle crashes/shutdowns
* feat: new metrics
- sfu_video_recorder_status
- sfu_video_recorder_restarts_total
- sfu_video_recording_errors_total
- sfu_screenshare_recorder_status
- sfu_screenshare_recorder_restarts_total
- sfu_screenshare_recording_errors_total
* fix(video): log start failures in VideoManager
* fix(mediasoup): propagate conference-media-specs to router settings
* build(mediasoup): 3.12.10
- [build(bbb-webrtc-recorder): v0.5.1](https://github.com/bigbluebutton/bigbluebutton/pull/186 …
=> build(bbb-webrtc-sfu): v2.12.0-beta.1, build(bbb-webrtc-recorder): v0.5.1

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Prevents a crash caused by incorrect value for logoutUrl being set on join.
Closes #18767
=> fix: incorrect set logoutUrl in join handler

build/packages-template/bbb-graphql-server/after-install.sh
The package `bbb-graphql-server` (Hasura) is failing during bbb-install, then it try again and the second attempt works.
It happens because hasura-cli try to apply metadata before the server is ready:
Including a delay of 2 seconds to run `/usr/local/bin/hasura metadata apply` must tackle the issue.
=> fix(build): Hasura installation fails on its first attempt

build/packages-template/bbb-transcription-controller/build.sh
Fixes accidential packaging of `.git` for the `bbb-transcription-controller` package.
`Note:` Please test this before merging. It should work, but the new 2.7 build environment doesn't work here yet, so I didn't have a chance to test.
=> fix(build): do not package .git for bbb-transcription-controller

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/install-hasura.sh, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_ref.yaml, bbb-graphql-server/update_graphql_data.sh, bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts, build/packages-template/bbb-graphql-server/after-install.sh
The userlist is being sorted wrongly because of Upper/Lowercase and Accents chars.
This PR fix this problem:
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Moreover:
- **Collate C.UTF-8**: On creating `bbb_graphql` database set `LC_COLLATE 'C.UTF-8'` - forcing the database to behave in same way independently of the server locale
- **`nameSortable`**: Add a new indexed column `nameSortable` to `user` table, which is the `name` in lowercase and without accents, meant for sorting
=> fix (graphql): Userlist sorting uppercase wrongly (introduces user.nameSortable)

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts
Adjusts chat styles so line breaks are correctly displayed in `p` and `code` elements.
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/835e14c1-afe8-488a-bc57-85e74371b56e
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/f03c05cc-5cf6-4208-b8ec-502098a370e3
=> fix: markdown line breaks

build/packages-template/bbb-webhooks/after-install.sh
Sets the correct salt + url for bbb-webhooks
Closes https://github.com/bigbluebutton/bigbluebutton/issues/18740
We were using bigbluebutton.properties rather than /etc/bigbluebutton/bbb-web.properties. I was trying to think of scenarios where `bbb-conf` does not exist at the time of `bbb-webhooks` installation, but can't think of one.
Credits: @snadal for suggesting this in https://github.com/bigbluebutton/bigbluebutton/issues/18740#issuecomment-1710605206
=> build: bbb-webhooks set secret and url

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/styles.ts
This PR adds the white color to welcome message background.
Example:
=> Fix: Welcome message transparent background

.github/workflows/automated-tests.yml
In the automated tests since PR #18426, the build phase monitors specific directories for each package to determine a `CACHE_KEY` based on the last commit in those directories. 
The build process utilizes code from `build/packages-template/$PACKAGE_NAME` to generate the artifact.
To ensure accuracy and consistency, it's crucial that the cache is refreshed whenever there are changes in a package's build directory. 
This pull request ensures that a new cache is generated whenever modifications are detected in the respective build directory.
For instance:
If the file `build/packages-template/bbb-fsesl-akka/build.sh` was changed in the current PR, it will obtain a new `CACHE_CACHE` and therefore will run the build for `bbb-fsesl-akka` instead of use the cache of any previous PR.
=> ci: Refresh package's cache whenever there are changes in its build directory

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts
Fix regression of user name appearing on top of user avatar when `avatarURL` is provided
=> fix: user name on top of avatar

bbb-libreoffice/docker/Dockerfile
Building the Docker image that runs Libreoffice (for conversions) was quite time-consuming. Specifically, the phase involving the installation of Libreoffice into the container running Alpine took a while.
```
FROM amazoncorretto:17-alpine
RUN apk add fontconfig libreoffice
```
To decrease this installation time, we created a new Docker image. This updated image comes with both Alpine and Libreoffice pre-installed. This is a departure from the previous approach, where the Docker image was first downloaded with just Alpine, and then Libreoffice was added in a subsequent step. This modification significantly cuts down the installation time.
<table>
<tr>
<td>Before (~2m43s)</td>
<td>After (~22s)</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
New Docker Image: …
=> refactor(bbb-libreoffice): Switch Docker image to use the one built by BBB (reducing install time significantly)

bbb-graphql-server/update_graphql_data.sh, build/packages-template/bbb-graphql-server/after-install.sh
This PR introduces 3 tweaks:
- Adds the param `with (force)` in order to avoid the error `database "bbb_graphql" is being accessed by other users`
<table><tr><td>
</td></tr></table>
https://www.postgresql.org/docs/current/sql-dropdatabase.html
It requires PostgreSQL >= 13 (by default BBB installs v14.9)
- Remove the param `-a` to reduce logs
<table><tr><td>
</td></tr></table>
- Include the param `-q` to reduce logs
<table><tr><td>
</td></tr></table>
https://www.postgresql.org/docs/current/app-psql.html
=> refactor (graphql-server): Improves build script

build/packages-template/bbb-html5/workers-start.sh
Fix Automated tests that was very often failing on step `Install BBB`
=> fix (html5): tweak func that waits for port 27017 to be ready before init replicaset

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/styles.ts
This PR fixes an unexpected behaviour introduced in the 3.0 migration, where the mute button was moving to the right.
=> Fix: Mute button moving right

bbb-graphql-server/bbb_schema.sql
For now it's hard coded 5 seconds.
In the future it will get the time from client config `public.captions.time` (After #18712).
Necessary for #18822
=> refactor (graphql-server): Expire audio caption after 5 seconds

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Updates smile2emoji dependency to the latest version in order to fix a bug with some strings being incorrectly replaced.
Closes #18808
=> fix: String substitution whenever the word constructor is typed in general chat

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
Adjusts cameraDock margin in smart layout for RTL languages.
Closes #18816
=> fix: RTL on mobile - webcam not centered

bigbluebutton-html5/imports/ui/Types/user.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
Add user reactions in the userlist
=> fix: user reactions do not appear in userlist

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.js
Adjusts webcam dropdown chevron position in RTL languages.
=> fix: video dropdown chevron in rtl

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/RemovePresentationPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPresentationDAO.scala
Deletes presentations from the Postgres when the presentation has been removed from a meeting.
Previously when a presentation was removed from a meeting the presentation would remain in Postgres instead of also being removed there.
=> Delete presentation from Postgres when presentation is removed

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/UpdateBreakoutRoomsTimeMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala
Fix the following prop:
```gql
subscription {
meeting {
duration
}
}
```
=> fix (graphql-server): Meeting duration not updating when breakout rooms receive a new time

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
This PR fixes the bug reported on issue number #18861 
Userlist after fix:
#18861
=> Fix: [3.0] Scrolling down the user list to the end will jump to the beginning

bbb-graphql-actions-adapter-server/src/actions/sendGroupChatMsg.ts
Fix errors identified by Automated Tests related with unlocked users sending chat messages:
Thanks a lot for testing team @antonbsa @gabriellpr. It's a really edge case which would be really hard to find without Automated tests.
=> fix (graphql-actions): Unlocked users can't send chat message

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserEmojiCmdMsgHdlr.scala
Closes #18574 
I was not able to reproduce the problem.
Considering that "We haven't had any reports from users about problems with the emoji selector".
I just improved the code to avoid running the function when the user is not found.
It will prevent from getting this error again.
=> fix (akka-apps): None.get error on change user Emoji

record-and-playback/core/lib/recordandplayback/edl/audio.rb
This is a refinement of the fix introduced in 3c1a9cd7c4.
Further investigation of the issue reveals that the cause of the bad timestamps which result in error messages or hang is when the `apad` filter does not receive any input audio frames. This happens if the seekpoint is after the end of audio. The existing seekpoint checks can't cover this, because in a deskshare file the video stream can continue on after the audio stream ends.
The `,asetpts=N` filter was added to deal with this problem, and it works in most cases. But there is a case where it fails - when the "mismatched length" audio stretching to work around broken recordings from BigBlueButton 0.81/0.90 kicks in.
The issue there is that the `atrim=start=S` filter (used due to the difficulty of calculating seeks when stretching) …
=> fix(recording): Deskshare audio processing hang

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
Adds the `endAllBreakoutRooms` call to `checkIfNeedToEndMeetingWhenNoModerators` so that when a meeting has been ended because there are no moderators the breakout rooms will also be ended as well.
Closes #18876
=> fix: End breakout rooms when ENDED_DUE_TO_NO_MODERATOR

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
This PR adds bounds to the presentation zoom changer to ensure that the zoom value remains within an acceptable range.
Closes #18837
=> fix: Add Bounds to Presentation Zoom Changer

bbb-export-annotations/deploy.sh, bbb-export-annotations/run-dev.sh, bbb-graphql-actions-adapter-server/deploy.sh, bbb-graphql-actions-adapter-server/run-dev.sh, bbb-graphql-middleware/install-graphql-middleware.sh
In order to facilitate the development environment, I added some useful scripts:
- `bbb-export-annotations/deploy.sh`
- `bbb-export-annotations/run-dev.sh`
- `bbb-graphql-actions-adapter-server/deploy.sh`
- `bbb-graphql-actions-adapter-server/run-dev.sh`
This scripts are becoming default for every application:
- `run-dev.sh` : Stops the service and execute the application
- `deploy.sh`: Build a new version of the application, copy to the service directory, and restart the service
=> Add new shell scripts useful for development

docs/docs/administration/customize.md
This script makes it easy for a BigBlueButton administrator to enable the `bbb-presentation-video` format.
=> Add script to easily setup video recording format

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
This PR fixes the chat input losing focus after typing + enter.
Example:
=> Fix: Chat input losing focus.

akka-bbb-apps/project/Dependencies.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingClientSettingsDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PostgresProfile.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationHistoryDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/LiveMeeting.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/RunningMeeting.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/RunningMeetings.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_clientSettings.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
**Description**:
- Introduces a new GraphQL Type named `meeting_clientSettings`.
- Includes a field called `clientSettingsJson`.
**Motivation**:
This change allows clients to fetch their settings directly via GraphQL, serving as an alternative to the existing method that relies on `Meteor.settings` (which sources from a yml config file).
----
**`meeting.clientSettings`**:
The field will also be available inside the Type `meeting`:
```gql
subscription {
meeting {
meetingId
clientSettings {
clientSettingsJson
}
}
}
```
----
**Querying only specific setting property**:
It's also possible to query directly the Type `meeting_clientSettings` and bring only a specific field from the settings.
This example query only `appName` and `paginationSorting` instead of query the whole json of settings …
=> graphql: Client Settings Retrieval through Graphql

bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
Changes the regex pattern for parsing presentation SVG page sizes to include decimal numbers.
Presentation page sizes were failing to be parsed when the values for `height` and `width` were decimal numbers instead of integer numbers.
=> fix: Page dimension parse error with decimal numbers 

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
Fix `A` letter appearing on top of user avatar when avatarURL is provided
=> fix: remove "a" in user avatar

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/MakePresentationDownloadReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPageDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPresentationDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_page.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_page_curr.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_presentation.yaml
Rename the following props:
| Before  | After | Detail |
|--------|--------|--------|
| numPages  | totalPages |
| pagesUploaded  | totalPagesUploaded |
|  | uploadCompleted | not changed |
| converting  | uploadInProgress |
| errorMsgKey  | uploadErrorMsgKey |
| errorDetails  | uploadErrorDetailsJson | (type changed to jsonb) |
|  | exportToChatInProgress | new prop |
|  | exportToChatStatus | new prop |
|  | exportToChatCurrentPage | new prop |
|  | exportToChatHasError | new prop |
| Before  | After | Detail |
|--------|--------|--------|
| converted  | uploadCompleted |
| urls  | urlsJson | (type changed to jsonb) |
=> graphql: refactor presentation props

bbb-common-web/src/main/java/org/bigbluebutton/presentation/handlers/Png2SvgConversionHandler.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, build/packages-template/bbb-web/opts-jammy.sh
Currently the option "Convert notes to presentation" is not working when the notes contain Emojis:
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/577965b6-ee4f-47de-aa35-37e9ac0c735a
This PR adds a log to inform which error occured during the command `convert /tmp/test.png /tmp/test1.svg`.
This log helped to identify the error:
The error is: `convert-im6.q16: delegate failed 'potrace' --svg --output '%o' '%i'' @ error/delegate.c/InvokeDelegate/1966.`.
The error is from the ImageMagick convert command, specifically its inability to handle the conversion process due to a missing delegate. Delegates in ImageMagick are external programs that ImageMagick uses to handle formats it doesn't natively support. In this case, it's trying to use 'potrace' for the conversion to SVG and …
=> fix: "Convert notes to presentation" not working when it contains emojis

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPageConvertedSysMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPresentationDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/PresentationPods.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Presentation.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
Sends the text content of each presentation from `bbb-web` to `akka-apps` so that it can be stored in Postgres.
Currently the BBB client parses a presentation's text content from the `txtUri` that is associated with each page in the presentation. Instead of doing this `bbb-web` now directly sends the text content of each page to `akka-apps` to be stored in Postgres so that it can be accessed directly by the client.
=> refactor: Store presentation text content in Postgres

bbb-libreoffice/docker/Dockerfile
=> build(bbb-libreoffice): Switch the LibreOffice Docker image to use the one built by BBB (backport to 2.7)

bbb-libreoffice/docker/Dockerfile
Upgrades LibreOffice (used for document conversion) from 7.3.7.2 to 7.5.7.1
Closes #none
https://nvd.nist.gov/vuln/detail/CVE-2023-4863
Quoting from @GhaziTriki 's response on https://groups.google.com/g/bigbluebutton-dev/c/9zdWgkM1c6o
>LIbreoffice has been patched on September 2023 https://9to5linux.com/libreoffice-7-6-2-and-7-5-7-released-to-address-critical-webp-vulnerability
>Libreoffice in BBB is a kind of jail and has access to only a necessary amount of computing resources.
>More investigation about the current version is needed, but I assume that updating the LibreOffice docker image in BBB should be safe.
=> (sec)build(bbb-libreoffice): bump to 7.5.7.1

bbb-common-web/src/main/java/org/bigbluebutton/api/Util.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/MimeTypeUtils.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedFileTypes.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
It basically implements the pre-upload presentation via GET, so now it is possible to pass a download URL to the create endpoint.
The behavior now is: if one passes in `preUploadedPresentation`, then this presentation will override the `default.pdf`, since `preUploadedPresentationOverrideDefault=true` by default in the `application.properties`. To avoid that, it is necessary to also send in `preUploadedPresentationOverrideDefault=false`.
Closes #18924 
Notice that all requirements of precedence are respected. 
**Naming discussion:**
One of the main concerns when doing this feature was how to name the presentation sent in the parameter, when the only thing we have is the URL to access it. It can be of the form:
```
<host>/presentation-name.pdf
<host>/presentation-name.pdf?query1=1 …
```
=> feature (api): Add preUploadedPresentation param to API's /create via GET

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fix the check for presence of parentMeetingID when isBreakout is true. There were two problems:
1. The first part of the if-clause would always be true when isBreakout was set to any value. It should only be true when isBreakout is passed as true. This is achieved by checking ` isBreakout == "true"`.
2. The second part of the if-clause used the parameter "parentIdMeetingId", but the correct parameter according to API Docs is parentMeetingID . The parameter has been renamed appropriately.
For more details on the effect of these problems see the linked issue.
Closes #18961
=> fix: check for presence of parentMeetingID if isBreakout is true

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Performs a check when creating a breakout room through the API to see if the parent meeting exists.
Currently no check is done to see if the meeting corresponding to the provided `parentMeetingID` actually exists which can lead to an error.
=> fix (bbb-web): Null pointer exception when parent meeting does not exist

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
The previous PR #18765 did not fix the issue. So this PR fixes it by using a better strategy where the centralization is achieved with display flex, align-items and justify-content.
Closes #18763
=> fix(user-list): center icons on apple devices

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
Give/remove whiteboard access was not being updated correctly
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/c9c5d696-f3f5-4995-b865-7759395b04fa
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/b1a17044-c62b-4714-a77d-51bb4f234886
=> fix: whiteboard access label in userlist

bbb-learning-dashboard/src/components/PollsTable.jsx
This PR fixes the bug where poll answers in other languages were not being translated to client language.
After fix:
#18919
=> Fix: Poll answers not being translated in learning dashboard

akka-bbb-apps/src/main/scala/org/bigbluebutton/ClientSettings.scala
Just a hot fix correcting the path of plugins in akka
=> fix (akka-apps / plugins): path for plugin in data channel validation

bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-data-channel/container.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-data-channel/dataChannelItemManager/container.tsx
It fixes the data channel dispatcher function after being bundled.
When bundled, the data channel dispatcher function didn't work as it did in development mode.
Closely related to: https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/46
=> feat(plugin) - fix data channel dispatcher

bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-hooks-handler/container.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-hooks-handler/use-users-overview/container.tsx, bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
It adds support for the new hook `useUsersOverview`, though it doesn't include a new plugin sample specially made for it. The sample it is included is the `SampleActionsBarPlugin`, which just logs a message in the console with all the users in it.
Closely related to https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/47
=> feat(plugin): New Hook useUsersOverview

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
This PR fixes a big where the chat poll results were being cut off.
Examples: 
Before:
After:
=> Fix: Chat poll results being cut off

bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/styles.ts
This PR adds some margin so the talking indicator doesn't get too close to user list button.
=> Fix: Talking indicador too close from user list button

bigbluebutton-html5/imports/utils/throttle.js
Backports 3.0 fixes to the throttle function (#18857 + #19048)
Closes #19011
=> fix: Waiting room indicator sound defective

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/SwitchTimerReqMsgHdlr.scala
Following the behavior of 2.7.
=> fix (akka-apps): Automatically reset values upon switching between Stopwatch and Timer

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
- Adds a new menu item in the "options" menu, that opens the Manage Layouts modal.
- Removes the Manage Layouts menu item from the "+" menu for viewers, keeping it for moderators and presenter
Closes #19052
=> refactor: Move manage layouts to three-dots menu

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/common/button/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/styled-components/palette.js, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json, docs/docs/administration/customize.md
Introduces join parameter `userdata-bbb_direct_leave_button` and also an entry for `public.app.defaultSettings.application.directLeaveButton: false` such that 
if `true`:
An extra button will appear immediately to the left of the three-dots menu. The icon will be the same as the existing leave icon. The background will be red ('danger'). Clicking on this button will act the same way as clicking on the existing button today in the three dots menu.
If `false` (or if no such parameter passed) (i.e. default) - the leave button will be in the list of options opened by the three dots button.
Closes #12614
=> feat: leave meeting button

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts, bigbluebutton-html5/imports/ui/core/hooks/createUseSubscription.ts, bigbluebutton-html5/imports/ui/core/hooks/useCurrentPresentation.ts, bigbluebutton-html5/imports/ui/core/hooks/useCurrentUser.ts, bigbluebutton-html5/imports/ui/core/hooks/useMeeting.ts, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Following #17854 and #17992.
This PR add support for **JsonPatch** in the project `bbb-html5` through the hook `createUseSubscription`.
And make the component `ChatMessageList` make use of it.
Motivation:
- Issue #17810
- Avoid sending an entire document when only a small part has changed (reducing payload size)
- Contribute to overall network efficiency
A few advantages of this strategy was explained during the BigBlueButtonWorld 2023: https://youtu.be/2v6X8-_B3lk?t=1207
=> refactor (graphql/html5): Make chat receive graphql data (messages) using Json Patch

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
Makes raise hand shortcut work with the new reactions bar
Closes #18937
=> fix: The shortcut for raising hand is not functioning as expected @ 2.7.1

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
* [fix: specify a unique mock authToken for dial-in users](https://github.com/bigbluebutton/bigbluebutton/commit/2f12992c20b0350bd7581e9d910416a229f0b108) 
- Every dial in user has its RegistedUser authToken set to an empty string.
Since authToken is the RegUser's HashMap indexing key, this causes a
bunch of inconsistencies; eg.: endpoint ejection will stop working if
more than one dial-in user joined a single meeting because the
later dial-in devices overwrite the earlier ones in the RegUsers map.
- The authToken is now mocked as the user's intId (which, for dial-in, is
the voice user ID) so that some sort of uniqueness is guaranteed within
the voice conf scope.
* [fix: reversed userColor and avatar args in dial-in user creation](https://github.com/bigbluebutton/bigbluebutton/commit/c6ccb …
=> fix: specify a unique mock authToken for dial-in users, +

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
Fix for an issue with the whiteboard access icon (multi user whiteboard) not being removed if the presentation page is changed
=> fix: whiteboard access icon in userlist

bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.js, docs/docs/administration/customize.md
This PR is merging some 27 changes into 30.
Those being:
- fix: RTL on mobile - webcam not centered - [18851](https://github.com/bigbluebutton/bigbluebutton/pull/18851)
- fix: video dropdown chevron in rtl - [18872](https://github.com/bigbluebutton/bigbluebutton/pull/18872)
- docs: add notes on how to tweak screen sharing quality - [18884](https://github.com/bigbluebutton/bigbluebutton/pull/18884)
- fix: Add Bounds to Presentation Zoom Changer - [18887](https://github.com/bigbluebutton/bigbluebutton/pull/18887)
=> v27 changes ported to v30 part 1.

bigbluebutton-html5/imports/ui/Types/hook.ts, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/component.tsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-typing-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-hooks-handler/use-current-presentation/container.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/plugin-hooks-handler/use-current-user/container.tsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/guest-panel-opener/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx, bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/component.tsx, bigbluebutton-html5/imports/ui/core/hooks/createUseSubscription.ts, bigbluebutton-html5/imports/ui/core/hooks/useChat.ts, bigbluebutton-html5/imports/ui/core/hooks/useCurrentPresentation.ts, bigbluebutton-html5/imports/ui/core/hooks/useCurrentUser.ts, bigbluebutton-html5/imports/ui/core/hooks/useMeeting.ts
It changes the return type of the graphql data hooks. 
It will contain more information such as error that can possibly happen, whether it is still loading the data... In addition to that, it will also fit the return type expected for the new plugin hooks architecture, which will have the error object and load information as well.
=> feature(html5): Change return type of the graphql data hook

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserAwayReqMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/core/enums/chat.ts
Inserts a chat message from the system into Postgres when a user changes their away status. 
When a user's away status changes a message should be sent in chat to notify other users of this change.
=> Refactor: Add chat message to Postgres when user status changes 

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserConnectionStatusDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, bbb-graphql-client-test/src/App.js, bbb-graphql-client-test/src/MyInfo.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
This PR introduces a streamlined flow for users to join meetings using GraphQL mutations.
- **GraphQL Connection Without Authentication:** Users can now establish a GraphQL connection without needing to authenticate or join first. This change is facilitated by introducing a new role:
- `pre_join_bbb_client`: Assigned to users before they join the meeting.
The `pre_join_bbb_client` role is limited to the following operations:
1. **Subscription for Current User Status:**
Allows users to check their current status.
```gql
subscription {
user_current {
userId
name
joined
joinErrorCode
joinErrorMessage
}
}
```
2. **Mutation for Joining the Meeting:**
Enables users to join the meeting.
```gql
mutation UserJoin($authToken: String!, $clientType: String!) {
userJoin(
authToken: $authToken, …
```
=> graphql: New User Flow for Joining Meetings via GraphQL

bigbluebutton-tests/playwright/user/user.spec.js
Removes the flaky flag for tests that have issues resolved.
* Remove user
* Lock See other viewer's webcams
* Lock see other viewer's annotations
=> test: Removes flaky flags

bigbluebutton-html5/imports/ui/components/raisehand-notifier/component.jsx, bigbluebutton-tests/playwright/user/user.spec.js
This PR fixes the bug where the Moderator can't lower hands by clicking the avatr in the modal.
As provided on the original PR by myself. - https://github.com/bigbluebutton/bigbluebutton/pull/18977
=> Fix: Moderator lowering hand from toast broken

build/packages-template/bbb-etherpad/settings.json
Same as #19131, but targeting `v2.7.x-release`.
=> fix: Bump Etherpad's export rate limiting (2.7)

bbb-pads.placeholder.sh
=> chore: Bump bbb-pads to 1.5.2 (backport)

bbb-playback.placeholder.sh
Backport of #19071 (and #18788) to BBB 2.6
=> chore: Bump bbb-playback to 5.0.2 (backport)

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Now it's possible to call the API `/getJoinUrl` passing a `enforceLayout` param to be appended to the generated URL.
For instance:
GET Request: 
`https://bbb30.bbb.imdt.dev/bigbluebutton/api/getJoinUrl?sessionToken=bdikzqbnorrr2qeb&enforceLayout=camerasOnly`
Return:
```json
{
"response": {
"returncode": "SUCCESS",
"message": "Join URL provided successfully.",
"url": "https://bbb30.myserver.dev/bigbluebutton/api/join?fullName=teacher+1&meetingID=random-8878255&role=MODERATOR&redirect=true&userID=w_ioptwwjej6ae&enforceLayout=camerasOnly&checksum=aaa"
}
}
``` 
Closes #19140
=> feature: Support pass param enforceLayout to Api /getJoinUrl

record-and-playback/core/lib/recordandplayback/edl/audio.rb
This pull request addresses an issue in BBB 3.0 where the recording service crashes on a fresh install, leading to retry counters accumulating into the thousands and generating large log files. The issue occurred due to incorrectly resolved merge conflicts in the recording processing scripts. 
The problematic section was aligned with the 2.7 implementation.
=>  fix(rap): Recording service crashes in BBB 3.0

bigbluebutton-web/gradle.properties
Upgrades Spring to 2.7.17 and embedded Tomcat to 9.0.82. Also versions of Grails and Groovy saw a bump.
As mentioned on the original PR by @antobinary - https://github.com/bigbluebutton/bigbluebutton/pull/18981
Some vulnerabilities were patched
- https://www.cve.org/CVERecord?id=CVE-2023-44487 -- Fix: Upgrade to org.springframework.boot:spring-boot-starter-tomcat@2.7.17
- https://www.cve.org/CVERecord?id=CVE-2023-42794 -- Fix: Upgrade to org.springframework.boot:spring-boot-starter-tomcat@2.7.17
=> chore: upgrade Spring to 2.7.17

bbb-etherpad.placeholder.sh
Upgraded Etherpad to from 1.9.3 to 1.9.4
Closes Issue(s)
Closes #
Motivation
Mostly for the Log4j and axios upgrades
More
https://github.com/ether/etherpad-lite/releases/tag/v1.9.4
As providaded in the original PR by @antobinary - https://github.com/bigbluebutton/bigbluebutton/pull/19041
=> chore: Bump Etherpad to 1.9.4

bbb-learning-dashboard/package-lock.json
Upgraded some npm dependencies that were reported vulnerable.
As mentioned in the original PR by @antobinary - https://github.com/bigbluebutton/bigbluebutton/pull/18979
=> chore: npm audit fixes for bbb-learning-dashboard

bigbluebutton-web/build.gradle, bigbluebutton-web/gradle.properties, bigbluebutton-web/gradle/wrapper/gradle-wrapper.properties
Upgrades `bbb-web` to the latest versions of Grails and Spring 5.
The purpose of this Grails upgrade is to make the transition to Grails 7 easier when it releases. The Spring upgrade is to address the vulnerabilities, [CVE-2023-20863](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-20863) and [CVE-2023-20861](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-20861) present in `spring-core` version 5.3.21.
=> chore: Upgrade Grails to 6.1

docs/docs/greenlight/v3/install.md, docs/docs/greenlight/v3/migration.md
Adds new Greenlight v3 docs for migrating local accounts from v2 -> v3
=> Greenlight v3 Docs: Add information for migrating local accounts

.github/ISSUE_TEMPLATE/docs-issue.md
Fixes typo of the word "believe" in GitHub template for creating docs issue
=> docs: Fix typo in docs issue template

docs/docs/administration/customize.md
Very minor change. Files were moved to the `assets` folder but the documentation was still referencing the old path.
=> docs: Update outdated reference to index.html path

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/cursor/component.jsx
This pull request addresses the issue of cursor movement appearing jumpy, particularly noticeable on faster servers. The aim is to enhance the cursor's motion fluidity, making it more natural and less distracting during interactive sessions.
This is achieved by adding a CSS transition property (transition: 'left 0.3s ease-out, top 0.3s ease-out') to the cursor's style.
=> fix: Add Transitions To Improve Cursor Movement Fluidity

bigbluebutton-html5/imports/ui/components/mobile-app-modal/component.jsx
This button breaks when the meeting name contains white space!
This PR fix the problem, I tested even using `/` in the name of the meeting and it's working properly now:
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/ba34ffa5-8ce9-46ff-b4b8-f6c9f84be412
=> fix: Button 'Open Tablet app' breaks when the meeting name contains white space

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts
This PR corrects the color of the listen only icon.
=> Fix: listen only wrong color

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
This PR changes user list tooltip's position to stop it from hindering the talking indicator button.
Before:
After:
=> Fix: user list tooltip hindering talking indicator

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/layout/enums.js, bigbluebutton-html5/imports/ui/components/layout/layout-manager/camerasOnly.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/participantsChatOnlyLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationOnlyLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
This PR adds 3 new layouts: "Cameras Only", "Presentation Only", and "Participants and Chat Only", as requested in issue #18879. The layouts are not visible to the user and can only be activated via custom parameters. To improve these layouts, some issues need to be addressed:
* Should the hidden features in each layout remain hidden? For example, in "Cameras Only", should controls such as displaying the user list, opening presentations, sharing screens, etc., be hidden?
* In the "Presentation Only" layout, does external video and screen sharing count as part of the presentation?
* In the "Participants and Chat Only" layout, should the components take up the entire screen?
These questions have not been resolved as they are not part of the scope of the task and are considered as …
=> Adds new layouts for specific integration scenarios

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/layout/context.jsx, bigbluebutton-html5/imports/ui/components/layout/enums.js, bigbluebutton-html5/imports/ui/components/layout/layout-manager/camerasOnly.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/participantsAndChatOnlyLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationOnlyLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
Makes the following updates to the layouts:
- renames `participantsChatOnly` to `participantsAndChatOnly`;
- moves the list of layouts that should appear in the layout modal to `/imports/ui/components/layout/enums` file
- removes empty space on top and bottom of the main area when `userdata-bbb_hide_nav_bar` and/or `userdata-bbb_hide_actions_bar` are set to true
=> layout improvements

bbb-graphql-middleware/bbb-graphql-middleware-config.env, bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/websrv/rediscli.go
The following configs was introduced via ENV VAR:
```
BBB_GRAPHQL_MIDDLEWARE_REDIS_ADDRESS=127.0.0.1:6379
BBB_GRAPHQL_MIDDLEWARE_REDIS_PASSWORD=
BBB_GRAPHQL_MIDDLEWARE_HASURA_WS=ws://127.0.0.1:8080/v1/graphql
BBB_GRAPHQL_MIDDLEWARE_LOG_LEVEL=INFO
```
=> graphql-middlware: Make graphql-middleware more configurable

bbb-graphql-actions-adapter-server/src/actions/meetingEnd.ts, bbb-graphql-actions-adapter-server/src/actions/meetingLayoutSetProps.ts, bbb-graphql-actions-adapter-server/src/actions/meetingLayoutSetSyncWithPresenterLayout.ts, bbb-graphql-actions-adapter-server/src/actions/meetingLockSettingsSetProps.ts, bbb-graphql-actions-adapter-server/src/actions/meetingRecordingSetStatus.ts, bbb-graphql-actions-adapter-server/src/actions/meetingSetMuted.ts, bbb-graphql-actions-adapter-server/src/actions/meetingSetWebcamOnlyForModerator.ts, bbb-graphql-actions-adapter-server/src/actions/userEjectCameras.ts, bbb-graphql-actions-adapter-server/src/actions/userEjectFromVoice.ts, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
```gql
mutation {
meetingEnd
}
#Depends on `allowModsToEjectCameras=true`
mutation {
userEjectCameras(
userId: "w_5ukvmnxbg5lo"
)
}
mutation {
userEjectFromVoice(
userId: "w_5ukvmnxbg5lo",
banUser: false
)
}
mutation {
meetingSetMuted(
muted: true
exceptPresenter: true
)
}
mutation {
meetingLayoutSetProps(
layout: "videoFocus",
syncWithPresenterLayout: true,
presentationIsOpen: true,
isResizing: false,
cameraPosition: "contentTop",
focusedCamera: "none",
presentationVideoRate: 0
)
}
mutation {
meetingLayoutSetSyncWithPresenterLayout(
syncWithPresenterLayout: true
)
}
mutation {
meetingLockSettingsSetProps(
disableCam: true,
disableMic: true,
disablePrivChat: false,
disablePubChat: false,
disableNotes: false,
hideUserList: false,
lockOnJoin: true,
lockOnJoinConfigurable: false, …
```
=> graphql-actions: Moderators actions 

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_guest.yaml
In favor of #19240
- Moderator get users position
```gql
{
user_guest(order_by: {positionInWaitingQueue: asc}) {
positionInWaitingQueue
user {
name
}
}
}
```
- User get his position while waiting
```gql
{
user_current {
guestStatus {
positionInWaitingQueue
}
}
}
```
=> graphql-server: Add field positionInWaitingQueue to GuestUser

docs/docs/greenlight/v3/install.md
Updated greenlight docs install.md to include instructions for usage of rake task user:set_admin_role which upgrades an existing user account to Administrator
Closes issue [#5515](https://github.com/bigbluebutton/greenlight/issues/5515) on greenlight repo
Updated greenlight repo to include the rake task and just updating the corresponding greenlight documentation here.
=> docs: updated greenlight docs to include user:set_admin_role rake task

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- Fix type `user_breakoutRoom` showing old rooms
- Makes it possible to aggregate available breakoutRooms through `user_current`
```gql
subscription {
user_current {
name
breakoutRooms_aggregate(where: {showInvitation: {_eq: true}}) {
roomsToShowInvitation: aggregate {
count
}
}
}
}
```
=> fix (graphql-server): Type user_breakoutRoom showing old rooms

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_componentsFlags.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
In order to improve Client efficiency, this PR introduce a few flags that will inform to the Client whether it is necessary to render certain components or not.
Adds a prop `componentsFlags` to Type `meeting`
```gql
subscription {
meeting {
meetingId
componentsFlags {
hasBreakoutRoom
hasExternalVideo
hasPoll
hasScreenshare
hasTimer
audioTranscriptionCaption
typedCaption
}
}
}
```
```json
{
"meetingId": "6fd958cd0c1f967f2eceda95b91b69edc9876690-1702058871500",
"componentsFlags": {
"hasBreakoutRoom": true,
"hasExternalVideo": false,
"hasPoll": false,
"hasScreenshare": false,
"hasTimer": false,
"audioTranscriptionCaption": ["fr-FR","pt-BR"],
"typedCaption": ["en"]
}
}
```
It is also possible to query the flags directly (not through `meeting.componentsFlags`)
```gql
query { …
```
=> Graphql: Introduce meeting.componentsFlags

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-graphql-middleware/graphql.nginx, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/graphql.nginx, bbb-graphql-server/metadata/allow_list.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_guest.yaml, bbb-graphql-server/metadata/query_collections.yaml, bbb-graphql-server/metadata/rest_endpoints.yaml, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts, bigbluebutton-html5/private/static/guest-wait/guest-wait.html
This PR makes Graphql provide data for guest-wait page.
In favor of: https://github.com/bigbluebutton/bigbluebutton/pull/19240
Other than that:
This PR removes the state `seatWait ("Guest waiting for a seat in the meeting.")`. This state creates confusion as there's no organized queue for when a slot becomes available. I think this is a great opportunity for a refactor: https://github.com/bigbluebutton/bigbluebutton/issues/19330
=> refactor: Refactor guest-wait page to fetch data from Hasura

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserReactionEmojiReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ClearAllUsersReactionCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserReactionTimeExpiredCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserReactionDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
Graphql was not respecting the time set on `public.userReaction.expire` for Reactions.
Required by: #19333
_Alert for development: This config should be set in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` once Akka-apps doesn´t read the config from `bigbluebutton-html5` project._
=> fix: Graphql with hard-coded reaction expire time

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PermissionCheck.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EjectUserFromBreakoutInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/Sender.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/GraphqlActionsSubscriberActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala, bbb-graphql-middleware/internal/common/SafeChannel.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/hascli/replayer/replayer.go, bbb-graphql-middleware/internal/hascli/retransmiter/retransmiter.go, bbb-graphql-middleware/internal/msgpatch/jsonpatch.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/conninithandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/rediscli.go, bbb-graphql-middleware/internal/websrv/writer/writer.go
- Change some log messages and levels in order to avoid thinking it's a system error when actually it's a normal situation.
- Rename channel names and set the same name in all places to avoid confusion (`fromBrowserToHasuraConnectionEstablishingChannel`,  `fromBrowserToHasuraChannel`,  `fromHasuraToBrowserChannel`).
- Rename `InvalidateUserGraphqlConnectionSysMsg` to `ForceUserGraphqlReconnectionSysMsg` to make it clearer that the user will not be removed but just reconnected to refresh roles.
- Rename `replayer` to `retransmiter` to make it clearer.
- Convert all go `chan interface{}` to `SafeChannel` introduced in #18895 to avoid the error bellow:
```
Nov 30 18:44:35 bbb30-load-test bbb-graphql-middleware[155748]: {"_routine":"BrowserConnectionReader","browserConnectionId":"BC0000000001" …
```
=> refactor: Graphql middleware enhancements

record-and-playback/core/scripts/bigbluebutton.yml
Sets `bbb_version` in `bigbluebutton.yml` to `3.0`, as the whiteboard shapes stored in `tldraw.json` are incompatible with earlier versions like 2.6 and 2.7 due to Tldraw having been upgraded to a newer version.
This version string will be used by other components (e.g., `bbb-playback`) to determine which Tldraw version to display.
=> recording: Bump bbb_version to 3.0 in bigbluebutton.yml

bbb-pads.placeholder.sh
Porting https://github.com/bigbluebutton/bigbluebutton/pull/19070 to v3.0.x-release
=> build: Bump bbb-pads to 1.5.2 (port from 2.7) #19070

build/packages-template/bbb-freeswitch-core/build.sh, freeswitch.placeholder.sh
Upgrades FreeSWITCH to the latest patch release to address a security advisory.
Closes #none
https://github.com/signalwire/freeswitch/security/advisories/GHSA-39gv-hq72-j6m6 security advisory
* sofia-sip had to be upgraded to v1.13.17 (latest) too
* libks seemed happy to also be upgraded to v2.0.3 (latest)
* spandsp could not be set to 7b0b8cf3d42b725405bcc63145de5e280265ce4e - could not build
* libwebsockets could not be set to 4.3.3 - could not build
=> build(sec): upgrade FreeSWITCH to 1.10.11 +sofia-sip +libks

bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
Closes #
Current zoom rate by wheel is too slow compared to the previous versions. It's important to be able to quickly navigate the slide in a real life lecture.
I guess the core developers will fine-tune the parameters including this one. So this PR is like my humble proposal/request.
=> [3.0a] quicker zoom by wheel

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR addresses an issue in the Whiteboard component where users experienced jitter during wheel zooming. These changes enhance the smoothness of the zoom functionality.
before:
after:
=> fix: Improve Wheel Zoom Stability

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/User.java, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/LockSettingsChanged.java, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/WebcamsOnlyForModeratorChanged.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_showUserlist.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_curr.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_history_curr.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_page_cursor.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_camera.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_public.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
This update introduces Hasura session variables to enhance query performance, particularly for validations involving `lockSettings`. Previously, queries frequently checked `lockSettings` and `userId` to determine user access to specific data, such as cursor visibility. This approach hindered query multiplexing efficiency. Now, `lockSettings` are fetched only once when the Graphql connection is established, using session variables. This reduces reliance on repetitive, resource-intensive checks. Key areas benefiting from this include:
- Userlist visibility (`lockSettings.hideUserList`)
- Cursor visibility for other viewers (`lockSettings.hideViewersCursor`)
- Annotation visibility (`lockSettings.hideViewersAnnotation`)
- Webcam access control (`webcamsOnlyForModerator`)
- Add …
=> refactor (graphql-server): Optimize Hasura Queries with Session Variables

bigbluebutton-html5/imports/ui/components/common/tooltip/bbbtip.css, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/styles.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.js
This PR removes user selection from following items to avoid inconvinient unintentional selection:
- Tooltips in general
- recording indicator
- user-actions from webcam framing
=> Fix: Removing some inconvinient user selection from certain items

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala, bbb-graphql-actions/src/actions/breakoutRoomCreate.ts
It used to be validated in the `Meteor.call('createBreakoutRoom')`, which was replaced by graphql actions.
So this validation will now be performed in Akka-apps since now it knows the client configs.
=> refactor (akka-apps): Validate number of breakout rooms in the backend

bbb-webhooks.placeholder.sh, build/packages-template/bbb-webhooks/after-install.sh, build/packages-template/bbb-webhooks/build.sh, docs/docs/development/webhooks.md
- [build(bbb-webhooks): v3.0.0-beta.3](https://github.com/bigbluebutton/bigbluebutton/commit/0368a677a6b18504bad89b0a4cb765f29fc46a12) 
- Bump bbb-webhooks to v3.0.0-beta.3. The full v3.0.x changelog can be
found at: https://github.com/bigbluebutton/bbb-webhooks/blob/v3.0.0-beta.3/CHANGELOG.md#changelog
- Transition from `npm install` to `npm ci`
- Adjust configs that changed paths (`hooks.getRaw`, `log.filename`)
- Omit `.git` directory from the final package
- [docs: adjust docs to be compatible with bbb-webhooks@v3.0.x](https://github.com/bigbluebutton/bigbluebutton/commit/8ec9b7f68f6e92303cf3a8e92356b03e3d2db73f) 
- These are minor changes to make the current bbb-webhooks documentation
page compatible with the newer bbb-webhooks@v3.0.x versions.
- It'll be further detailed with some …
=> build(bbb-webhooks): v3.0.0-beta.3

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/styles.js, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/public/locales/en.json
Adds a specific function to handle the creation of the exported presentation's toast notification that were missing.
Closes #19278
=> fix(chat): exported presentation notification

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/SendMessageToBreakoutRoomInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala, bbb-graphql-actions/src/actions/chatSendMessage.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts, bigbluebutton-html5/imports/ui/components/chat/service.js
This PR will:
- Fix: Moderators have `chatEmphasizedText = true` in private chat
- Fix: Messages is considering the current user role to set `chatEmphasizedText` (it should consider the role of the moment the msg was sent)
- Consider config `public.chat.moderatorChatEmphasized` to emphasize or not
- Make akka-apps populate `chatEmphasizedText` (instead of graphql-actions)
=> Fix and Refactor moderatorChatEmphasize

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/styles.js, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/public/locales/en.json
Adds a specific function to handle the creation of the exported presentation's toast notification that were missing.
Closes #19278
=> fix(chat): exported presentation notification (backport to 2.6)

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/startup/client/base.jsx, docs/docs/administration/customize.md
Adds a join parameter to allow for a finer control on who sees the animations -- people who explicitly enable them
Closes #none
Some users complaining about too much noise when using emoji rain. However, others still like that noise, i.e. can't just disable for all via settings.yml
Pass on join `userdata-bbb_show_animations_default=false` and you should not be seeing animations (most specifically emoji rain i.e. Reactions)
=> feat: join param for default animations setting value

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/api-version.ftlx, docs/docs/administration/cluster-proxy.md
As highlighted by @schrd in PR #19207, there's a need to modify the way we set the GraphQL WebSocket (WS) URL, especially for cluster environments.
**Initial Approach:**
- We initially planned to set the GraphQL WS URL in the `bbb-html5.yml` file. 
**Issue Identified:**
- However, the client settings will start to be fetched via GraphQL. Consequently, the client wouldn't have the correct GraphQL URL for connection, as it's supposed to retrieve this information through GraphQL itself.
**Proposed Solution:**
- To address this, we are moving the configuration of the GraphQL URL to the `bbb-web.properties` file.
- This change allows the GraphQL URL to be accessible via the API endpoint: `https://bbb30.bbb.imdt.dev/bigbluebutton/api/`.
This update ensures proper access to the GraphQL WS URL in …
=> Update GraphQL WebSocket URL Configuration for Cluster Setup

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/channel-manager/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/types.ts, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/chat/loaded-chat-messages/hook-manager.ts, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/presentations/current-presentation/hook-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/shared/custom-subscription/hook-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/users/current-user/hook-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/users/loaded-user-list/hook-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/extensible-areas/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/loader/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/loader/types.ts, bigbluebutton-html5/imports/ui/components/plugins-engine/manager.tsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
It refactors some enums and filenames to enhance readability.
Improve organization, readability and scalability
This PR is closely related to https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/64
=> feat(plugin): Refactor enums and filenames

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/19263 by also filtering the avatar when user.away or user.raiseHands are true. Before it was only done for the reactions from the reactions bar.
Closes #19263
=> Fix: away and raiseHands 'reactions' being hidden by avatar image

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, bbb-graphql-client-test/src/App.js, bbb-graphql-client-test/src/Auth.js, bbb-graphql-client-test/src/ChatMessages.js, bbb-graphql-client-test/src/ChatPublicMessages.js, bbb-graphql-client-test/src/CursorsAll.js, bbb-graphql-client-test/src/MeetingInfo.js, bbb-graphql-client-test/src/MyInfo.js, bbb-graphql-client-test/src/UserConnectionStatus.js, bbb-graphql-client-test/src/UserList.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
This PR will:
- Makes graphql provide `authToken` (necessary for joining process)
- Add an example how to handle error `Authentication hook unauthorized this request`
- Add an example of validations to redirect the user to components `guest-room`, `pre-join`, `end-meeting`, `meeting`
- fix a problem where the user received wrong Hasura-Role after leaving the meeting
This is a test using the Client-Test to perform some meeting actions:
[Screencast from 2024-01-18 10-30-25.webm](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/1cf8aea8-635b-4e89-9229-726128026729)
=> Refactor: Makes Graphql provide authToken (makes /api/enter unnecessary)

akka-bbb-apps/src/main/scala/org/bigbluebutton/ClientSettings.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/PollHdlrHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToPollReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserReactionEmojiReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala, bbb-graphql-actions/src/actions/pollSubmitUserTypedVote.ts
- Add `public.poll.maxTypedAnswerLength` validation to Backend (akka-apps)
- Akka-apps automatically check if there is a similar answer and pick its id and submit user answer
This new approach simplify the flow. Previously Meter would send one message to add the answer and another to submit the vote. Now graphql will send only one message and Akka-apps will add the answer and submit user vote.
Before:
After:
=> Refactor Poll flow for typed answer (reducing steps)

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll_option.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll_response.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll_user.yaml
- Add permission for `poll.users_aggregate`
- Add permission for `poll.responses_aggregate`
- Add permission for `poll.options_aggregate`
- Add field `createdAt` that can be used for `order_by`
```gql
subscription {
poll(order_by: {createdAt: asc}, limit: 1) {
pollId
users_aggregate {
aggregate {
count
}
}
responses_aggregate {
aggregate {
count
}
}
}
}
```
=> Refactor (graphql): Add permission to aggregate Poll users/responses

bigbluebutton-html5/imports/ui/components/mobile-app-modal/container.jsx, bigbluebutton-html5/imports/ui/components/mobile-app-modal/mobile-app-modal-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/mobile-app-modal/mobile-app-modal-graphql/styles.ts, bigbluebutton-html5/imports/ui/services/auth/index.js
Migrate mobile app modal from Meteor to GraphQL.
=> Refactor: Migrate mobile app modal component

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_sharedNotes_diff.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Now it's possible to fetch sharedNotes patch using graphql stream:
```gql
subscription MySubscription {
sharedNotes_diff_stream(batch_size: 10, cursor: {initial_value: {rev: 0}}, where: {sharedNotesExtId: {_eq: "notes"}}) {
start
end
diff
rev
}
}
```
=> Graphql provide SharedNotes diff

akka-bbb-apps/src/main/scala/org/bigbluebutton/ClientSettings.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/plugin/PluginDataChannelDeleteMessageMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/plugin/PluginDataChannelDispatchMessageMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/plugin/PluginDataChannelResetMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/plugin/PluginHdlrs.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PluginDataChannelMessageDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PluginMsgs.scala, bbb-graphql-actions/src/actions/pluginDataChannelDeleteMessage.ts, bbb-graphql-actions/src/actions/pluginDataChannelDispatchMessage.ts, bbb-graphql-actions/src/actions/pluginDataChannelReset.ts, bbb-graphql-client-test/src/PluginDataChannel.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
This PR will:
- Renames action `dispatchPluginDataChannelMessage` to `pluginDataChannelDispatchMessage`
- Adds action `pluginDataChannelReset`
```gql
mutation PluginDataChannelReset($pluginName: String!, $dataChannel: String!) {
pluginDataChannelReset(
pluginName: $pluginName,
dataChannel: $dataChannel
)
}
```
- Adds action `pluginDataChannelDeleteMessage`
```gql
mutation PluginDataChannelDeleteMessage($pluginName: String!, $dataChannel: String!, $messageId: String!) {
pluginDataChannelDeleteMessage(
pluginName: $pluginName,
dataChannel: $dataChannel,
messageId: $messageId
)
}
```
- Adds config `public.plugins.$plugin.dataChannels.deletePermission` (optional)
- Options are `moderator, presenter, all, sender`
- Adds examples on how to use it on …
=> Plugins: Add actions to Delete/Reset dataChannel messages

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/TimerModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/DeactivateTimerReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/StartTimerReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/StopTimerReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/SwitchTimerReqMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/TimerMsgs.scala, bbb-graphql-actions/src/actions/timerStop.ts, bbb-graphql-server/metadata/actions.graphql, bigbluebutton-html5/imports/ui/components/timer/component.jsx, bigbluebutton-html5/imports/ui/components/timer/container.jsx, bigbluebutton-html5/imports/ui/components/timer/mutations.jsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/component.tsx
- The accumulated prop will now be calculated on the backend, and the client will access this information via Graphql.
- Fixed an error where the timer/stopwatch continued running and did not reset upon deactivation.
- Fixed an error where the system did not reset to Stopwatch mode upon deactivation.
- Fixed an error where, when switching between Timer and Stopwatch, the timer did not stop running.
Related: #19451 #19242
=> Refactor (Timer): Shift Accumulated Time Calculation to Backend

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/settings.yml
* [fix(bbb-html5): customHeartbeat would not close stale sessions, +](https://github.com/bigbluebutton/bigbluebutton/commit/c9db859b4f0dd4e3b94588ef270e0901bb43d64f)
- This commit includes a call to the default heartbeat termination callback so sockets are correctly cleaned up when the custom heartbeat is activated. It also adds a customHeartbeatUseDataFrames config to allow controlling whether the custom heartbeat should use WS data frames as valid heartbeats as well - this should only be useful for testing/debugging purposes and the default behavior (true) is maintained.
* [fix(bbb-html5): frontend crash due to undefined vars in customHeartbeat](https://github.com/bigbluebutton/bigbluebutton/pull/19017/commits/450dda45c404f5e28e9fc77ac511f3c9aaf02814) 
- Meteor frontends may crash when …
=> fix(bbb-html5): customHeartbeat would not close stale sessions, +

bbb-webrtc-recorder.placeholder.sh
* [build(bbb-webrtc-recorder): v0.6.0](https://github.com/bigbluebutton/bigbluebutton/commit/9ba037397bd450ee3db12a40dfbc922fb44cad8f)
* feat: recorder.writeToDevNull option to write files to /dev/null (testing)
* fix: crash due to negative seqnums in sequence unwrapper
n/a
=> [2.7] build(bbb-webrtc-recorder): v0.6.0

bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/queries.jsx
This PR addresses an issue in the multi-user drawing feature related to page-switching behavior. The fix ensures that when multi-user drawing is enabled and the presenter switches to a different page, they can still see the drawings made by other users and retain control over the multi-user drawing feature.
The issue was observed when multi-user drawing was enabled: if the presenter switched to a different page, they would lose the ability to view drawings made by other users, and the controls for the multi-user feature would stop working. This meant the presenter could not toggle multi-user off until returning to the original page where multi-user was enabled.
=> Fix: Multi-User Drawing Issue When Presenter Switches Pages

record-and-playback/core/systemd/bbb-rap-caption-inbox.service, record-and-playback/core/systemd/bbb-rap-resque-worker.service
Adds Nice=19 to the service files of bbb-rap-resque-worker and bbb-caption-inbox.
Closes #
The ffmpeg calls in the recording processing services can lead to significant spikes in CPU usage, especially when called without limitation on number of threads. In high load scenarios (very large conferences), this may lead to competition for CPU resources with other, more critical, processes.
Setting a high nice level to de-prioritize the recording processing makes sense, since it is generally not critical to process these as fast as possible.
There is also a ffmpeg call within bbb-presentation-video, but it is bottlenecked and therefore doesn't lead to very high CPU usage.
Furthermore, I have a patch to set a (hardcoded) fixed number of threads to all ffmpeg calls, for input and output …
=> build: Process recordings with Niceness 19

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Currently it's impossible to know if the current user responded to an Anonymous Poll. Once Graphql doesn't provide this information. 
This PR introduces a new flag to obtain this information:
```gql
subscription {
poll {
pollId
userCurrent {
responded
}
}
}
```
Result:
```json
{
"data": {
"poll": [
{
"pollId": "62a08f9862fe4b25f54a2d181ba38c5cca23c2d8",
"userCurrent": {
"responded": false
}
}
]
}
}
```
=> Graphql: New flag to inform if current user responded to a Poll (useful for Anonymous Polls)

bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java
Port of https://github.com/bigbluebutton/bigbluebutton/commit/fd8c92714092b937dc1f099d2e9d0a72985cb738 to BBB 3.0
Fixes https://github.com/bigbluebutton/bigbluebutton/security/advisories/GHSA-j42p-fh2w-24q6 (to be published)
=> fix(sec): validate URL for external upload of presentation (port from 2.7)

bbb-export-annotations/package-lock.json, bbb-export-annotations/package.json
- Ports https://github.com/bigbluebutton/bigbluebutton/pull/19389 to BBB 3.0
- Bumps axios even further, to 1.6.5
- tweaks the limitations for npm and nodejs engine to be more permissive (to allow for `npm audit` on nodejs 20 systems)
=> chore(export-ann): bump axios etc (port from 2.7)

bbb-common-web/build.sbt
Ports https://github.com/bigbluebutton/bigbluebutton/pull/19385 to BBB 3.0
=> fix: Bump spring-boot-starter-validation to 2.7.17 to match bbb-web (port from 2.7)

bbb-graphql-middleware/internal/common/StreamCursorUtils.go, bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/hascli/retransmiter/retransmiter.go
This pull request enhances the functionality of GraphQL's subscription feature, specifically for stream-type subscriptions. In this mode, clients initiate the connection by specifying an initial cursor. GraphQL then streams data that is new or updated beyond this cursor point (https://hasura.io/docs/latest/subscriptions/postgres/streaming/index/). 
However, there's an issue when a user's role changes (e.g., gaining Presenter status). This change necessitates reestablishing their GraphQL connection to update their role, which inadvertently triggers a resend of all active subscriptions. Consequently, stream subscriptions retransmit the initial cursor, leading to the redundant transmission of previously received data.
To address this, we've implemented a middleware solution. …
=> feature (graphql-middlware): Enhancing GraphQL Stream Subscriptions: Efficient Handling of Connection Resets and Cursor Management

bbb-graphql-actions/src/actions/presAnnotationSubmit.ts, bbb-graphql-server/metadata/actions.graphql
Graphql-action `presAnnotationSubmit` expects input `annotations` with type `string`.
This PR fix it to require type `json (array)` instead.
The input will expect json array of objects containing any props, for instance:
```gql
mutation {
presAnnotationSubmit(
pageId: "378197720ae01998e297287eff2bca274b79512c-1706052526592/1"
annotations: [
{
id: "shape:Ji4QiPLuDj98XJIJ0A5h1",
annotationInfo: {
x: 401.9972451790634,
y: 269.90358126721765,
rotation: 0,
isLocked: false,
opacity: 1,
meta: {
updatedBy: "w_rjq2wjba5ccy",
createdBy: undefined,
},
id: "shape:Ji4QiPLuDj98XJIJ0A5h1",
type: "draw",
props: {
segments: [
{
type: "free",
points: [
{
x: 0,
y: 0,
z: 0.5
},
{
x: 33.06,
y: 37.47,
z: 0.5
},
{
x: 39.67,
y: 50.69,
z: 0.5
},
{
x: 57.3,
y: 70.52,
z: 0.5
},
{
x: 85.95,
y: 101.38,
z: 0.5
},
{
x: …
```
=> fix: Graphql-action to write annotations should expect type json instead of string

bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Prevents annotation subscription from being recreated.
Removes annotation data duplication.
Closes #19495
Since the GraphQL data stream sends all data on first render and then sends only updates, we don't need to use a query to grab initial annotation data.
=> fix(whiteboard): prevent annotation subscription from being recreated

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/cursor/component.jsx
Ports https://github.com/bigbluebutton/bigbluebutton/pull/19127 to BBB 3.0
=> fix: add transitions to cursors for smoothing (port from 2.7)

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
Ports https://github.com/bigbluebutton/bigbluebutton/pull/19266 to BBB 3.0
Note: the file name/path had changed and so had the content. I had to tweak the change. I tested after the tweaks and it seemed to work fine.
I used this file in GLv3 as avatar:
Before:
After:
=> fix away and raiseHands 'reactions' being hidden by avatar image

docs/docusaurus.config.js
Reverts bigbluebutton/bigbluebutton#19522 There are are consequences for the docs deploy that did not show locally. Digging deeper
=> Revert "docs: Force trailingSlash"

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_connectionStatus.yaml, bigbluebutton-html5/imports/ui/components/connection-status/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/mutations.jsx, bigbluebutton-html5/imports/ui/components/connection-status/queries.jsx
This PR introduces two distinct methods for calculating Round-Trip Time (RTT):
- `networkRttInMs`: This measures the time required for the application to send a Mutation to Hasura and receive a confirmation response. It reflects the duration taken for a round-trip network communication between the application and Hasura.
- `applicationRttInMs`: This calculation involves several steps:
- The application sends a `connectionAliveAt` timestamp to Hasura.
- The application then receives this timestamp back through a subscription.
- Following this, the application sends a confirmation back to Hasura, acknowledging the receipt of the `connectionAliveAt` timestamp.
- Hasura records the time of this acknowledgement as `userClientResponseAt` in the database.
- The RTT is calculated by comparing the …
=> Introduce `networkRttInMs` and `applicationRttInMs`

bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/hascli/retransmiter/retransmiter.go, bbb-graphql-middleware/internal/websrv/connhandler.go
When a user's role is modified, the connection between the graphql-middleware and the graphql-server (Hasura) is reset for that user. However, if a request (mutation) is sent to Hasura and no confirmation response is received, this request remains active in the Middleware. As a result, when the connection is re-established, the same request is sent again. This can lead to unexpected issues, such as the same chat message being sent twice.
To solve this, the proposed change (PR) will ensure that the connection to Hasura is not closed while awaiting a response to any pending request. Additionally, it will modify the re-transmitter, activated upon establishing a new connection, to prevent it from resending requests of the type 'Mutation'.
----
It's really hard to reproduce, I could do it by …
=> refactor (graphql-middlware): Maintain Hasura Connection During Active Mutations

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/install-hasura.sh, bbb-graphql-server/update_graphql_data.sh, build/packages-template/bbb-graphql-server/after-install.sh
Following #19104 and #19454, the system is transitioning away from using `ValidateAuthTokenReqMsg` for user authentication. In the new approach, Graphql will handle the authentication process. However, until the complete phase-out of the Meteor framework, there is a need for an interim solution to validate user authTokens. The proposed idea is to enable Meteor to query the Graphql database directly. This will allow Meteor to verify whether a user's token is valid during the transition period.
Database: `bbb_graphql`
User (read-only): `bbb_frontend`
Password: `bbb_frontend`
Allowed query:
```sql
select "meetingId", "userId" 
from v_user_connection_auth 
where "authToken" = 'yc14toemfvcx'
```
=> Graphql: Implementing Read-Only Database Access for Frontend (temporarily)

bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/writer/writer.go
As suggested by @TiagoJacobs at https://github.com/bigbluebutton/bigbluebutton/pull/19535#issuecomment-1915619510
This PR updates the middleware to halt the acceptance of new messages from the browser when it is in the process of disconnecting from the Hasura connection. 
Messages received during this period will be queued and subsequently processed once a connection to Hasura is re-established.
=> refactor (graphql-middleware): Queue Messages During Hasura Disconnection

bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/websrv/connhandler.go
During the latest development call, as highlighted by @antobinary, an issue was identified in the system. When a user is granted presenter status, they encounter a problem where they are unable to stop external video playback, among other presenter-specific functionalities.
This Pull Request (PR) addresses and resolves this issue. The root cause of the problem was identified as follows: when a user becomes a presenter, the client-side application ceases various data subscriptions. This led to an issue where, if the Hasura backend responded with data related to these subscriptions, the client's middleware no longer recognized or handled this data, as the subscriptions had been stopped. The PR contains fixes to ensure that this problem does not occur when a user is assigned presenter …
=> fix (graphql-middleware): User get Presenter status but can't stop external video

bigbluebutton-html5/imports/ui/core/graphql/queries/userVoiceSubscription.ts
Changes talking indicator order to be the same as 2.7.
Closes #19544
=> fix: Muting via who-is-talking -- queue via timestamp again

bbb-graphql-server/install-hasura.sh, bbb-graphql-server/update_graphql_data.sh, build/packages-template/bbb-graphql-server/after-install.sh
All the tables of the database are created on each server update.
So it needs to give permission for user `bbb_frontend` every time as well.
Related: #19537
=> fix (graphql-server): Give permission for bbb_frontend every time tables are created

bbb-graphql-middleware/internal/hascli/conn/reader/reader.go
Revert **`GoRoutines to manage the messages received from Hasura`** once it is better to guarantee that the messages will be delivered to browser in the correct order.
Related: #19559
=> refactor (graphq-middleware): Revert using go routine to process Hasura messages

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Restores button for hiding tldraw tools.
Closes none
=> fix(whiteboard): restore `Hide toolbars` button

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
Allows empty typed poll to be published.
Closes #19443
=> fix: [3.0] - Publishing empty typed response question crashes public chat

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Fix presentation uploader crash by not checking for annotations if the presentation is not yet uploaded.
The query used to check for annotations uses the presentationId, which includes the filename for files that are not uploaded and may cause a crash if the filename contains certain characters
Closes #19505
=> fix: Upload the exported users list to presentation breaks the whiteboard

bigbluebutton-html5/imports/ui/components/poll/styles.js
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/19536 from 3.0 to 2.7
Removes custom button styles in poll panel button.
Closes #19506
=> fix: Incorrect hover style on the upload presentation button in the polling menu (2.7)

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EjectUserFromBreakoutInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserLeftVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSessionBasicData.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/GuestPolicyValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/UserSessionValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/service/SessionService.java, bbb-graphql-client-test/src/Auth.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/actions.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_guest.yaml, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
This Pull Request addresses an issue where user sessions are immediately removed after a meeting ends. This creates a problem for users who refresh their browser and seek information about the meeting they were part of, as there's no retained information about the ended meeting or the user's involvement.
- With this PR, user sessions will now remain active for a specified duration after a meeting concludes. This allows users to access important information about their participation, including whether the meeting has ended, if they were ejected, or if they logged out.
- To avoid side effects, we introduce a new `Map` structure for storing sessions of removed users. This Map will be exclusively accessed by the Graphql AuthHook, ensuring no impact on other service authentication behaviors.
- …
=> Introducing Session Persistence Post-Meeting

bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_clientSettings.yaml
The client needs to adjust certain settings when a user has left the room. One example of these settings is `askForFeedbackOnLogout`. Therefore, it is essential to allow users to access the ClientSettings type, even if they are no longer present in the room.
It's also crucial to note that in order to connect to the GraphQL server, a valid session on the bbb-web is required. This means that the user must possess a valid `/join` link.
Related #18926
=> Graphql: Allow not-joined-users query ClientSettings

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml
It's necessary for the `meeting-end` component.
```gql
query {
meeting {
ended 
endedAt 
endedReasonCode
endedBy
endedByUserName
}
}
```
```json
{
"data": {
"meeting": [
{
"ended": true,
"endedAt": "2024-02-06T16:24:52.262+00:00",
"endedReasonCode": "ENDED_AFTER_USER_LOGGED_OUT",
"endedBy": "w_uwcx5kivyhts",
"endedByUserName": "teacher 1"
},
]
}
}
```
=> Graphql: Provide meeting ending details

bigbluebutton-html5/imports/ui/components/raisehand-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/raisehand-notifier/styles.js
This PR addresses an issue where elements are overlapping in the raise hand toast notifier. It aims to fix this problem to ensure a smoother user experience.
#18969
=> Fix: Avatar overlaping other notifications on toast area

record-and-playback/core/scripts/utils/gen_webvtt
This is a workaround for #19178 - but it does not fix the issue. The caption recording events with invalid empty `<locale/>` are simply dropped with a warning message, to allow the recording and any valid caption streams present to be processed.
This workaround also needs to be applied to 3.0; the commit is trivial to cherry-pick. It also applies to 2.6, but I'm not sure if it's important enough to be worth a new 2.6 release?
=> recording: work around invalid locale in caption events

bigbluebutton-html5/imports/ui/components/activity-check/component.jsx
This PR fixes a bug where the inactivity modal was not popping up.
#18917
=> Fix: Modal of the inactivity inspection does not show up

akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/InMessages.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserEstablishedGraphqlConnectionInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingAfterReconnectReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserGraphqlConnectionDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/GraphqlActionsSubscriberActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala, bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/go.mod, bbb-graphql-middleware/go.sum, bbb-graphql-middleware/internal/common/GlobalState.go, bbb-graphql-middleware/internal/websrv/rediscli.go, bbb-graphql-server/bbb_schema.sql
This update focuses on enhancing the system's method of tracking user connection status, as part of the broader initiative to migrate away from Meteor. Traditionally, a user's connection status was determined by their interaction with Meteor. However, this change proposes leveraging GraphQL connections for this purpose.
The essence of this pull request is to shift the basis for marking a user as disconnected from their Meteor interactions to their activity with GraphQL connections. It introduces a system that actively observes a user's engagement with GraphQL. A user's connection will be registered upon connecting through GraphQL, and should they terminate all such connections, the system will mark the user as disconnected. This status change triggers the removal of the user from the room …
=> refactor (akka-apps): Switching from Meteor to GraphQL to determine whether user is connected

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/services.ts
Restores poll results on chat export
=> fix: poll results on chat export

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
This PR aims to fix a bgu where the graphic for poll results in chat were visually incorrect.
After the fix:
=> Fix: Poll results in chat showing the wrong graphic

bigbluebutton-html5/imports/ui/components/activity-check/component.jsx
This PR fixes a bug where the inactivity modal was not popping up.
Does not close any issues in 30, but 30 has the same bug that happened in 27, mentioned in issue https://github.com/bigbluebutton/bigbluebutton/issues/18917
=> Fix: Inactivity modal

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala, bbb-learning-dashboard/src/App.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Introduces `disabledFeatures=learningDashboardDownloadSessionData`
[screen-recorder-wed-feb-14-2024-10-14-13.webm](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/e07512db-20bd-4aa2-ab49-1d5f9c85b466)
Related #14203
=> feat(config): Add option to disabled "Download session data" on Learning Dashboard

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/styles.ts
Adjusts external video z-index value so emoji rain does not go behind it
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/09f27f0d-ec9a-47b4-99a1-6bfb1f03eafc
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/953e0d9a-11be-4acb-9d1c-012f07df460f
=> fix: external video z-index

bbb-graphql-server/metadata/query_collections.yaml, bbb-graphql-server/metadata/rest_endpoints.yaml
In favor of #19507
This PR introduces a new Hasura REST endpoint `api/rest/clientStartupSettings` that will return the props used by the client before rendering the meeting itself.
- askForFeedbackOnLogout
- allowDefaultLogoutUrl
- learningDashboardBase
- fallbackLocale
- fallbackOnEmptyString
- clientLog
A similar strategy was previously used on https://github.com/bigbluebutton/bigbluebutton/blob/7d1f2a9f18a319f582e60a21dfefd37d4758eb91/bigbluebutton-html5/private/static/guest-wait/guest-wait.html#L293
How to test it:
```js
const sessionToken = 'd2c0q6nrhq7czhzn';
const GUEST_WAIT_ENDPOINT = '/api/rest/clientStartupSettings/';
const url = new URL(`${window.location.origin}${GUEST_WAIT_ENDPOINT}`);
const headers = new Headers({'X-Session-Token': sessionToken,'Content-Type': …
```
=> Create an endpoint to get client-startup-settings via REST API

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Adds onEnded event to stop video playback for all users when external video ends.
Closes #19620
=> fix: Taking the presenter plays the external video again

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Checks if a presentation object is undefined before trying to set its `isCurrent` value. Addresses a rare crash.
Mitigates https://github.com/bigbluebutton/bigbluebutton/issues/19601 but does not fully close it.
This patch avoids the crash but I am not quite sure of the exact reason why this object is undefined in some cases.
Also, it seems in some cases the list of presentations in the dialog is missing one of the presentations (with this patch). On re-opening of the dialog it seems fine. Let's see if others perhaps have better ideas about patching this.
In order to debug this and try the fix I resorted to spinning up a temporary 2.7.4 server with a dev environment. I used the ./deploy_to_usr_share.sh script in bbb-html5 to deploy changes as I could not hit the issue while in dev mode. …
=> fix: Aviod presentation conversion causing a crash

bigbluebutton-html5/imports/startup/client/intl.jsx
Fix invalid hook call error on intl component.
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`
=> fix: intl invalid hook call

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
Add new events to be handled by `RedisRecorderActor`:
- Away
- Raise Hand
- Reaction
It will be recorded using the event `ParticipantStatusChangeEvent`:
```xml
<recording>
<event timestamp="7192468" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent">
<date>2024-02-13T09:37:40.314-03</date>
<status>reactionEmoji</status>
<userId>w_xovgdgnftlik</userId>
<value>👍</value>
<timestampUTC>1707827860314</timestampUTC>
</event>
<event timestamp="7195174" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent">
<date>2024-02-13T09:37:43.020-03</date>
<status>raiseHand</status>
<userId>w_ehofmeh9rkmy</userId>
<value>true</value>
<timestampUTC>1707827863020</timestampUTC>
</event>
<event timestamp="7197737" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent"> …
```
=> refactor (events.xml): Record raiseHand, away and reaction events

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
Apply changes made in https://github.com/bigbluebutton/bigbluebutton/pull/19232  towards the "End meeting (for all)" button in the dropdown of the optional leave-meeting-button to the end meeting button found in the settings dropdown when using the default configuration (i.e. Leave Meeting button not enabled):
- Add and use app.navBar.settingsDropdown.endMeetingForAllLabel (with text "End Meeting for all") for the End Meeting button
- Change the icon of the End Meeting button from icon-bbb-application to icon-bbb-close
=> refactor: End meeting button tweaks

bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room-graphql/create-breakout-room/manage-room-label/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room-graphql/create-breakout-room/styles.ts, bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx, bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/options-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/presentation-download-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/services/settings/index.js
Fixes several warnings showing up on console.
**Examples**:
Closes none
=> fix(warnings): prop types, invalid hook calls, etc.

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSessionBasicData.java, bbb-graphql-client-test/src/Auth.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_learningDashboard.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
In favor of: #19507
The new property, `meeting.learningDashboard.learningDashboardAccessToken`, is accessible to all users. However, it only provides data for users with Moderator privileges. This approach simplifies client-side operations by eliminating the need for the client to verify whether a user is a Moderator before requesting the token. Instead, the client can always request the token, and a successful return will indicate that the user has the necessary permissions to access the Dashboard.
```gql
query {
meeting {
learningDashboard {
learningDashboardAccessToken
}
}
}
```
Moreover:
This PR will make the session variable `X-Hasura-ModeratorInMeeting` be populated even for users that already left the meeting. It is important because moderators need to obtain the Dashboard-token …
=> Introduces learningDashboard-AccessToken through Graphql

bigbluebutton-html5/imports/ui/components/breakout-room/styles.js, bigbluebutton-html5/imports/ui/components/captions/styles.js, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/styles.ts, bigbluebutton-html5/imports/ui/components/notes/styles.js, bigbluebutton-html5/imports/ui/components/sidebar-content/styles.js, bigbluebutton-html5/imports/ui/components/timer/component.jsx, bigbluebutton-html5/imports/ui/components/timer/container.jsx, bigbluebutton-html5/imports/ui/components/timer/styles.js, bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/styles.ts
- adjusts sidebar content panels left/right padding so the spacing in both sides is the same
- makes Timer panel use the same header component as the other panels
=> style: adjust sidebar content styles

bigbluebutton-html5/imports/ui/components/notes/component.jsx
This PR corrects the chat name when using grid layout with shared notes pinned.
This PR was motivated by the output of a testing party made by our testing team.
=> Fix: Wrong chat name in grid layout when shared notes are pinned

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR revises the shape access logic in the whiteboard component to ensure proper interaction permissions. With these changes, viewers are restricted to interacting only with shapes they have created unless they have presenter or moderator privileges, in which case they can interact with any shapes.
Before this fix, a flaw in the `hasShapeAccess` function allowed all users to interact with any shape on the whiteboard, regardless of the creator. This oversight led to viewers being able to make changes to shapes they didn't own, but these changes wouldn't be reflected for others because they weren't propagated to `akka`.
=> Fix: Shape Access Logic for Non-Moderator Viewers

bbb-graphql-middleware/bbb-graphql-middleware.service
This PR removes the `LimitNOFILE=1024` setting from the `bbb-graphql-middleware` service's systemd configuration to address the service's need to support more than 1024 WebSocket connections concurrently. By eliminating this limit, we aim to enhance the service's capability to handle a greater number of user connections without hitting the open file descriptor ceiling, thus ensuring improved scalability and reliability for user interactions.
=> Remove LimitNOFILE=1024 Restriction from bbb-graphql-middleware

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/styles.ts
- Increases padding between last chat message and message input
- Adds padding between chat messages and the chat area scrollbar
=> style: adjust chat panel styles

bbb-export-annotations/workers/process.js
In certain situations, Tldraw fails to specify a size for the textbox shape, causing text rendering issues that crash the export process. This pull request introduces a check for this scenario, preventing the crash and adding appropriate exception handling to contain such errors to a single shape.
Closes #19668
Thanks to @thuh-reflact for providing the fix.
=> fix(bbb-export-annotations): handle missing textbox size in Tldraw

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala
Ports #19634 from BBB 2.7
Note that https://github.com/bigbluebutton/bigbluebutton/pull/19633 does not need to be ported as we've removed the corresponding file.
=> fix: Reduce logs in SendWhiteboardAnnotationPubMsgHdlr.scala (port)

bigbluebutton-html5/imports/ui/components/common/button/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/options-dropdown/component.jsx
This PR adds 2 minor changes related to the new (direct) leave button:
- Don't render the inner empty span
- Only show the separator element in the options dropdown when there's at least one item below
|Before|After|
|:-:|:-:|
|![](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/1158784d-9ef3-4458-93bd-22650cbe09b0)|![](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/431ca710-8c1e-41a1-96d4-8fb5b0fa31c5) ![](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/9b000702-2ccf-47ed-a69d-8410d4623fa3)|
=> fix: Minor changes related to the new leave meeting button

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/styles.js, bigbluebutton-html5/public/locales/en.json, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/polling/polling.spec.js
This pull request introduces an answer verification feature for polls.
The motivation behind this update stems from instances where polls remained unanswered, leading to unexpected behaviors like system messages lacking content for Typed polls or displaying empty graphic responses in True or False polls.
Now polling modal look after the changes:
No answers: 
With answers:
=> Client: Poll answer verification

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR restores the ability for the presenter to switch slides via the arrow keys without having to click on the presentation toolbar to get back the pointer focus after drawing or pan/zoom.
Closes #19687
=> fix(whiteboard): Enable Slide Change By Arrow Keys

akka-bbb-apps/src/main/scala/org/bigbluebutton/ClientSettings.scala
The `settings.yml` file includes sensitive configurations under the `:private` property. It is crucial that this information is not exposed to users via GraphQL. Additionally, there is no need for Akka applications to load these settings. Therefore, the purpose of this PR is to prevent Akka applications from reading these sensitive settings to enhance security measures.
=> Prevent from exposing client private configs through Graphql

bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx, bigbluebutton-html5/public/locales/en.json
Adds missing internationalization strings
=> fix: missing internationalization warnings

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
Restores poll results icon - chat
Closes #19695
=> fix: User avatar not appearing correctly when poll results on chat

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_voice_mongodb_adapter.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
While a few client components still depends on mini-mongo collections, it is necessary to populate these collections.
So @Tainan404 is working on query Graphql data to populate the mini-mongo collections.
This PR introduces a new graphql Type `user_voice_mongodb_adapter` that will be used to populate the collection `voice-users`.
```gql
subscription {
user_voice_mongodb_adapter_stream(cursor: {initial_value: {voiceUpdatedAt: "2020-01-01"}}, batch_size: 100) {
callerName
callerNum
callingWith
endTime
endedAt
floor
hideTalkingIndicatorAt
joined
lastFloorTime
lastSpeakChangedAt
listenOnly
muted
showTalkingIndicator
spoke
startTime
startedAt
talking
userId
voiceConf
voiceConfCallSession
voiceConfCallState
voiceConfClientSession
voiceUpdatedAt
voiceUserId
}
}
```
=> Introduces graphql adapter for mongodb voice-users

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/TimerDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_timer.yaml, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/component.tsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/queries.tsx
As highlighted by @Scroody, the issue at hand is that `Timer.running` remains set to `true` indefinitely, even after the timer has counted down to 0. The proposed change in this PR is to adjust the timer's behavior so that running becomes `false` once the timer reaches its conclusion.
Additionally, the PR includes a refactoring of column names: changing `startedAt` to `startedOn` and `endedAt` to `endedOn`. This alteration aims to standardize naming conventions within the database, where `On` is used for bigint values and `At` indicates PostgreSQL timestamps.
=> Graphqh: Automatically set running=false when timer has counted down to 0

bigbluebutton-html5/imports/ui/components/poll/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Increase maximum size for poll answer text in whiteboard annotation.
=> style: Increase answer size in poll results annotation

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
Combine (case insensitive) the poll responses when displayed in chat area.
=> fix(chat): combine chat poll responses

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
Move the `open` state of user items into parent component so it decides which item is open.
Closes #19690
=> fix(user-list): prevent applying action to wrong user

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
In favor of #19507
It will be necessary to insert even banned users, once they will need to fetch the reason why they are unable to join using `user_current`.
=> Graphql: Insert joining users to db even when they are banned

bbb-common-web/build.sbt, bigbluebutton-web/build.gradle
backport of https://github.com/bigbluebutton/bigbluebutton/pull/19660 to BBB 2.6
=> fix(sec): bump postgresql to 42.7.2 (backport)

bbb-common-web/build.sbt, bigbluebutton-web/build.gradle
Bumps up postgress driver to 42.7.2 (used in bbb-recording-imex optional component https://github.com/bigbluebutton/bigbluebutton/pull/14786) 
Closes #none
https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-24rp-q3w6-vc56
Alternatively can remove `/usr/share/bbb-web/WEB-INF/lib/postgresql-42.4.3.jar` and restart BBB. The dependency is only used for an optional recording API via database setup.
=> fix(sec): bump postgresql to 42.7.2

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectionAliveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectionUpdateRttReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserConnectionStatusDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala, bbb-graphql-actions/src/actions/userSetConnectionAlive.ts, bbb-graphql-actions/src/actions/userSetConnectionRtt.ts, bbb-graphql-client-test/src/UserConnectionStatus.js, bbb-graphql-server/bbb-graphql-server.service, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_connectionStatus.yaml, bigbluebutton-html5/imports/ui/components/connection-status/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/mutations.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- Fix user connection status not updating
- Introduce action `userSetConnectionAlive` for updating user connection Alive sign
```gql
mutation UpdateConnectionAliveAt {
userSetConnectionAlive
}
```
- Introduce action `userSetConnectionRtt` for updating user RTT
```gql
mutation UpdateConnectionRtt($networkRttInMs: Float!) {
userSetConnectionRtt(
networkRttInMs: $networkRttInMs
)
}
```
- Remove old way to update user connection status (using Hasura update)
=> refactor: User Connection Status flow

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
It fixes the problem where isMuted is not defined yet and it is used.
=> fix: external-video isMuted error

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala, akka-bbb-apps/src/universal/conf/application.conf, docs/docs/development/api.md, docs/docs/new-features.md
Introduces a new config for akka-apps so that the use of `sha256` is no longer hardcoded in breakouts join url creation. Detailed docs are included in this PR.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/19726 / https://github.com/bigbluebutton/bigbluebutton/issues/19736
Breakouts joining would result in a screen complaining about the checksum.
=> feat(config): add checkSumAlgorithmForBreakouts in akka-apps

bbb-graphql-middleware/bbb-graphql-middleware-config.env, bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/go.mod, bbb-graphql-middleware/go.sum
In this update to our `bbb-graphql-middleware` application, we've implemented a configurable rate-limiting mechanism for managing WebSocket GraphQL connections. 
The established default rate limit is set at **one new connection every 50 milliseconds (20 users per second)**. This configuration is carefully chosen to align with the minimum BigBlueButton system requirements of an 8-Core CPU server.
This approach ensures that the usability and responsiveness for existing users in a meeting are maintained at optimal levels, protecting the overall meeting quality from being compromised by a surge in new connections.
Recognizing the diverse performance capabilities of server setups, we've introduced the `BBB_GRAPHQL_MIDDLEWARE_RATE_LIMIT_IN_MS` environment variable. This addition allows system …
=> graphql-middleware: Implement Rate Limit for new Ws Connections

akka-bbb-apps/build.sbt
As reported by @antobinary .
When using the script `./run-dev.sh`  to run Akka-apps from source, it is ignoring the configs from `/etc/bigbluebutton/bbb-apps-akka.conf`.
=> Fix (akka-apps): Config from /etc not being read when running through `sbt reStart`

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala, akka-bbb-apps/src/universal/conf/application.conf, docs/docs/development/api.md, docs/docs/new-features.md
=> feat(config): add checkSumAlgorithmForBreakouts in akka-apps (port)

docs/docs/administration/customize.md
Update documentation. The current BBB setup deny PINs that are shorter then nine numbers.
Keep the documentation up to date
Relevant issue: https://github.com/bigbluebutton/bigbluebutton/issues/17858
=> docs: Update Freeswitch Documentation: Nine Numbers PIN 

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room-graphql/create-breakout-room/component.tsx
Fix move user to breakout after breakout creation.
Closes #19244
=> fix: Invite users after creating breakout rooms not working

akka-bbb-apps/src/universal/conf/application.conf
This PR increases the `queueSize` parameter in our Scala/Slick setup for Postgres from the default 1,000 to 20,000 to handle spikes of up to 1,000 simultaneous users more effectively. 
This change aims to prevent queue overflow, ensuring smoother operation and enhanced stability during high load scenarios.
https://scala-slick.org/doc/3.3.0/database.html
=> refactor (akka-apps): Increase Slick/Postgres queueSize

bigbluebutton-html5/public/locales/en.json
Removes a duplicated localization row
Closes #
This duplication led to Transifex pickup to fail, resulting in missing strings.
Transifex should pick this change right away, allowing for people to translate `End meeting for all` and possibly other missing strings.
=> fix(locale): Remove duplicate localization row

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes a bug where the external video starts to play from the wrong time.
#19245
=> Fix: External video starting at wrong time

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR addresses two issues in the whiteboard functionality:
- It corrects the slide's position when the zoom is reset to 100% following a pan operation.
- It ensures the slide maintains its intended position after a resize event, rather than resetting to a default position.
before:
after:
=> fix(whiteboard): Correct Slide Position On Zoom Reset And Resize

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx
This pull request resolves the issue where messages from the previous chat were displayed prematurely, appearing before messages from the subsequent chat. This fix ensures that messages are displayed in the correct chronological order.
#19200
=> Fix: Messages from the previous chat  being carried on chat switch.

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR resolves an issue that allowed non-presenters to pan the canvas, a feature meant to be exclusive to the presenter until further controls for the infinite canvas are implemented. After this fix, only presenters will have the ability to pan the canvas, aligning with the intended functionality.
Partially closes #19580
=> fix(whiteboard): Ensure Only Presenter Has Ability to Pan Canvas

bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bigbluebutton-html5/imports/ui/components/meeting-ended/meeting-ended-ts/component.tsx, bigbluebutton-html5/imports/ui/components/meeting-ended/meeting-ended-ts/queries.ts
Fix error when user is ejected from a meeting and the data is not being fetched to show the right screen
=> Fix: meeting end not fetching user data

bbb-graphql-middleware/internal/common/SafeChannel.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/rediscli.go, bbb-graphql-middleware/internal/websrv/writer/writer.go, bbb-graphql-middleware/run-dev.sh
This PR tackle an issue where BBB was increasing CPU usage when 400+ connections was being closed at the same time.
It would impact when the meeting is finished and all the browsers has its ws connection closed!
The main change is at `bbb-graphql-middleware/internal/websrv/reader/reader.go` that is now receiving the browser `contextCancel` func and call it when the browser connection is closed.
Moreover:
- Improve logs
- Improve `run-dev.sh` 
- Improve var names
=> refactor (graphql-middleware): Improve performance when browser finish graphql connection

bbb-graphql-middleware/internal/common/SafeChannel.go, bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/hascli/retransmiter/retransmiter.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/writer/writer.go
Following #19784
When Hasura Client would re-connect, it was closing the channel `MsgReceivingActiveChan` to inform that the channel  
`fromBrowserToHasuraChannel` should be frozen!
Now the channel was renamed to `FreezeMsgFromBrowserChan` and it will just send a message to the channel instead of closing it:
It was necessary because once the channel was closed, this `case` would start a loop (causing increase of CPU usage):
---
Other loop was identified when the channel `fromHasuraToBrowserChannel` was closed.
Now it will `break`  the loop once it identifies the channel is closed (and the client will die soon).
=> refactor (graphql-middleware): Improve re-connection flow

bigbluebutton-html5/imports/ui/Types/user.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
fix typescript errors:
`imports/ui/Types/user.ts(57,3): error TS2300: Duplicate identifier 'isDialIn'.`
```  
/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
178:1   error  Expected indentation of 4 spaces but found 2  indent
180:1   error  Expected indentation of 4 spaces but found 2  indent
181:1   error  Expected indentation of 6 spaces but found 4  indent
182:1   error  Expected indentation of 4 spaces but found 2  indent
182:10  error  Unnecessary 'else' after 'return'             no-else-return
183:1   error  Expected indentation of 6 spaces but found 4  indent
184:1   error  Expected indentation of 8 spaces but found 6  indent
185:1   error  Expected indentation of 8 spaces but found 6  indent
186:1   error …
```
=> fix: ts errors

bbb-webrtc-recorder.placeholder.sh
* fix: panic due to invalid OPUS samples pushed to builder
* build(docker): go 1.21
* build: bump pion/webrtc/v3 to v3.2.24
=> [3.0] build(bbb-webrtc-recorder): v0.7.0

bbb-webrtc-sfu.placeholder.sh
* feat: add incrementBy util to prometheus-agent
* feat(core): add event callback and dispatch metrics
* fix: another edge case where subprocesses fail to recover
* fix: subprocesses fail to recover from multiple crashes
* feat: add inbound queue size and job failure metrics
* feat: add dry-run recording mode
* feat: add time_to_mute/unmute metrics
* feat: add warn logs for when hold/mute actions exceed max bucket time
* feat(mediasoup): add mediasoup_ice_transport_protocol metric
* feat(mediasoup): per-worker resource metrics
* feat(mediasoup): add worker label to transport/router/prod/cons metrics
* fix(audio): log and track metrics for hold/unhold timeouts
* fix(bbb-webrtc-recorder): exception when removing nullish recording callbacks
* fix(mediasoup): check for null producers
* …
=> [3.0] build(bbb-webrtc-sfu): v2.13.2

bbb-webrtc-sfu.placeholder.sh
* feat: add incrementBy util to prometheus-agent
* feat(core): add event callback and dispatch metrics
* fix: another edge case where subprocesses fail to recover
* fix: subprocesses fail to recover from multiple crashes
* feat: add inbound queue size and job failure metrics
* feat: add dry-run recording mode
* feat: add time_to_mute/unmute metrics
* feat: add warn logs for when hold/mute actions exceed max bucket time
* feat(mediasoup): add mediasoup_ice_transport_protocol metric
* feat(mediasoup): per-worker resource metrics
* feat(mediasoup): add worker label to transport/router/prod/cons metrics
* fix(audio): log and track metrics for hold/unhold timeouts
* fix(bbb-webrtc-recorder): exception when removing nullish recording callbacks
* fix(mediasoup): check for null producers
* …
=> [2.7] build(bbb-webrtc-sfu): v2.13.2

bbb-webrtc-recorder.placeholder.sh
* fix: panic due to invalid OPUS samples pushed to builder
* build(docker): go 1.21
* build: bump pion/webrtc/v3 to v3.2.24
=> [2.7] build(bbb-webrtc-recorder): v0.7.0

bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
This PR updates the CSS to handle the hiding of the Tldraw native navigation and control UI elements
before:
after:
=> fix(whiteboard): Hide Tldraw Native Navigation And Control Elements

bbb-graphql-middleware/bbb-graphql-middleware-config.env, bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/common/CustomRateLimiter.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
- Implements `CustomRateLimiter` once `golang.org/x/time/rate` was not cancelling disconnected clients properly
- Add env var `BBB_GRAPHQL_MIDDLEWARE_MAX_CONN_PER_SECOND=10`  
- Remove env var `BBB_GRAPHQL_MIDDLEWARE_RATE_LIMIT_IN_MS=50`
- HTML5 Client will wait 30 seconds for server response before creating a new Graphql WS Connection. It will be useful to save the client position in the queue when several users are connection simultaneously
- Improve `websrv/connhandler.go` once it was throwing panic errors in extreme situations
=> refactor (graphql-middleware): Improve rate limiter and others

docs/docs/accessibility.md, docs/docs/administration/configure-firewall.md, docs/docs/administration/install.md, docs/docs/administration/nextcloud.md, docs/docs/release-notes.md, docs/docs/support/road-map.md, docs/docs/testing/release-testing.md
Note that is PR also renames docs/docs/accessiblity.md → docs/docs/accessibility.md.
There exists another file with a typo in the filename (docs/static/img/23-user-reponse.png) which might be unused.
=> Fix some typos (found by typos)

bigbluebutton-html5/imports/ui/components/poll/container.jsx
fix wrong chat id being set on poll publish
=> fix: wrong chat name displayed when poll is published

bigbluebutton-html5/imports/ui/components/connection-manager/startup-data-fetch/component.tsx
When a session is invalid user can't fetch settings data from server, the error wasn't handle, this PR implements a catch to handle it.
=> Fix: loading client with invalid session token

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_lockSettings.yaml
Add missing fields that is required by the client, as reported by @Tainan404 
```gql
subscription {
meeting {
lockSettings {
lockOnJoin
lockOnJoinConfigurable
}
endWhenNoModerator
endWhenNoModeratorDelayInMinutes
}
}
```
=> Graphql: Add missing fields to lockSettings and endWhenNoModerator

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR, following up on #19688, addresses a bug where shapes for viewers would not update correctly if selected while another user with appropriate privileges made updates to the same shape. This fix ensures that shape updates are reflected even while selected, improving the collaborative editing experience.
before: 
after:
=> fix(whiteboard): Selected Shapes Fail To Update On External Edits

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Restores inactivity check feature, using data from graphQL
Back-end part: #19851
Closes #19826
=> fix: inactivity warning - front-end

bbb-graphql-server/metadata/query_collections.yaml, bigbluebutton-html5/client/main.tsx, bigbluebutton-html5/client/meetingClient.jsx, bigbluebutton-html5/imports/startup/client/intlLoader.tsx
Prevent end meeting screen error by restoring intlLoader location and using `clientStartupSettings` for intl settings.
=> fix: meeting end screen

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the problem with the paused external video skipping when user actions happened.
#19775
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/aa348459-f13f-4ce7-9a8c-fd6f0bdecf00
=> Fix: External video plays while paused when it has some user action

.github/actions/merge-branches/action.yml, .github/workflows/automated-tests.yml, .github/workflows/check-merge-conflict.yml, .github/workflows/deploy-docs.yml, .github/workflows/ts-code-compilation.yml, .github/workflows/ts-code-validation.yml
This fixes several CI warnings like this one:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3,
actions/cache@v3, actions/upload-artifact@v3. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Update several GitHub actions which still used deprecated Node.js 16

build/packages-template/bbb-graphql-server/build.sh
It's throwing an error while trying to install Hasura-CLI:
In order to avoid it, this PR force the last version that it can install without errors: `v2.36.2`.
Let's follow the issue: https://github.com/jjangga0214/hasura-cli/issues/116
=> build: Force hasura cli v2.36.2 to avoid error

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/pads/service.js
Unpin shared notes from media area when sharing an external video.
Closes #19800
=> fix: unpin notes when sharing external video

bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go
- Increase WS Read Limit from default `32768` to `999999`
It is necessary because Annotation mutations often exceeds the default limit!
=> refactor (graphql-middleware): Increase Ws Read Limit (necessary for annotations)

bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go
- Increase WS Read Limit from default 32768 to 999999 (10MB)
#19913 was not enough
=> refactor (graphql-middleware): Increase Ws Read Limit to 10MB (necessary for annotations)

bbb-export-annotations/config/settings.json, bbb-export-annotations/master.js, bbb-export-annotations/workers/collector.js, bbb-export-annotations/workers/notifier.js, bbb-export-annotations/workers/process.js
The pull request #19707 sets CairoSVG's `--unsafe` option to let external resources be loaded. Albeit necessary to, e.g., load presentation slides, some server admins may choose to disable it out of an abundance of caution.
CairoSVG versions before 2.7 can set the flag to false.
=> fix(bbb-export-annotations): Flag to force CairoSVG to embed images

bbb-export-annotations/master.js, bbb-export-annotations/workers/collector.js, bbb-export-annotations/workers/notifier.js, bbb-export-annotations/workers/process.js
1) update function redis.createClient to use redis host+port from config/settings.json otherwise redis use default host (localhost) and default port (6379)
see; 
https://redis.io/docs/connect/clients/nodejs/ 
under "Connect to your production Redis with TLS"
2) force cairosvg to create pdf files with embedded pictures - necessary for cairosvg since version 2.7.0
see;
https://github.com/Kozea/CairoSVG/releases/tag/2.7.0
maybe
https://github.com/bigbluebutton/bigbluebutton/issues/18746
https://github.com/bigbluebutton/bigbluebutton/issues/18739
to build my own docker image for bbb-export-annotations
when i debug the errors (no background image, no redis communication) no errors where thrown.
furthermore the try-catch block aren't helpful because the error wouldn't catched.
and the logger …
=> updates bbb-export-annotations

bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/common/GlobalState.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go
It will help to monitor the current status of the Middleware.
Especially useful for overload scenarios.
It adds two logs:
- Summary:
```json
{
"activeBrowserHandlers":1,
"activeSubscriptions":28,
"activeWsConnections":1,
"numGoroutine":14,
"pendingMutations":0
}
```
- Detailed:
```json
{
"Hasura-CurrentPresentationPagesSubscription-Added":3,
"Hasura-CurrentPresentationPagesSubscription-Completed":3,
"Hasura-CursorSubscription-Added":3,
"Hasura-CursorSubscription-Completed":3,
"Hasura-GetChatData-Added":3,
"Hasura-GetChatData-Completed":3,
"Hasura-IsTyping-Added":5,
"Hasura-IsTyping-Completed":5,
"Hasura-MeetingSubscription-Added":8,
"Hasura-MeetingSubscription-Completed":8,
"Hasura-MySubscription-Added":3,
"Hasura-MySubscription-Completed":3,
"Hasura-Patched_MeetingSubscription-Added":3, …
```
=> graphql-middleware: Add periodic log with Activities Overview

bigbluebutton-html5/imports/ui/components/connection-status/queries.jsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/queries.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/queries.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/queries.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/chatSubscription.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/pollResultsSubscription.js, bigbluebutton-html5/imports/ui/core/graphql/queries/pollSubscription.js, bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
Ensuring easier identification of subscriptions that might be requested too frequently. This enhancement is particularly useful in conjunction with the middleware logs introduced in PR #19926, enhancing our ability to monitor and analyze subscription usage effectively.
=> refactor (html5): Add operationName for subscriptions that lacks it

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- Rewrites the audio modal component as function component.
- If the user has `userdata-bbb_force_listen_only=true`, shows modal loading state until the autoplay check is shown. This prevents rendering useless stuff.
The main change is the `skipAudioOptions` function which decides when to show the loading screen:
Then
```js
skipAudioOptions() {
const {
isConnecting,
} = this.props;
const {
content,
hasError,
} = this.state;
return isConnecting && !content && !hasError;
}
```
Now
```js
const skipAudioOptions = () => (isConnecting || (forceListenOnlyAttendee && !autoplayChecked))
&& !content
&& !hasError;
```
Closes #19428
=> fix(audio modal): show loading state while autoplay not checked

bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/common/GlobalState.go, bbb-graphql-middleware/internal/hascli/client.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go
Improve #19926
- Also add env var `BBB_GRAPHQL_MIDDLEWARE_JSON_PATCH_DISABLED` for performance tests
- It will log only messages requested too frequently
- New log format:
```json
{
"_Sum-mutation":{
"Started":1232,
"Completed":1232
},
"_Sum-streaming":{
"Started":6,
"Completed":0
},
"_Sum-subscription":{
"Started":58,
"Completed":0
},
"_Sum-subscription_aggregate":{
"Started":5,
"Completed":0
},
"__BrowserConnection":{
"Started":2,
"Completed":0
},
"__HasuraConnection":{
"Started":2,
"Completed":0
},
"__WebsocketConnection":{
"Started":2,
"Completed":0
},
"mutation-UpdateConnectionAliveAt":{
"Started":616,
"Completed":616
},
"mutation-UpdateConnectionRtt":{
"Started":616,
"Completed":616
}
}
```
=> refactor (graphql-middleware): Improve activities status logs and add option to disable JsonPatch

bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/common/GlobalState.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go
Now it will log number of times each subscription received data.
It will help to identify messages fetched too frequently.
```json
{
"_Sum-mutation":{
"Started":233,
"Completed":233,
"DataReceived":0
},
"_Sum-query":{
"Started":24,
"Completed":24,
"DataReceived":0
},
"_Sum-streaming":{
"Started":12,
"Completed":0,
"DataReceived":0
},
"_Sum-subscription":{
"Started":134,
"Completed":9,
"DataReceived":0
},
"_Sum-subscription_aggregate":{
"Started":10,
"Completed":0,
"DataReceived":0
},
"__BrowserConnection":{
"Started":4,
"Completed":0,
"DataReceived":0
},
"__HasuraConnection":{
"Started":7,
"Completed":3,
"DataReceived":0
},
"__WebsocketConnection":{
"Started":4,
"Completed":0,
"DataReceived":0
},
"mutation-PresentationPublishCursor":{
"Started":83,
"Completed":83,
"DataReceived":80
}, …
```
=> graphql-middleware: Track most requested  messages for performance analysis

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR implements a configuration change utilizing the `canMoveCamera` setting from `tldraw` to disable the mouse wheel's pan shortcut. This ensures that viewers are unable to activate the panning feature inadvertently. This approach is more efficient as it avoids direct modifications to the `tldraw` codebase, which was previously considered. It also fixes the lint issues in the hooks.
Closes #19580
=> fix(whiteboard): Use canMoveCamera To Disable Viewer Mouse Wheel Pan

bbb-graphql-actions/src/config.ts, bbb-graphql-actions/src/index.ts, bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx, bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts, bigbluebutton-html5/private/config/settings.yml
This PR defines a max size, in bytes, for mutation payloads. It defaults to 10MB. This prevents from sending big annotation mutations.
See https://github.com/bigbluebutton/bigbluebutton/pull/19916 and https://github.com/bigbluebutton/bigbluebutton/pull/19913.
=> fix: limit mutation payloads to 10MB by default

bigbluebutton-tests/playwright/breakout/breakout.spec.js
Re-adds `Breakout › After creating › Invite user after creating rooms` test to CI since it was fixed on #19753 and it's passing locally
=> test: Re-add breakout test to CI

bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/button/container.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx, bigbluebutton-html5/imports/ui/components/connection-status/queries.jsx
Makes the connection status button use just the current user's status data. There is no need to subscribe to every user's data there. The modal will subscribe when opened.
=> fix: connection status button subscribing to data of all users

bbb-graphql-actions/src/actions/meetingLayoutSetProps.ts, bigbluebutton-html5/imports/ui/components/app/container.jsx
Adjusts meetingLayoutSetProps permissions to check if the user is presenter instead of checking for moderator status
Closes #19859
=> fix: Viewer presenter (non moderator) cannot push layout to all

bigbluebutton-html5/imports/ui/components/polling/polling-graphql/styles.ts, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Fixes polling box covering the whole presentation when it's in fullscreen.
Before (while in fullscreen)
After (while in fullscreen)
=> fix(poll): poll element covering the whole presentation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR resolves an issue where some hooks were called conditionally, which is not permitted by Reacts rules of hooks. By ensuring that all hooks are called unconditionally at the top level of functional components, we maintain the correct execution order of hooks ensuring consistency across renders.
same changes in #19831
=> fix(whiteboard): Remove Conditionally Called Hooks Error

bigbluebutton-html5/imports/startup/client/logger.js
Fixes the errors that were happening when using the client remote logger (disabled by default).
Errors that this PR fixes:
=> fix(bbb-html5): Fix remote logger

bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx, bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/queries.ts, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/container.jsx
- fix "Leave meeting" button
- fix long delay for displaying "meeting ended" screen when user leaves meeting
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/859fc2a9-acf8-43a2-80fa-2aaa3bff7bd8
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/7bdb0c97-613b-4731-a2fa-1473c3d4be49
=> Fix: leave meeting button

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/styles.js, bigbluebutton-html5/private/config/settings.yml
This PR enables the modification of the highlight color for the webcam (when someone is talking) via settings.yml file with a rgb color code.
Code example:
`webcamBorderHighlightColor: [50, 255, 50]`
<details>
<summary>Result preview</summary>
</details>
Closes #16068
=> Adds custom color highlight option for webcam

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationDAO.scala, bigbluebutton-html5/imports/ui/components/whiteboard/queries.ts
- It will gather all annotations received and update it into the database in one single transaction.
- It will also send a single update to delete a batch of annotations.
- It will stop populating the table `pres_annotation_history` while it is not being used (in the future we will discuss about start to use it or completely remove it).
- And it will receive batches of 100 annotations in the Client, instead of 10.
It aims to improve the experience of drawing in the whiteboard!
=> refactor (graphql-server): Makes it faster to update annotations

bigbluebutton-html5/imports/ui/components/video-provider/service.js
Fix bug where a viewer could not share webcam when grid mode is enabled
=> fix: share camera on grid mode

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomEndedInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/ChangeUserBreakoutReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EndAllBreakoutRoomsMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/SendMessageToAllBreakoutRoomsMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/UpdateBreakoutRoomsTimeMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/BroadcastLayoutMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/ShowPollResultReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SetRecordingStatusCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/NotificationDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PostgresProfile.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/MuteAllExceptPresentersCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/MuteMeetingCmdMsgHdlr.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_notification.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Users can receive all notifications through Graphql type `notification`.
It's recommended to use it as stream with `createdAt` as `Date.now()` (for instance the stream `chat_message_public_stream`).
```gql
subscription {
notification_stream(batch_size: 10, cursor: {initial_value: {createdAt: "2024-04-12"}}) {
notificationType
icon
messageId
messageValues
isSingleUserNotification
createdAt
}
}
```
It will provide only the notifications created in the last 5 seconds.
This way if a user is promoted to Moderator, he will not be able to fetch old notifications sent before he was moderator.
=> Introduces graphql Notification

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/container.jsx, bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/service.js
Get users count from graphql instead of meteor collection (a generic message is displayed when the number is not available)
=> fix: users count not available on end meeting modal

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
Fix issue with parts of the breakout modal disappearing when a warning is displayed.
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/0133d8a2-72b6-47b3-9bf8-88e28a3a660f
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/d885054c-3d73-4d01-9aef-f30ca855483b
=> fix: breakout styles

build/packages-template/bbb-html5/after-install.sh
Fix a problem where html5 package is upgraded but nginx provide old assets!
Related: #19942 #19968
=> build (html5): Add step to clear Nginx cache to refresh Meteor assets

bigbluebutton-html5/imports/ui/components/emoji-rain/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-rain/service.js
- [fix(reactions): crash when interactionsButton coords are absent](https://github.com/bigbluebutton/bigbluebutton/commit/66788e9697e8e43087af194fa83c1cdf6b646df3) 
- The client may crash whenever a emoji rain animation is triggered, but
the interactions button element cannot be located. This happens because
the button coordinates are fetched without checking whether the element
exists.
- Get the coordinate fetching method to return null if the
interactionsButton element cannot be located, and ignore the emoji rain
action if that is the case. Whenever no valid coordinates are found, log
an warning so we can track this and figure out what's happening with the
button.
- Fix a few typos in the getInteractionsButtonCoordinates method.
None
=> [2.7] fix(reactions): crash when interactionsButton coords are absent

bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js
- [fix(bbb-html5): crash when stopping WebRTC peers](https://github.com/bigbluebutton/bigbluebutton/commit/610f3b165bd783f87249fc6a52b4706fdfa6e97a) 
- There's a race condition that may cause a client crash whenever a
connectionstatechange callback is cleaned up in a peer without a
valid peer connection present in our custom RTCPeerConnection wrapper.
- Check for peerConnection availability in the WebRtcPeer wrapper before
trying to clean up its connectionstatechange callback.
None
=> [2.7] fix(bbb-html5): crash when stopping WebRTC peers

bigbluebutton-html5/imports/ui/services/meeting-settings/index.js
- [fix(bbb-html5): crash due to undefined metadataProp access](https://github.com/bigbluebutton/bigbluebutton/commit/71f958ca472f4faf2a8a6c83931f40165dbaf63f) 
- A client crash may happen if either the Meeting collection or the
document's metadataProp attribute are undefined whenever the
getFromMeetingSettings util is called to fetch metadata.
It's debatable whether anything is working in the client if the
documents being accessed here are unavailable, but it'll still be logged
and might bork an ongoing reconnect.
- Use optional chaining + nullish coalescing to avoid causing TypeErrors
in those situations while also returning default metadata values
properly.
None
=> [2.7] fix(bbb-html5): crash due to undefined metadataProp access

bigbluebutton-html5/imports/ui/components/screenreader-alert/component.jsx
Credits to @Arthurk12 
- [fix(screen-reader): add safeguards for adding alerts](https://github.com/bigbluebutton/bigbluebutton/commit/6cb0e914ab9fd38e16ac943317a6b8809bb5b645) 
- Adds checks for the alert's text and DOM element before adding screen
reader alerts.
- Fixes a potential client crash
None
=> [2.7] fix(screen-reader): add safeguards for adding alerts

bigbluebutton-html5/imports/ui/components/settings/service.js
Credits to @Arthurk12 
- [fix: add safeguards when returning user roles](https://github.com/bigbluebutton/bigbluebutton/commit/72032f23970ffa7af66a4ea3ad5e865a9c3452e0)
- Fixes a potential client crash
None
=> [2.7] fix: add safeguards when returning user roles

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- [fix(bbb-html5): crash on video-provider unmount](https://github.com/bigbluebutton/bigbluebutton/commit/10a6a840b568c3bb1af1b920cfd468a08b2479ee) 
- There's a race condition that may cause a client crash whenever a
video-provider's unmount procedure is run, but its signalling websocket
is undefined. The WS's callback handlers are re-assigned without
checking for the socket's availability, causing an unhandled TypeError.
- The WS may be undefined in a couple of scenarios, e.g.: unmouting before
the socket was successfully set up, unmounting while a reconnect is in
place etc.
- Check whether the socket exists before accessing it in video-provider's
componentWillUnmount routine.
None
=> [2.7] fix(bbb-html5): crash on video-provider unmount

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room-graphql/create-breakout-room/room-managment-state/component.tsx
refactor breakout moveUser function to accept multiple users, so many users can be moved from one room to another in a single call
Closes #19976
=> fix: Randomly assign viewers into breakouts filter

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Since the pan tool is only available for the presenter, it has to be checked whether it actually exists before attempting to modify its class list.
Closes #20025
=> fix(whiteboard): check before manipulating pan tool class list

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR refactors the logic behind the unsynched player message to the BBB external video.
Showing the unsynched message when it shouldn't in this example changing moderator with external video paused:
[bug.webm](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/fe47e652-15df-48cf-95bd-9fbeb0d9257f)
The message should be shown when the video is unsynchronized, for example, when a person joins the external video activity and the video was already playing a period of time.
[shouldShowMsg.webm](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/7c38511e-9b61-431b-bb2c-a22e955c4147)
The solving of the problem was adding some kind of conditional for the message to show (before it showed on components mounting if the player was not playing - not ideal) and then …
=> Fix: External video autoplay block

bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/video-provider/queries.ts
fix grid mode webcam ordering
self -> users not sharing camera  -> users sharing camera camera
self -> users in alphabetic order
=> fix: grid mode webcam order

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/TransferUserToMeetingRequestHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom_assignedUser.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom_participant.yaml
It fix this button:
Reported by @Tainan404 !
----
This PR implements the option "Transfer User" in Graphql.
It will create a copy of the user and insert using the `meetingId` of the breakoutRoom (just like it was done in Mongodb).
https://github.com/bigbluebutton/bigbluebutton/blob/d19d2868110a52cab8d1e0864da40907300b95ed/bigbluebutton-html5/imports/api/voice-users/server/handlers/joinVoiceUser.js#L36
And this users will be flagged in the database with the option `transferredFromParentMeeting=true`.
=> fix (graphql-sever): Option "Join audio" in breakout rooms not working

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom_assignedUser.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom_participant.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pluginDataChannelMessage.yaml
- Fix a problem that main user could not get info of breakoutRoom audio-only participants
- Add a flag `isAudioOnly` to indicate that user joined in the breakoutRoom as audio-only
```gql
subscription {
breakoutRoom(order_by: {sequence: asc}){
shortName
participants {
userId
isAudioOnly
user {
name
nameSortable
}
}
}
}
```
Related: #20031
=> graphql-server: Add flag `isAudioOnly` for breakoutRoom participant

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room-graphql/create-breakout-room/room-managment-state/component.tsx
Similar to #20014, but for displaying users in the correct breakout room in the "manage users" modal
=> fix: move users to the correct breakout room in manage users modal

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/caption/CaptionApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/CaptionDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/CaptionLangDAO.scala, bbb-graphql-actions/src/actions/captionSetOwner.ts, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_caption.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_caption_typed_activeLocales.yaml
Add graphql action to set caption owner!
```gql
mutation {
captionSetOwner(locale: "en", ownerUserId: "w_xxlfoz5hifpv")
}
```
Once it is called, the Type `caption_typed_activeLocales` will return the caption locale and its owner.
=> Graphql-server: Add mutation `captionSetOwner`

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/layout/context.jsx, bigbluebutton-html5/imports/ui/components/notes/component.jsx, bigbluebutton-html5/imports/ui/components/notes/notes-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js
It fixes a problem where pinned sharedNotes was not unmounting from the presentation area when another component, such as screenshare or external-video, requested to be rendered within the presentation area.
See error below:
https://github.com/bigbluebutton/bigbluebutton/assets/69865537/193defaf-9971-43f0-8385-b42dc9b3da2d
Now, the fix:
https://github.com/bigbluebutton/bigbluebutton/assets/69865537/262d323c-40d7-40ae-815a-8d79e6dc9ced
=> fix(html5): SharedNotes not unmounting when other components pile up in layout manager

bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Fix the error encountered when attempting to send updates for the whiteboard cursor when whiteboardId is unavailable.
=> fix: missing whiteboardId error

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx, bigbluebutton-tests/playwright/breakout/create.js, bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/core/elements.js
- Fixes `Breakout › After creating › Message to all rooms` => failing due to the tooltip displayed in front of the button when performing click action;
- Fixes `Breakout › After creating › User can choose a room` => testing code with wrong steps, outcoming false positive
=> test: fix breakout tests failing on CI

bigbluebutton-html5/client/main.tsx, bigbluebutton-html5/imports/ui/components/components-data/screenshareGraphQlMiniMongoAdapter/component.tsx, bigbluebutton-html5/imports/ui/components/components-data/screenshareGraphQlMiniMongoAdapter/queries.ts, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
Remove screenshare subscription to meteor and make it implementing a graphql adapter
=> Refactor: migrate screenshare to graphql using a adapter

bigbluebutton-html5/imports/ui/components/settings/component.jsx
Fix: switching to a region specific locale does not work. If the user changes locale to `pr-BR`, `pt` messages will be displayed instead.
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/4ee7b26a-8e51-40ce-8c33-c13b67e700ff
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/eff7c1ad-7fd0-4602-b923-cede5d95ab0f
=> fix: save region specific language does not work

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/Types/meeting.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/meetingSubscription.ts, docs/docs/data/create.tsx, docs/docs/development/api.md
This pull request adds a new parameter `loginURL` to the `/create` API endpoint. The purpose of this parameter is to allow third-party applications to specify a URL for users to access and join a live meeting.
This feature is particularly useful in hybrid settings. For example, a teacher can display a QR code within BigBlueButton (BBB), which students can scan to be taken directly to a site like Greenlight. There, they can enter their name and join the meeting to participate in activities like an online poll.
API /create param:
`loginURL=https://myserver.bbb//rooms/4h9-3s2-ffs-mam`
Graphql query:
```gql
subscription {
meeting {
loginUrl
}
}
```
=> feature: Add new API /create param `loginURL`

bigbluebutton-html5/imports/ui/core/hooks/useCurrentUser.ts, bigbluebutton-html5/imports/ui/core/providers/current-user.tsx
This PR reimplements useCurrentUser to use a useSubscription, we must use the premise of never making a data hook depend on a provider, but rather the opposite.
=> Refactor: useUserCurrentData to use subscription

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
- [fix(audio): review device selection in mobile endpoints](https://github.com/bigbluebutton/bigbluebutton/commit/141c553b170f51e3cc758d1e59232ed063ec410d) 
- Mobile users have no way to change I/O devices after joining audio.
The removal of the audio options chevron in mobile browsers was supposed
to be replaced by something else - in this case, by the dedicated
leave/join audio button. That didn't happen, leave/join audio button
retained the old behavior.
- Review device selection in mobile endpoints via two UI/UX changes:
- Restore the device selection chevron/icon in mobile endpoints
- Override the leave/join button action in mobile endpoints so that it
opens the device selection contextual menu, which also includes the
"Leave audio" option. This retains the old behavior (leaving …
=> fix(audio): review device selection in mobile endpoints

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
- [fix: crash at meeting-ended due to undefined access + incorrect meetingID](https://github.com/bigbluebutton/bigbluebutton/commit/5f59453548bb5aca23d016b14ab8af3f9b73fdc7) 
- Fixes an undefined access crash at the meeting-ended component caused by
trying to access a property of a nullish user document.
Fixes incorrect access to the meetingId property of the user document -
currently fetched as meetingID, which doesn't exist.
None
=> fix: crash at meeting-ended due to undefined access + incorrect meetingID

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
WebRTC-based stats generation in the connection status modal is broken on Firefox >= 125. A broken type check coupled with a new partially implemented RTCIceTransport dictionary causes an undefined function call when fetching the selected candidate pair. Since that error is unhandled, collection breaks.
Correctly check for the getSelectedCandidatePair method availability in RTCIceTransport so that it skips to pair inference from getStats if necessary.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/20117
=> fix(audio): broken connection stats on Firefox >= 125
