bigbluebutton/bigbluebutton

bigbluebutton-html5/private/config/settings.yml
Enables French captions by default
Closes https://github.com/bigbluebutton/bigbluebutton/issues/18155
BBB has a wide adoption in French speaking countries. Having this option enabled by default will help people try out closed captions on any deployment inclulding test and demo servers BBB maintains.
=> chore: Enable French captions by default

build/packages-template/bbb-webhooks/after-install.sh, build/packages-template/bbb-webhooks/build.sh
Backport of #18144 to BBB 2.5.x
=> build: recover installation of bbb-webhooks (backport from BBB 2.6)

docs/docs/development/api.md
=> docs: Fix typo at api.md

docs/docs/support/faq.md
Add a sentence regarding the possibility to use animated PP presentation.
1. It is the most frequently asked questions that I receive when I recommend a migration from Zoom to BBB.
2. The quality of conversion of animated effect by PPspliT seems to have greatly improved recently.
=> [doc] guide to use animated PP file

.github/workflows/automated-tests.yml, .gitlab-ci.yml, akka-bbb-apps/build.sbt, akka-bbb-fsesl/build.sbt, bbb-common-message/build.sbt, bbb-common-web/build.sbt, bbb-fsesl-client/build.sbt, bigbluebutton-web/gradle.properties, build/packages-template/bbb-web/after-install.sh, build/packages-template/bbb-web/build.sh, build/packages-template/bbb-web/opts-focal.sh, docs/docs/development/dev-guide.md, docs/docs/new-features.md
Modified build configurations on `bbb-common-message`, `bbb-common-web`, `bigbluebutton-web`, `akka-bbb-apps`, `bbb-fsesl-client`, and `akka-bbb-fsesl` to support Java 17.
Also upgrades GORM to 7.3.1 and Groovy to 3.0.11.
Oracle support for Java 11 is coming to an end in ~3 months so it is necessary to upgrade from Java 11 to Java 17.
=> build: Java 17 support

build/packages-template/bbb-web/after-install.sh
Adapts bbb-web for upgrades from java11 env. In case bbb-install.sh is not used, bbb-web needs additional post-install code to set the preferred java version.
Closes #none
In an upgrade without bbb-install.sh from 2.7.0-alpha.1 or 2.6.x, the environment was:
```
root@droplet-2856:~# update-alternatives --get-selections | grep java
jaotc                          manual   /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc
jar                            manual   /usr/lib/jvm/java-11-openjdk-amd64/bin/jar
jarsigner                      manual   /usr/lib/jvm/java-11-openjdk-amd64/bin/jarsigner
java                           manual   /usr/lib/jvm/java-11-openjdk-amd64/bin/java
javac                          manual   /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
javadoc                        manual …
```
=> build: Adapt bbb-web for upgrades from java11 env

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
[Screencast from 2023-06-15 09-50-03.webm](https://github.com/bigbluebutton/bigbluebutton/assets/3728706/e118508c-39a1-4f1d-9789-79724bfa716d)
=> fix: audio button position changes when modal is open

bigbluebutton-html5/imports/ui/components/common/modal/base/component.jsx, bigbluebutton-html5/imports/ui/components/common/modal/simple/component.jsx, bigbluebutton-tests/playwright/audio/audio.js, bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/audio/util.js, bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/customparameters/customparameters.js, bigbluebutton-tests/playwright/package-lock.json, bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/presentation/presentation.js
- Updates all dependencies (except `chalk`);
- Fixes modal props not being applied to the component;
- Minor changes for breakout tests and notification checks;
=> test: Fix data-test prop in modals and update dependencies

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/GetScreenBroadcastPermissionReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareRtmpBroadcastStartedVoiceConfEvtMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/media/service.js
Back-end portion for disabled feature camera as content.
Closes #18021
=> feat: [issue-18021-back-end] - Back-end portion of disabled camera as content

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
Sort grid mode items by name, instead of adding users that are not sharing camera to the end of the list.
Closes #18126
=> refactor: Sort Grid Mode items alphabetically

build/packages-template/bbb-webrtc-sfu/after-install.sh
=> build: fix mismatched quote

bbb-learning-dashboard/package-lock.json, bbb-learning-dashboard/package.json
Upgrading learning dashboard npm dependencies to resolve npm audit alerts.
=> chore: upgrade learning dashboard dependencies

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/install-hasura.sh, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom.yaml
Migrate the new prop of breakouts `sendInvitationToModerators` to graphql data.
Since #18197 was merged.
=> refactor (graphql-server): New prop breakoutroom.sendInvitationToModerators to graphql

bbb-learning-dashboard/package-lock.json, bbb-learning-dashboard/package.json
Reverts bigbluebutton/bigbluebutton#18246
=> Revert "chore: upgrade learning dashboard dependencies"

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/container.jsx
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/3268f76c-dbb2-4374-b155-1e116308a674
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/ac511c93-8866-4d3f-a195-6f77205451b0
=> fix: sidebar resizing - focus on video layout (grid mode)

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat.yaml, bbb-learning-dashboard/package-lock.json, bbb-learning-dashboard/package.json, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-area/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/component.jsx
- Also merge 2.7 into Develop
```
subscription {
chat {
chatId
lastSeenAt
}
}
```
=> refactor (graphql-server): Add prop lastSeenAt to ChatList

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserStateDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserVoiceDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_ref.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_voice.yaml
Add prop `speechLocale` introduced in #17724 to graphql endpoints `user` and `user_current`.
=> refactor (graphql-server): new prop user.speechLocale

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/customparameters/constants.js, bigbluebutton-tests/playwright/customparameters/customparameters.js, bigbluebutton-tests/playwright/customparameters/customparameters.spec.js
Implements 4 tests for the disabledFeatures and the disabledFeaturesExclude related to the slide snapshot and the camera as content features.
=> test: slide snapshot, camera as content disabledFeatures tests

bigbluebutton-html5/imports/ui/components/pads/service.js
=> fix: throttledPinPad function

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
This PR fixes the bug where the users tries to disable self-view and disables all cameras instead.
#18217
=> Fix: All cameras being disabled

bigbluebutton-html5/imports/ui/components/raisehand-notifier/container.jsx
This PR implements code that allow the mods to be on the raised hands queue and participate better in on going discussions.
#16510
=> Enhancement: Raise hand behaviour changes

bigbluebutton-html5/imports/ui/components/presentation/service.js
Adjusts quick poll character limit.
Closes #18307
=> fix: Multiple selection polling not showing entirely a long option line

bigbluebutton-html5/imports/ui/components/timer/component.jsx, bigbluebutton-html5/imports/ui/components/timer/styles.js
Makes the following changes to timer/stopwatch panel:
- time inputs only appear when in timer mode
- adjust input and button styles
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/d3eea489-ef60-41e0-bccd-6c58d954b5dd
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/5593cabf-dc9e-49fa-89e4-8c890df1ea4e
=> style: adjust timer styles

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.js
Use `<ul>` and `<li>` for the list of users in connections status modal.
=> fix(accessibility): implement the list of users within the session logs as a list

bigbluebutton-tests/playwright/core/settings.js, bigbluebutton-tests/playwright/user/status.js
=> test: fixing set status

bigbluebutton-html5/imports/ui/components/poll/service.js
It adds Label in the result of a quick poll, if it was predefined in the slide.
Closes #18308 
See a little demo ahead: 
https://github.com/bigbluebutton/bigbluebutton/assets/69865537/a5146d06-91f4-44a8-8832-5a96b090176f
=> feature: Make quick poll result labels consistent with the uploaded slides 

bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
It fixes audio button when joining audio in a breakout.
Closes #18259
https://github.com/bigbluebutton/bigbluebutton/assets/69865537/572b0387-d243-4687-9732-f090580dfbbf
=> Fix - join audio in breakout room

bigbluebutton-html5/imports/ui/components/emoji-picker/reactions-bar/component.jsx
Use native emoji in reactions bar.
Closes #18342
=> Reactions bar - reduce load time

bbb-learning-dashboard/src/components/StatusTable.jsx, bbb-learning-dashboard/src/components/UsersTable.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/common/locales-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/common/modal/simple/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.js, bigbluebutton-html5/imports/ui/components/poll/service.js, bigbluebutton-html5/imports/ui/components/presentation/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/public/locales/fa_IR.json, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/helpers.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/presentation/presentation.js, bigbluebutton-tests/playwright/presentation/presentation.spec.js, bigbluebutton-web/gradle.properties
Regular propagation of fixes to upstream
=> chore: Merge 2.6.10+ (July 21, 2023) into 2.7

bbb-presentation-video.placeholder.sh
* https://github.com/bigbluebutton/bbb-presentation-video/pull/45 by @kepstin
* Fixes https://github.com/bigbluebutton/bbb-presentation-video/issues/43
* Fixes https://github.com/bigbluebutton/bbb-presentation-video/issues/44
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.2...4.0.3
=> chore(bbb-presentation-video): Update to 4.0.3

bigbluebutton-tests/playwright/presentation/presentation.js
Adds a check for the fit-to-width button to check if it's on or off.
=> test: check to fit-to-width

bbb-pads.placeholder.sh
Sets a newer version of `bbb-pads`
Closes #none
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.5.0
=> chore: Bump bbb-pads to 1.5.0

bbb-pads.placeholder.sh
Sets a newer version of `bbb-pads`
Closes #none
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.5.1
=> chore: Bump bbb-pads to 1.5.1

.github/workflows/automated-tests.yml
This PR updates the URLs used for downloading necessary files since the host has been changed
=> ci: Update URLs

bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js
=> fix: Dial-in users not in list

bigbluebutton-html5/public/locales/en.json
This PR makes navigation through meeting ended page easier, by adjusting the text to let clear in the message what actions BBB expects from users. 
#18334 
Before: 
After:
=> Client: Re-writing of the meeting ending to make navigation more clear for users

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/smart-video-share/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
This PR updates the handling of smart slide questions and URLs detection. The previous implementation struggled with multi-line questions and missed some URLs when they were listed as bullets on the slide.
Closes #18357 and #18356
=> fix: Enhance Smart Slide Question And URL Detection

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RecordAndClearPreviousMarkersCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SetRecordingStatusCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingRecordingDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingRecordingPoliciesDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_meeting.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
```
query {
meeting_recording {
isRecording
startedAt
startedBy
stoppedAt
stoppedBy
previousRecordedTimeInSeconds
}
meeting {
recording {
isRecording
startedAt
startedBy
stoppedAt
stoppedBy
previousRecordedTimeInSeconds
}
}
}
```
=> refactor (graphql-server): Add endpoint meeting_recording

bigbluebutton-html5/private/config/settings.yml, docs/docs/new-features.md
Changes the default value for `app.public.guestPolicyExtraAllowOptions` in `bbb-html5` config file `settings.yml`
Closes # none
Simplification.
Before
After
=> chore: set guestPolicyExtraAllowOptions to false

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
This PR fixes the Pulse animation used for when the user is talking and has an avatar image.
=> Fix: pulse animation with avatar

bigbluebutton-html5/imports/ui/components/timer/indicator/styles.js
This PR better adjusts the margin of timer element.
=> Client: Margin of timer adjusted to better fitting size

bigbluebutton-html5/imports/ui/components/timer/indicator/styles.js
This PR better adjusts the margin of timer element.
=> style: Margin of timer adjusted to better fitting size

bigbluebutton-html5/public/locales/en.json
Rewording a label
Closes #none
Related https://github.com/bigbluebutton/bigbluebutton/issues/18449
Hopefully improving the wording.
=> refactor: Reworded the label for download pres+annotations

.github/workflows/automated-tests.yml
=> WIP: tests: Speed up building time by using cache

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.jsx, bigbluebutton-html5/public/locales/en.json
This PR let the user choose which cam to disable (or disable all  of them).
#17970 
Single cam disable:
Disable all cams:
=> fix: Disabled self cam tied to specific cam (or all cams)

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserReactionDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_reaction.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_reaction_current.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
- Get current reaction (not expired) at `user.reaction`
```gql
subscription {
user {
name
reaction {
reactionEmoji
userId
}
}
}
```
- Get all reactions (not expired)
```gql
subscription {
user_reaction {
createdAt
expiresAt
reactionEmoji
user {
userId
name
}
}
}
```
=> (graphql-server): Provides data for Reactions

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx
=> fix: Display raise hand and away emoji in userlist

bigbluebutton-html5/private/config/settings.yml, docs/docs/new-features.md
Changes the default value for `public.app.wakeLock.enabled` and `public.app.defaultSettings.application.wakeLock` in `bbb-html5` config file `settings.yml`
=> chore: set wakeLock.enabled to true

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/styles.js, bigbluebutton-html5/imports/ui/components/common/menu/styles.js
- align emoji in reactions bar
- adds distinct colors for focused and active reaction
https://github.com/bigbluebutton/bigbluebutton/pull/18447#pullrequestreview-1567532528
=> style: reactions bar improvements

.github/workflows/automated-tests.yml
<table>
<tr>
<td>
Previously, our tests were executed directly on the PR code:
</td>
<td>
This PR modifies the CI process to merge the PR changes into the master branch and then run the tests on this combined codebase:
</td>
<tr><td>
</td>
<td>
</td>
</tr></table>
**Benefits:**
1. **Better Bug Detection**: This will identify potential bugs or issues that might only appear post-merging, ensuring a more stable master branch.
2. **Up-to-date Test Execution**: Even if the PR has outdated code, it will be tested against the most recent `bigbluebutton-tests` code from the master branch.
3. **Facilitated Test Re-runs**: If tests fail for a PR and a subsequent PR provides a fix, simply re-running the tests for the original PR will incorporate the fixes from the newer PR, reducing redundancy and …
=> ci(tests): Merge PR into master branch before running tests

freeswitch.placeholder.sh
Pulls the latest fixes from branch 'master' up to https://github.com/signalwire/freeswitch/commit/41507363f3fffcdad547b168e55fbe3383a24c3d
Closes #none
Includes various recent fixes -- 6 months of work past the current 1.10.9
=> chore: Bump FreeSWITCH to 'master' from end of July 2023

build/packages-template/bbb-playback-notes/build.sh, build/packages-template/bbb-playback-podcast/build.sh, build/packages-template/bbb-playback-presentation/build.sh, build/packages-template/bbb-playback-screenshare/build.sh, build/packages-template/bbb-playback-video/build.sh, build/packages-template/bbb-playback/build.sh
Updates the package descriptions for all `bbbplayback*` packages. Based on @kepstin 's recommendation.
Closes #none
More fitting descriptions...
=> build: Update the descriptions for bbb-playback packages

bigbluebutton-config/bin/bbb-conf, build/packages-template/bbb-graphql-middleware/build.sh, build/packages-template/bbb-html5/opts-jammy.sh
* build: list bbb-graphql-middleware as dependency to bbb-html5
* build: correct configs for bbb-graphql-middleware.service
* fix(bbb-conf): add graphql services and mongo to --status list
Closes #none
Got bbb-graphql-middleware to start :confetti_ball:
=> build: Fixes for bbb-graphql-middleware, bbb-conf updates

bigbluebutton-tests/playwright/polling/poll.js
Adds a check inside the poll results on the whiteboard test, where only the presenter is able to edit the poll results.
=> test: only presenter can edit the poll results

bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/whiteboard/draw.js, bigbluebutton-tests/playwright/whiteboard/whiteboard.spec.js
Adds a check for the right-click button on the whiteboard. So it covers this already resolved issue #17894
=> test: Check for right click on whiteboard

freeswitch.placeholder.sh
- [build(freeswitch): v1.10.10](https://github.com/bigbluebutton/bigbluebutton/commit/23cfc80a326cd87f55f3d68ee96952a1fada645c) 
- See: https://github.com/signalwire/freeswitch/releases/tag/v1.10.10
n/a
=> build(freeswitch): v1.10.10

build/packages-template/bbb-graphql-server/after-install.sh
Bypassed the service enabling / start of bbb-graphql-server for docker environments...
Closes #none
Trying to handle an issue with after-install.sh of `bbb-graphql-server` while building for docker-dev. Looks like in some other after-install.sh blocks we have such a check. We don't start the service automatically on install but do so later on. The error I am hitting is `WARNING: Could not add bbb-graphql-server to autostart: neither update-rc nor chkconfig found!`
=> build: /.dockerenv tweak for bbb-graphql-server

bigbluebutton-html5/imports/ui/services/virtual-background/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Fixes the below problem by replacing the wasm detection library.
=> fix(bbb-html5): Replace wasm detection library

bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/container.jsx, bigbluebutton-html5/imports/ui/components/webcam/container.jsx, bigbluebutton-html5/private/config/settings.yml
Implements pagination in grid mode.
Default values:
```
desktopGridPageSizes:
moderator: 48
viewer: 48
mobileGridPageSizes:
moderator: 14
viewer: 14
```
Closes #18125
=> feat(bbb-html5): Grid mode pagination

build/deb-helper.sh
Recovers SERVLET_DIR definition deb-helper.sh
Closes #none
Was removed in https://github.com/bigbluebutton/bigbluebutton/pull/18514 but is still needed
=> build: Recover SERVLET_DIR definition deb-helper.sh

bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
=> fix (bbb-web) (2.6): Getting wrong final URL (from redirect) on presentation upload

bigbluebutton-html5/imports/ui/components/common/menu/component.jsx, bigbluebutton-html5/imports/ui/components/common/menu/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
fix `Warning: React does not recognize the prop on a DOM element.` warnings.
=> refactor: fix invalid prop warnings

bigbluebutton-html5/imports/startup/client/base.jsx
Fix incorrect chat appearing when a user joins a meeting.
=> fix: incorrect chat on join

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/componet.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
- fix name being displayed in italic even for online users
- remove extra space between user name and message
=> style: adjust chat message styles

bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addBulkGroupChatMsgs.js, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/component.tsx
Modifies the chat to correctly render links, line breaks, and special characters.
=> Fix: handling of chat messages

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR prevents the presentation slide from jerking while panning.
Closes #18596
=> fix: Stop Presentation Jerks While Panning

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/chat-list-item/styles.ts
Removes border in chat list items
=> style: remove chat list item border

bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/api/group-chat-msg/server/methods/sendGroupChatMsg.js, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
- Removes html escaping/manipulation in the chat
- Adds configuration options in settings.yml for users to specify supported Markdown features.
- Updates client-side rendering to process and display markdown (considering the enabled markdown features).
Closes #18594
=> Modify chat to use markdown

bigbluebutton-tests/playwright/breakout/breakout.spec.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/options/options.spec.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/polling/polling.spec.js, bigbluebutton-tests/playwright/presentation/presentation.spec.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/whiteboard/whiteboard.spec.js
Adds the @flaky to the failing tests on ci.
=> test: adding flaky tag to failing tests on ci

bigbluebutton-html5/imports/utils/throttle.js
Implements .cancel in custom throttle function.
Closes #18602
=> fix: Client crashes when mute microphone while Closed Caption is executing

bigbluebutton-html5/imports/ui/components/app/component.jsx
Restores changes made in https://github.com/bigbluebutton/bigbluebutton/pull/18452/commits/632b7764bfe1ed5a56bcb316ded04daf9da23dc0 and lost on a merge of 2.7.x-release into develop.
=> fix: fit to width feature

.github/workflows/automated-tests.yml, .gitlab-ci.yml, akka-bbb-apps/build.sbt, akka-bbb-fsesl/build.sbt, bbb-common-message/build.sbt, bbb-common-web/build.sbt, bbb-export-annotations/package-lock.json, bbb-export-annotations/package.json, bbb-fsesl-client/build.sbt, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-web/gradle.properties, build/packages-template/bbb-web/after-install.sh, build/packages-template/bbb-web/build.sh, build/packages-template/bbb-web/opts-focal.sh, build/packages-template/bbb-webrtc-sfu/after-install.sh, docs/docs/development/dev-guide.md, docs/docs/new-features.md
This is a backport from BBB 2.7
Backports https://github.com/bigbluebutton/bigbluebutton/pull/18159 https://github.com/bigbluebutton/bigbluebutton/pull/18154/ https://github.com/bigbluebutton/bigbluebutton/pull/18162 https://github.com/bigbluebutton/bigbluebutton/pull/18195 https://github.com/bigbluebutton/bigbluebutton/pull/18196
Packaging image changes: https://github.com/bigbluebutton/bbb-docker-build-packages/pull/2 
bbb-install changes: https://github.com/bigbluebutton/bbb-install/pull/676
Closes partially https://github.com/bigbluebutton/bigbluebutton/issues/16101
NodeJS 16 official maintenance ends soon (Sept 11, 2023) https://nodejs.dev/en/about/releases/
Java 11 premium support ends soon (Sept 2023) https://www.oracle.com/java/technologies/java-se-support-roadmap.html
=> build: Upgrade to Java17, NodeJS 18

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/componet.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/component.tsx, bigbluebutton-html5/imports/ui/core/enums/chat.ts, bigbluebutton-html5/imports/ui/core/events/events.ts
This pull request introduces the chat enums which consolidates all chat-related enums into a single organized structure. This change enhances the maintainability and readability of our codebase by centralizing the definitions of chat-related constants.
=> Add: Chat enums

docs/docs/new-features.md
Adding documentation to help with the upgrade to 2.6.14.
Closes #none
Related to #18680 
Administrators need to handle the jump of NodeJS 16->19.
=> docs: add info on NodeJS v18 and Java 17 upgrade paths

docs/docs/new-features.md
Improves the docs for 2.6.14 upgrade of nodejs.
Closes #none
You can perform an upgrade of nodejs, no need for purge of the older version first.
=> docs: Improve docs for 2.6.14 upgrade of nodejs

.github/workflows/ts-code-compilation.yml, .github/workflows/ts-code-validation.yml
Improves the typescript compilation and validation CI's to use same checkout/merge approach as the automated test CI.
=> Add merge-branches step to typescript compilation and validation CI

.github/workflows/ts-code-compilation.yml, .github/workflows/ts-code-validation.yml
Make the typescript compilation and validation CI have same rules as the automated tests.
=> Add selective execution rules to typescript compilation and validation CI

.github/workflows/automated-tests-publish-results.yml
Modify the workflow named "Publish Test Results" to be "Automated tests - publish results", as these results are related with the automated tests.
=> Improve automated tests results publication workflow name

docs/build.sh, docs/docs/administration/lti.md, docs/docs/greenlight/v3/install.md, docs/docs/new-features.md, docs/src/components/HomepageFeatures/index.tsx
Updated the docs to indicate that BBB 2.7 is stable, no longer dev.
Closes #none
=> docs: 2.7 released docs

docs/docusaurus.config.js
=> docs: set 2.7 as the current docs version

docs/docusaurus.config.js
Adds rerouting to handle links like https://docs.bigbluebutton.org/2.7/new-features
Closes #none
Preparations for 2.7.0
=> docs: Handle routes in docusaurus.config.js

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, build/packages-template/bbb-etherpad/build.sh, build/packages-template/bbb-export-annotations/build.sh, build/packages-template/bbb-pads/build.sh, build/packages-template/bbb-webhooks/build.sh, build/packages-template/bbb-webrtc-sfu/build.sh, docs/docs/new-features.md
Regular propagation of fixes to upstream.
=> chore: Merge BBB 2.6.14 into v2.7.x-release

build/packages-template/bbb-webhooks/build.sh, build/packages-template/bbb-webrtc-sfu/build.sh
Fixes a version specification of yq I missed to spot when we merged v2.7.x-release into develop
Closes #none
yq on branch `develop` is 4+
=> build: drop yq 3 requirement on "develop"

bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/layouts/layouts.spec.js, bigbluebutton-tests/playwright/learningdashboard/learningdashboard.spec.js, bigbluebutton-tests/playwright/options/options.spec.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/playwright.config.js, bigbluebutton-tests/playwright/polling/polling.spec.js, bigbluebutton-tests/playwright/reconnection/reconnection.spec.js
Sets dynamically the mode to run the tests, getting the most out of #18664. When running on a single machine, it will still be reusing previously opened pages for the subsequent test steps
=> test: Dynamically set parallel or serial mode

build/packages-template/bbb-transcription-controller/build.sh
Reverts https://github.com/bigbluebutton/bigbluebutton/commit/a1d8f4bf7e964080a8ce42623df3aeb03e5f670d in favor of https://github.com/bigbluebutton/bigbluebutton/pull/18756
Closes #none
I made a mistake while testing #18756 and thought an alternative (https://github.com/bigbluebutton/bigbluebutton/commit/a1d8f4bf7e964080a8ce42623df3aeb03e5f670d) was needed.
=> revert: drop .git from bbb-tranctiption-controller (second version)

bbb-playback.placeholder.sh
Propagates fixes from bbb-playback from last 6 months
Closes https://github.com/bigbluebutton/bigbluebutton/issues/18721 and others
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.1
=> chore: Bump bbb-playback to 5.0.1

docs/docs/development/api.md
Added info on what disabledFeatures options were added in 2.7
Closes #none
=> docs: info on what disabledFeatures options were added in 2.7

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/popup-content/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/user/lockViewers.js, bigbluebutton-tests/playwright/user/multiusers.js, bigbluebutton-tests/playwright/user/user.spec.js
Fix a few multiusers tests:
Toggle user list
Make presenter 
Take presenter
Promote to moderator
Demote to viewer
Give and remove whiteboard access
Allow Everyone
Accept - Guest policy
=> test: fixing multiusers

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
This PR fixes the bug where the mods were bring locked along with the viewers
=> Fix: Mods being locked

.github/workflows/automated-tests.yml
=> ci (tests): Generate one config/log artifact for each runner

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/componet.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/chat-list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/chat-list-item/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
Same as https://github.com/bigbluebutton/bigbluebutton/pull/18806, but for the chat area.
=> fix: user avatar in chat

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/popup-content/styles.ts
This PR fixes the style of buttons that  were a little off in 3.0.
=> Fix: Buttons styles for 3.0

.github/workflows/automated-tests.yml
Increases the timeout for install+test from 15mins to 25mins
Closes #
none
In some cases we hit the 15mins timeout and the tests do not complete.
=> ci: Increase the timeout for install+test from 15mins to 25mins

bbb-graphql-server/install-hasura.sh, bbb-graphql-server/update_graphql_data.sh, build/packages-template/bbb-graphql-server/after-install.sh, build/packages-template/bbb-graphql-server/build.sh
- Adds param `--skip-update-check` to Hasura cli in order to avoid external requests
- Update Hasura version to 2.33.4
=> refactor (graphql-server): Hasura cli skip update check

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
=> fix(html5): fix nav-bar plugin exception

bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/service.ts
Fix mute feature in talking indicator area
=> fix: mute user in talking indicator

docs/build.sh
Modifies the build script for our docs to support using tags instead of branches for old BBB releases
Closes #none
Currently the docs building is broken because branch `v2.5.x-release` no longer exists (I deleted it as part of retiring BBB 2.5)
=> docs: use tag v2.5.9 to construct BBB 2.5 docs

bbb-presentation-video.placeholder.sh
* https://github.com/bigbluebutton/bbb-presentation-video/pull/47 by @kepstin
* https://github.com/bigbluebutton/bbb-presentation-video/pull/46 by @kepstin
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.3...4.0.4
=> bbb-presentation-video: Update to 4.0.4

bbb-presentation-video.placeholder.sh, record-and-playback/core/lib/recordandplayback/edl/audio.rb
This PR is a backport (cherry-pick) of the following PRs:
* https://github.com/bigbluebutton/bigbluebutton/pull/18892
* https://github.com/bigbluebutton/bigbluebutton/pull/18893
to BigBlueButton 2.6. See those PRs for details.
=> Recording fix backports for 2.6

bbb-etherpad.placeholder.sh
Upgrades etherpad-lite to 1.9.3
Closes #
https://github.com/ether/etherpad-lite/releases/tag/v1.9.2
https://github.com/ether/etherpad-lite/releases/tag/v1.9.3
=> build(etherpad): Bump etherpad-lite to 1.9.3

bigbluebutton-tests/playwright/chat/chat.js, bigbluebutton-tests/playwright/user/lockViewers.js, bigbluebutton-tests/playwright/user/user.spec.js
Add checks for the typing indicator and remove the @flaky from the test "Lock See other viewers in the Users list".
=> test:  Check for typing indicator +  remove flaky

bigbluebutton-html5/imports/ui/core/hooks/useShortcut.tsx
This PR fixes the the shortcut hook therefore also fixing the hooks that were not working previously.
=> Fix: shortcut hook

bigbluebutton-html5/imports/ui/components/audio/captions/speech/service.js
After the change from lodash to radash, we've implemented our own throttle function, it work properly to almost all cases, but it doesn't work well to audio caption cutting the words and have a type of "batch" in captions making it unusable, I changed it to radash throttle and it started work pretty fine.
=> Hotfix: Audio captions not working properly

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/components/user-avatar/styles.js
Centers icons indicating presenter, audio state and whiteboard access in the user list.
Closes #18763
=> fix(user-list): center icons on safari

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.js, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/styles.js, bigbluebutton-html5/imports/ui/components/emoji-picker/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-picker/reactions-picker/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-picker/reactions-picker/styles.js, bigbluebutton-html5/imports/ui/components/emoji-rain/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-rain/container.jsx, bigbluebutton-html5/imports/ui/components/emoji-rain/service.js, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
Ports new version of reactions for BBB 2.7
[emojis.webm](https://github.com/bigbluebutton/bigbluebutton/assets/91704222/02e53b7f-b9c3-4bfe-98c9-956f5e4138b5)
=> feat(reactions): port new reactions

docs/docs/new-features.md
Adds brief mention of Reactions Animations, how to enable them on a server and how to toggle them on/off via in-client Settings.
Closes #none
Related: #18959 
They are off by default so lots of people will be asking how to enable...
=> docs: Add info on reactions animations

bigbluebutton-html5/package-lock.json
Upgraded some npm dependencies that were reported vulnerable.
Closes #
none
`npm audit` was reported vulnerable dependencies.
=> chore: npm audit fixes bbb-html5

bbb-learning-dashboard/package-lock.json
Upgraded some npm dependencies that were reported vulnerable.
Closes # none
`npm audit` was reported vulnerable dependencies.
=> chore: npm audit fixes for bbb-learning-dashboard

bigbluebutton-web/gradle.properties
Upgrades Spring to 2.7.17 and embedded Tomcat to 9.0.82. Also versions of Grails and Groovy saw a bump.
Closes #none
Some vulnerabilities were patched
* https://www.cve.org/CVERecord?id=CVE-2023-44487  -- Fix: Upgrade to org.springframework.boot:spring-boot-starter-tomcat@2.7.17
* https://www.cve.org/CVERecord?id=CVE-2023-42794 -- Fix: Upgrade to org.springframework.boot:spring-boot-starter-tomcat@2.7.17
=> chore: upgrade Spring to 2.7.17

docs/docs/data/create.tsx, docs/docs/development/api.md
Adding docs for two new CREATE parameters: preUploadedPresentation and preUploadedPresentationName
Closes #
Documenting what was added in #18953
=> docs: preUploadedPresentation and preUploadedPresentationName

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
This PR changes the focus into the chat input when chat list is clicked.
Exemple.
=> Client: Focus on input when clicking chat

bigbluebutton-tests/playwright/presentation/presentation.spec.js
Adds the flaky flag to the test "Upload other presentations format", because the test is inconsistent.
=> test: Adds @flaky to other presentation format test

.github/dependabot.yml
Initializes the configurations for Dependabot.
Branch v2.6.x-release -- nothing for the moment. Ideally security updates once a week. No version updates.
Branch v2.7.x-release -- security updates daily. No version updates.
Branch v3.0.x-release -- security updates and versions updates daily.
Branch develop -- nothing for the moment. Ideally security updates and version updates once a week.
Closes #none
Improvement of dependency updates, directly triggering pull requests and CI runs
=> chore: configure Dependabot

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
=> feat(plugin): use latest plugin SDK version

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/component.tsx
Fix roving feature, making chat list accessible by keyboard
https://github.com/bigbluebutton/bigbluebutton/assets/3728706/09b0c97f-61b1-454d-95e9-fd5297911601
=> fix(accessibility): roving functionality in chat list

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
This PR makes so the number in the multi user whiteboard is clickable and doesn't change the cursor.
=> Client: Multi user whiteboard number clickable

bbb-etherpad.placeholder.sh
Upgraded Etherpad to from 1.9.3 to 1.9.4
Closes #
Mostly for the Log4j and axios upgrades
https://github.com/ether/etherpad-lite/releases/tag/v1.9.4
=> chore: Bump Etherpad to 1.9.4

bigbluebutton-html5/imports/utils/throttle.js
Improves throttle function so it respects the delay on the second time the function is triggered.
=> fix: improve throttle function

bbb-libreoffice/docker/Dockerfile
Upgrades LibreOffice from 7.5.7 to 7.6.2.1
Closes #18984
Version 7.5 is EOL in a month
=> chore: Upgrade LibreOffice to 7.6.2

.github/workflows/automated-tests.yml
=> ci (backport 2.7): Refresh package's cache whenever there are changes in its build directory

bigbluebutton-html5/imports/ui/components/timer/indicator/container.jsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/component.tsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/queries.tsx, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/service.ts, bigbluebutton-html5/imports/ui/components/timer/timer-graphql/indicator/styles.ts, bigbluebutton-html5/imports/utils/humanizeSeconds.js
Migrate the Timer indicator to use TS + Graphql
=> Refactor: Migrate timer indicator

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatUserDAO.scala, bbb-graphql-client-test/src/ChatsInfo.js, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_user.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_private.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_public.yaml, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-typing-indicator/queries.ts
Before (look the left screen, the first name in Typing Indicator is always who typed last):
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/52aa490e-4c24-4a7f-9a8c-59e0db19d38a
After (the first name is who started typing first):
https://github.com/bigbluebutton/bigbluebutton/assets/5660191/504175b8-f65b-43d8-9e25-3a6976251bc0
=> fix (graphql): Fix order of who is typing

bbb-pads.placeholder.sh
Pulls newer bbb-pads
Closes # none
Freshly cut 1.5.2 with a bunch of newer library versions
https://github.com/bigbluebutton/bbb-pads/releases/tag/v1.5.2
=> chore: Bump bbb-pads to 1.5.2

bigbluebutton-html5/imports/ui/Types/meeting.ts, bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/modal/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/modal/service.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/modal/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/service.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/progress-bar/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/progress-bar/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/reload-button/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/reload-button/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/subtitles/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/subtitles/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/volume-slide/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/volume-slide/styles.ts, bigbluebutton-html5/imports/ui/components/external-video-player/modal/container.jsx, bigbluebutton-html5/imports/ui/components/layout/layoutTypes.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/meetingSubscription.ts
Same of #18909, but made in 3.0 branch, the first version were meant to develop branch having a few conflicts when changed to 3.0 so a made a new branching cherry picking the commits
=> Refactor: Migrate external video player

bbb-playback.placeholder.sh
Libs updates on bbb-playback
Closes # none
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.2
=> chore: Bump bbb-playback to 5.0.2

bbb-webhooks.placeholder.sh
- [build(bbb-webhooks): v2.6.1](https://github.com/bigbluebutton/bigbluebutton/commit/31d2bf798e66afeb47b79257bc7737bfc5ed6711) 
* See https://github.com/bigbluebutton/bbb-webhooks/releases/tag/v2.6.1
None
=> build(bbb-webhooks): v2.6.1

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
This PR restores the keyboard roving functionality for user list
=> fix(accessibility): restore roving functionality in user list

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-presentation-video.placeholder.sh, bigbluebutton-html5/imports/ui/components/audio/captions/speech/service.js, record-and-playback/core/lib/recordandplayback/edl/audio.rb
This PR is merging some 27 changes into 30.
Those being:
- fix: End breakout rooms when ENDED_DUE_TO_NO_MODERATOR - [18891](https://github.com/bigbluebutton/bigbluebutton/pull/18891)
- fix(recording): Deskshare audio processing hang - [18892](https://github.com/bigbluebutton/bigbluebutton/pull/18892)
- bbb-presentation-video: Update to 4.0.4 - [18893](https://github.com/bigbluebutton/bigbluebutton/pull/18893)
- Hotfix: Audio captions not working properly - [18906](https://github.com/bigbluebutton/bigbluebutton/pull/18906)
=> v27 changes ported to v30 part 2.

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Includes `npm audit fix` and `npm audit fix --force` upgrades for `bbb-html5`
Closes #none
Preparation for 2.6.15
=> chore: npm dependencies upgrades in bbb-html5

bbb-export-annotations/package-lock.json
Includes `npm audit fix` upgrades for `bbb-export-annotations`
Closes # none
Preparations for 2.6.15
=> chore: npm dependencies upgrades in bbb-export-annotations

bbb-learning-dashboard/package-lock.json
Includes `npm audit fix` upgrades for `bbb-learning-dashboard`
Closes #none
Preparations for BBB 2.6.15
=> chore: npm dependencies upgrades in bbb-learning-dashboard

bbb-libreoffice/docker/Dockerfile
Backports several commits to upgrade LibreOffice to 7.6.2 (already used in BBB 2.7+), also anything under 7.6 is EOL
Closes #none
Preparations for BBB 2.6.15
=> chore: Bump LibreOffice to 7.6.2 (backport)

bigbluebutton-web/gradle.properties
Backport of  #18981 to BBB 2.6
=> chore: upgrade Spring to 2.7.17 (backport)

.github/workflows/automated-tests.yml
Changing from `v2.8` to `v3.0`
=> ci: Fix automated tests workflow installation

bigbluebutton-html5/imports/ui/components/webcam/container.jsx
Restores resize of presentation area in custom layout after the migration to use graphql data
=> fix: restore resize presentation area in custom layout

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
=> fix: fix logoutUrl (backup)

bigbluebutton-html5/public/locales/el_GR.json
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following localization files have been updated:</p><h3 …
=> Translations 60cd9b750d2d41cd929b29887b4db1e8 el gr

bbb-webrtc-sfu.placeholder.sh
[build(bbb-webrtc-sfu): v2.12.0](https://github.com/bigbluebutton/bigbluebutton/commit/06262e309a4bbcbdfbee1766ab66c8e4f4a8e163)
See https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.12.0
Closes Issue(s)
n/a
As provided in the original PR by @prlanzarin - https://github.com/bigbluebutton/bigbluebutton/pull/19053
=> build(bbb-webrtc-sfu): v2.12.0 (port of #19053)

docs/docs/administration/install.md
=> docs: Update typos in install.md

.github/ISSUE_TEMPLATE/docs-issue.md, docs/docs/administration/customize.md, docs/docs/administration/install.md, docs/docs/greenlight/v3/install.md, docs/docs/greenlight/v3/migration.md
Backporting a few docs related commits so they run through the docs build correctly
PRs #18972 #18965 #18964  #19195
=> docs: Docs backport

docs/docs/greenlight/v3/migration.md
=> Greenlight v3 docs: More cleanup and reorg

bbb-graphql-actions-adapter-server/src/actions/userJoin.ts
This file was missing in PR #19104
=> graphql: Add graphql-action: `userJoin`

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PostgresProfile.scala, bbb-graphql-actions-adapter-server/src/actions/pollCancel.ts, bbb-graphql-actions-adapter-server/src/actions/pollCreate.ts, bbb-graphql-actions-adapter-server/src/actions/pollPublishResult.ts, bbb-graphql-actions-adapter-server/src/actions/pollSubmitUserTypedVote.ts, bbb-graphql-actions-adapter-server/src/actions/pollSubmitUserVote.ts, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
```gql
mutation {
pollCreate(pollId: "123", pollType: "YN", secretPoll: false, question: "Yes????", isMultipleResponse: false)
}
mutation {
pollCancel
}
```
```gql
mutation {
pollCreate(pollId: "123", pollType: "YN", secretPoll: false, question: "Yes????", isMultipleResponse: false)
}
mutation {
pollSubmitUserVote(pollId: "0e674ec965b9ceba97c2f3e452a692e6d7d0d3c1-1701172198597/1/1701172741078", answerIds: [0])
}
mutation {
pollPublishResult(pollId: "0e674ec965b9ceba97c2f3e452a692e6d7d0d3c1-1701172198597/1/1701172741078")
}
```
```gql
mutation {
pollCreate(pollId: "123", pollType: "CUSTOM", secretPoll: false, question: "Best color in your opinion????", isMultipleResponse: true, answers: ["Orange","Blue","Red"])
}
mutation {
pollSubmitUserVote(pollId: …
```
=> graphql-actions: Poll actions

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Upgrade to the latest version of plugins sdk.
=> feat(plugin): upgrade plugin sdk

bigbluebutton-config/bin/bbb-conf
Fixes a command (appearing as part of a comment) in bbb-conf
Closes #none
Without the missing quote the command was invalid.
Reported by PaulS
=> fix(conf): Update bbb-conf missing a quiotation

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-tests/playwright/breakout/breakout.spec.js, bigbluebutton-tests/playwright/breakout/create.js, bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/core/elements.js
This PR updates the flaky tests list for the Breakout test suite. The current flaky ones are still flagged since it's been spotted a client-side bug
=> test: Update breakout flaky tests

docs/docs/administration/privacy.md, docs/docs/new-features.md, docs/docs/testing/release-testing.md
In order to upgrade to docusaurus v3, we need to comply with mdx v3 **on each docs branch**. This is the version for 2.6 BBB docs
=> docs: comply to MDX v3 (stricter markdown)

.github/ISSUE_TEMPLATE/docs-issue.md, .github/dependabot.yml, README.md, docs/build.sh, docs/docs/administration/customize.md, docs/docs/administration/install.md, docs/docs/greenlight/v3/install.md, docs/docs/greenlight/v3/migration.md, docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, docs/yarn.lock
Carries docs/ and .github/ updates from branch `develop` to branch `v3.0.x-release` because I'd like to [for the next couple of months] switch the default branch of this repo to be `v3.0.x-release`. These updates should allow me to change the branch without breaking the docs building action. 
Closes #none
The main reason I'd like to change the default branch is to take advantage of the automatic dependabot upgrades to the 3.0 branch rather than the develop branch. I've tried configuring dependabot and it just does not seem to pick up the configuration, so here we are. I am not aware of negative consequences of this PR or of the branch change. I will likely make the default branch be 'develop' again in a couple of months.
=> chore: Port docs and ci changes to v3.0.x-release

bbb-graphql-actions-adapter-server/src/actions/guestUsersSetLobbyMessage.ts, bbb-graphql-actions-adapter-server/src/actions/guestUsersSetLobbyMessagePrivate.ts, bbb-graphql-actions-adapter-server/src/actions/guestUsersSetPolicy.ts, bbb-graphql-actions-adapter-server/src/actions/guestUsersSubmitApprovalStatus.ts, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
```gql
mutation {
guestUsersSetPolicy(
guestPolicy: "ASK_MODERATOR"
)
}
mutation {
guestUsersSubmitApprovalStatus(
guests: [
{
guest: "w_tdtjhwpdkyhu",
status: "ALLOW"
},
{
guest: "w_smqqn0rgsfvn",
status: "DENY"
}
]
)
}
mutation {
guestUsersSetLobbyMessage(
message: "Please wait a few minutes!!!!!"
)
}
mutation {
guestUsersSetLobbyMessagePrivate(
guestId: "w_5psfubbvtcur",
message: "Hello student, I'll approve you"
)
}
```
=> graphql-actions: GuestUsers actions 

bbb-graphql-actions-adapter-server/src/actions/sharedNotesCreateSession.ts, bbb-graphql-actions-adapter-server/src/actions/sharedNotesSetPinned.ts, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
```gql
mutation {
sharedNotesSetPinned(
sharedNotesExtId: "notes",
pinned: true
)
}
mutation {
sharedNotesCreateSession(
sharedNotesExtId: "notes"
)
}
```
=> graphql-actions: SharedNotes actions

bbb-graphql-actions-adapter-server/src/actions/presentationSetWriters.ts, bbb-graphql-actions-adapter-server/src/actions/presentationSetZoom.ts, bbb-graphql-server/metadata/actions.graphql, bbb-graphql-server/metadata/actions.yaml
```gql
mutation {
presentationSetWriters(
pageId: "cb37519792173ec523e57add160b29b4fdf32e3b-1701965138127/1",
usersIds: ["w_w8bchbv2yfng", "w_dlnkhbyncdwy"]
)
}
mutation {
presentationSetWriters(
pageId: "cb37519792173ec523e57add160b29b4fdf32e3b-1701965138127/1",
usersIds: []
)
}
mutation {
presentationSetZoom(
presentationId: "cb37519792173ec523e57add160b29b4fdf32e3b-1701965138127",
pageId: "cb37519792173ec523e57add160b29b4fdf32e3b-1701965138127/1",
pageNum: 1,
xOffset: 0,
yOffset: 0,
widthRatio: 63.297763896137795,
heightRatio: 63.295929018789145
)
}
```
=> graphql-actions: Presentation actions

docs/docs/greenlight/v3/install.md
Backporting #19224 to v2.7.x-release
=> docs: updated greenlight docs to include user:set_admin_role rake task

docs/docusaurus.config.js
Closes #none
`Error: Invalid docs option "versions": unknown versions (2.5,3.0) found. Available version names are: 2.7, 2.6, 2.5-legacy`
=> docs: Fix for 2.5 legacy docs branch

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
It adds support for the new Ui Events, and adds a sample showing how to play around with it.
Closely related to https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/38
=> feat(plugins): Ui Events

docs/docs/administration/install.md, docs/docs/development/dev-guide.md
Adds the top portion of 2 pages including info on index, id, etc
Closes #none
Could not build the docs due to error `Couldn't find any doc with id "development/guide"`
Missed in #19302
=> docs: add missing index portions to 2 pages

docs/docusaurus.config.js
This is work in progress. We seem to have multiple `hreflang` in the `head` portion of the docs pages.
Closes #none
cc @paulseto
We're checking if dropping the `en` explicit locale will only keep the last row.
This change is very likely to be reverted shortly.
=> docs: WIP - drop i18n placeholder - SEO work

bigbluebutton-html5/private/config/settings.yml
Reduces [in half] the how long it takes before your reaction (emoji) is reset.
Closes #none
Based on [numerous] end user feedback.
=> chore: Reduce reaction expiration to be 30s

bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_componentsFlags.yaml
As suggested by @Tainan404 .
This PR:
- 🟢 Adds flag `meeting_componentFlags.hasCaption` 
- 🔴 Removes flag `meeting_componentFlags.audioTranscriptionCaption` 
- 🔴 Removes flag `meeting_componentFlags.typedCaption`
```gql
query {
meeting {
componentsFlags {
hasBreakoutRoom
hasCaption
hasExternalVideo
hasPoll
hasScreenshare
hasTimer
}
}
}
```
Related #19320
=> refactor (graphql-server): Include flag hasCaption

docs/docusaurus.config.js
Reverts bigbluebutton/bigbluebutton#19334
No change in the hreflang on the page.
=> Revert "docs: WIP - drop i18n placeholder - SEO work"

build/packages-template/bbb-freeswitch-core/build.sh, freeswitch.placeholder.sh
=> build(sec): upgrade FreeSWITCH to 1.10.11 +sofia-sip +libks

build/packages-template/bbb-freeswitch-core/build.sh, freeswitch.placeholder.sh
Port of #19377 to BigBlueButton 3.0-alpha*
=> build(sec): upgrade FreeSWITCH to 1.10.11 +sofia-sip +libks (#19377)

bbb-common-web/build.sbt
Bump spring-boot-starter-validation to 2.7.17 to match bbb-web
Closes #none
In https://github.com/bigbluebutton/bigbluebutton/pull/18981 we upgraded Spring to 2.7.17 but missed this library
=> fix: Bump spring-boot-starter-validation to 2.7.17 to match bbb-web

docs/docs/administration/customize.md
A follow up to https://github.com/bigbluebutton/bigbluebutton/commit/551028ba51165bf56e283b36221a61686ada60bc
Also escaped the `<` `>` chars which tripped the build (MDX 3)
Closes #none
Gladia support saw its first version released in BBB 2.7.4 yesterday.
=> docs: Tweaks to gladia io docs

bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx, bigbluebutton-html5/imports/ui/components/timer/container.jsx
fix issue with timer panel not opening when timer feature is activated
=> fix: timer panel does not open

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/component.tsx, bigbluebutton-html5/imports/ui/core/hooks/useShortcut.tsx, bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/breakout/create.js, bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/chat/util.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/helpers.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/layouts/layouts.spec.js, bigbluebutton-tests/playwright/learningdashboard/learningdashboard.spec.js, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/options/options.spec.js, bigbluebutton-tests/playwright/parameters/constants.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/parameters/util.js, bigbluebutton-tests/playwright/polling/poll.js, bigbluebutton-tests/playwright/polling/polling.spec.js, bigbluebutton-tests/playwright/presentation/presentation.js, bigbluebutton-tests/playwright/presentation/util.js, bigbluebutton-tests/playwright/reconnection/reconnection.spec.js, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
- Fixes `shortcuts` tests (and add it to CI runs);
- Fixes whiteboard selector - Tldraw v2;
- Sets `Notifications › Chat › Private Chat notification`, `Create Parameters › Max Participants`, `Create Parameters › Meeting Duration`, `Audio > Auto join`, `Audio > Force Listen Only` tests as flaky;
=> test: Fix no-flaky tests and properly set the execution mode

bbb-webrtc-sfu.placeholder.sh
* [build(bbb-webrtc-sfu): v2.12.2](https://github.com/bigbluebutton/bigbluebutton/commit/5a831d225c771b8136de6ea3916edd426a0fb22c) 
* fix(screenshare): resolve subscriberAnswer job
* fix(bbb-webrtc-recorder): exception when removing nullish recording callbacks
* fix(mediasoup): check for null producers
* build(mediasoup): 3.12.16
n/a
https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.12.2
=> build(bbb-webrtc-sfu): v2.12.2

bbb-webrtc-recorder.placeholder.sh
* [build(bbb-webrtc-recorder): v0.6.0](https://github.com/bigbluebutton/bigbluebutton/commit/82aa24164ac76fbb085626b33b889803bce92ac6) 
* feat: recorder.writeToDevNull option to write files to /dev/null (testing)
* fix: crash due to negative seqnums in sequence unwrapper
n/a
=> [3.0] build(bbb-webrtc-recorder): v0.6.0

bbb-webhooks.placeholder.sh
* [build(bbb-webhooks): v3.0.0-beta.4](https://github.com/bigbluebutton/bigbluebutton/commit/62cf89cf266e0ea7dae47ef2583a2a09dd9726c3) 
* fix: use ISO timestamps in production logs
* chore: remove unused events
* `rap-published`, `rap-unpublished`, `rap-deleted`
* chore: support internal_meeting_id != record_id on rap events
* !fix(webhooks): remove general getRaw configuration
* fix(test): use redisUrl for node-redis client configuration
* fix(test): pick up mocha configs via new .mocharc.yml file
* build: set .nvmrc to lts/iron (Node.js 20)
n/a
=> build(bbb-webhooks): v3.0.0-beta.4

bbb-webrtc-sfu.placeholder.sh
* [build(bbb-webrtc-sfu): v2.13.0-alpha.1](https://github.com/bigbluebutton/bigbluebutton/commit/da31a8d0f7b557909ff1b1c9dadce0157ce11923) 
* feat: add inbound queue size and job failure metrics
* feat: add dry-run recording mode
* feat: add time_to_mute/unmute metrics
* fix(audio): log and track metrics for hold/unhold timeouts
* fix(bbb-webrtc-recorder): exception when removing nullish recording callbacks
* fix(mediasoup): check for null producers
* fix(screenshare): resolve subscriberAnswer job
* fix(audio): prevent false positives in TLO toggle metrics
* refactor: replace logger lib, Winston -> Pino
* Winston's been problematic (missing logs) and Pino is more performant
* build: bump Docker and nvmrc to Node.js 20 (LTS)
n/a
=> build(bbb-webrtc-sfu): v2.13.0-alpha.1

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
Ports https://github.com/bigbluebutton/bigbluebutton/commit/59cdb136ad29859a3b6817ae56e83f057d44cf38 to BBB 3.0
fixes https://github.com/bigbluebutton/bigbluebutton/security/advisories/GHSA-r3vv-c788-9fph (to be published)
=> fix(sec): filter tags in presentation name (port from 2.7)

bigbluebutton-web/build.gradle, bigbluebutton-web/gradle.properties, bigbluebutton-web/gradle/wrapper/gradle-wrapper.properties
Port https://github.com/bigbluebutton/bigbluebutton/pull/19193 to BBB 3.0
=> chore(bbb-web): Upgrade Grails to 6.1 (port from 2.7)

bigbluebutton-html5/imports/ui/components/polling/container.jsx, bigbluebutton-html5/imports/ui/components/polling/polling-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/polling/polling-graphql/queries.ts, bigbluebutton-html5/imports/ui/components/polling/polling-graphql/service.ts, bigbluebutton-html5/imports/ui/components/polling/polling-graphql/styles.ts
Migrate poll answer gathering from Meteor to GraphQL.
=> Refactor: migrate poll answer gathering

bigbluebutton-html5/imports/ui/components/common/tooltip/bbbtip.css, bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Ports https://github.com/bigbluebutton/bigbluebutton/pull/19114 to BBB 3.0
=> fix: upgrade tooltip dependency and fix open tooltip on mobile (port from 2.7)

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Ports https://github.com/bigbluebutton/bigbluebutton/pull/19366 and https://github.com/bigbluebutton/bigbluebutton/pull/19395 to BBB 3.0
=> chore: bump axios (bbb-html5) (port from 2.7)

docs/docs/administration/bbb-conf.md, docs/docs/administration/install.md, docs/docs/greenlight/v3/install.md, docs/docs/greenlight/v3/migration.md
Ports to BBB 3.0 the following:
* https://github.com/bigbluebutton/bigbluebutton/pull/19166
* https://github.com/bigbluebutton/bigbluebutton/pull/18890
* https://github.com/bigbluebutton/bigbluebutton/pull/19205
* https://github.com/bigbluebutton/bigbluebutton/pull/19224
=> docs: port 2.7.4 tweaks on GL mostly

docs/docusaurus.config.js
Allow to customize the presence/absence of a trailing slash at the end of URLs/links, and how static HTML files are generated
Forces a trailing slash `/` at the end of urls. Seems to be desired for SEO.
Closes #
Allow to customize the presence/absence of a trailing slash at the end of URLs/links, and how static HTML files are generated
https://docusaurus.io/docs/api/docusaurus-config#trailingSlash
=> docs: Force trailingSlash

docs/docusaurus.config.js
Forces a trailing slash `/` at the end of urls. Seems to be desired for SEO.
This is a resubmit of #19522 after in #19528 I dropped it after some docs build pipeline issues appeared. Here I handle those, have tested them too.
Closes #none
Allow to customize the presence/absence of a trailing slash at the end of URLs/links, and how static HTML files are generated
>Allow to customize the presence/absence of a trailing slash at the end of URLs/links, and how static HTML files are generated
https://docusaurus.io/docs/api/docusaurus-config#trailingSlash
=> docs: enable trailingSlashes (2) and handle redirects

bbb-graphql-middleware/internal/hascli/conn/writer/writer.go
Reverts bigbluebutton/bigbluebutton#19523
=> Revert "Prevent graphql-middlware from re-transmitting Mutations"

bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
Backports https://github.com/bigbluebutton/bigbluebutton/pull/19372 from branch `develop`
=> fix: quicker zoom by wheel (backport from develop)

bigbluebutton-html5/imports/ui/components/timer/container.jsx
Makes timer stop and reset if time is changed (similar to BBB 2.7).
=> fix: stop and reset timer when time is changed

bbb-graphql-actions/src/actions/presAnnotationDelete.ts, bbb-graphql-actions/src/actions/presAnnotationDeleteAll.ts, bbb-graphql-actions/src/actions/presAnnotationSubmit.ts
It will allow non-moderators users to send whiteboard-related actions (remove wrong validation).
=> fix: Multi-user whiteboard not working with graphql

bbb-libreoffice/assets/convert-cool.sh, bbb-libreoffice/install-local.sh, bbb-libreoffice/install-remote.sh, build/packages-template/bbb-libreoffice-docker/after-install.sh, build/packages-template/bbb-libreoffice-docker/build.sh
This pull request add a conversion script for presentation to use Collabora Online. This is functionally equivalent to JODConverter (convert-remote).
Note: this is officially a contribution from Collabora Productivity.
Closes #18793 
Organisation that have Collabora Online installed might prefer to use it for the conversion instead instead of JODConverter or a local version.
Not sure where to update the documentation for this. I'll be happy to help. If you have any concernes, comment, change, I'd be happy to oblige.
Also I tried to make sure all the install scripts were updated.
=> Presentation: Add Script for Using Collabora Online as Document Converter

bbb-graphql-middleware/internal/common/Hasher.go, bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/hascli/conn/reader/reader.go, bbb-graphql-middleware/internal/hascli/conn/writer/writer.go, bbb-graphql-middleware/internal/msgpatch/jsonpatch.go
- **Data Uniqueness Verification**: For each subscription, the system will maintain a SHA256 hash of the most recently received data packet. Upon receiving a new message from Hasura, it will compare the new message's SHA256 hash with the hash of the last received message. If the hashes match, indicating no change in the data, the message will be disregarded. This mechanism is particularly beneficial in scenarios where the Hasura connection is reset, prompting Hasura to resend previously transmitted data. From the browser's standpoint, these retransmissions will now be seamlessly handled, ensuring that duplicate data does not affect the user experience.
- **Optimized `PatchMessage` Function**: The `PatchMessage` function has been streamlined. Given that the incoming message data is already …
=> enhancement (graphql-middleware): Data Uniqueness Verification and others

bigbluebutton-html5/imports/ui/components/poll/styles.js
Removes custom button styles in poll panel button.
Closes #19506
=> fix: Incorrect hover style on the upload presentation button in the polling menu

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/styles.js
Fixes invisible quick poll dropdown for YES/NO polls.
Closes #19445
=> fix(polling): invisible quick poll dropdown

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Disables presentation menu for files whose upload process is not completed.
Closes #19518
=> fix(presentation): disable menu for not uploaded files

docs/docs/administration/customize.md
Closes a block of code to fix the view of the docs page.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/19585
Thanks to @cmos64 for reporting this in https://github.com/bigbluebutton/bigbluebutton/issues/19585
I will send another PR for the BBB 3.0+ docs
=> docs: Close code block in customize md

docs/docs/administration/customize.md
=> docs: Close code block in customize md (port of 19588)

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fixes the functionality of taking a snapshot of current slide, which is broken after tldraw version update.
Closes #19556
=> fix(whiteboard): snapshot of current slide

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/utils.js
Removes both absent font file loading and unused code.
Closes #19579
=> fix(whiteboard): remove absent font file loading

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
display "hide toolbars" whiteboard menu option for all users.
=> fix: hide toolbar button only appearing for presenter

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
=> fix: follow chat tail

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
This PR permits presenters to edit poll result annotations.
[Screencast from 08-02-2024 11:24:39.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/5e14b9d4-521c-422e-b796-82f8454602b0)
Closes #19575
=> fix(whiteboard): poll result annotation handling

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
This PR addresses a critical issue where the whiteboard could crash if the undo shortcut was held down to undo changes rapidly. It introduces a more efficient undo/redo mechanism that supports continuous action when the shortcut keys are held down, preventing the application from crashing under rapid undo requests.
Additionally, this PR implements optimizations to reduce unnecessary re-renders, particularly noticeable during slide transitions and when toggling the multi-user functionality on the whiteboard. These changes result in smoother transitions without the previous flashing or flickering, enhancing the user experience.
Closes #19591
=> fix(whiteboard) Prevent Continuous Undo Crash and Improve Rendering Performance

bigbluebutton-html5/imports/api/annotations/server/methods/sendBulkAnnotations.js
We no longer need this information (was useful while adopting tldraw)
Closes #none
=> fix: Drop heavy log from sendBulkAnnotations.js

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala
Reducing logs -- this was useful back when we were adopting tldraw. I am disabling the logs but not removing it yet.
Closes #none
=> fix: Reduce logs in SendWhiteboardAnnotationPubMsgHdlr.scala

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
Backport https://github.com/bigbluebutton/bigbluebutton/pull/19618 to BBB 2.7
=> feat: Record raiseHand, away and Reaction events (backport)

bigbluebutton-html5/imports/ui/components/poll/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Improves the layout of poll result annotations.
Closes none
=> feat(poll annotations): better annotation layout

bigbluebutton-html5/private/config/settings.yml
Restores askForConfirmationOnLeave default value on settings.yml file
=> restore askForConfirmationOnLeave default value

bbb-common-web/build.sbt, bigbluebutton-web/build.gradle
Porting https://github.com/bigbluebutton/bigbluebutton/pull/19660 to BBB 3.0+
=> fix(sec): bump postgresql to 42.7.2 (port)

record-and-playback/core/scripts/utils/gen_webvtt
=> recording: work around invalid locale in caption events (port)

bbb-libreoffice/assets/convert-cool.sh, bbb-libreoffice/install-local.sh, bbb-libreoffice/install-remote.sh, build/packages-template/bbb-libreoffice-docker/after-install.sh, build/packages-template/bbb-libreoffice-docker/build.sh
Backport of #18783 from `develop` branch
=> feat(presentation): Add Script for Using Collabora Online as Document Converter (backport)

bbb-export-annotations/workers/process.js
=> fix(bbb-export-annotations): handle missing textbox size in Tldraw (port) 

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx, docs/docs/data/join.tsx
1. Uses data from the `/enter` api endpoint to set the default user layout on join.
2. Updates docs for the `defaultLayout` join parameter with a slightly better description.
Closes #19571
Possible values for `defaultLayout` are: `CUSTOM_LAYOUT`, `SMART_LAYOUT`, `PRESENTATION_FOCUS` or `VIDEO_FOCUS`. If none is provided, the meeting layout will be used:
https://github.com/bigbluebutton/bigbluebutton/blob/04714848cf59c2910fe108cff883cbc837d354a7/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L397
https://github.com/bigbluebutton/bigbluebutton/blob/04714848cf59c2910fe108cff883cbc837d354a7/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L400
=> fix(layout): `defaultLayout` join parameter

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Fix mute external video on echo test.
Closes #19246
=> fix: External video - Video sound is not muted when connecting microphone (echo test)

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/services.ts
Restores user away on chat export
Closes #19168
=> fix: user away message on chat export

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/button/component.tsx
Changes condition for displaying audio captions button.
Closes #19607
=> fix: Captions controls duplicated

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js
fix download presentation popup link not updating
Closes #19180
=> fix: Download presentation popup window is broken

docs/docs/administration/install.md
* Update old links. Keeping old links to repositories [can be dangerous](https://socradar.io/danger-lurking-in-github-repositories/).
* Delete old and not currently maintained Ansible repositories
Keeping the documentation safety and up to date
=> Update Links In install.md Doc

docs/docs/administration/install.md
Backport #18295 to BBB 2.7 docs
=> docs: drop old links #18295 from wilkis3/wilkis3-doc-admin-install-links (backport)

docs/docs/administration/customize.md
=> docs: Update FreeSWITCH configs - Nine digits PIN

bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx
Use cdn url for layouts' resources.
Closes #none
@trinhhuutam submitted this simple fix (#17352) almost a year ago but was not in a position to sign a CLA.
> Can you help to find a way for this fix code can be merged into BBB without my legal / copyright paper work????
This pull request is meant to include the fix. Thank you @trinhhuutam for reporting the issue and pointing to the fix.
=> fix(bbb-html5): Use CDN for resource of layouts

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/audiocaptions/AudioCaptionsApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/audiocaptions/TranscriptionProviderErrorMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/AudioCaptionsMsgs.scala, bbb-transcription-controller.placeholder.sh, bigbluebutton-html5/imports/api/audio-captions/server/eventHandlers.js, bigbluebutton-html5/imports/api/audio-captions/server/handlers/transcriptionProviderError.js, bigbluebutton-html5/imports/ui/components/audio/captions/service.js, bigbluebutton-html5/imports/ui/components/audio/captions/speech/service.js, bigbluebutton-html5/imports/ui/components/captions/component.jsx, bigbluebutton-html5/private/config/settings.yml
- minUtteranceLength is now 1 second by default
- Fixed bug in the rendering code that made captions jump around and render less smoothly
- captions.dictation: false now hides the dictation button in the captions page
- Problems with the gladia key will be returned by the server and printed on the console
- audioCaptions.language.locale: auto together with audioCaptions.language.defaultSetLocale: true can be used to set 'Auto Detect' as the default value for transcription
Depends on newer bbb-transcription-controller version: https://github.com/bigbluebutton/bbb-transcription-controller/releases/tag/v0.2.2
=> fix: Several Gladia transcription fixes

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
Disables the processing of `TranscriptUpdatedEvtMsg` message which means no longer generating `TranscriptUpdatedEvent` recording event.
Closes # none
Related: https://github.com/bigbluebutton/bigbluebutton/issues/19701
https://github.com/bigbluebutton/bigbluebutton/issues/19701
=> !fix(captions): disable recording event TranscriptUpdatedEvent

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
Fix userlist labels appearing as `[object Object]`
=> fix: userlist labels

bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
Prevent `UpdateConnectionRtt` mutation from running several times at startup.
=> fix(connection status): prevent mutation from running several times

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/pin-area/component.jsx
Fix unpin button on top of webcam not working as expected.
=> fix: unpin video button

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
This pull request enhances user experience by implementing translations for the answers that users receive as poll answers in chat. 
PS: The language in the SS is Brazilian Portuguese - and the question is a "Yes, no or Abstention" question.
=> Fix: Polls answers in chat have no translation

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/service.ts
Improves chat link regular expression:
=> improve chat link regex

docs/docs/administration/customize.md
Added docs for how to update/replace localizations on a server.
Closes #none
It's a common use case.
=> docs: Instructions for how to update localization file de.json

build/packages-template/bbb-export-annotations/opts-jammy.sh
=> build(export-annotations): Add dependency poppler-utils (port)

docs/docs/administration/install.md
=> docs: Update Links In install.md Doc (port)

docs/docs/administration/customize.md
=> docs: Update FreeSWITCH configs - Nine digits PIN (port)

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
=> !fix(captions): disable recording event TranscriptUpdatedEvent (port)

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala, akka-bbb-apps/src/universal/conf/application.conf, docs/docs/development/api.md, docs/docs/new-features.md
=> feat(config): add checkSumAlgorithmForBreakouts in akka-apps (port) #19754

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
=> fix: Avoid presentation conversion causing a crash (port)

bigbluebutton-web/gradle.properties
Update tomcat to 9.0.86
Closes #
https://www.cve.org/CVERecord?id=CVE-2024-24549
=> fix(sec): Bump tomcatEmbed to 9.0.86

bigbluebutton-web/build.gradle
Update org.json:json
Closes #
https://www.cve.org/CVERecord?id=CVE-2023-5072
=> fix(sec): Update org.json:json

akka-bbb-apps/project/Dependencies.scala, akka-bbb-fsesl/project/Dependencies.scala, bbb-fsesl-client/project/Dependencies.scala
Bump logback to 1.2.13 for akka- projects
Closes #
=> fix(sec): Bump logback to 1.2.13 for akka- projects

docs/docs/administration/turn-server.md
=> docs: bash script reads /etc/turnserver.conf to get realm and secret (port)

build/packages-template/bbb-html5/after-install.sh
Generate index file of locales at build time
=> fix: generate locales index.json

bigbluebutton-html5/imports/ui/components/raisehand-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/raisehand-notifier/container.jsx, bigbluebutton-html5/imports/ui/components/raisehand-notifier/queries.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
- makes raise hand notification use data from graphQL
- updates apollo client to the latest version
=> refactor: Raise hand notification using graphql

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/component.tsx
Changes condition for playing chat audio alerts.
Closes #19865
=> fix(chat): audio alert playing incorrectly

bbb-export-annotations/config/settings.json, bbb-export-annotations/master.js, bbb-export-annotations/workers/collector.js, bbb-export-annotations/workers/notifier.js, bbb-export-annotations/workers/process.js
Porting #19779 's work from @ben-ba and @danielpetri1 to BBB 3.0
=> fix(bbb-export-annotations): Flag to force CairoSVG to embed images and improved redis socket configs

build/packages-template/bbb-html5/bbb-html5-meteor-assets-cache.conf, build/packages-template/bbb-html5/bbb-html5.nginx, build/packages-template/bbb-html5/build.sh
New approach to run HTML5 client when Meteor service is not active
https://github.com/bigbluebutton/bigbluebutton/pull/19938#issuecomment-2030991668
https://github.com/bigbluebutton/bigbluebutton/pull/19869
=> refactor: add meteor assets cache to build script

bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Fix a issue where the layout isn't propagated
=> Fix: layout not propagating

bigbluebutton-html5/imports/ui/components/connection-manager/startup-data-fetch/component.tsx
in some edge cases the value of the endpoint returns undefined.
=> Fix: failed settings fetch

bbb-graphql-middleware/internal/common/ActivitiesOverview.go, bbb-graphql-middleware/internal/hascli/client.go, bigbluebutton-html5/imports/ui/core/hooks/useMeeting.ts
=> refactor (graphql-middleware): Fix wrong logs in activities overview

bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx, bigbluebutton-html5/imports/ui/components/connection-status/service.js
Restores the `session logs` tabs in the connection status modal.
See https://github.com/bigbluebutton/bigbluebutton/pull/19949#issuecomment-2035656379.
=> fix(connection status): restore session logs tab

bigbluebutton-html5/imports/ui/components/polling/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx
=> fix(poll): avoid rendering polling component twice

bigbluebutton-html5/run-dev.sh
Following the integration of [PR #19942](https://github.com/bigbluebutton/bigbluebutton/pull/19942) into BigBlueButton, developers have observed that code changes are not being reflected in the development environment. This behavior is attributed to the persistent caching of assets by Nginx, hindering the immediate application of updates to HTML5 components.
This Pull Request addresses the issue by incorporating a periodic cleanup routine for the Nginx cache directory (/tmp/meteor-assets-nginx-cache/) within the run-dev script. By doing so, it ensures that any modifications made to the HTML5 codebase are promptly visible upon the next page reload, thereby significantly improving the development workflow.
Key Highlights:
- Introduces a background cache cleanup process that runs in parallel …
=> fix(bbb-html5): fixes the code reload in development

bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/service.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
Get user names from graphql instead of Users collection
=> fix: save user names feature

bigbluebutton-tests/playwright/polling/poll.js, bigbluebutton-tests/playwright/polling/polling.spec.js, bigbluebutton-tests/playwright/polling/util.js
Adds a joinParameter to avoid presentation notifications on the polling tests.
=> test: Avoid presentation notifications on polling tests

bigbluebutton-html5/imports/ui/components/raisehand-notifier/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/service.ts
Prevents errors when a user is removed from the meeting
=> fix: ejected user errors

bigbluebutton-html5/imports/ui/services/settings/index.js
Fixes client settings not persisting on page reloads.
=> fix: client settings not persisting

bigbluebutton-html5/imports/ui/components/video-provider/service.js
fix render loop on grid mode when camera pagination is active
=> fix: grid mode loop when pagination is active

bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js
- [fix(audio): acquire streams before negotiation when peer is answerer](https://github.com/bigbluebutton/bigbluebutton/commit/555a8f652209bc936a435867f0a6b70c72b7e3d8) 
- When a sendrecv peer acts as the answerer, gUM is only called _after_
the remote offer is received. This is fine, but the error handling runs
different in that scenario in a way that eventual gUM errors are treated
as negotiation errors, leading to inconsistencies when surfacing the
error to end users.
- If a peer is acting as answerer and is a transceiver, acquire the local
streams _before_ actual negotiation so that gUM errors are surfaced
correctly (and we spare uneeded negotiation steps).
None
=> [2.7] fix(audio): acquire streams before negotiation when peer is answerer

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationDAO.scala, bigbluebutton-html5/imports/ui/components/whiteboard/queries.ts
- Fix a problem where it was updating all annotations instead of only the modified ones
- Increase batchSize to make sure client will receive all updates at once
=> fix (graphql-server): Update only modified annotations

bbb-playback.placeholder.sh
Bump bbb-playback to 5.1.0 which contains support for tldraw v2 by @danielpetri1 (and other updates)
Closes #none
Support for tldraw v2-alpha.18
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.1.0
=> build: Bump bbb-playback.placeholder.sh to 5.1.0 (tldraw v2 alpha.18)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Restores maxNumberOfAnnotations check when adding a shape to the whiteboard
=> fix: restore max annotations limit

bigbluebutton-web/build.gradle
=> fix(sec): Bump org.json:json (backport)

bigbluebutton-web/gradle.properties
=> fix(sec): Bump tomcatEmbed to 9.0.86 (#19814) (backport)

akka-bbb-apps/project/Dependencies.scala, akka-bbb-fsesl/project/Dependencies.scala, bbb-fsesl-client/project/Dependencies.scala
=> fix(sec): Bump logback-classic (backport)

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/utils.js
Similar to #20018, restores shape type validation when adding a shape to the whiteboard.
=> fix: restore shape type validation

bigbluebutton-html5/imports/api/video-streams/server/handlers/webcamSync.js
fix for the following error in webcam sync handler:
=> fix: not a function error

bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/presentation/presentation.js, bigbluebutton-tests/playwright/screenshare/screenshare.js, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js, bigbluebutton-tests/playwright/screenshare/util.js
Adds the test to check if the external video stops when the screenshare starts.
=> test: Screenshare should stop external video

bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
=> Refactor: remove unused subscriptions

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/service.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
This PR adds data nedded for code highlighter plugin to work and some markup changes.
=> Data: Data needed for plugins

bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/service.ts
Removes unused code that was restored by a merge
=> fix: remove unused code

bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/meeting/from-core/hook-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/meeting/from-core/utils.ts, bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/manager.tsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Gives support for useMeeting from the plugin SDK
closely related to https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/81
=> feat(plugin): Support useMeeting hook for plugin

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/settings.yml
=> fix(bbb-html5): customHeartbeat would not close stale sessions (port)

bigbluebutton-html5/imports/api/user-reaction/server/methods/setUserReaction.js
Fix emoji not being filtered on send method
=> Fix: user reaction not showing right emoji

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
Fix throttled function that is triggered when a user starts typing in the chat
=> fix: throttle in user typing mutation

docs/docs/administration/cluster-proxy.md
Fix documentation errors discovered by @pielonet.  Add instructions for caching html5client assets on the proxies to reduce load on BBB servers if many clients join at once.
none.
=> Docs: fix cluster setup instructions

bbb-export-annotations/package-lock.json, bbb-learning-dashboard/package-lock.json, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Run `npm audit` and `npm audit fix` to update npm dependencies.
Closes # none
Making sure all npm dependencies are up to date
=> chore: bump npm deps

bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-polls/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-polls/container.jsx
Fix missing props warnings in the client
=> fix: client warnings

bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx, bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/queries.ts, bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/service.ts, bigbluebutton-html5/imports/ui/components/user-list/component.jsx
Fix custom logo feature (pass `logo=<image-url>` parameter when creating a meeting)
This feature looks like a good candidate for a test @gabriellpr @antonbsa
=> fix: custom logo

bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/hooks/index.ts
Fixes crash when enabling/disabling video pagination.
Closes #20192
=> fix(webcam): conditional hook call

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
The mininum limit for userlist is 50, it was being stated with zero, what caused a call to server asking for zero data, what i made was set the valu of limit to 50, so at first try it goes with the right value to server
=> Fix: userlist going with zeroed values to server

bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
Fixes locale setting not persisting after page refresh.
Settings -> Application Language -> Change it -> Refresh the page -> See the page in the previous language.
None
=> fix: locale setting not persisting

docs/docusaurus.config.js
Can't build the docs on 2.7 right now due to https://github.com/bigbluebutton/bigbluebutton/pull/20206
Closes #
=> docs: drop plugin @cmfcmf/docusaurus-search-local

docs/docusaurus.config.js
Same as https://github.com/bigbluebutton/bigbluebutton/pull/20226 but for 2.6
=> docs: drop plugin @cmfcmf/docusaurus-search-local [2.6]

docs/docs/administration/install.md
It seems that the kernel version of Ubuntu 22 LTS turned 6.2.0 on August 2023.
=> [3.0a] update doc for installation

docs/docs/administration/customize.md
Adds some warnings regarding the default.pdf. 
Closes #18082
=> [doc] avoid confusion of default presentation

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR fixes  the reported zoom edge cases affecting the presenter and attendees.
Closes #20211
=> fix(whiteboard): Tldraw Camera Edge Cases For Users

docs/docs/new-features.md
Added yq upgrade in the 3.0 docs
Closes #none
yq changed syntax. People should be aware.
=> docs: Added yq upgrade in the 3.0 docs

bbb-graphql-server/bbb_schema.sql
=> fix (graphql-server): Reactions not expiring

bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Adds talking info to current user subscription
Closes #20260
=> fix: The mute button is not pulsing while talking

bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx
Terminate connection when a error is handled in the client
=> Add: terminate connection on client error

build/packages-template/bbb-record-core/bbb-record-core.logrotate, build/packages-template/bbb-webrtc-sfu/bbb-webrtc-sfu.logrotate
Backports #20249 to BBB 3.0
Thank you @GhaziTriki
=> build: Update logrotate rule to add date extension to archived logs files.

docs/docs/accessibility.md, docs/docs/administration/configure-firewall.md, docs/docs/administration/install.md, docs/docs/administration/nextcloud.md, docs/docs/testing/release-testing.md
Porting #19776 to BBB 3.0
Thanks @stweil !
=> docs: Fix some typos (found by typos)

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/hooks.ts, bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/hooks/index.ts, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Properly drops both audio and video when joining breakout rooms through breakout confirmation modal.
Closes #20265
=> fix: drop audio and video when joining breakout room

bigbluebutton-html5/deploy_to_usr_share.sh
Creates index.json which was missing when deploying
Closes #none
Related: #19881 
Could not load the client after a deploy due to this file missing
=> fix: create locale index.json in deploy_to_usr_share.sh

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Fixes:
- stops/restarts audio captions when the user becomes muted/unmuted
- adds debug level logs
=> fix(captions): Fixed captions mute/unmute, adding some debug logs

bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
Adds missing parameter in Settings.save called in intlAdapter component.
=> fix: add missing parameter in Settings.save - intl adapter

bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/styles.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/user-status/component.tsx, bigbluebutton-html5/public/locales/en.json
Includes webcam control refinements and fixes.
The fixes are:
- Webcam menu not being shown when it's in fullscreen.
- A crash due to icons being rendered as text nodes.
Closes #20356
=> improvement/fix(webcam): refine webcam controls

bigbluebutton-html5/imports/ui/components/app/component.jsx
=> fix(audio): conditions for muting the user on leave

docs/docs/data/create.tsx
Updates the docs with the correct default value for whether breakouts are recorded.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/18419
=> docs: adjust correct default value for breakouts being recorded

bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/ContentTypeValidator.java
=> fix(API): Allow additional parameters in content type headers 3.0

bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/ContentTypeValidator.java
=> fix(API): Allow additional parameters in content type headers 2.6

bigbluebutton-html5/imports/ui/components/app/component.jsx
Fix incorrect chat id value being set when layout is changed
=> fix: incorrect chat id being set on layout change

bigbluebutton-tests/playwright/sharednotes/sharednotes.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
Updates and enables `Pin and unpin notes onto whiteboard` test on CI
=> test: Pin and unpin notes onto whiteboard on CI

bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Removes unused fields from userCurrentSubscription
=> Refactor: remove unused fields from current user subscription

bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.14.0-beta.2](https://github.com/bigbluebutton/bigbluebutton/commit/e275b8c74e0a92cd31f86b23cfb321c35abc9dee)
None
- feat(freeswitch): overridable UA string
- feat(audio): muteOnStart detection for conditional dialplans
- feat(audio): mute passive-sendrecv clients on start
=> build(bbb-webrtc-sfu): v2.14.0-beta.2

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR updates the presentation dropdown menu option icon to address the duplication of icons within the same group.
Closes #20409
=> fix(whiteboard): Update presentation dropdown menu icon

bigbluebutton-html5/run-dev.sh, build/packages-template/bbb-html5/after-install.sh
Since https://github.com/bigbluebutton/bigbluebutton/pull/20336 it is not longer necessary!
=> refactor: Remove meteor-assets cleanup routine

bbb-graphql-server/install-hasura.sh, build/packages-template/bbb-graphql-server/build.sh
More details at: https://github.com/hasura/graphql-engine/releases/tag/v2.40.0
=> build (graphql-server): Upgrade Hasura to version v2.40.0

record-and-playback/video/scripts/process/video.rb, record-and-playback/video/scripts/publish/video.rb
Adds information for number of participants, raw size, and playback size to recording video format metadata.
Closes #20307
=> fix(recording): Add participants, raw size, and playback size information to video metadata

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/page/component.tsx
It fixes the useLoadedUserlist data-consumption hook.
=> fix(html5): useLoadedUserlist plugin data-consumption hook

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/raise-hand/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/container.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/guest-policy/container.jsx
Remove with trackers from components that stoped to use Meteor
=> refactor: Remove withtrackers

bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
Fixes the `overrideLocale` config not working.
None
=> fix(intl): `overrideLocale` config

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
Removes `withTracker` from `NavbarContainer`.
=> refactor: remove navbar withTracker

bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/parameters/constants.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js
- `Multi Users Pen Only`;
- `Presenter Tools`;
- `Multi Users Tools`;
https://github.com/bigbluebutton/bigbluebutton/issues/19961#issuecomment-2038138364
=> test: Fix and enable whiteboard parameter tests on CI

bbb-playback.placeholder.sh
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.1.1
=> build: Bump bbb-playback to 5.1.1

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SetUserSpeechLocaleMsgHdlr.scala, bbb-graphql-server/bbb_schema.sql, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/captions/component.tsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx
It fixes subscription of captions due to undefined captionLocale.
See demo down below:
https://github.com/bigbluebutton/bigbluebutton/assets/69865537/09d74984-f3f2-4e4e-8197-d516dc70957f
=> fix(html5): caption subscription error

docs/docs/data/create.tsx
=> [3.0] docs: adjust correct default value for breakouts being recorded

docs/docs/data/create.tsx, docs/docs/development/api.md, docs/docs/new-features.md
=> docs: document allowPromoteGuestToModerator [3.0]

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx
fix invalid hook call in audio captions component
=> fix: invalid hook call error when audio captions are active

bbb-webrtc-sfu.placeholder.sh
v2.14.0-beta.3
---
* feat(audio): support for mute-and-hold on start
* fix(audio): mute/unmute stuck due to inconsistent hold status
=> build(bbb-webrtc-sfu): v2.14.0-beta.3

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/container.jsx
fix whiteboard writers subscription missing parameter
=> fix: whiteboard subscription parameters

bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR fixes a bug where focus is not properly shifting to the chat input while editing shapes on the whiteboard.
Closes #19886
=> fix(whiteboard): Focus not moving to chat while editing shape

docs/docs/data/create.tsx, docs/docs/development/api.md
Backport https://github.com/bigbluebutton/bigbluebutton/pull/20499 to BBB 2.7
=> docs: document allowPromoteGuestToModerator [2.7]

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/service.ts
Adds debounce and throttle to mute/unmute button to prevent users from spamming this actions.
Depends on this [fix](https://github.com/bigbluebutton/bigbluebutton/pull/20510) to wok properly.
Closes #20484
=> fix(audio-controls): add debounce/throttle to mute/unmute

bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the external video skipping
=> Fix: External video skipping

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPageCursorDAO.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPageWritersDAO.scala, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/whiteboard/hooks.ts, bigbluebutton-html5/imports/ui/components/whiteboard/queries.ts
- When multi-whiteboard is disabled, remove all unused cursors from the database
- Always filter for `isCurrentPage` or `pageId` when getting cursors/writers
=> refactor: Improvements related to whiteboard cursors/writers

bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/service.ts
Adjusts custom logo url value being set without the correct prefix
Closes #20526
=> fix: userdata-bbb_display_branding_area parameter not working

bigbluebutton-html5/imports/ui/services/storage/observable.ts
Removes parsing error logging from the storage singleton.
None
It's not a useful log.
=> fix: remove storage parsing error logging

docs/docs/development/api.md
Adjusts the data input to be `sendChatMessageEndpointTableData` in #20323 
Closes #
Could not build the docs.
=> docs: Fix broken api.md building

docs/docs/development/api.md
In https://github.com/bigbluebutton/bigbluebutton/pull/20514 I mistakenly listed this new parameter as a join one. It's a create parameter. The 3.0+ docs is fine.
Closes #none
=> docs: Clarify that allowPromoteGuestToModerator is a CREATE parameter

docs/docs/administration/customize.md, docs/docs/new-features.md
Adds docs for Gladia captions support on BBB 3.0
- copied from 2.7, adapted the commands
Closes #none
The docs were not copied earlier since Gladia support was not ported yet.
=> docs: 3.0 Added Gladia docs (how to configure)

bigbluebutton-html5/imports/ui/components/notes/component.tsx
This PR fixes the UI bug where a white rectangle would appear in gird layout when the notes were pinned.
#20488
=> Fix:[3.0] White bar shows up when public chat is closed

bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_voice_activity.yaml
=> fix (gql-server): Fix wrong filter in `user_voice_activity_stream`

bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx, bigbluebutton-html5/imports/ui/core/graphql/apolloContextHolder/apolloContextHolder.ts, bigbluebutton-html5/imports/ui/core/singletons/subscriptionStore.ts
Fix: cache notification when subscription data changes.
Fix: connection not being closed when user left the meeting
=> Fix: cache notification and connection close

bigbluebutton-tests/playwright/parameters/parameters.spec.js
Adds the branding area parameter test on ci.
=> test: add branding parameter test on ci

bigbluebutton-html5/imports/ui/components/generic-content/generic-sidekick-content/container.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/channel-manager/reader-manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/manager.tsx
Fix data-channel updates when subscribing and fix a generic content case when it updates the sidekick area fast enough so that the previous one didn't vanish.
=> fix: fix data-channel and generic-content

bigbluebutton-html5/imports/ui/components/connection-manager/startup-data-fetch/component.tsx
Removes Meteor's `Session` global object usage introduced in https://github.com/bigbluebutton/bigbluebutton/pull/20439.
=> refactor: remove Session usage

bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
=> fix: `userdata-bbb_override_default_locale` param

bigbluebutton-html5/imports/ui/components/video-provider/hooks/index.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.tsx
Fixes the webcam button flickering on webcam join.
See the button become active, inactive, and then active again:
[Screencast from 20-06-2024 11:48:56.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/7d07a735-d394-4fac-bc13-ce6eb21b39f0)
[Screencast from 20-06-2024 11:46:44.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/a45a3b53-731f-46fd-bc6f-7e05796d750d)
None
=> fix(webcam): webcam button flickering on join

docs/docs/new-features.md, docs/docs/plugins.md, docs/docusaurus.config.js, docs/package-lock.json
Introduces a first cut of the Plugins page in the docs.
Closes #none
We have plenty to say about plugins and are also in need of a suitable spot to list them all.
=> docs: First cut of a Plugins page (unlisted for the moment)

docs/docs/administration/customize.md
Tweak gladia documentation with improved yq commands
Closes #none
The old commands did not work for me when not using `root`
=> docs: Tweak gladia documentation with improved yq commands

bigbluebutton-html5/imports/startup/client/intlAdapter.tsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Some style polishing for the whiteboard toolbar.
Dark:
Light:
Closes #20523
=> style(whiteboard): polishing toolbar styles

bigbluebutton-html5/imports/ui/components/whiteboard/queries.ts
- removes unused fields from whiteboard cursor subscription
- adds order by clause so results always come in the same order
=> refactor: remove unused data in cursor subscription

.github/PULL_REQUEST_TEMPLATE.md
Since I've been assigned as a reviewer/tester in many PRs, I usually face cases in which I need to contact who's contributing to understand exactly what to test and the specific configurations for the upcoming changes/fixes. This PR adds a new topic to the template, facilitating the reviewing process
=> chore: Update PR template with 'how to test'

build/packages-template/bbb-webrtc-sfu/after-install.sh
Cleans up the after-install.sh script for bbb-webrtc-sfu
Closes #none
I had commented out a bunch of code when we were trying to install without Kurento on Ubuntu 22.04 and forgot to tidy up.
CI passing suffices - it means the build of the package succeeded and media tests ran fine.
=> build: Clean up sfu after-install

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/ParticipantJoinRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/UserJoinedMeetingEvtMsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
=> feat(events): Add user custom data to events.xml 3.0

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/captions/component.tsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/live/component.tsx
This PR re-enforces the number of lines that were set to the CC.
#20542 
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/7128c302-f686-49f5-846b-8abdf364fa61
=> Fix: Captions lines are duplicated; limit how many rows

bbb-graphql-middleware/internal/akka_apps/client.go, bbb-graphql-middleware/internal/bbb_web/client.go, bbb-graphql-middleware/internal/hasura/conn/writer/writer.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/writer/writer.go, bbb-graphql-middleware/run-dev.sh
Include some validation to the result of `/checkAuthorization` request and in some cases try to authentication again in order to reduce reconnections!
=> refactor (gql-middleware): Improve validation on checking user authorization

bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/button/container.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
Fix for the following alerts in sonarcloud:
- This function expects no arguments, but 1 was provided.
- Do not use "Error" to declare a variable
- Do not use "Array" to declare a parameter
- React component names must start with an uppercase letter.
Components with changed lines should still work the same after this PR, as it aims on only applying good practices and not changing any behavior.
=> refactor: fix sonarcloud alerts

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/DatabaseConnection.scala
Following #20594.
It is necessary to handle `break()` and it was missing!
=> fix (akka-apps): Avoid error on exec more than 500 inserts

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR addresses an issue where presentations in portrait orientation were not properly synced between the viewer's screen and the presenter's screen. 
Closes #20601
=> fix(whiteboard): Handle viewer's portrait oriented presentations

bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
Adds margin between icon and label of recording button.
Before
After
=> style: recording button label margin

bigbluebutton-html5/imports/ui/components/connection-status/component.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx, bigbluebutton-html5/imports/ui/core/utils/getBaseUrl.ts
New function returns the base url for bbb, based in the settings `public.app.bbbWebBase`.
=> Add: base url util for api

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR improves the transition when switching slides. Previously, when switching slides, there was a noticeable animation of the slide scaling to fit the available area. Now, the transition is smoother, and there is no visible scaling.
This change eliminates the visible delay observed when switching slides and prevents the slides from scaling down to position, providing a more seamless and fluid user experience.
=> fix(whiteboard): Handle preloading next slide camera position

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
This PR fixes the calculation for valid user for breakout rooms.
#19870 
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/95b4b668-bda2-40c9-8ad3-19e039f3bb1e
=> Fix: Breakouts calculation for valid users incorrect

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/MakePresentationDownloadReqMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
- Fixes duplicated toasts.
- Fixes some items not showing up on the toast.
Closes #20611
=> fix: inconsistencies in presentation upload toast

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/styles.ts
Port https://github.com/bigbluebutton/bigbluebutton/pull/20669 to 3.0
=> fix: external video can be seen through sidebar on mobile

bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/breakout/breakout.spec.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/connectionStatus/connectionStatus.spec.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/layouts/layouts.spec.js, bigbluebutton-tests/playwright/learningdashboard/learningdashboard.spec.js, bigbluebutton-tests/playwright/notifications/notifications.spec.js, bigbluebutton-tests/playwright/options/options.spec.js, bigbluebutton-tests/playwright/package-lock.json, bigbluebutton-tests/playwright/package.json, bigbluebutton-tests/playwright/parameters/parameters.spec.js, bigbluebutton-tests/playwright/playwright.config.js, bigbluebutton-tests/playwright/polling/polling.spec.js, bigbluebutton-tests/playwright/presentation/presentation.spec.js, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js, bigbluebutton-tests/playwright/user/multiusers.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/webcam/webcam.spec.js, bigbluebutton-tests/playwright/whiteboard/whiteboard.spec.js
- Updates playwright + other dependencies;
- Changes the way to tag tests;
This can avoid some unexpected CI failures we've been facing recently. Also, it's been a while since the last update.
- `--last-failed` flag when running tests to re-run only the previous failed ones;
=> test: Update dependencies + change test tagging approach

bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx, bigbluebutton-html5/imports/ui/components/settings-loader/component.tsx
As some steps were removed/ refactored, this PR updates the visual representation of them.
=> Fix: Loading steps not being accurately represented

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetPageInfiniteWhiteboardPubMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/services/features/index.js
Adds option in `disabledFeatures` for infinite whiteboard.
Closes #20651
=> feat(whiteboard): add option to `disabledFeatures` for infinite whiteboard

build/packages-template/bbb-playback/build.sh
Follow up from https://github.com/bigbluebutton/bigbluebutton/pull/20607
Looks like I caused before my change the build directory was (somehow) not copied over, only its contents. The result is that playback files are not where they are expected but inside an additional directory.
Closes # none
Copying the playback files where they are meant to be copied.
`ls -l /var/bigbluebutton/playback/presentation/2.3/`
Expected:
```
bigbluebutton@anton-droplet-8135:~/bigbluebutton/build$ ls -l /var/bigbluebutton/playback/presentation/2.3/
total 36
-rw-r--r-- 1 bigbluebutton bigbluebutton 5253 Jul 16 01:28 asset-manifest.json
-rw-r--r-- 1 bigbluebutton bigbluebutton    6 Jul 16 01:28 bbb-playback-version
-rw-r--r-- 1 bigbluebutton bigbluebutton 1150 Jul 16 01:28 favicon.ico
-rw-r--r-- 1 bigbluebutton …
```
=> build: bbb-playback copy files properly

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/button/container.jsx, bigbluebutton-html5/imports/ui/components/connection-status/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/adapter.tsx, bigbluebutton-html5/imports/ui/components/video-provider/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/container.tsx, bigbluebutton-html5/imports/ui/components/video-provider/enums.ts, bigbluebutton-html5/imports/ui/components/video-provider/hooks/index.ts, bigbluebutton-html5/imports/ui/components/video-provider/service.ts, bigbluebutton-html5/imports/ui/components/video-provider/state.ts, bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.ts, bigbluebutton-html5/imports/ui/components/video-provider/types.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/pin-area/component.tsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/webcam/component.tsx, bigbluebutton-html5/imports/ui/services/storage/observable.ts
This PR includes a couple of fixes along with performance improvements.
The Join Webcam button will now be disabled when the client is disconnected.
The grid will be properly padded by grid items.
**Page 1:**
**Page 2:**
- Remove the need to pass in configuration values as arguments to the hooks (Meteor residue).
- Use enum to store video item types (`grid`, `stream`, `connecting`).
- Remove useless `useEffect`.
- Improve code quality in general.
- Fix pagination arrows appearing on moderators.
None, as far as I know.
1. Join several users (15 or more).
2. Start webcams in all of them.
3. Try out webcam pagination.
=> fix(webcam): a couple of pagination fixes, improvements, et al.

bbb-common-web/src/main/java/org/bigbluebutton/presentation/MimeTypeUtils.java, bigbluebutton-html5/private/config/settings.yml, docs/docs/development/api.md
See screenshots of docs ahead:
This actually closes #20346
=> feat(html5; docs; common-web): increase readability and information for docs

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR removes active cursors for users whose access has been revoked, whether due to disabling multi-user mode or individual access revocation.
Closes #20726
=> fix(whiteboard): Remove active cursors in tldraw when access is revoked

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Pulls in the latest bbb/tldraw https://github.com/bigbluebutton/tldraw/releases/tag/v2.0.0-alpha.23
Closes # none
Resolves a browser console error about locales
The package `bbb-html5` should build and install fine. Whiteboard should work normally. No errors in the browser console after whiteboard loading.
=> chore: bump tldraw to alpha.23

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
=> fix: Graphql permission wrong for auto assigned presenter

bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx, bigbluebutton-html5/public/locales/en.json
This PR fixes the missing button with which the moderator could invite user to breakout rooms
=> Fix: [3.0] Breakout room invitation option missing from user dropdown

bigbluebutton-web/build.gradle
Updates `grails-plugin-databinding`
Closes #none
https://nvd.nist.gov/vuln/detail/CVE-2023-46131
The CI + checking the version after merge:
```
$ ls -l /usr/share/bbb-web/WEB-INF/lib/grails-plugin-databinding*          
-rw-r--r-- 1 bigbluebutton bigbluebutton 315826 Jul 24 16:11 /usr/share/bbb-web/WEB-INF/lib/grails-plugin-databinding-5.3.4.jar
```
=> chore(core): Update grails-plugin-databinding

bigbluebutton-web/gradle.properties
Upgrades bbb-web dependency `tomcatEmbedVersion`
Closes #none
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-7430175
The CI has enough coverage - building, installing, starting meetings, using api, uploading etc.
=> chore(core): upgrade embedded tomcat

bigbluebutton-html5/imports/api/bbb-web-api/index.ts, bigbluebutton-html5/imports/api/bbb-web-api/types.ts, bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx, bigbluebutton-html5/imports/ui/components/settings-loader/component.tsx
Centralizes `/bigbluebutton/api` requests in a singleton with the aim of centralizing requests to the bbb-web's API.
The data will be cached to the `sessionStorage` to avoid unnecessary requests, as the data returned by that endpoint is static.
None
The client is requesting `/bigbluebutton/api` several times.
=> refactor(html5): centralize `/bigbluebutton/api` requests

bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js
=> fix: Dial-In participants are not visible in the participants

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx
Fix chat alerts settings value
=> fix: chat alerts

docs/docs/data/join.tsx
Unifies the two distinct entries describing `webcamBackgroundURL`.
Closes #none
Thanks @SamuelWei for letting me know about this!
not needed
=> docs: remove extra entry for webcamBackgroundURL

docs/docs/development/api.md
Thanks @SamuelWei for reporting!
=> docs: fix name of errorRedirectUrl in api docs

docs/docs/development/api.md
=> [3.0]docs: adjust name for errorRedirectUrl

bigbluebutton-html5/private/config/settings.yml
Removes `instanceId` from `settings.yml`
Closes #none
Not used. Introduced in 3.0.
=> fix: Remove unnecessary instanceId property in settings.yml

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/20830.
Closes #20787
=> fix(presentation): presentation snapshot overflowing the slide [2.7]

.gitlab-ci.yml
Bump Go from 1.20 to 1.22.5 This is the version used for building packages (so bbb-webrtc-recorder, bbb-graphql-middleware, etc)
https://github.com/bigbluebutton/bbb-docker-build-packages/blob/v3.0.x-release/Dockerfile#L12
Closes #none
https://endoflife.date/go Go 1.20 support ended half a year ago.
CI should pass.
=> chore: build images with Go 1.22.5

bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/components/activity-check/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-test/container.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/service.ts, bigbluebutton-html5/imports/ui/components/notifications/service.ts, bigbluebutton-html5/imports/ui/components/polling/service.ts, bigbluebutton-html5/imports/ui/components/raisehand-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/imports/ui/services/virtual-background/service.js
Removes instanceId from html5 client
follow up from #20744
=> refactor: remove instanceId from client

bigbluebutton-tests/playwright/chat/chat.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/user/timer.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/user/util.js
- Split Timer test into separate tests for each feature (stopwatch and timer);
- Fixes/Updates steps on both and enables them on CI;
- Adds many assertions;
- Updates the assertions description to make them more clear about the actual performed action - and expected behavior;
=> test: Timer and stopwatch tests enhancements

bigbluebutton-html5/imports/ui/components/polling/styles.ts
Ports #20798 changes to `3.0`.
=> fix: Improve screen reader accessibility for polling modal

docs/package-lock.json
Fix security issues which were reported by Dependabot by running `npm audit fix`.
=> docs: npm audit updates

bigbluebutton-config/bin/bbb-conf
This fixes #18907 and uses the solution which was suggested in this issue.
Fixes: 3222d2b94bf359b5 ("fix(bbb-conf): Handle yq upgrade related issues")
It fixes an issue.
Closes #18907
I had this issue.
Install latest release 3 and run `bbb-conf --check`.
=> Fix `bbb-conf --check`

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/BreakoutRoom2x.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java, bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/breakout-room-user-assignment/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/types.ts, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/styles.ts, bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Ports breakout changes from 2.7 to 3.0 (#20734, #20764, #20769)
Closes #20824
=> Port breakouts enhancements from 2.7.10 to 3.0

bigbluebutton-config/bin/bbb-conf, build/opts-global.sh, build/packages-template/bbb-config/opts-jammy.sh, build/packages-template/bbb-html5/before-install.sh, docs/docs/new-features.md
Closes #
Since #20811 we no longer need it. It is also a version that was maintained by Meteor, after NodeJS v14 went EOL in April 2023
A working client + empty `/usr/lib/bbb-html5/node`
=> build: remove old custom bbb-html5 NodeJS binaries

bbb-graphql-actions/package.json, bigbluebutton-html5/deploy.sh, bigbluebutton-html5/run-dev.sh, bigbluebutton-html5/webpack.config.js, build/packages-template/bbb-html5/bbb-html5.nginx.dev, build/packages-template/bbb-html5/bbb-html5.nginx.static
- Add `run-dev.sh`
- Add `deploy.sh`
- Tweak Webpack and Nginx to run from source properly
TODO: Check how to provide `/html5client/locales` from source.
=> Add scripts to run html5 from source

bigbluebutton-html5/public/stylesheets/fonts.css
Adjusts fonts path in css to match new build
=> fix: fonts path

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/styles.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.ts, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/styles.ts
Adds doctype to new html main file and removes styles that are not needed anymore.
some additional styles (quirks mode) might be added by the browser if there's no DOCTYPE declaration in the first line of the html file. (https://developer.mozilla.org/en-US/docs/Glossary/Doctype)
=> fix: restores doctype declaration

bigbluebutton-html5/private/config/settings.yml
Include links to which languages are supported by the captions providers.
Closes # none
The links were handy in 2.7 but we did not port them.
Copied from https://github.com/bigbluebutton/bigbluebutton/pull/19987 but with updated Gladia link
=> chore: add list of supported languages for captions

docs/docs/administration/configure-firewall.md, docs/docs/administration/customize.md, docs/docs/administration/privacy.md, docs/docs/administration/turn-server.md, docs/docs/development/architecture.md, docs/docs/development/dev-guide.md, docs/docs/new-features.md, docs/docs/support/troubleshooting.md
- docs: remove leftover Kurento documentation
- 
Closes https://github.com/bigbluebutton/bigbluebutton/issues/20209
https://github.com/bigbluebutton/bigbluebutton/issues/20209
=> docs: remove leftover Kurento documentation

bigbluebutton-html5/public/stylesheets/bbb-icons.css
This PR fixes the visually broken autoplay button.
#20887
=> Fix: [3.0] Audio autoplay button is visually broken

bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
Fix feedback screen buttons actions and labels
1. set `askForFeedbackOnLogout: true` in settings file
2. join a meeting
3. leave meeting
4. try to use the "send feedback" feature
=> fix: feedback screen buttons

bigbluebutton-html5/imports/ui/components/connection-status/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/service.js
This PR removes rtt precision and fixes the error log when connecting in audio,  the error was being caused by I function that was being not mere useful for the client, theres other funcitons the monitors the audio health.
=> Fix: connection status issues

bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Restores presentation on annotation added.
Closes #20880
=> fix: `userdata-force_restore_presentation_on_new_events`

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR includes a new storage item to preserve the external video player volume between videos and refreshes in the client.
=> Add: store volume settings to preserve between player refresh

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/timer/component.jsx, bigbluebutton-html5/imports/ui/components/timer/indicator/component.jsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/user/timer.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/user/util.js
Adds the timer/stopwatch test to 2.7
=> test: Backporting timer/stopwatch test to 2.7

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR fixes the wheel zoom only working on the first page of the presentation.
=> fix(whiteboard): Wheel zoom not working on other pages

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/wake-lock/container.jsx
This PR fixes browser console errors.
=> Fix: Errors and warnings

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Fixes poll results not appearing in the snapshot of current slide.
Whiteboard:
Resulting snapshot now:
Resulting snapshot then:
n/a
=> fix(presentation): poll results not appearing in the snapshot of slide

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/styles.ts, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/styles.ts
This PR fixes the loading animation for buttons on mobile.
#20985
=> Fix: [3.0] Distorted microphone loading animation on smaller screens (mobile)

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.js, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.js
Added background blur filter to audio and video modal when a user enters the room, after that no blur filter is applied.
None
[Screencast from 26-08-2024 16:53:29.webm](https://github.com/user-attachments/assets/541a1f79-67a6-466e-b458-a18666b44d12)
=> feat(modal): added blur backdrop filter when user join the room

docs/docs/administration/configuration-files.md
Likely resulted from copy-pasting
before
=> docs: Remove OBJ characters from docs

bigbluebutton-web/build.gradle, bigbluebutton-web/gradle.properties
Ports #20767 and #20768 to BBB 3.0+
=> chore(core): upgrade embedded tomcat, grails-plugin-databinding

.gitlab-ci.yml
Use a newer image for building BBB packages.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/20961
https://github.com/bigbluebutton/bbb-docker-build-packages/pull/8
In a session mute/unmute self and observe the sounds. Compare to BBB 2.7
=> chore: use newer image for building packages

bbb-pads.placeholder.sh
Bump bbb-pads to 1.5.3
Closes # none
Some dependency updates.
https://github.com/bigbluebutton/bbb-pads/compare/v1.5.2...v1.5.3
=> chore: Bump bbb-pads to 1.5.3

freeswitch.placeholder.sh
Upgrades FreeSWITCH to the latest [open] version, containing ~7 months of patches/improvements.
Closes #none
https://github.com/signalwire/freeswitch/releases/tag/v1.10.12
Audio should work, closed captions with Gladia (via bbb-transcription-controller) shoud work.
@prlanzarin I tested locally and it seemed to work fine, no noticeable difference. Would you like to run any kind of additional testing etc? Or only when it's time to backport to BBB 2.7?
=> chore: upgrade FreeSWITCH to 1.10.12

docs/docs/testing/release-testing.md
Escaping a couple of characters which were breaking the docs builds.
Closes # none
Just the docs were not being built.
The docs build should proceed.
similar: https://github.com/bigbluebutton/bigbluebutton/pull/19279
=> docs: escape non mdx compliant characters

docs/docs/data/create.tsx
=> docs: fix name for notifyRecordingIsOn create parameter [2.7]

docs/docs/data/create.tsx
Fix incorrect reference to `remindRecordingIsOn` which should be `notifyRecordingIsOn`.
Closes # none
Thanks @pielonet for reporting this!
I will backport this to 2.7 docs too.
=> docs: fix name for notifyRecordingIsOn create parameter

docs/package-lock.json, docs/package.json
Reverts https://github.com/bigbluebutton/bigbluebutton/pull/20901
Closes #
Can't build the docs anymore on 'develop' after merging 'v3.0.x-release' into 'develop' with this commit in it.
Docs build goes past the stage Build all versions.
We'll need to revisit #20901 
error:
```
> bigbluebutton-docs@0.0.1 docusaurus
> npx docusaurus docs:version 3.0
/home/runner/work/bigbluebutton/bigbluebutton/docs/node_modules/@docusaurus/utils/lib/moduleUtils.js:36
throw new Error(logger_1.default.interpolate `Docusaurus could not load module at path path=${modulePath}\nCause: ${error.message}`, { cause: error });
^
Error: Docusaurus could not load module at path "/home/runner/work/bigbluebutton/bigbluebutton/docs/docusaurus.config.js"
Cause: Cannot find module '@cmfcmf/docusaurus-search-local'
Require …
```
=> docs: undo bump docusaurus preset classic Revert #20901

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/live/styles.ts
Fixes avatar username color in captions when dark mode is enabled. Similar to #20999.
None
=> fix(captions): fix avatar username color

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/activity-check/container.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/component.tsx, bigbluebutton-html5/imports/ui/components/layout/observer.tsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/hooks.ts, bigbluebutton-html5/imports/ui/components/layout/push-layout/mutations.ts, bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/service.ts, bigbluebutton-html5/imports/ui/components/webcam/component.tsx
This PR does lots of cleanup in the `AppContainer`, `AppComponent` and `Base` components.
Those components were becoming overloaded by component-specific code, for example, layout code. This PR aims to isolate things and move code into respective components.
- https://github.com/bigbluebutton/bigbluebutton/commit/25fe8b812539e75df86f072d21d8b42c86bf5202: Introduces a new component for grouping general layout updates, rendered by `AppComponent`.
- https://github.com/bigbluebutton/bigbluebutton/commit/393339d63dca4627e0b1d47c216e9e3caad358f7, https://github.com/bigbluebutton/bigbluebutton/commit/368f0dd935e73478d8582f5a5ae6d8a50b6cf6df, https://github.com/bigbluebutton/bigbluebutton/commit/c9e1a32d94dc7a9a8d8c4a101221368b0e961ed4: Moves _push layout code_ into `PushLayoutEngine`.
None, but …
=> refactor: App component cleanup

bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/channel-manager/manager.tsx, bigbluebutton-html5/imports/ui/components/plugins-engine/data-channel/manager.tsx
Just a useDataChannel fix and a quick refactor
=> fix: fix useDataChannel subscribe events

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Just an update of SDK to version 0.0.58. Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/21004
=> feat(plugins): update SDK to version 0.0.58

record-and-playback/core/lib/recordandplayback/edl/video.rb
I found a failed recording where a deskshare video file could not be decoded when seeking was used (oddly enough, it could decode without seeking). Turns out that remuxing the file was enough to make things work.
In the video processing code, after checking for other known video file problems that are fixed by remuxing, also try decoding one frame of the video with a seek time applied.
Since more videos can end up being remuxed now, I moved the output of the remux to a new subdirectory. Since more file types than just 'flv' can be remuxed, I switched the output to the 'nut' container instead. (This is ffmpeg's generic container format, and can hold any audio/video which ffmpeg can process, so it works well for temporary files.)
=> Recording: Do a test decode to detect video seek problems

docs/docs/development/dev-guide.md
Tweaking the path of the configs file for `sipjsHackViaWs` to not depend on a removed path.
Closes # none
Pointed out in https://groups.google.com/g/bigbluebutton-dev/c/KaTFzXj02cQ/m/YuzW_hBNAwAJ
=> docs: update instructions for enabling sipjsHackViaWs in dev env

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/notify/component.jsx
Logs whether the user chose to Continue or Leave when presented with the dialog on notifyRecordingIsOn
Closes #21134 
Assist administrator with better traceability
To test you need to add
`notifyRecordingIsOn=true`
in `/etc/bigbluebutton/bbb-web.properties` and restart BBB.
Sample of the log:
```
{
"logCode": "recording_started_notify_user_hit_continue",
"logDescription": "The user is reminded that recording commences. The user pressed Continue.",
"connectionId": "jyY7qEuAikyL88Ecm",
"extraInfo": {
"clientURL": "https://anton-droplet-4324.do.blindside-dev.com/html5client/join?sessionToken=jpnotrcinmshoc4j"
},
"userInfo": {
"sessionToken": "jpnotrcinmshoc4j",
"meetingId": "728d334a030f7296a9e0c10210a30e33b9343198-1726240150047",
"requesterUserId": "w_jxhw30nz8ezz",
"fullname": "User …
```
=> chore(client): Add logs for recording notify action

bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go, bbb-graphql-middleware/internal/akka_apps/client.go, bbb-graphql-middleware/internal/bbb_web/client.go, bbb-graphql-middleware/internal/common/types.go, bbb-graphql-middleware/internal/gql_actions/client.go, bbb-graphql-middleware/internal/hasura/client.go, bbb-graphql-middleware/internal/hasura/conn/reader/reader.go, bbb-graphql-middleware/internal/hasura/conn/writer/writer.go, bbb-graphql-middleware/internal/hasura/retransmiter/retransmiter.go, bbb-graphql-middleware/internal/websrv/connhandler.go, bbb-graphql-middleware/internal/websrv/reader/reader.go, bbb-graphql-middleware/internal/websrv/writer/writer.go, bbb-graphql-middleware/run-dev.sh
This PR refactors several classes in the `graphql-middleware` to include additional information such as `meetingId`, `userId`, and `sessionToken`. These additions make it easier to track and inspect a user's actions throughout their journey in the system.
For DEBUG logs, we've also added details like the file name, line number, and the function that called the logger. This makes debugging more straightforward by pinpointing exactly where logs are coming from.
These improvements will help developers and support teams quickly filter logs by user or session and efficiently identify and resolve issues.
---
Before:
```json
{
"browserConnectionId":"BC0000000003",
"hasuraConnectionId":"HC0000000004",
"level":"info",
"msg":"connected with Hasura",
"time":"2024-09-13T15:18:27-03:00"
}
``` 
After: …
=> refactor (gql-middleware): Enhance logging information adding more context

build/packages-template/bbb-export-annotations/opts-focal.sh
This library seems missing on custom images (notably dedicated (but not cloud) Hetzner) It is already present on all other installations we are aware of. If the library is not present, some annotations (most notably text) will be missing when trying to export annotations from whiteboard in both main and breakout rooms.
Closes #17927 (it's closed already but this seems to be the ultimate solution)
Closes #17303 (on 2.7. Not sure if we will backport to 2.6 at this point)
Closes #20690 (several other pull requests contributed there but this should be the last one)
Missing annotations reported by users in specific deployments.
Thanks to G. Schwed for bringing this up again and for confirming this as a fix!
=> build: Require libmagickcore-6.q16-6-extra for export-annotations

bigbluebutton-html5/imports/ui/components/whiteboard/cursors/component.jsx
This PR improves the cursor position calculation for touch events, ensuring correct placement in fullscreen mode and adjusting offsets appropriately
Related to  #17332 , #17722
=> fix: Correct cursor position calculation for touch events 

bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/notify/component.tsx
ports #21185 changes to BBB 3.0
_Logs whether the user chose to Continue or Leave when presented with the dialog on notifyRecordingIsOn_
=> chore(client): Add logs for recording notify action (3.0)

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Adds safeguard when checking for video srcObject in video preview component
=> fix: undefined object in video preview

bbb-webhooks.placeholder.sh
[v3.2.2](https://github.com/bigbluebutton/bbb-webhooks/releases/tag/v3.2.2)
---
* fix: handle missing checksum in API requests
* fix: cleanup corrupted Redis mappings
* fix: stale meeting mappings due to incorrect inactivity report
* build: express@4.21.0
* build: sinon@19.0.2
=> build(bbb-webhooks): v3.2.2

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(audio): restore "add more data to audio_joined/failure logs"](https://github.com/bigbluebutton/bigbluebutton/commit/313a6cb53d16fdc70bc0ed70e09294988f8f7ed5) 
- Commit https://github.com/bigbluebutton/bigbluebutton/commit/26815f4679a5abaad9549a324a28a15ddf9c9db9 was seemingly lost
during a merge in the 3.0.x-release branch. Nothing breaks, but we're
missing the log info originally added via that commit.
- Restore the changes in https://github.com/bigbluebutton/bigbluebutton/commit/26815f4679a5abaad9549a324a28a15ddf9c9db9:
- Add secondsToActivateAudio, inputDeviceId, outputDeviceId and isListenOnly
to audio_joined.extraInfo
- Add inputDeviceId, outputDeviceId and isListenOnly to
audio_failure.extraInfo
- Add a try-catch to the device enforcement procedure triggered by
onAudioJoin - …
=> fix(audio): restore "add more data to audio_joined/failure logs"

bbb-playback.placeholder.sh
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.1.2
Includes the polling annotation in presentation format playback. Closes https://github.com/bigbluebutton/bbb-playback/issues/277
=> build: Bump bbb-playback to 5.1.2

docs/docs/data/create.tsx, docs/docs/development/api.md, docs/docs/new-features.md
It was backported to BBB 2.7.9 so no longer counted as introduced in BBB 3.0
Modifies #20499 since we backported `allowPromoteGuestToModerator` to BBB 2.7.9 as well, making it the more accurate "introduction" of the parameter.
Closes # none
Thanks @SamuelWei for pointing this out!
=> docs: modify docs for allowPromoteGuestToModerator

docs/docs/data/create.tsx, docs/docs/development/api.md
Adjust the documentation to reflect that allowPromoteGuestToModerator was introduced in BBB 2.7.9 (not in 3.0) see #21241 
Closes #
BBB 2.7 match for https://github.com/bigbluebutton/bigbluebutton/pull/21241
Thanks @SamuelWei
=> docs: allowPromoteGuestToModerator documentation tweak [2.7]

bigbluebutton-html5/imports/api/bbb-web-api/index.ts, bigbluebutton-web/bbb-web.nginx, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy, docs/docs/administration/cluster-proxy.md
Some things were still broken in cluster setups:
- generating the relative URL to the API endpoint
- some CORS headers were missing
Closes #21130
Running multi node BBB without cluster setup feels wrong.
Thanks to @Ithanil and @danimo for investigating the issue
=> 3.0beta1 clusterfixes

bbb-playback.placeholder.sh
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.1.3
=> build: Bump bbb-playback to 5.1.3

bigbluebutton-tests/playwright/chat/chat.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/core/elements.js
Adds the test "Prevent specific user from sending public chat messages" for 2.7 and also on ci.
=> test: Prevent user from posting public chat

bigbluebutton-html5/imports/ui/components/layout/modal/styles.js
This PR fixes the layout modal style so it looks visually better.
=> style(modal): Update modal styles for better positioning on small screens

bigbluebutton-html5/imports/ui/components/meeting-ended/rating/styles.js
This PR alters feedbakc star icon so it better indicates how many starts are being given and simultaneously fix a mobile bug where the user had to click out to apply star.
#21316 & #21318 
Activate the custom parameter feedback on logout and play around with the stars.
=> fix(meeting-ended/rating): Update star rating icon to improve visual representation.

bigbluebutton-html5/imports/ui/components/common/menu/styles.js
fix issue with the first item in reactions button appearing as selected in ios
Closes #21320
=> fix: pre selected item in reactions button - mobile

bbb-webhooks.placeholder.sh
[v3.3.0](https://github.com/bigbluebutton/bbb-webhooks/releases/tag/v3.3.0)
---
* feat(metrics): add gauges for meeting and user Redis mappings
* fix(metrics): properly handle Prometheus collection failures
* fix(metrics): handle promises in setCollectorWithGenerator
=> build(bbb-webhooks): v3.3.0

bigbluebutton-html5/private/config/settings.yml
Just removing a language specification in a comment.
=> [3.0 chore] Remove language specification

bigbluebutton-config/bin/bbb-conf
* we were trying to touch the file every time even
for commands like bbb-conf --status
which are fine to be ran as non-sudo
* removed a few uses of `sudo` which were put in a block where `need_root` check
was already performed
* switched bbb-conf writing to bbb-html5.yml not settings.yml
Closes https://github.com/bigbluebutton/bigbluebutton/issues/19496
Seeing an error on `bbb-conf --status` as non-root user
run `bbb-conf --status` as non-root user
=> fix(conf): fix creating sfus etc override yml as non-sudo

bbb-presentation-video.placeholder.sh
https://github.com/bigbluebutton/bbb-presentation-video/releases/tag/5.0.0-beta.2
=> build: Bump bbb-presentation-video to 5.0.0-beta.2

record-and-playback/core/scripts/bigbluebutton.yml
Setting playback_protocol to https.
Closes #
Changing the default value from http to https. At this point the playback links generated in the recording metadata.xml files should default to httpS protocol
=> recording: Set playback_protocol to https

bbb-transcription-controller.placeholder.sh
https://github.com/bigbluebutton/bbb-transcription-controller/releases/tag/v0.2.7
https://github.com/bigbluebutton/bbb-transcription-controller/releases/tag/v0.2.8
=> build: Bump bbb-transcription-controller to 0.2.8

docs/docs/new-features.md
Documenting how to use ClamAV for presentation file scanning.
Closes # none
Related to: https://github.com/bigbluebutton/bigbluebutton/pull/21217
Needed to document https://github.com/bigbluebutton/bigbluebutton/pull/21217
This PR is a set of instructions. I documented them as I was testing them.
It might be nice to expand
- a note on updating the database for malicious elements
- some alternatives to running on the same box (pool of network clamavs)
- could mention the cpu / memory demand  (later on)
=> docs: Added a section for ClamAV

bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/Types/message.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/mutations.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/styles.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/styles.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx, bigbluebutton-html5/imports/ui/core/enums/chat.ts, bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts, bigbluebutton-html5/imports/ui/hooks/useStickyScroll.ts, bigbluebutton-html5/imports/ui/services/features/index.js, bigbluebutton-html5/imports/ui/services/storage/hooks.ts, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/locales/en.json
Add UI support for chat messages replies.
[Screencast from 2024-10-02 19-22-21.webm](https://github.com/user-attachments/assets/36675469-137f-4040-ac92-d56d3eb44d87)
n/a
See https://github.com/bigbluebutton/bigbluebutton/pull/21296 for the backend portion.
=> feat(chat): message replies

bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/container.jsx
Closes #21308
Join a session and switch to the next slide.
https://github.com/user-attachments/assets/1b57397f-f49a-41d7-bf8c-62655b9c9590
=> Fix: Handle repeated client console error (on slide change)

bigbluebutton-html5/imports/ui/components/waiting-users/service.js, bigbluebutton-html5/private/config/settings.yml
Space out the group handling of guest accept all.
Handle the groups in batches of up to three.
Dispatch a new batch approval every 500ms (configurable)
Closes # none official
We are seeing bbb-html5-frontends at 100% cpu for several minutes
when on a server with medium load a meeting sees the following scenario:
The moderator joins, sets guest policy to ASK_MODERATOR.
Lots of guests join the lobby (up to a hundred).
Then we see the approval of everyone (as the official session start time is hit).
Multiply this by a few similar sessions starting at the same time on the server and the
result is bbb-html5-frontend* CPU at maximum % for minutes at a time, long delays to load the client, etc.
Start a couple of busy sessions.
Then start one with guest policy ask moderator.
as guests fill up the …
=> fix: Space out approval of guests to better handle larger groups

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSessionBasicData.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
Add `fullname`, `userExtId` and `meetingExtId` to be stored for removed users, it will be useful for integrations.
=> refactor (bbb-web): Add more info for Removed User Session.

bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx, bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/components/join-handler/custom-users-settings/component.tsx, bigbluebutton-html5/imports/ui/components/settings-loader/component.tsx
This PR removes the stack trace from error screen to reduce the polution and not mislead the user, also removes the error code, because no pattern is followed and could cause misunderstanding of whats happening.
OBS: Future Refactor needed, relating errors and the codes so this item can be restored. #21455
Run the command `sudo bbb-conf --restart` in the server.
New:
Old:
=> Remove: Remove stack trace and error code from error screen

bigbluebutton-html5/private/config/settings.yml
Changes Hindi locale from hi-ID to hi-IN. 
Based on https://cloud.google.com/speech-to-text/docs/speech-to-text-supported-languages
=> [3.0.0b2] Fix Hindi locale

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Add stack trace to better investigate error in webcam background
=> chore(html5): Add stack trace to better investigate error in webcam background

bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/breakout-room-user-assignment-mobile/room-user-list/component.tsx
This PR fixes an issue where the moderator would click to asign a user and would asign other.
To test it join mobile bbb with 2 users (or more) and asign them to brakouts.
Before
[recording (16).webm](https://github.com/user-attachments/assets/b86451d1-a5a9-47e5-b8b2-722e269eda65)
After
[Screencast from 2024-10-03 16-54-08.webm](https://github.com/user-attachments/assets/030278ad-d24d-4676-ac12-07c6de289978)
=> Fix/mobile breakouts: Clicking one user would select another user

bigbluebutton-html5/imports/ui/components/app/service.js, bigbluebutton-html5/imports/ui/components/user-list/container.jsx
Branding logo is refresh every time dark mode refresh.
Closes None
[Screencast from 11-10-2024 12:51:25.webm](https://github.com/user-attachments/assets/2428535f-c618-4a44-aeb8-59f0a4d98ba9)
=> fix(dark-logo): darkreader changes are propagated to the user list

bigbluebutton-html5/imports/api/meetings/server/publishers.js
Adds a check to see if we have a user found before trying to look up the role.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/21483
Thanks to @fabio-garcia for describing this fix in https://github.com/bigbluebutton/bigbluebutton/issues/21483
See https://github.com/bigbluebutton/bigbluebutton/issues/21483
=> fix: Check if user is found before looking up role

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
clarify on LAD default value comment in bbb properties
Closes #
The previous version could (and was) misread as 0 being default
=> docs: clarify on LAD default value comment

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
=> [3.0]docs: clarify on LAD default value comment

bigbluebutton-html5/imports/ui/components/webcam/component.tsx, bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR addresses an issue where users on mobile devices, specifically in grid layouts, could not properly access or use whiteboard tools.
It also includes automatic toolbar hiding on mobile phones during interactions to maximize screen space and improve visibility on smaller screens.
Closes #21291
=> fix(whiteboard): Mobile whiteboard tool access with auto hiding

bigbluebutton-html5/imports/ui/components/learning-dashboard/service.js
=> fix (LAD/cluster) (backport 2.7): Enable LearningDashboard cookie support across different subdomains

docs/docs/administration/cluster-proxy.md
Updates the url for LAD in cluster proxy setup
Closes #none
Reported by @pielonet
=> docs: Update url for LAD in cluster proxy setup

docs/docs/administration/cluster-proxy.md
port of https://github.com/bigbluebutton/bigbluebutton/pull/21511
=> [3.0]docs: Update url for LAD in cluster proxy setup

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR updates tldraw's default text vertical and horizontal alignment values.
related to #21405
=> fix(whiteboard): Update tldraw default text alignment values

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/styles.ts
Refactor user actions component to conditionally render actions dropdown based on availability
Closes #21440
1. Join a meeting with an user.
2. Click on the user.
=> fix: User name is displayed when current user is selected on user list

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts
This PR alters some MD heading specifications in CSS.
Enter a meeting play around with MD heading in chat.
=> style(chat/message-content): Enhance heading styles in chat message component

.github/workflows/automated-tests.yml
Configure HTML5ClientLog for ci to try to debug using the `/var/log/nginx/html5-client.log` log.
Closes # none
We are seeing some connection issues instances on CI test runs. Trying to obtain logs.
Pull the logs, Look for `/var/log/nginx/html5-client.log` that should have been generated.
`cat /var/log/nginx/html5-client.log | sed -u -e 's/\\x22/"/g' -e 's/\\x5C/\\/g'` into a more digestible form.
=> ci: Configure HTML5ClientLog for ci

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationHistoryDAO.scala, bbb-graphql-server/bbb_schema.sql
This PR updates the `annotationInfo` field to `jsonb`, removing the need to check if it’s a JSON or a string. For removed annotations, the value will be `null`. This change, as confirmed by @KDSBrowne, will simplify client code.
Related: #21509  
Supports: #21571
Example:
```gql
subscription {
pres_annotation_history_curr {
annotationId
annotationInfo
pageId
presentationId
updatedAt
userId
}
}
```
```json
{
"data": {
"pres_annotation_history_curr": [
{
"annotationId": "shape:yqoGH5E81xtAgcUU1qX8s",
"annotationInfo": {
"x": 946.1111111111111,
"y": 323.00347222222223,
"id": "shape:yqoGH5E81xtAgcUU1qX8s",
"meta": {
"createdBy": "w_evuaiobx1vx8",
"updatedBy": "w_evuaiobx1vx8"
},
"type": "draw",
"index": "a1",
"props": {
"dash": "draw",
"fill": "none",
"size": "m",
"color": "black",
"isPen": …
```
=> refactor (gql-server): Convert `pres_annotation_history_curr.annotationInfo` to type Jsonb instead of String

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/private/config/settings.yml
Changes message toolbar positioning and display same sender message time on hover.
Closes n/a
=> fix(chat): Stick message toolbar to the message content and display message time on hover

bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/button/component.tsx, bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/button/styles.ts, bigbluebutton-html5/private/config/settings.yml
Added `bottom ` so icon gets aligned. (crooked icon)
=> style(audio/captions): Adjust icon positioning in the Closed Caption Toggle Button.

bbb-webrtc-sfu.placeholder.sh
[build(bbb-webrtc-sfu): v2.16.1](https://github.com/bigbluebutton/bigbluebutton/commit/d975dd0ef93e2969e37a9a2866dec0ed732a7cea) 
* fix(core): onEvent is not a transaction, treat it accordingly
* build: mcs-js@0.0.21
None
=> build(bbb-webrtc-sfu): v2.16.1

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx
Fix a bug where we cannot open links from replies.
n/a
=> fix(chat): Unable to open links from replies

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx, bigbluebutton-html5/imports/ui/components/poll/components/LiveResult.tsx
Removes decimals from poll results.
Closes #21594
- Create a Poll
- Publish a Poll
Needs a Follow up form @KDSBrowne making this change on whiteboard component.
=> Fix: Remove polls Decimals

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
This PR correctly determine sender identity and system message status in `ChatMessage` component.
Closes #21554 
Starta breakout room, assign users to them and then send message to all breakouts.
=> fix(chat/message): Correctly determine sender identity and system message status in `ChatMessage` component.

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR increases the MOUNTED_CAMERA_DELAY to ensure the tldraw camera is correctly positioned when it mounts
=> fix(whiteboard): Increase MOUNTED_CAMERA_DELAY time

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Updates the timeout values for the tldraw camera.
=> fix(whiteboard): Update tldraw camera timeout values

bigbluebutton-config/bin/bbb-conf
Reloading alone was not sufficient, errors on upgrade via bbb-install Credits: @hiroshisuga
Continuation from https://github.com/bigbluebutton/bigbluebutton/pull/21642 but also restarts nginx if not running.
Closes #21687 
Resolves `nginx.service is not active, cannot reload.`
Upgrade from BBB 3.0.0-beta.5 to the latest BBB (with this change) and not having to restart nginx manually/reboot.
=> conf: Reload or restart nginx before starting BBB

docs/docs/administration/install.md
Backport of #21674 from @basisbit to BBB 3.0
=> docs: install.md: suggest current vserver model (#21674)

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.js, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.js
This PR removes an unnecessary element in video preview, that was causing the actions bar buttons padding to be alternated. 
It also changes the margins got gaps for consistency. 
Start a meeting and use the actions bar (open video modal)
=> refactor(video-preview): Refactor VideoPreview component to improve structure and remove unnecessary background element.

docs/docs/development/api.md
=> docs: Added logoutURL to the list of api changes for 3.0

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
=> fix(bbb-web): Check to see if moderator has left in moderator count 3.0

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/styles.js, bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
This PR updates bbb/tldraw to the latest version and modifies the CSS to accommodate the new button introduced in the main toolbar.
Key Changes:
- Removed Top-Left Toolbar: The top-left toolbar was removed to streamline the UI and reduce visual clutter.
- Actions Button Relocation: The actions button previously located in the top-left toolbar has been moved to the bottom of the main toolbar.
before:
after:
=> fix(whiteboard): Update tldraw version and css to handle extra tool

bigbluebutton-html5/private/config/settings.yml
Enables by default the 3.0 chat features Edit, Delete, Reply and Reactions https://github.com/bigbluebutton/bigbluebutton/pull/21385 https://github.com/bigbluebutton/bigbluebutton/pull/21355 https://github.com/bigbluebutton/bigbluebutton/pull/21335
Closes # none
https://github.com/bigbluebutton/bigbluebutton/pull/21713 handled the recording scripts changes needed
https://github.com/bigbluebutton/bbb-playback/pull/286 added the needed changes to bbb-playback
Although https://github.com/bigbluebutton/bbb-presentation-video/issues/57 is still to be done, the video format is opt-in, so we should be able to enable the feature before it's implemented for that format.
=> chore: Enable by default chat edit, delete, reply, reactions

bigbluebutton-html5/package-lock.json
Updating dependencies for bbb-html5
Closes # none
```
cross-spawn  <6.0.6 || >=7.0.0 <7.0.5
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
node_modules/execa/node_modules/cross-spawn
http-proxy-middleware  <2.0.7
Severity: high
Denial of service in http-proxy-middleware - https://github.com/advisories/GHSA-c7qv-q95q-8v27
fix available via `npm audit fix`
node_modules/http-proxy-middleware
2 high severity vulnerabilities
```
=> chore: npm audit bbb-html5

bbb-export-annotations/package-lock.json
Updating dependencies of bbb-export-annotations
Closes #none
```
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
```
=> chore: npm audit bbb-export-annotations

docs/docs/new-features.md
- [docs: add info on LiveKit](https://github.com/bigbluebutton/bigbluebutton/commit/6598f6ab08201e2ec427a88b5c9fe9e5ddd92eb7) 
- Add LiveKit to the list of experimental features in 3.0 with:
* Instructions on enabling and using it
* Links to the issue tracker/meta issue
None
Ref #21374
=> docs: add info on LiveKit

build/packages-template/bbb-livekit/after-install.sh, build/packages-template/bbb-livekit/build.sh, build/packages-template/bbb-livekit/livekit-sip.service, build/packages-template/bbb-livekit/livekit-sip.yaml
Add livekit-sip as an optional service to the livekit package.
It is purposefully not part of the default bigbluebutton target.
=> build: Add livekit-sip to bbb-livekit package.

docs/docs/administration/install.md
This PR fixes two broken links in the docs: install.md
=> docs: Update install.md

docs/docusaurus.config.js
Adds a redirect to fix some old links to /3.0/new
Closes # none
See #21809
=> docs: add forwarding on 3.0/new

bigbluebutton-web/gradle.properties
Updating embedded-tomcat
Closes # none
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-8383920
=> chore(sec): bump embedded tomcat to 9.0.96

bbb-common-web/build.sbt, bbb-common-web/project/Dependencies.scala, bigbluebutton-web/pres-checker/build.gradle
Updates tika-* dependencies of bbb-web from 2.8.0 to 3.0.0 to mitigate some reported vulnerabilities
Closes # none
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612984
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254296
https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613076
Upload presentation files of various formats.
Tested with https://github.com/bigbluebutton/bigbluebutton/pull/18030#issuecomment-1568967945
=> chore(sec): bump tika (mime type detection) to 3.0.0

bigbluebutton-html5/deploy_to_usr_share.sh, bigbluebutton-html5/package-lock.json
Pulls newer version of several dependencies of `bbb-html5` based on `npm audit`
Also changes slightly the deploy script as I have been hitting problems with `meteor npm i`
Closes # none
npm audit
ci suffices
=> chore(sec): bbb-html5 npm audit

bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx, bigbluebutton-html5/imports/ui/components/emoji-rain/component.jsx, bigbluebutton-tests/playwright/core/settings.js, bigbluebutton-tests/playwright/user/multiusers.js, bigbluebutton-tests/playwright/user/user.spec.js
Adds the reactions tests for 2.7, and also runs it on ci.
=> test: adds the reactions tests for 2.7

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, docs/docs/data/getJoinUrl.tsx, docs/docs/development/api.md
The `getJoinUrl` endpoint generates a new `/join` URL that can be used to create a new session for an existing user. By associating the new session token with the same user ID, all sessions will appear as the same user in the user list, ensuring accurate user counts. Moderators can also customize the new session’s layout and user data parameters, allowing flexible control over the session’s environment and functionality.
This is particularly useful for hybrid environments where multiple screens in the same room each require a distinct session with different layouts.
It also facilitates seamless user session transfers to another device. For example, a mobile device can scan a QR code displayed on a computer, instantly migrating the user’s session from one device to another.
**Resource …
=> docs: Add docs for `getJoinUrl` and its parameters

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/service.js
- [fix(webcam): add rollback to video-preview gUM, improve logs](https://github.com/bigbluebutton/bigbluebutton/commit/a4c3ea34ace57a6fbd280a2428a829ab62b15873) 
- Following up on https://github.com/bigbluebutton/bigbluebutton/commit/2b503f47482695965f3218bf28ed9cbd6e6060ba, it'd be good if we had:
- More info on why getUserMedia fails
- A rollback procedure in case gUM failures are recoverable.
- This commit adds a rollback procedure for video-preview gUM calls whenever
the error type is OverConstrainedError. The retry happens with the
simplest constraint possible.
- Additionally:
- Add more information to video-preview gUM failure logs
- Add a centralized gUM error log to video-preview's service doGUM
util
- Proceed with the gUM routines even if the initial enumeration call
fails as the …
=> fix(webcam): add rollback to video-preview gUM, improve logs

bigbluebutton-config/bin/bbb-conf
This is a backport of PR #18141 for BBB 2.7
=> conf: Prevent deadlock while restarting BBB

docs/docs/administration/turn-server.md, docs/docs/support/faq.md
Replaces the link to test.bigbluebutton.org with a link to demo.bigbluebutton.org
Closes #
We no longer maintain a server test.bigbluebutton.org
=> docs: change link from test to demo bbb org

docs/docs/administration/turn-server.md, docs/docs/development/api.md, docs/docs/support/faq.md
=> docs: replace test with demo bbb org

bigbluebutton-html5/imports/ui/components/common/toast/styles.js, bigbluebutton-html5/imports/ui/components/presentation/styles.js, bigbluebutton-html5/imports/ui/components/raisehand-notifier/styles.js, bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
This PR fixes the toast styles to fit the styles found in 27.
Start a meeting and trigger toasts.
Before:
After:
=> style(toast): Update toast styles to fit 27's

bbb-common-web/build.sbt, bbb-common-web/project/Dependencies.scala, bigbluebutton-web/pres-checker/build.gradle
Ports https://github.com/bigbluebutton/bigbluebutton/pull/21823 to BBB 3.0+
=> [3.0]chore(sec): bump tika (mime type detection) to 3.0.0

docs/docs/new-features.md
Add three links to the list of the recent beta releases (beta.5, beta.6 & beta.7) in the new-features.md docs file
=> docs: Update new-features.md

bbb-graphql-server/bbb_schema.sql
Improve the performance of views `v_meeting_recording` and `v_user_connectionStatusReport` by removing the strategy of `array_agg` which is more costly for the server.
=> refactor (gqp-server): Improve performance of two views used by Hasura

docs/docs/accessibility.md, docs/docs/administration/cluster-proxy.md, docs/docs/administration/configure-firewall.md, docs/docs/administration/customize.md, docs/docs/administration/install.md, docs/docs/development/architecture.md, docs/docs/new-features.md, docs/docs/support/faq.md, docs/docs/support/troubleshooting.md, docs/static/img/diagrams/BBB30arch.drawio
I fixed a typo which I found while reading the documentation and used `codespell` and `typos` to find and fix more documentation issues.
=> Fix typos and grammar issues in documentation

bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR addresses a crash issue that occurs when renaming a frame shape on the whiteboard under specific conditions. It ensures proper handling of interactions when editing a frame label and clicking within the frame.
Steps to Reproduce:
Edit the label of a "Frame".
Click once inside the frame.
Click anywhere else on the whiteboard.
before:
after:
Closes #21765
=> fix(whiteboard): Handle crash renaming a frame on the whiteboard

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/styles.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx, bigbluebutton-html5/public/locales/en.json
This PR includes a few fixes and enhancements to improve the experience on the chat.
[Screencast from 12-12-2024 15:10:50.webm](https://github.com/user-attachments/assets/32fec61f-c086-4308-baed-c642f505246b)
Also, it fixes two bugs:
1. Message being refocused after closing and opening the chat panel.
2. User is not able to select text from messages by using only the mouse (context menu > copy).
n/a
Go to chat and try out the abovementioned features.
You can navigate betwen the chat messages by focusing the message list and then pressing `KeyUp` or `KeyDown`. When you get the message you want, you can access its toolbar by pressing `ArrowRight`.
=> fix(chat): A few fixes and enhancements

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomDAO.scala, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom_createdLatest.yaml, bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
In order to re-implement https://github.com/bigbluebutton/bigbluebutton/pull/13678 in 3.0.
This PR provides a new graphql type `breakoutRoom_createdLatest` that will provide info about the last rooms created.
The new type is available only for moderators.
```gql
subscription {
breakoutRoom_createdLatest {
breakoutRoomId
sequence
name
shortName
isDefaultName
durationInSeconds
freeJoin
sendInvitationToModerators
captureNotes
captureSlides
createdAt
startedAt
endedAt
}
}
```
```json
{
"data": {
"breakoutRoom_createdLatest": [
{
"breakoutRoomId": "2f12fec547a3878aa471b47bea2bff68df844e42-1736777408492",
"sequence": 1,
"name": "Room 1",
"shortName": "Room 1",
"isDefaultName": true,
"durationInSeconds": 900,
"freeJoin": false,
"sendInvitationToModerators": false,
"captureNotes": false, …
```
=> feat (gql-server): Introduces Type `breakoutRoom_createdLatest` for restoring last rooms

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/LearningDashboardService.java
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/21998
=> fix (bbb-web/akka) (2.7) : Fix a few Learning Analytic Dashboard related issues

bigbluebutton-tests/playwright/audio/audio.spec.js, bigbluebutton-tests/playwright/breakout/breakout.spec.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/connectionFailure/connectionFailure.spec.js, bigbluebutton-tests/playwright/presentation/presentation.spec.js, bigbluebutton-tests/playwright/screenshare/screenshare.spec.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/webcam/webcam.spec.js, docs/docs/testing/release-testing.md
Updates `release-testing` doc and `.spec` files with the manual test link
- port of #20913
- port of #22000
=> docs: Updates release-testing docs (from 2.7)

docs/docs/testing/release-testing.md
Adjust the docs to drop some characters that we can no longer use in MDX
Closes #
```
Error: MDX compilation failed for file "/home/bigbluebutton/src/docs/docs/testing/release-testing.md"
Cause: Unexpected character `-` (U+002D) before name, expected a character that can start a name, such as a letter, `$`, or `_`
Details:
{
"column": 120,
"message": "Unexpected character `-` (U+002D) before name, expected a character that can start a name, such as a letter, `$`, or `_`",
"line": 1797,
"name": "1797:120",
"place": {
"_bufferIndex": 113,
"_index": 0,
"line": 1797,
"column": 120,
"offset": 74450
},
"reason": "Unexpected character `-` (U+002D) before name, expected a character that can start a name, such as a letter, `$`, or `_`",
"ruleId": "unexpected-character",
"source": …
```
=> fix: Remove characters breaking the docs build

docs/docs/new-features.md
- [docs: instructions to run livekit/egress via Docker](https://github.com/bigbluebutton/bigbluebutton/commit/6015e7c28221406d7dad96de551acf58a8d13266) 
- Add instructions on how to run livekit/egress via Docker. This should
enable recording capture with LiveKit.
-  Keep in mind these are temporary instructions while a proper
build/install routine isn't in place. Once it is, these instructions
will be amended.
None
Ref #21059
=> docs: instructions to run livekit/egress via Docker

docs/docs/testing/release-testing.md
Same as https://github.com/bigbluebutton/bigbluebutton/pull/22019 but on BBB 3.0+
=> [3.0] docs: fix characters breaking docs build

docs/docs/data/create.tsx, docs/docs/development/api.md
Includes `pluginManifests` to the list of supported CREATE parameters starting with BBB 3.0.
Closes #none
It was missing from the docs and people were requesting the functionality without knowing it was implemented.
=> docs: include pluginManifests as CREATE parameter

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/queries.ts, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/queries.ts, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx
Fixes several places where the breakout room name is not translated when it is the default name.
Closes n/a
=> fix(breakout): Breakout default name not translated in several places

bbb-graphql-server/bbb-graphql-schema.md
This PR introduces a document detailing all Types and Fields of BBB GraphQL. The document serves as a reference for plugin developers and BBB developers.
In the future, this content will be incorporated into the official documentation and enhanced with more detailed descriptions. This is the initial version.
=> graphql-server: Types and Fields Reference for BBB GraphQL (Initial Version)

bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Adds check for chat start closed param in push layout engine, to ensure that the chat will only start open if this setting is not used.
Closes #22081
1. Configure startClosed: true (default is false)
2. Start the meeting with settings above
3. Wait for chat to be processed or not
=> fix: public.chat.startClosed has no effect

docs/docs/administration/customize.md, docs/docs/data/create.tsx, docs/docs/data/join.tsx, docs/docs/development/api.md
Documents:
- `userdata-bbb_hide_notifications` from https://github.com/bigbluebutton/bigbluebutton/pull/21415
- `userdata-bbb_hide_controls` from https://github.com/bigbluebutton/bigbluebutton/pull/21410
- `MEDIA_ONLY` from https://github.com/bigbluebutton/bigbluebutton/pull/21409
- changed Kurento parameters to Media parameters
Closes # none
Documentation was missing.
=> docs: userdata-bbb_hide_notifications, userdata-bbb_hide_controls, MEDIA_ONLY

.github/workflows/deploy-docs.yml
Updates the version of actions/upload-pages-artifact from v1 to v3
Closes # none
before
after:
Docs build
=> ci: update upload-pages-artifact to v3

.github/workflows/deploy-docs.yml
Same as https://github.com/bigbluebutton/bigbluebutton/pull/22170 but to branch develop
=> ci: update upload-pages-artifact to v3 [develop]

docs/docs/support/faq.md
Adds a question mark at the end of the questions in the FAQ section of the docs.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/17128
There were only a few questions ending in a `?`.
=> docs: add question mark for questions in FAQ

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx, bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/guest-items/guestPendingUser.tsx, bigbluebutton-html5/imports/ui/components/waiting-users/waiting-users-graphql/guest-items/guestUserItem.tsx
Improves user experience for screen reader users by adding aria hints for user lists in BBB:
* Meeting participants list
* waiting users list
Make BBB the most accessible virtual classroom and video conferencing system.
=> Accessibility: improve userlists

bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx, bigbluebutton-html5/imports/ui/components/layout/push-layout/hooks.ts, bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Fixes a bug where the local layout is not updated when the presenter pushes meeting layout.
Closes #22157
=> fix(layout): Local layout not respecting meeting layout

bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx, bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/styles.ts
Improved UI to a better usability in sidebar content.
Closes None
[Screencast from 31-01-2025 14:33:38.webm](https://github.com/user-attachments/assets/27238cd3-16b6-45b3-9174-6c494029f73f)
=> fix(breakout-room): UI improvements for usability

bigbluebutton-html5/imports/ui/components/common/toast/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/styles.ts, bigbluebutton-html5/imports/ui/components/recording/component.tsx, bigbluebutton-html5/imports/ui/services/notification/index.js
Addition of tooltips that were missing and correction of title showed when recording is already started. Correction of the "Leave Meeting" button clickable area.
Closes None
[Screencast from 29-01-2025 15:05:40.webm](https://github.com/user-attachments/assets/5440b6de-ba0e-4438-88f4-a27fc6b7e24e)
=> fix(recording-button): tooltip and behavior corrections

bbb-presentation-video.placeholder.sh
https://github.com/bigbluebutton/bbb-presentation-video/releases/tag/4.0.5
Brings in newer fixes from bbb-presentation-video
Closes # none
A fix is included in 4.0.5, see https://github.com/bigbluebutton/bbb-presentation-video/pull/56
=> chore: Bump bbb-presentation-video to 4.0.5

docs/docs/administration/customize.md, docs/docs/new-features.md
Documents:
- Adds a mention of S3 cache for presentations in whats new in 3.0
- Moves the ClamAV info to Customize and link to it
- Adds a link to rc.2; add missing layout to whats new
- Adds 3 plugins to the list
- Adjust the sections of Customize so they fit the correct sections
- Adds instructions for multiple Hasuras  #21855
=> docs: Various 3.0 documentation; Multiple Hasuras instructions

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/reaction-item/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts, bigbluebutton-html5/imports/ui/core/enums/chat.ts
- Improve keyboard navigation by trapping the focus within message container.
- Implement roving on message reactions.
- Simplify code.
- Remove the listbox role from page container so screen readers can access the messages (Thanks @KDSBrowne).
[Screencast from 30-01-2025 09:30:56.webm](https://github.com/user-attachments/assets/07becb6b-a9ba-43ea-9322-d5c62e7b2200)
Partially closes #22075
- Go to chat.
- Enter several messages.
- Try accessing all chat features by using only keyboard.
=> fix(chat): Keyboard navigation + message accessibility

docs/docs/data/create.tsx
Adjusts info about default meetingLayout
Closes # none
=> docs: Adjust info about default meetingLayout

bbb-graphql-actions/src/actions/userSetRaiseHand.ts, bbb-graphql-actions/src/imports/validation.ts
Allows presenters who are not moderators to also lower hands in the session.
Closes #22103 
Matching BBB 2.7 and user expectations.
Follow the steps from #22103
=> fix(gql-actions): Allow non-moderator presenters to also lower raise hands

bigbluebutton-config/bin/bbb-record
Porting #21885 to BBB 3.0
Thanks @pizkaz
I had to tweak the title rows a little bit to get the alignments right on BBB 3.0
=> [3.0] impr(bbb-record): Clarify recording status output

bigbluebutton-web/gradle.properties
Bumps embedded tomcat to 9.0.98
Closes # none
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-8523186
=> [3.0]chore(sec): bump embedded tomcat to 9.0.98

bigbluebutton-web/gradle.properties
=> [2.7]chore(sec): bump embedded tomcat to 9.0.98

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts, bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/styles.ts, bigbluebutton-html5/imports/ui/stylesheets/styled-components/general.js
- Overall size of side panels: Size aligned with the start and end of the icons in the sidebar.
- Font size of modified notifications.
- Size of modified user list elements.
- Restrict the 'Public Chat' and 'Private Chat' buttons to a single line.
- Talking effect fixed.
Closes None
=> fix(UI): UI fixes pointed by design team

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Reverts bigbluebutton/bigbluebutton#22207
Reverting as this PR introduced a bug when changing layout!
=> Revert "fix(whiteboard): Remove duplicate zoom propagation"

bigbluebutton-html5/imports/ui/components/sidebar-navigation/user-notes-list-item/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/user-item-toolbar/component.tsx, bigbluebutton-tests/playwright/breakout/join.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/parameters/disabledFeatures.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.js, bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js, bigbluebutton-tests/playwright/sharednotes/util.js, bigbluebutton-tests/playwright/user/lockViewers.js, bigbluebutton-tests/puppeteer/sharednotes/util.js
This PR fixes + updates all shared notes tests with the new UI
- steps description enhanced;
- `Pin and unpin notes onto whiteboard` assertions update + flaky flag removed;
=> test(new-ui): Update shared notes test steps

bigbluebutton-html5/imports/api/screenshare/client/bridge/livekit.ts
- [fix(livekit): screen subscription occasionally fails](https://github.com/bigbluebutton/bigbluebutton/commit/282d7166c26e956ee54e5c1487f0a29992de1f5b) 
- LiveKit's screen share bridge occasionally fails to subscribe to remote
publications - more likely when joining a room with an ongoing
subscription. There was a routine in place to sync publications on join,
but it had an issue where publication _tracks_ might no be populated yet
when running that sync. That causes the source check for the track to
fail, and so does the subscription.
None
Ref #21059
=> fix(livekit): screen subscription occasionally fails

bbb-webhooks.placeholder.sh
- [build(bbb-webhooks): v3.3.1](https://github.com/bigbluebutton/bigbluebutton/commit/0f658052db4e9a04a922810f31f9e5c4ad4f7e01) 
* fix: missing userdata in user-joined event (BBB 2.7 and 3.0)
* build: express@4.21.2
None
=> build(bbb-webhooks): v3.3.1

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
This PR fixes the conditional render of the reactions button based on the `public.userReaction.enabled` and `public.app.reactionsButton.enabled` settings
=> fix(reactions-button): Conditionally render reactions button based on settings

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx, bigbluebutton-html5/imports/ui/components/connection-status/button/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx, bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/styles.ts, bigbluebutton-html5/imports/ui/components/nav-bar/styles.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js, bigbluebutton-html5/imports/ui/components/settings/styles.js
Fixes:
- Recording button is too big in the navigation sidebar and pulls the three dots out of the screen
- Settings modal should fit the screen - tabs are taking up to much space
- The navigation sidebar is a little bit over the talking indicators (
- The icon of the navigation sidebar toggle button should be changed
- The emoji picker is shifted and unaccessible
Already right
- Actions bar is too crowded with new buttons
- Mobile client should not have custom layout
Needs new design from design team
- The navigation sidebar is a little bit over the talking indicators 
Closes None
=> fix(mobile): UI mobile improvements for better usability

docs/docs/support/troubleshooting.md
=> docs: Add docs for Network-Client Common Errors

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Just updates SDK version to 0.0.73.
CORE PR was merged before update: https://github.com/bigbluebutton/bigbluebutton/pull/22269
=> [update-sdk-version] update sdk version to 0.0.73

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
Fixes chat loading all pages on the first render.
Chat with 200+ messages (5 pages):
[Screencast from 10-02-2025 16:31:01.webm](https://github.com/user-attachments/assets/0315a905-9262-46fb-88e0-42464be4b937)
Same scenario:
[Screencast from 10-02-2025 16:32:23.webm](https://github.com/user-attachments/assets/5fb32ce8-198d-4c48-a344-98109fcc6bbc)
n/a
=> fix(chat): Fix chat loading all pages

bigbluebutton-html5/imports/ui/components/user-list/component.tsx
fix incorrect locale string id and description
=> fix: typo in userlist component

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR adds a missing import for the logger.
Closes #22327
=> fix(whiteboard): Add missing logger import

bigbluebutton-tests/playwright/chat/chat.js, bigbluebutton-tests/playwright/chat/chat.spec.js, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/page.js
This PR improves and fixes chat tests:
- properly usage of `grantClipboardPermissions` and settings;
- emoji tests related update;
- update and enable tests that only worked on headed mode previously;
- assertions improved;
=> test: Improve chat tests

bigbluebutton-html5/imports/ui/components/user-list/crowd-action-buttons/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/guest-management/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/guest-management/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/guest-management/waiting-users/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/guest-management/waiting-users/guest-policy/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/guest-management/waiting-users/guest-policy/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/guest-management/waiting-users/styles.ts, bigbluebutton-html5/imports/ui/components/user-list/styles.ts
Implementation of new Guest Manager UI and new user list footer spacing.
Closes None
[Screencast from 18-02-2025 15:53:45.webm](https://github.com/user-attachments/assets/97d5e3f5-fbbb-4dbb-b605-e0bdba7601e3)
=> feat(user-list): new guest management UI and footer space

bigbluebutton-html5/imports/ui/components/poll/components/PollQuestionArea.tsx, bigbluebutton-html5/imports/ui/components/poll/styles.ts
Make changes on poll creation panel to make it fit mostly all screen
Closes #22143
-  Open Poll cration Panel
-  See Results
=> Poll: Reduce gaps to make Poll fit in a screen 1080p

bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
Adds the reason message when redirecting the user to the logoutUrl, so external apps can know why the user was redirected.
We need this info in the Custom Feedback app to show why the user was redirected (in bbb the meetingEnd screen can be disabled)
- Leave/end/kick user from meeting
- See redirected url with the param
=> feat(html): add reason to the redirect logoutUrl

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fix sessionName param in getJoinURL request
Closes #22357
=> Fix sessionName param in getJoinURL

bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.17.0-beta.3](https://github.com/bigbluebutton/bigbluebutton/commit/a123f15fdf17d6f2d86caecc59910c3b887300b1) 
* feat(livekit): add egress retry routines and Prometheus metrics
* fix(livekit): retry egress regardless of error type
* fix(livekit): handle egress shutdowns and assorted fixes
None, ref #21059
=> build(bbb-webrtc-sfu): v2.17.0-beta.3

bbb-graphql-server/bbb-graphql-schema.md, bbb-graphql-server/bbb_schema.sql, bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/queries.ts, bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Bots shouldn't receive breakout invitations
Closes None
=> fix(breakout-rooms): invitations not open for bot

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GuestsWaitingApprovedMsgHdlr.scala
Dial-in users was not joining properly after being approved by the Moderator.
And Moderator was not receiving notification that the dial-in user was waiting.
[Screencast from 2025-02-21 16-21-35.webm](https://github.com/user-attachments/assets/5dca49cf-e9b3-42f5-b94f-63898bf47764)
Closes:
#22307
#22345
=> fix (akka-apps): fix problems with Dial-In users when Guest Policy is Ask Moderator

bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.17.0-beta.4](https://github.com/bigbluebutton/bigbluebutton/commit/e32dd8231054cecf09a94292245c4bea5ae840c4)
* feat(livekit): add support for recordFullDurationMedia=false
* feat(livekit): make egress retry timers configurable
* fix(livekit): temporarily disable custom maxParticipants limit
None
=> build(bbb-webrtc-sfu): v2.17.0-beta.4

docs/docusaurus.config.js
Set 3.0 as default in docs dropdown
Closes # none
3.0.0 being released.
=> docs: Set 3.0 as default in docs dropdown

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, bbb-graphql-server/bbb_schema.sql
Update ejected status of guest in database and adjust view query to take it into account.
Closes #21833
Guests that close the waiting window/lose connection  were not being removed from guest panel.
See issue.
=> fix(guest-waiting): update guest as ejected in database

bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/imports/ui/services/meeting-settings/index.js
Adds safeguards to prevent errors (in this case caught but likely the whiteboard crashed) due to undefined
Closes #none
In session logs I am seeing
```
{
"name": "clientLogger",
"level": 50,
"logCode": "ErrorBoundaryWithReload.GlobalError",
"extraInfo": {
"errorMessage": "Cannot read property 'data' of undefined",
"errorStack": "TypeError: Cannot read property 'data' of undefined\n    at https://SERVER/html5client/bundle.46683395b08aabc84ee6.js:2:563176\n    at Object.error (https://SERVER/html5client/bundle.46683395b08aabc84ee6.js:2:401252)\n    at O (https://SERVER/html5client/bundle.46683395b08aabc84ee6.js:2:2295618)\n    at T (https://SERVER/html5client/bundle.46683395b08aabc84ee6.js:2:2296075)\n    at e.t.error (https://SERVER/html5client/bundle.46683395b08aabc84ee6.js:2:2296660)\n …
```
=> fix: Add checks to avoid undefined and crashes

bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Adds checks for possibly undefined values
Prevent errors / crashes
=> fix: add checks for undefined values

.github/dependabot.yml
Tweaked the configuration for Dependabot so that
- the frequency is reduced from daily to weekly
- `v2.7.x-release` is set as the legacy (security patches only)
- `v3.0.x-release` is set as the the current branch (security patches only)
- `v3.1.x-release` is set as the branch where dependency dev updates (not only security) are welcome
Closes # none
We just got a burst of 90 PRs on `v3.0.x-release` of which a good deal is dev updates (and we will likely close them).
=> chore: dependabot to fix sec only on 2.7, 3.0; on 3.1 - anything

bbb-playback.placeholder.sh
Bump bbb-playback to 5.3.0
Closes # none
https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.3.0
=> build: Bump bbb-playback to 5.3.0

bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/user/multiusers.js, bigbluebutton-tests/playwright/user/user.spec.js, bigbluebutton-tests/playwright/user/util.js
- Updates `Mute all users` to `Disable users join muted`;
- Fixes and updates steps of `Mute all users except presenter` + re-enable in CI;
=> test: Mute users tests update

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Bumps tldraw to alpha.27 (from our fork) so we can pull our latest changes.
Related:
https://github.com/bigbluebutton/bigbluebutton/pull/22487
https://github.com/bigbluebutton/bigbluebutton/pull/22588
https://github.com/bigbluebutton/tldraw/releases/tag/v2.0.0-alpha.27
=> chore: bump tldraw to 2.0.0-alpha.27

bigbluebutton-web/gradle.properties
Bump embedded tomcat to version 9.0.102 due to vulnerabilities in .98.
.99 resulted in initialization issues. .100 worked fine but so did .102.
Closes # none
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-9396739
=> [3.0]chore(sec): bump embedded tomcat to 9.0.102

bbb-graphql-actions/src/actions/pollCreate.ts, bigbluebutton-html5/imports/ui/components/poll/components/StartPollButton.tsx, bigbluebutton-html5/public/locales/en.json
Reduces the mininum value for custom polls options, allowing custom polls to be created with one option.
=> refactor: allow custom polls with one option

bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.17.0-beta.5](https://github.com/bigbluebutton/bigbluebutton/commit/5210b52db3426dffd4de76103a984f8aae8db0c7)
Closes https://github.com/bigbluebutton/bigbluebutton/issues/22434
=> build(bbb-webrtc-sfu): v2.17.0-beta.5

docs/docs/administration/customize.md
Improves the client title change docs.
Closes # none
The docs portion about changing the client title was wrong, and was also duplicated.
=> docs: Adjust client title docs

docs/docs/new-features.md
Adds lists of what was removed/changed/added to bigbluebutton.properties to assist administrators with the transition from BBB 2.7 to 3.0
Closes # none
Assist administrators with the transition from BBB 2.7 to 3.0
=> docs: Full list of changes to bbb-web properties

bbb-graphql-middleware/go.mod, bbb-graphql-middleware/go.sum
Updates `klauspost/compress` dependency of bbb-graphql-middleware.
Closes # none
Snyk is panicking.
=> chore: bump klauspost/compress

bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Memoize whiteboard custom UI overrides configuration.
Closes #22705
=> fix(html5): Memoize whiteboard custom UI overrides config

docs/docs/data/create.tsx
Clarifies how we resolve the situation when we have plugin lists provided both on per-server basis and on /create.
Closes # none
It's a confusing area.
=> docs: Clarify conflict resolution in pluginManifests

.github/workflows/automated-tests-publish-results.yml
after https://github.com/bigbluebutton/bigbluebutton/pull/22749 merge, I noticed an unexpected action error:
```
/home/runner/work/_temp/-------.sh: line 5: syntax error: unexpected end of file
Error: Process completed with exit code 2.
```
This PR fixes the run script block with the correct formatting. The error occurs when triggered by a merge PR event, so I tried the same in my fork with these changes and got no errors
=> ci(fix): Correct formatted run script

bigbluebutton-html5/client/main.html, bigbluebutton-html5/deploy.sh, bigbluebutton-html5/package.json, bigbluebutton-html5/webpack.config.js, build/packages-template/bbb-html5/build.sh
Safari browsers (<=16) fail to load the client properly due to issues caused by the `TerserPlugin` minification process, resulting in errors like `Right side of assignment cannot be destructured` and later `ReferenceError: Can't find variable: HistoryManager` and related race conditions. 
**Disabling `TerserPlugin` resolves these errors but significantly increases the bundle size (from `5.6 MB` to `13 MB`).**
The implemented solution generates two bundles:
- **Minified bundle (5.6 MB)**: Served to modern browsers and Safari versions >16.
- **Non-minified bundle (13 MB)**: Served exclusively to older Safari versions (<=16), ensuring functionality without errors.
This selective bundling guarantees that older Safari browsers work correctly without negatively impacting performance for other …
=> fix (html5): Fix whiteboard crash on Safari versions <= 16

bbb-webrtc-sfu.placeholder.sh
v2.17.0-beta.7
---
* fix(audio): channel incorrectly muted when transferring to breakout room
=> build(bbb-webrtc-sfu): v2.17.0-beta.7

bigbluebutton-html5/imports/ui/components/wake-lock/container.jsx
fix wake lock permission error when joining a session with a mobile device.
Closes #22724
1. join a meeting on a mobile device
=> fix: error acquiring wake lock

bigbluebutton-html5/imports/startup/client/logger/index.ts
Make logs by level to better filter them on console.
Closes #22373
- Join a user 
- Open devtools
- Select network tab
- Add a network throttling to 3G or offline 
- Wait 15s
- Look at the logs
[Screencast from 25-03-2025 09:44:15.webm](https://github.com/user-attachments/assets/e963daa1-ac22-4948-9e70-64bca0e99ae2)
=> Refactor(html5): Make logs by level

bbb-webrtc-sfu.placeholder.sh
v2.17.0-beta.8
---
* feat(metrics): add counter for transceiver's consumer restarts
* fix(audio): handle global audio bridge failures
* fix(audio): make fs-consumer-bridge disconn handler verify current IDs
* chore(audio): add option to control when global audio restarts
=> build(bbb-webrtc-sfu): v2.17.0-beta.8

bigbluebutton-html5/imports/ui/components/session-details/component.tsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/core/helpers.js, bigbluebutton-tests/playwright/core/page.js, bigbluebutton-tests/playwright/parameters/constants.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js
Adds `Custom Parameters › Show Session Details on Join` test
=> test: Add session details modal (join parameter) test

bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
Aims to prevent `TypeError: Cannot read properties of null (reading 'getBoundingClientRect')`
Closes # none
Client logs pointing to 
Not sure how exactly to hit this. But am seeing logs about it.
=> fix(html5): Prevent undefined rect

bbb-export-annotations/workers/process.js
The variable outputDir already contains 'jobId' in workers/process.js. So the path written is not functionnal if we just copy-paste it :)
Example :
Saved PDF at /var/bigbluebutton/df7d32d5c54708e36660921af0c2c0addaf83888-1741621036246/df7d32d5c54708e36660921af0c2c0addaf83888-1741621036246/d7458334e763643017dc4683d77fb29b8d0a9a13-1741621036274/pdfs/3lbieiaroyc87a9g/3lbieiaroyc87a9g/annotated_slides.pdf
Whereas the real functionnal path is :
Saved PDF at /var/bigbluebutton/df7d32d5c54708e36660921af0c2c0addaf83888-1741621036246/df7d32d5c54708e36660921af0c2c0addaf83888-1741621036246/d7458334e763643017dc4683d77fb29b8d0a9a13-1741621036274/pdfs/3lbieiaroyc87a9g/annotated_slides.pdf
Closes #
=> SMALL FIX : Remove duplicate jobId in logger

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/page/component.tsx, bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Add missing subscription data for current user. That data are used to check if the current user has whiteboard access.
Closes #22798
=> fix(html5): Add missing subscription data for current user

bbb-webrtc-sfu.placeholder.sh
v2.17.0
---
* feat(livekit): add track egress support
* feat(livekit): webhooks module
* feat(livekit): server side BBB <-> LiveKit event sync
* feat(livekit): add server domain to metadata
* feat: base-manager may opt out of connecting to mcs-core
* feat: add `enabled` flag to SFU modules, default to true
* feat: add state sync and recording RPCs for LiveKit
* feat(livekit): sync screen share state with BBB
* feat(livekit): handle camera ejections
* feat(livekit): add egress retry routines and Prometheus metrics
* feat(livekit): add support for recordFullDurationMedia=false
* feat(livekit): make egress retry timers configurable
* fix(livekit): do not sync stale egress instances
* fix(livekit): improve state sync and external user handling
* fix(core): onEvent is not a transaction, treat …
=> build(bbb-webrtc-sfu): v2.17.0

bbb-webrtc-sfu.placeholder.sh
v2.17.1
---
* build(medisoup): 3.14.14 (without extra debug logs)
=> build(bbb-webrtc-sfu): v2.17.1

record-and-playback/core/lib/recordandplayback/edl/video.rb
The video remux isn't guaranteed to fix video decoding problems. Ensure that the video decoding check is re-run after the remux step is done, to see whether the remux actually helped.
This fixes a recording processing failure in some recordings from BigBlueButton <3.0.4 where it's possible that the video recording corruption issues might produce a video file which has unrecoverable corruption in the video codec initialization data, such that no video can be decoded.
=> recording: Recheck whether video can be decoded after remux

bbb-export-annotations/shapes/TextShape.js
Preserve whitespaces in text shapes.
Whiteboard:
Exported presentation:
- With the fix: [default.pdf](https://github.com/user-attachments/files/19605881/default.pdf)
- Without the fix: [default (1).pdf](https://github.com/user-attachments/files/19605886/default.1.pdf)
Closes #[22031](https://github.com/bigbluebutton/bigbluebutton/issues/22031)
=> fix(bbb-export-annotations): Preserve whitespaces in text shapes

bbb-export-annotations/shapes/Shape.js, bbb-export-annotations/shapes/StickyNote.js
- Add some padding to the container.
- Wrap overly long words.
**Whiteboard:**
**Exported annotations:**
- Before: [default (1).pdf](https://github.com/user-attachments/files/19593139/default.1.pdf)
- Now: [default.pdf](https://github.com/user-attachments/files/19593143/default.pdf)
Closes #21312
=> fix(bbb-export-annotations): Fix rendering of sticky notes

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRaiseHandReqMsgHdlr.scala, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/services/features/index.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, docs/docs/data/create.tsx, docs/docs/development/api.md
Implements disabledFeatures: raiseHand
Closes #22829
1. create a meeting and set `disabledFeatures=raiseHand`
2. join the meeting
3. raise hand button should not be displayed
=> feat: Support to disable raise hand feature via disabledFeatures

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Bumps tldraw from alpha.27 to .29
Closes # none
https://github.com/bigbluebutton/tldraw/pull/28 was needed for https://github.com/bigbluebutton/bigbluebutton/pull/22624
=> chore(client): bump tldraw to 2.0.0-alpha.29

.github/workflows/automated-tests-publish-results.yml
Porting #22922 to the correct base/default branch
=> feat(ci): New step in CI to publish in digital oceanic spaces (mockup)

docs/docs/administration/customize.md, docs/docs/support/troubleshooting.md
Renames apply-conf.sh to apply-config.sh -- likely a typo.
Closes #17766
There is no such file apply-conf.sh
=> docs: Rename apply-conf.sh to apply-config.sh

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfSlidesGenerationService.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationConversionCompletionService.java
Adds additional logs to the presentation conversion process to track pages that have finished processing.
These additional logs may be useful to identify rare erroneous behaviours in the document conversion process.
=> refactor(API): Add more logs during presentation conversion

bigbluebutton-html5/imports/ui/components/video-provider/service.ts
=> fix (html5): avoid `cannot read prop of null` for `isLocalStream` param

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
- Recalculate chat scroll position only when the new loaded page is the first page to load.
Closes #22898
=> fix(html5): Chat auto scrolling glitch

bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/component.tsx
- Fixes a bug where the user is unable to click to play the video if autoplay is blocked.
Closes #22961
=> fix(html5|external-video): Unable to play on mobile

bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx, bigbluebutton-tests/playwright/core/elements.js, bigbluebutton-tests/playwright/parameters/constants.js, bigbluebutton-tests/playwright/parameters/customparameters.js, bigbluebutton-tests/playwright/parameters/parameters.spec.js
Implements the logoutURL parameter test.
https://docs.bigbluebutton.org/development/api/#create
=> test: logoutURL parameter

bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
Save unsent messages on session storage instead of local storage.
Closes #22990
=> fix(html5/chat): Save unsent messages on session storage

bbb-webrtc-sfu.placeholder.sh
v2.18.0
---
* feat(livekit): support recording LiveKit streams through bbb-webrtc-recorder
* feat(livekit): add webrtc-recorder status and error metrics to LK module
* feat(livekit): add recorder reqs/resps counter metrics
* fix(livekit): make dial-in pin requirement configurable (default: false)
* fix(livekit): create inbound trunks based on voice bridge number
* fix(livekit): clean trunks and dispatch rules on restarts
* fix(livekit): attach room metadata to inbound trunks and dispatch rules
* fix(livekit): link dispatch rules to respective inbound trunks
* fix(livekit): expose inbound trunks and dispatch rules configs
* fix: restart loop on boot due to early requests
* fix(livekit): guarantee uniqueness of "external" LK users
=> build(bbb-webrtc-sfu): v2.18.0

bbb-webrtc-sfu.placeholder.sh
v2.18.0
---
* feat(livekit): support recording LiveKit streams through bbb-webrtc-recorder
* feat(livekit): add webrtc-recorder status and error metrics to LK module
* feat(livekit): add recorder reqs/resps counter metrics
* fix(livekit): make dial-in pin requirement configurable (default: false)
* fix(livekit): create inbound trunks based on voice bridge number
* fix(livekit): clean trunks and dispatch rules on restarts
* fix(livekit): attach room metadata to inbound trunks and dispatch rules
* fix(livekit): link dispatch rules to respective inbound trunks
* fix(livekit): expose inbound trunks and dispatch rules configs
* fix: restart loop on boot due to early requests
* fix(livekit): guarantee uniqueness of "external" LK users
=> [3.1] build(bbb-webrtc-sfu): v2.18.0

bbb-webrtc-recorder.placeholder.sh
- See: https://github.com/bigbluebutton/bbb-webrtc-recorder/releases/tag/v0.9.0
- [build(bbb-webrtc-recorder): v0.9.0](a1269fd95df0a89cb231cad4cc0913620f3c3d01)
* feat: extend RPCs to support different recording adapters
* feat(livekit): initial support for recording LiveKit tracks (audio, video, screen)
* feat(livekit): implement RTP status change events
* feat: write capture stats to file
* feat(livekit): add writer-level stats
* feat(livekit): add extended Prometheus metrics for adapter/recorder stats
* feat: implement active_tracks Prom metric
* feat: implement in/out/invalid request metrics
* fix: failing jitterbuffer tests
* fix: startRecording did not reject unknown adapters
* fix: add graceful shutdown
* fix: retry Redis reconn if it drops
* fix(livekit): properly handle RTP read …
=> [3.1] build(bbb-webrtc-recorder): v0.9.0

bbb-webrtc-sfu.placeholder.sh
* [build(bbb-webrtc-sfu): v2.18.1](https://github.com/bigbluebutton/bigbluebutton/commit/c72077ba081be012bc0974222ed18e27b2724163) 
* chore(livekit): bbb-webrtc-recorder as the default recording adapter
None
=> [3.1] build(bbb-webrtc-sfu): v2.18.1

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ExternalVideoDAO.scala, bigbluebutton-html5/imports/ui/Types/meeting.ts, bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
- Adds a new `start` event.
- Updates the playback progress for viewers every time the player data is updated instead of just on `play` or `stop`. This guarantees strict synchronization.
Closes #23000
See the linked issue.
=> fix(html5/external-video): Make the player respect timestamp from URL

docs/build.sh, docs/docs/administration/customize.md, docs/docs/administration/install.md, docs/docs/development/dev-guide.md, docs/docs/new-features.md, docs/docs/support/faq.md, docs/docusaurus.config.js, docs/src/components/HomepageFeatures/index.tsx, docs/static/img/diagrams/BBB30arch.drawio
This is the first draft of the BigBlueButton 3.1 documentation.
Closes # none
Preparing for releasing the first iteration of BBB 3.1.
=> docs: First draft of 3.1 documentation

bbb-presentation-video.placeholder.sh
https://github.com/bigbluebutton/bbb-presentation-video/releases/tag/5.0.0-rc.1
=> build: Bump bbb-presentation-video to 5.0.0-rc.1

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
This PR adds support for quick poll questions/titles that do not include question marks.
Closes #22887
- Upload this file on prosentation
[test presentation.pdf](https://github.com/user-attachments/files/19874602/test.presentation.pdf)
- Navigate through slides to try quick polls.
[Screencast from 23-04-2025 16:10:37.webm](https://github.com/user-attachments/assets/adaa0a27-91ff-48c2-a6be-c4e7f0581650)
=> Refactor(html5): Add support for question without interrogation mark
