bigbluebutton/bigbluebutton

- bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx
Fix issue with user not being able to join the default selected breakout form the invitation modal when "Allow users to choose rooms" option is checked.
> fix: user can't join default selected breakout

- bigbluebutton-html5/client/main.tsx
- bigbluebutton-html5/imports/ui/components/components-data/graphqlToMiniMongoAdapterManager/component.tsx
- bigbluebutton-html5/imports/ui/components/components-data/meetingGrapQlMiniMongoAdapter/component.tsx
- bigbluebutton-html5/imports/ui/components/components-data/userGrapQlMiniMongoAdapter/component.tsx
- bigbluebutton-html5/imports/ui/components/components-data/voiceUserGraphQlMiniMongoAdapter/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/adapter.tsx
After the subscription component removal a few race condition started to happen on client, it was indentified to be client loading before the adapter sync finish.
> Fix: add a adapters manager to lock loading while data sync

- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/hooks/index.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/queries.ts
- Do not fetch user data of users who are not in webcam.
- Except when grid layout is active. In this situation we need to know about all users.
> fix(webcam): fetch user data of webcam users only

- bigbluebutton-html5/private/config/settings.yml
Increases the minimum version requirement for Safari browser on mobile and desktop.
Closes # none
@prlanzarin / @Arthurk12  reported that since Safari Mobile < 13.4 and Safari Desktop < 13.1 do not have access to the ResizeObserver API, some odd behaviours are observed in our client.
> chore: Bump requirement for safari versions

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
removes chat error when a message is sent
Closes #20142
> fix: Warning message character limit exceeded is still showing up after being sent

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
Forces the toolbar width to be the maximum available width, which is the width of the media area, on mobile devices. Also allow the toolbar to overflow with an horizontal scroll when the available width is not enough to display all of its contents.
> [2.7] fix(presentation): toolbar width on small screens

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-tools/noop-tool/component.ts
This PR adds a `No Operation` tool to fix the issue where the presenter retained drawing capabilities after losing presenter status in a whiteboard session. By assigning the `No Operation` tool to users without whiteboard access, it effectively nullifies any drawing actions. 
Closes #19985
> fix(whiteboard): Deactivate Drawing Tool On Access Change

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
- [fix(user-list): validate before getting element attribute](https://github.com/bigbluebutton/bigbluebutton/commit/41c58d2466a489f98d5f49ce0bc08c6bc692cedf) 
- Fixes a client crash
- Implements check for getAttribute type before calling it.
None
> fix(bbb-html5): validate before getting user-list element attribute

- bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
- [fix(poll): filter users array before processing](https://github.com/bigbluebutton/bigbluebutton/commit/8dad2db2e22720ac0a1ac1d17bc7b239cc8b50cd) 
- Fix a crash in the polls live result by filtering out undefined users.
This scenario might happen when getting user information by an id that
is not present in the current usernames list by some inconsistency
between the user's information from the users context and poll
votes/responses.
None
> fix(bbb-html5): filter poll users array before processing

- bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
- [fix(external-video): Youtube captions toggle](https://github.com/bigbluebutton/bigbluebutton/commit/eb29634a876a2a4d952a75dd01a1751b8af1802a) 
- Ensures setOption and unloadModule are functions before calling.
- Potentially fixes a crash caught in production logs
None
> fix(bbb-html5): potential crash in Youtube captions toggle

- bigbluebutton-html5/imports/ui/components/wake-lock/service.js
- [fix(wake-lock): correct parameter type for log code](https://github.com/bigbluebutton/bigbluebutton/commit/4e7d7dd45278dd36345e99f7d1125c45681af74b) 
- Previously, an object was incorrectly passed as the log code parameter.
- Fixes it by ensuring that a string is passed instead.
None
> fix(bbb-html5): correct parameter type for wake lock log codes

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(audio): minimize redundant audio exit toasts](https://github.com/bigbluebutton/bigbluebutton/commit/d658d81148da53a1695c09cac9e57710b55b8c95)
- Audio exit toasts are fired in some redundant situations, e.g.: when the
error help screen is render.
- Change the logic a bit so that it's only fired when the audio help modal
won't be shown, i.e.: when audio had successfully connected beforehand.
None
3.0 version of https://github.com/bigbluebutton/bigbluebutton/pull/20004
> fix(audio): minimize redundant audio exit toasts

- bigbluebutton-html5/imports/ui/components/emoji-rain/component.jsx
- bigbluebutton-html5/imports/ui/components/emoji-rain/service.js
- [fix(reactions): crash when interactionsButton coords are absent](https://github.com/bigbluebutton/bigbluebutton/commit/cfa013fdaafebc1aea6b80b6dc82473eb8823924) 
- The client may crash whenever a emoji rain animation is triggered, but
the interactions button element cannot be located. This happens because
the button coordinates are fetched without checking whether the element
exists.
- Get the coordinate fetching method to return null if the
interactionsButton element cannot be located, and ignore the emoji rain
action if that is the case. Whenever no valid coordinates are found, log
an warning so we can track this and figure out what's happening with the
button.
- Fix a few typos in the getInteractionsButtonCoordinates method.
None
3.0 version of
> fix(reactions): crash when interactionsButton coords are absent

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/component.tsx
- [fix(bbb-html5): crash on video-provider unmount](https://github.com/bigbluebutton/bigbluebutton/commit/eccb06369b06c68022eab41bb93fa13181e54054)
- There's a race condition that may cause a client crash whenever a
video-provider's unmount procedure is run, but its signalling websocket
is undefined. The WS's callback handlers are re-assigned without
checking for the socket's availability, causing an unhandled TypeError.
- The WS may be undefined in a couple of scenarios, e.g.: unmouting before
the socket was successfully set up, unmounting while a reconnect is in
place etc.
- Check whether the socket exists before accessing it in video-provider's
componentWillUnmount routine.
None
3.0 version of https://github.com/bigbluebutton/bigbluebutton/pull/20008
> fix(bbb-html5): crash on video-provider unmount

- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js
- [fix(bbb-html5): crash when stopping WebRTC peers](https://github.com/bigbluebutton/bigbluebutton/commit/85cdc7cc2ac818672130ec0e528d07cfc2745592) 
- There's a race condition that may cause a client crash whenever a
connectionstatechange callback is cleaned up in a peer without a
valid peer connection present in our custom RTCPeerConnection wrapper.
- Check for peerConnection availability in the WebRtcPeer wrapper before
trying to clean up its connectionstatechange callback.
None
3.0 version of https://github.com/bigbluebutton/bigbluebutton/pull/20009
> fix(bbb-html5): crash when stopping WebRTC peers

- bigbluebutton-html5/imports/ui/components/settings/service.js
Credits to @Arthurk12 
- [fix: add safeguards when returning user roles](https://github.com/bigbluebutton/bigbluebutton/commit/148c25e2cb5bad082b2c96570fddd509b26ace83)
- Fixes a potential client crash
None
3.0 version of https://github.com/bigbluebutton/bigbluebutton/pull/20013
> fix: add safeguards when returning user roles

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the presenter change re-starting the external video by removing the previous condition in charge of setting the value in which the video would play on component's mounting.
The 'playerCurrentTime' is updated by the DB and the DB does not recieve this value each second, this value is only used to do calculations on the videos actual current time and because of that this value should not be used to decide in which duration the video is at.
The value was set like that because of past experiences of the video skipping on start, I did some testing and it does't seem to occur anymore.
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/7726e272-f07c-4ec9-8724-76b9df732eb5
#20032
> Fix: External video re-starting when changing presenters

- bbb-graphql-middleware/internal/gql_actions/client.go
Apollo client expects to receive a `complete` message in order to consider a mutation finished.
This PR include this message following the `data` message.
> fix (graphql-middleware): After returning a Mutation data, it should send a `complete` message

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
Adjusts whiteboard cursor updates so it only sends data about users that have whiteboard access.
> fix: only send cursor updates of users with whiteboard access

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/queries.ts
- bigbluebutton-html5/imports/ui/components/screenreader-alert/queries.ts
Add name to welcome message query and unread chats subscription.
You should define a name for every GraphQL operation in your application. Doing so provides the following benefits:
- You clarify the purpose of each operation for both yourself and your teammates.
- You avoid unexpected errors when combining multiple operations in a single query document (an anonymous operation can only appear alone).
- You improve debugging output in both client and server code, helping you identify exactly which operation is causing issues.
(https://www.apollographql.com/docs/react/data/operation-best-practices/)
> refactor: add names to unnamed queries

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- build/packages-template/bbb-graphql-middleware/graphql.nginx
**Background**
The current GraphQL endpoint is set to `/v1/graphql`, a path originally chosen due to Hasura's usage. 
However, the BBB client now interacts with the GraphQL middleware rather than directly with Hasura.
**Proposed Changes**
This PR changes the GraphQL endpoint to `/graphql` without versioning, for the following reasons:
1. Middleware Alignment: Since the client accesses the GraphQL middleware instead of Hasura, changing the path clarifies that requests are directed to the middleware layer.
2. Future Versioning: The new path also leaves room for possible versioning of the middleware in the future.
> refactor (gql-middleware): Change Graphql endpoint to `/graphql`

- bigbluebutton-html5/client/main.tsx
- bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx
The ErrorBoundary component has a generic log message that is not overridable and will aggregate errors from different components. The ideal scenario is that log tags are configurable so that errors can be filtered in log post-processing.
- Add the logMetadata: { logCode, logMessage } prop to the ErrorBoundary component so that log tags are configurable. Default tags are maintained.
- Add specific log metadatas for the client startup error boundary (logCode: 'app_startup_crash') and the user connection error boundary (logCode: 'app_crash').
None
Catching application crashes in production.
> fix(bbb-html5): add specific logCodes for root error boundaries

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes a `ReferenceError` that occurs when changing slides in the viewer. The issue was caused by an undefined variable `effectiveZoom`, which affects the canvas position, resulting in incorrect display alignment for the viewers when the presenter switches slides.
before:
after:
> fix(whiteboard): Correct Viewer Canvas Position on Slide Change

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Changes enforceLayout join parameter value format so it matches other layout-related parameters
`custom`, `smart`, `presentationFocus`, `videoFocus`, `camerasOnly`, `presentationOnly`, `participantsAndChatOnly`
`CUSTOM_LAYOUT`, `SMART_LAYOUT`, `PRESENTATION_FOCUS`, `VIDEO_FOCUS`,`CAMERAS_ONLY`,`PRESENTATION_ONLY`, `PARTICIPANTS_AND_CHAT_ONLY`
> refactor: change enforceLayout to match defaultMeetingLayout format

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
Add optional chaining operator so an error does not occur in timer if currentUser is not available
> fix: optional chaining on isModerator

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes the bug in 2.7 where the zoom settings for slides during a live presentation were not properly reflected in the recording. Previously, zooming into a slide and then changing to another slide would show per slide zoom level during a live session, but in the recording, the zoom from the first slide was applied to all subsequent slides.
Closes #20139
> fix(whiteboard): Inconsistent Zoom Between Live Session And Recording

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
In the first implementation we made store precious data users to not handle the loading stage, It's causing a bug where the old data it's being shown in the use list instead of the new one.
> Remove: user list local state storing previous users list data

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Layouts.scala
On receiving `MeetingCreatedEvtMsg`, it used to be set on Meteor: https://github.com/bigbluebutton/bigbluebutton/blob/6ba4aad05a9668f4b084e43005b4a70e7a803c0c/bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js#L50
Now this part was removed and I'm moving this values to the backend.
> refactor (akka-apps): Set correct default values for Layout

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EndBreakoutRoomInternalMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/MakePresentationDownloadReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationConversionUpdatePubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresPresentationDAO.scala
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
Following the refactor to shift several responsibilities from Meteor to Akka-apps, this PR introduces the following changes:
1. Presentations imported from breakout rooms, such as whiteboard or shared notes, will now be inserted into the database sooner. This allows for better tracking of the presentation's progress.
3. Presentations with errors, like "No content to capture," will also be inserted into the database. This provides presenters with clear feedback on why a presentation may not be available in a given room.
Future idea: Improve the error reporting mechanism during content import. Currently, inserting a placeholder presentation with an error message is a temporary solution copied from Meteor. This approach should be refined for better error handling in the future.
> refactor (akka-apps): Show progress while importing whiteboard and sharedNotes from breakoutRoom

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
This PR updates the position and responsiveness of the `tldraw` toolbar to match the behavior observed in version 2.7. In version 2.7, the toolbar was vertically positioned on the right and transitioned to the bottom in a horizontal layout for smaller screen sizes. This update ensures that as users transition from version 2.7 to version 3.0, the toolbar's behavior and positioning remain consistent, reducing confusion.
> fix(whiteboard): Align 3.0 Whiteboard Toolbar Position with v2.7 Behavior

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/muteToggle.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
This pull request ensures that mutation calls for disabling away mode are only made when away mode is enabled.
Reduce workload on the server
> refactor: only send disable away mutation if user is away

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR disables the duplication shortcut key while drawing on the whiteboard. The fix prevents unexpected duplications during the drawing process, ensuring that users can draw uninterrupted without inadvertently triggering the duplication shortcut. This adjustment aligns the functionality with  the 2.0 version of tldraw.
Closes #20200
> fix(whiteboard): Disable Duplication Shortcut Key While Drawing

- bigbluebutton-html5/imports/ui/components/timer/panel/component.tsx
- bigbluebutton-html5/imports/ui/core/graphql/queries/timer.ts
Removes obsolete property `endedOn` and closes timer panel when feature is deactivated.
Closes #20259
> Fix: timer panel remains open when the feature is deactivated

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR fixes an issue where late joiners to a whiteboard session were unable to see shapes drawn on previous slides before they joined. With these changes, late joiners will now be able to see all annotations made on all slides prior to their arrival in the session.
> fix(whiteboard): Shapes Missing On Previous Slides For Late Joiners

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/TimerModel.scala
- bigbluebutton-html5/imports/ui/components/timer/indicator/component.tsx
- Adjusts default value for timer music
- Fix issue with timer indicator stopping when timer music is changed
Closes #20258
> fix: Timer stops updating if you select music

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
Do not display breakout settings when moving users
Closes #20266
> fix: Breakouts' settings incorrect when going to Manage users modal

- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts
- bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
- bigbluebutton-html5/imports/ui/components/common/menu/skeleton.tsx
- bigbluebutton-html5/imports/ui/components/common/menu/styles.js
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Adds loaders for dynamic menu items in the chat menu to avoid layout shift and fetchs data from core hooks to speed up the loading.
None
> fix(chat): add loaders for dynamic menu items

- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx
Adjusts userlist options dropdown useMemo dependency array so it does not display incorrect locale when language is changed.
Closes #20262
> fix: After locale change some menus show in the old locale

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/TimerModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/StartTimerReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/timer/SwitchTimerReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/TimerDAO.scala
- bbb-graphql-server/bbb_schema.sql
When the timer reaches the end, the `running` flag is set to `false`, but the `accumulated` time is not being reset correctly. This issue arises because the message indicating the end of the timer, which previously handled resetting the `accumulated` time, is no longer being sent.
Now `akka-apps` will check for this situation on the next "start" and reset it automatically.
Closes #20237
> fix (akka-apps): Timer not resetting `accumulated` value properly

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes two issues (1) it prevents the whiteboard disappearing when using the left arrow key at the start of the slides or the right arrow key at the end, and (2) it ensures that the event listener for slide navigation via arrow keys works without needing to click the presentation toolbar.
Closes #20278
> fix(whiteboard): Slide Navigation Crash and Event Listener Update

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
This PR ensures the tldraw camera remains within the bounds of the presentation slide, preventing the unwanted panning jitter behavior. It also disables the pan tool for non-presenters.
Closes #20242
> fix(whiteboard): Improve Camera Bounds Logic To Prevent Pan Jitter

- bigbluebutton-tests/playwright/layouts/layouts.js
- bigbluebutton-tests/playwright/layouts/layouts.spec.js
Fixes the layout tests by changing the test to use the closeAllNotifcations function instead of the waitAndClick.
> test: Fix layout tests

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes an error with the external video, where as soon as the user started and external video session, the video would skip forward, the amount of time the video would skip depends on the latency.
[Screencast from 2024-05-15 10-25-50.webm](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/3c538763-da1d-4437-8f5c-2a0d93cf72b8)
[Screencast from 2024-05-15 10-18-48.webm](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/dcf9f2a8-f1e1-48e9-a2cf-c0999fb718b6)
> Fix: external video skipping

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Port of #20121 to BBB 2.6
Tested (before/after) on a 2.6.18 server with FireFox 126 Nightly
---
WebRTC-based stats generation in the connection status modal is broken on Firefox >= 125. A broken type check coupled with a new partially implemented RTCIceTransport dictionary causes and undefined function call when fetching the selected candidate pair. Since that error is unhandled, collection breaks.
Correctly check for the getSelectedCandidatePair method availability in RTCIceTransport so that it skips to pair inference from getStats if necessary.
> [2.6] fix(audio): broken connection stats on Firefox >= 125

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-tools/noop-tool/component.ts
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
Previous versions of Tldraw's SDK were released under the permissive Apache-2.0 license.
However, on On December 20th, 2023, Tldraw announced a change in which only non-commercial uses of Tldraw are permitted without purchasing a commercial license.
This PR replaces the tldraw packages used by the client with the last 2.x pre-release version that remains licensed under Apache-2.0, i.e., v2.0.0-alpha.19.
The source code for the packages hosted on npm is available [here](https://github.com/bigbluebutton/tldraw).
> chore: Replace tldraw with @bigbluebutton/tldraw

- docs/docs/development/api.md
Note that the API parameters are case-sensitive in BigBlueButton.
Makes clear in the API docs that the parameters are case sensitive
> docs: Make clear in docs that parameters are case sensitive. 

- build/packages-template/bbb-record-core/bbb-record-core.logrotate
- build/packages-template/bbb-webrtc-sfu/bbb-webrtc-sfu.logrotate
Add date to archived log filename.
Better readability for system administrators.
> build: Update logrotate rule to add date extension to archived logs files

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/timer/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/chat-list-item/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-polls/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/component.tsx
This PR add styles on the list item styles, in order to show which tab is currently being used. (See example).
#18314
Before:
After:
> UI: Selected tab's style indicating active

- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
Adjusts current user subscription info to correctly display "show welcome message" option in chat dropdown
Closes #20342
> fix: "Show Welcome Message" button always disabled

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-tests/playwright/polling/polling.spec.js
This PR selects the "no operation tool" for users who don't have whiteboard access when `tldraw` mounts. This prevents these users from accessing the right-click menu, ensuring that only users with the appropriate permissions can interact with the whiteboard features.
Closes #20318
> fix(whiteboard): Disable Tldraw Menu For Users Without Whiteboard Access

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Adds error boundary for the whiteboard component, so whiteboard component errors don't break the whole client.
> refactor: add error boundary in whiteboard

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes an issue with the duplicate shape shortcut key where it was activating the browser bookmark. Now the shortcut key only duplicates the selected shape without activating bookmarks.
It also re-enables the shortcuts for selecting tools on the toolbar.
Closes #20288
> fix(whiteboard): Ensure duplicate shape shortcut does not trigger bookmark

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy
Dropping the GET url map for `insertDocument` as it's not supported
Closes # none
We don't support GET for insertDocument
> fix: only allow POST for insertDocument in UrlMappings.groovy

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy
> fix: only allow POST for insertDocument in UrlMappings.groovy [2.7]

- bbb-graphql-middleware/internal/hasura/conn/writer/writer.go
Introduces a new env var `BBB_GRAPHQL_MIDDLEWARE_DENIED_SUBSCRIPTIONS` that allow to block some subscriptions by informing the list of subscriptions `operationName` to ignore.
For instance, to block all streaming subscriptions set this param at `/etc/default/bbb-graphql-middleware`.
```
BBB_GRAPHQL_MIDDLEWARE_DENIED_SUBSCRIPTIONS=voiceUserStream,getCursorCoordinatesStream,getNotificationStream,annotationsStream,getEmojisToRain
```
_It will not be included on docs or as sample in `/etc/default/bbb-graphql-middleware` because it is a debugging var that might be changed or removed._
> feat (gql-middleware): Add env var to deny certain subscriptions

- bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go
- bbb-graphql-middleware/internal/common/types.go
- bbb-graphql-middleware/internal/hasura/conn/reader/reader.go
- bbb-graphql-middleware/internal/hasura/conn/writer/writer.go
- bbb-graphql-middleware/internal/msgpatch/jsonpatch.go
To generate a JsonPatch, it's essential to retain the previously received data for comparison with the new data. Currently, this data is stored in files.
To improve the middleware's performance, this PR adds an option to store the previous data in memory instead of files.
To enable this feature, you need to update `/etc/default/bbb-graphql-middleware` by adding one of the following lines:
- **Store in files (default)**
```
BBB_GRAPHQL_MIDDLEWARE_RAW_DATA_CACHE_STORAGE_MODE=file
```
- **Store in memory**
```
BBB_GRAPHQL_MIDDLEWARE_RAW_DATA_CACHE_STORAGE_MODE=memory
```
**Note:** This configuration option is intended for debugging purposes and may be changed or removed in the future. Therefore, it will not be documented or included as a sample in `/etc/default/bbb-graphql-middleware`.
> feat (gql-middleware): Add an env var to choose to store raw data cache in memory or file

- bigbluebutton-html5/imports/ui/core/hooks/createUseSubscription.ts
- bigbluebutton-html5/imports/ui/core/hooks/useDeduplicatedSubscription.ts
Change the logic of stop subscription to also includes the parameters changes and stop with the old parameters
> Fix: Make useDeduplicatedSubscription stop subscription with old parameters

- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/hooks/index.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/state.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/types.ts
Fixes a bug where the client stops all webcams when stopping a specific webcam.
None
> fix(webcam): stopping a specific webcam will actually stop all

- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/user-options-dropdown/component.tsx
Fix "create breakout rooms" options appearing in manage users dropdown when breakouts are active
> fix: create breakout rooms button in userlist dropdown

- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/user-status/component.tsx
This PR removes the code that limits the emojis to appear only when user has no raised hands on webcam item area.
#20419
> UI: Raise hand and emoji showing at the same time.

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR adds functionality for handling line shape handles in akka. This ensures that the correct line shape data is transmitted to viewers, with the handles attribute properly overwritten instead of merged.
Additionally, it includes frontend checks to prevent unnecessary updates based on the meta properties of shapes. (related to #20070)
Closes #20306,  #20340
> fix(whiteboard): Properly handle line shape handles in akka

- bigbluebutton-html5/imports/ui/components/notifications/component.tsx
- bigbluebutton-html5/imports/ui/components/notifications/queries.ts
This enhancement will allow the client to specify which notifications should be received, rather than the server sending all notifications regardless of whether the client uses them or not.
Improve performance
> fix: Only receive user join/leave and guest join notifications if enabled

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_caption_activeLocales.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_ref.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/queries.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/queries.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-provider-graphql/video-list/video-list-item/user-status/component.tsx
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
- bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
This PR introduces a change to store the user's `reactionEmoji` directly in the `user` table. This adjustment streamlines the process of fetching the current emoji, as it eliminates the need to compare the entire history of emojis to find the most recent one.
- Before: `user.reaction.reactionEmoji`
- Now: `user.reactionEmoji`
An Akka-apps routine is now in place to ensure that expired emojis are cleared from the `user` table. This makes the query more efficient since it no longer needs to filter out expired reactions.
This refactor is part of a series of improvements designed to make GraphQL queries faster and more efficient for the server.
> refactor: Simplifying ReactionEmoji Storage and Queries

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-shapes/poll/component.tsx
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-shapes/poll/poll-shape-migrations.ts
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-shapes/poll/poll-shape-props.ts
- bigbluebutton-html5/imports/ui/components/whiteboard/custom-shapes/poll/poll-shape-types.ts
- bigbluebutton-html5/imports/ui/components/whiteboard/service.js
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
- bigbluebutton-tests/playwright/core/elements.js
- bigbluebutton-tests/playwright/polling/poll.js
This PR introduces a new shape to the whiteboard for polls. Previously, the poll shape was a regular rectangle with text added to the label. With tldraw v19, we can now create new shapes that can be any React component. So, we've updated the poll shape to unify with the component displayed in the chat panel.
Before:
After:
#20371 
The new poll shape uses the same component as the chat published poll, ensuring a consistent look across both the whiteboard and the chat panel. This unification helps in maintaining visual consistency and improves the overall user experience.
> feat(whiteboard): Reuse poll result diagram as a whiteboard shape

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/live/component.tsx
As detected in the last dev-call, captions with languages other than English were not being displayed. This PR fixes it, now, any language the user chooses to see captions from, they will see it correctly.
> fix(html5): Fix captionLocale logic to fetch correct captions

- bbb-presentation-video.placeholder.sh
* https://github.com/bigbluebutton/bbb-presentation-video/pull/49 by @danielpetri1
**Full Changelog**: https://github.com/bigbluebutton/bbb-presentation-video/compare/4.0.4...5.0.0-beta.1
Note that despite BigBlueButton 3.0 being based on Ubuntu 22.04, the bbb-presentation-video package is still being built on Ubuntu 20.04. This is not an issue, the package remains compatible with the newer Ubuntu version.
> build: Update bbb-presentation-video to 5.0.0-beta.1 for Tldraw v2 shape support

- bigbluebutton-tests/playwright/presentation/presentation.spec.js
Removes the flaky flag for the test presentation snapshot, so it will run again on CI.
> test: adding test presentation snapshot to ci

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/ChangeUserBreakoutReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomUserDAO.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_breakoutRoom.yaml
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/queries.ts
- bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/queries.ts
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
- Add the following columns to the `breakoutRoom_user` table: `userJoinedSomeRoomAt`, `isLastAssignedRoom`, `isLastJoinedRoom`, `isUserCurrentlyInRoom`, and `showInvitation`. These additions will precompute the necessary data and flags, eliminating the need to generate them for each query. This change will reduce the load on the queries, especially those relying on PostgreSQL window functions, which were making the queries very resource-intensive.
- Fix the button  "Already in room" / "Ask to join" (that was using wrong condition)
- Fix invitation showing wrong pre-selected room (closes #20453)
- Fix problems when moving users to another room
> refactor: BreakoutRoom storage and handlers

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/layout/context.jsx
Adjusts layout checks so shared notes remain pinned if layout is changed
Closes #20450
Closes #20442
> fix: Pinned notes disappears when changing layout

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
This PR fixes the bug where the chat input would lose focus after sending messages. 
#20399
> Fix: Focus on text input is lost after sending the message

- build/packages-template/bbb-etherpad/build.sh
- build/packages-template/bbb-export-annotations/build.sh
- build/packages-template/bbb-html5/build.sh
- build/packages-template/bbb-pads/build.sh
- build/packages-template/bbb-record-core/build.sh
Port of #20347 to BBB 3.0+
… system
If the build system for packages has a umask of `0077`, cloned repositories will have no permissions for group and other. As the build scripts for some packages just copy from clone git repos, this will preserve the permissions in the package and prevent the following services from startup:
* `bbb-html5`
* `etherpad`
* `bbb-pads`
* `bbb-export-annotations`
* `bbb-rap-*`
This patch grants everyone read permissions to the code in the packages.
> build(fix): File permissions in packages should not depend on umask of build… [3.0]

- bigbluebutton-html5/imports/utils/debounce.js
Fixes the debounce function to work properly when leading is true by adding a condition to reset and reschedule the timeout whenever a subsequent call happens whithin the delay timeframe.
Closes #20509
> fix(debounce): reset timeout when leading is true

- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml
- bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
This PR refactors the userlist ordering and improves database indexing. Key changes include:
- Ensuring the presenter is always placed at the top of the userlist (currently presenter is like a normal user in the ordering when multi-whiteboard is enabled).
- Ignoring emojis when sorting names.
- Adding `registeredOn` as a sort column above `userId` for cases where two or more users have the same name.
- Updating the database index to align with the client's sorting criteria.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
> fix: Refactor Userlist Ordering

- bbb-graphql-server/bbb_schema.sql
When a user leaves the meeting, they receive the status `clientNotResponding` after a few seconds, which is then displayed in the connection report:
The correct behavior should not treat users who left the meeting as having a connection problem.
Addresses one issue of #20486
> fix (gql-server): not treat users who left the meeting as having a connection problem

- docs/docs/administration/customize.md
Adjusts default value for bbb_display_branding_area parameter in docs
https://github.com/bigbluebutton/bigbluebutton/commit/da8075e2ede5989b163643f2ed0b16de231ff15c
> docs(fix): incorrect default value for bbb_display_branding_area in docs

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR restores the functionality of activating the pan tool when the spacebar is pressed and reverting to the previously selected tool when the spacebar is released.
The ability to switch to the pan tool using the spacebar is a common and expected behavior in many graphic and design applications. Restoring this functionality improves the user experience by making the whiteboard toolset more intuitive
> fix(whiteboard): Restore pan tool activation via spacebar

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx
adjusts presentation toolbar font color
Closes #20524
> fix: Font color inconsistent in whiteboard toolbar

- docs/docs/greenlight/v3/migration.md
See https://github.com/bigbluebutton/greenlight/issues/5849.
> docs(GL): correct statements about presentations not being migrated and how to fix entity too large errors

- bbb-graphql-middleware/internal/websrv/connhandler.go
Avoid sending msg `UserGraphqlConnectionClosedSysMsg` to akka-apps when it didn't send the `UserGraphqlConnectionEstablishedSysMsg` previously.
> refactor (gql-middleware): Avoid sending msg GraphqlConnectionClosed when unnecessary

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
The first implementation was considering when server is down, but after a few field test was noticed a issue when a network was down causing the issue of the client not being notified about it, it happens because our network layer (graphql-ws) doesn't automatic notify connection issues, we should make it manually
> Change: improve connection status to work when network is down

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserVoiceDAO.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_voice_activity.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Currently, updating user `muted` and `talking` statuses involves multiple subscriptions, causing each subscription to update whenever any user talks. This redundancy increases latency and data traffic.
To address this, we will:
1. Use stream subscriptions to consume `muted` and `talking` data, reducing update latency.
2. Detach `muted` and `talking` properties from multiple subscriptions, centralizing them into a single subscription.
@JoVictorNunes will develop a specialized hook to provide `whoIsTalking` and `whoIsUnmuted` data, removing this information from other subscriptions.
This PR introduces:
- A new PostgreSQL view.
- A new GraphQL type.
These additions will help João implement the centralized hook and reduce data traffic for the GraphQL server.
```gql
subscription { …
```
> refactor: Introduce a new Graphql type to consume user `muted` and `talking` statuses

- build/packages-template/bbb-graphql-middleware/bbb-graphql-middleware.service
- build/packages-template/bbb-graphql-server/bbb-graphql-server.service
This PR increases the maximum allowed number of open files, to fix issues like this: `Network.Socket.accept: resource exhausted (Too many open files)`
> refactor (gql-server): Increase maximum allowed number of open files

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
Change the userlist to keep the first page always loaded, it makes the client looks loading fasters and also allows a better naviagation
> refactor(perf): make user list always load first userlist page

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/live/component.tsx
This PR fixes the bug where the name initial would overlap the user's avatar.
#20529
> Fix: Avatar is transparent in cc

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/styles.ts
This PR fixes the arrow in the 'mute' button.
> Fix: Wrong position of audio arrow

- bigbluebutton-html5/imports/ui/components/app/component.jsx
This PR fixes the issue where the notifications regarding the user status/reactions would show the translation id instead of the proper message.
#20539
> Fix: Null label for emoji setting toast

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR restores the cut, copy, and paste functionality on the whiteboard via keyboard shortcuts.
The shortcut keys for cut (Ctrl+X), copy (Ctrl+C), and paste (Ctrl+V) were not working.
> fix(whiteboard): Restore cut, copy and paste functionality via keyboard

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/ParticipantJoinRecordEvent.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/UserJoinedMeetingEvtMsgBuilder.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/MeetingsManagerActor.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/ToAkkaAppsSendersTrait.scala
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
Adds the user custom data parameters than can be optionally sent with `join` calls to the `events.xml`. The user custom data map is converted into a JSON string and then embedded in a new `userCustomData` tag in `ParticipantJoinEvent` events.
For example, if the custom user data passed in the `join` call is `userdata-test123=456` and `userdata-test789=123` then the corresponding `ParticipantJoinEvent` would look like:
```
<event timestamp="18755143" module="PARTICIPANT" eventname="ParticipantJoinEvent">
<name>User 2073172</name>
<role>VIEWER</role>
<date>2024-06-21T18:25:24.172Z</date>
<externalUserId>w_7fn2vrv6r74c</externalUserId>
<userId>w_7fn2vrv6r74c</userId>
<userdata>{"test789":"123","test123":"456"}</userdata>
<timestampUTC>1718994324172</timestampUTC>
</event>
```
Alternatively, …
> feat(events): Add user custom data to events.xml

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/styles.ts
This PR fixes the bug where the emoji in the webcam would trigger elements rearrangement.
#20538 
[341111925-91bc0d2a-2f15-4ce4-901e-433d3b651964.webm](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/9841057a-0e41-4bd8-a6db-bf57184a86e0)
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/3f0c7fbb-5b0f-4169-9e24-a1dcbf54fa74
> Fix: Webcam display of emoji can trigger elements rearrangement

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/container.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/hooks/useMuteMicrophone.ts
- bigbluebutton-html5/imports/ui/components/audio/container.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/container.tsx
- bigbluebutton-html5/imports/ui/core/hooks/useTalkingUsers.ts
- bigbluebutton-html5/imports/ui/core/hooks/useVoiceActivity.ts
- bigbluebutton-html5/imports/ui/core/hooks/useWhoIsTalking.ts
- bigbluebutton-html5/imports/ui/core/hooks/useWhoIsUnmuted.ts
This PR includes fixes and improvements for the changes introduced in https://github.com/bigbluebutton/bigbluebutton/pull/20568.
- Use mapping object instead of `Set`.
- Call `setTimeout` only when the state update is invoked.
- `useVoiceActivity` no longer stores it own state. It leaves the duty of managing muted users to the callers.
- Improve talking indicator sorting.
- Improve timeout handling by splitting the registry into `spokeTimeoutRegistry` and `mutedTimeoutRegistry`. That way, we have more fine-grained control over timeouts.
None
> fix: improve the hooks of voice activity

- bigbluebutton-html5/imports/ui/core/hooks/useDeduplicatedSubscription.ts
It tweaks the `useDeduplicatedSubscription` hook to handle the `skip` option properly by doing the cleanup when the option is `true`. That fixes a bug where the grid layout is not being activated if the user is already sharing webcam before grid layout activation.
Closes none
Related to https://github.com/bigbluebutton/bigbluebutton/pull/20447.
> fix(webcam): grid layout not activating in some cases

- bigbluebutton-web/bbb-web.nginx
- build/packages-template/bbb-html5/bbb-html5.nginx
Currently, the RTT measurement relies on responses from `gql-middleware` and `gql-actions`. This dependency can cause delays on the server side, which may result in a high RTT. Users might mistakenly think the issue lies with their connection when it's actually a server-side problem.
To accurately measure RTT and diagnose client connection issues, it's better to have an endpoint that isn't affected by any application delays. 
This PR introduces a new endpoint at `/bigbluebutton/ping` in Nginx. The endpoint will simply return `200 ""`, allowing us to measure RTT solely based on the server network without any influence from application-level delays.
> nginx/html5: Introduce endpoint `/bigbluebutton/ping` for RTT calc

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/DatabaseConnection.scala
- bbb-graphql-middleware/internal/gql_actions/client.go
This logs will be useful for analysis of @TiagoJacobs .
- Add a log to `akka-apps` to inform how long each batch took to exec:
```
9 actions executed in the database in 11.877587 ms
```
- Add a TRACE log to `gql-middleware` to inform how long each request to `gql-actions` took to finish:
```json
{"_routine":"GraphqlActionsClient","browserConnectionId":"BC0000000081","duration":"10 ms","funcName":"userSetConnectionAlive","inputs":{"networkRttInMs":5.300000000745058},"level":"info","msg":"Executed!","statusCode":200,"time":"2024-06-30T14:07:38-03:00"}
```
- Add an INFO log to `gql-middleware` to inform how long slow requests to `gql-actions` took to finish:
```json
{"_routine":"GraphqlActionsClient","browserConnectionId":"BC0000000081","duration":"150 …
```
> refactor: Add TRACE logs for graphql-actions

- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
Removes recording indicator label in phones
Join a meeting with recording enabled on a phone
> fix: remove recording indicator label in phone

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
This PR adds extra condition to make sure presentation is indeed rendered before showing buttons.
#20610 
https://github.com/bigbluebutton/bigbluebutton/assets/36093456/fac892ac-27e9-4ae5-a67f-34d25aa42893
> Fix: Whiteboard options button should not appear without the presentation

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx
- bigbluebutton-html5/imports/ui/core/adapters/voice-activity.tsx
- bigbluebutton-html5/imports/ui/core/hooks/useTalkingUsers.ts
- bigbluebutton-html5/imports/ui/core/hooks/useVoiceActivity.ts
- bigbluebutton-html5/imports/ui/core/hooks/useWhoIsTalking.ts
- bigbluebutton-html5/imports/ui/core/hooks/useWhoIsUnmuted.ts
Adds a voice activity adapter in order to make just one `VoiceActivity` subscription. That adapter will dispatch stream data to the hook state of `useWhoIsTalking`, `useWhoIsUnmuted` and `useTalkingUsers`. Those hooks will consolidate the stream data and make it available through one single `makeVar`, making the state shared across all hook calls.
The subscription will start if at least one of these hooks is being called. If none of these hooks is being called the subscription will stop.
The hook state will be cleared when the hook is not being called.
None
Currently the client doesn't support deduplicated streams, so we need a way of consolidating the data we want in order to avoid making several subscriptions.
> refactor: add voice activity adapter

- bbb-graphql-middleware/internal/gql_actions/client.go
- bbb-graphql-middleware/internal/hasura/conn/reader/reader.go
- bbb-graphql-middleware/internal/hasura/conn/writer/writer.go
- bbb-graphql-middleware/internal/websrv/reader/reader.go
- bbb-graphql-middleware/internal/websrv/rediscli.go
- It also trim the input names before sending to Graphql-actions
> fix: Graphql Middleware logging bytes

- bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/Feedback.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Aiming to remove all Meteor dependencies, we need to remove the current `/html5client/feedback` endpoint.
So this feedback handler will be moved to BBB-WEB.
The new URL will be  `/bigbluebutton/api/feedback`.
It has a different validation once the user's session will be removed before he sends the feedback. So it will check the removed sessions to validate the user.
Necessary for #20625.
[Screencast from 2024-07-03 10-09-15.webm](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/0bb9f376-e862-40e9-afb5-dff2aeec2642)
> refactor (bbb-web): Introduces `/api/feedback` endpoint (to replace Meteor `/html5client/feedback`)

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
This PR fixes the breakout room message so it matches the 2.7 version.
> Fix: Message to all style not matching 2.7

- build/packages-template/bbb-graphql-server/after-install.sh
This PR fixes an issue where the `/usr/share/bbb-graphql-server/config.yaml` does not update correctly after a package update.
When some Hasura default config is changed, during a package update the file `/etc/default/bbb-graphql-server` is overwritten, resetting the `HASURA_GRAPHQL_ADMIN_SECRET` to `bigbluebutton`. 
A new random password is then generated for security.
The issue arises when `/usr/share/bbb-graphql-server/config.yaml` does not reset and thus doesn't receive the new password, causing a mismatch.
- Ensure `/usr/share/bbb-graphql-server/config.yaml` updates with the new password.
- Print the new password message only after generation (not always as before).
> fix (build/gql-server): Hasura trying to apply metadata using wrong password

- bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx
Fix a small issue introduced in the PR #20630, that was showing two messages at same time on the notification bar
> Fix: showing two message at same time on notification bar

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/MakePresentationDownloadReqMsgHdlr.scala
Adjusts permission for download presentation to check for presenter status instead of moderator role.
Closes #20029
1. Create conference
2. Join as moderator
3. Join as guest
4. Give the presenter rights to guest 
5. Upload presentation as guest
6. Enable download of the presentation
7. Try to download the presentation
**before:** presentation download link is empty and does not work
**after:** presentation download link works
> fix: Enable download of the presentation not possible for temporarily presenters

- bbb-graphql-middleware/internal/common/types.go
- bbb-graphql-middleware/internal/gql_actions/client.go
- bbb-graphql-middleware/internal/hasura/client.go
- bbb-graphql-middleware/internal/hasura/conn/reader/reader.go
- bbb-graphql-middleware/internal/hasura/conn/writer/writer.go
- bbb-graphql-middleware/internal/hasura/retransmiter/retransmiter.go
- bbb-graphql-middleware/internal/websrv/connhandler.go
- bbb-graphql-middleware/internal/websrv/reader/reader.go
- bbb-graphql-middleware/internal/websrv/writer/writer.go
1. **Remove `fromBrowserToHasuraConnectionEstablishingChannel`:**
- **Previous Setup:** 
- `fromBrowserToHasura` worked in parallel with `fromBrowserToHasuraConnectionEstablishingChannel`.
- `fromBrowserToHasuraConnectionEstablishingChannel` was only needed until receiving the `connection_init` message, after which it was closed.
- **New Setup:** 
- The code now first receives `connection_init`.
- After `connection_init`, it initializes the routine to consume subsequent messages.
- This removes the need for two separate channels. The initial routine handles messages until `connection_init`, then stops reading, while the subsequent routine handles messages from that point onward.
2. **Remove Routine Waiting for All Mutations to Finish Before Closing Hasura Connection:**
- **Previous …
> refactor (gql-middlware): Refactored code to simplify channel handling and remove unnecessary routines

- bigbluebutton-html5/imports/ui/components/video-provider/service.js
fix grid mode displaying viewers when "See other viewers in the Users list" is locked
Closes #20569
1. Create a room
2. Click on three dots in the upper right corner
3. Click on "Choose Layout"
4. Select 'Grid layout'
5. Click on 'Update'
6. Click on 'Gear' Icon next to 'Users' in left bar.
7. Click on 'lock viewers'
8. Set 'See other Viewers webcams' to 'locked'
9. Set 'See other viewers in the Users list' to 'locked'
10. Open the room in two other browser incognito tabs and log in with usernames 'participant 1' and 'participant 2'
11. Set the video mode to 'Grid layout' in the participant tabs as welll (steps 2-5 above!)
**before**: viewers see other viewers' in cameras area
**after**: viewers should only see moderators tiles
> fix: Layout VIDEO_FOCUS shows empty tiles for other participants when see other viewers is locked

- bigbluebutton-html5/imports/ui/core/hooks/useTalkingUsers.ts
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Fixes talking indicator getting stuck when the user exits audio while he's talking.
None
How to reproduce the bug:
1. Join audio.
2. Keep talking.
3. Exit audio.
4. See your talking indicator stuck on the navbar.
> fix: talking indicator getting stuck on audio exit

- bbb-graphql-middleware/internal/hasura/conn/writer/writer.go
- bbb-graphql-middleware/internal/hasura/retransmiter/retransmiter.go
When a user is promoted to mod or presenter, all the subscriptions are recreated to fetch it with refreshed permissions.
Gqlphql-middlware is not sending the cursor properly which cause an error and it stop receiving new data.
Error:
```
{
"type": "error",
"id": "f6f8a6ec-d30d-45f0-a044-635fc419197f",
"payload": [
{
"message": "not a valid graphql query",
"extensions": {
"path": "$.query",
"code": "validation-failed"
}
}
]
}
```
Reported by @antonbsa (also investigated by @JoVictorNunes )
> fix (gql-middlware): error when Retransmitting streaming subscription

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR updates the code for handling shortcuts to include support for Mac keys. It ensures proper handling of keyboard events for actions like undo, redo, and delete.
Some of the tldraw shortcuts were not working on Macs.
> fix(whiteboard): Update shortcut support for mac keys

- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR improves the zoom functionality on the whiteboard by modifying the wheel zoom behavior. It ensures that the zoom now follows the pointer location.
Previously, the zoom did not follow the pointer location. By updating the zoom functionality to center around the pointer, users can have more precise control over the zooming.
> fix(whiteboard): Focus wheel zoom towards mouse pointer

- bigbluebutton-html5/imports/ui/components/layout/layout-manager/camerasOnly.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationOnlyLayout.jsx
Fix sidebar content appearing in integration layouts
join a meeting with one of the integration layouts that should not display a sidebar (custom join parameter `enforceLayout=CAMERAS_ONLY` or `enforceLayout=PRESENTATION_ONLY`
media area is not using all available space
media area should use all available space
> fix: sidebar in integration layouts

- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
Do not display layout button in the three dots menu if layouts are disabled.
Closes #20667
Join a meeting with the custom parameter `disabledFeatures=layouts`
Manage layout option appears in the three dots menu
Manage layout does not appear in the three dots menu
> fix: Manage Layouts ignores disabledFeatures

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR increases the offset of the duplicated shape using Ctrl + d.
Pasting with Ctrl + v after copying with Ctrl + (c | x) will overlay on top of the existing shape instead of having it offset. This is the default behavior for tldraw.
> fix(whiteboard): Increase duplicated shape distance from original

- bbb-graphql-actions/deploy.sh
- bbb-graphql-actions/src/imports/validation.ts
- bbb-graphql-actions/src/index.ts
Return more useful information in the error messages of Graphql Actions.
Now it will show the `actionName` and the missing permission (`not moderator` for instance).
Example of the message logged in the browser console after some error:
Before:
```
ERROR: clientLogger: [Network error]: ApolloError: graphql actions request failed: Permission Denied.
```
After:
```
ERROR: clientLogger: [Network error]: ApolloError: graphql actions request failed: meetingEnd: Permission Denied (not moderator).
```
> refactor (gql-actions): Make error messages show more details

- bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Fixes a bug where the external video autoplay warning can be seen through the sidebar panel on mobile devices.
[Screencast from 09-07-2024 08:32:41.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/acfbe6f3-e703-4ec1-aba4-4f5a603f5117)
Closes #20654
> fix: external video can be seen through sidebar on mobile

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes an issue where pressing the delete key while editing text within a shape would inadvertently delete the entire shape. The update ensures that the delete key functions correctly by only removing the text as intended without deleting the shape.
Delete key was removing text shapes while editing when it shouldn't.
> fix(whiteboard) Delete key removing text shape while editing

- bigbluebutton-html5/imports/ui/components/connection-status/service.js
- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
Fixes the sorting of connection status reports. Sorting is carried out by `lastUnstableStatus`.
None, but fixes a crash when openning the connection status modal.
> fix(connection-status): user report sorting

- build/packages-template/bbb-graphql-server/after-install.sh
There are situations where the Hasura password is reset. In such cases, it is crucial to restart the Hasura service to ensure it recognizes and applies the new password. 
Without a restart, the service will fail to apply the metadata successfully, leading to an upgrade failure. 
This failure can also impact other services, such as GraphQL Middleware, preventing them from completing their own upgrades. 
This PR addresses this issue by restarting Hasura service when the package is upgraded.
> fix (build): Force to always restart Hasura service after package upgrade

- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/settings-loader/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/hooks/index.ts
- removes useMemo in record indicator component that had time as dependency
- removes unused and unique data from talking indicator useMemo
- removes useStreamUsers hook useMemo
increase client-side performance by removing useMemo from components that do not benefit from it
> refactor: reduce useMemo use

- bigbluebutton-html5/imports/ui/components/plugins-engine/loader/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/types.ts
This will make use of the integrity attribute present in script tags to prevent supply chain attacks if plugins are loaded from external domains. The checksum should be added as follows in the plugin config:
plugins:
- name: GenericComponentPlugin
url: https://lucas.elos.dev/plugins/GenericComponentPlugin.js
checksum: "sha384-6eedeb944134dfea9b0395bc4eb312c7b77747e7834e46b83e05becf19aad6f1"
...
If the file has changed on the server the javascript will not load in the client. The script tag supports many hashing functions, here's an exemple of how the checksum can be calculated:
openssl dgst -sha384 -binary GenericComponentPlugin.js | base64
If the plugin does not include the `checksum` setting the check is skipped and thus the default behavior for all plugins is not changed. This is an …
> feat(plugin): Verify plugin integrity with 'checksum' option

- .github/workflows/automated-tests-publish-results.yml
This PR adds the needed code for the publish results workflow to make a comment when the automated tests start to run. This will ease when the action has been re-ran - currently, the previous result comment is being kept.
As this workflow runs based on the pushed file in the default branch for security reasons, the changes here will only be noticed after its merge
> ci: Introduces "in progress" PR comment

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
- bigbluebutton-html5/public/locales/en.json
This PR fixes the missing button with which the moderator could invite user to breakout rooms
#19644
> Fix: [2.7] Breakout room invitation option missing from user dropdown

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Fix condition that would cause external video area to remain in place after the presenter ends sharing a video.
- Start sharing external video
- Stop sharing external video
- Presenter can't click "next slide" button
- Presenter is able to pass the slide by clicking "next slide" button
> fix: presenter could not change slide after external video

- .github/workflows/automated-tests-publish-results.yml
- .github/workflows/automated-tests.yml
- .github/workflows/check-merge-conflict.yml
We've noticed recently the `Merge conflict check` and `Automated tests - publish results` workflows not working properly when adding or deleting the bot comment. in the publish results workflow logs, I could see this error with status 403:
```
Error: Unhandled error: HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
```
looks like we are exceeding the API requests due to both actions running at the same moment (every time a commit is pushed and right after the automated tests workflow starts - which is triggered by pushing a commit).
Adding the [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency#overview) field can avoid this behavior ([see here](https://docs.github.com/en/rest/using-the-rest-api/best-practices-fo …
> chore: Avoid exceeding a secondary rate limit on workflows

- bigbluebutton-html5/imports/ui/components/layout/context.jsx
fix blank space in media area after sharing external video
Closes #20728
1. Join in a meeting with 2 users;
2. Share a video;
3. Stop sharing video;
4. As the presenter: `Actions button > manage presentations > delete all > confirm`;
> fix: Blank space when removing all presentations after sharing an external video

- bigbluebutton-html5/imports/ui/components/plugins-engine/ui-commands/handler.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/ui-commands/presentation/handler.tsx
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
What does this PR do?
Allows plugins to open and close the presentation area component via commands.
Needs https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/95
> feat(plugins): add open and close presentation area command support

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/FileTypeConstants.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/MimeTypeUtils.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedDocumentFilter.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedFileTypes.java
- bigbluebutton-html5/private/config/settings.yml
- docs/docs/development/api.md
It does a set of things related to file-type support:
- It removes support for `.odi` and `.odc`;
- It adds support for `.webp` files (even thought animated webp's aren't animated after the image processing in the back-end);
- It adds support for `.odg` files;
- It adds support for SVG files;
- It unifies file-type validation in the back-end document processing;
- It makes the list of supported file-types in the front-end equal to that of the back-end;
- And lastly, it adds a brief comment in the documentation pointing to the supported file-types.
Screenshot of the Doc comment down below:
Closes #20346 and #20092
- Build common-web;
- Run from source code bbb-web;
- Run html5 from source code as well;
- Now try to upload a .odi file, then a .odc file, see errors;
- Try to upload a .odg …
> fix(bbb-web and html5): removed .odi and .odc file-type supports

- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/deploy.sh
- bigbluebutton-html5/private/config/settings.yml
- build/packages-template/bbb-graphql-server/after-install.sh
A temporary user and view was created to allow Meteor perform user validation.
It is no longer used so this PR removes this part.
- Remove view `v_user_connection_auth`
- Remove user `bbb_frontend`
> remove (gql-server): Removes old postgresql user/tables created for Meteor auth

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/FileTypeConstants.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/MimeTypeUtils.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedDocumentFilter.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/SupportedFileTypes.java
- bigbluebutton-html5/private/config/settings.yml
- docs/docs/development/api.md
It does a set of things related to file-type support:
- It removes support for `.odi` and `.odc`;
- It adds support for `.webp` files (even thought animated webp's aren't animated after the image processing in the back-end);
- It adds support for `.odg` files;
- It adds support for SVG files;
- It unifies file-type validation in the back-end document processing;
- It makes the list of supported file-types in the front-end equal to that of the back-end;
- And lastly, it adds a brief comment in the documentation pointing to the supported file-types.
Screenshots of the Doc comment down below:
Closes #20346 and #20092
- Build common-web;
- Run from source code bbb-web;
- Run html5 from source code as well;
- Now try to upload a .odi file, then a .odc file, see errors;
- Try to upload a .odg …
> fix(bbb-web and html5): removed .odi and .odc file-type supports (back-port)

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Fix a case where the media area would get empty if all the presentations are removed while an external video is being shared.
1. Join in a meeting with 2 users;
2. Share external video;
4. As the presenter: `Actions button > manage presentations > delete all > confirm`;
5. Stop sharing external video;
> fix: Blank space when removing all presentations when external video is playing

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/BreakoutRoom2x.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.js
- bigbluebutton-html5/public/locales/en.json
Introduces two new parameters to the `CreateBreakoutRoomsCmdMsg` call that controls which presentations and which slides appear in the breakout rooms.
Closes #20626 
Provide the backend functionality for the client to build upon
When the client creates the breakout room, each of them can individually specify the new `allPages` and `presId` parameters.
- When `allPages` is true, the presentation in the breakout room contains all slides of the specified presentation. If false, it uses the current slide or the one that the presentation showed last.
- `presId` is the identifier of the desired presentation. If left blank, it defaults to the current presentation.
The parameters interact as follows:
| All pages | Presentation | Breakout room shows …
> feat: Pass a different presentation to each breakout

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/service.ts
fix crash on Firefox if speech synthesis is not enabled
Closes #20747
1. Set `media.webspeech.synth.enabled` to `false` in Firefox about:config
2. Join Session
> fix: Client crash on load when media.webspeech.synth.enabled = false

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/service.js
Confirmation popup was not showing when the user had joined audio, and also the mute function was not working, this PR fixes it
- Fix missing isMuted in Audio Service
- Fix muteMicrophone function not working on leave
- The `onbeforeunload` event was not receiving the updated muteMicrophone function, so the function was not working
1. Start a meeting with `askForConfirmationOnLeave` enabled
2. Join audio with microphone
3. Unmute own microphone
4. Try to close the tab/window
The confirmation dialog should appear and the microphone should be muted.
> fix: askForConfirmationOnLeave not working if user joined mic

- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
Hides presentation dropdown on breakout update modal if breakouts are active
Closes #20760
2. create breakout rooms (presentation dropdown should be visible for each breakout room
3. select "manage users" in breakout panel dropdown
4. presentation dropdown should not appear
> Breakouts - do not allow slide/presentation change on breakout update

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx
- bigbluebutton-html5/private/config/settings.yml
introduces allowDocsManagementInBreakouts property in settings.yml
Closes #20759
2. create breakout rooms
3. join a breakout room
4. if `allowDocsManagementInBreakouts: false` (default), the presenter should not see `Upload/Manage presentations` on the + button
> feat(config): introduce allowPresentationManagementInBreakouts to be able to block breakouts pres uploads

- bigbluebutton-html5/client/stylesheets/bbb-icons.css
> fix: restore timer icon

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
- bigbluebutton-html5/imports/ui/components/video-preview/service.js
- bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
- bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/context.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
- bigbluebutton-html5/imports/ui/services/virtual-background/index.js
- bigbluebutton-html5/imports/ui/services/virtual-background/service.js
- bigbluebutton-html5/imports/ui/services/webrtc-base/bbb-video-stream.js
This PR fixes two bugs in the video preview:
- Client dropping the virtual background when the webcam profile changes.
- If webcam is shared with virtual background applied, stopped, and then re-shared the video preview fails to apply the virtual background effect, causing a blank webcam.
Plus:
- Show the virtual background image provided by `webcamBackgroundURL` param in the virtual background selector.
`webcamBackgroundURL=https://content.r9cdn.net/rimg/dimg/63/30/85cee65b-city-46053-1673284fa31.jpg`:
> fix(webcam): client failing to apply virtual background effect

- bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
- bigbluebutton-html5/imports/ui/services/virtual-background/service.js
- Use StorageSingleton to correct save and restore webcam background. 
- Remove unused storage set.
Closes #20765
> fix(webcam): wrong VirtualBackground storage info

- bigbluebutton-html5/imports/ui/components/connection-status/service.js
Fixes connection status picking wrong status due to not considering config value format properly.
None
> fix(html5): connection status picking wrong status

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
fix issue with settings not being passed correctly to whiteboard component
https://github.com/user-attachments/assets/27711425-418c-4f00-bdc1-e3e0a7d52f72
https://github.com/user-attachments/assets/44385e67-dd35-4b6b-95b8-500a4058ba64
1. enable "Auto Hide Whiteboard Toolbars" in settings panel
2. move mouse cursor out of the presentation area
3. whiteboard toolbars should be hidden
> fix: auto hide whiteboard toolbars not working

- docs/docs/administration/cluster-proxy.md
Fixes the graphqlWebsocketUrl in the 3.0 cluster proxy setup documentation, by removing the /v1 from the URL.  The client won't load when the URL is entered as suggested by the present docs.
I noticed that https://github.com/bigbluebutton/bigbluebutton/pull/20647/files contains the same change, but the future of that PR is unclear to me.
Also I'm not sure how that https://github.com/bigbluebutton/bigbluebutton/pull/20664/files relates.
Furthermore, but not directly related: In my BBB 3.0 build with cluster proxy setup, in the browser console I still see CORS errors that I don't see in an equivalent 2.7 build or 3.0 without cluster proxy. I'm not sure what is missing, both GraphQL CORS options are set according to docs.
> docs: fix graphqlWebsocketUrl in cluster proxy setup docs

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala
Currently, a scheduler is configured to remove all meeting data 1 hour after a meeting ends. The issue arises when the akka-apps service is restarted, causing the scheduler to be lost. 
This PR introduces a routine that runs every minute to identify and purge old meetings that were not removed properly from the database.
> refactor (akka-apps): Routine to purge old meetings from Graphql database

- bigbluebutton-html5/client/stylesheets/bbb-icons.css
- bigbluebutton-html5/imports/ui/components/emoji-picker/component.jsx
The icon used for emoji picker was removed in 3.0 because it was the same as the deprecated reaction icons. However it's still present in the woff file and thus I've only restored the css style and brought the button back since we still need it.
Also I've added a small hack to fix the emoji picker width. A better fix would probably involve a rewrite of the code and should be done at some point.
> Fix emoji picker icon and width on 3.0

- bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
- bigbluebutton-html5/imports/ui/components/settings/service.js
1. fix issue where an invalid `index` locale is displayed in the "application language" dropdown
2. fix issue where the notification displayed after saving settings is always in the default locale
issue 1:
1. create / join a meeting
2. open the "options" menu (3-dots menu on top right of the client)
3. open application language dropdown
4. "index" value should not be displayed
issue 2:
1. create / join a meeting with the default locale (`en`)
2. open the "options" menu (3-dots menu on top right of the client)
3. open application language dropdown
4. select `Español - Spanish` 
5. save the changes (a notification should be displayed in **english** saying that the settings are saved)
6. repeat steps 2-3
7. select `Português - Portuguese`
8. save the changes (a notification should be …
> fix: locales issues

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/TimerModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
Previously, the Timer properties were only reset when a new timer was started. This caused inconsistencies in the GraphQL database as the values were not properly updated.
To address this, we have introduced a routine that runs every 5 seconds. This routine checks for finished timers and resets their values if they are found to be completed. This ensures that the database remains consistent and accurate.
> refactor (akka-apps): Routine to reset finished Timers

- bigbluebutton-html5/imports/ui/components/polling/styles.js
This PR improves accessibility for screen reader users by updating the polling question and options to use heading elements (`<h1>`). This makes it easier for users to find the poll using heading navigation shortcuts.
Issue #20621 pointed out that screen reader users had trouble finding the polling modal. We added headings so users can jump to the poll with screen reader shortcuts. The modal stays in the complementary landmark region, so users can also find it quickly using NVDA's d or JAWS' r keys, instead of moving it to the end of the DOM.
> fix: Improve screen reader accessibility for polling modal

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Removes unused validation logic for the deprecated `enter` endpoint in `bbb-web`.
In the case that an API requested failed validation this code would try to run but would not be able to since the `enter` endpoint was removed. This resulted in the requests returning back a `500 Internal Server Error` instead of the proper validation failure response.
> fix(api): Remove old enter endpoint validation logic

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/styles.ts
This PR fixes an issue where by double clicking the chat, the user would be unable to re-click it and resto focus on chat input.
> Fix: Unable to focus chat when double clicking it

- bigbluebutton-tests/playwright/notifications/notifications.js
- Adds assertions on `Notifications › Audio notifications` test to cover bug fixed by https://github.com/bigbluebutton/bigbluebutton/pull/20805
> test: Add checks for audio notification related to loss in connection

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
Fixes annotations overflowing the slide container in presentation snapshots, which adds a white margin. Some annotations gets lost.
> fix(presentation): presentation snapshot overflowing the slide

- bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
Ports #12712 changes to v3.0.x-release.
_With #12620 and #12692, the quick poll accepts up to 9 options, however the labeling of quick poll in the presentation tool bar still shows only A-G letters, such as "A/B/C/D/E/F/G/8/9". This patch fixes the problem._
> fix: Label of quick poll items up to 'I'

- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/styles.ts
When shared notes are pinned the button exhibits an improper black border, fixed it
> fix(sharedNotes): Fix pinned shared notes button border

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Sometimes, when sharing an YouTube video, the external video player starts at an advanced point, which harms the user experience. This happens when `currentTime` is between 0 and 1, making the player consider it as percentage. This PR truncates that value when it's less than `1`, making `0` the minimum value possible.
Partially closes (maybe) https://github.com/bigbluebutton/bigbluebutton/issues/19981 (not sure)
Closes (maybe) https://github.com/bigbluebutton/bigbluebutton/issues/19862 (not sure)
> fix(external-video): player starting at an advanced point

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/utils.js
This PR introduces calculations to estimate and apply the size of text shapes in `tldraw-v1` as users type. The implementation leverages a utility function, TextUtil, that calculates the dimensions of the text based on its content and style properties. This approach mirrors the functionality in tldraw v1, where similar calculations are handled internally. The key improvement is ensuring that text shapes always have a defined size, preventing issues where size attributes might be missing during the editing process.
The motivation for this PR is to address the issue where `tldraw-v1` did not dynamically apply a size to text shapes while typing. Previously, tldraw-v1 calculated the size of text shapes during the `onCommand` event, which occurs after typing is completed. This approach could …
> fix: Ensure size estimate is applied to text shapes while typing

- bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
Fixes wrong locale being sent to plugins with useUiData in some cases:
- If the user change the language and then refreshes the page, the plugins were still receving the original language locale.
> fix(plugin): current locale not being sent when client reloads

- bbb-export-annotations/workers/process.js
If ImageMagick fails to rasterize text for some reason so that it can be included in a PDF export, a corrupted image file was being generated that prevented subsequent shapes from appearing on the resulting PDF.
This PR proactively prevents the corrupted image file from being included in the SVG.
Closes #20690
I managed to reproduce the issue by adding very large amounts of text to the whiteboard (e.g., a 5000-word Lorem Ipsum).
In BBB 3.0, we do not rely on ImageMagick to embed text in the exported PDF. Hence, it is not necessary to port this PR.
> fix(bbb-export-annotations): Handle text rendering issue

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/imports/ui/components/meeting-ended/styles.ts
Adjusts size and position for the "send feedback" button
1. join a meeting with the parameter `userdata-bbb_ask_for_feedback_on_logout=true`
2. leave/end meeting
3. select any number of stars in feedback rating area
> fix: "send feedback" button styles

- bigbluebutton-tests/playwright/presentation/presentation.spec.js
- bigbluebutton-tests/playwright/screenshare/screenshare.spec.js
Skip the tests related to the external video because youtube says that the tests are bots.
Skipped tests:
* Start external video
* Start screen share stops external video
> test: skipping test yt related

- bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
Skips the test pin notes onto whiteboard, which will be updated. 
See issue #20892 for more information.
> test: Skip pin notes onto whiteboard to be updated

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/service.ts
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
Adds a flag `muteAudioOutputWhenAway` to control if output audio should be disabled when a user is in away mode (default: `false`).
Before this change, output audio is always muted when a user is away.
Feedback on #20076
> add config flag to mute audio output on away mode

- bigbluebutton-config/bin/bbb-conf
Warn when a file like `/etc/default/bbb-graphql-server.dpkg-dist` is detected.
Closes #none
When upgrading BBB 3.0 servers, frequently there are files kept during the installation.
Most often they are the config files for `bbb-graphql-server` and `bbb-graphql-middleware`.
**Note**: when upgrading a 3.0.0-alpha.7 server to 3.0.0-beta.1+ BBB server, such a configuration being withheld means that users cannot join the session, resulting in "error 300 something went wrong".
The most common problem is that we actually change the value for `HASURA_GRAPHQL_ADMIN_SECRET` in`/etc/default/bbb-graphql-server` but that means any newer `/etc/default/bbb-graphql-server` from packaging is put aside.
Sample run:
```
#
/etc/default/bbb-graphql-server.dpkg-dist
```
> config: Warn when .dpkg-dist files detected in /etc/default

- bigbluebutton-html5/package.json
- bigbluebutton-html5/webpack.config.js
This PR split the dev and prod configs in webpack, it was made to improve dx expirence, because the hmr was taking 30s to build, disabling the minifier made the hmr compiler 10x faster, but the minifier is essential for the prod code, so I splitted adding it only in prod config.
> Fix: Improve performance in webpack hmr and build

- bigbluebutton-html5/package.json
- [Restore](https://github.com/bigbluebutton/bigbluebutton/pull/20811/files#r1698682454) the `lint:file` npm script. Rationale outlined in
- https://github.com/bigbluebutton/bigbluebutton/pull/13870
> The lint:fix hook fixes/alters things. The lint run script runs eslint over the whole root directory.
> I just want to check linting offenses on a per-file/directory basis without having files messed with or needing a fancy IDE.
If there's an alternative in place that doesn't require a globally installed eslint, please let me know + close this.
> fix(html5): restore lint:file npm script

- build/packages-template/bbb-html5/build.sh
Closes # none
Related #20811 
In #20811 we removed the gzip commands from `build.sh` of `bbb-html5` package and the gzip flag from nginx. In https://github.com/bigbluebutton/bigbluebutton/pull/20899 we recovered the nginx portion and here we recover the gzip of the resources.
The client should load fine, fonts, styles etc should appear fine. Ensure you clear cache prior to testing.
The largest file `bundle.xxxxxxxxx.js` used to be 5.9MB, now is 1.4MB.
before:
after:
Comparable with the ~1.6MB BBB 2.7.12 client's JS bundle.
Credits to @prlanzarin for noting that we're removing it without cause in  #20811 and for following up with further analysis. I just tested locally and am sending the PR.
> build: revert removal of gzip command in bbb-html5/build.sh

- bigbluebutton-tests/playwright/audio/audio.spec.js
- bigbluebutton-tests/playwright/breakout/breakout.spec.js
- bigbluebutton-tests/playwright/chat/chat.spec.js
- bigbluebutton-tests/playwright/connectionFailure/connectionFailure.spec.js
- bigbluebutton-tests/playwright/presentation/presentation.spec.js
- bigbluebutton-tests/playwright/screenshare/screenshare.spec.js
- bigbluebutton-tests/playwright/user/user.spec.js
- bigbluebutton-tests/playwright/webcam/webcam.spec.js
- docs/docs/testing/release-testing.md
- Fixes links on `.spec` test files
- Adds the following tests of new features:
- disable self-view
- share camera as content
- use different presentation in breakout rooms
- prevent specific user from sending public chat messages
- reaction
- override default presentation on CREATE meeting API call
- set a webcam background by passing a url
- timer and stopwatch
- grid layout
- Updates the existing tests:
- enable/disable presentation download
- set status (removed)
- clear status (removed)
- raise / lower hand
- update everyone's layout
- all layout tests
> docs: Testing plan update (what's new features)

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
This PR fixes an issue where the user would click outside the emoji picker on chat, and it would not close.
https://github.com/user-attachments/assets/80974fa8-cc53-4b86-bc5a-a91dce891980
> Fix: Emoji picker not closing when clicking outside

- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/layout/context.jsx
- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
This PR restores the presentation to its previous state after sharing media.
Before:
After:
Presentation was always restored after sharing screen, sharing camera as content, sharing generic content or sharing external video.
> fix(presentation): restore last state after sharing media

- bigbluebutton-html5/imports/ui/components/plugins-engine/loader/manager.tsx
- [fix: use logger convention in plugin startup logs](https://github.com/bigbluebutton/bigbluebutton/commit/abd6f7fea1aefa0b1a97feafb82515951c7d4e5e) 
- The plugin loader startup logs aren't following the logger convention,
which makes them hard to work with when post-processing logs.
The appended error message is also not useful since we're logging a
Event variant raw (which either outputs {} or nonsense like { isTrusted:
etc }).
- Make the plugin "loaded" and "error" logs adhere to logger conventions.
In the future, the error log could use some tuning - there's no useful
info about root cause here.
None
Stumbled upon this when debugging a broken dev plugin.
> fix: use logger convention in plugin startup logs

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
This PR keeps the emoji on the user list and reaction button until it times out or user changes emoji/reaction.
#20817
> Fix: Even number of emoji clicks hide who the sender was

- bigbluebutton-tests/playwright/presentation/presentation.spec.js
Adds the flaky flag to the external video test, and the test will be updated.
> test: removing temporally external video test from ci

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
- bigbluebutton-html5/public/locales/en.json
this PR creates a history of rtt events with bad status, also modifies the interface to not show the connections status when the client isn't responding for user not misundertand the message (before user not responding was being shown with good status) also add a icon for status without a event, that doesn't generates a timestamp.
> Add: Local history of rtt status changes

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/MeetingDAO.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
- bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml
- bigbluebutton-html5/imports/ui/components/app/service.js
- bigbluebutton-html5/imports/ui/components/app/styles.js
- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx
- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/queries.ts
- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/service.ts
- bigbluebutton-html5/imports/ui/components/user-list/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
Port darklogo feature to 3.0
None
Providing a logo for the api, if you activate dark mode the colors of the logo will be inverted. If you provide a logo and a darklogo to the api, it will use the darklogo instead of inverting the logo colors.
> feat(darklogo): port customDarkLogo

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
Puts the right color for the default user avatar in chat when dark mode is enabled.
None
Before:
After:
> fix(darkmode): fix avatar username color in chat when dark mode is enabled

- bigbluebutton-html5/webpack.config.js
As reported by @lfzawacki , a request using method `HEAD` to the html5client server such as `curl -I http://localhost:3000/` crashes the application.
It's not so easy to fix. As a workaround I included a handler specific for HEAD requests that will stop the regular flow and return hard-coded headers, avoiding the app from crashing.
Once it is only used for development, I think it can solve for now.
And rather than using `curl -I http://localhost:3000/` to get the headers (HEAD method request).
It's possible to use `curl -i -r 0-0 http://localhost:3000` instead (GET method request, but filtering only the headers).
> fix (html5-dev-server): Prevent HEAD requests from crashing webpack-dev-server

- bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.js
Adjusts connection status modal padding
> style: adjust connection status modal padding

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
This is used by the upcoming custom feedback app together with the logoutURL functionality.
Here's an example of the logoutURL we'd configure in `bigbluebutton-web/grails-app/conf/bigbluebutton.properties`:
bigbluebutton.web.logoutURL=${bigbluebutton.web.serverURL}/feedback?meetingID=%%MEETINGID%%&userID=%%USERID%%
The `%%MEETINGID%%` and `%%USERID%%` parameters can be used as templates that will be substituted by the time the user is redirected after they leave the meeting. The currently implemented parameters are:
**%%MEETINGID%%** : The current meeting's internal meeting ID
**%%USERID%%** : The current user's internal user ID
**%%USERNAME%%** : The current user's name
These parameters might change or be updated in the future.
> feat(logout): Add option to send userId and meetingId to logoutURL

- bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/service.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(audio): prevent permission check loop in Safari](https://github.com/bigbluebutton/bigbluebutton/commit/1e53140a00dcb568ab50517aafa90815791ebe10) 
- Safari may enter a microphone permission check loop due to buggy behavior
in the Permissions API. When permission isn't permanently denied, gUM
requests fail with a NotAllowedError for a few seconds. During this time,
the permission state remains 'prompt' instead of transitioning to 'denied'
and back to 'prompt' after the timeout.
- This leads to an issue where, on retrying while in 'prompt' + blocked,
the client loops through gUM checks via: 
1) checking permission in the API,
2) receiving 'prompt', so trying gUM, 
3) gUM fails, 
4) returning to the modal and checking permission again because the API 
still says 'prompt' =)
- …
> fix(audio): prevent permission check loop in Safari

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetUserApiMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/service/UserInfoService.scala
- bbb-graphql-client-test/src/Auth.js
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_clientSettings.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_learningDashboard.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_guest.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_ref.yaml
- bbb-learning-dashboard/src/components/UserDetails/component.jsx
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts
- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/queries.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/service.js
- bigbluebutton-html5/imports/ui/core/graphql/queries/chatSubscription.ts
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
This PR refactors the `isOnline` flag to `currentlyInMeeting` to clarify its meaning, and renames the Hasura role `not_joined_bbb_client` to `bbb_client_not_in_meeting` for better accuracy.
The current GraphQL flag, `isOnline`, is used to indicate that a user has joined a meeting and has not yet left or been ejected. However, the term "isOnline" can be misleading, as it might be interpreted as the user's general internet connectivity status rather than their active presence in the meeting.
To avoid this ambiguity, the flag is being renamed to `currentlyInMeeting`, which more accurately describes its purpose: to indicate that a user is actively in the meeting.
Additionally, this PR updates the Hasura role naming conventions for better clarity:
- The role `not_joined_bbb_client`, which is …
> refactor (gql-server): Introduce flag `currentlyInMeeting` (replacing `isOnline`)

- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/RecordingFileSplitter.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
- akka-bbb-apps/src/universal/conf/application.conf
- [feat: adds option to split audio recording in multiple files by length](https://github.com/bigbluebutton/bigbluebutton/commit/4514649c4f9fb6d352675d5404cbd64b07395584) 
- FreeSWITCH sometimes drop frames in very long recordings generating
a raw file smaller than the total time recorded. The other issue is the
occasional drifting.
- This adds option to split audio recording in multiple files by
duration (minutes) to work around this problem in setups that are prone to it. 
**Disabled by default.**
None
> feat: add option to split audio recording in multiple files by duration

- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/universal/conf/application.conf
- [feat: make guest policy optional for dial-in in akka-apps](https://github.com/bigbluebutton/bigbluebutton/commit/dd1cf00dd25ba48e5c3a480115c77725b928ea33) 
- Dial-in endpoints currently follow the same guest approval process as regular
users. While this is correct for default installations, it complicates the join
procedure in setups where approval is managed externally, such as with pre-
configured conference PIN codes. Another relevant scenario is when call
origination is done from BBB, rather than as an inbound call.
- This commit makes the enforcement of the guest policy for dial-in/external
endpoints optional in akka-apps. **The default behavior remains unchanged
(enforce)**. This provides more flexibility for the dial-in mechanism, allowing
for smoother handling of the scenarios …
> feat: make guest policy configurable for dial-in endpoints

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
- bigbluebutton-html5/private/config/settings.yml
- docs/docs/administration/configuration-files.md
- [refactor: remove "server" target from bbb-html5's clientLog](https://github.com/bigbluebutton/bigbluebutton/commit/814204d5fdb9620328f9a0eb39f71c600de80f0b) 
- Support for clientLog's "server" target (Meteor) was removed in
https://github.com/bigbluebutton/bigbluebutton/commit/50d445f02640e997e8e590dcc32236f9279e1d52, but configuration and docs entries for it remained.
- There's no alternative for it, so I'm removing the leftover
configuration and doc entries.
- [refactor: remove server logger from bbb-html5's settings](https://github.com/bigbluebutton/bigbluebutton/commit/7a952586210d35c6811b365a32a8404e25f4c681) 
- Support for bbb-html5's server logger (Winston) was removed in
https://github.com/bigbluebutton/bigbluebutton/commit/50d445f02640e997e8e590dcc32236f9279e1d52, but …
> refactor: remove bbb-html5's server logger and client-to-server Meteor log target configs

- bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.15.0-beta.0](https://github.com/bigbluebutton/bigbluebutton/commit/c38f8aa41dedf425a9ec398a4299340e8d11e864) 
- feat: add restartIce support for video/screenshare modules
None
To be further contextualized with client side changes.
> build(bbb-webrtc-sfu): v2.15.0-beta.0

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/service.js
- [fix(connection-status): packet loss causes false positive critical alerts](https://github.com/bigbluebutton/bigbluebutton/pull/21049/commits/a306c239070429311aaa1ad468aad52e6d1f8764)
- In 3.0, the packet loss metric used to trigger connection status alerts was changed
to the one generated by the `startMonitoringNetwork` method used by the
connection status modal. Since packet loss thresholds were not adjusted (0.5,
0.1, 0.2), a single lost packet causes the status alert to be permanently
stuck on "critical". This is explained by how different those metrics
are:
- **Before (2.7):** A 5-probe wide calculation of inbound packet loss
fraction based on `packetsLost` and `packetsReceived` metrics.
- **Now (3.0):** An absolute counter of inbound lost packets.
- This commit restores the …
> fix(connection-status): packet loss causes false positive critical alerts

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/styles.ts
This PR fixes a big where the chat input area would dislocate from its position once the emoji window got open.
https://github.com/user-attachments/assets/9f66dec1-a1e2-4fb3-b362-3e6d3b191deb
https://github.com/user-attachments/assets/1c05ddb2-d20d-4603-bc71-f7aada70bb1c
> Fix: Emoji window dislocating chat input area

- .github/workflows/automated-tests.yml
Add `BBB_GRAPHQL_MIDDLEWARE_LOG_LEVEL=TRACE` for middleware during Automated tests
It will help to debug tests that are stuck in this screen:
> ci: Add loglevel=trace for middleware during Automated tests

- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
This PR introduces a small update to the logging format by appending the "ms" (milliseconds) suffix to the RTT (Round-Trip Time) values.
This change is intended to make the time unit explicit and improve log readability.
Open browser console and type RTT in the filter, the logs should show up.
> Client: Add ms suffix to RTT values in logs

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/muteToggle.tsx
This PR stops the push-to-talk shortcut from intercepting when the m key is pressed along with a modifier key (e.g., Alt or Ctrl).
related to #21032, where the push-to-talk functionality was triggering even when modifier keys were used with the m key.
> fix: Push to talk intercepting shortcut with modifier

- bigbluebutton-html5/client/main.tsx
What does this PR do?
Following thr PR https://github.com/bigbluebutton/bigbluebutton/pull/21043, this PR disable the react devtools in production
> Disable react devtools in prod

- build/packages-template/bbb-graphql-server/after-install.sh
Undo `chmod 700 /usr/share/bbb-graphql-server/` introduced in https://github.com/bigbluebutton/bigbluebutton/pull/20993 
It's necessary because the user `postgres` needs to read `/usr/share/bbb-graphql-server/bbb_schema.sql` from the directory.
> fix (gql-server): Remove strict permission of `bbb-graphql-server` directory

- docs/docs/new-features.md
- [docs: clarify transparentListenOnly::true behavior](https://github.com/bigbluebutton/bigbluebutton/commit/6647a982c1bacc1ef022ace4baaa2c969a674597) 
- The changes in https://github.com/bigbluebutton/bigbluebutton/pull/20782
do not mean that enabling `transparentListenOnly: true` sets `listenOnlyMode: false`.
I.e., the user prompt to choose between mic or listen-only still exists. Instead, it
allows users to seamlessly switch between modes without rejoining audio.
- While the goal is for `transparentListenOnly: true` to eventually imply `listenOnlyMode:
false`, the default audio activation behavior is still under review by the UI team, and
the current default remains unchanged.
- This commit updates the "What's New" documentation to reflect these points correctly.
None
Follow up to …
> docs: clarify transparentListenOnly::true behavior

- .github/workflows/automated-tests.yml
- build/packages-template/bbb-graphql-server/after-install.sh
Tests frequently fail at the `Install BBB` step, showing the error below. It is unclear whether the issue originates from the command `/usr/local/bin/hasura metadata apply --skip-update-check` or occurs in a subsequent step. 
To diagnose this, we propose setting a timeout for the `metadata apply` step and adding a confirmation message to verify that the script has reached its end.
> build/tests: Attempt to fix a random error during the tests

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
It fixes `setAway` mutation being sent three times due to providing two interaction listeners.
n/a
> fix: setAway mutation being sent three times

- bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/services/notification/index.js
- bigbluebutton-html5/imports/ui/services/notification/styles.js
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
Adds support for troubleshooting links for screenshare errors, similar to the troubleshooting links introduced for audio in [#20174](https://github.com/bigbluebutton/bigbluebutton/pull/20174). The troubleshooting links can be specified through settings option: `public.media.screenshareTroubleshootingLinks`, with links indexed by error codes they correspond to.
Adds default troubleshooting link for error 1136: [https://support.bigbluebutton.org/hc/en-us/articles/1500005316582-Share-my-screen#:~:text=Error%201136%3A%20Permission%20to%20capture,able%20to%20screen%20share%20again](https://support.bigbluebutton.org/hc/en-us/articles/1500005316582-Share-my-screen#:~:text=Error%201136%3A%20Permission%20to%20capture,able%20to%20screen%20share%20again)
Additionally, it changes the toast …
> feat(screenshare): add support for troubleshooting links

- bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx
This PR fixes a behavior  where the restore presentation button wouldn't work as expected due to the presentation being bellow the chat in grid layout.
#18966 
To test it, start a meeting and set it to grid layout, then minimize presentation, close the chat and finally - restore presentation.
> Fix: When in Grid Layout, presentation does not become visible on "Restore presentation" unless chat column is open

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts
Adjusts userlist and breakout creation modal so layout does not break if a participant joins with a long name
breakout creation modal:
userlist:
breakout creation modal:
userlist:
Closes #19900
1. Create a User with a long combination of first name and last name (e.g.: fridolin max winfried manfred joachim Mueller Meier Schmitz)
2. join with a user with short name
3. Check if the user avatar size in userlist is different for the user with a long name
4. Create new Breakout-Rooms under Settings
5. Assign the user to a room manually
6. Watch the assignment fields of each room change
> style: improve long username display in userlist and breakout creation

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserAwayReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserLockSettingsInMeetingCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserLockSettingsDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
- bbb-graphql-actions/src/actions/userSetUserLockSettings.ts
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_lockSettings.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Add `userLockSettings` to allow `disablePublicChat` for individual users
This PR introduces `userLockSettings`, which includes an option to set `disablePublicChat` for specific users, rather than only for all locked viewers as before. This implementation covers the backend and GraphQL portions; the frontend changes will be addressed in a separate PR. 
This is a port of #20585, originally implemented for version 2.7 using the old architecture with MongoDB.
- Mutation to set `user.userLockSettings.disablePubChat`:
```gql
mutation($disablePubChat: Boolean!, $userId: String!) {
userSetUserLockSettings(disablePubChat: $disablePubChat, userId: $userId)
}
```
- Subscription `user`
```gql
subscription {
user {
userId
userLockSettings {
disablePublicChat
}
}
}
```
- Subscription `user_current` …
> feat (port from 2.7): Add `userLockSettings` to allow `disablePublicChat` for individual users (backend portion only)

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/muteToggle.tsx
This PR reduces the cooldown for the push-to-talk feature to address instances where reactivating the microphone takes too long after the initial use.
During daily meetings, some users have reported experiencing delays when re-activating their microphones.
I don't believe the changes require testing, but testing the microphone re-activation time and suggesting more comfortable numbers could improve the overall user experience with this feature.
> Usability: Changing push to talk cooldown

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts
This PR fixes the border radius in system messages being different from one another.
I don't believe this needs real testing, just by observing the changes it is possible to see the changes.
> Fix: Border radius on system messages

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserAwayReqMsgHdlr.scala
- bbb-graphql-server/bbb_schema.sql
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-typing-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/component.tsx
- bigbluebutton-html5/imports/ui/core/graphql/mutations/userMutations.ts
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
- bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts
- bigbluebutton-html5/public/locales/en.json
Implements the frontend portion of #21117, allowing disablePublicChat for individual users and tweaks backend validation so the flag is ignored for moderators.
Closes #20825
1. join a meeting with a moderator and a viewer
2. moderator opens the userlist dropdown for the viewer and selects "lock public chat"
3. viewer public chat is locked
> feat (port from 2.7): Add userLockSettings to allow disablePublicChat for individual users (frontend portion)

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutHdlrHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/BreakoutRoomUserDAO.scala
Fix the flag `hasJoined` that indicates if the user has joined in a breakout room.
That was not being updated properly as reported by @JoVictorNunes.
```gql
subscription {
breakoutRoom {
userId
hasJoined
}
}
```
> fix (akka-apps): graphql flag `breakoutRoom.hasJoined` is not accurate

- bbb-libreoffice/docker/Dockerfile
Upgrades LibreOffice (used for presentation conversion) from 7.6.2 to 24.08.0.3.
(note that LO changed their versioning. We did not miss huge changes, just this is the release from August 2024)
Closes # none
Build PR: https://github.com/bigbluebutton/bigbluebutton-docker-libreoffice/pull/9
Related: #19045
We are debugging some conversion edge cases. We thought upgrading to the latest would be welcome.
I tested on 3.0.0-beta.1 via:
`/usr/bin/docker run bbb-soffice sh -c "/usr/bin/soffice --version"` -- check your current version. Expect 7.6.x
`docker pull bigbluebutton/bbb-libreoffice:24.08.0-20240909-132800` -- pull this version.
`docker image rm bbb-soffice:latest -f` -- remove the current LO image (just to be certain)
`docker image tag …
> build: Upgrade LibreOffice to 24.08.0.3

- record-and-playback/core/lib/recordandplayback/edl/audio.rb
The merge of 2.7 code into 3.0 dropped a change from d402f519c61adcc260ff20c978718dfddf509eca which was part of a fix to prevent a recording processing hang when processing deskshare streams which contain audio. Re-apply that change.
> Fix incorrect merge in recording audio processing

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/breakout-room-user-assignment/component.tsx
This PR adds sorting to breakout rooms similar to what happens in the user list.
#21031
To test this PR just enter the meeting with multiple users with different names, open the breakout room modal and check if the names in the boxes are sorted correctly by adding them both randomly and one by one to the rooms.
> Enhancement: Sort the list of names in breakout dialog similar to the Users list

- bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/hooks.ts
- bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/queries.ts
FIxes a bug where the audio does not reconnect automatically on breakout room exit. The main room relies on the `hasJoined` field of the `breakoutRoom` subscription to check when the user left the breakout room. However, that flag is `true` for some users, `false` for others (bug?). `isUserCurrentlyInRoom` seems to be a more consistent flag as of https://github.com/bigbluebutton/bigbluebutton/pull/20475.
Closes #21044
How to reproduce the bug:
1. Join a session with 8 users (1 moderator and 7 viewers, for example).
2. Join full audio on all of them and keep all unmuted.
3. Create breakout rooms and assign all users.
4. Join the breakout rooms for all users.
5. As moderator, end the breakout rooms.
6. See just a few users rejoin in main room audio, most of them fail to rejoin.
> fix(audio): Returning from breakout does not always rejoin you in main room audio

- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Delays push layout component render until meeting data is available
Closes #21138
1. Create and join a meeting;
2. Check the layout management modal (correct layout is selected)
3. Join another user;
4. Check the layout management modal (default layout should be selected)
The layout modal bug occurred because the push layout component was rendered before the meeting data was available.
> fix: No layout selected in modal for users other than presenter

- bigbluebutton-html5/imports/api/audio/client/bridge/base.js
- bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/button/container.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/service.js
- bigbluebutton-html5/imports/ui/components/screenshare/service.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- bigbluebutton-html5/imports/utils/stats.js
- bigbluebutton-html5/private/config/settings.yml
- [feat: add WebRTC stats information to client logs](https://github.com/bigbluebutton/bigbluebutton/commit/3c4e3de2869254cdc52d2434227a03476849cf7d) 
- We should be able to capture  WebRTC stats in some form for post-processing
so that it helps on debugging support requests (and other use cases, e.g.:
improving field trial analysis on test servers).
Although much of WebRTC stats information can be gathered via server side
components, none have logs as structured for proper post-processing as
the client logs - so we're going the client route for now.
- Capture WebRTC stats information for audio and screen sharing via:
- Audio logCodes: new `stats` extraInfo field
- `audio_joined`
- `audio_failure`
- `sfuaudio_error_retry_through_relay`
- `sfuaudio_error_try_to_reconnect`
- Screen share …
> feat: add WebRTC stats information to client logs

- bigbluebutton-html5/imports/ui/components/audio/audio-dial/component.jsx
this PR ads the # as trailing sign in dial in modal for conference pin
#20956
To test it you can either use dial in to join audio or disable the condition for the modal to appear making it visible and in doing so being able to see the trailing sign.
> Fix: Conference PIN (phone dial-in) doesn't show the needed pound sign in popup

- bigbluebutton-html5/imports/ui/components/audio/audio-dial/component.jsx
This PR is a port from the same fix on 27 version - [PR2113](https://github.com/bigbluebutton/bigbluebutton/pull/21113)
> Fix: Conference PIN (phone dial-in) doesn't show the needed pound sign in popup (port to 30)

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/styles.ts
This PR adjusts font size and add margin to offline user indicator
The motivation for this PR is to update the styles and ensure that the information display aligns with the overall design pattern of BBB's user interface.
As it is a visual change, I believe the screenshots will suffice, but in case one wants to test it anyway, you could open an instance of 30 and see the visual changes.
> Style: Adjust font size and add margin to offline user indicator (chat/message-header)

- bigbluebutton-html5/imports/ui/components/common/button/styles.js
This PR is simply an ease-in to the loading of buttons, due to the animations starting and ending too fast on low latency environments the user could be under the impression it was a visual bug.  This PR also will make the animation start after 500ms of clicking the button, making it smoother on lower latencies.
Doesn't close any issues but it's a reference to a change requested in PR [20918](https://github.com/bigbluebutton/bigbluebutton/pull/20918)
> Ease in loading anim

- bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js
- bigbluebutton-html5/imports/ui/components/components-data/users-context/adapter.jsx
- bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx
Fixes phantom user bug by changing the logic of the context action 'add_user_persistent_data' that was not correctly handling the transition of user roles. Some users were left with wrong logged out status because the context logic only updated its state when the added user was logged out.
Closes #20251
> fix(users-context): phantom user

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/modal/container.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/service.js
- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
- [fix: run full RTC stats collection only when necessary](https://github.com/bigbluebutton/bigbluebutton/commit/3e9e7e3e2b284fe55c418a36f980ea0a913a4892)
- In BBB 3.0, a change was made to collect full WebRTC stats continuously.
This method gathers stats from *all* peers and *all* senders and receivers
every 2 seconds. Originally, it was intended to run only when the user opened
the connection status dialog, providing in-depth info in the UI and making it
available for copying.
- This new behavior is not ideal. Running full stats collection every 2 seconds
in meetings with 20+ peers/transceivers wastes client resources since the
collected data is unused 99% of the time.
- This commit reverts to the pre-3.0 behavior (≤2.7), where full stats collection
(`startNetworkMonitoring`) runs only …
> fix: run full RTC stats collection only when necessary

- bbb-webrtc-sfu.placeholder.sh
- bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js
- bigbluebutton-html5/imports/ui/services/webrtc-base/peer.js
- bigbluebutton-html5/private/config/settings.yml
- [feat: add experimental support for ICE restart](https://github.com/bigbluebutton/bigbluebutton/commit/27d6bca5156c793f692d78d34171688f462bd609) 
- We currently use full renegotiation for audio, video, and screen sharing
reconnections, which involves re-creating transports and signaling channels
from scratch. While effective in some scenarios, this approach is slow and,
especially with outbound cameras and screen sharing, prone to failures.
- To counter that, WebRTC provides a mechanism to restart ICE without needing
to re-create the peer connection. This allows us to avoid full renegotiation
and bypass some server-side signaling limitations. Implementing ICE restart
should make outbound camera/screen sharing reconnections more reliable and
faster.
- This commit implements the ICE …
> feat: add experimental support for ICE restart

- bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- [fix: disable ICE restart for recvonly endpoints](https://github.com/bigbluebutton/bigbluebutton/commit/3a5c3df5382065ecffe6473c92c839991d7eacf0) 
- The experimental ICE restart introduced in commit https://github.com/bigbluebutton/bigbluebutton/commit/d2dde8a9b19a700ff427371d4122126cb28bda1d should only be
used for `sendonly` or `sendrecv` transports. There are two main reasons:
- Server-side changes are required to support `recvonly` endpoints,
particularly the proper handling of the server’s `setup` role in the
its SDPs during an ICE restart. These changes are too broad for now,
so they are deferred to future releases (SFU@v2.16/BBB@3.0).
- Full reconnections for `recvonly` endpoints are currently reliable,
unlike for `send*` endpoints. ICE restarts could still provide benefits
for …
> fix: disable ICE restart for recvonly endpoints

- freeswitch.placeholder.sh
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/21066 to BBB 2.7
> chore: upgrade FreeSWITCH to 1.10.12 (port)

- bbb-webrtc-sfu.placeholder.sh
v2.15.0
---
* feat: add restartIce support for video/screenshare modules
* refactor: rename ICE restart flag to `restartIce`, true by default
* build: pino@9.3.2
* build: config@3.3.12
* build: ws@8.18.0
* build: bufferutil@4.0.8
* build: mcs-js@0.0.20
* build: uuid@10.0.0
* build: mediasoup-client@3.7.16
* build: mediasoup@3.14.14
* build: SIP.js@v0.7.5.14
> [2.7] build(bbb-webrtc-sfu): v2.15.0

- bbb-webrtc-sfu.placeholder.sh
v2.15.0
---
* feat: add restartIce support for video/screenshare modules
* refactor: rename ICE restart flag to `restartIce`, true by default
* build: pino@9.3.2
* build: config@3.3.12
* build: ws@8.18.0
* build: bufferutil@4.0.8
* build: mcs-js@0.0.20
* build: uuid@10.0.0
* build: mediasoup-client@3.7.16
* build: mediasoup@3.14.14
* build: SIP.js@v0.7.5.14
> build(bbb-webrtc-sfu): v2.15.0

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
This PR Adds a new flag to settings that allows apollo dev tools to be enable in production build
> Add: Flag to enable apollo devtools in production

- bigbluebutton-html5/imports/ui/components/app/styles.js
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Clean up inverted css selectors passed to Dark Reader and add new ones for elements not correctly transformed to dark theme. These include the tldraw color picker, text shape color, selected color indicator, tool opacity slider, and camera dock background.
Comparsion:
Before and after:
> fix(dark-theme): adjust Dark Reader CSS selectors

- bbb-pads.placeholder.sh
Backport https://github.com/bigbluebutton/bigbluebutton/pull/21071 to BBB 2.7
> [2.7] build: Bump bbb-pads to 1.5.3

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
- Background shape can show white borders due to rounding erros in the tldraw canvas, change size and position of background shape to avoid it. 
- Disable tl container outline showing when in focus.
Before
After
> fix(whiteboard): background white borders

- bigbluebutton-tests/playwright/core/constants.js
- bigbluebutton-tests/playwright/layouts/layouts.spec.js
- bigbluebutton-tests/playwright/presentation/presentation.spec.js
- bigbluebutton-tests/playwright/user/timer.js
- bigbluebutton-tests/playwright/user/user.spec.js
- bigbluebutton-tests/playwright/whiteboard/whiteboard.spec.js
This PR changes the test flow in order to avoid false failures we've been facing recently. in addition, I've fixed the way we prevent the presentation notifications when we don't need to check them and they might cause difficulties in the assertions/snapshot comparisons
> test: Update timer test to avoid false failures + fix hide presentation param on unrelated tests

- bigbluebutton-html5/webpack.config.js
Implements a timeout for cache be stored in filesystem, using the property [maxAge](https://webpack.js.org/configuration/cache/#cachemaxage), i reduced it to one day (default is one month).
> html5: Set Cache Expiry to 24 Hours in Webpack Configuration

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR improves the whiteboard's performance by batching shape updates and persisting them only during idle or editing states, instead of on every action. This reduces the frequency of unnecessary updates being sent to the server.
In the previous version (2.7), updates were only sent after updates were completed, but in 3.0, updates are sent continuously during the drawing process. This PR restores the behavior of sending updates only after the user stops interacting with shapes, using `draw.idle`, `select.idle`, and `select.editing_shape` paths provided by the tldraw API.
> fix(whiteboard): Batch shape updates and persist on idle or editing states

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
Fix an issue where users that joined with `userdata-` params set was not being able to be banned.
This PR change the way the user is registered in akka-apps, 
Now it requires the prop `userCustomData` when creating a new user, because the function that populated `userCustomData` later was causing the issue.
Closes #21207
> fix (akka-apps): Banned users being able to rejoin (when they have customdata)

- bigbluebutton-tests/playwright/presentation/presentation.spec.js
Sets `Presentation › Manage › Upload single presentation` and `Presentation › Manage › Upload Other Presentations Format` tests as flaky aiming to avoid holding up PR merges.
I've confirmed that an expected notification is not displayed only for the presenter after uploading a presentation file:
- Presenter
- Viewer
> test: Add flaky flag on presentation test

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/component.tsx
Adjusts chat notification popup so it correctly displays user away message
1. join a meeting with 2 users
2. user A enables chat popup notifications
3. user A closes chat area
4. user B enters away mode
5. notification displayed for user A should contain a message "user B is away"
> fix: chat popup notification for user away does not contain information

- bigbluebutton-html5/imports/startup/client/logger/index.ts
- bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx
Adjusts BBBClientLogger to work with the new way to get client settings - logger streams were being created at export time (when client settings are not yet available).
issue reported by @antobinary + @prlanzarin 
1. start bigbluebutton with any `clientLog` settings other than the default ones
2. join a meeting
> fix: client logger streams being created at export time

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Since **camera as content** and **video preview** share the same UI component, `userdata-bbb_skip_video_preview=true` makes the same device be shared twice if the user shares webcam and then shares camera as content, and vice versa.
This PR adds an extra condition to ignore `userdata-bbb_skip_video_preview=true` and allow the user to select the device if the initial device is already shared.
Closes #21165
> fix(webcam): do not skip video preview if initial device is already shared

- bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/ui/components/video-provider/component.tsx
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/audio-broker.js
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/screenshare-broker.js
- bigbluebutton-html5/imports/ui/services/bbb-webrtc-sfu/sfu-base-broker.js
- bigbluebutton-html5/imports/ui/services/webrtc-base/peer.js
- bigbluebutton-html5/private/config/settings.yml
Ports https://github.com/bigbluebutton/bigbluebutton/pull/21008 and https://github.com/bigbluebutton/bigbluebutton/pull/21189 from 2.7 into 3.0.
- [feat: add experimental support for ICE restart](https://github.com/bigbluebutton/bigbluebutton/commit/a57f7cd0af0483decd01cd4f4b6eb7884a8ad738) 
- We currently use full renegotiation for audio, video, and screen sharing
reconnections, which involves re-creating transports and signaling channels
from scratch. While effective in some scenarios, this approach is slow and,
especially with outbound cameras and screen sharing, prone to failures.
- To counter that, WebRTC provides a mechanism to restart ICE without needing
to re-create the peer connection. This allows us to avoid full renegotiation
and bypass some server-side signaling limitations. …
> [3.0] feat: add experimental support for ICE restart

- bigbluebutton-html5/imports/ui/components/common/button/component.jsx
- bigbluebutton-html5/imports/ui/components/common/icon-svg/component.tsx
Fix issue with recording button icon not appearing on mobile devices due to it being wrapped in a div by default.
The bug was being caused by the new "icon svg" component implementation, that included a styled div that is used by some icons, but not all.
1. create a meeting with recording enabled
2. join the meeting on a mobile device
3. the recording button (and its icon) should be displayed
> fix: recording icon does not appear on mobile devices

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/muteToggle.tsx
This PR fixes an issue where the push to talk used in quick succession would bug the loading animation on mute/unmute button - 
making the loading animation last forever or until next activation of the button
https://github.com/user-attachments/assets/cb032085-ef2b-4095-830d-3bd70b43635c
https://github.com/user-attachments/assets/fd63ff0b-b162-4616-9c98-f0845318c831
> fix(audio/muteToggle): Fix mute loading state on push to talk

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
Polishes the logging of the _shouldRetry_ handler of the graphql client. It is logging the `TerminatedCloseEvent` as error. Instead log it as info.
n/a
Logging it as error can cause confusion, since it is not a fatal error.
See https://the-guild.dev/graphql/ws/docs/classes/client.TerminatedCloseEvent.
> fix(connection): tweak `shouldRetry` handler logging

- bigbluebutton-html5/imports/ui/components/common/modal/confirmation/component.jsx
adjusts confirmation modal props, so the secondary button has the correct styling.
focused
unfocused
focused
unfocused
1. join a meeting with recording enabled
2. click the recording indicator button to start/stop recording
3. check the "no" button styles
> style: adjust confirmation modal props

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/notify/component.tsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
addresses the following sonarcloud alerts:
- whiteboard: This function expects 3 arguments, but 4 were provided.
- chat message form: Unexpected empty object pattern.
- recording indicator: 'setIsOpen' PropType is defined but prop is never used
whiteboard, chat message form and recording indicator components should still work the same after these changes.
> refactor: sonarcloud alerts

- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_timer.yaml
- bigbluebutton-html5/imports/ui/components/timer/indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/timer/panel/component.tsx
- bigbluebutton-html5/imports/ui/core/graphql/queries/timer.ts
Fixes timer beep failing to play intermittently. This is due to the interval being cleaned up before it reaches `0`. This PR separates _updating the time_ and _playing the beep_ into different things. _Updating the time_ will keep as-is, each client updating its own local state. In order to know when to play the beep, this PR adds a new auto-generated server-side flag, `elapsed`, which becomes `true` when the timer reaches its endpoint. Clients will observe such flag to know when beeping.
Closes #21156
1. `cd ./bbb-graphql-server && ./deploy.sh`
2. Join a session with several users.
3. Start the timer.
4. When it reaches `0` it should always beep for all users.
> fix(timer): beep failing to play intermittently

- bigbluebutton-html5/imports/ui/components/settings/service.js
This PR removes unnecessary code regarding notifications and fixing some issues with them.
#21214 
To test this correction:
1. Start a meeting with 1 moderator and 1 viewer
2. Turn off the popup notifications for raised hands
3. Viewer raises hand (but not lowers)
4. Change settings again and turn them ON
5. See notification that wasn't there before
> refactor(settings/service): Refactor  to remove unnecessary  for notification.

- bbb-webrtc-sfu.placeholder.sh
v2.16.0
---
* feat(mediasoup): pipe mediasoup logs to webrtc-sfu's logger
- All piped logs have their `msg` field prefixed with `[SFU_MEDIASOUP]`.
The log pipe can be disabled via `mediasoup.pipeLogs` (bool).
* refactor(mediasoup): review log levels and metadata
> [3.0] build(bbb-webrtc-sfu): v2.16.0

- bbb-webrtc-sfu.placeholder.sh
v2.16.0
---
* feat(mediasoup): pipe mediasoup logs to webrtc-sfu's logger
- All piped logs have their `msg` field prefixed with `[SFU_MEDIASOUP]`.
The log pipe can be disabled via `mediasoup.pipeLogs` (bool).
* refactor(mediasoup): review log levels and metadata
> [2.7] build(bbb-webrtc-sfu): v2.16.0

- bigbluebutton-html5/imports/ui/components/app/styles.js
Refactor styles to update the background color of connection status bars so it does not become invisible in dark mode.
1. join a meeting with dark mode enabled
2. see connection status icon
> fix (styles): Update connection status bars background color

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/button/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/captions/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/service.ts
Refactors the label generation for audio captions in the audio-captions button and captions components. Instead of directly using the intl formatMessage function, the label is now generated using the intlMessages object and the getLocaleName function from the audio-captions service. This change prevents an issue with custom locales.
1. Add a new locale in `public.app.audioCaptions.language.available` settings
2. Join a meeting
3. Try to select a locale for transcription in the audio join modal
> fix(audio-captions): label generation for audio captions with custom locales

- bigbluebutton-html5/imports/ui/components/layout/observer.tsx
- bigbluebutton-html5/imports/ui/services/settings/index.js
This PR refactors a custom parameter/setting that was not persisting across page refreshes. It complements the changes introduced in PR [21255
](https://github.com/bigbluebutton/bigbluebutton/pull/21255).
#21260
1. Start a meeting using custom parameters: `bbb_prefer_dark_theme=true` or `bbb_show_animations_default=false`
2. Test one of the parameters above by trying to use animations or setting dark theme to off in the settings
3. See if they persist
> refactor/fix(settings): Refactor animation settings retrieval to fix problem with refreshing.

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/SendMessageToBreakoutRoomInternalMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageFromApiSysPubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GroupChats.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala
- bbb-graphql-actions/src/actions/chatSendMessage.ts
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_private.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_public.yaml
Aiming to enable the implementation of the feature Reply Chat Message, this PR introduces new fields to Graphql:
Mutation to reply:
```gql
mutation($chatId: String!, $chatMessageInMarkdownFormat: String!, $replyToMessageId: String) {
chatSendMessage(
chatId: $chatId, 
chatMessageInMarkdownFormat: $chatMessageInMarkdownFormat,
replyToMessageId: $replyToMessageId
)
}
```
- Subscription to bring the original message and its author:
```gql
subscription {
chat_message_public {
message
user {
name
}
replyToMessage {
message
user {
name
}
}
}
}
```
- New field to know the sequence of that message and them identify the page it lies (it will be useful when the user click on the quote and is redirected to the original message)
```gql
subscription {
chat_message_public {
message
messageSequence
}
} …
```
> gql-server: Add props to enable a user to Reply a chat message (backend portion)

- bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
- bigbluebutton-html5/imports/ui/components/connection-status/button/styles.js
- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/styles.ts
This PR re-sets some values to mobile, so the navbar is fully acessible all the time
Join BBB on your phone, and play around with navbar elements
> style(connection-status): Enhance mobile responsiveness for connection status and recording indicator components.

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
- bigbluebutton-html5/imports/ui/components/common/menu/styles.js
- Updates the raise hand button to to remove focus when raise hand is used.
- Updates the styles of the menu component to not display hover styles in mobile devices.
https://github.com/user-attachments/assets/9f45d858-5928-4bca-abc1-d9e760269736
Closes #21292
1. join a meeting on a mobile device
2. open reactions bar, select raise hand
3. select raise hand again
4. raise hand button should not be selected
> fix: raise hand remains selected on mobile devices

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
This PR addresses the issue where the GraphQL connection’s close events were triggering a terminal error. The terminal error was intended to be generated only when the connection is rejected due to reasons such as insufficient permissions or an invalid session, not from a close event. With this fix, the close event will now simply update the connection status to "disconnected" and emit a log. Terminal errors will only be triggered by reconnection failures, such as permission issues or exceeded retry attempts.
Closes #21147
Join a new meeting and restart bbb-graphql-middleware using the command `sudo systemctl restart bbb-graphql-middleware`
> Fix: close event emitting a terminal error

- bigbluebutton-html5/imports/ui/components/activity-check/container.jsx
restores intl prop in activity check component
Closes #21306
Set in `/etc/bigbluebutton/bbb-web.properties`
```
userInactivityInspectTimerInMinutes=1
userInactivityThresholdInMinutes=2
userActivitySignResponseDelayInMinutes=1
```
restart `sudo bbb-conf --restart`
1. Create a session
2. Join with moderator
3. Send a chat message
4. Stop moving the cursor (even go to a different browser tab)
5. Wait a couple of minutes
> fix: Client crashes on activity check

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/DeleteGroupChatMessageReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/EditGroupChatMessageReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChat.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChatHdlrs.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala
- bbb-graphql-actions/src/actions/chatDeleteMessage.ts
- bbb-graphql-actions/src/actions/chatEditMessage.ts
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_private.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_public.yaml
This PR introduces two new mutations for editing and deleting chat messages:
```gql
mutation($chatId: String!, $messageId: String!, $chatMessageInMarkdownFormat: String!) {
chatEditMessage(chatId: $chatId, messageId: $messageId, chatMessageInMarkdownFormat: $chatMessageInMarkdownFormat)
}
```
```gql
mutation($chatId: String!, $messageId: String!) {
chatDeleteMessage(chatId: $chatId, messageId: $messageId)
}
```
Additionally, three new fields are added to the `chat_message` type for both public and private chats:
```gql
subscription {
chat_message_public {
editedAt
deletedAt
deletedBy {
name
}
}
}
```
```gql
subscription {
chat_message_public {
editedAt
deletedAt
deletedBy {
name
}
}
}
```
A new `chat_message_history` table has been introduced to store previous versions of edited or …
> gql-server: Allow users to edit and delete chat messages (backend portion)

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
This PR fixes the away toggle to show the correct state throughout refreshes. 
Closes #21333 
Start a meeting, use away toggle and refresh the page.
> Fix: [3.0] Wrong away toggle initial state

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
This PR adds memoization and comparsion functions to the chat pages and chat messages to prevent whole chat re-renders and unnecessary message re-renders caused by React's default shallow comparsion mechanism. The comparsion functions ensure that only the pertinent message attributes trigger a component's re-render.
Messages sent by a user are not updated (re-rendered) when their role change. In other words, the chat messages reflect the user's role at the time the message was sent. Altering the message to reflect the user's current role could confuse participants, as it would modify the context of the past conversation. This behavior has been validated by the UI/UX team and brings benefits such as performance improvements and consistent behavior with how playback handles such messages. …
> feat(chat): improve messages rendering

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/SetCamShowAsContentReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/UserBroadcastCamStartMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/WebcamApp2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserCameraDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Webcams.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WebcamsMsgs.scala
- bbb-graphql-actions/src/actions/cameraSetShowAsContent.ts
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_camera.yaml
- Subscription
```gql
subscription {
user_camera {
showAsContent
}
}
```
- Mutation (only for `presenter` and `contentType='screenshare'`)
```gql
mutation($streamId: String!, $showAsContent: Boolean!) {
cameraSetShowAsContent(streamId: $streamId, showAsContent: $showAsContent)
}
```
Related #21303
> refactor (gql-server): Rename `user_camera` prop from `focused` to `showAsContent`

- bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx
- bigbluebutton-html5/imports/ui/components/layout/modal/styles.js
This PR visaully removes the custom layout from the layouts modal and also applies some style so the modal doesn't look so empty.
closes #21293 & #17939
Join BBB as mobile, open the layout modal.
> style(layout/modal): Removing custom layout (visually) from layouts modal

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/chat-list/styles.ts
This PR fixes a bug where the moderator would be unable to reach the user list, due to too many tabs opened in this user list area making it go down and disappear.
The PR also removes the private chat scroll bar on mobile devices and adds a 'general', that way, the user to get to navigate with 3 different scrolls and instead can use only one.
Note that this changes DON'T mess with the user list scroll nor it's pagination, which is made based on the screen size.
Also, the design team was consulted for this change.
Closes #21328
The motivation for the making of this PR was that adding another scroll to acess the rest of the elements such as:  Notes, Guest Policy and etc... Could be a little annoying for the user.
Enter a BBB meeting with a presenter on mobile,  add as many tabs as possible …
> fix: [3.0] Can't access user list when in landscape mode on mobile and with a few features opened

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/styles.ts
This PR  adapts the chat poll results to smaller and differently oriented screens.
To test it, open BBB and publish a poll, then try mobile orientations (landscape and portrait)
Mobile/Landscape
Mobile/Portrait
Desktop/Web
> style/enhancement: Adapting poll results to various screen types.

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/DeleteGroupChatMessageReactionReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/GroupChatHdlrs.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageReactionReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/ChatMessageReactionDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala
- bbb-graphql-actions/src/actions/chatDeleteMessageReaction.ts
- bbb-graphql-actions/src/actions/chatSendMessageReaction.ts
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/actions.graphql
- bbb-graphql-server/metadata/actions.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_private.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_public.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_chat_message_reaction.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
Introduces graphql fields and mutations to send/delete chat message reactions!
- Public subscriptions to get message reactions:
```gql
subscription {
chat_message_public {
message
reactions {
createdAt
reactionEmoji
user {
name
}
}
}
}
```
- Private subscriptions to get message reactions:
```gql
subscription {
chat_message_private {
message
reactions {
createdAt
reactionEmoji
user {
name
}
}
}
}
```
- Example of result
```json
{
"data": {
"chat_message_public": [
{
"message": "hello",
"reactions": [
{
"createdAt": "2024-10-03T17:19:49.854+00:00",
"reactionEmoji": "😐",
"user": {
"name": "teacher 1"
}
},
{
"createdAt": "2024-10-03T17:20:10.984+00:00",
"reactionEmoji": "😐",
"user": {
"name": "student 2"
}
},
{
"createdAt": "2024-10-03T17:20:33.292+00:00",
"reactionEmoji": "👏",
"user": { …
```
> graphql-server: Add support for chat message Reactions (backend portion)

- bigbluebutton-web/nginx-confs/presentation-slides.nginx
Always add CORS headers to requests to the rendered slides. There is no authentication required to access the slides, so we can allow requests from anywhere.
Closes #21262 
There should be no good reason not to use the cluster setup if you run multiple nodes.
> Fix CORS Header for rendered slides

- build/packages-template/bbb-graphql-middleware/build.sh
- build/packages-template/bbb-graphql-server/build.sh
…f build system
If the build system for packages has a umask of `0077`, cloned repositories will have no permissions for group and other. If build scripts just copy files, permissions will persist. This commit fixes permissions for some files which otherwise prevents startup `bbb-graphql-server.service` and `bbb-graphql-middleware.service`.
Fixes permissions in packages. Makes build process less dependant on the umask of the package build system.
If the build system for packages has a umask of 0077, cloned repositories will have no permissions for group and other. As the build scripts for some packages just copy from clone git repos, this will preserve the permissions in the package and prevent the following services from startup:
* `bbb-graphql-server.service`
* …
> build(fix): File permissions in packages should not depend on umask of build system

- build/setup.sh
Ensures that docker is always called with sudo privileges during package build. If the user does not have access to the docker socket, root privileges are required.
> Consistently call docker with sudo privileges

- build/setup.sh
Ensures that docker is always called with sudo privileges during package build. If the user does not have access to the docker socket, root privileges are required.
This is a backport of #21363
> Consistently call docker with sudo privileges (2.7 backport)

- bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
This PR fixes an issue where the `userdata-bbb_force_listen_only` param would include moderators when it shouldn't.
The real problem was that the data was being requested before obtained, and in doing so being assumed false.
The solution was to contdition the return to identify if it had the whole data before rendering. 
Closes #21326
Create a BBB meeting using `userdata-bbb_force_listen_only` param - Join with both Moderator and Viewer.
Before
https://github.com/user-attachments/assets/6b5e749d-f91b-4131-b410-8bb98cb9a93a
After
[Screencast from 2024-10-04 11-12-19.webm](https://github.com/user-attachments/assets/f7c279a2-4a84-4197-adc5-47ab4cb40316)
> Fix: `userdata-bbb_force_listen_only`param applying to moderator

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala
This PR fixes an issue where the user would set a max number of participants, and the parameter would allow 1 user less than the set number.
#19426 (partial)
The motivation was to make the parameter a little more usable.
Set the number of max users in the join parameter, and enter with the number of users you set.
> Fix(Akka): [3.0] - maxParticipants is applying one less than the parameter value

- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/page/component.tsx
This PR intends to restore the keyboard navigation on userlist, I refactored the code to support the pagination and have a easy way to get the element, it stopped work on the migration from the virtual list to the pagenation, before the virtualized returned a ref with all elements on screen and with the removing of it only the parent page was being returned.
OBS: I'm using the key values directly because the KeyCode is deprecated https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
Navigate with tab til reach main userlist area so press, space, enter or arrow down to navigate using arrow keys.
> Fix: Restore keyboard navigation on userlist

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR restricts the "hand" tool keyboard shortcut to only the presenter, preventing non-presenters from activating it.
Closes #21304
> fix(whiteboard): Restrict pan keyboard shortcut to presenter only

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
This PR disables the native tldraw options that are not yet fully supported and, in some cases, can cause issues. The disabled options include:
- Edit Link
- Toggle Lock
- Reorder
- Move to Page
- Copy as
- Export as
The following options are still available:
- Cut
- Copy
- Paste
- Select All
- Select None
- Delete
- Duplicate
Closes #21314
> fix(whiteboard): Disable tldraw right-click options

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.tsx
This PR fixes the issue where the button to enable fullscreen of a webcam appears for iPhone users.
Closes #21332
> Fix(webcam): do not display fullscreen button on iPhone

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Refactor whiteboard container to use lock context for checking if a user has active locks.
Closes #21297
1. Join in a meeting with a moderator and 2 viewers;
2. Manage users > Lock viewers > See other viewers cursors;
3. Unlock a viewer and move other viewer's cursor;
> fix: Unlocking specific user to see other viewers cursors not working

- bigbluebutton-html5/imports/startup/client/intlAdapter.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/component.tsx
fix:
1. issue where the "join audio" button tooltip would be displayed in the wrong language after switching locales
2. issue where the "settings have been saved" toast would be displayed in the wrong language after switching locales
for item 1:
2. change language in settings menu
3. save settings
4. see join audio button tooltip
for item 2:
2. change language to any (A) language
5. save settings
6. change language to any (B) language
7. save settings
8. change font size in settings menu
9. save settings
10. see "settings have been saved" message being displayed in "A" language instead of "B"
> fix: locale issues

- bigbluebutton-html5/imports/ui/components/notes/component.tsx
This PR fixes an issue where the notes were not able to retrieve the notes data upon pinning, and in so, making the WB "crash".
Closes #21283 
Start a meeting, pin shared notes onto WB.
After fix
https://github.com/user-attachments/assets/9159875a-0a5f-48e9-ab2c-10e88c2b9c5e
> Fix: [3.0 Beta2] Pinning shared notes onto whiteboard crashes whiteboard

- bigbluebutton-html5/imports/ui/components/nav-bar/options-dropdown/component.jsx
Fix incorrect call to function used to enter fullscreen
2. open "options" dropdown
3. select "Fullscreen Application" (first item)
> fix: fullscreen button does not work

- build/packages-template/bbb-html5/build.sh
- build/packages-template/bbb-libreoffice-docker/build.sh
- build/packages-template/bbb-playback-presentation/build.sh
- build/packages-template/bbb-playback-video/build.sh
- build/packages-template/bbb-record-core/build.sh
Fixes permissions in packages if packages are built with a restrictive umask such as `0077`. It fixes missing read permissions which prevent service startup.
> build: Umask fixes for 2.7 build scripts

- bbb-graphql-server/bbb_schema.sql
- The current size limit for the `value` column in the `meeting_metadata` table is 100 characters. In some cases, this is insufficient as the parameter can exceed that limit.
- To resolve this, the column size is increased to 1000 characters.
- Similarly, the `value` column in the `user_metadata` table had a limit of 255 characters. Since it's difficult to predict the size of incoming data, the limit is also increased to 1000 characters to accommodate larger values.
Reported by @prlanzarin and @ffdixon.
> refactor (gql-server): Increases the size limit of the `value` column in the metadata tables

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
enable private chat with moderators for locked viewers.
Closes #21317
1. Join 2 users into a meeting. One moderator, one viewer.
2. lock private chat
3. as moderator open private chat with viewer
4. moderator can send chat messages
5. viewer cannot send chat messages
> fix: [3.0 Beta 2] Chat lock settings do not work as expected

- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/talking-indicator/styles.ts
This PR Adjusts the style and functionality of talking indicator based on the user's role.
Join a meeting with both moderator/presenter and viewer and put out pointer over the talking indicator.
https://github.com/user-attachments/assets/a9ade71f-9287-4bc3-bf12-bdb6008f73a3
> refactor(nav-bar/talking-indicator): Refactor styles in `TalkingIndicator` to conditionally apply styles based on user role.

- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
Just makes plugin manifest accept "-" character.
Make manifests like this:
```json
{
// ...
"remoteDataSources": [
{
"name": "allUsers",
"url": "${meta_my-callback-url}",
"fetchMode": "onMeetingCreate",
"permissions": ["moderator", "viewer"]
}
]
}
```
be correctly interpreted.
> fix(common-web): Make plugin manifest accept "-" character for placeholders

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/styles.ts
This PR fixes a lack of padding when the recording indicator is in "recording mode" - but only for viewers.
Start a meeting, start recording and join with a viewer.
> style(nav-bar/recording-indicator): Refactor padding in `RecordingStatusViewOnly` for consistent spacing.

- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_presenceLog.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
This PR adds the `user_presenceLog` type to the GraphQL schema, which will enable tracking of users' presence in the meeting, including those who have already exited the session. This functionality is essential for teachers to view a comprehensive list of attendees, including those no longer in the meeting.
```gql
subscription {
user_presenceLog {
extId
userId
currentlyInMeeting
isModerator
}
}
```
It is not intended to be used by the Client. But it will be useful for plugins.
---
It also adds a column `user.firstJoinedAt` that was necessary to track if the user has already joined in the meeting (in the past).
This column is not being provided by any graphql Type, but it can easily be provided in the future if necessary.
> feat (gql-server): Introduces graphql Type `user_presenceLog` to indicate users that have joined

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
- Avoids calling `seekTo` before the `onStart` event. In such case, React Player seems to remount the player, triggering a new `onReady` event, which was causing an infinite loop.
- Eliminates the `onReady` handler and moves its responsibility into the `onStart` handler.
Closes #21310
> fix(external-video): Video file sharing is broken

- bigbluebutton-html5/imports/ui/services/meeting-settings/index.js
The metadata is comming from server with { name: metaname, value: metavalue }, which is not compatible with getFromMeetingSettings, so it's not reading corretly. Convert it before storing.
Meeting metadata was not being read correctly in client.
Create a meeting with some meta, e.g. `media-server-video`, see if it is changing the related feature.
> fix(client): convert meeting metadata to expected format

- bbb-graphql-middleware/internal/common/CustomCache.go
- bbb-graphql-middleware/internal/common/SafeChannelByte.go
This PR addresses two memory leaks that were causing the service to accumulate memory without releasing it.
1. **Global lock cleanup**: The global lock used to prevent processing the same message multiple times was not being removed. This lock is now automatically cleared after 30 seconds, once all connections have benefitted from the cache.
2. **Channel closure issue**: A routine was failing to close properly due to a frozen channel. The channel will now always be unfrozen before attempting to close it, ensuring proper routine shutdown.
With these fixes, memory usage returns to its normal state after all users leave the meeting, and the garbage collector can reclaim memory after a few minutes.
Kudos to @prlanzarin for reporting this issue 👏
> fix (gql-middleware): Fix memory leaks

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Plugins.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/PluginManifest.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
This PR basically refactors the name `pluginsManifests` to `pluginManifests` parameter and makes necessary changes. Outside of that, it adds the possibility of sending a relative plugin js entrypoint in manifest. So now, the structure can Also be as follows:
```json
{
"requiredSdkVersion": "~0.0.59",
"name": "H5pPlugin",
"javascriptEntrypointUrl": "H5pPlugin.js",
"localesBaseUrl": "https://cdn.dominio.com/pluginabc/",
"eventPersistence": {
"isEnabled": true,
"maximumPayloadSizeInBytes": 1024,
"rateLimiting": {
"messagesAllowedPerSecond": 10,
"messagesAllowedPerMinute": 20
}
},
"dataChannels": [
{
"name": "testResult",
"pushPermission": ["moderator"],
"replaceOrDeletePermission": ["creator", "moderator"]
}
]
}
```
And the absolute js entrypoint would be the `baseUrl` of the `manifest.json` …
> feat(akka): Plugin Js relative entrypoint and refactor of `pluginManifests` parameter

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
This PR removes the hide toolbar menu option for users who do not have access to the whiteboard.
Closes #21404
> fix(whiteboard): Only show hide toolbar option to users with WB access

- bigbluebutton-html5/imports/api/audio/client/bridge/sfu-audio-bridge.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(audio): check error codes before retrying on start failure](https://github.com/bigbluebutton/bigbluebutton/commit/a07e319e903e8274a122a93c963b1fbb0b238364) 
- The check for whether an error code is deemed "retryable" in
sfu-audio-bridge's joinAudio code is reversed - which may cause
unwarranted audio retries on join failures.
- [fix(audio): prevent overlapping sessions from gUM-induced timeouts](https://github.com/bigbluebutton/bigbluebutton/commit/d0ad8afe64d119a03b46efe71d61a064178f444e) 
- `getUserMedia` is called by each audio bridge if it hasn't been
triggered during pre-flight screens. This ties gUM to the bridge's
negotiation timers and audio-manager's activation tracking, leading to
two issues:
- A gUM prompt left unanswered for over 30 seconds can cause an
incorrect 1010 …
> fix(audio): clear input device IDs if getUserMedia fails, +

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutHdlrHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/user-actions/service.ts
- docs/docs/administration/customize.md
- Included a new userdata `userdata-bbb_parent_room_moderator` so akka-apps can
signal the HTML5 client that the user had a moderator role when the breakout room
was created. 
- This user will have an extra permission inside the breakout room where
he/she will be able to kick other users out.
- This userdata is passed automatically by akka-apps when creating the breakout joinUrl
Possibility for moderators to enter a breakout and have better control.
- Start a metting with some moderators and viewers.
- Start breakouts and join with viewer and moderator
- The moderator should see the "Remove User" option when clicking a user name inside the breakout
Built on top of https://github.com/bigbluebutton/bigbluebutton/pull/21470 to avoid conflicts.
> feat: allow parent room moderators to kick other users in breakouts

- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala
- bbb-learning-dashboard/src/App.js
- bbb-learning-dashboard/src/components/StatusTable.jsx
- bbb-learning-dashboard/src/components/UserDetails/component.jsx
- bbb-learning-dashboard/src/components/UsersTable.jsx
- bbb-learning-dashboard/src/index.js
- bbb-learning-dashboard/src/services/UserService.js
Store and show sessions of users that re-enter (reopen tab) with the same internalID.
Example how it was:
And now, after the user reopens the tab:
Previously, when a user closes the tab and later rejoin with same url, the learning dashboard treated it as the user never left, so the online time of the user was wrong.
- Join a session and close/rejoin multiple times with same user and same URL (wait for the user to leave userList before rejoining)
- Open learning dashboard and check join and left times, and also online time, it should show all sessions and calculate the online time correctly.
Also include some bonus fixes for localization strings and poll content breaking exported csv.
> fix(learning-dashboard): show all sessions of users with the same internalID

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/layout/context.jsx
- bigbluebutton-html5/imports/ui/components/layout/enums.js
- bigbluebutton-html5/imports/ui/components/layout/initState.js
- bigbluebutton-html5/imports/ui/components/layout/layoutTypes.ts
- bigbluebutton-html5/imports/ui/components/layout/observer.tsx
Introduces a mechanism to control the rendering of notification toasts in the layout context and attach that to a join parameter called `userdata-bbb_hide_notifications`. When this parameter is set to `true`, all notification toasts are suppressed in the client. 
None
Use the join parameter `userdata-bbb_hide_notifications` and check whether notification toasts are rendered in the client. Some events that trigger notification toasts are: lock settings update, layout propagation, presentation upload...
> feat: add `bbb_hide_notifications`

- bbb-graphql-server/bbb_schema.sql
The trigger that populates raiseHand-time was removed wrongly at #20717.
This PR restores it and fixes the ordering issue, placing users with hand raised on the top!
> fix: Users with raiseHand are not on the top of the the userlist

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/layout/context.jsx
- bigbluebutton-html5/imports/ui/components/layout/enums.js
- bigbluebutton-html5/imports/ui/components/layout/initState.js
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx
- bigbluebutton-html5/imports/ui/components/layout/layoutTypes.ts
- bigbluebutton-html5/imports/ui/components/layout/observer.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
Introduces the userdata join parameter `bbb_hide_controls`, which hides the actions bar and the top row of the navigation bar (including the close sidebar button, room title, connectivity indicator, and leave meeting button) while keeping the row with the talking indicator and timer indicator visible.
None
> feat(layout): add userdata `bbb_hide_controls` 

- .github/workflows/automated-tests.yml
The step "Install BBB" in our workflow sometimes exceeds 25 minutes, and it needs a retry mechanism to handle such long runtimes. We were previously using the `nick-fields/retry@v3` library for this purpose, but it's not functioning correctly in our case.
There is an unresolved issue with this library, reported some time ago, with no recent updates or responses from the maintainers: https://github.com/nick-fields/retry/issues/114.
To address this, I am replacing the use of the external library with a shell script to manage timeouts and retries. This should provide better control and reliability for the `Install BBB` step.
----
Fix:
> refactor (ci/tests): Replace retry method for `./bbb-install.sh` step

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/styles.ts
Refactor user list item styles to prevent userlist item being cut due to margin being applied to the wrong element.
> style: adjust userlist item margin

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
The condition to create a new toast was looking for the toastId and not verifying if This notification is enable or not, changing it to verify the toast is active removed the error, Looks like with the status updating too frequently caused notification have a race condition and load a new notification if the old is not active.
Closes #21321
Open a breakout with the option `Save shared notes` in the breakout edit the shared notes and finish the breakout meeting, but the best approach to test it is use the automated test described in the issue.
> Fix: Presentation uploader toast not appearing sometimes when converting notes from breakouts

- .github/workflows/automated-tests.yml
This PR adds steps to clean up incomplete installations when the "Install BBB" step times out.
When the "Install BBB" step times out, it can leave ongoing apt installations in an incomplete state, preventing retries. This PR introduces cleanup steps to ensure that any interrupted installations are properly handled, allowing the process to restart smoothly.
> refactor (ci/tests): Stop any ongoing processes before retrying to install bbb

- bigbluebutton-html5/imports/ui/components/learning-dashboard/service.js
Small fix to avoid error in case `.settings.public.app.learningDashboardBase` is not set.
> fix (html5): prevent error if `learningDashboardBase` is missing

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
It fixes plugins not running into breakout-rooms, so now, the same plugins that run on the main-room are going to also run into the breakouts.
Closes https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/127
There are some required plugins that will run into breakouts, so this must have been sorted out.
Really simple:
- Load a plugin into your BBB session (via create parameter or `.properties` bbb-web configuration)
- See if it runs in the main room;
- Create a breakout-room;
- See if it runs into the breakout you just created.
Demo of the newly fixed behaviour:
https://github.com/user-attachments/assets/72f67558-b071-4395-b759-025b09e1c83d
For this Demo, and for the tests, I used [SampleActionButtonDropdownPlugin](https://github.com/bigbluebutton/bigbluebutton-html-plugin- …
> fix(bbb-web): fix plugins not loading nor running into breakout-rooms

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/imports/ui/components/meeting-ended/service.ts
Enable LearningDashboard cookie support across different subdomains.
After a meeting ends, the client sets a cookie `ld-${meetingId}` with a token used to retrieve meeting data in JSON format. The Learning Dashboard needs access to this cookie to obtain the token.
The issue occurs in a Cluster setup where the Dashboard is hosted on a different subdomain, preventing it from accessing the cookie. 
To resolve this, the client will set the cookie using the root domain (excluding the subdomain). This allows the cookie to be accessible from any subdomain.
_Important to mention that it will happen only when the LADashboard has a custom `.public.app.learningDashboardBase` (config), by default nothing will change._
> fix (LAD/cluster): Enable LearningDashboard cookie support across different subdomains

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/service.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [chore(audio): add I/O device data to audio logs](https://github.com/bigbluebutton/bigbluebutton/commit/0ecf665aca) 
- I/O device IDs are logged in some specific logCodes, but they aren't too
useful on their own without the rest of the MediaDeviceInfo object. We
need that extra data (label, group) to be able to better investigate
incorrect device issues and NotFoundError occurrences.
- Register full I/O device info whenever the client fetches them and add
those, unfiltered, to the following logCodes:
- audiomanager_error_getting_device
- audiomanager_error_device_not_found
- audiomanager_error_unknown
- audio_joined
- audio_ended
- audio_failure
- audiomanager_input_live_device_change_failure
- audiomanager_output_device_change_failure
None
1. Enable client logging
2. Join/leave audio …
> chore(audio): add I/O device data to audio logs

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PresAnnotationHistoryDAO.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_curr.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_history_curr.yaml
- bigbluebutton-html5/imports/ui/components/whiteboard/queries.ts
Currently, annotations are fetched from the `pres_annotation_curr` table, which stores only the latest version of each annotation. Whenever an annotation is modified, the row is updated with the new version, leading to several issues:
1. **Lost History:** All previous edits are overwritten, making it impossible to reconstruct the history of changes.
2. **Concurrent Modifications:** In a multi-user whiteboard scenario, if two users modify an annotation at the same time, only one change is recorded, as updates are fetched every 100ms, potentially missing one of the changes.
3. **Large Payloads:** When an annotation is changed, the entire object is sent to clients, instead of just the modified parts, increasing the size of the payload unnecessarily.
This PR re-enables the …
> refactor (graphql-server): Preserves the entire history of annotation changes (type `pres_annotation_history_curr`)

- .github/workflows/automated-tests.yml
This PR will solve two issues during `Install BBB` step on Automated tests:
- When retrying to install BBB, it's missing to unlock the file `/var/cache/debconf/config.dat`
- BBB-Install very often stuck on step `Installing the firefox snap`, so it will hold this package to avoid upgrading it.
> ci: Improve retry for `Install BBB` step in Automated Tests

- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/component.tsx
This PR fixed a console error being emitted every time the userlist is closed, it was introduce at #20975, because of a `useDeduplicateSubscription` hook being used inside a useEffect hook, React doesn't allow the use of hooks inside of lifecycle hooks of a component thwoing a error.
No issues was opened.
1. Open devtools
2. Clear the logs
3. Open/close the userlist several times.
> Fix: hook being used inside useEffect

- bigbluebutton-html5/imports/ui/components/notifications/component.tsx
Refactor notifications component to handle audio alerts when push alerts are not enabled
1. join a meeting with user A
2. enable user join/leave audio alerts for user A, but keep push alerts disabled
3. join with another user (user B)
4. user A should hear an audio alert
> fix: audio alerts for user join/leave only work if push alerts are enabled

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
- bigbluebutton-html5/imports/utils/object-utils.js
- When the user clicks `Load more messages` the client freezes for a few seconds before rendering the new page. This was happening because the message component was overheaded with hook calls and data access which were triggering an additional render. In order to fix that, all those hook calls within the message component were placed in the parent component (more stable, doesn't rerender frequently) and passed as props to the message component.
Closes #21434 
1. Start a session.
2. Go to the chat.
3. Type 100+ messages.
4. Scroll up and click 'Load more messages'.
> fix(chat): Loading a new message page freezes the client

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
This PR intends to make the client terminates the connection when notice that it's stale, the own apollo client tries to reconnect when the `shouldRetry` returns `true`, I also set a configurable amount of time to try the reconnection.
Closes #21062
Join the client and switch network or turn on/off a VPN.
> Fix: Force reconnection in case of stale connection.

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/DeleteGroupChatMessageReqMsgHdlr.scala
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
Deleting others' chat messages is not allowed in Breakout Rooms, as all participants are moderators.
> fix: Prevent moderators from deleting others' chat messages in Breakout Rooms

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-header/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/emoji-button/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/queries.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-popup/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/styles.tsx
- bigbluebutton-html5/imports/utils/object-utils.js
- bigbluebutton-html5/private/config/settings.yml
This PR includes a bunch of improvements and fixes for the chat.
- Restore the original message typed in the message input after editing a message.
- Fix messages scrolling behind the welcome message.
- Disable chat roving If no message toolbar feature is enabled.
- Button for cancelling a reply hiding if chat panel is narrowed.
- Add timeout for cleaning up non-visible message pages when the user scrolls to the end of the message list.
- Fix loading spinner not showing when a new page is loading.
- Align offline indicator (which indicates that the sender of a message is offline) on the left-hand side of the message header.
- Add infinite scroll.
- Message input focus style
- Message toolbar hover styles
- Fixed offline indicator
- Besides those this PR includes some fixes targeting …
> fix(chat): Improved usability, UI fixes, et al.

- bigbluebutton-config/bin/bbb-conf
In `bbb-conf`, exclude the `pluginManifests` config from the non-empty value check in `bigbluebutton.properties`, as it is expected to be null and does not cause issues.
Before:
After:
> fix (bbb-conf): Exclude the `pluginManifests` config from the non-empty value check

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Plugins.scala
It creates a new feature to the plugin's manifest: Allowing (or not) the plugin to run in the breakout-rooms.
As a default, if this property is not set in manifest, it will be taken as false, so that plugin will not load on breakout-rooms. If, however, the developer wants it to run in the breakout-rooms, they need to explicitly tell in the manifest by setting `enabledForBreakoutRooms` as true.
Closes https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/126
Take one of the plugins that already has the manifest structure, such as the https://github.com/bigbluebutton/plugin-pick-random-user, and do the following steps:
- Run it either in dev mode or not (as is);
- Create a meeting with the plugin (either by `/create` parameters or by `.properties` configuration file from …
> feat(akka): add feature to decide whether the plugin will run on the breakout-rooms or not

- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx
This PR intends to fix a bug when the user session doesn't exist in graphql the client keeps in infinity loading, It happens because every query returns empty in the case, I verify if the query loaded and the query came empty, in that case I throw a error that no data was found.
Doesn't close but related to #21285
- Run this Command on server console `sudo -u postgres psql -d bbb_graphql -c "delete from meeting where 1=1"`
> Fix: Infinity loading screen when meeting doesn't exist on Graphql

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the seek functionality of non-youtube players in external video.
Closes #19981 with help of PR #21469
Start a meeting, use external video with non-youtube video sources, and try do skip the video by clicking the progress bar.
> fix(external-video-player): fix seek functionality to the external video player(non youtube)

- bigbluebutton-config/bin/bbb-conf
- build/packages-template/bbb-config/build.sh
- included postgres in bigbluebutton.target (which means it gets restarted together with the rest of the services via `bbb-conf --restart`)
- includes `nginx`, `freeswitch`, `redis-server` in bigbluebutton.target (which means they get restarted together with the rest of the services via `bbb-conf --restart`)   -- this was mostly done by @danimo in https://github.com/bigbluebutton/bigbluebutton/commit/61ce7ab9b658cea6e069faf91c96e6cb1d90f349 but the overrides were getting cleared later in the `bbb-config` building, so they never really worked.
- `postgres` included in the `bbb-conf --status` list
- no longer reload nginx on `bbb-conf --restart` as it gets restarted anyway
Closes https://github.com/bigbluebutton/bigbluebutton/issues/21446
``` …
```
> build: postgres to restart together with BBB

- bigbluebutton-tests/playwright/breakout/breakout.spec.js
`Export breakout room whiteboard annotations` often fails in Ci runs, likely `Export breakout room shared notes` would be if enabled;
Related issue: #21576
> test: Breakout export tests flagged as flaky

- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
Force shared notes unpin when a screen share starts to ensure shared notes are always accessible.
Closes #21513
> fix(shared-notes): force unpin on screen share start

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/service.js
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- [refactor(audio): make audio join cancel configurable](https://github.com/bigbluebutton/bigbluebutton/commit/82a208ff78fa844ad0805a7b27dcf51a3a915796) 
- [Audio was made "cancellable" a while ago](https://github.com/bigbluebutton/bigbluebutton/pull/13821) by allowing users to close the
audio modal while audio is being negotiated. By looking through metrics,
I have a theory that this may be:
1. increasing error rates artificially
2. confusing end users who mistakenly click outside of the modal.
- Cancelling audio join should not be an option in the first place if
there's no good way to let users know how to roll back from that
situation (there isn't, right now). There are also timeouts in place in
both audio bridges so that it doesn't stay "loading" forever.
- This commit adds a new flag …
> refactor(audio): make audio join cancel configurable

- .github/workflows/automated-tests.yml
Removes the special scheduling policies for `bbb-webrtc-sfu`
It adds an override file for `bbb-webrtc-sfu` that changes the `CPUSchedulingPolicy=other`, default was `CPUSchedulingPolicy=fifo`
reason:
Subprocess forking does cause CPU hikes, but it's still unclear why some envs get those processes pegged at 100% in restricted environments (informed by @prlanzarin)
PS: It's not clear if this issue affects Automated Tests, but it is a possible cause that makes `install-bbb` stuck very often.
> ci: Removes the special scheduling policies for `bbb-webrtc-sfu`

- bigbluebutton-html5/imports/ui/components/nav-bar/options-dropdown/component.jsx
- bigbluebutton-html5/public/locales/en.json
- inverts presence switch colors
- adds localization for presence label
Closes #21590
> fix: Presence switch in menu is reversed

- .github/workflows/automated-tests.yml
- build/packages-template/bbb-freeswitch-sounds/build.sh
This PR updates the freeswitch build cache link due to recent failures in CI runs
> ci: Update freeswtich build cache link

- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
This PR fixes the issue when navigating through keyboard over recording status was triggering the start recording modal, it was happening because the function to trigger the modal was not filtering which key could enable it, I made it support only the `Enter` key. 
No issue was Opened
1. Select Meeting name in navbar.
2. press Tab twice in the keyboard.
3. See the start recording modal open.
> Fix: recoding start being triggered by any key

- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
It basically makes the plugin's manifests fetches asynchronous, so that if someone has lot's of plugins to load, it will take mostly the same amount of time as if they had a few.
Besides testing if the plugins still load normally (combining 2 or 3), one can add logs in the beginning of the manifest fetch and at the end, and one more after all the futures had been completed. This way, it's possible to analyse if the processes occurred parallel to one another.
> feat(common-web): Add asynchronous fetch to plugin's manifests

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx
This PR ensures that the log message Starting browser speech recognition is only sent when speech recognition (CC) is enabled, reducing unnecessary log entries when speech recognition is off.
Closes #21577 
Look for the log message with and without CC on.
> fix(captions/speech): Fix logger debug message placement in `start` function

- .github/workflows/automated-tests.yml
While removing MongoDB we had temporarily switched the CI to use a no-mongo branch which is now merged (and deleted)
Switch back to the official bbb-install branch for BBB 3.0
Closes #none
I deleted the no-mongo branch. Its changes made it to the v3.0.x-release one.
Passing CI
> ci: Use the default bbb-install.sh for BBB 3.0

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx
This PR ensures that the log message Stopbrowser speech recognition is only sent when speech recognition (CC) is enabled, reducing unnecessary log entries when speech recognition is off.
Closes #21577
> fix(captions/speech): Fix logger debug message placement in stop function

- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
The error was caused by a missing validation when the screenshare starts.
Closes #21586
- Join with a prenseter and a viewer
- start screenshare 
- look at viewer browser logs
> Fix: unpin shared notes when screenshare started

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/container.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/options-dropdown/component.jsx
- bigbluebutton-tests/playwright/layouts/layouts.js
- bigbluebutton-tests/playwright/parameters/disabledFeatures.js
removes layout settings option from actions dropdown - it is still available in options dropdown (3 dots menu)
Closes #21592
> fix: Layout settings reachable from Plus menu as well as 3 dot menu

- .github/workflows/automated-tests.yml
- build/packages-template/bbb-freeswitch-core/build.sh
- build/packages-template/bbb-freeswitch-sounds/build.sh
Backporting https://github.com/bigbluebutton/bigbluebutton/pull/21617 to BBB 2.7
Also:
* Switch to using BigBlueButton's fork of drachtio-freeswitch-modules (because the original was deleted. I found someone's clone and luckily it had the commit we use)
* Switch to using BigBlueButton's fork of warmcat/libwebsockets (to avoid issues if the original is deleted)
Note: I am not switching to BBB forks of repositories owned by SignalWire(FreeSWITCH)
> [2.7]ci: update link to download FS sounds.tar.gz

- build/packages-template/bbb-freeswitch-core/build.sh
the original repo disappeared;
Replacing libwebsockets repo to be using our fork too to avoid surprises
Porting a portion of https://github.com/bigbluebutton/bigbluebutton/pull/21635 to BBB 3.0+
> [3.0]build: use BBB fork of drachtio-freeswitch-modules

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/PresentationPods.scala
- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
- bigbluebutton-html5/imports/utils/slideCalcUtils.js
This PR updates the zoom functionality on the infinite whiteboard by lowering the minimum zoom level to 25%. This enhancement allows users to zoom out beyond the slide boundary
Closes #21103
> fix(whiteboard): Lower min zoom to 25 percent for infinite whiteboard

- bigbluebutton-config/bin/bbb-conf
Re-insert a reload of nginx on BBB restart
Closes #none
This was removed in #21532 as nginx is also restarted with BBB but it seems the reload is needed. We see some instances of nginx having to be reloaded for BBB to properly start
BBB upgrades [where nginx configs changed] should not stall
> conf: Reload nginx before starting BBB

- bigbluebutton-html5/imports/ui/components/common/tooltip/component.jsx
- bigbluebutton-html5/private/config/settings.yml
This PR changes a setting on tooltips (tippy) - the `interactive` option is set to `false`.
This change was made to prevent some tooltips to overlap and/or stay opened in situations where they shouldn't.
_e.g_  The new chat interactions, as in the image bellow:
Hover the mouse over any button or element that has a tooltip, when you move your pointer away from the element, the tooltip should vanish.
> fix(tooltip): Fix tooltip interactivity and update toolbar options in settings

- akka-bbb-apps/src/universal/conf/application.conf
- bbb-graphql-server/deploy.sh
- bbb-graphql-server/metadata/databases/databases.yaml
- build/packages-template/bbb-graphql-server/after-install.sh
- build/packages-template/bbb-graphql-server/hasura-config.env
This PR introduces dedicated PostgreSQL users for each application, replacing the use of the general `postgres` user across all applications. The new users are as follows:
- `bbb_core`: for Akka-Apps application
- `bbb_hasura`: for Hasura (read-only access)
- `hasura_app`: for Hasura metadata
This setup facilitates better monitoring by allowing us to track which application is making queries and to monitor each application's connection count. 
Additionally, it enables the possibility of setting a `max_connections` limit per application in the future.
> refactor (gql-server): Create dedicated postgres users for each application

- bbb-graphql-server/deploy.sh
- build/packages-template/bbb-graphql-server/after-install.sh
- Always recreate the database `hasura_app` to make sure it has the right permissions
- Also makes psql commands less verbose once it's not important to be logged
> refactor (gq-server): Make sure Hasura database has the correct permissions

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/styles.ts
This PR adjusts the chevron on RTL layouts.
Before
After
> refactor(audio-controls): Refactor padding imports in `input-stream-live-selector/styles.ts` for consistency.

- .github/workflows/automated-tests.yml
This PR intends to add a maximum time for `Install test dependencies` as it recently got stuck taking 1hour+ in a process that usually takes up to 5 minutes
> test(ci): add timeout-minutes on install test dependecies step

- build/packages-template/bbb-graphql-server/build.sh
Also switch to official method to install Hasura-CLI once npm doesn't provide the last versions.
> Bump Hasura version to 2.44.0

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR improves shape access control by using the tldraw API to retrieve the current shape list, ensuring users can only interact with shapes they created (unless they are a presenter/moderator).
Previously, there were cases where viewers could unintentionally access shapes locally they did not create.
before:
after:
> fix(whiteboard): Get current shape list from tldraw api for access management

- record-and-playback/presentation/scripts/publish/presentation.rb
Depending on the exact imagemagick version and configuration available, the command used for the last-ditch image generation might not work for generating svg slides, causing recording processing to fail completely.
It's trivial to manually generate an svg image of the desired size, so do that instead.
This fix is also applicable to the 2.7 branch.
> Recording: Fix presentation format handling for missing svg slides

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes a bug where the presentation area crashes when joining a breakout room that’s still loading the slide. It adds null checks for the shapes object to prevent errors from undefined or null values during whiteboard initialization.
Closes #21691
> fix(whiteboard): Add null check for shapes before usage

- docs/docs/administration/install.md
The install.md docs page was suggesting a vserver model which is not available any more. This PR updates the suggestion to the same but newer hardware model.
Avoid confusion of new users.
- open https://www.hetzner.com/cloud/ and look for `CCX32`. It is not there any more.
- open https://www.hetzner.com/cloud/ and look for `CCX33`. It is there and shows the suggested dedicated 8 CPU cores and 32 GB RAM.
> docs: install.md: suggest current vserver model

- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
- bigbluebutton-html5/public/locales/en.json
This PR changes the tooltip text on "Reactions bar" to "Share a reaction".
Just mind the tooltip of the reactions button.
> fix(actions-bar/reactions-button): Update reactions button label to Share a reaction

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
This PR refactors the feedback prompt logic to ensure that feedback is only requested after the main meeting session ends, excluding breakout sessions. 
Closes #21403 
1. Host a main meeting and verify that the feedback prompt appears when the meeting ends.
2. Create a breakout session and confirm that no feedback prompt appears after it ends.
> fix(meeting-ended): Refactor feedback prompt logic to exclude breakout sessions

- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/styles.ts
- bigbluebutton-html5/public/locales/en.json
refactor shared notes "locked" label to improve readability
> style: adjust locked shared notes label icon and text

- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-participants-title/component.tsx
- bigbluebutton-html5/public/locales/en.json
Update user participants title to include the number of users in the locale string, preventing an issue with participants number being displayed as `USERS) 1(` instead of `USERS (1)` after switching to a RTL locale and back to an LTR locale
https://github.com/user-attachments/assets/a3201992-d928-486b-90e5-27480f0c47c5
https://github.com/user-attachments/assets/2174bc91-1c6e-4dc3-bab3-456310d85cae
2. switch language to arabic
3. switch language back to english
4. see error
> fix: number of participants in userlist is not correctly displayed after switching to RTL locale

- docs/docs/administration/customize.md
As requested on issue #17139 this PR adds documentation about default logo, since all other items were documented already.
Closes #17139
> Documentation: Adding documentation about default logo

- bbb-graphql-server/bbb_schema.sql
When the user has a single occurrence of connection issue, the time is not populated properly:
<table>
<tr><td>
Before:
</td></tr>
<tr><td>
After:
</td></tr>
</table>
How to reproduce:
Send a single mutation indicating that the connections RTT is bad:
<table><tr><td>
</td></tr></table>
It helps to fix #21406, but the problem when client is not responding still happens.
> fix (gql-server): Connection Status with time empty when user has a single occurrence of connection problem

- bbb-graphql-middleware/internal/gql_actions/client.go
It was using the wrong rate limiter for mutations.
Which was causing problems for example: Not being able to jump slides after a bunch of actions.
> fix (gql-middleware): Wrong rate limit for mutations

- bigbluebutton-html5/client/meetingClient.jsx
- bigbluebutton-html5/imports/startup/client/intlLoader.tsx
- bigbluebutton-html5/imports/ui/components/common/loading-screen/component.jsx
- bigbluebutton-html5/imports/ui/components/common/loading-screen/loading-screen-HOC/component.tsx
- bigbluebutton-html5/imports/ui/components/common/loading-screen/styles.js
- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
- bigbluebutton-html5/imports/ui/components/join-handler/custom-users-settings/component.tsx
- bigbluebutton-html5/imports/ui/components/join-handler/guest-wait/component.tsx
- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/imports/ui/components/settings-loader/component.tsx
removes `1/2`, `2/2` text from loading screen 
https://github.com/user-attachments/assets/16b998d1-ba2a-4164-bb48-fa6c39d057e4
https://github.com/user-attachments/assets/9513a1ea-f56d-44c8-a1ff-ae72640a2654
Loading steps text is leftover from when BBB had 5 loading steps, and it's not needed anymore
> refactor: remove loading steps text

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
This PR improves the stability of the camera position and zoom in the TLDraw. It also defers the loading of TLDraw until the browser tab comes into focus. This adjustment addresses an issue where the TLDraw API's `getViewportPageBounds` function would return incorrect default values if the library was loaded while the browser was not in focus.
The camera position and zoom could easily fall out of sync due to `getViewportPageBounds` returning incorrect default values when the tab is not in focus.
> fix(whiteboard): Improve tldraw camera and zoom stability

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/PublicChatRecordEvent.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
- record-and-playback/core/lib/recordandplayback/generators/events.rb
- record-and-playback/presentation/scripts/publish/presentation.rb
It adds chat features to the recordings, that being:
- Reply;
- Reaction;
- Edition;
- Deletion;
All those new chat features are supported now for the record-and-playback as described in #21645 
Closes #21645 
- Checkout to this PR;
- Into the development environment (BBB server or container): go to the record-and-playback directory and run `./deploy; sudo systemctl restart bbb-rap-starter; sudo systemctl restart bbb-rap-resque-worker.service`
- Then clone https://github.com/bigbluebutton/bbb-playback and checkout to my PR there;
- Run `./deploy` of the playback;
- Record a session and wait until the recording is generated (this may take a while);
- See results.
Closely related to https://github.com/bigbluebutton/bbb-playback/pull/286
Demo: …
> feat(record-and-playback): Added chat features to recordings

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
Does a small change to the position of the message time label, preventing it from both overlapping the message text and being overlapped by the toolbar.
n/a
> fix(chat): Slightly tweak message time label position

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This fixes a few cases that could result in 500 errors when using templated logoutUrl (after https://github.com/bigbluebutton/bigbluebutton/pull/20965)
Also might lay the foundation to help the work being done here: https://github.com/bigbluebutton/bigbluebutton/pull/21204
> fix(bbb-web): Prevent redirect with invalid characters

- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
Adds a check when determining the number of moderators in meeting to see if a moderator has left before including them in the total.
Closes #21749
1. Create meeting
2. Join the meeting as a moderator
3. Call `getMeetingInfo` to see the number of participants and the number of moderators
4. Leave the meeting
5. After 20-30 seconds call `getMeetingInfo` to check that the number of participants and moderators is correct.
> fix(bbb-web): Check to see if moderator has left in moderator count

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/component.tsx
- Fixes a bug where the chat scroll goes off after the user clicks a reply, closes the chat, and then opens it again. Such bug happens when the replied message is in the same page as the reply message.
n/a
> fix(chat): Scroll going off after clicking a reply

- bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
This PR moves the chat resizing trigger to the side (very very slightly), so the scrollbar on the chat could become easier to click.
Closes #21471 
Create a meeting, spam the chat with message so the scroll would appear, then try and click it.
> style(sidebar): Update sidebar handle styles to improve chat scroll.

- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR improves the handling of ongoing shape editing. It replaces the manual approach of setting `editingShape` to null with the `complete()` method from the tldraw API. This ensures that all in-progress interactions, such as shape editing, are properly finalized and ended.
The previous method of manually setting `editingShape` to null was insufficient and could result in the error: "Uncaught Error: Expected an editing shape!"
before:
after:
> fix(whiteboard): Use complete api call to end shape editing

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR attempts to fix a null error crash in the whiteboard component that occurred under specific conditions when joining sessions.
This error was happening in some cases on join
> fix(whiteboard): Prevent null error crash during session join

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/service.js
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
Fix for an issue with latest Google Chrome version where the browser would not request the slide image when "snapshot of current slide" is used - we need to manually replace the image URL with a base64 version.
Closes #18739
1. join a meeting on latest google chrome (131.0.x)
2. try to use "snapshot of current slide" feature
> fix: Snapshot of slide shows only annotations but no image

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
The authentication for Graphql endpoints was not considering the config `allowRequestsWithoutSession`.
This PR fix it and add an warning for this config that will help to better understand the reason of its existence.
[Screencast from 2024-11-25 17-06-42.webm](https://github.com/user-attachments/assets/18d649f9-a952-45f0-96dd-52d095554afc)
Fix: #21697 #21129
> fix: `allowRequestsWithoutSession` not working for Graphql endpoints

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GroupChatMsg.scala
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/core/enums/chat.ts
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
Automatically send a chat message announcing when a new presenter is set.
It is enabled by default, but there is a config to disable at `settings.yml`, `public.chat.announcePresenterChangeInChat`.
Closes: #21573
> feat: announce new presenter in chat, under config `announcePresenterChangeInChat`

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/styles.js
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
moves the whiteboard options button to the right side (left in RTL languages)
> move whiteboard options button to right

- .github/workflows/automated-tests.yml
- build/packages-template/bbb-graphql-server/build.sh
- build/packages-template/bbb-graphql-server/opts-jammy.sh
Switches the required version for `postgresql` from the recently added 17
to the version which comes with Ubuntu 22.04 -- `postgresql-14`
Closes #21441 
Together with  https://github.com/bigbluebutton/bbb-install/pull/759 closes #21386 
When we/I added the code from https://github.com/bigbluebutton/bbb-install/pull/759
that allowed for postgres to get upgraded on reruns of bbb-install.sh
See #21386 for the mess that created (basically no predictability on which postgres you are using)
Also that meant we could not reliably override configs for postgres - see #21441 
https://github.com/bigbluebutton/bigbluebutton/pull/21588 was an attempt to add predictability
however, we could still not guarantee that version 17 would be used if bbb-install.sh was to silently pull version 18 later on. …
> !build: Use the default postgresql version (14) for Ubuntu 22.04

- bigbluebutton-html5/imports/ui/components/actions-bar/screenshare/component.jsx
- bigbluebutton-html5/public/locales/en.json
Adds missing string locale in screenshare button
disable "enable other participants desktop sharing" and make user presenter
> fix: missing locale string

- bigbluebutton-html5/imports/api/audio/client/bridge/livekit.ts
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/livekit.ts
- bigbluebutton-html5/imports/ui/components/livekit/component.tsx
- bigbluebutton-html5/imports/ui/components/screenshare/service.js
- bigbluebutton-html5/imports/ui/components/video-provider/livekit-camera-bridge/component.tsx
- [fix: typo in fallback LiveKit URL](https://github.com/bigbluebutton/bigbluebutton/commit/ced120c15f36720724e0312ee47a2f905171bd10) 
- There's a typo in the fallback LiveKit URL generation when parsing the
client's setting which would made the URL be nil if the livekit config
object was unset.
- [refactor(livekit): add additional debug logging](https://github.com/bigbluebutton/bigbluebutton/commit/9e837f88f3a23673c627a27704674efcd2be853c) 
- Add additional debug logging to LiveKit based A/V/screen share to be
able to capture more information on testing phases.
Take the oportunity to standardize messages with a `LiveKit` prefix and
logCodecs with a `livekit_` prefix.
None
> fix: typo in fallback LiveKit URL, log improvements

- .github/workflows/automated-tests.yml
The removal of `apt-updates` in the second attempt was introduced when the ci was running slowly.
It is not necessary anymore since #21612
This step was sometimes causing this problem:
> fix (ci): Undo "Remove apt-updates of bbb-install (on retry)"

- bigbluebutton-html5/imports/ui/components/common/file-reader/component.jsx
Adjusts virtual background upload toast to work after #21695
Closes #21346
> fix: adjust virtual background upload toast styles

- bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
- docs/docs/data/create.tsx
- docs/docs/data/join.tsx
- docs/docs/development/api.md
Removes:
API Params (`/create`):
- `learningDashboardEnabled` (replaced by `disabledFeatures=learningDashboard`)
- `virtualBackgroundsDisabled` (replaced by `disabledFeatures=virtualBackgrounds`)
- `breakoutRoomsEnabled` (replaced by `disabledFeatures=breakoutRooms`)
Configs (`bigbluebutton.properties`)
- `learningDashboardEnabled` (replaced by `disabledFeatures=learningDashboard`)
- `breakoutRoomsEnabled` (replaced by `disabledFeatures=virtualBackgrounds`)
Docs:
- `/join joinViaHtml5` (param no longer exists)
- `/create keepEvents` (param no longer exists)
- And removes info about params removed in this PR
> api/docs: Removes a few deprecated params

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
- bbb-graphql-middleware/internal/common/CustomCache.go
We have a global lock mechanism to prevent processing the same message multiple times #19964. Initially, the cache of locks was expected to be needed for at most 30 seconds. However, in high-access scenarios, some messages are taking longer than 30 seconds to arrive and be processed.
This led to a situation where a routine could acquire a lock on an ID at, say, the 30th second and attempt to unlock it later, but the lock would no longer exist because it was removed from the cache after 30 seconds. This caused errors and inconsistent behavior.
**Solution:**
This PR implements a reference counter for each lock to track how many routines are currently using it. Instead of removing locks based on a time threshold, a lock will now only be removed from the cache when all routines have released …
> fix (gql-middleware): Implement reference-counted locks to resolve concurrency issues in global cache

- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/ExternalVideoModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PermissionCheck.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/ScreenshareModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EjectUserFromBreakoutInternalMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/UpdateBreakoutRoomsTimeMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserAwayReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRaiseHandReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GenerateLiveKitTokenRespMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/webcam/UpdateWebcamsOnlyForModeratorCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/graphql/GraphqlMiddleware.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GetGuestsWaitingApprovalReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeUserGenerator.scala
- akka-bbb-apps/src/universal/conf/application.conf
- bbb-graphql-middleware/cmd/bbb-graphql-middleware/main.go
- bbb-graphql-middleware/internal/websrv/reconnectionHandler.go
Currently, when a user joins, changes roles, becomes a presenter, or leaves, Akka-Apps:
1. Updates the database.
2. Sends a Redis message to `graphql-middleware` to invalidate and restart the GraphQL connection with Hasura.  
This ensures the connection reflects the new session variables (e.g., role changes). However, the current approach is asynchronous and does not guarantee that the GraphQL connection will restart before the client receives the new status and begins sending queries with expectations of the updated role.  
In cases where the server is slow, this creates a race condition where the client queries using outdated session variables.
This PR introduces a new synchronous HTTP endpoint in `graphql-middleware` to manage GraphQL reconnections. The new flow ensures Akka-Apps can: …
> fix (gql-middleware): Introducing synchronous graphql reconnection endpoint to resolve race condition issues

- bbb-common-web/src/main/java/org/bigbluebutton/api/service/ValidationService.java
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Replace the tokens in the logout Url on the server rather than in the client.  This is possible after the implementation of logout url per user (see #21204 and #20285)
This is a follow up PR for #20285 
Promised to do this follow up work in the already merged pr #20285 
Join a meeting by api, and set a logout url including tokens such as `%%USERID%%`  or `%%MEETINGID%%` or `%%USERNAME%%`
Observe whether the tokens are replaced as soon as you logout of the meeting.
> refactor: Replace tokens in the logout url on the server

- docs/docs/new-features.md
- [docs: add note on LiveKit + Node.js 22](https://github.com/bigbluebutton/bigbluebutton/commit/6dd7f874a11920ade7096cbfd491f4e8d1729541) 
- Older 3.0 installations might still be using Node.js 18. LiveKit's
controller module requires Node.js 22. Add an extra step to remind users
to check their Node.js version before trying out LiveKit.
None
> docs: add note on LiveKit + Node.js 22

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/GetUserApiMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserSessionTokenReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserMetadata.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/UserSessionTokenDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/service/UserInfoService.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMsgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSession.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/RegisterUserSessionToken.java
- bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_session.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_session_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/tables.yaml
- bigbluebutton-html5/imports/ui/Types/user.ts
- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
- bigbluebutton-html5/imports/ui/core/graphql/queries/currentUserSubscription.ts
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This PR adds new parameters to the `/getJoinUrl` API, restoring some functionality from the previous 2.7 version. 
Previously, certain user properties could be adjusted via `getJoinUrl`. However, after internal discussions, we decided on a different approach. Instead of altering user properties like name directly, users can now "clone" themselves by generating a new `sessionToken` associated with the same `userId`. This ensures that the new session will appear as the same user in the user list, maintaining the correct user count. As a result, it's no longer possible to change the user’s properties after the session is created.
With this PR, the following parameters can be passed to `/getJoinUrl` for a specific session:
- `enforceLayout`
- Any parameter prefixed with `userdata-*`
- …
> bbb-web: Improve `getJoinUrl` by supporting `enforceLayout` and `userdata-*` params

- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_session.yaml
Add aggregate permission for Type `user_session`, that was missing on #21836 .
```gql
subscription {
user_session_aggregate(where: {connectionsAlive: {_gt: "0"}}) {
aggregate {
count
}
}
}
```
```json
{
"data": {
"user_session_aggregate": {
"aggregate": {
"count": 2
}
}
}
}
```
> gql-server: Allow aggregation queries for graphql Type `user_session`

- bigbluebutton-html5/imports/ui/components/join-handler/guest-wait/component.tsx
removes `3/5` text from guest lobby
#21709
> refactor: remove loading steps text from guest lobby

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
- bigbluebutton-html5/imports/ui/components/video-preview/service.js
- bigbluebutton-html5/private/config/settings.yml
- [fix(webcam): add option to skip initial enumerateDevices](https://github.com/bigbluebutton/bigbluebutton/commit/31a3e9cc221c2ba17c840323871025d385a9ef4d) 
- See: https://github.com/bigbluebutton/bigbluebutton/issues/21746
The client currently does an enumerate -> optional gUM -> enumerate flow
(the last enum only if necessary - i.e.: fingerprinting measures were in
effect in the first enumerate), which is an attempt to save extra
enumerate/gUM calls whenever necessary. The fact that it's breaking gUM
in Firefox seems like a browser bug, but we should work around it.
- Add a flag (public.media.skipInitialCamEnumeration) that allows skipping
the initial optimistic enumerateDevices call to try to work around the
aforementioned issue.
Might close #21746
> fix(webcam): add option to skip initial enumerateDevices

- bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
fix character escape in guest management panel
Closes #21852
1. Join a session as moderator
2. Switch the guest policy (from gear icon menu) to Always ask
3. Join as a viewer (waiting in the lobby)
4. Have the moderator send a message to the lobby which includes ', for example `I'm your father`
5. Check message in guest management panel
> fix: Apostrophe character not displayed correctly in guest panel [2.7]

- bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/RecordingServiceFileImpl.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/service/impl/XmlServiceImpl.java
- docs/docs/development/api.md
Removes the excess pagination data from the paginated `getRecordings` response. The response is now nearly identical to the unpaginated response except for the addition of a `totalElements` tag that indicates the total number of recordings that matched the specified criteria. Below is an example of the new paginated `getRecordings` response.
```
<response>
<returncode>SUCCESS</returncode>
<recordings>
...
</recordings>
<totalElements>3</totalElements>
</response>
```
Additionally, there was a bug in determining the total number recordings due to recording metadata with the same `recordingID` being merged in the construction of the response. The total number of elements was being calculated based on the unmerged number of recordings and therefore would sometimes report that there are more …
> Refactor(bbb-web): Remove unnecessary pagination data and fix total elements bug 

- build/packages-template/bbb-graphql-server/build.sh
Previously, the BBB build process installed the Hasura CLI by calling an external script hosted on:  
<https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh>
This approach was not ideal because it relied on code outside of our control. To address this, this PR replicates the essential logic from that external script directly into our own build process. Ensuring full visibility into the installation steps.
*Suggested by @danimo* https://github.com/bigbluebutton/bigbluebutton/issues/20083#issuecomment-2079352523
**Closes #20083**
> refactor (build): Stops calling external script to install Hasura CLI

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/reaction-item/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/reaction-item/styles.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-reactions/styles.ts
- bigbluebutton-html5/public/locales/en.json
Add reaction emoji shortcodes to the reaction tooltip label.
Add reaction item accessibility string.
Extract reaction item in its own component.
n/a
> fix(chat): Add emoji shortcodes to message reaction labels

- bigbluebutton-html5/run-prod.sh
- build/packages-template/bbb-html5/bbb-html5.nginx.dev
This PR simplifies the process of updating labels in the HTML5 project by ensuring that browsers automatically recognize and display the latest label changes without manual intervention.
1. **Dynamic Locale Directory:**  
Nginx will now attempt to load locale files from `/home/bigbluebutton/src/bigbluebutton-html5/public/locales`, which is the default directory in a Docker development environment. If that directory is not available (e.g., in production), it will gracefully fall back to using `/usr/share/bigbluebutton/html5-client/locales`.
2. **No-Caching Headers for Locales:**  
To avoid issues with stale labels, this PR adds HTTP headers that prevent browsers from caching the locale files. As a result, any changes to labels are reflected immediately, with no need to clear browser caches …
> improvement (html5): Automatically fetch locales from project directory in development environment

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-form/service.ts
updates chat regex to allow images and do not allow links that do not start with http:// or https://
Closes #21751
join a session and send messages with links in the chat
> fix: Enhance link detection to avoid mistakenly identifying strings that are not intended to be links

- bigbluebutton-web/gradle.properties
Porting https://github.com/bigbluebutton/bigbluebutton/pull/21824 to BBB 3.0+
> [3.0]chore(sec): bump embedded tomcat to 9.0.96

- bbb-common-web/project/Dependencies.scala
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/UploadedPresentation.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfSlidesGenerationService.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PngCreatorImp.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationConversionCompletionService.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/S3FileManager.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/TarGzManager.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/TextFileCreatorImp.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ThumbnailCreatorImp.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
- docs/docs/administration/customize.md
This functionality stores outputs such as PDFs (separated per page), SVGs, PNGs, thumbnails and text generated from PDFs or document files uploaded as presentations.
The processed outputs are cached in an S3-based storage system, keyed by a hash of the presentation file.
When the same presentation is uploaded again, the system retrieves the cached outputs, avoiding redundant processing and improving performance.
The configs should be set at `/etc/bigbluebutton/bbb-web.properties`:
```
presentationConversionCacheEnabled=true
presentationConversionCacheS3AccessKeyId=
presentationConversionCacheS3AccessKeySecret=
presentationConversionCacheS3BucketName=
presentationConversionCacheS3Region=
presentationConversionCacheS3EndpointURL=
presentationConversionCacheS3PathStyle=false
```
> feat (bbb-web): Introduces S3-based cache for presentation assets

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
- bigbluebutton-html5/imports/ui/services/notification/index.js
This PR fixes an error that made the snapshot of the current slide show a blank card instead of the toast.
Closes #21872 
Start a meeting and snapshot a slide.
> fix(presentation-menu): Refactor toast notification to use the correct method for displaying info.

- record-and-playback/video/playback/video/css/video.css
- record-and-playback/video/playback/video/js/popcorn.chattimeline.js
- record-and-playback/video/scripts/process/video.rb
The chat panel in the video recording format is restyled to look more like the live BigBlueButton session, with timestamps shown beside the user names and chat bubbles.
Emoji reactions are added, and so are replies (which show the first line of the message being replied to). The user's name is only shown for the first message sent in a series of messages by the same user.
The entire Popcorn plugin for chattimeline is basically rewritten, in a more modern JS style, and to build the more complex HTML elements needed for the new chat features.
The video format recording processing script is updated to add some additional required attributes to the chattimeline in the video.xml file. Note that because this is processed by Popcorn, the XML structure is somewhat limited - nested elements like …
> recording: BBB3 chat features for video recording format

- bigbluebutton-config/bin/bbb-conf
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/21903
[3.0.0-beta6] WEBHOOKS_APP_PORT null in `bbb-conf --check`.
Closes #21903
Fixes the false positive warning I found in bbb-v3-beta-6.
Test if the warning in bbb-conf --check is still displayed.
> Fixes issue #21903: [3.0.0-beta6] WEBHOOKS_APP_PORT null in bbb-conf --check

- bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/service.ts
Adds missing parameter in joinMicrophone method, that was causing an error when leaving a breakout room
2. join with audio in the main room
3. join in a breakout room
4. click to leave the breakout room
5. see error in the main room
> fix: audio rejoin after breakout

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
This PR fixes a bug where the user would create more than 2 breakout rooms and when updating those rooms, would be able to update only room  1 and 2.
Closes #21760 
Start a meeting, play around with creating and updating breakout rooms.
Before
After
> fix(breakout-room/create-breakout-room): Refactor initial state for number of rooms in `CreateBreakoutRoom` component

- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_componentsFlags.yaml
Introduces two components flags suggested by @Tainan404.
Using these flags allows the client to easily decide which components to render without needing to create a separate subscription for this validation.
```gql
subscription {
meeting_componentFlags {
hasCurrentPresentation
isSharedNotedPinned
}
}
```
> gql: Add flags `hasCurrentPresentation` and `isSharedNotedPinned` for `componentsFlags`

- bigbluebutton-html5/imports/api/bbb-web-api/index.ts
The Html5 Client retrieves the API URL from `/bigbluebutton/api` and stores it in session storage. If the API URL changes, the client may continue using the outdated URL from the cache.
**Solution:**  
- **Remove Session Storage:** Eliminate caching the API URL in session storage.
- **Use In-Memory Singleton:** Store the API URL in a singleton in-memory object, ensuring it only persists until the browser is refreshed.
Closes #21927
> fix (html5): Store API URL In-Memory to avoid Session Storage caching issues

- .github/workflows/automated-tests.yml
Increasing the volume of logs helps us identify why some tests are failing.
This PR enables `debug` level logging for the following components:
- Etherpad-lite
- BBB-Pad
- Hasura
- Graphql-actions
> ci: Enables `debug` level logging for  for `etherpad`, `bbb-pads`, `hasura` and `gql-actions`

- .github/workflows/automated-tests.yml
Installs Sipp in CI server as it enable to run tests for dial-in users.
With sipp installed it is possible to simulate a dial-in user by running:
```
VOICE_BRIDGE=76034
cd /opt/sipp
sudo sipp -sn uac_pcap -m 1 -aa -d 30000 -s $VOICE_BRIDGE "$(hostname -I | awk '{print $1}')":5060
```
Replacing the VOICE_BRIDGE with the same number used during `/create` of the meeting.
More info: https://github.com/SIPp/sipp.git
> ci (automated tests): Install Sipp (for future dial-in user tests)

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-web/bbb-web.nginx
The client periodically requests a static endpoint to measure its round-trip time (RTT) with the server. Currently, this endpoint is named `/ping`, which can be misleading, as it might be mistaken for a keep-alive request or confused with the periodic GraphQL "ping" used to check if the client is still connected.
This PR renames the endpoint to `/rtt-check` to clearly indicate its purpose: measuring the client’s RTT to the server.
> refactor (bbb-web): Rename endpoint `/ping` to `/rtt-check` to clarify its purpose

- bigbluebutton-html5/imports/ui/components/common/error-boundary/error-boundary-with-reload/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This pull request resolves an issue where the error boundary for the whiteboard in breakout rooms fails to recover when a crash occurs. The recovery mechanism does not properly trigger in breakout rooms because the listeners are not yet attached when the error boundary renders its children.
Closes #21952
> fix(whiteboard): Delay rendering of error boundary children until listeners attach

- bigbluebutton-html5/imports/ui/components/common/error-boundary/component.jsx
This PR adds a log in the error boundary showing the stack trace for better debugging of crashes, I've tried to modify the logger to show more info, but the browser bunyan converts the error to string showing the path of the bundle instead the reference to the line like in a normal log.
- Deploy the code to production.
- Join as presenter.
- reload the client until the crash happens.
Before:
After:
Demo:
[Screencast from 09-01-2025 21:39:21.webm](https://github.com/user-attachments/assets/1ba47f62-5bbb-44d3-af6a-a468177cea46)
> Add: New log showing the error caught by error Boundary component

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/poll-content/styles.ts
- bigbluebutton-html5/imports/ui/components/poll/components/CustomizedAxisTick.tsx
- bigbluebutton-html5/imports/ui/components/poll/components/LiveResult.tsx
Shorten overly long poll options by wrapping the text and appending `...` (ellipsis) to it.
Closes #21878
test file for Smart Slides: [long_poll (1).pdf](https://github.com/user-attachments/files/18379794/long_poll.1.pdf)
> fix(poll): Wrap overly long poll options

- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
- bigbluebutton-html5/private/config/settings.yml
- docs/docs/administration/customize.md
introduces **showSessionDetailsOnJoin** parameter, making it possible to change the session details modal initial state when joining a meeting
Closes #21886
https://github.com/bigbluebutton/bigbluebutton/issues/21886#issuecomment-2552108002
1. set `public.layout.showSessionDetailsOnJoin` as `true` in the settings file or use the join parameter `userdata-bbb_show_session_details_on_join=true`
2. join the meeting and the session details modal should open
> feat: introduce showSessionDetailsOnJoin parameter

- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
Restores keyboard navigation using tab on recording button.
Closes #21984
1. Create a meeting
2. Try to navigate with tab past the recording button
> fix: Tab stops on recording button

- bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
The original purpose of the error screen was to display issues occurring on the server side, such as unauthorized access or network problems, which prevented the client from communicating successfully. However, it’s now also being used by several components within the client itself whenever a component crashes. In these cases, it doesn’t make sense to stop the audio or display a login error. Therefore, it’s better to remove those behaviors from the error screen and let it simply serve as a display, while leaving error handling to error boundaries (as is currently done).
> Remove: Side effects from error screen

- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/LearningDashboardActor.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/LearningDashboardService.java
Fix a few issues reported by @ritzalam 
- LAD data file is being written twice every time.
- Errors on saving the LAD file is not being captured by journal logs (cause it is a `System.out`).
- In case of error on saving the LAD file, it would not close the `FileOutputStream` properly.
> fix (bbb-web/akka): Fix a few Learning Analytic Dashboard related issues

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
Adjusts breakout creation modal so the checkboxes use default value from settings file
Closes #21950
1. change any (or all) setting related to the breakout checkboxes default value (`public.app.breakouts.allowUserChooseRoomByDefault`,`public.app.breakouts.captureWhiteboardByDefault`,`public.app.breakouts.captureSharedNotesByDefault`,`public.app.breakouts.sendInvitationToAssignedModeratorsByDefault`, )
2. join a meeting
3. open "create breakout rooms" modal
4. verify if the checkboxes with default values set as `true` are checked
> fix: Breakout defaults from bbb-html5.yml not respected

- bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx
- bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
Adjusts sidebar styles so the chat and other types of content appear correctly on mobile devices.
Closes #21930
1. Start meeting
2. Enter meeting on a mobile device
3. Try to open chat or public note
> fix: chat does not open on mobile devices

- bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/component.jsx
- bigbluebutton-html5/imports/ui/components/video-preview/virtual-background/styles.js
Changes upload virtual background icon and adjusts icon size/padding
Closes #21978
> Use upload icon for add background for webcam

- docs/bbb-docs.nginx
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/run-dev.sh
This PR introduces a `run-dev.sh` script, consistent with other BBB projects, to simplify running documentation in a development environment using BBB Docker DEV.
- Sets up a `/docs` endpoint in the Nginx server.
- Provides easy access to the documentation at `https://bbb-docker-host/docs`.
1. Run the script inside the container:
```bash
./run-dev.sh
```
2. Open your browser and navigate to the suggested URL:
```
https://bbb-docker-host/docs
```
> docs: Add `run-dev.sh` Script for Running Docs in Development

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- docs/docs/data/create.tsx
- docs/docs/development/api.md
Adds the following samples in `bigbluebutton.properties`:
```
disabledFeatures=deleteChatMessage, editChatMessage, replyChatMessage, chatMessageReactions
```
And adds the following docs:
---
> docs: Add docs for `disabledFeatures` options of new chat features

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Replaces Apollo's deprecated callback `onSubscriptionData` with the recommended `onData`. See https://www.apollographql.com/docs/react/api/react/hooks#onsubscriptiondataoptional.
Closes #21997
The abovementioned issue is caused when the client browser has [React Dev Tools](https://react.dev/learn/react-developer-tools) installed on it. For some reason, React Dev Tools runs some kind of overriding on the [Console](https://developer.mozilla.org/en-US/docs/Web/API/console) interface, which by itself alone can be problematic.
It turns out that the Apollo's `useSubscription` hook also runs some kind of overriding on the same interface for its log system, which is triggered when using a deprecated `useSubscription` option in production.
Both may be conflicting with each other when overriding …
> fix(whiteboard): Fix whiteboard crash on reload

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/ImageResolution.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/handlers/ImageResolutionServiceHandler.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ImageResolutionService.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ImageSlidesGenerationService.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
This PR updates the method for obtaining the resolution of image files during presentation uploads. Instead of using `ImageIO.read`, the system now relies on the `identify` command from ImageMagick.  
`ImageIO.read` was causing `java.lang.OutOfMemoryError: Java heap space` when attempting to read large image files. Switching to `identify` resolves this issue by offloading the resolution detection to an external, memory-efficient tool.
> refactor (bbb-web): Use `identify` (ImageMagick) for image resolution in presentation uploads

- bigbluebutton-html5/imports/ui/components/whiteboard/service.js
- bigbluebutton-html5/public/svgs/tldraw/arrow-left.svg
This PR adds the missing tldraw icon for arrow-left, resolving the issue where the icon was not found.
The absence of the arrow-left icon caused a console error when it was referenced.
> fix(whiteboard): Add missing tldraw arrow-left icon

- bigbluebutton-tests/playwright/breakout/join.js
- bigbluebutton-tests/playwright/presentation/presentation.js
Replaces all actions of closing toast notification for its related function, so the action will be the same in every case
There were some CI failures due to missing timeout, which got PW stuck into the closing toast action
> test: Replace closing toast for its related function

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/livekit/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- [feat(livekit): make room options configurable, enable adaptiveStream](https://github.com/bigbluebutton/bigbluebutton/commit/1bb9c2b8bf124bfdc77bef64bba821d3a268e3ae) 
- Make LiveKit's room options configurable via the client's configuration.
Additionally, enable adaptiveStream by default (as well as dynacast,
even though that it largely unsupported in our VP8-only scenario).
None
Ref #21059
> feat(livekit): make room options configurable, enable adaptiveStream

- record-and-playback/core/lib/recordandplayback/edl/audio.rb
- record-and-playback/core/lib/recordandplayback/generators/audio.rb
- record-and-playback/core/lib/recordandplayback/generators/events.rb
- record-and-playback/core/scripts/archive/archive.rb
- record-and-playback/core/scripts/bigbluebutton.yml
Adds support for livekit audio capture events and files.
Basically the audio edl now stores all active audios at each moment and when more than one audio is present they are mixed together in the render method.
Previous behaviour for other events is preserverd.
Sample event por reference:
```
<event timestamp="3173077711" module="bbb-webrtc-sfu" eventname="AudioTrackPublishedEvent">
<userId>w_fodi3y98tzex</userId>
<source>microphone</source>
<meeting_id>bd86fde4446324b79e3fb3f31ae67e4c67a57405-1736419145593</meeting_id>
<filename>/var/lib/bbb-webrtc-recorder/audio/bd86fde4446324b79e3fb3f31ae67e4c67a57405-1736419145593/microphone-w_fodi3y98tzex-TR_AMi4Y5RdyzdbNR.ogg</filename>
<timestampUTC>1736419164951753770</timestampUTC>
</event>
```
Needs a livekit setup with egress to record
1. …
> feat(recording): livekit track-based audio processing

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- When the client is starting up the whiteboard seems to be doing some kind of zoom initialization which is affecting some effects of the presentation component. A timeout was added to ignore presentation restoration in the first 5 seconds after client startup. This fixes a bug where the config `bbbHidePresentationOnJoin` does not take effect.
Closes #21581
> fix(whiteboard): Add timeout for ignoring presentation restoration on new events

- bigbluebutton-html5/imports/ui/components/raisehand-notifier/component.jsx
- bigbluebutton-html5/imports/ui/components/raisehand-notifier/styles.js
Just a fix in the raise hand notification's CSS
Closes #22043
If one finds it fit, it would be nice to also test the other notifications, since the recent updates in the react-toastify of https://github.com/bigbluebutton/bigbluebutton/pull/22024
See the fixed behaviour in the demo below:
https://github.com/user-attachments/assets/d0191c9e-82b1-46f1-9c2f-e368dbc3aa1c
> fix: Fix raise hand notification CSS with recent updates 

- bigbluebutton-tests/playwright/audio/audio.spec.js
- bigbluebutton-tests/playwright/parameters/parameters.spec.js
- bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
- bigbluebutton-tests/playwright/user/multiusers.js
Adds flaky flags on 3 tests failing in recent CI runs:
- `Force restore presentation on new events`: not restoring presentation after zooming in;
- `Pin and unpin notes onto whiteboard`: not restoring presentation after unpinning notes;
- `Mute yourself by clicking the mute button`: looks like it's not unmuting/muting correctly - mic button keeps in current state
- `Raise and lower Hand` test step fixed, also failed in recent CI runs
> test: Flag recent CI test failures as flaky

- bbb-graphql-server/bbb-graphql-schema.md
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_learningDashboard.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_meeting_usersPolicies.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_poll_user.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_curr.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_annotation_history_curr.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_pres_page_cursor.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_camera.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_connectionStatus.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_connectionStatusReport.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_guest.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_livekit.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_reaction.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_reaction_current.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_private.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_typing_public.yaml
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_user_voice.yaml
- Remove `v_` from type names that contained it
- Include `meetingId` as condition to all relationships
- Remove unused relationships
- Include Type Permission details (Moderators, Presenter, Self-Related Data)
- Create link for relationships (appointing to Type)
- Include field type of relationship (Object 1:1 or Array 1:n)
- Remove Types that is not possible to query directly
> Refactor (gql-server) Standardize type names and relationship condition (and improve ref document)

- .github/workflows/automated-tests.yml
This PR sets the same ubuntu version as the other steps, also to avoid the following warning
> ci: Specify ubuntu version on upload-report step

- bbb-graphql-middleware/internal/websrv/connhandler.go
If a connection does not supply the expected CORS headers, the websocket will not return a connection. So that would leave a stack trace in the logs without indication for the reason.
Not reported as issue yet.
> fix(middleware): check browser connection before using it

- bigbluebutton-web/grails-app/services/org/bigbluebutton/web/services/PresentationService.groovy
This PR modifies the logic for handling presentation uploads to improve the process of waiting for the meeting to be created. Previously, the system waited for a fixed delay of **5 seconds** before proceeding with the presentation conversion. Now, the logic has been updated to **check every 1 second** if the meeting has been created and is running, allowing the process to start sooner if the meeting becomes available.
This change is particularly beneficial for uploads during an ongoing meeting, as the meeting is already created, and the process can start immediately without waiting.
<table>
<tr>
<td>Before (8 seconds):</td>
<td>After (2 seconds):</td>
</tr>
<tr>
<td>
[Screencast from 2025-01-27 09-32-39.webm](https://github.com/user-attachments/assets/323ad504-577f-4bc2-95a7-4546e4f00221) …
> refactor (bbb-web) Speed up upload of presentations by removing a fixed delay

- build/packages-template/bbb-graphql-server/build.sh
- build/packages-template/bbb-livekit/build.sh
- build/packages-template/bbb-webrtc-recorder/build.sh
If the packages are built with umask 0077 on the build system, the config files deployed by packages are not readable by the services. This fixes some new spotted places.
> build: fix config file permissions

- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx
This PR alters the leave meeting button and the end meeting button style - so the users don't accidentally click the end meeting by mistake.
Closes #20908 
Start a meeting and observe the end/leave meeting buttons on nav-bar area.
Before
After
> style(nav-bar/leave-meeting-button): Update button styles for better visibility and accessibility.

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/queries.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/services.ts
- bigbluebutton-tests/playwright/chat/chat.js
- removes welcome message from chat copy/save
- fix "user X is now the presenter" messages when chat is saved
Closes #22036
1. Start a session
2. Save the public chat (before posting anything) via the three dots menu -> Save
3. Copy+Paste the public chat via the three dots menu -> Copy
> refactor: Copy/Save chat needs to drop the Welcome message

- bigbluebutton-html5/imports/ui/components/pads/pads-graphql/component.tsx
fix issue where the shared notes buttons tooltips would be displayed in the wrong language after switching locales
2. open shared notes
3. change language in settings menu
4. save settings
5. see shared notes buttons
> fix: locale not updating in shared notes

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/chat-actions/component.tsx
fix issue where the chat dropdown options would be displayed in the wrong language after switching locales
2. change language in settings menu
3. save settings
4. see chat dropdown options
> fix: locale not updating in chat dropdown

- bigbluebutton-web/grails-app/services/org/bigbluebutton/web/services/PresentationService.groovy
Fix presentation upload bug introduced in #22089
The bug caused the presentation upload to wait for the meeting to be running before proceeding. However, this only happened after the first user joined. The correct behavior is to start the upload process as soon as the meeting is created.
> fix (bbb-web): Check if meeting is created (instead of running) to proceed with pres upload

- bigbluebutton-html5/imports/ui/components/session-details/component.tsx
- bigbluebutton-html5/imports/ui/components/session-details/styles.ts
adjusts session details modal to:
- correctly break text when displaying 2 columns
- only display login url for moderators
> refactor: adjust session details modal text

- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
Adjusts layout being incorrectly set on mobile
Closes #22053
1. Create a meeting
2. Join with three different users and then turn on their webcams
3. Join with another one on mobile
4. See the blue button
> fix: Button behind userList toggle on mobile

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/buttons/LiveSelection.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/styles.ts
- bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
- bigbluebutton-html5/imports/ui/components/common/menu/styles.js
- bigbluebutton-html5/public/locales/en.json
applies the following changes to the audio devices dropdown:
- adjusts titles ("Microphone" and "Speakers" text) font-weight to bold  
- removes separator (hr element) between titles and devices
- switch title icon to the left
- align available devices text with titles
- adjust current devices font-weight to bold
- increase the "current device" icon size and change color to green
Closes #22080
2. open audio devices dropdown
> style: restyle audio devices dropdown

- build/packages-template/bbb-etherpad/build.sh
Change `ep_cursortrace` plugin to mconf custom fork, it includes https://github.com/mconf/ep_cursortrace/pull/2, which fixes client slowing down when there's too many edits in shared notes in short time.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/21959
Join with two users, open shared nodes. Start typing as fast as you can in shared notes (or just keep a key pressed), see if client don't slow down.
> chore(etherpad): change ep_cursortrace to mconf's fork

- bigbluebutton-html5/imports/ui/Types/presentation.ts
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/utils.ts
- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
- bigbluebutton-html5/imports/ui/hooks/usePreviousValue.ts
It basically:
- Restores the check icon that appeared in the toast whenever a presentation was done uploading;
- Restore the clear error button behaviour (it wasn't necessary to confirm to remove presentation with errors);
- Fix an export problem related to latest changes in the presentation uploader component.
Closes #22038
I recommend one to test all possible scenarios of uploading presentations:
- Add multiple presentations;
- Add multiple presentations and remove one;
- Add presentations with Error;
- ...
Also, there is 2 other ways of uploading presentation client side:
- Convert shared-notes to presentation;
- And select option to save whiteboard and shared notes in breakouts creation;
If you think of any way of triggering the presentation toast, feel free to test it.
Here is a demo …
> fix(HTML5): Restore back 2.7 behaviours for presentation uploader

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/captions/component.tsx
Fix font rendering issue on message about lack of speech recognition support (issue only happens on chromium browser) by adjusting font-size of element.
1. enable audioCaptions
2. join a meeting on chromium (not chrome)
3. open audio modal
> fix: transcription warning font rendering issue

- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Fixes an issue where the whiteboard would reload incorrectly due to an error in the presentation uploader when switching presenters
before:
after:
related to #22119
> fix(html5): Presentation uploader causing error on presenter change

- bigbluebutton-html5/imports/ui/components/common/error-boundary/error-boundary-with-reload/component.jsx
similar to #22067, the whiteboard should not crash if a user tries to call an action and does not have permission for it.
if presenter is changed as soon as the client loads, the client will try to set the presentation zoom and fail due to the user not having presenter status anymore - this should not have side effects, and fail silently.
1. join a meeting with 2 users
2. change presenter as soon as the whiteboard loads
3. whiteboard should not crash and reload
> fix: Avoid reloading whiteboard due to permission error

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
Sets the `done` flag to `true` after rasterization to ensure that a blank SVG is not used for rasterized presentation pages. Also calculates the image resolution to use during rasterization based on the temporary PNG that is generated.
During presentation upload whenever a page needed to be rasterized the `done` flag was not being set to `true` after rasterization. Because of this it was assumed that an error occurred during SVG generation and therefore the default blank SVG would be used for that page.
Upload a document with pages that require rasterization. Before these changes any of these pages would be blank. After the pages should be displayed correctly.
> fix(bbb-web): Rasterized pages always blank

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts
- bigbluebutton-html5/imports/ui/core/utils/getStatus.js
This PR improves RTT logs by combining the setRttValue and setRttStatus functions into one. Previously, misunderstandings arose because these values could become unsynchronized. By consolidating both setters, we ensure that the logs always use the most up-to-date data, thereby displaying the correct values. 
Closes #22065
> fix(client): Connection status function accepting 2 params, meant to improve log readability

- bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meetings.ftlx
Uses computer format for numeric fields in the Freemarker `getMeetings` response so that numbers greater than 1,000 do not contain commas.
Closes #22102
Either join a meeting with at least 1,000 users or override the number of users returned [here](https://github.com/bigbluebutton/bigbluebutton/blob/c14393519b987e13ba8fbadcde9fb792b0b20a67/bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java#L794) and then call `getMeetings` and look at the numeric fields, specifically `participantCount`.
> fix(API): Remove commas from numeric fields in API responses

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the bug that occurs when a user becomes the presenter and the player reloads. The issue arises because the react-player library does not treat the controls prop as reactive; it only reads its value during mounting and doesn't update if that value changes.
(I've opened a issue for it on react-player repository https://github.com/cookpete/react-player/issues/1920)
Additionally, there was no straightforward way to distinguish between a user-initiated onPlay event and one triggered by the system. To address this, I introduced a new variable that detects client reloads and ignores the first onPlay handler call in those cases.
Closes #22090
- Join with two users.
- Play a external video.
- Pause the external video.
- Switch the presenter between users.
[Screencast from 30-01-2025 …
> Fix: External video autoplaying when presenter changes

- bigbluebutton-tests/playwright/breakout/breakout.spec.js
- bigbluebutton-tests/playwright/chat/chat.spec.js
- bigbluebutton-tests/playwright/layouts/layouts.spec.js
- bigbluebutton-tests/playwright/learningdashboard/learningdashboard.spec.js
- bigbluebutton-tests/playwright/notifications/notifications.spec.js
- bigbluebutton-tests/playwright/options/options.spec.js
- bigbluebutton-tests/playwright/parameters/parameters.spec.js
- bigbluebutton-tests/playwright/polling/polling.spec.js
- bigbluebutton-tests/playwright/presentation/presentation.spec.js
- bigbluebutton-tests/playwright/sharednotes/sharednotes.spec.js
- bigbluebutton-tests/playwright/user/user.spec.js
- bigbluebutton-tests/playwright/webcam/webcam.spec.js
Following the new UI changes + latest v3.1 CI outputs, this PR flags `145` tests as flaky (specifically `flaky-3.1` for easier filtering and further fixing) to avoid running on CI. All of these tests must be updated to follow the current steps with the new UI
> test: Flag all failing test with new UI as flaky

- .github/actions/upload-blob-report/action.yml
- .github/workflows/automated-tests.yml
This PR updates all workflow actions for `automated-tests` from v3 to v4, mainly the upload and download artifact version (now deprecated, see deprecation notice [here](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/))
**More**
it also backports a few needed changes to work properly with v4 actions
> ci: Update CI workflow actions version

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/styles.js
- bigbluebutton-html5/imports/ui/components/common/selector/component.tsx
- bigbluebutton-html5/imports/ui/components/common/selector/styles.ts
- bigbluebutton-html5/imports/ui/components/common/selector/types.ts
- bigbluebutton-html5/imports/ui/components/common/separator/component.tsx
- bigbluebutton-html5/imports/ui/components/common/separator/styles.ts
- bigbluebutton-html5/imports/ui/components/common/separator/types.ts
- bigbluebutton-html5/imports/ui/components/common/toggle-group/component.tsx
- bigbluebutton-html5/imports/ui/components/common/toggle-group/styles.ts
- bigbluebutton-html5/imports/ui/components/common/toggle-group/types.ts
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
This PR is a backport of #22001.
> This PR is the core part of the following PR in plugins-sdk repo: https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/141
> 
> - Adds proper handling and components for rendering the two new actions bar items that can be injected through plugins sdk: selector and toggle group.
> - Extend the Separator component to allow rendering icons as separators in the actions bar as requested by plugins sdk.
Just setup and run the sample actions bar example plugin from the plugins-sdk samples
> Backport of: feat(extensible-areas): add Actions bar generic component

- bigbluebutton-html5/imports/ui/components/layout/push-layout/hooks.ts
Adds a fallback value for the focused camera ID to 'none', which can be undefined while the layout context is still calculating the output values.
(originally part of #22108)
> fix(layout): focused camera missing required parameter

- bigbluebutton-html5/imports/ui/components/notifications/component.tsx
- bigbluebutton-html5/imports/ui/components/notifications/styles.ts
Adds the name of the waiting user to the notification title (like it was on 2.7).
Before:
After:
Set "Ask moderator" as guest policy, join with a guest and see notification for moderator.
> fix(notification): add guest user name to notification

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/webcam/component.tsx
- bigbluebutton-html5/public/locales/en.json
It improves user experience for screen reader users.
Add h2 elements to several elements of the user interface so users can consistently jump between them. This makes navigation consistent with other parts of the BBB UI such as the user panel.
In NVDA press `h` to open the headings navigation. There are new targets for talking indicator area, camera area (not translated yet), actions bar and icons on the top right corner of the screen.
I could not yet figure out how to make the `Cameras` string translatable. Hints would be apreciated.
> Accessibility: improve screenreader navigation

- bigbluebutton-html5/imports/ui/components/profile-settings/audio-selectors/component.tsx
- bigbluebutton-html5/imports/ui/components/profile-settings/component.tsx
- bigbluebutton-html5/imports/ui/components/profile-settings/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/guest-management/waiting-users/component.tsx
Supersedes https://github.com/bigbluebutton/bigbluebutton/pull/22136
- Round Camera Preview border
- Fix empty input/output devices
- Only add scrollbar to area below video preview
- Re-apply brightness after changing camera quality profile
- Save camera and profile in storage
- Fix unable to disable VirtualBackound toggle when there was brightness applied
- Disable camera quality selector when camera is already shared, add tooltip
- Change brightness slider sizes according to design
- Fix some extra white spaces
- Correct minimize label
Bonus: add onClick to Waiting Users header so all label and button can be clicked to expand to show waiting users.
> fix(profile-settings): several ui bug fixes

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/profile-settings/component.tsx
- bigbluebutton-html5/imports/ui/components/recording/container.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/service.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/user-name-with-subs/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
- bigbluebutton-html5/public/locales/pt_BR.json
This PR does several small things:
* Bots (automated users) can't be interacted with by moderators in the user list (no private chat, no control of whiteboard, etc...). The only button preserved is 'Remove User'
* Bots will now be labeled in the user list
* Fix the label for current user. In 3.0 it is marked by the '(you)' next to your name and on 3.1 it was only marked by bold text. We restored the behavior from 3.0
> Limit options for interaction with bots in the userlist and correct some styles 

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/private-chat-list/component.tsx
- bigbluebutton-html5/imports/ui/components/profile-settings/styles.ts
- bigbluebutton-html5/imports/ui/components/sidebar-content/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/crowd-action-buttons/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/styles.ts
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/styles.ts
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/general.js
Chats buttons only appers when has a active private conversation. Correction of padding, gap and colors in the sidebar contents.
Whitout private conversations
> [3.1] fix(sidebar-content): new chat buttons behavior and padding correction

- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/chat/loaded-chat-messages/hook-manager.ts
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/meeting/from-core/hook-manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/presentations/current-presentation/hook-manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/shared/custom-subscription/hook-manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/shared/custom-subscription/types.ts
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/user-voice/talking-indicator/hook-manager.ts
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/users/current-user/hook-manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/domain/users/loaded-user-list/hook-manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/data-consumption/types.ts
It fixes a strange behaviour that kept happening to some of our data-consumption hooks for the plugin-sdk, which is: data was not updated correctly in the first moments of the meeting.
The solution was to just change the way that the client core updates the data for the plugin whenever a new plugin subscribes to that data-consumption hook (now it updates based on the counter).  
Closes https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/119#issuecomment-2612663687
I advise you to test all data-consumption hooks, see if everything goes as expected, since the changes in this PR were more structural.
And to properly test if the issue has been resolved, follow the steps to first reproduce it, then apply the PR to see if it  doesn't happen:
- On a v3.0.x-release branch, add …
> fix(plugin-sdk): useCurrentUser not updating correctly

- docs/docs/data/create.tsx
- docs/docs/data/end.tsx
- docs/docs/data/getRecordings.tsx
- docs/docs/data/join.tsx
- docs/docs/data/publishRecordings.tsx
- docs/docs/data/sendChatMessage.tsx
- docs/docs/development/api.md
- docs/src/components/APITableComponent/index.tsx
- docs/src/components/APITableComponent/styles.module.css
Improve the formatting of the API parameters table to allow specifying minimum and maximum values, as well as minimum and maximum lengths for string values. These get displayed in the "Type" column below the data type name.
Alter the appearance of required and deprecated parameters to make required parameters stand out more, and more clearly indicate deprecated parameters.
I've reformatted some of the existing parameter entries to take advantage of the new features, and added or corrected descriptions to several parameters.
Here's how the `sendChatMessage` table looks following this change:
> docs: Document formatting updates and corrections for 3.0

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Since we're already propagating zoom changes on camera updates dispatched by tldraw state on this line https://github.com/bigbluebutton/bigbluebutton/blob/68f3a0ec3c1e8d16ab3a4a25676d5cc9b0f9ae99/bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx#L741
this PR removes duplicate logic which runs within a useEffect. This PR also slightly adjusts the condition for propagating zoom updates in order to comprise all cases.
Closes #21527
The removed code is sometimes being executed before the whiteboard canvas is rendered, so the zoom mutation is being called with some odd values, which in turn is messing with the viewers zoom.
There must not be zoom propagation regressions.
> fix(whiteboard): Remove duplicate zoom propagation

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
- Fixes a bug where the chat scroll does not stick to the bottom after sending a reply message.
- Fixes a bug where you are unable to load the previous message page by scrolling up if the chat scroll is already stuck at the top.
Closes #22018
> fix(chat): Unstable scroll + unable to load previous page

- .gitlab-ci.yml
Backport of #22210 (minus nodejs which is using 18.x rather than a specific pinned version)
> [2.7] chore: Newer image including bumped Go, grails

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/container.jsx
- bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
This PR adds an **access key shortcut (`X`)** to the **Leave Meeting dropdown menu**, making it easier for **screen reader users** to access the options.
Closes #22097
> fix: Add access key for leave meeting dropdown menu

- bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
- bigbluebutton-html5/public/locales/en.json
Adds touch gesture support for undo and redo functionality on the whiteboard:
- Two-finger tap for undo.
- Three-finger tap for redo.
**Note**: Users must not have the pencil tool selected when performing a redo action.
The undo and redo UI buttons were removed from the interface in favor of keyboard shortcuts. However, mobile users without keyboards needed an alternative way to perform undo and redo actions. This PR introduces touch gestures to address this.
> fix(whiteboard): Add touch gesture support for undo and redo

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/pinned-apps/component.tsx
- bigbluebutton-tests/playwright/breakout/breakout.spec.js
- bigbluebutton-tests/playwright/breakout/create.js
- bigbluebutton-tests/playwright/breakout/join.js
- bigbluebutton-tests/playwright/core/elements.js
- bigbluebutton-tests/playwright/core/page.js
- bigbluebutton-tests/playwright/parameters/disabledFeatures.js
- bigbluebutton-tests/playwright/stress/stress.js
- bigbluebutton-tests/puppeteer/breakout/create.js
Updates all breakout test steps to follow current steps with the new UI
- with the default viewport, tests were throwing errors since the little viewport has a bad button disposition:
- 1920x1080
> test(new-ui): Update breakout test steps

- bigbluebutton-html5/imports/ui/components/mobile-app-modal/component.jsx
Currently, the "Open in BigBlueButton in Table App" option requests a join URL from the `getJoinUrl` endpoint. However, it attempts to use the client's domain, which is incompatible with a Cluster setup. This PR adjusts the request to retrieve the domain from the `public.app.bbbWebBase` configuration.
Fix #22205
> fix (html5) (2.7): "Open in BigBlueButton in Table App" not working in cluster setup (using wrong api domain)

- bigbluebutton-html5/imports/ui/components/mobile-app-modal/mobile-app-modal-graphql/component.tsx
Currently, the "Open in BigBlueButton in Table App" option requests a join URL from the `getJoinUrl` endpoint. However, it attempts to use the client's domain, which is incompatible with a Cluster setup. This PR adjusts the request to retrieve the domain from the `public.app.bbbWebBase` configuration (`getBaseUrl`).
Fix #22205
> fix (html5) (3.0): "Open in BigBlueButton in Table App" not working in cluster setup (using wrong api domain)

- bigbluebutton-config/bin/bbb-record
Using `X` and ` ` to indicate presence / absence of recording components in the output of `bbb-record --list` and `bbb-record --list-recent` is not very helpful in a long table where the header runs out of sight. This patch uses the same letters as the header to indicate presence and `.` to indicate absence of components. This greatly improves readability of the table.
While I was at it, I also fixed the table header.
Before:
```
$ sudo bbb-record --list-recent | head -n16
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------ …
```
> impr(bbb-record): Clarify recording status output

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/private-chat-list/chat-list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/private-chat-list/component.tsx
- bigbluebutton-html5/imports/ui/components/common/control-header/right/component.jsx
- bigbluebutton-html5/imports/ui/components/profile-settings/audio-selectors/component.tsx
- bigbluebutton-html5/imports/ui/components/profile-settings/component.tsx
- bigbluebutton-html5/imports/ui/components/recording/container.tsx
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/component.tsx
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/container.tsx
- bigbluebutton-html5/imports/ui/components/user-list/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/user-name-with-subs/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/styles.ts
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-avatar/styles.ts
- bigbluebutton-html5/imports/ui/core/utils/keyboardRove.ts
Merge after: https://github.com/bigbluebutton/bigbluebutton/pull/22214
In the new design the learning analytics dashboard button in the navigation sidebar should not be visible for non-moderators.
Before:
After:
> [3.1] Hides learning analytics dashboard for non-moderators.

- bigbluebutton-tests/playwright/user/multiusers.js
Attempt to fix the following error:
Watching the video the aut test is able to open the dropdown:
But a few milliseconds later it loads the video and closes automatically:
This PR tweak the test to wait for the `<video>` element instead of the parent container.
> fix (tests): Improve 'Pinning and unpinning webcams'

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
disables webcam sharing button when a preview error is being displayed
Closes #22163
1. Create a meeting
2. Join the webcam and deny the permission
3. Try to start sharing the webcam
4. "Start sharing" button should be disabled
> fix: Whiteboard reloads with error message when webcam is denied

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/components/connection-status/button/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/component.jsx
- [fix(breakouts): validation of minimum breakouts duration](https://github.com/bigbluebutton/bigbluebutton/commit/2020512c62cac137b3033bcbebefbdb973682a93)
Prevents the duration input in the breakouts creation panel from
assuming values lower than the minimum, while still showing the error
message to inform users about the minimum duration.
- [fix(settings): move about to last tab](https://github.com/bigbluebutton/bigbluebutton/commit/d1392d56c71ba5eed751fd1dfdcd22003ab75810)
Moves 'about' to the last tab and leaves the 'application' as the first
tab.
> fix: minimum breakouts duration validation & settings tabs 

- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
- [fix: restore bbb_record_permission and bbb_record_permission_tooltip](https://github.com/bigbluebutton/bigbluebutton/commit/6bbe929092cc5c2d1553cc1555a31e733fcd367f) 
- Both userdatas were partially broken after re-implementing the
recording indicator.
- Correctly render bbb_record_permission_tooltip when appropriate (i.e.:
recording is paused and the user has no permission, following 3.0
behavior).
- Adjust places where bbb_record_permission was partially ignored when
rendering tooltips, titles and buttons.
None
> fix: restore bbb_record_permission and bbb_record_permission_tooltip

- bigbluebutton-tests/playwright/user/multiusers.js
This PR fixes an incorrect element expected in an assertion of the `User › Actions › Raise Hand Rejected` test. This incorrect element, however, didn't throw the test failure every time, only when it took a bit longer to load as it expected the previous state, not the current.
> test: Fix correct assertion element

- bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
The key is used as an id when it is lowercased.
However, here it was camelCased thus causing a discrepancy and
the internationalization was crashing the client
Corrects an issue with https://github.com/bigbluebutton/bigbluebutton/pull/22117 where the internationalization key was expected to be all lowercase but was camelCase instead
Closes # none
reported by @paulseto 
Load the client and try to open the Shortcuts table from the "kebob" button (where Settings are located).
> fix: Shortcuts list was crashing the client

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(livekit): no mic output after joining audio in "listen only" mode](https://github.com/bigbluebutton/bigbluebutton/commit/ac154fb0829775cb453210454e867bc45c396aeb) 
- Whenever an user joins as "listen only" (no input device, lock settings
is enforced) and later tries to activate a microphone mid-call, the mic
in question will output no audio. This only affects the LiveKit bridge.
This is due to an uneeded "isListenOnly" flag check in audio-manager's
setSenderTrackEnabled interface.
- Removed some unused vars in audio-manager
Partially https://github.com/bigbluebutton/bigbluebutton/issues/22099
> fix(livekit): no mic output after joining audio in "listen only" mode

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- [fix(audio): bridge callbacks might be uninitialized](https://github.com/bigbluebutton/bigbluebutton/commit/f4e329ce71431db84c981492d96f713c7a687ae6) 
- Audio bridge callbacks are, for unknown reasons, specified through
joinAudio calls rather than when initializing bridges. This has the
potential to cause issues with bridge such as LiveKit which triggers
audio join automatically rather than due to user input.
- Set the audio-manager callback in bridges during the bridge load
procedure and thus guarantee that it exists in bridges in all scenarios.
n/a
> fix(audio): bridge callbacks might be uninitialized

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/styles.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/styles.tsx
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/palette.js
- adjusts moderator messages in the chat to have a different background color instead of making the text bold
- adjusts hover styles for the messages, to have a different border color instead of a different background color
Closes #19852
1. join a meeting with 2 users: one moderator and one viewer
2. send messages in the chat
3. see styles for viewer and moderator messages
> style: adjust chat message styles (blue background for moderators)

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/db/PluginDAO.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Plugins.scala
- bbb-graphql-server/bbb_schema.sql
- bbb-graphql-server/metadata/databases/BigBlueButton/tables/public_v_plugin.yaml
This PR adds the `localesBaseUrl` to the plugin's table in the postgres. This will be useful for the plugin to fetch this data easily.
Add internationalization for the plugins more easily as requested in the issue https://github.com/bigbluebutton/plugin-typed-captions/issues/6
To test this, there ar 3 PRs that work together here: This one in the CORE, the one in the SDK, mentioned ahead and the one in the typed-captions (which will be sent later on), so the 3 of them must be tested at the same time.
- First, one will have to apply the SDK manually into the plugin-typed-captions (Considering both in the correct branches);
- Run in dev mode;
- So as we are testing it with ngrok, they put some barriers there to avoid security breaches, so to properly make the testing work, do the following: …
> feat(plugins): add useLocaleMessage to plugins

- bigbluebutton-html5/imports/ui/components/session-details/component.tsx
- bigbluebutton-html5/public/locales/en.json
The modal title was too specific in English and didn't translate well into other languages(e.g., portuguese). This commit changes the title to something more generic, improving its fit accross multiple languages.
- English:
Before:
After:
- Portuguese:
Before:
After:
> fix(session-details): generalize modal title for better localization

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
Fix incorrect state of create breakout button after moving user with free join enabled.
Closes #22268
1. Create a meeting with a presenter and an attendee
2. Click on Create Breakout Rooms
3. Enable the "allow users to choose room" option
4. Move the user to a room, then move back to the main box.
5. See the Create button not disabled
> fix: Enable allow users to choose room blocking create button on breakouts

- bigbluebutton-tests/playwright/core/elements.js
- bigbluebutton-tests/playwright/core/page.js
- bigbluebutton-tests/playwright/playwright.config.js
- bigbluebutton-tests/playwright/user/multiusers.js
This PR improves the pinning and unpinning webcam assertions. we've recently spotted a few CIs failing in related steps. The test expects this pinning behavior:
- for viewers: Mods priority -> pinned order;
- for mods: pinned order;
now, this test also:
- waits for each user's own webcam to load;
- waits for other users' webcam to load (both actions prevent failure when performing clicks before the camera video is not fully loaded);
- sets a default `actionTimeout` value;
- adds `getVisibleLocator` function;
- assertion descriptions improved
> test: Enhance pinning webcam assertions

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
- bigbluebutton-tests/playwright/user/lockViewers.js
Adds height tracking to the stable dimensions polling logic and uses it to handle resize changes instead of a timeout.
Closes #22293
> fix(whiteboard): Include height for polling stable container dimensions

- bigbluebutton-html5/imports/ui/components/layout/layout-manager/layoutEngine.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
Fix cameras position when the layout is changed to "focus on presentation"
Closes #22227
1. Create a meeting
2. Share the webcam with two users
3. Change the layout to "focus on presentation"
> fix: cameras position on focus on presentation layout

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationConversionCompletedSysPubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPageConversionStartedSysMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodsApp.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetCurrentPresentationPubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetPresentationDownloadablePubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/PresentationPods.scala
- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
- bigbluebutton-html5/public/locales/en.json
- bigbluebutton-tests/playwright/breakout/join.js
- bigbluebutton-tests/playwright/core/constants.js
- bigbluebutton-tests/playwright/core/elements.js
- bigbluebutton-tests/playwright/notifications/chatNotifications.js
- bigbluebutton-tests/playwright/notifications/notifications.spec.js
- bigbluebutton-tests/playwright/notifications/presenterNotifications.js
- bigbluebutton-tests/playwright/notifications/recordingNotifications.js
- bigbluebutton-tests/playwright/notifications/util.js
- bigbluebutton-tests/playwright/polling/polling.spec.js
- bigbluebutton-tests/playwright/presentation/presentation.js
- bigbluebutton-tests/playwright/presentation/presentation.spec.js
- bigbluebutton-tests/playwright/presentation/util.js
- bigbluebutton-tests/playwright/user/lockViewers.js
- bigbluebutton-tests/playwright/user/multiusers.js
- bigbluebutton-tests/playwright/user/user.spec.js
- bigbluebutton-tests/playwright/whiteboard/whiteboard.spec.js
The client was repeatedly displaying the notification about the Current Presentation.  
To resolve this and align with the new notification pattern, this PR moves the notification-sending action to `akka-apps`, simplifying the client by removing its complex logic.
Before:
After:
Fix: #22185
> fix (html5): Client always showing "Current presentation" notification

- .github/actions/merge-branches/action.yml
> ci (3.1): Improve git merge strategy by adding `--no-rebase param`

- bigbluebutton-html5/imports/ui/components/poll/component.tsx
- Adjusts poll panel behavior, so an active poll is not stopped if the panel is minimized.
- Fix minimize button label id
Closes #22230
2. open poll panel and start a poll
3. click "minimize polling"
4. poll should not be stopped
> fix: do not stop poll if polling panel is minimized

- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/styles.js
Adds a chevron icon in the session title, as a visual indicator that the area is clickable
2. see the new icon in session title
> Add visual indicator on session name

- bigbluebutton-html5/imports/ui/components/breakout-room/breakout-room/components/timeRemaining.tsx
This PR limits the maximum size of the time variable in the breakout time change form. It prevents sending a number larger than the server can handle. In such cases, the UI resets without applying any changes, making it unnecessary to allow excessively large values.
- Create a Breakout.
- try to change it duration
- see results
> Fix: Limit time size on breakout duration change

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/captions/component.tsx
The issue occurs when audio captions are enabled but the browser does not grant the necessary permissions, causing the client to enter a loop while attempting to fetch the data.
Closes #22078
- Set `app.audioCaptions.enabled` to `true` in the setting.yml
- Join a browser with no permission granted for audio transcription (I used chromium)
- Open audio modal and start echo test
- See the results.
Before:
After:
> Fix: audio modal endless setState on audio modal

- bigbluebutton-html5/imports/ui/components/layout/modal/component.jsx
Makes push layout not be stored between meetings
Closes #22231
1. set `public.app.userSettingsStorage: local` in settings file
2. join a meeting
3. enable "Update to everyone" in layout modal
4. join a new meeting
5. "Update to everyone" should not be enabled
> fix: per meeting push layout

- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
follow up to #22333 (which included the changes to the layout modal) to also use per meeting push layout in the pushLayoutEngine component.
> fix: get push layout settings from storage in pushLayoutEngine component

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/nav-bar/nav-bar-graphql/recording-indicator/component.tsx
fix issue where the recording button and system messages in the chat would be displayed in the wrong language after switching locales
1. join a meeting with recording enabled
2. change language in settings menu
3. save settings
4. see the recording button label and the message in the chat "{user}  is now the presenter" - both should be in the same language as the rest of the client
> fix: locale not updating in recording button and chat system messages

- bigbluebutton-html5/imports/ui/components/apps-gallery/component.tsx
- bigbluebutton-html5/imports/ui/components/layout/context.jsx
- bigbluebutton-html5/imports/ui/components/layout/layoutTypes.ts
- bigbluebutton-html5/imports/ui/components/plugins-engine/extensible-areas/components/apps-gallery/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/extensible-areas/components/generic-content/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/extensible-areas/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/extensible-areas/types.ts
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/container.tsx
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/pinned-apps/component.tsx
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
- [feat(plugins): add apps gallery extensible area](https://github.com/bigbluebutton/bigbluebutton/commit/35e013ccf7847e96706daafce9e56c5ef6796c45) 
Adds new extensible area for the apps gallery. Previously, to add an entry in the apps gallery, a plugin should inject a generic sidekick content, which means that something would be shown in the sidebar content. But, as the concept of an app is growing beyond the sidebar content, this new extensible area allows for injecting an entry in the apps gallery and can execute any action using the 'onClick' callback.
- [fix(plugins): unregistering generic sidekick content](https://github.com/bigbluebutton/bigbluebutton/commit/028d797aebd54ea77df97a9235286c173d0e0cda) 
The generic sidekick contents were not being unregistered from the apps gallery. …
> [3.1] feat(plugins): add apps gallery extensible area & fix(plugins): unregistering generic sidekick content 

- bigbluebutton-html5/imports/ui/components/video-provider/hooks/index.ts
- [fix: client crashes when paginationThresholds comes into effect](https://github.com/bigbluebutton/bigbluebutton/commit/28674d58ed5525215ebc25ff33c3e14d7e9720fb) 
- Whenever paginationThresholds kicks in, the client crashes for everyone
in the room. That's caused by a conditional hook call when calculating
new page sizes :)
Closes https://github.com/bigbluebutton/bigbluebutton/issues/22355
> fix: client crashes when paginationThresholds comes into effect

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Cancels previous polling for stable whiteboard container when the presentation area is resized. This way we guarantee that the polling queuing is done in the right order.
Closes #22292
Closes #21302
Closes #21191
> fix(whiteboard): Unstable zoom when presentation area is resized

- bigbluebutton-tests/playwright/parameters/constants.js
- bigbluebutton-tests/playwright/parameters/createParameters.js
- bigbluebutton-tests/playwright/parameters/parameters.spec.js
This PR updates/fixes the `Create Parameters › Message Only To Moderators` test, which has been disabled since the welcome message moved to the session details modal. it will also run in CI again for now on
> test: Update messsage only to mods param test

- .github/workflows/automated-tests.yml
This PR enables the test result download for each shard separately
The current average test result download size is around 1.3GB. Sometimes there are only a few failed tests to check locally but to see them, all the data should be downloaded. With this change, the developers can download only the one(s) they want to
> ci: Upload HTML test result from each shard separately

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-toolbar/styles.ts
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
Fixed the issue where the emoji picker was appearing off-screen on mobile. This was caused by the anchor being set to the toolbar and an incorrect configuration positioning the element too far to the right. I moved the emoji picker to the message component and added a condition for mobile devices to resolve this.
Closes #22113
- Send a message on mobile
- click to react on it
> Fix(chat): Emoji picker appearing out of bounds on mobile

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
- bigbluebutton-html5/private/config/settings.yml
Change rtt timeout to use `stats.timout` and decrease settings value to 10s, also add a log for failed requests to improve debug.
No issue opened.
Server didn'r repond:
Request timed out:
Failed to register user history:
> fix (html5): Improve check RTT flow to avoid wrong bad connection alert (and add more logs for errors)

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
Fix the presentation toolbar appearing under webcams and actions bar 
No issue opened
- Change layout to focus on video
- click to open the preesntation toolbar
Before:
After:
> Fix(presentation): toolbar being overlapped on video focus layout

- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
This PR fix the details modal appearing automatically every refresh.
Closes #21985
- Close modal
- Refresh
- See result
[Screencast from 21-02-2025 13:45:02.webm](https://github.com/user-attachments/assets/e8b961fc-61c3-41ac-af57-500d6891c9dd)
> fix (html5): Auto show Session Details modal only once

- bbb-graphql-server/bbb_schema.sql
This change converts to `UNLOGGED` all PostgreSQL tables used for Graphql-Server.
This improves write performance by eliminating Write-Ahead Logging (WAL), reducing I/O overhead for real-time operations. 
While data loss on a database crash is a risk, it’s acceptable for our use case where meeting data is temporary and only useful during each session, with no sensitive information.
Thanks to @defnull for the great suggestion!
https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-UNLOGGED
https://www.crunchydata.com/blog/postgresl-unlogged-tables
> perf (gql-server): Convert all graphql tables to `UNLOGGED` to improve writing performance

- bbb-graphql-server/deploy.sh
It will handle problems when running the script in a server different from docker dev:
Example of errors:
```
FATA[0000] {
"error": "invalid \"x-hasura-admin-secret\"/\"x-hasura-access-key\"",
"path": "$",
"code": "access-denied"
} 
```
or
```
could not change directory to "/root/bigbluebutton/bbb-graphql-server": Permission denied
```
> refactor (gql-server): tweak deploy script to make it work in any server

- bigbluebutton-tests/playwright/user/lockViewers.js
Adds steps to `User › Manage › Lock viewers › Lock see other viewers cursor` test to ensure expected cursors are correctly placed on the whiteboard on assertions
Recent CI failures:
> test: Additional steps to ensure correct cursors on assertions

- bigbluebutton-html5/imports/startup/client/intlLoader.tsx
- [fix: bbb-html5 locales lack cache busting query parameter](https://github.com/bigbluebutton/bigbluebutton/commit/4e7c599591c0fb3c61ee38b817f9aa4d24e00897) 
- The `v=VERSION` query parameter was lost in the rewrite of the locale
fetching component. This may cause locales to be incorrectly cached even
after server updates that alter them.
- Restore the `v=VERSION` query parameter to the locale URL (similarly to
how it was done in 2.7).
None
> fix: bbb-html5 locales lack cache busting query parameter

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
Include the error object in extraInfo for WebSocket error logs to enhance detail and provide better insight into the root cause.
No issue Opened.
- Create a meeting and join it
- on server console run `sudo systemctl restart nginx`
- Take a look on browser's console logs
Before:
After:
> Refactor(html5): Add error for extraInfo to improve log details

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/alert/queries.ts
changes audio alerts behavior, so alerts are played even when chat is open.
Closes #22159
1. join 2 users into a meeting
2. in the session settings enable audio notification for chat messages
3. ensure public chat panel is open
4. write a chat message
5. hear audio notification
> fix: Chat message audio notification not working correctly

- bigbluebutton-html5/imports/startup/client/logger/ServerStream.ts
- [fix: client logger does not send userInfo to external stream](https://github.com/bigbluebutton/bigbluebutton/commit/6f7cb2071fbcbe04f48ca7ec71a12bf7b9c3e4c4) 
- The `userInfo` metadata that's used in the client's external logging
stream is broken. The userInfo object is incorrectly overwritten with a
sessionToken-only object and is consequently not sent due to it missing
a meetingId.
- Adjust the ServerStream so that:
- The `userInfo` object is sent in payloads when available (same
trigger as 2.7, meetingId)
- The `userInfo` object attributes have the same names as the 2.7
variants (if they existed there). Some were renamed, and that may
break log parsers.
None
> fix: client logger does not send userInfo to external stream

- bigbluebutton-html5/imports/api/audio/client/bridge/service.js
- [fix(audio): extend retryable gUM error list](https://github.com/bigbluebutton/bigbluebutton/commit/f791a422833326be62c665b689f428e2594f78e6) 
- A portion of audio init errors are NotFoundError-coded gUM failures.
General cause for that is having no input devices, but sometimes they
_are_ present and this error is thrown anyways. The hypothesis here is
that tainted constraints (which carry deviceId and other attributes from
previous sessions) might be causing this. Same goes for NotReadableError.
- Add NotFoundError and NotReadableError to the list of retryable gUM
errors for audio. I'll keep an eye on telemetry data to see if this has
any effect.
None
> fix(audio): extend retryable gUM error list

- bigbluebutton-html5/imports/api/screenshare/client/bridge/livekit.ts
- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- [fix(livekit): blurry screen sharing due to borked presets](https://github.com/bigbluebutton/bigbluebutton/commit/5930a1b1d5b2333bfbf8ed21cbded1fdb16267d9) 
-  LiveKit's screen sharing presets aren't configurable in BBB. The default values
are also not ideal right now, which causes the received stream to be in
a lower quality than it should in specific scenarios due to adaptive
streaming.
- Make screen sharing's presets configurable, as well as adjust the
default encoding preset to something that makes for nicer layers
(1080p, 15fps).
None
> fix(livekit): blurry screen sharing due to borked presets

- bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
- [fix(audio): prevent retry loop when skip_check=true and error occurs](https://github.com/bigbluebutton/bigbluebutton/commit/dae725956cf800b782b6871a0d2fc4b3247c4f25) 
- When skip_check_audio=true and audio fails with some specific errors,
the audio modal gets stuck into a join retry loop. This causes logs to
be spammed and the modal to be effectively stuck in the Help screen with
an `UnknownError` identifier.
- Add a blocking state to the automatic audio join procedure that only
allows it to run once per audio modal mount lifecycle. If it fails once,
it won't retry automatically and instead follow the expected `Help -> Retry
-> Audio Settings -> Join` flow for error scenarios.
None
> fix(audio): prevent retry loop when skip_check=true and error occurs

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR is a follow-up for https://github.com/bigbluebutton/bigbluebutton/pull/22368. In this PR we continue to improve zoom stability when the presentation area is resized and on client startup.
[fix(whiteboard): Clamp presentation width to a minimum value of 0](https://github.com/bigbluebutton/bigbluebutton/commit/07ff24462bc3483875bd36a53b99d98db1f3df11):
- When calculating zoom with gap, clamp the resulting presentation width to a minimum value of 0 when subtracting the gap value.
[fix(whiteboard): Fallback to no gap base zoom](https://github.com/bigbluebutton/bigbluebutton/commit/ecb56c29d2c3dcef2c0512bfb2763f4274109cec):
- When calculating base zoom with gap, if the calculated zoom is 0 or Infinity, force recalculation with no gap. That's because we don't know the base zoom to fit …
> fix(whiteboard): Improve zoom stability

- docs/docs/administration/customize.md
* 2ab81a2f0ef5799e60a1b1c9d67a7945d782850b
This set of changes was added to BBB 2.7 via https://github.com/bigbluebutton/bigbluebutton/pull/18884 and later ported to BBB 3.0 via https://github.com/bigbluebutton/bigbluebutton/pull/19098 However, the port was done after all the yq commands had been bulk-updated and was these three were thus missed.
* 3e9f2450ed3401913fef480e5bb03d8bf169b0eb
Missing / in the file path
On BBB 3.0 we no longer have a `bbb-html5` service, so need to restart
BigBlueButton in its entirety.
Adjust the yq commands to the correct yq version's syntax.
Closes #22451
The old commands were only relevant to BBB <=2.7
```
cat /usr/local/bigbluebutton/core/scripts/presentation.yml | grep deskshare
deskshare_output_width: 1280
deskshare_output_height: 720 …
```
> docs: Adjust yq commands to yq version 4.16.2

- docs/docs/administration/customize.md
* [docs: update the portion about reducing webcam bandwidth](https://github.com/bigbluebutton/bigbluebutton/commit/652bd728fed9c4a98dff8bde7bdeea617c3aa679) 
The yq commands were from BigBlueButotn 2.7 (different yq version and syntax)
Also, running them did little to /etc/bigbluebutton/bbb-html.yml unless
the cameraProfiles portion was present and populated.
Therefore I added some optional instructions for how to populate it.
The resulting yml looks fine to me with the exception that
some profiles have a higher bandwidth than desired but are not in the
list of low, medium, high, hd. Seems they are activated for small
sessions only, so likely not a concern bandwidth-wise.
Revisits the documentation portion for Reduce bandwidth of webcams
modifying the `yq` commands to work on BBB 3.0 and …
> docs: update the portion about reducing webcam bandwidth

- bigbluebutton-html5/imports/ui/components/notifications-bar/styles.js
Fix issue with NotificationBar having uneven padding and a gap below to the chat/userlist.
Experienced visual consistency in BBB Community Call 2025-03-04
> Fix missing top padding for NotificationBar

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Add `NaN` check when calculating zoom (with gap or not). Then, fallback to `100%` if so.
Closes n/a
The lack of this check can crash the client.
> fix(whiteboard): Add `NaN` check for zoom calculation

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
changes poll behavior, so current poll is not ended on slide change.
Closes #22396
1. Click on the '+'
2. Click on 'Start a Poll'
3. Choose any type of poll and click 'Start Poll'
4. Change to a different slide using the > or < button
> fix: Changing slide while a poll is open closes the poll

- bigbluebutton-html5/imports/ui/components/poll/queries.ts
change poll results query to also show users who have not responded in live results.
Closes #22456
1. join a meeting with at least 2 users
2. start a poll
3. see live results in poll panel
> fix: Show users who have not responded to the poll results

- bbb-export-annotations/workers/process.js
This fix the problem when exporting a presentation of type image, it goes completely blank.
Closes #22219
Pretty simple:
- Checkout to this branch;
- Run `bbb-export-annotations` (you can `cd bbb-export-annotations`, then `./deploy.sh`);
- Create a meeting;
- Upload an image as a presentation;
- (optional) Make some annotations onto the whiteboard;
- Open the modal to upload a presentation;
- Click the 3 dots dropdown and click "Send out a download link for the presentation including annotations";
- Download the presentation from the chat message;
- See results. 
**Technical view:**
In 2.7, we processed image typed presentations and transformed them into PDFs (The final structure of their assets was the same - it even had a pdf instead of image), so the flow for exporting an image was the …
> fix(bbb-export-annotations): fix image export being blank

- bigbluebutton-html5/imports/ui/components/connection-manager/component.tsx
This PR fixes an issue where error 3006 was incorrectly displayed for network errors unrelated to subscriptions. I've updated the logic to filter errors based on subscription type.
No issue opened.
- Modify some mutation field to fail the request.
- Trigger the mutation.
- Don't see the error notification.
- Modify a subscription to failed (Add a invalid field).
- See the error.
> Fix(html5): Non subscription error triggering 3006 error

- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/livekit.ts
- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/external-video-player/volume-slider/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/service.js
This Pull Request fixes several issues related to screenshare audio. The first issue addressed is that audio was being muted when quick swap was enabled in a meeting and the presenter switched to presentation mode. Now, the audio sent by the presenter remains muted as expected. Additionally, this PR fixes an issue where screenshare and external video continued playing even when a non-media layout was selected (such as `CAMERAS_ONLY` or `PARTICIPANTS_AND_CHAT_ONLY`).
No Issue opened
First issue:
- Change the Setting  `public.layout.showScreenshareQuickSwapButton`.
- Create a meeting with this setting enabled.
- Join with two users.
- Share a screen with live audio.
- Swap to presentation.
- audio on viewer should not be playing.
Second issue:
- Join with a normal user 
- Join a second user …
> Refactor(html5): Make screenshare audio be muted when quick swap is enabled and when non media layout is selected

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toast/presentation-uploader-toast/component.jsx
adjusts presentation uploader toast to prevent undefined toastId crash
Closes #22463
> fix: Client crash when exporting a presentation (not every time)

- bigbluebutton-html5/imports/ui/components/whiteboard/container.jsx
Refetchs whiteboard shapes after toggling fit-to-width.
Closes #22409
When toggling fit-to-width the whiteboard component is remounted (is that intentional?), so all previous shapes are lost (except the last one; it is kept as the last state of the annotation stream).
> fix(whiteboard): Refetch shapes after toggling fit-to-width

- bigbluebutton-html5/imports/ui/components/notifications/service.ts
This PR fixes an issue where the leave notification audio was played multiple times when several users left the meeting simultaneously, given that the 'notify user leave' setting was enabled. I've added a throttle to ensure the audio plays at most once every 5 seconds when multiple users leave.
Closes #22440
- Join a meeting.
- In setting under notification tab, enable `user leave` audio notification.
- Join with several users (10-15).
- Leave with this users.
> Fix(html5): User leave notification burst

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-header/component.tsx
- bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
- bigbluebutton-html5/imports/ui/components/notes/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-graphql/user-list-content/user-notes/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-actions/component.tsx
Improves accessibility of BBB for screen reader users:
- add headings to chat and shared notes panels so screen reader users can navigate to them
- remove double button roles for menu buttons
BBB should be the number 1 virtual class room and videoconferencing software for everyone.
- open either chat or shared notes panel
- in screen reader open the navigate by headings tool
- see the added navigation entry
I hope I caught all cases where children of `BBBMenu` are not a `<button>` element.
> Accessibility improvements

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala
- akka-bbb-apps/src/universal/conf/logback.xml
Modify logback to replace \n with spaces in log output.
Before:
After:
> fix (akka-apps): Prevents line breaks in logs

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/service.ts
Fix an issue that prevent Safari older than 16.4 to open BBB 3.0 client:
It happens because Safari introduced support for regex lookbehind on 16.4. Before that this regex would throw an error "Invalid regular expression: invalid group specifier name".
> fix (html5): Change `textToMarkdown` func removing regex lookbehind

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
This PR add more details for the log `rtt_failed_to_register_user_history` to spot whats causing it on server side logs.
> Fix(html5): Add more details for error log on rtt fail

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
Attempts to fix an error that only happens in older Safari versions, due to AbortSignal.timeout not being available
1. join a meeting on Safari 15
2. see whiteboard
> fix: only use AbortSignal.timeout if available

- bigbluebutton-tests/playwright/chat/chat.spec.js
Re-enables `Chat › Copy and paste public message` test in CI as https://github.com/bigbluebutton/bigbluebutton/issues/22198 got fixed
> test: Remove flaky flag from chat test

- bigbluebutton-html5/imports/ui/components/notes/component.tsx
adds missing properties from shared notes header component
typescript code compilation step in ci was failing due to this
> fix: typescript warning

- bigbluebutton-html5/imports/ui/components/connection-status/component.jsx
This PR fixes an issue where, during client instability, an attempt to register the event in local history could fail. The issue occurred because the function used to calculate RTT did not verify whether user data was available, leading to null values in function calls. I resolved this by moving the data fetching outside the component, ensuring user data is available before starting the RTT calculation.
Although it is an error log, a failure would not cause any harm to the client's usability (like a crash). The only affected component would be the connection status modal, where the "My logs" tab would not display local logs if the client was completely offline.
No issue opened.
- Open devtools 
- Navigate to Network tab 
- On throttling dropdown Select 3G
Before: 
After:
> Fix(html5): Rtt error when trying to register instability on network

- bbb-graphql-middleware/internal/websrv/connhandler.go
Closes: #22626
Before:
After:
And now the browser receive a return with header `403 Forbidden`:
> fix (gql-middleware): Handle error when request Origin is not authorized

- akka-bbb-apps/src/templates/systemloader/systemd/start-template
Setting `LimitNOFILE=4096` will be fine for servers meeting BigBlueButton’s minimum requirements, safely handling the necessary file descriptors without issue.
`4096` is also the value used for `bbb-graphql-middleware` and `bbb-graphql-server`.
Closes: #22338
> fix (akka-apps): Increase default akka-apps LimitNOFILE to 4096

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
Fixes an issue where the zoom level was not persisted through presenter changes. The problem occurred because a logic intended for 'fitToWidth' was incorrectly applied during presenter transitions.
Part of #21873,  fitToWidth fix will be a follow up PR, because fit to width currently is a local state on client, not a meeting wide information, so more internal changed are needed.
- Join a meeting with two users.
- Zoom in with presenter user.
- Make another user Presenter.
[Screencast from 07-03-2025 11:45:29.webm](https://github.com/user-attachments/assets/53bf9c52-ee19-408d-9b39-7cad7b83c073)
> Fix(html5): Zoom not being persisted on presenter change

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR sets the default active tool to the Draw tool when mounting tldraw.
It was requested that the Draw tool be selected by default upon mount, eliminating the extra step of manually activating it and improving usability.
> fix(whiteboard): Default to Draw tool on tldraw mount

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/live/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/service.ts
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-captions/speech/component.tsx
This fixes several problems with the captions UI elements:
- We need to respect the captionLimit value from settings.yml properly, it should show the last 'N' captions when we split it in too many elements
- Sometimes the browser will throw speech recognition errors and/or end the transcription because of inactivity. We detect those cases and restart the transcription
> Fix captions getting stuck and showing with wrong timing

- bigbluebutton-tests/playwright/reconnection/reconnection.js
- bigbluebutton-tests/playwright/reconnection/reconnection.spec.js
Re-enables `Reconnection` tests as the blocking issue has been fixed
> test: Re-enable reconnection tests

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-content/text-content/styles.ts
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/page/chat-message/message-replied/styles.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/component.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-reply-intention/styles.tsx
- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/service.ts
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
This PR addresses several issues related to markdown rendering in chat messages:
- Sending a link with an empty description (`[](https://bigbluebutton.org/)`) resulted in an empty message.
- Simple inline code incorrectly converted links within its content into markdown.  
- Code blocks were not displayed correctly in reply quotes, as only the first line (a backtick `\``) was shown.
- Messages where the first line was blank resulted in an empty reply quote.
- Messages with an image as the first line caused the reply quote to be empty, and in chat input the image was displayed above the input (which is not allowed).
- Code blocks are now visually distinct with a different background and border, …
> fix (html5): Fix multiple markdown-related chat bugs

- docs/docs/development/api.md
Improves the documentation of `clientSettingsOverride` so that it includes enabling the call by overriding `allowOverrideClientSettingsOnCreateCall`
Closes #22654 
`allowOverrideClientSettingsOnCreateCall` was not mentioned before.
> docs: Include allowOverrideClientSettingsOnCreateCall mention in clientSettingsOverride

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/volume-slide/component.tsx
- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/toolbar/volume-slide/styles.ts
This PR fixes the mute status not being persisted on player remount
Follow up of #22457
- Join with two users 
- On presenter's client mute the user
- Make another user presenter.
- See mute status unchange.
[Screencast from 10-03-2025 15:56:47.webm](https://github.com/user-attachments/assets/d5fa2d6c-0568-4871-8c22-70474bfb833c)
> Fix(html5): External video mute not being persisted

- docs/docs/data/create.tsx
- docs/docs/development/api.md
- docs/docs/new-features.md
- docs/run-dev.sh
Just documentation for the `presentationConversionCacheEnabled` create parameter introced.
See some screenshots of the added portions:
> doc(bbb-web): Documentation for presentationConversionCacheEnabled

- bigbluebutton-html5/client/meetingClient.jsx
We see examples of trying to log when there is no stack property in e.error. Adding a bit of protection. It's possible that with this change we could avoid a whiteboard area crash , one of the instances of "Something went wrong. Trying to recover"
[fix: Avoid reading properties of null](https://github.com/bigbluebutton/bigbluebutton/commit/b3e6aee76314f118887c035898cdec5d15694d1b) 
We see examples of trying to log when there is no stack property in
e.error. Adding a bit of protection. It's possible that with this change
we could avoid a whiteboard area crash , one of the instances of
"Something went wrong. Trying to recover"
Closes # none
Seeing the following error + console logs
reported by @gabriellpr 
Joining the client with Chrome 93-95. Possibly other cases too but not sure how to …
> fix: Avoid reading properties of null

- docs/docs/new-features.md
Adds a mention of SetScreenshareAsContentEvent as a newly added event for recording.
n/a
> docs: Add docs for the new event SetScreenshareAsContentEvent

- bigbluebutton-html5/imports/ui/components/common/toast/styles.js
- bigbluebutton-html5/imports/ui/components/raisehand-notifier/styles.js
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/general.js
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
Adjusts toast size to be the same in all font-size %.
(also applies to other toasts, not just raise hand, making all the same size)
Closes #22676
1. Join a meeting
2. Go to the meeting settings and decrease the font-size to 75%
3. Raise hand
4. See the notification
> fix: Raise hand notification not well aligned on 75% font-size

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
It gives us the hability to control default behavior of recording in breakout rooms
Closes https://github.com/bigbluebutton/bigbluebutton/issues/22695
Set this in your `/etc/bigbluebutton/bbb-html5.yml`
```yml
public:
app:
breakouts:
recordRoomByDefault: true
```
> feat(html5): add control over default setting of breakout recordings

- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/styles.js
This PR fixes an issue where the volume slider remained visible in fullscreen mode during screen sharing. The issue occurred because the event listener was set to the hover event. I updated it to use the mousemove event and added a timeout to control the slider's visibility.
Closes #21375
- Join two users
- With presenter share it's screen
- with viewer put the screenshare on fullscreen
- just let the cursor over the screenshare
- See results
[Screencast from 19-03-2025 11:34:37.webm](https://github.com/user-attachments/assets/0c5ec083-1003-4ca2-8b44-f47a1274c042)
> Fix(html5): controls on fullscreen screenshare

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx
This PR fixes an issue where changing the presenter with zoom applied caused the reset button to be disabled. The issue occurred because the button logic required the initial zoom value to be different from the current value. This was valid in the past when changing the presenter reset the zoom, but now the best approach is to check if the current zoom differs from the default 100% value.
Closes #22661
- Join with two users
- In Presenter user, zoom the presentation
- Pass the presenter right for another user
- in new Presenter click to reset the zoom
[Screencast from 19-03-2025 14:38:46.webm](https://github.com/user-attachments/assets/e6fd72ce-aeb5-4278-9aae-4e804842f4ad)
> Fix(html5): Zoom reset not working on preseter's change

- bigbluebutton-tests/playwright/.gitignore
- bigbluebutton-tests/playwright/README.md
Updates `.gitignore` to include `pr-` folder in ignored directories
Useful when checking locally a PR test result without messing with the git changes or pushing them by mistake
> test: Ignore folders prefixed `pr-`

- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
- Prevent the whole audio modal from re-rendering after calling the `UpdateUserClientEchoTestRunningAt` mutation.
**Before**
[Screencast from 05-03-2025 16:18:56.webm](https://github.com/user-attachments/assets/5a96ebef-1432-4fbc-8488-a1678ac3e29b)
**Now**
[Screencast from 05-03-2025 16:17:53.webm](https://github.com/user-attachments/assets/e9cefcac-868f-4ec3-9eed-d1501ecc4098)
Closes #21672
> fix(html5): Prevent the whole audio modal from re-rendering

- .github/workflows/automated-tests-publish-results.yml
Avoids action failures noticed due to missing PR data on merge event - no need to run the action as no progress comment is expected anywhere
> ci: Skip publish action on merge event

- bigbluebutton-tests/playwright/core/page.js
Avoids `User › Manage > Mute all users except presenter` test assertion matching two elements:
```sh
Error: should display the "Moderator" user's conversation indicator to himself
should display the "Moderator" user's conversation indicator to himself: Error: strict mode violation: locator('button[data-test="isTalking"]').filter({ hasText: 'Moderator' }) resolved to 2 elements:
1) <button id="tippy-80" color="primary" position="bottom" aria-disabled="false" data-test="isTalking" aria-describedby="description" aria-label="Moderator is talking" class="sc-lcIPJg gatcbm sc-cAkrUM iwQwIV">…</button> aka getByLabel('Moderator is talking')
2) <button id="tippy-81" color="primary" position="bottom" aria-disabled="false" data-test="isTalking" aria-describedby="description" aria-label="Moderator2 …
```
> test(fix): Update user talking indicator check to use regex for exact match

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx
The client may crash in breakout room's management panel due to undefined user entries being set in the rooms' users arrays. Repro:
- Join with u1, u2; create BRs
- u2: join a BR, then leave *the main room*
- u1: try opening the mgmt panel
Properly filter user arrays in the RoomManagementState component so that no undefined entries are present there. This should prevent the crash described here as well as further issues.
> fix: client crash in breakout room mgmt panel

- bigbluebutton-html5/imports/ui/components/app/styles.js
This PR fixes an issue where the connection bars displayed a grayscale instead of a colored indicator when in a bad status. The issue was caused by a style det by dark mode, and I removed the css inline enforcing the gray scale to ensure the correct color representation based on the connection status. 
Closes #21496
- Join a user
- Open setting modal
- Enable dark mode
- Run the mutation 
```
mutation UpdateConnectionAliveAt($networkRttInMs: Float!) {
userSetConnectionAlive(networkRttInMs: $networkRttInMs)
}
```
with the variable 
```
{"networkRttInMs":2000}
```
on apollo [devtools](https://www.apollographql.com/docs/react/development-testing/developer-tooling#apollo-client-devtools)
- Open connection status modal
- Select the session logs
- See the results
Before
After
> Fix(html5): Connection status bars not showing colors on dark mode

- bigbluebutton-html5/client/meetingClient.jsx
- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/join-handler/presenceManager/component.tsx
- bigbluebutton-html5/imports/ui/components/legacy/component.jsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
Restores browser version check, that should display a message if the user's browser does not have the mininum requisites to run BigBlueButton
BBB had a similar feature provided by MeteorJS, and it was lost in the migration to GraphQL. This PR restores it.
1. Join a meeting with a browser version older than the ones defined in settings.yml file.
2. See the legacy client page
> fix: restore unsupported browser check

- bbb-webrtc-recorder.placeholder.sh
v0.8.0
---
* fix: multiple adjusments to VP8 sample building in the WebM recorder
* fix: multiple adjustments to packet loss handling
* fix: better pts generation for video samples
* fix: edge case adjusments to RTP jitter buffer and receive log
* chore: change default JB size
* feat: add option to write IVF copies of recorded streams
* feat: add option to use alternative video sample builder
* feat: make jb packet timeout configurable
* feat: make EBML max write queue sizes configurable
* build: use Galene's samplebuilder instead of Pion's
* build: sync ebml-go with upstream (4b8f657f0)
> build(bbb-webrtc-recorder): v0.8.0

- bigbluebutton-html5/client/main.html
- bigbluebutton-html5/imports/ui/components/audio/local-echo/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/local-echo/service.js
This PR fixes a bug where the client was crashing the whiteboard due to an error caught by the ErrorBoundary that handles all client log errors. The issue was related to two `<audio>` tags in the main HTML, both set with `autoplay`. During the client loading phase, users who had not yet interacted with the page were not granting permission for audio playback, which triggered the error.
Closes #22485
- Join with two users on FF
- Select first user and watis it load completely
- Select second user
- Se no crash and no erro of DOM exception on console.
Before:
[Screencast from 21-03-2025 09:19:49.webm](https://github.com/user-attachments/assets/5d9da7e8-c989-4504-960b-583e98dff665)
After:
[Screencast from 21-03-2025 09:24:33.webm](https://github.com/user-attachments/assets/60899433-c02a-4330- …
> Fix: whiteboard crash on second user join

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
This PR fixes a crash on the whiteboard when trying to select a tool using a keybind. The issue was caused by an incorrect ID being provided.
N/A
- Join a user
- click on whiteboard
- Press "R" in teh keyboard
- See it working.
[Screencast from 24-03-2025 09:06:31.webm](https://github.com/user-attachments/assets/fae15049-71a6-4e91-9294-f0a846ddb17f)
> fix(html5): Whiteboard crash when trying to use the rectangle shortcut

- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
[Screencast from 21-03-2025 13:01:52.webm](https://github.com/user-attachments/assets/8f303839-c897-4f50-89f7-5408741e27f9)
Closes #22735
1. Join a meeting.
2. Options > Settings > Enable Auto Hide Whiteboard Toolbars.
3. Move cursor in and out whiteboard.
> fix(html5): Extra padding on whiteboard toolbar when cursor is outside + auto hide enabled

- bigbluebutton-html5/imports/ui/components/legacy/component.jsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- bigbluebutton-html5/public/locales/en.json
update supported browser settings to include safari 14 and 15.
after #22764, the client loads correctly in Safari 14 and 15
> update minBrowserVersions to include safari 14 + 15

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
- bigbluebutton-html5/imports/ui/services/virtual-background/service.js
- Store webcam brightness settings on local/session storage.
- Restore that state on video preview opening.
[Screencast from 21-03-2025 09:40:18.webm](https://github.com/user-attachments/assets/f33533c1-8983-472d-a51b-4e1927885bcc)
Closes #22730
> fix(html5): Fix ephemeral webcam settings

- bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
This PR disable the assets button on whiteboard.
I used as base this issue and PR
https://github.com/tldraw/tldraw-v1/issues/289
https://github.com/tldraw/tldraw/pull/511
Closes #22745
- Join a meeting as presenter
- Click on `more` button
- Don't see assets tool 
[Screencast from 25-03-2025 09:16:39.webm](https://github.com/user-attachments/assets/22362952-3e3f-42bc-ac51-2611aab65d62)
> Refactor(html5): Disable assets tool on whiteboard

- record-and-playback/core/lib/recordandplayback/edl/video.rb
This combines a few improvements that I've figured out that are specific to processing/encoding of video. To summarize:
* Use faster options for intermediate video file encoding
* The overlay filters were a single-thread bottleneck; switch to xstack
* Don't composite videos hidden behind other videos
* Fix a tpad/fps filter bottleneck with long framerate gaps
* Process multiple cuts of video in parallel
The video encoding options were selected based on testing on a variety of recordings - they provide a reasonable speedup on the h264 encoding with only minor efficiency loss on the types of video that ffmpeg handles.
The compositing performed by the "overlay" filter is somewhat inefficient, especially when large numbers of individual videos are being composited using a separate overlay …
> Speed up compositing of video in recording processing

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
implements a new parameter `public.app.breakouts.offerRecordingForBreakouts` that controls if the checkbox to enable/disable breakout room recordings should be displayed in the breakout creation modal
1. set `offerRecordingForBreakouts` to false in settings file
2. join a meeting with recording breakouts enabled
3. create breakout rooms
4. "record" checkbox should not be displayed
5. Set `offerRecordingForBreakouts` to true in settings file
6. join a meeting with recording breakouts enabled 
7. create breakout rooms
8. "record" checkbox should be displayed
> feat: introduce offerRecordingForBreakouts parameter

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
This PR fixes an issue where moving a user from any breakout room to Room 0 (i.e., removing them from a breakout) was causing a crash. The bug occurred because the code attempted to retrieve a `breakoutId` during the move, but Room 0 does not have a `breakoutId`. As a result, `undefined` was being passed as a parameter to the mutation, which failed to affect the target user as expected.
Closes #22784
- Join with 1 mod and 2 viewers
- Create a breakout with the two viewers
- Go to "Manager users" on breakout panel
- Move a user from a breakout to room 0
- See it working
[Screencast from 27-03-2025 10:21:18.webm](https://github.com/user-attachments/assets/e3415eb3-553e-4a3e-b19e-6e428d8345de)
> Fix(html5): Users being moved to room zero on running meetings causes a crash

- bbb-webrtc-sfu.placeholder.sh
- [build(bbb-webrtc-sfu): v2.16.2](https://github.com/bigbluebutton/bigbluebutton/commit/f992a2f5fb7cae3572ea3f557455f04084fc1ca9) 
- fix(audio): TLO callerID matching is too strict
- fix(freeswitch): UA fails due to unescaped `"/` or abnormal URI user
Closes https://github.com/bigbluebutton/bigbluebutton/issues/22434
> build(bbb-webrtc-sfu): v2.16.2

- bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/mediaOnlyLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/participantsAndChatOnlyLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/push-layout/pushLayoutEngine.jsx
- bigbluebutton-html5/imports/ui/components/layout/utils.js
- bigbluebutton-html5/imports/ui/core/hooks/createUseSubscription.ts
It basically fixes the ui-command `changeEnforcedLayout` in the pluginApi. The problem was that for some layout transitions, some components were being misplaced on the UI.
Closes https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/158
With this fix, the `changeEnforcedLayout` can be better utilised in cases like hybrid classrooms, so that one can choose what to show in each device across the same session (and each device can change from oj).
Well, first I would advise to test thoroughly the layout transitions that can be accessible via UI and compare the results with the same set of actions done in the `v3.0.x-release`, all the behaviours should be the same. The possible layout types, in this case, would be:
- CUSTOM_LAYOUT
- SMART_LAYOUT
- PRESENTATION_FOCUS
- …
> fix(plugin/html5): fix ui-command changeEnforcedLayout for plugins 

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Adds checks for external video player functions `isMuted` and `getVolume` to avoid calling them when they are not yet available.
Client logs pointing to a case where these functions can be unavailable
> fix: prevent undefined functions in external video component

- bigbluebutton-html5/imports/ui/components/audio/audio-graphql/audio-controls/input-stream-live-selector/component.tsx
- bigbluebutton-html5/imports/ui/components/audio/audio-settings/component.jsx
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- bigbluebutton-html5/imports/ui/services/webrtc-base/utils.js
- [fix: crash due to MediaDevices EventTarget unavailability](https://github.com/bigbluebutton/bigbluebutton/commit/d6b1a65a5bced120ae2569661f6b36ae686265cb) 
- It seems that for some browsers (Safari 18.x), under some specific
circumstances, either the MediaDevices interface or the EventTarget
it should be inheriting from  aren't available. This causes a client
crash when trying to add devicechange event listeners.
- Add availability checks before adding/removing devicechange listeners.
Additionally:
- Log a warning whenever the MediaDevices interface is not fully
available. This is a *browser bug* and the log will help us report
this to vendors and help clear up any report that might be related
to the missing devicechange callbacks.
None
> fix: crash due to MediaDevices EventTarget unavailability

- docs/docs/data/create.tsx
- docs/tsconfig.json
It's really just a minor tweak to make the linking of `presentationConversionCacheEnabled` work in both development environment and production environment
Just checkout to this branch, and do `./run-dev.sh`.
> fix(doc): fix broken link in presentationConversionCacheEnabled 

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Adjusts undo and redo buttons so they also fade away when "Auto Hide Whiteboard Toolbars" is enabled.
Closes #22706
2. enable "Auto Hide Whiteboard Toolbars" in settings
3. move mouse over the whiteboard
4. move mouse out of the whiteboard
5. undo and redo buttons should fade away the same way as other whiteboard buttons
> fix: undo and redo buttons do not fade away

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/imports/ui/components/meeting-ended/service.ts
Adjusts meeting ended component to display the redirect button when `allowDefaultLogoutUrl: false` and `logoutURL` is set
1. set `public.app.allowDefaultLogoutUrl: false` in settings.yml
2. join a meeting passing `logoutURL` parameter on join api call
3. leave the meeting
4. a button to return to the home screen should be displayed
`allowDefaultLogoutUrl` true/false should have no effect if a custom logoutURL is provided
> fix: adjust allowDefaultLogoutUrl param behavior

- bigbluebutton-html5/imports/ui/components/common/error-boundary/error-boundary-with-reload/component.jsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- change minimum supported chrome version to 87
- adjusts error boundary to log but not reload whiteboard on resize error
(ResizeObserver loop limit exceeded warning in older versions of chrome will still be logged, but will not make the whiteboard reload)
Closes #22819
1. join a meeting on chrome >=87
> fix: enable support to older chrome version

- docs/README.md
- docs/build.sh
- docs/docusaurus.config.js
It does 2 things to enhance development experience:
- Adds Readme information to ease the learning curve of how to build and run the documentation;
- Adds a new parameter `--remote` to the `build.sh` script to select the git remote that one wants to fetch the branches from;
For the 1st point, I simply added some more information on tags to use and the `build.sh` script as well as the `run-dev.sh`.
The 2nd makes it more convenient to use the `build.sh` script. In my case, for instance, my git remote origin (My fork) is not quite synced with the official repository, so I'd rather fetch everything from upstream, which in my case is pointing to the official BBB repo.
Make it easier to add new documentation and even enhance docs structure.
> ref(doc): refactor documentation structure

- bigbluebutton-html5/webpack.config.js
Since #22764, the client has been generating two separate bundles. To ensure the Safari bundle uses the same hash as the standard bundle, we renamed it—but the script still tries to load chunks using the old bundle name, causing an error.
This PR updates the webpack config to generate a single bundle (no extra chunks). This resolves the naming mismatch and avoids runtime errors.
The standard bundle size increases from `5.6MB` to `6.8MB`, but this tradeoff may be beneficial, as it avoids downloading additional chunks during a meeting—potentially improving performance.
```
Loading chunk 446 failed.
(error: https://bbb/ 3.0.4 server/html5client/446.bundle.safari.js)
```
```
extraInfo.errorInfo_esobj.componentStack
Lazy
Player@https://BBB 3.0.4 …
```
> fix (html5): Limit html5 to generate one single bundle (no more chunks) to make it work in Safari 15

- bigbluebutton-config/bin/apply-lib.sh
- docs/docs/administration/customize.md
- docs/docs/development/api.md
- docs/docs/new-features.md
Removes references to the removed feedback form.
Closes # none
In https://github.com/bigbluebutton/bigbluebutton/pull/22111 we removed the feedback form (BBB 3.0)
However, the docs and the apply-lib script were not cleaned up, causing confusion.
> remove: Clean up after user feedback form removal

- bbb-export-annotations/workers/process.js
- Seems like `@svgdotjs/svg.js` is not respecting provided image dimensions when the slide image has a base64 image within the SVG. This is a fix for manually resizing both width and height of the SVG with the correct values.
Sample pdf: [3.0.2.pdf](https://github.com/user-attachments/files/19490435/3.0.2.pdf)
**Whiteboard**:
Exported pdf:
- With the fix: [302.pdf](https://github.com/user-attachments/files/19490502/302.pdf).
- Without the fix: [302 (1).pdf](https://github.com/user-attachments/files/19490510/302.1.pdf)
Closes #22704
> fix(bbb-export-annotations): `@svgdotjs/svg.js` not respecting provided image dimensions

- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
This PR fixes an issue where dark mode would flicker when the user took a snapshot of the presentation. The flicker was caused by a workaround introduced in version 2.6, which no longer appears to be necessary. I ran several tests and was unable to reproduce the original bug, so the workaround has been removed.
PR the introduced the workaround: https://github.com/bigbluebutton/bigbluebutton/pull/17194
Related issue: https://github.com/bigbluebutton/bigbluebutton/issues/17192
Closes #20989
- Open settings
- Enable dark mode
- On presentation click on options -> Snapshot of current slide
[Screencast from 27-03-2025 11:55:37.webm](https://github.com/user-attachments/assets/917d214e-b1b8-42ec-9e4a-bcda5c8c7fe6)
> Fix(html5): Dark mode flicker on presentation snapshot

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/styles.js
- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
- bigbluebutton-html5/imports/ui/stylesheets/styled-components/globalStyles.js
This PR fixes an issue where the three buttons on the whiteboard were not having their colors inverted when dark mode was enabled.
To resolve this, I used two approaches:
1. For the **Undo** and **Redo** buttons, which were using `<img>` elements to load images, I replaced them with `<div>` elements using CSS `mask`, following the same approach used by Tldraw. This allows the colors to be correctly inverted by dark mode.
2. For the **Styles** button, which is managed internally by Tldraw, I applied a global CSS style to ensure proper color inversion when dark mode is active.
Also made a small change suggested here https://github.com/bigbluebutton/bigbluebutton/pull/22777#issuecomment-2752995386 moving the styles for the tldraw global styles instead of keeping them on general one.
n/a
- …
> Fix(html5): Whiteboard dark mode buttons

- .github/workflows/automated-tests.yml
- bigbluebutton-tests/playwright/package.json
- Adds same `test-chromium-ci` and `test-firefox-ci` commands without `CI=true`
Ease test results reading - same default test logging, especially when running on a remote server (as we usually do during release testing)
You can still use `npm run test-chromium` followed by `test(s)_suite(s)` for filtering
> refactor(tests/npm scripts): Add npm scripts without `CI=true`

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/breakout-join-confirmation-graphql/component.tsx
- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/component.tsx
- bigbluebutton-html5/imports/ui/components/breakout-room/hooks.ts
- adds a log for the moderator with room info when breakout rooms are created
- adds a log if media stop fails when joining a breakout room
- adds a log to the breakout room invitation when free join is selected, with info about the breakout rooms available for the user to join
- adds a log to the breakout room invitation when free join is selected, with info about the room selected by the user
- change `app_component_componentdidmount` log to include info about the room being joined
partially #22836 
Does not implement akka-apps logs (to be addressed in a subsequent pull request, cc @gustavotrott )
> chore(html5): Add logs for breakout management

- bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx
Add a Check for `name` and `toLowerCase` on connection status.
Client logs pointing to a case where this field can be unavailable
> Fix(html5): Client error log related to missing name of user

- bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml
- docs/docs/administration/customize.md
- [fix(freeswitch): add basic dialplan instructions to reject anonymous UAs](https://github.com/bigbluebutton/bigbluebutton/commit/fc6f77f8522b728f1a46b604bf7bc0f3b2d3ba81) 
- Add the following basic checks to deny anonymous callers from joining
BBB-FreeSWITCH conferences by default:
- Caller-ID-Name/Number: common anonymity values, empty headers
- CLIR headers: honor number/name anonymity requests.
- Those checks reside at the conference level (bbb_conference.xml), which should
capture all calls directed to a *BigBlueButton* conference.
- Allowing anonymous UAs can be achieved by removing the
`reject_anonymous` extension and reloading the XML Dialplan
module/restarting FS.
None
> fix(freeswitch): add basic dialplan instructions to reject anonymous UAs

- bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx
Adjusts random assign algorithm, so users are evenly spread in breakout rooms
current algorithm only assigns a random room to each user, leading to rooms with many users and rooms with less users (sometimes empty) - with the new approach the users will be shuffled and then assigned to the rooms
1. join a meeting with a moderator and a a big number of viewers (> 10)
2. open create breakout panel
3. increase the number of breakouts
4. select "randomly assign" 
5. see if the users are evenly distributed
> breakouts: randomly assign users to rooms in an evenly distributed manner

- docs/docs/administration/customize.md
- [docs: add more info on dial-in anonymity](https://github.com/bigbluebutton/bigbluebutton/commit/a33098f4c5d790a9176a5c9a061e77639e6b8880) 
- Add more information to the docs section that explains
the dial-in anonymity checks in place, as well as move
it to a more appropriate place.
None
> docs: add more info on  dial-in anonymity

- bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx
this PR fixes the issue of the presentation zoom was not propagated when the fit to width was enabled.
Closes #22729
- Join Two users
- WIth Presenter enable fit to width
- With Presenter open a webcam.
[Screencast from 31-03-2025 17:21:36.webm](https://github.com/user-attachments/assets/2d42c753-0837-4266-813b-20b9147668ec)
> Fix(html5): Presenters height not propagating for another user when fit to width is enabled

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
This PR fixes the issue where the player does not correctly sync when the presenter drags the progress bar instead of clicking to seek.
Part of ##22176
- Join with two participants
- on presenter's client drag the progress bar
- See both clients synced
Before
[Screencast from 02-04-2025 09:58:34.webm](https://github.com/user-attachments/assets/6d171dd5-eb6c-47cb-8ee8-c7f73a952e6b)
After
[Screencast from 02-04-2025 09:56:19.webm](https://github.com/user-attachments/assets/41e96cb1-b864-48bd-9d9e-fa8763f66873)
> Fx(html5): External video no seeking when sliding the progress bar

- record-and-playback/core/lib/recordandplayback/edl/audio.rb
Audio render ffmpeg command was getting too big in long recordings with many different audio files, causing a crash (the command size was too big, and also we could hit 'too many open files' due to the same audio being referenced multiple times in the command).
- Process each segment individually, and concat them later (similar how it is done with webcams)
Crashs in production in some meetings (1h+) where some users were always joining audio.
> fix(recording): split audio render command for each segment

- bbb-graphql-middleware/internal/websrv/connhandler.go
It will help to debug when the client log show `graphql_server_closed_connection` "Graphql Server closed the connection".
> chore (gql-middleware): Log the reason why middleware disconnected the browser

- build/packages-template/bbb-html5/build.sh
This PR resolves the issue where CSS file requests included the default version instead of the build version. The problem occurred because the CSS files were being compressed before the build script had a chance to set their correct version, resulting in modified CSS files but outdated compressed versions. By moving the version assignment step to occur before compression, all files now correctly reflect the intended build version.
N/A
But probably related with the PR #22839 
Best way to test it, is the the binary from the test summary and install it on your own server, the files will be in `/usr/share/bigbluebutton/html5-client/`
Before:
After:
> Fix(html5): Version being incorrectly placed in CSS

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/service.ts
> fix (html5): Modify the `messageToMarkdown` function to support uppercase links

- bigbluebutton-html5/imports/ui/components/raisehand-notifier/styles.js
Adjusts icons position in raise hand toast when more than 3 users have raised hands
2. have at least 4 users with raised hands
3. as a moderator, check raise hand notification
> style: adjust raise hand toast with many users

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fixes an error that would sometimes occur during `insertDocument` calls that was being caused by a reference to an undefined `meetingId` variable.
Closes #22876
1. Create a meeting with API and add "presentation" to "disabledFeatures".
2. Send an `insertDocument` request for that meeting.
3. A `FAILED` response should be received.
> fix(API): Use meeting to get ID for insertDocument

- bigbluebutton-html5/imports/ui/core/hooks/useCurrentUser.ts
- adds a new error (logCode `multiple_current_user_error`) to log if the current user subscription returns more than one user
- filters results to only return those with the same id as the current user
> fix(client): log info about multiple users being returned from current user subscription and filter results

- .github/workflows/automated-tests-publish-results.yml
This pull request introduces a new job named **`publish-test-results`** in the **`Automated tests - publish results`** workflow.  
The new job is inserted **before** the `comment-pr` step.
- **New job**: `publish-test-results`
- Runs after `get-pr-data`
- Logs a simple `"hello world"` message (placeholder for future enhancements)
- **Updated `comment-pr` job**:
- Now depends on both `get-pr-data` and `publish-test-results`, ensuring proper execution order.
This prepares the workflow for publishing test results or artifacts in the future.  
Adding a dedicated step allows easier expansion without disrupting the existing PR commenting logic.
- Replace the placeholder with real test result parsing and publishing.
- Attach test reports or summaries as PR comments or workflow artifacts.
> (feat:ci) New step in CI to publish in digital oceanic spaces (mockup)

- bigbluebutton-html5/imports/ui/components/whiteboard/styles.js
Fix issue where the Assets tool incorrectly appears in the main toolbar for viewers when Multi Whiteboard mode is enabled.
N/A
- Join the meeting with a presenter and a viewer.
- Enable multi whiteboard.
- Look at viewer toolbar.
Before
After
> Fix(html5): Whiteboard assets tool appearing on main bar for viewers

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.tsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.tsx
Add camera stream ids to video tags.
None
For selection purposes. That way, we can select a video tag by stream id.
> html5: Add stream ids to webcam video tags

- bbb-graphql-actions/src/actions/userSetReactionEmoji.ts
- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/reactions-button/styles.js
- bigbluebutton-html5/public/locales/en.json
Includes a button to remove reaction in reactions bar
[Screencast from 2025-04-15 10-41-47.webm](https://github.com/user-attachments/assets/db06d592-ac44-4550-8d40-84d7103a919b)
Closes #21311
2. open reactions bar and select a reaction
3. open reactions bar again and select the X button
4. previously selected reaction should be removed
> fix: Emojis can't be reverted

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/chat-message-list/component.tsx
- Fixes chat scroll not sticking to the bottom after clicking 'More messages' button.
n/a
Sometimes, when lots of activity is going on in the chat, if the user clicks 'More messages below' to see the latest messages the client will not take him to the bottom if a new message arrives. That's because when a new message arrives, the container is resized and assumes a new height. But the auto scroll engine doesn't know this new height and will take the old height into account.
You need a way to send messages in the chat on regular interval in order to test it. Then, you can play around with the 'More messages below' button.
> fix(html5): Chat scroll not sticking to bottom

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfSlidesGenerationService.java
- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationConversionCompletionService.java
Adds error handling and logging for document conversion threads. Currently whenever an unchecked exception occurs in one of the worker threads responsible for document conversion the exception simply causes the thread to die and be replaced with no stacktrace which will lead to odd scenarios where document conversion fails to fully complete but no error is seen in the logs. Executing these threads in a try-catch block should allow the parent thread to catch and then log any exceptions that occur in the worker threads which will allow for a better understanding of any issues that occur during the document conversion process. Also removes some unnecessary logs that were added in #22900. 
Seeing a `Conversion task failed for page` error in the BBB Web log indicates that a problem occurred …
> fix(API): Add error handling to document conversion threads

- bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx
Resolved an issue where external video event updates were no longer propagated to viewers due to a reference to the last event not being cleared upon external video change
Closes #22964
1. join a meeting with 2 users
2. share an external video
3. pause the video
4. stop sharing the video
5. share another external video
6. pause the video
7. the video should also be stopped for the viewer
> fix: External youtube video is not syncing

- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.js
- bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
- bigbluebutton-html5/imports/ui/components/sidebar-navigation/styles.ts
- Fixes the icons being out of screen when screen is too small in the navigation sidebard
- (mobile): Adjusts presentation toolbar in mobile, also adds scroll if needed (by @Arthurk12)
- Fix Audio Filters toggle state not updating
> fix: add sidebar navigation and presentation toolbar scroll

- bigbluebutton-html5/imports/ui/components/common/menu/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/hooks.js
This PR fixes the issue of the autohide being hiding the buttons when a dropdown is open, it happened because the options button is non-native and is rendered in anothe part of the dom and just positioned over the whinteboard, so on mouse leave, I made it veirfy if the menu is open and just hide the buttons when menu is closed and the mouse out of the screen.
N/A
- Join with one user
- on settings enable auto hide for whiteboard tools
- Open the options dropdown and hover it
- See the tools visible 
[Screencast from 03-04-2025 10:50:43.webm](https://github.com/user-attachments/assets/d03bff02-f350-4ed0-afaa-d0033c778989)
> Fix(html5): Whiteboard autohide not working for opened menus

- bigbluebutton-html5/imports/ui/components/common/error-boundary/error-boundary-with-reload/component.jsx
Fix issue of whiteboard being crashed if the clipboard permission is denied, I've added a new condition for the reason "NotAllowedError" triggered when a browser permission is denied.
Closes #22955
- Open `Site settings`
- Change permission `Clipebaord` to `block`
- Draw a line on whiteboard
- R-click to copy and past
> Fix(html5): Whiteboard crash when clipboard permission is denied

- bigbluebutton-html5/imports/ui/components/chat/chat-graphql/component.tsx
When the user started a private chat but don't send any message and then pressed the back button, the chat became empty.
- Fixed by going back to the public chat
1. Join with two users.
2. Click start private chat button in user list
3. Don't send any message, just press the back arrow button
> fix(private-chat): back button inconsistent state

- bigbluebutton-html5/imports/ui/components/user-list/user-list-participants/list-item/service.ts
Viewers couldn't open private chat with other viewers because there was a wrong permission check. This PR fixes this check.
> fix(private-chat): viewers can't chat with each other

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
The PR https://github.com/bigbluebutton/bigbluebutton/pull/22923 changed the structure of the plugin extensible-area in the actions-bar button. This PR is a hot-fix to avoid that plugins with old SDKs break the entire client.
Closely related to https://github.com/bigbluebutton/bigbluebutton/pull/22923
> fix(html5): fix actions-bar extensible area breaking when plugin used old SDK 

- record-and-playback/core/lib/recordandplayback/edl/video.rb
In rare circumstances a deskshare video can be recorded which contains audio, but no video frames. Ensure that files where no video frames can be decoded are excluded from video processing.
> recording: check for videos with no decodable frames

- bbb-graphql-server/bbb_schema.sql
- [fix(core): increase max authToken size to 50 chars in user table](https://github.com/bigbluebutton/bigbluebutton/commit/bdda04165c9858ae0ff9a08da2f6b7de46d3d865) 
- The authToken property in the `user` table has a size limit of 16 chars.
That same property can be as large as the userId (intId) in scenarios
where non-web users (e.g.: dial-in) are involved, since authToken is
spoofed in akka-apps to be the same as that user's intId.
This may cause the insert op for that external user to fail, which
translates to them being missing in the user list.
- Increase the max authToken size to 50 chars in the `user` table, which
matches `userId`.
None
> fix(core): increase max authToken size to 50 chars in `user` table

- bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx
- bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
- bigbluebutton-html5/imports/ui/components/presentation/styles.js
- bigbluebutton-html5/imports/ui/components/sidebar-content/component.tsx
- Fixes missing top part of presentation/shared notes when in grid layout.
- Fixed presentation not fully showing when in sidebar (missing the sides):
- Fixed bug where the presentation is shown instead of pinned shared notes when changing between layouts
(grid, but also when notes are minimized and you change to presentationFocus)
https://github.com/user-attachments/assets/0e810083-df08-4020-ad18-29aad4c537db
This alson happens in 3.0
- Fixed CameraDock position when in sidebar (was stick to bottom)
> Fixes for video/presentation focus layout

- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- docs/docs/data/getJoinUrl.tsx
- docs/docs/development/api.md
Currently, only moderators can pass parameters when calling the `getJoinUrl` endpoint. However, this limitation poses issues in certain cases:
- **Mobile App (Whiteboard in iframe):** The app requests the `joinUrl` with the `enforceLayout` parameter to display only the whiteboard.
- **Plugins (e.g., hybrid rooms, remote-camera):** These may need to define a specific layout or pass `userdata-` parameters to control layout traits or behavior.
To address these scenarios while maintaining meeting security, we’ve introduced a new config option:  
`getJoinUrlUserdataBlocklist` in `bigbluebutton.properties`.
This config defines which `userdata-` parameters should be **blocked** when the user is **not a moderator**. By default, the following `userdata-` parameters are blocked:
- …
> refactor (bbb-web): Allow `getJoinUrl` parameters for non-moderators

- bbb-webrtc-sfu.placeholder.sh
- docs/docs/new-features.md
* [build(bbb-webrtc-sfu): v2.18.1](https://github.com/bigbluebutton/bigbluebutton/commit/c72077ba081be012bc0974222ed18e27b2724163) 
* chore(livekit): bbb-webrtc-recorder as the default recording adapter
* [docs(livekit): remove egress steps, add note about webrtc-recorder](https://github.com/bigbluebutton/bigbluebutton/commit/ea5686f0d37ff30aeae5b761f6d093892f3bdbdd) 
* bbb-webrtc-recorder is the default recorder for LiveKit tracks and is
enabled by default.
* Remove livekit/egress installation steps and make a note about this
change.
None
Ref #21059
> build(bbb-webrtc-sfu): v2.18.1; docs(livekit): remove egress steps, add note about webrtc-recorder

- build/packages-template/bbb-livekit/after-install.sh
Port of https://github.com/bigbluebutton/bigbluebutton/pull/23037 into 3.1
- [build(livekit): automatically set keys to webrtc-recorder](https://github.com/bigbluebutton/bigbluebutton/commit/ff4f2d920947955265cb9d172104f37dd34ed43a) 
- Automatically set LK's API key and secret to bbb-webrtc-recorder when
livekit-server is installed. See inline comment in after-install for
more details.
- Additionally:
- Guarantee key/secret are set for both webrtc-sfu and webrtc-recorder
regardless of whether livekit.yaml exists beforehand. Take only their
(SFU/rec) own configs into account when determining whether they
should be set or not.
None
> [3.1] build(livekit): automatically set keys to webrtc-recorder

- build/packages-template/bbb-livekit/after-install.sh
- [build(livekit): automatically set keys to webrtc-recorder](https://github.com/bigbluebutton/bigbluebutton/commit/ff4f2d920947955265cb9d172104f37dd34ed43a) 
- Automatically set LK's API key and secret to bbb-webrtc-recorder when
livekit-server is installed. See inline comment in after-install for
more details.
- Additionally:
- Guarantee key/secret are set for both webrtc-sfu and webrtc-recorder
regardless of whether livekit.yaml exists beforehand. Take only their
(SFU/rec) own configs into account when determining whether they
should be set or not.
None
Ref #21059 
Ref #23015
> build(livekit): automatically set LK keys to webrtc-recorder

- bigbluebutton-html5/imports/ui/Types/meetingClientSettings.ts
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.tsx
- bigbluebutton-html5/imports/ui/core/initial-values/meetingClientSettings.ts
- bigbluebutton-html5/private/config/settings.yml
- Add timeout to automatically redirect users to the logout URL on meeting end (or closing the window if the session is a breakout room).
Closes #22993
> fix(html5): Add timeout to redirect on meeting end

- bigbluebutton-html5/imports/ui/components/plugins-engine/manager.tsx
- bigbluebutton-html5/imports/ui/components/plugins-engine/query.ts
- bigbluebutton-html5/imports/ui/components/plugins-engine/types.ts
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
Problem: When multiple plugins were loaded in the same meeting, one `localesBaseUrl` could interfere in the others'. That's mainly because the query we had to search for this particular base URL was not filtering for the `pluginName`, so basically the locales would work quite well when having only one plugin.
Solution: As `localesBaseUrl` does not change during the entire meeting and we have that information the second we build the `pluginApi` for a particular plugin, instead of getting it via subscription, or even query, the client (bigbluebutton-html5)  will send it inside the pluginApi, which besides fixing the issue, will spare another subscription/query from running.
Closely related to: https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/pull/178
See the before and after …
> fix: Fix locale problem when having multiple plugins

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
Now breakout rooms will inherit the list of `disabledFeatures` from the parent meeting.
https://github.com/user-attachments/assets/222986cf-68ec-48ec-b0ba-80fc8750792e
Closes #21953
> fix (akka-apps): Breakout rooms not inheriting `disabledFeatures` from the parent meeting

- bbb-graphql-server/bbb_schema.sql
The `order_by` of `UserListSubscription` was adjusted here: https://github.com/bigbluebutton/bigbluebutton/commit/445e85e4b3a9512dad3fc97e5db35f17de599174
The table index should be updated accordingly.
> perf: Include `bot` for the list of columns for userlist index
