bigbluebutton/bigbluebutton

bigbluebutton-client/branding/default/style/css/BBBDefault.css, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AdvancedList.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
This PR changes the chat indicator from a black box back to the default background highlight style.
=> Change chat message selection indicator

bigbluebutton-client/src/org/bigbluebutton/util/i18n/ResourceUtil.as
Imporve ResourceUtil:
- Delete `isPreferredLocaleAvailable`
- Improve `getIndexForLocale`
- Imporve `localeChangeComplete`
- Store locale names and label as `String` instead of `XML` object.
- Use Linux EOL instead of the strange mix of Windows and Linux EOL.
=> Improve ResourceUtil.as class

bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java, bigbluebutton-web/src/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
Sometimes, several create meeting API requests are received for the same meeting at the same time. An example would be the Demo Meeting. We don't synchronize the creation of meeting that it results in a meeting with 2 different voice conference number between akka-apps and bbb-web. The first create request processed would be in akka-apps while the last request would be in bbb-web. 
So if the first request had a voice conf of 12345 while the last request has voice conf 67890, the meeting actor in akka-apps would be listening for ESL events on 12345 while the client would be joining 67890 voice conference.
This results in the client not displaying the voice icons but the users can hear each other.
This PR makes sure that there can only be one meeting created for multiple create requests by …
=> Synchronize create meeting

bigbluebutton-html5/imports/ui/components/settings/service.js
Increase default font size to 16px because this is the browser default.
=> [HTML5] Increases default font size

bigbluebutton-html5/imports/ui/components/actions-bar/service.js
added missing import that was causing the join audio button to not display the modal when clicked.
=> [HTML5] - JoinAudio btn fix

bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/models/WhiteboardModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/TextDrawListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.mxml
While a text is being edited in the whiteboard, a single mouse click does no more create a new text box, it just closes the current text zone.
=> Improve user experience for whiteboard text tool

record-and-playback/presentation/scripts/publish/presentation.rb
The code was previously dividing by the total number of votes rather than the max number of votes, which meant it was underestimating the width of the bars. In some cases, this meant that the label for number of votes would overlap the percentages.
Now fixed:
Also, the margins at the top/bottom were too large, meaning that in some cases (wide aspect ratio slides with few poll results) the bars were too squished. Also fixed:
Fixes #3725
=> recording presentation: Improve calculations of bar sizes in poll results

bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
Fix for #3786 
Improved the logic for when to update the messages list in the private chat, in particular don't update the messages list if the private chat partner is offline.. (Before this fix the scenario was leading to forever loop freezing the client)
=> [HTML5] Fix client freeze on private chat partner leaving. Fix for #3786

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/UsersModel.scala
- check if the client validating the token mathes the userId of the registered user. If
we don't, the client can pass any token and impersonate other users.
=>  Check userId when validating token

bbb-common-message/src/main/java/org/bigbluebutton/common/messages/RegisterUserMessage.java
In register user message, we were putting the externalUserId as the internal userId. When we use the internal userId to validate the token, the validate token reply reruns false if the internal userId and external userId are different as the case in breakout rooms.
=>  user internal userId instead of external userId 

bigbluebutton-client/locale/en_US/bbbResources.properties
This PR switches the key for focusing the chat message list from 'M' to 'R' because m is taken by IE. This PR also clarifies the the purpose of the key to avoid confusion with the global key to focus the chat input area.
=> Fix focus chat message list key and label

bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml, bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java
Two new improvements to the document conversion fallback:
1. Remove page extraction to PDF and replace image `convert` conversion command with `gs`.
2. Image conversion uses 72 DPI option if the initial conversion has timed-out or the SWF object contained twice the number of allowed objects, or use the 150 DPI by default.
=> Imporve document conversion fallback

bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/MessageReceiver.java, bigbluebutton-web/src/java/org/bigbluebutton/web/services/KeepAliveService.java
On redis-cli, we noticed that BbbWebSub isn't on the "client list". The auto-reconnect on bbb-web
wasn't triggered as not log was generated in bbb-web.log. Maybe the exception was something we
did not handle. Try catching all exception on this jedis connection.
=>  Add catch all exception to bbb-web redis subscriber

record-and-playback/presentation/scripts/publish/presentation.rb
The previous code assumed that if a shape event's timestamp was during the
time when a particular slide was visible, then the shape belonged to that
slide. This isn't always true with the text shapes, since a final close
event can be sent after the slide has switched.
For a more future-proof matching, use the presentation name and page number
fields on the shape events when available to match them with the appropriate
slide image.
=>  Use the presentation name/page number to match shapes to pages, not time.

bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/api/users/server/modifiers/createDummyUser.js, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/private/config/public/app.yaml, bigbluebutton-html5/private/config/public/user.yaml
WIth this new flag we can turn off/on the overall moderator functionalities to date. Should allowHTML5Moderator be false, these are the features that will be disabled:
-there will be no 'Participants' section in Settings
-there will be no way to kick/mute/unmute user
As a side note, this pull requests also hides the Actions button which currently only holds features not yet implemented.
The Video section of the settings is also temporarily hidden until the video capabilities require its display
=> HTML5: demote html5 moderator user to viewer based on flag

bigbluebutton-client/src/org/bigbluebutton/common/Images.as
All the cursor icons used for the whiteboard tools have their upper left part colored in white. Except the rectangle.
Currently used cursor icons: [Triangle](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/triangle.png), [Ellipse ](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/ellipse.png), [Line](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/line.png)
But for the rectangle we are using an icon with solid borders [shape_square](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/common/assets/images/shape_square.png …
=> [Flash] Corrected the cursor icon for the rectangle tool

bigbluebutton-html5/imports/api/audio/client/bridge/verto.js
Before this fix Verto audio users in html5 client were appearing as two users - a web and a voice one.
=> HTML5: Unify user and audiouser in verto bridge

bigbluebutton-client/resources/prod/lib/webrtc_stats_bridge.js
Switch to the promise-based getStats, and use the standardized
property names where available, with fallback to handle Chrome,
which hasn't fully switched yet.
The stats now only track the outgoing audio stream, as a way to
indicate quality, since the user can't hear themselves. This
might be revisited later; it would require tracking the stats
separately for incoming vs. outgoing and e.g. returning whichever
is worse.
=> Update webrtc stats bridge for modern Chrome/Firefox APIs

record-and-playback/core/scripts/rap-process-worker.rb
If processing didn't succeed, the directory where it is trying to write
the file might not exist, causing an exception in the worker which leads
to it getting stuck in a retry loop.
=> rap-process-worker: Write processing_time file only if processing succeeded

bbb-api-demo/src/main/webapp/demoHTML5.jsp
Added default values for meeting name and moderator status so we are able to log in from page only asking for username. This will allow using the html5 client from a combined [html5 vs flash] demo page
=> Demos: Allow username only logins (for demo purposes)

bigbluebutton-html5/imports/api/shapes/server/modifiers/addShape.js, bigbluebutton-html5/imports/ui/components/whiteboard/shapes/text/component.jsx
Fixed 2 Text shape bugs:
- it didn't handle new lines for some reason.
- it didn't preserve inner white spaces, they were always combined into one.
Resolves #3938
=> [HTML5] Text Shape 2.0

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
We have a "click" listener in the dropdown component attached to the window. It listens to user clicks, closes the dropdown (Status/Settings etc) if it was open, and moves focus back to the button that opens/closes the dropdown.
For some reason "click" listener was added in the `componentDidMount`, and as a result we always had 2 "click" listeners hanging around and firing on every mouse click, since "Status" and "Settings" dropdowns are always rendered, but their contents are not shown by default.
Moved "click" listeners initialization to the `handleShow` / `handleHide`. Now they are attached and removed when the user actually opens/closes the dropdown.
=> HTML5 - dropdown click listeners' fix

bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/service/WhiteboardService.java, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/TextObject.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/ShapeDrawListener.as
* Corrected an inverted length check in the ShapeDrawListener that stopped shapes from drawing
* Added a maximum char length for text annotations of 1024
=> Fix shape drawing and set max text length for text annotations

bigbluebutton-client/src/org/bigbluebutton/common/IMETextField.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/TextObject.as
This PR manually enables the IME mode when focusing into the Whiteboard TextObject for editing. This change allows users to input text as expected when typing in Japanese, Korean, and Chinese and the IME mode is enabled in the OS.
The PR is a fix for issue #2678.
=> Enable IME for text tool's basic TextField - fixes #2678

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This will allow HTML5 clients to call enterAPI to obtain correct logoutURL, welcomeMessage, etc (html5 clients will pass .....api?sessionToken=XXXXXXXX now that they can obtain it
=> Drop requirement for session[sessionToken]Send sessionToken in enterAPI redirect=false

bigbluebutton-html5/imports/api/chat/server/methods/sendChat.js
Function parseMessage was never called before publishing the chat message to Redis. Thus links sent from HTML5 client were never recognized and they were published as plain text in both html5 and Flash clients.
=> HTML5 - Chat links fix

bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/CursorPositionListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCursor.as
* Fixed an issue where the custom whiteboard cursor wasn't reset when canvas editing was disabled
* Fixed a divide-by-zero case when the cursor position listener fires before the whiteboard canvas has been set up
* Added a name next to the whiteboard cursors to add clarity when there are more than one
=> Whiteboard cursor fixes

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgDeserializer.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/ReceivedMessageRouter.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/UserBroadcastCamStartMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/UserBroadcastCamStopMsgHdlr.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/messages/MessageBody.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/messages/Messages.scala, bigbluebutton-client/src/org/bigbluebutton/core/connection/messages/UserBroadcastCamStartMsg.as, bigbluebutton-client/src/org/bigbluebutton/core/connection/messages/UserBroadcastCamStartMsgBody.as, bigbluebutton-client/src/org/bigbluebutton/core/connection/messages/UserBroadcastCamStopMsg.as, bigbluebutton-client/src/org/bigbluebutton/core/connection/messages/UserBroadcastCamStopMsgBody.as, bigbluebutton-client/src/org/bigbluebutton/core/managers/ConnectionManager.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
Implement user start/stop broadcast cam message using new message format. You can see how to send message from the client and how akka apps handles the message.
Also, how the cam started/stopped event messages are broadcasted to all clients.
=> user start/stop broadcast cam message

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/managers/WhiteboardManager.as
There was a three way race on client load to try and add the WhiteboardCanvas to the SlideView and set the whiteboardId that is supposed to be displayed. This PR moves the setting of the whiteboardId out of the PresentationWindow to split that logic up and hopefully make it more clear.
=> Rework setting the whiteboardId to display

bigbluebutton-html5/imports/ui/components/user-list/user-list-item/styles.scss
Fixes the missing chevron issue.
now visible:
=> [HTML5] - Missing dropdown menu chevron fix

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/meeting/SyncGetMeetingInfoRespMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentation/PresentationApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentation/SyncGetPresentationInfoRespMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SyncGetUsersMeetingRespMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationMsgs.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala, bigbluebutton-html5/imports/startup/server/redis2x.js, bigbluebutton-html5/private/config/server/redis.yaml
We need the data returned to populate the collections on the html5 client (if meteor process (re)started when some meetings were already active)
=> 2.0 Trigger syncing with state from akka-apps

bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollingService.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/model/Presentation.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
This PR removes the screenshare code that was embedded into the PresentationWindow and Presentation classes. The screenshare module is currently in a non-working state and will need to be fixed in a subsequent PR.
=> Remove screenshare from presentation

bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
In the current Firefox beta (55.0b5) when the tab with BBB in it loses focus the size of the application is set to (0,0) which is impossible under normal circumstances. I've added an improved resize handler that uses ChangeWatchers to the MainApplicationShell that recalculate the sizes.
Note: This PR doesn't fix the lockup that can happen when Firefox is maximized and the tab is switched.
=> Skip layout change when dimensions are invalid

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss, bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.scss, bigbluebutton-html5/imports/ui/components/audio/audio-notification/styles.scss, bigbluebutton-html5/imports/ui/components/audio/audio-test/styles.scss, bigbluebutton-html5/imports/ui/components/button/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-form/message-form-actions/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-list/styles.scss, bigbluebutton-html5/imports/ui/components/dropdown/styles.scss, bigbluebutton-html5/imports/ui/components/error-screen/styles.scss, bigbluebutton-html5/imports/ui/components/loading-screen/styles.scss, bigbluebutton-html5/imports/ui/components/modal/base/styles.scss, bigbluebutton-html5/imports/ui/components/modal/simple/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/styles.scss, bigbluebutton-html5/imports/ui/components/settings/submenus/styles.scss, bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/video-dock/styles.scss
On this PR we change the import from relative to absolute, preventing when moving components around directories, `npm start` crashing with no help messages because could not find the .sass file.
Using the absolute path on the inner components, even moving them around will keep the same location to `_all`
Example of crashing message:
=> [HTML5 - 2.0] Change relative path of the sass imports to absolute

bigbluebutton-html5/imports/api/2.0/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/api/2.0/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/private/config/public/app.yaml
- Add missing property `meetingId` on the meeting object.
- Remove the welcomeMessage from the HTML5 config and get it from the meeting api.
=> [HTML5 2.0] Fix meeting add

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
Fixed an error in the dispatching of the MadePresenterEvents. Those events are used when the state of the local user changes, but they were being dispatched when any user was changed instead.
I also corrected the maximum slide height calculation so that it didn't reserve too much space.
=> Presenter and slide size fix for 2.0

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/resources/prod/lib/verto_extension.js, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/events/WebRTCPublishWindowChangeState.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/WebRTCDeskshareManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
Once you start sharing the publish window opens and displays a loading message
=> Screenshare loading screen

bigbluebutton-html5/imports/api/2.0/screenshare/index.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/eventHandlers.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/broadcastStarted.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/broadcastStartedVoice.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/broadcastStopped.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/broadcastStoppedVoice.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/startedVoice.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/handlers/stoppedVoice.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/index.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/methods.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/modifiers/addBroadcast.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/modifiers/addVoiceUser.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/modifiers/clearBroadcast.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/modifiers/clearVoiceUser.js, bigbluebutton-html5/imports/api/2.0/screenshare/server/publishers.js, bigbluebutton-html5/server/main.js
The following messages are handle in this PR:
=> [HTML5 2.0]  - Move screenshare messages to 2.0

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/screenshare/ScreenshareStoppedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
Note:
We currently do the same (handle captions, polls, screenshare) on Presenter Switch and on Presenter Left. But Presenter Switch follows from Presenter Left so we technically handle the same twice (second time is ignored).
In my opinion we should keep it like this but if reviewer thinks we should not, please suggest so
=> Stop screenshare and poll on presenter leave

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserLeftVoiceConfEvtMsgHdlr.scala
- When a user is in the voice conference using webrtc and the browser refreshes, FS doesn't detect that the
webrtc connection has gone down so it is not able to send a user left voice conf message. It would take a
media timeout for FS to send a user left voice conf event. Remove the user from voice list when user leaves
the meeting. Not sure how this behaves on auto-reconnect of bbb-apps while the webrtc connection is actually
still working.
=> Remove voice user on refresh

bigbluebutton-web/web-app/WEB-INF/freemarker/include-recording.ftlx
There were some new parts added to the getRecordings template, but not included in the recording metadata which resulted in some exceptions being thrown when trying to build the getRecordings response. I've removed the offending pieces and the response is working like it was in 1.1 again.
=> Remove broken parts of getRecordings response building

bbb-webhooks/application.coffee, bbb-webhooks/hook.coffee, bbb-webhooks/id_mapping.coffee, bbb-webhooks/web_hooks.coffee
Was creating a new connection for each hook or mapping created and never closed them.
Now it created 2 connections only, one to read/write hooks and mappings and another to listen to events (pubsub).
The connection to read/write could be created and removed on demand, but decided not to do it because it could more easily result in connections being left open.
=> Fix multiple connections to redis on webhooks

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
This PR records a SharePresentationEvent when a ConversionComplete comes in with current=true. This is to match a similar behaviour from 1.1.
=> Record extra SharePresentationEvent when conversion complete and current

bigbluebutton-html5/imports/api/2.0/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/api/2.0/voice-users/server/handlers/joinVoiceUser.js, bigbluebutton-html5/imports/api/2.0/voice-users/server/modifiers/addVoiceUser.js, bigbluebutton-html5/imports/api/2.0/voice-users/server/modifiers/removeVoiceUser.js
Missing the `joined` state, user couldn't leave audio when using microphone in the HTML5 client.
=> [HTML5 2.0] Fix VoiceUser microphone state

record-and-playback/core/scripts/bigbluebutton.yml, record-and-playback/presentation/scripts/publish/presentation.rb
This fixes a few syntax errors and issues with the changes for bbb 2.0 GotoSlide events
It also marks recordings made on a 2.0 server with the '2.0' version, so we can handle things like the new thickness values correctly.
Add handling for the new 'command' element on the pencil shape, for the smooth curves feature. Also draw single-point paths as dots.
=> BigBlueButton 2.0 recording fixes

bigbluebutton-client/resources/prod/BigBlueButton.html
Workaround for this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1360666
Resizing the Flash content for half a sec makes Flash responsive again.
=> Fixes hanging Flash on tab switch in Firefox 55-56

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/StopPollReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStopMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala
Fix for #4191 
We now remove the webcam from a user who is leaving the meeting (due to refresh or reconnect). On page refresh we start with a clean slate and the webcam will not be re-shared automatically. On reconnect the webcam will be automatically shared if it was shared prior to the reconnect.
=> [Akka-apps 2.0] Drop camera for leaving user Fix for #4191

bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/UserGraphicHolder.mxml
UserGraphicHolder is keeping the move applied at the GraphicWrapper when the fullscreen is turned on. Just setting move to origin to fix it. Also refactored the parent selector so he selects the DisplayObjectContainer named BigBlueButton. Looks like to be a unique and static property to search for.
=> Fixed webcam fullscreen display position

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
This pull request tries to fix two things, actually.
First is a NPE that was happening at least in Firefox 54 (64-bits, Linux). accessibilityProperties in chatMessagesList could be null when trying to set it's description. I notice this because the copy/save/clear buttons on chat were never being initialized. They were simply missing on my Firefox.
The second thing is some extra code so the promote/demote users would actually work.
=> Fix promote demote users

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomEndedInternalMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LogoutAndEndMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingExpiryTrackerHelper.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/SendTimeRemainingUpdateHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/meeting/EndMeetingSysCmdMsgHdlr.scala
- send breakout ended event
- do not send negative time remaining updates
=>  - end breakout rooms when parent meeting ends

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingAfterReconnectReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala, bigbluebutton-client/src/org/bigbluebutton/core/events/TokenValidReconnectEvent.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/maps/UsersMainEventMap.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
Added a separate event to distinguish user join on reconnect from fresh user join. Using this piece of information we drop any matching voice users from akka-apps' voice user cache OR we recover them
Fix for #4229
=> Handle properly audio state on reconnect

bigbluebutton-html5/imports/startup/server/redis2x.js, bigbluebutton-html5/private/config/server/redis.yaml
Since Richard PR https://github.com/bigbluebutton/bigbluebutton/pull/4220 lots of messages were being ignore because of the separation of the redis channel contents, this is fix on this PR.
=> [HTML5 2.0] Handling Separate Redis Channel

bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
fixes the meeting title so that it doesn't default to "Default Room Title", when a title is provided.
=> [HTML5] - Meeting title fix

bigbluebutton-html5/imports/ui/components/audio/container.jsx
We were missing the check for the property `autoJoinAudio` inside audio modal, the Audio Modal was always showing, was fix on this PR.
=> [HTML5 2.0] Fix Audio Modal on Meeting Join

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/ShapeFactory.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/models/Whiteboard.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml
This PR changes the annotation storage from an array to a hash map. This change will hopefully decrease the run times when editing shapes drastically resulting in better performance when multiuser editing is turned on.
This PR also includes a fix for the multiuser button icons being reversed and the button taking up display space when invisible.
=> Improve client annotation editing speed

bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
Bumped chat font size from 12 to 14 and set the presentation download checkbox's selected state to false.
=> Increase chat size and set presentation download to false

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AddChatTabBox.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
- save, copy, and clear only applies to public chat
=>  - move public chat save, copy, and clean into chat options box for accessibility

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/core/model/users/User2x.as, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/SharedNotesOptions.as, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/AdditionalSharedNotesWindow.as, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/SharedNotesWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/components/SharedNotesRichTextEditor.mxml
Included some extra limitations in the notes (max length and max paste length). I'm not sure what will be the use case of this feature but if you guys need bigger notes you can set those values in client's config.xml.
Had to remove an old workaround we did for extra synchronization. I'll need more time to rethink that but I believe the notes can be used as they are to more testing.
=> 2.0 shared notes fixes

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/EllipseAnnotation.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/LineAnnotation.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/Pencil.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/PencilDrawAnnotation.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/RectangleAnnotation.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/ShapeFactory.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/TriangleAnnotation.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/CursorPositionListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/IDrawListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/PencilDrawListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/ShapeDrawListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/TextDrawListener.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/models/WhiteboardTool.as
The core of this PR is throttling of the whiteboard updates that the client sends out to one update every 50ms. In my tests this translates to 1-10 pairs of pencil coordinates being bundled together in an update. I've also included a fix for the DRAW_END so that when drawing is disabled (multiuser turned off, lost presenter, page change) the final DRAW_END is sent as expected so the pencil will smooth and the text will close. I've also increased the cursor position update to once every 50ms which should cause the annotations and the cursor to sync up.
The throttling of annotation updates caused a change in the pencil's DRAW_END properties. The canvas dimensions that used to be sent in the points have been moved to a new property "dimensions" and any left over coordinates are included in …
=> Improve client annotation edit

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/WebRTCDeskshareManager.as
---------------------------------------------------------
- ERROR: Wrong number of arguments supplied when calling method handleIsSharingScreenEvent
- EVENT TYPE: "IsSharingScreenEvent.IS_SCREENSHARING" (screenshare is sharing screen event)
- TAG: MethodInvoker
- GENERATOR: WebRTCDeskshareManager
- METHOD: handleIsSharingScreenEvent
- FILE: WebRTCDeskshareEventMap
- 1 ARGUMENT SUPPLIED: [Event type="screenshare is sharing screen event" bubbles=true cancelable=false eventPhase=2]
- STACK TRACE: ArgumentError: Error #1063: Argument count mismatch on org.bigbluebutton.modules.screenshare.managers::WebRTCDeskshareManager/handleIsSharingScreenEvent(). Expected 0, got 1.
at Function/http://adobe.com/AS3/2006/builtin::apply()
at com.asfusion.mate.core::MethodCaller/call()[/Users/nahuel/Documents/ …
=>  - fix exception

record-and-playback/core/scripts/utils/gen_webvtt
I've had a chance to see how this script behaves with actual live caption tracks now, and there's room for improvement. In particular, it often generates cues that overlap - the next one appears before the previous one disappears. The browser player position handles this really poorly, and it's nearly unreadable.
The solution is to, if two cues would overlap, merge them into a single multiline cue that displays for the full time. This is a lot easier to read.
Some extra code is added to de-overlap any remaining cues (e.g. if there's a third cue that would also overlap). This will reduce the time that the earlier cue gets shown below my preferred minimum, but not really much we can do about that if people are talking/typing quickly.
The code can easily be tweaked to set a different number …
=> Update caption track generation based on feedback

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/models/SlideViewModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as
Annotation clipping hasn't worked correctly for many versions. What I could figure out is that if the viewport width or height (whichever was the second one calculated) was a whole number the clipping would always fail, and if the second side calculated was a decimal number > n.5 or < n.5 it would sometimes fail to clip. By setting the viewports second side to always end in ".5" the clipping always seems to work. I have no idea why it works or even why it didn't work before.
=> Attempt to fix annotation clipping

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
The automatic JSON to Scala deserializer will spit out mixed number types as it sees fit and this clashes with usages that expect an exact type. This PR add a cleaner to the dimensions to the numbers into Ints.
=> Clean dimension numbers from pencil end message

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/models/SlideViewModel.as
This PR sets the viewed region back to 100% width and height when switching back to fit-to-page which is enough to get it working again.
This fixes https://github.com/bigbluebutton/bigbluebutton/issues/4339
=> Fix for switching back to fit-to-page

bigbluebutton-client/resources/prod/BigBlueButton.html, bigbluebutton-client/resources/prod/lib/bbb_blinker.js, bigbluebutton-client/src/org/bigbluebutton/core/events/FullscreenToggledEvent.as, bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCallbacks.as, bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatWindow.mxml
This pull request replaces the existing fullscreen toggle (based on Flash) with HTML5 API one (same as when you press F11 in the browser)
After this pull request is merged FireFox on Linux will not be able to trigger pop-ups (upload presentation, etc). This is already the case now if we switch to full screen mode via browser controls (F11)
I have also removed some code related to animations related to Flash based fullscreen toggle. Kept some tightly coupled code (e.x. showToolbar due to its usage on calculating positioning). Advice is welcome on the right approach - remove all / keep all / current state. @capilkey @GhaziTriki @fcecagno 
Note also the related #4330
=> Switch from flash based fullscreen to html5 api based

bigbluebutton-html5/imports/api/1.1/chat/server/methods/sendChat.js, bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx
replaces the instances of getElementById with callback refs. Also removes unused functions in the common server helpers.
=> [HTML5] - Replace Instances of getElementById

bigbluebutton-html5/imports/api/acl/Acl.js, bigbluebutton-html5/imports/utils/deepMerge.js
While merging inside, using the previously code, the deepMerge function change the state of the **this.config** object, making the following result appear:
If we merge **presenter** and **viewer**, the result would be correct, but the **this.config** is messed up, it change its internal objects to the result of the functions.
This occurs because of the `sources.shift()`, which change both references, i try the following codes to prevent this from happening, but no one work.
```
const acl = {
"viewer": {
"subscriptions": [
"users",
"cursor",
"screenshare",
"meetings",
"polls",
"chat",
"presentations",
"annotations",
"slides",
"captions",
"breakouts",
"voiceUsers"
],
"methods": [
"listenOnlyToggle",
"userLogout",
"setEmojiStatus",
"toggleSelfVoice",
"publishVote",
"sendChat"
]
}, …
```
=> [HTML5] Fix inconsistency inside the ACL, #4310

bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
This was causing some errors in applications using the BigBlueButton API. It has been changed to match the format of the other responses.
=> Remove <recording> tag around the getRecordings response.

bbb-webhooks/application.coffee, bbb-webhooks/callback_emitter.coffee, bbb-webhooks/config.coffee, bbb-webhooks/config_local.coffee.example, bbb-webhooks/hook.coffee, bbb-webhooks/id_mapping.coffee, bbb-webhooks/web_hooks.coffee
With all the changes to the messages BigBlueButton 2.0, it broke the webhooks module. I've gone through and updated it to handle the new messages properly. Since the messages don't use the `bigbluebutton:*` scope for channel names anymore, it's just listening for the messages on two separate channels (`from-akka-apps-redis-channel` for basic events, and `bigbluebutton:from-rap` for the record and playback updates).
I've also included a couple of fixes by @daronco (see #4180) that fix an issue with the webhooks module not properly cleaning up it's connections.
A BigBlueButton 1.1 server will not work with this version of the webhooks, this is strictly for 2.0 only. Anyone using 1.1 will have to use the webhooks from the `v1.1.x-release` branch (it's been updated with the redis connection …
=> Update webhooks module to support new messages in 2.0.

bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala
In BigBlueButton 1.1 the length property displayed in minutes. To keep consistent with that (to prevent applications using the API from displaying incorrect values) we should also convert the length to minutes in BigBlueButton 2.0.
=> Convert playback length to minutes when writing to XML.

bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
While Edge does support WebRTC now, the way it is supported is incompatible with the library we use. This PR makes it so the client always thinks WebRTC is not supported on Edge and can be removed once the library is updated.
See the issue here, https://github.com/bigbluebutton/bigbluebutton/issues/4384.
=> Block WebRTC on Edge

record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/core/spec/recordandplayback/deskshare_generator_spec.rb
The previous code looked for stop events and tried to find their associated start event. This obviously doesn't work if there was no stop event. But if there was a start event, we need to show the deskshare… so rework to code to try to find the matching stop to each start instead, and use the end of the meeting if no matching stop was found.
Fixes #4394
=> Handle recordings that have an unmatched DeskshareStartedEvent

bigbluebutton-html5/client/main.html
In /client/lib/bbb_webrtc_bridge_sip.js we now check for browser type via `bowser`. In order to be able to use `/client/lib/bbb_webrtc_bridge_sip.js` we need to load `bowser.js` too. Without this we cannot join the audio bridge
=> [HTML5 Client] Include bowser.js in html5 client for browser detection in webrtc

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
This log will help us track instances where the screenshare ended/did not work along with the reason for the behavior.
=> [Flash Client 2.0] Log unnatural end of screenshare

bigbluebutton-html5/imports/api/2.0/annotations/index.js, bigbluebutton-html5/imports/api/2.0/breakouts/index.js, bigbluebutton-html5/imports/api/2.0/captions/index.js, bigbluebutton-html5/imports/api/2.0/chat/index.js, bigbluebutton-html5/imports/api/2.0/cursor/index.js, bigbluebutton-html5/imports/api/2.0/meetings/index.js, bigbluebutton-html5/imports/api/2.0/polls/index.js, bigbluebutton-html5/imports/api/2.0/presentations/index.js, bigbluebutton-html5/imports/api/2.0/screenshare/index.js, bigbluebutton-html5/imports/api/2.0/slides/index.js, bigbluebutton-html5/imports/api/2.0/users/index.js, bigbluebutton-html5/imports/api/2.0/voice-users/index.js, bigbluebutton-html5/imports/api/2.0/whiteboard-multi-user/index.js
- All of the collections are indexed by `meetingId` (either separately or as a part of the compound index). That speeds up Meteor publishing the data for parallel meetings and cleaning the collections times, depending on the number of parallel meetings we have.
Cases where we need more than one index for the collection:
- Breakouts and VoiceUsers have queries using just `breakoutId` and `intId` accordingly, no `meetingId`, so we have to have a separate index for those cases.
- Chat is indexed by `toUsername`, `fromUserId`, and `toUserId`, as well as `meetingId`, which seems to cover most of the cases with publishing and adding the data.
- Annotations collection has a few different common queries, `id` and `meetingId, whiteboardId, userId` cover all the cases. (see the comments in the …
=> Added indexes for the html5 Mongo collections

bigbluebutton-html5/imports/api/2.0/slides/server/modifiers/changeCurrentSlide.js
Our current algorithm for changing the slide is simple:
1. Fetch an old slide based on the property `current: true`
2. Fetch a new slide based on the received `id`.
3. Update the new slide object with the `current: true`
4. Update the old slide object with the `current: false`.
The problem is when you have high latency or just click very fast - you can easily send 2 requests with the same slide id. And after the first request is processed we receive the second one. Following our algorithm we fetch old and new slides, but that's the same object. So we set the slide to `current: true`, and then set exactly the same object to `current: false`. And the slide just disappears from the html5 client, as if there is no presentation.
Added a check to prevent that scenario.
=> HTML5 - fix for the bug with the current Slide being unset

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
These logs will help identifying presentation conversion issues
Note, the label switch from 'invalid' to 'failed' is intentional - we want to have the same user-facing message
=> [Flash Client 2.0] Add log for invalid or failed presentation conversion

record-and-playback/presentation/playback/presentation/0.9.0/lib/writing.js, record-and-playback/presentation/playback/presentation/2.0/lib/writing.js
This happens when the slide is a plain image, for example.
Fixes #4425
=> Don't crash playback if text is not available for a slide.

bigbluebutton-html5/imports/startup/client/auth.js
Checks to see if the provided logoutURL string has http or https. If it doesn't we add and set window.location.href to the newly formatted URL string.
The bug was a result of setting window.location, which appended the logoutURL to the main application URL instead of replacing it.
=> [HTML5] - logoutRouteHandler Fix

record-and-playback/core/lib/recordandplayback/generators/events.rb
In some unusual cases, the recording start can be the last event in the
events file, or at least have the same timestamp as such.
Add some code to check the array bounds and break if needed, so we
don't check the timestamp on the (non-existant) event after the last
event.
=> Correctly handle a recording start being the last event in a recording.

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/services/user/mapUser.js
this will fix 2 bugs,
1) the user-list-item's avatar displaying the voice -user indicator icon for all user.
2) when a voice-user is talking, a ring around the avatar is rendered. If the voice-user is muted while talking, the isTalking ring indicator stays rendered to the screen; instead of disappearing.
=> [HTML5] Avatar indicator bug's

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
This PR temporarily hides the Push Notifications control from the Settings modal - until the feature is implemented.
=> [HTML5] Hide Push Notifications Setting

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
In HTML5 client the phone icon is not in `top center of screen` so the welcome message is confusing. Making it more generic allows the HTML5 client to reuse the message as is.
=> Welcome msg-drop location of phone icon so it applies to both html5 and flash clients

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx
The reference for the scrollContainer changed and as a result the value of the scrollContainer.scrollTop was always 0, which in its turn was breaking the Dropdown offset calculations.
Passed a callback with the ref of the scrollContainer instead of using `parentElement`.
=> HTML5 - Fix for an incorrectly displayed pop-up in the UserList

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/public/app.yaml
This PR makes sure the Settings modal uses the system's default locale. It also moves the `locale` setting under the `defaultSettings` in `app.yaml`.
=> [HTML5] Fix for the default locale in the Settings modal's selector (a.k.a. "Bulgarian bug").

bigbluebutton-client/resources/prod/BigBlueButton.html
We modified the login process of HTML5 client (and the parameters needed for login).
Now we simply need the sessionToken (just like in the Flash client) with a slightly different url
=> Navigate to html5 login if no Flash on system

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
This PR fixes the issue with the locale names that contain `_`: they were not able to change properly and, as a result, such locale names were not properly displayed in the Settings modal when shown as current language. Basically, we had formatting from `es-es` to `es_ES`, but didn't do it another way around when needed.
=> [HTML5 Client] Fix for locales containing `_`

bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as
In 2.0 the whiteboard was heavily modified and it stopped clicking through annotations or cursors even without a whiteboard tool selected. This PR makes sure that the whiteboard is always click through when it should be.
=> Fix whiteboard click through

record-and-playback/core/scripts/utils/gen_webvtt
If you're inserting at position 0 (and there was no previous deleted text
from that position), you can't use the timestamp from the previous character
position, since there's no previous character. Use the timestamp of the
following character instead.
=> Handle out of order inserts at the start of a caption stream.

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
When moderator close all breakout rooms, if the user didn't respond the invitation modal will close.
=> [HTML 5] Closes breakout room modal when the breakout room are closed

bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/UserAvatar.as, bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/UserGraphic.as
There were two issues with the User Avatar sizing. The first issue is that the video dock doesn't know the size of the image before loading so the aspect ratio of the latest avatar was always incorrect. I've added a call to invalidate the Video Dock container size once the image is loaded and the dimensions are known so the correct values are picked up. The second issue was that sizing for the inner object (image or webcam) was calculating the x or y values with the inner object's width or height instead of the new width or height. Using the wrong property resulted in the inner object always having it's position a little off. I've switched the algorithm to use the new value instead of the old one and it has fixed the positioning issue.
Relevant issues are #3605 and #3770.
=> Fix user avatar image sizing

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingAfterReconnectReqMsgHdlr.scala
I think the issue the code removed was trying to fix has been fixed in another commit.
The issue was https://github.com/bigbluebutton/bigbluebutton/issues/4229
The commit is 
https://github.com/bigbluebutton/bigbluebutton/commit/a6fb90e9c8f7647f35fdc1215040b37ae7cfbb02#diff-b0f61d648e5756b5fe9065652166bb9c
=> Remove auto-join voice handler on auto-reconnect

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentation/PresentationApp2x.scala
I had put in bounds checks for the presentation resize values and they work fine with fit-to-page because the width and height values should always be between the same values (100% - 25%). With fit-to-width though the height can be much smaller than 25% so I've just removed the lower bounds checks altogether.
=> Relax presentation resize bounds to accommodate fit-to-width

bigbluebutton-client/src/org/bigbluebutton/common/IBbbModuleWindow.as, bigbluebutton-client/src/org/bigbluebutton/main/views/NetworkStatsWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/broadcast/views/BroadcastWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/caption/views/CaptionWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/example/ExampleChatWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/layout/model/WindowLayout.as, bigbluebutton-client/src/org/bigbluebutton/modules/notes/views/NotesWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/AdditionalSharedNotesWindow.as, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/SharedNotesWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/VideoDock.mxml
This PR adds getName() functions to each of the MDIWindows so that we aren't stuck with just using the class name as an identifier in the Layout Module. Most of the windows still use their class names for the returned value, but this will allow us to have identifiers like "ChatWindow[0-n]" and "PresentationWindow[0-n]" inside of the layout definitions.
The ids being used for the Chat and Presentation Windows still needs work as they aren't very human friendly.
=> Changed the layout module to use custom names instead of the class name

bigbluebutton-client/resources/prod/layout.xml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/ChatEventMapDelegate.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/GroupChatBoxMapper.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/GroupChatWindowMapper.as
This PR makes the ChatWindow names more human readable (ChatWindow{n}) and reworks the opening procedure so that it is sequential.
=> Make Chat Pods layout compatible

bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/modules/present/managers/PresentManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/model/PresentOptions.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/model/PresentationWindowManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
This PR reworks how the PresentationWindows are opened and tracked and also adds consistent identification to them so that they are compatible with layouts.
=> Add proper window identification to PresentationWindows

bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/ChatEventMap.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/ChatEventMapDelegate.as
This PR implements closing of the ChatWindows as expected when the ChatModule is stopped (logged out, disconnected, etc).
=> [2.1] Close all ChatWindows when module is stopped

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PermissionCheck.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/chat/ClearPublicChatHistoryPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/BroadcastLayoutMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AddUserToPresenterGroupCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/AssignPresenterReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserEmojiCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUsersInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LogoutAndEndMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RemoveUserFromPresenterGroupCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SetRecordingStatusCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/MuteMeetingCmdMsgHdlr.scala
This PR implements some of the rights management checks. Covered are Users, Broadcast Layout, and Clear Chat. I took a different spin on what was already there because I didn't want to write all of the code that would be required to follow the original method.
Original way: https://github.com/bigbluebutton/bigbluebutton/blob/a5ddf0b2038e5fa7935755b2aae59ce88884600d/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala
My way: https://github.com/capilkey/bigbluebutton/blob/ebcf7dc4cca20a999dc2603addf796c0ca96a63b/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/chat/ClearPublicChatHistoryPubMsgHdlr.scala
=> Add some of the rights management checks

bigbluebutton-html5/imports/startup/client/auth.js
Got this error in the console:
Instead showing me a logout button with the error it was just a black screen.
Checked, it turned out that we forgot to change one of the imports in #4524 
This fixes it.
=> [HTML5] - Fixed a logClient function call

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/AbstractPresentationRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/CreatePresentationPodRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/RemovePresentationPodRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/ResizeAndMoveSlideRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/SetPresenterInPodRecordEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
RecordEvent Changes
* Updated cursor event to have presentation name and page (matches other whiteboard events)
* Updated Presentation events to all have podId and presentationName
* Added three new recorded events (CreatePresentationPodEvent, RemovePresentationPodEvent, SetPresenterInPodEvent)
* Exchanged SendPublicMessageEvtMsg for GroupChatMessageBroadcastEvtMsg and filtered on chatId == GroupChatApp.MAIN_PUBLIC_CHAT
* Note: end result is no change for recording processing for chat messages
=> Modify presentation, chat, and cursor record events to match 2.1 specs

bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/LayoutsCombo.mxml
We kept the layout name retrieval from #4635 and removed the translation in locales.
=> Fall back to the layout name if a translation could not be found

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala
The problem was that if the Flash client reconnects during a meeting but the audio connection remains intact, akka-apps would still tell all clients that the user has left audio.
Removing this logic fixes the issue.
=> Do not send UserLeftVoice on UserLeave - fix for audio state issue on reconnect

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala, bigbluebutton-client/src/org/bigbluebutton/core/UsersUtil.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatOptionsTab.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
This PR fixes three minor bugs in 2.1.
* stops viewers from being able to create new public chat pods
* fixes a race condition in the LayoutManager on client load
* stops viewer clients from trying to initialize the lock settings on client load
=> Fix three bugs in 2.1

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
This PR fixes the issue with default language in Settings modal. It was possible to change locales successfully, but the dropdown always had Bulgarian language as the current value.
Change in behaviour: the dropdown is not displayed if the list of available locales is `undefined` (rather than displaying an empty broken dropdown).
=> Bulgarian Bug Vol. 3

bigbluebutton-client/src/org/bigbluebutton/main/views/LanguageSelector.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/ScreenshareService.as, bigbluebutton-client/src/org/bigbluebutton/util/i18n/ResourceUtil.as
The ResourceUtil initialization was broken and didn't complete fully when the default locale from the browser was the same as the master locale (en_US). I added a skip over the resource loading because it already exists and faked that it had been loaded. The selector now switches to "English" on load like it used to and the first line shows "Default Locale" like it used to.
I also included two one liners that avoid null exceptions that I hit doing other things.
=> Fix default locale selector

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
Yesterday I added a similar change to the master branch (2.1). The results were good so this a 2.0 version to block excess messages from being produced.
=> (2.0 only) block zoom slider change processing when not presenter

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Add configuration to control what client (HTML5 vs Flash) the users join a meeting with:
- *optional:  on join parameter*
`joinViaHtml5=true` (per client join)
Explanation: if you pass `joinViaHtml5=true` your user will join in the HTML5 client
- *optional  bigbluebutton.properties parameters:*
```
attendeesJoinViaHTML5Client=false
moderatorsJoinViaHTML5Client=false
```
Explanation: if you set `attendeesJoinViaHTML5Client=true` all attendees will join in the HTML5 client
if you set `moderatorsJoinViaHTML5Client=true` all moderators will join in the HTML5 client
=> Provide option to join via html5 over flash client

bigbluebutton-client/src/org/bigbluebutton/main/events/ShortcutEvent.as, bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/ToolbarPopupButton.mxml
This PR blocks the webcam popup from opening when the user is locked. It's a fix for issue #4329.
=> Block webcam popup opening when locked

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx
#4734 introduced a workaround for the Firefox 57 and 58 for Android, to support the text shape functionality.
But I forgot to add Android detection there, just checked if it was Firefox.
As a result textarea is not focused on desktops in FF 57 and 58 by default, and it's waiting for the second "touchstart" event to move focus there. Which you can't do, if you are using the mouse only.
This fixes it.
And disabled a default spell check for the text shape.
=> Fixed Text Shape for the desktop FF 57 and 58, disabled spellCheck

bigbluebutton-html5/imports/ui/services/settings/index.js
Currently html5 login completely fails in Edge, all users can see is a dark screen.
`navigator.languages` is undefined there, it tries to extract [0] from `undefined` and fails.
This fixes it.
=> Fixed a problem with the default locale selection in Edge

bigbluebutton-html5/imports/api/polls/server/eventHandlers.js, bigbluebutton-html5/imports/api/polls/server/handlers/userVoted.js, bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js, bigbluebutton-html5/imports/api/polls/server/modifiers/updateVotes.js
Fixes #4778 
* renamed `UserRespondedToPollEvtMsg` to `PollUpdatedEvtMsg`
* adjusted the code not to expect presenterId to be passed
This was done to adapt the html5 client to changes made in #4776
=> Poll updated event - drop requesterId/presenterId and rename event

bigbluebutton-html5/imports/api/voice-users/server/handlers/joinVoiceUser.js, bigbluebutton-html5/imports/api/voice-users/server/handlers/leftVoiceUser.js, bigbluebutton-html5/imports/api/voice-users/server/methods.js, bigbluebutton-html5/imports/api/voice-users/server/methods/ejectUserFromVoice.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx, bigbluebutton-html5/private/config/public/acl.yaml, bigbluebutton-html5/private/config/server/redis.yaml
Fixes #4457 
Adjustments coming:
* Make call-in/dial-in users visually different than web users #4786 (design required, aiming for 2.1)
* Voice users are not sent over to html5 server on meteor start #4784 (aiming for 2.0)
* Locking the microphone control in a meeting does not have effect on dial-in users #4787 (changes must be done on BBB)
=> Handle dial-in users in HTML5

bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/events/ExportEvent.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileExportWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/IWhiteboardOverlay.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/IWhiteboardToolbar.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardTextToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml
The PresentationWindow and SlideView in the PresentationModule imported the WhiteboardCanvas directly which resulted in the PresentationModule being bigger than it needs to be and removing the ability to build the WhiteboardModule on its own. This PR adds two interfaces so all the PresentationModule needs to include is those small interfaces instead of most of the WhiteboardModule.
=> Decouple whiteboard from presentation

bigbluebutton-client/resources/prod/lib/bigbluebutton.js, bigbluebutton-client/src/org/bigbluebutton/util/i18n/ResourceUtil.as
This PR fixes the locale initialization when the browser suggests a locale we don't have. Previously this would result in the client not starting up and it would sit on a white screen.
I also tacked on an increase to the timeout before focusing the Flash content because sometimes it can take longer to become active.
=> Fix locale initialization

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/LayoutsCombo.mxml
I removed a 6 pixel padding on the top of the main toolbar that made it unbalanced and 10 pixels from the bottom control bar because it didn't need all that space. I also increased the number of layouts visible in the combobox from 10 to 15.
=> Fixes for some spacing issues in the client

bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/component.jsx
Prior to this change the echo test in Safari on iOS 11 would result in blank screen - the UI would not render at all due to not specifying how/where Safari should render it. Adding specification for Safari resolved the issue
=> Add permissionLayout location for Safari

bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
This allows the previously defined styles to render as expected.
fixes issue #4969
=> Fix broken view styles displayed on error, on meetingEnd and for removed users

bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
Fixes issue #4972
Now when you hold down the close button, the background no longer disappears.
=> Edit css to prevent disappearing close btn background

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/video-dock/component.jsx, bigbluebutton-html5/imports/ui/components/video-dock/video-menu/component.jsx
Implement changes requested on #4955 after it was merged.
Display either 'start' or 'stop' screenshare button (#4926), only if screensharing is enabled on config file (#4927).
=> Adjusts on screenshare button and requested changes

bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
Now it properly covers the other actions bar buttons. Fixes #4954
=> Aligned the dropdown's close button on small screens

bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as, bigbluebutton-html5/imports/api/video/server/handlers/userSharedHtml5Webcam.js, bigbluebutton-html5/imports/api/video/server/handlers/userUnsharedHtml5Webcam.js
Fix the regex that checks the Flash stream id by adding the option "-recorded" to the pattern, making sure recorded streams are matched too.
=> Fix flash stream regex

bigbluebutton-html5/imports/api/annotations/server/modifiers/addAnnotation.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/pencil/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx
The client was breaking because of the race condition between the last pencil message and the "clear annotation" message.
Annotations were cleared, but then the last pencil message was passed through, and the result was an empty `points` array and no `commands` property in the annotation object.
One way to trigger that bug is to start drawing, then move and release your mouse over one of the wb-toolbar buttons.
Changed 3 things here:
- added a whiteboardId to the pensil_base object. This is not going to affect anything, except maybe indexing.
- prevented onMouseUp triggering if there was no onMouseDown (in case if you start drawing an annotation and then release your mouse over one of the whiteboard toolbar's buttons).
- added a check to the PencilDrawComponent, since the above case can …
=> Fixed Pencil rendering breaking the html5 client

bigbluebutton-html5/imports/startup/client/base.jsx
When a HTML5 client user gets kicked from the conference - or the conference is ended, the user ends up in the echo test and is able to hear himself. Fix #4999
=> Exit from audio when in meeting ended to prevent echo test

bigbluebutton-html5/imports/startup/server/logger.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Added npm package `winston-daily-rotate-file`, Addresses #2939 
To test - change 
`datePattern: '.yyyy-dd-MM',`
to
`datePattern: '.yyyy-dd-MM-mm',`
This way the logs will rotate every minute (easier to test)
Also consider increasing the settings-production.json loglevel to 'verbose'
Start the HTML5 client in production mode via 
```
rm -r node_modules
meteor reset
meteor npm install
NODE_ENV=production npm start
```
Use the client for a few minutes and then look at the log files for production:
`ls -l ll /var/log/bigbluebutton/html5/` and make sure that there are several files, containing a minute-length of logs
=> Added daily log rotation in production env

bigbluebutton-config/bin/bbb-record
Tracked the error down to bbb-record line 718 ff. which is called by bbb-conf --debug and misses support for "https". Added support for "https" and incorrect flagging vanishes.
=> Issue #3985: bbb-conf --debug incorrectly flags

bigbluebutton-html5/imports/ui/components/video-dock/component.jsx, labs/bbb-webrtc-sfu/lib/video/video.js
This PR adds some functionalities to the video components:
* A timeout that will dis-engage the video sharing and the button if the sharing fails.
* A rewritten version of the shouldComponentUpdate method that actually does the correct thing at all times (we no longer rely on users and nextUsers to be ordered and contain the same number of users)
* Better handling of reconnect when user is offline
* Better reconnect of video shared videos that stop flowing for a few moments
=> Video share button timeout and re-written shouldComponentUpdate method

bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json
Currently all the exceptions are caught in the redis.js file, but nothing is displayed neither in development nor in production modes, no logs at all.
- Enabled the logging for the development and production
- Displayed a stack trace for all the errors if applicable
=> Fixed the logging of the Meteor server-side methods

bigbluebutton-client/resources/prod/BigBlueButton.html
Redirect the user straight to the html5 client (if it is available on the server)
=> Redirect Android, iOS users to html5 except on Puffin browser

bigbluebutton-config/bin/bbb-conf
Reverts bigbluebutton/bigbluebutton#5110
Instead of bbb-conf, we now have bbb-html5.service requiring mongod to be running prior to starting. Fixed through packages
=> Revert "Give mongod a moment to startup before bbb-html5"

clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/commands/RequestWelcomeMessageCommand.as, clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/commands/RequestWelcomeMessageSignal.as
I forgot to include the RequestWelcomeMessageSignal and RequestWelcomeMessageCommand classes that I created.
=> Include missing classes in AIR client

bigbluebutton-html5/imports/api/meetings/server/handlers/meetingDestruction.js, bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
It turned out that "meetings" collections wasn't cleared on meeting destruction, since there was an error that prevented the code from being executed.
Also, there was another exception thrown when we tried to change the role of the previous presenter, but there was no presenters before.
Both are fixed here.
=> Fixed exceptions thrown during meeting destruction and presenter assignment 

bigbluebutton-html5/imports/api/voice-users/server/eventHandlers.js, bigbluebutton-html5/imports/api/voice-users/server/handlers/getVoiceUsers.js, bigbluebutton-html5/imports/api/voice-users/server/modifiers/updateVoiceUser.js
This PR added handling of `GetVoiceUsersMeetingRespMsg` messages to make sure the voice states are properly updated after users are reconnected. It fixes #4686.
=> [HTML5 Client] Adjustments in handling of reconnected voice users

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-extension.js
While investigating the FPS/resolution constraints, I also found why the chrome extension prompt wasn't being shown in the HTML5 client (#5073). So I fixed it, could you take a look @jfsiebel?
How to test the FPS modifications: share your screen, either in Flash or HTML5, Chrome or Firefox, and see if the FPS seems noticeably reduced (should be something between 5-10 FPS).
How to test the Chrome extension fix: configure a proper extension with its store link and key, uninstall it (if installed) and try sharing your screen in the HTML5 client on Chrome. A notification should pop out recommending the installation of the extension, alongside with the configured store link.
=> Limited screensharing FPS to 5-10, resolution to screen size and fixed chrome extension prompt

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/pencil/component.jsx
Even though we couldn't reproduce #5137 - I added an extra check which is supposed to prevent the potential bug with the last Pencil message display.
Most likely it was an edge case where some users had a slow connection and a presenter turned off the multi-user mode and cleared the whiteboard right away whilst some users were still catching up with the updates and were still allowed to send messages.
=> Added an extra check for the Pencil's DRAW_END message

bigbluebutton-html5/imports/startup/server/logger.js, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json
This PR adds console logging in production + removes daily rotation logs and logging to file in development.
The console logs were tested in the package mode and it was confirmed that `systemctl` picks logging from HTML5 client.
=> [HTML5 Client] Production Logging to Console

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
This should fix a condition where ICE candidates weren't being correctly processed by the SFU component, which made a presenter unable to start screensharing sometimes or viewers unable to see the shared stream (#4932).
Also limited Firefox WebRTC screenshare options to `screen` only. This is because Firefox can randomly crash while trying to share other applications or windows; in some cases it can even freeze the computer. That doesn't happen with `screen` only.
=> Fixing WebRTC screensharing ICE processing (#4932) and limiting Firefox screensharing choices

bigbluebutton-client/resources/prod/BigBlueButton.html
Reverting #5181 as it causes a major issue - if the html5 client (server side) is not running, the Flash client remains hidden (cannot be used).
When we revisit 5181 we should make sure we cover this use case
=> Revert pr #5181

bigbluebutton-html5/imports/ui/components/button/component.jsx, bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
Fixes issue #4920, where tool tips are staying visible after a button is tapped on mobile.
=> Fix tooltip staying visible after tapping from mobile devices

labs/bbb-webrtc-sfu/lib/video/video.js
This forces H264 in HTML5 video through SDP mangling.
It should avoid high CPU usage in Kurento in cases where people enter with Chrome/Firefox (opting for VP8) and with Safari/iOS in the same meeting (opting for H264), which makes Kurento transcode video between parties.
=> Forcing H264 in HTML5 video

bigbluebutton-client/resources/prod/BigBlueButton.html
Fix for #5165.
Handles the case of 404 response from `html5client/check` as well (Flash client can load successfully when HTML5 client is inactive).
=> [HTML5 Client] Hide client type option when already detected. Vol. 2.

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
This PR implements a `ejectUserFromVoice` after the user is "removed" instead of just updating our local voice collection when a user left the meeting,
This PR also implement and improve the current event handlers for iceConnection state changes.
This is a attempt to fix #5183.
=> Sends a ejectUserFromVoice after removing a user

clients/flash/air-client/src/Main-app.xml
AIR 28 has a bug where you can't use URL app invocation. This PR bumps the AIR version to 29 so the app can launch again.
=> Bump AIR version from 28 to 29

clients/flash/air-client/src/Default.css, clients/flash/air-client/src/css/hdpi.css, clients/flash/air-client/src/css/ldpi.css, clients/flash/air-client/src/css/mdpi.css, clients/flash/air-client/src/css/xhdpi.css, clients/flash/air-client/src/css/xxhdpi.css, clients/flash/air-client/src/css/xxxhdpi.css, clients/flash/air-client/src/org/bigbluebutton/air/chat/views/skins/SendButtonSkin.mxml, clients/flash/air-client/src/org/bigbluebutton/air/main/views/skins/TopButtonSkin.mxml
The top navigation buttons and chat's send button only had a label and this meant that the area that would register a click was very small. I've added a background to both so that they will register clicks as expected.
=> [AIR] Add background for TopButtons and chat's SendButton

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-extension.js
I further specified Chrome's constraints with google-specific optimizations. The quality is fairly better now. There's an increase on used bandwidth, but that's the tradeoff.
Firefox seems fairly good with no changes, but I've seen some cases where it throttles the stream and don't raises the quality back up. Firefox optimizations will probably come in another PR.
=> Improved Chrome WebRTC screenshare constraints

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
We can't force 16:9. Some browsers don't work well with this, and mobiles get an `overconstrained` error.
Fixes #5358
=> Raised max resolution for webcam constraints

bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/service.js, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/polling/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-menu/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-menu/service.js
This PR is a follow up on #5327.
- Remove the width transition from the presentation since it looks janky while swapping.
- Fix presenter controls not showing in firefox. Fix #5354 
- Fix webcams not resizing properly in some odd cases. Fix #5355 
- Fix wrong calculations while having a focused webcam.
=> Follow up on the webcam swap/design

bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
Show lock image if webcamsOnlyForModerator is enabled, however it is not possible to unlock this feature. Improve #5067
=> Show lock image if webcamsOnlyForModerator is enabled

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
Currently when you click in retry there is no indication that something is happening.
Now when you click in retry the user is informed that something is happening.
=> Add friendly iteration on audio settings retry

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
The arrows for when a webcam is loading now correctly spins counter-clockwise.
=> Loading screen rotation spins counter-clockwise

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.scss, bigbluebutton-html5/imports/ui/components/dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/dropdown/list/title/component.jsx, bigbluebutton-html5/imports/ui/components/dropdown/trigger/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/locales/en.json
This PR fixes how the mobile screen reader interacts with the html5 client.
* mobile SR no longer has access to elements behind the current view.
* adds makeup-screenreader-trap package.
* adds aria-expanded to dropdown menus.
* SR alerts the audio modal connecting text.
* other minor bug fixes.
=> Fix mobile screen reader functionality

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/video-dock/component.jsx, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json
We now have a BBB screensharing extension for Google Chrome - it whitelists *.bigbluebutton.org domains only and is built from the files in https://github.com/bigbluebutton/screenshare-chrome-extension
Prefer custom link/key over the default but if no custom ones, fallback to default ones.
=> Set default KEY and LINK for Chrome screenshare extension 

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/WebRTCViewerWindowManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/WebRTCDeskshareService.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/AnimatedDots.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
This PR updates the look and feel of the WebRTCDesktopViewWindow to match what was done in the Java view window. I've also added in connecting dots to the WebRTC view and publish windows to give the user an idea that something is happening while the client waits for the stream to start.
=> Update WebRTCDesktopViewWindow and add connecting dots for view and publish windows

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
- when the pointer tool is selected hide thickness and color button, as it was with the hand tool.
=> Hide thickness and color buttons in whiteboard toolbar

clients/flash/air-client/src/org/bigbluebutton/air/poll/services/PollMessageReceiver.as
This PR handles an additional poll stop scenario that occurs when the presenter publishes the poll instead of just closing it.
=> [AIR] Stop the active poll when the result is shown

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, labs/bbb-webrtc-sfu/lib/connection-manager/WebsocketConnectionManager.js, labs/bbb-webrtc-sfu/package-lock.json, labs/bbb-webrtc-sfu/package.json
This fixes an issue where idle websockets are closed after a period of time under certain networks.
There's no logic involved in this ping/pong yet, it's just to keep the socket alive.
I also updated SFUs package-lock.
=> Added websocket ping pong to SFU clients

labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/MediaController.js
There was a routine that marks a media session as started missing in the mcs-core lib, so recordings weren't being correctly stopped.
=> Fixed recording stop in SFU

bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
Different playbacks of the same recording should now be responded as multiple <format> inside the same <playback> tag
=> Grouping playbacks inside the same recording

bigbluebutton-client/branding/default/style/css/org/bigbluebutton/skins/ToolTipSkin.as, bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/main/views/AudioSelectionWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/FlashMicSettings.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/phone/events/AudioSelectionWindowEvent.as, bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/WebRTCCallManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/phone/views/components/ToolbarButton.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/Pencil.as
Sometimes the user will close the audio selection window without reading it and then not know how to join the audio. This PR creates a tooltip with the text "Click here to join the audio" and points to the join audio button if the audio modals are closed without joining. The call out will also be shown if meeting has "autoJoin" turned off in the config.xml.
Fixes issue #5441.
=> Show a call out when a user doesn't join audio

labs/bbb-webrtc-sfu/config/default.example.yml, video-broadcast/src/main/webapp/WEB-INF/red5-web.xml
From now on webrtc screenshare [via Kurento] will only be recorded by Kurento and red5's video-broadcast app will be used only for streaming live to potential Flash client meeting viewers
=> Enable kurento screenshare recording, disable red5 video-broadcast ss recording

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, labs/bbb-webrtc-sfu/lib/bbb/pubsub/bbb-gw.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
This improves the resolution handling for screensharing by reducing the max resolution to a factor of 1080p while preserving the original track's aspect ratio. I also fixed a bug with the `rtmpBroadcast` message sending in the SFU component that was messing with the width/height being sent to video-broadcast.
A careful round of testing on this would be welcome.
=> Preserving WebRTC screenshare aspect ratio in video-broadcast

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ViewerWindowManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/WebRTCViewerWindowManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
The wrong event was being fired by the WebRTCDesktopViewWindow which resulted in it not being closed when the Screenshare Module was shutdown. This PR changes the event from the WindowCloseEvent to the WebRTCWindowCloseEvent.
=> Fix WebRTCDesktopViewWindow not being closed properly

record-and-playback/screenshare/scripts/screenshare.yml
I forgot to include the 'K' multiplier on the bitrate values, so they
were all 1000 times too low.
=> RnP: Fix bitrate in screenshare.yml

bigbluebutton-client/src/org/bigbluebutton/modules/phone/views/components/ToolbarButton.mxml
Instead of hiding the callout when audio is successfully joined, this PR hides the callout when the button is clicked.
=> Hide audio callout when button is clicked

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserBroadcastCamStopMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, bbb-video/src/main/java/org/bigbluebutton/app/video/VideoApplication.java, bbb-video/src/main/java/org/bigbluebutton/red5/pubsub/MessagePublisher.java, bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
Currently, the flash client is the one sending the start/stop webcam stream messages to the server. When the connections to red5 from the client is auto-reconnecting, these messages might not reach the server resulting in multiple or missing webcam displays.
Have bbb-video in red5 instead send the start/stop stream messages. Red5 will detect if the connection with the stream disconnected so it will send the stop stream message.
=> Cleanup video stream on reconnect

bbb-screenshare/app/src/main/webapp/WEB-INF/classes/logback-screenshare.xml
Change red5 screenshare log format to be the same as other red5 logs.
=>  - change red5 screenshare log format

bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
This PR fixes #5484. 
Before we were using the Windows permission images everywhere, but Mac computers. The problem was that Linux follows the Mac format not the Windows format. This PR makes the Mac images the default.
=> Use Mac mic permission image everywhere, but Windows

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- Currently, when starts a screen share, the connecting icon is behind the video, so when you share a small screen, the icon appears in the background. In my PR the icon is removed from the screen when video is loaded
Closes issue #5514.
My PR: 
V2:
=> Hide connecting icon when screeshare is loaded.

bigbluebutton-html5/imports/startup/client/auth.js
Test via http://mconf.github.io/api-mate/ where you set **custom parameters**: `joinViaHtml5=true` 
and **meta_ \*** : `meeting-name=blah`
before this PR `meeting-name=blah` results in broken client - JSON not able to parse 'blah'
after this PR the client should appear fine
=> Support metadata with improper format

record-and-playback/core/scripts/archive/archive.rb, record-and-playback/core/scripts/sanity/sanity.rb
There's some cases where you can get 0-duration recordings due to
recording event placement (e.g. a single recording event is the last
event in the events.xml). Detect these cases, and treat them like
no recording marks in the archive script (it will stop the recording
from being automatically processed).
I've also adjusted the sanity script to detect these cases and error
out. The recording processing scripts cannot handle 0-length recordings,
you have to manually edit the events. I've added a message to the
sanity log about this.
=> RaP: Improve check for record events in archive, sanity scripts

record-and-playback/core/lib/recordandplayback/generators/presentation.rb, record-and-playback/presentation/scripts/process/presentation.rb
This improves the quality of portrait documents, before they were
1200px when landscape documents got 1600px.
Switching to scaling to a square means that we can use the "-scale-to"
option on pdftocaio, which means that it generates images directly
at the desired size. This can save quite a bit of time (and memory)
if a document was uploaded with extremely large page size.
=> RaP: Scale to a square when generating slide images for pres. format

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/modules/present/model/PresentOptions.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
There's been some sort of regression in Firefox 60+ related to file uploading, see issue #5564. This PR replaces the file select with a warning to use a different browser. Once the problem is fixed or a workaround is discovered we can revert these changes.
=> Temporarily disable uploading on Win Firefox 60+

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
The issue (#5564) doesn't happen on 32-bit Windows so this PR adds a check for 64-bit Windows.
=> Add a 64-bit check to the Firefox 60+ upload block

record-and-playback/core/scripts/sanity/sanity.rb
Due to improvements in the recording scripts, most of the stuff the sanity
script was checking for is no longer needed (missing/corrupt video files
are handled by the processing scripts). The version of this script in
master has been cleaned up so that the only things it does are:
- Check that the events.xml exists and is properly formatted xml
- Rebuild flv files from red5 .flv.ser/.flv.info files
The script from master is compatible with the 2.0 code, so just use it
as-is.
This fixes a problem where following the recent red5 upgrade in 2.0 branch,
an flv file is never written for webcam streams where no frames were
received, despite there being recording events.
=> RaP: Merge the sanity script from master branch

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/startup/client/auth.js, bigbluebutton-html5/imports/ui/components/nav-bar/service.js, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
in PRs #3983 and #4091 we customized bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy so the apis could be used with the login method of the html5 client of the day. Now that we log in via the same method as the Flash client [but with different redirectUrl] we revert back the customizations.
Also needed to add `{ credentials: 'same-origin' }` to that the client uses the correct JSESSIONID when calling `fetch`. Tnx for the tip @oswaldoacauan @capilkey
=> Revert special api changes made for html5 client

bigbluebutton-html5/imports/ui/components/dropdown/list/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/styles.scss
This fixes #5394 
* up / down arrow -> cycle through users in userlist (if menu is closed)
* up / down arrow  -> cycle through open menu options (if menu is open)
* Removes box shadow on the userlist item with an open menu
=> Improve userlist dropdown menu key-board functionality

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/private/locales/en.json
When a user tries to share screen on Safari, display a toast saying it's currently not supported by the browser.
=> Display a toast for screensharing not supported by Safari

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AdvancedList.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
The chat auto-scroll behaviour at new messages is updated to the following :
- If I am sender of the last message the chat list will auto-scroll.
- If I the scroll bar is at the end will auto-scroll if a new message is received.
- In all other cases the blue ribbon will display, the will disappear if clicked or the list is scrolled till the end.
=> Added new unread message ribbon to chat and update auto-scroll behaviour

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/container.jsx
- Disable UserList and Chat components from being resizable in mobile views.
- Prevent NavBar from being hidden on mobile in some cases. Fix #5568 
- Add the userListCompact state in App and pass it down correctly.
- Change the userListCompact state based on the UserList width.
- Remove the action of closing the UserList when the user resize it.
This PR will impact on #5511
=> Disable resizable userlist and chat in mobile views

akka-bbb-apps/scala/BreakoutRoom.sc, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutHdlrHelpers.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala, bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutJoinURL.js, bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/ui/components/nav-bar/service.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
As consequence of #5583 we are required to follow a server-provided link (with a set JSESSIONID) in order to call /enter and obtain information from the server.
This PR modifies `akka-apps` component so the breakout url for html5 users is using `redirect=true` and `joinViaHtml5=true`. This url is propagated to HTML5 server side component where it makes its way into Mongo. The url is then utilized on the appropriate clients.
Dropped dependency on `xml2js` as we no longer need to pull xml and construct url ourselves.
=> Breakout rooms - join by following server-provided url to html5 client

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json
Previously, if the browsers locale was set to "ja", the client would default to "en" because it would not find any "ja.json".
Now, it will check for a viable fallback option.
Example : 
also adjusts the width of the userlist re-size handle to match that of the chat.
=> Improve html5 locale fallback selection

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/BigBlueButton.mxml, bigbluebutton-client/src/org/bigbluebutton/common/logging/DisplayWarningAction.as, bigbluebutton-client/src/org/bigbluebutton/common/logging/GlobalExceptionHandler.as, bigbluebutton-client/src/org/bigbluebutton/common/logging/GlobalExceptionHandlerAction.as, bigbluebutton-client/src/org/bigbluebutton/common/logging/LogHandlerAction.as, bigbluebutton-client/src/org/bigbluebutton/common/logging/LogUtil.as, bigbluebutton-client/src/org/bigbluebutton/core/managers/ConfigManager2.as, bigbluebutton-client/src/org/bigbluebutton/main/events/ClientStatusEvent.as, bigbluebutton-client/src/org/bigbluebutton/main/model/options/LoggingOptions.as, bigbluebutton-client/src/org/bigbluebutton/main/views/ClientStatusItemRenderer.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/WarningButton.mxml
Catch any unhandled and copy it to clipboard for better bug reporting. Those type of errors will be logged as `fatal`, they are also marked with unique ID, hashed from their stack-trace.
=> Globally catch any unhandled exception

bigbluebutton-html5/imports/ui/components/chat/notification/push-notification/component.jsx
Changing the interval between chat push notifications (from 5 to 2 sec) and how long the notifications are visible (from 2 to 4 sec).
=> Chat push notifications timing

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
=>  Prevent long chat message to make the chat area of the client to be resized

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/AnimatedProgressBar.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml
This PR adds a 15s loading bar to replace the animated dots. Addresses #5706.
=> Add a loading bar for WebRTC screenshare start up in the Flash client

record-and-playback/core/lib/recordandplayback/generators/audio_processor.rb
The archive_dir can be the raw recording directory in some recording
formats - including, hopefully, presentation at some point (to avoid the
extra copy)
=> RaP: Store rendered audio temp file in target directory, not archive_dir

bigbluebutton-client/src/org/bigbluebutton/modules/chat/model/ChatMessage.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AdvancedList.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
This PR has two chat improvements. The first change is and attempt to improve the performance of the chat message rendering by avoiding multiple calls to the same expensive functions. The second change is to fix a bug where if you select a chat message the list will attempt to scroll to show the selected message every time a new message comes in.
=> Two chat improvements

record-and-playback/core/lib/recordandplayback/edl/video.rb
The checks for 0 numerator or denominator were failing due to
type mismatch
=> RaP: Convert aspect ratio numbers to int before checking value

record-and-playback/presentation/scripts/publish/presentation.rb
In some cases, we get DRAW_END events for pencil shapes from the
html5 client that have no dataPoints. The only thing we can really
do here is detect the issue and ignore the shape.
In some cases, this may result in the shape's intermediate drawing
updates being shown, but it'll disappear when the end event happens.
=> RaP: Don't error on pencil drawings with 0 dataPoints

bigbluebutton-config/cron.daily/bigbluebutton
- Fully clean up temporary stream files for all red5 webapps.
- Also clean up temporary stream files for kurento recordings.
- Add a new, separate variable for controlling maximum time to keep log files.
- Clean up old (rotated) log files for red5, tomcat, recording which were accumulating.
=> Improve bigbluebutton cleanup cron job

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Full audio exit was broken when SFU listen only was enabled because I was mishandling the way I fetched the SFU bridge.
=> Fixed full audio exit when SFU listen only is enabled

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Fixes #5519.
Rationale: the `disconnected` ICE connection state is not fatal and may transition either to a valid state (`connected` once again, or `checking` -> `connected`) or a invalid/fatal one (`failed` -> `closed` or `closed`). So I changed the `disconnected` handling in the termination callback to `closed` and let it transition naturally to a final state.
I also added an `exitAudio` call on the manager's error callback. This is because we didn't close the audio/SIP session when a fatal error happened and that'd possibly leave a FreeSWITCH connection dangling or cause further inconsistency problems.
=> Fixed audio state bug (#5519)

bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/cursor/presentation-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/pencil-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
This PR is a follow-up on #5594 and implements/fix the following:
- Prevent disconnected users from drawing locally
- Fix most linter errors introduced in #5594
- Fix the undo action not interacting correctly with text shapes (#5618)
- Fix scrolling while drawing in Apple devices, needs more testing (#5672)
- Fix local shapes not being removed after the user lost the drawing permission (#5677)
- Fix some reconnect interactions with the local shapes (#5671)
- Fix not being able to draw in some areas of the presentation (#5768 and #5778)
- Fix cursor not showing while on top of some areas of the presentation (#5768 and #5778)
=> Whiteboard fixes and improvements

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/services/unread-messages/index.js
- Don't notify old messages when reload. Closes #5796.
- Fix chat height in desktop screen.
=> Tiny fixes in chat and notifications

labs/bbb-webrtc-sfu/config/default.example.yml, labs/bbb-webrtc-sfu/lib/h264-sdp.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
Rationale: The problem resides in our low-bandwidth approach coupled with the profile Chrome uses on Windows with hardware acceleration on. The profile is a bit higher than normal, which triggers an aggressive compression in the browser to fit the stream into the available bandwidth, resulting in a garbled joke.  So I devised a workaround by including an option to prefer a specific H264 profile for screenshare procedures, which is the baseline profile that Firefox uses by default and that Chrome uses with hardware acceleration off. If the configured profile is non-existant in the SDP, the negotiation is unchanged and things should work as before.
=> Improving WebRTC screenshare quality on chrome + windows

bigbluebutton-html5/imports/api/group-chat-msg/index.js, bigbluebutton-html5/imports/api/group-chat-msg/server/eventHandlers.js, bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/groupChatMsgBroadcast.js, bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/groupChatsMsgs.js, bigbluebutton-html5/imports/api/group-chat-msg/server/index.js, bigbluebutton-html5/imports/api/group-chat-msg/server/methods.js, bigbluebutton-html5/imports/api/group-chat-msg/server/methods/sendGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/removeGroupChat.js, bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js, bigbluebutton-html5/imports/api/group-chat/index.js, bigbluebutton-html5/imports/api/group-chat/server/eventHandlers.js, bigbluebutton-html5/imports/api/group-chat/server/handlers/groupChatCreated.js, bigbluebutton-html5/imports/api/group-chat/server/handlers/groupChatDestroyed.js, bigbluebutton-html5/imports/api/group-chat/server/handlers/groupChats.js, bigbluebutton-html5/imports/api/group-chat/server/index.js, bigbluebutton-html5/imports/api/group-chat/server/methods.js, bigbluebutton-html5/imports/api/group-chat/server/methods/createGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/methods/destroyGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/addGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/clearGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/removeGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/publishers.js, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json, bigbluebutton-html5/server/main.js
This PR implements the basic structure for GroupChats for 2.1, some messages regarding access and user permissions are not being handled yet since we do not support them in any of the clients.
There is a know bug where group-chats are not created if a meeting is already running before we start HTML5 server, this is because we are missing a `Sync` message #5224 
The publishers and methods are just boilerplates to be implemented together with #4988 
Closes #4987
=> Implement basic GroupChat messages

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/utils/fetchStunTurnServers.js, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json, labs/bbb-webrtc-sfu/lib/audio/AudioManager.js
This PR includes a bunch of minor improvements to the HTML5 client listed below. A separate PR will be opened that adds STUN/TURN config and window sharing to the Flash client.
- Added support to SFU client-side components (screenshare, video and listen only) for fetching the configured STUN/TURN servers in the BBB API. If no ICE servers are configured, they fall back to the default, preconfigured pool of public STUN servers.
- Correctly propagating the SFU URL configuration to the screenshare script
- Made the screensharing options (window, application, tabs) configurable for both Firefox and Chrome. The config parameters are called `chromeScreenshareSources` (an array that can carry `screen`, `window` and `tab` values), and `firefoxScreenshareSource` (a string that can carry `screen`, …
=> [HTML5] STUN/TURN config support for SFU client-side apps and general improvements

bigbluebutton-client/resources/prod/lib/kurento-extension.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/kurento.js, labs/bbb-webrtc-sfu/lib/screenshare/ScreenshareManager.js
When KMS is misconfigured in the SFU component, it should throw a `Connection error` on the first attempt to connect.
Also landed a quick fix for Flash<->HTML5 interop that was broken on #5842, while I don't open the Flash equivalent of that one.
=> SFU correctly throwing connection error on KMS misconfig

bigbluebutton-html5/imports/api/users/server/eventHandlers.js, bigbluebutton-html5/imports/api/users/server/handlers/guestApproved.js, bigbluebutton-html5/imports/ui/components/app/container.jsx
It will be revisited in BBB 2.2
In 2.0 it is not picking correctly the switch from `approved` from `false` to `true` and is displayed permanently.
=> Disable HTML5 waiting screen for guest approve

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
This PR is an attempt to fix the tag attachment race condition that happens in the WebRTC video component. Seems good based on the tests I ran, but we need to keep on watch to see if it happens again.
It also adds some other minor fixes:
- Correctly checking peer availability in the client on SFU responses
- Cleaning SFU listen only ping/pong interval on exit
=> Trying to fix WebRTC video tag attachment

bigbluebutton-html5/imports/api/breakouts/server/eventHandlers.js, bigbluebutton-html5/imports/api/breakouts/server/methods.js, bigbluebutton-html5/imports/api/breakouts/server/methods/requestJoinURL.js, bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/service.js, bigbluebutton-html5/private/locales/en.json
- Add a method for request a breakout room join url.
- Create a UI for select breakout room.
- Remove breakout url getter in nav bar
- Allow users gets all breakouts when is free join breakout rooms.
Closes #5562.
=> Allow html5 user to join in any breakout room

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/private/locales/en.json
- When audio lock setting is enable viewers are connected as listen only.
- When to open the audio modal, only the listen only is enabled to join.
Closes #5833.
=> Comply audio lock setting.

bigbluebutton-config/bin/bbb-conf
chromeExtensionLinkURL gets crippled in config.xml thus Google Chrome server sharing extension fails to install through crippled link.
=> Crippled chromeExtensionLinkURL in bbb-conf

bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/modules/users/model/UsersOptions.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
Fixes in this PR:
* Removed the "moderatorUnmute" option from config.xml because moderators can never unmute other users anymore
* Fixed an issue in the method that processes newly joined users where their "guest" state wasn't being set properly
* Fixed an issue where viewers were shown a button to mute/unmute other users in the user list
* Fixed an issue where moderators could sometimes see no audio icons at all
=> Fixes for 2.2 merge issues in the client

bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileExportWindow.mxml
If you load the static SWF assets for the client from a CDN source instead of the BBB server an exception is thrown if you try to export the slide with annotations. This PR changes the exporting to use the PNG version of the slide instead of the SWF version so that no code is executed.
=> Use png of slide for export with annotations

bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
The gear in the user list was being shown to moderators when they moused over their own row and "allowUserLookup" was false. In that scenario there's nothing in the menu so it looks like the button does nothing. This PR makes sure the gear button is only shown to moderators when it isn't their own row.
=> Correct the userlist gear visibility

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
=> Presentation selected to be uploaded (or the first one of them) becomes current.

bigbluebutton-client/src/org/bigbluebutton/main/views/ShortcutHelpWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UserLookUpWindow.mxml
This PR changes the itemrenderer for the UserLookupWindow's value column to be selectable so that users can copy the text. I also made the window a little wider and made the property column thinner to give maximum space to the values.
=> Copyable user info

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
currently recording status not update when start/stop a meeting recording.
=> Fix recording status not update in nav bar.

bigbluebutton-web/grails-app/conf/spring/turn-stun-servers.xml
When some code was being moved around, it looks like a bad sed command got run
on this file which made the comments/documentation unreadable.
Revert to the previous version of the file.
=> Fix comments in turn-stun-servers.xml (v2.2-dev)

bigbluebutton-web/grails-app/conf/spring/turn-stun-servers.xml
When some code was being moved around, it looks like a bad sed command got run
on this file which made the comments/documentation unreadable.
Revert to the previous version of the file.
=> Fix comments in turn-stun-servers.xml (v2.0.x-release)

bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as, bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as
This PR makes the clearing of annotations and cursors on whiteboard change and cursor clearing on multiuser being turned off more assertive. Previously only annotations that were known were cleared and cursors were only cleared if the other client sent a new cursor coordinate. This would sometimes result in orphaned annotations and cursors. The new forceful clears should hopefully clear up both problems.
=> More assertive annotation and cursor clearing

bigbluebutton-html5/private/config/settings-production.json
The client logger can now be configured on the production settings #5604
=> Added client-logger settings to production

bigbluebutton-html5/imports/startup/client/auth.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
This PR ensures that the upload modal stays closed after a confirm / dismiss.
Also after sharing a cam, it will remain connected after the user's first route change.
=> Fix upload modal and cam unshare bug

bigbluebutton-client/resources/prod/locales.xml, bigbluebutton-client/src/BigBlueButton.mxml, bigbluebutton-client/src/org/bigbluebutton/core/BigBlueButtonApplication.as, bigbluebutton-client/src/org/bigbluebutton/core/managers/ConfigManager2.as, bigbluebutton-client/src/org/bigbluebutton/core/managers/PopUpManagerImpl.as, bigbluebutton-client/src/org/bigbluebutton/core/managers/SystemManager.as, bigbluebutton-client/src/org/bigbluebutton/main/views/LanguageSelector.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/BroadcastButton.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/SharedNotesWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/util/i18n/ResourceUtil.as
- Fix centring popups when `layoutDirection` is RTL. (Fix #5898):
- Create a custom `SystemManager` defined in `frame` tag to define to `IPopUpManager` inside.
- Create a custom `PopUpManager` that fixes Flex SDK popup centring.
- Made Persan language display from right to left.
- Improve preferred language detection, look for 'language_COUNTRY' format, then for `language`, and if not found we search for the first locale having the format `language_*`.
- Application layout direction change is moved from `MainApplicationShell` to `ResourceUtil`
- Make `MainApplicationShell` set the `layoutDirection` just after the `configXML` is loaded.
- Handle fixed position pop-ups in RTL mode.
- Improve logging by using the `LOGGER` property instead of `trace` function.
(Tested only on chrome-win-10)
=> Improve RTL layout behaviour and fix its display

bigbluebutton-html5/imports/startup/client/auth.js, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-menu/container.jsx
Changes necessary for custom implementations to use userdata and metadata parameters from the API correctly.
Also some small additions to the video and screen-share react elements:
* Add key to scree-nshare video tag to prevent console warnings
* Add ids to screen-share and video buttons to facilitate dom navigation of pages.
=> Add support for custom parameters (userdata) in HTML5 client

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml
Currently if an error occurs while trying to start the WebRTC screenshare in the Flash client, the user won't always be notified. This PR adds a simple 30s timeout to try and catch unhandled errors and inform the user that screenshare is likely not going to work.
=> Add a timeout to WebRTCScreensharePublishWin startup

bbb-webhooks/callback_emitter.js, bbb-webhooks/config.js, bbb-webhooks/config_local.js.example, bbb-webhooks/hook.js, bbb-webhooks/messageMapping.js, bbb-webhooks/test/test.js, bbb-webhooks/web_hooks.js, bbb-webhooks/web_server.js
There are two formats of webhooks we support: the raw format, when you pass getRaw=true on the hooks/create call, send to the callback the original (raw) event received on Redis; and the processed format, when you pass getRaw=false or do not pass anything on the hooks/create call, send the callback in a simpler and more structured format. When config.hooks.getRaw=true and the registered hook was getRaw=false, the callback wouldn't be called.
Also, include a commit that we missed in the previous PR.
@daronco @kmyokoyama please review.
=> Fix webhooks

bigbluebutton-html5/client/compatibility/sip.js
Rationale: the negotiation failed because SIP.js was resolving the local description without properly waiting for ICE completion, so the generated SDP would end up without any ICE candidate and FreeSWITCH would reject the call. The permissioning thing was more of a side effect that freed the stuck ICE candidate, so it ended up work. We now only resolve the local description when ICE gathering was properly completed and processed.
=> [HTML5] Attempt to fix SIP.js listen only permission problems

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/services/api/index.js
These commits add a few new options to the logging of mostly the media components using webrtc and the  bbb-webrtc-sfu.
Logging messages in these components now have a final object argument that can include a number of options. By default, we include the userId and userName that is calling the logger funcition and a 'topic' that is the name of the component, but can be overriden. New stuff can be added on a call by call basis. Here's some examples:
CLIENT LOG (DEBUG.ws):  "Received new message 'playStart'" , {
message: {
connectionId: 10,
type: "video",
role: "share",
id: "playStart",
cameraId: "w_29yvkyefydmz",
},
topic: "ws",
userId: "w_29yvkyefydmz",
userName: "vvvvv",
}
CLIENT LOG (INFO.video):  "Handle play start for camera", { 
cameraId: "w_29yvkyefydmz",
topic: "video",
userId: …
=> Additions to video, listen-only and screenshare logging

bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx
When you run the client in headless Chrome, it is possible to get `undefined` values from `browser-detect`. This PR allows client to work well in that situation (browser detection defaults to desktop).
=> Handling the case when browser detection package fails.

bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js, bigbluebutton-html5/imports/api/users/server/handlers/guestApproved.js, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Prior to this we could see `Error invoking Method 'logClient': Internal server error [500]` when webcams/screenshare were active
=> Add check for logClient to obtain meetingId for media calls

labs/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/AudioHandler.js
This solves an issue where the SFU listen only wouldn't work when FreeSWITCH and Kurento were in different IPs/environments.
=> Fix SFU listen only for dockerized environment

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json, bigbluebutton-html5/private/locales/en.json
Help button that links the user to the tutorial videos has been added to the drop-down list. The placeholder icon that is used for the button is the same icon used for the about button. Currently there is no icon that is a question mark can be used for the help button. #5962
=> Added help button to drop-down list

bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
In the current state, a guest user in the HTML5 client gets stuck in the "Waiting for approval..." loading window. This PR should fix that specific case when the policy is `ALWAYS_ACCEPT`.
=> Added support for ALWAYS_ACCEPT guest policy in the HTML5 client

bigbluebutton-html5/imports/ui/components/screenshare/service.js
It was firing an exception because the output was expected to be a `boolean` literal on the actions-bar component, but it was actually returning a string with the `rtmp` url.
=> [HTML5] Fixed WebRTC Screenshare isVideoBroadcasting check

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json, labs/bbb-webrtc-sfu/config/default.example.yml, labs/bbb-webrtc-sfu/lib/audio/audio.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SdpSession.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/utils/SdpWrapper.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js, labs/bbb-webrtc-sfu/lib/video/video.js
This PR adds a target bitrate option for both WebRTC webcams and screenshare. This can be configured in `bbb-webrtc-sfu`'s `config/default.yml`. See the `default.example.yml` file for an example. The new parameters are:
- `webcam-target-bitrate`: webcam target bitrate in kbps. Set it to `0` for unconstrained. Default 300 kbps.
- `screenshare-target-bitrate`: screenshare target bitrate in kbps. Set it to `0` for unconstrained. Default is unconstrained.
Be aware that the target bitrate will act as an ideal bitrate, but it might still be lower than that because we still use a REMB approach where the bitrate is scaled down to fit the worst connection in the conference.
Also added in this PR:
- Made the WebRTC camera constraints configurable. We can now set them (in the WebRTC spec format) in …
=> [HTML5] Added target bitrate option for WebRTC screenshare and webcam

akka-bbb-apps/src/main/resources/application.conf, akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
This PR adds a config property "whiteboard.multiUserDefault" to the akka-apps config that determines what the starting state of the multi-user whiteboard is. The default default is "false".
=> Add config option in akka-apps for default multi-user whiteboard state

bigbluebutton-config/bin/bbb-conf
Fixed #5967. Storing `chromeExtensionLink` happens now before applying the first change oto `config.xml`.
=> Fix chromeExtensionLink restore in bbb-conf

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
The WebRTC screenshare RTMP stream doesn't display correctly in Firefox on Mac. The stream only seems to show keyframes and not the intermediate steps. This PR adds automatic fallback to Java screenshare if the user is the presenter and displays a recommendation to switch to Chrome if the user is viewing the stream.
=> Add warning to Flash for WebRTC screenshare in FF on Mac

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, labs/bbb-webrtc-sfu/lib/audio/AudioManager.js, labs/bbb-webrtc-sfu/lib/audio/audio.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/freeswitch/freeswitch.js
Includes:
- Listen only correctly detects Kurento shutting down/crashing and meeting maintains a consistent state
- Correctly propagating an error to the client when KMS is misconfigured or down
- Fixed any "forever reconnecting" problem we had before (corrected client-side error handling on SFU audio bridge and implemented a max retry for the ICE gathering/joinListenOnly promise race)
=> Improvements to SFU listen only error handling

bigbluebutton-html5/imports/startup/client/logger.js
The fullInfo from Auth was being fetched once and then reused for every log message sent out. Caching this way meant that Auth wasn't filled with the correct information on a user's first load and all of the log messages couldn't be identified. This PR changes logging to fetch the fullInfo from Auth every time a log is sent out which will mean that the results are always accurate at the time of log creation.
=> Fetch fullInfo from Auth every time instead of caching

bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/users/views/StatusItemRenderer.mxml
This PR adds checks to the Status and Media ItemRenderers to detect when they are recycled and applied to a different user.
=> Reset rolledOver when user itemrenderers are used for a different user

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RecordAndClearPreviousMarkersCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/RecordStatusResetEvent.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala
Update for #5534
On @kepstin request this update handle the new record and clear previous marker events and saves it into the following format in `events.xml`
```xml
<event timestamp="539744812" module="PARTICIPANT" eventname="RecordStatusReset">
<userId>w_nlw1bcznkpys</userId>
</event>
```
=> Add a new message RecordStatusResetSysMsg to be handled and saved in events.xml

bigbluebutton-html5/client/compatibility/kurento-extension.js, labs/bbb-webrtc-sfu/lib/base/BaseManager.js, labs/bbb-webrtc-sfu/lib/bbb/messages/Constants.js, labs/bbb-webrtc-sfu/lib/bbb/pubsub/bbb-gw.js, labs/bbb-webrtc-sfu/lib/connection-manager/WebsocketConnectionManager.js, labs/bbb-webrtc-sfu/lib/screenshare/ScreenshareManager.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
Fixes #5974.
Listen presenter assigned message on SFU and close the session to avoid completing an ongoing screenshare negotiation when it's not needed anymore.
=> Fix screenshare edge case with presenter switch

bigbluebutton-client/resources/config.xml.template, bigbluebutton-client/src/org/bigbluebutton/core/managers/ConnectionManager.as, bigbluebutton-client/src/org/bigbluebutton/core/services/BandwidthMonitor.as, bigbluebutton-client/src/org/bigbluebutton/main/maps/ApplicationEventMap.mxml, bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesProxy.as, bigbluebutton-client/src/org/bigbluebutton/main/model/options/PortTestOptions.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as, bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/ConnectionManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/red5/Connection.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/business/VideoProxy.as, bigbluebutton-client/src/org/red5/flash/bwcheck/app/BandwidthDetectionApp.as
This PR addresses #6059. I've added an optional fallback host property (ipv4FallbackHost) to the <porttest> section of config.xml and if the property isn't blank the client will try the fallback host before trying to tunnel. The only change required to apply this yourself is a domain that only has IPv4 resolution and then to set the value of the property to "rtmp://ipv4host.com".  One fallout from this is that the module RTMP URIs will not longer use the hostname contained in their values, but we never really supported messing with them anyways.
=> Add RTMP fallback for IPv4-only hostname to the client

bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesProxy.as
This PR is a follow up to https://github.com/bigbluebutton/bigbluebutton/pull/6069 and adds a specific log message so the fallback case can be identified in the logs.
=> Add a specific log message when falling back to rtmp ipv4

bigbluebutton-client/src/org/bigbluebutton/main/events/BBBEvent.as, bigbluebutton-client/src/org/bigbluebutton/main/maps/ApplicationEventMap.mxml, bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as, bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as, bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/LayoutsCombo.mxml
=> Fix lock settings

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
The regex was greedily combining some of the app portion into the server portion. It's been edited to be more explicit.
=> Fix WebRTC screenshare RTMP URL regular expression

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
This is just a small CSS change to crop the cameras to cover the entire video rectangle. This does not change anything about the webrtc stream size or bandwidth, but in my opinion looks prettier and uses the interface more appropriately.
Here's a picture of how it looks:
=> Make it so that cameras use the full space of the video window

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopPublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/WebRTCDesktopViewWindow.mxml
Previously if your config.xml had RTMPS for all other red5 connections the WebRTC screenshare URL would still be RTMP. This PR makes it so that the screenshare connections inherit the protocol used in the config.xml.
Resolves #6078.
=> Make Flash WebRTC screenshare use RTMPS when available

labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SdpSession.js
The check was missing a case where there was no video codec available after the SDP passed through the H264 enforcement filter. It should throw the appropriate error for that case now (`Error 2203`).
=> Improve codec availability detection in SFU

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/core/managers/ConfigManager2.as, bigbluebutton-client/src/org/bigbluebutton/main/events/MeetingNotFoundEvent.as, bigbluebutton-client/src/org/bigbluebutton/main/model/modules/EnterApiService.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as, bigbluebutton-client/src/org/bigbluebutton/main/views/LoadingBar.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/LoggedOutWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
If the config.xml, or enter API, couldn't be loaded the client would sit on the loading bar and sometimes throw and exception. This PR simplifies the error handling and reports the error to the user rather than just showing nothing. In previous versions the client would automatically fetch the default logout URL (api/signOut), but at some point that stopped returning a URL.
=> Fix error handling when client parts fail to load

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/removeMeeting.js, bigbluebutton-html5/imports/api/presentation-pods/server/modifiers/clearPresentationPods.js, bigbluebutton-html5/imports/api/presentation-pods/server/modifiers/removePresentationPod.js, bigbluebutton-html5/imports/api/presentation-upload-token/server/modifiers/clearPresentationUploadToken.js, bigbluebutton-html5/imports/api/presentations/server/modifiers/clearPresentations.js
This PR fixes presentation pods and presentation upload token collections not being cleared correctly when a pod is removed or a presentation. I also fixed the log message when removing GroupChatMsg.
=> Fix not clearing pods and token when removing a meeting

record-and-playback/presentation/playback/presentation/2.0/playback.css, record-and-playback/presentation/scripts/publish/presentation.rb
This fixes a couple minor issues in the recording presentation and playback:
- The font size of text shapes wasn't correct
- Poll images weren't put into the presentation subdirectories, and the filenames contained a `//` from an empty path component.
=> Recording fixes for BBB 2.2

record-and-playback/presentation/playback/presentation/2.0/playback.css, record-and-playback/presentation/scripts/publish/presentation.rb
This fixes a couple minor issues in the recording presentation and playback:
- The font size of text shapes wasn't correct
- Poll images weren't put into the presentation subdirectories, and the filenames contained a `//` from an empty path component.
=> Recording fixes for BBB 2.0

bigbluebutton-html5/imports/api/meetings/server/modifiers/removeMeeting.js, bigbluebutton-html5/imports/api/users-settings/index.js, bigbluebutton-html5/imports/api/users-settings/server/index.js, bigbluebutton-html5/imports/api/users-settings/server/methods.js, bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/api/users-settings/server/modifiers/addUserSetting.js, bigbluebutton-html5/imports/api/users-settings/server/modifiers/clearUsersSettings.js, bigbluebutton-html5/imports/api/users-settings/server/publishers.js, bigbluebutton-html5/imports/startup/client/auth.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/logout-confirmation/container.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/service.js, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/services/users-settings/index.js, bigbluebutton-html5/private/config/settings-development.json, bigbluebutton-html5/private/config/settings-production.json, bigbluebutton-html5/server/main.js
Enables to set dynamic settings per user in a meeting, partially close #5989.
Supported settings for now:
- autoJoin
- listenOnlyMode
- forceListenOnly
- skipCheck
- clientTitle
- lockOnJoin (still need to be implemented)
- askForFeedbackOnLogout
- displayBrandingArea
- enableScreensharing
- enableVideo
- enableVideoStats
In Custom parameters add `userdata-{any of settings above}={some value}` for each needed setting
---
next step is expand the list of available settings:
- Restrict non-presenters in multi-user whiteboard to only pen tool (#5850)
- Make the list of whiteboard tools configurable (#5826)
=> Custom user settings

bigbluebutton-html5/imports/api/users/server/modifiers/changeRole.js
Closes #6004 
Closes #6107 
Improvements on the way we maintain a user's array of current roles (used for ACL): allowed items are `viewer`, `moderator`, `presenter`
The bugs resolved had to do with discrepancy between ACL item and UI or duplicated items in array
=> Maintain array of user roles so they are unique

bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, labs/bbb-webrtc-sfu/lib/audio/AudioManager.js, labs/bbb-webrtc-sfu/lib/base/BaseManager.js
This PR includes the following:
- Revamped the `kurento-utils` library to get rid of deprecated WebRTC API calls. We should be now up to spec, with an exception to chrome screenshare constraints. This was done because Safari 12 disable the legacy API support by default, which was making video and audio a bit unreliable on Safari. Safari 11 does support the updated spec AFAIK.
- Improvements to video reliability on Safari (Mac/iOS).
- Added a forced microphone permission request on Safari when trying to join listen only. This is related to WebKit ICE gathering policies, as said in the following: https://webkit.org/blog/7763/a-closer-look-into-webrtc/
- Transitioned SFU listen only to use `MediaStream` instead of using the HTML audio tag directly. This should improve its robustness.
- Added …
=> Improvements to Safari WebRTC interop and SFU listen only

bigbluebutton-html5/client/compatibility/kurento-utils.js
Added the `onunmute` listener to WebRTC MediaStreamTracks to detect tracks that turned unmuted after a while. This is a follow up to #6128 that fixes an issue that appeared with viewing screenshare on Firefox and increases overall reliability.
=> Added onunmute listener to MediaStreamTrack

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
A security update of Imagemagick library added a policy to PDF files.
To make `convert` command work, an update is necessary. The update is described in the answer of this link https://askubuntu.com/questions/1081695/error-during-converting-jpg-to-pdf
=> Add process handler to image conversion in SvgImageCreatorImp.java

bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
This PR adds extra data on the get recording api response.
```
<recording>
...
<playback>
<format>
<type>podcast</type>
<url>
https://example.com/podcast/fffc312304296c2f0287e2e5e98b79c4e3379692-1538487285527/audio.ogg
</url>
<processingTime>0</processingTime>
<length>7</length>
</format>
</playback>
<data>
<format>
<type>metrics</type>
<url>
https://example.com/metrics/fffc312304296c2f0287e2e5e98b79c4e3379692-1538487285527/data.json
</url>
</format>
</data>
</recording>
```
=>  Return some data metrics on get recordings api

bigbluebutton-html5/client/compatibility/kurento-extension.js
When using the screen share, Chrome and Firefox implements a functionality to choose which screen it should share.
In Electron it needs to be implemented manually. This code is to verify when the user is using Electron as client and then intercept the screen chooser with the Electron app implementation.
=> Adds compatibility with Electron Chromium to choose one screen to share

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, labs/bbb-webrtc-sfu/config/default.example.yml, labs/bbb-webrtc-sfu/lib/audio/audio.js, labs/bbb-webrtc-sfu/lib/base/BaseManager.js, labs/bbb-webrtc-sfu/lib/base/BaseProvider.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/kurento/kurento.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/constants/Constants.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/MediaController.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/MediaSession.js, labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/Room.js, labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js, labs/bbb-webrtc-sfu/lib/video/VideoManager.js, labs/bbb-webrtc-sfu/lib/video/video.js
- Implemented a websocket pool with configurable size (see `kurento-websocket-pool-size`). SFU will round robin between those websockets when communicating with Kurento. This was done to mitigate some issues we've seen and people have reported about Kurento websockets sometimes ending up unresponsive under high load. Basically, from what I've tested, handling ~50 elements per websocket is a pretty safe bet with Kurento, hence I made the default websocket pool size `7` by assuming a high load ceiling of ~350 streams. Keep in mind each of the processes (audio, video and screenshare) have its own pool, so it should amount to ~21 different and balanced connections.
- Added comments explaining some of the not-so-clear configuration parameters in `bbb-webrtc-sfu`
- Fixed an edge case when …
=> Make bbb-webrtc-sfu connect to Kurento using multiple websockets and other assorted improvements

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareSelectionWindow.mxml
The strings that are being used for the tooltips don't exist so the tooltips just show "undefined". This PR changes the tooltips to use the accessibility text which is a good substitute because the tooltips now read, "Start WebRTC screensharing" and "Start Java screensharing".
=> Fix the tooltips for the screenshare type buttons

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/startup/client/auth.js, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/service.js, bigbluebutton-html5/imports/ui/components/presentation/default-content/component.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/private/locales/en.json
Given that we use `userdata-` parameters in the html5 client, this pull request switches the existing meatadata parameters to userdata alternatives.
Test by passing the following block in the `customParameters` field in API MATE
```
joinViaHtml5=true
userdata-autoSwapLayout=true
userdata-autoShareWebcam=true
userdata-hidePresentation=true
```
=> Drop metadata configs; use userdata configs for autoSwap

bigbluebutton-client/resources/prod/BigBlueButton.html, bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
The WebRTC audio stats weren't being used and were just cluttering up the console output. I've disabled them to clear the console up.
Fixes #6175
=> [Flash] disable the webrtc audio stats

bigbluebutton-client/src/org/bigbluebutton/core/managers/ReconnectionManager.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
The old NetConnectionDelegate code would force a disconnect if the first reconnect attempt failed. My changes log the reconnect attempt failure now and it will instead try a few times. This helps if the connection isn't quite set up again.
=> Fix Flash reconnect attempts

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingAfterReconnectReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/testdata/FakeTestData.scala, bigbluebutton-client/src/org/bigbluebutton/core/model/users/VoiceUsers2x.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
When we receive a user left message, it might be because the client is reconnecting. Wait a few seconds for the client to reconnect and if it fails to reconnect, then remove the user's from the user's list and notify the other clients.
=> Delay removing user when leaving

bigbluebutton-html5/client/compatibility/kurento-extension.js
Trailing comma in function arguments does not allowed until ECMAScript 2017
=> Fix compatibility in some old browser

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/service.jsx, bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
This PR creates a HOC for components that have a shortcut and a custom parameter to define which shortcut will be available.
`userdata-shortcuts=["openOptions", "toggleMute"]`
- openOptions
- toggleUserList
- toggleMute
- joinAudio
- leaveAudio
- togglePublicChat
- hidePrivateChat
- closePrivateChat
- openActions
- openStatus
=> Configurable available shortcuts

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
We use the external meeting ID in `endCallbackUrl`.
=> Add `meetingid` GET parameter to endCallbackUrl

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- fix issue where meeting doesn't end when last user leaves or when meeting is never joined.
- the client to server rtt message is always updating the meeting activity. This prevents the meeting
from ending due to inactivity.
=> Fix issue: Meeting doesn't end when last user leaves

build_script.sh
This fixes the issue with linting that occurs when PR is related to HTML5 client, but at least one of the modified files is outside `bigbluebutton-html5` folder.
=> Filtering the files for linting

bigbluebutton-html5/imports/ui/components/user-list/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
The user list now scrolls correctly when overflow occurs. #6242
=> Fixed user list scroll

bigbluebutton-html5/private/config/settings.yml
The structure remains the same. Only the notation is modified for easier parsing/editing via tools like Ansible. With the previous notation it was not straightforward how to match  log type with log level or enabled flag
=> Modify clientLog notation for easier parse-edit

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx
Improvements to the client logs appearing on user join/subscription.
No more `User joined meeting and subscribed to data successfully` logs when opening/closing userlist / public chat or changing status.
=> Better client logs on user join/subscription

record-and-playback/podcast/scripts/process/podcast.rb, record-and-playback/podcast/scripts/publish/podcast.rb
@kepstin , not sure if you guys still uses this, but I was testing something else and found those,
at process:
```
E, [2018-12-06T12:10:23.833143 #4062] ERROR -- : undefined method `xpath' for #<String:0x00000001c8d3f8>
E, [2018-12-06T12:10:23.833291 #4062] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:34:in `get_num_participants'
E, [2018-12-06T12:10:23.833322 #4062] ERROR -- : process/podcast.rb:117:in `<main>'
```
and at publish:
```
E, [2018-12-06T12:35:20.280856 #5160] ERROR -- : undefined method `xpath' for #<String:0x00000001a199a0>
E, [2018-12-06T12:35:20.280902 #5160] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback/generators/events.rb:474:in `get_record_status_events'
E, [2018-12-06T12:35:20.280930 #5160] ERROR -- : …
```
=> Fixes podcast undefined method xpath errors

bigbluebutton-html5/imports/ui/services/unread-messages/index.js
Fix a problem with incorrectly unread chat notification when the user already read all messages. close #6258
=> Fix unread chat notification.

record-and-playback/core/lib/recordandplayback/events_archiver.rb
Issue #6338
It looks like there was a logic error in the code that was causing it
to break out of the event deletion loop early when deleting events for
the last (or only) segment in a recording. (In this case, last_index
is -1, so i >= last_index is always true).
The trim_events_for call was always succeeding, so the events were
being removed from the event list (meeting:{ID}:recordings key) even
though the events themselves hadn't been deleted in the loop.
I've moved the trim_events_for call to below the event deletion loop
to ensure that if the archive script is interrupted, the events list
will contain all not-yet-deleted events.
=> Ensure the archiver deletes events from redis for the last segment

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/actions-bar/service.js, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/private/locales/en.json
This PR adds: 
- Free join checkbox
- Drag and drop grid to sort users (Desktop only by now)
This PR modifies:
- The publisher rule for moderator to see all breakouts related with parent meeting.
- The breakout invitation rule to invite only users on breakout.
Closes #6262, #6261.
=> Add drag & drop grid for breakout rooms

bigbluebutton-html5/imports/api/breakouts/server/modifiers/clearBreakouts.js, bigbluebutton-html5/imports/api/captions/server/modifiers/clearCaptions.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/clearGroupChat.js, bigbluebutton-html5/imports/api/polls/server/modifiers/clearPolls.js, bigbluebutton-html5/imports/api/presentation-upload-token/server/modifiers/clearPresentationUploadToken.js, bigbluebutton-html5/imports/api/presentations/server/modifiers/clearPresentations.js, bigbluebutton-html5/imports/api/slides/server/modifiers/clearSlides.js, bigbluebutton-html5/imports/api/users-settings/server/modifiers/clearUsersSettings.js, bigbluebutton-html5/imports/api/users/server/modifiers/clearUsers.js, bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js
Before:
```
I20181213-20:07:38.589(0)? info: Cleared GroupChatMsg (183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1544731618269)
I20181213-20:07:38.590(0)? info: Cleared GroupChat (183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1544731618269)
I20181213-20:07:38.597(0)? Exception in callback of async function: TypeError: callback is not a function
I20181213-20:07:38.598(0)?     at packages/mongo/collection.js:729:7
I20181213-20:07:38.599(0)?     at runWithEnvironment (packages/meteor.js:1356:24)
I20181213-20:07:38.600(0)?     at packages/meteor.js:1369:14
I20181213-20:07:38.601(0)?     at packages/mongo/mongo_driver.js:331:7
I20181213-20:07:38.601(0)?     at runWithEnvironment (packages/meteor.js:1356:24)
I20181213-20:07:38.602(0)? Exception in callback of async function: TypeError: callback is not a …
```
=> Improve format of callbacks on collection document removal (to address exception)

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
This is a follow-up to #6425.
I've basically added a `restarting` flag to the camera stop procedures as to identify a reconnection attempt so we won't delete the restart timers that keep track of them.
=> Fixed HTML5 viewer cam reconnections

bigbluebutton-client/resources/prod/lib/sip.js
Chrome is introducing a new "unified plan" for their WebRTC SDP and in Chrome 72 they are going to be making it the default format. Our webrtc library and FreeSWITCH aren't set up to handle the format change yet so this PR creates the RTCPeerConnection in "plan-b" mode (legacy way) as a stop gap until we can be compatible with the new SDP format and WebRTC APIs.
Other browsers and older versions of Chrome should just ignore the new property and will continue to function the same as they have in the past.
See #6414 for the original issue.
For information on the differences between the unified plan and plan-b refer to: https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU
=> Create RTCPeerConnection with sdpSemantics:plan-b for Chrome unified-plan

bigbluebutton-html5/client/compatibility/sip.js
The original PR for this issue is #6435. This PR is a copy to make the same change to the HTML5 client's version of sip.js.
=> [HTML5] create RTCPeerConnection with sdpSemantics:plan-b for Chrome unified-plan

bigbluebutton-client/resources/prod/lib/sip.js, bigbluebutton-html5/client/compatibility/sip.js
These commits are cherry-picked from #6435 and #6436 to apply the Chrome unified plan workaround to 2.2 code.
=> Chrome plan-b support applied to 2.2 cherry-picked from 2.0

bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js
Set `public` as default value for Session property `idChatOpen` in order to prevent some unexpected behaviour from Chat component and fix a problem with unread messages counter and scroll. It's a follow up from #6440.
=> Set default value for idChatOpen

bigbluebutton-html5/imports/ui/components/chat/message-list/styles.scss, bigbluebutton-html5/imports/ui/components/chat/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
- Fix opacity on presentation uploader. Fix #6402.
- Fix scroll disappearing with long messages. The scroll disappearing because it's no width defined, hence, the message list uses the content size. Fix #6443. 
- Add margin bottom in title of the chat. Fix #4903 (Partial).
=> Fix some bugs at BBB HTML5 client

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- Wait for SDP to be processed before adding candidates to peer on video
This was done to go around an issue reporting with webkit implementations that happened when we tried to add ICE candidates to the peer before the SDP was processed.
```
ERROR: clientLogger: [video] Error adding candidate: TypeError: Can only call RTCPeerConnection.addIceCandidate on instances of RTCPeerConnection https://..
```
=> Fix Safari issue with processing ICE candidates for video

bigbluebutton-html5/client/compatibility/kurento-extension.js
- Removed ICE state change listener on screenshare presenter exit
Sometimes an ICE connection error toast would pop when exiting screensharing because the listener wasn't correctly removed for the presenter.
=> Fixed incorrect error toast on screenshare presenter exit

bigbluebutton-html5/imports/ui/components/video-preview/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
This PR fixes #6251. It improves the mobile UI and makes sure we remove the event listener for `beforeunload`.
=> Improve webcam picker

bigbluebutton-client/locale/en_US/bbbResources.properties, bigbluebutton-client/src/org/bigbluebutton/main/model/PortTest.as, bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesProxy.as, bigbluebutton-client/src/org/bigbluebutton/main/views/LoadingBar.mxml
In some scenarios with FF 62+, Win 10, and RTMPS the connection will stall without any warnings or other messages. This PR adds a 10s timer that will show a recommendation to try Chrome when the conditions are met.
I also added some extra log messages to some edge cases in the port test logic that previously didn't have any.
=> Add detection for a stalled connection with FF62+ and Win 10

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Particularly common in Safari when loading html5 client inside iframe
Closes #6433 
Reasoning - Enter API failed, resulted in no useful data sent to client, unable to authenticate
=>  BBB-web: add allowRequestsWithoutSession=false to handle missing cookie

bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
If a user had a quote in their name (commonly used for nicknames) they were unable to join audio because sip.js would reject it. This PR replaces any instance of " with ' in the user name which will get around the block without greatly changing semantics.
=> Replace double quotes in audio name with single quotes

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.scss, bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/styles.scss, bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx, bigbluebutton-html5/imports/ui/components/modal/simple/styles.scss, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
The modal component can now be used for various  different modal designed with the hideBorder option. With the hideBorder property set to true, there is no need to individually modify modalBase for each component , thus now all modals will have a consistent structure with one another. #6016
=> Added option to use modal component without header border

bigbluebutton-html5/imports/startup/client/intl.jsx
Uses `addLocaleData` to register the available locale data module's with the locale data registry. Closes #6406
=> Fix broken locales on load

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-client/resources/prod/lib/kurento-utils.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js
This adds support for the new `navigator.getDisplayMedia` call on Google Chrome (edit: and Edge) which doesn't demand an extension for screensharing. This PR is backwards compatible with extension sharing: if the user is using an older version of Chrome, it'll fallback to the `chooseDesktopMedia` based screensharing.
This has been applied to both Flash and HTML5 clients. The advanced constraints we used (`goog*`) to better control quality and performance aren't supported by gDM, but I left them there in case they get supported in the future. The `frameRate`, `width` and `height` constraints aren't supported by gDM too, so I had to work around that by applying then manually as optional constraints to the `MediaStreamTrack` generated by the call.
Another thing that isn't supported yet by …
=> Add support for getDisplayMedia on Chrome and Edge

record-and-playback/presentation/playback/presentation/2.0/playback.js
Previously, the acorn player was being initialized before the asynchronous
load of captions information completed, meaning that the acorn player didn't
know there were caption tracks, and the CC selector control wasn't available.
Fixes #6463
=> Wait until the media is ready before initializing the acorn player.

bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
Limit the zoom functionality (double-tap) to occur only when the pan tool is selected #6520
=> Limit the zoom functionality in double-tap #6520

bigbluebutton-html5/imports/ui/components/user-list/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This PR fix a problem with some users getting ejected after try to initiate a private chat when private chat is locked. Update the UI when private chat is locked to only show this action when the users already had a private chat conversation.(only affect viewers, moderators still see the action every time)
Issue: #6434
=> Fix a problem with ejected user when private chat is locked.

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
Avoid send same message when user press enter many times in a slow dispositive. Fix issue #6500
=> Avoid duplicated messages. #6500

bigbluebutton-client/resources/prod/lib/adapter.js, bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
This PR is the first steps towards supported WebRTC for Edge. There are some FreeSWITCH configuration changes required to go along with these code changes.
The various SIP profiles in /opt/freeswitch/conf/sip_profiles/ need to have the following changes.
Remove or comment out the line `<param name="nonce-ttl" value="60"/>` in all of the profiles.
The IPv4 profiles need the following ACLs:
```
<param name="apply-candidate-acl" value="localnet.auto"/>
<param name="apply-candidate-acl" value="wan_v4.auto"/>
<param name="apply-candidate-acl" value="rfc1918.auto"/>
<param name="apply-candidate-acl" value="any_v4.auto"/>
```
The IPv6 profiles need the following ACLs:
```
<param name="apply-candidate-acl" value="wan_v6.auto"/>
<param name="apply-candidate-acl" value="rfc1918.auto"/>
<param …
```
=> Remove WebRTC blocks for Edge and update adapter.js

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-client/resources/prod/lib/kurento-utils.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js
Ported a fraction of #6599 that improves `getDisplayMedia` detection and usage.
This was done because Chrome folks decided to move it from the `navigator` scope to `navigator.mediaDevices` on 72, and Edge still relies on the `navigator` scope.
=> Improved getDisplayMedia detection

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-client/resources/prod/lib/kurento-utils.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js
- Backported #6490 from 2.2 to support extension-less screensharing via getDisplayMedia
- Fixed an issue with Chrome extension-based screensharing with the latest adapter.
=> Backport of getDisplayMedia support (#6490) and Chrome screenshare fixes

bigbluebutton-client/resources/config.xml.template
This PR updates the copyright in config.xml to use 2019 instead of 2018.
=> Update the copyright in 2.0 Flash client to 2019

bigbluebutton-html5/client/compatibility/kurento-utils.js
Reverted a change made to `kurento-utils.js`related to how the SDP offer was passed through the `WebRtcPeer.generateOffer` callback.
@gustavotrott If you could retest this with your Safari/iOS stuff. I'm not sure why this was changed in the first place on #6547. The change, to me, seems to bind the offer callback to the gathering state which would make the negotiation a bit non-trickle and also broke webcam/screensharing on Chrome+Windows.
=> Fix webcam/screen sharing on Windows

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Improper use of `webcamDeviceId` from `state` results in sharing wrong webcam.
=> Fix the issue with webcam preview and webcams dropdown

bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as
WebRTC screenshare for Edge isn't working in 2.0 so this PR re-enables the block.
=> Add back WebRTC screenshare block for Edge

bigbluebutton-client/resources/prod/lib/adapter.js, bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
This PR contains and cherry-picked commit from #6593 that removes the hardcoded WebRTC blocks for Edge. I don't think WebRTC screenshare will work in Edge, but it will allow for future work to be done.
Same as with #6593 there's additional configuration changes needed for FreeSWITCH. The various SIP profiles in /opt/freeswitch/conf/sip_profiles/ need to have the following changes.
Remove or comment out the line `<param name="nonce-ttl" value="60"/>` in all of the profiles.
The IPv4 profiles need the following ACLs:
```
<param name="apply-candidate-acl" value="localnet.auto"/>
<param name="apply-candidate-acl" value="wan_v4.auto"/>
<param name="apply-candidate-acl" value="rfc1918.auto"/>
<param name="apply-candidate-acl" value="any_v4.auto"/>
```
The IPv6 profiles need the following ACLs: …
=> [2.2] Remove WebRTC blocks for Edge and update adapter.js

bigbluebutton-client/resources/prod/lib/kurento-extension.js
Ported another fraction of #6599. Must be merged when  #6609 is merged, else Chrome extension-based screensharing on Flash will break.
=> [2.2][Flash] Fixed Chrome extension-based screensharing with latest adapter

bigbluebutton-html5/client/compatibility/adapter.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
This PR updates the version of adapter.js to the latest build so that Edge audio can be supported in the HTML5 client.
I also renabled the sip.js logging and sent it through the common client logger. The audio bridge code needs a major rewrite to support effective error reporting so I'll worry about making the logging configurable then.
=> Update the version of adapterjs and renable sipjs logging

bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-client/resources/prod/lib/kurento-utils.js, bigbluebutton-html5/client/compatibility/kurento-extension.js, bigbluebutton-html5/client/compatibility/kurento-utils.js
The Safari webview decided not to provide the mediaDevices scope and that broke things.
=> Check if mediaDevices exists before checking for gDM availability

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx
Show the audio model when microphone is locked in meeting, and fix a problem while connecting to listen only when microphone is locked, and remove lock layout from lock options.
Issue: #6574
=> Show audio modal when microphone is locked

bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
The ICE connection has multiple stages and in most browsers the call is ready when the connection state is "connected", but in Edge the call isn't ready until the state is "completed". This PR makes our bridge code ignore the "connected" state update when the browser is Edge.
=> Webrtc call is ready in Edge when completed not connected

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
This PR hide the manage users option in user list for viewers.
Issue: #6675
=> Don't show manage users option for viewers

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
This PR removes the mapping of the sip.js logs to our custom logger. The formatting didn't really translate well and I don't know that the noise is really necessary to send to the server at the moment. I've instead added more log messages for specific things that will contain the information that is relevant later.
=> Update the html5 sipjs logging with more messages

bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as
This PR adjusts the check for an Chrome screenshare extension key so that it only checks when the browser version is less than 72.
I also included a fix to a warning when building the NetConnectionDelegate about duplicate variable definitions in the same scope.
=> Remove the Chrome extension check for versions >= 72

record-and-playback/presentation/playback/presentation/2.0/playback.js
The initialization order change to support captions moved the acorn
initialization to after some of the popcorn init had already run. We
have to move that function to run after we create the acorn player
so it references the correct #video element (since acorn replaces/
moves it during init)
=> Fix loading slide images in presentation format

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx
The mobile APP does not support Microfone and share Camera (for now).
So it is necessary to hide this options to avoid errors in application.
This PR adds:
- Verifies if the userAgent contains "bbbnative" and set isMobileNative
- Does not render Mic button if isMobileNative is true
- Does not render Camera button if isMobileNative is true
_The APP is including the string bbbnative in the userAgent string to make this verification possible_
=> Hide Mic and Camera buttons when userAgent is Mobile App

bbb-api-demo/src/main/webapp/demoNative.jsp, bbb-api-demo/src/main/webapp/demo_header.jsp
This PR adds:
- Demo page that try to launch a native app if it exists (is installed)
_When the user has the App installed in their device. The App is automatically launched and join the conference._
=> Add open-in-native-app functionality in demo page

record-and-playback/presentation/playback/presentation/2.0/playback.js
Revert the changes to fix caption loading, because the change in the order of initialization has broken a bunch of other stuff like loading presentation pages and syncing deskshare video.
=> Break captions

bigbluebutton-html5/imports/ui/components/audio/device-selector/component.jsx
Like we discussed in #6590, Safari can't obtain the list of output audio devices.
This PR verify when browser is Safari and populate the `Speakers list` with only one option: "Default"
**Before**
**After**
=> Show 'Default' in Speakers list when browser is Safari

bigbluebutton-client/resources/prod/BigBlueButton.html, bigbluebutton-client/resources/prod/lib/bbb_blinker.js, bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
This PR updates a JS function that determines browser and version to use bowser for detection as it's more accurate and up to date than the old method. I also discovered that the browser detection in ScreensharePublishWindow used for showing the help images was removed awhile back so I've fixed that also.
=> Use bowser for browser detection - 2.0 Edition

bigbluebutton-client/resources/prod/BigBlueButton.html, bigbluebutton-client/resources/prod/lib/bbb_blinker.js, bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
This PR updates a JS function that determines browser and version to use bowser for detection as it's more accurate and up to date than the old method. I also discovered that the browser detection in ScreensharePublishWindow used for showing the help images was removed awhile back so I've fixed that also.
=> Use bowser for browser detection - 2.2 Edition

bbb-common-web/src/main/java/org/bigbluebutton/api/util/ParamsUtil.java, bigbluebutton-client/resources/prod/lib/kurento-extension.js, bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/note/service.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js, bigbluebutton-web/bbb-web.nginx, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
Rebased and resolved #6645 after bbb-web changes.
For this to work we need to change `notes.nginx` for:
```
location ~ "^\/pad\/p\/(\w+)" {
rewrite                /pad/(.*) /$1 break;
rewrite                ^/pad$ /pad/ permanent;
proxy_pass             http://localhost:9001;
proxy_pass_header      Server;
proxy_redirect         / /pad;
proxy_set_header       Host $host;
proxy_buffering off;
auth_request /bigbluebutton/connection/checkAuthorization;
auth_request_set $auth_status $upstream_status;
}
location /pad {
rewrite                /pad/(.*) /$1 break;
rewrite                ^/pad$ /pad/ permanent;
proxy_pass             http://localhost:9001/;
proxy_pass_header      Server;
proxy_redirect         / /pad;
proxy_set_header       Host $host;
proxy_buffering off;
}
location …
```
=> Minimal authentication for SFU and Etherpad connections

bigbluebutton-config/bin/apply-config.template, bigbluebutton-config/bin/bbb-conf
This pull request 
* Refactors some of bbb-conf to use xmlstarlet and yq for more reliable extraction of data
* adds `apply-config.template` to `/etc/bigbluebutton/bbb-conf` to serve as a template for `apply-config.sh`
System administrators can use `apply-config.sh` to automatically apply local configuration changes when updating packages followed by `bbb-conf --setip` or `bbb-conf --restart`.
=> Update bbb-conf to now call apply-config.sh (if available)

bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
Reverts bigbluebutton/bigbluebutton#6729
Reverting as this change causes viewers in a meeting to obtain privileges (and to look like) moderators
With line `changeRole(ROLE_MODERATOR, false, userId, meetingId);`
Without it:
=> Revert "Fix error when user is not moderator"

bigbluebutton-html5/imports/ui/components/actions-bar/service.js
The code was trying to use the `moderator` property of User, but that doesn't exist and the role is actually stored in `role`. This PR fixes #6565.
=> Fix ActionBar moderator check

bigbluebutton-html5/package.json
As a bonus to removing the explicit dependency, we can now also run `npm audit` without having to make code changes!
Note - there were no changes in package-lock.json this time
=> Remove explicit dependency to core-js

bigbluebutton-html5/imports/startup/client/base.jsx
This PR fix the problem with subscribing every 10s to collections when recording is active, also solve a problem with text tool, reported in #6796.
_Issue: #6723_
=> Prevent subscribing every 10s when recording

bigbluebutton-html5/imports/api/external-videos/server/methods/startWatchingExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js, bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx
When the current presenter is sharing an external video and he leaves, the sharing video is stopped.
_Issue: #6596_
=> Stop external video sharing when current presenter leaves

bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
This PR is a copy of #6514, but for master this time. It changes any " in a user's name into ' which is accepted by sip.js.
Fixes #6805.
=> Replace double quotes in audio name with single quotes - 2.2 edition

record-and-playback/core/lib/recordandplayback/events_archiver.rb
BigBlueButton can sometimes write events out of order - this particularly
seems to affect the final RecordStatusEvent in a meeting which was ended
while recording was still running. This breaks the recording processing
scripts.
As a workaround, sort the events as they're being written into the events.xml
file. We have the following properties:
* The input data is already mostly sorted
* Items in the wrong position will be no more than a couple spots off from where
they should be
* We should not change the relative order of events with the same timestamp.
The best algorithm to use here is a simple insertion sort. When adding each new
event to the XML structure, it scans backwards through existing events until it
finds the correct position.
For #6035
=> Sort events when writing the events.xml file

record-and-playback/core/lib/recordandplayback/events_archiver.rb
I had renamed prev_event to previous_event, but missed a couple of spots.
=> Recording events archiver: fix syntax errors

record-and-playback/core/lib/recordandplayback/events_archiver.rb
To help us track down exactly why this is happening - and know when we've
properly fixed it - add some logging.
=> Recording archive: log when events are are out of order and must be sorted

record-and-playback/core/scripts/rap-archive-worker.rb
This was added to workaround for red5 taking a while to rewrite the
serialized (.ser) data that it streams to disk back to the .flv format.
The workaround is no longer needed, for two reasons:
* The sanity scripts run the red5 code to generate the .flv from the .ser
if needed, and
* We're expecting more people to be using WebRTC media in the future anyways
This makes recordings available up to 2 minutes earlier than they would have
been otherwise.
Fixes #6826
=> Recording: Remove the red5 race workaround that delays processing

bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as, bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
This PR restores back the functionality for detecting a quick poll. We currently only support polling on the main pod so I've made some simplifications for finding the current page.
Fixes #6771.
=> Restore quick polling in Flash

bigbluebutton-html5/private/config/settings.yml
- This was done to mitigate packet loss and flickering and better abide to our default configured bitrate (300kbps).
This goes alongside updates to bbb-webrtc-sfu and kurento-media-server to increase reliablity and diminish stream artifacts.
I'll probably revisit this resolution change once I can correctly identify the source of corrupted frames, but I really think we should
maintain this as 320x240 for the time being. 640x480 would only be feasible if we increased our default bitrate config to 500kbps.
=> [HTML5] Change default resolution for webcams to 320x240

bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/note/styles.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/palette.scss, bigbluebutton-html5/private/locales/en.json
This PR will provide a visible label indicating the key used to move keyboard focus out of the text editor, for users who don't have a detected pointer device. Also provides an announcement of this label when the `iframe` is focused with the screen readers virtual cursor.
Closes #6656
=> Improve shared notes accessibility

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/CreateGroupChatReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatOptionsTab.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatTab.mxml, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This PR fixes a couple of issues related to private chat for viewer users. The detection for whether or not the input box is enabled was broken and was throwing an exception. This meant that the input was always enabled and would sometimes allow viewers to get on the wrong side of the permission checks and get ejected. This PR also restores extra private chat functionality so that a viewer can start and respond to a private chat involving a moderator. ~~I've only covered the Flash client side of this work, but the HTML5 side can easily be added after this has been merged.~~ Both clients allow viewers to private chat with moderators.
=> Fix private chat for viewers and allow private chat with moderators

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
This PR is to fix the issue #5456 
_In my tests, I don't see the webcam icon after timeout error.
But I see the icon when I close the video preview modal through close button._
=> Stop tracks when close preview modal

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
There were two spots (one in bbb-common-web and one in akka-apps) where the incorrect inactivity values were getting used. The first case was that bbb-web would create a meeting with values swapped. The second case was using the `userInactivityInspectTimerInMinutes` where the `userInactivityThresholdInMinutes` was supposed to be.
Values for testing that I used were:
```
"userInactivityInspectTimerInMinutes": 2
"userInactivityThresholdInMinutes": 3
"userActivitySignResponseDelayInMinutes": 1
```
The inspect time needs to be greater than the response delay or people don't get kicked. It might be possible to set the threshold lower also.
=> Fixed mapping of inactivity values

bigbluebutton-html5/imports/ui/components/media/styles.scss
Avoid `NS_ERROR_FAILURE` in Firefox which leads to client crash and solves a problem when presenter publish a poll and a viewer is with presentation close.
- _Poll issue: #6710_
- _Multi whiteboard issue: #6857_
The problem was that Firefox can't handle `getBBox()` of element that are `display: none`, the solution was set the elements to use `visibility: hidden` instead.
In the example below it's possible to observe this behaviour:
https://jsfiddle.net/dekkard/b0t5mbea/
You will need 2 or more users
Enable multi whiteboard
Start drawing or leaving the presentation area with the cursor and then close the presentation. (The problem should only occurs on Firefox)(The exception don't occurs often)
=> Avoid client crash when in multi whiteboard mode and when publishing polls

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
This Pr adds:
- Change webcam resolution to 640x480 if using iOS (It is necessary because iOS cannot give 320x240)
- Guarantee the `constraints.video.deviceId` is in devices list of `enumerateDevices` (sometimes the `webcamDeviceId` was an invalid Id in iOS tests)
This PR solves the #6947 issue.
=> Change webcam resolution to 640x480 if using iOS

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss, bigbluebutton-html5/private/locales/en.json
Closes #6973 and #6907.
Also display's the fullscreen button in the options menu for Safari 12, partially closing #6936.
=> Fix fitToWidth label toggle / button alignment

bigbluebutton-web/pres-checker/build.gradle, bigbluebutton-web/pres-checker/build.sh
Used classes from `commons-compress` seems to not be provided in POI 4.
This PR fixes the following issue when running the presentation checker.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:298)
at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xslf.usermodel.XMLSlideShow.<init>(XMLSlideShow.java:109)
at org.bigbluebutton.prescheck.Main.check(Main.java:38)
at org.bigbluebutton.prescheck.Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at …
```
=> Add commons-compress dependency to pres-checker project

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala
Previously an unlocked viewer couldn't unmute when the microphones were locked in a meeting. I just had to add an additional check for the user's personal lock state.
Issue was reported in https://github.com/bigbluebutton/bigbluebutton/pull/7005
=> Allow unlocked viewers to unmute when meeting is locked

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
This is a complement for #6985.
Now instead of detecting ios/iphone/ipad, it detects failure to obtain `getUserMedia`, and then try a different resolution
=> Change to higher resolution if getUserMedia throws exception

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/TimeUtil.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-apps/src/universal/conf/application.conf, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala
Sometimes, nodejs takes most of the CPU that users takes a long time to load the client and join. This way, we can detect if there are a number of users failing to join the meeting.
=>  - track if user joins within a certain period of time. 

bigbluebutton-html5/imports/api/group-chat-msg/server/eventHandlers.js, bigbluebutton-html5/imports/api/group-chat/server/eventHandlers.js, bigbluebutton-html5/imports/api/voice-users/server/modifiers/updateVoiceUser.js
Prior to this change, every time a Flash client user joined the meeting, the entire chat history would be resent via redis (to the Flash user) but html5 server side would also pick it up and re-process.
=> Only process chat msgs when requested from html5

bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx, bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This PR adds an empty space to the user avatar where the audio icon is displayed when the user isn't in audio. The goal is to make it more clear that something is missing. For the moment, I think we want to just try it out and see what we think. The issue is #7053.
=> Show bite out of avatar when not in audio

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
The headers for three of the audio modal contents were being fetched only once in the constructor. I moved the formatMessage() call to the render so that the desired string is used.
Reported here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/w8hnHj7IvWY.
=> Moved the translation of the audio modal headers

bigbluebutton-html5/imports/ui/components/chat/container.jsx
For some reason the moderator-only message was getting cleared from the public chat when "Clear" was run. This PR removes the code that hid the message. The work is based off of #6898 which was a similar fix for the welcome message.
Reported here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/w8hnHj7IvWY.
=> Don't clear the mod message from chat

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/styles.scss, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss, bigbluebutton-html5/private/locales/en.json
This PR adds warnings to the audio and video modals that inform Edge (and potential) IE users that their browser isn't fully supported and that they should use Chrome or Firefox.
I also fixed an infinite loop in the video preview.
=> Add modal warnings for edge users

bigbluebutton-html5/imports/ui/components/button/styles.scss, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
This PR makes it so that both disabled and non-disabled buttons will now show the desired focus outline to Chrome users. It also adds some extra spacing to the bottom buttons in the video preview modal so that they don't cut each other off.
=> Fix outline of disabled buttons and button getting cut off

bigbluebutton-html5/imports/startup/client/base.jsx
The base component is updated every time that a user starts or stops talking.
When it happens, the subscription to Annotations collection is recreated (and the mongo document that represent the annotation is removed/inserted causing the component to be unmounted/mounted).
In order to avoid this behavior, this pull request modifies it to not remove/insert the document representing the current annotation.
Closes #6904.
=> Talking causes text tool lose focus

bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
`Auth.clearCredentials` was changing the properties for `null` and the base uses these properties to do `Meteor.subscriptions` and when a property is changed the meteor remakes the subcritions passing the null values to the publishers.
Closes #6925.
=> Remove clear credentials that cause new client subscriptions.

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GuestsWaitingApprovedMsgHdlr.scala, bigbluebutton-html5/imports/api/guest-users/server/eventHandlers.js, bigbluebutton-html5/imports/api/guest-users/server/handlers/guestApproved.js, bigbluebutton-html5/imports/api/guest-users/server/handlers/guestsWaitingForApproval.js
This should handle #6987 
Right now Meteor is listening and processing all `GuestsWaitingForApprovalEvtMsg` and `GuestsWaitingApprovedEvtMsg` messages.
This way `akka-apps` will always send a message addressed to Meteor and Meteor can filter what it is supposed to process or not.
=> Sending an extra message for guest management in Meteor

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
Fixed if statement that prevented state to be updated with the most recent notifications, causing the audible notifications to happen only when toasts were enabled.
Closes #7195
=> Fix audible notifications

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/AddShapeWhiteboardRecordEvent.scala
Sometimes, we get null values for some of our whiteboard shapes. We need to
weed these out so as not to cause any problems to other components. We've
seen where the null values killed the RecorderActor when trying to write to redis.
This PR looks through all values for each whiteboard shape coming in from the client and remove those with null values.
=>  - remove null values from whiteboard shapes

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
In the Flash client we kept the WebRTC timeouts fairly short because we wanted to be able to fallback to the Flash audio for a better experience, but in the HTML5 client we have no fallback. This PR increases the timeouts because it's the only shot we have.
=> Increase audio timeouts in HTML5

bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
Was seeing logs like
```
[{"name":"clientLogger","level":50,"logCode":"startup_error","levelName":"error","msg":"TypeError: Cannot read property '0' of undefinedn    at k.handleEscapeHide (https://____________.com/html5client/9dfe674c161537255e5a566f150dc06b872bc725.js?meteor_js_resource=true:125:819887)","time":"2019-04-18T15:52:02.400Z"
```
=> Add checks before operating with tooltips

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
This PR fixes the case where a poll is published but the waiting message / animation does not disappear.
The issue was reported on slack. 
* Polling still says [Waiting for results ... (with animation)] even after I published the poll results
=> Hide poll waiting message on publish

bigbluebutton-html5/imports/startup/client/base.jsx
When the user with the expired session tries to join the meeting, the client tries to subscribe for the collections but throws an error because the publisher requires the credentials to ensure that it's a trusted user.
=> Remove server exception when user with expired session tries to join

bigbluebutton-html5/client/legacy.jsx, bigbluebutton-html5/client/main.html, bigbluebutton-html5/imports/ui/components/legacy/component.jsx, bigbluebutton-html5/imports/ui/components/legacy/styles.css, bigbluebutton-html5/package.json, bigbluebutton-html5/private/locales/en.json, bigbluebutton-html5/server/main.js
This PR implements Meteor's built-in legacy browser detection in order to load an alternate minimal client that will render on all devices. I had to duplicate the react-intl initialization because the original implementor imports classes that cause issues. I also couldn't use SCSS because it will use Proxy and it's not possible to polyfill Proxy.
I put in two different messages depending on whether or not the browser is not supported (IE) or an old version of supported browser. I also included a fallback static string for the scenario where the locale can't be loaded.
IE:
Old Chrome:
=> Add alternate legacy browser content

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/MuteUserCmdMsgHdlr.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/AppsTestFixtures.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-message/src/test/scala/org/bigbluebutton/common2/TestFixtures.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-client/src/org/bigbluebutton/core/model/Meeting.as, bigbluebutton-client/src/org/bigbluebutton/core/model/MeetingBuilder.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/EnterApiResponse.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as, bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
After some discussion with @capilkey, @fcecagno and @prlanzarin, the permission to unmute any user is something we could use on our end. So I changed this https://github.com/bigbluebutton/bigbluebutton/pull/7234 from `unmuteViewers` to `unmuteUsers`.
=> Unmute users

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/minBrowserVersion.js, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/server/main.js
This PR moves the legacy browser versions into settings.yml which will make configuration changes easier. I also added an endpoint for the app at "/html5client/useragent" that will return back the browser information that Meteor will detect for the user. This will be helpful down the road if there's a browser that is showing the legacy content when it shouldn't.
I also added "firefoxMobile" to the list because it was getting incorrectly flagged as unsupported. This will address one part of #5765.
=> Move legacy browser versions into settings.yml

bigbluebutton-html5/imports/ui/components/lock-viewers/notify/component.jsx
Closes #7394 
The strings no longer matched the lock settings props so could not be used as keys
Related to #7138
=> Adjust lock chat strings to be used as keys

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
This PR changes how the client determines when it's in the echo test and when the transfer to the conference is successful. The new method is to have the FreeSWITCH dialplan send back DTMF INFO messages so that we don't have to rely on guessing or the server components. 
In order for this to work there are some dialplan changes required. The first two files already exist and need to be changed and the third file is new.
/opt/freeswitch/conf/dialplan/default/bbb_conference.xml
```xml
<include>
<extension name="bbb_conferences_ws">
<condition field="${bbb_authorized}" expression="true" break="on-false"/>
<condition field="${sip_via_protocol}" expression="^wss?$"/>
<condition field="destination_number" expression="^(\d{5,6})$">
<action application="set" data="jitterbuffer_msec=20:400"/> …
```
=> Improved audio connect and transfer

bigbluebutton-html5/imports/ui/components/toast/component.jsx
Fixes toasts not being announced in Firefox & Edge by screen reader (JAWS)
=> Remove duplicate "role=alert" prop from toast notification

bigbluebutton-html5/imports/api/slides/server/modifiers/addSlide.js, bigbluebutton-html5/private/config/settings.yml
The HTML5 server code downloads the slides to determine their width and height, but there are some scenarios where the client needs an HTTPS URL and the server can only access the HTTP endpoint. This PR adds a flag that will turn on the necessary conversion to support this set up.
=> Add option to force server to use HTTP slide URIs

bigbluebutton-html5/imports/api/users/server/methods.js, bigbluebutton-html5/imports/api/users/server/methods/userLeftMeeting.js, bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
This PR fix user logout behavior, before the user logout creates a modal overlapping the client causing some side effects like users keeps in meeting and being able to hear YouTube shared video. This PR implements a new method to set user as 'loggedOut' and setting it offline.
closes #7198.
=> Log out user prior to Feedback (end all media streams)

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/service.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Closes #7279.
Selecting the fullscreen button on the presentation should no longer cause the error to be shown.
In Edge the error was  : `clientLogger: TypeError: Object doesn't support property or method 'requestFullscreen'`.
=> Fix refPresentationContainer requestFullscreen is not a function

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/utils/sdpUtils.js, bigbluebutton-html5/package.json, bigbluebutton-html5/public/compatibility/sip.js
* Built upon the work @capilkey had done on translating the audio SDPs on SIP.js. The problem here is that FreeSWITCH does not support Unified Plan yet and Safari is rolling out version where Plan B is completely disabled. This PR adds the capability to translate audio SDPs between both versions. Currently it's only restricted to Safari endpoints
* Added two new hacks to our SIP.js: 
- `hackPlanBUnifiedPlanTranslation`: enables the SDP translation. UA parameter.
- `hackAddAudioTransceiver`: there was some code inside SIP.js that we added to create `transceivers`
for Safari endpoints that ran inside WebView. It wasn't restricted to those, so along with `offerToReceiveAudio` it was duplicating audio streams in Chrome/Firefox/Edgium. Added the hack so we can control when it should be added …
=> Added Unified Plan <-> Plan B translation for Safari endpoints

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/modal/fullscreen/component.jsx, bigbluebutton-html5/imports/ui/components/modal/fullscreen/styles.scss, bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx, bigbluebutton-html5/private/locales/en.json
Makes the Join room button show that it opens a new window
Also fixes the modals all showing "Done" as their confirm label.
=> Add indication that join breakout room btn opens new window

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
There were a couple of regressions introduced in the last couple of days. The first was that the error code being set on logout was changed from 430 to 403 for some reason and that caused the UI to show a message saying that the user had been ejected when they hadn't. The other issue was that the network stats work added a line that removed an event listener on base unmount, but it didn't check to see if the object existed which resulted in a client crash on logout.
=> Fix HTML5 logout

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
Before it looked like this
and now it looks like this
I also found that long names of offline users were clipping like this
so now they look like this
=> Fix chat message name alignment

bigbluebutton-html5/imports/ui/components/external-video-player/service.js
Some YouTube URLs (playlists, embeds and videos with the time code in the URL) would not display correctly, this new regex fixes these cases and should work for every other format currently available. If there's more URL formats failing let me know!
=> Fix external video youtube regular expression

bigbluebutton-html5/imports/api/presentations/server/methods/setPresentation.js
Closes https://github.com/bigbluebutton/bigbluebutton/issues/7516
To test:
substitute
`return setPresentation(currentPresentation.id, podId);`
for
```return setPresentation(`${currentPresentation.id}______`, podId);```
in `presentation-uploader/service.js`
=> Handle incorrect presentationId passed from client

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu-item/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx
This PR allows the items on the whiteboard toolbar to be activated via they keyboard. Also fixes the screen reader not announcing the aria-label on the language select element in the application settings.
=> Make whiteboard toolbar accessible via keyboard

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
An SVG animation's repeatCount attribute needs to be greater than 0 or 'indefinite' and we were setting it to 0 which resulted in repeated warnings. This changes it to the expected value of 1 so it only runs once.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatCount
=> Fix repeatCount usage in SVG animations

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/utils/sdpUtils.js, bigbluebutton-html5/public/compatibility/sip.js
We've noticed some calls to FreeSWITCH are failing because the browsers are starting to add mDNS (*.local) candidates to the SDPs and they cause FS to choke. This PR adds a filter step to sip.js that removes any candidates that have ".local" in them.
=> Strip mDNS candidates from sip.js SDPs

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
The log that says that that some left the audio was lower priority than all of the other audio log levels.
=> Bump audio leave log level

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
I was looking through the logs sent by the client and all of the Kurento listen-only errors get turned into generic CONNECTION_ERRORs. The reason is supposed to be mapped to bridgeError which is supposed to mapped to cause in the log, but reason is almost always undefined. I looked through the client code and there are at least four different error formats that can be passed back to the onFail handler.
* Error with reason
* Error with id
* String
* Nothing
=> Try to improve Kurento listen-only error reporting

record-and-playback/core/lib/recordandplayback.rb
It used to print:
```
Failed to download file: undefined local variable or method `respose' for BigBlueButton:Module
Did you mean?  response
```
because the incorrect variable name was used in the error message.
There was no effect other than the message in the log, since the shared notes
couldn't be archived anyways, and the only thing the exception did was ...
prevent the shared notes from being archived.
=> RaP: Fix error message when shared notes could not be archived.

bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/lock-viewers/context/consumer.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/context.js, bigbluebutton-html5/imports/ui/components/lock-viewers/context/provider.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/withContext.jsx, bigbluebutton-html5/imports/ui/services/user/mapUser.js
This PR intend to add a context ([context Api](https://reactjs.org/docs/context.html)) to consolidate the lock settings data.
Problem:
Whenever we want to make sure that the lock settings are applied, we repeat the same step, take the meeting and the user, and compare `user.isLocked` && `meeting.lockSettingsProps.<Any lock>`, the idea of this context is inject lock data as props in wrapped component and simplify his verification and be able to access it data  regardless the deepness of component.
Way to use:
To use this context, simply import the container into `/imports/ui/components/lock-viewers/context/container.jsx` and encapsulate the target component, such as the context use a provider component, the children must be a component for work properly.
Any component deeper than the …
=> Add context to manage locksettings

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
This PR makes it possible to repeatedly click the "Randomly assign" button to reshuffle the viewers. It also fixes the randomizer so the number of users in each room will be the same.
Fixes #7388
=> Improve breakout room randomizer

bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
When a voice user comes in for the first time we try to determine if they're voice-only or not. If the user is voice-only we create a User set to 'dial-in-user' for them and then follow up with the creation of a real VoiceUser. As far as I can tell the cause of the issue is that when we create the User with type 'dial-in-user' the addUser code will also trigger the creation of a dummy VoiceUser. The final list of operations is then: dummy VoiceUser, dial-in User, real VoiceUser. It's likely a race condition with the creation of two VoiceUsers with the same ID so this PR removes the race by avoiding the creation of the dummy VoiceUser when the User is a 'dial-in-user'.
The original issue was spotty anyways and would only happen once out of a dozen tries for me, but I couldn't reproduce at …
=> Fix for voice-only users not appearing in the audio

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/private/config/settings.yml
Sibling: https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/33. The configs are optional, but the SFU PR must be on for them to have any effect.
Testing: fiddle with the settings parameters, check the bandwidth specs on the remote SDP on chrome://webrtc-internals (AS/TIAS fields).
PS.: accidentally commited a commented code removal on preview that was unneeded...
=> Add bitrate config options to cameraProfiles

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ConnectionController.groovy
Since the `authed` does not verify an user at server side, we need to remove this check so users that join as `guest=false` can establish websockets connections
=> Avoid checking for authentication

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx
This PR adds a corner triangle to the whiteboard toolbar buttons that have sub-menus so it's easier for the user to tell that there's something more there. It also sets the default tool back to the hand so there's less accidental drawing. I also found an issue with the functionality where you press the spacebar to pan. If you pressed and released Space while pan was selected it would change you to a different tool.
Fixes #7587
=> Set default tool to pan and add corner triangle

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/captions/reader-menu/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/captions/reader-menu/styles.scss, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/captions/writer-menu/component.jsx, bigbluebutton-html5/imports/ui/components/captions/writer-menu/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/private/locales/en.json
Closes #7586
Implements all the suggestions from @tylercopeland from 7586
Also sets the default thickness for whiteboard to 1
=> UI improvements to Closed Captions (part 2)

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss, bigbluebutton-html5/private/locales/en.json
Thinking a little bit more about #7603. Saw the reference of using `···` somewhere in Internet:
=> Refactored shared notes content notification

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
Update Browser Bunyan and enable `flushOnClose` for the `external` target (issue #6923).
=> flushOnClose option for Browser Bunyan

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
There was an exception thrown if you opened the modal before the default presentation had been converted. I've added an extra check to make sure the first presentation exists.
After this PR the modal will open, but it won't update when the default presentation finally converts because the presentations are being cached on modal open for some reason. I'm pretty sure that issue has been around for a long time though. The state of the confirm button is also very odd and inconsistent.
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/7666
=> Fix exception in presentation uploader

bigbluebutton-html5/client/main.jsx
The errors in the client were getting logged with the full stack trace as the message which meant that you couldn't group exceptions because the stack has the domain in it. This PR makes the log message just the error message which should allow for grouping and determining which errors happen more frequently. I also decided to strip "Uncaught" from the start of any messages because Chrome likes to add that on and it doesn't add anything in our case. The full stack will be available in the `stackTrace` parameter for viewing afterwards.
=> Change client error formatting

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
We have been encountering errors on demo:
```
Jun 24 12:49:24 demo.bigbluebutton.org systemd_start.sh[6224]: error: CLIENT LOG: TypeError: Cannot read property 'CONNECTION_ERROR' of undefined
Jun 24 12:49:24 demo.bigbluebutton.org systemd_start.sh[6224]:     at UA.h (https://demo.bigbluebutton.org/html5client/cbb07aeb6e882508c69f5f6639a9c987d13b0fb7.js?meteor_js_resource=true:125:1059312)
Jun 24 12:49:24 demo.bigbluebutton.org systemd_start.sh[6224]:     at UA.EventEmitter.emit (https://demo.bigbluebutton.org/html5client/compatibility/sip.js?v=553:112:17)
Jun 24 12:49:24 demo.bigbluebutton.org systemd_start.sh[6224]:     at UA.onTransportError (https://demo.bigbluebutton.org/html5client/compatibility/sip.js?v=553:9110:8) ...
```
because baseErrorCodes was not defined
=> baseErrorCodes not defined

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
Sometimes webcams would randomly drop 15s after being *correctly* shared. This was due to a race condition on how we set the auto reconnection timers which is currently anchored on local ICE candidates being generated. `handlePlayStart` clears reconnection timers, but sometimes browsers (mainly Firefox) generate new candidates even after the connection was properly established, so it'd re-set the reconnection timer because we weren't checking if the peer had already started.
So I added a check to assert that the peer hasn't started yet when setting the timers. Also made sure the peer is marked as started first thing on `handlePlayStart` (just to be sure).
This tackles the defunct https://github.com/bigbluebutton/bigbluebutton/issues/7518.
The exceptions being thrown on #7672 and #7673 …
=> Fix issue where webcam would randomly drop after starting properly

bigbluebutton-html5/imports/api/users/server/handlers/userJoined.js, bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/imports/ui/components/video-provider/many-users-notify/container.jsx
There was a new property mysteriously being checked for in #7606 when trying to add a new User. The new property was "moderator" which doesn't exist in the User data model in any other components. Adding this check broke a few other message handlers because they use the proper data model and didn't conform to the changes made in #7606. I rolled back the check and did proper data fetching to only user properties that should exist.
While doing this I discovered that any exceptions thrown during redis message handling were being caught and silenced so we had no way of detecting this regression until we noticed that functionality was broken. I changed the exception handling to always log as an error so we can detect these regressions much easier in the future.
Fixes #7697
=> Fix regression from #7606

bigbluebutton-html5/public/compatibility/kurento-utils.js
Addresses the error seen in
`"stackTrace":"TypeError: can't redefine non-configurable property \"userAgent\""`
Note, there are still definitions of `ua` in the code so ideally we need to extract this out.
=> Avoid re-defining userAgent in kurento-utils.js

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/handlers/changeRole.js, bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js, bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/api/users/server/modifiers/changePresenter.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/private/config/settings.yml
This PR builds on PR #7557 
There was a lot of weird stuff being done with user roles that didn't match how every other BBB component does roles. The biggest issue was "presenter" status being misinterpreted as role (which it definitely is not). There was also duplicate of the role value into two different properties that might or might not exist. These two problems caused a lot of confusion in the code with properties that sometimes existed and sometimes didn't and inefficiencies with extra data fetching that wasn't needed.
=> Clean up user roles

bigbluebutton-html5/imports/ui/components/audio/device-selector/component.jsx
Recent PR tried to fetch devices from props instead of state. This switches it back.
Fixed #7740
=> Fix audio input selector

bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js, bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js, bigbluebutton-html5/imports/startup/server/index.js
This PR contains fixes for three different server exceptions that I found in the logs. 
The first was an exception if no `extraInfo` parameter was included in a log. The second was an exception when a poll response was attempted, but no poll could be found. The third was an exception when /feeback was called, but the user couldn't be found.
=> Fix HTML5 server exceptions

bigbluebutton-html5/imports/api/meetings/server/modifiers/changeUserLock.js, bigbluebutton-html5/imports/api/ping-pong/server/methods/ping.js, bigbluebutton-html5/imports/api/video/server/modifiers/sharedWebcam.js, bigbluebutton-html5/imports/api/video/server/modifiers/unsharedWebcam.js
There were four instances where the Users collection could be upserted with partial User objects and it might have been resulting in invalid User objects getting to the client.
=> Change unsafe Users upserts to updates

bigbluebutton-html5/imports/ui/components/actions-bar/captions/reader-menu/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/captions/reader-menu/styles.scss, bigbluebutton-html5/imports/ui/components/captions/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
This PR fixes the accessibility issues reported for the live closed captions.
* Adds aria labels to input fields in closed caption modal.
* Assign the lang attribute to the parent container of the change of language.  (e.g., `<option lang="fr">Français</option>`)
* Makes the color picker display names instead of hex values on hover.
* Makes the screen reader announce the live captions.
=> Fix accessibility issues in closed captions

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/settings.yml
This PR adds a property in the settings to provide a way to override the locale used to load the client (was previously detected by the browser).
This came up in a forum thread
https://groups.google.com/forum/#!msg/bigbluebutton-setup/nqvVCYQF11w/6c3vkZ1KAgAJ
=> Add property in setting.yml to override default locale

bigbluebutton-html5/imports/ui/services/settings/index.js
To be revisited -- currently it causes issues with calling `makeCall` before Meteor is fully connected
// side note: do we need this value in the collection?
=> Skip saving viewParticipantsWebcams in collection

bigbluebutton-html5/private/config/settings.yml
Turns out `undefined` actually converts to a string instead of a `null` value. This was causing an issue because the check for the locale is expecting the string to either be a locale or not exist.
Closes #7776
=> Change overrideLocale default from undefined to null

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/RecordingController.groovy
Avoid casting content type to a CommonsMultipartFile object.
```
2019-07-17T14:21:11.755Z DEBUG o.b.w.c.RecordingController - RecordingController#putRecordingTextTrack
2019-07-17T14:21:11.818Z DEBUG o.b.w.c.RecordingController - Captions for recordID: 4180a696dccc0abae3594ba222e3a97d51301a65-1560279067558
2019-07-17T14:21:11.819Z INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=66494c9ceb83ac523878d4f6582b6620b7d9a512 length=40
2019-07-17T14:21:12.089Z DEBUG o.b.w.c.RecordingController - Captions kind: captions
2019-07-17T14:21:12.089Z DEBUG o.b.w.c.RecordingController - Captions lang: pt_BR
2019-07-17T14:21:12.090Z DEBUG o.b.w.c.RecordingController - Captions locale: pt-BR
2019-07-17T14:21:12.133Z ERROR StackTrace - Full Stack Trace: …
```
=> Fix on getting caption file content type

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/public/compatibility/kurento-extension.js
- Removed the custom `logFunc`/`modLogger` that overcomplicated things
- Refactored the kurento-extension.js script logs to actually mean something and be a bit less bulky when on `info` level, but more meaningful than it was before.
- Removed some leftover logs and added a TODO to create an error normalizer to that kurento-extension script so it's easier to handle the stuff it throws.
video-provider log review will come in a separate PR.
=> Refactor screenshare/listen only client-side logs

bigbluebutton-html5/imports/api/presentation-upload-token/server/handlers/presentationUploadTokenPass.js, bigbluebutton-html5/imports/api/presentation-upload-token/server/methods.js, bigbluebutton-html5/imports/api/presentation-upload-token/server/methods/setUsedToken.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
Issue causes: 
- The client does a location query to get the token, using the same parameters, that way when files with same name are uploaded the find returns the old token, instead of waiting for the message from the server.
Solution:
- I've added a `used` field which is set to true when the upload is started.
Closes #7519.
=> Fix same name files failing in upload.

bigbluebutton-html5/imports/ui/components/legacy/component.jsx
This PR fixes the legacy component not rendering the translated strings for supported locales. Previously it would only display correctly in English.
=> Fix locales not working in legacy component

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/public/compatibility/kurento-utils.js
Kind of addresses #7798 and #7693.
This does some shenanigans to bind media element `play` calls that failed to user actions (mouse clicks, key presses, screen touch). I added a listener on `window` for a new event called `mediaTagPlayFailed`. Tags that fail to `play` should emit it so that the failures can be handled.
With this, if an autoplay issue happen, the media will be successfully played on the next action the user does. There's no UI intrusion with this.
Media tags that I covered in this PR:
- Video
- Screenshare
- Listen only via SFU
It can cause some strangeness, though, to see stuff start working when you click something or go type in the chat. I suggest that someone more CSS-savvy builds upon this PR in the very near future by:
- Changing the `Media` component ` …
=> Yet another workaround for autoplay issues

bigbluebutton-html5/TRANSIFEX_PULL_INSTRUCTIONS.md
The HTML5 Transifex steps were in the docs, but the public can't pull the translations anyways so there's no point in having it in the docs.
=> Move Transifex instructions to the repo from docs

bigbluebutton-html5/imports/api/presentation-pods/server/utils/isPodPresenter.js, bigbluebutton-html5/imports/api/presentations/server/modifiers/addPresentation.js, bigbluebutton-html5/imports/api/slides/index.js, bigbluebutton-html5/imports/api/slides/server/helpers.js, bigbluebutton-html5/imports/api/slides/server/methods/switchSlide.js, bigbluebutton-html5/imports/api/slides/server/methods/zoomSlide.js, bigbluebutton-html5/imports/api/slides/server/modifiers/addSlide.js, bigbluebutton-html5/imports/api/slides/server/modifiers/addSlidePositions.js, bigbluebutton-html5/imports/api/slides/server/modifiers/changeCurrentSlide.js, bigbluebutton-html5/imports/api/slides/server/modifiers/clearSlides.js, bigbluebutton-html5/imports/api/slides/server/modifiers/clearSlidesPresentation.js, bigbluebutton-html5/imports/api/slides/server/modifiers/resizeSlide.js, bigbluebutton-html5/imports/api/slides/server/publishers.js, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/private/config/settings.yml
The slide position updates frequently when panning or zooming and it was causing the whole Slide record to be sent to every client multiple times per second. The Slide record is very heavy with a lot of text and it was very inefficient. This PR leaves the mostly static properties of the slide in Slide and creates a new collection for just the slide positions.
Normally when there's a new collection it needs a bunch of filler around and a separate directory for it in the file structure, but I chose to keep the new collection inside of the api/slides directory because creation and destruction is directly tied together. They're basically one collection, but are only split for performance reasons.
=> Move slide positions into their own collection

bigbluebutton-html5/imports/ui/components/chat/alert/audio-alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
If the user have audio alerts enabled in settings, the alert will play even if the user is in other tab or with the browser minimized. It uses [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API).
=> Send audo alert for new messages when in another tab or browser minimized

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
Addresses #6994.
Triggered if it fails during a successfully negotiated listen only session (for any reason). Tries to reconnect **once**. Reuses the beep warning and the reconnecting toast done in the client audio manager to notify the user it's trying to reconnect.
There's a 15s timer on the reconnection attempt in case the server is unresponsive for some reason.
=> Add auto-reconnect to SFU listen only (#6994)

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx
This PR protects against the case where there's no slide position (race condition, file deleted on the server). If the fallback is hit, the presentation area will look like the following.
Fixes #7873
=> Protect against no slide position

bigbluebutton-html5/imports/startup/server/logger.js
In order to actually set the log level in Winston it needs to be set in the logger and in the transport. We were only setting the log level in the transport so it was useless.
=> Fix HTML5 server logger initialization

bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/private/locales/en.json
Currently we only have a single message for when the chat message form is disabled, but when chat is locked it is showing the an incorrect reason.
=> Add hint in message form for when chat is locked

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
This PR fixes that errors
Race condition
```
Uncaught TypeError: targetClassname.includes is not a function
at WebcamDraggable.handleWebcamDragStop (component.jsx:168)
at Object.Draggable._this.onDragStop [as onStop] (modules.js?hash=0e5f549658b3f98d9d35f6eae2a01dd3458212ef:84094)
at HTMLDocument.DraggableCore._this.handleDragStop (modules.js?hash=0e5f549658b3f98d9d35f6eae2a01dd3458212ef:83793)
handleWebcamDragStop @ component.jsx:168
Draggable._this.onDragStop @ modules.js?hash=0e5f549658b3f98d9d35f6eae2a01dd3458212ef:84094
DraggableCore._this.handleDragStop @ modules.js?hash=0e5f549658b3f98d9d35f6eae2a01dd3458212ef:83793
```
> _happens when the client is presenter (has the bottom presentation toolbar) and resizes the screen in such a way that the presentation can't be viewed_
=> Fix log errors on webcam draggable

bigbluebutton-html5/imports/api/cursor/server/methods/publishCursorUpdate.js
The updates might get rejected by akka-apps if they're sent late, but the user won't get kicked for cursor updates so it's not major.
Fixes #7890
=> Allow negative cursor updates to publish

record-and-playback/core/lib/recordandplayback/events_archiver.rb
Found another case where the html5 client was passing through control
characters, in the original presentation name field.
Rather than play whack-a-mole with different fields which may eventually
get poorly sanitized user data, apply the control character filtering
to all properties.
Adjust the character range to do the following:
* Allow horizontal tab (0x09), it's not problematic.
* Disallow control characters in the range 0x1A-0x1F. Probably missed by accident.
=> Delete control characters from all recording event properties

bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
This PR ensures that you can zoom outside of the normal boundaries when using touch controls.
=> Add max and min zoom for mobile

bigbluebutton-html5/imports/ui/services/api/index.js
Changed up the string being logged to tell us specifically which call failed and made the log output correctly. I also had to put in a special case check so that there isn't a potential infinite loop of failed log attempts.
=> Improve the failed Meteor call log

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx
Audio alerts for chat are playing even when the user sended a message and when the user had the chat panel open.
- Join with 2 clients
- Enable **Audio Alerts for Chat** in Settings for one of them
- Start to send chat messages
If you open the chat list in the user with audio alerts enabled and start to send messages you will hear the alert
The above behavior will not happen anymore
=> Fix audio alerts for chat playing when they shouldn't

bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
The code was looking at the swap layout property only, but there's a second function that determines if a swap layout should be obeyed. This PR adds the check to the second function.
Fixes #7870
=> Show presentation and whiteboard controls after auto swap back

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss
Before this the user-list avatar was 30.8x32 and the chat avatar was 31.5x32. After this PR the user-list avatar is also 31.5x32.
=> Make user-list avatar the same width as chat avatar

bigbluebutton-html5/imports/api/users/server/handlers/emojiStatus.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx
The problem was caused by a wrong parameter being passed down to the function.
=> Fix Clear All status icons

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
This PR changes the code that tracks the initial connection to Meteor. We used to check the connection status every 200ms and this code changes it to use a Tracker which is much more responsive. I also added an exit case when the connection fails. We can also now track the time it took someone to connect in an easier manner and see how long people take on average.
I thought about adding a ~5s timeout also, but some people take 15s or more to connect so a timeout is difficult.
=> More responsive and less noisy initial connection watcher

bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
Found another pointless use of mapUser that brings in the voice data for no reason.
=> Remove pointless userMap in screenshare view

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/startTyping.js, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/container.jsx, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/private/config/settings.yml
This PR moves some props related to the users typing out of the chat and into the message-form container. Prevents `getPublicGroupMessages()` being re-run on every keystroke by anyone in the meeting.
=> Move props for typing indicator from chat to message-form

bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx
When microphone lock was activated the moderators couldn't join with microphone and the lock wasn't affecting attendees.
=> Fix microphone lock affecting moderators

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx
The problem was caused because the system messages don't have a sender.
=> Fix problem with clear chat when popup alerts are enabled

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
Previously the recording icon was made with CSS and it didn't always render well in all browsers. This PR changes the icon to be an SVG instead which seems to scale better from my tests.
Old:
New:
=> Use an SVG for the recording icon

bigbluebutton-html5/imports/ui/components/modal/fullscreen/styles.scss
This PR fixes the popout icon position / rotation in the confirm button of the join breakout room modal.
Closes #7734
=> Update join breakout room modal RTL style

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-modal/container.jsx
=> Fix join by phone icon placement in RTL

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Other client logs have started to attach extraInfo.error properties and they've been using Objects instead of the Strings that the audio failures use. This type mismatch causes log aggregators to throw a fit. I moved the audio error codes to a different property so they can be parsed again.
=> Change audio error code log property

bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This is a followup to #8030.
When the client tries to determine what actions are available for each row in the user list it was doing duplicate requests for that row's User and VoiceUser objects even though the information was already present in the component. I've changed the getAvailableActions() function use the information we already have.
I also found some bugs with the chat list. If there were private chats active with two users with the same name the sort would throw an exception. There was also an issue where if you closed the private chat it wouldn't hide it like intended and it also wouldn't restore it if a new message came in.
=> Fix duplicate user fetch and chat list bugs

bigbluebutton-config/cron.daily/bigbluebutton
The bbb-webrtc-sfu logs are getting rotated, but the old logs just accumulate. Add the directory to the bigbluebutton cron.daily so they get removed.
=> Cleanup old bbb-webrtc-sfu logs

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
The function that was handling errors thrown when retrieving a microphone wasn't working and the code would continue on an error. This lead to the issue being hidden farther into the code. It should be using a proper Promise rejection now.
I also added a log message with the cause so we can track how many times people have issues with their microphones and which specific cause they run into.
There's also a one line fix for a warning when the video preview modal was opened.
=> Fix microphone failure detection

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js
Fixes #8064 
The check for moderator was coming from the Service and was not going through a `withTracker` watcher, so the clearChat option would be hidden if the user role was changed or initially picked too early
=> Reliably check mod status for clearing chat

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/imports/utils/mediaElementPlayRetry.js, bigbluebutton-html5/public/compatibility/kurento-extension.js
- Fixes an issue with processing candidates before the remote SDP answer was set. This broke Safari on some cases. Video already had that code, so I ported it over to screenshare/listen only.
- Add retries to media element play as to try to make it more robust in case of random failures.
- Disable screenshare view autoplay and leave it only to manual JS play.
- Log improvements. Moved some stuff around to uniformize it and make it easier to correlate. ie:
```
Start/success ratio:
* SS presenter:
- kurentoextension_screenshare_request_start_presenter
- screenshare_presenter_start_success
* SS viewer
- kurentoextension_screenshare_request_start_viewer
- screenshare_viewer_media_play_success
* Listen only
- kurentoextension_listenonly_request_start
- listenonly_media_play_success
* Autoplay: …
```
=> Fixes to client-side screenshare/listen only code and log improvements

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ConnectionManager.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/DelayedCommandSenderService.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java
- FreeSWITCH core dumped and akka-fsesl managed to reconnect. However, commands (mute, unmute, record, etc.) to FS are not reaching FS.
But events (user joined, left, talking) from FS are received by akka-fsesl. Can't determine where the commands are falling off. These
extra logging hopefully helps us narrow down if this happens again.
I wasn't able to reproduce the issue when stopping and restarting FS. Akka-fsesl reconnects and command/events are flowing in both
directions.
=>  Add more logging

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
From https://github.com/marcominetti/node-memwatch
The `info object` will look something like:
```
{ 
start: Fri, 29 Jun 2012 14:12:13 GMT,
end: Fri, 29 Jun 2012 14:12:33 GMT,
growth: 67984,
reason: 'heap growth over 5 consecutive GCs (20s) - 11.67 mb/hr' 
}
```
The `stats` data will look something like this:
```
{
"num_full_gc": 17,
"num_inc_gc": 8,
"heap_compactions": 8,
"estimated_base": 2592568,
"current_base": 2592568,
"min": 2499912,
"max": 2592568,
"usage_trend": 0
}
```
=> Add monitor for memory usage in nodejs html5

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
This updates the character used for the arrow icon in the join audio modal. It should now be visible on iOS devices.
=> Update arrow character used in join audio modal

bigbluebutton-html5/imports/ui/components/breakout-room/service.js
We were too aggressive in our field pruning and remove information that was still needed.
Fixes #8094
=> Restore breakout name in invitation modal

record-and-playback/presentation/playback/presentation/2.0/acornmediaplayer/jquery.acornmediaplayer.js
This reverts a bbb-specific customization made in the jquery.acornmediaplayer.js
file: it's restored to what the upstream player did. I can't find any explanation
for why this change was made in the first place? Reverting it doesn't seem to
cause any playback issues (Popcorn still works, in particular).
=> Fix autoplay of deskshare video in presentation playback format

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/container.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/service.js
There was some code in actions-bar/component that toggled the presentation/video swap when there was no presentation and an external video or screenshare. This was there to ensure that having a video and no presentation would show a big webcam area (the 'swapped' version), but with external video or screenshare you would correctly see the media and the cameras. Unfortunately this caused race conditions with the autoSwap custom data parameters and 50% of the times the auto swap would not work.
So this attempts to fix the problems with swap and empty presentations while still keeping the autoSwap flag functional. I also think that it keeps the code more contained to the media component without the need of including implementaiton details in unrelated components.
=> Fix auto swap race condition

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/private/locales/en.json
This PR changes the webcam profiles to only use the bit rate for quality reduction. This means no more need for scanning the profiles to see which ones a device will match. I also added in surfacing of errors so that users aren't just show an empty list of webcams when there's a problem. There's also simple view states now so that users aren't shown an empty list of webcams before media has been allowed.
There's also a shot at trying to default to the front-facing camera on mobile devices. I think it should work on Android, but I'm not 100% sure that Safari will obey it.
=> Bitrate only webcam profiles and error handling

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/meeting/DestroyMeetingSysCmdMsgHdlr.scala, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/CheckIfConfIsRunningCommand.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/ForceEjectUserCommand.java
We are seeing issue where voice recording continues after the meeting ends resulting in very large wav files.
The reason is that when we eject the users from the voice conference when the meeting ends, some users are not ejected. Somehow, freeswitch cannot find the userid even if listing the conference users shows the user.
To fix:
We try to stop the recording then the meeting ends by sending a stop recording command to freeswitch.
If the users cannot be ejected using the "kick all" command, we kill the channel instead by using "uuid_kill" command.
=> Stop voice conf recording when meeting ends

bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
This PR adds the number of the breakout room to the tab title. With this change it will be easier to differentiate breakout room tabs when multiple are open at the same time.
=> Add the breakout number to the tab title

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/arc-player.jsx
As far as I know I would try to access the null player because autoplay blocks the player from loading. With these checks everything seems to work until the user clicks on the Instructure Player, on which point the sync starts working.
=> A few more checks to prevent errors with the Arc Player

bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx
Making screensharing work on Safari 13 needs more time and testing since it involves moving some sensitive code around, so we're just disabling it for the next beta release.
Temporarily addresses #8142.
=> Remove screensharing option from Safari by UA checks (#8142)

bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx, bigbluebutton-html5/imports/ui/components/switch/component.jsx, bigbluebutton-html5/imports/ui/components/switch/styles.scss
This PR inverts the colours of the lock settings toggles so that unchecked is green and checked is red.
=> Invert toggle colours in the lock settings

record-and-playback/presentation/playback/presentation/2.0/lib/writing.js, record-and-playback/presentation/playback/presentation/2.0/playback.js
If the secondary media loaded before the main media, it would run the
"setMediaSync" function before the main media player was setup. As a
side-effect of setting up the main media player, all of the event handlers
added by the setMediaSync function are detached, and so the secondary
media never starts playing.
Move the call to setMediaSync to after the media-ready events for all
media have fired, so that it can reliably attach the event handlers.
=> Fix deskshare media sync when deskshare loads before webcam/audio

bigbluebutton-html5/imports/startup/server/index.js
The value in settings is `heapdump.enabled: true`, but the code was doing a truthy check on just `heapdump` so it was always enabled if memwatch.stats was enabled.
=> Fix check for heapdump enabled

bigbluebutton-html5/imports/ui/components/video-preview/styles.scss
With a 16:9 webcam and a small screen, the webcam preview video could overflow into the select boxes. I've added a width limiter to avoid the problem.
I also adjusted the spacing a little.
=> Limit width of the webcam preview video

record-and-playback/presentation/playback/presentation/2.0/playback.js
Previously the setMediaSync function was only called after the deskshare
loaded, but by moving it to run after all media loaded, it now runs even
on recordings that didn't have deskshare. Make it do nothing (return early)
in that case.
=> presentation playback: Make setMediaSync a no-op if there's no deskshare

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ConnectionManager.java
- on auto-reconnect when FS restarts, the auto-reconnect add another
listener to the ESL client resulting in multiple handlers of ESL events
and multiple messages to akka-apps. This resulted in multiple recordings
of audio when the first user joins as akka-apps receives 2 user join events.
=>  Have only one ESL listener

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ConnectionManager.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/CheckIfConfIsRunningCommand.java
- when meeting ends, we try to eject all users by force from freeswitch to make sure
that recording ends. However, we are not actually sending the command to freeswitch.
This change sends the command so that users can be kicked out.
=>  Eject users by force from FreeSWITCH

bigbluebutton-html5/package.json
This allows to run meteor in dev mode using the optimized mongo db from packaging instead of embeded meteor mongodb.
Usage: ``` npm run-script start:dev-fast-mongo```
=> Add script to start meteor using external mongo (from packaging) 

akka-bbb-apps/.gitignore, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/MeetingStatus2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-fsesl/.gitignore, akka-bbb-fsesl/run-dev.sh, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/FreeswitchConferenceEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/IVoiceConferenceService.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/events/VoiceConfRunningAndRecordingEvent.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/CheckIfConfIsRunningCommand.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/ConferenceCheckRecordCommand.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/response/XMLResponseConferenceListParser.java, akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/RxJsonMsgDeserializer.scala, akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/RxJsonMsgHdlrActor.scala, akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/VoiceConferenceService.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
- We had an issue where FreeSWITCH, for some unknow reason, stopped recording the voice conference
in the middle of the meeting while there are users in the voice conference. We've relied on the
voice conf started event to trigger recording of wav files. This event is sent when the first user
joins the voice conference. In this case, there was no voice user joined after the recording stopped
as there were already users in the voice conference. TO make sure that the audio is recorded, akka-apps
will send a "check if voice conf is running and recording" message to FreeSWITCH every 30sec. If akka-apps
receives a "running=true recording=false" response from FreeSWITCH, akka-apps will send a start recording
msg to FreeSWITCH.
=>  Make sure we record audio if meeting is recorded

record-and-playback/presentation/playback/presentation/2.0/lib/writing.js
Someone on the mailing list had some recordings which were using the 2.0
playback, but were missing the deskshare.xml file (which should always
be present for 2.0… strange). It's safe to continue loading the recording
playback if the deskshare.xml file is not found, the recording will just act
as if there were no deskshare start/stop events.
=> Make presentation playback continue if deskshare.xml was not found

bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/CoreMsgs.scala, bigbluebutton-html5/imports/startup/server/redis.js
Adding a new timestamp field on message so we can collect stats on message processing times.
Should be merged together with https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/38
=> Add timestamp on msg envelope

record-and-playback/core/lib/recordandplayback/events_archiver.rb, record-and-playback/core/scripts/archive/archive.rb
The wav files from the freeswitch recordings are huge, uncompressed.
There's no reason to keep them as wav, we can compress them in the
archive step.
=> recording archive: Compress audio files

bigbluebutton-html5/imports/api/external-videos/index.js, bigbluebutton-html5/imports/api/external-videos/server/index.js, bigbluebutton-html5/imports/api/external-videos/server/methods.js, bigbluebutton-html5/imports/api/external-videos/server/methods/destroyExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js, bigbluebutton-html5/imports/api/meetings/server/handlers/meetingDestruction.js, bigbluebutton-html5/imports/ui/components/external-video-player/service.js
By creating a different server instance of the streamer once for every meeting. Still trying to determine if the streamers are collected automatically when the objetcts are collected or if I should do something to clear them when the meeting ends.
=> Fix multiple external videos synced to different meetings

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/container.jsx
The request to get a join URL for the initial breakout room was being done in a Tracker when in freeJoin mode. It lead to a flood of messages and potentially taking down the whole server if there were enough people in the meeting.
Fixes #8234
=> Only request a breakout join URL once

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/cursor-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/pencil-draw-listener/component.jsx
Just trying to reduce the frequency of updates of some potentially problematic areas. Both the cursor and the annotations update quite frequently and often the browser and computer can't keep up. This PR slightly increases the throttle of the cursor updates and adds a three point buffer of pencil updates.
=> Throttle the pencil updates and increase cursor throttle

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/compatibility/sip.js
Adds an option to attempt the reconnecting WebRTC audio call using relay candidates only. Most of our failed audio calls are ICE negotiation failures after the call has initially been connected. Hopefully this will force the use of the TURN server on the reconnect and in turn force TCP.
=> Add option to reconnect audio with relay only

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
The quick poll and cc button should both render horizontally instead of vertically now
Closes #8257
=> Fix quick poll / cc button rendering vertically

bigbluebutton-html5/private/locales/en.json
The message used for this string provided misleading information to the user, giving the impression that a poll would end if the panel is no longer open. However, polls do remain active if the panel is not visible due to the use of the hide panel button.
=> Update active poll panel description message string

bigbluebutton-html5/private/config/settings.yml
#8258 was supposed to have that config option as `false` by default (TURN is an optional setup step so we can't force it).
=> Default config relayOnlyOnReconnect set to false (follow-up to #8258)

record-and-playback/screenshare/scripts/screenshare.yml
Add an example to enable generating an mp4 file (Apple device compatibility)
Switch the webm generation to use the faster single-pass encode by default,
since 2-pass is much slower and more cpu intensive.
Fixes #8253
=> Update the configuration examples for screenshare recording processing

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PdfConversionInvalidErrorSysPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodHdlrs.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationPodsMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/presentation/ConversionMessageConstants.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/BigPdfException.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/messages/PdfConversionInvalid.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, bigbluebutton-html5/imports/api/presentations/server/eventHandlers.js, bigbluebutton-html5/imports/api/presentations/server/handlers/presentationConversionUpdate.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/private/locales/en.json, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
**The problem:** In some cases a user uploads a PDF that generated blank pages. The issue we found is that sometimes a PDF page conversion times out.
**The solution:** If a PDF size is 10MB+, we extract the pages one by one and check that it has no page exceeds 8MB+. If a page has 8MB+ size, the PDF is marked as big and would not be converted. The client then asks the user to compress/optimize the uploaded PDF before uploading it again.
=> Detect big PDF files and check the page size

bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss, bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
Reverts bigbluebutton/bigbluebutton#7859
When testing further in a larger meeting noticed:
* in some cases we cannot view webcams until we minimize the presentation
* in some cases switching between tabs causes the webcams to disappear
* in some cases the view for presenter and viewer differs when 2 webcams running
Got to do some more cleanup. The resizing part seems fine but these regressions are disruptive
=> Revert "Webcams area resizable"

bigbluebutton-html5/private/locales/en.json
Tell user to split file when uploaded file is too big (size) or too many pages.
Fixes issue https://github.com/bigbluebutton/bigbluebutton/issues/8272
=> Change message when uploaded file is too large

bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/imports/utils/safari-webrtc.js
This tackles an issue for some browsers that, if no gUM permission was granted beforehand, won't generate any other candidates other than mDNS obfuscated ones. Since our prflx candidates handling seems to be lacking something and the browsers won't generate `srflx` or `relay` candidates for some reason, the workaround is to detect that and request gUM permission for microphone (best chance of gUM working).
Also in this PR:
- Moved video-provider gUM fallback detection to be used only on recvonly streams.
- Added the gUM fallback for screenshare recvonly streams.
- Removed the UA checks for the gUM fallback. All browsers will pass through it now.
- Added some client logging for those cases.
- Fixed some linter warnings in `safari-webrtc.js`
=> Account for mDNS candidates on gUM fallback for recvonly peers

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
- We want to be able to correlate client webrtc calls with freeswitch logs. We add extra info
on callerid which we strip out in akka-fsesl.
NOTE:
Client needs to be modified to add the info. This PR handles both callerid (with and without) formats so can be safely merged without waiting for the client changes.
=>  Track client's webrtc call session

bigbluebutton-html5/imports/startup/client/logger.js, bigbluebutton-html5/private/config/settings.yml
```[
{
"name": "clientLogger",
"level": 30,
"logCode": "sip_js_ice_connection_success",
"extraInfo": {
"currentState": "connected"
},
"levelName": "info",
"msg": "ICE connection success. Current state - connected",
"time": "2019-11-14T23:05:40.287Z",
"src": "MediaHandler.handleConnectionCompleted (https://anton.blindside-dev.com/html5client/app/app.js?hash=f6a7273f42c82fb36b7ef223643ecb40491434ed:56882:16)",
"v": 1,
"userInfo": {
"sessionToken": "j021unnpdmyjbrk1",
"meetingId": "183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1573669656655",
"requesterUserId": "w_9tmtmlk0bjqt",
"fullname": "ee",
"confname": "Demo Meeting",
"externUserID": "w_9tmtmlk0bjqt",
"uniqueClientSession": "j021unnpdmyjbrk1-l582as"
},
"clientBuild": "HTML5_CLIENT_VERSION",
"logTag": "log-from-server-group-003",
"url": …
```
=> Allow for logTag parameter in settings.yml

bigbluebutton-html5/imports/ui/components/video-preview/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx
This PR Removes the skip video preview from video button and just enble if auto share flag is true.
=> Don't skip video preview if called via interface

bigbluebutton-config/bin/bbb-record
Users don't expect not-recorded meetings to appear when rebuilding
all of their existing recordings.
You can still use bbb-record --rebuild on a single not-recorded
meeting to force it to process.
Fixes #6394
=> bbb-record: Skip ".norecord" meetings when running --rebuildall

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Before:
After:
Requested by @ritzalam
=> Replaced "Audio Error" with a template literal of the error

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala
When meteor requests for meeting information from akka-apps, no reply is given when there are no meetings running. Send reply to get meeting request when there are no meeting running.
=> Synching of meetings between meteor and akka-apps

bigbluebutton-html5/imports/ui/components/button/component.jsx, bigbluebutton-html5/imports/ui/components/fullscreen-button/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx, bigbluebutton-html5/imports/ui/components/tooltip/bbbtip.css, bigbluebutton-html5/imports/ui/components/tooltip/component.jsx, bigbluebutton-html5/package.json
Fixes the issue with tool tips not displaying correctly. Also adds a tool-tip for muting users in the talking indicator (only visible to moderators)
=> Fix tool-tips after tippy.js update to 5.1.1

akka-bbb-apps/src/main/scala/org/bigbluebutton/LockSettingsUtil.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeLockSettingsInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LockUserInMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserTalkingInVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala
All of the paths to check for users joining, unmuting, and talking
If microphones are locked:
[x] 1. Mute users on join if they aren't Moderator
[x] 2. When an unmute comes back from FS check to see if it’s allowed or not and mute them again as necessary
[x] 3. Check that unmutes originating from locked users are disallowed
Already handled
[x] 4. When mic lock settings changes enforce the lock on non-moderators on the server-side (send the events to FS to lock the users)
In all cases:
[x] 5. Check if the user is identified as listen-only and mute them if they are
[x] 6. Check the talking events from FS to see if a talking is coming in from a listen-only user and re-mute as necessary
=> Enforce lock settings on server

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/breakpoints.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/typography.scss
This pr will prevent the whos talking indicator from being in a state where can be overlapped by the whiteboard or webcams.
=> Fix elements overlapping whos talking

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.scss
=> Reduce size of mic icon in talking indicator

bigbluebutton-config/bin/bbb-conf
Switch to using curl instead, which doesn't have this problem (and outputs to stdout by default, too)
=> Fix 'wget-log' issue in bbb-conf

bigbluebutton-html5/imports/api/screenshare/server/handlers/screenshareStarted.js, bigbluebutton-html5/imports/api/users/server/modifiers/changePresenter.js, bigbluebutton-html5/imports/ui/components/screenshare/service.js
* If presenter changes during external video sharing (YouTube, etc), stop the video
* If screenshare starts while external video is being shared, stop the video.
* If external video is shared while screensharing, stop screensharing
Closes #7334
=> Prevent parallel screenshare and external-video

bigbluebutton-config/bin/bbb-conf
The compressed fs logs are about 50 MB for 1 GB.
=> Store FreeSwitch logs in bbb-conf --zip.

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Keeping these packages causes issues in development mode but not in production mode (these are all devDependencies)
Need to update them (re-add them) once they are compatible with node12 (fibers 4.x more specifically)
=> webdriver* and wdio* packages are not node12 ready

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
Cont'd from #8386 
Before:
`2020-01-09T15:50:49.859Z ERROR o.b.c.p.s.ReceivedJsonMsgHandlerActor - Cannot route envelope name GetRunningMeetingsReqMsg`
After:
```
2020-01-09T15:57:44.970Z INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"GetRunningMeetingsReqMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1578585464967},"core":{"header":{"name":"GetRunningMeetingsReqMsg"},"body":{"requesterId":"nodeJSapp"}}}
2020-01-09T15:57:44.971Z INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"GetRunningMeetingsRespMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1578585464970},"core":{"header":{"name":"GetRunningMeetingsRespMsg"},"body":{"meetings":["1ebc36f58d48e60778e021173a69fb6326154fbd-1578585441601"]}}}
```
=> Add handling route for GetRunningMeetingsReqMsg

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/startup/client/base.jsx
The server already requests that FreeSWITCH end a user's audio call if they're kicked, but the client was handling that as an unexpected disconnect and trying to reconnect. Most of the work was to ensure that the client stops trying to rejoin. There's one line change in base.jsx that restores the original look of meeting eject experience.
=> Make the client end the call when kicked

record-and-playback/core/scripts/utils/gen_poll_svg, record-and-playback/presentation/scripts/publish/presentation.rb, record-and-playback/pyproject.toml
Write a tool that generates the poll svg images directly from the
BBB poll description. This avoids the issues with special characters
in the gnuplot labels, and gives us a lot more flexibility in how
the polls are formatted and styled.
Note: the ubuntu packages `python3 python3-attr python3-cairo python3-gi gir1.2-pango-1.0` should be added as dependencies of bbb-record-core if they're not already present.
=> presentation recording: generate poll svg images without gnuplot

record-and-playback/presentation/scripts/publish/presentation.rb
If the poll size happened to be not an integer, the poll generation would fail.
Round it to an integer for the generation tool.
=> recording presentation format: round poll sizes to integers

bigbluebutton-html5/imports/ui/components/cursor/service.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/services/auth/index.js, bigbluebutton-html5/private/config/settings.yml
The problem was caused when meteor restarted without reloading the page, the ddp subscription called a `onStop` event that set all handlers to `undefined` after we set the handlers on the streamer init function.
=> Fix streamer not working on meteor restart

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss, bigbluebutton-html5/private/config/settings.yml
Adds `allowDownloadable` prop to presentation config of `settings.yml` which enables/disables the download option in the Upload presentation dialog.
Closes #8449
=> Add config to show download option in the Upload presentation dialog

bigbluebutton-html5/imports/api/annotations/addAnnotation.js
This PR allows a whiteboard user to create text-area's by clicking on the whiteboard while the text tool is selected.
=> Create text area's by clicking on whiteboard (text tool selected)

bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js
I added the meetingId to the external video sync log and also increased the level to info because we need to be able to track this at the default log level.
=> Add the meetingId to the external video sync update logs

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx
Following the specification for `getScreenCTM` firefox returns null for the svg out of the screen, but it doesn't comply with the other browsers behavior.
https://bugzilla.mozilla.org/show_bug.cgi?id=1446011
Closes #8439.
=> Workaround to CTM request in svg out of the screen

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
This PR allows the presenter to switch the current presentation via the actions drop down menu, instead of having to open the upload modal.
=> Add ability to switch presentations via actions menu (Presenter)

record-and-playback/core/Rakefile
I moved the location of the worker classes around, but forgot to update
the Rakefile to include them from the new location.
=> rap: Fix require paths in Rakefile

bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/invitation/container.jsx
This PR implements a design behavior that is not to show the  breakout invitation modal to moderator, it is expected that the moderator will use the side menu to join the breakout room.
=> Add a rule to don't show breakout invitation modal to moderators

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/GuestsApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/guests/GuestWaitingLeftMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/GuestsMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/RegisteredUser.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/java/org/bigbluebutton/web/services/WaitingGuestCleanupTimerTask.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, bigbluebutton-html5/imports/api/guest-users/server/eventHandlers.js, bigbluebutton-html5/imports/api/guest-users/server/handlers/guestWaitingLeft.js, bigbluebutton-html5/imports/api/guest-users/server/modifiers/removeGuest.js, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fixes #8203 .
This includes in `bbb-web` a monitor for the guests that are polling for their status.
- If the waiting guest doesn't make a poll to the server for 15 seconds (guest page default is 5 seconds), `bbb-web` removes his registered user and sends a `GuestWaitingLeftMsg` to `akka-apps`.
- `akka-apps` removes the user from the waiting guest list and from the registered users list and sends a `GuestWaitingLeftEvtMsg` for the clients to update.
=> Removes waiting guests that stop polling for their status

bigbluebutton-html5/private/config/settings.yml
This PR updates the minimum browser version requirements to run the html5 client. I based this update on the following browser features used by the client: `Network Information`, `Page Visibility`, `WebSocket`, `MediaDevices` and `WebRTC`.
Closes #8521.
=> set new minimum browsers versions to run html5 client

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
The peer object was being fetched only once in the ICE candidate callback and it would, sometimes, fetch a placeholder empty object which would be kept in the callback closure till the end of the peer lifecycle. With that, the didSDPAnswered state variable which controls the outbound ICE queue wouldn't be correctly read and the queue would never be flushed
=> Fix race condition in video-provider that may cause peers to fail

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
From #8580:
> The peer object was being fetched only once in the ICE candidate callback and it would, sometimes, fetch a placeholder empty object which would be kept in the callback closure till the end of the peer lifecycle. 
> With that, the didSDPAnswered state variable which controls the outbound ICE queue wouldn't be correctly read and the queue would never be flushed.
=> 2.3 equivalent of #8580

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java, bbb-fsesl-client/src/main/java/org/freeswitch/esl/client/inbound/InboundClientHandler.java, bbb-fsesl-client/src/main/java/org/freeswitch/esl/client/internal/AbstractEslClientHandler.java
When waiting for a response from FS after sending an ESL command and the ESL connection disconnects, the sending thread will be blocked as the trigger for it to unblock is the response from FS which never comes.
Add a 30 second timeout waiting for response and give up to go send a new FS ESL command.
=>  Add timeout waiting for response from FreeSWITCH when sending ESL command

record-and-playback/core/lib/recordandplayback.rb, record-and-playback/core/lib/recordandplayback/workers/archive_worker.rb, record-and-playback/core/lib/recordandplayback/workers/captions_worker.rb, record-and-playback/core/lib/recordandplayback/workers/events_worker.rb, record-and-playback/core/lib/recordandplayback/workers/process_worker.rb, record-and-playback/core/lib/recordandplayback/workers/publish_worker.rb, record-and-playback/core/lib/recordandplayback/workers/sanity_worker.rb, record-and-playback/core/scripts/rap-starter.rb
Was pointing to the wrong directory when loading the ruby scripts. Also made the directory easier to configure, it's all in a single place now.
=> Fix the paths to the ruby scripts on the rap workers

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- add check if the meeting that ended isn't a breakout room and if there is an end-meeting-callback-url.
=>  Breakout rooms shouldn't call the end meeting callback url

bigbluebutton-html5/private/config/settings.yml
The original value of 30s was leading to people getting removed from meetings if they missed one ping. Setting it to three minutes should cut down drastically on the chance of a false positive happening.
=> Increase the pingpong removal timeout to reduce false positives

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceConfCallStateEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/FreeswitchConferenceEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/IVoiceConferenceService.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/events/FreeswitchStatusReplyEvent.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/events/VoiceCallStateEvent.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ConnectionManager.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/CheckFreeswitchStatusCommand.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/GetUsersStatusCommand.java, akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/VoiceConferenceService.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala, bbb-fsesl-client/src/main/java/org/freeswitch/esl/client/inbound/Client.java
Currently, we user DTMF to inform the client when the call session is in echo test and when entering the voice conference.
Unfortunately, sometimes when FS sends the DTMF, FS crashes.
Monitor the progress of the call session using ESL events and propagate to the client.
The client would be informed of these call states: CALL_STARTED, IN_ECHO_TEST, IN_CONFERENCE, CALL_ENDED.
These are the new messages sent by akka-apps. The client should handle these events.
```
{"envelope":{"name":"VoiceCallStateEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1580941054957","userId":"75998"},"timestamp":1580941069614},"core":{"header":{"name":"VoiceCallStateEvtMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1580941054957","userId":"75998" …
```
=>  Track call session state

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
This PR fix the welcome message being clipped, it happens because messages containing html styles (e.g: `<b/>`,`<h1>`) could increase the text font after the 
cell measurer run, what this PR does is remove the [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) and add a parser the converts the text in a element and use a callback to call the measure a few moments after the render.
Closes #8530.
=> Fix bottom clip in first chat message

bbb-common-web/src/main/java/org/bigbluebutton/presentation/DocumentConversionServiceImp.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/OfficeToPdfConversionSuccessFilter.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java
Send message when office to pdf conversion failed.
When converting an office doc to pdf fails, the client displays the message "Ops, something went wrong" which isn't helpful.
Send message to client why office to pdf conversion failed. And it looks like it is already handled in ```imports/api/presentations/server/handlers/presentationConversionUpdate.js```. Just need to modify the client to display an appropriate message like "Failed to convert office document. Please upload a pdf instead."
This PR sends a message when pre-check of office doc fails and when libreoffice fails to convert the document.
=> Office to PDF conversion failed message

bigbluebutton-html5/.meteor/packages, bigbluebutton-html5/.meteor/versions, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/server/main.js
We use RocketChat/meteor-stream (for the cursor, etc) and it had a dependency of an old lodash version (with a vulnerability). This pull request removes the lodash Atmosphere package and uses a trick to replace its use with the npm package lodash.
I also removed the Atmosphere jquery package because it seems to be outdated (with vulnerability) and I am not seeing how/where it is used. jQuery is mentioned in kurento-utils.js but all functionality seems intact after removing it.
In addition it turned out that webcams display was implicitly relying on lodash without importing _ so the client broke when I removed the Atmosphere package. I added an explicit import to point to lodash._
=> Remove some atmosphere packages

bigbluebutton-html5/imports/ui/components/dropdown/list/title/component.jsx, bigbluebutton-html5/imports/utils/fetchStunTurnServers.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Cont'd from #8667 
On these spots we were relying on the meteor lodash package, now removed. Use the npm lodash package instead via import.
=> Explicitly import lodash where it is used

bigbluebutton-html5/.babelrc, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
This PR removes `babel-plugin-react-remove-properties` package. It allows the HTML5 client to have `data-test` attributes in production.
=> Keep data-test attributes in production

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/api/voice-call-states/index.js, bigbluebutton-html5/imports/api/voice-call-states/server/eventHandlers.js, bigbluebutton-html5/imports/api/voice-call-states/server/handlers/voiceCallStateEvent.js, bigbluebutton-html5/imports/api/voice-call-states/server/index.js, bigbluebutton-html5/imports/api/voice-call-states/server/modifiers/clearVoiceCallStates.js, bigbluebutton-html5/imports/api/voice-call-states/server/publishers.js, bigbluebutton-html5/imports/api/voice-call-states/utils/callStates.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/server/main.js
Currently we send DTMFs from FreeSWITCH to the client to notify about updates to the call (in echo test and transfer succeeded). Unfortunately if the websocket to the client disconnects and reconnects FS doesn't handle it well and will crash when trying to send the DTMF to the client. This PR implements the client changes to match the work done in #8607.
Fixes #8616
=> Use internal messages for call state instead of DTMF

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss
=> Fix user-list item text-overflow

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/public/compatibility/sip.js
In some cases the audio element won't completely follow through with playing a WebRTC stream for some reason. At the moment this happens the most with iOS Safari users. This PR attempts to detect when this failure happens and as a fallback plays the audio through an AudioContext.
I've also added a few log messages to know when this happens and to know when we get normal autoplay failures with the AudioElement.
This should hopefully address #8133, but we need confirmation.
=> Implement WebAudio fallback

record-and-playback/core/Gemfile.lock
Bump nokogiri for CVE-2020-7595
=> Bump nokogiri

bigbluebutton-html5/imports/api/external-videos/server/methods.js, bigbluebutton-html5/imports/api/external-videos/server/methods/emitExternalVideoEvent.js, bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/service.js
* Using less call to mongodb by moving presenter check code outside of the streamer callback. This meant it was called once per user per message, now it's only called once per message. Code can handle more messages per second now.
* Sending a timestamp together with playerUpdate messages. This allows us to sync the videos better if the message arrives a little late or ignore the messages if they arrive very late (which would cause skipping)
* Fix stopWatchingExternalVideo to use the correct credentials and make it work again (edit: added one more commit as per Anton's comments)
* New throttling logic for pausing/unpausing the video. This make it impossible for the presenter to generate a high number of useless start/stop messages by simply holding the space bar or clicking very fast
=> More enhancements to the external video code

bigbluebutton-html5/imports/api/external-videos/server/methods/emitExternalVideoEvent.js
The function was trying to get the `userId` property from extractCredentials when it's actually named `requesterUserId`
=> Fix external video extractCredentials usage

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/api/voice-users/server/methods/listenOnlyToggle.js, bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js
There were some collection finds that weren't including the meetingId in the selector which could rarely result in a collision because userId is only unique to a meeting.
=> Harden some server-side collection selectors

bigbluebutton-config/bin/bbb-conf
Due to a change in the Kurento packages naming convention, gstreamer packages don't naturally upgrade. This snippet checks if the installed gstreamer packages are the same as the one available in the repository. If they are not, it will update (possibly downgrade).
=> Force update gstreamer packages

bigbluebutton-config/bin/bbb-conf
The snippet to update gstreamer dependencies was only being triggered by --restart, now it's going to be triggered by --clean and --setip as well.
=> Additional modifications to #8715

bigbluebutton-html5/client/main.html, bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/package.json
Adds clarification regarding the license of the HTML5 client
Initially I added the text to [almost] all source files in the client in https://github.com/antobinary/bigbluebutton/commit/15f4efe4223b9a6784c70344c8bbcf38b83a51d3 but the issue is that when minimizing the code, these lines are kept, so the resulting client files to be served (js and css) are ~500KB larger.
=> Add license and copyright info for HTML5 client

bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/userTyping.js, bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js
Started digging into the chat panel management because the "who's typing" indicator isn't showing in RC6 and discovered a lot of inconsistencies with how the open chat was being intialized, used, and then destroyed.
When it is first opened the Session variable idChatOpen is set to '' and there are a bunch of places in the code that look for a truthy value and if it's falsey then the code defaults to that meaning the public chat is open. This leads approach leads to problems because it doesn't fix the core problem of why the idChatOpen isn't set correctly and it means that everywhere that gets idChatOpen needs to have the exactly same fallback.
The second problem I found is when the chat panel closes the ChatContainer is re-rendered multiple times while idChatOpen is set to '' which means …
=> Fix idChatOpen Session usage

bigbluebutton-html5/public/compatibility/kurento-extension.js
2.2 backport of #8710.
```
Tracks the listen only WebRTC PC ICE connection state. On transition to failure states:
- Log the error
- Trigger a reconnect
```
=> Track listen only ICE connection state to trigger reconnections

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/private/locales/en.json
The minimum length warning for a chat message will flicker and shift every time you press enter with an empty input box. Every other application that I checked that had chat just did nothing when I tried to send an empty message.
=> Remove the minMessageLength warning from chat

bigbluebutton-html5/imports/ui/components/app/styles.scss
The styling of the webcam containers sets z-index for them, but nothing higher up in the DOM uses properties that create a new stacking context so the webcams are being placed on top of everything in the client in certain scenarios.
The easiest way to reproduce is to load the client in Firefox, close the chat, share your webcam, and then click the gear icon above the users list. You will be able to interact with the rows that are in line with the presentation area, but any that are in line with the webcams you won't be able to interact with.
This PR sets the z-index on the media container to `0` which tells the browser to create a new stacking context. This means that nothing inside of the media container can escape the stacking order of the container.
=> Force a stacking context to be created for the media container

bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/WebRTCCallManager.as, bigbluebutton-client/src/org/bigbluebutton/util/browser/BrowserCheck.as
People use Puffin Browser only when they are on a mobile device and have to use
BBB flash client. They cannot use a browser with WebRTC support,
in our case, we in Dumalogiya temporarily disabled HTML5 version
due to problems with sharing webcams across HTML5 and Flash clients and we are
not ready to fully migrate to HTML5 client because it e.g. lacks support
of changing window layouts. So, we want to avoid showing this warning in Puffin Browser.
P.S. I did not try to build Flash client after this change. Hope it builds. It's difficult to do because building and deploying of BBB is not automated and debian specs are not published.
=> Don't recommend Firefox or Chrome for WebRTC when Puffin is being used

bigbluebutton-html5/imports/ui/components/video-provider/service.js
When the client is loaded over HTTP the WebRTC methods aren't available and the client crashes to blue. This PR adds a check before trying to fetch the webcams that resolves the problem and lets the client load.
Actual change is line 43-50, the other changes are automatic linting changes.
=> Fix client crash when client is unsecured

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
The action button render can run before the presentation information has fully loaded. This PR adds a check to exit the makePresentationItems function if the presentation pods aren't there.
=> Fix client crash race condition with presentation pods

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
We removed jquery in BBB 2.2.x as it was not used. Here we have an easy
replacement for jquery in the face of pure javascript. This way we do
not need to re-import jquery package as dependency.
Prior to this commit webcams could not be shared (ever since we merged BBB 2.2.x into 2.3)
credit to @vitormateusalmeida
=> Replace use of $ jquery with javascript in webcam-draggable-overlay

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/captions/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/presentation-options/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss, bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss, bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/styles.scss
This PR moves the quick poll button which was a part of the actions bar into the presentation toolbar
=> Move quick poll button to presentation tool bar

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/startup/server/index.js
This PR fixes the issue where the client gets stuck in a render loop after trying to change the locale via the UI settings, if the `overrideLocale` config is set.
To test in `settings.yml` set the `overrideLocale` to any supported locale. Once the client loads, change the client locale via the UI settings.  Should no longer cause the client to keep reloading  infinitely.
Was mentioned in #8336
=> Fix render loop after changing locale with override setting

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
There was an edge case where a client would send the ValidateAuthToken request message and then disconnect. The ValidateAuthToken response would come back and the HTML5 server would then automatically send a message saying that the user is joining. This resulted in ghost users that the HTML5 server didn't have an active connection for and akka-apps was relying on being told about.
The added protections in this PR are to check that there is an active connection before joining. Even with this PR there's a small window where it can still fail, but a full rework of the login logic is going to have to wait for the next release.
=> Only join a user if the connection is still active

record-and-playback/core/scripts/archive/archive.rb
After the last segment of a recording has been archived, it is safe to delete the original files that were recorded by the various media handling components. This patch deletes the freeswitch audio files and kurento webcam/screenshare files after they have been archived.
It needs to be used in combination with some changes to users/groups and directory permissions to allow the `bigbluebutton` user to delete files that it could previously only read.
Add bigbluebutton user to freeswitch group
```sh
usermod bigbluebutton -a -G freeswitch
```
Allow group write permissions on the freeswitch meetings directory
```sh
chmod 0775 /var/freeswitch/meetings
```
???
Edit systemd unit `kurento-media-server.service`
```
[Service]
UMask=0002
```
(don't forget to `systemctl daemon-reload` afterwards!)
Add …
=> Have the recording archive delete originals of archived media

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/styles.scss
This PR makes the current presentation change notification handle files with long names (removes the scroll bar). Also, improves the notification so it doesn't create extra toast's; if the presentation is changed quickly it updates the existing one.
Before:
After:
Closes #8800
=> Improve current presentation toast

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotation-factory/reactive-annotation/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotation-factory/static-annotation/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotation-group/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotation-group/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/ellipse/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/helpers.js, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/line/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/pencil/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/rectangle/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/triangle/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/pencil-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
The main purpose of this PR is to no longer send DRAW_START and DRAW_UPDATE events. This will drastically lower the CPU load when using the whiteboard. This should mean that drawing with the pencil is easier because it doesn't need to be redrawing the lines multiple times for the preview and final portions.
Further things that could be improved would be to move the DRAW_END path creation to a background worker potentially to make it not lock the thread. Could also split the final annotations into multiple layers somehow because it can still get laggy when there are lots of shapes.
=> Whiteboard performance improvements

bigbluebutton-html5/private/config/settings.yml
This pull request adds `.jpeg` to the supported file extensions list, thus allowing users to upload and use such files as presentation in BigBlueButton.
The presentation file upload feature allows users to select files with various file extensions like `.pdf`, `.ppt`, `.jpg` and others. So far, the `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` did not include `.jpeg` and thus files with that file ending were not supported.
`.jpg` and `.jpeg` are the same file format. The three letter version is often used because early versions of windows did only allow three letter file endings.
=> add support for upload of '.jpeg' files (not just '.jpg')

bigbluebutton-html5/public/compatibility/sip.js
Change `iceCheckingTimeout` from 5 seconds to 1 second in `/usr/share/meteor/bundle/programs/web.browser/app/compatibility/sip.js`
One of the most annoying things about breakout rooms is that the users have to do the echo test again. So they have to wait 7 to 12 seconds again every time (for typical bbb configurations) just for the echo test to connect. This PR reduces the iceCheckingTimeout from 5 seconds to 1 second, which is still way more than enough for finding candidates to connect to the freeswitch server unless there is a configuration or network load issue. Depending on network of the used client, this change saves the user between 4 to 8 seconds for every time they activate audio playback or microphone.
The original 5 seconds timeout is a default of the official sip.js library …
=> Reduce "Connecting to Echotest" waiting time by 4 seconds

bigbluebutton-web/grails-app/conf/application.groovy, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
This is a fix for presentation download vulnerabilities.
If js file is uploaded with image file extension, it is executed when downloaded.
How to reproduce:
1. upload js file with filename like 'xxx.png'
2. turn it downloadable
3. download it
-> browser executes javascript.
Please feel free to edit this.
Cheers,
Mitsu
=> Set content-type for presentation download

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
- track ejected user based on external userid. If user rejoins with the same external
userid, fail the validate token.
=>  Prevent ejected users from rejoining

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/EjectUserFromVoiceCmdMsgHdlr.scala
When a dial-in caller is ejected from the meeting, keep track of the callerid number.
When the same callerid number rejoins the conference, eject the caller.
=>  Keep track of banned dial-in callers

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
Some users join with multiple browsers. When user is ejecting self from one browser,
do not eject all sessions for that user and do not prevent them from rejoining.
=>  Do not ban users ejecting self from meeting

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, bigbluebutton-html5/private/config/settings.yml
We need to increase the length of the voice conference. If we have lots of meetings running,
there is a high chance of collision.
Need corresponding changes to FreeSWITCH dialplan.
In bbb_echo_test.xml, change to `expression="^echo(\d{5,11})$"`.
In bbb_conference.xml, change to `expression="^(\d{5,11})$"`.
=>  Increase voice conf length

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx
Browsers on MacOS are using differen modifier keys for shortcuts. (Table https://www.w3schools.com/jsref/prop_html_accesskey.asp)
This PR is adding the correct keys to the Shortcut help menu in html5 client.
=> fixes shortcut help on mac browsers

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
Do not send disconnect message when validate token fails as meteor will disconnect the client itself.
=>  Do not send disconnect message

record-and-playback/core/lib/recordandplayback.rb, record-and-playback/core/scripts/archive/archive.rb, record-and-playback/core/scripts/events/events.rb
RaP can generate smaller notes id when there should be zeros at start of it. It wasn't possible to retrieve notes in those cases with Etherpad responding 404's.
=> Fix note id length

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx
The typing indicator wouldn't show the typing users if there was an error. It will now show both and better decide whether or not to leave a space.
=> Fix the spacing in the typing indicator

bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js, bigbluebutton-html5/imports/startup/client/logger.js
Included a new field `connectionId` in logs coming from either client side to Meteor or to nginx endpoint
```
{
"name":"clientLogger",
"level":50,
"logCode":"startup_client_usercouldnotlogin_error",
"levelName":"error",
"msg":"User could not log in HTML5, hit 401",
"time":"2020-04-30T20:41:24.214Z",
"src":"Base.renderByState (https://anton.blindside-dev.com/html5client/app/app.js?hash=9d542d25f0f76711c78d446055acfe1b5f509dff:59121:16)",
"v":1,
"clientBuild":"HTML5_CLIENT_VERSION",
"connectionId":"9E3GpGGLtp6ZFQzPb",
"url":"https://anton-local.blindside-dev.com/html5client/join?sessionToken=xcpeu65pdcemyxpu11",
"userAgent":"...",
"count":2
},
```
=> Include Meteor connection ID in logs from client

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss
This PR fixes an issue when selecting multiple users in the user list with a mouse it was causing previously selected users to remain highlighted.
There was a conflict with the styles, the keyboard navigation styling still needs adjusting.
=> Prevent multiple users displaying as selected in user list

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Fix a race condition where the `userId` isn't available at the moment we set custom parameters.
close #9375
=> Fix race condition in addUserSettings

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
We had an issue where `document.querySelector('section[class^=media]')` was undefined so referring to its properties would crash the client.
=> Split querySelector with fallback value

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
When guestPolicy is ASK_MODERATOR, authenticated user is waited for approval, while non authenticated user is allowed.
=> Fix calcGuestStatus

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
Tweaking `RegisteredUsers.remove(u.id, liveMeeting.registeredUsers)`
since we no longer have .remove on RegisteredUsers
=> Adjust #8499 for 58fed457541e9282fb7556aa606e52112ce89d98

bigbluebutton-config/cron.daily/bigbluebutton
- Enabled deletion of >14d old already published raw recording data by default in the daily cronjob script
- reduce amount of `harddrive full - what do?` issues
- improve data privacy by default: User expectation is that parts of the recording which are not "recorded" by pressing the recording-marker do not actually get recorded. For technical reasons the whole session gets recorded, but there is no need to keep that raw recording data for longer than the configured 14 days.
Partially solves #9202
=> enable deletion of 14d old already published raw recordings by default

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
in RTL layout, selecting colors and font thickness parts in whiteboard, will not appear correctly when they expand; one item will be thrown out of the container (overflow).
the following images demonstrate the problems.
adding some additional style to customSvgIcon class in css will fix the bug.
http://up.maralhost.com/do.php?img=359
http://up.maralhost.com/do.php?img=364
=> Rebasing for v2.2.x-release #9173 customSvgIcon css class bug fixed for rtl layouts

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
in RTL layout, selecting colors and font thickness parts in whiteboard, will not appear correctly when they expand; one item will be thrown out of the container (overflow).
the following images demonstrate the problems.
adding some additional style to customSvgIcon class in css will fix the bug.
http://up.maralhost.com/do.php?img=359
http://up.maralhost.com/do.php?img=364
=> customSvgIcon css class bug fixed for rtl layouts

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss
This PR is an improvement on #9365 and fixes the mentioned styling issue. It adds a click handler which correctly sets the currently selected user. The absence of this handler was the underlining cause for the user-list displaying two users as selected when using a mouse.
=> Set correct state in user list for selected user onClick

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/styles.scss
This PR localizes the default poll options which closes #9302. It also add's an outline to the published poll annotation text. The idea behind the outline is to prevent the case where the result for a given poll is not distinguishable from the annotation background.
=> Localize default poll options before calculating annotation required space 

akka-bbb-apps/src/universal/conf/application.conf
- attack surface reduction by having akka-bbb-apps only listen on localhost/127.0.0.1
akka-bbb-apps is the server side application which handles the state of meetings on the server. There is no need to expose it to the internet, as all requests should go through nginx or are directly made from other BBB apps running on localhost
=> akka-bbb-apps only listen on localhost

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PermissionCheck.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectDuplicateUserReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectUserFromMeetingCmdMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- users who are ejected from meeting because of permission check cannot
rejoin meeting as we mark them as banned. Only users ejected by a
moderator should be banned. Later on, we should make the moderator
indicate if the ejected user should be bannd or not.
see https://github.com/bigbluebutton/bigbluebutton/issues/9608
=>  Ejected users due to permission check cannot rejoin meeting

bigbluebutton-config/bin/bbb-conf
Our BBB instance is fully https encrypted, so there are no connections on port 80, and it seems that flash and therefore port 1935 is fully deprecated. by adding port 443, we can actually see what connections are being made at the moment.
As requested in [this issue](https://github.com/bigbluebutton/bigbluebutton/issues/9069).
=> added port 443 to bbb-conf --network command.

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- separate conf num with space instead of dash
Initial work on more flexible formatting is being done in
https://github.com/ritzalam/bigbluebutton/tree/format-voice-conf-number
This just addresses complaints on mailing list that separating using '-'
is confusing.
=>  Format conference num

bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
* Update react-player to latest version (not related to sync, but I've tested the latest version and it has some fixes for different player bugs) _EDIT: sent missing package-lock.json file_
* Some OSes + browsers would have problems when sending float numbers via meteor messages, which would turn regular floats into negative integers. So for now we're rounding the time and working with integers before we send them throught the network
* I've removed the timestamp correction logic. This code is incorrect in subtle ways and breaks with computers in very different timezones. This was originaly put in to correct the problems we saw with video skipping and created more trouble than it solved. Hopefully the skipping is fixed by the second commit.
I'd ask you to test these changes with the …
=> Attempt to fix external video syncing

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/service.js, bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/public/compatibility/kurento-extension.js, bigbluebutton-html5/public/compatibility/kurento-utils.js
- Adds support for screensharing on Safari 13+ on **desktops** or whichever version has getDisplayMedia enabled
- To be conservative and backwards compatible, I`ve maintained the current gUM-based code available as a fallback for those still using older versions of FF or Chrome
- Made screenshare constraints configurable. The constraints config will be piped directly to gDM, so it`s just a regular gDM constraint dictionary
- Fixed an issue where Firefox wouldn't pick up the specific screenshare constraints (ie frameRate, width, height). Firefox should now be correctly frame rate and resolution constrained.
=> Screenshare: add support on Safari 13+ and make constraints configurable

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
In breakout rooms everyone is moderator, so there is no point of lock settings
=> Do not display "Lock viewers" option in breakouts

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/service.jsx, bigbluebutton-html5/private/config/settings.yml
Closes #9592,
This PR also fixes shortcuts not working for components with multiple keys and removes the `openStatus` shortcut (this will no longer function as intended since the status items were moved out of the action bar).
=> Fix userData-shortcuts causing client crash 

record-and-playback/presentation/scripts/publish/presentation.rb
There's nothing reasonable we can do here if the font size is missing.
Works around #9621 
The actual bug appears to be in the HTML5 client - it shouldn't be emitting events where the calced_font_size is not set.
=> presentation: ignore text shapes with missing calcedFontSize

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
Reverts bigbluebutton/bigbluebutton#9189
After merging #9189 we saw multiple community members experience issues (see #9656 )
Thank you @pedrobmarin for investigating this!
When the policy is ASK_MODERATOR, if you are not a moderator you will have to wait to join the meeting.
=> Revert "Fix calcGuestStatus"

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/component.jsx
This PR stops the chat input field jumping when the typing or error indicator is displayed.
before:
after:
=> Prevent chat input shifting with error & typing messages

bigbluebutton-html5/imports/startup/client/base.jsx
Currently when the user logout from a breakout room he sees the same message as when he logout from normal room, and after it's redirected to the defined link. 
This PR changes the behavior, so when the user logout from a breakout room the breakout room tab is closed, the same behavior of when the breakout room time expires or moderator end all breakout rooms.
=> Close tab when user logout from a breakout room

record-and-playback/core/scripts/rap-process-worker.rb
Simpler solution than the ones proposed by #9183 and #9249.
Uses function from the module: https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/record-and-playback/core/lib/recordandplayback.rb#L244
=> Sort sanity files so it processes older recordings first

bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fixes #9024 (voiceBridge collision for two independent meetings) by performing two changes:
1. Abort meeting creation if either telVoice or webVoice collide with an existing meeting
2. If telVoice is generated by BBB (i.e. not passed to the API), try up to 10 times for a unique telVoice
Since the issue is extremely rare, step 2 should find a valid telVoice within 1 try.
The fix was tested by forcing telVoice collisions through the API as well as by setting colliding values in ApiController.groovy and adjusting the random number generation in ParamsProcessorUtil.java.
Those changes were cleaned before submission.
Normal behavior of BBB is unchanged, this should only handle the corner cases.
=> Fix voiceBridge collision (Issue #9024)

bigbluebutton-config/cron.hourly/bbb-restart-kms
This pull request adds the `bbb-restart-kms` script, which was added to the bbb 2.2.3 release, but never got added to the code repository.
resolves #9048
The `/etc/cron.hourly/bbb-restart-kms` script restarts kurento-media-server and bbb-webrtc-sfu every 24 hours if there are currently no bbb users online / actively using the system. This was added to the ubuntu install package with version 2.2.3 and probably is a workaround for memory leaks or similar issues.
This file might be missing the +x file flag so it can be executed on linux based systems.
=> add missing bbb-restart-kms script which was added to 2.2.3 but is missing in the repo

bbb-lti/Dockerfile, bigbluebutton-web/Dockerfile
Signed-off-by: fenn-cs <fenn25.fn@gmail.com>
`services.gradle.org` would reject the request if it's not secured causing `make release` to fail at the indicated point. 
```
Step 2/19 : RUN mkdir -p /root/tools  && cd /root/tools  && wget http://services.gradle.org/distributions/gradle-2.12-bin.zip  && unzip gradle-2.12-bin.zip  && ln -s gradle-2.12 gradle
---> Running in f426e1399565
--2020-01-16 02:15:46--  http://services.gradle.org/distributions/gradle-2.12-bin.zip
Resolving services.gradle.org (services.gradle.org)... 104.18.190.9, 104.18.191.9, 2606:4700::6812:be09, ...
Connecting to services.gradle.org (services.gradle.org)|104.18.190.9|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-01-16 02:15:47 ERROR 403: Forbidden.
The command '/bin/sh -c mkdir -p …
```
=> http => https to prevent 403 access denied during gradle download

bigbluebutton-html5/imports/ui/components/captions/component.jsx
Improves how screen readers interact with the live close captions. This change makes screen readers announce each word as it is entered in the captions. 
Previously, users would have to navigate to the captions for the screen reader to announce them. (users may not realize captions are displayed before they disappear)
=> Make screen reader announce captions as they are appear

bigbluebutton-config/bin/bbb-conf
Use the event socket layer (ESL) password in FreeSWITCH when checking if FreeSWITCH is listening on port 8021.
=> Use the specified ESL password

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/private/config/settings.yml
Very trivial addition:
If bbb_show_participants_on_login is true (or unset) then setting **bbb_show_public_chat_on_login=false** causes the public chat component (div) to be initially hidden on login (until user expands it).
---
Only thing that needs to be changed is in
greenlight/app/controllers/concerns/bbb_server.rb
and add join_opts["userdata-bbb_show_public_chat_on_login"] = false
to the block with
join_opts = {}
join_opts[:userID] = uid if uid
join_opts[:join_via_html5] = true
join_opts[:guest] = true if options[:require_moderator_approval] && !options[:user_is_moderator]
<<add it here>>
=> Add bbb_show_public_chat_on_login as a join (co-) parameter

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/arc-player.jsx
Add the onMount callback to our custom instructure media player and make sure it loads again.
=> Call onmount for custom arc-player

bbb-common-web/project/Dependencies.scala, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/Office2PdfPageConverter.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeDocumentConversionFilter.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java, bigbluebutton-web/build.gradle
When attacker uploads vulnerable excel or libreoffice calc file, the formulas are executed in a server when JODConverter converts documents to pdf.
This produces a potential risk to expose server's data to attackers or
possible DoS attack.
(see as FYI https://www.notsosecure.com/data-exfiltration-formula-injection/)
By setting `AutoCalculate` off, you can prevent server from running formula.
=> Fix XML(Formula) Injection

bigbluebutton-config/bin/bbb-conf
If detected the default FreeSWITCH event socket layer password is in use, update it (and BigBlueButton's configuration files) to a new password.
=> Update bbb conf 23

bbb-lti/grails-app/views/tool/index.gsp
The former code showed each character of the preview thumbnail urls in an image tag, which filled up the page without sense.
Please also consider this for backporting to 2.2.x. Because of the corona situation, many universities use the LTI-Plugin and this obvious error makes it hard to use, because the recording list becomes huge without need. But without deb-packages, many deployments will not adapt.
This error was already mentioned in the google-groups, but there were no answer to it.
=> fix broken thumbnail display in LTI-plugin

bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
invokes `toggleSwapLayout` if the layout is swapped when the screen share closes
#9768
=> Fix ending of screenshare displaying empty container

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Restore capacity of user settings for guest users. The problem was that guest users are not `authed` then the process of saving the user settings never happened.
closes #9737
=> Fix custom parameters for guest users

bigbluebutton-html5/private/config/settings.yml
This patch adds a short comment block to the HTML5 client's
configuration file explaining the options available for the camera
profiles. Having this in the configuration file helps as a quick
reference and means that administrators do not need to find external
sources of information.
=> [HTML5 Client] Camera Profile Documentation

bigbluebutton-html5/private/locales/en.json
This patch updates the note about which external videos can be shared
by looking at what react-player supports. Most notably, SoundCloud and
external video URLs are added.
This also removes the mention of Instructure Media for which I could not
find a way to actually use it. It is also not mentioned in the list of
supported sources by react-player.
Finally, this fixes the misspelled name of Dailymotion.
=> Update Note About Sharing External Video

record-and-playback/core/lib/recordandplayback.rb, record-and-playback/core/scripts/rap-publish-worker.rb, record-and-playback/presentation/scripts/process/presentation.rb
This PR fixes an issue with reading and writing files.
File.open is used which means that a file will remain open
unless explicilty closed or the program exit. This doesn't work
for an NFS mount as the scripts try to "rm -rf" when the file
is still open. This commit fixes that by replacing all .opens
with .reads in 3 locations.
Fixes #9062 and #9110 (duplicates)
Our BBB hosts only have a maximum disk size of 25GB so we could not store recordings locally. An external NFS mount was used for the Kurento, FreeSWITCH and other directories to ensure that the entire process still worked. However, we ran into this issue and the existing fixes in the issues were quick hacks that did not solve the issue at large. It is also good practice to close files after using them. It may be necessary to apply …
=> Ensure that files are handled safely in recording scripts

bbb-common-web/src/main/java/org/bigbluebutton/api/ApiErrors.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
@elor I was having some trouble trying to understand #9251. Somehow I was still able to create meetings with the same `voiceBridge`. Does this makes any sense?
Replaced `==` string compare to a `String.equals` (since the string is a validated non-null object) and included a new API error to make it more clear at the response.
=> Fix voice bridge compare

bigbluebutton-html5/imports/ui/components/app/component.jsx
This prevents the session being closed if you drag and drop a file onto the window.
A simple way to prevent #9661  until we  allow drag-and-drop of presentation over the main BigBlueButton area in a future version.
=> Prevent drag and drop of files closing session

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx
adds a debounce to prevent the ability to unmute when spam clicking the button. 
partially closes #9731
=> Add debounce to talking indicator mute function

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
Removes `-` as the default placeholder in the live poll results.
#9766
=> Fix poll vote not incrementing when - is used as a custom option

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu/component.jsx
Closes the whiteboard toolbar sub menu when outside of the tools are clicked
#9730
=> Close whiteboard toolbar sub menu on mousedown

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
This PR prevents the whiteboard crashing when publishing a poll with a large `.pdf` by adding a max font-size to the font calculation.
#9451
=> Fix poll annotation error with large presentations

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss
Fixes the position of the unread indicator for the shared notes.
before:
after:
=> Fix shared note unread indicator placement

bigbluebutton-html5/private/locales/en.json
Make the consequence of ending a meeting more clear to the moderator.
=> Make end meeting more clear

bigbluebutton-config/bin/bbb-conf
When we run `bbb-conf --check` and we changed `defaultGuestPolicy` value in `bigbluebutton.properties`, there this warning:
Since it's already supported by HTML5 client, this warning can be removed.
=> Remove warning about unsupported defaultGuestPolicy in HTML5 client

bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js, bigbluebutton-html5/imports/ui/components/user-list/service.js
In some cases the VoiceUsers collection has incorrect `muted=true` state for a viewer. If a moderator triggers `toggleVoice` on them, attempting to mute them, the resulting redis message will state that the moderator is trying to unmute rather than to mute. Combined with `meeting.usersProp.allowModsToUnmuteUsers=false`, the result is that the moderator gets kicked out from the meeting.
In this PR I have added a condition so that if `meeting.usersProp.allowModsToUnmuteUsers=false`, the bbb-html5 app will not inject any requests to unmute others.
At first I was trying to convert the `toggle` event into a separate `mute | unmute ` event but this has a more visible negative side effect when the VoiceUsers state is out of sync. Namely, you will not be able to trigger a mute call on an unmuted …
=> Prevent 'unmute' calls for others caused by incorrect state

bigbluebutton-html5/imports/startup/client/logger.js
This info should help debugging, mostly cases of
- shared publicly/bookmarked link to a BBB session
- hitting Refresh after stumbling upon 401 or network issues
When unable to authenticate:
I20200630-14:11:26.907(-4)? error: {"logCode":{"clientURL":"https://anton-local.blindside-dev.com/html5client/join?sessionToken=w6h6lnxb4l7un0kz_"},"logDescription":"User could not log in HTML5, hit 401","connectionId":"s8B2TjvjY9MPG5Hqg","extraInfo":{"validUser":"notFound"},"userInfo":{}}
When able to authenticate:
I20200630-14:35:25.191(-4)? info: {"logCode":"app_component_componentdidmount","logDescription":"Client loaded successfully","connectionId":"mtjwfQkXCAWhE7j9H","extraInfo":{"clientURL":"https://anton-local.blindside-dev.com/html5client/join?sessionToken=w6h6lnxb4l7un0kz","validUser":"valid"} …
=> Added clientURL to client logs

record-and-playback/core/lib/recordandplayback/generators/events.rb, record-and-playback/presentation/scripts/process/presentation.rb, record-and-playback/presentation/scripts/publish/presentation.rb
This adds workarounds for an issue seen in BigBlueButton where the `presentationName` field in recording events contains invalid data (usually the original filename of the presentation plus several numeric digits). It was failing if the directory matching the `presentationName` did not exist.
Also a fix for the participants count to correctly exclude reconnects
=> Recording bugfixes for presentation format

bbb-webhooks/callback_emitter.js, bbb-webhooks/config/custom-environment-variables.yml, bbb-webhooks/config/default.example.yml
- Add a new config `requestTimeout`.
* Add a new environment variable mapping for it called `REQUEST_TIMEOUT`.
* The config is piped to the `request` module POST request in `callback_emitter.js`. It makes it properly throw socket establishment timeout errors and prevent queue clogging when there's no response from the webhook recipient.
The lack of the timeout config caused queue clogs when, due to ie network instability or network misconfigs, no response was received for a POST request fired from bbb-webhooks. Worst of all, it'd clog silently. So this will make it properly log the timeout errors and keep trying to resend the POST requests until it works.
=> bbb-webhooks: add a timeout configuration to be used on POST requests

bigbluebutton-config/bin/bbb-conf
As pointed out on [bigbluebutton-dev](https://groups.google.com/forum/#!msg/bigbluebutton-dev/iwTMelhdktw/y6RsBhXLAgAJ) it is common practice in nginx config to [specify an underscore](https://nginx.org/en/docs/http/server_names.html#miscellaneous_names) for `server_name` as a catch-all.
The `bbb-conf` script should respect that common practice and suppress warning if `server_name` is `_`.
In order to avoid `postinst` scripts to overwrite the `_`, they should be changed as well:
from:
sed -i "s/server_name  .*/server_name  $IP;/g" /etc/nginx/sites-available/bigbluebutton
to:
sed -i "s/server_name  [^_].*/server_name  $IP;/g" /etc/nginx/sites-available/bigbluebutton
Using `server_name  _;` and not touching it anymore also helps preventing problems like #9544.
=> bbb-conf: respect underscore in nginx server_name

record-and-playback/core/lib/recordandplayback/workers/sanity_worker.rb
Closes #8790.
Included an extra check after post archive routine to interrupt the regular record processing flow if it's a norecord meeting
=> Skip recording process step for norecord meetings

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/private/config/settings.yml
-  video-provider: make ReconnectingWebsocket's `connectionTimeout` configurable (default value was preserved)
-  video-provider: make camera timeouts configurable (default values were preserved)
-  audio: make listen only call timeout configurable
None.
Those timeout values were hardcoded and they were always meant to be configurable so that users have the freedom
to adjust their setups according to their user base network conditions (and also make things more flexible if they wish).
I kept the default values, but I do think they should be preferably increased in a default setup. I could blabber about how this is a stopgap and how we should change the mechanics of some of our stuff regarding doing all we can upfront instead of on demand to reduce connection times, but that's a topic for …
=> Make some media connection timeouts configurable

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/panopto.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/service.js, bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/download-presentation-button/styles.scss
This uses the "social URL" avaialble from Panopto to play their video content using ou simple FilePlayer.
Example of a Panopto video URL: https://rwu.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=353d11ad-cd72-461b-9fe9-aa49010d3c8e
Also included is a fix for a situation where Chrome would not display video controls for mp4 videos on the html5 client. There was a style override of the control bar style in Chrome, I think the goal was to hide controls when a camera is made fullscreen. This doesn't seem to be necessary anymore and had the side-effect of hiding the actual video player controls we needed to make video sharing work.
=> Implement a simple Panopto external video player

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
Fix missing leading zeros in conference number
Rewrite conference number formating to use only string manipulation as converting to Int removes leading zeros.
fixes #9769
=> Fix missing leading zeros in conference number for 2.2.x

bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss
This change allows the List of waiting users to scroll if it is longer than the screen. 
fixes #9533
When there are more users than a single screen height can accomodate, it is impossible to get to the last few users in the list. 
Tested with Firefox
=> Make List of waiting users scrollable
