bigbluebutton/bigbluebutton

- record-and-playback/core/scripts/sanity/sanity.rb
This was causing the sanity check to fail.
Fixes https://code.google.com/p/bigbluebutton/issues/detail?id=1873
> Skip the 'ser' repair if there are no webcam videos

- bigbluebutton-client/resources/prod/BigBlueButton.html
This pull request is in reference to the comments on a previous commit. https://github.com/capilkey/bigbluebutton/commit/10874f986d9d4e9ab7f722f8a1aa3e4566fff281
> move the pixel alignment check to a callback

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/resources/prod/lib/bbb_api_bridge.js
- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCallbacks.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/events/WebRTCEchoTestEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/WebRTCCallManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/maps/WebRTCEventMap.mxml
fixed a race condition in the webrtc javascript code, and propagated the cause value for "call failed" errors (1004).
> WebRTC fixes

- bigbluebutton-apps/src/main/java/org/bigbluebutton/conference/service/chat/ChatMessageListener.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/RedisMessagingService.java
-Allow json breaking symbols: " and \ in chat messages
-Fix some log strings
> HTML5 Client chat symbols

- bigbluebutton-client/src/org/bigbluebutton/core/model/Config.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/PortTestProxy.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/EnterApiService.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModuleManager.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesDispatcher.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesProxy.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as
- get meeting and user info so we can log more info when user fails to connect to Red5
>  - remote stun related code

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/resources/prod/lib/bbblogger.js
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCallbacks.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/events/WebRTCCallEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/WebRTCCallManager.as
* Cleaned up a race condition with the TURN retrieval
* Added a debug line when the TURN retrieval fails
* Fixed a case where the TURN return doesn't match
* Fixed two issues with WebRTC warnings
> Improvements to WebRTC

- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/api/InMessages.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/api/OutMessages.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/red5/UsersClientMessageSender.scala
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesDispatcher.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/managers/ConnectionManager.as
- add a detection when a meeting actor has hung resulting in users not being able to do anything
>  - lower log level on some logs so we can filter

- labs/meteor-client/app/client/stylesheets/chat.less
- labs/meteor-client/app/client/stylesheets/whiteboard.less
- labs/meteor-client/app/client/views/whiteboard/slide.coffee
- labs/meteor-client/app/client/views/whiteboard/whiteboard.coffee
- labs/meteor-client/app/client/views/whiteboard/whiteboard.html
-Improve the way whiteboard height is calculated (to maximize visibility)
-fixed a bug with tiny (1x1px) whiteboard on FF
-A4 slides fit to width on mobile portrait
-whiteboard centering compatible with IE
-chat tab fixes
> Whiteboard modifications

- labs/meteor-client/app/client/globals.coffee
- labs/meteor-client/app/client/main.html
- labs/meteor-client/app/client/stylesheets/chat.less
- labs/meteor-client/app/client/stylesheets/style.less
- labs/meteor-client/app/client/stylesheets/users.less
- labs/meteor-client/app/client/views/chat/chat_bar.coffee
- labs/meteor-client/app/client/views/chat/chat_bar.html
- labs/meteor-client/app/config.coffee
Added recognizing mobile devices and setting different default Chat settings for mobile/PC.
Added necessary variables to config.coffee.
Improved scaling, so the view doesn't change when URL field appears while scrolling down on mobile devices.
> Mobile View's changes

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/style.less
- Push menu replaces the old sliding menu.
- When the push menu is opened, the scrolling is disabled until the user click somewhere on the page.
- Chevron icons are replaced with the "hamburger" menu icon.
> HTML5 client's push menu.

- bigbluebutton-client/resources/prod/BigBlueButton.html
> Addition to pull req #554

- bigbluebutton-client/src/org/bigbluebutton/main/model/users/BBBUser.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
Fixed problem when changing presenter with webcam
> Fixed problem when changing presenter with webcam

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/config.coffee
- bigbluebutton-html5/app/lib/router.coffee
- bigbluebutton-html5/app/server/user_permissions.coffee
-use the logout URL the Flash client uses (grab from enter/api)
-get rid of the hardcoded IP in config.coffee for the HTML5 client
> html5client: LogoutURL reuse

- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonInGW.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/api/ValueObjects.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/red5/UsersClientMessageSender.scala
- bigbluebutton-apps/src/main/scala/org/bigbluebutton/core/apps/users/redis/UsersMessageToJsonConverter.scala
- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/core/vo/LockSettingsVO.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/LockSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
Added lockOnJoinConfigurable property to lock config
> Bbb lock settings

- bigbluebutton-client/resources/prod/BigBlueButton.html
- bigbluebutton-html5/app/lib/router.coffee
-created a Meteor endpoint so we can check if the html5 client is running and ready to handle a new user
-updated BigBlueButton.html to properly use that checkpoint
> meteor endpoint /html5client/check. update BigBlueButton.html

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/views/chat/chat_bar.coffee
- bigbluebutton-html5/app/client/views/chat/chat_bar.html
-use a dropdown for the userslist (to select a partner for private chat)
-use -/+ buttons to regulate the font-size
-fixed a bug when a client didn't set a proper default font size
> html5client: Options reorganize

- bigbluebutton-html5/app/client/main.coffee
Fixes the issue with WebRTC browser support notifications and Firefox.
> HTML5 client: fix for WebRTC browser support notifications.

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.mxml
* Increased the WebRTC transfer timeout from 3 to 5 seconds
* Added URL parsing to private messages
* Annotations follow the mouse if it leaves the WhiteboardCanvas area. Previously they would just stop updating.
> Three different bug fixes

- bigbluebutton-client/resources/prod/lib/bbb_deskshare.js
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/utils/JavaCheck.as
Now desktop sharing runs again on Linux.
> Fix issue 1909

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/views/sharedTemplates.html
- Fixes the bug with the absence of the push menu for the user who enters the client using a mobile device in landscape orientation and then switches to portrait.
- Rearranges the push menu buttons according to the order of the panels on mobile device in portrait mode.
- Disables the tooltips on mobile devices.
> HTML5 client: push menu update.

- bigbluebutton-client/src/org/bigbluebutton/main/views/FlashMicSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/LayoutsCombo.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/business/VideoWindowItf.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardTextToolbar.mxml
* hopefully fix the flash mic list so that it repopulates 	
* reset the client layout even if the already selected item is clicked 	
* updated the webcam url regex to match the new userid format 	
* reset the TextToolbar position when it is made visible
* avoid redraws of the TextToolbar when possible
> Misc 0.9.0 fixes

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/slide.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
Adds the ability to watch the whiteboard in full screen mode.
> Whiteboard in full screen mode.

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/main/model/LayoutOptions.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/FlashMicSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/WebRTCEchoTest.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/maps/LayoutEventMap.mxml
* fixed issue 1915
* removed some unused options from config.xml
* increased the height one of the TextArea objects in the Flash and WebRTC echo tests
> Three client fixes

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/model/LayoutDefinition.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
There are still weird behaviours. Go to demo12.jsp and choose Webinar for the layout. 
1. Switch to default and resize the browser. The UserWindow will animate from the bottom to the top every time you resize. 
2. Then minimize the ChatWindow. The UserWindow will move as well.
> made a bunch of layout changes, still doesn't work 100% correct

- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/slide.coffee
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_paper.coffee
- Fixes the issue with a tiny whiteboard (slide appears very small on first load).
- Corrects the size of the cursor on first load.
> HTML5 client: whiteboard bug fixes related to the first client load.

- record-and-playback/core/lib/recordandplayback/generators/events.rb
- record-and-playback/presentation/scripts/publish/presentation.rb
Fixes https://code.google.com/p/bigbluebutton/issues/detail?id=1927
> Recording clear

- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/view/components/DesktopPublishWindow.mxml
Getting this into 0.9.0 as well.
> Chrome can manually allow NPAPI until version 45, modified publish window to match

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/lib/bbb_api_bridge.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/views/chat/chat_bar.coffee
- bigbluebutton-html5/app/client/views/users/user_item.coffee
- bigbluebutton-html5/app/client/views/users/user_list.coffee
- bigbluebutton-html5/app/client/whiteboard_models/utils.coffee
- bigbluebutton-html5/app/server/collection_methods/chat.coffee
- bigbluebutton-html5/app/server/collection_methods/users.coffee
HTML5 client functionality is now almost exclusively inside the bridge API.
> Moving functionality into BBB bridge

- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
- bigbluebutton-html5/app/lib/router.coffee
-added a display for the slide counter (e.g. 3/4) for presenting HTML5 client
-fixed <ip>/html5client redirecting to undefined
-added tooltips for the slides controls
> html5client:Presenter switch slide - count for slides

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/resources/prod/lib/bbb_deskshare.js
- bigbluebutton-client/src/DeskShareModule.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/managers/DeskshareManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/managers/PublishWindowManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/model/DeskshareOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/view/components/DesktopPublishWindow.mxml
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/DeskShareApplet.java
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/DeskshareClient.java
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/ScreenShareInfo.java
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/ScreenSharerRunner.java
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/net/NetworkSocketStreamSender.java
- deskshare/applet/src/main/java/org/bigbluebutton/deskshare/client/net/NetworkStreamSender.java
New parameters in the config.xml file
```<module name="DeskShareModule" 
url="http://HOST/client/DeskShareModule.swf?v=VERSION" 
uri="rtmp://HOST/deskShare"
uriTLS="HOST"
useTLS="false"
showButton="true"
autoStart="false"
autoFullScreen="false"
baseTabIndex="201"
/>```
`useTLS` lets the applet the know whether or not it should use TLS, if should be true or false
if `useTLS` is false, then `uriTLS` should point to the actual bigbluebutton server
if `useTLS` is true, then `uriTLS` should point to the SSL terminating service, in our case stunnel
> Deskshare tls

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- right-hand side menu improvements
- push menu darkens the rest of the page
- improved switching between views
- mobile view bug fixes
- mobile UI improvements
> HTML5 Client: Mobile View Updates

- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
Integrates the presenter's slide switching feature into the new UI.
> HTML5 client: presenter switching slide with the new UI.

- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/modals.less
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/views/modals/modals.html
- Makes the right-hand menu's buttons work.
- Adjusts the size of the dialog windows (Settings, Logout) to the mobile view.
> HTML5 client: right-hand menu.

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/slide.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
- Always keeps the whiteboard within borders.
- Fixes the position and styling of the slide navigation controllers.
- Makes the whiteboard correctly scale when the slide navigation controllers appear/disappear.
> HTML5 client: whiteboard bug fixes.

- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/views/users/user_item.html
User can now mute/unmute by clicking an icon in the userlist.
> HTML5 client: ability to mute/unmute yourself from userlist.

- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/stylesheets/modals.less
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/chat/chat_bar.html
- bigbluebutton-html5/app/client/views/modals/modals.html
- bigbluebutton-html5/app/client/views/users/users_list.html
Corrected borders, icons, colors.
Changed Settiings window.
Improved positioning.
> UI Changes for a desktop view

- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
- Allows user to raise/lower hand by clicking the button soaring over the whiteboard.
- Styles the whiteboard buttons.
- Some code refactoring.
> HTML5 client: raise/lower hand.

- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml
I accidentally left the sample display that I used for testing active in the code.
> Disabled the sample poll display

- bigbluebutton-html5/app/.meteor/packages
- bigbluebutton-html5/app/.meteor/versions
- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/views/users/users_list.html
- Makes the menus slide over the screen instead of pushing it aside.
- Adds animations to the menus.
- Changes the styling of side menus.
- Cleans up the old sliding menu code.
> HTML5 client: new sliding menu.

- bbb-video/build.gradle
- bbb-video/src/main/java/org/bigbluebutton/app/video/VideoApplication.java
- bbb-video/src/main/java/org/bigbluebutton/red5/pubsub/GenericObjectPoolConfigWrapper.java
- bbb-video/src/main/java/org/bigbluebutton/red5/pubsub/MessagePublisher.java
- bbb-video/src/main/java/org/bigbluebutton/red5/pubsub/MessageSender.java
- bbb-video/src/main/java/org/bigbluebutton/red5/pubsub/MessageToSend.java
- bbb-video/src/main/webapp/WEB-INF/bbb-redis-pool.xml
- bbb-video/src/main/webapp/WEB-INF/red5-web.xml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/business/VideoProxy.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/events/ConnectedEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMapDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/ToolbarPopupButton.mxml
- bigbluebutton-web/grails-app/conf/UrlMappings.groovy
Handle disconnects to bbb-video and reconnect if the cause is a network issue
> Reconnect to bbb video

- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/views/modals/modals.html
- bigbluebutton-html5/app/client/views/sharedTemplates.html
- Unifies the way buttons are constructed.
- Changes the size of the hamburger buttons on desktop (landscape view or narrow desktop window).
> HTML5 client: hamburger buttons.

- akka-bbb-apps/build.sbt
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/WhiteboardModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/recorders/WhiteboardEventRedisRecorder.scala
- akka-bbb-fsesl/build.sbt
- bbb-common-message/build.sbt
- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/Util.java
- bigbluebutton-apps/build.gradle
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/WhiteboardClientMessageSender.java
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/PollResult.as
Poll result message now comes into the client but isn't displayed in the whiteboard. Need to figure out why.
> Try to display poll result in whiteboard

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/views/chat/chat_bar.coffee
- bigbluebutton-html5/app/client/views/chat/chat_bar.html
- bigbluebutton-html5/app/client/views/sharedTemplates.coffee
- bigbluebutton-html5/app/client/views/sharedTemplates.html
- bigbluebutton-html5/app/client/views/users/user_item.coffee
- bigbluebutton-html5/app/client/views/users/user_item.html
- bigbluebutton-html5/app/client/views/users/user_list.coffee
- bigbluebutton-html5/app/client/views/users/users_list.html
- added the functionality for unread private and public chat messages
- removed "Close user list" button from the user list
- fixed 2 bugs with a private chat tab and notifications on relogin 
- added styling for notifications for desktop views and partially for mobile ones
- changed some styling for user list
- added focus to the input text area right after opening a private chat tab
- clicking your own username now leads to a public chat
> Chat notifications and UI changes

- .gitignore
- akka-bbb-apps/.gitignore
- akka-bbb-fsesl/.gitignore
- bigbluebutton-client/.gitignore
Improved .gitignore files with better generic and custom patterns.
> Improved .gitignore files with better patterns.

- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
It uses a fairly simple regex, but if you notice false positives or no button when one should be there let me know.
> Added a quick poll button

- bigbluebutton-html5/app/.meteor/packages
- bigbluebutton-html5/app/.meteor/versions
- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/stylesheets/style.less
- Adds the ability to open/close the left-hand and right-hand menus with a horizontal pan gesture on mobile devices.
- Makes the touch events work faster.
- Fixes minor UI bugs in navbar.
> HTML5 client: horizontal pan gesture on mobile devices.

- bigbluebutton-client/src/BigBlueButton.mxml
- bigbluebutton-client/src/BigBlueButtonMainContainer.mxml
- bigbluebutton-client/src/org/bigbluebutton/core/BBBApplication.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
Updated application life-cycle : the application configuration is loaded before displaying the main application shell, all loaded resources will then be able to access the configuration without any issue.
> Updated application lifecycle: load the configuration before display

- bigbluebutton-html5/app/.meteor/packages
- bigbluebutton-html5/app/.meteor/versions
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/style.less
- Sets the presentation title to always use as much space as possible without interfering with buttons.
- Fixes the navbar's audio button: positioning and behaviour on hovering.
- Makes the navbar buttons look consistent.
- Corrects the file references in Chrome/Firefox CSS inspector.
> HTML5 client: navbar bug fixes.

- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
I changed the QuickPollButton label to follow the form "A/B/C/D" to match the entries in the dropdown menu.
I made the poll menu items translatable to match the rest of the poll labels.
I re positioned menu in the UsersWindow so that it isn't cut off by the bottom of the screen.
> Poll label changes

- record-and-playback/presentation/playback/presentation/0.9.0/lib/writing.js
- record-and-playback/presentation/scripts/publish/presentation.rb
Note that this requires a new dependency be added to the
"bbb-playback-presentation" format; the "gnuplot" package is now
required (it's used to actually generate the chart images)
> Add poll result display to the 'presentation' recording format

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollGraphic.as
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollResultsModal.as
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/PollResultObject.as
Improved the poll scaling. 
Made sure old graphics in the poll whiteboard object are removed. 
Added detection for true/false and yes/no
Rearranged some stuff in the PollResultsModal
> Misc polling changes

- bigbluebutton-html5/app/client/views/whiteboard/slide.coffee
- bigbluebutton-html5/app/server/collection_methods/slides.coffee
HTML5 client can now handle image URIs in old format (png_uri) as well.
> HTML5 client: PNG legacy issue.

- bigbluebutton-client/resources/prod/lib/bbb_blinker.js
- bigbluebutton-client/src/org/bigbluebutton/main/views/AudioSelectionWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/deskshare/model/DeskshareOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/model/VideoConfOptions.as
Detection of Puffin browser and disabling webcam, microphone and desktop sharing buttons.
> Puffin browser detection

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/lib/bbb_api_bridge.coffee
- bigbluebutton-html5/app/client/lib/regex-weburl.js
- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_paper.coffee
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_poll.coffee
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_text.coffee
- bigbluebutton-html5/app/collections/collections.coffee
- bigbluebutton-html5/app/config.coffee
- bigbluebutton-html5/app/lib/router.coffee
- bigbluebutton-html5/app/server/collection_methods/poll.coffee
- bigbluebutton-html5/app/server/collection_methods/shapes.coffee
- bigbluebutton-html5/app/server/publish.coffee
- bigbluebutton-html5/app/server/redispubsub.coffee
- bigbluebutton-html5/app/server/server.coffee
- bigbluebutton-html5/app/server/user_permissions.coffee
- Implemented Polling.
- Added proper sorting to the user list.
- Added a new library for URL recognition.
> Polling, Sorting and URL Validation

- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollChoicesModal.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollGraphic.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/PollResultObject.as
Fixed the spelling of "presentation"
Improved the spacing for the poll label column
> Misc poll fixes

- record-and-playback/presentation/scripts/publish/presentation.rb
There were a couple of problems:
* A division by 0 when calculating the percentages
* Positioning of the number of results counter was incorrect
Fixes #2739
> Fix poll in recording when there are 0 responders

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/src/org/bigbluebutton/main/views/FlashMicSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/events/ChatNoiseEnabledEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AddChatTabBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollChoicesModal.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
* Add checkbox chat sounds
* Increase font size in audio dialogs
* Move ChromeMicPermission down 50px
* Clean up presentation sizing on page load
* Add an ICE connection timeout of 60s to avoid the 5-10min when Chrome decides not to work in a timely manner
> Miscellaneous Client fixes for 1.0

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/Poll.scala
- bigbluebutton-client/resources/prod/profiles.xml
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/BBBUser.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollDataProcessor.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
* Swapped the Yes/No and True/False answers
* Added a widescreen video profile
* Restricted @poll to the presenter
* Fixed the accessible poll results when using custom polls
* Lowered the volume of the start poll ping
> Misc client changes 100

- bigbluebutton-client/src/org/bigbluebutton/core/UsersUtil.as
- bigbluebutton-client/src/org/bigbluebutton/core/services/UsersService.as
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCallbacks.as
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCalls.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/ConfigParameters.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/PortTestProxy.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/DependancyResolver.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModuleDescriptor.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModuleManager.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesDispatcher.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/modules/ModulesProxy.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/BBBUser.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/LoadingBar.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollDataProcessor.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/util/i18n/ResourceUtil.as
1. Do cleanup by removing debug logs.
2. Log flash player capabilities.
> Log flash capabilities

- bigbluebutton-config/web/index.html
Updating index.html for upcoming BigBlueButton 1.0-beta
> Added Chat, Emoji, and Polling to index page

- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_poll.coffee
- added outer white-space so that it looks like in the Flash client
- corrected 'Public' button in the private chat tab
> Polling shape correction

- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/PresentationClientMessageSender.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
> Fix max upload pages

- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/UserClientMessageSender.java
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/ConnectionInvokerService.java
- bigbluebutton-apps/src/main/resources/logback-bigbluebutton.xml
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
Add more logs to investigate issue where once in a while the message to the client is never sent from Red5.
> Allow changing loglevels

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
For every case in the "upload" method we add an HTTP header and body to avoid having a 404 status when getting the response back from the server. It should resolve #2732
> Presentation upload returns a 200 HTTP status.

- bigbluebutton-client/resources/prod/BigBlueButton.html
Apply fix for #2832 to BigBlueButton 0.9.1
> Apply fix for #2832 to BigBlueButton 0.9.1

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/main.coffee
- bigbluebutton-html5/app/client/stylesheets/chat.less
- Fixed a bug with hidden chat messages after switching from portrait to landscape orientation
- Fixed a bug with shrinking chatbody while typing chat message in portrait, or switching to portrait from landcape when a long message has already been typed but not sent
- Removed horizontal scrolling from the chat in the mobile view, as long chat messages were displayed out of the chat window.
> Chat improvements

- bigbluebutton-config/bin/bbb-conf
> Fixed #2835

- bigbluebutton-html5/app/server/collection_methods/meetings.coffee
- bigbluebutton-html5/app/server/collection_methods/users.coffee
- bigbluebutton-html5/app/server/redispubsub.coffee
- bigbluebutton-html5/app/server/user_permissions.coffee
-fixed the permissions check on the server side (param names had to be adjusted)
-added extra condition on user join related to the bug with extra users in the html5 client
-improved logs for debugging of the userlist with extra users bug in the html5 client
> html5client: user join and lock settings changes

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/lib/bbb_api_bridge.coffee
- bigbluebutton-html5/app/server/collection_methods/chat.coffee
- bigbluebutton-html5/app/server/collection_methods/meetings.coffee
- bigbluebutton-html5/app/server/collection_methods/users.coffee
- bigbluebutton-html5/app/server/user_permissions.coffee
-Use upsert when adding to the meeting, users and chat collections to avoid race condition in {find + insert}
-clearing userName in getInSession - use the one from minimongo
> html5client: use upsert to avoid race cond

- bigbluebutton-client/resources/prod/lib/sip.js
Adds a candidate timeout and updates stream.stop() to match the new format.
> Updated SIP.js to match master

- bigbluebutton-html5/app/client/stylesheets/chat.less
- bigbluebutton-html5/app/client/stylesheets/modals.less
- bigbluebutton-html5/app/client/stylesheets/variables.less
- bigbluebutton-html5/app/client/views/modals/modals.html
- fix UI discrepancies with Firefox
- move some magic numbers into variables
- uniform height for matching components
> Settings Modal Adjustments

- bigbluebutton-html5/app/server/collection_methods/meetings.coffee
- bigbluebutton-html5/app/server/redispubsub.coffee
- bigbluebutton-html5/app/server/server.coffee
-fix a function definition bug
-keep track of queue length
-omit some messages from entering the queue
-cleaning up
> html5client:Queue updates

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/views/chat/chat_bar.html
- bigbluebutton-html5/app/client/views/modals/modals.coffee
- bigbluebutton-html5/app/client/views/whiteboard/slide.coffee
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_paper.coffee
- Fixed the problem when tall slides weren't displayed on the first client load
- Added font-size changes to the input text area and adjusted resizing to it
> Slide Loading and Resizing corrections

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/src/org/bigbluebutton/main/views/ShortcutHelpWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
Minor Client fixes, one them contains a fix for #2847
> Minor Client fixes

- bigbluebutton-html5/app/server/collection_methods/presentations.coffee
There was a change on akka-bbb-apps to which we now adapted. Slide switching works again
> html5client:fix presentation slide change from html5 presenter

- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- Fixes broken emoji icons (removes thin black lines).
- Fixes the sizing of Exit Fullscreen button.
- Optimizes LESS code of emoji animations (puts opacity animation into a for loop).
> HTML5 client: UI bug fixes and some code optimization.

- bigbluebutton-html5/app/.meteor/packages
- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.coffee
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
Client-side work for the HTML5 client for the presentation uploader functionality
> Work on HTML5 client file uploader for presenters.

- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
Corrects a bug introduced in https://github.com/bigbluebutton/bigbluebutton/pull/2849
> Correct the presentation back button enabled check

- bigbluebutton-html5/app/client/stylesheets/users.less
> Fix a bug introduced on the user list design changes on HTML5

- bigbluebutton-html5/app/client/stylesheets/style.less
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/stylesheets/whiteboard.less
- bigbluebutton-html5/package.json
- Updates Grunt configuration to make its setup easier.
- Gets the missing hamburger button and presentation title back to the mobile navbar.
- Updates the color scheme and border radius of the userlist menu on mobile.
- Changes the way the currently active emoji button is highlighted.
> HTML5 client: Grunt configuration update + UI bug fixes and adjustments.

- bigbluebutton-html5/app/client/globals.coffee
- bigbluebutton-html5/app/client/stylesheets/users.less
- bigbluebutton-html5/app/client/views/users/user_item.coffee
- bigbluebutton-html5/app/client/views/users/user_item.html
- bigbluebutton-html5/app/server/collection_methods/users.coffee
- bigbluebutton-html5/app/server/user_permissions.coffee
This adds the set presenter to the html5
In order to set a presenter, the user must be a moderator.
> Add set presenter to HTML5

- bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/handlers/AbstractPageConverterHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/handlers/Pdf2PngPageConverterHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/handlers/Png2SwfPageConverterHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java
Updated faulty PDF file conversion mechanism. Now, we  go through the following process:
- Extract the PDF page to a single PDF file.
- Convert the PDF file to a PNG image.
- Conert the PNG image to a SWF file.
> Updated faulty PDF file conversion mechanism

- bigbluebutton-config/bin/bbb-conf
> Made bbb-conf more resilient to commented parameters

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/common/TabIndexer.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/ToolbarPopupButton.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/UserGraphicHolder.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/VideoDock.mxml
#2898 is general accessibility fixes for things new to 1.0
#2788 is an exception thrown when you press ctrl+k in the chat window
#2789 is focus moving around when you press ctrl+s to send your chat message
> Fixes for issues #2898, #2788, #2789

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/ImageToSwfSlide.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/PageConverter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/PdfToSwfSlide.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/ImageMagickPageConverter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Jpeg2SwfPageConverter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Office2PdfPageConverter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/PdfPageToImageConversionService.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Png2SwfPageConverter.java
Fix issue https://github.com/bigbluebutton/bigbluebutton/issues/2965
Number of conversion threads can now be configured through bigbluebutton.properties
> Improve pdf2swf conversion

- akka-bbb-apps/src/main/java/org/bigbluebutton/core/service/recorder/RedisDispatcher.java
- akka-bbb-apps/src/main/resources/application.conf
- akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/RecorderActor.scala
- bbb-video/src/main/java/org/bigbluebutton/app/video/EventRecordingService.java
- bbb-video/src/main/webapp/WEB-INF/bigbluebutton-video.properties
- bbb-video/src/main/webapp/WEB-INF/red5-web.xml
- deskshare/app/src/main/java/org/bigbluebutton/deskshare/server/recorder/EventRecorder.java
- deskshare/app/src/main/webapp/WEB-INF/deskshare.properties
- deskshare/app/src/main/webapp/WEB-INF/red5-web.xml
Fix for issue https://github.com/bigbluebutton/bigbluebutton/issues/2962
> Expire redis keys after 14 days

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/views/LayoutsCombo.mxml
This pull request include fix for issue #2768
> Fixes #2768

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
* Added 4 pixels between the chat time and the right border
* Unbolded the lock settings categories in the popup
* Reduced the chat cue volume to 30%
* Shortened the copyright string in the client footer
> Minor UI changes for the Flash client

- bigbluebutton-html5/app/client/globals.js
- bigbluebutton-html5/app/client/lib/bbb_api_bridge.js
- bigbluebutton-html5/app/client/main.js
- bigbluebutton-html5/app/client/views/whiteboard/slide.js
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.js
- bigbluebutton-html5/app/client/whiteboard_models/utils.js
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_ellipse.js
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_paper.js
- bigbluebutton-html5/app/client/whiteboard_models/whiteboard_text.js
- bigbluebutton-html5/app/server/collection_methods/slides.js
- bigbluebutton-html5/app/server/server.js
- Fixed the bug with slide still displaying after the presentation's removal.
- No more exceptions while switching between uploaded presentations.
- Optimized the whiteboard's flow and removed duplicated function calls.
- Returned polling buttons back.
> Fixes for issues #2955, #2942, #2941

- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/service/PresentationService.java
Pulling in @fcecagno 's changes to fix exception that kills MeetingActor.
https://github.com/mconf/bigbluebutton/commit/f673122da28d49f4f21fae7b94855c74acc171a5#diff-15703d5a01a0898c78a617696fbedfd3
> Guard against na n in presentation messages

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/resources/prod/BigBlueButton.html
- bigbluebutton-client/resources/prod/lib/bigbluebutton.js
- bigbluebutton-client/src/org/bigbluebutton/main/model/ShortcutOptions.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/ShortcutHelpWindow.mxml
* Fixed the labelling on the HTML "Focus the client" button
* Added a CSS class to hide the "Ready" text
* Darkened the fonts in the client to increase the contrast
* Increased the starting size of the ShortcutWindow
> Four minor accessibility fixes

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AddChatTabBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
> Show chat options tab when private chat disabled

- bigbluebutton-web/src/groovy/org/bigbluebutton/api/RecordingServiceHelperImp.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Recording.java
- bigbluebutton-web/web-app/WEB-INF/freemarker/get-recordings.ftl
- record-and-playback/presentation/scripts/process/presentation.rb
- record-and-playback/presentation/scripts/publish/presentation.rb
I screwed up my master before the merge was applied. I restored it from a snapshot.
https://github.com/bigbluebutton/bigbluebutton/pull/3013
> Fix for bugs related to new states for recordings

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/services/MessageReceiver.as
Fix bigbluebutton/bigbluebutton#2710
> Fix bigbluebutton/bigbluebutton#2710

- bbb-api-demo/src/main/webapp/demo11.html
As reported in https://github.com/bigbluebutton/bigbluebutton/issues/2892
> Added missing div to fix WebRTC audio for JavaScript API demo

- bigbluebutton-html5/app/client/globals.js
- bigbluebutton-html5/app/client/main.html
- bigbluebutton-html5/app/client/views/users/user_item.html
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.html
- bigbluebutton-html5/app/client/views/whiteboard/whiteboard.js
- bigbluebutton-html5/app/server/collection_methods/users.js
- bigbluebutton-html5/app/server/server.js
I've been working on the Mconf version of the HTML5 client and I'm sending some changes back to make our life easier when we need to integrate the code.
The first commit removes some extraneous function calls that would cause Meteor errors.
The second commit refactors the emoji/icon code a little so it isn't repeated every time we add a new emoji. New emojis can be added by simply creating a new entry on the array returned by emojiIcons(). The icon templates were broken up a bit and new ones can be added without the need of adding new if/else clauses.
> HTML5: Small corrections to userUpdateVoice and emoji refactoring

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/services/MessageReceiver.as
Stop applying initial layout to moderators. bigbluebutton/bigbluebutton#2710
> Stop applying initial layout to moderators. 

- bbb-lti/grails-app/conf/lti.properties
- bbb-lti/grails-app/controllers/org/bigbluebutton/ToolController.groovy
- bbb-lti/grails-app/services/org/bigbluebutton/LtiService.groovy
- bbb-lti/lti.nginx
- Fixed issue with app not responding to https requests
- Added configuration for ignoring/considering lti key/secret
- Extended logParameters to show them ordered
It also requires a change in /etc/tomcat7/server.xml in order to support https. It has been deployed (and tested) into test-install
> bbb-lti: Implemented improvements to the LTI integration

- bigbluebutton-client/src/org/bigbluebutton/main/views/ShortcutHelpWindow.mxml
> Refresh the shortcuts ArrayCollection.

- .gitignore
- clients/flash/build.gradle
- clients/flash/common-library/build.gradle
- clients/flash/settings.gradle
- clients/flash/web-client/build.gradle
Created a multi-project gradle for common-library and web-client
How to compile?
```
gradle build createHtmlWrapper
```
> Gradlefx for the Flex 4 client

- clients/flash/air-client/build.gradle
- clients/flash/common-library/build.gradle
- clients/flash/settings.gradle
- clients/flash/web-client/build.gradle
- Fixed source directories.
- Mobile client is now built with minimal configuration using GradleFx.
> Gradlefx build update the Flex 4 client

- record-and-playback/core/scripts/utils/gen_webvtt
- record-and-playback/presentation/scripts/process/presentation.rb
- record-and-playback/presentation/scripts/publish/presentation.rb
This is the initial set of processing scripts to handle closed caption events.
It currently does simple "pop-on" style caption tracks.
The actual code in the playback html/js to load the captions and display them isn't yet completed, it'll be added later.
> Recording captions processing scripts

- bigbluebutton-client/src/org/bigbluebutton/main/views/VideoWithWarnings.as
* Added callback getters to VideoWithWarnings
> Correction to #3074

- bigbluebutton-html5/Gruntfile.js
- bigbluebutton-html5/client/main.jsx
- bigbluebutton-html5/imports/locales/index.js
- bigbluebutton-html5/imports/startup/client/routes.js
- bigbluebutton-html5/imports/ui/components/media/MediaContainer.jsx
- bigbluebutton-html5/package.json
- Sets the linter to rerun only on the files that have been modified since the last check.
- Adds additional Grunt commands to run the linter without starting Meteor.
- Fixes a few linter warnings.
> HTML5 Client: Build Setup Update.

- akka-bbb-apps/src/main/resources/application.conf
- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- bbb-screenshare/.gitignore
- bbb-video/build.gradle
- bigbluebutton-client/resources/prod/lib/verto_extension_share.js
- bigbluebutton-html5/package.json
- video-broadcast/.gitignore
- video-broadcast/build.gradle
-fix build for video-broadcast
-use updated common-messages in bbb-video
-add to .gitignore files
-html5 avoid using sudo for npm
-html5 add a required package
-webrtc deskshare - use more appropriate resolution, fps
...
> adjust configurations (post 1.0)

- akka-bbb-apps/src/universal/conf/application.ini
Need to tell service location of application config.
> Setup application config

- bigbluebutton-config/bin/bbb-conf
- bigbluebutton-config/bin/bbb-record
Updated bbb-conf to support BigBlueButton 1.1-dev on Ubuntu 16.04.  Most of the changes were switching from init.d to systemd stop/restart.
> Updates BigBlueButton 1.1-dev

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/resources/prod/lib/sip.js
This pull request upgrades sip.js to 0.7.5 (newest release).
While this code works, I had to include a workaround for https://github.com/bigbluebutton/bigbluebutton/issues/3204 because no STUN/TURN server(s) are returned.
> Upgrade sip.js to 0.7.5

- bigbluebutton-html5/client/main.html
- bigbluebutton-html5/imports/api/common/server/helpers.js
- bigbluebutton-html5/imports/api/slides/server/modifiers/addSlideToCollection.js
- bigbluebutton-html5/imports/startup/client/routes.js
- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/app/service.js
- bigbluebutton-html5/imports/ui/components/whiteboard/slide/component.jsx
- Added a check to see if the slide file exists before trying to retrieve its dimensions ( #3206 )
- Added a white background for the slide as it's transparent in some cases
- Added a viewport
> Minor fixes

- bigbluebutton-client/resources/prod/lib/bbb_api_bridge.js
- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCallbacks.as
- Need to pass sessionToken to get stuns for webrtc call.
Fixes #3204
>   Fix issue 3204

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/JsonMessageSenderActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/OutMessages.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutRoomApp.scala
- bbb-common-message/src/main/java/org/bigbluebutton/messages/payload/CreateBreakoutRoomRequestPayload.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/MeetingMessageHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java
If the parent meeting is recorded, record also the breakout rooms.
>  Record breakout rooms

- bigbluebutton-client/src/org/bigbluebutton/core/managers/ConfigManager2.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ScreenshareManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ViewerWindowManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/ScreenshareService.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
When the client loads the config.xml, initialize how the client logs.
> Fix client logging

- bbb-screenshare/jws/webstart/src/main/java/org/bigbluebutton/screenshare/client/ScreenRegionSharer.java
- bbb-screenshare/jws/webstart/src/main/java/org/bigbluebutton/screenshare/client/net/NetworkHttpStreamSender.java
- bbb-screenshare/jws/webstart/src/main/java/org/bigbluebutton/screenshare/client/net/NetworkStreamSender.java
Fred is still running into the issue. Add more logs to figure out the sequence
of events when sharing starts.
>  Screenshare issue when starting first time on Mac

- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ScreenshareManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ViewerWindowManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/ScreenshareService.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/red5/Connection.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
Remove filename information when logging as the logger already includes it.
>  Cleanup Logs

- bbb-screenshare/jws/webstart/src/main/java/org/bigbluebutton/screenshare/client/net/NetworkHttpStreamSender.java
- bbb-screenshare/jws/webstart/src/main/java/org/bigbluebutton/screenshare/client/net/NetworkStreamSender.java
Comment out update logs to minimize noise in the logs.
>  Cleanup logging

- bigbluebutton-html5/config.js
- bigbluebutton-html5/imports/api/slides/server/modifiers/addSlideToCollection.js
- bigbluebutton-html5/imports/startup/server/index.js
- bigbluebutton-html5/imports/startup/server/logger.js
We need to know the type of connection for the slide dimension calculation process
> html5client:Add httpS flag in config instead of detecting prod vs dev env

- bbb-api-demo/src/main/webapp/demo12.jsp
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/RecordingService.java
Fix for issue #3148 and some other minor patches for using dynamic configXML
> bbb-web: fix config xml

- bigbluebutton-config/cron.daily/bigbluebutton
Some of the stuff has gotten moved around in the 1.1 dev process.
> Use correct directories and service names in daily cron

- bigbluebutton-client/src/ScreenshareStandalone.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/services/ScreenshareService.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
- fix issue where client throws exception when connection to screenshare gets disconnected.
> client throws exception when connection to screen share disconnects

- record-and-playback/core/lib/recordandplayback.rb
- record-and-playback/core/scripts/sanity/sanity.rb
Logger was apparently imported by the matterhorn stuff ?! so move that
to the main library.
Fix a variable reference in sanity.
> Fix errors in recording scripts.

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/main/views/LoggedOutWindow.mxml
- User in not redirected automatically to the logoutURL
- Imporved logout message for breakout room.
> User in not redirected automatically to the logoutURL

- bigbluebutton-html5/imports/ui/components/dropdown/list/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/trigger/component.jsx
> [HTML5] Fix SPACE/ENTER behavior

- bigbluebutton-html5/imports/ui/components/logout-confirmation/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/styles.scss
- bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
- bigbluebutton-html5/imports/ui/services/auth/index.js
HTML5 Dropdown - fixed warnings and added style
> HTML5 Dropdown - fixed warnings and added style

- bbb-lti/lti.nginx
Change required for addressing issue 3361
> bbb-lti: Fixed bug in nginx configuration that prevented https of working fine

- bigbluebutton-html5/private/config/public/app.yaml
Replaced \r with HTML <br /> tags to fix formatting.
> HTML5 - Welcome Chat Message Fixed

- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
HTML5 - Dropdown List : fixed a bug which is not opened the list at the first time
> HTML5 - Dropdown List 

- akka-bbb-apps/src/main/resources/application.conf
- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/JsonMessageSenderActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/LiveMeeting.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/Protocol.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/ProtocolMessages.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/OutMessages.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutRoomApp.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutRoomModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PresentationApp.scala
- bbb-common-message/src/main/java/org/bigbluebutton/messages/payload/CreateBreakoutRoomRequestPayload.java
- bbb-common-message/src/test/java/org/bigbluebutton/messages/CreateBreakoutRoomRequestTest.java
- bigbluebutton-web/build.gradle
- bigbluebutton-web/grails-app/conf/spring/resources.xml
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/MeetingMessageHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/GhostscriptPageExtractor.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
- Breakout rooms use current presentation slide as default presentation.
- Updated NuProcess dependency to version 1.1.0
- Generated PDF pages are under `pds` instead of `svgs/tmp`
> Breakout rooms use current presentation slide

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- bigbluebutton-web/src/groovy/org/bigbluebutton/api/RecordingServiceHelperImp.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Extension.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Recording.java
- bigbluebutton-web/web-app/WEB-INF/freemarker/get-recordings.ftl
- record-and-playback/core/lib/recordandplayback/generators/presentation.rb
- record-and-playback/presentation/scripts/process/presentation.rb
- record-and-playback/presentation/scripts/publish/presentation.rb
It is being tested through the new integrations.
It needs to be reviewed before merge
> Extension preview for thumbnails on recordings

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/Util.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
Complete PR #3397 with missing commits
> Breakout rooms use current presentation - part 2

- bigbluebutton-html5/client/main.jsx
> fixed console log error

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
> HTML5 - actions_dropdown component

- bigbluebutton-config/bin/bbb-conf
bbb-conf stops and starts redis server & checks video and freeswitch recordings directories
> Update to bbb-conf for --check, --stop and --start

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/core/model/Config.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/managers/UsersManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/model/BreakoutRoomsOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/model/UsersOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/BreakoutRoomSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
Move client breakout rooms configuration to a new node and added a new option to enable/disable recordings for breakout rooms.
> Added flag to config.xml to enable/disable the visibility of the Record option

- bigbluebutton-web/web-app/WEB-INF/freemarker/get-recordings.ftl
record-and-playback: Removed preview extension (thumbnails) from recordings when only has default presentation
> bbb-web: Escaped strings used in freemarker template for thumbnails

- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
Add log to track why client hangs connecting to Red5.
>  - add log to indicate successful connection to bbb-apps

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
When the HTML5 client is loaded, the Actions button and its related options are not rendered unless the user is a Presenter.
> Actions button only available to Presentor

- bigbluebutton-html5/imports/api/presentations/server/modifiers/addPresentation.js
- bigbluebutton-html5/imports/api/presentations/server/modifiers/removePresentation.js
- Fix bug where removed presentations were not removed correctly from the collection
- Fix bug where new presentations were duplicated in the collection
> [HTML5] Fix bug related to presentation handlers

- bigbluebutton-html5/imports/api/phone/index.js
- bigbluebutton-html5/imports/api/phone/server/getStun.js
- bigbluebutton-html5/imports/api/users/server/methods/unmuteUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/updateVoiceUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/userJoined.js
- bigbluebutton-html5/imports/locales/index.js
- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/container.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/audio-settings/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/join-audio/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/listen-only/component.jsx
- Join Audio button switches to Leave audio after joining in audio or listen only
- Joining in audio will display the mute/unmute button options (listen only has no muting options)
- Mute button switches to unmute depending on status
- Leave audio properly exits the call, user is able to rejoin after exiting
> Mute, Unmute, Leave Audio

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/MeetingActor.scala
The first schedule is set to after 5 seconds then all to 10 seconds.
> Update schedule period of MonitorNumberOfWebUsers.

- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/container.jsx
- bigbluebutton-html5/imports/ui/components/settings/service.js
The settings menu now renders options based on weather the user is a Presenter/Moderator or Viewer.
Audio, Video and Application setting options can be seen by all users.
Participants setting option is only visible to Presenter/Moderator.
> Settings menu options - Presenter/Moderator vs Viewer

- bigbluebutton-html5/imports/api/captions/server/modifiers/eventHandlers.js
- bigbluebutton-html5/imports/api/cursor/server/publishers.js
- bigbluebutton-html5/imports/startup/server/logger.js
- bigbluebutton-html5/private/config/development/server/log.yaml
- bigbluebutton-html5/private/config/production/server/log.yaml
Updated Winston logger configuration, set levels and colors.
Included changes to set messages to 'debug'.
> New logger levels

- bigbluebutton-html5/client/main.css
Add CSS rule for elements with `[hidden]` and `[aria-hidden]` attributes.
> [HTML5] Fix style for hidden/aria-hidden attributes

- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/audio-settings/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/listen-only/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/styles.scss
- bigbluebutton-html5/imports/ui/components/audio-test/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-test/container.jsx
- bigbluebutton-html5/imports/ui/components/enter-audio/component.jsx
- bigbluebutton-html5/imports/ui/components/enter-audio/container.jsx
- bigbluebutton-html5/imports/ui/components/mic-source/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/styles.scss
- bigbluebutton-html5/imports/ui/components/settings/submenus/audio/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/submenus/styles.scss
- bigbluebutton-html5/imports/ui/components/speaker-source/component.jsx
- bigbluebutton-html5/imports/ui/components/stream-volume/component.jsx
I've broken down the Audio settings into separate components. 5 new components have been added which are used in the audio-settings and audio-modal
< MicSource />
< SpeakerSource />
< StreamVolume />
< AudioTest />
< EnterAudio />
> Added audio-setting components

- bigbluebutton-client/src/org/bigbluebutton/common/CustomMdiWindow.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/BBBUser.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/maps/LayoutEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/services/MessageReceiver.as
- New attendees get their layout locked;
- Double clicking top overlay won't maximize a window;
- Right clicking won't show minimize/maximize options; and
- Changing presenter will update lock settings.
I think this relates at least to #3188 and #3464
> Fixed some layout lock issues

- bigbluebutton-config/bin/bbb-conf
Updated bbb-conf for detecting when FreeSWITCH is not responding to event socket commands on 8021.
> Updated bbb-conf to detect problems with FS on 8021

- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMapDelegate.as
> Fix double display of webcams on reconnect #3250

- bigbluebutton-html5/imports/locales/en.json
- bigbluebutton-html5/imports/ui/components/button/styles.scss
- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
- bigbluebutton-html5/imports/ui/components/chat/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/component.jsx
I've made changes to the UI based on the suggestions Tyler provided.
> UI Changes Update

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/slide-controls/component.jsx
To un-comment, move the */ back to the actual comment above each component
> HTML5 - comment out unimplemented presenter slide control UI

- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
added muted/unmuted button for the current user
> HTML5 Client userlist - added muted/unmuted button for the current user

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonInGW.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/MeetingModel.scala
- akka-bbb-apps/src/test/scala/org/bigbluebutton/core/AppsTestFixtures.scala
- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/Constants.java
- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/CreateMeetingMessage.java
- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/MessageFromJsonConverter.java
- bbb-common-message/src/main/java/org/bigbluebutton/messages/CreateMeetingRequest.java
- bbb-common-message/src/test/java/org/bigbluebutton/messages/CreateMeetingRequestTest.java
- bigbluebutton-client/src/org/bigbluebutton/core/model/Meeting.as
- bigbluebutton-client/src/org/bigbluebutton/core/model/MeetingBuilder.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/MeetingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Meeting.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/Constants.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/MessageToJson.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/MessagingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/RedisMessagingService.java
- bigbluebutton-web/src/java/org/bigbluebutton/api/messaging/converters/messages/CreateMeetingMessage.java
Only the moderator is able to see webcam streams, whether he shares his stream or receives other streams.
> Webcams only for moderator

- bbb-client-check/resources/lib/api-bridge.js
Add handlers for BBB.webRTCCall* calls which are needed for the WebRTC Echo (and Socket) tests
> Bbb-client-check add missing functions for WebRTCEchoTest

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/model/LayoutDefinition.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
* changed screenshare help text from Label to Text so they can be multi-line and gave them a set width to force text wrapping
* added ScreensharePublishWindow and ScreenshareViewWindow to the layout exclusion list and removed DesksharePublishWindow and DeskshareViewWindow
> Fixes for #3546 and #3547

- bbb-api-demo/src/main/webapp/bbb_api.jsp
- bbb-api-demo/src/main/webapp/demoHTML5.jsp
Only the user name is required
The new field meetingname is pre-filled with "Demo Meeting"
> bbb-api-demo: Allow html5 client demo to join meetings other than Demo Meeting

- record-and-playback/presentation/playback/presentation/0.9.0/lib/writing.js
- record-and-playback/presentation/playback/presentation/0.9.0/playback.js
> Restoring annotations when swapping presentation with video

- bbb-api-demo/src/main/webapp/demoHTML5.jsp
Missed some code when committing #3564
> bbb-api-demo: addition to pr 3564

- bbb-api-demo/src/main/webapp/bbb_api.jsp
- bbb-api-demo/src/main/webapp/demoHTML5.jsp
Adding a checkbox allowing the user to join as moderator (default = unchecked -> attendee)
> bbb-api-demo: Add parameter to join html5 client as moderator

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
Change the static text to a localized version.
Fixes #3578
> Add custom poll option text to locales

- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMapDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/GraphicsWrapper.as
This pull request is the proper fix for #3515. It also reverts a previous fix attempt which resulted in issue #3572.
> Filter out webcam duplicates. Also fixes #3572

- bigbluebutton-html5/imports/ui/components/whiteboard/slide-controls/styles.scss
changed arrow color of presentation
> HTML5 - arrow key of presentation

- bigbluebutton-client/resources/prod/BigBlueButton.html
Fixes #3593 (follows @capilkey 's suggestion)
> recover redirect to html5 client on android device

- record-and-playback/presentation/playback/presentation/0.9.0/lib/popcorn.chattimeline.js
> In recording playback, chat links open in a new tab

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
> Escaping Java's properties file instructions

- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/ClientMessage.java
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/ConnectionInvokerService.java
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/DisconnectAllClientsMessage.java
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/DisconnectAllMessage.java
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/client/messaging/DisconnectClientMessage.java
Handle exceptions properly when sending message to client. We were not handling the
exception so when it occured, the thread stopped and we can't send messages from
server to client anymore.
>  Handle exception when sending message to client

- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
- bigbluebutton-html5/imports/ui/components/button/component.jsx
- bigbluebutton-html5/imports/ui/components/button/styles.scss
The mute button style changes when a voice user is talking and reverts back to its normal style when the user stops talking.
> Mute button glow indicator

- bigbluebutton-html5/imports/api/phone/index.js
- bigbluebutton-html5/imports/locales/en.json
- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-notification/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-notification/container.jsx
- bigbluebutton-html5/imports/ui/components/audio-notification/styles.scss
The user is notified by a red notification bar in the even of an audio failure status,
with the ability to close the notification.
> Audio Error notification

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
> fix bug preventing stun/turn call. Fixes #3627

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
> Link "enableEmojiStatus" enabled/disabled to the emoji button.

- akka-bbb-apps/src/main/java/org/bigbluebutton/core/pubsub/receivers/PresentationMessageListener.java
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/core/EventConstants.as
- bigbluebutton-client/src/org/bigbluebutton/main/api/ExternalApiCalls.as
- bigbluebutton-client/src/org/bigbluebutton/main/api/maps/ExternalApiEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/events/OfficeDocConvertInvalidEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/Constants.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/messaging/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
- bigbluebutton-web/build.gradle
- bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/ConversionMessageConstants.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/DocumentConversionServiceImp.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/OfficeToPdfConversionSuccessFilter.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/UploadedPresentation.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/OfficeDocumentValidator.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java
> Avoid converting some pptx files with certain properties and inform the user.

- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
- bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
changed divider of recorded icon
> HTML5 - changed divider of recorded icon

- bigbluebutton-html5/imports/ui/components/chat/message-list/styles.scss
- Removed unwanted right margin spacing in chat list
> Chat List Scrollbar Fix

- bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
This fixes the bug where the chat box doesn't scroll to the bottom automatically.
> HTML5 - Chat scroll fix

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PresentationApp.scala
when we get invalid coordinate for presentation slide, change coordinate so it falls within bounds
>  Fix issue where presentation page is displayed incorrectly

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PresentationApp.scala
Forgot to assign the values correctly.
>  Fix presentation slide coordinates

- bigbluebutton-html5/imports/locales/en.json
- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/audio-modal/join-audio/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
Have not touched the Settings labels since that component is being reworked
> HTML5: Localization of labels in audio and chat areas

- bigbluebutton-web/src/groovy/org/bigbluebutton/api/RecordingServiceHelperImp.groovy
- bigbluebutton-web/src/java/org/bigbluebutton/api/domain/Recording.java
- bigbluebutton-web/web-app/WEB-INF/freemarker/get-recordings.ftl
- record-and-playback/core/lib/recordandplayback/generators/events.rb
- record-and-playback/presentation/scripts/process/presentation.rb
...in getRecordings call
Resolves #3623
> Returning number of users that participated in each meeting

- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
> Move moderator back to main audio when a breakout room has been ended

- bigbluebutton-client/src/org/bigbluebutton/main/views/CameraDisplaySettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
Fixes the issue where camera list is empty.
> Display camera list

- bigbluebutton-config/cron.daily/bigbluebutton
Remove *meta files from /usr/share/red5/webapps/video/streams
> Remove *.meta files from saved red5 streams

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
changed the location of slide's arrow buttons
> HTML5 - changed the location of slide's arrow buttons

- bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
- bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/updateVoiceUser.js
Fix bugs introduced on #3684.
- Multiple welcome messages when refreshing the browser
- Audio messages not updating the collection
- Ghost users on the HTML5 meeting
> [HTML] Fix bugs related to the Users API

- bigbluebutton-html5/imports/api/chat/server/publishers.js
- bigbluebutton-html5/imports/api/polls/server/publishers.js
- bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/startup/server/userPermissions.js
- corrected permissions for presenter ( setPresenter should only be allowed to moderators )
- fixed these exceptions:
> HTML5 - permissions/exceptions fixes

- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/audio-menu/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
- bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
Mute button returns null if not in Mic Audio, because of this the flex box keeps the available buttons centered.
Moved the exitAudio API to the container.
> Actions Bar Positioning

- bigbluebutton-client/src/org/bigbluebutton/main/model/users/BreakoutRoom.as
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/Conference.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/RoomActionsRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
- Kick user feature is now disabled in breakout rooms.
- Non-moderator role can ask for an invitation to the last breakout room he were in.
> Breakout rooms improve for viewer role

- bigbluebutton-client/branding/default/style/css/BBBDefault.css
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
The main shell and footer are also dark in "Video Chat" layout.
> Black video chat layout update

- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/TextDrawAnnotation.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/TextDrawListener.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardTextToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/buttons/TextButton.mxml
It is now possible to use the text tool for the whiteboard using a single mouse click in addition to drag to draw a text zone.
> Whiteboard text tool update

- bigbluebutton-config/bin/bbb-conf
Fixed https://github.com/bigbluebutton/bigbluebutton/issues/3777
> Update calculation for free memory

- bigbluebutton-html5/imports/api/polls/server/modifiers/updateVotes.js
Fix poll options remain visible on html5 when published.
> Fix poll options remain visible on html5, closes #3806 HTML5

- bigbluebutton-web/src/java/org/bigbluebutton/presentation/handlers/AbstractPageConverterHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/handlers/Pdf2SwfPageConverterHandler.java
- bigbluebutton-web/src/java/org/bigbluebutton/presentation/imp/Pdf2SwfPageConverter.java
> Make sure that blank swf is loaded if fallback document conversion does not work.

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
Also replaced MDIWindows of the new screenshare to use BBB's CustomMdiWindows where there is some extra controls.
Related to #3803.
> Fixing stack overflow when opening screenshare window

- bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
Fix the problem on offline avatar, being display incorrect on chat and under messages.
> Fix avatar issue in chat, HTML5 #3830

- bigbluebutton-html5/imports/ui/components/app/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/styles.scss
Truncate user name and chat name
> HTML5 - Truncate user name and chat name

- bigbluebutton-html5/imports/ui/components/chat/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/list/title/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
- bigbluebutton-html5/private/locales/en.json
Added a DropdownListTitle component. 
Makes it so that the userListItem menu title is unfocusable and gets announced by the screen reader.
> [HTML5] - Accessibility update 05

- bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx
Fix the problem on the chat not displaying the correct offline status
> HotfixChat, HTML5 issues #3829

- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
- bigbluebutton-html5/imports/api/audio/client/bridge/verto.js
- bigbluebutton-html5/imports/api/audio/client/manager/index.js
- bigbluebutton-html5/imports/ui/components/audio/service.js
> HTML5: Fix issue with listenOnly not hanging up

- bigbluebutton-client/resources/prod/BigBlueButton.html
This PR forces Flash to launch in Edge 15+ to fix #3812.
> Force Flash on Edge 15+

- clients/flash/air-client/generate_css_dpi.sh
- clients/flash/air-client/src/css/hdpi.css
- clients/flash/air-client/src/css/ldpi.css
- clients/flash/air-client/src/css/mdpi.css
- clients/flash/air-client/src/css/xxhdpi.css
- clients/flash/air-client/src/css/xxxhdpi.css
- Added a shell script to generate multi-resolution css files.
- Added generated css files for the mobile client.
> Mobile resolutions css files

- bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss
fixed display unread count for long name user
> HTML5 - fixed display unread count for long name user

- bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
- bigbluebutton-html5/private/locales/en.json
Add a leave button on the error screen, the result can be see below
> Add leave button to error screen

- bigbluebutton-html5/imports/api/audio/client/manager/index.js
- bigbluebutton-html5/imports/api/users/server/modifiers/lockAllViewersMic.js
- bigbluebutton-html5/imports/ui/components/audio/service.js
> HTML5: If microphone lock is enforced, pick listenOnly join over using mic

- bigbluebutton-config/bin/bbb-conf
Also added mongod to `bbb-conf --restart` in bbb-conf
> Remove refs to ghostscript

- bigbluebutton-client/.actionScriptProperties
- clients/flash/air-client/generate_css_dpi.sh
- clients/flash/air-client/src/css/hdpi.css
- clients/flash/air-client/src/css/ldpi.css
- clients/flash/air-client/src/css/mdpi.css
- clients/flash/air-client/src/css/xhdpi.css
- clients/flash/air-client/src/css/xxhdpi.css
- clients/flash/air-client/src/css/xxxhdpi.css
- clients/flash/air-client/src/org/bigbluebutton/air/common/views/NoTabView.as
- clients/flash/air-client/src/org/bigbluebutton/air/main/views/LoadingScreenMediator.as
- clients/flash/air-client/src/org/bigbluebutton/air/main/views/PagesNavigatorViewMediator.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/settings/views/camera/CameraProfileItemRenderer.mxml
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/settings/views/camera/CameraSettingsViewBase.as
- "Back" soft button is now handled for navigation.
- Add new item renderer for video profiles list.client
> [Mobile] - Handle "back" soft button and add item render to video profiles list

- bigbluebutton-html5/imports/ui/services/auth/index.js
- bigbluebutton-html5/private/config/development/public/app.yaml
- bigbluebutton-html5/private/config/production/public/app.yaml
Fix the client reconnection on development, adding timeout config for dev and prod
> Fix client reconnection timeout

- bigbluebutton-client/resources/prod/lib/webrtc_stats_bridge.js
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardTextToolbar.mxml
- bigbluebutton-html5/imports/api/audio/client/bridge/verto.js
- bigbluebutton-html5/imports/ui/services/auth/index.js
- bigbluebutton-html5/private/config/development/public/app.yaml
- bigbluebutton-html5/private/config/production/public/app.yaml
Merge latest master changes into 2x branch.
> Merging latest master branch into 2x branch

- bigbluebutton-client/build.xml
- bigbluebutton-client/resources/prod/BigBlueButton.html
- bigbluebutton-client/src/BigBlueButton.mxml
remove the blue flash screen on client loading.
> flash blue to white screen

- bigbluebutton-html5/imports/ui/components/app/styles.scss
fixed navbar to be displayed on mobile
> HTML5 - fixed navbar to be displayed on mobile

- bigbluebutton-html5/imports/api/users/server/handlers/lockedStatusChange.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
- bigbluebutton-html5/private/locales/en.json
HTML5 - added locked status for users
>  HTML5 - added locked status for users  

- bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/api/users/server/methods/userLogout.js
- bigbluebutton-html5/imports/api/users/server/publishers.js
Handle thrown exception in try-catch block instead of substituting for a warning
> Revisit pull request #3934

- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
HTML5 - removed 'lockedLayout' variable
> HTML5 - removed 'lockedLayout' variable

- bigbluebutton-client/src/org/bigbluebutton/common/IMETextField.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/TextObject.as
Backport of the IME fix to apply it to 1.1 also.
> Backport whiteboard text tool IME fix from PR #3994

- README.md
- bbb-webhooks/README.md
- bigbluebutton-html5/imports/startup/server/userPermissions.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
fixed setPresenter error through HTML5
> HTML5 - fixed setPresenter error through HTML5

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/ShowPollResultReqMsgHdlr.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/polling/service/PollDataProcessor.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/maps/WhiteboardEventMap.mxml
Note - the annotation result is not displayed on the slide after publish but the message arrives to the client and is handled (from what I see) as expected
> 2.0 polls - flash client portion + adjustments on the akka apps model

- bigbluebutton-html5/imports/api/meetings/server/modifiers/removeMeeting.js
- bigbluebutton-html5/imports/api/users/server/publishers.js
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/private/locales/en.json
fixed errors when the meeting is ended by apimate
> HTML5 - fixed errors when the meeting is ended by apimate

- bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/api/users/server/publishers.js
added check that current meeting is existed or not
> HTML5 - added check that current meeting is existed or not

- akka-bbb-apps/src/main/resources/application.conf
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/deskshare/DeskshareRtmpBroadcastStartedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/deskshare/DeskshareRtmpBroadcastStoppedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/deskshare/DeskshareStartedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/deskshare/DeskshareStoppedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserMutedInVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserTalkingInVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/EjectUserFromVoiceCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/RecordingStartedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/AppsRedisSubscriberActor.scala
- akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java
- akka-bbb-fsesl/src/main/scala/org/bigbluebutton/endpoint/redis/AppsRedisSubscriberActor.scala
- akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/RxJsonMsgDeserializer.scala
- akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/RxJsonMsgHdlrActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
- bigbluebutton-client/.actionScriptProperties
- bigbluebutton-client/.project
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- bigbluebutton-web/grails-app/conf/spring/resources.xml
- use webrtc screenshare using FS Verto
- publish screenshare as rtmp to red5
- flash clients view screenshare from red5 rtmp
BONUS:
- Fix mute/unmute/talking of user in voice conference
>  FreeSWITCH webrtc screenshare

- bbb-apps-common/src/main/scala/org/bigbluebutton/client/MsgToClientJsonActor.scala
- bbb-screenshare/app/build.sbt
- bbb-screenshare/app/deploy.sh
- bbb-screenshare/app/src/main/scala/org/bigbluebutton/app/screenshare/ScreenShareApplication.scala
- bbb-screenshare/app/src/main/scala/org/bigbluebutton/app/screenshare/SystemConfiguration.scala
- bbb-screenshare/app/src/main/scala/org/bigbluebutton/app/screenshare/redis/AppsRedisSubscriberActor.scala
- bbb-screenshare/app/src/main/scala/org/bigbluebutton/app/screenshare/redis/IncomingJsonMessageBus.scala
- bbb-screenshare/app/src/main/scala/org/bigbluebutton/app/screenshare/redis/ReceivedJsonMsgHandlerActor.scala
- bbb-screenshare/app/src/main/webapp/WEB-INF/classes/application.conf
- bbb-screenshare/app/src/main/webapp/WEB-INF/classes/screenshare-app.conf
- bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/BigBlueButtonApplication.java
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/maps/WebRTCDeskshareEventMap.mxml
- update red5 screenshare app to use 2.0 messages
> Update jws screenshare

- bigbluebutton-html5/imports/api/1.1/users/server/methods.js
- bigbluebutton-html5/imports/api/2.0/users/server/handlers/emojiStatus.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/setEmojiStatus.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/api/2.0/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/api/2.0/users/server/modifiers/removeUser.js
- bigbluebutton-html5/imports/ui/components/actions-bar/emoji-menu/service.js
- bigbluebutton-html5/imports/ui/components/chat/service.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
On this PR, the following messages are handle:
- Fix
> [HTML5 2.0]  Move emoji messages to 2.0

- bigbluebutton-config/bin/bbb-conf
Update screenshareRtmpServer on bbb-conf --setip
> Bbb 2x mconf

- bigbluebutton-html5/imports/api/2.0/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/startup/client/auth.js
- bigbluebutton-html5/imports/ui/services/auth/index.js
Fixed the problem of user cannot logout in the html5 client.
> [HTML5 2.0] Fix User logout

- bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-item/component.jsx
Fix so JAWS announces users properly, also makes JAWS notify the user if the chat log is empty or not.
> [HTML5] - ARIA fixes to work with JAWS

- bigbluebutton-client/resources/config.xml.template
Referenced by Pedro here in the restore of 1.1 screenshare
https://github.com/bigbluebutton/bigbluebutton/pull/4060#issuecomment-314280782
> Sets showButton to true

- bigbluebutton-client/resources/prod/lib/verto_extension.js
- flash client can access the api
- html5 client passes info when call is made like they do for audio
- if nothing is provided defaults to verto's defaults
> Enable stun/turn use within verto

- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/WebRTCDeskshareManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/utils/WebRTCScreenshareUtility.as
logs out messages in the requirements gathering steps. more detail for messages
> Adds some WebRTC Screenshare logging

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
> bbb_web - modified stun/turn api

- bigbluebutton-client/resources/prod/BigBlueButton.html
- labs/kurento-screenshare/lib/bbb/messages/Constants.js
- labs/kurento-screenshare/lib/bbb/messages/Messaging.js
- labs/kurento-screenshare/lib/bbb/messages/screenshare/ScreenshareRTMPBroadcastStartedEventMessage2x.js
- labs/kurento-screenshare/lib/bbb/messages/screenshare/ScreenshareRTMPBroadcastStoppedEventMessage2x.js
- labs/kurento-screenshare/lib/screenshare.js
The duplicated adapter import was impairing webrtc audio
> Move kurento screenshare messages to 2.0 and removed duplicated adapter import

- bigbluebutton-html5/imports/api/2.0/users/server/handlers/validateAuthToken.js
The welcome message back to show on the HTML5 client, when the user log in.
> [HTML5 2.0] Fix Welcome Messages

- bigbluebutton-config/web/css/style.css
- bigbluebutton-config/web/index.html
Don't know if the spelling was intentional. Nevertheless, could be an unintentional mistake too.
> grammatical error (metting -> meeting)

- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/UserSharedWebcamMessage.java
- bbb-common-message/src/main/java/org/bigbluebutton/common/messages/UserUnshareWebcamRequestMessage.java
- put back old messages as they are still used by video-broadcast and bbb-video. We  can remove them once we've worked on those 2 apps.
>  Fix compile issue with bbb-video and video-broadcast app

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/main/model/options/LayoutOptions.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/model/UsersOptions.as
Hid the network monitor, layout editing, and guest UI elements by default.
> Hide some UI elements by default

- bigbluebutton-html5/imports/api/1.1/audio/client/bridge/sip.js
- bigbluebutton-html5/imports/api/1.1/audio/client/manager/index.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/listenOnlyToggle.js
- bigbluebutton-html5/imports/startup/client/auth.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/audio/service.js
- bigbluebutton-html5/imports/ui/services/auth/index.js
On this PR we manage to handle again the connection between the WebRTC and HTML5 client.
Now we dynamic fetch the stun/turn servers when the user click on the **Listen Only** or **Microphone**, inside the join modal.
> [HTML5 2.0] Fix join audio on the HTML5 client 2.0

- bbb-api-demo/src/main/webapp/demoHTML5.jsp
Applied changes suggested by @mmarangoni
> Use mod and attendee passwords in createMeeting call in demoHTML5.jsp

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
Display time remaining of meeting when duration is not zero.
> Display time remaining

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/EndBreakoutRoomInternalMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/LogoutAndEndMeetingCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/meeting/EndMeetingSysCmdMsgHdlr.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
- fix request breakout url
- log when meeting is ended from api or when user logs out
> Log meeting expiry

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/ChangeLockSettingsInMeetingCmdMsgHdlr.scala
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindowEventHandler.as
- make flash client explicitly send user join message to server
>  - do not send extra messages on validate token response

- akka-bbb-apps/src/main/resources/application.conf
- akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/SharedNotesModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/CreateSharedNoteReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/DestroySharedNoteReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/GetSharedNotesPubMsgHdlr.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SharedNotesMsgs.scala
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/locale/pt_BR/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/events/CurrentDocumentEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/maps/SharedNotesEventMapDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/SharedNotesWindow.mxml
- Fixed multiple notes creation
- Included maximum number of notes control at server side
> Limiting the number of shared notes

- bigbluebutton-html5/imports/api/2.0/users/server/handlers/guestApproved.js
- bigbluebutton-html5/imports/api/2.0/users/server/handlers/validateAuthToken.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/userJoin.js
- Publish `JoinMeetingReqMsg` after the auth token validation
- Publish `JoinMeetingReqMsg` for approved guest users
> [HTML5] Implements the new join flow

- bigbluebutton-html5/imports/api/2.0/meetings/server/eventHandlers.js
- bigbluebutton-html5/imports/api/2.0/meetings/server/handlers/meetingEnd.js
- bigbluebutton-html5/imports/api/2.0/meetings/server/modifiers/removeMeeting.js
The meeting now correct clears the info when ended.
> [HTML5 2.0] Handling meeting end

- bigbluebutton-html5/imports/api/2.0/presentations/server/eventHandlers.js
Without this change the slide does not display in some cases including presentation change
> [HTML5 2.0] Handle PresentationConversionCompletedEvtMsg

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Layouts.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/layout/services/MessageReceiver.as
This PR restricts applying remote layouts to only non-moderators.
> Only apply remote layouts to non-moderators

- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as
This PR makes the whiteboard cursor colour switch correctly with the presenter switch.
> Fix presenter cursor colour

- record-and-playback/presentation/scripts/publish/presentation.rb
This fixes recording generation on BBB 2.0, where there is no longer
an automatic GotoSlide sent after every SharePresentation
> Have presentation recording script remember current slide

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/InMessages.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/BreakoutModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutRoomUsersUpdateMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/SendBreakoutUsersUpdateMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/TransferUserToMeetingRequestHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/BreakoutRoom2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
- bigbluebutton-client/src/org/bigbluebutton/main/model/users/NetConnectionDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindowEventHandler.as
- partial fix to breakout listen in
> breakout listen mode

- bigbluebutton-web/grails-app/conf/BigBlueButtonFilters.groovy
- bigbluebutton-web/grails-app/views/api/error.gsp
<response>
<returncode>503</returncode>
<reason>API Service Unavailable</reason>
</response>
>  - return the following response when api service is unavailable.

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/branding/default/style/css/org/bigbluebutton/skins/PopUpButtonSkin.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/LockSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/managers/ToolbarButtonManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardTextToolbar.mxml
> [Flash 2.0] - Fix file upload window and UI updates2x client theme

- record-and-playback/presentation/playback/presentation/0.9.0/lib/writing.js
- record-and-playback/presentation/scripts/publish/presentation.rb
Main thing here is a rewrite of the shape display javascript in the presentation recording format.
> Bbb 20 rec fixes

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/ClientToServerLatencyTracerMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/WhiteboardMsgs.scala
- bigbluebutton-client/src/org/bigbluebutton/core/events/PerformRttTraceEvent.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/maps/WhiteboardEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/models/WhiteboardModel.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/services/WhiteboardService.as
- send rtt of client to server so we can collect data
>  - trigger sending of rtt from server side

- akka-bbb-fsesl/build.sbt
- bbb-fsesl-client/build.sbt
- bbb-fsesl-client/src/main/java/org/freeswitch/esl/client/inbound/Client.java
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
> Handle renamed stop_talking_handler event from FreeSWITCH

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/RoomActionsRenderer.mxml
Fix issue where user cannot request for a join url for breakout rooms.
> Breakout request join url

- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainCanvas.mxml
>  - reposition screen share publish window

- bigbluebutton-client/resources/prod/BigBlueButton.html
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
SWF was missing a param to make this work
> Flash client's chrome fullscreen fix

- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/business/shapes/Pencil.as
This PR changes the pencil update drawing from individual lineTo commands to one path.
> Draw pencil updates more efficiently

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/jhotdraw/Bezier.java
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/util/jhotdraw/BezierWrapper.java
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml
The pencil smoothing was a little too aggressive and it ended up with some weird results when drawing small shapes. This PR relaxes the pre-smoothing noise reduction which results in a more complicated, but more accurate representation.
I've also tacked on a simple tooltip for the multiuser whiteboard button.
> Relax pencil smoothing

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/SharedNotesModel.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/ClearSharedNotePubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/SharedNotesApp2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/sharednotes/UpdateSharedNoteReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SharedNotesMsgs.scala
- bigbluebutton-client/src/org/bigbluebutton/core/model/SharedNotes.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/events/SharedNotesEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/managers/SharedNotesManager.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/maps/SharedNotesEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/services/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/SharedNotesWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/views/components/SharedNotesRichTextEditor.mxml
- Removed the color picker
- Correctly show the ability to create a new note in all windows
- Cleaning the notes in the client and the server
> Shared notes changes

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
> Resolve issue with unread chat notification not displayed

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- bigbluebutton-client/src/org/bigbluebutton/common/Role.as
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
Fix for #4356 
- disabled promote/demote user
- fixed role so the phone user is no longer marked as presenter
- trigger eject from audio instead of kick web user
> Adjustments for phone user

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserLeftVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala
- fix issue where audio isn't recording if there is already a user joined listen only before a user
joins full duplex.
>  fix issue where audio isn't recording 

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/model/ScreenshareOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreensharePublishWindow.mxml
> Add enablePause="true" for Screenshare

- bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
Need to escape values of the meta portion of the metadata.xml otherwise the xml parser is going to choke.
> Fix escaping of metadata xml

- bigbluebutton-html5/package.json
- bigbluebutton-html5/tests/webdriverio/specs/login.spec.js
- bigbluebutton-html5/tests/webdriverio/utils.js
- bigbluebutton-html5/tests/webdriverio/wdio.conf.js
- There are 5 supported browsers running concurrently now: stable Chrome, dev Chrome, mobile Chrome, stable Firefox, nightly Firefox.
- Some unnecessary repetition is removed (function that types usernames).
- ~~Test command is now a part of the git precommit hook.~~
> [HTML5 Client] Test Update: Support for browser versioning + Code optimization

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
> [Flash 2.0] - Update file upload user experience

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
- bigbluebutton-client/resources/prod/lib/sip.js
This PR updates sip.js to the latest release (0.7.8). I wasn't able to successfully merge in some customizations  to sip.js that we had made, but they should be able to be added again if really needed. The removed customizations can be found in this commit, https://github.com/bigbluebutton/bigbluebutton/commit/21170265e2c8e6d6131da770b37080eed1d0b695#diff-e91f3afaac61b4684f0ec3e037ade572.
> Upgrade sip.js to 0.7.8

- bbb-common-web/src/main/scala/org/bigbluebutton/api2/util/RecMetaXmlHelper.scala
Fix issue introduced in #4403 .
> Convert getRecordings XML to a String.

- bigbluebutton-html5/imports/ui/components/chat/service.js
fixes  a bug where you can't open chat pane: `Cannot read property 'disablePubChat' of undefined`
> [HTML5] - Fix Chat bug

- bigbluebutton-html5/imports/api/2.0/chat/server/methods/clearPublicChatHistory.js
- bigbluebutton-html5/imports/api/2.0/chat/server/methods/sendChat.js
- bigbluebutton-html5/imports/api/2.0/meetings/server/methods/endMeeting.js
- bigbluebutton-html5/imports/api/2.0/polls/server/methods/publishVote.js
- bigbluebutton-html5/imports/api/2.0/slides/server/methods/switchSlide.js
- bigbluebutton-html5/imports/api/2.0/slides/server/modifiers/addSlide.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/assignPresenter.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/requestStunTurn.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/setEmojiStatus.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/userJoin.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/userLeaving.js
- bigbluebutton-html5/imports/api/2.0/users/server/methods/validateAuthToken.js
- bigbluebutton-html5/imports/api/2.0/voice-users/server/methods/listenOnlyToggle.js
- bigbluebutton-html5/imports/api/2.0/voice-users/server/methods/muteToggle.js
- bigbluebutton-html5/imports/startup/server/redis2x.js
adds publishSystemMessage, publishMeetingMessage and publishUserMessage which create their corresponding headers then pass them off to the publish function.
> [HTML5] - header functions update

- bigbluebutton-client/src/org/bigbluebutton/modules/layout/managers/LayoutManager.as
These changes should allow for easier detection/troubleshooting of issues depending on layout specific features (Closed Captions, Shared Notes, etc)
> [Flash Client 2.0] Add client log on layout change

- bigbluebutton-html5/imports/api/2.0/chat/server/handlers/chatPublicHistoryClear.js
This fixes the broken clear chat feature.
issue #4372
> [HTML5] - Fix clear chat feature

- bigbluebutton-html5/imports/ui/components/logout-confirmation/component.jsx
- bigbluebutton-html5/imports/ui/components/logout-confirmation/container.jsx
- bigbluebutton-html5/imports/ui/components/logout-confirmation/service.js
Removes the option to end meeting on logout when user is in a breakout.
> [HTML5] Fix breakout logout

- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/mute-button/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
fixes the bug where the Mute button is rendered for listenOnly users.
> [HTML5] - Mute button fix

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeDocumentValidator2.java
- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
- change location of preschecker
>  - lower timeout timer for validation

- bigbluebutton-html5/imports/ui/services/user/mapUser.js
Fix user mapping for users outside the voiceConf collection.
> [HTML5] Fix bug when user wasnt in voiceConf

- bigbluebutton-html5/imports/ui/components/app/container.jsx
Fix an issue that prevented breakout room tabs from closing when the timer ran out.
> [HTML5] - Fix Breakout tab not closing

- bigbluebutton-client/src/org/bigbluebutton/main/model/options/HelpOptions.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/FlashMicSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/WebRTCEchoTest.mxml
This PR fixes the help URL that is launched so that it uses the value set in config.xml. 
This fixes issue #4409.
> Fix help button URL

- bigbluebutton-html5/imports/api/2.0/audio/client/manager/index.js
Make the format of turn servers (grabbed from bigbluebutton/api/stuns) match expected format (used in Flash)
> [HTML5 client] Modify format of TURN server config for webrtc

- bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
> Updating presenter status

- bigbluebutton-html5/imports/utils/statuses.js
* added missing button icon change on: sad, happy, applause, confused
* reordered the list so it matches the order used in other places in the code
> [HTML5 client] Add missing states in emoji button icon change

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/StatusItemRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
> Less spacing between user renderers buttons

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
from FS as HTML5 client connects with no mic
>  - do not set listenOnly status when receiving user joined voice event..

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala
change how we handle listen only for html5 user
> Change listen only for html5

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/trigger/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
Fixed console warnings that appear for viewers and / or moderators on initial login, when they open a user list and chat.
All except one. There is a custom prop validator in the DropdownList, which will need to be adjusted later.
> [HTML5] - Fix for the React console warnings

- bigbluebutton-html5/imports/api/voice-users/server/modifiers/updateVoiceUser.js
Change function name to match file name
> Fix function name in updateVoiceUser

- bigbluebutton-html5/imports/api/users/server/modifiers/clearUsers.js
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx
- bigbluebutton-html5/imports/utils/humanizeSeconds.js
> [HTML5] Fix issue introduced on #4488

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
Fix a bug when upload modal was open and the user lose presenter role, modal still remained open.
> [HTML5] Fix presentation upload modal  bug

- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/UserJoinedVoice.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/domain/Recording.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
https://github.com/bigbluebutton/bigbluebutton/issues/4541
https://github.com/bigbluebutton/bigbluebutton/issues/4558
> Fix a couple of issue

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/CreateNewPresentationPodPubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodHdlrs.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/PresentationPodsApp.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetCurrentPagePubMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/presentationpod/SetPresenterInPodReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/PresentationPods.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/pubsub/senders/ReceivedJsonMsgHandlerActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Presentation.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/PresentationPodsMsgs.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/present/business/PresentProxy.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/events/SetPresenterInPodReqEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/events/SetPresenterInPodRespEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/maps/PresentEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/messaging/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/messaging/MessageSender.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
-handled `default.pdf` display (was causing issues because bbb-web did not know the podId akka-apps gave to the default pres pod)
-pods are isolated in terms of slide changes
-work on current pod presenter
> Presentation Pods improvements

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/branding/default/style/css/org/bigbluebutton/skins/ButtonSkin.as
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/BigBlueButton.mxml
- bigbluebutton-client/src/org/bigbluebutton/core/PopUpUtil.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/BreakoutRoomSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/ToolbarPopupButton.mxml
- bigbluebutton-client/src/org/bigbluebutton/util/SessionTokenUtil.as
- Update screen-sharing switch display button style.
- Update Alert default button width.
> [Flash 2.0] - General imporvements to buttons

- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
Fix the inverted logic in allowedToMuteAudio and allowedToUnmuteAudio and user-list actions.
> fix allowedToMuteAudio and allowedToUnmuteAudio logic and created action

- bigbluebutton-html5/imports/api/users/server/handlers/changeRole.js
- bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/changeRole.js
- bigbluebutton-html5/private/config/public/user.yaml
Changes the changeRole modifier to be able to apply / remove any role passed to it.
> Change Role refactor

- bigbluebutton-html5/imports/ui/components/app/container.jsx
Fix an issue that prevented the users from being removed when the meeting was ended by a moderator
> Remove user on meeting end

- bbb-apps-common/build.sbt
- bbb-apps-common/src/main/scala/org/bigbluebutton/client/meeting/UserActor.scala
- bigbluebutton-apps/build.gradle
- bigbluebutton-client/resources/prod/layout.xml
- override meetingId and userId of messages from client
- fix presentation window name in layout.xml
> Rights management and layout id

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- hardcode default presentation window for pre-uploaded presentations and for creation of breakout rooms
> Setup presentation window for pre-uploaded presentation

- bigbluebutton-client/resources/prod/guest-wait.html
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
- landing page where guests wait for approval from moderator
> create guest lobby html page

- bigbluebutton-config/web/index_html5_vs_flash.html
With this file we can easily overwrite index.html on test servers via `cp index_html5_vs_flash.html index.html`
> Add portal with HTML5 *AND* Flash entry point

- bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js
This PR adds changes that release the stored WebRTC microphone when a call ends. It needs heavy testing to make sure there aren't regressions. Of particular note is reconnects and making sure that the user can still talk after a reconnect.
> Release the saved WebRTC microphone when call ends

- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/startup/client/intl.jsx
- bigbluebutton-html5/imports/startup/server/index.js
- bigbluebutton-html5/imports/ui/services/settings/index.js
Initialize the html5 client locale as the browser locale, if the user has not selected a locale previously.
> Set initial locale to be the browser one

- bigbluebutton-html5/imports/ui/components/polling/container.jsx
Introduced in [#4488](https://github.com/bigbluebutton/bigbluebutton/pull/4488/files#diff-4066570cc193e216fcc448e5e6ab4d7fR6)
> Fixed a bug with passing props to the polling container

- bigbluebutton-html5/imports/ui/services/settings/index.js
settings service was missing a `||`
> Fixes settings service

- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
> Fix presentation context menu when switching locale

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/events/NewGroupChatMessageEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/ChatEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/maps/ChatEventMapDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/model/GroupChat.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml
- open private chat window when a new message is received.
> Fix chat issues

- bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/private/config/public/app.yaml
Add a config flag that allow moderator to unmute muted users.
> add moderatorUnmute feature in HTML5 client

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/RegisterUserReqMsgHdlr.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/UsersMgs.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
- bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/MeetingsManagerActor.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/ToAkkaAppsSendersTrait.scala
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fix issue where when moderator joins, a request approval to join is sent to other moderators.
>  - determine guest status properly for moderators

- bigbluebutton-client/src/org/bigbluebutton/main/views/PendingGuestsWindow.mxml
>  - remove authenicated users list for approval as we only deal with guests

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/GroupChats.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatTab.mxml
- when user leaves, disable private chat input and re-enable when the user rejoins
> Fix private chat issues

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
> Use a Text component for long ProgresBar label.

- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
> Fix meeting label width.

- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
* Includes handling of dynamically promoted/demoted moderator
> Show presentation pods dropdown only to moderators

- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
synching with latest v2.0.x-release branch
> Synch with v2.0

- bigbluebutton-client/resources/prod/BigBlueButton.html
@antobinary Replacement for #4723
> Improve bigbluebutton-client/resources/prod/BigBlueButton.html

- bigbluebutton-html5/imports/api/users/server/methods/assignPresenter.js
- bigbluebutton-html5/imports/api/users/server/methods/kickUser.js
- bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js
> Pass mute boolean in redis msg on mute/unmute user

- bigbluebutton-html5/private/locales/en.json
- Readd message when error occurs with message length.
- closes #4730.
> Readd missing messages.

- bigbluebutton-html5/imports/api/chat/server/handlers/chatPublicHistoryClear.js
- bigbluebutton-html5/imports/ui/components/chat/container.jsx
- bigbluebutton-html5/private/config/public/chat.yaml
- bigbluebutton-html5/private/locales/en.json
- Message "The public chat history was cleared by a moderator" now is able be translated.
>  Localize message from when clear the chat.

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/main/views/AudioSelectionWindow.mxml
This PR finishes the solution to issue #4319.
> Add a warning about microphone access for chrome on HTTP

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
This PR is a fix for issue #4393.
> Check for failed chat message parse

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala
- bbb-apps-common/src/main/scala/org/bigbluebutton/client/meeting/UserActor.scala
- make sure that the client gets validated first before sending messages from server to client.
> Validate connection

- bigbluebutton-html5/imports/ui/components/user-list/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/styles.scss
>  Fix false click in userlist.

- bbb-lti/grails-app/assets/javascripts/tool.js
- bbb-lti/grails-app/assets/stylesheets/tool.css
- bbb-lti/grails-app/controllers/org/bigbluebutton/ToolController.groovy
- bbb-lti/grails-app/i18n/messages.properties
- bbb-lti/grails-app/i18n/messages_es.properties
- bbb-lti/grails-app/i18n/messages_fr.properties
- bbb-lti/grails-app/views/tool/index.gsp
- Fixed dataTable and made the eye icon toggle
- Added image preview to recordings
> bbb-lti: Fixes datatable and adds image preview

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutApp2x.scala
- bbb-api-demo/src/main/webapp/bbb_api.jsp
- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- use sha256hex when calculating checksum for API calls
> Use sha256hex

- bigbluebutton-html5/imports/ui/components/chat/message-list/styles.scss
> Fixed last chat message view in Firefox

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala
- bbb-apps-common/src/main/scala/org/bigbluebutton/client/meeting/AllowedMessageNames.scala
- use current presentation and page of main presentation window as default presentation for breakout rooms
>  - add create breakout rooms request to whitelist

- record-and-playback/core/scripts/sanity/sanity.rb
When working with the segmented recording format, the events file might
end with a mismatched start video event for an incomplete file. The
sanity script was removing this event, meaning the video didn't show up
in future segments.
Simply drop the code that tries to find invalid video files and removes
them from the events file. The new video processing code is already
robust against missing or corrupt files.
> Don't delete video events in the sanity script.

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/events/ChatHistoryEvent.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/business/PresentProxy.as
This PR fixes two exceptions thrown when the client reconnects.
> Fix exceptions on reconnect

- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
We had three old message handlers that didn't need to be there anymore and I had forgotten a break in the IsMeetingMutedRespMsg case that was causing issues.
> Cleanup minor issues with Users MessageReceiver

- bigbluebutton-html5/imports/ui/components/button/styles.scss
- bigbluebutton-html5/imports/ui/stylesheets/variables/general.scss
Thanks @tylercopeland for help.
Fixes #3576
> Fixed round buttons' icon centering

- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileDownloadWindow.mxml
- listen for presentation download changed message in the file download window
>  Update file download window with pres download change event

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserJoinMeetingAfterReconnectReqMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala
> Fix put meeting and at muted status

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/core/TimerUtil.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
The warning doesn't show in the main room and if the user doesn't close it themselves it will be closed when the timer is up.
> Addd a minute warning when breakout rooms are going to close

- labs/bbb-webrtc-sfu/package.json
* Put rid dependency in production part of package.json
> Fix problem when building HTML5 screenshare + video PR

- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AddChatTabBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/model/BreakoutRoomsOptions.as
> Disable private chat for breakout rooms

- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx
- Changed a default tool selected to 'pencil' ( #4807 )
- Disabled the thickness and color menu buttons when the 'hand' tool is selected  ( #4808 )
Probably should be merged after #4821 , I'd like to make a few small changes after that.
> Improved Whiteboard toolbar's user experience

- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx
> Fix user list dropdown bug when making user presenter. 

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/private/locales/en.json
> Updated the message displayed to the kicked user

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatWindowEventHandler.as
> Sort private chat users alphabetically.

- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
The Fullscreen option will not render for iOS devices.
fixes issue #4823
> Hide fullscreen option for iOS devices

- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
> Fix alpha value for ScreenshareViewWindow change display button

- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
> Fix ScreenshareViewWindow scroll-bars in original video size mode

- bigbluebutton-client/src/org/bigbluebutton/main/views/WebRTCEchoTest.mxml
> Delay showing confirmation buttons in WebRTCEchoTest under firefox

- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/messages/PresentationPodVO.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/services/messaging/MessageReceiver.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/services/ChatMessageSender.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/commands/ConnectCommand.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/commands/GoToSlideCommand.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/models/Presentation.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/models/PresentationList.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/services/IPresentationService.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/services/PresentMessageReceiver.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/services/PresentMessageSender.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/presentation/services/PresentationService.as
This PR gets the default presentation pod information working in the AIR client. If we have time or if it's required we'll deal with the other pods later.
> Update AIR client with 2.1 presentation code

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
> Show moderator message header in bold

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
> Disable webcam button in media column for all users when webcamsOnlyForModerator is on

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Mute/unmute button's icon didn't update when you pressed it (even though the actual functionality worked just fine).
> [HTML5 Client] Fix for Mute/Unmute button's icon update.

- bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
- bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/createDummyUser.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/startup/mapToAcl.js
- bigbluebutton-html5/imports/startup/server/redis.js
- bigbluebutton-html5/imports/ui/services/auth/index.js
- bigbluebutton-html5/private/config/development/server/log.yaml
-includes the work done in #4814 and #4866
> Adjust html5 client join to work with BBB 2.1 (master branch)

- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
- bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss
- bigbluebutton-html5/imports/ui/stylesheets/variables/breakpoints.scss
This fixes the responsiveness of the ActionBar buttons to look as expected for small screens.
isssue #4819 
[View as Presenter]
[View as Non-Presenter]
> Fix alignment of ActionsBar buttons for small screens

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/WebcamsOnlyForModeratorRecordEvent.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala
- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/main/views/AudioSelectionWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/LockSettings.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
> Improve webcams only for moderator

- bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
- Moves the uniqueid functions to the constructor, only to switch when the component is rendered.
> Fix issue #4992. Unable to clear chat.

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/main/views/RecordButton.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/model/ChatConversation.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/AdvancedList.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
> Improve moderator icon display in ChatMessageRenderer

- bigbluebutton-html5/transifex.sh
One commit for indentation fix, one commit for actual changes
> Omit pulling en.json (the source file) from transifex

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/src/org/bigbluebutton/main/views/LoadingBar.mxml
- bigbluebutton-client/src/org/bigbluebutton/main/views/MainApplicationShell.mxml
> Use a separate label for LoadingBar

- bigbluebutton-html5/private/config/settings-production.json
Changes made in  #4821 needed to be propagated to the `settings-production.json` file
Resolves #5037
> Adjust production settings to match changes on dev settigns  #4821

- bigbluebutton-client/src/org/bigbluebutton/main/views/LoggedOutWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/notes/views/NotesView.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/util/QueryStringParameters.as
> User interface fixes

- bigbluebutton-html5/imports/startup/client/auth.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/startup/client/routes.js
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
- bigbluebutton-html5/imports/ui/services/auth/index.js
Ejected user will no longer be able to click the Back button to rejoin the meeting as a ghost user.
This fixes issue #4970
> Prevent kicked user's ability to rejoin meeting via back btn

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
> Highlight microphone icon in users list when microphone is locked

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
> Show "Viewers Locked" when webcamsOnlyForModerator is on

- bigbluebutton-client/src/org/bigbluebutton/main/views/QuotesView.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/FileUploadWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/JoinBreakoutRoomWindow.mxml
> Replace remnant spark labels by mx label and text

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/model/ChatMessage.as
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
Fix #5012 by using data binding.
> Fully rely on binding to display chat messages

- bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml
> Show record button for all users

- clients/flash/air-client/src/Default.css
- clients/flash/air-client/src/css/xhdpi.css
- clients/flash/air-client/src/org/bigbluebutton/air/chat/ChatConfig.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/models/ChatMessagesSession.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/models/GroupChat.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/views/ChatViewBase.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/chat/views/ChatViewMediatorBase.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/commands/ConnectCommand.as
I've added the welcome message and clear chat messages, moved the send button from the left to the right, reset the newMessage counter when actively viewing a chat group, and scrolled the chat message list when viewing a chat group.
> Minor AIR updates for 2.1 chat

- bigbluebutton-html5/imports/ui/components/settings/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/container.jsx
> Prevent error on settings change with userlist open

- bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
> Force reading config.xml in utf-8 format

- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/WhiteboardCanvasDisplayModel.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCanvas.as
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardCursor.as
This PR refactors the way that cursor visualization interacts with multiuser state. It should result in better performance and better hiding of cursors when multiuser is turned off.
> Improve the interaction between multiuser and cursors

- record-and-playback/core/lib/recordandplayback/edl/video.rb
Red5 sometimes writes webcam video files with a large offset in the
video frame offsets, sometimes up to 30 or even 60 seconds. However,
the start event in the events.xml file corresponds to the time at
which red5 received the first keyframe (recorded frame) in the video.
The end result is that the video will sometimes appear to be
delayed (out of sync) in the processed recording.
The correction is simple: We're already reading video metadata,
including the timestamp of the first frame, so we just have to apply
a correction during video processing to undo the frame timestamp
offsets in the video file.
> Workaround video sync issue due to red5 timestamp offset

- record-and-playback/core/lib/recordandplayback/events_archiver.rb
With the current segment processing, we might be processing one segment
while archiving a different segment from the same recording. To avoid
that the processing scripts see an incomplete events.xml file, write to
a temp file then rename.
> Archive events.xml file in a concurrency-friendly way.

- record-and-playback/core/lib/recordandplayback/edl/audio.rb
In some cases when there is a slight mismatch between audio file
duration and event timestamp difference, and we have a record
status or chapter break event in a certain location, it could
trigger a seek past the end of an audio file. Detect this
condition and just render silence instead.
Also adjust the thresholds for the audio length scaling - they
were being triggered on short recordings that should be correct.
> Rework audio processing to avoid seeking past end of file

- bigbluebutton-html5/imports/ui/components/video-dock/component.jsx
> Fix when the user disconnects stay a ghost webcam.

- bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Don't know if this has any side effects, but it should be updated.
> Updated bbb-web apiVersion to 2.0

- clients/flash/air-client/src/Main.mxml
- clients/flash/air-client/src/org/bigbluebutton/air/AppConfig.as
- clients/flash/air-client/src/org/bigbluebutton/air/main/MainConfig.as
- clients/flash/air-client/src/org/bigbluebutton/air/main/views/BannerView.as
- clients/flash/air-client/src/org/bigbluebutton/air/main/views/BannerViewMediator.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/models/ConferenceParameters.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/models/IConferenceParameters.as
- clients/flash/common-library/src/main/actionscript/org/bigbluebutton/lib/main/services/LoginService.as
TODO: Need to figure out how to apply banner into Main.mxml as it is not listening to a signal.
>  [WIP] handle banner param from create api

- bigbluebutton-client/resources/prod/BigBlueButton.html
> [HTML5 Client] Hide client type option when already detected.

- labs/bbb-webrtc-sfu/lib/ProcessManager.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/constants/Constants.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SdpSession.js
- labs/bbb-webrtc-sfu/lib/screenshare/ScreenshareProcess.js
- labs/bbb-webrtc-sfu/lib/video/VideoManager.js
- labs/bbb-webrtc-sfu/lib/video/VideoProcess.js
- labs/bbb-webrtc-sfu/server.js
Worked on a few things:
- Refactored subprocesses handling; there was a case where some of them could hang when closing the SFU component, that shouldn't happen anymore. Also, if any process crashes it will be automatically restarted.
- Added detection for when Kurento is offline in the SFU kurento adapter.
- Tracking media subscribers in SFU as to clean the Kurento endpoints; that should diminish some endpoint leaks we've seen and reduce the number of open file descriptors a bit.
- Some initial work on better error handling. This, specifically, is a WIP. Error handling is not so good right now, and I plan to work on that as soon as I can.
> bbb-webrtc-sfu optimizations

- bigbluebutton-client/resources/prod/lib/kurento-extension.js
- bigbluebutton-html5/client/compatibility/kurento-extension.js
Resolves #5178 
Also includes some linting on `kurento-extension.js`
> Kurento screensharing - handle "stop sharing" trigger from Chrome

- bigbluebutton-html5/imports/api/meetings/server/methods.js
- bigbluebutton-html5/imports/api/meetings/server/methods/toggleRecording.js
- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
- bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
- bigbluebutton-html5/private/locales/en.json
Implement the feature of start and stop recording a meeting in HTML5, closes #5127
> Implement start stop recording html5

- bigbluebutton-html5/imports/ui/components/video-dock/component.jsx
> Stop the video when an error occurs

- bigbluebutton-client/resources/prod/lib/kurento-extension.js
- bigbluebutton-html5/client/compatibility/kurento-extension.js
This is particularly important when sharing from FireFox where we only allow sharing fullscreen (of all screens)
> Set max height and width for screenshare to 1080 x 1920

- bigbluebutton-html5/imports/ui/components/switch/component.jsx
- bigbluebutton-html5/private/locales/en.json
Adds localized strings for the text inside the switch component.
fixes #5236
> Localize text in switch component

- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
> Stop screen share when switch presenter.

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss
prevents the slide control buttons shape from changing on hover / focus.
fixes #5233
> Prevent slide control btn changing shape

- bigbluebutton-html5/imports/api/acl/Acl.js
- bigbluebutton-html5/imports/api/users/server/publishers.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/ui/services/auth/index.js
This PR fixes the issue described on #5240  and also fixes the bug where reconnected users are redirected to `/logout`.
> Fix ghost and reconnecting users

- bigbluebutton-html5/imports/ui/components/media/container.jsx
- bigbluebutton-html5/imports/ui/components/media/service.js
- bigbluebutton-html5/private/locales/en.json
Show a notification for all user when a presenter start/end a screen share, closes #5205
> Implement notification when a presenter start and end a screenshare

- clients/flash/air-client/src/org/bigbluebutton/air/main/views/LoadingScreenMediator.as
Revert LoadingScreenMediator back to what it was.
> [AIR] revert LoadingScreenMediator

- bigbluebutton-html5/imports/ui/components/button/component.jsx
- bigbluebutton-html5/imports/ui/components/polling/component.jsx
- bigbluebutton-html5/imports/ui/components/polling/styles.scss
> Prevent text overflow on polling buttons

- bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js
- bigbluebutton-html5/imports/api/users/server/modifiers/setConnectionId.js
- bigbluebutton-html5/imports/api/users/server/modifiers/setConnectionIdAndAuthToken.js
Enforce authToken for every user that tries to rejoin a meeting, resolve #5261.
> Enforce authToken to re-joining users

- bigbluebutton-html5/imports/ui/components/media/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-dock/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-dock/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/service.js
- bigbluebutton-html5/imports/ui/services/user/mapUser.js
> Comply lock setting "see other viewer's webcams"

- bigbluebutton-html5/imports/startup/client/auth.js
- bigbluebutton-html5/imports/ui/components/user-list/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/custom-logo/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/custom-logo/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
> Add custom logo area 

- clients/flash/air-client/src/org/bigbluebutton/air/participants/models/ParticipantTitle.as
- clients/flash/air-client/src/org/bigbluebutton/air/participants/models/ParticipantsCollection.as
- clients/flash/air-client/src/org/bigbluebutton/air/participants/views/ParticipantsViewBase.as
The diff on the sort looks awful, but I basically separated out the User and Chat specific parts of the sort so the main function is easier to read and follow and then simplified the sort logic so there's less lookups and it's hopefully more efficient. Took the sort from 30+ lines down to 14.
> [AIR] Update participants sort

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/styles.scss
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js
- Add box-shadow on video button
- Reenable video button on SFU or permission errors (fixes #5308)
- Wait for user permission before starting timeout (fixes #5305)
> Fix small bugs on video-provider

- bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/content/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/list/component.jsx
- bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/trigger/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/styles.scss
- Update the dropdown focus/hover styles to the latest designs
- Remove default active state on dropdown menus. Closes #5313
> Update on the Dropdown styling

- bigbluebutton-html5/imports/ui/components/settings/component.jsx
- bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx
> Fix settings modal opening when you click to open userlist

- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Now when you exit audio, the navigator tab indication doesn't show that he is using media anymore, fix #5253 and fix #5252.
> Fix media tab indication on audio exit

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/service.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/MediaController.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/media-server.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/MediaSession.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SfuUser.js
- labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
Fixed a few regressions found on #5327:
- Correctly stopping viewer streams
- Handling media flow errors
- Fixed the service isSharing state
And on #5333:
- Fixed non h264 enforced screenshare streams
- Corrected error objects creation
> Follow up on #5327 and #5333

- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Fix the problem with joining audio in Firefox that was introduced in #5348
> Fix problem on joining audio in Firefox

- bigbluebutton-html5/imports/ui/components/actions-bar/emoji-select/component.jsx
- bigbluebutton-html5/private/locales/en.json
> Change status label to comply with client

- bigbluebutton-html5/imports/ui/components/audio/service.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Issue: Audio messages do not update when you change the language.
Move this.messages to your own function, then every time the update the audio component will update the messages.
Closes #5366.
> set audio messages in a own function.

- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareViewWindow.mxml
> Delete centering videoHolder in all cases from ScreenshareViewWindow

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ChangeUserRoleCmdMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala
- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatMessageRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/MediaItemRenderer.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
Store role change in session and registered users then propagate the change from akka-apps to bbb-web.
Fix for #5083
> Persist use role update

- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMap.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMapDelegate.as
Fix role change and page reload not taking in account webcam display when is on
Fixes #5387
> Fix video display for webcamsOnlyForModerator 

- bigbluebutton-html5/imports/api/annotations/server/modifiers/addAnnotation.js
- bigbluebutton-html5/imports/startup/server/redis.js
- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
Reverts bigbluebutton/bigbluebutton#5400  - it caused a lot of delay on production, contrary to simulated production/development environments :(
> Revert "[HTML5 Client] Whiteboard Bulk Operations"

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/stylesheets/variables/breakpoints.scss
- bigbluebutton-html5/package-lock.json
- bigbluebutton-html5/package.json
This PR
* adds re-resizable package.
* makes userlist / chat width scalable.
> Make userlist and chat width scalable

- bigbluebutton-client/branding/default/style/css/V2Theme.css
- bigbluebutton-client/branding/default/style/css/org/bigbluebutton/skins/ToolTipSkin.as
- bigbluebutton-client/src/org/bigbluebutton/modules/phone/views/components/ToolbarButton.mxml
This PR makes the audio call out style similar to the normal tool tips and makes it only show for 15s instead of 30s.
> Change style of the audio call out

- bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
- bigbluebutton-html5/imports/ui/components/screenshare/styles.scss
> Add spinning arrows while load the screenshare.

- bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
> Adjust meeting props to add freeJoin br room

- bbb-api-demo/src/main/webapp/bbb_api.jsp
- bbb-api-demo/src/main/webapp/demoHTML5.jsp
- bbb-api-demo/src/main/webapp/demoHTML5Video.jsp
Also adjusted the joinURL call to include flags for isModerator (in addition to isHTML5Client)
> Adjusted html5 demos to be recordable

- bigbluebutton-client/resources/prod/lib/kurento-extension.js
- bigbluebutton-html5/client/compatibility/kurento-extension.js
Fixed the limiting. And the limit is now WQXGA (2560x1600), aka the 16:10 version of 1440p.
> Fixed screenshare resolution limit

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
- Remove shouldComponentUpdate() that prevents status update.
- add listen only icon in webcam status.
closes #5455 and #5452.
> Show listen only icon in webcam status.

- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx
#5397 
The correct full screen button now displays when the client is in full screen.
> Full screen button fix

- bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/container.jsx
- bigbluebutton-html5/imports/utils/deviceInfo.js
> Prevent whiteboard textarea flickering

- bigbluebutton-html5/imports/api/chat/server/methods/sendChat.js
- bigbluebutton-html5/imports/ui/components/chat/service.js
> [HTML5 Client] Server-side timestamps in chat messages.

- bigbluebutton-web/grails-app/conf/UrlMappings.groovy
- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
NOTE: This doesn't fix issue with uploading file with FF 60 on Windows 10.
Modify /etc/bigbluebutton/nginx/web.nginx with the following:
location /bigbluebutton {
proxy_http_version 1.1;
location /bigbluebutton {
proxy_pass         http://127.0.0.1:8080;
proxy_redirect     default;
proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
add_header P3P 'CP="No P3P policy available"';
}
location /bigbluebutton/presentation/upload {
proxy_pass         http://127.0.0.1:8080;
proxy_redirect     default;
proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
add_header P3P 'CP="No P3P policy available"';
client_max_body_size       30m;
client_body_buffer_size    128k;
proxy_connect_timeout      90;
proxy_send_timeout         90;
proxy_read_timeout         90; …
>  - add some kind of check to uploaded file

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/domain/MeetingInactivityTracker.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/test/scala/org/bigbluebutton/core2/message/handlers/ValidateAuthTokenReqMsgHdlrTestsSpec.scala
@ritzalam Can you please test if and confirm that it works like expected?
> Make breakout rooms expire only by their duration

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
The user list now displays all users#5398
> User list fixed to display all users

- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss
The colour range of the avatars have been reduced to blues and purples, audio state have been increased in size, and lastly the talking indicator is bigger. #5593
> User list UI changes implemented

- record-and-playback/core/lib/recordandplayback/edl/video.rb
Since the update to the newer red5, seeking in flv files (webcams in
particular are noticable) has been broken, resulting in cameras
appearing to "hang" any time there is a cut in the generated video -
which happens when start/stop button is pushed, or when cameras are
added or removed.
We can detect the problematic video files because the timestamp of the
first frame is large (old red5 versions always set first frame
timestamp to 0.001 seconds). If we see a file like this, having ffmpeg
remux the file - rewriting the timestamps and index - works around the
problem.
> RaP: Workaround broken seeking in flv after red5 update.

- bigbluebutton-html5/imports/ui/components/audio/echo-test/component.jsx
- Disable button to prevent call handle audio several times.
Closes #5471.
> Disable yes button on echo-test when clicked.

- bigbluebutton-web/run.sh
Change port so as not to conflict with Kurento
> Change bbb-web dev port

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx
> Fix User-item menu options not being triggered

- bigbluebutton-html5/client/main.html
- bigbluebutton-html5/client/main.jsx
- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
> Make window title configurable (part of Branding)

- bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatBox.mxml
@ritzalam Can you please test this before merging it?
> Fix chat ribbon flickering when a lot of messages are arriving

- bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/PollResultsModal.as
> Put focus on PollResultsModal when it shows to avoid changing slides

- bigbluebutton-client/src/org/bigbluebutton/modules/phone/views/components/ToolbarButton.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/sharednotes/maps/SharedNotesEventMapDelegate.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/views/UserGraphicHolder.mxml
Fix for #5623 and other excpetions
> Fix flash null exceptions

- bigbluebutton-html5/client/main.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
> Make HTML5 client title the same format as Flash client (to include meeting name)

- bigbluebutton-client/resources/prod/locales.xml
> Add Haitian locale to flash client

- bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutStarted.js
- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx
* Fixed issues with incorrect time remaining in breakouts
* Resolved a problem with breakout window/tabs not closing at expiration time
> Breakouts improvements in HTML5

- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
The structure and parameter names expected by SIP.UA are slightly different than what bbb-web api returns. This code adapts the response so it fits
> Pass correct structure for TURNs

- bigbluebutton-html5/imports/ui/components/presentation/cursor/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
> Remove cursor when user leaves the meeting.

- bigbluebutton-html5/imports/startup/server/redis.js
- bigbluebutton-html5/imports/ui/components/audio/audio-stream-volume/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
+ Addressed logs like `error: CLIENT LOG: [object Object]`
+ had to address some lint complaints
> Improve specific HTML5 logs

- bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx
This PR fixes the chat counter in general + how scrolling affects the counter.
This should fix both #5494 and #5578.
> Chat counter and scrolling

- bigbluebutton-html5/imports/startup/client/auth.js
In the future we should move these parameters from meta* to customParam
> HTML5: Process only meta params from the list of the handled ones

- bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/5678
>  - update rec metadata for all formats

- record-and-playback/core/lib/recordandplayback/edl/video.rb
- Support ffmpeg 4.0 (Mostly future-proofing, but it has some major improvements so I want to use it…)
- Fix some problems with the red5 seek workaround (it was remuxing video sometimes when it didn't have to) and switch to aspect-ratio aware scaling (which might fix some very rare cases of stretched/squished webcams).
> Recording processing fixes

- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
> Vertically align recording tag with the session title

- bigbluebutton-html5/imports/api/video/server/handlers/userSharedHtml5Webcam.js
- bigbluebutton-html5/imports/api/video/server/handlers/userUnsharedHtml5Webcam.js
> skip share/unshare of flash webcams using "if" instead of "check".

- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/CallbackUrlService.java
- bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/ICallbackEvent.java
- bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/MeetingEndedEvent.java
- bigbluebutton-web/grails-app/conf/spring/resources.xml
To use, add meta_endcallbackurl parameter on the create api call.
Implementation of issue https://github.com/bigbluebutton/bigbluebutton/issues/5724
>   Implement end meeting callback url

- bbb-client-check/src/org/bigbluebutton/clientcheck/service/RTMPTunnelingService.as
- bbb-voice/src/main/java/org/bigbluebutton/voiceconf/red5/Application.java
> Fix SIP connection test and improve logging for SIP Application class

- bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
> Typing chat on iPhone partially hides the post button

- bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
> Moderator only message support.

- bigbluebutton-html5/imports/ui/components/app/styles.scss
> Adjust view of mobile user actions list

- bigbluebutton-client/src/org/bigbluebutton/modules/users/model/UsersOptions.as
- accidentally deleted when fixing merge conflicts
> Fix compile error

- bigbluebutton-html5/imports/ui/components/user-list/service.js
> Move current user to the top of the users list.

- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
This PR changes the default setting for chat push notifications to false, until #5797 is resolved.
> DIsable chat push notifications by default.

- bigbluebutton-html5/client/main.html
Reverts bigbluebutton/bigbluebutton#5809 as it caused #5813
> Revert "Prevent screen from moving while drawing"

- bigbluebutton-html5/imports/ui/components/chat/styles.scss
- bigbluebutton-html5/imports/ui/components/toast/component.jsx
- bigbluebutton-html5/imports/ui/components/toast/styles.scss
- This PR pass the background color as inherit to line-clamp.
Before:
Now:
> Fix white blocks when hover toast

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/notification/component.jsx
> Don't push chat notification if chat is open

- bigbluebutton-client/locale/en_US/bbbResources.properties
- bigbluebutton-client/src/org/bigbluebutton/modules/screenshare/view/components/ScreenshareSelectionWindow.mxml
> Updated hardware acceleration hint and check

- bigbluebutton-html5/private/config/settings-development.json
- bigbluebutton-html5/private/config/settings-production.json
> Add 1px thickness option to whiteboard pencil

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
> change mute/unmute icon

- bigbluebutton-client/src/org/bigbluebutton/main/views/VideoWithWarnings.as
- bigbluebutton-client/src/org/bigbluebutton/main/views/VideoWithWarningsBase.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/users/services/MessageReceiver.as
- bigbluebutton-client/src/org/bigbluebutton/modules/videoconf/maps/VideoEventMapDelegate.as
Fix issue (1) reported in the following forum thread https://groups.google.com/forum/#!topic/bigbluebutton-dev/W6-MuQ03qC4
> Fix camera lock when skipCamSettingsCheck is true

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/WhiteboardToolbar.mxml
- bigbluebutton-client/src/org/bigbluebutton/modules/whiteboard/views/models/WhiteboardOptions.as
Implement feature #5850 for Flash client.
> Pen tool only for multi-user whiteboard

- bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java
- bigbluebutton-client/src/org/bigbluebutton/modules/present/business/PresentProxy.as
- bigbluebutton-web/grails-app/conf/UrlMappings.groovy
- allow downloading of non-pdf files
- allow downloading of file with utf-8 filenames
> Fix pres download issue

- bigbluebutton-html5/imports/api/voice-users/server/handlers/joinVoiceUser.js
- bigbluebutton-html5/imports/api/voice-users/server/handlers/leftVoiceUser.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-list-content/component.jsx
- bigbluebutton-html5/imports/ui/services/user/mapUser.js
> Add user when moderator join via audio only in breakout room

- bigbluebutton-html5/imports/startup/client/base.jsx
> Remove redundant import causing HTML5 app to fail starting

- bigbluebutton-html5/imports/ui/components/audio/service.js
> Fix audio lock setting not applied.

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx
The screen sharing button is moved from the drop down list to the action bar. #5783
> Desktop share button moved to the action bar component

- bigbluebutton-html5/imports/startup/client/base.jsx
the way to reproduce the bug is to set the  devtools network to slow 3g and reload the tab.
Closes #5892.
> Fix intl id being showing.

- labs/bbb-webrtc-sfu/lib/base/BaseProvider.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/MCSApiStub.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/media/MediaController.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/RecordingSession.js
- labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SfuUser.js
- labs/bbb-webrtc-sfu/lib/screenshare/screenshare.js
- labs/bbb-webrtc-sfu/lib/video/video.js
Also refactored SFU recording path handling to make it easier to maintain and a bit less error prone.
> Fixed screenshare recording

- bigbluebutton-html5/imports/ui/components/app/styles.scss
> Fix ios scrolling when drawing

- bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js
> Fix for the client logging error

- bbb-webhooks/messageMapping.js
Add hooks for camera, presentation, screenshare, emoji and recording events
> Add new events to webhooks

- labs/bbb-webrtc-sfu/lib/bbb/pubsub/bbb-gw.js
- labs/bbb-webrtc-sfu/lib/connection-manager/WebsocketConnectionManager.js
Prevent a crash in bbb-webrtc-sfu when handling some kinds of websocket errors.
> Correctly handle a websocket error

- bigbluebutton-html5/imports/ui/components/user-avatar/component.jsx
- bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss
Userlist avatars now pulse using transform instead of box-shadow. #5945
> Pulse animation performance improved

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
> Fix audio status icon inconsistent size on webcams

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/private/locales/en.json
Currently, the video ice connection state errors result in default errors (when media stops flowing, webcam is unshared with a generic message). This PR adds the code to detect state changes and, when needed, stop sharing video and throw a toast notification.
> Better handling of video ice connection state errors.

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss
- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
> fix toolbars losing border radius when overlap the presentation.

- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/SyncGetVoiceUsersMsgHdlr.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp2x.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala
- akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/FromAkkaAppsMsgSenderActor.scala
- bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala
- bigbluebutton-html5/imports/api/users/server/modifiers/addDialInUser.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/api/voice-users/server/eventHandlers.js
- bigbluebutton-html5/imports/api/voice-users/server/handlers/joinVoiceUser.js
- bigbluebutton-html5/imports/api/voice-users/server/handlers/voiceUsers.js
This PR add a new message in akka-apps, `SyncGetVoiceUsersRespMsg`, that solves #4784,  also handle the message on HTML5.
> Add SyncGetVoiceUsersRespMsg message in akka

- bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/styles.scss
- bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
The dropdown menu is no longer pushed off screen on Firefox. #5972
> Prevented the presenataion title from pushing the dropdown menu off-screen

- bigbluebutton-html5/client/compatibility/kurento-extension.js
- bigbluebutton-html5/client/compatibility/kurento-utils.js
- bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Placeholder buffer on audioContext, upstarting <audio> tag as muted, playing bogus audio on HTML5 tag if possible on a higher level of the user action stack.
> Improvements to Safari/Chrome autoplay policy

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Follow up on #6019 regarding @oswaldoacauan 's suggestion
> Resolving listen only stream correctly

- bigbluebutton-html5/imports/ui/services/user/mapUser.js
> Fix listenOnly being interpreted as muted audio (client side)

- bigbluebutton-html5/imports/api/meetings/server/publishers.js
Only necessary information is now published to the client.
> Only propagate necessary information to client

- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Make SIP.js listen only a fallback to SFU when it's enabled and a client fails to successfully connect.
When the connection is closed or reset, the client will go through the fallback procedure again (SFU -> SIP.js).
If SFU is disabled, behaviour is untouched.
Also fixed the `Connecting...` modal disappearing on a retry and the listen only button getting stuck when the user fails to join listen only after reaching the max retry number.
> Add SIP.js listen only as fallback when SFU is enabled

- bigbluebutton-html5/imports/ui/components/app/component.jsx
The chat area can now be extended significantly more than it originally could. #6000
> Extended the Width of the Chat Area

- bigbluebutton-html5/imports/ui/components/chat/styles.scss
Attempt to fix the fuzzy chat rendering.
This seems to fix it for me on Chrome/Linux probably need testing from other people who experienced the issue.
> Fix fuzzy chat font rendering.

- bigbluebutton-client/resources/prod/BigBlueButton.html
- bigbluebutton-client/resources/prod/lib/adapter.js
- bigbluebutton-client/resources/prod/lib/sip.js
Adapter.js was a very old version and it was being loaded after sip.js so it wasn't taking effect when it was actually needed. I've updated the version and moved it higher in the page load order.
> Update adapter.js in the Flash client and make sure it loads in correct order

- record-and-playback/core/scripts/bbb-1.1-meeting-tag
Script for fixing meeting tag in recordings migrated from BBB 1.0 and before.
> Fix meeting tag in recordings migrated from BBB 1.0 and before (fixed #6089)

- bigbluebutton-html5/imports/ui/components/modal/simple/styles.scss
A small change to modal overlay follow the @tylercopeland designs.
> Change modal overlay color for client consistency.

- bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java
- bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/UpdateRecordingStatus.java
- bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/CallbackUrlService.java
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/bus/ReceivedJsonMsgHdlrActor.scala
- bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
> Add "recordingmarks" to end meeting callback url

- bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/ui/components/chat/container.jsx
- bigbluebutton-html5/imports/ui/components/chat/service.js
- bigbluebutton-html5/imports/ui/services/user/mapUser.js
Handle system messages on main public chat to behave like system messages on 2.0, and add moderator message, close #5969.
> Handle system messages in public chat

- bigbluebutton-client/src/org/bigbluebutton/modules/users/views/UsersWindow.mxml
> Fix breakout rooms buttons visibility for moderators

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
> Add pointer cursor when hover over the video dropdown

- bigbluebutton-html5/imports/ui/components/app/styles.scss
> Remove behavior that add opacity when hover the presentation area.

- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-draw-listener/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
Handle cases where the tool list is empty and when the tool list have only one item
> Configurable whiteboard tools improvement

- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
Our call flow is to first connect the user to the echo test and then once they say "Yes I can hear myself" we send a DTMF(1) to transfer the B-leg to the conference voice bridge. In some browsers (Firefox) the WebRTC call says that it is connected before everything is actually hooked up and it's possible for someone to send the DTMF before it can actually do anything. Sending the DTMF results in the UI either hanging or showing an invalid states.
I had to workaround the same problem in the Flash client and the only solution I could come up with was to just delay the showing of the buttons so the user can't click too fast. This PR implements a similar timeout.
> [HTML5] delay the notfication that the echo test is connected

- bbb-webhooks/.dockerignore
- bbb-webhooks/config.js
- bbb-webhooks/messageMapping.js
- bbb-webhooks/userMapping.js
- bbb-webhooks/web_hooks.js
- fix compatibility with old messaging format
- fix record and playback callbacks
- save user in memory before save it to redis (to avoid race condition when lookup)
- add external meeting id to all rap callbacks
> Fix webhooks

- bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
- bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
> Add meteor disconnect

- .travis.yml
- build_script.sh
There are 2 build stages: `Linter` and `Tests`. Since the `Linter` stage goes first, we allow it to fail.
> Build Stages

- bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
- bigbluebutton-html5/private/config/settings.yml
The option to unmute other users is removed, while still leaving the functionality to mute yourself. #6208
> Removed option to unmute other users

- bbb-api-demo/src/main/webapp/demo_iframe.jsp
- bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
> Avoid race condition when detecting user join audio from outside iframe

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/service.js
This is needed to run the new version of `bbb-webrtc-sfu`. It should be merged when https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/1 is merged and packaging is properly set up.
> Added voiceBridge prop to video-provider and forward it to SFU

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Re-implementation of work done in this commit https://github.com/bigbluebutton/bigbluebutton/commit/e4a6f31abc2a9f33a34d6933ddb089b61c4af8ef
> Lock enter and stuns to valid session+token

- bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/styles.scss
> Fix manage user menu alignment

- bbb-api-demo/src/main/webapp/demo_iframe.jsp
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Removed the need to poll for the audio state.
> Improve signal for audio join/leave when in iframe

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
This is a quick workaround to fix a race condition where a viewer stream would be resubscribed in-negotiation when the component state changed too rapidly.
I should get rid of this workaround (and most of the flaky code in the video component) when I'm able to finish the client-side refactor for the SFU clients I started in the summit.
> Workaround on webcam viewer race condition when state changes rapidly

- bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
- bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss
- bigbluebutton-html5/imports/ui/components/button/styles.scss
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-menu/styles.scss
> Change the buttons on actions bar to ghost buttons

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
> Fixes presentation slide conversion timeout

- bigbluebutton-html5/private/locales/en.json
> Edit poll label

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
Fixes bug introduced on https://github.com/bigbluebutton/bigbluebutton/pull/6312/ to solve issue  #6311
> Fixes slide conversion timeout to be in nano seconds

- bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
> Change icon for clearing annotations in whiteboard

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java
The slide conversion timeout was not being read from config file.
> Makes slide conversion timeout great again

- bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
Fix some case when assignPresenter enter in a loop and keep log stuck, close #6294.
> Fix assignPresenter loop

- bigbluebutton-html5/imports/api/slides/server/methods/zoomSlide.js
- bigbluebutton-html5/imports/ui/components/presentation/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/zoom-tool/component.jsx
- bigbluebutton-html5/imports/utils/slideCalcUtils.js
Change from 5% to 25% zoom increment value.
> Increase zoom increment

- bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
Reverting #6270 #6326 as we experience forever loop in some instances
> Revert presenter assign 6270 6326

- bigbluebutton-html5/imports/ui/components/app/container.jsx
- bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/service.js
The micsLocked boolean is now set correctly when microphones are locked.
> Fixed micsLocked check

- bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Related to https://github.com/bigbluebutton/bigbluebutton/commit/8dee81db8d56503568274fdd85c0582a944d23d1
> Handle logs that cannot be stringified/parsed

- bigbluebutton-config/bin/bbb-conf
> Dynamically detect is sudo is needed

- bigbluebutton-client/resources/prod/lib/kurento-extension.js
I added a reconnection procedure to the `kurento-extension.js` script to attempt to reconnect 4 times when the initial WS connection establishment fails and screenshare has not been started yet.
This is to workaround the problem we've seen on some server where the WS connection establishment randomly fails sometimes. Since I can't reproduce this on my dev environment and couldn't pinpoint the reason why (it isn't related to the SFU component; either the browser, nginx or the client or server-side network is dropping it), I think the workaround should be enough to at least make the error transparent to the user and reconnect without making a fuss about it.
If somebody could deploy this on a server that is prone to the error happening and test it before widespread deployment, that would be …
> Added a reconnection procedure to Flash WebRTC screensharing to workaround connection failures

- bigbluebutton-config/bin/bbb-conf
Cleanup logs for redis, mongodb, kurento-media-server and bigbluebutton sub-directories.
> Better logs cleanup

- bigbluebutton-html5/imports/ui/services/auth/index.js
> Addressing a race condition causing Auth timeout

- bigbluebutton-html5/imports/ui/components/button/component.jsx
> Remove tooltip for active buttons

- bigbluebutton-client/resources/config.xml.template
- bigbluebutton-client/src/org/bigbluebutton/modules/chat/model/ChatOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/model/PresentOptions.as
- bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml
- Disable group chats
- Disable presentation download 
- Add a new configuration entry fir multi-presentation pods.
> Updated flash client configuration

- bigbluebutton-config/bin/bbb-conf
> Better display of BigBlueButton services

- bigbluebutton-html5/imports/api/presentation-pods/server/index.js
- bigbluebutton-html5/imports/api/presentation-pods/server/methods.js
- bigbluebutton-html5/imports/api/presentation-pods/server/methods/setPresenterInPodReqMsg.js
- bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
Re-work from #6326 , prevent problem in infinity assign presenter loop.
close #6109 and close #5941
> Set presenter in default pod

- bigbluebutton-html5/imports/ui/components/media/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
> Hide presentation controls in swapped state

- bigbluebutton-html5/imports/api/breakouts/server/publishers.js
- bigbluebutton-html5/imports/startup/client/base.jsx
> Fix countdown doesn't appearing in breakout room

- bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
> Fix double tooltips being rendered per button

- bigbluebutton-html5/imports/ui/components/chat/container.jsx
- bigbluebutton-html5/imports/ui/components/chat/service.js
There is a problem with session value `idChatOpen`, this PR fix some problem with this value being empty
> Fix sending message and chat close button problem.

- bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
This PR will increase the size of the tooltip and add an arrow.
[old]
[new]
> Increase tooltip size and add arrow

- bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
> Make resizable panel width persist

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
> Fix proptype warnings

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
Pass right function to onChange event. Fix #6415
> Fix skip to slide handler

- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
- bigbluebutton-html5/private/locales/en.json
fix file selector does not work correctly in mobile browers.
> Fix file uploader mobile

- bigbluebutton-config/bin/bbb-conf
Update the regular expression to properly check for ffmpeg 4.0, 4.1, etc.
> Update check for ffmpeg 4.x

- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss
Fix border radius in buttons on presentation-toolbar
> Fix style border presentation toolbar

- bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss
Fix padding in the webcam dropdown menu.
- Add 
margin-left: -.25rem;
margin-right: -.25rem;
padding-left: .25rem;
padding-right: .25rem;
Fix #6014
> Fix padding in the webcam dropdown menu

- bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js
- bigbluebutton-html5/imports/ui/components/chat/service.js
Add welcome message to save/copy feature in chat, and fix a problem with a race condition when cleaning the chat.
> Add Welcome Message back to save/copy chat

- bigbluebutton-html5/imports/startup/client/base.jsx
> Fix user rejoining to meeting when is ejected

- bigbluebutton-html5/imports/ui/components/media/container.jsx
> Reposition presentation on mobile when data saving is turned on

- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/app/styles.scss
Margin added to the chat window. #5577
> Added margin to chat-window

- bigbluebutton-html5/private/config/settings.yml
@antobinary here are those extra configs we discuss about
> Extra config to be used with generic Etherpad servers

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
Fix a problem with the user list don't updating automatically lock status when lock settings had changed. #6524
> Fix problem with user list don't updating on lock change

- bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
.. to match the default width of chat module. Closes #6529
> Reduce the width of shared notes default width

- bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx
> Fix echo test bug where it stays active after closing

- bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
- bigbluebutton-html5/imports/ui/components/dropdown/styles.scss
- bigbluebutton-html5/imports/ui/components/media/styles.scss
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/service.js
- bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/styles.scss
Fix z-index in floatingOverlay style class of presentation. Fix #6457
> Fix z-index in presentation

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/private/locales/en.json
Adds an option to take presenter role in the actions menu.
Partially closes--  #6354 (requires #6535 )
> Add take presenter role option to actions menu

- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
Fixes the close menu button remaining visible and console error for undefined elements
> 2.0 - Improve dropdown menu click handler

- bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx
> Fix closing about modal

- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
> Changed default color in the whiteboard toolbar #5691

- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx
> Fix getBoundingClientRect error on console.

- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
> Fix for the issue with webcam preview and dropdown value

- build_script.sh
Only linting files that exist.
> Fix for the issue with linter failing if there are removed files

- bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
> Set the default draw thickness to 2

- bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx
- bigbluebutton-html5/imports/ui/components/error-screen/component.jsx
- bigbluebutton-html5/imports/ui/components/error-screen/styles.scss
- bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
- bigbluebutton-html5/private/locales/en.json
> Re style error component and implements error description.

- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
> Exclude moderator in the Randomly Assign

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
I keep the messages but omit the logs
> Remove ping-pong logs for webcams

- bigbluebutton-html5/client/compatibility/kurento-utils.js
> Fixed Safari check in kurento-utils

- bigbluebutton-html5/imports/ui/components/audio/audio-test/styles.scss
> Fix audio test play button.

- bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
> Fix blank panel when breakout rooms ends

- labs/docker/k8s/bbb-freeswitch.yaml
- labs/docker/k8s/bbb-web.yaml
- labs/docker/k8s/bbb-webhooks.yaml
- labs/docker/k8s/bbb-webrtc-sfu.yaml
this is for https://github.com/bigbluebutton/bigbluebutton/issues/6548 .
> Adding variables listed in the docker README

- bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
- bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
> Fix dropdown menu in webcam

- bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
- bigbluebutton-html5/imports/ui/components/video-provider/service.js
- The meetingId->voiceBridge swap is needed to use this with SFU 2.2.x
- Added a workaround for webcam viewers that is on 2.2 but not 2.0
> Backport commits needed for running 2.0 with SFU 2.2.x

- bigbluebutton-html5/client/compatibility/kurento-extension.js
> [HTML5] Chrome extension-based screensharing with the newest adapter

- bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
> Allow start breakout rooms with empty rooms when is freejoin.

- bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/styles.scss
Avoid fullscreen icon to overlap media icons
> Fixed video fullscreen position

- bigbluebutton-html5/imports/api/users/server/eventHandlers.js
- bigbluebutton-html5/imports/api/users/server/methods.js
- bigbluebutton-html5/imports/api/users/server/methods/toggleUserLock.js
- bigbluebutton-html5/imports/ui/components/user-list/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/service.js
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
- bigbluebutton-html5/private/locales/en.json
This PR add the capability to moderators unlock/lock attendees when the meeting is locked.
Issue: #6661
> Add action to unlock/lock individual attendee

- bigbluebutton-html5/imports/startup/client/base.jsx
My solution was to make the rendering of the component wait for the creation of the meeting, solving the identified race condition problem. Fix issue #6401
> Check if the meeting exists #6401

- bigbluebutton-html5/client/main.jsx
- bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
- bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
- bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/startup/client/logger.js
- bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx
- bigbluebutton-html5/imports/ui/components/app/component.jsx
- bigbluebutton-html5/imports/ui/components/audio/device-selector/component.jsx
- bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
- bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
- bigbluebutton-html5/imports/ui/components/whiteboard/service.js
- bigbluebutton-html5/imports/ui/services/audio-manager/index.js
- bigbluebutton-html5/imports/ui/services/auth/index.js
Changes to the logs:
- added `logCode`
- added build number
> Improve logging

- labs/docker/Makefile
- labs/docker/docker-compose.yml
- labs/docker/k8s/bbb-kurento.yaml
- labs/docker/kurento/Dockerfile
- labs/docker/kurento/docker-entrypoint.sh
- labs/docker/kurento/healthchecker.sh
- fix Makefile to build all images
- add the ability to build the kurento image from different sources
- add environment variables to customize stun, turn, rtp ports and websocket port
> Update docker files for Kurento

- bbb-webhooks/Dockerfile
- bbb-webhooks/config.js
- bbb-webhooks/messageMapping.js
Add events `rap-published`, `rap-unpublished` and `rap-deleted` when these actions are triggered by bbb-web due to an API call.
> Add recording events to webhooks

- bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
> Fix duplicated dropdowns on userlist.

- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
> Fix error when user is not moderator

- bigbluebutton-html5/imports/ui/components/external-video-player/service.js
Resolving #6725 
@lfzawacki does this look ok?
> Matching extra YouTube video IDs from different URL formats

- bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx
> Fix Warning when closing private chat

- bigbluebutton-html5/imports/startup/client/base.jsx
> Fix log error when meteor restart

- bbb-screenshare/app/deploy.sh
- bigbluebutton-config/bin/bbb-conf
- bigbluebutton-config/bin/bbb-record
- bigbluebutton-web/bbb-web.nginx
- record-and-playback/core/scripts/post_publish/post_publish_recording_ready_callback.rb
- record-and-playback/core/systemd/bbb-rap-archive-worker.service
- record-and-playback/core/systemd/bbb-rap-process-worker.service
- record-and-playback/core/systemd/bbb-rap-publish-worker.service
- record-and-playback/core/systemd/bbb-rap-sanity-worker.service
- record-and-playback/deploy.sh
I updated files and directories paths, used the right `bigbluebutton` user for recording directories. I also made distinct `SERVLET_DIR`, `TOMCAT_DIR` and `LTI_DIR` in `bbb-conf`.
@kepstin and @ffdixon can you please review it?
> Update permissions and config file path for the new bbb-web

- bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
convert does not auto rotate image by default.
https://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/
> Fix convert jpg with orientation metadata

- bigbluebutton-html5/imports/ui/components/chat/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/container.jsx
- bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
- bigbluebutton-html5/imports/ui/components/chat/service.js
- bigbluebutton-html5/private/locales/en.json
> Fix chat input between chats

- bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/styles.scss
- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss
> Fix sidebar elements appearance

- bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/6748
```
Result for enter api call
{
"response": {
"returncode": "SUCCESS",
"fullname": "User 4638856",
"confname": "random-9175585cvcv",
"meetingID": "045d68fcdfb04bc7be99fcba60642edd9740b940-1549922460436",
"externMeetingID": "random-9175585cvcv",
"externUserID": "w_fs3cblzf6th1",
"internalUserID": "w_fs3cblzf6th1",
"authToken": "emuo8zxcjiuj",
"role": "MODERATOR",
"guest": false,
"guestStatus": "ALLOW",
"conference": "045d68fcdfb04bc7be99fcba60642edd9740b940-1549922460436",
"room": "045d68fcdfb04bc7be99fcba60642edd9740b940-1549922460436",
"voicebridge": "70667",
"dialnumber": "613-555-1234",
"webvoiceconf": "70667",
"mode": "LIVE",
"record": "false",
"isBreakout": false,
"logoutTimer": 0,
"allowStartStopRecording": true, …
```
>  - fix json response format for stuns and enter api

- bigbluebutton-html5/imports/api/presentations/server/handlers/presentationRemove.js
> Fix remove presentation feature

- bigbluebutton-html5/imports/ui/components/notifications-bar/component.jsx
> Prevent SR seeing timer notifications as alerts

- bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js
Issue #6705
(`logContents` is only printed once - under `meta`)
> Fix for duplication in logs

- record-and-playback/presentation/playback/presentation/2.0/playback.js
Revert the changes to recording scripts that broke presentation/chat pending a better fix to captions
> Break captions

- bigbluebutton-html5/imports/ui/components/poll/component.jsx
- bigbluebutton-html5/imports/ui/components/poll/styles.scss
- bigbluebutton-html5/private/locales/en.json
> Make SR announce poll inputs individually

- bigbluebutton-html5/imports/ui/components/tooltip/component.jsx
> Fix for the tooltip error on mobile

- bigbluebutton-html5/imports/ui/components/notifications-bar/component.jsx
> Fix for console error joining breakout room

- bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx
> Fix chat save feature on Firefox

- bigbluebutton-html5/imports/ui/components/chat/component.jsx
fixes the following console error:
> Fix console error

- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
> Fix unread message indicator remains active

- bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutJoinURL.js
- bigbluebutton-html5/imports/api/breakouts/server/methods/requestJoinURL.js
- bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js
- bigbluebutton-html5/imports/api/users/server/publishers.js
- bigbluebutton-html5/imports/startup/client/base.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
- bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/service.js
- bigbluebutton-html5/imports/ui/components/user-list/service.js
> Allow re-invite user that didn't joined in meeting

- bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js
> Fix clear public chat

- bigbluebutton-html5/imports/api/annotations/index.js
- bigbluebutton-html5/imports/api/annotations/server/methods.js
- bigbluebutton-html5/imports/api/annotations/server/methods/sendBulkAnnotations.js
- bigbluebutton-html5/imports/ui/components/whiteboard/service.js
This PR prevent the drawing problem by guaranteeing the annotation messages order.
Issue: #6038
> Prevent drawing problem

- bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
- bigbluebutton-html5/private/locales/en.json
Change the action label for when a video is already been shared.
Issue: #6604
> Update share youtube video label

- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
- bigbluebutton-html5/private/config/settings.yml
Moves the help link to `settings.yml`.
Closes #6029
> Make the help link configurable

- bigbluebutton-html5/imports/ui/stylesheets/variables/general.scss
> Center user avatar icons in Edge

- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js
> Handle setting presentation as downloadable prior to uploading it

- bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
> Fix incorrect reference in pres isDownloadable

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
- bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
> Make feedback work on logout

- record-and-playback/presentation/playback/presentation/2.0/playback.js
Tested a little, looking good. Needs better testing with playback in mobile and uploading new presentations.
Please take this whole issue thread as consideration on this https://github.com/bigbluebutton/bigbluebutton/issues/6463
> Playback loading closed captions

- bigbluebutton-html5/imports/ui/components/actions-bar/service.js
> Fix breakout room items don't appearing

- bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
Additionally using client logger to handle feedback (in addition to the existing logging).
> Client logger on feedback

- bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
This PR enables to turn on/off the mute meeting option in user options menu.
_Issue: #6817_
> Fix mute all users option
