bigbluebutton/bigbluebutton

bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/component.jsx
=> Preserve original capitalization of username in fullscreen button.

bigbluebutton-html5/imports/ui/components/error-screen/styles.scss
=> Fix text overflow in error screen button.

bigbluebutton-html5/imports/api/polls/server/modifiers/addPoll.js
=> Exclude dial in users from polls

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Issue #6839.
- Fix for the presentation full screen button in Edge (didn't show).
- Fix for the webcam full screen button in Edge (didn't work).
=> Fullscreen in Edge

bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js
=> Fix links in welcome message

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
=> Fix the issue with videos overlapping whiteboard

bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss, bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss
=> Improve talking indicators in edge

bigbluebutton-html5/imports/ui/components/audio/echo-test/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/container.jsx
=> Mute shared video when echo test is open.

bigbluebutton-html5/imports/ui/components/chat/service.js
=> Fix save chat with URL

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx, bigbluebutton-html5/private/config/settings.yml
- Send log record batches more often
- Add timeout before going to logout URL
=> Improvement for the feedback client logging

bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss
Fixes:
* Main meeting can view all breakout on server.
* Start meeting with null duration. #6919 
Add:
* Indicator with number of user selected for each breakout. #6920
=> Breakout room edge cases.

bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
Welcome message is now more prominent and is no longer removed when the clear public chat function is run. #6673
=> Improve welcome message

bigbluebutton-html5/imports/api/annotations/addAnnotation.js, bigbluebutton-html5/imports/api/annotations/server/modifiers/addAnnotation.js, bigbluebutton-html5/imports/api/annotations/server/publishers.js, bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/captions/server/publishers.js, bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js, bigbluebutton-html5/imports/api/group-chat/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/polls/server/publishers.js, bigbluebutton-html5/imports/api/presentation-pods/server/publishers.js, bigbluebutton-html5/imports/api/presentation-upload-token/server/publishers.js, bigbluebutton-html5/imports/api/presentations/server/handlers/presentationConversionUpdate.js, bigbluebutton-html5/imports/api/presentations/server/publishers.js, bigbluebutton-html5/imports/api/screenshare/server/publishers.js, bigbluebutton-html5/imports/api/slides/server/modifiers/resizeSlide.js, bigbluebutton-html5/imports/api/slides/server/publishers.js, bigbluebutton-html5/imports/api/users-settings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/api/voice-users/server/publishers.js, bigbluebutton-html5/imports/api/whiteboard-multi-user/server/publishers.js, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
* reduced log noise for common benign events 
* marked video and locale warnings as such (previously error level)
* addressed missing variable declaration in annotation code
Closes #6922
=> Reduce log noise; minor adjustment to locale error catcher

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
* enable screensharing by default
* updated react-color (npm vulnerability audit)
=> Enable screenshare by default; npm audit

bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/container.jsx, bigbluebutton-html5/imports/ui/components/poll/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js, bigbluebutton-html5/private/locales/en.json
=> Fix poll exception when no presentation selected.

bigbluebutton-html5/imports/ui/components/dropdown/list/styles.scss
=> Fix set status chevron icon clipped on hover

bigbluebutton-html5/imports/startup/client/base.jsx
=> Show subscription are ready at the right time.

bigbluebutton-html5/imports/ui/components/user-list/service.js
=> Don't show demote/promote action in breakout rooms

bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx
=> Mute locked users instead of removing audio.

bigbluebutton-html5/imports/api/screenshare/server/modifiers/clearScreenshare.js
=> Add callback to screenshare remove

bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
=> Adjust background for name in webcam area

bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Improved YouTube URL input field

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/private/config/settings.yml
=> Change as mime types are coded

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
Fixes:
* Don't allow viewers users views all breakouts rooms meeting.
* fix Join modal being open when generate URL. #6787
* Fix users get stuck in `generating url...` state.
=> Fix few breakout  room bugs.

bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js, bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
We currently only send the DTMF(1) to transfer to the main voice bridge once and in some cases with Firefox we find that FreeSWITCH isn't ready to receive right away. This PR adds retries of the DTMF for Firefox users so they don't get a premature error message.
It's a workaround for the following FS bug, https://freeswitch.org/jira/browse/FS-11661.
=> Add transfer DTMF resend for Firefox users

bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Add message to share YouTube modal

bigbluebutton-config/bin/bbb-conf
- Replace  legacy command parsing ` by $().
- Update logs paths for clean and zip commands.
- Fix third party applications detection.
- Better CentOS detection.
- Remove unused function and variables.
- Unify indentation using spaces.
- Remove trailing spaces.
=> Refactoring to bbb-conf shell script application for 2.2

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
Document conversion to SWF can be now switched on and off.
=> Added a new flag to switch SWF files conversion on and off

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala, akka-bbb-apps/src/test/scala/org/bigbluebutton/core/AppsTestFixtures.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/BreakoutMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/CreateBreakoutRoom.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/MeetingsManagerActor.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
=> Copy dial number from the parent room to all breakout rooms.

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
=> Fix weird number in breakout user counter

bigbluebutton-html5/.gitignore
=> Remove old folders references of .gitignore file.

bigbluebutton-client/branding/default/style/css/V2Theme.css, bigbluebutton-client/src/org/bigbluebutton/main/model/users/JoinService.as, bigbluebutton-client/src/org/bigbluebutton/main/model/users/UserService.as, bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatTab.mxml
This PR adds in some missing properties in the enter API parsing. I also rearranged the parsing in JoinService so that it matches where it's used in UserService. This change should hopefully make it easier to compare the two.
I also removed some whitespace from the ChatTab and made it look a little better.
=> Fix enter API parsing and cleaned up the ChatTab

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-close-button/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx
Some behaviors I included to make everything more stable:
- on presenter change: reset fit-to-width
- on slide change: reset fit-to-width
- when in fit-to-width and zoomed:
- on resize: reset zoom
=> Fit-to-width adapted to the new toolbar

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
=> Close local webcam view on logout

bigbluebutton-html5/imports/ui/components/recording/component.jsx, bigbluebutton-html5/imports/ui/components/recording/container.jsx, bigbluebutton-html5/private/locales/en.json
=> Add resume title to recording modal

bbb-common-web/src/test/resources/get-meeting-info.ftlx, bbb-common-web/src/test/resources/get-meetings.ftlx, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx, bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meetings.ftlx
=> Fix API variables formatting for meeting endTime and duration.

bigbluebutton-html5/client/main.html
This PR adds detection for IE users and displays a warning to them to use a different browser. I had to put the warning outside of the application because our main application code won't load because of newer functionality not being compatible.
=> Warning for IE users

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
=> Fix user counter in breakout room panel

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
This PR adds a spacebar hotkey for the presenter to activate the whiteboard Pan tool.
#2198
=> Add spacebar hotkey to toggle whiteboard Pan tool

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
=> Fix moderator being able to stop recording when it aren't allowed

bigbluebutton-html5/imports/ui/components/checkbox/component.jsx, bigbluebutton-html5/imports/ui/components/icon/component.jsx, bigbluebutton-html5/imports/ui/components/modal/fullscreen/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/service.js, bigbluebutton-html5/imports/ui/components/settings/submenus/closed-captions/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/participants/component.jsx
This PR sort presentations by his upload timestamp, also update some components to avoid unnecessary re-render when presentation pages are being processed.
_Issue: #6840_
=> Sort presentation list

bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/styles.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/breakpoints.scss
=> Improved permissions-overlay

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx
This PR will add the suggestions in #6838:
- ensure menu options are in upper case
- remove white spaces from option labels
- converts numbers to alpha characters in option labels
- removes duplicate options appearing in menu
=> Improvements to quick poll menu options

bigbluebutton-html5/imports/ui/components/presentation/component.jsx
=> Fix client crashing when prensentation isn't converted

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
=> Fix error log caused by dropdown event listener.

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
=> Restrict when spacebar shortcut is activated

bigbluebutton-html5/imports/ui/components/presentation/presentation-close-button/component.jsx, bigbluebutton-html5/private/locales/en.json
Close presentation was changed to Hide presentation.
Closes #7060
=> Change close presentation to hide presentation

bigbluebutton-html5/imports/api/guest-users/server/methods.js, bigbluebutton-html5/imports/api/guest-users/server/methods/changeGuestPolicy.js, bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/container.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/service.js, bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss, bigbluebutton-html5/private/locales/en.json
This PR adds a checkbox on waiting users panel for change meeting guest policies and "remember" the moderator choice.
=> Add remember checkbox for remember guest policy choice

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx
=> Fix state for record-indicator

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
=> Open breakout room in new tab automatically when request new join url

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js
This was causing
`error: CLIENT LOG: TypeError: o.findOne(...) is undefined`
and 
`error: CLIENT LOG: TypeError: Cannot read property 'name' of undefined`
I am not sure how to reproduce the issue but tracing logs led me here
=> Remove metadata duplication from Kurento client logs

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/whiteboard/SendWhiteboardAnnotationPubMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala
=>  - log whiteboard shape that has null values

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/private/locales/en.json
=> Add spacebar to the "hotkey" list

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
=> Change icons for audio toast notifications

labs/stress-testing/bbb-test
- Chromium-based browsers support
- new tabs/windows switch
- better portatibility (bash may be not /bin/bash on BSD systems, 'which' command is not POSIX-compatible)
- detect local IP via hostname command
- allow passing arguements to script in any order
- allow connecting via HTTPS
- allow setting custom sleep time
=> bbb-test v0.3:

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx, bigbluebutton-html5/private/locales/en.json
Feature to save (download) user names for moderators.
Closes #7203
=> Feature download user names list for moderators

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/private/locales/en.json
=> Add arrow key shortcuts to switch presentation slides

bigbluebutton-html5/imports/ui/components/settings/component.jsx
=> Hide closed captions option from settings

bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/service.js, bigbluebutton-html5/imports/ui/components/poll/live-result/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Improve polling live result design / sorting

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Before:
(separate lines, missing info)
After:
=> Reduce webcam logging lines, improve info quality

bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
=> Fix toolbar don't reszing when breakout close.

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/app/service.js, bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-button/container.jsx, bigbluebutton-html5/private/locales/en.json
=> Add toast indicating to upgrade iOS version (12.2+)

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
=> Change dial user icon to phone on in user list

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
=> Update hyperlink color

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
Added a few more items to the logs
Switched `'Received error from SFU:` from debug to error level
=> Added logCode in video_provider

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/service.js
=> Fix user count in breakout panel using users collection

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
=> Update record button label

bigbluebutton-html5/imports/ui/components/app/service.js, bigbluebutton-html5/imports/ui/components/toast/component.jsx
=> Fix typo in regular expression detecting iOS version

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/component.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/container.jsx, bigbluebutton-html5/imports/ui/components/external-video-player/modal/styles.scss, bigbluebutton-html5/private/locales/en.json
=> merge start/stop buttons in share external video modal

bigbluebutton-html5/imports/api/breakouts/server/eventHandlers.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/breakoutStarted.js, bigbluebutton-html5/imports/api/breakouts/server/handlers/joinedUsersChanged.js, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx
=> Fix create breakout room missing some users.

bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
This PR tries fix the text annotation bug reverting to old annotation subscription handler.
=> Fix text annotation

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/container.jsx
=> Fix breakout room notification with wrong initial state.

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
=> Unshare webcam when join in a breakout room

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
=> Create API returns an error when no password parameter is provided

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
=> Fix downloaded file encoding.

bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js
The callback was not checking if the meteor update had affected any documents.
Closes #7314
=> Fixes the duplicated messages when meeting is ended

bigbluebutton-html5/imports/ui/components/poll/component.jsx
=> Fix custom poll button deactivating start button

bigbluebutton-html5/imports/startup/client/base.jsx
=> Fix error screen at meeting ends

bigbluebutton-config/bin/bbb-conf
=> Added check for multiple bbb-common-message libs

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx
Also adds `htmlFor` attribute to labels for select elements in webcam preview
=> Move warnings to top of modals

bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
=> Breakouts should omit the end meeting menu

bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/private/config/settings.yml
=> Add password field for redis settings

bigbluebutton-html5/package-lock.json
Related to https://github.com/bigbluebutton/bigbluebutton/pull/7283/commits/8faf5d809cabf18e4b2dda838ed4f18dccb182f0 and #7283 
https://github.com/sass/node-sass/issues/2625
`found 0 vulnerabilities`
=> Updated "tar" dependency node-sass #2625 

bigbluebutton-html5/imports/ui/components/meeting-ended/rating/component.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/rating/styles.scss
=> Add style to feedback legend label

bigbluebutton-config/bin/bbb-conf
=> Display etherpad service status.

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Reverts bigbluebutton/bigbluebutton#7384
Turns out others are using the API without passing passwords.
=> Revert "Create API returns now returns error when no passwords provided for meeting"

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/container.jsx, bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
=> Stop webcams when opens audio modal.

bigbluebutton-html5/imports/ui/services/auth/index.js
Inside of Tracker.autorun checks if subscription already exists before subscribing.
Closes #7314
=> Verifies if subscription already exists before calling subscribe

bigbluebutton-html5/imports/ui/components/actions-bar/service.js
=> Don't show phone user on create breakout room list

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/private/locales/ar.json, bigbluebutton-html5/private/locales/en.json
=> Localise offline status in chat

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/private/locales/en.json
This PR makes the screen reader announce the time along with it's measure unit. In this case, minutes.
=> Add time unit to aria labels in create breakout rooms modal

bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/private/locales/en.json
This will make the screen reader also announce the current application font size percentage for the Decrease and Increase font size button aria labels in the settings modal.
=> Add current size to Increase / Decrease font size btn aria labels

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx
=> Fix leaveSession static not called

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/container.jsx
=> Fix breakout showing wrong message in breakout start

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Hopefully this will help us debug any problems happening in specific servers and or clients.
=> Add some logs to the external video sync

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/imports/ui/services/user/mapUser.js
=> Add breakout  room indicator in user list.

bigbluebutton-html5/imports/ui/services/auth/index.js
=> Revert #7440 due to causing #7502 join stuck

bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
=> Fix overflow of webcams-draggable

bigbluebutton-html5/imports/api/annotations/server/methods/sendAnnotation.js
=> Add meteor check for annotations to avoid malformed message.

bigbluebutton-html5/imports/ui/components/end-meeting-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/tests/webdriverio/pageobjects/chat.page.js, bigbluebutton-html5/tests/webdriverio/pageobjects/landing.page.js, bigbluebutton-html5/tests/webdriverio/pageobjects/modal.page.js, bigbluebutton-html5/tests/webdriverio/pageobjects/page.js, bigbluebutton-html5/tests/webdriverio/pageobjects/settings.page.js, bigbluebutton-html5/tests/webdriverio/specs/chat.spec.js, bigbluebutton-html5/tests/webdriverio/specs/settings.spec.js, bigbluebutton-html5/tests/webdriverio/utils.js, bigbluebutton-html5/tests/webdriverio/wdio.conf.js
This PR is based on the code that was written by me and @OZhurbenko (pull requests: https://github.com/bigbluebutton/bigbluebutton/pull/3972, https://github.com/bigbluebutton/bigbluebutton/pull/4242, https://github.com/bigbluebutton/bigbluebutton/pull/4923).
`npm test` - command to run the tests. `baseUrl` needs to be set in `wdio.conf.js`.
Commands for the Selenium server:
`./node_modules/.bin/webdriver-manager update`
`xvfb-run ./node_modules/.bin/webdriver-manager start`
(Xvfb can be installed with `sudo apt-get install xvfb`).
=> WebdriverIO Tests

bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/component.jsx
=> Pass callback for closing of permissions-overlay

bigbluebutton-html5/imports/startup/client/base.jsx
=> Fix the warning that appears when user enters as guest

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss
=> Align the checkbox and the label (guest management)

bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
=> Fix webcam size after minimize the presentation

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/invitation/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/service.js, bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/service.js, bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss, bigbluebutton-html5/imports/ui/components/notifications-bar/container.jsx
Creates component for breakout invitation to organize the code and make it better to read and understand.
Besides, it fixes a bug which allowed the user to join the breakout room twice when the user clicks in "Join room".
Closes #7555
=> Creates component for breakout invitation

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ImageToSwfSlidesGenerationService.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfToSwfSlidesGenerationService.java, bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml
=> Fix svgImagesRequired, generatePngs and swfSlidesRequired flags

bigbluebutton-html5/imports/api/captions/server/modifiers/updatePad.js, bigbluebutton-html5/imports/api/note/index.js, bigbluebutton-html5/imports/api/note/server/eventHandlers.js, bigbluebutton-html5/imports/api/note/server/handlers/padUpdate.js, bigbluebutton-html5/imports/api/note/server/helpers.js, bigbluebutton-html5/imports/api/note/server/index.js, bigbluebutton-html5/imports/api/note/server/modifiers/addNote.js, bigbluebutton-html5/imports/api/note/server/modifiers/updateNote.js, bigbluebutton-html5/imports/ui/components/note/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss
=> Shared notes unread indicator

bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss
=> Fix shared notes not highlighting when selected

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
=> Fix last participant isn't shown in user list on android

bigbluebutton-html5/imports/ui/components/modal/fullscreen/component.jsx, bigbluebutton-html5/imports/ui/components/modal/simple/component.jsx
=> Handle dismiss prop being undefined. 

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/container.jsx
=> Hide fullscreen buttons from iPhones

bigbluebutton-html5/imports/ui/components/legacy/component.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-html5/private/locales/en.json
=> Add Chrome on iOS to legacy detection

bigbluebutton-html5/.eslintrc.js, bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/tests/webdriverio/specs/chat.spec.js, bigbluebutton-html5/tests/webdriverio/specs/presentation.spec.js
- Update `.eslintrc.js`
- Improve chat-related tests
- Add `presentation.spec.js`
=> WebdriverIO tests improvements

bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx
=> Fix user names not displaying on cursors in RTL

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
=> Fix published poll results not rendering correctly in RTL

bigbluebutton-html5/imports/ui/components/polling/styles.scss
=> Prevent access to dropdown menu while showing poll (small screens)

bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/variables/video.scss
=> Draggable webcams grid improvements

bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Fix DOM injection in number of rooms select

bigbluebutton-html5/imports/api/users/server/methods/userChangedSettings.js, bigbluebutton-html5/imports/api/users/server/modifiers/setChangedSettings.js
Improve logic to send a message only when value had changed, instead of every settings save.
=> Improve userChangedSettings method

bigbluebutton-html5/private/locales/en.json
Closes #7615
I like @fungma 's point about the localization to other languages.
=> Improve wording in chat placeholder #7615

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/polling/container.jsx, bigbluebutton-html5/private/config/settings.yml
=> Add enabled poll property in settings.yml

bigbluebutton-html5/imports/ui/services/auth/index.js
... to provide easier matching of different sessions by the same user
...,"requesterUserId":"w_kaekhnokbzrm","fullname":"2_________","confname":"Demo Meeting2","externUserID":"w_kaekhnokbzrm","uniqueClientSession":"ys2kfgqmprma9265-ptp1zvo"...
=> Prepend sessionToken to uniqueClientSession

bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
=> Add lock verification for users actions

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
=> Fix cannot read property 'focus' of null

bigbluebutton-html5/imports/ui/services/user/mapUser.js
=> Handle default value for isBreakoutUser property for dummy users

bigbluebutton-html5/imports/api/ping-pong/server/publishers.js, bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/startup/server/index.js
Users were getting incorrectly marked as 'online' causing the partial users to get picked up by UI components and processed. Still needs good testing with more people, but I'm pretty sure this is the cause of the crashes.
Fixes #7739
=> Fix crash from invalid online users

bigbluebutton-html5/imports/ui/components/poll/component.jsx
=> Fix publishing second custom poll not working

bigbluebutton-config/bin/bbb-conf
=> Update all recording types link tags

bigbluebutton-html5/imports/ui/components/audio/audio-dial/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-dial/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Tip that explains how to mute/unmute yourself using a phone

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/services/api/index.js
=> Prevent client freze on Meteor.call() if not connected

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
=> Add missing end of re-run for fetchToken

bigbluebutton-html5/imports/ui/components/media/styles.scss
Related to #7756 
(by @capilkey )
=> Hide scrollbar for media (webcams)

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
=> Webcam draggable refactoring

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
=> Fix panel resizing for RTL locales

bigbluebutton-config/bin/bbb-conf
=> Fix bbb-transcode-akka not being properly started and stopped.

bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx, bigbluebutton-html5/private/config/settings.yml
=> Creates parameter to enable or disable the Logout option

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/media/service.js, bigbluebutton-html5/private/config/settings.yml
=> Changes the position of the parameter enableExternalVideo in the settings.yml

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/private/config/settings.yml
=> Add enabled parameter to chat in settings.yml

bigbluebutton-html5/imports/api/meetings/server/methods/toggleWebcamsOnlyForModerator.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/webcamOnlyModerator.js, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/container.jsx
=> Fix webcams of other viewers lock toggle

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
Made a thorough review of all log calls in the video-provider component to make it output useful information.
- Removed some unused `extraInfo` payloads
- Remade various log messages to try to establish a coherent and informative flow of share-unshare-error
- Refactored some minor stuff I found along the way and added some comments.
=> Refactor video-provider component logs

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/public/compatibility/kurento-extension.js
`47.30.135.243 [2019-07-23T06:43:57-04:00] [{"name":"clientLogger","level":50,"logCode":"startup_error","stackTrace":"ReferenceError: id is not definedn    at T.handleIceCandidate (https://demo.bigbluebutton.org/html5client/fcd69a3906e02cdc87d66d2dc86d0de51b7caf9d.js?meteor_js_resource=true:125:362881)n    at T.onWsMessage (https://demo.bigbluebutton.org/html5client/fcd69a3906e02cdc87d66d2dc86d0de51b7caf9d.js?meteor_js_resource=true:125:359460)n    at WebSocket._handleMessage (https://demo.bigbluebutton.org/html5client/fcd69a3906`
=> Use correct property in log for video-provider

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
https://www.tutorialkart.com/mongodb/mongodb-project-fields-in-result/
=> Minor optimization using Fields in miniMongo

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
=> Removes tooltip from start recording button

bigbluebutton-config/cron.daily/bigbluebutton
Do not delete errors.log as it will contain information when KMS crashes.
=>  Delete only kurento logs

record-and-playback/screenshare/scripts/process/screenshare.rb
Fixes issue https://github.com/bigbluebutton/bigbluebutton/issues/7867
=>  Add missing param when calling create_webcam_edl

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-list/styles.scss
=> Add space to the right and below the welcome message correct

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
Closes #7824 
Tested on MacOS, Ubuntu - firefox, chrome and safari.
=> Fix cursor stuck on dragging in firefox

bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Delay `setCustomData` in order to avoid problem with undefined values.
=> Delay setCustomData to after join

bigbluebutton-html5/imports/ui/components/meeting-ended/rating/component.jsx
=> Fix layout in feedback modal (RTL)

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
=> Fix single webcam overflow

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Fixes #7916
I think the issue was introduced when I removed the mapUser usage from the webcam code.
=> Don't show muted on video when listenOnly

bigbluebutton-html5/imports/api/group-chat-msg/index.js, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
=> Fix chat input placeholder text

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/cursor-listener/component.jsx
The problem was caused by an event not being handled properly.
=> Prevent problem after drawing on tablet/mobile

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
This PR change the first tool loaded in whiteboard toolbar when multi user is enabled by presenter.
Closes #7340
=> Change the default tool in multi-user

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This PR fixes the loss of the chat input focus when the user-list updates.
=> Fix chat input loss of focus

bigbluebutton-html5/imports/api/group-chat-msg/server/methods/startUserTyping.js, bigbluebutton-html5/imports/api/group-chat-msg/server/methods/stopUserTyping.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/startTyping.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/stopTyping.js, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
This PR fixes ghost users appearing in the typing indicator and improves the responsiveness of the indicator.
=> Fix ghost users showing in the typing indicator

bigbluebutton-config/bin/bbb-conf
Update to leave 127.0.0.1 for kurento[0].url (see https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/37)
=> Don't update kurento[0].url

bigbluebutton-html5/imports/ui/components/chat/container.jsx
Fix the logic to show the partner disconnected message
=> Recovery partner disconnected message

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/tests/webdriverio/pageobjects/chat.page.js, bigbluebutton-html5/tests/webdriverio/specs/chat.spec.js, bigbluebutton-html5/tests/webdriverio/specs/presentation.spec.js, bigbluebutton-html5/tests/webdriverio/specs/settings.spec.js
`Enter` key doesn't work. This PR replaces it with button clicks.
=> Automated tests: button clicks instead of pressing Enter key

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx
It's hard to reproduce the issue in #7980, but this PR should fix it.
Fixes #7980 (I hope)
=> Make sure the whiteboard toolbar exists first before animating

bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
This PR fixes the log for mute showing as unmute. It also adds some audio logs associated with the breakout rooms.
=> Fix mute audio log

bigbluebutton-html5/imports/ui/components/shortcut-help/styles.scss
=> Fix spacing for keyboard shortcuts modal (RTL)

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
=> Fix space next to current presentation (RTL)

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
=> Fix chat error message alignment (RTL)

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Pretty extensive rework of how the chat messages update and figure out whether they are on the screen.
=> Improve chat rendering performance and rework read message detection

akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/FreeswitchConferenceEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ConnectionManager.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/FreeswitchApplication.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/CheckFreeswitchStatusCommand.java, akka-bbb-fsesl/src/main/scala/org/bigbluebutton/freeswitch/RxJsonMsgHdlrActor.scala
- add more logs to trace messages
- add FS status check by sending ESL message to FS
=>  Add more akka fsesl logs

bigbluebutton-html5/imports/ui/components/media/service.js
Remove the webcam and poll restrictions, so it's possible to start with the presentation minimized.
=> Give the option to start with presentation minimized

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
This should fix the problem reported in #8044
=> Detect presenter change and reassign external video to new presenter

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/startTyping.js, bigbluebutton-html5/imports/ui/components/chat/message-form/typing-indicator/container.jsx
=> Remove Viewers from Users Typing when User list is locked

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/service.js, bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss, bigbluebutton-html5/private/locales/en.json
Disable the option to join a room in breakout room panel if the user is already connected to the breakout room
=> Prevent user to connect again if already in breakout room

bbb-lti/build.gradle, bbb-lti/grails-app/i18n/messages.properties, bbb-lti/grails-app/views/tool/error.gsp, bbb-lti/grails-app/views/tool/index.gsp
It should also fix the getRecordings call in the LTI application.
=> Fix LTI resources build

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
=> Prevent close btn remaining visible on mobile (user dropdown)

bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-name/styles.scss
=> Fix unread indicator not displaying with long names

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
Builds upon #8122 and fixes the final remaining issue with the PR.
=> Viewer webcam lock unshare

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx
=> Fix viewer webcam not unsharing when lock setting is enable

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/service.js
This PR builds upon #8125 and fixes the last remaining issues.
=> List users in a breakout in the breakout panel

bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/service.js
=> Show breakout room members under the breakout room name

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/private/config/settings.yml
Add a option to generate a heap dump file so it's possible to check a memory snapshot.
=> Add heapdump dependency

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Prevent the user to click multiple times in the upload button.
=> Fix multiple clicks on upload button

record-and-playback/core/lib/recordandplayback/generators/video.rb, record-and-playback/presentation/playback/presentation/2.0/lib/writing.js, record-and-playback/presentation/playback/presentation/2.0/playback.html, record-and-playback/presentation/playback/presentation/2.0/playback.js
#5986
Some changes we made for `mp4` media recordings to work with iOS and extra adjustments we have on our playback
=> Patching playback updates for iOS

bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
=> Fix actions button misplacement in RTL mode

record-and-playback/core/scripts/archive/archive.rb
This fixes the archive script after #8233 was merged.
=> Fix typos in archive script

bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
One small change to exit the external video emit checker a little earlier and another change to increase the sync interval to 5 seconds.
=> Adjust external video sync interval and emit check

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx
=> Exit main audio when moderator joins breakoutroom via panel

bigbluebutton-html5/imports/ui/components/presentation/service.js
=> Fix quick poll detecting wrong options

bigbluebutton-html5/imports/ui/components/presentation/service.js
Fire Fox doesn't support negative lookaheads
=> Replace negative lookahead used in Regex

bbb-apps-common/src/main/scala/org/bigbluebutton/client/meeting/UserActor.scala
- fix compile issue on bbb-apps-common as a result of adding a timestamp field on the header.
=>  red5 bbb apps compile issue

bigbluebutton-config/bin/bbb-conf
=> Force root user check when assigning a new IP.

bigbluebutton-config/bin/bbb-conf
=> Set IP and shared secret for bbb-webhooks based on the right files.

bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx
I'm fetching the role data in the constructor which is unorthodox, but in this case I specifically don't want the data to be reactive.
Closes #8284 
An alternative to #8288
=> Attaches the user's role with feedback

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/container.jsx, bigbluebutton-html5/private/locales/en.json
=> Add notification when recording started with no mic users

bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss, bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
This PR fix #7859 and closes #7855
=> Webcam resizable

bigbluebutton-config/bin/bbb-conf
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/8312
=> Keep html5 client log file permissions

bigbluebutton-html5/imports/ui/components/breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/typography.scss
=> Update text style

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/imports/utils/keyCodes.js
This used to be a feature in the Flash client and this is necessary for presentation remotes to work with the HTML client.
=> Added event listener to change slides with Page Up and Page Down

record-and-playback/screenshare/scripts/process/screenshare.rb
=> screenshare recording format: add breakout room info to metadata.xml

bigbluebutton-html5/public/compatibility/sip.js
The UI is temporary and needs to be replaced with something else, but I need to get something in.
=> Handle sip.js autoplay failure

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
This PR adds a hangup when the call times out which should hopefully solve a case where we can have two calls running at the same time. It also contains protections against accidentally double-clicking to join the audio twice.
=> Hangup sip.js on timeout and stop audio join double click

bigbluebutton-html5/imports/api/voice-users/server/modifiers/updateVoiceUser.js, bigbluebutton-html5/imports/ui/components/app/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/service.js, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/styles.scss
This PR adds improvements to the styling and an increase in the length of time a user remains visible in (doubling from 3 - 6 seconds).  The indicator also shows when users have been muted once they have spoken.
=> Update talking indicator styles

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx
Swapping the keys as requested by @kaitkrull  to fit most of the remotes.
=> Swapping PAGE_UP and PAGE_DOWN key bindings

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
- Add an outbound ICE queue for all video-provider client peers
- Only send candidates after the SDP exchange was locked (done because of a stop-start glare that can happen on high load)
- Fix reconnect interval calculation
- Add reconnection for viewers on ICE failures
- Add reconnection for viewers on WebRTC stack errors
- Add reconnection for viewers on SFU server-side errors
=> Improvements to camera viewer reconnections and added an outbound ICE queue for cameras

bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/public/compatibility/kurento-extension.js
These changes are backward compatible. Will work with either 2.3.x or 2.4.x. SFU 2.4.x also works without this PR.
The changes are important, though, because with them we can optimize some stuff in the SFU component.
=> [HTML5] Compatibility changes for SFU 2.4.x

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
The goal of the PR is to get more information about when the listen only connections run into issues.
=> Listen only logging improvements

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Applying the same logging changes to 2.2 so we can get data sooner.
=> Listen only logging improvements (2.2 version)

bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js, bigbluebutton-html5/imports/api/cursor/server/streamer.js, bigbluebutton-html5/imports/ui/components/cursor/service.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx, bigbluebutton-html5/private/config/settings.yml
Add debug messages to cursor streamer
=> Add debug messages to cursor streamer

record-and-playback/core/scripts/rap-process-worker.rb
It will only process recordings in which the ID matches the pattern. By default the pattern is `nil` and it will process all recordings. The pattern is passed as in:
```
rap-process-worker.rb -p "[0-4]$"
```
The pattern is a string that's converted to a regex and matched against the recording ID.
An example on how to have multiple workers running in the server:
* Edit `/usr/lib/systemd/system/bbb-rap-process-worker.service` and set the command to: `ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb -p "[0-4]$"`.
* Copy `/usr/lib/systemd/system/bbb-rap-process-worker.service` to `/usr/lib/systemd/system/bbb-rap-process-worker-2.service`.
* Edit `/usr/lib/systemd/system/bbb-rap-process-worker-2.service` and set the command to …
=> Add option to rap-process-worker to accept a filtering pattern

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
https://github.com/meteor/meteor/pull/10527/commits/ c0bf4b281f87327134bea32447262f3085caad7d
=> Update package fibers to 4.0.x to work with node12

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/utils/sdpUtils.js, bigbluebutton-html5/public/compatibility/sip.js
Looking to get more info about the candidates being generated by users. This will allow us to generate statistics. The big thing I'm looking for is how many people have IPv6 and how many people generate a relay candidate.
=> Extra log messages for sipjs candidates

bigbluebutton-html5/imports/utils/sdpUtils.js
=> Move sip.js sdp logging properties under extraInfo

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
=> Fix restore presentation button overlap (Mobile - Presenter)

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
=> Prevent chat error shifting input field

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/styles.scss
=> Fix spacing in note button

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/utils/sdpUtils.js, bigbluebutton-html5/public/compatibility/sip.js
This PR adds parsing of the selected ICE candidate for sip.js calls by checking the WebRTC stats after the ICE connection has succeeded. This will help with getting statistics on the types of candidates being used.
=> Log the selected sip.js candidate

bigbluebutton-config/bin/bbb-conf
Gather logs of redis, html5-client and fix syslog.
@ffdixon Do we need to add FreeSwitch logs?
=> Store more logs with bbb-conf --zip

bigbluebutton-html5/imports/ui/components/shortcut-help/service.jsx
=> Fix keyboard shortcuts not working

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
=> Prevent no-mic warning displaying when recording is stopped

bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/note/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
Fixes #7947 and adds shared notes notification to the user-list toggle button
=> Fix shared notes notification

bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/styles.scss, bigbluebutton-html5/private/locales/en.json
Fixes #7843 and includes missing localization.
=> Fix guest icon

bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js, bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
=> Trying to fix external video sync problems

bigbluebutton-html5/imports/api/external-videos/server/methods/initializeExternalVideo.js
Looking to get more information about the events being sent through the external video streamer.
=> Adjust external video logs

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
This is how we fixed #5843 on our end.
Force-pushed over v2.2.x-release so can be used on both master or 2.2
=> Check for maxParticipants before registering an user

bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
=> Fix exception when publishing poll while presentation swapped (chrome)

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
=> Fixes render loop

bigbluebutton-html5/imports/ui/components/legacy/component.jsx, bigbluebutton-html5/private/config/settings.yml
Closes #8101.
[webrtc test](https://test.webrtc.org/)
=> Add Yandex browser to the list of supported browsers

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/container.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/sort-user-list/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/actions-bar/service.js
=> Show user who joined the breakout room in the invitation mode

bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx, bigbluebutton-html5/private/config/settings.yml
=> Fixes resizing bar appearing while there are no webcams shared

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json, bigbluebutton-html5/tests/puppeteer/chat/clear.js, bigbluebutton-html5/tests/puppeteer/chat/copy.js, bigbluebutton-html5/tests/puppeteer/chat/elements.js, bigbluebutton-html5/tests/puppeteer/chat/send.js, bigbluebutton-html5/tests/puppeteer/chat/util.js, bigbluebutton-html5/tests/puppeteer/core/elements.js, bigbluebutton-html5/tests/puppeteer/core/page.js, bigbluebutton-html5/tests/puppeteer/presentation/elements.js, bigbluebutton-html5/tests/puppeteer/presentation/upload.js, bigbluebutton-html5/tests/puppeteer/user/status.js
This PR updates the Puppeteer tests to make them work with the code on master branch.
=> Fixes for Puppeteer tests

bigbluebutton-html5/imports/ui/components/breakout-room/invitation/component.jsx
=> Show right breakout room in free join mode

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/private/config/settings.yml
Instead of having it as a property in settings.yml
Test by adding
```
joinViaHtml5=true
userdata-bbb_show_participants_on_login=false
```
in customParameters in API MATE
The userlist should be expanded on page load unless you're testing on mobile or you are passing this new property
=> Add bbb_show_participants_on_login as a join parameter

bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx
=> Add throttle to user typing call

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/container.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx
This PR prevents pasted text in the chat displaying as Poll results.
=> Prevent text pasted in chat displaying as poll result

bbb-webhooks/callback_emitter.js, bbb-webhooks/messageMapping.js
Some fixes made by @fcecagno that we had only on our end
=> Webhooks fixes

bigbluebutton-html5/imports/startup/client/intl.jsx
=> Fix panel resize when first loading in RTL

bigbluebutton-html5/imports/ui/components/media/component.jsx, bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
=> Fixes media rerender

bigbluebutton-html5/imports/ui/components/audio/service.js
=> Add debounce to mute/unmute button

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx, bigbluebutton-html5/tests/puppeteer/breakout.test.js, bigbluebutton-html5/tests/puppeteer/breakout/create.js, bigbluebutton-html5/tests/puppeteer/breakout/elements.js, bigbluebutton-html5/tests/puppeteer/breakout/join.js, bigbluebutton-html5/tests/puppeteer/breakout/util.js, bigbluebutton-html5/tests/puppeteer/core/page.js, bigbluebutton-html5/tests/puppeteer/user/multiusers.js
it creates breakoutrooms
adds data-tests to use during the Test
adds a fix to pass a parameter to init a user as Viewer or Moderator
and tests if Moderator2 joins breakoutrooms or not.. etc...
=> adds join Breakoutrooms Test Spec

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
=> Move kick user option to bottom of options list

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Turn off png generation as we don't use it.
=> Turn off png generation

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Initially introduced with `react-router` package (which was subsequently removed)
=> Remove unused package "history"

akka-bbb-apps/project/Dependencies.scala, akka-bbb-fsesl/project/Dependencies.scala, bbb-common-message/project/Dependencies.scala, bbb-common-web/project/Dependencies.scala, bigbluebutton-web/build.gradle, bigbluebutton-web/pres-checker/build.gradle
=> Updated java projects dependencies versions for 2.2

bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js
The main issue fixed in this PR is that there was an edge case where you could have cursor updates queued up and then a meeting could end before they were processed. The left over queued data would throw an exception when the server went to emit it and the data was never cleared from the queue. With this PR the cursors are removed from the queue before trying to emit them and the try/catch is around each individual meeting's messages so that the rest of the keys will still process.
The `process()` function also had a strange pseudo throttle to it and I switched it over to use a standard throttle.
=> Harden the cursor streamer emit logic

bigbluebutton-html5/imports/ui/components/app/styles.scss
=> Fix whiteboard toolbar overlapping userlist

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx
=> Fix RTL in chat using react-virtualized

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Needed for creating AWS image.
Need to modify packaging to copy the files in `/usr/share/bigbluebutton/blank/` instead of `/var/bigbluebutton/blank/`
=>  move location of presentation page blank files

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/styles.scss
=> Fix chat names with emoji's being clipped

bigbluebutton-html5/imports/ui/components/user-list/service.js
=> Sort private chat messages by last activity

bigbluebutton-html5/imports/ui/components/audio/echo-test/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/component.jsx, bigbluebutton-html5/tests/puppeteer/audio.test.js, bigbluebutton-html5/tests/puppeteer/audio/audio.js, bigbluebutton-html5/tests/puppeteer/audio/util.js, bigbluebutton-html5/tests/puppeteer/core/elements.js, bigbluebutton-html5/tests/puppeteer/core/page.js
this audio test requires to add to `.env` file the following 2 lines:
- `AUDIO_FILE=$HOME/bbb/src/bigbluebutton/bigbluebutton-html5/tests/puppeteer/media/audio.wav`
- `IS_AUDIO_TEST=true`
download link of the audio file: [audio.wav file](https://drive.google.com/file/d/1ydN25uvbX-Ij864QHaDD3liN_u8JB6QV/view?usp=sharing)
=> adds audio emulation and mute other user test considering isTalking indicator #12

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/ScreenshareModel.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserConnectedToGlobalAudioMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/VoiceUsers.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Webcams.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/ESLEventListener.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/GetAllUsersCommand.java, akka-bbb-fsesl/src/main/java/org/bigbluebutton/freeswitch/voice/freeswitch/actions/GetUsersStatusCommand.java, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala
Dump out some meeting stats so we can glean more info on what's happening in a meeting.
The log would be something like
```
{"envelope":{"name":"MeetingStatsDataSysMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1584210633793},"core":{"header":{"name":"MeetingStatsDataSysMsg"},"body":{"stats":{"meeting":{"meeting":{"name":"Demo Meeting","extId":"Demo Meeting","intId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1584210438329","isBreakout":false},"record":{"record":true,"autoStartRecording":false,"allowStartStopRecording":true,"keepEvents":false},"metadata":{"metadata":{}},"isRecording":false},"users":{"registered":1,"users":{"users":1,"moderators":1,"viewer":0}},"voice":{"users":1,"listenOnly":{"total":0,"kurento":0,"freeswitch":0},"twoWayCallers":1,"dialIn":0,"muted":0,"unmuted":1},"we …
```
=> Generate meeting data

.github/ISSUE_TEMPLATE/html5-issue.md
This would be useful for get a notion from wich version it comes happening and which changes can causes the possible bugs.
=> Add BBB version to html5 issue template

bigbluebutton-html5/imports/ui/components/user-avatar/styles.scss
=> Fix presenter indicator problem in Safari / Opera 

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/startup/server/index.js
Re-sending  #8755 so it's still included after the revert that was done
=> Fix render loop after changing locale with override setting

bigbluebutton-html5/imports/startup/client/base.jsx
=> Fix chat opening after saving application settings

bigbluebutton-html5/imports/ui/components/presentation/service.js
=> Fix presentation download by using the presentation id not its name

bigbluebutton-web/run-prod.sh
Make bbb-web bind to localhost
=>  Bind to localhost

record-and-playback/core/scripts/events/events.rb
This will add and extra `events.etherpad` file at `/var/bigbluebutton/events/[meetingId]` if the server is running `keepEvents` enabled.
=> Included Etherpad's data as events to be stored

bigbluebutton-html5/imports/ui/components/media/styles.scss, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/styles.scss
This PR is back porting  #8426 to 2.2
=> Fix exception in presentation when minimized and poll published

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
This patch switches to HTTPS for the links configured for and displayed
in the client.
=> Switch To HTTPS Links

bigbluebutton-html5/imports/ui/components/chat/service.js
Adds `lockSettingsProps.disablePrivateChat` to the fields filter.
=> Improving on chat lock settings

bigbluebutton-html5/imports/api/presentation-pods/server/methods/setPresenterInPodReqMsg.js, bigbluebutton-html5/imports/api/users-infos/server/methods/removeUserInformation.js, bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/user-info/component.jsx, bigbluebutton-html5/imports/ui/components/user-info/service.js
Enforce the use of extractCredentials in methods
=> Enforce extractCredentials

bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java
- add dashes to conference numbers so it is easier to read
=>  Format conference numbers

bigbluebutton-html5/imports/ui/components/media/component.jsx
This fixes the drawing issue introduced by the back ported #9289.
this should have been included as well.
closes #9335
=> Fix media overlay blocking whiteboard when drawing

bigbluebutton-html5/imports/api/captions/server/methods/appendText.js, bigbluebutton-html5/imports/ui/components/captions/service.js
This PR fixes the live captions not displaying when using the speech recognition option.
=> Fix live captions via dictation not displaying

bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/Util.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/DocumentConversionServiceImp.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/UploadedPresentation.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/PresentationController.groovy
- verify presentation and meeting id formats
- construct presentation file path making sure that they are valid
- add "downloadable" flag to check if presentation can be downloaded or not
- collect presentation upload errors so we can send to the client in the future
=>  Rework presentation download and upload

bbb-common-web/src/main/java/org/bigbluebutton/api/RecordingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/Util.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/DocumentConversionServiceImp.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java
- fix filename regex
- create download flag when uploading file with that can be downloaded
=>  Reweork file upload and download

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js
=> Use Meteor setTimeout to run within Fiber

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss, bigbluebutton-html5/private/locales/en.json
This PR adds a confirmation modal to the remove user action.
=> Adds remove user confirmation 

README.md
Hi all
I am new here. I am happy to go with another emoji if you prefer.
Cheers Stefan
=> Use unicode emoji to balance brackets

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/container.jsx
=> Close video preview modal when "share webcam" lock activated

bigbluebutton-html5/imports/ui/components/video-provider/service.js
=> Fix 'See other viewers in the Users list' lock enforcing lock on 'See other viewers webcams'

bigbluebutton-html5/client/main.jsx, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/startup/client/intl.jsx
Move Intl component outside of Base component
=> Move Intl component outside of Base component

bigbluebutton-html5/imports/ui/components/note/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/container.jsx, bigbluebutton-html5/private/locales/en.json
=> Change shared notes lock behavior 

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/styles.scss
=> Adds arrow to toggle user list icon

record-and-playback/presentation/playback/presentation/2.0/lib/writing.js
Pulling in #9489 into BigBlueButton 2.2.x
=> Fix presentation playback on iPad for iOS 13

bigbluebutton-html5/imports/ui/components/audio/container.jsx
=> Apply autoShareWebCam on return from breakout room

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
https://github.com/bigbluebutton/bigbluebutton/issues/7460 https://github.com/bigbluebutton/bigbluebutton/issues/9181 https://github.com/bigbluebutton/bigbluebutton/issues/9523 https://github.com/bigbluebutton/bigbluebutton/issues/9600
=> Avoid guest promotion

bigbluebutton-config/bin/bbb-conf
as suggested in https://github.com/bigbluebutton/bigbluebutton/issues/9069
=> removing /tmp/t_net after --network finished

bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Initially tried to do it via publish-subscribe extra conditions but relying on EnterAPI was more robust.
=> Only provide modOnlyMessage to moderators

bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/private/locales/en.json
=> Change prompt message when screen share not supported

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
=> Update shared note item style

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
Passing 'credentials' is obsolete. I did not spot issues in my tests. Looking for thorough tests of promoting/demoting/breakouts prior to merging this
=> Simplify the code used for promote-demote subscriptions

bigbluebutton-html5/imports/ui/components/modal/remove-user/component.jsx, bigbluebutton-html5/imports/ui/components/modal/remove-user/styles.scss, bigbluebutton-html5/private/locales/en.json
=> Update message / style for remove user confirmation

bigbluebutton-html5/imports/ui/services/settings/index.js
=> Prevent userChangedLocalSettings call failing at start

bigbluebutton-html5/imports/ui/components/shortcut-help/service.jsx
=> Fix non userData defined shortcuts not functioning

bigbluebutton-html5/imports/ui/components/chat/styles.scss
=> Fix chat dropdown not filling screen (mobile)

bigbluebutton-html5/imports/startup/server/settings.js
this would allow package maintaners to move config to /etc
see #9085
=> add env to specify settings location

bigbluebutton-html5/imports/ui/components/presentation/default-content/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/default-content/styles.scss
This PR fixes and issue Initially reported in #9410
=> Hide default content when hidePresentation and autoSwapLayout enabled

bigbluebutton-html5/imports/api/breakouts/server/publishers.js, bigbluebutton-html5/imports/api/meetings/server/publishers.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
Subscribe to `users`, `meetings` and `breakouts` collections when user role change.
closes #9733
=> Subscribe to collections when user role change

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Update react-player and fix twitch player.
=> Fix twitch external video sharing

bigbluebutton-config/bin/bbb-conf, bigbluebutton-config/cron.hourly/bbb-resync-freeswitch
* Add FreeSWITCH event socket layer (ESL) password to `bbb-resync-freeswitch`
* Don't print out new ESL password when changed
=> Bbb conf 29

bbb-webhooks/package-lock.json
Update minimist to latest version.  Closed #9834
=> Update minimist to latest version.

bbb-webhooks/package-lock.json
Update minimist to latest version (CVE-2020-7598)
=> Update minimist to latest version

bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/api/video-streams/server/modifiers/clearVideoStreams.js
Clear video streams collection on meeting end
closes #9154
=> Clear video streams collection

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
Prevents the starting of private chat with a `dial-in-user`
#9853
=> Disable chat option with dial in users

bigbluebutton-html5/imports/ui/components/button/component.jsx
Resolves React warning when using `customIcon` AND `circle` in `<Button />` component.
- closes #9875
Customizing BBB HTML5 client and found warning in console.
=> centralize base prop cleaning / deletion

bigbluebutton-html5/imports/ui/components/authenticated-handler/component.jsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/components/error-screen/styles.scss, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js
Remove button to log in back and change component layout for `ErrorScreen`
close #9798 
close #9799
=> Remove Log In back button in error screen

bigbluebutton-config/bin/bbb-conf
Makes a simple change that corrects a regex error.
Closes #9171
=> Fix regex issue in bbb-conf

bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/default-content/component.jsx
Handles the autoSwar and hidePresentation parameters in the userData
#9410
=> Handle userData autoSwap and hidePresentation params

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx, bigbluebutton-html5/private/config/settings.yml
This PR fixes a long agonized issue that is non-mirrored video.  In this PR, I introduce the following:
1. Ability for mirroring to be done for the current client's video
1. An option in settings.yml to control this, off by default to allow this to quickly be merged into a minor release
1. An option to turn on mirroring as part of the API call on join by passing in `userdata-bbb_mirror_own_webcam=true` to the GET request 
Note: This doesn't affect everyone else's video in your view, nor does it change everyone else's view of you.
Closes #8355 
There was lots of discussion regarding this and how many people were having to stray away from BBB because their clients were getting frustrated. I didn't know quite how to implement this but once @prlanzarin contributed, I got to work. The goal is …
=> Enable mirroring for video streams

bigbluebutton-html5/tests/puppeteer/notifications.test.js, bigbluebutton-html5/tests/puppeteer/notifications/notifications.js, bigbluebutton-html5/tests/puppeteer/notifications/util.js, bigbluebutton-html5/tests/puppeteer/user/multiusers.js
this PR fixes bugs in #8836 and #8775
=> bbb notifications automated test

bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
same of #9760, but for 2.2 version.
=> Improve audio reconnection for muted users for 2.2

bigbluebutton-html5/imports/api/voice-users/server/methods/muteToggle.js, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
Reverts bigbluebutton/bigbluebutton#9780
The action bar button was getting stuck in Muted state
=> Revert "Improve audio reconnection for muted users for 2.2"

bigbluebutton-html5/tests/puppeteer/core/page.js
this PR forces puppeteer to use english `'en-US'`
=> force english use in puppeteer

bigbluebutton-html5/tests/puppeteer/audio.test.js, bigbluebutton-html5/tests/puppeteer/core/page.js, bigbluebutton-html5/tests/puppeteer/webcam.test.js, bigbluebutton-html5/tests/puppeteer/webcam/check.js, bigbluebutton-html5/tests/puppeteer/webcam/elements.js, bigbluebutton-html5/tests/puppeteer/webcam/share.js, bigbluebutton-html5/tests/puppeteer/webcam/util.js
this PR updates the audio and webcam automated tests to make them stable
=> fixes webcam and audio automated tests

bigbluebutton-config/bin/bbb-conf
Ensure ELS password is always updated.
=> Ensure ESL password is updated

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/Office2PdfPageConverter.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java, bbb-libreoffice/assets/bbb-libreoffice.service, bbb-libreoffice/assets/libreoffice_container.sh, bbb-libreoffice/docker/Dockerfile, bbb-libreoffice/docker/bbb-libreoffice-entrypoint.sh, bbb-libreoffice/install.sh, bbb-libreoffice/uninstall.sh
This PR turns libreoffice into a systemd service that runs inside a docker container.
https://docs.bigbluebutton.org/2.2/dev.html#developing-bbb-web
```
cd bbb-libreoffice
sudo ./install.sh
```
To test, run:
``` 
telnet 127.0.0.1 8201 
```
```
cd bbb-libreoffice
sudo ./uninstall.sh
```
=> Detach libreoffice from bbb-web ( running as a docker container )

bigbluebutton-html5/private/config/settings.yml
Enable by default multiple webcams https://github.com/bigbluebutton/bigbluebutton/pull/8374
Enable by default network stats https://github.com/bigbluebutton/bigbluebutton/pull/8579
=> Enable multiple webcams and network stats by default

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx
=> Drop webcam when join a breakout room by clicking 'Join room'

bigbluebutton-html5/imports/api/users-settings/server/publishers.js, bigbluebutton-html5/imports/startup/client/base.jsx
Copy user parameters values from main room into breakout rooms.
closes #9612
=> Use main room user parameters in breakouts room

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/styles.scss
=> Auto select default.pdf after deleting the current presentation

bigbluebutton-html5/tests/puppeteer/breakout.test.js, bigbluebutton-html5/tests/puppeteer/breakout/create.js, bigbluebutton-html5/tests/puppeteer/breakout/elements.js, bigbluebutton-html5/tests/puppeteer/breakout/join.js, bigbluebutton-html5/tests/puppeteer/breakout/util.js
this PR fixes breakout automated test and makes it stable
=> Fix breakout autotest

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/clearGroupChatMsg.js
Clear private messages on meeting end
=> Clear private messages on meeting end

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/pencil/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu-item/component.jsx
Reverts bigbluebutton/bigbluebutton#9498
Needs some adjustment before re-merging - in some cases causes a loop on client load
=> Revert "Replace unsafe react lifecycle methods"

bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx, bigbluebutton-html5/tests/puppeteer/breakout.test.js, bigbluebutton-html5/tests/puppeteer/breakout/create.js, bigbluebutton-html5/tests/puppeteer/breakout/elements.js, bigbluebutton-html5/tests/puppeteer/breakout/join.js, bigbluebutton-html5/tests/puppeteer/chat.test.js, bigbluebutton-html5/tests/puppeteer/chat/save.js, bigbluebutton-html5/tests/puppeteer/chat/util.js, bigbluebutton-html5/tests/puppeteer/core/elements.js, bigbluebutton-html5/tests/puppeteer/core/page.js, bigbluebutton-html5/tests/puppeteer/notes/util.js, bigbluebutton-html5/tests/puppeteer/notifications.test.js, bigbluebutton-html5/tests/puppeteer/notifications/elements.js, bigbluebutton-html5/tests/puppeteer/notifications/notifications.js, bigbluebutton-html5/tests/puppeteer/notifications/util.js, bigbluebutton-html5/tests/puppeteer/package-lock.json, bigbluebutton-html5/tests/puppeteer/presentation.test.js, bigbluebutton-html5/tests/puppeteer/screenshare.test.js, bigbluebutton-html5/tests/puppeteer/screenshare/screenshare.js, bigbluebutton-html5/tests/puppeteer/screenshare/util.js, bigbluebutton-html5/tests/puppeteer/sharednotes.test.js, bigbluebutton-html5/tests/puppeteer/user.test.js, bigbluebutton-html5/tests/puppeteer/virtualizedlist/virtualize.js, bigbluebutton-html5/tests/puppeteer/whiteboard.test.js
**What does this PR do ?**
This PR adds audio, webcam and screenshare test specs to breakoutrooms automated test
also it fixes notifications, chat, screenshare, shared note, presentation, virtualized users list, multiusers and whiteboard automated tests after fails caused by changes in other parts of the bbb code
=> add specs to breakout autotest and fix old outdated autotests

bigbluebutton-config/bin/bbb-conf
We collect more nginx logs regarding bigbluebutton using bbb-conf --zip
=> Collect more bigbluebutton nginx access logs in bbb-conf --zip

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-preview/container.jsx, bigbluebutton-html5/imports/ui/components/video-preview/styles.scss, bigbluebutton-html5/private/locales/en.json
Just a QoL improvement we did on our end regarding the multiple webcams.
=> Multiple webcams stop all button

bbb-common-web/src/main/java/org/bigbluebutton/presentation/PresentationUrlDownloadService.java, bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java, bbb-libreoffice/assets/bbb-libreoffice.service, bbb-libreoffice/assets/libreoffice_container.sh, bbb-libreoffice/docker/Dockerfile, bbb-libreoffice/install.sh, bbb-libreoffice/uninstall.sh, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/doc-conversion.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy, bigbluebutton-web/run.sh
Fixes https://github.com/bigbluebutton/bigbluebutton/issues/10109 and:
- Add error handling for situation when bbb-web can't create the presentation directory ;
- Create temporary folders for soffice on start ;
- Make ports configurable ;
- Remove unused import ;
- Enforce the execution of bbb-web as `bigbluebutton` (even in development) ;
- Use systemd template config ;
- Ensure that libreoffice docker's user will have same uid as host's bigbluebutton user ;
- Lock container access to host (input);
- Lock container access to internet (forward);
Steps to test:
1 - Install soffice container:
```
cd bbb-libreoffice
sudo ./install.sh
```
2 - Compile bbb-common-message ;
3 - Compile bbb-common-web ;
4 - Run bigbluebutton-web from source;
=> Improvements on web and bbb-libreoffice

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/ui/components/settings/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/imports/ui/components/settings/submenus/styles.scss
=> Rework locales list generation

bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/message/component.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx
Also moved welcomeMessage sanitizing from client to server side
=> Sanitized modOnlyMessage prior to using it

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
At the end of `sip.nginx`:
```
auth_request /bigbluebutton/connection/checkAuthorization;
auth_request_set $auth_status $upstream_status;
```
=> Add a minimum socket validation to full-audio connection

bigbluebutton-html5/imports/ui/components/external-video-player/custom-players/panopto.jsx
Makes the panopto MATCH_URL regex more generic. 
This fixes a problem where some valid panopto links were not working.
=> Improve Panopto MATCH_URL regular expression

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js
Updates the file names for saved chat / users list. (includes meeting name)
before:
`public-chat-9898392829.txt`
`users-list-9898392829.txt`
after:
`bbb-Demo Meeting[public-chat]_2020-7-31_13-6.txt`
`bbb-Demo Meeting[users-list]_2020-7-31_13-6.txt`
closes #10170
=> Update filenames for saved public chat / users list

bigbluebutton-html5/imports/ui/components/presentation/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/styles.scss, bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/status-notifier/styles.scss, bigbluebutton-html5/imports/ui/components/toast/styles.scss, bigbluebutton-html5/imports/ui/stylesheets/variables/typography.scss, bigbluebutton-html5/private/locales/en.json
Adds presentation download link to the current presentation toast notification.
#10041
=> Notify users when presentation is available for download

bigbluebutton-html5/imports/startup/client/intl.jsx
reimplement the PR 9498 in splitted PRs
#8744
=> Remove unsafe lifecycle from intl component

bigbluebutton-html5/imports/api/annotations/addAnnotation.js
Prevents users from creating text area's on the whiteboard smaller than a single character.
#10204
=> Fix text area's being created smaller than a single character

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
Makes the drop down menus disappear when a menu item is selected.
#10281
=> Fix dropdown menus not closing on item select

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
Removes the user dropdown mute items, as well as the clear public chat option in breakout rooms.
Related to #10210
=> Remove mute and clear public chat options from breakouts

bigbluebutton-html5/imports/startup/client/intl.jsx
This PR adds a check to the default locale fallback
=> Fix intl loop

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
reimplement the PR 9498 in splitted PRs
#8744
=> Remove unsafe lifecycle from all dropdown related components

record-and-playback/presentation/playback/presentation/2.0/lib/popcorn.chattimeline.js, record-and-playback/presentation/playback/presentation/2.0/playback.js
Make sure `<br>`'s are added when required.
closes #10157
I had issues with playback.
My contributor agreement was just send to Fred, so this will probably have to be enabled before this can be merged.
=> Fix newlines in playback of chat

bigbluebutton-html5/imports/ui/services/audio-manager/index.js
We noticed that the mute action button wasn't being consistent when
using muteOnStart as meeting configuration.
Included the addition of the voice user object to the collection as
an event to also be observed.
Closes #9905 & #9582.
=> Include voice user's upsert to changes observer

bigbluebutton-config/bin/bbb-record
Backporting https://github.com/bigbluebutton/bigbluebutton/pull/10346 to v2.2.x-release
=> Also delete opus files in freeswitch cache dir

record-and-playback/core/scripts/rap-starter.rb
Fix an error in recording using 2.3a2
None in my knowledge.
Newly installed 2.3a2 fails in recording.
Nothing special.
=> A bug in rap-starter.rb

bigbluebutton-html5/imports/api/external-videos/server/methods/startWatchingExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/methods/stopWatchingExternalVideo.js
Prevent a case where viewers can start/stop an external video.
=> Prevent non presenters to start/stop an external video

bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js, bigbluebutton-html5/imports/ui/components/media/container.jsx
Remove extra white space from custom parameter.
=> Normalize custom parameters

bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/api/users/server/store/bannedUsers.js
Fix `bannedUsers` log and remove the meeting from the structure on meeting end.
=> Fix banned users log

bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
This PR adds data-test to webcams Items and considers talking user feature
=> add webcams layout talking user data test

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
This PR fix the user item rtl with Virtualized list
#10354
=> Add rtl to userItem

bigbluebutton-html5/tests/puppeteer/core/page.js, bigbluebutton-html5/tests/puppeteer/run.sh, bigbluebutton-html5/tests/puppeteer/webcam/elements.js, bigbluebutton-html5/tests/puppeteer/webcam/util.js, bigbluebutton-html5/tests/puppeteer/webcam/webcamlayout.js, bigbluebutton-html5/tests/puppeteer/webcamlayout.obj.js, bigbluebutton-html5/tests/puppeteer/webcamlayout.test.js
this PR adds webcams layout test suite
to run this specific test: `./tests/puppeteer/run.sh -t webcamlayout -h BBB_SERVER_NAME -s SECRET_KEY`
Expected output:
``` PASS  tests/puppeteer/webcamlayout.test.js (19.706s)
Webcams Layout
✓ Join Webcam and microphone (17891ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        20.728s
Ran all test suites matching /webcamlayout.test.js/i.
=> adds webcams layout test suite

bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/styles.scss, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/private/config/settings.yml
Use this wisely: breakoutRoomLimit parameter was introduced to controll max number of breakout rooms.
@mvasylenko & @ned64 changed target and refactored #10154 to this to be integrated with bigbluebutton 2.2.
=> Configurable max number of breakout rooms

bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/container.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx
reimplement the PR 9498 in splitted PRs
Closes #8744
=> Remove unsafe lifecycle from all media and presentation components

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/styles.scss
=> Fix misalign in presenter useritem

bigbluebutton-config/bin/apply-lib.sh
Modify updating the path so it will apply to installations that had installed 2.2.24.
=> Ensure the path is always updated

bigbluebutton-html5/imports/ui/components/user-list/service.js
Fix last name sort function to handle cases where both last name are `null`.
=> Fix last name sort function for save user names

bigbluebutton-html5/imports/ui/components/video-preview/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
the added data-test to video mirroring will be used in webcam video mirroring automated test spec, in custom parameters test suite.
=> adds missing webcam video mirroring data-test

akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/PermissionCheck.scala, akka-bbb-apps/src/universal/conf/application.conf
PermissionCheck verifies ejectOnViolation before eject an user
=> Option to prevent eject users by permission violation

record-and-playback/core/lib/recordandplayback.rb
The previous implementation of the BigBlueButton.execute method runs the
process with separate stdout and stderr streams. It first reads all of
the output from stdout, then reads all of the output from stderr.
This can cause a deadlock if the process writes a lot of data to stderr.
The IO buffer for stderr could fill, blocking progress. But since it
hasn't closed stdout, the ruby script is still waiting on a read to
stdout.
Switch to an execution method (using IO.popen) that allows combining
stdout and stderr into a single stream, eliminating the issue.
=> Fix io deadlock in recording scripts process execution utilities

bigbluebutton-html5/imports/api/users/server/methods.js, bigbluebutton-html5/imports/api/users/server/methods/checkSessionToken.js, bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js, bigbluebutton-html5/imports/ui/services/auth/index.js
Prevent user who logout from the meeting to rejoin using the same sessionToken
=> Add extra check for sessionToken

bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/services/auth/index.js
Prevent that multiple handlers are attached to socket close event for the same user.
Need more test with a high load server.
=> Prevent multiple on close handler attach

bigbluebutton-html5/tests/puppeteer/all.test.js
this PR adds Webcams Layout to the all in one autotests script.
=> adds webcams layout autotest to all.test.js

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
Latest SIP.js version sets this using peerConnectionConfiguration property instead of UserAgent option.
This solves #10569
More information [here](https://github.com/bigbluebutton/bigbluebutton/issues/10569 )
=> Set stun/turn server for audio's peer in html5 client

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
Adds aria tags to shared notes button
screen readers were not announcing this element
=> Fix aria labels on shared notes button

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/OfficeToPdfConversionService.java
Speedup the conversion of office documents by disabling the document update feature
=> Disable libreoffice document update ( speed up the conversion )

bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js, bigbluebutton-html5/imports/ui/components/polling/component.jsx
Uses the poll Id passed to `publishVote` instead of querying Polls collection for the current Id
should fix an Exception that was happening
```
syslog:Sep 21 16:13:42 m000425 systemd_start.sh[1812]: Exception while invoking method 'publishVote' { Error: Match error: Expected object, got undefined
syslog:Sep 21 16:13:42 m000425 systemd_start.sh[1812]:   message: 'Match error: Expected object, got undefined',
```
=> Fix exception while invoking method 'publishVote'

bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js, bigbluebutton-html5/imports/startup/client/logger.js, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/error-screen/component.jsx, bigbluebutton-html5/imports/ui/components/join-handler/component.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js, bigbluebutton-html5/private/locales/en.json
Change a couple of logs related to authentication process flow.
e.g
Invalid session token ejected (**403**):
```
I20201002-17:12:54.496(0)? warn: An invalid sessionToken tried to validateAuthToken meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1601657828480 authToken=bmzjaneq9xvq
I20201002-17:12:54.504(0)? error: {"logCode":"authenticatedhandlercomponent_setreason","logDescription":"Encountered error while trying to authenticate","connectionId":"MLRFjDZYqX2HN5yzc","extraInfo":{"reason":{"error":403,"description":"User has an invalid sessionToken due to ejection"},"clientURL":"https://sinforoso.bbbvm.imdt.com.br/html5client/join?sessionToken=e7kr6j8p8f1feibh","validUser":"notFound"},"userInfo":{"sessionToken":"e7kr6j8p8f1feibh","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-16016 …
```
=> Improve  log in/authentication logs

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx
=> Better handling audio reconnection

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/ui/components/cursor/service.js, bigbluebutton-html5/imports/ui/components/whiteboard/service.js, bigbluebutton-html5/imports/ui/services/auth/index.js
Improve annotations and cursor streamer logs, also add a type info for some logs in authentication process and rollback some attempts to fix multiple leaving end call.
=> Improve annotations and cursor streamer logs

bigbluebutton-config/bin/apply-lib.sh
Ensures the bbb-webrtc-sfu waits for all three KMS media servers to start.
Thanks to https://github.com/bigbluebutton/bigbluebutton/pull/10651 for suggesting it!
=> bbb-webrtc-sfu wait for multiple Kurentos

bigbluebutton-config/bin/bbb-conf, bigbluebutton-config/bin/bbb-record, bigbluebutton-config/cron.daily/bigbluebutton
On BBB 2.3 we no longer include red5, bigbluebutton-client, etc.
Related to #10593
=> Removed traces of red5 apps, flash client, etc from bigbluebutton-config/

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/ui/components/fullscreen-button/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/container.jsx, bigbluebutton-html5/private/config/settings.yml, bigbluebutton-web/grails-app/conf/spring/turn-stun-servers.xml
This solves #10712 and helps reducing the frequency mentioned in #10713 .
Also backporting a few commits to 2.3 to 2.2
=> Audio Improvements

bigbluebutton-config/bin/bbb-conf, bigbluebutton-web/grails-app/conf/spring/turn-stun-servers.xml
Don't check for libreoffice on bionic.  Since it's running in docker, it will not be found.
=> Bbb conf libreoffice

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/removeGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/methods/destroyGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/addGroupChat.js, bigbluebutton-html5/imports/api/group-chat/server/modifiers/removeGroupChat.js, bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js, bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js, bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js, bigbluebutton-html5/imports/api/users/server/publishers.js, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/ui/components/actions-bar/service.js, bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/cursor/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/services/auth/index.js, bigbluebutton-html5/imports/ui/services/network-information/index.js, bigbluebutton-html5/imports/ui/services/unread-messages/index.js
- Remove user from collection when he leave the meeting
- Remove property `connectionStatus` from user document
- Adjust components to handle this new behavior
Reduce collection size for meetings with a lot of participants.
=> Remove user from collection on exit

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
Changed the maximum attempts of the UserAgent reconnection (this should be changed when binding audio's websocket to meteor's connection state).
Added a log to monitor WS reconnect attempts.
=> Properly stops userAgent / peer when audio connection/reconnection fails

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala, bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js, bigbluebutton-html5/imports/ui/components/polling/service.js
Stops the ability for a user to submit multiple vote's per poll. 
#10705
=> Prevent users from sending multiple votes per poll

bigbluebutton-html5/imports/startup/server/redis.js
* Simplified the debug functionality for redis.js so it utilizes Logger.debug directly.
* Placed frequent debug messages behind a condition, so only if redis debug is enabled do we attempt to interpolate the strings to be logged (assumed some slight CPU use reduction, thanks @tdjac0bs for bringing this up!)
* Added meetingId in the log line informing about large queue of messages buffered up to be processed. With the previous format it suggested that there is one queue per nodejs process, while in reality it is one queue per meeting. This should help answer why meeting A is suffering from degraded performance while meeting B is doing well.
Note for monitoring tools: The previous format of the log
`error: prev queue size=101`
is now changed to
`warn: Redis: MeetingMessageQueue for …
=> Simplified redis debug and placed behind check

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Sanitize all parameters of api's, avoiding potential problems with some parsers ( \08, etc )
Fixes #10818
=> Sanitize parameters of API's. Fixes #10818

bigbluebutton-config/bin/bbb-record
Currently, `bbb-record` uses a bunch of different style for indentation,
sometimes tabs, sometimes to, three or four spaces and these are
sometimes mixed on a line by line basis, making it hard to read and to
get what's going on.
This is a simple patch making the style of `bbb-record` consistent by
using three spaces for indentation which seemed to be the most commonly
used type of indentation here.
=> Style of bbb-record

bigbluebutton-html5/imports/ui/components/nav-bar/talking-indicator/container.jsx
This is a part of #10848, as discussed in https://github.com/bigbluebutton/bigbluebutton/pull/10848#discussion_r525480434
=> Filter 'name' field in user's search

bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/package.json
I was not comparing correctly the instance id from the process and from the meta param (comparing string to int).
Also adjusted the port and url for running bbb-html5 in dev mode locally
Continuation from #10860
=> parse instanceId as int; develop on port 4000

bigbluebutton-html5/imports/startup/server/index.js
=> Port socket sockejs timeout to 2.3

bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/groupChatMsgBroadcast.js, bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js
=> Port Handle chat messages in sync way for 2.3

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/settings.yml
Add flag to enable/disabled custom heartbeat functions.
=> Add flag to enable/disabled custom heartbeat

bigbluebutton-config/bin/bbb-conf
Mask the output of the `which ufw` command.
=> Mask output of which command

bigbluebutton-html5/imports/ui/components/chat/message-list/component.jsx, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
This PR Fix the chat scroll to follow new messages.
=> Fix scroll doesn't scrolling to Bottom

bigbluebutton-config/bin/bbb-record
This patch fixes a typo in bbb-record causing problems by checking the
bigbluebtuuon user.
=> Fix Typo in bbb-record

bigbluebutton-html5/imports/api/captions/server/helpers.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/imports/startup/server/settings.js, bigbluebutton-html5/imports/ui/components/activity-check/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-test/container.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/audio-alert/component.jsx, bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-overlay/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/service.js, bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/pencil-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/shape-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js, bigbluebutton-html5/private/config/settings.yml
After the introduction of `instanceId` in the URL of the client, we had a few resources that were listed as not found in a session.
Continuation from #10868
Related to #10860
=> Include instanceId in resources url

bigbluebutton-html5/imports/api/annotations/server/modifiers/clearAnnotations.js, bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js, bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js, bigbluebutton-html5/imports/api/captions/server/methods/updateOwner.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/api/presentations/server/modifiers/setCurrentPresentation.js, bigbluebutton-html5/imports/api/screenshare/server/modifiers/addScreenshare.js, bigbluebutton-html5/imports/api/slides/server/modifiers/changeCurrentSlide.js, bigbluebutton-html5/imports/api/slides/server/modifiers/clearSlidesPresentation.js, bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/api/users/server/modifiers/removeUser.js, bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js
Prevent a case where voiceUser collection was being clean for entire server.
=> Prevent voiceUser clean for entire server

bigbluebutton-html5/imports/startup/server/index.js
There is some cases where node was crashing without logging, this PR add a listener to `uncaught` exceptions, also add a try/catch for custom heartbeat function.
=> Add uncaught error log and fix custom heartbeat problem

bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/private/config/settings.yml
Generate data about messages received and handled by redis.
=> Generate data from redis messages

bigbluebutton-html5/imports/startup/server/index.js
Propagating #10953 to 'develop' before pulling 2.2 into 2.3
=> Cherry-pick PR #10953

bigbluebutton-config/bin/apply-lib.sh
=> fix typo in apply-lib.sh

bigbluebutton-config/bin/bbb-conf
=> Fix dangling fi

bigbluebutton-html5/imports/api/annotations/server/handlers/whiteboardSend.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/imports/startup/server/metrics.js, bigbluebutton-html5/private/config/settings.yml
Add an option to generate periodically heap snapshots,  also add an option to remove a meeting from metrics file when the meeting has ended.
=> Add option to generate heap file and tweak metrics

bigbluebutton-config/bin/bbb-conf
Fix for https://github.com/bigbluebutton/bigbluebutton/issues/11036
Signed off by marvin.wegener@outlook.de
=> Update URL to HTTPS

bigbluebutton-html5/private/config/settings.yml
settings.yml "media" configs incorrectly placed under "stats" during #11033
=> settings.yml media configs incorrectly placed under "stats"

bigbluebutton-config/bin/bbb-conf
Most of the changes date back to #10700 
We were trying to trace down a problematic change likely when merging 2.2.31 into 2.3 ( #11033 )
If anyone spots issues with bbb-conf on their 2.3 server, please comment
=> Recover 2.3-alpha3 version of bbb-conf

bigbluebutton-config/bin/bbb-conf
Start/stop tomcat8 with `bbb-conf --stop` and `bbb-conf --start`.
=> Restart tomcat8

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx
Suppress warning of React player.
To suppress warnings when playing an external media file.
The original code seems harmless.
=> Suppress warning of React file player

.gitmodules
Reverts bigbluebutton/bigbluebutton#11094
Need to temporarily revert this as it's causing issues with our internal build system.
=> Revert "add submodules: bbb-webrtc-sfu, etherpad-lite, freeswitch"

bigbluebutton-html5/imports/ui/components/user-list/service.js
In a rare case that I have limited view on this issue was hit on login on build 1315 (today). This was the only unchecked spot I found
=> Ensure sorting has a fallback in case of undefined name

bigbluebutton-html5/imports/api/captions/server/helpers.js
Fixes the URL used on Closed Captions by reading port variable from environment.
Closes #11116
=> Fixes closed captions language list

bigbluebutton-html5/imports/ui/components/actions-bar/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js
Fixes crash on user's client when a presenter is kicked, by setting the moderator as the new presenter.
Closes #11181
=> Fixes crash when presenter is kicked

bigbluebutton-html5/imports/api/annotations/server/handlers/whiteboardSend.js, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/cursor-listener/component.jsx, bigbluebutton-html5/private/config/settings.yml
Add configurable process interval for cursor and annotations queue.
#11169
=> Configurable annotation and cursor interval

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/startTyping.js, bigbluebutton-html5/imports/ui/components/chat/message-form/container.jsx
Add a throttle to `startUserTyping` function in order to reduce the number of messages sent to akka-apps.
=> Throttle user typing indicator function

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
Using now 'application' instead of old 'audio' path
=> Fix wrong path in settings for audio constraints

bigbluebutton-html5/imports/api/users/server/publishers.js
Before this pull request we had cases (caused by race-condition) where the joining of a new user would propagate that user's dummyUser template to the remaining clients in the meeting. That caused troubles since the dummy user does not have intId, name, etc. You would see console error for .toLowerCase() of undefined (user.name being undefined)
In this PR we filter the user collection subset we make available to the clients so only non-dummy users (i.e. ones with intId populated) are published
=> Only publish full users to client side, no dummy users

bigbluebutton-html5/imports/startup/server/index.js, bigbluebutton-html5/private/config/settings.yml
Add a possibility to configure heapdump threshold value.
=> Add heapdump threshold in settings

bigbluebutton-html5/imports/ui/components/video-provider/service.js
https://github.com/bigbluebutton/bigbluebutton/pull/11142 exposed a bug where cameras that were being shared and timed out (so not effectively shared to the server) would get stuck in the UI and in video-provider's local webcam state.
This PR fixes it by:
- Properly clean up video-provider service's isConnecting/deviceId when a camera negotiation times out
- Remove a unused attribute of the service's constructor
- Add some more inline comments explain what the stopVideo method should do
None
This bug is currently only present in 2.2 development branch.
Related to https://github.com/bigbluebutton/bigbluebutton/pull/11142
=> video-provider: fix inconsistent client state when a webcam being shared times out

bigbluebutton-html5/imports/api/users/server/handlers/validateAuthToken.js, bigbluebutton-html5/imports/api/users/server/methods/validateAuthToken.js, bigbluebutton-html5/imports/startup/server/ClientConnections.js, bigbluebutton-html5/private/config/settings.yml
Synchronize active users with open connections from server, preventing users that got stuck on meetings.
=> Synchronize users with active connections

bigbluebutton-html5/imports/ui/components/video-provider/video-button/component.jsx
Fixes webcam icon active state
=> Fixes active webcam icon

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
Cherry-picking "fix typing indicator display" from PR #11173
=> Fixes typing indicator display

bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/api/users/server/methods/userLeftMeeting.js
Change client connections structure to have saved only active connection id  for the user.
=> Remove old connection id on user leave

bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/poll/service.js
Adds a default poll avatar color.
Closes #11291
=> Fix icon in chat poll result not displaying

bigbluebutton-html5/imports/ui/components/audio/audio-controls/component.jsx, bigbluebutton-html5/imports/ui/components/muted-alert/component.jsx
Clones the unmuted  `inputStream` in the `MutedAlert` for usage with the `hark` package.
Closes #10733
Closes #10725
=> Clone unmuted input stream for usage with hark

bigbluebutton-html5/imports/api/users/server/methods/setMobileUser.js, bigbluebutton-html5/imports/api/users/server/modifiers/setMobile.js
Added the missing extractCredential method and replaced the old callback strategy
with the new try-catch block.
Closes #11321
=> Fix mobile user-list identification

bigbluebutton-html5/imports/api/meetings/server/modifiers/clearMeetingTimeRemaining.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js
Clear `meeting-time-remaining` collection on meeting end.
=> Clear meeting-time-remaining collection

bigbluebutton-html5/imports/api/guest-users/server/modifiers/clearGuestUsers.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/clearMeetingTimeRemaining.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/meetingHasEnded.js, bigbluebutton-html5/imports/api/screenshare/server/modifiers/clearScreenshare.js, bigbluebutton-html5/imports/api/voice-call-states/server/modifiers/clearVoiceCallStates.js, bigbluebutton-html5/imports/api/whiteboard-multi-user/server/modifiers/clearWhiteboardMultiUser.js
Changes made in #11355 and #11356 targeting develop branch.
=> [2.3] Clear missing collections on meeting end

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/pencil/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-menu-item/component.jsx, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/toolbar-submenu-item/component.jsx
Includes PR #10217 and resolves conflicts
=> Remove unsafe lifecycle from all whiteboard related components

bigbluebutton-html5/imports/ui/components/audio/service.js
=> Fix lost output audio when change client language

bigbluebutton-config/bin/bbb-conf
=> Added STUN check

bigbluebutton-html5/imports/ui/services/settings/index.js
This PR implements a changed state for settings, fixingthe isse where the meeting settings change but isn't implemented for all users.
Closes #8545
=> Store the changed and default settings in different variables

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx
Changes data-test on chat messages to display the correct values.
closes #11396
=> Fix 'data-test' values for chat messages

bigbluebutton-html5/imports/ui/components/audio/service.js
Remove duplicate import of throttle
Accidentally left behind in the merge PR #11428
=> Remove duplicate import of throttle

bigbluebutton-html5/private/locales/en.json
Fixes a typo in EN locale.
contribution to open source community.
=> Typo "qestion"

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/private/config/settings.yml
Fixes `userdata-bbb_show_public_chat_on_login` and `userdata-bbb_show_participants_on_login` checking on login so the parameters are correctly set.
Adds `public.app.layout.showParticipantsOnLogin` (default: `true`) parameter to settings file
closes #11391
closes #11392
=> Fix layout params (show participants + show public chat) not affecting the meeting

bigbluebutton-html5/imports/startup/server/settings.js
Implemented merge option for default and local settings in bbb-html5 file.
The motivation is to provide a mechanism to override the system configuration and allows developers to make changes without breaking operator configurations.
=> Implemented merge option for default and local settings.

bigbluebutton-html5/tests/puppeteer/customparameters/customparameters.js
Changes skip check test to match new behavior of skip test parameter (PR #11453)
=> Fix skip check test

bigbluebutton-html5/imports/ui/components/shortcut-help/component.jsx, bigbluebutton-html5/private/locales/en.json
Add a shortcut help of toggle full-screen by Enter key.
Related to the PR #10590 , which has been accepted.
User's convenience.
=> Shortcut help for toggle fullscreen 

bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/chat-list-item/component.jsx
At nav-bar has a red dot indicating that has unread messages, it was broken.
=> Fix nav-bar unread message indicator

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Improves PR #11480 solution with @Tainan404 suggestion (adding all system messages to an array to prevent unnecessary re-renders).
=> Fix unnecessary re-renders caused by #11480 changes

bigbluebutton-html5/imports/startup/server/redis.js
Add extra logs on redis for a better understanding of messages handling and queues creation.
=> Add extra logs when handling messages on redis

bigbluebutton-html5/imports/ui/components/dropdown/component.jsx
Fixes userlist menu bug happening on tablets, partially fixed by PR #11500
closes #11473
=> Fix for userlist menu on tablets

bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/audio/service.js, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/container.jsx, bigbluebutton-html5/imports/ui/services/audio-manager/index.js
=> Recover mute state for moderator when returning from breakout's audio transfer

bigbluebutton-html5/private/locales/en.json
Fix a typo in translations.
@antobinary I've also made a few corrections on Transifex for the french translations. It seems you were the one pulling them in the past. Should I notify you when updating translations?
=> Remove extra period

bigbluebutton-html5/imports/ui/components/breakout-room/breakout-remaining-time/container.jsx
Fixes breakout timer bug when timers get out of sync.
closes #11358
=> Fix breakout room timer sync

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx
Changes prop name to correctly display chat messages timestamp.
closes #11461
=> Fix chat messages timestamp

bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx
This is a backport of #11477 (by @KDSBrowne ) to 2.2.x, langing in 2.2.34
See the original pull request ^^ for full details
=> Update handleClick condition (fix text-area for FireFox)

record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb
Add a few helpful notes for anyone who wants to use this callback script about what extra ruby gems and bbb server configuration are needed.
=> Add some extra docs/setup instructions to the analytics callback script

bigbluebutton-html5/private/config/settings.yml
Inadvertently introduced by #11514
=> Revert custom changes to settings.yml

bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/styles.scss
This adds the avatar back to the chat messages for poll results
closes #11291
=> Add avatar back to chat poll result message

bigbluebutton-html5/imports/startup/client/base.jsx
When validating tokens, the dummyUser created at the beginning is set
with validated=true. This means there won't be the state change that used
to occur from validated:false to validated:true (which detects the moment
joined the meeting) , therefore the alert code that expects for this change
won't run.
To fix this for audio alerts, we now detect when user join by observing
additions in Users's collection. This is actually good because we start
observing this only once (in componentDidMount), differently we used to do,
by calling this every time the tracker was activated.
To distinguish between the user addition that initially populates user's
collection from those that happens after user join (which are the ones we
want), we store the initial state (at componentDidMount) and compare it …
=> Fix audio and push alerts for user join

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Reverts bigbluebutton/bigbluebutton#11553
Something's off
=> Revert "Fix clear chat for single message"

bigbluebutton-html5/imports/startup/client/base.jsx
Complements #11533
Thanks to @antobinary  who suggested these improvements
=> Improve performance when doing user join notifications

akka-bbb-apps/src/main/scala/org/bigbluebutton/ApiService.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/BigBlueButtonActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/senders/MsgBuilder.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/service/HealthzService.scala, bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/RedisStorageService.java, bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/SystemMsgs.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/messaging/messages/KeepAliveReply.java, bbb-common-web/src/main/java/org/bigbluebutton/api/pub/IPublisherService.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/java/org/bigbluebutton/web/services/KeepAlivePong.java, bbb-common-web/src/main/java/org/bigbluebutton/web/services/KeepAliveService.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/MsgBuilder.scala, bbb-common-web/src/main/scala/org/bigbluebutton/api2/meeting/OldMeetingMsgHdlrActor.scala
This PR completes the healthz endpoint for internal debugging of the application
Health check endpoint
To test the endpoint send a GET request to localhost:8901/healthz endpoint
=> Bbb core http endpoint wip

bigbluebutton-html5/imports/startup/client/base.jsx
Also removed unnecessary fields
Related to #11568
=> Move some validations to the User's collection query

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx
Fixes incorrectly displaying of "restore presentation" button if settings `public.layout.hidePresentation` and `public.layout.autoSwapLayout` are set to true
closes #11145
=> Fixes incorrectly displaying of 'restore presentation' button when presentation is disabled

bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js, bigbluebutton-html5/imports/api/meetings/server/methods/endMeeting.js, bigbluebutton-html5/imports/ui/components/meeting-ended/component.jsx, bigbluebutton-html5/private/locales/en.json
Adds the name of the user who ended the meeting to the `MeetingEnded` modal message
closes #9856
=> When a moderator ends a meeting, indicate to viewers who ended the meeting

bigbluebutton-html5/imports/startup/server/index.js
Re-enables legacy client after changes made in PR #11486
=> Fix legacy client with customHeartbeat:false

bigbluebutton-html5/imports/api/users/server/methods/userLeaving.js, bigbluebutton-html5/imports/api/users/server/methods/userLeftMeeting.js
Include `loggedOut` property in `UserLeaveReqMsg` message payload.
#11220
=> Alter UserLeaveReqMsg message payload

bigbluebutton-html5/imports/ui/components/captions/service.js, bigbluebutton-html5/private/config/settings.yml
Changes locales list url to match PR #11234 new url
Changes caption locales list order
=> Fix locales url settings + captions locales order

bigbluebutton-html5/public/locales/en.json
User Repsonse -> User Response
=> Fix poll response text typo

bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx
Adds captions and guest list data to `layout-manager` component.
=> Fix captions and guest list openPanel error

bigbluebutton-config/bin/apply-lib.sh
Updated detection of HOST and PROTOCOL to use `/etc/bigbluebutton/bbb-web.properties` in `apply-lib.sh`
=> Added detectio for /etc/bigbluebutton/bbb-web.properties

bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/service.js
This PR adds an optional-chaining operator for all the posJoinMessage uses.
closes #11528
=> Fix for posJoinMessage as undefined

bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx
Adds HTML escaping to typed poll responses before displaying results in chat.
Feedback from @jfsiebel after checking PR #11620 changes
=> Escaping user typed poll results

bigbluebutton-html5/imports/startup/client/base.jsx
Fixes the appearing of public chat panel after every webcam share/unshare action, by checking if `openPanel` session value is already set when `base.jsx` gets rendered/re-rendered.
closes #11625
closes #11665
=> Fixes chat panel appearing after webcam share/unshare

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/private/config/settings.yml
Rework on locales fetch to make sure all components get updated with new messages when language is changed.
closes #11714
=> Locales fetch rework

record-and-playback/core/scripts/bigbluebutton.yml
Use 127.0.0.1 insted of localhost since Etherpad only listens for ipv4.
=> Avoid localhost at notes endpoint

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx
Fixes an issue where the RTL/LTR parameter was not being reflected by userlist element after changing languages.
The issue was spotted by @daminebenq while testing PR #11719
=> Fix userlist RTL/LTR for userlist when language is changed

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/component.jsx
Fixes an element Id that is not unique.
=> Fix duplicate element Id in UserParticipants

bigbluebutton-html5/imports/api/annotations/server/methods/sendBulkAnnotations.js, bigbluebutton-html5/imports/ui/components/whiteboard/service.js
Adds try/catch and retry whiteboard annotations sending if the user loses connection 
closes #11430
=> Retry sending annotations if user information is not available

bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx
This PR fixes the crash when change to public chat and the bug of change between chats and the list of messages doesn't change
Closes #11528
https://user-images.githubusercontent.com/15806883/112489021-d1206180-8d5c-11eb-8e2a-ff60b47d6c6d.mp4
=> Fix Cannot read property 'posJoinMessages' of undefined

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
https://github.com/meteor/node-stubs/issues/26
=> Updated meteor-node-stubs from 1.0.1 to 1.0.3

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java
This PR reduces the impact of #8618 by increasing hardcoded timeout from 7s to 60s
A subsequent PR is going to be sent by @gustavotrott to:
-> Make this timeout configurable;
-> Add a log telling that timeout happened
=> Quick fix to avoid empty slides

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
Removes black border that could appear when webcam video is being resized
=> Remove black border on video resize

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss
Reverts bigbluebutton/bigbluebutton#11755
See #11755 for more info
=> Revert "Remove black border on video resize"

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx, bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/media/container.jsx, bigbluebutton-html5/imports/ui/components/video-provider/service.js, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Keeps track of shared video devices when user joins a breakout room, to share it again when the user leaves breakout room.
=> Auto-reconnect webcam after leaving breakout room

bigbluebutton-config/bin/bbb-conf
Improve logic for detecting distro in bbb-conf
=> Improve logic for detecting distro in bbb-conf

bigbluebutton-config/bin/bbb-conf
Resolves: https://github.com/bigbluebutton/bigbluebutton/issues/11035
=> Fix URL in bbb-conf warning

bigbluebutton-html5/public/locales/en.json
Removed duplicate key:value pair for en.json Continuation from #11758 
Transifex spotted it first and complained...
Can't have duplicated keys, this was an accident
=> Removed duplicate key:value pair for en.json

bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/presentation/presentation-close-button/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/container.jsx
This fixes invalid aria values and removes the default role attributes included with the virtualized list package.
Fixes these critical accessibility issues
=> Remove invalid aria values and roles without proper structure

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/ValidateAuthTokenReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala
This PR  modifies Banned user rejoining error code and error message
This PR was created to add more meaningful error code and messages by the akka-apps for the UI.
=> fix:Banned user rejoining error code modified with error message

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Updates meteor-node-stubs to 1.0.3
Updates y18n to 4.0.1
Closes #
Older versions raised security vulnerability flags
=> Updated meteor-node-stubs and y18n

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/private/config/settings.yml
Backports #11631 and #11728 to BigBlueButton 2.2.x (to be included in 2.2.36)
Detailed motivation in #11631 and #11728
=> Backport sdpSemantics unified-plan

bigbluebutton-html5/imports/api/captions/server/helpers.js, bigbluebutton-html5/imports/api/captions/server/methods/appendText.js, bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js, bigbluebutton-html5/imports/api/captions/server/methods/fetchReadOnlyPadId.js, bigbluebutton-html5/imports/api/common/server/etherpad.js, bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/api/note/server/helpers.js, bigbluebutton-html5/imports/api/note/server/methods/createNote.js, bigbluebutton-html5/imports/ui/components/captions/service.js
Isolate most Pad related functions and secure shared notes and closed
captions creation to only when there is a reachable Etherpad server
configured.
Closes https://github.com/bigbluebutton/bigbluebutton/issues/7910
=> Refactor Etherpad API calls

bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/styles.scss
This PR changes the colors of the selected `User Response` button to make it different from `Start Poll`.
=> Different colors for the selected User Response poll button

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
Substitutes hard coded heading string for localized one in presentation uploader
Closes #11829
=> Fix localization of heading in presentation uploader

bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx
Fix broken actions bar in mobile devices
=> Fix actions bar height for mobile

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Makes video dropdown fullscreen in mobile devices
Closes #7597
=> Fix mobile video dropdown

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js, bigbluebutton-html5/imports/api/captions/server/helpers.js, bigbluebutton-html5/imports/api/captions/server/methods/appendText.js, bigbluebutton-html5/imports/api/captions/server/methods/createCaptions.js, bigbluebutton-html5/imports/api/captions/server/methods/fetchReadOnlyPadId.js, bigbluebutton-html5/imports/api/common/server/etherpad.js, bigbluebutton-html5/imports/api/common/server/helpers.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/api/note/server/helpers.js, bigbluebutton-html5/imports/api/note/server/methods/createNote.js, bigbluebutton-html5/imports/ui/components/captions/service.js
In case of issues, here's a list of files where manual conflict resolution was required.
Tested locally, all seemed fine.
```
```
=> Merged 2.2.36 into 2.3-beta

bigbluebutton-html5/imports/ui/components/debug-window/component.jsx
Change a Portuguese to English in the debug window.
I guess this is a temporary item during the beta test. I post this PR as a quick fix until it is removed after the beta testing.
=> Portuguese in debug window

.github/ISSUE_TEMPLATE/core-issue.md, .github/ISSUE_TEMPLATE/installation-issue.md
Created this two new labels to match the other templates.
=> Add labels to core and installation issues

bigbluebutton-config/bin/bbb-conf
Pickup the correct shared secret when changing bbb-apps-akka.conf
=> Pickup the correct shared secret when changing bbb-apps-akka.conf

bigbluebutton-html5/private/config/settings.yml
Changes default value of `showAllAvailableLocales` to **true** in settings file
Closes #11863
=> Changes showAllAvailableLocales settings default value

bigbluebutton-html5/imports/api/users-persistent-data/server/publishers.js, bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/styles.scss, bigbluebutton-html5/imports/ui/components/connection-status/service.js, bigbluebutton-html5/public/locales/en.json
Re-includes offline users to the connection modal list
Adds `meetingId` to `UsersPersistentData`
Closes #11789
=> Re-include offline users to the connection modal's users list

bigbluebutton-html5/imports/ui/components/connection-status/service.js
Covers https://github.com/bigbluebutton/bigbluebutton/pull/11847#issuecomment-812120523 and push offline users to the bottom of the list.
=> Offline users' connection status improvements

bigbluebutton-html5/imports/ui/components/nav-bar/component.jsx
Fix the unread indicator in nav bar
Closes #11795
=> Fix unread notes being not shown in navbar

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss
=> fix: audio device selector problem when using RTL locales

bigbluebutton-html5/imports/api/users-persistent-data/server/modifiers/addUserPersistentData.js
=> fix: dial-in users don't appear in participant's list

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
Fix true/false and yes/no quick poll localization for results displayed in chat.
Closes #11858
=> Localized quick poll answers

bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/container.jsx
Enables Triggering layout rearrangement by quick poll button.
Closes #11924 
After posting the PR #11900, I realised that there is one more. There should be nothing more, I suppose...
=> Trigger layout rearrangement by quick poll button

bigbluebutton-html5/imports/ui/components/audio/permissions-overlay/styles.scss, bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-toolbar/component.jsx, bigbluebutton-html5/imports/ui/stylesheets/mixins/_scrollable.scss
Removes code that is specific to old versions of MS Edge.
Obsolete code found while working on PR #11920
=> Remove old Edge specific code

bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/styles.scss
Makes the presenter menu scrollable if size increases (by uploading a lot of presentations) over 50% of viewport height.
Closes #11916
=> Makes presenter menu scrollable

bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx, bigbluebutton-html5/imports/ui/components/chat/component.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/container.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/alert/container.jsx
This PR use the users context to fix many components that are crashing the client when user is missing in the collection as the user information is persisted on client using the context that merge the collections `Users` and `users-persistent-data`.
Closes #11699
=> Fix client crashing because users object is missing

bigbluebutton-html5/imports/startup/server/redis.js
Remove bbb-html5-backend log when meeting handled by other backend
The logging is excessive. This line was introduced when we were first implementing spreading meetings' handling across different bbb-html5 instances. I have not seen use of it ever since https://github.com/bigbluebutton/bigbluebutton/pull/11650 which resolved the only problem I was aware of
=> Remove bbb-html5-backend log when meeting handled by other backend

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx, bigbluebutton-html5/imports/ui/components/connection-status/modal/component.jsx, bigbluebutton-html5/imports/ui/components/status-notifier/component.jsx, bigbluebutton-html5/tests/puppeteer/user.obj.js, bigbluebutton-html5/tests/puppeteer/user/elements.js, bigbluebutton-html5/tests/puppeteer/user/multiusers.js, bigbluebutton-html5/tests/puppeteer/whiteboard/elements.js
This PR adds the following:
- Raise hand test spec
- User Offline Connection Status test spec
=> Add missing Connection Status and Hand raising specs

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js
- Fixes an error that happened on save or copy messages after clearing chat.
- Translates `PUBLIC_CHAT_CLEAR` message on save/copy chat.
- Removes extra whitespace from username on save/copy chat.
```
[09:09]  Welcome to test-meeting!This server is running BigBlueButton.
[09:09]  PUBLIC_CHAT_CLEAR
[09:09] User 1053508 : test
```
```
[09:09] Welcome to test-meeting!This server is running BigBlueButton.
[09:09] The public chat history was cleared by a moderator
[09:09] User 1053508: test
```
Closes #11894
=> Fix save and copy messages

bigbluebutton-html5/imports/ui/components/chat/alert/component.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/container.jsx, bigbluebutton-html5/imports/ui/services/unread-messages/index.js
Makes use of `chatContext` for chat audio and popup alerts
Closes #11949
=> Fix chat alerts

bigbluebutton-html5/imports/ui/components/app/styles.scss
Adds scroll to polling panel on mobile
Closes #11973
=> Scroll on polling panel - mobile

bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx, bigbluebutton-html5/imports/ui/components/components-data/chat-context/context.jsx, bigbluebutton-html5/imports/ui/components/subscriptions/component.jsx
I added an action to clear the messages that come from subscription and changed the way to remove the messages when the chat is cleared (Because the re-sub also impacts this feature).
Closes #11842
=> Fix duplicated messages

bigbluebutton-html5/imports/ui/components/audio/audio-controls/input-stream-live-selector/component.jsx
Makes the audio selection menu scrollable if size increases (by having a lot of available devices) over 50% of viewport height.
Closes #11987
=> Make audio selection menu scrollable

bigbluebutton-html5/imports/ui/components/audio/audio-dial/styles.scss
Forces display of phone and pin numbers `ltr` even in `rtl` languages
Closes #8985
=> Fix phone number display in RTL

bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx, bigbluebutton-html5/imports/ui/components/modal/random-user/styles.scss
This PR makes sure that there's no bisque background on the random user picking modal.
=> Remove the background colour that highlights random user picking modal

bigbluebutton-html5/imports/api/cursor/server/handlers/cursorUpdate.js, bigbluebutton-html5/imports/api/cursor/server/streamer.js, bigbluebutton-html5/imports/ui/components/cursor/service.js
Makes cursor update get userId from `extractCredentials`
=> Publish cursor using reliable userId

bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx, bigbluebutton-html5/imports/ui/components/audio/audio-controls/container.jsx, bigbluebutton-html5/imports/ui/components/chat/alert/container.jsx, bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/container.jsx, bigbluebutton-html5/imports/ui/components/chat/container.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx, bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx, bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx, bigbluebutton-html5/imports/ui/components/lock-viewers/context/container.jsx, bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx, bigbluebutton-html5/imports/ui/components/presentation/container.jsx, bigbluebutton-html5/imports/ui/components/status-notifier/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-messages/container.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/alert/container.jsx
Adds another level to the usersContext data (meetingId), separating user data from main room and breakout rooms.
Closes #11977
=> Add meetingId to usersContext

bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/container.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/component.jsx, bigbluebutton-html5/imports/ui/components/poll/live-result/service.js
Gets usernames from context to prevent poll crash if user leaves after voting.
Closes #12075
=> Get users data from context in poll live-result

bigbluebutton-html5/imports/ui/components/modal/random-user/container.jsx
Gets user data from context to prevent a crash if user leaves while the moderator is using random user selection feature.
Similar to #12075, reported in [this comment](https://github.com/bigbluebutton/bigbluebutton/issues/12075#issuecomment-822532441)
=> Get users data from context in random user select

bigbluebutton-html5/imports/ui/components/presentation/download-presentation-button/component.jsx
increase download button size
fixes #7684
This is a job in my league. :)
=> increase download button size

bigbluebutton-html5/imports/ui/components/layout/context.jsx, bigbluebutton-html5/private/config/settings.yml
Removes unused settings key. [additional context](https://github.com/bigbluebutton/bigbluebutton/issues/9532#issuecomment-825047015)
=> Remove webcamsDefaultPlacement unused settings

bigbluebutton-html5/imports/api/audio/client/bridge/sip.js
When joining breakout audio, the output device selected in the main room is
used in breakout.
When returning from breakout rooms, the output audio device previously set in
the main room is restored.
Some specific info:
SIPSession doesn't handle Storage anymore, we do this in SIPBridge, since
it has more info about the current selected device and it doesn't depend of
a session being oppened.
We also now pass the  output device ID when joining audio sessions. We can
then keep this information in the Storage.
Closes #11663
=> fix: breakout audio don't use previously selected output device

bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/RedisStorageService.java, bigbluebutton-web/run-dev.sh
- add a new script that you can run in dev env without needing to be run as bigbluebutton
- remove unneeded import
=> Bbb web run dev

akka-bbb-apps/src/main/scala/org/bigbluebutton/Boot.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/SystemConfiguration.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/groupchats/SendGroupChatMessageMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, akka-bbb-apps/src/universal/conf/application.conf
Add flag to disable logging of chat messages.
Some organizations doesn't want to log chat messages for privacy reasons. Allow system admins to turn off logging of the chat messages.
=> Do not log chat msgs

bigbluebutton-html5/imports/api/connection-status/server/methods/addConnectionStatus.js, bigbluebutton-html5/imports/ui/components/connection-status/service.js, bigbluebutton-html5/imports/utils/stats.js, bigbluebutton-html5/private/config/settings.yml
Includes a log at Meteor's addConnectionStatus method to log danger,
critical and recoveries triggers on user's connection status change.
=> chore(connection status): log status change at the server

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx, bigbluebutton-html5/imports/ui/components/poll/component.jsx
- sets a constant to limit poll question length
- adds poll messages to the list of messages that should be resized to prevent overlap
Closes #12068
=> fix: Prevent long poll question message overlapping

bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/actions-bar/actions-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx, bigbluebutton-html5/imports/ui/components/captions/writer-menu/component.jsx, bigbluebutton-html5/imports/ui/components/note/component.jsx, bigbluebutton-html5/imports/ui/components/note/service.js, bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-notes/component.jsx
This PR closes #12050. 
Added an update after some panel (shared notes and others) is open/close to fix the issue.
Fix some linter errors.
=> Fix layout broken after open+close shared notes

bigbluebutton-html5/imports/api/group-chat-msg/server/methods/chatMessageBeforeJoinCounter.js
The issue was caused bya missing filter byt he meetingId in the meteor server.
Closes #12094
=> Fix messages load stuck

bigbluebutton-html5/imports/ui/components/modal/random-user/component.jsx, bigbluebutton-html5/private/config/settings.yml
This PR makes sure the countdown that appears during the random user picking is optional.
=> Make random user picking coundown (UI + audio) optional

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToPollReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/polls/RespondToTypedPollReqMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala
Sort the number of responses and display the top 7 responses.
If a poll has several responses (especially the user type polls), there is a possibility that the client crashes because of the whiteboard poll result display.
=> Cutoff poll responses

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Polls.scala
- collate all remaining responses to indicate in the display the number of responses.
We display only the top 7 poll responses. But we need to show that there are other responses
not displayed individually.
=>  - lump other responses in the poll and include in the display

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js, bigbluebutton-html5/imports/api/users/server/modifiers/setMobile.js, bigbluebutton-html5/imports/startup/client/base.jsx, bigbluebutton-html5/imports/ui/components/connection-status/service.js, bigbluebutton-html5/imports/ui/components/user-list/service.js
Removes unused code reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
=> refactor: remove unused code

bigbluebutton-html5/imports/api/polls/server/methods/publishTypedVote.js, bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/polling/component.jsx, bigbluebutton-html5/private/config/settings.yml
Add configuration for max length typed answer in poll
=> Add configuration for max length typed answer in poll

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/waiting-users/component.jsx, bigbluebutton-html5/imports/ui/components/waiting-users/component.jsx
Closes #12143 
This PR fixes the problem when open waiting room to accept or deny a gest user.
=> Fix layout broken when close waiting room panel

bigbluebutton-html5/private/static/guest-wait/guest-wait.html
Adds a few missing string to be translated for guest-wait page.
Continuation from #12213 
Thanks to @pedrobmarin for bringing this up in https://github.com/bigbluebutton/bigbluebutton/pull/12213#issuecomment-829621024
Thanks to Johannes and @danimo for translating the newly added strings to German
// Tested this, including the Lobby messages
=> feat(bbb-html5): localize guest-wait.html (part2)

bigbluebutton-html5/private/config/settings.yml
Removed "dev" from 2.3 versioning in settings.yml
Closes #12223 Thanks @cod3r0k
=> chore: Removed "dev" from 2.3 versioning in settings.yml

bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx
Changes "open presentation" button position, so "raise hand" button position stays in the same place when presentation is hidden.
Closes #12242
=> Change open presentation button position

bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx
Add the ability to navigate to specific users from the room lists and move them via the keyboard.
Improvements mentioned in #12078
=> feat(accessibility): Improve keyboard Access For Breakout Room Assignment

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Updates to maintained version of `sanitize-html`
Closes #12288
=> fix(security): Update sanitize-html package

bigbluebutton-html5/imports/startup/server/ClientConnections.js
Replace single quotes with backticks in log message.
=> fix: template syntax in string literal

bigbluebutton-html5/imports/api/captions/server/methods/editCaptions.js, bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js, bigbluebutton-html5/imports/api/polls/server/methods/publishVote.js, bigbluebutton-html5/imports/api/users-settings/server/publishers.js, bigbluebutton-html5/imports/api/video-streams/server/helpers.js, bigbluebutton-html5/imports/api/video-streams/server/modifiers/sharedWebcam.js
This PR adds the `meetingId` to some queries in server to avoid conflicts among meetings.
=> Add filter by meetingId in server queries

bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Updates lint-staged from 8.1.3 to 11.0.0
Closes #
Some security vulnerabilities (this is a development dependency, not a production one)
=> chore: Updated lint-staged from 8.1.3 to 11.0.0

bbb-webhooks/package-lock.json, bbb-webhooks/package.json
\+ lodash@4.17.21
added 208 packages from 892 contributors in 4.512s
fixed 8 of 9 vulnerabilities in 209 scanned packages
1 package update for 1 vulnerability involved breaking changes
\+ redis@3.1.2
\+ mocha@8.3.2
added 77 packages from 48 contributors, removed 3 packages and updated 11 packages in 8.948s
fixed 3 of 3 vulnerabilities in 209 scanned packages
2 package updates for 2 vulnerabilities involved breaking changes
\+ body-parser@1.19.0
\+ js-yaml@3.14.1
\+ nock@10.0.6
\+ supertest@3.4.2
\+ sinon@7.5.0
added 21 packages from 28 contributors, removed 11 packages, updated 29 packages, moved 3 packages and audited 293 packages in 6.064s
=> chore(webhooks): update dependencies

bigbluebutton-html5/imports/ui/components/captions/pad/service.js
This use of variable 'ownerId' always evaluates to true.
=> refactor(closed captions): useless conditional

bigbluebutton-html5/imports/utils/stats.js
Missing from 83c813ac6f803b71d535265b1054a3c7daddf119
=> refactor(connection status): remove superfluous trailing argument

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Re-implements scroll to position using virtualized list. 
Chat component will keep track of visible items and restore scroll position when opening a chat.
Closes #12313
=> fix: chat jumps to top when opened/closed

bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx
This PR fixes the presentaiton uploader not showing new presentations when presenter changes, It happens because theres no logic to update the presentation list in the client of the new presenter.
Closes #12267
=> Fix Presentation uploader missing items

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Implements auto-scroll in chat when a new message is sent/received.
=> fix: handle new message auto-scroll in chat

bigbluebutton-html5/imports/ui/components/user-list/service.js
Adds avatar image to the private chat listing
Closes #12355
=> fix: show avatar in private chat list

bigbluebutton-html5/imports/ui/components/chat/message-form/styles.scss
=> Chat input padding

bigbluebutton-config/bin/bbb-conf
Check that the binary stunclinet exists before running it.
=> Run stunclient if it exists

bigbluebutton-html5/imports/ui/components/user-list/service.js, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/component.jsx, bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx
Fixes an issue where a private chat started by another user would appear in chat list before any message is sent.
Closes #12411
=> fix: do not display private chat before first message is sent

bigbluebutton-html5/.meteor/packages, bigbluebutton-html5/.meteor/versions, bigbluebutton-html5/imports/startup/server/redis.js, bigbluebutton-html5/package-lock.json, bigbluebutton-html5/package.json
Replaces [PowerQueue](https://github.com/CollectionFS/Meteor-power-queue) with [queue](https://www.npmjs.com/package/queue).
Closes #12376
=> fix: replace power-queue dependency

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx
Removes unused imports and variables reported by [lgtm alerts](https://lgtm.com/projects/g/bigbluebutton/bigbluebutton/alerts)
=> refactor: remove unused import and variables

bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addSystemMsg.js, bigbluebutton-html5/imports/api/polls/server/handlers/sendPollChatMsg.js, bigbluebutton-html5/imports/ui/components/chat/service.js, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/poll-list-item/component.jsx, bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/message-chat-item/poll-list-item/styles.scss, bigbluebutton-html5/imports/ui/components/poll/live-result/styles.scss, bigbluebutton-html5/imports/ui/components/poll/service.js, bigbluebutton-html5/imports/ui/components/polling/styles.scss
Pass PollData Object as extra instead of string in SystemChatMessage to able to assemble the result better in the Chat (without having to do a lot of parsing).
Extract PollListItem to a component.
Fix prolems with ":" char in answers.
Respect poll question formatting (lineBreaks/spaces) in other fields of UI
Closes #12375
=> refactor: redo how poll result chat message is done

bigbluebutton-html5/imports/ui/components/app/component.jsx
This fixes an issue with the modals (settings, connection status, keyboard shortcuts,...) not working on new layout manager (#12394).
=> Add modals to new layout manager

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx
Adds the actions bar to the new Layout Manager (WIP)
=> actions bar in new layout manager

bigbluebutton-html5/imports/startup/client/intl.jsx, bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/component.jsx
Reverts bigbluebutton/bigbluebutton#12497
I am hitting issues with it locally and I need to push 2.3.3 out...
=> Revert "fix: different navbar size for locales with large fonts"

bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx, bigbluebutton-html5/private/config/settings.yml
What does this PR do?
Add option to disable the public chat copy/save function to comply with GDPR
Closes Issue(s)
Closes #12472
=> Add field to toggle the download of the public chat message

bigbluebutton-html5/imports/api/external-videos/server/modifiers/startExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/modifiers/stopExternalVideo.js, bigbluebutton-html5/imports/api/external-videos/server/modifiers/updateExternalVideo.js
As discussed in https://github.com/bigbluebutton/bigbluebutton/pull/12504 .
Add missing data check and move the existing ones inside the try-catch
blocks.
=> refactor(external videos): data check

bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss, bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/component.jsx
Shows video talking indicator even if the video isn't ready.
Closes #11902 
Kudos @Arthurk12
=> fix(video): talking indicator

bigbluebutton-web/build.gradle
Added other repos to use as location of dependencies.
Running build.sh was failing because it cannot resolve some dependencies off of https://repo.grails.org/grails/core repo.
Added other repos to use as location of dependencies.
=> fix:  Add new maven repos in bbb-web

bigbluebutton-html5/imports/ui/components/poll/styles.scss, bigbluebutton-html5/imports/ui/components/polling/styles.scss, bigbluebutton-html5/imports/ui/components/tooltip/bbbtip.css
Fixes for the following alerts:
=> fix: css alerts

bigbluebutton-html5/imports/startup/client/intl.jsx
Adding Divehi (Maldivian) as a right-to-left language. Sorting alphabetically the existing list.
Closes #
I received a message on Transifex asking why Divehi is not set as a right-to-left language. ... I did not know it was one. I am setting it to RTL now.
=> Set Divehi as RTL

bigbluebutton-html5/imports/ui/components/app/component.jsx, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/layout/context/context.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/screenshare/component.jsx, bigbluebutton-html5/imports/ui/components/screenshare/container.jsx
Adds screenshare component to new layout manager
=> Screenshare component - new Layout Manager

bigbluebutton-html5/imports/ui/components/whiteboard/annotations/poll/component.jsx
=> fix(poll): missed test for polls with > 5 default answers

bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx, bigbluebutton-html5/imports/ui/components/debug-window/component.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx
Removes unused code in layout manager related files.
=> refactor: remove unused code in new Layout Manager

bigbluebutton-html5/imports/startup/server/metrics.js
Restore mongo metrics generation.
=> Restore mongo metrics feature

bigbluebutton-html5/imports/ui/components/layout/context/context.jsx, bigbluebutton-html5/imports/ui/components/layout/defaultValues.js, bigbluebutton-html5/imports/ui/components/layout/layout-manager/videoFocusLayout.jsx, bigbluebutton-html5/imports/ui/components/sidebar-content/component.jsx
Implements vertical resize for the sidebar in focus on video layout.
=> feat: sidebar vertical resize - focus on video layout

bigbluebutton-html5/imports/ui/components/actions-bar/quick-poll-dropdown/component.jsx, bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/presentation/service.js, bigbluebutton-html5/private/config/settings.yml
Backport of https://github.com/bigbluebutton/bigbluebutton/pull/12620
=> fix(poll): Respect maxCustom property in quick-polls

bigbluebutton-html5/imports/api/users-settings/server/publishers.js, bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx, bigbluebutton-html5/imports/ui/components/components-data/users-context/context.jsx, bigbluebutton-html5/imports/ui/services/auth/index.js
Prevents a crash that happens when many users try to reconnect at the same time (refresh page)
closes #12685
=> fix: reconnection crash

bigbluebutton-html5/imports/api/polls/server/publishers.js
Filter poll data that moderators and viewers had access.
=> fix: Filter poll data for moderator and viewers

bbb-common-web/src/main/java/org/bigbluebutton/api/domain/UserSession.java, bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java
Fixes the null error thrown by Freemarker in get-sessions.ftlx.
=> Freemarker Null Error Fix

bigbluebutton-html5/imports/utils/sdpUtils.js
Complements #12705
Kudos to community users tomoya and baiden10 who first found this.
More info [here](https://groups.google.com/d/msgid/bigbluebutton-dev/77dd274f-3360-4819-ae07-fab8af4e024dn%40googlegroups.com?utm_medium=email&utm_source=footer)
=> fix(audio): mic not working when skipCheck=true

bigbluebutton-html5/imports/api/polls/server/publishers.js, bigbluebutton-html5/imports/ui/components/poll/component.jsx, bigbluebutton-html5/imports/ui/components/poll/container.jsx, bigbluebutton-html5/imports/ui/components/poll/service.js
Filter anonymous poll data that presenter, moderators and viewers had access.
=> Filter anonymous poll data for presenter, moderators and viewers 

bigbluebutton-html5/imports/ui/components/app/component.jsx
Adds missing components and notifications to new Layout Manager.
=> add missing components in new layout manager

bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/private/config/settings.yml
Sets Smart Layout (and new Layout Manager) as the default layout.
=> Set new Layout Manager as default

bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/CreateMeeting.java
Breakout room and record are no longer required parameters for create requests.
=> Modified request parameter requirements

bbb-common-web/src/main/java/org/bigbluebutton/api/model/request/CreateMeeting.java
Made voice bridge an optional parameter for create requests.
=> More changes to required request parameters

bigbluebutton-html5/imports/ui/services/auth/index.js
Fix race condition that caused the client to get stuck with the three dots on join.
=> Fix race condition in auth process

bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Updates the default URLs in the welcome message for bigbluebutton.org.
=> Fix URLS for bigbluebutton.org

bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Changed validation error message to only report a maximum of one error to the client even if there are multiple errors. All errors are still logged.
=> changed validation error message

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/layout/BroadcastLayoutMsgHdlr.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Layouts.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/RunningMeeting.scala, akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/AnalyticsActor.scala, bbb-common-message/src/main/scala/org/bigbluebutton/common2/domain/Meeting2x.scala, bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java, bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java, bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java, bbb-common-web/src/main/java/org/bigbluebutton/api/domain/MeetingLayout.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/IBbbWebApiGWApp.java, bbb-common-web/src/main/java/org/bigbluebutton/api2/domain/UsersProp2.java, bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala, bigbluebutton-config/bin/bbb-conf, bigbluebutton-html5/imports/api/meetings/server/eventHandlers.js, bigbluebutton-html5/imports/api/meetings/server/handlers/broadcastLayout.js, bigbluebutton-html5/imports/api/meetings/server/methods/changeLayout.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js, bigbluebutton-html5/imports/api/meetings/server/modifiers/changeLayout.js, bigbluebutton-web/grails-app/conf/bigbluebutton.properties, bigbluebutton-web/grails-app/conf/spring/resources.xml, bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy
Allow default layout to be configured in `bbb-web` configuration file, and handle layouts events.
Closes #12668
=> Allow default layout config in bbb-web

bigbluebutton-html5/private/config/settings.yml
To allow for more extensive usage/testing by community
More:
This is a follow-up to #12495
=> chore: Enable  blur by default

bigbluebutton-html5/imports/api/audio/client/bridge/kurento.js, bigbluebutton-html5/imports/api/screenshare/client/bridge/kurento.js, bigbluebutton-html5/imports/ui/components/video-provider/component.jsx
Preparing for release of 2.4-alpha2
=> Merge 2.3.8 into develop

akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/ActivityTrackerActor.scala, bbb-activity-report/index.html, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
This PR complements #12542 with some improvements.
- Set default value of `activityReportTracking` to `true`
- Removes all Start/Stop of Talk events to a single value with `totalTime`
- Change format of times in the Dashboard to `HH:mm:ss`
New format of `ActivityReportEvtMsg`:
```json
{
"intId":"edbeca08060154adfa28f36500dc96d3b6099034-1627058636303",
"extId":"random-2894176",
"name":"Meeting Test",
"users":{
"w_9mt9y0zjr9en":{
"intId":"w_9mt9y0zjr9en",
"extId":"w_9mt9y0zjr9en",
"name":"User Adm",
"answers":{
},
"talk":{
"totalTime":164282,
"lastTalkStartedOn":1627059213008
},
"webcams":[
{
"startedOn":1627058680575,
"stoppedOn":0
}],
"totalOfMessages":2,
"totalOfRaiseHands":1,
"totalOfEmojis":0,
"registeredOn":1627058641748,
"leftOn":0
},
"w_acwbcftun3nv":{
"intId":"w_acwbcftun3nv", …
```
=> Enhancements to Activity Report

bigbluebutton-html5/imports/ui/components/captions/pad/component.jsx
Fix a bug when this.recognition is null on Firefox.
Closes #12823
To fix a bug that my PR created...sorry!
=> this.recognition can be null

bigbluebutton-html5/imports/ui/components/video-provider/component.jsx, bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx, bigbluebutton-html5/public/locales/en.json
Remove the camera effect toggle @ video-list before anyone else wastes their time saying it's broken.
The cleanup task mentioned in #12836
=> refactor(virtual-backgrounds): remove camera effect toggle (video-list)

bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/ExternalProcessExecutor.java
ExternalProcessExecutor spawned sub-processes with stderr and
stdout buffers, but did not read from those buffers. Sub-processes
producing output sometimes would fill up these buffers and then hang
until the timeout occurs and the process is killed.
This fixes #12839 (PDF conversion hangs for 10 seconds per page)
by properly discarding command output. The patch also deprecates an
outdated and dangerous API and offers a safer alternative. Splitting
command arguments based on whitespace may result in unwanted behavior
if an argument (e.g. a filename) contains whitespace.
Closes #12839
I did NOT test this in any way, because I do not have a proper development environment available at the moment. Please review carefully.
=> fix(common-web): Sub-processes hang if output buffers fill up

bigbluebutton-html5/imports/ui/components/panel-manager/component.jsx
Fix legacy layout sidebar resize for poll, waiting users and caption panels.
Closes #12631
=> fix: sidebar panel resizing - legacy layout

bigbluebutton-html5/imports/api/group-chat-msg/server/publishers.js
Provides additional constraints for publisher
=> fix: Add meetingId to chatIds selector

bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/IsBooleanValidator.java
Converts boolean values to lowercase before validating them to ensure all cases are validated properly.
=> Converted boolean input values to lowercase before validating them

bigbluebutton-html5/imports/ui/components/app/component.jsx
Fixes the tab order for the different layouts.
Elements were not in the correct order
=> Fix Tab Order In Legacy and Other Layouts

bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/IsBooleanValidator.java, bbb-common-web/src/main/java/org/bigbluebutton/api/model/validator/IsIntegralValidator.java
Null values will now pass validation checks for parameters that are not required.
=> null values are now allowed for parameters that are not required

bigbluebutton-html5/package-lock.json
Adds some package-lock.json changes that were not committed in #12745 
Closes #
These are needed for correctly reconstructing npm dependencies among environments
=> chore: missing package-lock.json changes from #12745

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/component.jsx
Updates the manage user dropdown to the accessible menu dropdown
=> Update Manage Users Dropdown To Menu

bigbluebutton-html5/imports/ui/components/user-list/user-list-content/styles.scss
Adds a visible focus outline to the lists.
For keyboard accessibility to indicate that a list is selected and in focus.
=> Update List Style To Show Focus Outline

bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx
Fix camera resize in RTL languages (mentioned in https://github.com/bigbluebutton/bigbluebutton/pull/12740#issuecomment-890157813).
=> fix: webcam resize - RTL languages

bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx, bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx
Fix media and webcam position for RTL languages in smart and custom layouts.
Closes #12883
=> fix: RTL language - presentation page in portrait orientation breaks the interface

bigbluebutton-html5/imports/ui/components/chat/time-window-list/component.jsx
Remove the recalculation in the cache related to font load, currently we load the fonts before render
Closes #12544
=> Remove workarounds related to fonts load

bigbluebutton-html5/imports/ui/components/app/container.jsx, bigbluebutton-html5/private/config/settings.yml
In this PR you can add custom CSS file in config directly which will work as globally. Still `userdata-bbb_custom_style_url` can be use to override.
Closes #
At present you have to use `userdata-bbb_custom_style_url` to add custom CSS file but this require to custom development of API call. Most of existing BBB solution/plugins like moodle, wordpress, joomla don't have this option. In this PR you can easily add custom CSS file to change html5 client's look without modifying core files. 
Example: https://docs.bigbluebutton.org/admin/customize.html#examples
=> Feat: added option to allow to use customStyleUrl from config

bigbluebutton-html5/imports/api/presentation-pods/server/modifiers/setPresenterInPod.js, bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js
Prevent edge case where the client interface was showing wrong information about the current presenter.
=> Prevent edge case where interface show wrong info about current presenter

bigbluebutton-html5/imports/ui/components/breakout-join-confirmation/component.jsx
with @Tainan404
Adds waiting interval until the breakoutURL is available. 
Closes #
Otherwise we open about:// in some cases
=> fix: Await valid url on breakout before allowing to join; with @Tainan404

akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Layouts.scala, bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx, bigbluebutton-html5/public/locales/en.json, bigbluebutton-web/grails-app/conf/bigbluebutton.properties
Remove legacy option for valid layouts in `bbb-web` and `akka-apps`
Closes #12858
=> Remove legacy option for valid layouts

bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx
Fixes the labels used by the screen reader for the recording button.
=> Fix Aria Labels On Recording Button

bigbluebutton-tests/puppeteer/all.test.js, bigbluebutton-tests/puppeteer/polling.test.js, bigbluebutton-tests/puppeteer/trigger.test.js
Fix test names and reorder "requires" in `all.test.js`
=> test: fix tests name
